### ISSUE TITLE
Site support request - epio.app

### ISSUE THREAD

**Issue by zltkfkrl** [KurtBestor/Hitomi-Downloader#1308]
크롤링하고싶은데..
100% 파일 전부가 다운로드가 안되고
일부분만 다운받아져요.

도움요청드립니다.

https://yinjaixxx.epio.app/article/detail/5d94ebafa63c6400060de430

epio.app 사이트도 지원해주세요..

**Comment by zltkfkrl** [comment]
아맞다 그리고 업뎃이후로 작가명복사가 안되던데...

**Comment by KurtBestor** [comment]
작가명 복사 안 되는 문제 고쳤어요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by inablock** [comment]
It's still not working. I'm trying to download this one: https://girlimg.epio.app/article/detail/5e2c3da9f1929b000771ed77

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by KurtBestor** [comment]
@inablock 
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by inablock** [comment]
Here's what looks like for me.
```
Invalid: [epio] https://girlimg.epio.app / article / detail / 5e2c3da9f1929b000771ed77

version: 2.7h
platform: Windows-10-10.0.18362
order: 2
group: False
gal_num: https://girlimg.epio.app/article/detail/5e2c3da9f1929b000771ed77
dir: 
zip: 
type: epio
artist: None
url: https://girlimg.epio.app/article/detail/5e2c3da9f1929b000771ed77
valid: False
done: True
range: None
range_p: None
single: False
time: 1580059737.24 (Jan 27)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
wait...
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "epio_downloader", line 50, in read_page
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "epio_downloader", line 22, in read
File "epio_downloader", line 59, in get_info
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "epio_downloader", line 50, in read_page
Exception: Timeout


Invalid: fail=True
EOT: https://girlimg.epio.app/article/detail/5e2c3da9f1929b000771ed77
```

**Comment by KurtBestor** [comment]
@inablock Try this version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
