### ISSUE TITLE
제작자님 자꾸 귀찷게 해서 죄송합니다 근데요 자꾸 멈춰요 

### ISSUE THREAD

**Issue by dkfle222** [KurtBestor/Hitomi-Downloader#1504]
usty Judy

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://vimeo.com/345781677
dir: hitomi_downloaded_vimeo
zip: 
type: vimeo
artist: None
url: https://vimeo.com/345781677
valid: False
done: True
range: None
range_p: None
single: True
time: 1577115800.4 (Dec 24)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_vimeo\Busty Judy.mp4

[URLs]
[0001] https://gcs-vimeo.akamaized.net/exp=1577119702~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4156%2F13%2F345781677%2F1389598740.mp4~hmac=8088610c7a3d8a1d3e7aa6c7a26b8177e125522563b5df224d8e252d9e4ec342/vimeo-prod-skyfire-std-us/01/4156/13/345781677/1389598740.mp4?source=1

[Messages]
use just download

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\C:\Users\TG\Desktop\hitomi_downloader_GUI\hitomi_downloaded_vimeo\Busty Judy.mp4
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

valid=False 1
EOT: https://vimeo.com/345781677

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
