### ISSUE TITLE
히요비 다운로드 오류

### ISSUE THREAD

**Issue by ATGOS** [KurtBestor/Hitomi-Downloader#1518]
다른거는 잘되는것처럼 보이는데 이것만 빨간오류뜨네요
직접 사이트 들어가봐도 대충 다 괜찮아보이는데
이유가 궁금합니다
정보: 
Invalid: [hitomi] https://hiyobi.me / reader / 10000103#1-

version: 2.7d
platform: Windows-10-10.0.18362
order: 9
group: False
gal_num: https://hiyobi.me/reader/10000103#1-
dir: 
zip: 
type: hiyobi
artist: None
url: https://hiyobi.me/reader/10000103#1-
valid: False
done: True
range: None
range_p: None
single: False
time: 1577785356.21 (Dec 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x40561FF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1B3399B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hiyobi.me/reader/10000103#1-)
Find_ehen(id:10000103, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x26781F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hiyobi.me/reader/10000103#1-)
Find_ehen(id:10000103, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2870C930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hiyobi.me/reader/10000103#1-)
Find_ehen(id:10000103, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2469B270>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hiyobi.me/reader/10000103#1-)
Find_ehen(id:10000103, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2990E930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hiyobi.me/reader/10000103#1-)
Find_ehen(id:10000103, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2871D0B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hiyobi.me/reader/10000103#1-)
Find_ehen(id:10000103, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 224, in get_gal
Exception: get_gal Invalid server: auto

stop
Invalid: fail=False
stop
EOT: https://hiyobi.me/reader/10000103#1-

**Comment by KurtBestor** [comment]
참고해주세요: #1358
