### ISSUE TITLE
기본데이터 및 히토미 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by thanatos8** [KurtBestor/Hitomi-Downloader#1536]
좋은 프로그램을 만들어주셔서 정말 감사드리고. 새해 복 많이 받으시길 바랍니다.

이번 업데이트 후 검색기에 들어가서 기본데이터를 다운로드 하려고 하면
 
"데이터를 다운로드 하는중에 실패하였습니다"라는 오류가 뜨고
Traceback (most recent call last):
  File "hitomi_searcher", line 214, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 286, in read_html
Exception: proxy for urllib3

라고 뜹니다.

또한 그 전에 다운된 데이터로 검색을 하면 미리보기가 뜨지 않고 이걸 다운로드 하면 다운로드가 한참을 무한로딩 되다가 0p짜리 1kb 파일만 생성하고 끝나 버립니다.
![bug1](https://user-images.githubusercontent.com/59519043/71773650-a73a1e00-2fa3-11ea-81a6-0f6753604ed8.jpg)
![bug2](https://user-images.githubusercontent.com/59519043/71773651-a73a1e00-2fa3-11ea-9d49-6a39da3ab765.jpg)

히토미 다운로드 시도시 모든파일들이 다운로드시 위와같이 되어버립니다.

 다운로드0p 오류의 자세한 정보는

[Tanishi] INMOU l 음모 (1459236)

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: [Tanishi] INMOU l 음모 (1459236)
dir: hitomi_downloaded\[Tanishi] INMOU l 음모 (1459236)
zip: hitomi_downloaded\[Tanishi] INMOU l 음모 (1459236).zip
type: hitomi
artist: tanishi
url: 1459236
valid: True
done: True
range: None
range_p: None
single: False
time: 1578182222.75 (Jan 5)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
갤러리 넘버: 1459236

제목: INMOU l 음모

작가: tanishi

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: tankoubon, female:bbw, female:beauty mark, female:big areolae, female:big ass, female:big breasts, female:dark skin, female:defloration, female:femdom, female:hairy, female:hairy armpits, female:huge breasts, female:lingerie, female:milf, female:pantyhose, female:schoolgirl uniform, female:stockings, female:sweating, female:tall girl, female:tanlines, female:twintails, female:x-ray, male:armpit licking, male:schoolboy uniform, male:shota

언어: Korean

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: ehen
ehen_imgs(ex:False, url:1459236)
Find_ehen(id:1459236, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 542, in get_imgs
File "hitomi_downloader", line 978, in ehen_imgs
File "hitomi_downloader", line 891, in find_ehen
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: ehen
ehen_imgs(ex:True, url:1459236)
Find_ehen(id:1459236, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 542, in get_imgs
File "hitomi_downloader", line 978, in ehen_imgs
File "hitomi_downloader", line 891, in find_ehen
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: ehen
ehen_imgs(ex:False, url:1459236)
Find_ehen(id:1459236, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 542, in get_imgs
File "hitomi_downloader", line 978, in ehen_imgs
File "hitomi_downloader", line 891, in find_ehen
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: ehen
ehen_imgs(ex:True, url:1459236)
Find_ehen(id:1459236, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 542, in get_imgs
File "hitomi_downloader", line 978, in ehen_imgs
File "hitomi_downloader", line 891, in find_ehen
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: ehen
ehen_imgs(ex:False, url:1459236)
Find_ehen(id:1459236, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 542, in get_imgs
File "hitomi_downloader", line 978, in ehen_imgs
File "hitomi_downloader", line 891, in find_ehen
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 532, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 540, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 286, in read_html
Exception: proxy for urllib3

get_imgs server: ehen
ehen_imgs(ex:True, url:1459236)
Find_ehen(id:1459236, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 659, in read
File "hitomi_downloader", line 542, in get_imgs
File "hitomi_downloader", line 978, in ehen_imgs
File "hitomi_downloader", line 891, in find_ehen
File "downloader", line 286, in read_html
Exception: proxy for urllib3

FINAL SERVER: auto
ehen_url: None
imgs: 0

Title :
[Tanishi] INMOU l 음모 (1459236)

stop
EOT: #-*- [Tanishi] INMOU l 음모 (1459236)

입니다.

재설치하면 기본데이터 다운로드 오류는 처음에는 문제가 없으나 종료후 다시 시작하면 다시 생기고 미리보기와 다운로드 오류는 여전히 존재합니다.

**Comment by thanatos8** [comment]
쓰고나서 이것저것 해제해 보다보니 프록시 문제였네요.
프록시를 끄니 정상적으로 작동합니다.
