### ISSUE TITLE
유튜브 동영상이 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by vernika01** [KurtBestor/Hitomi-Downloader#1556]
항상 감사하게 사용하고 있습니다.
어제 밤부터 유튜브 동영상이 다운로드 되지 않아서 문의 드리려 합니다.
특정 동영상만 그런게 아니라 유튜브만 전체적으로 다운이 되질 않네요.
다른 사이트는 문제없이 다운이 됩니다.

Invalid: [youtube] https://www.youtube.com / watch?v=1AEvQAg6TE0&t=178s

version: 2.7e
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=1AEvQAg6TE0&t=178s
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=1AEvQAg6TE0&t=178s
valid: False
done: True
range: None
range_p: None
single: True
time: 1578564762.44 (Jan 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "youtube_downloader", line 138, in read
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "youtube_downloader", line 292, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1AEvQAg6TE0: YouTube said: Unable to extract video data

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=1AEvQAg6TE0&t=178s

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/72182581-2067c400-342f-11ea-8ae7-082cb17dc52a.png)

제 쪽에선 재현할 수 없네요.

[youtube-dl](http://ytdl-org.github.io/youtube-dl/) 로는 다운로드 되나요?

**Comment by vernika01** [comment]
답변 감사드립니다. 

답변 보고나서 youtube-dl 포함해서 pc에 설치해서 사용하는 다른 다운로더 몇개로 시도해봤는데 모두 다운이 되질 않았고 유튜브 동영상 다운로드 사이트에서 다운받기는 다운이 되더군요.
혹시 몰라서 ip 변경후 시도해보니 히토미 다운로더에서도 다운이 잘 됩니다.

신경써주셔서 감사합니다.
