### ISSUE TITLE
마나모아에서 일부 만화들이 다운로드 되지 않는것 같습니다.

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader#1561]
여러 만화를 동시에 시도했는데

몇몇 만화만 여러회차 재시도 해도 다운로드가 되지 않네요

로그남깁니다

Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=2115

version: 2.7e
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115
dir: 
zip: 
type: manamoa
artist: 오쿠 히로야
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115
valid: False
done: True
range: None
range_p: None
single: False
time: 1578756755.59 (Jan 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist][series] title
[seed] 기간트 1화 0
[seed] 기간트 2화 0
[seed] 기간트 3화 0
[seed] 기간트 4화 0
[seed] 기간트 5화 0
[seed] 기간트 6화 0
[seed] 기간트 7화 0
[seed] 기간트 8화 0
[seed] 기간트 9화 0
[seed] 기간트 10화 0
[seed] 기간트 11화 0
[seed] 기간트 12화 0
[seed] 기간트 13화 0
[seed] 기간트 14화 0
[seed] 기간트 15화 0
[seed] 기간트 16화 0
[seed] 기간트 17화 0
[seed] 기간트 18화 0
[seed] 기간트 19화 0
[seed] 기간트 20화 0
[seed] 기간트 21화 0
[seed] 기간트 22화 0
[seed] 기간트 23화 0
[seed] 기간트 24화 0
[seed] 기간트 25화 0
[seed] 기간트 26화 0
[seed] 기간트 27화 0
[seed] 기간트 28화 0
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=12981): Read timed out. (read timeout=<object object at 0x020D8480>)

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "manamoa_downloader", line 142, in read
File "manamoa_downloader", line 246, in get_imgs
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=12981): Read timed out. (read timeout=<object object at 0x020D8480>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115

dirFormat: [artist][series] title
[seed] 기간트 1화 0
[seed] 기간트 2화 0
[seed] 기간트 3화 0
[seed] 기간트 4화 0
[seed] 기간트 5화 0
[seed] 기간트 6화 0
[seed] 기간트 7화 0
[seed] 기간트 8화 0
[seed] 기간트 9화 0
[seed] 기간트 10화 0
[seed] 기간트 11화 0
[seed] 기간트 12화 0
[seed] 기간트 13화 0
[seed] 기간트 14화 0
[seed] 기간트 15화 0
[seed] 기간트 16화 0
[seed] 기간트 17화 0
[seed] 기간트 18화 0
[seed] 기간트 19화 0
[seed] 기간트 20화 0
[seed] 기간트 21화 0
[seed] 기간트 22화 0
[seed] 기간트 23화 0
[seed] 기간트 24화 0
[seed] 기간트 25화 0
[seed] 기간트 26화 0
[seed] 기간트 27화 0
[seed] 기간트 28화 0
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=14558): Read timed out. (read timeout=<object object at 0x020D8480>)

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "manamoa_downloader", line 142, in read
File "manamoa_downloader", line 246, in get_imgs
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=14558): Read timed out. (read timeout=<object object at 0x020D8480>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115

dirFormat: [artist][series] title
[seed] 기간트 1화 0
[seed] 기간트 2화 0
[seed] 기간트 3화 0
[seed] 기간트 4화 0
[seed] 기간트 5화 0
[seed] 기간트 6화 0
[seed] 기간트 7화 0
[seed] 기간트 8화 0
[seed] 기간트 9화 0
[seed] 기간트 10화 0
[seed] 기간트 11화 0
[seed] 기간트 12화 0
[seed] 기간트 13화 0
[seed] 기간트 14화 0
[seed] 기간트 15화 0
[seed] 기간트 16화 0
[seed] 기간트 17화 0
[seed] 기간트 18화 0
[seed] 기간트 19화 0
[seed] 기간트 20화 0
[seed] 기간트 21화 0
[seed] 기간트 22화 0
[seed] 기간트 23화 0
[seed] 기간트 24화 0
[seed] 기간트 25화 0
[seed] 기간트 26화 0
[seed] 기간트 27화 0
[seed] 기간트 28화 0
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=2784): Read timed out. (read timeout=<object object at 0x020D8480>)

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "manamoa_downloader", line 142, in read
File "manamoa_downloader", line 246, in get_imgs
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=2784): Read timed out. (read timeout=<object object at 0x020D8480>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115

dirFormat: [artist][series] title
[seed] 기간트 1화 0
[seed] 기간트 2화 0
[seed] 기간트 3화 0
[seed] 기간트 4화 0
[seed] 기간트 5화 0
[seed] 기간트 6화 0
[seed] 기간트 7화 0
[seed] 기간트 8화 0
[seed] 기간트 9화 0
[seed] 기간트 10화 0
[seed] 기간트 11화 0
[seed] 기간트 12화 0
[seed] 기간트 13화 0
[seed] 기간트 14화 0
[seed] 기간트 15화 0
[seed] 기간트 16화 0
[seed] 기간트 17화 0
[seed] 기간트 18화 0
[seed] 기간트 19화 0
[seed] 기간트 20화 0
[seed] 기간트 21화 0
[seed] 기간트 22화 0
[seed] 기간트 23화 0
[seed] 기간트 24화 0
[seed] 기간트 25화 0
[seed] 기간트 26화 0
[seed] 기간트 27화 0
[seed] 기간트 28화 0
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=6192): Read timed out. (read timeout=<object object at 0x02198480>)

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "manamoa_downloader", line 142, in read
File "manamoa_downloader", line 246, in get_imgs
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=6192): Read timed out. (read timeout=<object object at 0x02198480>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115

dirFormat: [artist][series] title
[seed] 기간트 1화 0
[seed] 기간트 2화 0
[seed] 기간트 3화 0
[seed] 기간트 4화 0
[seed] 기간트 5화 0
[seed] 기간트 6화 0
[seed] 기간트 7화 0
[seed] 기간트 8화 0
[seed] 기간트 9화 0
[seed] 기간트 10화 0
[seed] 기간트 11화 0
[seed] 기간트 12화 0
[seed] 기간트 13화 0
[seed] 기간트 14화 0
[seed] 기간트 15화 0
[seed] 기간트 16화 0
[seed] 기간트 17화 0
[seed] 기간트 18화 0
[seed] 기간트 19화 0
[seed] 기간트 20화 0
[seed] 기간트 21화 0
[seed] 기간트 22화 0
[seed] 기간트 23화 0
[seed] 기간트 24화 0
[seed] 기간트 25화 0
[seed] 기간트 26화 0
[seed] 기간트 27화 0
[seed] 기간트 28화 0
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=8202): Read timed out. (read timeout=<object object at 0x02198480>)

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "manamoa_downloader", line 142, in read
File "manamoa_downloader", line 246, in get_imgs
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=8202): Read timed out. (read timeout=<object object at 0x02198480>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115

dirFormat: [artist][series] title
[seed] 기간트 1화 0
[seed] 기간트 2화 0
[seed] 기간트 3화 0
[seed] 기간트 4화 0
[seed] 기간트 5화 0
[seed] 기간트 6화 0
[seed] 기간트 7화 0
[seed] 기간트 8화 0
[seed] 기간트 9화 0
[seed] 기간트 10화 0
[seed] 기간트 11화 0
[seed] 기간트 12화 0
[seed] 기간트 13화 0
[seed] 기간트 14화 0
[seed] 기간트 15화 0
[seed] 기간트 16화 0
[seed] 기간트 17화 0
[seed] 기간트 18화 0
[seed] 기간트 19화 0
[seed] 기간트 20화 0
[seed] 기간트 21화 0
[seed] 기간트 22화 0
[seed] 기간트 23화 0
[seed] 기간트 24화 0
[seed] 기간트 25화 0
[seed] 기간트 26화 0
[seed] 기간트 27화 0
[seed] 기간트 28화 0
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
[seed] 기간트 29화 1320
fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=9967): Read timed out. (read timeout=<object object at 0x00908480>)

stop
Traceback (most recent call last):
File "utils", line 799, in start
File "utils", line 846, in start_
File "manamoa_downloader", line 142, in read
File "manamoa_downloader", line 246, in get_imgs
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "manamoa_downloader", line 271, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=9967): Read timed out. (read timeout=<object object at 0x00908480>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2115

**Comment by KurtBestor** [comment]
지금도 안 되나요?
