### ISSUE TITLE
마나모아 다운이 막힌거 같습니다.

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader#1566]
Invalid: [manamoa] https://manamoa20.net / bbs / board.php?bo_table=manga&wr_id=2570067

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa20.net/bbs/board.php?bo_table=manga&wr_id=2570067
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa20.net/bbs/board.php?bo_table=manga&wr_id=2570067
valid: False
done: True
range: None
range_p: None
single: True
time: 1578913510.54 (Jan 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 661, in __init__
File "manamoa_downloader", line 96, in init
File "manamoa_downloader", line 62, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
stop
EOT: https://manamoa20.net/bbs/board.php?bo_table=manga&wr_id=2570067

------------------------------------------------------------------
안녕하세요. 어제까지 잘 다운이 됬는데.. 오늘 하니까 안되네요..

주소가 바뀌거나 막은거 같습니다 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by newbkor** [comment]
Invalid: [manamoa] https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=795940

version: 2.7e
platform: Windows-10-10.0.10240
order: 0
group: False
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=795940
dir: 
zip: 
type: manamoa
artist: 토조 치카
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4291
valid: False
done: True
range: None
range_p: None
single: False
time: 1578944286.89 (Jan 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4291
dirFormat: [artist] title
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
[seed] 유녀전기 40화 345740
fuckkk...
Traceback (most recent call last):
File "constants", line 588, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=5088): Read timed out. (read timeout=<object object at 0x02628480>)

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 175, in read
File "manamoa_downloader", line 273, in get_imgs
File "constants", line 615, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 588, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=5088): Read timed out. (read timeout=<object object at 0x02628480>)


Invalid: fail=True
EOT: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=795940

기존 최신업그레이드 버전과 올려주신버전의 오류가 같은것 같습니다.

**Comment by newbkor** [comment]
전체화 다운로드 / 개별화 다운로드 둘다 안되는 상황입니다.

**Comment by lducjswo** [comment]
저도 같은상황인데 다운 실패할때마다 다시하기 계속 하다보면 되더군요
10개받으면 그 중 3~4개정도 실패하는데 다시하기 신공으로 받고있습니다
막은건 아닌거같고 뭐가 문젠지 진짜 모르겠네요

**Comment by hhhssj** [comment]
https://manamoa23.net/ 에서 다운해보세요.  https://manamoa24.net/ 는 사이트에서 뭔가 걸어놓은 것 같아요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cocoman1111** [comment]
테스트 해보니 그냥 읽기만 계속하네요. 
https://manamoa23.net/ 으로 했을땐 다운이 됩니다.
