### ISSUE TITLE
마나모아 만화 중 일부가 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by kimsam0384** [KurtBestor/Hitomi-Downloader#1584]
마나모아23, 24, 25 등을 모두 시험해 보았고 test gui를 다시 깔아 다운로드 해 보았지만 되지 않습니다.

읽는 중... [FLIPFLOPs] 다윈즈 게임 / 다윈즈 게임 50화 (50 / 103)

version: 2.7e
platform: Windows-10-10.0.17134
order: -2
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=126
dir: 
zip: 
type: manamoa
artist: FLIPFLOPs
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=126
valid: True
done: False
range: None
range_p: None
single: False
time: 1579363804.87 (Jan 19)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
[seed] 다윈즈 게임 1화 0
[seed] 다윈즈 게임 2화 0
[seed] 다윈즈 게임 3화 0
[seed] 다윈즈 게임 4화 0
[seed] 다윈즈 게임 5화 0
[seed] 다윈즈 게임 6화 0
[seed] 다윈즈 게임 7화 0
[seed] 다윈즈 게임 8화 0
[seed] 다윈즈 게임 9화 0
[seed] 다윈즈 게임 10화 0
[seed] 다윈즈 게임 11화 0
[seed] 다윈즈 게임 12화 0
[seed] 다윈즈 게임 13화 0
[seed] 다윈즈 게임 14화 0
[seed] 다윈즈 게임 15화 0
[seed] 다윈즈 게임 16화 0
[seed] 다윈즈 게임 17화 0
[seed] 다윈즈 게임 18화 0
[seed] 다윈즈 게임 19화 0
[seed] 다윈즈 게임 20화 0
[seed] 다윈즈 게임 21화 0
[seed] 다윈즈 게임 22화 0
[seed] 다윈즈 게임 23화 0
[seed] 다윈즈 게임 24화 0
[seed] 다윈즈 게임 25화 0
[seed] 다윈즈 게임 26화 0
[seed] 다윈즈 게임 27화 0
[seed] 다윈즈 게임 28화 0
[seed] 다윈즈 게임 29화 0
[seed] 다윈즈 게임 30화 0
[seed] 다윈즈 게임 31화 0
[seed] 다윈즈 게임 32화 0
[seed] 다윈즈 게임 33화 0
[seed] 다윈즈 게임 34화 0
[seed] 다윈즈 게임 35화 0
[seed] 다윈즈 게임 36화 0
[seed] 다윈즈 게임 37화 0
[seed] 다윈즈 게임 38화 0
[seed] 다윈즈 게임 39화 0
[seed] 다윈즈 게임 40화 0
[seed] 다윈즈 게임 41화 0
[seed] 다윈즈 게임 42화 0
[seed] 다윈즈 게임 43화 0
[seed] 다윈즈 게임 44화 0
[seed] 다윈즈 게임 45화 0
[seed] 다윈즈 게임 46화 0
[seed] 다윈즈 게임 47화 0
[seed] 다윈즈 게임 48화 0
[seed] 다윈즈 게임 49화 0

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/72674101-56074f80-3ab6-11ea-8794-592af3045686.png)

제 쪽에선 잘 되네요.
모두 완료되어서 `done: False` 가 `done: True` 가 된 후 작업 정보 보여주세요.

**Comment by kimsam0384** [comment]
Invalid: [manamoa] https://manamoa23.net / bbs / page.php?hid=manga_detail&manga_id=126

version: 2.7e
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://manamoa23.net/bbs/page.php?hid=manga_detail&manga_id=126
dir: 
zip: 
type: manamoa
artist: FLIPFLOPs
url: https://manamoa23.net/bbs/page.php?hid=manga_detail&manga_id=126
valid: False
done: True
range: None
range_p: None
single: False
time: 1579701792.62 (Jan 22)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
[seed] 다윈즈 게임 1화 0
[seed] 다윈즈 게임 2화 0
[seed] 다윈즈 게임 3화 0
[seed] 다윈즈 게임 4화 0
[seed] 다윈즈 게임 5화 0
[seed] 다윈즈 게임 6화 0
[seed] 다윈즈 게임 7화 0
[seed] 다윈즈 게임 8화 0
[seed] 다윈즈 게임 9화 0
[seed] 다윈즈 게임 10화 0
[seed] 다윈즈 게임 11화 0
[seed] 다윈즈 게임 12화 0
[seed] 다윈즈 게임 13화 0
[seed] 다윈즈 게임 14화 0
[seed] 다윈즈 게임 15화 0
[seed] 다윈즈 게임 16화 0
[seed] 다윈즈 게임 17화 0
[seed] 다윈즈 게임 18화 0
[seed] 다윈즈 게임 19화 0
[seed] 다윈즈 게임 20화 0
[seed] 다윈즈 게임 21화 0
[seed] 다윈즈 게임 22화 0
[seed] 다윈즈 게임 23화 0
[seed] 다윈즈 게임 24화 0
[seed] 다윈즈 게임 25화 0
[seed] 다윈즈 게임 26화 0
[seed] 다윈즈 게임 27화 0
[seed] 다윈즈 게임 28화 0
[seed] 다윈즈 게임 29화 0
[seed] 다윈즈 게임 30화 0
[seed] 다윈즈 게임 31화 0
[seed] 다윈즈 게임 32화 0
[seed] 다윈즈 게임 33화 0
[seed] 다윈즈 게임 34화 0
[seed] 다윈즈 게임 35화 0
[seed] 다윈즈 게임 36화 0
[seed] 다윈즈 게임 37화 0
[seed] 다윈즈 게임 38화 0
[seed] 다윈즈 게임 39화 0
[seed] 다윈즈 게임 40화 0
[seed] 다윈즈 게임 41화 0
[seed] 다윈즈 게임 42화 0
[seed] 다윈즈 게임 43화 0
[seed] 다윈즈 게임 44화 0
[seed] 다윈즈 게임 45화 0
[seed] 다윈즈 게임 46화 0
[seed] 다윈즈 게임 47화 0
[seed] 다윈즈 게임 48화 0
[seed] 다윈즈 게임 49화 0
[seed] 다윈즈 게임 50화 0
[seed] 다윈즈 게임 51화 0
[seed] 다윈즈 게임 52화 0
[seed] 다윈즈 게임 53화 0
[seed] 다윈즈 게임 54화 0
[seed] 다윈즈 게임 55화 0
[seed] 다윈즈 게임 56화 0
[seed] 다윈즈 게임 57화 0
[seed] 다윈즈 게임 58화 0
[seed] 다윈즈 게임 59-1화 0
[seed] 다윈즈 게임 59-2화 0
[seed] 다윈즈 게임 60화 0
[seed] 다윈즈 게임 60-2화 0
[seed] 다윈즈 게임 61화 0
[seed] 다윈즈 게임 61-2화 0
[seed] 다윈즈 게임 62-1화 0
[seed] 다윈즈 게임 62-2화 0
[seed] 다윈즈 게임 63-1화 0
[seed] 다윈즈 게임 63-2화 0
[seed] 다윈즈 게임 64-1화 0
[seed] 다윈즈 게임 64-2화 0
[seed] 다윈즈 게임 65-1화 0
[seed] 다윈즈 게임 65-2화 0
[seed] 다윈즈 게임 66-1화 0
[seed] 다윈즈 게임 66-2화 0
[seed] 다윈즈 게임 67화 0
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
[seed] 다윈즈 게임 68화 72700
fuckkk...
Traceback (most recent call last):
File "constants", line 588, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 30, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=7496): Read timed out. (read timeout=<object object at 0x02658480>)

stop
Traceback (most recent call last):
File "utils", line 811, in start
File "utils", line 858, in start_
File "manamoa_downloader", line 175, in read
File "manamoa_downloader", line 273, in get_imgs
File "constants", line 615, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 588, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 30, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=7496): Read timed out. (read timeout=<object object at 0x02658480>)


Invalid: fail=True
EOT: https://manamoa23.net/bbs/page.php?hid=manga_detail&manga_id=126

**Comment by kimsam0384** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
2020-1-22 일짜 실험결과 안되네요..... 컴퓨터문제인가요?

**Comment by KurtBestor** [comment]
도메인이 바뀌었네요. [이 링크](https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=126)로 시도해주세요.

**Comment by kimsam0384** [comment]
Invalid: [manamoa] https://manamoa26.net / bbs / page.php?hid=manga_detail&manga_id=1050

version: 2.7h
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=1050
dir: 
zip: 
type: manamoa
artist: 타카가미 유리코
url: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=1050
valid: False
done: True
range: None
range_p: None
single: False
time: 1579961717.89 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 1화 0
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 2화 0
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 3화 0
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4화 0
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4-2화 391840
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4-2화 391840
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4-2화 391840
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4-2화 391840
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4-2화 391840
wait... 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 4-2화
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 5화 0
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 6화 0
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화 335400
wait... 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 7화
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
[seed] 이세계에서 폭신폭신쓰담쓰담 하기 위해서 노력합니다 8화 375980
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 30, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=10032): Read timed out. (read timeout=<object object at 0x02868480>)

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 175, in read
File "manamoa_downloader", line 273, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 30, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=10032): Read timed out. (read timeout=<object object at 0x02868480>)


Invalid: fail=True
EOT: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=1050



Invalid: [manamoa] https://manamoa26.net / bbs / page.php?hid=manga_detail&manga_id=9834

version: 2.7h
platform: Windows-10-10.0.17134
order: 1
group: False
gal_num: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=9834
dir: 
zip: 
type: manamoa
artist: 쿠로스 에마
url: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=9834
valid: False
done: True
range: None
range_p: None
single: False
time: 1579961696.56 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
[seed] 천검의 마술사라 불린 검사 1화 0
[seed] 천검의 마술사라 불린 검사 1-2화 0
[seed] 천검의 마술사라 불린 검사 2화 0
[seed] 천검의 마술사라 불린 검사 2-2화 10650
wait... 천검의 마술사라 불린 검사 2-2화
[seed] 천검의 마술사라 불린 검사 3화 336310
wait... 천검의 마술사라 불린 검사 3화
[seed] 천검의 마술사라 불린 검사 4화 351110
[seed] 천검의 마술사라 불린 검사 4화 351110
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
wait... 천검의 마술사라 불린 검사 4화
[seed] 천검의 마술사라 불린 검사 4화 351110
[seed] 천검의 마술사라 불린 검사 4화 351110
[seed] 천검의 마술사라 불린 검사 4화 351110
[seed] 천검의 마술사라 불린 검사 4화 351110
[seed] 천검의 마술사라 불린 검사 4화 351110
[seed] 천검의 마술사라 불린 검사 4화 351110
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 30, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=7171): Read timed out. (read timeout=<object object at 0x02868480>)

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 175, in read
File "manamoa_downloader", line 273, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 30, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=7171): Read timed out. (read timeout=<object object at 0x02868480>)


Invalid: fail=True
EOT: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=9834

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/73123200-c9d2bc00-3fd0-11ea-9d3c-a6af88cff9ac.png)

재현할 수 없네요. 혹시 인터넷 속도가 느린가요?
