### ISSUE TITLE
뉴토끼가 또 다운이 안되네요.

### ISSUE THREAD

**Issue by kamogun** [KurtBestor/Hitomi-Downloader#1603]
Invalid: [newtoki] https://newtoki43.net / comic / 91933

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://newtoki43.net/comic/91933
dir: 
zip: 
type: newtoki
artist: None
url: https://newtoki43.net/comic/91933
valid: False
done: True
range: None
range_p: None
single: False
time: 1579863506.16 (Jan 24)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Failed to get soup
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "dynamic_module_0", line 69, in read
File "dynamic_module_0", line 50, in soup
File "dynamic_module_0", line 110, in get_soup
Exception: Failed to get soup

Invalid: fail=True
EOT: https://newtoki43.net/comic/91933

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by kamogun** [comment]
지금도

Invalid: [newtoki] https://newtoki43.net / comic / 91933

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://newtoki43.net/comic/91933
dir: 
zip: 
type: newtoki
artist: None
url: https://newtoki43.net/comic/91933
valid: False
done: True
range: None
range_p: None
single: False
time: 1580207087.83 (Jan 28)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "dynamic_module_0", line 172, in get_imgs_page
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "dynamic_module_0", line 75, in read
File "dynamic_module_0", line 150, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "dynamic_module_0", line 172, in get_imgs_page
AttributeError: 'NoneType' object has no attribute 'findAll'


Invalid: fail=True
EOT: https://newtoki43.net/comic/91933


이렇게 나오네요.ㅠㅠ

**Comment by kamogun** [comment]
귀하는 1시간동안 접근 불가합니다. (2020-01-28 20:25:08 이후 접근 가능)

뉴토끼에서 크롤링 하면...막아 버리네요.ㅠㅠ

**Comment by kamogun** [comment]
귀하는 2400시간동안 접근 불가합니다. (2020-05-07 19:25:08 이후 접근 가능)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/74473032-41b44800-4ee6-11ea-81b1-1fefbcdced1a.png)


고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

IP가 차단되었으면 프록시 / VPN 등을 써서 IP를 바꿔주세요.
