### ISSUE TITLE
일부 유튜브 주소 다운 불가

### ISSUE THREAD

**Issue by superrogin** [KurtBestor/Hitomi-Downloader#1605]
https://www.youtube.com/playlist?list=PLwoYZIDfckTp_nrJBEbGbOvWAFNq2OWdj

해당 유튜브 목록을 다운 받으려고 시도 중 다음과 같은 10개의 영상은 다운이 안되고 invalid 에러가 뜨는 것을 확인했습니다.

https://www.youtube.com/watch?v=tqLiRx83LBw
https://www.youtube.com/watch?v=t1_beIo3QW0
https://www.youtube.com/watch?v=UI6qmBaQgUc
https://www.youtube.com/watch?v=a_77oKTzOy4
https://www.youtube.com/watch?v=mJn08phKNZE
https://www.youtube.com/watch?v=kgIz8ysA_UE
https://www.youtube.com/watch?v=AMQxpmF9lAs
https://www.youtube.com/watch?v=h8vXIBZWM6s
https://www.youtube.com/watch?v=A09Z9cEeYI8
https://www.youtube.com/watch?v=o55eTHIz1Xs

해당 주소를 직접 입력하고 받으려 시도해도 실패합니다.

다음은 가장 마지막 주소에 대한 작업정보입니다.

Invalid: [youtube] https://www.youtube.com / watch?v=o55eTHIz1Xs

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=o55eTHIz1Xs
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=o55eTHIz1Xs
valid: False
done: True
range: None
range_p: None
single: True
time: 1579913847.67 (Jan 25)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "youtube_downloader", line 138, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=o55eTHIz1Xs

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1604
