### ISSUE TITLE
pornhub 페이지 지정 다운로드 에러

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1607]
안녕하세요 선생님.
페이지 다운로드를 시도했지만 작동되지 않아서 이슈 올려둡니다!

예시 채널 : www.pornhub.com/channels/ddfnetwork
입력한 페이지 다운로드 숫자 : 16 ~ 30

입력한 정보는 위와 같습니다.
(뒤에서부터 15페이지 분량을 받으려고 -15 이렇게 입력도 해보았지만 되지 않았습니다ㅠ)

오류메세지 정보
:
Invalid: [pornhub] www.pornhub.com / channels / ddfnetwork

version: 2.7h
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: www.pornhub.com/channels/ddfnetwork
dir: 
zip: 
type: pornhub
artist: None
url: www.pornhub.com/channels/ddfnetwork
valid: False
done: True
range: 16 ~ 30
range_p: None
single: True
time: 1579956862.56 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
videos
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "pornhub_downloader", line 401, in get_videos
File "downloader", line 268, in read_html
File "requests\sessions", line 525, in get
File "downloader", line 85, in session_request
File "requests\sessions", line 498, in request
File "requests\sessions", line 441, in prepare_request
File "requests\models", line 309, in prepare
File "requests\models", line 383, in prepare_url
MissingSchema: Invalid URL 'www.pornhub.com/channels/ddfnetwork': No schema supplied. Perhaps you meant http://www.pornhub.com/channels/ddfnetwork?

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "pornhub_downloader", line 130, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "pornhub_downloader", line 401, in get_videos
File "downloader", line 268, in read_html
File "requests\sessions", line 525, in get
File "downloader", line 85, in session_request
File "requests\sessions", line 498, in request
File "requests\sessions", line 441, in prepare_request
File "requests\models", line 309, in prepare
File "requests\models", line 383, in prepare_url
MissingSchema: Invalid URL 'www.pornhub.com/channels/ddfnetwork': No schema supplied. Perhaps you meant http://www.pornhub.com/channels/ddfnetwork?

Invalid: fail=True
EOT: www.pornhub.com/channels/ddfnetwork

**Comment by KurtBestor** [comment]
https://www.pornhub.com/channels/ddfnetwork 와 같이 앞에 `http://` 나 `https://` 를 붙이세요.

**Comment by tdi2020** [comment]
앞에 붙이니까 잘 작동했습니다! TㅇT>
