### ISSUE TITLE
페이스북 로그인 필요

### ISSUE THREAD

**Issue by newbkor** [KurtBestor/Hitomi-Downloader#1617]
Invalid: [facebook] https://www.facebook.com / yukiao.jp

version: 2.7h
platform: Windows-10-10.0.10240
order: 1
group: False
gal_num: https://www.facebook.com/yukiao.jp
dir: 
zip: 
type: facebook
artist: None
url: https://www.facebook.com/yukiao.jp
valid: False
done: True
range: None
range_p: None
single: False
time: 1580215634.69 (Jan 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Login Required
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "facebook_downloader3", line 102, in read
File "facebook_downloader3", line 134, in get_imgs
Exception: Login Required

Invalid: fail=True
EOT: https://www.facebook.com/yukiao.jp

No photo div
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "facebook_downloader3", line 102, in read
File "facebook_downloader3", line 140, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/yukiao.jp

Login Required
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "facebook_downloader3", line 102, in read
File "facebook_downloader3", line 134, in get_imgs
Exception: Login Required

Invalid: fail=True
EOT: https://www.facebook.com/yukiao.jp

이경우에는 어떻게 해야하나요 ?

**Comment by KurtBestor** [comment]
페이스북 로그인은 현재 지원하지 않아요.
