### ISSUE TITLE
현재 트위터 다운로드가 안되는 것 같습니다

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader#1626]
오류 정보 첨부합니다.
보니깐 다른 트위터 사이트도 현재 invalid 메시지가 뜨는데 제가 놓친게 있을까요?

Invalid: [twitter] https://twitter.com / Grimphantom_Inc

version: 2.7h
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://twitter.com/Grimphantom_Inc
dir: 
zip: 
type: twitter
artist: None
url: https://twitter.com/Grimphantom_Inc
valid: False
done: True
range: None
range_p: None
single: False
time: 1580350555.64 (Jan 30)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "twitter_downloader", line 60, in init
File "twitter_downloader", line 67, in id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 228, in get_artist_and_id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 230, in get_artist_and_id
File "twitter_downloader", line 235, in get_artist
IndexError: list index out of range

Invalid: fail=True
stop
EOT: https://twitter.com/Grimphantom_Inc

stop
Traceback (most recent call last):
File "utils", line 669, in __init__
File "twitter_downloader", line 67, in id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 228, in get_artist_and_id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 230, in get_artist_and_id
File "twitter_downloader", line 235, in get_artist
IndexError: list index out of range

Invalid: fail=True
stop
EOT: https://twitter.com/Grimphantom_Inc

stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "twitter_downloader", line 60, in init
File "twitter_downloader", line 67, in id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 228, in get_artist_and_id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 230, in get_artist_and_id
File "twitter_downloader", line 235, in get_artist
IndexError: list index out of range

Invalid: fail=True
stop
EOT: https://twitter.com/Grimphantom_Inc

**Comment by kenasis428** [comment]
저도 다운 안됨 .. 트위터 방식 바꾼듯 ..?

**Comment by iamkkh0503** [comment]
저도 안되는군요 트위터에서 방식을 바꾼게 아닐까요?

**Comment by systembest** [comment]
저도 안되네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

확인 결과 잘 돌아갑니다! 감사합니다.

**Comment by Lovesky0319** [comment]
테스트버전은  msvcr90.dll 없다고 오류가 떠서 해당파일설치해도 실행이 안되고있습니다. 기존 버전은 여전히 작동이 잘되고 있네요..

**Comment by KurtBestor** [comment]
@Lovesky0319 어떤 OS 쓰시나요?

**Comment by Lovesky0319** [comment]
@KurtBestor 윈도우10 사용중입니다.

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by Lovesky0319** [comment]
> 어떤 백신 쓰시나요?

v3 사용중입니다.

**Comment by KurtBestor** [comment]
백신 예외 목록에 추가해서 실행해보세요.

**Comment by Lovesky0319** [comment]
> 백신 예외 목록에 추가해서 실행해보세요.

이 똥멍청이 구제해주셔서 감사합니다. ㅠㅠ 잘되네요

**Comment by pironi88** [comment]
알약백신/Win10 64bit 쓰는데 백신예외목록추가 어떻게 해요?

**Comment by KurtBestor** [comment]
알약 안 써서 모르겠네요.

**Comment by BatmanPerbert** [comment]
> Please test: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

It Doesn't work to me, I can't download from twitter... And well what can I do?
I'm new here so I really don't know anything about scripts or codes, Sorry
