### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by wankio** [KurtBestor/Hitomi-Downloader#1632]
```
[Messages]
stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "twitter_downloader", line 60, in init
File "twitter_downloader", line 67, in id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 228, in get_artist_and_id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 230, in get_artist_and_id
File "twitter_downloader", line 235, in get_artist
IndexError: list index out of range



Invalid: fail=True
stop
EOT: https://twitter.com/officialrinnier

```

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1626
