### ISSUE TITLE
새버전으로 다운로드 해봤지만 마나모아가 2월 5일 이전 만화들은 다운되고 2월 6일 이후는

### ISSUE THREAD

**Issue by hhhssj** [KurtBestor/Hitomi-Downloader#1652]
늘 수고해주셔서 너무 감사드립니다.

새버전으로 다운로드 해봤지만 마나모아가 2월 5일 이전 만화들은 다운되고 2월 6일 이후 만화는 다운시도해보니 만화가 다운되지 않습니다.  
2월 5일 이전 만화 3개 다운하고 2월 6일 만화 다운하려니까 잘안되네요. 이게 날짜 영향인 것도 같지만 연속적으로 다운하는 것을 막은 것 같기도 합니다.

그냥 하루에 조금씩 다운받아야 되는 것인지 궁금합니다. 

셔틀 아이즈

version: 2.7h
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://manamoa27.net/bbs/page.php?hid=manga_detail&manga_id=12927
dir: hitomi_downloaded_manamoa\셔틀 아이즈
zip: 
type: manamoa
artist: 하마하라 렌
url: https://manamoa27.net/bbs/page.php?hid=manga_detail&manga_id=12927
valid: True
done: False
range: None
range_p: [6, 7]
single: False
time: 1581015260.19 (Feb 7)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0000.jpeg
[0002] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0001.jpg
[0003] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0002.jpeg
[0004] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0003.jpg
[0005] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0004.jpeg
[0006] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0005.jpeg
[0007] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0006.jpeg
[0008] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0007.jpeg
[0009] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0008.jpeg
[0010] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0009.jpeg
[0011] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0010.jpeg
[0012] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0011.jpeg
[0013] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0012.jpeg
[0014] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0013.jpeg
[0015] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0014.jpeg
[0016] hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0015.jpeg
[0017] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0018] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0019] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0020] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0021] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0022] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0023] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0024] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0025] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0026] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0027] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0028] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0029] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0030] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0031] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0032] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0033] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0034] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0035] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0036] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0037] hitomi_downloaded_manamoa\셔틀 아이즈\lazy
[0038] hitomi_downloaded_manamoa\셔틀 아이즈\lazy

[URLs]
[0001] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/9a5a83bc3e62016e4d5e2b241a83b31d.jpeg?quick
[0002] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/d591712e5a98e3adcddfb6a3c8ebdff7.jpg?quick
[0003] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/f2066b3aceb925a550b293454ddda010.jpeg?quick
[0004] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/01b3071f807febeeb29104ec9b750e81.jpg?quick
[0005] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/914b4a04b70b3edf0f4aec5197af3fbe.jpeg?quick
[0006] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/39a8759640e0ad5668ab3ef0e0433a9c.jpeg?quick
[0007] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/7e6d4ee6e778c93a47997f625a8820ac.jpeg?quick
[0008] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/a8f76c881e115a701c996630ce41d03d.jpeg?quick
[0009] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/3130089c68bab94adeb4b2574d88a7a4.jpeg?quick
[0010] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/facd2cd08326b7eaf97aa17ff374a124.jpeg?quick
[0011] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/0fcf9dc697ec3a7dca806d4e6c52e021.jpeg?quick
[0012] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/79b51d35d08885eefa66e87e03d434f3.jpeg?quick
[0013] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/f7054f3354b7ff153cafabf7486eac5d.jpeg?quick
[0014] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/759806df66310b4e40160b842c56851c.jpeg?quick
[0015] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/7dd3776b3781841e2040f075e9b446af.jpeg?quick
[0016] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654) ---> https://cdntigermask.xyz//upload/c3f78896a989863028e507349f583a6e.jpeg?quick
[0017] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654)
[0018] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654)
[0019] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707654)
[0020] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0021] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0022] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0023] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0024] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0025] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0026] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0027] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0028] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0029] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0030] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0031] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0032] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0033] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0034] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0035] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0036] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0037] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)
[0038] LazyUrl(https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2707656)

[Messages]
dirFormat: title
셔틀 아이즈 7화 chapter:2707654 seed:0 domains:51
셔틀 아이즈 8화 chapter:2707656 seed:0 domains:51

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0011.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/79b51d35d08885eefa66e87e03d434f3.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBC5C70>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0003.jpg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/01b3071f807febeeb29104ec9b750e81.jpg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBDC1D0>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0012.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/f7054f3354b7ff153cafabf7486eac5d.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBC52B0>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0014.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/7dd3776b3781841e2040f075e9b446af.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBB52F0>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0007.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/a8f76c881e115a701c996630ce41d03d.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1C2929B0>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0000.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/9a5a83bc3e62016e4d5e2b241a83b31d.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBBE710>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0010.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/0fcf9dc697ec3a7dca806d4e6c52e021.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBDCB10>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0009.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/facd2cd08326b7eaf97aa17ff374a124.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EBDCA30>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0013.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/759806df66310b4e40160b842c56851c.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1C292070>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0004.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/914b4a04b70b3edf0f4aec5197af3fbe.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1C292150>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0005.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/39a8759640e0ad5668ab3ef0e0433a9c.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1C292650>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0008.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/3130089c68bab94adeb4b2574d88a7a4.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EB6EEF0>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0001.jpg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/d591712e5a98e3adcddfb6a3c8ebdff7.jpg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1AC3AC10>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0002.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/f2066b3aceb925a550b293454ddda010.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EB6EA10>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0015.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/c3f78896a989863028e507349f583a6e.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1EB6ED10>: Failed to establish a new connection: [Errno 10061] 

Fail : \\?\E:\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\셔틀 아이즈\셔틀 아이즈 7화\0006.jpeg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://cdntigermask.xyz//upload/7e6d4ee6e778c93a47997f625a8820ac.jpeg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F792530>: Failed to establish a new connection: [Errno 10061] 

use alternative url: https://cdntigermask.xyz//upload/79b51d35d08885eefa66e87e03d434f3.jpeg?quick --> https://s3.cdntigermask.xyz//upload/79b51d35d08885eefa66e87e03d434f3.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/01b3071f807febeeb29104ec9b750e81.jpg?quick --> https://s3.cdntigermask.xyz//upload/01b3071f807febeeb29104ec9b750e81.jpg?quick
use alternative url: https://cdntigermask.xyz//upload/f7054f3354b7ff153cafabf7486eac5d.jpeg?quick --> https://s3.cdntigermask.xyz//upload/f7054f3354b7ff153cafabf7486eac5d.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/7dd3776b3781841e2040f075e9b446af.jpeg?quick --> https://s3.cdntigermask.xyz//upload/7dd3776b3781841e2040f075e9b446af.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/a8f76c881e115a701c996630ce41d03d.jpeg?quick --> https://s3.cdntigermask.xyz//upload/a8f76c881e115a701c996630ce41d03d.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/9a5a83bc3e62016e4d5e2b241a83b31d.jpeg?quick --> https://s3.cdntigermask.xyz//upload/9a5a83bc3e62016e4d5e2b241a83b31d.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/0fcf9dc697ec3a7dca806d4e6c52e021.jpeg?quick --> https://s3.cdntigermask.xyz//upload/0fcf9dc697ec3a7dca806d4e6c52e021.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/facd2cd08326b7eaf97aa17ff374a124.jpeg?quick --> https://s3.cdntigermask.xyz//upload/facd2cd08326b7eaf97aa17ff374a124.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/759806df66310b4e40160b842c56851c.jpeg?quick --> https://s3.cdntigermask.xyz//upload/759806df66310b4e40160b842c56851c.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/914b4a04b70b3edf0f4aec5197af3fbe.jpeg?quick --> https://s3.cdntigermask.xyz//upload/914b4a04b70b3edf0f4aec5197af3fbe.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/39a8759640e0ad5668ab3ef0e0433a9c.jpeg?quick --> https://s3.cdntigermask.xyz//upload/39a8759640e0ad5668ab3ef0e0433a9c.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/3130089c68bab94adeb4b2574d88a7a4.jpeg?quick --> https://s3.cdntigermask.xyz//upload/3130089c68bab94adeb4b2574d88a7a4.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/d591712e5a98e3adcddfb6a3c8ebdff7.jpg?quick --> https://s3.cdntigermask.xyz//upload/d591712e5a98e3adcddfb6a3c8ebdff7.jpg?quick
use alternative url: https://cdntigermask.xyz//upload/f2066b3aceb925a550b293454ddda010.jpeg?quick --> https://s3.cdntigermask.xyz//upload/f2066b3aceb925a550b293454ddda010.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/c3f78896a989863028e507349f583a6e.jpeg?quick --> https://s3.cdntigermask.xyz//upload/c3f78896a989863028e507349f583a6e.jpeg?quick
use alternative url: https://cdntigermask.xyz//upload/7e6d4ee6e778c93a47997f625a8820ac.jpeg?quick --> https://s3.cdntigermask.xyz//upload/7e6d4ee6e778c93a47997f625a8820ac.jpeg?quick

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
