### ISSUE TITLE
테스트 버젼을 사용해 봤는데 안받아지는 파일이 있어서 전해드립니다.

### ISSUE THREAD

**Issue by cainar90** [KurtBestor/Hitomi-Downloader#1653]
테스트 버젼으로 다운을 해봤습니다.
새로 올라온 만화 중 몇몇을 받아 보았는데 문제가 생기지 않았습니다.
그런데 오래된 만화 중에서 다운이 안되는 것이 발견되어서 전해드립니다.
(만화 전편이 다 오래되었으나, 특정 몇몇 편만 다운이 안되고 다른 화는 잘 됩니다.)
(다운이 안되는 화는 구버젼으로 다운을 받았더니 잘 받아졌습니다.)
(에러 정보를 다 올려고 했는데 안올라가서 부분만 올렸습니다. 방법을 모르겠습니다.)

[미호시 메가네] 연애폭군

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648
dir: hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군
zip: 
type: manamoa
artist: 미호시 메가네
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4412
valid: False
done: True
range: None
range_p: None
single: False
time: 1581021958.01 (Feb 7)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0000.jpg
[0002] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0001.jpg
[0003] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0002.jpg
[0004] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0003.jpg
[0005] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0004.jpg
[0006] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0005.jpg
[0007] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0006.jpg
[0008] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0007.jpg
[0009] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0008.jpg
[0010] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0009.jpg
[0011] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0010.jpg
[0012] hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0011.jpg

[URLs]
[0001] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://1.bp.blogspot.com/-uaZbMvuL9FE/WRittIetL0I/AAAAAAAPapY/hg3gyR22agQPkxR5fQMqAsHt5Sp_mUKoQCLcB/s1600/000.jpg?quick
[0002] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://1.bp.blogspot.com/-4S6PCJlpe1M/WRittUekurI/AAAAAAAPapU/zeF9WmMM16ceE7CU7v50RtEaMdTXhdbuQCLcB/s1600/001.jpg?quick
[0003] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://4.bp.blogspot.com/-FsDGIQB2gEc/WRittabMyRI/AAAAAAAPapQ/f07STsTr7hA1yqnqBDPgk5kT71TTnFBawCLcB/s1600/002.jpg?quick
[0004] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://2.bp.blogspot.com/-riJpYh_BUgs/WRitt__KH3I/AAAAAAAPapo/-0CODxZNNl0_6VedMuW5he4edx37byWFgCLcB/s1600/003.jpg?quick
[0005] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://2.bp.blogspot.com/--6bOX-BfYCo/WRitt8R1C3I/AAAAAAAPaps/Dp_NXwxI_ZsCQq-5n9eyUBvgcoU9HNEwACLcB/s1600/004.jpg?quick
[0006] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://2.bp.blogspot.com/-DpgbLIctXeY/WRituD1XOQI/AAAAAAAPapw/arJFEU9bZH0IILLNiEyMwvagiU43oHSBwCLcB/s1600/005.jpg?quick
[0007] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://3.bp.blogspot.com/-3haDPaRHRgg/WRitu76BUjI/AAAAAAAPaqY/SyoVQG9cbKQBvcQ_jxddvrwNWCkfnz7oACLcB/s1600/006.jpg?quick
[0008] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://4.bp.blogspot.com/-TnhU1n93ShQ/WRitu-1UyNI/AAAAAAAPaqI/ImrxGYlR-ww6VL5LQqTbwmlCgkJ7WlcCwCLcB/s1600/007.jpg?quick
[0009] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://3.bp.blogspot.com/-J2_H8hzB3Ls/WRitu0U4e9I/AAAAAAAPaqQ/3ce-kS0ShVwjxx0oe1I-B_9X9J96A4sLgCLcB/s1600/008.jpg?quick
[0010] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://3.bp.blogspot.com/-lCqqbNLgvlc/WRitvrSx1qI/AAAAAAAPaqk/wjW30ABcagYwc5_UGnROCKzswrAnmqTKACLcB/s1600/009.jpg?quick
[0011] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://2.bp.blogspot.com/-ghYb8RtJPok/WRitvrq6h3I/AAAAAAAPaqs/SPPRTxCZ_g4nXKApf0YFs7bcNwhsXwtkQCLcB/s1600/010.jpg?quick
[0012] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=66648) ---> https://2.bp.blogspot.com/-6LH6eFBP3yA/WRitvwKOxSI/AAAAAAAPaqw/O1Qv6cWxW6MUJYuT0OHj0ZSiZR1q8snYwCLcB/s1600/011.jpg?quick

[Messages]
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4412
dirFormat: [artist] title
연애폭군 특별편 chapter:66648 seed:0 domains:51

Fail_404 : \\?\C:\Users\caina\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0001.jpg
Traceback (most recent call last):
File "downloader", line 748, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

-----

Fail : \\?\C:\Users\caina\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0001.jpg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://s3.1.bp.blogspot.com/-4S6PCJlpe1M/WRittUekurI/AAAAAAAPapU/zeF9WmMM16ceE7CU7v50RtEaMdTXhdbuQCLcB/s1600/001.jpg?quick
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1ED1DC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

-----

Fail : \\?\C:\Users\caina\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0001.jpg
Traceback (most recent call last):
File "downloader", line 777, in download
Exception: https://filecdn.xyz/upload/q/932c1b22e295ba336e1c0a9daa4b2f78.jpg
Traceback (most recent call last):
File "downloader", line 773, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1C64CD70>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

-----

Fail_404 : \\?\C:\Users\caina\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\[미호시 메가네] 연애폭군\연애폭군 특별편\0001.jpg
Traceback (most recent call last):
File "downloader", line 748, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://1.bp.blogspot.com/-4S6PCJlpe1M/WRittUekurI/AAAAAAAPapU/zeF9WmMM16ceE7CU7v50RtEaMdTXhdbuQCLcB/s1600/001.jpg?quick --> https://filecdn.xyz/upload/q/932c1b22e295ba336e1c0a9daa4b2f78.jpg

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cainar90** [comment]
옛날꺼 요즘꺼 합쳐서 2~300개 받아보았는데 현재로선 에러나는 파일이 없습니다.

**Comment by cainar90** [comment]
구버젼, 신버젼 둘 다 안받아지는 파일을 발견했습니다.

Invalid: [manamoa] https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=1343950

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=1343950
dir: 
zip: 
type: manamoa
artist: 우메하나
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10523
valid: False
done: True
range: None
range_p: None
single: False
time: 1581081796.56 (Feb 7)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10523
dirFormat: title
fuckkk...
Traceback (most recent call last):
File "constants", line 2660, in wrapper
File "manamoa_downloader", line 297, in get_imgs_page
File "manamoa_downloader", line 389, in get_imgs_page_legacy
TypeError: int() argument must be a string or a number, not 'NoneType'

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 182, in read
File "manamoa_downloader", line 280, in get_imgs
File "constants", line 2687, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 2660, in wrapper
File "manamoa_downloader", line 297, in get_imgs_page
File "manamoa_downloader", line 389, in get_imgs_page_legacy
TypeError: int() argument must be a string or a number, not 'NoneType'


Invalid: fail=True
EOT: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=1343950

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
