### ISSUE TITLE
유튜브 다운로드 불가 현상

### ISSUE THREAD

**Issue by univ11jung** [KurtBestor/Hitomi-Downloader#1655]
[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1100512873,a,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1100512873,a,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by KurtBestor** [comment]
해당 주소 알려주세요

**Comment by univ11jung** [comment]
로그 전체 코멘트로 남깁니다.

-------------------------------------------------------------------

읽는 중... https://www.youtube.com / watch?v=846cmDU2Ayk

version: 2.7h
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://www.youtube.com/watch?v=846cmDU2Ayk
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=846cmDU2Ayk
valid: True
done: False
range: None
range_p: None
single: True
time: 1582450975.57 (Feb 23)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1604#issuecomment-578409207
