### ISSUE TITLE
아무것도 안받아지는데요?;;

### ISSUE THREAD

**Issue by hellchang1356** [KurtBestor/Hitomi-Downloader#1675]
윈도우디펜더에서 앱 예외 해놨는데

유튜브부터해서 아무것도 다운이 안돼요 invalid 하면서...

nvalid: [youtube] https://youtu.be / YK0UdUf6rqM

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://youtu.be/YK0UdUf6rqM
dir: 
zip: 
type: youtube
artist: None
url: https://youtu.be/YK0UdUf6rqM
valid: False
done: True
range: None
range_p: None
single: True
time: 1581757503.0 (Feb 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "youtube_downloader", line 142, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[1596180896,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://youtu.be/YK0UdUf6rqM

**Comment by KurtBestor** [comment]
참고해주세요: #1604
