### ISSUE TITLE
트위터 다운로드가 안됩니다 + 건의

### ISSUE THREAD

**Issue by rlarkakstp** [KurtBestor/Hitomi-Downloader#1682]
트위터 모든 다운로드가 얼마전 업데이트 이후 (픽시브 다운버그 수정 이후) 다운이 안됩니다.
비공개 계정 / 공개 계정 차이 없이 전부 다운이 불가능합니다.

Invalid: [twitter] https://twitter.com / insight_co_kr

version: 2.7h
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://twitter.com/insight_co_kr
dir: 
zip: 
type: twitter
artist: None
url: https://twitter.com/insight_co_kr
valid: False
done: True
range: None
range_p: None
single: True
time: 1582013963.97 (Feb 18)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "twitter_downloader", line 60, in init
File "twitter_downloader", line 67, in id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 228, in get_artist_and_id
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "twitter_downloader", line 230, in get_artist_and_id
File "twitter_downloader", line 235, in get_artist
IndexError: list index out of range

Invalid: fail=True
stop
EOT: https://twitter.com/insight_co_kr

추가로 친구추가된 비공개 계정도 다운받을수 있게 픽시브처럼 설정에서 로그인을 할수 있게 만들어 주시면 감사하겠습니다...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1626

로그인은 브라우저에서 로그인 한 후에 쿠키 불러오면 돼요. `도움말` - `사용법` - `쿠키 불러오기` 참고해주세요.
