### ISSUE TITLE
마리망에서 다운이 안됩니다 어떤 페이지든 Invalid 뜹니다

### ISSUE THREAD

**Issue by monchertonton** [KurtBestor/Hitomi-Downloader#1691]
Invalid: [mrm] https://myreadingmanga.info / zom-natsume-shinizokonai-no-kemono-one-piece-dj-kr / 

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://myreadingmanga.info/zom-natsume-shinizokonai-no-kemono-one-piece-dj-kr/
dir: 
zip: 
type: mrm
artist: None
url: https://myreadingmanga.info/zom-natsume-shinizokonai-no-kemono-one-piece-dj-kr
valid: False
done: True
range: None
range_p: None
single: True
time: 1582335411.86 (Feb 21)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
cf protection
stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "mrm_downloader", line 44, in init
File "mrm_downloader", line 193, in get_session
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "clf", line 9, in wait
File "chrome", line 179, in start
File "chrome", line 96, in get
File "chrome", line 78, in get_local_version
Exception: No Chrome

Invalid: fail=True
stop
EOT: https://myreadingmanga.info/zom-natsume-shinizokonai-no-kemono-one-piece-dj-kr/

**Comment by KurtBestor** [comment]
[Google Chrome](https://chrome.com) 을 설치하세요.

**Comment by monchertonton** [comment]
> [Google Chrome](https://chrome.com) 을 설치하세요.

구글 크롬 현재 사용중인데 뭐가 문제일까요? 최신버전인데ㅠㅠ

**Comment by monchertonton** [comment]
크롬 지우고 재설치하니 해결되었네요 감사드립니다
