### ISSUE TITLE
유튜브 영상이 다운이 안됩니다

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader#1694]
몇몇 영상이 안되는거같은데 원인을 모르겠네요

Invalid: [youtube] https://www.youtube.com / watch?v=dvkkWXxCuEY

version: 2.7h
platform: Windows-10-10.0.18362
order: 31
group: False
gal_num: https://www.youtube.com/watch?v=dvkkWXxCuEY
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=dvkkWXxCuEY
valid: False
done: False
range: None
range_p: None
single: True
time: 1582377574.17 (Feb 22)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

fuckkk...
Traceback (most recent call last):
File "constants", line 605, in wrapper
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

stop
Traceback (most recent call last):
File "utils", line 803, in start
File "utils", line 850, in start_
File "youtube_downloader", line 148, in read
File "constants", line 632, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 605, in wrapper
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=dvkkWXxCuEY

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

fuckkk...
Traceback (most recent call last):
File "constants", line 605, in wrapper
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

stop
Traceback (most recent call last):
File "utils", line 803, in start
File "utils", line 850, in start_
File "youtube_downloader", line 148, in read
File "constants", line 632, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 605, in wrapper
File "youtube_downloader", line 306, in get_videos
File "youtube_dl_test", line 71, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: dvkkWXxCuEY: YouTube said: This video is unavailable.

Invalid: fail=True

**Comment by KurtBestor** [comment]
[youtube-dl](http://ytdl-org.github.io/youtube-dl/) 로는 되나요?

**Comment by rlacks1237** [comment]
youtube-dl.exe
이걸 실행하면 cmd가 열리는데 뭔가 잠깐 뜨고 바로 사라집니다

**Comment by KurtBestor** [comment]
실행파일 경로에서 주소창에 `cmd` 입력해서 cmd.exe 열고 다음 내용 입력하고 <kbd>Enter</kbd> 입력한 다음 나오는 내용 알려주세요:
```
youtube-dl.exe https://www.youtube.com/watch?v=dvkkWXxCuEY
```

**Comment by rlacks1237** [comment]
[youtube] dvkkWXxCuEY: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

입니다

**Comment by KurtBestor** [comment]
웹브라우저에선 동영상 보이나요?

**Comment by rlacks1237** [comment]
넵 보입니다

**Comment by KurtBestor** [comment]
프록시나 VPN 써서 보시나요?

**Comment by rlacks1237** [comment]
아뇨 아무것도 안씁니다

**Comment by KurtBestor** [comment]
유튜브 정보 얻어올 때 [youtube-dl](http://ytdl-org.github.io/youtube-dl/) 쓰는데 이게 안 되니 [여기](https://yt-dl.org/bug)에 문의해주세요.

**Comment by rlacks1237** [comment]
확인해보니 그냥 기다리는방법말곤 없어보이네요 일단 이틀정도 놔둬봐야겠네요

**Comment by rlacks1237** [comment]
기다리니 해결됬습니다 한 이틀정도 프로그램 켜지도 않고 놔뒀어요
