### ISSUE TITLE
epio

### ISSUE THREAD

**Issue by wankio** [KurtBestor/Hitomi-Downloader#1696]
```
Invalid: [epio] https://girlimg.epio.app / article / detail / 5b412ac8dcc9330007ce3a06

version: 2.7h
platform: Windows-10-10.0.18362
order: -1563
group: False
gal_num: https://girlimg.epio.app/article/detail/5b412ac8dcc9330007ce3a06
dir: 
zip: 
type: epio
artist: None
url: https://girlimg.epio.app/article/detail/5b412ac8dcc9330007ce3a06
valid: False
done: True
range: None
range_p: None
single: False
time: 1582391449.86 (Feb 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
wait...
'src'
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "epio_downloader", line 22, in read
File "epio_downloader", line 74, in get_info
KeyError: 'src'

Invalid: fail=True
EOT: https://girlimg.epio.app/article/detail/5b412ac8dcc9330007ce3a06

```

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wankio** [comment]
already tried with both Dev and non-Dev version,

**Comment by KurtBestor** [comment]
That's outdated. Please re-download the test version.

**Comment by wankio** [comment]
which version ? above link you gave me ?
or this lastest version ? Hitomi Downloader v2.7h

ty

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wankio** [comment]
tested and working with your newest reply
this version : 22.4 MB (23,553,294 bytes)

**Comment by wankio** [comment]
but somehow, it stucked, timeout

 ```

[Messages]

Fail : \\?\I:\TOOLS\hitomi_downloader_GUI_test(1)\hitomi_downloaded_epio\蕾丝兔宝宝 2012-05-01 (39P)\0023.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
Exception: http://cdnv2.girlimg.com/images/FmqTeIp3yjT47Z02lHPmcYcOilcg
Traceback (most recent call last):
File "downloader", line 792, in download
File "urllib3\request", line 76, in request
File "urllib3\request", line 97, in request_encode_url
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 423, in _make_request
File "urllib3\connectionpool", line 331, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host='cdnv2.girlimg.com', port=80): Read timed out. (read timeout=60)



Fail : \\?\I:\TOOLS\hitomi_downloader_GUI_test(1)\hitomi_downloaded_epio\蕾丝兔宝宝 2012-05-01 (39P)\0023.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
Exception: http://cdnv2.girlimg.com/images/FmqTeIp3yjT47Z02lHPmcYcOilcg
Traceback (most recent call last):
File "downloader", line 792, in download
File "urllib3\request", line 76, in request
File "urllib3\request", line 97, in request_encode_url
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 423, in _make_request
File "urllib3\connectionpool", line 331, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host='cdnv2.girlimg.com', port=80): Read timed out. (read timeout=60)
```

**Comment by KurtBestor** [comment]
Try this version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wankio** [comment]
worked great, ty. but i dont know why this version, size is so big, 43MB. many changes ??

**Comment by KurtBestor** [comment]
Try this version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wankio** [comment]
@KurtBestor 

work great but we have a problems, if folder name are same, it will checking existed folder and then checking downloaded content, if both are existed, it will skipped and marked links as completed

below is link have same title 
```
https://girlimg.epio.app/article/detail/5c473e5406386400072f496b
https://girlimg.epio.app/article/detail/5c47d31606386400072f49ec
https://girlimg.epio.app/article/detail/5c48a86e06386400072f4acd
https://girlimg.epio.app/article/detail/5c4cac0f06386400072f4d99
https://girlimg.epio.app/article/detail/5c47d9b906386400072f4a0a
https://girlimg.epio.app/article/detail/5c474c4906386400072f4989
```
