### ISSUE TITLE
hanime 영상깨짐 및 건의사항

### ISSUE THREAD

**Issue by IKKASSAN** [KurtBestor/Hitomi-Downloader#1707]
우선 모든 사람들의 편의를 위해 힘들게 프로그램을 만들어주신 Kurt Bestor님께 감사하다는 말로 시작합니다.

hanime 영상을 해당 프로그램으로 받고 나서 보면 재생은 잘 되지만 영상 중간중간 동영상 파일 특유의 깨짐 현상이 보입니다(초록색, 회색화면) 
뭐가 문제인지 최신 버전으로 다시 해보고 최신테스트 파일로 해봤지만 역시나 깨져있었습니다.
크롬의 확장프로그램으로도 다운이 안 되는 동영상형식(m3u8)이여서 그런지는 모르겠습니다. 
또 하나의 영상에서만 발견된 게 아니라 다수의 파일에서 오류를 발견됐습니다.
오류가 발생한 하나의 파일의 정보입니다.

[BugBug] 15 Bishoujo Hyouryuuki 1

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://members.hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1
dir: D:\hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://members.hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1
valid: True
done: True
range: None
range_p: None
single: True
time: 1582537171.92 (Feb 24)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] D:\hitomi_downloaded_hanime\[BugBug] 15 Bishoujo Hyouryuuki 1.mp4

[URLs]
[0001] M3u8_stream(https://hanime.tv/api/v1/m3u8s/33215.m3u8)

[Messages]
stop
EOT: https://members.hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1

다음은 건의사항입니다만

너무 무례하고 귀차니즘이 극에 달한 어리석은 자의 헛소리라 생각하고 무시하셔도 좋습니다
위대하신 존재의 기분이 나빠지신다면  어디 계시는지 모르기에 동서남북으로 한 번씩 대가리 박고 사죄하겠습니다.
첫번째로 마나모아 검색기록에 있는 페이지수(혹은 전체)로 다운이 가능한지입니다.
ex) https://manamoa.net/bbs/page.php?hid=manga_list&search_type=1&sfl=0&_0=&_1=&_2=7&_3=&_4=0&page=163
두번째로 hanime 검색기록(혹은 전체)으로 다운이 가능한지입니다.
ex)https://hanime.tv
https://hanime.tv/search

미천한 저를 위해 시간을 내주셔서 정말 감사합니다
그리고 코로나 조심하세요. 님이 아프시면 저도 마음이 찢어질 정도로 아픕니다.

**Comment by KurtBestor** [comment]
어떤  동영상 플레이어 쓰시나요?

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/351#issuecomment-447619182

**Comment by IKKASSAN** [comment]
온갖 플레이어 다 써봤습니다 행님
vlc media player
다음팟플레이어
5kplayer
km플레이어
곰플레이어
모바일 mx플레이어

혹여나 마나모아에서 만화 받을때 cpu 100퍼찍으면 이미지 한두개 오류 뜨던가 싶어서 영상받을때 cpu 점유율 확인했더니 아주 널널했습니다
컴터 사양은 
cpu i5-6600
메모리는 샘송 ddr4 8기가 pc4-17000
디스크에 베드섹터는 없습니다.

**Comment by KurtBestor** [comment]
깨진 영상 보내주시면 분석해볼게요.

**Comment by IKKASSAN** [comment]
디코로 메세지 보냈씁니다

**Comment by KurtBestor** [comment]
어떤 시간에 깨지는지 알려주세요.

**Comment by IKKASSAN** [comment]
구글메일 주소로 보낸 영상 08:24~08:37에 보시면 오류가 있습니다 화면이 깨저욧
-----Original Message-----

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by IKKASSAN** [comment]
이번엔 invalid가 떴습니다 ㅠㅠ 방화벽 허용했고 dpi 프로세스 켜진것도 봤는데 안되네요
마루마루 유튜브도 같이 해봤는데도 안됩니다 #1727랑 같은 상황인거 같네요

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by IKKASSAN** [comment]
Invalid: [hanime] https://hanime.tv / videos / hentai / 15-bishoujo-hyouryuuki-1

version: 2.7h (20-02-29 06:05:36 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1
dir: 
zip: 
type: hanime
artist: None
url: https://hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1
valid: False
done: True
range: None
range_p: None
single: True
time: 1582981991.92 (Feb 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "hanime_downloader", line 77, in get_video
File "downloader", line 282, in read_html
File "requests\sessions", line 546, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 524, in request
File "requests\sessions", line 700, in merge_environment_settings
File "requests\utils", line 761, in get_environ_proxies
File "requests\utils", line 745, in should_bypass_proxies
File "requests\utils", line 95, in proxy_bypass
File "requests\utils", line 61, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "hanime_downloader", line 60, in read
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "hanime_downloader", line 77, in get_video
File "downloader", line 282, in read_html
File "requests\sessions", line 546, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 524, in request
File "requests\sessions", line 700, in merge_environment_settings
File "requests\utils", line 761, in get_environ_proxies
File "requests\utils", line 745, in should_bypass_proxies
File "requests\utils", line 95, in proxy_bypass
File "requests\utils", line 61, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''


Invalid: fail=True
EOT: https://hanime.tv/videos/hentai/15-bishoujo-hyouryuuki-1

입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by IKKASSAN** [comment]
불초 아우. 형님께 최대한의 경의를 가지고 그랜절로 감사인사드립니다.

비록 미숙하여 3초밖에 하지 못하고 허리에서 좋지 않은 소리가 났지만 형님께 제 마음이 잘 전달 되었으리라 믿습니다. 감사합니다 감사합니다 감사합니다.
