### ISSUE TITLE
마나모아에 다운로더로 다운로드가 안되는 만화가 있습니다

### ISSUE THREAD

**Issue by whatohyou** [KurtBestor/Hitomi-Downloader#1711]
브라우저로는 보이는데 다운로더로는 다운로드가 안됩니다.

https://manamoa28.net/bbs/board.php?bo_table=manga&wr_id=2659027

Fail : \\?\D:\hitomi_downloader_GUI\hitomi_downloaded_manamoa\[카와조에 타이치] 부덕의 길드\부덕의 길드 32화\0025.jpg
Traceback (most recent call last):
File "downloader", line 771, in download
Exception: https://s3.filecdn.xyz//upload/64a70ad1d8cd56fd00afcead0b722156.jpg
Traceback (most recent call last):
File "downloader", line 767, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 350, in connect
File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

어떻게 해야 하나요?

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `DPI 우회` 를 키세요.

**Comment by whatohyou** [comment]
DPI우회는 기본으로 켜져있는데 다운로드가 되지 않습니다.

**Comment by whatohyou** [comment]
[카와조에 타이치] 부덕의 길드

version: 2.7d
platform: Windows-10-10.0.18362
order: 225
group: False
gal_num: https://manamoa28.net/bbs/page.php?hid=manga_detail&manga_id=806
dir: hitomi_downloaded_manamoa\[카와조에 타이치] 부덕의 길드
zip: 
type: manamoa
artist: 카와조에 타이치
url: https://manamoa28.net/bbs/page.php?hid=manga_detail&manga_id=806
valid: False
done: True
range: None
range_p: None
single: False
time: 1582762374.07 (Feb 27)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False

[1031] LazyUrl(https://manamoa28.net/bbs/board.php?bo_table=manga&wr_id=2659027) ---> https://filecdn.xyz//upload/8c244ad0df419b7b4f12709d49fd0044.jpg
[1032] LazyUrl(https://manamoa28.net/bbs/board.php?bo_table=manga&wr_id=2659027) ---> https://filecdn.xyz//upload/341921fbe4bb49b848fe1112e9e00ece.jpg


[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 173, in read
File "manamoa_downloader", line 161, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manamoa18.net/bbs/page.php?hid=manga_detail&manga_id=806

Skip: 부덕의 길드 31화
[seed] 부덕의 길드 32화 0

Fail : \\?\D:\hitomi_downloader_GUI\hitomi_downloaded_manamoa\[카와조에 타이치] 부덕의 길드\부덕의 길드 32화\0001.jpg
Traceback (most recent call last):
File "downloader", line 771, in download
Exception: https://filecdn.xyz//upload/8ae27aa2001b0784bc48eb9e8189a4cb.jpg
Traceback (most recent call last):
File "downloader", line 767, in download
File "urllib3\request", line 68, in request
File "urllib3\request", line 89, in request_encode_url
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 350, in connect
File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1647

**Comment by whatohyou** [comment]
잘됩니다 감사합니다.
