### ISSUE TITLE
몇일 전부터 익헨에서 특정 작품들이 다운이 되지 않습니다.

### ISSUE THREAD

**Issue by MantisKnight** [KurtBestor/Hitomi-Downloader#1714]
이상한게 컴퓨터마다 다운이 먹통이 되는 작품은 각기 조금씩 다른데... 원래는 문제 없이 다운 받았던 것들이라는 것이 다릅니다.

[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)

version: 2.7h
platform: Windows-10-10.0.18362
order: 3
group: False
gal_num: https://exhentai.org/g/1353532/dd38c139f2/
dir: Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)
zip: 
type: ehen
artist: obui
url: https://exhentai.org/g/1353532/dd38c139f2
valid: True
done: False
range: None
range_p: None
single: False
time: 1582770597.65 (Feb 27)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None

[Gallery]
갤러리 넘버: 1353532

제목: (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer)

작가: obui

그룹: oving

타입: doujinshi

시리즈: goblin slayer

캐릭터: cow girl, high elf archer, priestess, sword maiden, female knight, witch

태그: male:goblin, male:guro, male:monster, female:ahegao, female:amputee, female:anal, female:big breasts, female:birth, female:bondage, female:dark skin, female:double penetration, female:guro, female:loli, female:mind break, female:nipple fuck, female:pregnant, female:rape, female:ryona, female:stomach deformation, female:urethra insertion, group, male:snuff, female:blindfold, female:drugs, female:human cattle, female:impregnation

언어: N／A

[File Names]
[0001] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-1
[0002] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-2
[0003] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-3
[0004] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-4
[0005] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-5
[0006] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-6
[0007] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-7
[0008] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-8
[0009] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-9
[0010] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-10
[0011] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-11
[0012] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-12
[0013] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-13
[0014] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-14
[0015] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-15
[0016] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-16
[0017] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-17
[0018] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-18
[0019] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-19
[0020] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-20
[0021] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-21
[0022] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-22
[0023] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-23
[0024] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-24
[0025] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-25
[0026] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-26
[0027] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-27
[0028] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-28
[0029] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-29
[0030] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-30
[0031] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-31
[0032] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-32
[0033] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-33
[0034] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-34
[0035] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-35
[0036] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-36
[0037] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-37
[0038] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-38
[0039] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-39
[0040] Download\[Obui (Oving)] (C95) [OVing (Obui)] Goblin Lord ga Katta Hi + Omakebon (Goblin Slayer) (1353532)\1353532-40

[URLs]
[0001] https://exhentai.org/s/2d84ffd37f/1353532-1
[0002] https://exhentai.org/s/e761affa46/1353532-2
[0003] https://exhentai.org/s/0b179f7f11/1353532-3
[0004] https://exhentai.org/s/8f18cc1d26/1353532-4
[0005] https://exhentai.org/s/a66b51abec/1353532-5
[0006] https://exhentai.org/s/887bb36bef/1353532-6
[0007] https://exhentai.org/s/4e4fc0bce7/1353532-7
[0008] https://exhentai.org/s/ab6db7375e/1353532-8
[0009] https://exhentai.org/s/c5997191dd/1353532-9
[0010] https://exhentai.org/s/ee89005847/1353532-10
[0011] https://exhentai.org/s/9a049acfed/1353532-11
[0012] https://exhentai.org/s/b308d547f3/1353532-12
[0013] https://exhentai.org/s/701f5a4554/1353532-13
[0014] https://exhentai.org/s/d4ce04b409/1353532-14
[0015] https://exhentai.org/s/2db795b067/1353532-15
[0016] https://exhentai.org/s/13b0c8f9d6/1353532-16
[0017] https://exhentai.org/s/1b8d55897f/1353532-17
[0018] https://exhentai.org/s/ab25e07ece/1353532-18
[0019] https://exhentai.org/s/2bc158b60c/1353532-19
[0020] https://exhentai.org/s/0f46d68f6b/1353532-20
[0021] https://exhentai.org/s/40efef7e79/1353532-21
[0022] https://exhentai.org/s/930a49ca74/1353532-22
[0023] https://exhentai.org/s/55172895e3/1353532-23
[0024] https://exhentai.org/s/e91ac8363c/1353532-24
[0025] https://exhentai.org/s/5f3efd82fa/1353532-25
[0026] https://exhentai.org/s/744dadb4c2/1353532-26
[0027] https://exhentai.org/s/0e4a779b09/1353532-27
[0028] https://exhentai.org/s/d291eeef93/1353532-28
[0029] https://exhentai.org/s/eda4cf25d3/1353532-29
[0030] https://exhentai.org/s/4ed1daadc7/1353532-30
[0031] https://exhentai.org/s/e761affa46/1353532-31
[0032] https://exhentai.org/s/a0de549a20/1353532-32
[0033] https://exhentai.org/s/0393b523aa/1353532-33
[0034] https://exhentai.org/s/f7561764ff/1353532-34
[0035] https://exhentai.org/s/f8a567b560/1353532-35
[0036] https://exhentai.org/s/6ea7055756/1353532-36
[0037] https://exhentai.org/s/a23b94dce3/1353532-37
[0038] https://exhentai.org/s/86584f6c28/1353532-38
[0039] https://exhentai.org/s/ee4d8fa99b/1353532-39
[0040] https://exhentai.org/s/2af47bb2a9/1353532-40

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/1353532/dd38c139f2/)
using custom cookies
#### https://e-hentai.org/g/1353532/dd38c139f2 ----> https://e-hentai.org/g/1353532/dd38c139f2
Traceback (most recent call last):
File "hitomi_downloader", line 678, in read
File "hitomi_downloader", line 549, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
File "downloader", line 369, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/1353532/dd38c139f2/)
using custom cookies
#### https://exhentai.org/g/1353532/dd38c139f2 ----> https://exhentai.org/g/1353532/dd38c139f2
FINAL SERVER: ehen
ehen_url: https://exhentai.org/g/1353532/dd38c139f2
imgs: 40
E-Hentai: https://exhentai.org/g/1353532/dd38c139f2

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "hitomi_downloader", line 254, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "hitomi_downloader", line 254, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "hitomi_downloader", line 254, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/2d84ffd37f/1353532-1
Traceback (most recent call last):
File "ehen_downloader", line 37, in get_img
Exception: 509.gif

**Comment by KurtBestor** [comment]
참고해주세요: #1407

**Comment by MantisKnight** [comment]
> 참고해주세요: #1407

아, 정말 감사합니다. 저런게 있는지도 몰랐었네요...
