### ISSUE TITLE
저는 마나모아 여전히 다운안됩니다

### ISSUE THREAD

**Issue by doaldi** [KurtBestor/Hitomi-Downloader#1727]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이걸 설치해서 실행했는데 여전히 다운이 안됩니다 다른분들은 다 되는거 같은데 왜 저만 안되는지 모르겠네요;

Invalid: [manamoa] https://manamoa29.net / bbs / page.php?hid=manga_detail&manga_id=8081

version: 2.7h (20-02-29 06:05:36 GMT+0)
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=8081
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=8081
valid: False
done: True
range: None
range_p: None
single: False
time: 1582967842.32 (Feb 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
WebDriverException: Message: unknown error: cannot find Chrome binary

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
WebDriverException: Message: unknown error: cannot find Chrome binary

Invalid: fail=True
EOT: https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=8081

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 나오는 내용 보여주세요:
```
__import__('chrome').get_local_version()
```

**Comment by lducjswo** [comment]
저도 안됩니다 ㅠㅠ
저는 그거 쓰면 요렇게 나옵니다
(80, 0, 3987, 122)

**Comment by doaldi** [comment]
[u'C:\\Program Files (x86)\\Google\\Chrome Beta\\Application\\chrome.exe', 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe']
(80, 0, 3987, 16)

이렇게 뜹니다

**Comment by smart2k** [comment]
크롬이 안깔려있었어서 안됐었네요
크롬 설치하고 나니 오래 걸리긴 하지만 크롬창 뜨고 잘 됩니다.
정말 감사드립니다.

**Comment by doaldi** [comment]
제가 크롬 베타버전을 쓰고있던게 문제였나 보네요 일반버전으로 까니까 다운됩니다

**Comment by lducjswo** [comment]
저도 몇번 테스트 해보니 잘 됩니다
10개받는데 40분이 걸리긴 했지만요 
감사합니다
