### ISSUE TITLE
마나모아 29로 넘어간 이후부터 계속 다운이 되지 않습니다.

### ISSUE THREAD

**Issue by gling2** [KurtBestor/Hitomi-Downloader#1733]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

텍티컬 버전받아서 해보았으나 역시 다운이 되지 않더라구요..

Invalid: [manamoa] https://manamoa29.net / bbs / board.php?bo_table=manga&wr_id=2849886

version: 2.7h (20-02-29 05:49:36 GMT+0)
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2849886
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2849886
valid: False
done: True
range: None
range_p: None
single: True
time: 1583138880.02 (Mar 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 load...
Solve protection
【chrome】 load...
【chrome】 load...
Solve protection
【chrome】 load...
【chrome】 load...
Solve protection
【chrome】 load...
【chrome】 load...
stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "manamoa_downloader", line 140, in init
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 188, in start
File "chrome", line 105, in get
File "chrome", line 79, in get_local_version
Exception: No Chrome

Invalid: fail=True
stop
EOT: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2849886

**Comment by s25jin** [comment]
29말고 manamoa.net 로 접속가능하게 만든후에 해보세요 29로 하니까 저도 안되더라구요.
프리뷰버전 +  dpi 로 햇서요

**Comment by gling2** [comment]
s25jin manamoa.net으로 접속해서 텍티컬 프리뷰 버전 + dpi 우회도 해보았지만 다운이 안되더라구요..

**Comment by s25jin** [comment]
흠...원인이 몰까요. 윈도우10 에서 secretsni+gooddpi 한 상태에서 크롬접속해서 https://manamoa.net/ 접속 확인해서 정상 사용되는거 확인하고 히토미 다운로더 v2.7h 로 햇습니다.

**Comment by whatohyou** [comment]
그저께만 해도 잘 다운되었는데 오늘 하니까 저도 안되네요. 저는 외국이라 우회가 필요없이 접속은 잘되는데 다운로드가 안됩니다.

**Comment by whatohyou** [comment]
Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=1748

version: 2.7h (20-02-27 06:31:03 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748
valid: False
done: True
range: None
range_p: None
single: False
time: 1583210130.29 (Mar 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 208, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 180, in read
File "manamoa_downloader", line 167, in name
File "manamoa_downloader", line 153, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 208, in get_soup
Exception: No subject


Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748

다운로드 페이지 양식이 바뀌어서 주소를 파싱해오지 못하는 느낌이네요.

**Comment by KurtBestor** [comment]
@gling2 크롬 브라우저를 설치해주세요.

**Comment by KurtBestor** [comment]
@whatohyou 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1720

**Comment by whatohyou** [comment]
잘됩니다 감사합니다.
