### ISSUE TITLE
마나모아 또 막힌거 같네요

### ISSUE THREAD

**Issue by doaldi** [KurtBestor/Hitomi-Downloader#1738]
크롬창 몇번 켜졌다 꺼졌다 반복하더니 그냥 실패되고 맙니다 얼마전까진 잘되었는데 또 어떻게 막은 모양이네요

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by doaldi** [comment]
Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=12701

version: 2.7h (20-02-29 13:17:36 GMT+0)
platform: Windows-10-10.0.17763
order: 18
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701
valid: False
done: True
range: None
range_p: None
single: False
time: 1583391175.17 (Mar 5)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81



stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81




Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701

Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 211, in get_soup
File "manamoa_downloader", line 472, in read_html
File "downloader", line 302, in read_html
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 376, in _make_request
File "urllib3\connectionpool", line 994, in _validate_conn
File "urllib3\connection", line 300, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x06AF0430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 211, in get_soup
File "manamoa_downloader", line 472, in read_html
File "downloader", line 302, in read_html
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 376, in _make_request
File "urllib3\connectionpool", line 994, in _validate_conn
File "urllib3\connection", line 300, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x06AF0430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed


Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1106, in Invalid
File "downloader", line 302, in read_html
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 184, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x06ACDCD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701

Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81



stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81




Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701

**Comment by doaldi** [comment]
Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=12701

version: 2.7h (20-02-29 13:17:36 GMT+0)
platform: Windows-10-10.0.17763
order: 18
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701
valid: False
done: True
range: None
range_p: None
single: False
time: 1583391175.17 (Mar 5)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81



stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81




Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701

Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 211, in get_soup
File "manamoa_downloader", line 472, in read_html
File "downloader", line 302, in read_html
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 376, in _make_request
File "urllib3\connectionpool", line 994, in _validate_conn
File "urllib3\connection", line 300, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x06AF0430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 211, in get_soup
File "manamoa_downloader", line 472, in read_html
File "downloader", line 302, in read_html
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 376, in _make_request
File "urllib3\connectionpool", line 994, in _validate_conn
File "urllib3\connection", line 300, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x06AF0430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed


Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1106, in Invalid
File "downloader", line 302, in read_html
File "urllib3\poolmanager", line 330, in urlopen
File "urllib3\connectionpool", line 720, in urlopen
File "urllib3\util\retry", line 376, in increment
File "urllib3\connectionpool", line 672, in urlopen
File "urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 184, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x06ACDCD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701

Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81



stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81




Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12701

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
