### ISSUE TITLE
Cloudflare DDoS protection, 새 창을 안보이게 할 수 있을까요?

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#1742]
안녕하세요, 덕분에 프로그램을 잘 이용하고 있는 유저입니다. : )
 늘 빠르게 대응 해 주셔서 감사합니다.

 몇 시간 전 조금 특이하고 드문 상황이 발생했었는데, 약 80개의 링크를 입력 한 상태로 잠시 다른 일을 하고 왔더니, 새 창들이 셀 수 없을 정도로 열려있었고 '페이지를 복원하시겠습니까?' 라는 문구와 런타임에 관련 된 '영어로 된 팝업 메시지' 또한 수십개가 쌓여 있었습니다.

 작업을 시행하는 과정에서 오류 메시지를 포함한 새 창들이 스스로 사라지지 않은 모양 인지라 약간의 지연 현상을 거치며 새 창들을 모두 제거하였고, 작업 중이었던 목록들은 전부 붉은 글씨로 [불완전한 작업] 으로 처리되어 있었기에, '불완전한 작업 다시 시작'을 누르니 정상적으로 잘 작동하게 되었습니다.

 새 창이 열리는 현상은 사용자가 입력한 사이트에서 Cloudflare DDoS protection를 사용하고 있기 때문에 새 창이 열리는 것으로, 지난 이슈 글을 검색 했습니다.
 간혹 창이 열릴 때 마다 다른 작업들이 가려지게 되는 불편함도 있어서 아예 새 창을 안보이게 가릴 수 있는 방법은 없을까 문의를 드립니다.

**Comment by mita5549** [comment]
Invalid: [manamoa] https://manamoa29.net / bbs / board.php?bo_table=manga&wr_id=2836865

version: 2.7h (20-03-04 16:50:58 GMT+0)
platform: Windows-10-10.0.17763
order: 98
group: False
gal_num: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2836865
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2836865
valid: False
done: True
range: None
range_p: None
single: True
time: 1583428219.32 (Mar 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
stop
Traceback (most recent call last):
File "utils", line 672, in __init__
File "manamoa_downloader", line 140, in init
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir




Invalid: fail=True
stop
EOT: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2836865

**Comment by KurtBestor** [comment]
창을 보이지 않게 하면 reCAPTCHA 가 나오는 경우도 있고, 만약에 오류가 나거나 무한 로딩이면 직접 꺼주어야하는데 보이지 않으면 끄지 못해서 다른 모든 작업이 멈추는 등의 문제가 있어요.

해당 오류는 크롬 창이 여러 개 떠서 메모리가 부족해서 나오는 것 같은데, 좀 더 안정적으로 되게 바꿨어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
아... 그런 문제가 또 있군요.
테스트 해보겠습니다!
