### ISSUE TITLE
vimeo 다운로드가 안됩니다

### ISSUE THREAD

**Issue by uniyui** [KurtBestor/Hitomi-Downloader#1747]
Invalid: [vimeo] https://vimeo.com / 216475723

version: 2.7h
platform: Windows-8.1-6.3.9600
order: 0
group: False
gal_num: https://vimeo.com/216475723
dir: 
zip: 
type: vimeo
artist: None
url: https://vimeo.com/216475723
valid: False
done: True
range: None
range_p: None
single: True
time: 1583554085.51 (Mar 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "vimeo_downloader", line 54, in __init__
KeyError: 'width'

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "vimeo_downloader", line 36, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "vimeo_downloader", line 54, in __init__
KeyError: 'width'

Invalid: fail=True
EOT: https://vimeo.com/216475723

fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "vimeo_downloader", line 54, in __init__
KeyError: 'width'

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "vimeo_downloader", line 36, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "vimeo_downloader", line 54, in __init__
KeyError: 'width'

Invalid: fail=True
EOT: https://vimeo.com/216475723

이렇게 뜨네요...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by uniyui** [comment]
정상 작동합니다. 감사합니다.
