### ISSUE TITLE
마나모아 다운 자체가 안됩니다.

### ISSUE THREAD

**Issue by led26-max** [KurtBestor/Hitomi-Downloader#1762]
2월달부터 마나모아 전체가 다운시 오류가 뜨네요??
전부 빨간색으로 없는 자료로 나옵니다.
테스트 버전, 현재 버전 전부 빨간색으로 나옵니다.
다운이 아예 안되는 건가요?

1번째
Invalid: [manamoa] https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=7582

version: 2.7h
platform: Windows-10-10.0.18362
order: 12
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=7582
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=7582
valid: False
done: True
range: None
range_p: None
single: False
time: 1583760692.45 (Mar 9)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 173, in read
File "manamoa_downloader", line 160, in name
File "manamoa_downloader", line 146, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=7582

2번째
Invalid: [manamoa] https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=4289

version: 2.7h
platform: Windows-10-10.0.18362
order: 13
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=4289
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=4289
valid: False
done: True
range: None
range_p: None
single: False
time: 1583760678.29 (Mar 9)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 173, in read
File "manamoa_downloader", line 160, in name
File "manamoa_downloader", line 146, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=4289

**Comment by KurtBestor** [comment]
작업 정보 보니 최신 테스트 버전이 아니네요.

**Comment by led26-max** [comment]
최신 테스트 버전이 어디있나요?
링크 걸어주실수 있나요?

**Comment by FoxSays** [comment]
저도 동일증상입니다. 다른 글에서 링크된 테스트 버전이란 받아도 2.7h로 뜨고 같은 증상이 있는데 별도로 받는 곳이 다른 이유가 있는지요?

**Comment by KurtBestor** [comment]
최신 테스트 버전은 작업 정보에 `version: 2.7h (20-03-09 14:11:41 GMT+0)` 라고 떠요.
