### ISSUE TITLE
Xhamster 다운이 안됩니다

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader#1763]
주소 입력하면 오류가 나는데 빨간색으로 주소를 못찾거나 하는건 아니고 다운로드 시작까지는 되는데 0퍼센트에서 진행 안되다가 노란색으로 오류뜹니다

작업정보에는
 [URLs]
[0001] https://video5.xhcdn.com/key=SbCvZKgMZ6NnL1qN22HywQ,end=1583787600,limit=3/data=211.177.153.3-dvp/speed=78k/initial_buffer=1163296/referer=force,.xhcdn.com,.xhamster10.com/009/816/276/240p.h264.mp4

[Messages]
use just download

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\G:\종범성님\manga\딸감_xhamster\Adorable anal babe.mp4
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

stop
valid=False 1
EOT: https://xhamster.com/videos/adorable-anal-babe-9816276

이렇게 뜹니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by supermekadeathstalin** [comment]
잘작동합니다
