### ISSUE TITLE
유튜브 다운로드가 안돼고 또 하나는 음악변환이 너무 느려요.

### ISSUE THREAD

**Issue by eternalgrow** [KurtBestor/Hitomi-Downloader#1776]
하나는 다운로드가 되긴하는데 너무 느리고 음악변환 100%에서 너무 오래걸립니다.  3번 시도 하는 중에  한번은 80%에서 멈춰서 변환이 지속 되길래 뭐지하고 끄고 반복하다가 100% 뜨고 나서 변환중이길래 이번에는 빨리 되겠지 했는데 10분 이상 걸린 것 같습니다.  컴퓨터를 새로 샀는데 컴 성능은 차이가 없는데 다운로드 속도랑 변환속도가 너무 차이가 나서 질문합니다. 윈도우 업데이트를 안해서 그런걸까요? dpi도 검색해서 설치해서 윈도우 업데이트하나 했긴했는데

또 하나는 다운로드가 시작을 안 합니다. 주황색표시? 
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1604#issuecomment-578409207
가서 test버전 다운 받아서 했는데 안돼요

이게 변환이 너무 느린 경우
14 Please, show me the way

version: 2.7h
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=NE72XPTf6JI&t=3s
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: tintinadulathon
url: https://www.youtube.com/watch?v=NE72XPTf6JI&t=3s
valid: True
done: False
range: None
range_p: None
single: True
time: 1584105799.22 (Mar 13)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\14 Please, show me the way.mp4

[URLs]
[0001] https://r6---sn-3u-nf0e.googlevideo.com/videoplayback?expire=1584127399&ei=R4lrXpflF5WPgQPyn5II&ip=175.195.40.97&id=o-ACtymnY4Bj89wDnqCOKJQJJNZAUQa4t6oyvMTvnJPzXI&itag=22&source=youtube&requiressl=yes&mh=a8&mm=31%2C29&mn=sn-3u-nf0e%2Csn-3u-bh2l6&ms=au%2Crdu&mv=m&mvi=5&pcm2cms=yes&pl=21&initcwndbps=1548750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=195.047&lmt=1576911640196045&mt=1584105698&fvip=6&fexp=23842630&beids=9466587&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ADKhkGMwRQIhAMbC5aMHShBNBTG1pOUOGNV8c13Du9oXmeWb6Ntl78wXAiBnqzFdg-aZ9bKNusV-9dl-zDA2ugTMiW3KtffiRqT6zw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIhAL41lhcjKsTASGHsKoxwWjveKnxl6fFKbTxqAwVcT5f3AiAh6C4H7WmR5KyHVb0oWp_JqDYMJ3_PWpgYo7EkJil68Q%3D%3D

[Messages]
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x0B8832F0> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 0fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4
FPS: 0

stop
Convert: C:\Users\lenovo\Downloads\hitomi_downloaded_youtube\14 Please, show me the way.mp4
rename (1): C:\Users\lenovo\Downloads\hitomi_downloaded_youtube\14 Please, show me the way.mp4 -> C:\Users\lenovo\Downloads\hitomi_downloaded_youtube\tmpFB72A0A2_i.mp4
-i tmpFB72A0A2_i.mp4 -shortest -preset ultrafast -b:a 320k tmpFB72A0A2_o.mp3

100%

다운이 안 되는 경우
18 Next Door To

version: 2.7h
platform: Windows-7-6.1.7601-SP1
order: 1
group: False
gal_num: https://www.youtube.com/watch?v=RoVhpaeXhVo
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: tintinadulathon
url: https://www.youtube.com/watch?v=RoVhpaeXhVo
valid: False
done: True
range: None
range_p: None
single: True
time: 1584105679.45 (Mar 13)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\18 Next Door To.mp4

[URLs]
[0001] https://r4---sn-3u-nf0l.googlevideo.com/videoplayback?expire=1584127279&ei=z4hrXoCdNPOKs8IP3MWYyAU&ip=175.195.40.97&id=o-AMbn2O1Df-2uDggY1_8xTx62C052UNo017gbGrYPKkBQ&itag=22&source=youtube&requiressl=yes&mh=Qm&mm=31%2C29&mn=sn-3u-nf0l%2Csn-3u-bh2e7&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1187500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=95.062&lmt=1576912034639258&mt=1584105586&fvip=4&fexp=23842630&beids=9466586&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ADKhkGMwRQIgShgnU9GXHS6NLtMGBS1kaYjRv_7bH8W9h52SOaBcwucCIQCJ3d5pCqlBgYUsSwZj9_WTGLhYLi0rgEA1sChKJJ8vuw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRAIgPYZF1LoPHuVjzirHMxiayIfMbrRAY0KO9xYgtYcvEDQCIAIZx5mBDNNJ0MlEZ9U1Co0Sg-mXOjhIGOzwdA__FQ-l

[Messages]
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x1BDA8130> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 0fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4
FPS: 0

downloader_v3 fail... p[1 / 4]
Traceback (most recent call last):
File "downloader_v3", line 67, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 4]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[1 / 4]
Traceback (most recent call last):
File "downloader_v3", line 67, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 4]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: size mismatch: 0 / 1048576

stop
valid=False 1
EOT: https://www.youtube.com/watch?v=RoVhpaeXhVo

다른 폴더에 테스트 버전으로 다운 시도 한 거

18 Next Door To

version: 2.7h (20-03-13 07:56:22 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=RoVhpaeXhVo&t=1s
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: tintinadulathon
url: https://www.youtube.com/watch?v=RoVhpaeXhVo&t=1s
valid: False
done: True
range: None
range_p: None
single: True
time: 1584107002.46 (Mar 13)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\18 Next Door To.mp4

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=RoVhpaeXhVo&t=1s) ---> https://r4---sn-3u-nf0l.googlevideo.com/videoplayback?expire=1584128604&ei=_I1rXvyNK6Kxigbi4pmIAQ&ip=175.195.40.97&id=o-ABBCTsnlJaAbkaOwXtB4ddNAkM_Hsp425gpxjoB4UiqL&itag=22&source=youtube&requiressl=yes&mh=Qm&mm=31%2C29&mn=sn-3u-nf0l%2Csn-3u-bh2e7&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1091250&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=95.062&lmt=1576912034639258&mt=1584106895&fvip=4&fexp=23842630&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ADKhkGMwRQIhAOSJV6xPh5FdOaaOjG5afJ3jW38XBXmZVTu8OOaEJujzAiBpE4gu2zcx35KG7v7EWhBqrJaOFGZquXknsQaBvt6kxQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRgIhANEVwJqQ4M2hdMNNCLKLv96gWcPciJoG8A0Nn-JOBj8xAiEA6gwsFUf3VUGjJadXiWKawF53qaasKzoBxJo8kWKHv_E%3D

[Messages]
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x000000002709EC48> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 0fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4
FPS: 0

downloader_v3 fail... p[1 / 4]
Traceback (most recent call last):
File "downloader_v3", line 68, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 4]
Traceback (most recent call last):
File "downloader_v3", line 71, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[1 / 4]
Traceback (most recent call last):
File "downloader_v3", line 68, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 4]
Traceback (most recent call last):
File "downloader_v3", line 71, in run
Exception: size mismatch: 0 / 1048576

stop
valid=False 1
EOT: https://www.youtube.com/watch?v=RoVhpaeXhVo&t=1s

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by eternalgrow** [comment]
잘 됩니다. 감사해요^^ 변환도 저번보다 수십배 빠르고 다운로드도 막힘없이 잘 됩니다.
