### ISSUE TITLE
마나모아;;;;

### ISSUE THREAD

**Issue by bbtan81** [KurtBestor/Hitomi-Downloader#1780]
감사히 잘 쓰고 있습니다..

3-13일자 테스트 버전 사용중에 유독 이것만 안되네요ㅜㅜ
Invalid: [manamoa] https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=1402

version: 2.7h (20-03-13 16:17:19 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1402
dir: 
zip: 
type: manamoa
artist: 타시로 테츠야
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1402
valid: False
done: True
range: None
range_p: None
single: False
time: 1584273344.9 (Mar 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
dirFormat: [artist] title
아카메가 벤다 본편코믹스만화번역1화 chapter:32784 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역2화 chapter:32792 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역3화 chapter:32796 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역4화 chapter:32802 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
아카메가 벤다 본편코믹스만화번역5화 chapter:32808 seed:0 domains:121
fuckkk...
Traceback (most recent call last):
File "constants", line 653, in wrapper
File "manamoa_downloader", line 330, in get_imgs_page
File "manamoa_downloader", line 461, in get_imgs_page_legacy
File "manamoa_downloader", line 77, in __init__
Exception: no url

stop
Traceback (most recent call last):
File "utils", line 815, in start
File "utils", line 865, in start_
File "manamoa_downloader", line 193, in read
File "manamoa_downloader", line 313, in get_imgs
File "constants", line 680, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 653, in wrapper
File "manamoa_downloader", line 330, in get_imgs_page
File "manamoa_downloader", line 461, in get_imgs_page_legacy
File "manamoa_downloader", line 77, in __init__
Exception: no url

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1402

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
