### ISSUE TITLE
사운드 클라우드 다운로드 불가 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1787]
존경하는 선생님
왜인지 다운로드가 안되어서 올려봅니다!
오늘도 건강하세요 선생님!

테스트 다운로드 주소 : https://soundcloud.com/lilpump

아래는 로그입니다

-----------------------------------------------
Invalid: [soundcloud] https://soundcloud.com / lilpump

version: 2.7h (20-03-04 16:50:58 GMT+0)
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://soundcloud.com/lilpump
dir: 
zip: 
type: soundcloud
artist: None
url: https://soundcloud.com/lilpump
valid: False
done: True
range: None
range_p: None
single: True
time: 1584488468.73 (Mar 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "soundcloud_downloader", line 173, in get_audios
KeyError: 'kind'

stop
Traceback (most recent call last):
File "utils", line 810, in start
File "utils", line 857, in start_
File "soundcloud_downloader", line 109, in read
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "soundcloud_downloader", line 173, in get_audios
KeyError: 'kind'

Invalid: fail=True
EOT: https://soundcloud.com/lilpump

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
존경하는 선생님 역시 잘 작동됩니다. 감사합니다!
