### ISSUE TITLE
마나모아 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by kimch0612** [KurtBestor/Hitomi-Downloader#1789]
방금 전까진 잘 됐는데 어느 순간부터 시작하자마자 바로 빨간색 글씨가 뜨면서 작업이 멈춰버리더라고요
2.7h 버전이었나요? 그거 쓰다가 안되길래 개발자님께서 프리뷰 버전 올리신것도 써봣는데 오류가 동일하게 뜨더라고요
오류코드 아래에 첨부하겠습니다
감사합니다

Invalid: [manamoa] https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=721

version: 2.7h (20-03-18 05:08:11 GMT+0)
platform: Windows-10-10.0.18362
order: 52
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721
dir: m_manamoa\[야마시타 분고] 모여라! 시튼 학원
zip: 
type: manamoa
artist: 야마시타 분고
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721
valid: False
done: True
range: None
range_p: None
single: False
time: 1584511530.99 (Mar 18)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 176, in name
File "manamoa_downloader", line 160, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 215, in get_soup
File "manamoa_downloader", line 113, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 204, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721

Solve protection
【chrome】 load...
【chrome】 loaded
dirFormat: [artist] title
Skip: 모여라! 시튼 학원 1화
Skip: 모여라! 시튼 학원 1화번외편
Skip: 모여라! 시튼 학원 2화
Skip: 모여라! 시튼 학원 2화번외편
Skip: 모여라! 시튼 학원 3-4화번외편
Skip: 모여라! 시튼 학원 3화
Skip: 모여라! 시튼 학원 4화
Skip: 모여라! 시튼 학원 5화
Skip: 모여라! 시튼 학원 5화번외편
Skip: 모여라! 시튼 학원 6화
Skip: 모여라! 시튼 학원 6화번외편
Skip: 모여라! 시튼 학원 7화
Skip: 모여라! 시튼 학원 7화번외편
Skip: 모여라! 시튼 학원 8화
Skip: 모여라! 시튼 학원 8화번외편
Skip: 모여라! 시튼 학원 9화
Skip: 모여라! 시튼 학원 10화
Skip: 모여라! 시튼 학원 11화
Skip: 모여라! 시튼 학원 12화
Skip: 모여라! 시튼 학원 13화
Skip: 모여라! 시튼 학원 14화
Skip: 모여라! 시튼 학원 14화번외편
Skip: 모여라! 시튼 학원 15화
Skip: 모여라! 시튼 학원 15화번외편
Skip: 모여라! 시튼 학원 16화
Skip: 모여라! 시튼 학원 16화번외편
Skip: 모여라! 시튼 학원 17화
Skip: 모여라! 시튼 학원 17화번외편
Skip: 모여라! 시튼 학원 18화
Skip: 모여라! 시튼 학원 18화번외편
Skip: 모여라! 시튼 학원 19화
Skip: 모여라! 시튼 학원 19화번외편
Skip: 모여라! 시튼 학원 20화
Skip: 모여라! 시튼 학원 20화번외편
Skip: 모여라! 시튼 학원 21화
Skip: 모여라! 시튼 학원 21화번외편
Skip: 모여라! 시튼 학원 22화
Skip: 모여라! 시튼 학원 22화번외편
Skip: 모여라! 시튼 학원 23화
Skip: 모여라! 시튼 학원 23화번외편
Skip: 모여라! 시튼 학원 24화
Skip: 모여라! 시튼 학원 24화번외편
Skip: 모여라! 시튼 학원 25화
Skip: 모여라! 시튼 학원 25화번외편
Skip: 모여라! 시튼 학원 26화
Skip: 모여라! 시튼 학원 26화번외편
Skip: 모여라! 시튼 학원 27화
Skip: 모여라! 시튼 학원 27화번외편
Skip: 모여라! 시튼 학원 28화
Skip: 모여라! 시튼 학원 28화번외편
Skip: 모여라! 시튼 학원 29화
Skip: 모여라! 시튼 학원 29화번외편
Skip: 모여라! 시튼 학원 30화
Skip: 모여라! 시튼 학원 30화번외편
Skip: 모여라! 시튼 학원 31화
Skip: 모여라! 시튼 학원 32화
Skip: 모여라! 시튼 학원 32화번외편
Skip: 모여라! 시튼 학원 33화
Skip: 모여라! 시튼 학원 33화번외편
Skip: 모여라! 시튼 학원 34화
Skip: 모여라! 시튼 학원 34화번외편
Skip: 모여라! 시튼 학원 35화
Skip: 모여라! 시튼 학원 35화번외편
Skip: 모여라! 시튼 학원 36화
Skip: 모여라! 시튼 학원 36화번외편
Skip: 모여라! 시튼 학원 37화
Skip: 모여라! 시튼 학원 37화번외편
Skip: 모여라! 시튼 학원 38화
Skip: 모여라! 시튼 학원 38화번외편
Skip: 모여라! 시튼 학원 39화
Skip: 모여라! 시튼 학원 39화번외편
Skip: 모여라! 시튼 학원 40화
Skip: 모여라! 시튼 학원 40화번외편
Skip: 모여라! 시튼 학원 41화
Skip: 모여라! 시튼 학원 41화번외편
Skip: 모여라! 시튼 학원 42화
Skip: 모여라! 시튼 학원 42화번외편
Skip: 모여라! 시튼 학원 43화
Skip: 모여라! 시튼 학원 43화번외편
Skip: 모여라! 시튼 학원 44화
Skip: 모여라! 시튼 학원 44화번외편
Skip: 모여라! 시튼 학원 45화
Skip: 모여라! 시튼 학원 45화번외편
Skip: 모여라! 시튼 학원 46화
Skip: 모여라! 시튼 학원 46화번외편
Skip: 모여라! 시튼 학원 47화
Skip: 모여라! 시튼 학원 47화번외편
Skip: 모여라! 시튼 학원 48화
Skip: 모여라! 시튼 학원 48화번외편
Skip: 모여라! 시튼 학원 49화
Skip: 모여라! 시튼 학원 49화번외편
Skip: 모여라! 시튼 학원 50화
Skip: 모여라! 시튼 학원 50화번외편
Skip: 모여라! 시튼 학원 51화
Skip: 모여라! 시튼 학원 51화번외편
Skip: 모여라! 시튼 학원 52화
Skip: 모여라! 시튼 학원 52화번외편
Skip: 모여라! 시튼 학원 53화
Skip: 모여라! 시튼 학원 53화번외편
Skip: 모여라! 시튼 학원 54화
Skip: 모여라! 시튼 학원 54화번외편
Skip: 모여라! 시튼 학원 55화
Skip: 모여라! 시튼 학원 55화번외편
Skip: 모여라! 시튼 학원 56화
Skip: 모여라! 시튼 학원 57화
Skip: 모여라! 시튼 학원 58화
Skip: 모여라! 시튼 학원 59화+보너스
Skip: 모여라! 시튼 학원 60화
Skip: 모여라! 시튼 학원 번외편
Skip: 모여라! 시튼 학원 61화
Skip: 모여라! 시튼 학원 61.5화
Skip: 모여라! 시튼 학원 62화
Skip: 모여라! 시튼 학원 62.5화
Skip: 모여라! 시튼 학원 63화
Skip: 모여라! 시튼 학원 64화
Skip: 모여라! 시튼 학원 65화
Skip: 모여라! 시튼 학원 66화
Skip: 모여라! 시튼 학원 67화
Skip: 모여라! 시튼 학원 68화
Skip: 모여라! 시튼 학원 69화
Skip: 모여라! 시튼 학원 70화
Skip: 모여라! 시튼 학원 71화
Skip: 모여라! 시튼 학원 72화
Skip: 모여라! 시튼 학원 73화
Skip: 모여라! 시튼 학원 74화
Skip: 모여라! 시튼 학원 75화
Skip: 모여라! 시튼 학원 76화
Skip: 모여라! 시튼 학원 77화
Skip: 모여라! 시튼 학원 78화
Skip: 모여라! 시튼 학원 79화
Skip: 모여라! 시튼 학원 80화
Skip: 모여라! 시튼 학원 81화
Skip: 모여라! 시튼 학원 82화
Skip: 모여라! 시튼 학원 83화
Skip: 모여라! 시튼 학원 84화
Skip: 모여라! 시튼 학원 84.5화
Skip: 모여라! 시튼 학원 85화
Skip: 모여라! 시튼 학원 86화
Skip: 모여라! 시튼 학원 87화
stop
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721

Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 177, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721

Solve protection
【chrome】 load...
【chrome】 loaded
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 189, in read
File "manamoa_downloader", line 177, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721

Solve protection
clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 815, in start
File "utils", line 865, in start_
File "manamoa_downloader", line 194, in read
File "manamoa_downloader", line 182, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721

Solve protection
clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 815, in start
File "utils", line 865, in start_
File "manamoa_downloader", line 194, in read
File "manamoa_downloader", line 182, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=721

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kimch0612** [comment]
> 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

링크에 들어가보니 소스 코드만 있고 프로그램은 없는 것 같습니다
확인 부탁드릴께요

**Comment by KurtBestor** [comment]
고쳤어요. 다시 다운로드 해주세요.

**Comment by kimch0612** [comment]
잘 되네요 감사합니다
추가로 궁금한게 있는데요,
프로그램에서 옵션 탭을 보면 클립보드에서 자동 추가라는 기능이 있잖습니까?
저는 이것을 마나모아랑 픽시브만 추가해서 쓰고 있는데, 프로그램을 껐다 켜면 계속 기본 값으로 리셋이 되더라고요
이게 정상인가요? 아니면 버그인가요?

**Comment by KurtBestor** [comment]
아직 구현되지 않은 기능이에요.

**Comment by kimch0612** [comment]
네 감사합니다
