### ISSUE TITLE
유튜브-사운드클라우드 오류

### ISSUE THREAD

**Issue by dlehdrjs0606** [KurtBestor/Hitomi-Downloader#1795]
유튜브는 변환중이라고 나오고
사운드클라우드는
Invalid: [soundcloud] https://soundcloud.com / waraku / feat-kang-borah

version: 2.7h (20-03-17 20:59:36 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://soundcloud.com/waraku/feat-kang-borah
dir: 
zip: 
type: soundcloud
artist: None
url: https://soundcloud.com/waraku/feat-kang-borah
valid: False
done: True
range: None
range_p: None
single: True
time: 1584592952.27 (Mar 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "downloader", line 313, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 360, in connect
File "site-packages\urllib3\util\ssl_", line 370, in ssl_wrap_socket
File "site-packages\urllib3\contrib\pyopenssl", line 491, in wrap_socket
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

Traceback (most recent call last):
File "downloader", line 313, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 360, in connect
File "site-packages\urllib3\util\ssl_", line 370, in ssl_wrap_socket
File "site-packages\urllib3\contrib\pyopenssl", line 491, in wrap_socket
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

fuckkk...
Traceback (most recent call last):
File "constants", line 668, in wrapper
File "soundcloud_downloader", line 165, in get_audios
File "downloader", line 383, in read_html
Exception: 403

stop
Traceback (most recent call last):
File "utils", line 815, in start
File "utils", line 865, in start_
File "soundcloud_downloader", line 109, in read
File "constants", line 695, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 668, in wrapper
File "soundcloud_downloader", line 165, in get_audios
File "downloader", line 383, in read_html
Exception: 403

Invalid: fail=True
EOT: https://soundcloud.com/waraku/feat-kang-borah
이렇게 나오네요

**Comment by KurtBestor** [comment]
유튜브는 변환될 때 까지 기다리시고, Soundcloud 는 다음 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1787
