### ISSUE TITLE
폰허브 다운이 안됩니다

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#1800]
Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph5df0a5f215451

version: 2.7h
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5df0a5f215451
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5df0a5f215451
valid: False
done: True
range: None
range_p: None
single: True
time: 1584722981.38 (Mar 21)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 2663, in wrapper
File "pornhub_downloader", line 253, in get_video
File "downloader", line 288, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 350, in connect
File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "pornhub_downloader", line 142, in read
File "constants", line 2690, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 2663, in wrapper
File "pornhub_downloader", line 253, in get_video
File "downloader", line 288, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 350, in connect
File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5df0a5f215451

**Comment by Sulwolhwa** [comment]
Invalid: [xhamster] https://xhamster.desi / videos / touhou-miku-r18-3d-mmd-gentleman-sex-dance-13550043

version: 2.7h
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://xhamster.desi/videos/touhou-miku-r18-3d-mmd-gentleman-sex-dance-13550043
dir: 
zip: 
type: xhamster
artist: None
url: https://xhamster.com/videos/touhou-miku-r18-3d-mmd-gentleman-sex-dance-13550043
valid: False
done: True
range: None
range_p: None
single: True
time: 1584723202.86 (Mar 21)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
ERROR: Unable to download webpage: <urlopen error [Errno 10054] > (caused by URLError(error(10054, ''),))
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "xhamster_downloader", line 53, in read
File "xhamster_downloader", line 85, in get_imgs
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 14, in report_error
DownloadError: ERROR: Unable to download webpage: <urlopen error [Errno 10054] > (caused by URLError(error(10054, ''),))

Invalid: fail=True
EOT: https://xhamster.desi/videos/touhou-miku-r18-3d-mmd-gentleman-sex-dance-13550043

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `DPI 우회` 를 켜세요.
