### ISSUE TITLE
마나모아 다운이 안됩니다

### ISSUE THREAD

**Issue by grapite** [KurtBestor/Hitomi-Downloader#1813]
컴퓨터 새걸로 바꾸고 나서 처음 시도하는데 안되네요
뭐가 문제인지 모르겠습니다

Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=4311

version: 2.7h (20-03-18 08:04:05 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311
valid: False
done: True
range: None
range_p: None
single: False
time: 1585314600.06 (Mar 27)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
[redirect domain] https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311 -> /bbs/page.php?hid=manga_detail&manga_id=4311
[redirect domain] https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311 -> /bbs/page.php?hid=manga_detail&manga_id=4311
[redirect domain] https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311 -> /bbs/page.php?hid=manga_detail&manga_id=4311
[redirect domain] https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311 -> /bbs/page.php?hid=manga_detail&manga_id=4311
fuckkk...
Traceback (most recent call last):
File "constants", line 671, in wrapper
File "manamoa_downloader", line 245, in get_soup
File "manamoa_downloader", line 537, in read_html
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 516, in request
File "requests\sessions", line 459, in prepare_request
File "requests\models", line 314, in prepare
File "requests\models", line 388, in prepare_url
MissingSchema: Invalid URL '/bbs/page.php?hid=manga_detail&manga_id=4311': No schema supplied. Perhaps you meant http:///bbs/page.php?hid=manga_detail&manga_id=4311?

stop
Traceback (most recent call last):
File "utils", line 815, in start
File "utils", line 865, in start_
File "manamoa_downloader", line 195, in read
File "manamoa_downloader", line 182, in name
File "manamoa_downloader", line 166, in soup
File "constants", line 698, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 671, in wrapper
File "manamoa_downloader", line 245, in get_soup
File "manamoa_downloader", line 537, in read_html
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 516, in request
File "requests\sessions", line 459, in prepare_request
File "requests\models", line 314, in prepare
File "requests\models", line 388, in prepare_url
MissingSchema: Invalid URL '/bbs/page.php?hid=manga_detail&manga_id=4311': No schema supplied. Perhaps you meant http:///bbs/page.php?hid=manga_detail&manga_id=4311?

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4311

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by grapite** [comment]
여전히 안됩니다

**Comment by grapite** [comment]
여전히 안됩니다

**Comment by grapite** [comment]
여전히 안됩니다

**Comment by KurtBestor** [comment]
작업 정보 보여주세요.

**Comment by grapite** [comment]
Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=1042

version: 2.7h (20-03-27 13:09:13 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1042
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1042
valid: False
done: True
range: None
range_p: None
single: False
time: 1585319550.14 (Mar 27)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 61, in solve
Exception: clf Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "manamoa_downloader", line 193, in read
File "manamoa_downloader", line 180, in name
File "manamoa_downloader", line 164, in soup
File "<decorator-gen-45>", line 2, in get_soup
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 61, in solve
Exception: clf Timeout


Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1042

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `DPI 우회` 를 켜세요.

**Comment by grapite** [comment]
되네요
감사합니다
