### ISSUE TITLE
업데이트후 유튜브 mp3 다운후 썸네일 미첨가

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#1816]
![asdaw](https://user-images.githubusercontent.com/53850082/77809595-acef5d80-70d3-11ea-95a5-1c37f9da52a7.png)

해당 이미지를보면 좌우 영상노래는 업데이트전에 받은것이고 

가운데 mp3 는 업데이트후 받은 노래입니다.

썸네일이 안나오네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
Invalid: [youtube] https://www.youtube.com / watch?v=vK7ADfHdylo

version: 2.8 (20-03-31 14:09:57 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=vK7ADfHdylo
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=vK7ADfHdylo
valid: False
done: True
range: None
range_p: None
single: True
time: 1585675546.51 (Apr 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

No videos
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "youtube_downloader", line 390, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=vK7ADfHdylo

**Comment by KurtBestor** [comment]
로그인하지 않고 너무 많이 다운로드해서 그런데, 유튜브 로그인 쿠키 넣으면 해결될거예요.

**Comment by kenasis428** [comment]
유튜브 로그인 쿠키는 어떻게 넣나요 ? 유튜브 로그아웃후 재 로그인해도 안되요.

**Comment by kenasis428** [comment]
잘 작동합니다 컴퓨터 내에서의 썸네일 잘나오고 음원파일 전환시 앨범에 재목 잘들어가고 
그덕에 폰에 도 각각 썸네일이 앨범 커버로 잘나옵니다.
