### ISSUE TITLE
폰허브 다운로드가 정상적으로 진행되지않습니다

### ISSUE THREAD

**Issue by as197543** [KurtBestor/Hitomi-Downloader#1832]
폰허브 다운로드가 정상적으로 진행되지않습니다
Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph58a733d0ea56a

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
valid: False
done: True
range: None
range_p: None
single: True
time: 1585487102.8 (Mar 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph58a733d0ea56a

Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5859958f2590d

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
valid: False
done: True
range: None
range_p: None
single: True
time: 1585486821.89 (Mar 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5859958f2590d

**Comment by KurtBestor** [comment]
참고해주세요: #1812
