### ISSUE TITLE
bdsmlr.com 문제

### ISSUE THREAD

**Issue by qweojfgd** [KurtBestor/Hitomi-Downloader#1862]
아직 텍스트 밖에 지원 안하는 건가요??

Invalid: [bdsmlr] https://masterol.bdsmlr.com / 

version: 2.8 (20-04-02 19:08:09 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://masterol.bdsmlr.com/
dir: 
zip: 
type: bdsmlr
artist: None
url: https://masterol.bdsmlr.com
valid: False
done: True
range: None
range_p: None
single: False
time: 1586078595.86 (Apr 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 685, in wrapper
File "bdsmlr_downloader", line 85, in get_imgs
AttributeError: 'NoneType' object has no attribute 'text'

stop
Traceback (most recent call last):
File "utils", line 869, in start
File "utils", line 919, in start_
File "bdsmlr_downloader", line 39, in read
File "<decorator-gen-59>", line 2, in get_imgs
File "constants", line 712, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 685, in wrapper
File "bdsmlr_downloader", line 85, in get_imgs
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://masterol.bdsmlr.com/

**Comment by KurtBestor** [comment]
고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
로그인이 필요한 블로그는 쿠키 넣어서 다운로드 할 수 있어요.
해당 블로그에서 직접 올리지 않고 reblog 한 포스트들은 다운로드하지 않아요.
해당 블로그는 reblog 인 포스트 밖에 없는 것 같아요.

**Comment by qweojfgd** [comment]
감사합니다. 아주 잘 됨.
