### ISSUE TITLE
porncomic 다운로드가 안됩니다

### ISSUE THREAD

**Issue by pink0258** [KurtBestor/Hitomi-Downloader#1865]
Invalid: [porncomix] https://www.porncomixonline.net / manga / dirtycomics-moose-the-big-gang-bang-theory-2 / 

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 13
group: False
gal_num: https://www.porncomixonline.net/manga/dirtycomics-moose-the-big-gang-bang-theory-2/
dir: 
zip: 
type: porncomix
artist: None
url: https://www.porncomixonline.net/manga/dirtycomics-moose-the-big-gang-bang-theory-2/?style=list
valid: False
done: True
range: None
range_p: None
single: False
time: 1586168721.26 (Apr 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "dynamic_module_2", line 83, in get_imgs
NotImplementedError: ???

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "dynamic_module_2", line 49, in read
File "<decorator-gen-70>", line 2, in get_imgs
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "dynamic_module_2", line 83, in get_imgs
NotImplementedError: ???

Invalid: fail=True
EOT: https://www.porncomixonline.net/manga/dirtycomics-moose-the-big-gang-bang-theory-2/

fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "dynamic_module_4", line 83, in get_imgs
NotImplementedError: ???

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "dynamic_module_4", line 49, in read
File "<decorator-gen-71>", line 2, in get_imgs
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "dynamic_module_4", line 83, in get_imgs
NotImplementedError: ???

Invalid: fail=True
EOT: https://www.porncomixonline.net/manga/dirtycomics-moose-the-big-gang-bang-theory-2/

![인베일드](https://user-images.githubusercontent.com/58359066/78549629-a5e7ee00-783d-11ea-9c97-4fb7ea35afeb.PNG)

**Comment by KurtBestor** [comment]
다음과 같이 입력해야해요: https://www.porncomixonline.net/manga/dirtycomics-moose-the-big-gang-bang-theory-2/dirtycomics-moose-the-big-gang-bang-theory-2

**Comment by pink0258** [comment]
아 제목을 한번 더 입력해야하는군요! 감사합니다!

**Comment by KurtBestor** [comment]
다음과 같이 개별 화 주소를 입력해주세요: https://www.porncomixonline.net/manga/dirtycomics-very-physical-education-issue-1-2/dirtycomics-very-physical-education-issue-1_1
