### ISSUE TITLE
Hanime 다운로드가 제대로 안됨

### ISSUE THREAD

**Issue by jjunleegood** [KurtBestor/Hitomi-Downloader#1883]
Hanime 다운로드를 하고 재생을 했는데 제대로 안되길래
로그인 쿠키 문제일까봐 cookie.txt 를 사용해서 불러오기를 하고 
다시 다운로드를 시도했지만 그대로여서 여기다가 올려봅니다.
( + 참고로 이 문제는 Hanime 의 모든 영상에서 일어나는 문제임 )

[ 문제 사항 ]
1. 영상 파일이 원본에 비해서 약간 뻥튀기가 됨 ex) 원본 : 324MB / 다운로드 후 : 376MB
2. 다운로드 작업이 되긴 하지만 파일이 제대로 다운이 되지 않은 듯함.
( 파일은 제대로 있지만 영상을 실행해보면 재생이 안됨. )

[ 로그 ]
[Pink Pineapple] Baku Ane Otouto Shibocchau zo! 1

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://members.hanime.tv/videos/hentai/baku-ane-otouto-shibocchau-zo-the-animation-1
dir: hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://members.hanime.tv/videos/hentai/baku-ane-otouto-shibocchau-zo-the-animation-1
valid: True
done: True
range: None
range_p: None
single: True
time: 1586590052.33 (Apr 11)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_hanime\[Pink Pineapple] Baku Ane Otouto Shibocchau zo! 1.mp4

[URLs]
[0001] M3u8_stream(https://hanime.tv/api/v1/m3u8s/29615.m3u8)

[Messages]

Fail : https://pay.uhnnu.top/0/3/1/2/v1x/segs/6L3UC/2/MaVKS5aU8v9NJqAVTwB27E3P.html
Traceback (most recent call last):
File "downloader", line 819, in download
Exception: 403

Fail : https://pay.uhnnu.top/0/3/1/2/v1x/segs/6L3UC/2/YDj0WRViZwH26vCMbOivDR26.html
Traceback (most recent call last):
File "downloader", line 860, in download
File "downloader", line 854, in Stream
File "socket", line 384, in read
File "httplib", line 583, in read
File "httplib", line 652, in _read_chunked
File "httplib", line 698, in _safe_read
File "socket", line 384, in read
File "ssl", line 754, in recv
File "ssl", line 641, in read
SSLError: ('The read operation timed out',)

Fail : https://pay.uhnnu.top/0/3/1/2/v1x/segs/6L3UC/2/fjCUxineUrRzSjK3D5ioZnZg.html
Traceback (most recent call last):
File "downloader", line 860, in download
File "downloader", line 854, in Stream
File "socket", line 384, in read
File "httplib", line 583, in read
File "httplib", line 656, in _read_chunked
File "httplib", line 698, in _safe_read
File "socket", line 384, in read
File "ssl", line 754, in recv
File "ssl", line 641, in read
SSLError: ('The read operation timed out',)

Fail : https://pay.uhnnu.top/0/3/1/2/v1x/segs/6L3UC/2/UQn8cB62f8nMRIHcJWvLsXdT.html
Traceback (most recent call last):
File "downloader", line 860, in download
File "downloader", line 854, in Stream
File "socket", line 384, in read
File "httplib", line 583, in read
File "httplib", line 625, in _read_chunked
File "socket", line 480, in readline
File "ssl", line 754, in recv
File "ssl", line 641, in read
SSLError: ('The read operation timed out',)

stop
EOT: https://members.hanime.tv/videos/hentai/baku-ane-otouto-shibocchau-zo-the-animation-1

**Comment by KurtBestor** [comment]
해당 파일 보내주시면 분석해볼게요.

**Comment by jjunleegood** [comment]
일단 여기다가 바로 올릴 수는 없어서 메가 드라이브 거쳐서 올려드릴게요

**Comment by jjunleegood** [comment]
https://mega.nz/file/zIsknCTJ#b7vjyzG8ntXJefSNHNjmZBQd40Qx1jTXckWIEW-bPoY
여기 해당 파일 (메가) 링크 입니다

**Comment by KurtBestor** [comment]
저는 제대로 보이는데, 어떤 동영상 플레이어 쓰시나요?

**Comment by jjunleegood** [comment]
윈도우 10에서 기본적으로 제공하는 플레이어 사용했는데
혹시 몰라서 다음 팟플레이어로 재생해보니까 정상적으로 보이네요.
번거롭게 해드려서 죄송합니다
