### ISSUE TITLE
감사합니다.

### ISSUE THREAD

**Issue by sfdaglkmerkg** [KurtBestor/Hitomi-Downloader#1888]
감사합니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by ckdwhrudwp0005** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)

version: 2.8 (20-04-04 05:35:08 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://e-hentai.org/g/1611931/ad1dbf457b/
dir: hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)
zip: 
type: ehen
artist: fumihiko
url: https://e-hentai.org/g/1611931/ad1dbf457b
valid: True
done: True
range: None
range_p: None
single: False
time: 1587432305.35 (Apr 21)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None


[Gallery]
갤러리 넘버: 1611931

제목: [Fantia] Fumihiko (ふみひこ)

작가: fumihiko

그룹: N/A

타입: imageset

시리즈: N/A

캐릭터: minato aqua, natsuiro matsuri, shirakami fubuki

태그: female:blowjob, female:masturbation, female:vtuber, houshou marine

언어: N/A


[File Names]
[0001] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_8823dd51_6e8a_4983_864d_eec7c8e93d77.jpg
[0002] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_39ee51d8_dd91_4afe_b3eb_85f50904294c.jpg
[0003] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_43a3a217_657c_47e7_8fca_7e78cc5c3ff2.jpg
[0004] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_06147b2a_ed5b_4303_9826_bf45da5b8fbe.jpg
[0005] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_3a9a071f_a47d_4d5c_b126_577ae76ac270.jpg
[0006] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_be5b897b_ecc9_4b6d_b424_584d182db11a.jpg
[0007] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_f607a7e2_2c9c_487c_a9c9_bdde19a8a2ea.jpg
[0008] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_9f205c0c_07cf_4312_b59c_72dcab161d88.jpg
[0009] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_c7d5de06_9c41_48f3_bc58_aebb57bbda97.jpg
[0010] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_c01a85ba_e3af_4eb4_b2de_3e19013d5fa7.jpg
[0011] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_c3ff1580_887d_422a_a1a3_3e184fda3398.jpg
[0012] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_d5f4e782_fe95_436b_b158_f0c6604377ca.jpg
[0013] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_b46e3963_15c0_4b42_a176_8300ffc43518.jpg
[0014] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_8014160f_6f07_4b4d_beb2_8bca67406019.jpg
[0015] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_41ebc182_12c6_403b_a855_154985d6b985.jpg
[0016] hitomi_downloaded\(1611931)[Fumihiko][N／A][N／A] [Fantia] Fumihiko (ふみひこ)\main_0bca279a_0475_41aa_9c64_650abb54db94.jpg


[URLs]
[0001] https://e-hentai.org/s/6fb9482c08/1611931-1 ---> https://ogrnran.ojggebytwrlb.hath.network/h/6fb9482c0892ba9a07a5b74507781dc3aaab847b-174208-800-1132-jpg/keystamp=1587432900-50a5a8f59f;fileindex=79183033;xres=org/main_8823dd51_6e8a_4983_864d_eec7c8e93d77.jpg
[0002] https://e-hentai.org/s/6b323da2e5/1611931-2 ---> https://iyrgnop.mibkimymhekr.hath.network:13659/h/6b323da2e5a8cc30cc9b70d611f9ec89d7420e91-179586-800-1132-jpg/keystamp=1587432900-a48faef2d1;fileindex=79183031;xres=org/main_39ee51d8_dd91_4afe_b3eb_85f50904294c.jpg
[0003] https://e-hentai.org/s/2f8ba3a020/1611931-3 ---> https://kkjdjgu.mhumvqewyohf.hath.network:51815/h/2f8ba3a020c5b02f94b3edf5e5e0bcf3647faf2c-129384-800-1132-jpg/keystamp=1587432900-8fbf1f5655;fileindex=79183032;xres=org/main_43a3a217_657c_47e7_8fca_7e78cc5c3ff2.jpg
[0004] https://e-hentai.org/s/2861c4897b/1611931-4 ---> https://fylrrrw.qubvnuultryo.hath.network/h/2861c4897bcf8147521b263275f8d1663bde2a23-137893-800-1132-jpg/keystamp=1587432900-c7be84a438;fileindex=79183054;xres=org/main_06147b2a_ed5b_4303_9826_bf45da5b8fbe.jpg
[0005] https://e-hentai.org/s/27185654a9/1611931-5 ---> https://rafxaga.ohtyqerxgboq.hath.network:48080/h/27185654a9604750995f56bc2c39a5a1f8b0d045-153845-800-1132-jpg/keystamp=1587432900-e4c786c0bd;fileindex=79183066;xres=org/main_3a9a071f_a47d_4d5c_b126_577ae76ac270.jpg
[0006] https://e-hentai.org/s/deec1c5f4b/1611931-6 ---> https://setcdjt.mibkimymhekr.hath.network/h/deec1c5f4b1ab6f8b93c56906ff0a0c81d31343a-159965-800-1132-jpg/keystamp=1587432900-f6dd86095e;fileindex=79183067;xres=org/main_be5b897b_ecc9_4b6d_b424_584d182db11a.jpg
[0007] https://e-hentai.org/s/35ebfbd1df/1611931-7 ---> https://fyycscc.gtpxtewbipib.hath.network/h/35ebfbd1dfa140a40ab79635ad4a6b4c6b79ca6d-150494-800-1132-jpg/keystamp=1587432900-e72c7b68e2;fileindex=79183068;xres=org/main_f607a7e2_2c9c_487c_a9c9_bdde19a8a2ea.jpg
[0008] https://e-hentai.org/s/23ac97c659/1611931-8 ---> https://xpjvnth.mibkimymhekr.hath.network/h/23ac97c65991764986fad65d241161ce48f29d26-188655-800-1132-jpg/keystamp=1587432900-83e9e5e7a5;fileindex=79183069;xres=org/main_9f205c0c_07cf_4312_b59c_72dcab161d88.jpg
[0009] https://e-hentai.org/s/55ad0c1d7c/1611931-9 ---> https://wfpwasv.gtpxtewbipib.hath.network/h/55ad0c1d7ce857b8675229b451f02320a7e08616-193073-800-1132-jpg/keystamp=1587432900-f7a294614f;fileindex=79183070;xres=org/main_c7d5de06_9c41_48f3_bc58_aebb57bbda97.jpg
[0010] https://e-hentai.org/s/aad57d64c2/1611931-10 ---> https://ukyfmyy.mibkimymhekr.hath.network/h/aad57d64c2364585c0c355e46ed415e02d9d0ef7-192860-800-1132-jpg/keystamp=1587432900-3b6881bed1;fileindex=79183071;xres=org/main_c01a85ba_e3af_4eb4_b2de_3e19013d5fa7.jpg
[0011] https://e-hentai.org/s/f0bf387fac/1611931-11 ---> https://iyrgnop.mibkimymhekr.hath.network:13659/h/f0bf387fac239c9c1a11a490ca97bf47992ebec7-187355-800-1132-jpg/keystamp=1587432900-7fcb70882d;fileindex=79183072;xres=org/main_c3ff1580_887d_422a_a1a3_3e184fda3398.jpg
[0012] https://e-hentai.org/s/b2fef02242/1611931-12 ---> https://rafxaga.ohtyqerxgboq.hath.network:48080/h/b2fef0224201c884b70b71fc009f9de8160648a3-153526-800-1132-jpg/keystamp=1587432900-9300ab6e82;fileindex=79183073;xres=org/main_d5f4e782_fe95_436b_b158_f0c6604377ca.jpg
[0013] https://e-hentai.org/s/65056ac4ac/1611931-13 ---> https://sttltyw.qubvnuultryo.hath.network/h/65056ac4ac9fac2465d1c561be7b56cbaca42d86-145673-800-1132-jpg/keystamp=1587432900-6a3907756b;fileindex=79183074;xres=org/main_b46e3963_15c0_4b42_a176_8300ffc43518.jpg
[0014] https://e-hentai.org/s/2abaafa835/1611931-14 ---> https://iyrgnop.mibkimymhekr.hath.network:13659/h/2abaafa835b93470b391362344f97bce2ea90b4e-146417-800-1132-jpg/keystamp=1587432900-0bb9cc1d49;fileindex=79183075;xres=org/main_8014160f_6f07_4b4d_beb2_8bca67406019.jpg
[0015] https://e-hentai.org/s/cd3bdce061/1611931-15 ---> https://wfpwasv.gtpxtewbipib.hath.network/h/cd3bdce06136f1ff18afdefdead898f23625b314-138844-800-1132-jpg/keystamp=1587432900-cfd513bf61;fileindex=79183076;xres=org/main_41ebc182_12c6_403b_a855_154985d6b985.jpg
[0016] https://e-hentai.org/s/6799ce81a8/1611931-16 ---> https://ukyfmyy.mibkimymhekr.hath.network/h/6799ce81a87d5d5dde4d56aa3be8d583604f6336-130081-800-1132-jpg/keystamp=1587432900-fd0f458ca9;fileindex=79183077;xres=org/main_0bca279a_0475_41aa_9c64_650abb54db94.jpg


[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/1611931/ad1dbf457b/)
using custom cookies
#### https://e-hentai.org/g/1611931/ad1dbf457b ----> https://e-hentai.org/g/1611931/ad1dbf457b
get_title_ehen: https://e-hentai.org/g/1611931/ad1dbf457b
FINAL SERVER: ehen
ehen_url: https://e-hentai.org/g/1611931/ad1dbf457b
imgs: 16
E-Hentai: https://e-hentai.org/g/1611931/ad1dbf457b

stop
EOT: https://e-hentai.org/g/1611931/ad1dbf457b/

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1074
