### ISSUE TITLE
iwara 영상 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by nasid117** [KurtBestor/Hitomi-Downloader#1924]
안녕하십니까. 좋은 프로그램 만들어주셔서 잘 사용하고 있습니다.

얼마 전부터 iwara 사이트에서 영상을 다운로드 받을 때 '읽는 중'에서 시간을 오래 끌더니
현재는 invalid가 뜨면서 모든 영상이 다운로드되지 않습니다.

어떻게 해결할 수 있는지 알려주신다면 고맙겠습니다. 

혹시 몰라 로그 하나 따왔습니다.
Invalid: [iwara] https://ecchi.iwara.tv / videos / 4lkmwsmqgkcyaxzw1?language=ja

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://ecchi.iwara.tv/videos/4lkmwsmqgkcyaxzw1?language=ja
dir: 
zip: 
type: iwara
artist: None
url: https://ecchi.iwara.tv/videos/4lkmwsmqgkcyaxzw1?language=ja
valid: False
done: False
range: None
range_p: None
single: True
time: 1587910716.47 (Apr 26)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
type: video
('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "iwara_downloader", line 52, in read
File "iwara_downloader", line 106, in get_files
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 412, in _make_request
File "httplib", line 1148, in getresponse
File "httplib", line 448, in begin
File "httplib", line 412, in _read_status
ProtocolError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

Invalid: fail=True

**Comment by KurtBestor** [comment]
설정에서 DPI 우회를 켜세요.

**Comment by nasid117** [comment]
DPI 우회를 켜도 그대로입니다.

**Comment by KurtBestor** [comment]
DPI 우회 킨 다음 다시 시도 해보고 에러 뜨는 작업 정보 보여주세요.

**Comment by nasid117** [comment]
Invalid: [iwara] https://ecchi.iwara.tv / videos / 4lkmwsmqgkcyaxzw1

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://ecchi.iwara.tv/videos/4lkmwsmqgkcyaxzw1
dir: 
zip: 
type: iwara
artist: None
url: https://ecchi.iwara.tv/videos/4lkmwsmqgkcyaxzw1
valid: False
done: False
range: None
range_p: None
single: True
time: 1588158719.81 (Apr 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
type: video
('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "iwara_downloader", line 52, in read
File "iwara_downloader", line 106, in get_files
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 412, in _make_request
File "httplib", line 1148, in getresponse
File "httplib", line 448, in begin
File "httplib", line 412, in _read_status
ProtocolError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

Invalid: fail=True

에러 로그입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by nasid117** [comment]
테크니컬 프리뷰에서도 오류가 납니다.

Invalid: [iwara] https://ecchi.iwara.tv / videos / 4lkmwsmqgkcyaxzw1

version: 2.8 (20-04-29 11:10:31 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://ecchi.iwara.tv/videos/4lkmwsmqgkcyaxzw1
dir: 
zip: 
type: iwara
artist: None
url: https://ecchi.iwara.tv/videos/4lkmwsmqgkcyaxzw1
valid: False
done: False
range: None
range_p: None
single: True
time: 1588174578.02 (Apr 30)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
type: video
('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
stop
Traceback (most recent call last):
File "utils", line 873, in start
File "utils", line 923, in start_
File "iwara_downloader", line 48, in read
File "iwara_downloader", line 103, in get_files
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 412, in _make_request
File "httplib", line 1148, in getresponse
File "httplib", line 448, in begin
File "httplib", line 412, in _read_status
ProtocolError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

Invalid: fail=True

**Comment by KurtBestor** [comment]
사이트에서 직접 재생은 되나요?

**Comment by nasid117** [comment]
네 직접 재생은 가능합니다

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by nasid117** [comment]
아 이제 잘 됩니다.
감사합니다
