### ISSUE TITLE
最近2天 hitomi.la这个网站无法下载

### ISSUE THREAD

**Issue by Mangel1986** [KurtBestor/Hitomi-Downloader#1935]
你好！ 非常感谢这个工具带来的便捷！ 最近2天 hitomi.la这个网站无法下载！
안녕하세요.이 도 구 를 편리 하 게 가 져 다 주 셔 서 감사합니다!최근 이틀 간 의 hitomi. la 는 이 사 이 트 를 다운로드 할 수 없습니다!

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by Mangel1986** [comment]
读取中... https://hitomi.la / galleries / 1622206.html

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://hitomi.la/galleries/1622206.html
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/1622206.html
valid: True
done: False
range: None
range_p: None
single: False
time: 1588266802.03 (May 1)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None


[Gallery]
None

**Comment by Mangel1986** [comment]
一直在滚动条 无法下载
[https://s1.ax1x.com/2020/05/01/JLvWdI.jpg](url)

**Comment by Mangel1986** [comment]
Invalid: [hitomi] https://hitomi.la / galleries / 1622206.html

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://hitomi.la/galleries/1622206.html
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/1622206.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1588266802.03 (May 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182C17904C8>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182D5BB0888>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182D5B2B888>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1622206.html)
Find_ehen(id:1622206, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
File "hitomi_downloader", line 932, in find_ehen
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182D5BB0308>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182D3ECFA08>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1622206.html)
Find_ehen(id:1622206, ex:True)
Find in HK...
not found in HK
max_page = 35933
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5.1
Brute-force search: 6.1
Brute-force search: 7.1
Brute-force search: 8.4
Brute-force search: 9.4
Brute-force search: 10.4
Brute-force search: 11.4
Brute-force search: 14.3
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182C1796908>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1622206.html)
Find_ehen(id:1622206, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
File "hitomi_downloader", line 932, in find_ehen
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182C17F33C8>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182D5BC3B48>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1622206.html)
Find_ehen(id:1622206, ex:True)
Find in HK...
not found in HK
max_page = 35933
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4.1
Brute-force search: 5.1
Brute-force search: 6.2
Brute-force search: 7.3
Brute-force search: 8.6
Brute-force search: 9.6
Brute-force search: 11.0
Brute-force search: 12.5
Brute-force search: 13.8
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182C1730C88>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1622206.html)
Find_ehen(id:1622206, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
File "hitomi_downloader", line 932, in find_ehen
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182C172A108>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 553, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000182C1790608>: Failed to establish a new connection: [Errno 10060] 

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1622206.html)
Find_ehen(id:1622206, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 682, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1028, in ehen_imgs
Exception: URL not found

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 741, in read
File "gallery", line 209, in get_gal
Exception: get_gal Invalid server: auto

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/galleries/1622206.html

**Comment by KurtBestor** [comment]
Where do you live? China? How do you access Hitomi.la?

**Comment by Mangel1986** [comment]
ShadowsocksR or VPN

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/1031#issuecomment-530310049

**Comment by Mangel1986** [comment]
아직 사용 할 수 없 지만 도 와 줘 서 고마워!
