### ISSUE TITLE
폰허브 다운이 안됩니다.

### ISSUE THREAD

**Issue by skauswd** [KurtBestor/Hitomi-Downloader#1941]
폰허브만 다운받으려하면 무한로딩이 걸리고 다운이 안되길래 테스트했더니 이렇게뜨고 dpi우회가 꺼지고 로딩되던게 invaild가 뜹니다.
![이미지 1](https://user-images.githubusercontent.com/64580488/80687078-b28df800-8b04-11ea-9b00-f70df0834b2f.png)
Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph5cb84de59b25d

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d
valid: False
done: True
range: None
range_p: None
single: True
time: 1588232084.42 (Apr 30)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 230, in get_video
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 514, in send
SSLError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5cb84de59b25d (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 230, in get_video
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 514, in send
SSLError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5cb84de59b25d (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d

fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 230, in get_video
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 516, in send
ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5cb84de59b25d (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6DCCD04C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 230, in get_video
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 516, in send
ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5cb84de59b25d (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6DCCD04C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1168, in Invalid
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1069, in request
File "httplib", line 1109, in _send_request
File "httplib", line 1065, in endheaders
File "httplib", line 892, in _send_output
File "httplib", line 854, in send
File "site-packages\urllib3\connection", line 184, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B6F07363C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

EOT: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d

fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 230, in get_video
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 516, in send
ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5cb84de59b25d (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6DFFA0C88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 230, in get_video
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 516, in send
ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5cb84de59b25d (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6DFFA0C88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1168, in Invalid
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1069, in request
File "httplib", line 1109, in _send_request
File "httplib", line 1065, in endheaders
File "httplib", line 892, in _send_output
File "httplib", line 854, in send
File "site-packages\urllib3\connection", line 184, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B6F0736B88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

EOT: https://www.pornhub.com/view_video.php?viewkey=ph5cb84de59b25d

**Comment by KurtBestor** [comment]
프로그램 여러개 켜면 원래 켜져있는 DPI 우회가 꺼져요.
`옵션` - `설정` - `고급` - `DPI 우회` 눌러서 켜 주세요.

참고해주세요: #1855
