### ISSUE TITLE
유튜브 다운로드가 정상적으로 되지않음.

### ISSUE THREAD

**Issue by collagen12** [KurtBestor/Hitomi-Downloader#1942]
![스크린샷 2020-04-30 오후 6 35 16](https://user-images.githubusercontent.com/58670693/80695846-757c3280-8b11-11ea-9af9-806cc7fc3088.jpg)

2.8v 이고 저렇게 뜨면서 다운로드가 안됨. 폴더열어봐도 아무것도 없음. ssyoutube나 다른 기존에 잘되던 유튜브 다운로드 소스들도 다 먹통된거보면 뭔가 수정한모양인데 ssyoutube는 되는것도 있고 안되는것도 있어서 헷갈림

https://www.youtube.com/watch?v=GhIa4gAhjWE 해당 유튜브링크

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by collagen12** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

Astronomia 2K19 (Radio Edit)

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=GhIa4gAhjWE
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: Stephan F - Topic
url: https://www.youtube.com/watch?v=GhIa4gAhjWE
valid: False
done: True
range: None
range_p: None
single: True
time: 1588239091.01 (Apr 30)
tags: []
goodbyedpi: False
lock: False
color: invalid_done
paused: False
format: mp4
p2f: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\Astronomia 2K19 (Radio Edit).mp4


[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=GhIa4gAhjWE) ---> https://r2---sn-ixaav8pnpvo-pjos.googlevideo.com/videoplayback?expire=1588260691&ei=85qqXt7fHrycs8IPtcmPsAk&ip=1.176.245.194&id=o-ANQBEGys4w0SxPaHh2oq799SmPtvRNdjx2i3p6NquRgZ&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=oW&mm=31%2C29&mn=sn-ixaav8pnpvo-pjos%2Csn-ogueln7y&ms=au%2Crdu&mv=m&mvi=1&pl=22&gcr=kr&initcwndbps=968750&vprv=1&mime=video%2Fmp4&gir=yes&clen=3752353&dur=190.480&lmt=1587728623611432&mt=1588238968&fvip=2&keepalive=yes&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgWtv_pd95UdneeGH29SwkxKXtlIQdSlNqIzarysMpH_YCIQC054POnPhFi_dO15ezGcFpe96U894HzjNidFRBtzvwWQ%3D%3D&sig=AJpPlLswRAIgXy58P5lYlZXOe2CSSwCqhNLkUTn0zyCSta8_mS1lh7oCID8Aml6S9vu--_5RjyI5AjQfjm2AY-LibCCzRRK5rbhs&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][25fps][None] webm None ─ 278 - 144x144 (144p)
[144p][25fps][None] mp4 None ─ 160 - 144x144 (144p)
[240p][25fps][None] mp4 None ─ 133 - 240x240 (240p)
[240p][25fps][None] webm None ─ 242 - 240x240 (240p)
[360p][25fps][None] webm None ─ 243 - 360x360 (360p)
[360p][25fps][None] mp4 None ─ 134 - 360x360 (360p)
[480p][25fps][None] webm None ─ 244 - 480x480 (480p)
[480p][25fps][None] mp4 None ─ 135 - 480x480 (480p)
[720p][25fps][None] mp4 None ─ 136 - 720x720 (720p)
[720p][25fps][None] webm None ─ 247 - 720x720 (720p)
[1080p][25fps][None] mp4 None ─ 137 - 1080x1080 (1080p)
[1080p][25fps][None] webm None ─ 248 - 1080x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 360x360 (360p)


# stream_final <youtube_dl_test.Video object at 0x00000276333DF708> 137 - 1080x1080 (1080p) 1080p mp4 None 25fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 360x360 (360p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 360x360 (360p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

Resolution: None
Codec: None / mp4a.40.2
Abr: 128kbps
Subtype: m4a
FPS: 0

Download audio: https://r2---sn-ixaav8pnpvo-pjos.googlevideo.com/videoplayback?expire=1588260691&ei=85qqXt7fHrycs8IPtcmPsAk&ip=1.176.245.194&id=o-ANQBEGys4w0SxPaHh2oq799SmPtvRNdjx2i3p6NquRgZ&itag=140&source=youtube&requiressl=yes&mh=oW&mm=31%2C29&mn=sn-ixaav8pnpvo-pjos%2Csn-ogueln7y&ms=au%2Crdu&mv=m&mvi=1&pl=22&gcr=kr&initcwndbps=968750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3084671&dur=190.486&lmt=1587728617733710&mt=1588238968&fvip=2&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgWtv_pd95UdneeGH29SwkxKXtlIQdSlNqIzarysMpH_YCIQC054POnPhFi_dO15ezGcFpe96U894HzjNidFRBtzvwWQ%3D%3D&sig=AJpPlLswRQIhAJXZhRwkkc7BYK60paU4j7qcvabJdD2zfx6c7WM-YUaTAiAtEM-ZhXGjT8k-H223LEWFNAKld6OnIkR9aCxrcsuyoQ==&ratebypass=yes
Convert: \\Mac\Home\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\Astronomia 2K19 (Radio Edit).mp4
rename (1): hitomi_downloaded_youtube\C9FAD531_a.tmp -> \\Mac\Home\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp524265A9_a.weba
rename (1): \\Mac\Home\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\Astronomia 2K19 (Radio Edit).mp4 -> \\Mac\Home\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp524265A9_v.mp4
-i tmp524265A9_v.mp4 -i tmp524265A9_a.weba -c copy -strict experimental -preset ultrafast tmp524265A9_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
1
[out]
'\\Mac\Home\DOWN~MO0\HITO~GX4\HITO~L95'
위의 경로를 현재 디렉터리로 하여 CMD.EXE가 실행되었습니다. UNC 경로는
지원되지 않습니다. Windows 디렉터리를 기본으로 합니다.
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
tmp524265A9_v.mp4: No such file or directory

Lazyurl pp Error: hitomi_downloaded_youtube\Astronomia 2K19 (Radio Edit).mp4
Traceback (most recent call last):
File "hitomi_downloader", line 360, in run
File "youtube_downloader", line 257, in pp
File "youtube_downloader", line 283, in _pp
File "ffmpeg", line 173, in merge
Exception: Failed to convert; exit code: 1

stop
EOT: https://www.youtube.com/watch?v=GhIa4gAhjWE

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1909#issuecomment-622356037

**Comment by djffkfl365** [comment]
저랑 같은 문제에요 ㅠㅠ
