### ISSUE TITLE
Problem when downloading from instagram

### ISSUE THREAD

**Issue by Rocneriano** [KurtBestor/Hitomi-Downloader#1947]
It's been a few days since I've been able to download from instagram, when I finish reading the pages the download speed stays at 0.0kb/s and a few seconds later without having downloaded anything it stays as an incomplete task, it goes to the next task and so on.
I leave the information of the task in case it can help something, it's a bit long 

Anastasia Karanikolaou (insta_stassiebaby)

version: 2.7h (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 66
group: False
gal_num: https://www.instagram.com/stassiebaby/
dir: hitomi_downloaded_insta\Anastasia Karanikolaou (insta_stassiebaby)
zip: 
type: insta
artist: Anastasia Karanikolaou
url: https://www.instagram.com/stassiebaby
valid: False
done: True
range: None
range_p: None
single: False
time: 1588385223.43 (May 1)
tags: [u'red', u'orange', u'yellow', u'green', u'blue']
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
There were a lot of names here that I had to delete in order to post this

[URLs]
There were a lot of url's here that I had to erase in order to post this

[Messages]
failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

no media.. retry... (1) ['3c7ca9dcefcf966d11dacf1f151335e8']
failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

failed to get query... 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx:Mozilla/5.0 (X12; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

no media.. retry... (2) ['3c7ca9dcefcf966d11dacf1f151335e8', '', u'3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx', u'3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx:Mozilla/5.0 (X12; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36']
failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

no media.. retry... (1) ['3c7ca9dcefcf966d11dacf1f151335e8']
failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

failed to get query... 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx:Mozilla/5.0 (X12; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

no media.. retry... (2) ['3c7ca9dcefcf966d11dacf1f151335e8', '', u'3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx', u'3c7ca9dcefcf966d11dacf1f151335e8:MTgYJ6obLHv2ejIPDhxRp1tsulPtGkfx:Mozilla/5.0 (X12; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36']
failed to get query... 3c7ca9dcefcf966d11dacf1f151335e8 
Traceback (most recent call last):
File "insta_downloader", line 212, in get_urls
KeyError: 'data'

LazyUrl error (https://www.instagram.com/p/B_lBOnfjMkK/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 575, in __call__
File "insta_downloader", line 136, in f
File "insta_downloader", line 285, in __init__
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

LazyUrl error (https://www.instagram.com/p/B_ROZxclDcw/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 575, in __call__
File "insta_downloader", line 136, in f
File "insta_downloader", line 285, in __init__
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

LazyUrl error (https://www.instagram.com/p/B_iHjGajDV0/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 575, in __call__
File "insta_downloader", line 136, in f
File "insta_downloader", line 285, in __init__
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

LazyUrl error (https://www.instagram.com/p/B_dM8utDx_c/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 575, in __call__
File "insta_downloader", line 136, in f
File "insta_downloader", line 285, in __init__
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

(**There was more information I had to delete in order to post this, but the rest looked like this:**

LazyUrl error (https://www.instagram.com/p/B_gCzKijDij/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 575, in __call__
File "insta_downloader", line 136, in f
File "insta_downloader", line 285, in __init__
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded )

stop
valid=False 1
EOT: https://www.instagram.com/stassiebaby/

**Comment by KurtBestor** [comment]
How about this?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Rocneriano** [comment]
Thank you very much! It worked.
