### ISSUE TITLE
luscious 가 invalid 라고뜨면 다운이안됩니다

### ISSUE THREAD

**Issue by aaas1234** [KurtBestor/Hitomi-Downloader#1955]
프로그램은 잘모르고, 그 다른대에서 프로그래머가알려주신 Technical Preview 이란것도 다운해봤는데 안됩니다 그 Technical Preview 에서 소스집도 다운받고 해봤는데 이집은 어떡게 쓰는지 모르겠군요
아무튼 계속 invalid 라고만뜹니다 다른건 잘되는것 같은데 luscious 만안되는것 같네요 
어떡해야하나요 아님 Technical Preview에서 어떡해야 할지 알려주세요

**Comment by aaas1234** [comment]
Invalid: [luscious] https://members.luscious.net / albums / ryuus-world-of-warcraft_107966 / 

version: 2.8 (20-05-01 11:35:50 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://members.luscious.net/albums/ryuus-world-of-warcraft_107966/
dir: 
zip: 
type: luscious
artist: None
url: https://members.luscious.net/albums/ryuus-world-of-warcraft_107966/
valid: False
done: True
range: None
range_p: None
single: False
time: 1588621119.68 (May 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 873, in start
File "utils", line 923, in start_
File "luscious_downloader", line 62, in read
File "luscious_downloader", line 148, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://members.luscious.net/albums/ryuus-world-of-warcraft_107966/

**Comment by aaas1234** [comment]
이제보니 상당히 많은 사이트가 안되는것 같으나 일단 luscious 부터 고쳐주세요
