### ISSUE TITLE
사이트 추가 건의합니다

### ISSUE THREAD

**Issue by vicecity560** [KurtBestor/Hitomi-Downloader#1960]
https://bestjavporn.com/
가능하신지 여쭈어 봅니다 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by vicecity560** [comment]
감사합니다.
확인하였으며 1080p 까지 있는 영상이 360p로 다운로드 되는 현상이 있습니다 ㅠ

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by vicecity560** [comment]
JAV kawaii KAWD-942 Face-Fuckin Frenzy: Irrumatio Training Koharu Suzuki

version: 2.8 (20-05-14 06:17:14 GMT+0)
platform: Windows-10-10.0.18362
order: 2
group: False
input: https://bestjavporn.com/video/jav-kawaii-kawd-942-face-fuckin-frenzy-irrumatio-training-koharu-suzuki/?asgtbndr=1
dir: hitomi_downloaded_bestjavporn
zip: 
type: bestjavporn
artist: None
url: https://bestjavporn.com/video/jav-kawaii-kawd-942-face-fuckin-frenzy-irrumatio-training-koharu-suzuki/?asgtbndr=1
valid: True
done: True
range: None
range_p: None
single: True
time: 1589543172.47 (May 15)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_bestjavporn\JAV kawaii KAWD-942 Face-Fuckin Frenzy： Irrumatio Training Koharu Suzuki.mp4


[URLs]
[0001] LazyUrl(https://video.bestjavporn.com/player.php?playerid=PYc2VydmVyPWtpc3NqYXYmdXJsPWh0dHBzJTNBJTJGJTJGa2lzc2phdi5jb20lMkY1MjEzMyUyRg==) ---> https://video.bestjavporn.com/stream/?vid=TWYUhSMGNITTZMeTl0WldScFlUa3VhMmx6YzJwaGRpNWpiMjB2YldWa2FXRXZkbWxrWlc5ekwyMXdOQzgxTWpFek0xODBPREJ3TG0xd05EOXpkRDExVlZWQlZUQjJNVkpTZFVsYU5VbzBlR3BrV0dObkptVTlNVFU0T1RZeU9UVTNOdz09


[Messages]
[480p] video/mp4 //video.bestjavporn.com/stream/?vid=TWYUhSMGNITTZMeTl0WldScFlUa3VhMmx6YzJwaGRpNWpiMjB2YldWa2FXRXZkbWxrWlc5ekwyMXdOQzgxTWpFek0xODBPREJ3TG0xd05EOXpkRDExVlZWQlZUQjJNVkpTZFVsYU5VbzBlR3BrV0dObkptVTlNVFU0T1RZeU9UVTNOdz09
https://video.bestjavporn.com/stream/?vid=TWYUhSMGNITTZMeTl0WldScFlUa3VhMmx6YzJwaGRpNWpiMjB2YldWa2FXRXZkbWxrWlc5ekwyMXdOQzgxTWpFek0xODBPREJ3TG0xd05EOXpkRDExVlZWQlZUQjJNVkpTZFVsYU5VbzBlR3BrV0dObkptVTlNVFU0T1RZeU9UVTNOdz09 -> https://media9.kissjav.com/media/videos/mp4/52133_480p.mp4?st=uUUAU0v1RRuIZ5J4xjdXcg&e=1589629577
downloader_v3 fail... p[596 / 810]
Traceback (most recent call last):
File "downloader_v3", line 66, in run
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 665, in send
File "requests\sessions", line 245, in resolve_redirects
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

stop
EOT: https://bestjavporn.com/video/jav-kawaii-kawd-942-face-fuckin-frenzy-irrumatio-training-koharu-suzuki/?asgtbndr=1


입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by vicecity560** [comment]
감사합니다. 테스트 완료하였습니다.
정상으로 720p 출력 됩니다.
