### ISSUE TITLE
마나모아 다운로드가 안됩니다

### ISSUE THREAD

**Issue by manamoadownloader** [KurtBestor/Hitomi-Downloader#1971]
만화 업데이트 목록에서 어떤건 다운 가능한데 대부분은 다운이 안됩니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by manamoadownloader** [comment]
Invalid: [manamoa] https://manamoa36.net / bbs / page.php?hid=manga_detail&manga_id=14201

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 1
group: False
gal_num: https://manamoa36.net/bbs/page.php?hid=manga_detail&manga_id=14201
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa36.net/bbs/page.php?hid=manga_detail&manga_id=14201
valid: False
done: True
range: None
range_p: None
single: False
time: 1589258213.5 (May 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 61, in solve
Exception: clf Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "manamoa_downloader", line 193, in read
File "manamoa_downloader", line 180, in name
File "manamoa_downloader", line 164, in soup
File "<decorator-gen-45>", line 2, in get_soup
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 61, in solve
Exception: clf Timeout


Invalid: fail=True
EOT: https://manamoa36.net/bbs/page.php?hid=manga_detail&manga_id=14201

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1813#issuecomment-605038798
