### ISSUE TITLE
유튜브 연령제한 동영상이 안받아집니다

### ISSUE THREAD

**Issue by jkl1q2w3e4r** [KurtBestor/Hitomi-Downloader#1977]
항상 사용하면서 감사하게 생각하고 있습니다.

issue#1909보고 최신 테스트버전으로 해봤는데 안되네요.

그리고 저번에 연령제한 동영상 받았을때 4k화질로 설정해뒀는데도 연령제한 걸린것들은 720p로만 받아지던데 연령제한 동영상은 원본 받을 수 없나요?
영상도 1440였습니다.

Invalid: [youtube] https://www.youtube.com / watch?v=HcWuNqPKEvo

version: 2.8 (20-05-14 06:17:14 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.youtube.com/watch?v=HcWuNqPKEvo
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=HcWuNqPKEvo
valid: False
done: True
range: None
range_p: None
single: True
time: 1589459661.61 (May 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

No videos
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=HcWuNqPKEvo

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/82900948-34ecc900-9f98-11ea-9d06-c7058fdd57cc.png)

로그인 쿠키 없어도 다운로드 돼요. 제 쪽에선 재현할 수가 없네요.
