### ISSUE TITLE
itmtu.net 다운로드 방법을 모르겠습니다

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader#1983]
안녕하세요
다운로더 정말 유용하게 사용하고 있습니다 감사합니다

http://www.itmtu.net/mm/66774/
여기를 다운로드 받으려고 보면

Invalid: [itmtu] http://www.itmtu.net / mm / 66774 / 

version: 2.8 (20-05-01 11:35:50 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: http://www.itmtu.net/mm/66774/
dir: 
zip: 
type: itmtu
artist: None
url: http://www.itmtu.net/mm/66774/
valid: False
done: True
range: None
range_p: None
single: False
time: 1589581717.63 (May 16)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
<urllib3.connection.HTTPConnection object at 0x0000023E555C7088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
stop
Traceback (most recent call last):
File "utils", line 873, in start
File "utils", line 923, in start_
File "itmtu_downloader", line 22, in read
File "itmtu_downloader", line 41, in get_info
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1069, in request
File "httplib", line 1109, in _send_request
File "httplib", line 1065, in endheaders
File "httplib", line 892, in _send_output
File "httplib", line 854, in send
File "site-packages\urllib3\connection", line 184, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023E555C7088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

Invalid: fail=True
EOT: http://www.itmtu.net/mm/66774/

요렇게 뜨고 실패하네요

저 주소를 넣는게 아닌건지..
다른 페이지도 마찬가지네요ㅠㅠ

로그인한 쿠키 넣었습니다

그리고 혹시 아래 사이트도 지원가능할까요?
https://www.porn.biz/

**Comment by Kagurazaka-Kizome** [comment]
I also face the same problem (나는 또한 같은 문제에 직면했다)

Invalid: [itmtu] http://www.itmtu.net / mm / 88088 / 

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: http://www.itmtu.net/mm/88088/
dir: 
zip: 
type: itmtu
artist: None
url: http://www.itmtu.net/mm/88088/
valid: False
done: True
range: None
range_p: None
single: False
time: 1589774062.13 (May 18)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
<urllib3.connection.HTTPConnection object at 0x000001AA919508C8>: Failed to establish a new connection: [Errno 10060] 
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "itmtu_downloader", line 23, in read
File "itmtu_downloader", line 42, in get_info
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1069, in request
File "httplib", line 1109, in _send_request
File "httplib", line 1065, in endheaders
File "httplib", line 892, in _send_output
File "httplib", line 854, in send
File "site-packages\urllib3\connection", line 184, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001AA919508C8>: Failed to establish a new connection: [Errno 10060] 

Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1168, in Invalid
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 412, in _make_request
File "httplib", line 1148, in getresponse
File "httplib", line 448, in begin
File "httplib", line 404, in _read_status
File "socket", line 480, in readline
ProtocolError: ('Connection aborted.', error(10054, ''))

EOT: http://www.itmtu.net/mm/88088/

<urllib3.connection.HTTPConnection object at 0x000001AAFEF83708>: Failed to establish a new connection: [Errno 10060] 
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "itmtu_downloader", line 23, in read
File "itmtu_downloader", line 42, in get_info
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 387, in _make_request
File "httplib", line 1069, in request
File "httplib", line 1109, in _send_request
File "httplib", line 1065, in endheaders
File "httplib", line 892, in _send_output
File "httplib", line 854, in send
File "site-packages\urllib3\connection", line 184, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001AAFEF83708>: Failed to establish a new connection: [Errno 10060] 

Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1168, in Invalid
File "downloader", line 315, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 412, in _make_request
File "httplib", line 1148, in getresponse
File "httplib", line 448, in begin
File "httplib", line 404, in _read_status
File "socket", line 480, in readline
ProtocolError: ('Connection aborted.', error(10054, ''))

EOT: http://www.itmtu.net/mm/88088/

**Comment by KurtBestor** [comment]
지금도 안 되나요?
