### ISSUE TITLE
툰코리아 다운로드 실패 문의 (스크립트 수정했음에도...)

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#1996]
개발자님 안녕하세요. 항상 잘 이용하고 있어 정말 감사드립니다.

다름이 아니라, 이번에 툰코리아을 이용하는 중 문제가 생겨 문의드립니다.

스크립트 메모장으로 열어서 toonkorea 라고 써진 것 전부 tkor로 바꾸니까 다른 것들은 정상적으로 다운이 됐는데, 특정 페이지에 대해서만 다운로드가 자꾸 실패하더라구요.

https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80
https://tkor.fun/%EC%9A%B0%EB%A6%AC%EC%82%AC%EC%9D%B4%EB%8A%90%EC%9D%80
https://tkor.fun/%ED%9C%B4%EC%A7%80%EB%8F%84%EB%91%91

위 세 링크는 자꾸 invalid 표시가 뜨면서 다운로드가 실패하는데, 뭐가 원인인지 알 수 있을까요?

우클릭>정보에 나온 내용도 같이 첨부합니다.

Invalid: [tkor] https://tkor.fun / %EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

version: 2.8 (20-05-13 08:38:11 GMT+0)
platform: Windows-10-10.0.18362
order: 3
group: False
input: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80
dir: 
zip: 
type: tkor
artist: None
url: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80
valid: False
done: True
range: ~100000
range_p: None
single: False
time: 1590229723.84 (May 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

stop
Traceback (most recent call last):
File "utils", line 897, in start
File "utils", line 956, in start_
File "dynamic_module_1", line 53, in read
File "dynamic_module_1", line 120, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 774, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

Invalid: fail=True
EOT: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

stop
Traceback (most recent call last):
File "utils", line 897, in start
File "utils", line 956, in start_
File "dynamic_module_1", line 53, in read
File "dynamic_module_1", line 120, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 774, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

Invalid: fail=True
EOT: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

stop
Traceback (most recent call last):
File "utils", line 897, in start
File "utils", line 956, in start_
File "dynamic_module_1", line 53, in read
File "dynamic_module_1", line 120, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 774, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

Invalid: fail=True
EOT: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

stop
Traceback (most recent call last):
File "utils", line 897, in start
File "utils", line 956, in start_
File "dynamic_module_1", line 53, in read
File "dynamic_module_1", line 120, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 774, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

Invalid: fail=True
EOT: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

stop
Traceback (most recent call last):
File "utils", line 897, in start
File "utils", line 956, in start_
File "dynamic_module_1", line 53, in read
File "dynamic_module_1", line 120, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 774, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

Invalid: fail=True
EOT: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

stop
Traceback (most recent call last):
File "utils", line 897, in start
File "utils", line 956, in start_
File "dynamic_module_1", line 53, in read
File "dynamic_module_1", line 120, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 774, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 747, in wrapper
File "dynamic_module_1", line 74, in get_imgs_page
File "base64", line 328, in decodestring
TypeError: a2b_base64() argument 1 must be string or buffer, not None

Invalid: fail=True
EOT: https://tkor.fun/%EC%98%86%EC%A7%91%EC%86%8C%EB%85%80

**Comment by bhfaker** [comment]
아 그리고 툰코리아 다운 시, 다운로더 설정과는 별개로 무조건 [작가명] 제목 이렇게 폴더명이 만들어지던데, 혹시 작가명을 빼고 제목만 나오게 할 순 없나요? 스크립트에서 수정할 수 있나요?

**Comment by KurtBestor** [comment]
고쳤어요. 다시 다운로드 해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

`clean_title(u'[{}] {}'.format(artist, title))` 을 `clean_title(title)` 로 바꾸세요.

**Comment by bhfaker** [comment]
정상적으로 작동하네요. 정말 감사합니다!
