### ISSUE TITLE
특정 유튜브 mp3 다운로드 불가

### ISSUE THREAD

**Issue by katc12** [KurtBestor/Hitomi-Downloader#2004]
1. Mulan - I'll Make A Man Out Of You (feat. @Black Gryph0n ) | EPIC VERSION

Invalid: [youtube] https://www.youtube.com / watch?v=rdbEJYS1wh4&list=LLC9GCkKf6oaWLw2EJE7F30Q&index=10&t=0s

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.15063
order: 1
group: False
gal_num: https://www.youtube.com/watch?v=rdbEJYS1wh4&list=LLC9GCkKf6oaWLw2EJE7F30Q&index=10&t=0s
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=rdbEJYS1wh4&list=LLC9GCkKf6oaWLw2EJE7F30Q&index=10&t=0s
valid: False
done: True
range: None
range_p: None
single: True
time: 1590630964.02 (May 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp3
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[144p][30fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 395 - 426x240 (240p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 396 - 640x360 (360p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 397 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][30fps][None] mp4 None ─ 398 - 1280x720 (720p)
[1080p][30fps][None] mp4 None ─ 399 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000021E7F100988> 251 - audio only (tiny) None webm opus 0fps
stream is not valid
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 73, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[144p][30fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 395 - 426x240 (240p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 396 - 640x360 (360p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 397 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][30fps][None] mp4 None ─ 398 - 1280x720 (720p)
[1080p][30fps][None] mp4 None ─ 399 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000021E7C40AB08> 249 - audio only (tiny) None webm opus 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E7DCC0588> 250 - audio only (tiny) None webm opus 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E009CFBC8> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E7F104748> 140 - audio only (tiny) None m4a mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E009CAC08> 251 - audio only (tiny) None webm opus 0fps
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "youtube_downloader", line 390, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=rdbEJYS1wh4&list=LLC9GCkKf6oaWLw2EJE7F30Q&index=10&t=0s

2. I'll Make a Man Out of You (feat. Black Gryph0n)

Invalid: [youtube] https://www.youtube.com / watch?v=yUn4JVqcde8

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.15063
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=yUn4JVqcde8
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=yUn4JVqcde8
valid: False
done: True
range: None
range_p: None
single: True
time: 1590631012.92 (May 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp3
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][25fps][None] webm None ─ 278 - 144x144 (144p)
[144p][25fps][None] mp4 None ─ 160 - 144x144 (144p)
[240p][25fps][None] webm None ─ 242 - 240x240 (240p)
[360p][25fps][None] mp4 None ─ 134 - 360x360 (360p)
[240p][25fps][None] mp4 None ─ 133 - 240x240 (240p)
[360p][25fps][None] webm None ─ 243 - 360x360 (360p)
[480p][25fps][None] mp4 None ─ 135 - 480x480 (480p)
[480p][25fps][None] webm None ─ 244 - 480x480 (480p)
[720p][25fps][None] mp4 None ─ 136 - 720x720 (720p)
[720p][25fps][None] webm None ─ 247 - 720x720 (720p)
[1080p][25fps][None] webm None ─ 248 - 1080x1080 (1080p)
[1080p][25fps][None] mp4 None ─ 137 - 1080x1080 (1080p)
[360p][25fps][96kbps] mp4 mp4a.40.2 ─ 18 - 360x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000021E7342CAC8> 251 - audio only (tiny) None webm opus 0fps
stream is not valid
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][25fps][None] webm None ─ 278 - 144x144 (144p)
[144p][25fps][None] mp4 None ─ 160 - 144x144 (144p)
[240p][25fps][None] webm None ─ 242 - 240x240 (240p)
[360p][25fps][None] mp4 None ─ 134 - 360x360 (360p)
[240p][25fps][None] mp4 None ─ 133 - 240x240 (240p)
[360p][25fps][None] webm None ─ 243 - 360x360 (360p)
[480p][25fps][None] mp4 None ─ 135 - 480x480 (480p)
[480p][25fps][None] webm None ─ 244 - 480x480 (480p)
[720p][25fps][None] mp4 None ─ 136 - 720x720 (720p)
[720p][25fps][None] webm None ─ 247 - 720x720 (720p)
[1080p][25fps][None] webm None ─ 248 - 1080x1080 (1080p)
[1080p][25fps][None] mp4 None ─ 137 - 1080x1080 (1080p)
[360p][25fps][96kbps] mp4 mp4a.40.2 ─ 18 - 360x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000021E735F95C8> 249 - audio only (tiny) None webm opus 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E00ABC408> 250 - audio only (tiny) None webm opus 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E00ABC8C8> 18 - 360x360 (360p) 360p mp4 mp4a.40.2 25fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E00ABC2C8> 140 - audio only (tiny) None m4a mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000021E00ABCEC8> 251 - audio only (tiny) None webm opus 0fps
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "youtube_downloader", line 390, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=yUn4JVqcde8

두가지 링크 넣어봤는데 전부 실패하네요. 
좋은하루 되십시오

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by katc12** [comment]
받아서 실행해봐도 안되네요...

Invalid: [youtube] https://www.youtube.com / watch?v=rdbEJYS1wh4

version: 2.8 (20-05-29 11:59:30 GMT+0)
platform: Windows-10-10.0.15063
order: 1
group: False
input: https://www.youtube.com/watch?v=rdbEJYS1wh4
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=rdbEJYS1wh4
valid: False
done: True
range: None
range_p: None
single: True
time: 1590762392.94 (May 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp3
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

No videos
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=rdbEJYS1wh4

**Comment by katc12** [comment]
와! 이제 잘됩니다 ㅋㅋㅋ 감사합니다
