### ISSUE TITLE
인스타그램 비공개 계정

### ISSUE THREAD

**Issue by doaq** [KurtBestor/Hitomi-Downloader#2013]
선생님
항상 감사합니다
인스타그램 비공개 계정 이미지 다운이 현재 가능한 상태인가요?
쿠키를 불러오라는 이야기가 있어서
원하는 url에서 cookies.txt 확장프로그램으로 쿠키 메모파일을 다운받은 후
도움말 쿠키 불러오기로 파일을 불러오면 success가 뜹니다
그리고 원하는 url을 작업창에 치면 invalid 라며 다운이 되지 않습니다
제가 잘못한 부분이 있는지 아니면 불가능한 것인지 부디 확인 부탁드립니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by doaq** [comment]
Invalid: [insta] https://www.instagram.com / ll / 

version: 2.8 (20-05-29 11:59:30 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://www.instagram.com/ll/
dir: 
zip: 
type: insta
artist: 
url: https://www.instagram.com/ll
valid: False
done: True
range: None
range_p: None
single: False
time: 1590769811.61 (May 30)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Failed to get stories; Login required: None
Too short: 0 / 57
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "insta_downloader", line 72, in read
File "insta_downloader", line 387, in get_imgs
File "insta_downloader", line 306, in get_urls
Exception: Too short: 0 / 57

Invalid: fail=True
EOT: https://www.instagram.com/ll/

**Comment by doaq** [comment]
전 gui 실행 파일만 다운받아서 썼는데 같이 첨부되어있는 소스코드? 파일은 용도를 몰라서 안받았거든요 혹시 그것때문은 아닌가요?

**Comment by KurtBestor** [comment]
팔로우 되어있는 계정 쿠키를 넣어야해요.
