### ISSUE TITLE
폰헙 paid video 다운할수있을까요?

### ISSUE THREAD

**Issue by sksdhtjdals** [KurtBestor/Hitomi-Downloader#2015]
Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5e8726cf1e4cd

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e8726cf1e4cd
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e8726cf1e4cd
valid: False
done: True
range: None
range_p: None
single: True
time: 1590838200.87 (May 30)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
isLogin 2
Video
decode
Video
decode
Video
decode
Video
decode
Video
decode
Video
decode
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "pornhub_downloader", line 225, in get_video
File "<decorator-gen-23>", line 2, in decode
File "locker", line 14, in wrapper
File "pornhub_decoder", line 21, in decode
Exception: No script

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "pornhub_downloader", line 159, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "pornhub_downloader", line 225, in get_video
File "<decorator-gen-23>", line 2, in decode
File "locker", line 14, in wrapper
File "pornhub_decoder", line 21, in decode
Exception: No script

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e8726cf1e4cd

이런식으로 에러가 뜨는데 안되는걸까요?..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1812

**Comment by sksdhtjdals** [comment]
답변하신대로 했더니 프리미엄 다운까지 되었네요
감사합니다.
다만.. 동영상이 재생이 되는 유료영상들은 받아지는데 저위에 적은 주소로 된 영상들은...
별도로 결제를 해야만 볼수 있는영상인가봅니다..
