### ISSUE TITLE
유튜브 다운로드가 안되는 문제

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2031]
시도한 주소 : https://www.youtube.com/watch?v=9HnaEeXa86k

아래와 같은 메세지가 출력되었습니다.

------------------------------------------------------------
Invalid: [youtube] https://www.youtube.com / watch?v=9HnaEeXa86k

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.youtube.com/watch?v=9HnaEeXa86k
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=9HnaEeXa86k
valid: False
done: True
range: None
range_p: None
single: True
time: 1591093387.29 (Jun 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 75, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

No videos
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=9HnaEeXa86k

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1816#issuecomment-606793783

**Comment by tdi2020** [comment]
존경하는 선생님 현재 테스트버전으로 쿠키를 넣어보면

Traceback (most recent call last):
  File "hitomi_downloader_gui", line 7186, in foo
ImportError: No module named cooker

라는 메세지가 출력되면서 쿠키 불러오기가 되질 않습니다ㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
쿠키입력 잘되는 것 확인했습니다 선생님 감사합니다!
