### ISSUE TITLE
유튜브 다운로드 불가 현상

### ISSUE THREAD

**Issue by univ11jung** [KurtBestor/Hitomi-Downloader#2033]
업데이트 이후 유튜브 다운로드가 안됩니다

=====================================

Invalid: [youtube] https://www.youtube.com / watch?list=PL5pycTgSAvaCpodswURacJkNyqu-BJUMj&v=EnDXGQmCz3U&feature=emb_title

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.youtube.com/watch?list=PL5pycTgSAvaCpodswURacJkNyqu-BJUMj&v=EnDXGQmCz3U&feature=emb_title
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?list=PL5pycTgSAvaCpodswURacJkNyqu-BJUMj&v=EnDXGQmCz3U&feature=emb_title
valid: False
done: True
range: None
range_p: None
single: True
time: 1591098166.48 (Jun 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 73, in get
File "youtube_dl_test", line 77, in __init__
KeyError: 'formats'

No videos
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?list=PL5pycTgSAvaCpodswURacJkNyqu-BJUMj&v=EnDXGQmCz3U&feature=emb_title

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
