### ISSUE TITLE
안녕하세요?. 2.8a 사용중 트위터 저장시 invalid 에러가 계속 납니다

### ISSUE THREAD

**Issue by Fusrofk** [KurtBestor/Hitomi-Downloader#2039]
도움 감사합니다!

Invalid: [twitter] https://twitter.com / i / status / 1164838890299019265

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://twitter.com/i/status/1164838890299019265
dir: 
zip: 
type: twitter
artist: めろ
url: https://twitter.com/skrn__kyawawa/status/1164838890299019265
valid: False
done: False
range: None
range_p: None
single: False
time: 1591315768.28 (Jun 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
single tweet
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitter_downloader", line 560, in get_imgs_single
Exception: no tabs

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "twitter_downloader", line 126, in read
File "<decorator-gen-18>", line 2, in get_imgs_single
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitter_downloader", line 560, in get_imgs_single
Exception: no tabs

Invalid: fail=True

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2035
