### ISSUE TITLE
트위치 다시보기 동영상 다운 불가

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader#2050]
![image](https://user-images.githubusercontent.com/36811336/84031708-23141880-a9d1-11ea-8fcc-3cc4a1c98f41.png)

https://www.twitch.tv/videos/636476002
https://www.twitch.tv/videos/644723952

수고하십니다,,

Invalid: [twitch] https://www.twitch.tv / videos / 636476002

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.twitch.tv/videos/636476002
dir: 
zip: 
type: twitch
artist: None
url: https://www.twitch.tv/videos/636476002
valid: False
done: True
range: None
range_p: None
single: True
time: 1591620133.2 (Jun 8)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitch_downloader", line 67, in get_img
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "twitch_downloader", line 45, in read
File "<decorator-gen-41>", line 2, in get_img
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitch_downloader", line 67, in get_img
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.twitch.tv/videos/636476002

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Yoon0618** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘 됩니다!
감사합니다 ^^7
