### ISSUE TITLE
nhentai Invalid download

### ISSUE THREAD

**Issue by callacall** [KurtBestor/Hitomi-Downloader#2053]
![5352772](https://user-images.githubusercontent.com/59549156/84105054-c0ab2e80-aa49-11ea-95c1-32040f37be48.png)
Downloading from nhentai with their new server always ended up with invalid error

Invalid: [nhentai] https://nhentai.net / g / 316272 / 

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.17763
order: 0
group: False
input: https://nhentai.net/g/316272/
dir: 
zip: 
type: nhentai
artist: None
url: https://nhentai.net/g/316272/
valid: False
done: True
range: None
range_p: None
single: False
time: 1591670391.01 (Jun 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "nhentai_downloader", line 95, in get_info
IndexError: list index out of range

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "nhentai_downloader", line 25, in read
File "nhentai_downloader", line 129, in get_imgs
File "<decorator-gen-32>", line 2, in get_info
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "nhentai_downloader", line 95, in get_info
IndexError: list index out of range

Invalid: fail=True
EOT: https://nhentai.net/g/316272/

**Comment by BatmanPerbert** [comment]
I have the same problem....

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by callacall** [comment]
Thank you for the replies man. Will try soon after im back home.

**Comment by KurtBestor** [comment]
Whatever is fine.
