### ISSUE TITLE
폰헙, 폰헙프리미엄 다운로드 불가 문제

### ISSUE THREAD

**Issue by Sisquaker** [KurtBestor/Hitomi-Downloader#2061]
현재 폰헙 폰헙프리미엄 모두 안됩니다. 기존에 있던 #1855 의 파일도 마찬가지 현상입니다. 뭔가 알고리즘이 바뀐게 아닐까...

쿠키 초기화 및 다시 cookie export 해서 시도해도 마찬가지 현상입니다.

확인 결과 외부 우회 프로그램과의 충돌로 밝혀졌습니다. 유니콘하고 충돌현상나는 듯 하네요.

Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph5eb979774cfab

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 6
group: False
input: https://www.pornhub.com/view_video.php?viewkey=ph5eb979774cfab
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5eb979774cfab
valid: False
done: True
range: None
range_p: None
single: True
time: 1591955560.1 (Jun 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "pornhub_downloader", line 208, in get_video
File "downloader", line 297, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 514, in send
SSLError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5eb979774cfab (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "pornhub_downloader", line 159, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "pornhub_downloader", line 208, in get_video
File "downloader", line 297, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 514, in send
SSLError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph5eb979774cfab (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5eb979774cfab

**Comment by Sisquaker** [comment]
상세 확인 결과, DPI 우회 킨 상태에서 유니콘 우회앱을 껐을 시 pornhub 사이트는 다운로드가 불가능하고, pornhubpremium 사이트는 다운로드가 가능합니다.

우회앱 키면 둘 다 불가능하고요.

**Comment by KurtBestor** [comment]
작업 정보를 보면 Premium 도 실패한 걸로 보이네요.
