### ISSUE TITLE
다운 멈춤 현상

### ISSUE THREAD

**Issue by fujl1** [KurtBestor/Hitomi-Downloader#2093]
다운시 얼마 지나지 않아 다운속도가 0이 됩니다. 재실행하면 또 어느 정도 받아지다가 다시 속도가 0이 되면서 멈추네요.

-----------------------------------------
[니시 오사무] 악마에 입문했습니다! 이루마 군

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 6
group: False
input: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471
dir: hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군
zip: 
type: manamoa
artist: 니시 오사무
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10200
valid: True
done: False
range: None
range_p: None
single: False
time: 1593315967.27 (Jun 28)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0000.jpg
[0002] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0001.jpg
[0003] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0002.jpg
[0004] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0003.jpg
[0005] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0004.jpg
[0006] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0005.jpg
[0007] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0006.jpg
[0008] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0007.jpg
[0009] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0008.jpg
[0010] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0009.jpg
[0011] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0010.jpg
[0012] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0011.jpg
[0013] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0012.jpg
[0014] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0013.jpg
[0015] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0014.jpg
[0016] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0015.jpg
[0017] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0016.jpg
[0018] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0017.jpg
[0019] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0018.jpg
[0020] hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0019.jpg

[URLs]
[0001] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnredbull.xyz//upload/f2427a59dcae544f1a1708c995d37fc1.jpg?quick
[0002] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnbrolake.xyz//upload/ff1609820dfb2cc2370b0dc1fb47a655.jpg?quick
[0003] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnraceable.xyz//upload/6a17f748c6918c2bc44d730f8b922184.jpg?quick
[0004] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnpublic.xyz//upload/a50c52dc7393aa0d6591617385f7407b.jpg?quick
[0005] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnvariable.xyz//upload/0ec638ea90c3fb51ffd2400ddd295c39.jpg?quick
[0006] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnalready.xyz//upload/679df6d68c9ee594ed793cea36936716.jpg?quick
[0007] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnanything.xyz//upload/2072c208df9e4a758a1801ea373dd468.jpg?quick
[0008] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnbetter.xyz//upload/01b44ec640bbf0399e05051d72ea1e1d.jpg?quick
[0009] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnappleheap.xyz//upload/f7f17f6ebb8371b6d2ff545f63aa16db.jpg?quick
[0010] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdndemonslayer.xyz//upload/abbc8ed75c1b18d385481117440194d6.jpg?quick
[0011] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnredbull.cc//upload/7bd56ddf20a1a0b2e8e2830feb845e3f.jpg?quick
[0012] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnbrolake.cc//upload/08617ab9a70ef4cdf596261d7f87d1c3.jpg?quick
[0013] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnraceable.cc//upload/70845ae41fd085b1b539290b0984e3e7.jpg?quick
[0014] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnpublic.cc//upload/f359aee9b524f6e93d270f89da154f77.jpg?quick
[0015] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnvariable.cc//upload/d950e97d49679f2a1536b708cb4f5c84.jpg?quick
[0016] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnredbull.xyz//upload/8b9226cdee12e665c9a9de4dcc359222.jpg?quick
[0017] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnbrolake.xyz//upload/37fb2dad5a3305e74e5f2b66455d719b.jpg?quick
[0018] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnraceable.xyz//upload/7bfbf3604da4c430fe03ecf65d22f579.jpg?quick
[0019] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnpublic.xyz//upload/bcb9abbcd0d75a77fd662432fdd8d991.jpg?quick
[0020] LazyUrl(https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=3484471) ---> https://cdnvariable.xyz//upload/897500556fa85182d319e509396ce9ec.jpg?quick

[Messages]
clf solved
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10200
clf solved
dirFormat: [artist] title
악마에 입문했습니다! 이루마 군 127화 chapter:3484471 seed:0 domains:60

Fail : \\?\D:\『정리』\(\hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0017.jpg
Traceback (most recent call last):
File "downloader", line 813, in download
Exception: https://cdnraceable.xyz//upload/7bfbf3604da4c430fe03ecf65d22f579.jpg?quick
Traceback (most recent call last):
File "downloader", line 809, in download
File "site-packages\urllib3\request", line 76, in request
File "site-packages\urllib3\request", line 97, in request_encode_url
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 360, in connect
File "site-packages\urllib3\util\ssl_", line 370, in ssl_wrap_socket
File "site-packages\urllib3\contrib\pyopenssl", line 491, in wrap_socket
SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)

use alternative url: https://cdnraceable.xyz//upload/7bfbf3604da4c430fe03ecf65d22f579.jpg?quick --> https://s3.cdnraceable.xyz//upload/7bfbf3604da4c430fe03ecf65d22f579.jpg?quick

Fail : \\?\D:\『정리』\(\hitomi_downloaded_manamoa\[니시 오사무] 악마에 입문했습니다! 이루마 군\악마에 입문했습니다! 이루마 군 127화\0002.jpg
Traceback (most recent call last):
File "downloader", line 813, in download
Exception: https://cdnraceable.xyz//upload/6a17f748c6918c2bc44d730f8b922184.jpg?quick
Traceback (most recent call last):
File "downloader", line 809, in download
File "site-packages\urllib3\request", line 76, in request
File "site-packages\urllib3\request", line 97, in request_encode_url
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 360, in connect
File "site-packages\urllib3\util\ssl_", line 370, in ssl_wrap_socket
File "site-packages\urllib3\contrib\pyopenssl", line 491, in wrap_socket
SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)

use alternative url: https://cdnraceable.xyz//upload/6a17f748c6918c2bc44d730f8b922184.jpg?quick --> https://s3.cdnraceable.xyz//upload/6a17f748c6918c2bc44d730f8b922184.jpg?quick

**Comment by geniussjt** [comment]
다운이 안되는 것 페이지 엑박(오류) 때문입니다 
그 사이트 문제입니다
눈동자는 지금 정상입니다
