### ISSUE TITLE
유튜브의 성인인증이 필요한 영상이 다운이 안됩니다

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2098]
Invalid: [youtube] https://www.youtube.com / watch?v=3waKEn2mWjw

version: 2.8a (20-06-30 08:11:04 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: -315
group: False
input: https://www.youtube.com/watch?v=3waKEn2mWjw
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=3waKEn2mWjw
valid: False
done: True
range: None
range_p: None
single: True
time: 1593595219.044871 (Jul 1)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_downloader", line 71, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

No videos
stop
Traceback (most recent call last):
File "utils", line 898, in start
File "utils", line 930, in start_
File "youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=3waKEn2mWjw

다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1766

**Comment by yuchan39** [comment]
감사합니다. 해결되었습니다.
