### ISSUE TITLE
I can't download from e-hentai.org

### ISSUE THREAD

**Issue by BatmanPerbert** [KurtBestor/Hitomi-Downloader#2100]
Hello!! I can't download from e-hentai using the normal version and the fix one... the link appears, I mean the program read the link but i'ts all what it does. Doesn't download nothing.

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by BatmanPerbert** [comment]
> Right click on the task and press Info... (I). Can you show me the info?

Reading... https://e-hentai.org / g / 1663458 / 19e5a43896

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 21
group: False
input: https://e-hentai.org/g/1663458/19e5a43896
dir: hitomi_downloaded\[Cyancapsule] Artist - Cyancapsule (1663458)
zip: 
type: ehen
artist: cyancapsule
url: https://e-hentai.org/g/1663458/19e5a43896
valid: True
done: False
range: None
range_p: None
single: False
time: 1593653315.92 (Jul 1)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None


[Gallery]
Gallery ID: 1663458

Title: Artist - Cyancapsule

Artists: cyancapsule

Groups: N/A

Types: western

Series: my little pony friendship is magic

Characters: applejack, rainbow dash

Tags: male:furry, female:big breasts, female:furry, female:horse girl, western imageset, male:anal, male:horse boy, male:human on furry, male:tomgirl, female:anal, female:bbw, female:blowjob, female:bunny girl, female:cowgirl, female:double penetration, female:dragon, female:freckles, female:futanari, female:gokkun, female:large tattoo, female:masturbation, female:midget, female:nakadashi, female:paizuri, female:piercing, female:pig, female:pig girl, female:sex toys, female:sheep girl, female:shemale, female:small breasts, female:stockings, female:tanlines

Language: N/A


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 571, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 317, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 376, in _make_request
File "site-packages\urllib3\connectionpool", line 994, in _validate_conn
File "site-packages\urllib3\connection", line 300, in connect
File "site-packages\urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001EC8F918B88>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi", line 95, in pop_img
File "hitomi", line 49, in get_data
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: hiyobi

**Comment by KurtBestor** [comment]
Can you show me the info after `done: False` is changed to `done: True` ?

**Comment by BatmanPerbert** [comment]
Hello!! It's seem to be a conection problem, apparently the only servers who doesn't work properly are from e-hentai.org, all the others page servers works very good and take the amount of internet that I want.
Now it download, but very slow and just sometimes that I enter in the application.

**Comment by BatmanPerbert** [comment]
Hello again! I have to say that it's alredy downloading but very slow, my conclusion is simple... maybe the servers from e-hentai.org doesn't work properly to my ip, because all the other websites work very good.
If the problem persist or gone insane I will make another comment. Thanks for the help!
