### ISSUE TITLE
bestjavporn 다운로드  문제 문의드립니다

### ISSUE THREAD

**Issue by chung4219** [KurtBestor/Hitomi-Downloader#2105]
안녕하세요 선생님 항상 감사드립니다.

다름이 아니라 bestjavporn 사이트에서 다운로드가 안되서 문의드립니다.

Invalid: [bestjavporn] https://bestjavporn.com / video / heyzo-1199 / 

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://bestjavporn.com/video/heyzo-1199/
dir: 
zip: 
type: bestjavporn
artist: None
url: https://bestjavporn.com/video/heyzo-1199/
valid: False
done: True
range: None
range_p: None
single: True
time: 1593848217.43 (Jul 4)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "bestjavporn_downloader", line 28, in read
File "<decorator-gen-67>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

Invalid: fail=True
EOT: https://bestjavporn.com/video/heyzo-1199/

fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "bestjavporn_downloader", line 28, in read
File "<decorator-gen-67>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

Invalid: fail=True
EOT: https://bestjavporn.com/video/heyzo-1199/

fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "bestjavporn_downloader", line 28, in read
File "<decorator-gen-67>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

Invalid: fail=True
EOT: https://bestjavporn.com/video/heyzo-1199/

fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "bestjavporn_downloader", line 28, in read
File "<decorator-gen-67>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

Invalid: fail=True
EOT: https://bestjavporn.com/video/heyzo-1199/

fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "bestjavporn_downloader", line 28, in read
File "<decorator-gen-67>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "bestjavporn_downloader", line 93, in get_video
File "utils", line 556, in urljoin
File "urlparse", line 321, in urljoin
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 3: ordinal not in range(128)

Invalid: fail=True
EOT: https://bestjavporn.com/video/heyzo-1199/

**Comment by KurtBestor** [comment]
BestJavPorn 은 최근에 사이트 변경으로 좀 복잡해져서 고칠 때까지 시간 좀 걸릴 것 같아요.

**Comment by chung4219** [comment]
그렇군요... 기다리고 있겠습니다! 항상 감사드립니다!

**Comment by KurtBestor** [comment]
살펴보니 사용자가 직접 영상을 올리는 게 아니라 다른 사이트에서 가져오는 시스템이고 그 중 대부분이 KissJAV 예요.
KissJav 는 프로그램에서 이미 지원하고 있어서 BestJavPorn 을 지원 사이트에서 뺄까 생각중이에요.
다른 의견 있나요?

**Comment by chung4219** [comment]
아앗 그렇군요 제가 너무 늦게 답글을 달게 되어서 죄송합니다 감사합니다!
