### ISSUE TITLE
네이버웹툰 다운로드가 안되네요

### ISSUE THREAD

**Issue by Lisrim** [KurtBestor/Hitomi-Downloader#2106]
Invalid: [navertoon] https://comic.naver.com / webtoon / list.nhn?titleId=22043

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 2
group: False
input: https://comic.naver.com/webtoon/list.nhn?titleId=22043
dir: 
zip: 
type: navertoon
artist: None
url: https://comic.naver.com/webtoon/list.nhn?titleId=22043
valid: False
done: True
range: None
range_p: None
single: False
time: 1593853929.95 (Jul 4)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 876, in start
File "navertoon_downloader", line 53, in init
File "<decorator-gen-12>", line 2, in get_pages
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "navertoon_downloader", line 127, in get_pages
Exception: artist not found

Invalid: fail=True
EOT: https://comic.naver.com/webtoon/list.nhn?titleId=22043

stop
Traceback (most recent call last):
File "utils", line 876, in start
File "navertoon_downloader", line 53, in init
File "<decorator-gen-12>", line 2, in get_pages
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "navertoon_downloader", line 127, in get_pages
Exception: artist not found

Invalid: fail=True
EOT: https://comic.naver.com/webtoon/list.nhn?titleId=22043

**Comment by KurtBestor** [comment]
모바일 버전 제공하는 웹툰만 지원해요.
