### ISSUE TITLE
마나모아가 다운이 안됩니다

### ISSUE THREAD

**Issue by x2ssuh** [KurtBestor/Hitomi-Downloader#2109]
DPI 우회를 켜고 하는데도 안되는데 이유를 알 수 있을까요?

Invalid: [manamoa] manamoa_784638

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: manamoa_784638
dir: 
zip: 
type: manamoa
artist: None
url: 784638
valid: False
done: True
range: None
range_p: None
single: False
time: 1593880907.55 (Jul 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 58, in solve
Exception: clf Timeout

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "manamoa_downloader", line 193, in read
File "manamoa_downloader", line 180, in name
File "manamoa_downloader", line 164, in soup
File "<decorator-gen-46>", line 2, in get_soup
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 58, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: manamoa_784638

no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 58, in solve
Exception: clf Timeout

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "manamoa_downloader", line 193, in read
File "manamoa_downloader", line 180, in name
File "manamoa_downloader", line 164, in soup
File "<decorator-gen-46>", line 2, in get_soup
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 58, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: manamoa_784638

**Comment by KurtBestor** [comment]
다음과 같이 주소를 입력해주세요: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10178

**Comment by x2ssuh** [comment]
말씀하신대로 manamoa_주소전체 또는 주소전체를 넣으니 해결되었습니다.

감사합니다.
