### ISSUE TITLE
다음 웹툰 다운로드 파싱 중 Invalid 오류가 발생합니다

### ISSUE THREAD

**Issue by ImSejin** [KurtBestor/Hitomi-Downloader#2112]
Invalid: [daumtoon] http://webtoon.daum.net / webtoon / view / HeavensSoul

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
input: http://webtoon.daum.net/webtoon/view/HeavensSoul
dir: 
zip: 
type: daumtoon
artist: None
url: http://webtoon.daum.net/webtoon/view/HeavensSoul
valid: False
done: True
range: None
range_p: None
single: False
time: 1593962801.98 (Jul 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', error(10054, ''))
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "daumtoon_downloader", line 146, in read
File "daumtoon_downloader", line 190, in get_imgs_all
File "daumtoon_downloader", line 160, in get_imgs
File "downloader", line 317, in read_html
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 376, in increment
File "site-packages\urllib3\connectionpool", line 672, in urlopen
File "site-packages\urllib3\connectionpool", line 412, in _make_request
File "httplib", line 1148, in getresponse
File "httplib", line 448, in begin
File "httplib", line 404, in _read_status
File "socket", line 480, in readline
ProtocolError: ('Connection aborted.', error(10054, ''))

Invalid: fail=True
EOT: http://webtoon.daum.net/webtoon/view/HeavensSoul

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ImSejin** [comment]
다른 네트워크 + 다른 기기로 해 본 결과 잘됩니다.

그러나, 문제가 발생한 최초의 기기에선 여전히 안됩니다.
로그 첨부해드립니다.

```
Invalid: [daumtoon] http://webtoon.daum.net / webtoon / view / HeavensSoul

version: 2.8a (20-07-07 04:10:18 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: http://webtoon.daum.net/webtoon/view/HeavensSoul
dir: 
zip: 
type: daumtoon
artist: None
url: http://webtoon.daum.net/webtoon/view/HeavensSoul
valid: False
done: True
range: None
range_p: None
single: False
time: 1594173546.3465798 (Jul 8)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "site-packages\urllib3\connectionpool", line 677, in urlopen
File "site-packages\urllib3\connectionpool", line 426, in _make_request
File "<string>", line 3, in raise_from
File "site-packages\urllib3\connectionpool", line 421, in _make_request
File "http\client", line 1344, in getresponse
File "http\client", line 306, in begin
File "http\client", line 267, in _read_status
File "socket", line 589, in readinto
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 902, in start
File "utils", line 934, in start_
File "extractor\daumtoon_downloader", line 146, in read
File "extractor\daumtoon_downloader", line 190, in get_imgs_all
File "extractor\daumtoon_downloader", line 160, in get_imgs
File "downloader", line 409, in read_html
File "downloader", line 327, in read_html
File "site-packages\urllib3\poolmanager", line 336, in urlopen
File "site-packages\urllib3\connectionpool", line 725, in urlopen
File "site-packages\urllib3\util\retry", line 379, in increment
File "site-packages\urllib3\packages\six", line 734, in reraise
File "site-packages\urllib3\connectionpool", line 677, in urlopen
File "site-packages\urllib3\connectionpool", line 426, in _make_request
File "<string>", line 3, in raise_from
File "site-packages\urllib3\connectionpool", line 421, in _make_request
File "http\client", line 1344, in getresponse
File "http\client", line 306, in begin
File "http\client", line 267, in _read_status
File "socket", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: http://webtoon.daum.net/webtoon/view/HeavensSoul
```
