### ISSUE TITLE
익헨 특정자료만 무한반복되다가 다운이 안됩니다.

### ISSUE THREAD

**Issue by zxcfld1** [KurtBestor/Hitomi-Downloader#2113]
다른 익헨 자료들은 다운이 잘되는데 몇몇자료는 계속 시도해도 다운이 안되는데 무슨 현상이죠?

![캡처_2020_07_07_06_55_13_9](https://user-images.githubusercontent.com/65436902/86651966-f29abb00-c01e-11ea-819b-8d9dd68f2d42.jpg)

![캡처_2020_07_07_07_07_14_455](https://user-images.githubusercontent.com/65436902/86653924-8620bb80-c020-11ea-88f2-eeb2ac3ae22a.jpg)

Invalid: [hitomi] https://exhentai.org / g / 732311 / 8a9428bcb8 / 

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.19041
order: 1
group: False
input: https://exhentai.org/g/732311/8a9428bcb8/
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/g/732311/8a9428bcb8/
valid: False
done: True
range: None
range_p: None
single: False
time: 1594072727.34 (Jul 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1067, in ehen_imgs
Exception: no images

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 403

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1067, in ehen_imgs
Exception: no images

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

FINAL SERVER: auto
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 744, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

stop
Invalid: fail=False
stop
EOT: https://exhentai.org/g/732311/8a9428bcb8/

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 692, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

FINAL SERVER: auto
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://e-hentai.org/g/732311/8a9428bcb8 ----> https://e-hentai.org/g/732311/8a9428bcb8
get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/732311/8a9428bcb8/)
#### https://exhentai.org/g/732311/8a9428bcb8 ----> https://exhentai.org/g/732311/8a9428bcb8
Traceback (most recent call last):
File "hitomi_downloader", line 744, in read
File "hitomi_downloader", line 573, in get_imgs
File "hitomi_downloader", line 1053, in ehen_imgs
File "downloader", line 387, in read_html
Exception: 404

stop
Invalid: fail=False
stop
EOT: https://exhentai.org/g/732311/8a9428bcb8/

**Comment by KurtBestor** [comment]
직접 웹브라우저로 보는 건 되나요?

**Comment by zxcfld1** [comment]
네. 직접 보는건 됩니다.

**Comment by KurtBestor** [comment]
제목이 어떻게 되나요?

**Comment by zxcfld1** [comment]
[BeastAnime] Preyship  입니다

**Comment by KurtBestor** [comment]
특정 계정만 볼 수 있는 그런 건가요? 저는 안 보이네요.

![image](https://user-images.githubusercontent.com/14768120/86909093-891bc900-c152-11ea-9959-d539802c2a95.png)

**Comment by zxcfld1** [comment]
제가 익헨 계정을 만들때 캐나다로 우회해서 만들었는데 

저한테만 보이는 자료여서 다운이 안된건가요

**Comment by KurtBestor** [comment]
로그아웃해도 보이나요?

**Comment by zxcfld1** [comment]
로그아웃해도 보입니다 

제가 아이피를 미국으로 우회해서 접속해봤는데 보입니다
