### ISSUE TITLE
기본 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by 20142020** [KurtBestor/Hitomi-Downloader#2117]
삭제된 데이터 다운로드는 되는데 

기본데이터는 아래 문구와함께 다운로드 실패가 뜨네요

Traceback (most recent call last):
  File "hitomi_searcher", line 214, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 387, in read_html
Exception: 502

**Comment by KurtBestor** [comment]
지금도 그런가요?

**Comment by 20142020** [comment]
지금은 또 다운로드가 가능합니다. 
이후에 비슷한 오류가 있으면 그냥 기다리면 되나요?

**Comment by KurtBestor** [comment]
어제 잠깐 크롤링 서버 오류로 문제 생겼었는데 고쳤어요.

**Comment by 20142020** [comment]
아~ 그렇군요 항상 감사합니다 !
