### ISSUE TITLE
twitch가 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by 564871378123248** [KurtBestor/Hitomi-Downloader#2133]
Invalid: [twitch] https://www.twitch.tv / videos / 675359023

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.twitch.tv/videos/675359023
dir: 
zip: 
type: twitch
artist: None
url: https://www.twitch.tv/videos/675359023
valid: False
done: True
range: None
range_p: None
single: True
time: 1594538449.25 (Jul 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitch_downloader", line 67, in get_img
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "twitch_downloader", line 45, in read
File "<decorator-gen-41>", line 2, in get_img
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitch_downloader", line 67, in get_img
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.twitch.tv/videos/675359023

fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitch_downloader", line 67, in get_img
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "twitch_downloader", line 45, in read
File "<decorator-gen-41>", line 2, in get_img
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "twitch_downloader", line 67, in get_img
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.twitch.tv/videos/675359023

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2050
