### ISSUE TITLE
jp.xhamster에서 일부 자료가 에러가 뜹니다

### ISSUE THREAD

**Issue by zifm** [KurtBestor/Hitomi-Downloader#2137]
Invalid: [xhamster] https://jp.xhamster13.com / videos / ohd362b-xhPR2sh

version: 2.8a (20-07-13 04:30:50 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://jp.xhamster13.com/videos/ohd362b-xhPR2sh
dir: 
zip: 
type: xhamster
artist: None
url: https://jp.xhamster.com/videos/ohd362b-xhPR2sh
valid: False
done: True
range: None
range_p: None
single: True
time: 1594691142.709261 (Jul 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 627, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 563, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 755, in http_error_302
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\xhamster", line 116, in _real_extract
File "youtube_dl\extractor\common", line 660, in _download_webpage_handle
File "youtube_dl\extractor\common", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\xhamster_downloader", line 117, in get_imgs
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\extractor\common", line 627, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 563, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 755, in http_error_302
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 563, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 755, in http_error_302
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\xhamster", line 116, in _real_extract
File "youtube_dl\extractor\common", line 660, in _download_webpage_handle
File "youtube_dl\extractor\common", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 906, in start
File "utils", line 938, in start_
File "extractor\xhamster_downloader", line 92, in read
File "extractor\xhamster_downloader", line 121, in get_imgs
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://jp.xhamster13.com/videos/ohd362b-xhPR2sh

이렇게 나옵니다

**Comment by KurtBestor** [comment]
비공개 동영상이네요.
