### ISSUE TITLE
히토미 데이터 읽기 실패

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader#2148]
---------------------------
Hitomi Downloader
---------------------------
데이터를 다운로드하는 중에 실패했습니다.
---------------------------
확인   자세한 정보 숨기기...   
---------------------------
Traceback (most recent call last):
  File "hitomi_searcher", line 222, in download_json
  File "zipfile", line 1063, in extractall
  File "zipfile", line 1051, in extract
  File "zipfile", line 1107, in _extract_member
  File "shutil", line 63, in copyfileobj
  File "zipfile", line 655, in read
  File "zipfile", line 715, in read1
  File "zipfile", line 670, in _update_crc
BadZipfile: Bad CRC-32 for file 'galleries0.json'

이렇게 뜨면서 히토미 읽기 실패가 뜹니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
