### ISSUE TITLE
다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by taemir** [KurtBestor/Hitomi-Downloader#2156]
며칠 전부터 manamoa, pornhub 등 사이트들의 다운로드가 막혔습니다.

아래는 manamoa 다운로드시의 에러 메세지입니다.

Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=9843

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9843
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9843
valid: False
done: True
range: None
range_p: None
single: False
time: 1595163559.1 (Jul 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 58, in solve
Exception: clf Timeout

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "manamoa_downloader", line 193, in read
File "manamoa_downloader", line 180, in name
File "manamoa_downloader", line 164, in soup
File "<decorator-gen-46>", line 2, in get_soup
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "manamoa_downloader", line 225, in get_soup
File "manamoa_downloader", line 210, in real_url
File "clf2", line 58, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=9843

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
