### ISSUE TITLE
선생님 유투브 4k영상 안받아지는거 같은데 어떻게 하면 되나요?

### ISSUE THREAD

**Issue by v5598** [KurtBestor/Hitomi-Downloader#2182]
Invalid: [youtube] https://www.youtube.com / watch?v=KmyJNlLzuow

version: 2.8a (20-07-27 10:16:44 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=KmyJNlLzuow
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=KmyJNlLzuow
valid: False
done: True
range: None
range_p: None
single: True
time: 1595945637.7667027 (Jul 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2107, in _real_extract
File "youtube_dl\extractor\youtube", line 1436, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 69, in get
File "youtube_dl_test", line 78, in __init__
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 15, in report_error
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1426, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1338, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1402, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

No videos
stop
Traceback (most recent call last):
File "utils", line 927, in start
File "utils", line 959, in start_
File "extractor\youtube_downloader", line 387, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=KmyJNlLzuow

**Comment by v5598** [comment]
감사합니다 센세
