### ISSUE TITLE
뉴토끼 스크립트를 적용하면 올바르지 않은 형식이라고 뜹니다

### ISSUE THREAD

**Issue by tlalgkek** [KurtBestor/Hitomi-Downloader#2186]
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4301, in exec_script
  File "dynamic_module_2", line 11, in <module>
ImportError: No module named page_selector

다운로더 버전은 v2.8a 입니다.

**Comment by tlalgkek** [comment]
죄송합니다. 테스트 버전으로 넣으니 인식이 되네요.

**Comment by inspection96** [comment]
테스트 버전 링크 남겨주실수 있으신가요?
