### ISSUE TITLE
쿠키가 있으나 다운로드가 안되는 아프리카 연령제한 다시보기

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2193]
안녕하세요 존경하는 KurtBestor선생님!
쿠키 로그인을 해야 다운로드 가능한 아프리카 연령제한 다시보기가 
어떤것은 되고 어떤것은 안되는 경우가 발생하여 보고드립니다.
즉 두 영상 모두 연령제한이 걸려있는데 쿠키 넣은 상태에서 한개만 invalid 뜨면서 안되는 상태입니다.

다운로드 가능한 연령제한 링크 : http://vod.afreecatv.com/PLAYER/STATION/59571979
다운로드 불가능한 연령제한 링크 : http://vod.afreecatv.com/PLAYER/STATION/58793073

위 주소 두가지로 테스트 해보았으며 안되는 다시보기의 경우 아래와 같이 출력됩니다.

----------------------------------------------------------------------------------------------------

Invalid: [afreeca] http://vod.afreecatv.com / PLAYER / STATION / 58793073

version: 2.8a (20-07-31 07:49:26 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/58793073
dir: 
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/58793073
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1596337313.1931784 (Aug 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\afreeca_downloader", line 73, in get_video
File "m3u8_tools", line 165, in playlist2stream
File "downloader", line 341, in read_html
Exception: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 800, in wrapper
File "m3u8_tools", line 86, in __init__
File "downloader", line 341, in read_html
Exception: 404

stop
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\afreeca_downloader", line 73, in get_video
File "m3u8_tools", line 165, in playlist2stream
File "downloader", line 341, in read_html
Exception: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 927, in start
File "utils", line 960, in start_
File "extractor\afreeca_downloader", line 46, in read
File "extractor\afreeca_downloader", line 76, in get_video
File "<decorator-gen-5>", line 2, in __init__
File "constants", line 830, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\afreeca_downloader", line 73, in get_video
File "m3u8_tools", line 165, in playlist2stream
File "downloader", line 341, in read_html
Exception: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 800, in wrapper
File "m3u8_tools", line 86, in __init__
File "downloader", line 341, in read_html
Exception: 404

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/58793073

fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\afreeca_downloader", line 73, in get_video
File "m3u8_tools", line 165, in playlist2stream
File "downloader", line 341, in read_html
Exception: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 800, in wrapper
File "m3u8_tools", line 86, in __init__
File "downloader", line 341, in read_html
Exception: 404

stop
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\afreeca_downloader", line 73, in get_video
File "m3u8_tools", line 165, in playlist2stream
File "downloader", line 341, in read_html
Exception: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 927, in start
File "utils", line 960, in start_
File "extractor\afreeca_downloader", line 46, in read
File "extractor\afreeca_downloader", line 76, in get_video
File "<decorator-gen-5>", line 2, in __init__
File "constants", line 830, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\afreeca_downloader", line 73, in get_video
File "m3u8_tools", line 165, in playlist2stream
File "downloader", line 341, in read_html
Exception: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 316, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://vod-archive-kr-cdn-z01.afreecatv.com/v1/video/_definst_/smil:vod/20200706/513/225175513/58793073_1594106163_5.smil/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 800, in wrapper
File "m3u8_tools", line 86, in __init__
File "downloader", line 341, in read_html
Exception: 404

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/58793073

'NoneType' object has no attribute 'string'
stop
Traceback (most recent call last):
File "utils", line 927, in start
File "utils", line 960, in start_
File "extractor\afreeca_downloader", line 46, in read
File "extractor\afreeca_downloader", line 66, in get_video
AttributeError: 'NoneType' object has no attribute 'string'

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/58793073

**Comment by tdi2020** [comment]
+추가+
다운로드 가능했던 링크(http://vod.afreecatv.com/PLAYER/STATION/59571979)도 갑자기 중단되더니
재시도 해도 안되네요!ㅠㅠ 아프리카에서 다운로드 시도를 확인하고 막는걸까요?
로그는 아래와 같습니다.

---------------------------------------------------------------------------------------
Invalid: [afreeca] http://vod.afreecatv.com / PLAYER / STATION / 59571979

version: 2.8a (20-07-31 07:49:26 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/59571979
dir: 
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/59571979
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1596375545.2890096 (Aug 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'string'
stop
Traceback (most recent call last):
File "utils", line 927, in start
File "utils", line 960, in start_
File "extractor\afreeca_downloader", line 46, in read
File "extractor\afreeca_downloader", line 66, in get_video
AttributeError: 'NoneType' object has no attribute 'string'

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/59571979

**Comment by KurtBestor** [comment]
해당 영상파일 36분 33초 부분이 잘못되었네요.

브라우저에서 직접 봐도 안 보여요.

![image](https://user-images.githubusercontent.com/14768120/89149527-b2841500-d597-11ea-9ced-3533631d6cc8.png)

**Comment by KurtBestor** [comment]
깨진 부분 제외하고 받도록 했어요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
와 깨졌을 거라곤 꿈에도 생각 못했는데 ㅠㅠ 너무 잘됩니다!! 이걸 찾아서 해결해주셨네요ㄷㄷㄷㄷ 킹갓KurtBestor선생님...
