### ISSUE TITLE
히X미 다운 다 안되고 중간에서 멈춥니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2214]
[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)

version: 2.8a (20-06-10 11:17:37 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://hitomi.la/doujinshi/sono-namida-ni-yowain-dayo-%7C-%EA%B7%B8-%EB%88%88%EB%AC%BC%EC%97%90-%EC%95%BD%ED%95%9C-%EA%B1%B0%EB%9D%BC%EA%B3%A0-%ED%95%9C%EA%B5%AD%EC%96%B4-1701971.html
dir: hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)
zip: 
type: hitomi
artist: yasson yoshiyuki
url: https://hitomi.la/doujinshi/sono-namida-ni-yowain-dayo-|-그-눈물에-약한-거라고-한국어-1701971.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1596857753.87 (Aug 8)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None

[Gallery]
갤러리 넘버: 1701971

제목: Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고

작가: yasson yoshiyuki

그룹: N/A

타입: doujinshi

시리즈: yowamushi pedal

캐릭터: sangaku manami, yasutomo arakita

태그: male:males only, male:tomgirl, male:yaoi

언어: Korean

[File Names]
[0001] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\1.png
[0002] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\2.png
[0003] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\3.png
[0004] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\4.png
[0005] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\5.png
[0006] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\6.png
[0007] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
[0008] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\8.png
[0009] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\9.png
[0010] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\10.png
[0011] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\11.png
[0012] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\12.png
[0013] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\13.png
[0014] hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\14.png

[URLs]
[0001] https://ba.hitomi.la/images/4/3a/bfd184858e6ff31b907a2b5d8c9743c4a161aa9a4abb046e7c7fafdf0425f3a4.png
[0002] https://ca.hitomi.la/images/f/35/964d677266af8953bcc6ec04cdd640e2a1312ca9f0c8df9a01c687aff216135f.png
[0003] https://ba.hitomi.la/images/6/b8/73353110fb8ff8aa7211161ddefdcb143fff797a2b843320f0520b327ebe4b86.png
[0004] https://ca.hitomi.la/images/7/32/64c8c1fed7663bfb2694dba34302dc390e709198b95ca0e5658561c6c08d0327.png
[0005] https://ca.hitomi.la/images/5/a1/a7a105f59d9c1ea11f6eb6673749800d3cbe3f12ad5a1d36152b300e494d7a15.png
[0006] https://aa.hitomi.la/images/e/e1/437892f5a5e4e6e9dd43443a54aa78607c6043ad2f32c98b3c3d661fd9622e1e.png
[0007] https://ca.hitomi.la/images/7/1d/3f63f2c7611f2885d99941dbc57c0eaa3fe6ca88320434c6ede66d1d047dc1d7.png
[0008] https://ba.hitomi.la/images/1/be/326b7a6288ab1a66dfd46b6d90b993126e1a6546a6a134c7091e03f7043e3be1.png
[0009] https://ca.hitomi.la/images/2/77/f1a111ba0bbe7f6ab59a21517626e327edd93ad0cb2458234d0b052709bad772.png
[0010] https://ca.hitomi.la/images/7/86/7c7f47242d4176707078bcdfab06081a606d67e2625a6119cfbdcc343ba2c867.png
[0011] https://ca.hitomi.la/images/e/a1/833bb592f0cb080701d0d69d52c089a5eb9c1c5fb3f08fc5b61bd92adcc1aa1e.png
[0012] https://aa.hitomi.la/images/9/36/0f90bec37e41fa32d6647fc8cbca452e140e355d68ba3d9c4a6ec1dcfbeb5369.png
[0013] https://aa.hitomi.la/images/6/75/1c79b6bcc9e2079c31123c1db57f0010996aa46fff8ebdb9c825251cdb7ba756.png
[0014] https://ba.hitomi.la/images/a/97/3d7d14205ff65ea8fb0039236db1ff4f13b70542491f94cbb5f0d68d76d0a97a.png

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 14
get_title__

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[Yasson Yoshiyuki] Sono Namida Ni Yowain Dayo ｜ 그 눈물에 약한 거라고 (1701971)\7.png
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/sono-namida-ni-yowain-dayo-%7C-%EA%B7%B8-%EB%88%88%EB%AC%BC%EC%97%90-%EC%95%BD%ED%95%9C-%EA%B1%B0%EB%9D%BC%EA%B3%A0-%ED%95%9C%EA%B5%AD%EC%96%B4-1701971.html

10시까지 잘 되는데요...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
감사합니다 정말 잘됐네요ㅠㅠ

**Comment by dktbdh** [comment]
아이고 감사합니다..

**Comment by adeline1225** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

기기 문제로 32비트만 사용이 가능해서 2.7h 버전을 쓰고 있는데 동일한 문제가 발생합니다. 2.7 버전의 픽스를 지원 해주실 수 없나요?

**Comment by adeline1225** [comment]
기기 문제로 32비트만 사용이 가능해서 2.7h 버전을 쓰고있는데 동일한 문제가 발생합니다. 2.7 버전의 픽스를 지원해주실 수 없나요?
