### ISSUE TITLE
눈동자(히X미) 다운 멈춤현상

### ISSUE THREAD

**Issue by msimsihan** [KurtBestor/Hitomi-Downloader#2216]
다운로드 시 처음에는 정상적으로 다운이 되다가 갑자기 다운속도가 0이 되면서 다운이 멈춥니다.
8장 짜리는 다운이 정상적으로 되는것을 확인하였지만 나머지 것들은 모두 같은 현상으로 똑같은 장수만 다운되고 멈춰버립니다.
[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.19041
order: 0
group: False
input: [Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)
dir: hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)
zip: 
type: hitomi
artist: endou okito
url: https://hitomi.la/galleries/1702223.html
valid: True
done: False
range: None
range_p: None
single: False
time: 1596869063.74 (Aug 8)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None

[Gallery]
갤러리 넘버: 1702223

제목: IkaZuka-san wa Bidou Danishinai

작가: endou okito

그룹: 70 nenshiki yuukyuu kikan

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: female:big breasts, female:females only, female:lactation, female:schoolgirl uniform, female:sex toys, female:strap-on, female:twintails, female:yuri

언어: Korean

[File Names]
[0001] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\01.jpg
[0002] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\02.jpg
[0003] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\03.jpg
[0004] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\04.jpg
[0005] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\05.jpg
[0006] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\06.jpg
[0007] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\07.jpg
[0008] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\08.jpg
[0009] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\09.jpg
[0010] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\10.jpg
[0011] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\11.jpg
[0012] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\12.jpg
[0013] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\13.jpg
[0014] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\14.jpg
[0015] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\15.jpg
[0016] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\16.jpg
[0017] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\17.jpg
[0018] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\18.jpg
[0019] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\19.jpg
[0020] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\20.jpg
[0021] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\21.jpg
[0022] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\22.jpg
[0023] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\23.jpg
[0024] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\24.jpg
[0025] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
[0026] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\26.jpg
[0027] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\27.jpg
[0028] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\28.jpg
[0029] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\29.jpg
[0030] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\30.jpg
[0031] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\31.jpg
[0032] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\32.jpg
[0033] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\33.jpg
[0034] hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg

[URLs]
[0001] https://aa.hitomi.la/images/d/81/e08c21bf24adf12f7686ddee81de5d9cbb7c54cfed251bd2c900fe8675cc881d.jpg
[0002] https://ba.hitomi.la/images/d/b5/78b4f6538697b280b1d0556a2968138c9457eee55f21ea3d386336405f863b5d.jpg
[0003] https://aa.hitomi.la/images/f/5d/72fe47274a5b145e412c6a76bd6e20956e93f16441fa3ece89448d9f69e875df.jpg
[0004] https://ba.hitomi.la/images/e/9a/63a7c306e209f75b1a2f8d493c7140a2a5a868f70c7faeed939a6df77dc8f9ae.jpg
[0005] https://ba.hitomi.la/images/5/be/d7d21e49370b355a03ab9b2df616718ce6b2116379bf40d31265cf0e70e17be5.jpg
[0006] https://ca.hitomi.la/images/2/6e/d89af1d6d3d119b08204468b845d7810643987d23a93bbd7cfba5f3b658a86e2.jpg
[0007] https://aa.hitomi.la/images/c/ea/090b703f62560961e7d7f85f7cb20b81ae1b53f101ae7fcf3e52232aa93d1eac.jpg
[0008] https://ca.hitomi.la/images/8/f8/988392d4a4ff204f5bd2701da72ba82977a5367d82878c3005fb7e3e47d7af88.jpg
[0009] https://ca.hitomi.la/images/d/bc/e3d0f5e341cb1d35970523dc93678b2d85bae48d77f6f85adbdb890ec64a5bcd.jpg
[0010] https://aa.hitomi.la/images/b/d2/c0385319bb44a59e0b5dae654b9eacc96cac2a1515c47d7d8e590904617dfd2b.jpg
[0011] https://ba.hitomi.la/images/3/d6/eed6d4f68bc89a6c27cd089e410bebe0bd073d5fc4e9d3f43b48ff5dedae2d63.jpg
[0012] https://aa.hitomi.la/images/f/5a/878e0951ded279b83b0d377e21c2f380c1d15ba273f25ef27ad6abac47ff65af.jpg
[0013] https://ba.hitomi.la/images/9/e8/4ffbff1f425f8cccb561184606db270f70b25a399ed76c74a09f1c75c9c70e89.jpg
[0014] https://aa.hitomi.la/images/d/d2/8c115315d3618552fb8baff80f57f2691e4b7bfdf33602da7da0dd55ec4a5d2d.jpg
[0015] https://ba.hitomi.la/images/6/76/0a8eb0c5f3df6d25659b77d244a33fde42140b2190dd30158e901097b832b766.jpg
[0016] https://ba.hitomi.la/images/1/fd/bb7ed7187ab6ccd0d92c380cc6908ed8763fc0e7b8b5a98ce61042a2549c0fd1.jpg
[0017] https://ca.hitomi.la/images/7/7a/5b8ed6ba26ed3974ce371c846e72afc1eb6e646a6abf9585ef8667813b1497a7.jpg
[0018] https://ca.hitomi.la/images/9/a4/e4c7143b4eb3ca88fa300b3d107322a2d8b6df07bbf2e4fcc36f6f2e9eb69a49.jpg
[0019] https://ca.hitomi.la/images/1/65/ce6cc1037283ee9525c3e3ae9e96cfbcc1c88ecc59065b3ff0ccf39c4b7af651.jpg
[0020] https://aa.hitomi.la/images/2/f3/24ef7a7884109fa56363ebe24a8a2229646d174ff7467a04be9dc347a60a9f32.jpg
[0021] https://aa.hitomi.la/images/e/cf/3620a87a2fc077290683433ce59440812b26e55e5f8f11d0d32a924a10dadcfe.jpg
[0022] https://ca.hitomi.la/images/c/d1/6f748f990d098844a9950bfde019ca930a6693b62e1514a4179a314c8981ed1c.jpg
[0023] https://ba.hitomi.la/images/9/dc/a732b825b0e1d0ed9bdbb36ebf19a37ad5cd065547d60c35d6568fd581987dc9.jpg
[0024] https://ca.hitomi.la/images/4/da/c46dfe5e59cb05ce187a746d0dad16e37d152197958ade846df66d226d05dda4.jpg
[0025] https://aa.hitomi.la/images/f/2d/aa4f1f04e7f5284cb75b7b0974682923515cd64b4110f3ab8defe94999a062df.jpg
[0026] https://ca.hitomi.la/images/8/c5/e510c25e9251e5a9fb7819fa46d5843f2ac89946af42f959e8f78e3bc1a1dc58.jpg
[0027] https://ca.hitomi.la/images/0/ef/04761cb7c57f9ffff7092f357c52822692da054e9d284f08f139df5eedd88ef0.jpg
[0028] https://ca.hitomi.la/images/4/59/f2dfd17dd6c87e0a658eaacc9b25abec60bc5c5d2ab216818bf56dfb4e833594.jpg
[0029] https://ba.hitomi.la/images/d/61/e12c0b0265342529b9addf0e11393900aea671806688162e0eaa5aa7b9dd661d.jpg
[0030] https://aa.hitomi.la/images/0/d2/ad24e740e0f83d0ec072502ef8bfea7d1c997c06e695235dec857648f82ecd20.jpg
[0031] https://ba.hitomi.la/images/a/a0/7fc0cb0853ecce87b089cf26ff03ec2c88860e5284a6911b753c8c45e698ea0a.jpg
[0032] https://ba.hitomi.la/images/0/82/4612e3d6ef49fa816495f29506c4dc0ebefbe5b883d6a34c1cf94fed395af820.jpg
[0033] https://ba.hitomi.la/images/9/fa/ea0346be75e0bc7ce0758ae95280cff98b5e54f30e0e7d9ce482a168ef3f1fa9.jpg
[0034] https://ca.hitomi.la/images/d/2f/f4f8be499b68b5ea59414790cd63b93a7b91b9c2955914be9ef59d8d37f562fd.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 34

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\34.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

Fail : \\?\D:\애니\~낙원추방\ \hitomi_downloader_GUI\hitomi_downloaded\[Endou Okito] IkaZuka-san wa Bidou Danishinai (1702223)\25.jpg
Traceback (most recent call last):
File "downloader", line 821, in download
Exception: 403

**Comment by Water-Sleep** [comment]
저도 같은 현상입니다.
100장이라면 90장 정도만 다운 받고 멈춰버리네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217

**Comment by msimsihan** [comment]
해결되었습니다.!감사합니다
