### ISSUE TITLE
스크립트 질문

### ISSUE THREAD

**Issue by meloncafe** [KurtBestor/Hitomi-Downloader#2221]
[arcalive.zip](https://github.com/KurtBestor/Hitomi-Downloader/files/5045145/arcalive.zip)

https://arca.live/b/lastorigin/5065039?p=1

아카라이브 다운로드 스크립트를 제작중인데 ssl handshake오류가 발생합니다

---------------------------

Traceback (most recent call last):
File "downloader", line 813, in download
Exception: //lll.arca.live/5e/5ebdd8804e6856004deaee74480fa5a63140a0ac158475ec703196682c153a51.png
Traceback (most recent call last):
File "downloader", line 809, in download
File "site-packages\urllib3\request", line 76, in request
File "site-packages\urllib3\request", line 97, in request_encode_url
File "site-packages\urllib3\poolmanager", line 369, in urlopen
File "site-packages\urllib3\poolmanager", line 330, in urlopen
File "site-packages\urllib3\connectionpool", line 760, in urlopen
File "site-packages\urllib3\connectionpool", line 760, in urlopen
File "site-packages\urllib3\connectionpool", line 720, in urlopen
File "site-packages\urllib3\util\retry", line 436, in increment
MaxRetryError: HTTPSConnectionPool(host='lll.arca.live', port=443): Max retries exceeded with url: /5e/5ebdd8804e6856004deaee74480fa5a63140a0ac158475ec703196682c153a51.png (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

---------------------------

스크립트단에서 처리할 방법이 있을까요?

그리고 스크립트에서 beautifulsoup을 사용할 때 css selector를 사용할 수 있으면 필요한 아이템 찾기가 더 쉬울것 같습니다

**Comment by meloncafe** [comment]
그리고 스크립트에서 beautifulsoup을 사용할 때 css selector를 사용할 수 있으면 필요한 아이템 찾기가 더 쉬울것 같습니다

**Comment by KurtBestor** [comment]
URL 앞에 프로토콜 빠졌네요.
