### ISSUE TITLE
애니24 스크립트 추가할려고하니깐 올바르지안은 형식이라고 하네요 ..

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#2227]
제목이 곧 내용 ... 

Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4301, in exec_script
  File "dynamic_module_1", line 14, in <module>
ImportError: No module named page_selector

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2165#issuecomment-662711161

**Comment by kenasis428** [comment]
잘 작동합니다 !
