### ISSUE TITLE
Hitomi.la incomplete download

### ISSUE THREAD

**Issue by callacall** [KurtBestor/Hitomi-Downloader#2230]
As some have reported in your discord, there seems to problem with download progress whenever i try to download from hitomi.la
![Untitled](https://user-images.githubusercontent.com/59549156/89731467-c937d980-da79-11ea-87d7-58d79434dfa0.png)
[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)

version: 2.8a (20-06-10 11:17:37 GMT+0)
platform: Windows-10-10.0.17763
order: 0
group: False
input: https://hitomi.la/doujinshi/bakunyuu-gyaru-no-ore-no-kanojo-ga-teniser-no-yarichin-otoko-ni-netorareta-hanashi-中文-1703315.html
dir: hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)
zip: 
type: hitomi
artist: nanohana
url: https://hitomi.la/doujinshi/bakunyuu-gyaru-no-ore-no-kanojo-ga-teniser-no-yarichin-otoko-ni-netorareta-hanashi-中文-1703315.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1596973848.38 (Aug 9)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None

[Gallery]
Gallery ID: 1703315

Title: Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi

Artists: nanohana

Groups: november.

Types: doujinshi

Series: azur lane

Characters: bremerton

Tags: female:ahegao, female:assjob, female:beauty mark, female:big areolae, female:big breasts, female:blackmail, female:blowjob, female:leg lock, female:mind break, female:nakadashi, female:netorare, female:paizuri, female:sole female, female:twintails, female:x-ray, full color, male:big penis, male:condom, male:gyaru-oh, male:sole male

Language: Chinese

[File Names]
[0001] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0000.jpg
[0002] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0001.jpg
[0003] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0002.jpg
[0004] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0003.jpg
[0005] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0004.jpg
[0006] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0005.jpg
[0007] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0006.jpg
[0008] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0007.jpg
[0009] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0008.jpg
[0010] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0009.jpg
[0011] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0010.jpg
[0012] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0011.jpg
[0013] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0012.jpg
[0014] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0013.jpg
[0015] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0014.jpg
[0016] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0015.jpg
[0017] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0016.jpg
[0018] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0017.jpg
[0019] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0018.jpg
[0020] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0019.jpg
[0021] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0020.jpg
[0022] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0021.jpg
[0023] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0022.jpg
[0024] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0023.jpg
[0025] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0024.jpg
[0026] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0025.jpg
[0027] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0026.jpg
[0028] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0027.jpg
[0029] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0028.jpg
[0030] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0029.jpg
[0031] hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0030.jpg

[URLs]
[0001] https://aa.hitomi.la/images/c/03/37f33904d300a24ec690e248b43f6f98527f999e24f8a95125e9a41e52af103c.jpg
[0002] https://aa.hitomi.la/images/9/51/55f875f0eec5439eeaa6c218835369f72be0048724d93b4e8547d0fcca8f1519.jpg
[0003] https://ba.hitomi.la/images/6/b5/47c07026c3995413cd5dadce3dc0af1db4127acc7a558eca8eb5adabb600cb56.jpg
[0004] https://ba.hitomi.la/images/9/0a/51dbf90acbcda09bf3ab9339b038538d9d5e56fb3a64ca6a9f8573202e3f80a9.jpg
[0005] https://aa.hitomi.la/images/3/1e/e54a42ec57e165929faffe19f9fce3614ae7d23eeeeb8ff87c710dddc3b021e3.jpg
[0006] https://ba.hitomi.la/images/c/73/43ea0acb77ff8271f0fc4889109ec5eaaebe2c9002e4afde671a2b594f29d73c.jpg
[0007] https://aa.hitomi.la/images/4/cc/10c29dcd99d549031b1752d75cbb1dd465ef90a1a3d368ec35b6d87ed3b4acc4.jpg
[0008] https://ba.hitomi.la/images/7/67/378942b2411494daee66a95e94121d42ed15b9b9fb716a5ced78c559e7d25677.jpg
[0009] https://aa.hitomi.la/images/a/66/eebe30009a84b7c368047ef7fea6125795c4c3f88bb96e07e32228995b60c66a.jpg
[0010] https://ca.hitomi.la/images/f/8c/8003350626bbd03eb2e8136bafcc9e76528f613b39b89efc3c0ddb4ac3e238cf.jpg
[0011] https://ba.hitomi.la/images/4/ac/452a86dd9927569fac368081efdd444dfa2e936ddab6d3ea975aaa09a83b1ac4.jpg
[0012] https://aa.hitomi.la/images/a/ff/2047c0ba7128374bd16ae5457b51a75cbdf987c099616451cedc04560f4c0ffa.jpg
[0013] https://aa.hitomi.la/images/3/cf/50f44e532ff01616638874d9c6f098033d56eac6e8ccba56a0535af4b2cf1cf3.jpg
[0014] https://aa.hitomi.la/images/5/ff/5250d5258ea3b2251b6a56e83a6d31903049f1813de8b89726acd817c4667ff5.jpg
[0015] https://ca.hitomi.la/images/a/e0/8461645ca08b27cc92354719bf2cf2106700586760c595d59107c0ac24f61e0a.jpg
[0016] https://ca.hitomi.la/images/c/a4/efad2342c0a11c494f79f9281fbd7d4b73236de08c3c464068271b7ad5481a4c.jpg
[0017] https://ca.hitomi.la/images/7/86/feab6655de21bd2c27610c9aed20847feb37dadb661f45f90c488e799f6e0867.jpg
[0018] https://ca.hitomi.la/images/4/9b/100f0ecd072017579a039e14d3660f288566076d112da66afd422c3fe53759b4.jpg
[0019] https://ca.hitomi.la/images/c/c2/e9177f2f1690f38e6df05d0437a9c972dffebdc4e9f920e1cfb10cf0a65adc2c.jpg
[0020] https://ba.hitomi.la/images/3/b5/4b6de64e1a0617c5848d2c0dfe37e1ebdbb09c54a0f3b0452d8406a0a1a89b53.jpg
[0021] https://aa.hitomi.la/images/1/6c/27e9cc35fd65c63e58ce7d240ca0a243c87eed8c03d9ac45adf718e54e59c6c1.jpg
[0022] https://ba.hitomi.la/images/a/82/aaad5b1981759aec908b24e26cf62483c4b9e40d47cd9699393e9e6b754de82a.jpg
[0023] https://ba.hitomi.la/images/b/fd/4a0af3675e22910424673d51a04af8c8f03eed84c425b3381e07ec6f5a2f8fdb.jpg
[0024] https://ca.hitomi.la/images/7/86/124d3474894aa41253a788e9990714e43ba21f3587a850dcdeb41cfd69462867.jpg
[0025] https://ba.hitomi.la/images/1/9a/e32fdf3ac5ea402aa2d26e522892b42059184e3ba5d70c900d2d9b85959129a1.jpg
[0026] https://ca.hitomi.la/images/3/dd/06d851d361a4f4c1d70dfc0072c86a9401b8b216d8ebc9859861c1df6ea23dd3.jpg
[0027] https://ba.hitomi.la/images/2/d0/a9c0755e20312591a303e07d39dc98507d27ce59bf3be209fe697936c95aed02.jpg
[0028] https://ba.hitomi.la/images/d/2b/07b424419a339ce207fbecc8188197d4b722ef4a51b844fcce8e4f0855bad2bd.jpg
[0029] https://ca.hitomi.la/images/e/53/0f60c1c0236172c13d55e073e0e1e06a3d458c5aea45bf0644ab3d99dbf0653e.jpg
[0030] https://ba.hitomi.la/images/1/52/ac92d1a805a4bb2030c9b65603cff3dc0e2bac47af78bc7bdfe13c6f2a531521.jpg
[0031] https://ba.hitomi.la/images/e/dc/40e1ace67a2b5f7e9580996d5992d59e162282129396ea2280ec0de1780c4dce.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 31
get_title__

Fail_404 : \\?\D:\Stuffs\Hitomi\hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0000.jpg
Traceback (most recent call last):
File "downloader", line 780, in download
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\Stuffs\Hitomi\hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0003.jpg
Traceback (most recent call last):
File "downloader", line 780, in download
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/bakunyuu-gyaru-no-ore-no-kanojo-ga-teniser-no-yarichin-otoko-ni-netorareta-hanashi-中文-1703315.html

get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 31

Fail_404 : \\?\D:\Stuffs\Hitomi\hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0000.jpg
Traceback (most recent call last):
File "downloader", line 780, in download
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\Stuffs\Hitomi\hitomi_downloaded\[Nanohana] Bakunyuu Gyaru no Ore no Kanojo ga Teniser no Yarichin Otoko ni Netorareta Hanashi (1703315)\0003.jpg
Traceback (most recent call last):
File "downloader", line 780, in download
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/bakunyuu-gyaru-no-ore-no-kanojo-ga-teniser-no-yarichin-otoko-ni-netorareta-hanashi-中文-1703315.html

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217

**Comment by callacall** [comment]
seems everything is back to normal so far. thank you.
