### ISSUE TITLE
히X미 다운중 멈춰버립니다.

### ISSUE THREAD

**Issue by cdreadme** [KurtBestor/Hitomi-Downloader#2233]
#2214 의 테스트 프로그램을 사용했으나 동일한 증상이 나옵니다.

version: 2.8a (20-08-07 15:45:26 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 5
group: False
input: https://hitomi.la/galleries/1612934.html
dir: hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)
zip: 
type: hitomi
artist: as109
url: https://hitomi.la/cg/kanzen-de-ryoujoku-na-maid--decensored--日本語-1612934.html
valid: True
done: False
range: None
range_p: None
single: False
time: 1596986103.3351774 (Aug 10)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None

[Gallery]
갤러리 넘버: 1612934

제목: Kanzen de Ryoujoku na Maid (decensored)

작가: as109

그룹: N/A

타입: artistcg

시리즈: touhou project

캐릭터: sakuya izayoi

태그: female:ahegao, female:blood, female:bondage, female:defloration, female:gaping, female:maid, female:rape, female:sex toys, female:shibari, female:sole female, female:stockings, male:first person perspective, male:sole male, uncensored, variant set

언어: Japanese

[File Names]
[0001] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\1.jpg
[0002] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0001.jpg
[0003] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0002.png
[0004] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0003.png
[0005] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0004.png
[0006] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0005.png
[0007] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0006.png
[0008] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0007.png
[0009] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\9.png
[0010] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0009.png
[0011] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0010.png
[0012] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0011.png
[0013] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0012.jpg
[0014] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\14.jpg
[0015] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0014.png
[0016] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0015.jpg
[0017] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0016.png
[0018] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0017.jpg
[0019] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0018.jpg
[0020] hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0019.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/4/1c/6c920d6cea48e6ab6c53ebaa510901c29a1761887c86b08695fee0ca174cd1c4.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ca.hitomi.la/images/7/41/fc0bff4e767d00e47d2fb3421944b8852e2c43696ed2f5ea86da99b8a9716417.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/4/cc/ad8732e4ac3c3b611cbaa9319adb8c322f86991bf28ceb0a4fb986806d9efcc4.png
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/6/6d/947278109c058a7e364beef809b90aaa944eb5fa447633ff58dfbb57e85cf6d6.png
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/f/87/6b36264420c68beeb9b1c6316524640ed120f15d34f5dbdee21c2a171073887f.png
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ca.hitomi.la/images/7/c8/e0bf45941d9e17b683169cc1a69e4d131adaea983356efe7cf6a463ac1b11c87.png
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/6/ff/8cead6072c7beb39a877e21bbd26d726f7e0ea89bb7898088e3e6e50b1b62ff6.png
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ca.hitomi.la/images/e/ec/5947c1f33cb17eb9bf0f905f4ccaf94ae2f9bf78476a5b5378d1e76285b55ece.png
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/c/20/5846c38791ef242ad1e46d056723cfdf2eed561de5bf0015284ebfca7207c20c.png
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/b/5e/bb9e91ada5e1b09e61e11b6d5568611afe1ab8b1824c1f3a4e414075ee22d5eb.png
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/1/d9/1a3ac697319738d0efc7cbfff70e9cb9bc30b3349bd292de5f32cb4973481d91.png
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/1/02/2a91fed63b46da3b5274eabd4a2409c75f344dc7ee68155be92fc3117fe59021.png
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ca.hitomi.la/images/e/c5/03831876dbb5443e1a5b3d82e5a8fac72a61fcd8d149fee531201adcc1abdc5e.jpg
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/f/28/bee84949e00eb05b0a8c869a689f3055fd4a0d9bdd0f0d9c320f82bc53eb428f.jpg
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ca.hitomi.la/images/c/e9/0d47bbabfe07312ccd1123e4f464f415355f25ebee70f3f11037a85f7bd77e9c.png
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/1/94/5c8b1b2a947c047e860db885318f4ff670669bb56489b9067dabe0efdf9b7941.jpg
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/2/52/b8dea565a93d0991884fbd3327627fc825d3027a1bfbbd99f582d6a18e110522.png
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/b/79/2019b31ef64badc76a0f4b60998680514f3d5494cde33349ff4d42c7f615d79b.jpg
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://aa.hitomi.la/images/4/b1/4aa2a62c8ff0f3649cbbd6fd3a06e3111a90931970b08bb72eddd4c7876f8b14.jpg
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1612934.html) ---> https://ba.hitomi.la/images/f/27/cfab806110360d31c4f4096a32f5191acc56666c71f8865ca2a58768fcd1327f.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 20
get_title__

Fail : \\?\G:\hi_loader\hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0000.jpg
Traceback (most recent call last):
File "downloader", line 855, in download
OSError: [Errno 22] Invalid argument: '\\\\?\\G:\\hi_loader\\hi_down_A\\As109\\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\\0000.jpg'

Fail : \\?\G:\hi_loader\hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0008.png
Traceback (most recent call last):
File "downloader", line 855, in download
OSError: [Errno 22] Invalid argument: '\\\\?\\G:\\hi_loader\\hi_down_A\\As109\\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\\0008.png'

Fail : \\?\G:\hi_loader\hi_down_A\As109\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\0013.jpg
Traceback (most recent call last):
File "downloader", line 855, in download
OSError: [Errno 22] Invalid argument: '\\\\?\\G:\\hi_loader\\hi_down_A\\As109\\Kanzen de Ryoujoku na Maid (decensored) [Touhou Project] [Japanese] (1612934)\\0013.jpg'

------------ 이하 동일 에러 

stop
valid=False 1
EOT: https://hitomi.la/galleries/1612934.html

======추가적으로 목록 받기도 안됩니다.
Traceback (most recent call last):
  File "hitomi_searcher", line 215, in download_json
  File "hitomi_searcher", line 412, in download_json_
Exception: http://kurtbestorthonanywhere.com/static2/h_data/galleries0.zip
No active exception to reraise

**Comment by KurtBestor** [comment]
가상머신에서 실행하시나요?

**Comment by wooeorbs** [comment]
테스트 파일을 원본 파일에 덮어 써서 생긴 문젭니다.
테스트 파일을 따로 실행시키고
이런 상태에 기본 데이터 파일을 받고
원본 파일에 다시 덮으면 잘 됩니다.

**Comment by cdreadme** [comment]
> 가상머신에서 실행하시나요?

공유기를 통한 인트라넷 드라이버에서 실행합니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
