### ISSUE TITLE
웨이보 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by cocokakao** [KurtBestor/Hitomi-Downloader#2240]
먼저 항상 좋은 프로그램 만드시고 업뎃해주시는 점 감사드립니다.

다름 아니라 웨이보 주소로 이미지 크롤링을 하는데 먹통이 된 것 같습니다. 

테스트로 올려주신 버전도 먹통인걸 확인했습니다.

작업정보 로그는 아래에 첨부합니다

Invalid: [weibo] https://weibo.com / p / 1005051907598035

version: 2.8a (20-08-10 11:52:56 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 3
group: False
input: https://weibo.com/p/1005051907598035
dir: 
zip: 
type: weibo
artist: None
url: https://weibo.com/u/1907598035
valid: False
done: True
range: None
range_p: None
single: False
time: 1597070625.4091952 (Aug 10)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf solved
uid: 1907598035, oid:1005051907598035
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\weibo_downloader", line 52, in read
File "extractor\weibo_downloader", line 179, in get_imgs
File "extractor\weibo_downloader", line 166, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://weibo.com/p/1005051907598035

clf solved
uid: 1907598035, oid:1005051907598035
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\weibo_downloader", line 52, in read
File "extractor\weibo_downloader", line 179, in get_imgs
File "extractor\weibo_downloader", line 166, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://weibo.com/p/1005051907598035

읽어주셔서 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by cocokakao** [comment]
정상 작동됩니다 감사합니다 ㅎㅎ
