### ISSUE TITLE
v3.0 no longer downloads the original-sized images from twitter

### ISSUE THREAD

**Issue by poyshu** [KurtBestor/Hitomi-Downloader#2244]
Hello,
Just found the new version (v3.0) no longer downloads the original-sized images from twitter.
Not sure if this is by design, or there's a setting for this. (I didn't find one) If this is an unintentional change, I hope it gets fixed soon.

By the way, I really appreciate your work; this is definitely by far one of the best downloaders I've found. I can't thank you more.

(Unlike the old version, the fetched URLs don't have ":orig" )
----------- Part of the log ------------
[File Names]
[0001] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288832480351358979_p0.png
[0002] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288832480351358979_p1.png
[0003] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288831841219358720_p0.jpg
[0004] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288831841219358720_p1.jpg
[0005] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288831481847017473_p0.png
[0006] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288831481847017473_p1.jpg
[0007] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288824380319870977_p0.png
[0008] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288824380319870977_p1.png
[0009] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288821749451067392_p0.png
[0010] hitomi_downloaded_twitter\Twitter (@//Twitter)\[20-07-30] 1288821749451067392_p1.jpg

[URLs]
[0001] LazyUrl_twitter(https://twitter.com/Twitter/status/1288832480351358979) ---> https://pbs.twimg.com/media/EeLaGc3U4AAhyU8.png
[0002] LazyUrl_twitter(https://twitter.com/Twitter/status/1288832480351358979) ---> https://pbs.twimg.com/media/EeLaQ2sUEAYBbgu.png
[0003] LazyUrl_twitter(https://twitter.com/Twitter/status/1288831841219358720) ---> https://pbs.twimg.com/media/EeLY0wtXoAUjyYQ.jpg
[0004] LazyUrl_twitter(https://twitter.com/Twitter/status/1288831841219358720) ---> https://pbs.twimg.com/media/EeLY6TcXsAEzYcA.jpg
[0005] LazyUrl_twitter(https://twitter.com/Twitter/status/1288831481847017473) ---> https://pbs.twimg.com/media/EeLY9_2VAAAsrAc.png
[0006] LazyUrl_twitter(https://twitter.com/Twitter/status/1288831481847017473) ---> https://pbs.twimg.com/media/EeLZXeMUYAItGbA.jpg
[0007] LazyUrl_twitter(https://twitter.com/Twitter/status/1288824380319870977) ---> https://pbs.twimg.com/media/EeLS3qTUEAAQ1fN.png
[0008] LazyUrl_twitter(https://twitter.com/Twitter/status/1288824380319870977) ---> https://pbs.twimg.com/media/EeLS6UKVAAIz2ue.png
[0009] LazyUrl_twitter(https://twitter.com/Twitter/status/1288821749451067392) ---> https://pbs.twimg.com/media/EeLQe5lVoAA2tEU.png
[0010] LazyUrl_twitter(https://twitter.com/Twitter/status/1288821749451067392) ---> https://pbs.twimg.com/media/EeLQiSiUMAAVik1.jpg

[Messages]
multiple tweets
types: img, video
max_pos=None, imgs=0
stop
EOT: https://twitter.com/twitter
--------------- Log ends -----------------

(oops I think I accidentally @ mentioned twitter hope they didn't get alarmed, edited them out)

**Comment by Rounlet** [comment]
저도 동일한 증상입니다.

다운로더로 받았을 때 82kb인데
직접 다운로드하면 166kb입니다.

트위터가 지금 전반적으로 이상 있어 보입니다. 
영상 받는 것도 그렇고..

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
빠른 피드백 감사합니다.

테스트 결과,
영상은 정상적으로 받아지는데
이미지 크기는 여전히 그대로입니다.

![주석 2020-08-12 063733](https://user-images.githubusercontent.com/47098778/89951538-956dd700-dc66-11ea-9169-c54de0fa7ce9.png)

이게 직접 다운로드한 이미지고 166kb 입니다.

![주석 2020-08-12 063747](https://user-images.githubusercontent.com/47098778/89951545-9868c780-dc66-11ea-9be8-9300942ea3bd.png)

이게 다운로더를 통해 받은 이미지고 82.7kb 입니다.

확인 부탁드립니다.

**Comment by KurtBestor** [comment]
@Rounlet 받아진 파일 지우고 다시 다운로드 하세요.

**Comment by Rounlet** [comment]
네, 처음에 시도할 때도 받아진 파일 지우고 시도했고
기존 설정없이 테스트 버전 받아서 바로 다운로드 해봤을 때도 결과는 동일합니다.

영상은 동일하게 잘 받아집니다.

![주석 2020-08-12 065737](https://user-images.githubusercontent.com/47098778/89953074-60af4f00-dc69-11ea-9be3-529e2dba734c.png)

![주석 2020-08-12 070108](https://user-images.githubusercontent.com/47098778/89953223-a0763680-dc69-11ea-85a5-26e06f24c160.png)

위 사진은 다운로더로 방금 받은 이미지 정보 입니다.

**Comment by KurtBestor** [comment]
개별 트윗 주소로 다운로드 했나요?

**Comment by Rounlet** [comment]
아닙니다.
![주석 2020-08-12 070856](https://user-images.githubusercontent.com/47098778/89953788-bc2e0c80-dc6a-11ea-89ff-9248ff23814f.png)
요렇게 다운로더에 들어갔으며

 저 사진은 다운로드된 폴더에서 한개만 빼서 대조한 것 입니다.

**Comment by KurtBestor** [comment]
Legacy 방식으로 오래된 트윗까지 불러올 수 있었는데 막혔네요. 비슷한 방식인 [twMediaDownloader](https://github.com/furyutei/twMediaDownloader) 도 작동하지 않아요.
실패하면 새 API로 다운로드하도록 했는데 이건 :orig 처리가 안 되어있어요.
새 API 는 오래된 트윗을 불러올 수 없어서 일단 다른 방법이 있는지 시도해볼게요.

**Comment by Rounlet** [comment]
넵.. 부탁드리겠습니다..!ㅠㅠ

**Comment by poyshu** [comment]
That was frustrating. Which makes me wonder is twitter secretly watching this thread. Anyway, thank you for your hard work.

**Comment by yuchan39** [comment]
안녕하세요.

다운로더 작동 확인 중 발생한 문제입니다.

Invalid: [twitter] https://twitter.com / R_Kitada

version: 3.0 (20-08-11 17:19:50 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 11
group: False
input: https://twitter.com/R_Kitada
dir: 
zip: 
type: twitter
artist: きただりょうま✍️エグゼロスTVアニメ放送中
url: https://twitter.com/R_Kitada
valid: False
done: True
range: ~9999999
range_p: None
single: False
time: 1597218819.7850485 (Aug 12)
tags: []
goodbyedpi: None
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
multiple tweets
types: img, video
max_pos=None, imgs=0
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
over try
Traceback (most recent call last):
File "extractor\twitter_downloader", line 309, in get_imgs
File "extractor\twitter_downloader", line 408, in get_imgs_legacy
Exception: No imgs

cursor: None
cursor: None
'1186249145704517633'
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\twitter_downloader", line 138, in read
File "extractor\twitter_downloader", line 317, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
KeyError: '1186249145704517633'

Invalid: fail=True
EOT: https://twitter.com/R_Kitada

multiple tweets
types: img, video
max_pos=None, imgs=0
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
over try
Traceback (most recent call last):
File "extractor\twitter_downloader", line 309, in get_imgs
File "extractor\twitter_downloader", line 408, in get_imgs_legacy
Exception: No imgs

cursor: None
cursor: None
'1186249145704517633'
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\twitter_downloader", line 138, in read
File "extractor\twitter_downloader", line 317, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
KeyError: '1186249145704517633'

Invalid: fail=True
EOT: https://twitter.com/R_Kitada

multiple tweets
types: img, video
max_pos=None, imgs=0
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
over try
Traceback (most recent call last):
File "extractor\twitter_downloader", line 309, in get_imgs
File "extractor\twitter_downloader", line 408, in get_imgs_legacy
Exception: No imgs

cursor: None
cursor: None
'1186249145704517633'
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\twitter_downloader", line 138, in read
File "extractor\twitter_downloader", line 317, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
KeyError: '1186249145704517633'

Invalid: fail=True
EOT: https://twitter.com/R_Kitada

---------------------------------------------------------------------------------------------------------

Invalid: [twitter] https://twitter.com / kasu1923

version: 3.0 (20-08-11 17:19:50 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 6
group: False
input: https://twitter.com/kasu1923
dir: 
zip: 
type: twitter
artist: 米白粕🍸🏖🌟
url: https://twitter.com/kasu1923
valid: False
done: True
range: ~9999999
range_p: None
single: False
time: 1597218852.2804887 (Aug 12)
tags: []
goodbyedpi: None
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
multiple tweets
types: img, video
max_pos=None, imgs=0
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
over try
Traceback (most recent call last):
File "extractor\twitter_downloader", line 309, in get_imgs
File "extractor\twitter_downloader", line 408, in get_imgs_legacy
Exception: No imgs

cursor: None
cursor: None
'1144025418002944006'
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\twitter_downloader", line 138, in read
File "extractor\twitter_downloader", line 317, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
KeyError: '1144025418002944006'

Invalid: fail=True
EOT: https://twitter.com/kasu1923

multiple tweets
types: img, video
max_pos=None, imgs=0
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
over try
Traceback (most recent call last):
File "extractor\twitter_downloader", line 309, in get_imgs
File "extractor\twitter_downloader", line 408, in get_imgs_legacy
Exception: No imgs

cursor: None
cursor: None
'1144025418002944006'
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\twitter_downloader", line 138, in read
File "extractor\twitter_downloader", line 317, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
KeyError: '1144025418002944006'

Invalid: fail=True
EOT: https://twitter.com/kasu1923

multiple tweets
types: img, video
max_pos=None, imgs=0
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
can not load json: Expecting value: line 1 column 1 (char 0)
over try
Traceback (most recent call last):
File "extractor\twitter_downloader", line 309, in get_imgs
File "extractor\twitter_downloader", line 408, in get_imgs_legacy
Exception: No imgs

cursor: None
cursor: None
'1144025418002944006'
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\twitter_downloader", line 138, in read
File "extractor\twitter_downloader", line 317, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
KeyError: '1144025418002944006'

Invalid: fail=True
EOT: https://twitter.com/kasu1923

와 같이 version: 3.0 (20-08-11 17:19:50 GMT+0)에서 다운이 되지 않는 트위터 주소도 있습니다.

감사합니다.

**Comment by KurtBestor** [comment]
고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
![주석 2020-08-12 172213](https://user-images.githubusercontent.com/47098778/89992568-671ce580-dcc0-11ea-8f1f-67bf2d10fa04.png)

잘 작동합니다.
고생많으셨고.. 

늘 그렇듯 너무 감사드립니다..!!
빠른 피드백도 감사드려요!

**Comment by yuchan39** [comment]
정상작동 확인했습니다.

빠른 피드백 감사합니다.

정말 고맙습니다, 선생님.
