### ISSUE TITLE
툰코에서 다운이 안되는게 있습니다

### ISSUE THREAD

**Issue by Lisrim** [KurtBestor/Hitomi-Downloader#2248]
고생 많으십니다
툰코에서 특정작품이 다운이안되길래 문의드려봅니다

Invalid: [toonkor] tkor.wiki / 모럴센스

version: 3.0 (20-08-10 16:49:42 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 14
group: False
input: tkor.wiki/모럴센스
dir: 
zip: 
type: toonkor
artist: None
url: tkor.wiki/모럴센스
valid: False
done: True
range: None
range_p: None
single: False
time: 1597194619.556944 (Aug 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
모럴센스 00화
모럴센스 00화
모럴센스 00화
모럴센스 00화
fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 510, in open
File "urllib\request", line 328, in __init__
File "urllib\request", line 354, in full_url
File "urllib\request", line 383, in _parse
ValueError: unknown url type: '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 312, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 97, in session_request
File "requests\sessions", line 516, in request
File "requests\sessions", line 459, in prepare_request
File "requests\models", line 314, in prepare
File "requests\models", line 388, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html': No schema supplied. Perhaps you meant http:///%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 805, in wrapper
File "dynamic_module_2", line 73, in get_imgs_page
File "downloader", line 409, in read_html
File "downloader", line 327, in read_html
File "site-packages\urllib3\poolmanager", line 325, in urlopen
File "site-packages\urllib3\poolmanager", line 231, in connection_from_host
urllib3.exceptions.LocationValueError: No host specified.

stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "dynamic_module_2", line 54, in read
File "dynamic_module_2", line 126, in get_imgs
File "<decorator-gen-89>", line 2, in get_imgs_page
File "constants", line 835, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 510, in open
File "urllib\request", line 328, in __init__
File "urllib\request", line 354, in full_url
File "urllib\request", line 383, in _parse
ValueError: unknown url type: '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 312, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 97, in session_request
File "requests\sessions", line 516, in request
File "requests\sessions", line 459, in prepare_request
File "requests\models", line 314, in prepare
File "requests\models", line 388, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html': No schema supplied. Perhaps you meant http:///%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 805, in wrapper
File "dynamic_module_2", line 73, in get_imgs_page
File "downloader", line 409, in read_html
File "downloader", line 327, in read_html
File "site-packages\urllib3\poolmanager", line 325, in urlopen
File "site-packages\urllib3\poolmanager", line 231, in connection_from_host
urllib3.exceptions.LocationValueError: No host specified.

Invalid: fail=True
EOT: tkor.wiki/모럴센스

모럴센스 00화
모럴센스 00화
모럴센스 00화
모럴센스 00화
fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 510, in open
File "urllib\request", line 328, in __init__
File "urllib\request", line 354, in full_url
File "urllib\request", line 383, in _parse
ValueError: unknown url type: '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 312, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 97, in session_request
File "requests\sessions", line 516, in request
File "requests\sessions", line 459, in prepare_request
File "requests\models", line 314, in prepare
File "requests\models", line 388, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html': No schema supplied. Perhaps you meant http:///%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 805, in wrapper
File "dynamic_module_2", line 73, in get_imgs_page
File "downloader", line 409, in read_html
File "downloader", line 327, in read_html
File "site-packages\urllib3\poolmanager", line 325, in urlopen
File "site-packages\urllib3\poolmanager", line 231, in connection_from_host
urllib3.exceptions.LocationValueError: No host specified.

stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "dynamic_module_2", line 54, in read
File "dynamic_module_2", line 126, in get_imgs
File "<decorator-gen-89>", line 2, in get_imgs_page
File "constants", line 835, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "downloader", line 284, in read_html
File "urllib\request", line 510, in open
File "urllib\request", line 328, in __init__
File "urllib\request", line 354, in full_url
File "urllib\request", line 383, in _parse
ValueError: unknown url type: '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 312, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 97, in session_request
File "requests\sessions", line 516, in request
File "requests\sessions", line 459, in prepare_request
File "requests\models", line 314, in prepare
File "requests\models", line 388, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '/%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html': No schema supplied. Perhaps you meant http:///%EB%AA%A8%EB%9F%B4%EC%84%BC%EC%8A%A4_00%ED%99%94.html?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "constants", line 805, in wrapper
File "dynamic_module_2", line 73, in get_imgs_page
File "downloader", line 409, in read_html
File "downloader", line 327, in read_html
File "site-packages\urllib3\poolmanager", line 325, in urlopen
File "site-packages\urllib3\poolmanager", line 231, in connection_from_host
urllib3.exceptions.LocationValueError: No host specified.

Invalid: fail=True
EOT: tkor.wiki/모럴센스

**Comment by KurtBestor** [comment]
다음과 같이 프로토콜을 붙여주세요: `https://tkor.wiki/모럴센스`

**Comment by Lisrim** [comment]
헙.프로토콜을 못봤네요 감사합니다
