### ISSUE TITLE
카카오페이지 쿠키 적용이 안되는 것 같습니다. 

### ISSUE THREAD

**Issue by lililillilililililill** [KurtBestor/Hitomi-Downloader#2249]
카카오페이지 로그인 후 (사용법에 나와있는 쿠키 확장프로그램에서)txt파일 형식의 쿠키를 다운받아 불러오기 했음에도, 로그인이 필요한 나이제한이 있는 작품에서 로그인 적용이 안 되네요.

To download cookies for **this tab** click here, or download **all cookies**.에서
**this tab**과 **all cookies** 두 가지를 모두 해봤으나 안되네요.

-------------------------------------------------------------------------------------------------------------------------------
Invalid: [kakaopage] https://page.kakao.com / home?seriesId=52760334

version: 3.0 (20-08-11 17:19:50 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://page.kakao.com/home?seriesId=52760334
dir: 
zip: 
type: kakaopage
artist: None
url: https://page.kakao.com/home?seriesId=52760334
valid: False
done: True
range: None
range_p: None
single: False
time: 1597204639.907929 (Aug 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 157, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/home?seriesId=52760334

no imgs
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 157, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/home?seriesId=52760334

no imgs
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 157, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/home?seriesId=52760334

**Comment by KurtBestor** [comment]
카카오페이지에서 User agent 까지 검사하네요. <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 열고 다음 입력하고 <kbd>Enter</kbd> 눌러서 적용한 후에 다시 다운로드하세요:
```
from extractor import kakaopage_downloader;kakaopage_downloader.UA='<쿠키 추출한 브라우저의 User agent>' 
```

User agent 는 [여기](https://www.whatismybrowser.com/detect/what-is-my-user-agent)에서 확인할 수 있어요.

**Comment by lililillilililililill** [comment]
해결되었습니다. 감사합니다.

**Comment by ajslajsl0123** [comment]
카카오페이지는 결제한 것 만 다운 되나요??
