### ISSUE TITLE
업그레이드후 pixiv 코믹이 다운이 안됩니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#2259]
valid: [pixiv_comic] https://comic.pixiv.net / works / 6785

version: 3.0 (20-08-10 16:49:42 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 1
group: False
input: https://comic.pixiv.net/works/6785
dir: 
zip: 
type: pixiv_comic
artist: ゆりかご
url: https://comic.pixiv.net/works/6785
valid: False
done: True
range: None
range_p: None
single: False
time: 1597314148.3239195 (Aug 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf solved
dirFormat: [artist] title
fuckkk...
Traceback (most recent call last):
File "constants", line 805, in wrapper
File "extractor\pixiv_comic_downloader", line 163, in get_imgs_page
AttributeError: 'NoneType' object has no attribute 'attrs'

stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\pixiv_comic_downloader", line 77, in read
File "extractor\pixiv_comic_downloader", line 153, in get_imgs
File "<decorator-gen-45>", line 2, in get_imgs_page
File "constants", line 835, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 805, in wrapper
File "extractor\pixiv_comic_downloader", line 163, in get_imgs_page
AttributeError: 'NoneType' object has no attribute 'attrs'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6785

정보는 이렇습니다
항상 감사합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
테스트버전은 잘되는군요 정말 감사드립니다
