### ISSUE TITLE
일부png파일 이미지압축불가문제

### ISSUE THREAD

**Issue by jake-0805** [KurtBestor/Hitomi-Downloader#2273]
가끔씩png파일이 압축이안될때가 있습니다.
아래에 첨부한 히토미게시물엔 간헐적으로 몇장만 이미지압축이 안되는데
어떤건 모든파일이 전부 압축이 안되기도 합니다.

**파일 이름: 017IMG_20190309_0017.png [17/46]
이미지 정보: 2113x3000 (PNG,RGBA32)**
이미지압축이 가능한 이미지의 정보

**파일 이름: 018IMG_20190309_0018.png [18/46]
이미지 정보: 2107x3000 (PNG,GRAY8ALPHA8)**
불가능한 이미지의 정보

아래는 정보입니다.
------------------------------------------------------------
[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)

version: 3.0 (20-08-10 16:49:42 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 86
group: False
input: 1385761
dir: hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)
zip: 
type: hitomi
artist: allegro, Etc
url: https://hitomi.la/doujinshi/hitozuma-futei-koubi-zuroku-yuu-日本語-1385761.html
valid: True
done: True
range: None
range_p: None
single: False
time: 1597510195.8187187 (Aug 16)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
갤러리 넘버: 1385761

제목: Hitozuma Futei Koubi Zuroku Yuu

작가: allegro, doctor masube, etuzan jakusui, itou eight, morisoba, yamaoka koutetsurou

그룹: isocurve

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: female:big breasts, female:blindfold, female:cheating, female:fishnets, female:milf, female:netorare, female:stockings, female:sweating, goudoushi, group, male:dark skin, male:eyemask, male:muscle, male:sweating, mmf threesome

언어: Japanese

[File Names]
[0001] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\001IMG_20190309_0001.jpg
[0002] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\002IMG_20190309_0002.jpg
[0003] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\003IMG_20190309_0003.jpg
[0004] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\004IMG_20190309_0004.jpg
[0005] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\005IMG_20190309_0005.jpg
[0006] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\006IMG_20190309_0006.jpg
[0007] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\007IMG_20190309_0007.jpg
[0008] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\008IMG_20190309_0008.jpg
[0009] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\009IMG_20190309_0009.png
[0010] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\010IMG_20190309_0010.jpg
[0011] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\011IMG_20190309_0011.jpg
[0012] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\012IMG_20190309_0012.jpg
[0013] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\013IMG_20190309_0013.jpg
[0014] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\014IMG_20190309_0014.jpg
[0015] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\015IMG_20190309_0015.jpg
[0016] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\016IMG_20190309_0016.jpg
[0017] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\017IMG_20190309_0017.jpg
[0018] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\018IMG_20190309_0018.png
[0019] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\019IMG_20190309_0019.png
[0020] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\020IMG_20190309_0020.jpg
[0021] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\021IMG_20190309_0021.jpg
[0022] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\022IMG_20190309_0022.jpg
[0023] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\023IMG_20190309_0023.jpg
[0024] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\024IMG_20190309_0024.jpg
[0025] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\025IMG_20190309_0025.jpg
[0026] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\026IMG_20190309_0026.jpg
[0027] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\027IMG_20190309_0027.jpg
[0028] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\028IMG_20190309_0028.jpg
[0029] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\029IMG_20190309_0029.jpg
[0030] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\030IMG_20190309_0030.jpg
[0031] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\031IMG_20190309_0031.jpg
[0032] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\032IMG_20190309_0032.jpg
[0033] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\033IMG_20190309_0033.jpg
[0034] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\034IMG_20190309_0034.jpg
[0035] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\035IMG_20190309_0035.jpg
[0036] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\036IMG_20190309_0036.jpg
[0037] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\037IMG_20190309_0037.jpg
[0038] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\038IMG_20190309_0038.jpg
[0039] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\039IMG_20190309_0039.jpg
[0040] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\040IMG_20190309_0040.jpg
[0041] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\041IMG_20190309_0041.jpg
[0042] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\042IMG_20190309_0042.jpg
[0043] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\043IMG_20190309_0043.jpg
[0044] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\044IMG_20190309_0044.png
[0045] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\045IMG_20190309_0045.jpg
[0046] hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\046IMG_20190309_0046.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/6/c7/6febd56cba5e8aeb50e15fa83d1aa1b9ad4b46a8c2c6c3ee06ae25a008870c76.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/5/ba/a9c9e030ed8490e95cd26081882bc72f12371af6ae41830b9324b68371b03ba5.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/e/30/67b6b17337cc52641abab695b43c40c4dde6ec71a240483b8c88f673fbdee30e.png
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/8/4b/0a6f10caa886ee97de2d1d475517b7601446de9eaa3e74a1765a68b4250ed4b8.png
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/c/70/3f93a11572aa41a6dbc175a6f15c4c75626b0f0ad54ea0bab877bf3297fc770c.png
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/1/d9/e2641b08aac32bda1d6277c6dc603b7a9db5fb2a02ad2d53678ec52d092fbd91.png
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/6/07/808d827a5beba5b075501db4a0c52e1288fbe9a2a742a32f8b2076fdd02f2076.png
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/9/a2/2000afa98f33da3c80511e81d673f5c76f183dd0b926d9c4a2b2f293451fea29.png
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/4/bf/eb41fa3c23dff86df605ddccad9e34cd59b1badb6d5d4ae8b6a1519045b70bf4.png
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/5/ef/d462bb0a4f3bde1454cb8d91f7bdaff23b5867f3950b8f5fced5eaf32d76bef5.png
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/6/7b/6cb0a053304afb99c98e4f8bb4eafc0c5649eb838a8217692d573eb90a6f07b6.png
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/c/7d/395332f2f70b49d1e5b9fea09cb4064e9ce2691d1c16ab75aca4dc08925ee7dc.png
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/0/a0/20bf882768fa6339948e4271115a383f49389ae837d5ff620cb199bf54b28a00.png
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/f/5b/414d6e7d75a9b00aedb04f1de8aaccac42173c17fb7c8af5f1125690100085bf.png
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/f/07/0efec39df269bf7ecd060870cd3566930ca56c142d3a8a1894f0f1c6ffe9a07f.png
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/7/c8/8e83bad192202b53832eeee385260f6d4ebbf166c9aab2277e94c974e5099c87.png
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/a/23/e5e73adb80c1b741673f9f9c58cb41cc145d373b5bc45080eb1e9a43f764223a.png
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/8/4b/5bce699d890c7433903a82d1aeb421bfd209696bd2e1f82eed764c0cc1d544b8.png
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/7/b3/4c21692d599740ca4678586ac11eb36143d86bec0b08f3d02a0d66bd03065b37.png
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/7/bd/3ac151d5040f4293152ab2951cbdbb0f948e548728f7c6f692f4722dc5dc2bd7.png
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/0/b8/f3130b67c8adac4736c8254cb7aa6c744fbcc03a58800e31331c41e262168b80.png
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/8/7d/436d50277dc3cfa2bee4cd025e7cf3c6d0be470ab183f50dc43d34e37b54a7d8.png
[0023] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/5/fd/38191e245948f14250553d66c0fc871ed8656aaa79f77611da8fe14f08dddfd5.png
[0024] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/9/d9/e04f597059c33e7afca9103909d3b39c3012b549ebeeeb0b17f617a7472dad99.png
[0025] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/0/48/87f28a0e7868cdeb745dac191baa8d2afb684ab79e497fc9099ac49297c78480.png
[0026] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/b/77/c598c3a153ac2f1d19d8884d81e7de12324147101a1382511934f2eaaaae177b.png
[0027] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/a/96/c5f17a6e5d8f92030acc0c91f98fe84cca5e81ba9c3ca399245eb846e752c96a.png
[0028] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/d/4c/a1746dd8e81fe238b781e0d6ba25d5f547e22886be1ab92b5d1de7f882ab24cd.png
[0029] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/e/4d/5c6a3e894acd623541f89b332b12241dd353496e405f65db757fa8bf1ea8f4de.png
[0030] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/b/ca/d20435da47850b7652454b986f491b2d09a8b0ed4363fef100dddf43ca6b9cab.png
[0031] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/a/61/5115b9c85d3aa3963f172870315a5f3d77dd3726e97821047642008cd960a61a.png
[0032] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/f/65/b97b21caafb86617cc870c6763763971bb490ff06d3ee810b6e50dea77ce965f.png
[0033] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/6/96/486e765fe3f8503fc6ccdb4538a41448082685b02c5525b4671e6319e597c966.png
[0034] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/e/f1/952b24f9abd9bc15c761ae0d9808509bbbf8899086ec98afbb40026b4c946f1e.png
[0035] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/a/c0/41bd72831ae2d8850a329d232161d69b092ac629a9af9373832a7f3d3a300c0a.png
[0036] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/a/e3/9d77bb8cd472ca39424c46740da352f7a0619ea65703464e0b3f5a8e1d817e3a.png
[0037] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/a/2e/e18a5d462fca6283b136f9a02dcc7fc265babd0cdfac245b3369b526ad1e12ea.png
[0038] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/9/55/2e770ae76b44d2655c61ab8419cc299651f1a4f83d3bcb61741e2e383807f559.png
[0039] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/e/f5/c5e1b2437350ee695485e1988cd58ef85259f1f52eb49eb192e98e2505593f5e.png
[0040] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/d/72/0578bf08b14605fc09a521c9909b652f39e4aa2ba7e4d4b95f89be9024f0c72d.png
[0041] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/b/d6/21f988962515e5bd693ccba749af8446fde9985034b8ce20fdb99dd88a602d6b.png
[0042] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/4/d6/2b05327c1dda687d39d9b34735e3f8bf17a5e72987dd1a0c4897aae15c2e8d64.png
[0043] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://aa.hitomi.la/images/1/14/89a9fa80ddc4e7eb50ad96b9b6f652d3845cb5aa5f8e5ab61c2863642e500141.png
[0044] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/6/03/580f9f8b6beae7a3994f0ded454d4bdb327272bdf7c684f6b53c178fc2ac4036.png
[0045] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ba.hitomi.la/images/b/fd/7203a5fcdc191f9e25629adab1a457af71f4209d76d723c712664f385c076fdb.png
[0046] LazyUrl_hitomi(https://hitomi.la/reader/1385761.html) ---> https://ca.hitomi.la/images/e/bf/1ed1e3ffe391d94e8aa5f328bcd8a8edaa6837cc7b3ab709a1a8e0136d04fbfe.png

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 46
get_title__

Fail : \\?\E:\망가 백업\압축용\hitomi_downloaded\[Allegro, Etc] [Isocurve] [Japanese] Hitozuma Futei Koubi Zuroku Yuu (1385761)\039IMG_20190309_0039.png
Traceback (most recent call last):
File "downloader", line 885, in download
File "downloader", line 878, in Stream
File "http\client", line 457, in read
File "http\client", line 501, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

stop
quality: 80%
[001IMG_20190309_0001.jpg] [jpg] 4286x6041 --> 603x850
[002IMG_20190309_0002.jpg] [jpg] 4269x6032 --> 602x850
[003IMG_20190309_0003.png] [jpg] 2122x3000 --> 601x850
[004IMG_20190309_0004.png] [jpg] 2091x3000 --> 592x850
[005IMG_20190309_0005.png] [jpg] 2113x3000 --> 599x850
[006IMG_20190309_0006.png] [jpg] 2101x3000 --> 595x850
[007IMG_20190309_0007.png] [jpg] 2113x3000 --> 599x850
[008IMG_20190309_0008.png] [jpg] 2104x3000 --> 596x850
Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'LA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1623, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode LA as JPEG

[010IMG_20190309_0010.png] [jpg] 2106x3000 --> 597x850
[011IMG_20190309_0011.png] [jpg] 2115x3000 --> 599x850
[012IMG_20190309_0012.png] [jpg] 2109x3000 --> 598x850
[013IMG_20190309_0013.png] [jpg] 2122x3000 --> 601x850
[014IMG_20190309_0014.png] [jpg] 2112x3000 --> 598x850
[015IMG_20190309_0015.png] [jpg] 2110x3000 --> 598x850
[016IMG_20190309_0016.png] [jpg] 2118x3000 --> 600x850
[017IMG_20190309_0017.png] [jpg] 2113x3000 --> 599x850
Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'LA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1623, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode LA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'LA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1623, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode LA as JPEG

[020IMG_20190309_0020.png] [jpg] 2109x3000 --> 598x850
[021IMG_20190309_0021.png] [jpg] 2115x3000 --> 599x850
[022IMG_20190309_0022.png] [jpg] 2109x3000 --> 598x850
[023IMG_20190309_0023.png] [jpg] 2110x3000 --> 598x850
[024IMG_20190309_0024.png] [jpg] 2104x3000 --> 596x850
[025IMG_20190309_0025.png] [jpg] 2115x3000 --> 599x850
[026IMG_20190309_0026.png] [jpg] 2096x3000 --> 594x850
[027IMG_20190309_0027.png] [jpg] 2037x3000 --> 577x850
[028IMG_20190309_0028.png] [jpg] 2118x3000 --> 600x850
[029IMG_20190309_0029.png] [jpg] 2116x3000 --> 600x850
[030IMG_20190309_0030.png] [jpg] 2106x3000 --> 597x850
[031IMG_20190309_0031.png] [jpg] 2118x3000 --> 600x850
[032IMG_20190309_0032.png] [jpg] 2113x3000 --> 599x850
[033IMG_20190309_0033.png] [jpg] 2116x3000 --> 600x850
[034IMG_20190309_0034.png] [jpg] 2119x3000 --> 600x850
[035IMG_20190309_0035.png] [jpg] 2113x3000 --> 599x850
[036IMG_20190309_0036.png] [jpg] 2107x3000 --> 597x850
[037IMG_20190309_0037.png] [jpg] 2119x3000 --> 600x850
[038IMG_20190309_0038.png] [jpg] 2107x3000 --> 597x850
[039IMG_20190309_0039.png] [jpg] 2109x3000 --> 598x850
[040IMG_20190309_0040.png] [jpg] 2119x3000 --> 600x850
[041IMG_20190309_0041.png] [jpg] 2116x3000 --> 600x850
[042IMG_20190309_0042.png] [jpg] 2121x3000 --> 601x850
[043IMG_20190309_0043.png] [jpg] 2122x3000 --> 601x850
Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'LA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1623, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode LA as JPEG

[045IMG_20190309_0045.png] [jpg] 2128x3000 --> 603x850
[046IMG_20190309_0046.png] [jpg] 2061x3000 --> 584x850
EOT: 1385761

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wkd284** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘되네요 감사합니다.

그런데 이 테스트버전으로 검색기 검색후 다운로드루 제거를 누르니 Can not determine type 라고하면서 다운이 되지않네요.  클립보드 자동 다운로드는 작동합니다.

아래는 정보입니다.
-----------
Can not determine type: [Saigado] Suite For My Sweet Shinteiban (1652481)

version: 3.0a (20-08-15 19:20:40 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: [Saigado] Suite For My Sweet Shinteiban (1652481)
dir: 
zip: 
type: hitomi
artist: None
url: [Saigado] Suite For My Sweet Shinteiban (1652481)
valid: False
done: True
range: None
range_p: None
single: False
time: 1597525476.5662074 (Aug 16)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
갤러리 넘버: 1652481

제목: Suite For My Sweet Shinteiban

작가: saigado

그룹: saigado

타입: doujinshi

시리즈: neon genesis evangelion

캐릭터: makoto hyuga, maya ibuki, ritsuko akagi, shigeru aoba

태그: group, mmf threesome, female:anal, female:blowjob, female:catgirl, female:collar, female:futanari, female:lab coat, female:masturbation, female:petplay, female:stockings, female:yuri, male:glasses

언어: Korean


[File Names]



[URLs]



[Messages]
stop
Invalid: fail=False
EOT: [Saigado] Suite For My Sweet Shinteiban (1652481)

**Comment by KurtBestor** [comment]
새 버전에선 잘 될거예요.

**Comment by wkd284** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘되네요 감사합니다.

그런데 이 테스트버전으로 검색기 검색후 다운로드루 제거를 누르니 Can not determine type 라고하면서 다운이 되지않네요.  클립보드 자동 다운로드는 작동합니다.

아래는 정보입니다.
-----------
Can not determine type: [Saigado] Suite For My Sweet Shinteiban (1652481)

version: 3.0a (20-08-15 19:20:40 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: [Saigado] Suite For My Sweet Shinteiban (1652481)
dir: 
zip: 
type: hitomi
artist: None
url: [Saigado] Suite For My Sweet Shinteiban (1652481)
valid: False
done: True
range: None
range_p: None
single: False
time: 1597525476.5662074 (Aug 16)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
갤러리 넘버: 1652481

제목: Suite For My Sweet Shinteiban

작가: saigado

그룹: saigado

타입: doujinshi

시리즈: neon genesis evangelion

캐릭터: makoto hyuga, maya ibuki, ritsuko akagi, shigeru aoba

태그: group, mmf threesome, female:anal, female:blowjob, female:catgirl, female:collar, female:futanari, female:lab coat, female:masturbation, female:petplay, female:stockings, female:yuri, male:glasses

언어: Korean


[File Names]



[URLs]



[Messages]
stop
Invalid: fail=False
EOT: [Saigado] Suite For My Sweet Shinteiban (1652481)

> 
> 
> 새 버전에선 잘 될거예요.

잘됩니다 감사합니다!
