### ISSUE TITLE
툰코 스크립트 추가 오류

### ISSUE THREAD

**Issue by Psychopath7** [KurtBestor/Hitomi-Downloader#2281]
툰코 스크립트 추가하는데 오류뜨면서 추가가 안돼요 ㅠㅠ

    Traceback (most recent call last):
      File "console\Console.py", line 153, in execSingle
      File "<string>", line 5
        import downloader
             ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "console\Console.py", line 157, in execSingle
      File "<string>", line 33, in <module>
      File "<string>", line 40, in Downloader_toonkor
    NameError: name 'try_n' is not defined

**Comment by KurtBestor** [comment]
도움말 스크립트 사용법 참고해주세요..

**Comment by Psychopath7** [comment]
Ctrl+Alt+C한 후에 History 오른쪽칸에 툰코 스크립트 붙여넣은다음 Enter키 누르면 추가 되는거 아닌가용? ㅜㅜ

**Comment by KurtBestor** [comment]
도움말 스크립트 사용법 참고해주세요..

**Comment by Psychopath7** [comment]
도움말 스크립트 사용법 확인 후 그대로 해보니깐 됐어요! 감사합니다!!ㅎㅎ
