### ISSUE TITLE
크기 조절 사용시 변환 후 앞뒤 빼고 날아갑니다.

### ISSUE THREAD

**Issue by Ooooool** [KurtBestor/Hitomi-Downloader#2288]
[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 34

stop
quality: 75%
[000.jpg] [jpg] 2125x3000 --> 1360x1920
[001.jpg] [jpg] 2125x3000 --> 1360x1920
Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "customWidget", line 1626, in convert_imgs
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

[032.jpg] [jpg] 2125x3000 --> 1360x1920
[999.jpg] [jpg] 2130x3000 --> 1363x1920
valid=False 2
EOT: #-*- [3104] Kanashimi ga Kirai dattara (1663892)

그리고 주황색으로 바뀌는데 다시 시작하면 그냥 작업완료로 바뀝니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Ooooool** [comment]
잘 되네요. 감사합니다.
