### ISSUE TITLE
bdsmlr 잘 되다가 안되는데 무슨 이유 때문인가요?

### ISSUE THREAD

**Issue by zjaaodRhddl** [KurtBestor/Hitomi-Downloader#2299]
Invalid: [bdsmlr] https://elsawalker.bdsmlr.com / 

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://elsawalker.bdsmlr.com/
dir: 
zip: 
type: bdsmlr
artist: None
url: https://elsawalker.bdsmlr.com
valid: False
done: True
range: None
range_p: None
single: False
time: 1597840600.1759677 (Aug 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'attrs'
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\bdsmlr_downloader", line 40, in read
File "<decorator-gen-60>", line 2, in get_imgs
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "extractor\bdsmlr_downloader", line 94, in get_imgs
AttributeError: 'NoneType' object has no attribute 'attrs'

Invalid: fail=True
EOT: https://elsawalker.bdsmlr.com/

너무 많이 다운 받아서 제한 된 걸 까요?

**Comment by zjaaodRhddl** [comment]
ㅠㅠ 이제 아예 안되네요 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by zjaaodRhddl** [comment]
다운은 잘 됩니다 근데 스크롤이나 우클릭 목록삭제 클릭 등 기본적인 기능은 안됩니다 감사합니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by zjaaodRhddl** [comment]
다운로드는 완벽합니다. 단 다운로드 중일 때  스크롤 우클릭 목록삭제는 작동하지 않으나 모든 다운로드 작업이 끝난 후 다시 켜면 정상작동합니다.
