### ISSUE TITLE
트위터 다시시작 문의

### ISSUE THREAD

**Issue by wc892** [KurtBestor/Hitomi-Downloader#2303]
트위터 231명을 구독하고있습니다

전체선택후 한번에 다시시작하면 최신사진/동영상을 업데이트 못합니다

읽는중으로 로딩되다가  대부분 Invalid: [twitter] https://twitter.com /아이디  이렇게 뜨고나서
 
정상적인 완료로 뜹니다 폴더들어가서 확인하면 최신사진/동영상 업데이트가 안되어있습니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by wc892** [comment]
이전 테스트링크 주신거랑 똑같이 노란색으로 완료되고 노란색느낌표 뜨면서 완료됩니다

보니까 항상 똑같은 사람만 노란색느낌표뜨면서 완료되네요

냥냥2 (@yaHrrxENI7YMR4q)

version: 3.0b (20-08-23 16:09:17 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 61
group: False
input: https://twitter.com/yaHrrxENI7YMR4q
dir: E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)
zip: 
type: twitter
artist: 냥냥2
url: https://twitter.com/yaHrrxENI7YMR4q
valid: False
done: True
range: None
range_p: None
single: False
time: 1598103471.763705 (Aug 22)
tags: ['gray']
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]
[0001] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-07-16] 1283605309143969792_p0.jpg
[0002] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-07-16] 1283605309143969792_p1.jpg
[0003] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-07-08] 1280781206250905601_p0.jpg
[0004] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-07-02] 1278400256774791168_p0.jpg
[0005] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-28] 1277233529819205633_p0.jpg
[0006] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-27] 1276818691640799232_p0.jpg
[0007] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-27] 1276804844787912704_p0.mp4
[0008] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-26] 1276453129098194945_p0.mp4
[0009] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-19] 1273924339004366849_p0.jpg
[0010] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-19] 1273924339004366849_p1.jpg
[0011] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-05] 1268558496200458241_p0.jpg
[0012] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-05] 1268558496200458241_p1.jpg
[0013] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-05] 1268558496200458241_p2.jpg
[0014] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-04] 1268423635363958785_p0.jpg
[0015] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-04] 1268423635363958785_p1.jpg
[0016] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-02] 1267743419280941056_p0.mp4
[0017] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-01] 1267418675591565312_p0.jpg
[0018] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-06-01] 1267358718061998082_p0.mp4
[0019] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-31] 1267108153394487297_p0.jpg
[0020] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-31] 1267108153394487297_p1.jpg
[0021] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-31] 1266921898635440129_p0.mp4
[0022] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266723062885396485_p0.jpg
[0023] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266694541853114368_p0.jpg
[0024] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266694541853114368_p1.jpg
[0025] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266694541853114368_p2.jpg
[0026] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266683583717994496_p0.mp4
[0027] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266674984404938753_p0.mp4
[0028] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266639107586846721_p0.jpg
[0029] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266639107586846721_p1.jpg
[0030] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266634250918322176_p0.mp4
[0031] E:\[auto download]\히토미\twitter\냥냥2 (@yaHrrxENI7YMR4q)\[20-05-30] 1266631192226357250_p0.mp4


[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 966, in start
File "extractor\twitter_downloader", line 108, in init
File "<decorator-gen-15>", line 2, in get_artist_username
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\twitter_downloader", line 735, in get_artist_username
File "extractor\twitter_downloader", line 226, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/yaHrrxENI7YMR4q

invalid; revert
stop
Traceback (most recent call last):
File "utils", line 966, in start
File "extractor\twitter_downloader", line 108, in init
File "<decorator-gen-15>", line 2, in get_artist_username
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\twitter_downloader", line 735, in get_artist_username
File "extractor\twitter_downloader", line 226, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/yaHrrxENI7YMR4q

invalid; revert
stop
Traceback (most recent call last):
File "utils", line 966, in start
File "extractor\twitter_downloader", line 108, in init
File "<decorator-gen-15>", line 2, in get_artist_username
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\twitter_downloader", line 735, in get_artist_username
File "extractor\twitter_downloader", line 226, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/yaHrrxENI7YMR4q

invalid; revert
stop
Traceback (most recent call last):
File "utils", line 966, in start
File "extractor\twitter_downloader", line 108, in init
File "<decorator-gen-15>", line 2, in get_artist_username
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\twitter_downloader", line 735, in get_artist_username
File "extractor\twitter_downloader", line 226, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/yaHrrxENI7YMR4q

invalid; revert
stop
Traceback (most recent call last):
File "utils", line 966, in start
File "extractor\twitter_downloader", line 108, in init
File "<decorator-gen-15>", line 2, in get_artist_username
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\twitter_downloader", line 735, in get_artist_username
File "extractor\twitter_downloader", line 226, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/yaHrrxENI7YMR4q

invalid; revert
stop
Traceback (most recent call last):
File "utils", line 966, in start
File "extractor\twitter_downloader", line 108, in init
File "<decorator-gen-15>", line 2, in get_artist_username
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\twitter_downloader", line 735, in get_artist_username
File "extractor\twitter_downloader", line 226, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/yaHrrxENI7YMR4q

invalid; revert

**Comment by KurtBestor** [comment]
삭제된 계정이네요.

**Comment by wc892** [comment]
일단 노란새경고뜬거 20명정도확인해봤는데요 
계정잠금/계정 사진,미디어없음  간혹 있고 대부분 아무문제없는 계정이었습니다
밑에 링크는 이시각 문제없는 계정입니다
노란색경고 뜨고 만약 미디어가 20개이면  [아이디  20/20 ]  완료된상태서 노란색으로 경고뜹니다

https://twitter.com/princexx____              

https://twitter.com/6dtuvbLo7xBrtms     

https://twitter.com/ying5527               

https://twitter.com/I_m_the_queen_

https://twitter.com/18_lovelycat

https://twitter.com/prre_

https://twitter.com/miaowu_i

https://twitter.com/172_8n

https://twitter.com/Busanbongbong

https://twitter.com/yumylover

https://twitter.com/x_k1e

https://twitter.com/yaho_yeahi

https://twitter.com/nanesimsim

https://twitter.com/love_doggy_

**Comment by KurtBestor** [comment]
안 되는 작업 있으면 작업 정보 보여주세요.
