### ISSUE TITLE
픽시브 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2324]
안녕하세요. 

다운로더 잘 쓰고 있습니다.

픽시브 다운로드가 되지 않습니다.

Invalid: [pixiv] https://www.pixiv.net / users / 524329

version: 3.0b (20-08-24 06:57:25 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://www.pixiv.net/users/524329
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/users/524329
valid: False
done: False
range: None
range_p: None
single: False
time: 1598322644.1222157 (Aug 25)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/524329

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/524329

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/524329

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/524329

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/524329

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True

----------------------------------------------------------------------------------------------------------------------------------------------
Invalid: [pixiv] https://www.pixiv.net / users / 49984557

version: 3.0b (20-08-24 06:57:25 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.pixiv.net/users/49984557
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/users/49984557
valid: False
done: True
range: None
range_p: None
single: False
time: 1598322644.121218 (Aug 25)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49984557

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49984557

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49984557

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49984557

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49984557

PIXIV_TYPE: user
Type: all
info: None
'Downloader_pixiv' object has no attribute '_id'
stop
Traceback (most recent call last):
File "utils", line 973, in start
File "utils", line 1019, in start_
File "extractor\pixiv_downloader", line 163, in read
File "extractor\pixiv_downloader", line 133, in id
AttributeError: 'Downloader_pixiv' object has no attribute '_id'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49984557

감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by yuchan39** [comment]
version: 3.0b (20-08-25 09:26:16 GMT+0)에서 정상작동 확인했습니다.

감사합니다!
