### ISSUE TITLE
제이마나 다른 애들은 다운로드가 되는데...

### ISSUE THREAD

**Issue by bittet** [KurtBestor/Hitomi-Downloader#2361]
이런 것은 왜 다운로드가 안될까요?
https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

Invalid: [jmana] https://jmana.net / book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 13
group: False
input: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84
dir: f:\manga
zip: f:\manga
type: jmana
artist: N/A
url: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84
valid: False
done: True
range: None
range_p: None
single: False
time: 1598791650.672852 (Aug 30)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

no html
no html
no html
no html
no html
no html
no html
clf solved
no html
no html
no html
no html
no html
no html
no html
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

no html
no html
no html
no html
no html
no html
no html
clf solved
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
stop
Traceback (most recent call last):
File "utils", line 957, in start
File "extractor\jmana_downloader", line 65, in init
File "extractor\jmana_downloader", line 23, in fix_url
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

clf solved
clf solved
dirFormat: [artist] title
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\jmana_downloader", line 94, in read
File "extractor\jmana_downloader", line 229, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84

**Comment by bittet** [comment]
그냥 불안정한가보네요.  몇몇 만화들이 되었다 안되었다 하는거보니...서버 문제인지도...
이슈 클로즈 합니다.

**Comment by bittet** [comment]
아...역시 되지 않네요.  

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%97%90%EB%8F%84+%EC%97%90%EB%A1%9C+%EC%88%98%ED%98%B8%EC%A0%84
