### ISSUE TITLE
유튜브 일부공개 다운로드 변환오류

### ISSUE THREAD

**Issue by hdhd55** [KurtBestor/Hitomi-Downloader#2368]
기존 버전에서 다운로드 후 주황색으로 변환이 제대로 안되었는지

파일을 눌러도 재생이 안됬습니다. 그래서 검색해보니 저랑 비슷한 상황인것같은 분의 글에 올려진 테스트버전으로 해보았지만

이번에는 아예 다운로드가 안되는 상황입니다.

https://github.com/KurtBestor/Hitomi-Downloader/issues/2317

이 링크의 테스트 버전을 사용했고 

정보메뉴의 경우 이렇게 출력되었습니다.

Invalid: [youtube] https://www.youtube.com / watch?v=zZUfccc8Ua8

version: 3.0b (20-08-30 04:13:43 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=zZUfccc8Ua8
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=zZUfccc8Ua8
valid: False
done: True
range: None
range_p: None
single: True
time: 1598805316.654699 (Aug 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[144p][30fps][None] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (DASH video)
[240p][30fps][None] mp4 [avc1.4d4015 / None] ─ 133 - 426x240 (DASH video)
[360p][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (DASH video)
[480p][30fps][None] mp4 [avc1.4d401f / None] ─ 135 - 854x480 (DASH video)
[720p][30fps][None] mp4 [avc1.4d401f / None] ─ 136 - 1280x720 (DASH video)
[720p][60fps][None] mp4 [avc1.4d4020 / None] ─ 298 - 1280x720 (DASH video)
[1080p][30fps][None] mp4 [avc1.4d4028 / None] ─ 137 - 1920x1080 (DASH video)
[1080p][60fps][None] mp4 [avc1.4d402a / None] ─ 299 - 1920x1080 (DASH video)

# stream_final <youtube_dl_test.Video object at 0x0000022F7D61AC48> 136 - 1280x720 (DASH video) 720p mp4 None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022F7D61AD08> 298 - 1280x720 (DASH video) 720p mp4 None 60fps
AV codec: avc1.4d4020
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7D61AC48> 136 - 1280x720 (DASH video) 720p mp4 None 30fps
AV codec: avc1.4d401f
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7D61AC08> 135 - 854x480 (DASH video) 480p mp4 None 30fps
AV codec: avc1.4d401f
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F610FEAC8> 134 - 640x360 (DASH video) 360p mp4 None 30fps
AV codec: avc1.4d401e
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F607FF708> 133 - 426x240 (DASH video) 240p mp4 None 30fps
AV codec: avc1.4d4015
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F607F5348> 160 - 256x144 (DASH video) 144p mp4 None 30fps
AV codec: avc1.4d400c
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\youtube_downloader", line 386, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=zZUfccc8Ua8

[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[144p][30fps][None] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (DASH video)
[240p][30fps][None] mp4 [avc1.4d4015 / None] ─ 133 - 426x240 (DASH video)
[360p][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (DASH video)
[480p][30fps][None] mp4 [avc1.4d401f / None] ─ 135 - 854x480 (DASH video)
[720p][30fps][None] mp4 [avc1.4d401f / None] ─ 136 - 1280x720 (DASH video)
[720p][60fps][None] mp4 [avc1.4d4020 / None] ─ 298 - 1280x720 (DASH video)
[1080p][30fps][None] mp4 [avc1.4d4028 / None] ─ 137 - 1920x1080 (DASH video)
[1080p][60fps][None] mp4 [avc1.4d402a / None] ─ 299 - 1920x1080 (DASH video)

# stream_final <youtube_dl_test.Video object at 0x0000022F7F621C88> 136 - 1280x720 (DASH video) 720p mp4 None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022F7F621D48> 298 - 1280x720 (DASH video) 720p mp4 None 60fps
AV codec: avc1.4d4020
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7F621C88> 136 - 1280x720 (DASH video) 720p mp4 None 30fps
AV codec: avc1.4d401f
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7F621AC8> 135 - 854x480 (DASH video) 480p mp4 None 30fps
AV codec: avc1.4d401f
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7F621C48> 134 - 640x360 (DASH video) 360p mp4 None 30fps
AV codec: avc1.4d401e
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7F621D88> 133 - 426x240 (DASH video) 240p mp4 None 30fps
AV codec: avc1.4d4015
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022F7F621488> 160 - 256x144 (DASH video) 144p mp4 None 30fps
AV codec: avc1.4d400c
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\youtube_downloader", line 386, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=zZUfccc8Ua8

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
