### ISSUE TITLE
유튜브 다운로드 안되는 영상있어용

### ISSUE THREAD

**Issue by LegusHeeneon** [KurtBestor/Hitomi-Downloader#2376]
유튜브 영상중 다운안되는 게 있어 작업정보 올려봅니다. 3.0b 버전으로 받아서 해봤는데두 안되네요

아마 성인인증 필요한 영상이라 그런것 같기도 한데... 혹 픽시브처럼 본인계정으로 로그인하면 다운로드 가능하게 하는 방식은 어떨까합니다 일단은 정보 첨부할게요

 이 건은 수정 안되어도 괜찮으니 지금처럼 좋은 서비스 오래오래 했으면 합니다 넘모 개꿀이야 사랑해요
---------------------------

Invalid: [youtube] https://www.youtube.com / watch?v=od45nMHwNsw

version: 3.0b (20-08-30 18:16:19 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=od45nMHwNsw
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=od45nMHwNsw
valid: False
done: True
range: None
range_p: None
single: True
time: 1598890374.9282877 (Sep 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: od45nMHwNsw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: od45nMHwNsw: YouTube said: Unable to extract video data

No videos
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\youtube_downloader", line 386, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=od45nMHwNsw

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1766
