### ISSUE TITLE
유튜브 안되는 영상

### ISSUE THREAD

**Issue by shirimpeye** [KurtBestor/Hitomi-Downloader#2384]
유투브에서 멤버십 가입자만 가능같은 경우엔 안되더라구요 ㅜㅜ
솔직히 돈내고 이거 쓰는것도 아니니 굳이 수정하실 필요는 없다고 생각하지만, 그래도 해주시면 넘모 감사할것같아요..!!
항상 잘 쓰고 있고, 감사합니당!!

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by shirimpeye** [comment]
Invalid: [youtube] https://www.youtube.com / watch?v=bphBxO0lG8k

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=bphBxO0lG8k
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=bphBxO0lG8k
valid: False
done: True
range: None
range_p: None
single: True
time: 1599627741.2435098 (Sep 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: This video is available to this channel's members on level: Tomato (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

No videos
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\youtube_downloader", line 401, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=bphBxO0lG8k

이렇게 나옵니다.. 답장이 늦음 점은 죄송합니다 ㅜㅜ

**Comment by KurtBestor** [comment]
옵션 - 설정 - 고급 설정 - 쿠키 - 불러오기 에서 유튜브 로그인 쿠키 넣어주세요.
