### ISSUE TITLE
마나토끼에서 계속해서 다운이 안되는 만화가 있습니다

### ISSUE THREAD

**Issue by kimwansul** [KurtBestor/Hitomi-Downloader#2395]
확인부탁드립니다 감사합니다

Invalid: [manatoki] https://manatoki73.net / comic / 146791?tag=%ED%8C%90%ED%83%80%EC%A7%80

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 177
group: False
input: https://manatoki73.net/comic/146791?tag=%ED%8C%90%ED%83%80%EC%A7%80
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki73.net/comic/146791?tag=%ED%8C%90%ED%83%80%EC%A7%80
valid: False
done: True
range: None
range_p: None
single: False
time: 1599163447.072965 (Sep 4)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
name 'get_soup' is not defined
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "dynamic_module_1", line 69, in read
File "dynamic_module_1", line 50, in soup
NameError: name 'get_soup' is not defined

Invalid: fail=True
EOT: https://manatoki73.net/comic/146791?tag=%ED%8C%90%ED%83%80%EC%A7%80

현자의 제자를 자칭하는 현자 1화 14
현자의 제자를 자칭하는 현자 2화 11
현자의 제자를 자칭하는 현자 3화 23
현자의 제자를 자칭하는 현자 4화 23
현자의 제자를 자칭하는 현자 5화 24
현자의 제자를 자칭하는 현자 6화 6
현자의 제자를 자칭하는 현자 7화 23
현자의 제자를 자칭하는 현자 8화 24
현자의 제자를 자칭하는 현자 9화 23
현자의 제자를 자칭하는 현자 10화 8
현자의 제자를 자칭하는 현자 11화 24
현자의 제자를 자칭하는 현자 12화 24
현자의 제자를 자칭하는 현자 13화 23
현자의 제자를 자칭하는 현자 14화 26
현자의 제자를 자칭하는 현자 15화 24
현자의 제자를 자칭하는 현자 16화 22
현자의 제자를 자칭하는 현자 17화 8
현자의 제자를 자칭하는 현자 18화 15
현자의 제자를 자칭하는 현자 19화 23
현자의 제자를 자칭하는 현자 20화 21
현자의 제자를 자칭하는 현자 21화 17
현자의 제자를 자칭하는 현자 22화 28
현자의 제자를 자칭하는 현자 23화 27
현자의 제자를 자칭하는 현자 24화 27
현자의 제자를 자칭하는 현자 25화 19
현자의 제자를 자칭하는 현자 26화 37
현자의 제자를 자칭하는 현자 27화 14
현자의 제자를 자칭하는 현자 28화 36
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "dynamic_module_1", line 75, in read
File "dynamic_module_1", line 143, in get_imgs
File "<decorator-gen-88>", line 2, in get_imgs_page
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "dynamic_module_1", line 187, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/146791?tag=%ED%8C%90%ED%83%80%EC%A7%80

현자의 제자를 자칭하는 현자 1화 14
현자의 제자를 자칭하는 현자 2화 11
현자의 제자를 자칭하는 현자 3화 23
현자의 제자를 자칭하는 현자 4화 23
현자의 제자를 자칭하는 현자 5화 24
현자의 제자를 자칭하는 현자 6화 6
현자의 제자를 자칭하는 현자 7화 23
현자의 제자를 자칭하는 현자 8화 24
현자의 제자를 자칭하는 현자 9화 23
현자의 제자를 자칭하는 현자 10화 8
현자의 제자를 자칭하는 현자 11화 24
현자의 제자를 자칭하는 현자 12화 24
현자의 제자를 자칭하는 현자 13화 23
현자의 제자를 자칭하는 현자 14화 26
현자의 제자를 자칭하는 현자 15화 24
현자의 제자를 자칭하는 현자 16화 22
현자의 제자를 자칭하는 현자 17화 8
현자의 제자를 자칭하는 현자 18화 15
현자의 제자를 자칭하는 현자 19화 23
현자의 제자를 자칭하는 현자 20화 21
현자의 제자를 자칭하는 현자 21화 17
현자의 제자를 자칭하는 현자 22화 28
현자의 제자를 자칭하는 현자 23화 27
현자의 제자를 자칭하는 현자 24화 27
현자의 제자를 자칭하는 현자 25화 19
현자의 제자를 자칭하는 현자 26화 37
현자의 제자를 자칭하는 현자 27화 14
현자의 제자를 자칭하는 현자 28화 36
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "dynamic_module_1", line 75, in read
File "dynamic_module_1", line 143, in get_imgs
File "<decorator-gen-88>", line 2, in get_imgs_page
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "dynamic_module_1", line 187, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/146791?tag=%ED%8C%90%ED%83%80%EC%A7%80

**Comment by mita5549** [comment]
no imgs
stop

구문에서 다운로드가 취소되는 거 같습니다. 
다운로드가 취소 된 29화 (https://manatoki73.net/comic/184758?tag=%ED%8C%90%ED%83%80%EC%A7%80&spage=1)

**Comment by woghkstod** [comment]
다른 것도 살펴보니, 중간에 한 개 화에 이미지가 없으면, 그대로 링크오류로 빨갛게 되면서 전체가 멈추는군요.
수동으로 그 화수만 빼고 받아보면 잘 받아집니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kimwansul** [comment]
감사합니다!! 테스트 버전 사용으로 되는 만화가 상당히 많아졌습니다!!! 그래도 아직 안되는  만화들이 있어 그 중 하나를 아래에 적어 두었습니다

Invalid: [manatoki] https://manatoki73.net / comic / 125226?tag=%EC%9D%BC%EC%83%81

version: 3.0b (20-09-06 13:45:14 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 259
group: False
input: https://manatoki73.net/comic/125226?tag=%EC%9D%BC%EC%83%81
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki73.net/comic/125226?tag=%EC%9D%BC%EC%83%81
valid: False
done: True
range: None
range_p: None
single: False
time: 1599456271.8899956 (Sep 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
아내, 초등학생이 되다. 1화 28
아내, 초등학생이 되다. 2화 20
아내, 초등학생이 되다. 3화 20
아내, 초등학생이 되다. 4화 20
아내, 초등학생이 되다. 5화 20
아내, 초등학생이 되다. 6화 19
아내, 초등학생이 되다. 7화 21
아내, 초등학생이 되다. 8화 40
아내, 초등학생이 되다. 9화 42
no imgs
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_1", line 75, in read
File "dynamic_module_1", line 143, in get_imgs
File "<decorator-gen-91>", line 2, in get_imgs_page
File "constants", line 811, in wrapper
File "constants", line 782, in wrapper
File "dynamic_module_1", line 187, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/125226?tag=%EC%9D%BC%EC%83%81

아내, 초등학생이 되다. 1화 28
아내, 초등학생이 되다. 2화 20
아내, 초등학생이 되다. 3화 20
아내, 초등학생이 되다. 4화 20
아내, 초등학생이 되다. 5화 20
아내, 초등학생이 되다. 6화 19
아내, 초등학생이 되다. 7화 21
아내, 초등학생이 되다. 8화 40
아내, 초등학생이 되다. 9화 42
no imgs
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_1", line 75, in read
File "dynamic_module_1", line 143, in get_imgs
File "<decorator-gen-91>", line 2, in get_imgs_page
File "constants", line 811, in wrapper
File "constants", line 782, in wrapper
File "dynamic_module_1", line 187, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/125226?tag=%EC%9D%BC%EC%83%81

아내, 초등학생이 되다. 1화 28
아내, 초등학생이 되다. 2화 20
아내, 초등학생이 되다. 3화 20
아내, 초등학생이 되다. 4화 20
아내, 초등학생이 되다. 5화 20
아내, 초등학생이 되다. 6화 19
아내, 초등학생이 되다. 7화 21
아내, 초등학생이 되다. 8화 40
아내, 초등학생이 되다. 9화 42
no imgs
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_1", line 75, in read
File "dynamic_module_1", line 143, in get_imgs
File "<decorator-gen-91>", line 2, in get_imgs_page
File "constants", line 811, in wrapper
File "constants", line 782, in wrapper
File "dynamic_module_1", line 187, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/125226?tag=%EC%9D%BC%EC%83%81

**Comment by KurtBestor** [comment]
스크립트 적용하지 말고 해보세요. 이미 테스트 버전에서 포함되어있어요.

**Comment by kimwansul** [comment]
스크립트 지우고 실행 하고 다운 해 보니 완벽합니다...... ㅠㅜ 정말 감사합니닷!!!!!
