### ISSUE TITLE
테스트 버전 마나토끼 다운로드 문제

### ISSUE THREAD

**Issue by melong1001** [KurtBestor/Hitomi-Downloader#2400]
최신 테스트 버전 적용후에도
마나토끼에서 정상적으로 다운로드가 이루어지지 않습니다

goodbyedpi는 시스템에서 적용중이고

혹시 몰라서
1. 뉴토끼 스크립트 적용 없이 시도
2. 뉴토끼 스크립트 적용 후 시도

모두 같은 결과입니다

Info log 첨부합니다

Invalid: [manatoki] https://manatoki73.net / comic / 147257

version: 3.0b (20-09-03 21:21:06 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://manatoki73.net/comic/147257
dir: 
zip: 
type: manatoki
artist: 쿠마노 큐우
url: https://manatoki73.net/comic/147257
valid: False
done: True
range: None
range_p: None
single: False
time: 1599229685.8861268 (Sep 4)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
빠지지 않는 성검쨩 1화 18
빠지지 않는 성검쨩 2화 16
빠지지 않는 성검쨩 3화 14
빠지지 않는 성검쨩 4화 10
빠지지 않는 성검쨩 5화 9
빠지지 않는 성검쨩 6화 10
빠지지 않는 성검쨩 7화 10
빠지지 않는 성검쨩 8화 10
빠지지 않는 성검쨩 9화 10
빠지지 않는 성검쨩 10화 10
빠지지 않는 성검쨩 11화 10
빠지지 않는 성검쨩 12화 10
빠지지 않는 성검쨩 13화 10
빠지지 않는 성검쨩 14화 10
no imgs
stop
Traceback (most recent call last):
File "utils", line 1007, in start
File "utils", line 1053, in start_
File "extractor\manatoki_downloader", line 76, in read
File "extractor\manatoki_downloader", line 154, in get_imgs
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 811, in wrapper
File "constants", line 782, in wrapper
File "extractor\manatoki_downloader", line 198, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/147257

**Comment by mita5549** [comment]
해당 만화의 15번 이미지가 없어서 이후 작업이 정상적으로 진행되지 않는 것 같습니다.
 15화: https://manatoki73.net/comic/194955

 위에서부터 - 16화 - 15화 - 목록 전체 입니다.
![image](https://user-images.githubusercontent.com/45882353/92302673-eabcb000-efa8-11ea-8f89-08e896dfb068.png)


==================================
 15화 오류메시지 출력
Invalid: [manatoki] https://manatoki73.net / comic / 194955

version: 3.0b (20-09-02 17:54:37 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 1
group: False
input: https://manatoki73.net/comic/194955
dir: 
zip: 
type: manatoki
artist: 쿠마노 큐우
url: https://manatoki73.net/comic/147257
valid: False
done: True
range: None
range_p: [14]
single: False
time: 1599299496.8395832 (Sep 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1008, in start
File "utils", line 1054, in start_
File "extractor\manatoki_downloader", line 76, in read
File "extractor\manatoki_downloader", line 154, in get_imgs
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 811, in wrapper
File "constants", line 782, in wrapper
File "extractor\manatoki_downloader", line 198, in get_imgs_page
Exception: no imgs

Invalid: fail=True
EOT: https://manatoki73.net/comic/194955

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2395

**Comment by melong1001** [comment]
신규 테스트버전으로, 중간에 오류나는 화수 제외하고
정상적으로 다운됨을 확인하였습니다

감사합니다
