### ISSUE TITLE
유튜브 다운로드가 자꾸 실패합니다.

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2412]
https://www.youtube.com/watch?v=Co3nvfe-V1U&t=1s&ab_channel=asmrwooyeon%EC%9A%B0%EC%97%B0

위 링크 다운로드가 자꾸 실패하네요 (mp3 형식입니다)

아래는 작업 정보입니다

ASMR | 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 | camera brushing | mouth sounds

version: 3.0b (20-08-30 18:16:19 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=Co3nvfe-V1U
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: asmr wooyeon 우연
url: https://www.youtube.com/watch?v=Co3nvfe-V1U
valid: False
done: True
range: ~100000
range_p: None
single: True
time: 1599317091.1240191 (Sep 5)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: mp3
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=Co3nvfe-V1U) ---> https://r4---sn-n3cgv5qc5oq-bh2ls.googlevideo.com/videoplayback?expire=1599338701&ei=baRTX72XEfOwigar36vYDg&ip=211.215.135.202&id=o-ADswzA-2PZlFWbdVCPgC7ZHZa0VBK2AFC9cUBjEWj9DR&itag=22&source=youtube&requiressl=yes&mh=Iu&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2ls%2Csn-i3belnlz&ms=au%2Conr&mv=m&mvi=4&pl=23&initcwndbps=1462500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=1121.756&lmt=1539008534023837&mt=1599316958&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOcFjYukgbmUxll7ahsjv25qDDr8Simmi7oiMj6njRCfAiAVGPjtAtVlF8hjmrpZdghwSrgB8fbw7X2qmbtUeTO9nQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAN1RhgIg5fUmYGT8m7TqwQLYV1AfXJXbmQhBcYkGYTXVAiBX6RielgrQPle5o2EVxMYT9t2CvJPi5hL1zPtCTmYtVA%3D%3D

[Messages]
[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][50kbps] webm [None / opus] ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm [None / opus] ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (DASH audio)
[144p][30fps][None] webm [vp9 / None] ─ 278 - 256x144 (DASH video)
[144p][30fps][None] mp4 [avc1.4d400b / None] ─ 160 - 256x144 (DASH video)
[240p][30fps][None] webm [vp9 / None] ─ 242 - 426x240 (DASH video)
[240p][30fps][None] mp4 [avc1.4d400c / None] ─ 133 - 426x240 (DASH video)
[360p][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (DASH video)
[360p][30fps][None] webm [vp9 / None] ─ 243 - 640x360 (DASH video)
[480p][30fps][None] webm [vp9 / None] ─ 244 - 854x480 (DASH video)
[480p][30fps][None] mp4 [avc1.4d4014 / None] ─ 135 - 854x480 (DASH video)
[720p][30fps][None] webm [vp9 / None] ─ 247 - 1280x720 (DASH video)
[720p][30fps][None] mp4 [avc1.4d4016 / None] ─ 136 - 1280x720 (DASH video)
[1080p][30fps][None] webm [vp9 / None] ─ 248 - 1920x1080 (DASH video)
[1080p][30fps][None] mp4 [avc1.640028 / None] ─ 137 - 1920x1080 (DASH video)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x000001F7D50DCCC8> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 30fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4
FPS: 30

downloader_v3 fail... p[0 / 91]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 574729 / 1048576

downloader_v3 fail... p[2 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[1 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 91]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 574729 / 1048576

downloader_v3 fail... p[3 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[2 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[1 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

### reset size ###
downloader_v3 fail... p[1 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[2 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 91]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 574729 / 1048576

downloader_v3 fail... p[0 / 91]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 574729 / 1048576

downloader_v3 fail... p[2 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[1 / 91]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

### reset size ###
use just download

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

Fail : \\?\D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\ASMR ｜ 스르륵 눈이 감기는 카메라 브러싱과 팅글폭발 입소리, 냠냠 짭짭 ｜ camera brushing ｜ mouth sounds.mp4
Traceback (most recent call last):
File "downloader", line 979, in download
Exception: Size mismatch: 574729 / 95065985

stop
valid=False 1
EOT: https://www.youtube.com/watch?v=Co3nvfe-V1U

**Comment by KurtBestor** [comment]
유튜브 서버에서 파일이 잘못된 것 같은데 좀 더 낮은 음질로 다운로드하면 잘 되네요. 128k 로 다운로드 해주세요.
