### ISSUE TITLE
마나토끼 에러 문의드립니다

### ISSUE THREAD

**Issue by TTY54** [KurtBestor/Hitomi-Downloader#2420]
Invalid: [manatoki] https://newtoki73.com / webtoon / 208564

version: 3.0b (20-09-04 22:00:23 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 3
group: False
input: https://newtoki73.com/webtoon/208564
dir: 
zip: 
type: manatoki
artist: None
url: https://newtoki73.com/webtoon/208564
valid: False
done: True
range: None
range_p: None
single: False
time: 1599307687.2704568 (Sep 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\manatoki_downloader", line 73, in read
File "extractor\manatoki_downloader", line 70, in name
File "extractor\manatoki_downloader", line 88, in get_title
File "extractor\manatoki_downloader", line 96, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://newtoki73.com/webtoon/208564

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\manatoki_downloader", line 73, in read
File "extractor\manatoki_downloader", line 70, in name
File "extractor\manatoki_downloader", line 88, in get_title
File "extractor\manatoki_downloader", line 96, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://newtoki73.com/webtoon/208564

항상 잘 쓰고 있습니다. 정말 감사합니다.

카카오페이지에서 다운로드 하려니까 복잡하기도 하고 유료구매해야만 가능한 것 같아서 '

광고 부착된거 감안하고 마나토끼에서 다운로드 하려니 에러가 뜨네요..

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
