### ISSUE TITLE
유튜브 다운로드 100%로 표시된 이후 파일이 사라집니다

### ISSUE THREAD

**Issue by cwc10** [KurtBestor/Hitomi-Downloader#2436]
![image](https://user-images.githubusercontent.com/71062941/92691791-1c08f780-f37e-11ea-8a59-dae559b36724.png)

정상적으로 종료시 파란색 게이지로 바뀌어야 할텐데 주황색게이지 100%에서 멈추고 
저장경로에서 99%시점까지 존재하던 파일이 사라집니다. 

작업정보 첨부합니다
【紳士向けMMD】鹿島ワールドイズマイン【R-18】

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.16299-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=ZmcS7smPYdw
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: MMD保管庫
url: https://www.youtube.com/watch?v=ZmcS7smPYdw
valid: False
done: True
range: None
range_p: None
single: True
time: 1599720378.4528332 (Sep 10)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\【紳士向けMMD】鹿島ワールドイズマイン【R-18】.mp4

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=ZmcS7smPYdw) ---> Dash_stream(https://manifest.googlevideo.com/api/manifest/dash/expire/1599741994/ei/ystZX6PSK8q24gKwoK_wDg/ip/114.207.181.235/id/666712eec98f61dc/source/youtube/requiressl/yes/playback_host/r1---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/mh/jw/mm/31,26/mn/sn-n3cgv5qc5oq-bh2sk,sn-i3b7knsd/ms/au,onr/mv/m/mvi/1/pcm2cms/yes/pl/13/hfr/all/as/fmp4_audio_clear,webm_audio_clear,webm2_audio_clear,fmp4_sd_hd_clear,webm2_sd_hd_clear/initcwndbps/1147500/vprv/1/mt/1599720271/fvip/1/keepalive/yes/beids/9466587/itag/0/sparams/expire,ei,ip,id,source,requiressl,hfr,as,vprv,itag/sig/AOq0QJ8wRAIgAnWGFoD1j9wfBjWq8sIvhHABpumk_CJtnnhGvZMa-24CICwlGuMG9w39ampldCvPp6tslthaWJC9nSLSlh5s1fRW/lsparams/playback_host,mh,mm,mn,ms,mv,mvi,pcm2cms,pl,initcwndbps/lsig/AG3C_xAwRQIhAIE2soA4u5ATQR_G4rRONTflrI4tvgDhSTvZex6iXriCAiBYxjg08BgM396TWx1LIQTLX6NMzzkSjvPir44-o-wzrA==)

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: ZmcS7smPYdw: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 70, in get
File "youtube_dl_test", line 100, in __init__
File "youtube_dl_test", line 38, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: ZmcS7smPYdw: YouTube said: Unable to extract video data

[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[144p][30fps][None] webm None ─ 278 - 256x144 (DASH video)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (DASH video)
[240p][30fps][None] webm None ─ 242 - 426x240 (DASH video)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (DASH video)
[360p][30fps][None] webm None ─ 243 - 640x360 (DASH video)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (DASH video)
[480p][30fps][None] webm None ─ 244 - 854x480 (DASH video)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (DASH video)
[720p][30fps][None] webm None ─ 247 - 1280x720 (DASH video)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (DASH video)
[720p][60fps][None] webm None ─ 302 - 1280x720 (DASH video)
[720p][60fps][None] mp4 None ─ 298 - 1280x720 (DASH video)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x00000284BD0E4C88> 247 - 1280x720 (DASH video) 720p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x00000284BD0E4B08> 136 - 1280x720 (DASH video) 720p mp4 None 30fps
# stream_final <youtube_dl_test.Video object at 0x00000284BD0E4808> 302 - 1280x720 (DASH video) 720p webm None 60fps
# stream_final <youtube_dl_test.Video object at 0x00000284BD0E4688> 298 - 1280x720 (DASH video) 720p mp4 None 60fps
[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)

Resolution: None
Codec: None / mp4a.40.2
Abr: 128kbps
Subtype: m4a
FPS: 0

### reset size ###
use just download
Download audio: Dash_stream(https://manifest.googlevideo.com/api/manifest/dash/expire/1599741994/ei/ystZX6PSK8q24gKwoK_wDg/ip/114.207.181.235/id/666712eec98f61dc/source/youtube/requiressl/yes/playback_host/r1---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/mh/jw/mm/31,26/mn/sn-n3cgv5qc5oq-bh2sk,sn-i3b7knsd/ms/au,onr/mv/m/mvi/1/pcm2cms/yes/pl/13/hfr/all/as/fmp4_audio_clear,webm_audio_clear,webm2_audio_clear,fmp4_sd_hd_clear,webm2_sd_hd_clear/initcwndbps/1147500/vprv/1/mt/1599720271/fvip/1/keepalive/yes/beids/9466587/itag/0/sparams/expire,ei,ip,id,source,requiressl,hfr,as,vprv,itag/sig/AOq0QJ8wRAIgAnWGFoD1j9wfBjWq8sIvhHABpumk_CJtnnhGvZMa-24CICwlGuMG9w39ampldCvPp6tslthaWJC9nSLSlh5s1fRW/lsparams/playback_host,mh,mm,mn,ms,mv,mvi,pcm2cms,pl,initcwndbps/lsig/AG3C_xAwRQIhAIE2soA4u5ATQR_G4rRONTflrI4tvgDhSTvZex6iXriCAiBYxjg08BgM396TWx1LIQTLX6NMzzkSjvPir44-o-wzrA==)
use just download
Convert: \\?\C:\Users\112\Desktop\00000\hitomi_downloaded_youtube\【紳士向けMMD】鹿島ワールドイズマイン【R-18】.mp4
rename (1): \\?\C:\Users\112\Desktop\00000\hitomi_downloaded_youtube\a9f8b83b6c324840a0d957ea4640d695_a.tmp -> \\?\C:\Users\112\Desktop\00000\hitomi_downloaded_youtube\tmpe2793af8fac4421ca8fb34ebe6a63002_a.weba
rename (1): \\?\C:\Users\112\Desktop\00000\hitomi_downloaded_youtube\【紳士向けMMD】鹿島ワールドイズマイン【R-18】.mp4 -> \\?\C:\Users\112\Desktop\00000\hitomi_downloaded_youtube\tmpe2793af8fac4421ca8fb34ebe6a63002_v.mp4
-i tmpe2793af8fac4421ca8fb34ebe6a63002_v.mp4 -i tmpe2793af8fac4421ca8fb34ebe6a63002_a.weba -c copy -strict experimental -preset ultrafast tmpe2793af8fac4421ca8fb34ebe6a63002_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
1
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, matroska,webm, from 'tmpe2793af8fac4421ca8fb34ebe6a63002_v.mp4': 
Metadata: 
encoder : google/video-file 
http://youtube.com/streaming/otf/durations/112015: Segment-Count: 33 
: Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,4367, 
: 
: 
Duration: N/A, start: 0.000000, bitrate: N/A 
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1280x720, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default) 
Input #1, matroska,webm, from 'tmpe2793af8fac4421ca8fb34ebe6a63002_a.weba': 
Metadata: 
encoder : google/video-file 
Duration: 00:02:55.06, start: -0.007000, bitrate: 130 kb/s 
Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default) 
[mp4 @ 08332e00] track 1: codec frame size is not set 
Output #0, mp4, to 'tmpe2793af8fac4421ca8fb34ebe6a63002_o.mp4': 
Metadata: 
http://youtube.com/streaming/otf/durations/112015: Segment-Count: 33 
: Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,4367, 
: 
: 
encoder : Lavf58.20.100 
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 16k tbn, 1k tbc (default) 
Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp (default) 
Stream mapping: 
Stream #0:0 -> #0:0 (copy) 
Stream #1:0 -> #0:1 (copy) 
Press [q] to stop, [?] for help 
[mp4 @ 08332e00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 85600 >= 85328 
av_interleaved_write_frame(): Invalid argument 
frame= 323 fps=0.0 q=-1.0 Lsize= 1393kB time=00:00:05.36 bitrate=2128.6kbits/s speed= 383x 
video:1322kB audio:84kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 
Conversion failed! 

Lazyurl pp Error: \\?\C:\Users\112\Desktop\00000\hitomi_downloaded_youtube\【紳士向けMMD】鹿島ワールドイズマイン【R-18】.mp4
Traceback (most recent call last):
File "hitomi_downloader", line 301, in run
File "extractor\youtube_downloader", line 263, in pp
File "extractor\youtube_downloader", line 288, in _pp
File "ffmpeg", line 167, in merge
Exception: Failed to convert; exit code: 1

stop
EOT: https://www.youtube.com/watch?v=ZmcS7smPYdw

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2317
