### ISSUE TITLE
avgle  invaild 문의드립니다

### ISSUE THREAD

**Issue by profit1234** [KurtBestor/Hitomi-Downloader#2507]
안녕하세요 평소에 프로그램 잘 쓰고 있습니다 
오류가 나서 문의 드려요

Invalid: [avgle] https://avgle.com / video / zJKPxPd4_P5 / carib-091120-001-菊川みつ葉

version: 3.0b (20-09-23 12:12:22 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://avgle.com/video/zJKPxPd4_P5/carib-091120-001-菊川みつ葉
dir: 
zip: 
type: avgle
artist: None
url: https://avgle.com/video/zJKPxPd4_P5/carib-091120-001-菊川みつ葉
valid: False
done: True
range: None
range_p: None
single: True
time: 1600864438.796085 (Sep 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', OSError(0, 'Error'))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 0] Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\avgle_downloader", line 30, in read
File "<decorator-gen-61>", line 2, in get_video
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\avgle_downloader", line 45, in get_video
File "downloader", line 330, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

Invalid: fail=True
EOT: https://avgle.com/video/zJKPxPd4_P5/carib-091120-001-菊川みつ葉

이렇게 뜨네요 2300번에서 프리뷰도 다운받아봤는데 invalid가 뜨네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2327
