### ISSUE TITLE
다운로드 이슈

### ISSUE THREAD

**Issue by floygrasm** [KurtBestor/Hitomi-Downloader#2512]
카카오 페이지 이용권으로 열람한 회차가 다운로드가 안됩니다, 구매하지 않은 상품이라는 오류가 뜹니다.

[월랑] 환생검귀

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://page.kakao.com/home?seriesId=55368407
dir: kakaopage\[월랑] 환생검귀
zip: 
type: kakaopage
artist: 월랑
url: https://page.kakao.com/home?seriesId=55368407
valid: True
done: True
range: None
range_p: [0, 5]
single: False
time: 1600982029.865965 (Sep 24)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]
[0001] kakaopage\[월랑] 환생검귀\환생검귀 1화\0000.jpg
[0002] kakaopage\[월랑] 환생검귀\환생검귀 1화\0001.jpg
[0003] kakaopage\[월랑] 환생검귀\환생검귀 1화\0002.jpg
[0004] kakaopage\[월랑] 환생검귀\환생검귀 1화\0003.jpg
[0005] kakaopage\[월랑] 환생검귀\환생검귀 1화\0004.jpg
[0006] kakaopage\[월랑] 환생검귀\환생검귀 1화\0005.jpg
[0007] kakaopage\[월랑] 환생검귀\환생검귀 1화\0006.jpg
[0008] kakaopage\[월랑] 환생검귀\환생검귀 1화\0007.jpg
[0009] kakaopage\[월랑] 환생검귀\환생검귀 1화\0008.jpg
[0010] kakaopage\[월랑] 환생검귀\환생검귀 1화\0009.jpg
[0011] kakaopage\[월랑] 환생검귀\환생검귀 1화\0010.jpg
[0012] kakaopage\[월랑] 환생검귀\환생검귀 1화\0011.jpg
[0013] kakaopage\[월랑] 환생검귀\환생검귀 1화\0012.jpg
[0014] kakaopage\[월랑] 환생검귀\환생검귀 1화\0013.jpg
[0015] kakaopage\[월랑] 환생검귀\환생검귀 1화\0014.jpg
[0016] kakaopage\[월랑] 환생검귀\환생검귀 1화\0015.jpg
[0017] kakaopage\[월랑] 환생검귀\환생검귀 1화\0016.jpg
[0018] kakaopage\[월랑] 환생검귀\환생검귀 1화\0017.jpg
[0019] kakaopage\[월랑] 환생검귀\환생검귀 1화\0018.jpg
[0020] kakaopage\[월랑] 환생검귀\환생검귀 1화\0019.jpg
[0021] kakaopage\[월랑] 환생검귀\환생검귀 1화\0020.jpg
[0022] kakaopage\[월랑] 환생검귀\환생검귀 1화\0021.jpg
[0023] kakaopage\[월랑] 환생검귀\환생검귀 1화\0022.jpg
[0024] kakaopage\[월랑] 환생검귀\환생검귀 1화\0023.jpg
[0025] kakaopage\[월랑] 환생검귀\환생검귀 1화\0024.jpg
[0026] kakaopage\[월랑] 환생검귀\환생검귀 1화\0025.jpg
[0027] kakaopage\[월랑] 환생검귀\환생검귀 1화\0026.jpg
[0028] kakaopage\[월랑] 환생검귀\환생검귀 1화\0027.jpg

[URLs]
[0001] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=u6M3MsXx0H-MLj5TjyuhGWFOwb4k-rbQ7t_dYb-UHL6skP9PCmHfJoJKk1Yme5gH&filename=5056041_1595395213705.jpeg&signature=ChtEgxB6LuydSmX6bxHpSS2uK4s%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0002] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=1doau4nEPlbKhyaHo598RJUS7fNsyJk6llCXXSHrbYqNx0e216fF5NqmbVRb5fw0&filename=5056041_1595395213831.jpeg&signature=70vpYOTNBBVCD5DHGvM4ExIVAtg%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0003] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=vRSb5p5Tt6GtO5xWepUFUu8bgdBpnB_NbA0HWS1vtniOAo4Rhml5U1XzRNypHFDf&filename=5056041_1595395213949.jpeg&signature=P321KvfaMHaVESvwclpAJOZ1%2BCM%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0004] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=2Eu9kQISFav6icR2GW8GUTitXWdz1WtTHdrovtIgnNH1hdFG3POhbq6pU_Fi_Hth&filename=5056041_1595395214018.jpeg&signature=o2LvNZuWMjVmAQ7Y9V4wV6qacMI%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0005] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=qG8Jsri4QBG4Sa_l7I1UwgOiBZ37YyJL3zEBV8nV3gFqVKb70iLGRrpSLdumV-UN&filename=5056041_1595395214103.jpeg&signature=0GTe%2B3IZR43NNTy3QwsP9p1uN2o%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0006] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=1pbVUT8fW7pdpK0mPLxcKJKV6h1o0kVtBYP40ghjMNa5xXtV35QtHDrStssOZ9u9&filename=5056041_1595395214205.jpeg&signature=doLendHrP1yKQilHvVzy935yoeg%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0007] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=b2_dRqP7EnYuFwjBxy2VrCJkb-K7lyLZIvhpHXOKftruziYtKgB3lhdVfCw7ZTs1&filename=5056041_1595395214300.jpeg&signature=AcTkosVIif75kqG9ZCHjUfV%2FUeE%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0008] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=TmsOKPpsaG3k7n5WPk-EF8nvO-tY9LHXxc6byGyEURPTwnmtNt576NUen5b8F6Ti&filename=5056041_1595395214394.jpeg&signature=Pi9akKECy%2Fw9rnS1FkqQmLMFtuU%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0009] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=1lPcjvwKczTMwrVN0nkWjYS7lJ8VR7MsKICdUv90Yi3C9Osx28xVzWfDfE-xrITL&filename=5056041_1595395214473.jpeg&signature=JE8PxyGtFq4OARw974NHFQy8KUc%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0010] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=9Rl789lHAxmVAQrYj_HOzC6_00ck9r833x3U9J_0UC61AoRGzLimlsl0kzWac4vK&filename=5056041_1595395214550.jpeg&signature=kn75uDT90afCMnLdOzsKE9QQJ%2Fw%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0011] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=zOD4c5hucABhM_y5drRTcTNNiNpFMRhQFMYUBbO6BUG5IE8ICSrOMUBvfImeBqpo&filename=5056041_1595395214629.jpeg&signature=WC9bHQZnEU8FuQqCZ9Oz9epqMhI%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0012] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=7uIQFCfy12nowLfZNqmfIKr2WJXlg35osidDAPkP1qi5aKauEhwYa3IpOwspBuGR&filename=5056041_1595395214711.jpeg&signature=yvOgQrM4VAR1uu9ymln%2BN7hfpHE%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0013] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=7DYkggnjNy-FE-tEA5jAjB_ZbPxZphvapxIukrkSO-Ulyk-wat3lpdBwJx9YsoDN&filename=5056041_1595395214786.jpeg&signature=djXVvzkRZsTaNBFwyvb5%2B0YJ8Q0%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0014] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=Bk9W5u6OB0egUJQkvohEReTaXYx_OlqtsiH0yDAsrM5jsNUMaWIT7rao61UEbSC2&filename=5056041_1595395214871.jpeg&signature=ERgoA0Id8YBs6u9azddIlWae07A%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0015] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=m4d7oarkz-AzzrLGOFHXgnvBuLEvE2oNJVvIuY3DbBhLhXhACdZJ9mV8LtZbsYzy&filename=5056041_1595395214955.jpeg&signature=1i5jFO78kjEfOvUR8UwkjzINHxA%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0016] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=lbmr39psUeD5vHjq3iUkq3NooUa-TBxNycJkvkro48WBP9LViv-FouYKjcDNuq6A&filename=5056041_1595395215041.jpeg&signature=qfhE00GjDlSOErNeWrLLrB60f1k%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0017] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=XraKPdWwz45bKjj71-DXl0-RNXEdkdy-Sf_HaiMA1JmZpWnZHOR7lM3iUhC8gO1Z&filename=5056041_1595395215116.jpeg&signature=%2FIJNCgkSgVm9vILvIIfXNl4TlF8%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0018] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=f9T9XYTtRiezULCEOABHydSdq0g-Kxl7xZba_yQbm9OLlKyNi5VGR-5q1Ym9jF-Q&filename=5056041_1595395215202.jpeg&signature=6zViqg98xKR3u%2FjYf85bNbyRzVI%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0019] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=sxf7sADHYzo75cPKtNWTMGUB_QFMLh0CWE8MlwpX0z2L7laARFNz3s5qN5kHXqT1&filename=5056041_1595395215283.jpeg&signature=8HML2PzycCO45BsOdmcNfvYq9Lg%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0020] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=FxZnLxxtxBHueiQwgEY2qd1_PNvcBRzuW8pw5RGg2lmIuzDmOspt5g8K30wibIdk&filename=5056041_1595395215360.jpeg&signature=a8FRI%2Bcz%2FjNTLzkP1rajMoOWeOo%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0021] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=O9Lv64IRPnMMYtWru_Sso7M7arWI8yMcIT8gDPwy91-3NphBlQJlGiaMofuBxnjb&filename=5056041_1595395215434.jpeg&signature=NWi%2FauMv73AN4N7nIrZ2H5DNEfg%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0022] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=py9FBtN5Xhd-qHUgAwtkD6PCA-5YWZXFn5IhKPciNFaym1XUlKaeFHg7V0yve9v2&filename=5056041_1595395215513.jpeg&signature=FFB%2Bh%2BVS%2B1RB6Qcbw1fIWpd20zc%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0023] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=NVgS3DKWajG9AXIeFVXXGWO_wOEywue6je67WsHAwh6g2R2R41TMzf3dAZ3fTfD9&filename=5056041_1595395215596.jpeg&signature=%2Bgiq8Leyy7BLfM04KzV58yLEdVo%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0024] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=zd5U5JXBpfLxieJlJL_93xcoA04uYd2XdX1J2ULJN9Q2qwrhHXIrQ-p5a7Vq4S1r&filename=5056041_1595395215673.jpeg&signature=cB6cWPFU%2Bxx8qey0rpVgtt6dqw8%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0025] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=Itv881xh5FbKu8hw7CNwLXPEnJW7pl-fIYWelrWwgeHeoADuaOEA3LnYzpxvgZvT&filename=5056041_1595395215749.jpeg&signature=emEtdtkOosHYzsHzTFSrjDOTONE%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0026] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=ehkvEigXmZl_scrFtqflWuTMgS-vIme83E-MNs6mWecVsIwfJlFDgGU1rjlXVWeX&filename=5056041_1595395215821.jpeg&signature=gTBDV6j4UDVGN7w09PsU%2BANVXyk%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0027] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=X7SOBqJZWctQibz8ON6lUijYUf1MQdCwA5iOVXPg6vKJZtCEVgSUPiG4NHm9SuUY&filename=5056041_1595395215897.jpeg&signature=NtZmCwVNDizqrBaARaoXPB6P1gM%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0028] LazyUrl(https://page.kakao.com/viewer?productId=55371086) ---> https://page-edge.kakao.com/sdownload/resource?kid=5BZ6bL7fGlaoEeawvo5YXSU5AO-8KDAVJsvTJ8AuTsJ3q0iDG_a8bP_L7sbJ7Pn2&filename=5056041_1595395215973.jpeg&signature=wHJoFctfpAh4%2F2sSY6P1nK426ro%3D&expires=1600989240&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX

[Messages]
환생검귀 1화 28
환생검귀 6화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 153, in get_info
File "<decorator-gen-68>", line 2, in get_imgs_page
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\kakaopage_downloader", line 113, in get_imgs_page
Exception: 구매하지 않은 상품입니다.

stop
EOT: https://page.kakao.com/home?seriesId=55368407

혹시몰라서 로그인 쿠키를 살펴보니 몇일전 저장했던 쿠키와 오늘 만든 쿠키의 차이점
cs.kakao.com in
 JSESSIONID 유무

【.cs.kakao.com】
  sticky-cookie 유무

**Comment by floygrasm** [comment]
자체해결
