### ISSUE TITLE
티스토리 다운 문제입니다

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2532]
안녕하세요. 

다운로더 잘 쓰고 있습니다.

티스토리 중 다운로드 되지 않는 것들이 있습니다.

Invalid: [tistory] https://ehasd6.tistory.com / 2300

version: 3.1 (20-09-24 12:49:34 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 22
group: False
input: https://ehasd6.tistory.com/2300
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/2300
valid: False
done: True
range: None
range_p: None
single: False
time: 1601238174.8234012 (Sep 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://ehasd6.tistory.com/2300

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2300

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2300

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2300

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2300

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2300

----------------------------------------------------------------------------------------------------------------------------------------------
Invalid: [tistory] https://ehasd6.tistory.com / 1417

version: 3.1 (20-09-24 12:49:34 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 21
group: False
input: https://ehasd6.tistory.com/1417
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/1417
valid: False
done: True
range: None
range_p: None
single: False
time: 1601238172.3674042 (Sep 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1417

----------------------------------------------------------------------------------------------------------------------------------------------
Invalid: [tistory] https://ehasd6.tistory.com / 2413

version: 3.1 (20-09-24 12:49:34 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 10
group: False
input: https://ehasd6.tistory.com/2413
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/2413
valid: False
done: True
range: None
range_p: None
single: False
time: 1601238167.0866344 (Sep 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2413

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2413

no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2413
----------------------------------------------------------------------------------------------------------------------------------------------
Invalid: [tistory] https://ehasd6.tistory.com / 2274

version: 3.1 (20-09-24 12:49:34 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 5
group: False
input: https://ehasd6.tistory.com/2274
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/2274
valid: False
done: True
range: None
range_p: None
single: False
time: 1601238250.3004355 (Sep 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no view
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "dynamic_module_2", line 20, in read
File "dynamic_module_2", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/2274
----------------------------------------------------------------------------------------------------------------------------------------------
https://ehasd6.tistory.com/2261
https://ehasd6.tistory.com/2252
https://ehasd6.tistory.com/2304
https://ehasd6.tistory.com/1446

같이 티스토리에서 다운로드가 되지 않는 것들이 있습니다.

바쁘신 와중에도 항상 피드백 해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
고쳤어요. 다시 다운로드해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
정상적으로 다운로드 되는 것을 확인했습니다.
감사합니다.
