### ISSUE TITLE
인스타 작업 실행시 오류

### ISSUE THREAD

**Issue by ij1510** [KurtBestor/Hitomi-Downloader#2539]
항상 좋은 프로그램 신세지고 있습니다!

다름이 아니라 프로그램에 쿠키를 넣은 후 인스타그램을 다운로드 할 때 "스토리"만 받아지고 나머지 게시물은 받아지지 않는 현상이 발생하여 문의 드립니다. (작업 색깔 주황색으로 바뀜)

다운로더 프로그램의 쿠키를 초기화 한 상태에서 공개 계정을 다운로드할때는 스토리를 포함해 모든 게시물이 받아지는 반면에, 
쿠키를 넣은 후 다운로드를 시도하면 비공개 계정, 공개 계정 관계없이 인스타 스토리만 받아집니다.
 다만, 작업을 읽는 과정에서는 게시물까지 다 읽는 듯 싶습니다. ( 작업 추가시 "읽는중.."메세지와 숫자 카운트가 표시됨 )

제 로그인 쿠키에 문제가 있나 싶어  "인스타 로그아웃 - 크롬 쿠키 초기화 - 인스타 로그인 - 크롬 확장프로그램으로 쿠키 다운로드 - 프로그램에 쿠키 불러오기로 쿠키 추가"  과정을 반복하여도 똑같네요...

하단에 예시 작업 정보를 첨부해드립니다 

(insta_xx_fqqqq)

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: -989
group: False
input: https://www.instagram.com/xx_fqqqq
dir: hitomi_downloaded_insta\ (insta_xx_fqqqq)
zip: 
type: insta
artist: None
url: https://www.instagram.com/xx_fqqqq
valid: False
done: True
range: ~8000
range_p: None
single: False
time: 1601388150.7691221 (Sep 29)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_insta\ (insta_xx_fqqqq)\stories_2015548712809651409.mp4
[0002] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0003] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0004] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0005] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0006] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0007] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0008] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0009] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0010] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0011] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0012] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0013] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0014] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0015] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0016] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0017] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0018] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0019] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0020] hitomi_downloaded_insta\ (insta_xx_fqqqq)
[0021] hitomi_downloaded_insta\ (insta_xx_fqqqq)

[URLs]
[0001] https://scontent-ssn1-1.cdninstagram.com/v/t50.12441-16/56710854_2067114770054237_1385895685584383481_n.mp4?cb=ae824530-854f1720&efg=eyJxZV9ncm91cHMiOiJbXCJpZ19wcm9ncmVzc2l2ZV91cmxnZW4ucHJvZHVjdF90eXBlLnN0b3J5XCJdIn0&_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=105&_nc_ohc=71QWdWHTmJgAX8g3eBM&oe=5F75868A&oh=0fc47e2c70cc938d2e8e5350b9bb41c3
[0002] LazyUrl(https://www.instagram.com/p/CCaXF-ZHh3PyLOr884mCEBTUvNMRMpPrtY_Zwk0/)
[0003] LazyUrl(https://www.instagram.com/p/B_KgvbInheqpLJ-KHb_Fe-KcY_tR2Kbmw2CqU40/)
[0004] LazyUrl(https://www.instagram.com/p/B8stzzHne99PTxnvkI3_zC4GDLePu5xeHICQ7w0/)
[0005] LazyUrl(https://www.instagram.com/p/B6V6sIGnkT-NtWdHGMPDOifi3B8E54o2e8n0eQ0/)
[0006] LazyUrl(https://www.instagram.com/p/B3fO1bqHLK5xBY-tcNY3xJK4F7wDLA8Pp3kn1w0/)
[0007] LazyUrl(https://www.instagram.com/p/B29a0j6HlQcySZ0Hl4ccYVFTxDSneGzsZZqGM00/)
[0008] LazyUrl(https://www.instagram.com/p/B29P1JeHN2g7aW6nZJkqOJbpKiVvNb4ESdMAZQ0/)
[0009] LazyUrl(https://www.instagram.com/p/B26e_xGHIePJNrFmt6bJeRQmFHoX3SD378kHvw0/)
[0010] LazyUrl(https://www.instagram.com/p/B1Wm2RbHWxkdTUt1hYxLifmqm7xoh4Kv4jgM-40/)
[0011] LazyUrl(https://www.instagram.com/p/Bzk7Z0NnuDLaPwIM3YJ__Dh7L6oTkCnM_y5IC40/)
[0012] LazyUrl(https://www.instagram.com/p/BzkHd5nHVAoWTCcsjdRpz5lqw9TpxFp9wzT0780/)
[0013] LazyUrl(https://www.instagram.com/p/BxzKgpmnc_6gVw53P7dSjXmUZaInqmHQQNSFaw0/)
[0014] LazyUrl(https://www.instagram.com/p/Bw1-QXQgDcWtuLxdcsk6GI1gpOe7bXEnvQuwcg0/)
[0015] LazyUrl(https://www.instagram.com/p/Bwwl_0dg3eGfTQlb3We080_G3d8h3sVfotaTR80/)
[0016] LazyUrl(https://www.instagram.com/p/Bv7HvdJgCa9fyaElw1QmElEVErchA1a_IqZ8DM0/)
[0017] LazyUrl(https://www.instagram.com/p/Bv4oku3Ad2GGLGStfy3JVKmsI8KD2e-iOEDb5U0/)
[0018] LazyUrl(https://www.instagram.com/p/BvCSs1RAMqXVH2IwwcBTjTIj2jOUEGMdS35NcU0/)
[0019] LazyUrl(https://www.instagram.com/p/Bu5ZQTOA-ZhFHLaX0uvoz-jk6zcWj3QK9L6QO00/)
[0020] LazyUrl(https://www.instagram.com/p/Bug3IPMD86SLxy-oe3pWSbGUfm1la6-Egmjgfc0/)
[0021] LazyUrl(https://www.instagram.com/p/Bud9CEDHECZqoY6nMupO0JCcK_qrjclD3OqVaY0/)

[Messages]
Failed to get stories; Login required: None
stories: 17987144404211438
-i "stories_2015548712809651409.mp4" -map 0:v:0 -c copy -f null -
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'stories_2015548712809651409.mp4': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Duration: 00:00:03.07, start: 0.000000, bitrate: 384 kb/s 
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x1136 [SAR 639:640 DAR 9:16], 316 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default) 
Metadata: 
handler_name : Core Media Video 
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default) 
Metadata: 
handler_name : Core Media Audio 
Output #0, null, to 'pipe:': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x1136 [SAR 639:640 DAR 9:16], q=2-31, 316 kb/s, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default) 
Metadata: 
handler_name : Core Media Video 
Stream mapping: 
Stream #0:0 -> #0:0 (copy) 
Press [q] to stop, [?] for help 
frame= 89 fps=0.0 q=-1.0 Lsize=N/A time=00:00:02.86 bitrate=N/A speed=6.19e+03x 
video:115kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 

-ss 0.57 -noaccurate_seek -i "stories_2015548712809651409.mp4" -vframes 1 "C:\Users\user\AppData\Local\Temp\tmpdb28d7cb089b4fc89998dcc17d6f04e0_o.png"
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'stories_2015548712809651409.mp4': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Duration: 00:00:03.07, start: 0.000000, bitrate: 384 kb/s 
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x1136 [SAR 639:640 DAR 9:16], 316 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default) 
Metadata: 
handler_name : Core Media Video 
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default) 
Metadata: 
handler_name : Core Media Audio 
Stream mapping: 
Stream #0:0 -> #0:0 (h264 (native) -> png (native)) 
Press [q] to stop, [?] for help 
Output #0, image2, to 'C:\Users\user\AppData\Local\Temp\tmpdb28d7cb089b4fc89998dcc17d6f04e0_o.png': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Stream #0:0(und): Video: png, rgb24, 640x1136 [SAR 639:640 DAR 9:16], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default) 
Metadata: 
handler_name : Core Media Video 
encoder : Lavc58.35.100 png 
frame= 1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A dup=0 drop=15 speed=0.412x 
video:245kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 

-i "stories_2015548712809651409.mp4" -map 0:v:0 -c copy -f null -
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'stories_2015548712809651409.mp4': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Duration: 00:00:03.07, start: 0.000000, bitrate: 384 kb/s 
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x1136 [SAR 639:640 DAR 9:16], 316 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default) 
Metadata: 
handler_name : Core Media Video 
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default) 
Metadata: 
handler_name : Core Media Audio 
Output #0, null, to 'pipe:': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x1136 [SAR 639:640 DAR 9:16], q=2-31, 316 kb/s, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default) 
Metadata: 
handler_name : Core Media Video 
Stream mapping: 
Stream #0:0 -> #0:0 (copy) 
Press [q] to stop, [?] for help 
frame= 89 fps=0.0 q=-1.0 Lsize=N/A time=00:00:02.86 bitrate=N/A speed=5.5e+03x 
video:115kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 

-ss 0.57 -noaccurate_seek -i "stories_2015548712809651409.mp4" -vframes 1 "C:\Users\user\AppData\Local\Temp\tmpc43a3170ca9f49daba3ea7437a1c2735_o.png"
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'stories_2015548712809651409.mp4': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Duration: 00:00:03.07, start: 0.000000, bitrate: 384 kb/s 
Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x1136 [SAR 639:640 DAR 9:16], 316 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default) 
Metadata: 
handler_name : Core Media Video 
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default) 
Metadata: 
handler_name : Core Media Audio 
Stream mapping: 
Stream #0:0 -> #0:0 (h264 (native) -> png (native)) 
Press [q] to stop, [?] for help 
Output #0, image2, to 'C:\Users\user\AppData\Local\Temp\tmpc43a3170ca9f49daba3ea7437a1c2735_o.png': 
Metadata: 
major_brand : isom 
minor_version : 512 
compatible_brands: isomiso2avc1mp41 
encoder : Lavf58.20.100 
Stream #0:0(und): Video: png, rgb24, 640x1136 [SAR 639:640 DAR 9:16], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default) 
Metadata: 
handler_name : Core Media Video 
encoder : Lavc58.35.100 png 
frame= 1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A dup=0 drop=15 speed=0.412x 
video:245kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 

LazyUrl error (https://www.instagram.com/p/CCaXF-ZHh3PyLOr884mCEBTUvNMRMpPrtY_Zwk0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B_KgvbInheqpLJ-KHb_Fe-KcY_tR2Kbmw2CqU40/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B8stzzHne99PTxnvkI3_zC4GDLePu5xeHICQ7w0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B29a0j6HlQcySZ0Hl4ccYVFTxDSneGzsZZqGM00/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B6V6sIGnkT-NtWdHGMPDOifi3B8E54o2e8n0eQ0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B3fO1bqHLK5xBY-tcNY3xJK4F7wDLA8Pp3kn1w0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B29P1JeHN2g7aW6nZJkqOJbpKiVvNb4ESdMAZQ0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B26e_xGHIePJNrFmt6bJeRQmFHoX3SD378kHvw0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B1Wm2RbHWxkdTUt1hYxLifmqm7xoh4Kv4jgM-40/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bzk7Z0NnuDLaPwIM3YJ__Dh7L6oTkCnM_y5IC40/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BzkHd5nHVAoWTCcsjdRpz5lqw9TpxFp9wzT0780/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bw1-QXQgDcWtuLxdcsk6GI1gpOe7bXEnvQuwcg0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bv7HvdJgCa9fyaElw1QmElEVErchA1a_IqZ8DM0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bwwl_0dg3eGfTQlb3We080_G3d8h3sVfotaTR80/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BxzKgpmnc_6gVw53P7dSjXmUZaInqmHQQNSFaw0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bv4oku3Ad2GGLGStfy3JVKmsI8KD2e-iOEDb5U0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BvCSs1RAMqXVH2IwwcBTjTIj2jOUEGMdS35NcU0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bu5ZQTOA-ZhFHLaX0uvoz-jk6zcWj3QK9L6QO00/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bud9CEDHECZqoY6nMupO0JCcK_qrjclD3OqVaY0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bug3IPMD86SLxy-oe3pWSbGUfm1la6-Egmjgfc0/):
Traceback (most recent call last):
File "hitomi_downloader", line 226, in run
File "utils", line 690, in __call__
File "<decorator-gen-9>", line 2, in get
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\insta_downloader", line 183, in get
File "extractor\insta_downloader", line 328, in __init__
File "extractor\insta_downloader", line 119, in get_sd
Exception: no _sharedData

stop
valid=False 1
EOT: https://www.instagram.com/xx_fqqqq

**Comment by KurtBestor** [comment]
다시 로그인해서 쿠키 새로 넣어보고 안 되면 알려주세요.

**Comment by ij1510** [comment]
혹시 몰라서 사흘정도 텀을 두고 다시 시도해도 같은 현상이 일어납니다.
