### ISSUE TITLE
갑자기 검색기 데이터 갱신이 안되네요

### ISSUE THREAD

**Issue by whfflsek** [KurtBestor/Hitomi-Downloader#2540]
데이터 다운로드에 실패했다고 나옵니다.

Traceback (most recent call last):
  File "hitomi_searcher", line 217, in download_json
  File "hitomi_searcher", line 375, in download_json_
  File "json\__init__", line 348, in loads
  File "json\decoder", line 337, in decode
  File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KurtBestor** [comment]
지금도 안 되나요?
