### ISSUE TITLE
Pornhub 채널 다운로드 문제

### ISSUE THREAD

**Issue by Sisquaker** [KurtBestor/Hitomi-Downloader#2546]
폰헙이나 폰헙프리미엄에서 다운로드 중, 리스트 다운로드가 제대로 작동하지 않는군요...

확인결과 channel 이나, pornstar 에서는 정상적으로 작동하지만

model 은 전부 안되는군요.

수정이 필요합니다...

Invalid: [pornhub] https://www.pornhub.com / model / lady-wow

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 2
group: False
input: https://www.pornhub.com/model/lady-wow
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/model/lady-wow
valid: False
done: True
range: None
range_p: None
single: True
time: 1601536102.6416576 (Oct 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
videos
invalid soup: https://www.pornhub.com/model/lady-wow
clf solved
https://www.pornhub.com/model/lady-wow/videos/upload/ajax?o=mr&page=1 (0)
break: no lis
local variable 'e_' referenced before assignment
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\pornhub_downloader", line 158, in read
UnboundLocalError: local variable 'e_' referenced before assignment

Invalid: fail=True
EOT: https://www.pornhub.com/model/lady-wow

**Comment by KurtBestor** [comment]
지금도 안 되나요?
