### ISSUE TITLE
네이버 웹툰 다운 실패

### ISSUE THREAD

**Issue by RuPeo** [KurtBestor/Hitomi-Downloader#2549]
네이버 웹툰 일부중 다운이 안되는 웹툰이 있어서 알려드립니다.

Invalid: [navertoon] https://comic.naver.com / webtoon / list.nhn?titleId=730148

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://comic.naver.com/webtoon/list.nhn?titleId=730148
dir: 
zip: 
type: navertoon
artist: None
url: https://comic.naver.com/webtoon/list.nhn?titleId=730148
valid: False
done: True
range: None
range_p: None
single: False
time: 1601701182.578707 (Oct 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "extractor\navertoon_downloader", line 113, in get_pages
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1000, in start
File "extractor\navertoon_downloader", line 52, in init
File "<decorator-gen-13>", line 2, in get_pages
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\navertoon_downloader", line 121, in get_pages
Exception: Age verification is required for service. Please sign in.

Invalid: fail=True
EOT: https://comic.naver.com/webtoon/list.nhn?titleId=730148

stop
Traceback (most recent call last):
File "extractor\navertoon_downloader", line 113, in get_pages
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1000, in start
File "extractor\navertoon_downloader", line 52, in init
File "<decorator-gen-13>", line 2, in get_pages
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\navertoon_downloader", line 121, in get_pages
Exception: Age verification is required for service. Please sign in.

Invalid: fail=True
EOT: https://comic.naver.com/webtoon/list.nhn?titleId=730148

이게 에러 내용입니다...

**Comment by KurtBestor** [comment]
로그인 쿠키를 넣으세요.
