### ISSUE TITLE
웨이보나 SNS 일부에서 다시 시작 기능이 동작하지 않습니다 

### ISSUE THREAD

**Issue by mju00rian** [KurtBestor/Hitomi-Downloader#2554]
기존 다운로드 이슈 글에 있던 테스트 버전도 사용해보고 했지만 변함없이 다시 시작 기능시 주황색 삼각형에 느낌표 표시가 뜨면서 다운로드가 이뤄지지 않고 있습니다

특히 웨이보에서 이 현상이 두드러지게 나타나고 있습니다 
웨이보 쿠키는 넣었습니다 

테스트 링크 : weibo.com/u/1752376494

Money不太甜 (weibo_1752376494)

version: 2.8 (20-10-03 20:18:49 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 789
group: False
input: weibo.com/u/1752376494
dir: hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)
zip: 
type: weibo
artist: None
url: weibo.com/u/1752376494
valid: False
done: True
range: None
range_p: None
single: False
time: 1600924161.8330853 (Sep 24)
tags: []
goodbyedpi: False
lock: True
color: invalid_done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-09-10] 4547686612606599.jpg
[0002] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-09-01] 4544430190231557.jpg
[0003] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-09-01] 4544430186299887.jpg
[0004] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-08-30] 4543687538639115.jpg
[0005] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-08-30] 4543687538377000.jpg
[0006] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-08-30] 4543687538376917.jpg
[0007] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-07-26] 4531027206734503.jpg
[0008] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-07-21] 4529247605752850.jpg
[0009] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-06-19] 4517650665657372.jpg
[0010] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-06-14] 4515839833713930.jpg
[0011] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-06-09] 4514036505765564.jpg
[0012] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-06-07] 4513201387855673.jpg
[0013] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-06-07] 4513201387508422.jpg
[0014] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-05-23] 4507764062380558.jpg
[0015] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-05-23] 4507529923032697.jpg
[0016] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-05-18] 4506000153523958.jpg
[0017] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-05-18] 4506000153523956.jpg
[0018] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-05-16] 4505307936108332.jpg
[0019] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-05-09] 4502654783080225.jpg
[0020] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-28] 4498808601419677.jpg
[0021] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-25] 4497664038734491.jpg
[0022] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-17] 4494485711334345.jpg
[0023] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-17] 4494485711334344.jpg
[0024] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-17] 4494485711334343.jpg
[0025] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-17] 4494485711151334.jpg
[0026] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-12] 4492992037146576.jpg
[0027] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-04-03] 4489688809428841.jpg
[0028] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-03-31] 4488613267998993.jpg
[0029] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[20-03-28] 4487233161579592.jpg
[0030] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[19-08-29] 4410665979740314.jpg
[0031] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[19-08-28] 4410239070896196.jpg
[0032] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[19-02-19] 4341426933658955.jpg
[0033] hitomi_downloaded_weibo\Money不太甜 (weibo_1752376494)\[14-07-26] 3736619533338636.jpg

[URLs]

[Messages]
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1016, in start
File "utils", line 1062, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert
no html
clf solved
uid: 1752376494, oid:1005051752376494
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1016, in start
File "utils", line 1062, in start_
File "extractor\weibo_downloader", line 49, in read
File "extractor\weibo_downloader", line 155, in get_imgs
File "extractor\weibo_downloader", line 142, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: weibo.com/u/1752376494

invalid; revert

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/97100199-37348a00-16d4-11eb-9a25-1a3be5db1852.png)

재현할 수가 없네요. 웹브라우저에서 직접 보는 건 되나요?

**Comment by mju00rian** [comment]
답이 너무 늦어 죄송합니다
예 웹브라우저에서는 평범하게 들어가집니다

2020년 10월 25일 (일) 오후 3:11, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by KurtBestor** [comment]
계속 시도해도 안 되나요?

**Comment by mju00rian** [comment]
예 몇 번을 시도해도 변함이 없습니다
페이스북은 비슷한 증상에서 여러번 시도하면 제대로 다운로드가 완료되곤하는데 웨이보는 몇번을 시도해도 똑같은 현상입니다

2020년 11월 11일 (수) 오전 2:32, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mju00rian** [comment]
다운로드 실패 시 작업 정보가 바로 뜨는 아이콘이 생겼지만 작업이 진행되지 않는 점은 변화 없습니다
테스트 버전에서 작업 정보 클릭하여 나온 메시지 입니다

Invalid: [weibo] https://weibo.com/u/6880826706

version: 3.2a (20-11-11 21:29:17 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://weibo.com/u/6880826706
dir:
zip:
type: weibo
artist: None
url: https://weibo.com/u/6880826706
valid: False
done: True
range: None
range_p: None
single: False
time: 1605141869.6130056 (Nov 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
no html
not f
clf solved
uid: 6880826706, oid:1005056880826706
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 157, in get_imgs
File "<decorator-gen-109>", line 2, in get_albums
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\weibo_downloader", line 144, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: https://weibo.com/u/6880826706

2020년 11월 12일 (목) 오전 12:45, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by KurtBestor** [comment]
여기 들어가면 어떻게 보이나요?: https://photo.weibo.com/6880826706/albums?rd=1

**Comment by mju00rian** [comment]
[image: 화면 캡처 2020-11-12 121551.jpg]
이렇게 보입니다

2020년 11월 12일 (목) 오전 10:25, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by KurtBestor** [comment]
이미지가 안 보여요.

여기 직접 와서 달아주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2554

**Comment by mju00rian** [comment]
![화면 캡처 2020-11-12 121551](https://user-images.githubusercontent.com/64242744/98943377-b9c1a400-2532-11eb-9753-80586af16d69.jpg)
예 다시 올렸습니다 감사합니다

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mju00rian** [comment]
> 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

감사합니다
확인해보니 동일한 증상이 발생하고 있으며, 작업 정보 창의 메시지는 아래와 같습니다 

Invalid: [weibo] https://weibo.com/u/6880826706

version: 3.2a (20-11-12 19:00:53 UTC)
platform: Windows-10-10.0.18362-SP0
order: 18
group: False
input: https://weibo.com/u/6880826706
dir: 
zip: 
type: weibo
artist: None
url: https://weibo.com/u/6880826706
valid: False
done: True
range: None
range_p: None
single: False
time: 1605237600.3797421 (Nov 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
no html
not f
clf solved
uid: 6880826706, oid:1005056880826706
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 157, in get_imgs
File "<decorator-gen-109>", line 2, in get_albums
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\weibo_downloader", line 144, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: https://weibo.com/u/6880826706

no html
not f
not f
not f
not f
no html
clf solved
uid: 6880826706, oid:1005056880826706
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: https://weibo.com/u/6880826706

no html
clf solved
uid: 6880826706, oid:1005056880826706
Expecting value: line 2 column 3 (char 3)
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\weibo_downloader", line 50, in read
File "extractor\weibo_downloader", line 156, in get_imgs
File "extractor\weibo_downloader", line 143, in get_albums
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

Invalid: fail=True
EOT: https://weibo.com/u/6880826706

**Comment by mju00rian** [comment]
해결되었습니다. PC에서 로그인했을 때 웨이보 앱의 QR코드로 로그인 후 쿠키를 추출했었던 것이 문제가 된 듯 합니다
아이디 비번 로그인 후 QR 코드 인증하자 정상 다운로드가 이뤄지고 있습니다 
좋은 프로그램 항상 감사드립니다
