### ISSUE TITLE
유튜브 연령제한영상 다운오류 문제

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2558]
안녕하세요 존경하는 KurtBestor 선생님!

현재 최신버전에서 쿠키 늘 하던 방식대로 구동중인데 유튜브 연령제한영상만 다운이 안되는 증상입니다.

로그는 아래와 같습니다!

---------------------------------------------------------------------------------

Invalid: [youtube] https://www.youtube.com / watch?v=1UxuuwylNGU

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://www.youtube.com/watch?v=1UxuuwylNGU
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=1UxuuwylNGU
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1601981951.4466512 (Oct 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 530, in extract
File "youtube_dl\extractor\youtube", line 1894, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

No videos
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=1UxuuwylNGU

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by tdi2020** [comment]
네 지금도 안되네요 ㅠㅠ 
연령제한의 경우 영상도 채널도 안되는것 같은데 같은 증상인지는 모르겠습니다!
연령제한도 잘 봐지는 상태의 연령확인 계정을 쿠키 내보내서 불러오기까지 잘 했는데 안되네요.

A 테스트 영상 : https://www.youtube.com/watch?v=1UxuuwylNGU

B 테스트 채널 : https://www.youtube.com/channel/UCsqRr_bHxNFB56VCZQiLChg


----------------------------------------------------------------------------------------------------------------------
**A(영상) 오류메세지**
Invalid: [youtube] https://www.youtube.com/watch?v=1UxuuwylNGU

version: 3.2a (20-11-05 18:20:09 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://www.youtube.com/watch?v=1UxuuwylNGU
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=1UxuuwylNGU
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1605313819.2816563 (Nov 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: 1UxuuwylNGU: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: 1UxuuwylNGU: YouTube said: Unable to extract video data

No videos
stop
Traceback (most recent call last):
File "utils", line 1030, in start
File "utils", line 1077, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=1UxuuwylNGU
----------------------------------------------------------------------------------------------------------------------








----------------------------------------------------------------------------------------------------------------------
**B(채널) 오류메세지**
Invalid: [youtube] https://www.youtube.com/channel/UCsqRr_bHxNFB56VCZQiLChg

version: 3.2a (20-11-05 18:20:09 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/channel/UCsqRr_bHxNFB56VCZQiLChg
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/channel/UCsqRr_bHxNFB56VCZQiLChg
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1605313999.6385133 (Nov 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}


[Gallery]
None


[File Names]



[URLs]



[Messages]
No videos
stop
Traceback (most recent call last):
File "utils", line 1030, in start
File "utils", line 1077, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/channel/UCsqRr_bHxNFB56VCZQiLChg
----------------------------------------------------------------------------------------------------------------------

**Comment by tdi2020** [comment]
<비 연령제한 영상 다운중 발생한 Invalid>

youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

에러 메세지에 요부분이 있던데... 이게 무엇일까요? 
연령제한이 아닌 그냥 다운로드 시도(음악)인데도Invaild가 되어요.  분명 연령제한 아니면 다운되는 쿠키였는데..
갑자기 다받구 변환중 상태에서 멈춤-> 그담부턴 이렇게 되면서 아예 invalid 되어버리네요ㅠㅠ

혹시 다운로드를 시도한 계정을 밴당하는 걸까요? 
왜냐하면 이러구 난 뒤부터는 해당 쿠키로 다른 어느것도 똑같이 Invaild 되는듯 합니다.


시도한 주소 : https://www.youtube.com/watch?v=xUsE-DTkWWk



__________________________________________________________________________________________

Invalid: [youtube] https://www.youtube.com/watch?v=xUsE-DTkWWk

version: 3.2a (20-11-05 18:20:09 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=xUsE-DTkWWk
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=xUsE-DTkWWk
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1605323231.17594 (Nov 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\extractor\common", line 632, in _request_webpage
File "youtube_dl\YoutubeDL", line 2238, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1798, in _real_extract
File "youtube_dl\extractor\youtube", line 277, in _download_webpage_handle
File "youtube_dl\extractor\common", line 665, in _download_webpage_handle
File "youtube_dl\extractor\common", line 650, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

No videos
stop
Traceback (most recent call last):
File "utils", line 1030, in start
File "utils", line 1077, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=xUsE-DTkWWk

**Comment by KurtBestor** [comment]
영상 정보 추출할 때 [youtube-dl](https://youtube-dl.org) 쓰는데 임베딩 금지한 영상은 추출 못하는 것 같아요.
채널은 이거 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2124
429 뜨는 건 이거 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1816#issuecomment-606793783
