### ISSUE TITLE
페이스북 다운 오류

### ISSUE THREAD

**Issue by rnsrnsrhrnak** [KurtBestor/Hitomi-Downloader#2562]
[Messages]
No photo div
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\facebook_downloader", line 106, in read
File "extractor\facebook_downloader", line 147, in get_imgs
Exception: No photo div

--------------------------------------------------------------------------------------------------

[Messages]
no name
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\facebook_downloader", line 104, in read
File "extractor\facebook_downloader", line 90, in name
File "extractor\facebook_downloader", line 125, in get_title
Exception: no name

이런 오류들 뜨는데 [페이스북[](url)]( #2417 ) 이 이슈는 아직 안고쳐진 건가요?
항상 감사드립니다

**Comment by KurtBestor** [comment]
네, 좀 복잡해서 시간이 걸리네요.
