### ISSUE TITLE
다음웹툰 다운불가작품

### ISSUE THREAD

**Issue by Lisrim** [KurtBestor/Hitomi-Downloader#2571]
다음웹툰중 다운이안되는게있어서 문의드립니다.

Invalid: [daumtoon] http://webtoon.daum.net / webtoon / view / p_dinner

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 1
group: False
input: http://webtoon.daum.net/webtoon/view/p_dinner
dir: 
zip: 
type: daumtoon
artist: None
url: http://webtoon.daum.net/webtoon/view/p_dinner
valid: False
done: True
range: None
range_p: None
single: True
time: 1602236886.5947456 (Oct 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "extractor\daumtoon_downloader", line 130, in init
File "extractor\daumtoon_downloader", line 67, in get_info
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: http://webtoon.daum.net/webtoon/view/p_dinner

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
