### ISSUE TITLE
pornhub 다운이 안됩니다

### ISSUE THREAD

**Issue by swlight** [KurtBestor/Hitomi-Downloader#2581]
Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph5e66748e60ac4

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.pornhub.com/view_video.php?viewkey=ph5e66748e60ac4
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5e66748e60ac4
valid: False
done: True
range: None
range_p: None
single: True
time: 1602425399.5491679 (Oct 11)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\pornhub_downloader", line 185, in read
File "<decorator-gen-24>", line 2, in get_video
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\pornhub_downloader", line 242, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e66748e60ac4

**Comment by KurtBestor** [comment]
이 문제와 비슷해보이는데 확인해보세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2237
