### ISSUE TITLE
GoodbyeDpi 우회가 안되는 것 같습니다

### ISSUE THREAD

**Issue by yjjjon** [KurtBestor/Hitomi-Downloader#2587]
로딩만 계속되고 결국 아래 메시지가 나오면서 닫기네요

Traceback (most recent call last):
  File "urllib\request", line 1319, in do_open
  File "http\client", line 1252, in request
  File "http\client", line 1298, in _send_request
  File "http\client", line 1247, in endheaders
  File "http\client", line 1026, in _send_output
  File "http\client", line 966, in send
  File "http\client", line 1414, in connect
  File "http\client", line 938, in connect
  File "socket", line 728, in create_connection
  File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 289, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 543, in _open
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 1362, in https_open
  File "urllib\request", line 1321, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connection", line 160, in _new_conn
  File "site-packages\urllib3\util\connection", line 84, in create_connection
  File "site-packages\urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool", line 677, in urlopen
  File "site-packages\urllib3\connectionpool", line 381, in _make_request
  File "site-packages\urllib3\connectionpool", line 976, in _validate_conn
  File "site-packages\urllib3\connection", line 308, in connect
  File "site-packages\urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000000F2703C6508>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 449, in send
  File "site-packages\urllib3\connectionpool", line 725, in urlopen
  File "site-packages\urllib3\util\retry", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kurtbestor.github.io', port=443): Max retries exceeded with url: /res/tags.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000000F2703C6508>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 317, in read_html
  File "requests\api", line 76, in get
  File "requests\api", line 61, in request
  File "downloader", line 97, in session_request
  File "requests\sessions", line 530, in request
  File "requests\sessions", line 643, in send
  File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kurtbestor.github.io', port=443): Max retries exceeded with url: /res/tags.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000000F2703C6508>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connection", line 160, in _new_conn
  File "site-packages\urllib3\util\connection", line 84, in create_connection
  File "site-packages\urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_gui", line 6089, in updateCompleter
  File "downloader", line 414, in read_html
  File "downloader", line 332, in read_html
  File "site-packages\urllib3\poolmanager", line 336, in urlopen
  File "site-packages\urllib3\connectionpool", line 725, in urlopen
  File "site-packages\urllib3\util\retry", line 379, in increment
  File "site-packages\urllib3\packages\six", line 735, in reraise
  File "site-packages\urllib3\connectionpool", line 677, in urlopen
  File "site-packages\urllib3\connectionpool", line 381, in _make_request
  File "site-packages\urllib3\connectionpool", line 976, in _validate_conn
  File "site-packages\urllib3\connection", line 308, in connect
  File "site-packages\urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000000F27F4B5CC8>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

해결 방법이 있을까요?

**Comment by KurtBestor** [comment]
프록시 쓰시는 것 있나요?
