### ISSUE TITLE
픽시브 코믹이 다운이 되질않습니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#2589]
항상 감사히 잘 쓰고있습니다
픽시브 코믹이 잘되다가 갑자기 되질않네요
정보는 이렇습니다

Invalid: [pixiv_comic] https://comic.pixiv.net / works / 6939

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 4
group: False
input: https://comic.pixiv.net/works/6939
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/6939
valid: False
done: True
range: None
range_p: None
single: False
time: 1602656661.3560376 (Oct 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\pixiv_comic_downloader", line 73, in read
File "extractor\pixiv_comic_downloader", line 59, in name
File "extractor\pixiv_comic_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6939

clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\pixiv_comic_downloader", line 73, in read
File "extractor\pixiv_comic_downloader", line 59, in name
File "extractor\pixiv_comic_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6939

clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\pixiv_comic_downloader", line 73, in read
File "extractor\pixiv_comic_downloader", line 59, in name
File "extractor\pixiv_comic_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6939

clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\pixiv_comic_downloader", line 73, in read
File "extractor\pixiv_comic_downloader", line 59, in name
File "extractor\pixiv_comic_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6939

**Comment by wlskekrk** [comment]
갑자기 또 잘되네요 이건 무시하셔도 될듯합니다
