### ISSUE TITLE
유튜브 4K VR 영상이 다운 안 되네요.

### ISSUE THREAD

**Issue by 82cypher** [KurtBestor/Hitomi-Downloader#2606]
어떤 것은 VR은 커녕 일반영상만 다운이 되는 것도 있어요.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by mrbobfive** [comment]
Invalid: [youtube] https://www.youtube.com / watch?v=2VvufOqFRPU

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=2VvufOqFRPU
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=2VvufOqFRPU
valid: False
done: True
range: None
range_p: None
single: True
time: 1603715046.8778527 (Oct 26)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}


[Gallery]
None


[File Names]



[URLs]



[Messages]
[None][0fps][50kbps] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (tiny)
[None][30fps][None] webm [vp9 / None] ─ 278 - 256x144 (144s)
[None][30fps][None] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (144s)
[None][30fps][None] webm [vp9 / None] ─ 242 - 424x240 (240s)
[None][30fps][None] mp4 [avc1.4d4015 / None] ─ 133 - 424x240 (240s)
[None][30fps][None] webm [vp9 / None] ─ 243 - 640x360 (360s)
[None][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360s)
[None][30fps][None] webm [vp9 / None] ─ 244 - 848x480 (480s)
[None][30fps][None] mp4 [avc1.4d401f / None] ─ 135 - 848x480 (480s)
[None][30fps][None] webm [vp9 / None] ─ 247 - 1280x720 (720s)
[None][30fps][None] mp4 [avc1.4d401f / None] ─ 136 - 1280x720 (720s)
[None][60fps][None] webm [vp9 / None] ─ 302 - 1280x720 (720s60)
[None][30fps][None] webm [vp9 / None] ─ 248 - 1920x1080 (1080s)
[None][60fps][None] mp4 [avc1.4d4020 / None] ─ 298 - 1280x720 (720s60)
[None][30fps][None] mp4 [avc1.640028 / None] ─ 137 - 1920x1080 (1080s)
[None][60fps][None] webm [vp9 / None] ─ 303 - 1920x1080 (1080s60)
[None][60fps][None] mp4 [avc1.64002a / None] ─ 299 - 1920x1080 (1080s60)
[None][60fps][None] webm [vp9 / None] ─ 272 - 2560x2880 (2160s60)
[None][30fps][None] webm [vp9 / None] ─ 271 - 2560x1440 (1440s)
[None][30fps][None] mp4 [avc1.640032 / None] ─ 264 - 2560x1440 (1440s)
[None][30fps][None] mp4 [avc1.640033 / None] ─ 266 - 2560x2160 (2160s)
[None][30fps][None] webm [vp9 / None] ─ 313 - 2560x2160 (2160s)
[None][60fps][None] mp4 [avc1.640033 / None] ─ 304 - 2560x1440 (1440s60)
[None][60fps][None] mp4 [avc1.640033 / None] ─ 305 - 2560x2160 (2160s60)
[None][60fps][None] webm [vp9 / None] ─ 308 - 2560x1440 (1440s60)
[None][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360s)
[None][30fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720s)


No videos
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=2VvufOqFRPU

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mrbobfive** [comment]
다운은 잘 되요.
플레이어가 문제인지 다운로더가 문제인지 모르겠지만, VR이 안 되는군요.

2020년 11월 12일 (목) 오전 1:30, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by kyul4510** [comment]
유튜브 요즘 VR 영상은 제대로 다운이 안되는듯 합니다

https://youtu.be/I5yLb_0oBtI?si=enKUefi0QILdMoEF

예를 들어 이 영상을 다운 받으면 
VR영상이 아니라 평면영상으로 다운되는거 같아요
해결법을 찾아보니 파이썬을 이용해야 한다는 글을 봤습니다

https://m.cafe.naver.com/ca-fe/web/cafes/vrmaniac/articles/232569?useCafeId=false&tc

히토미다운로더에도 적용이 가능할까요?
