### ISSUE TITLE
히XX 다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2609]
[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://hitomi.la/galleries/1759700.html
dir: hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)
zip: 
type: hitomi
artist: 4why, chicke iii
url: https://hitomi.la/doujinshi/ai-no-toukakoukan-|-사랑의-등가교환-한국어-1759700.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1603244425.5083697 (Oct 21)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None

[Gallery]
갤러리 넘버: 1759700

제목: Ai no Toukakoukan ｜ 사랑의 등가교환

작가: 4why, chicke iii

그룹: bad mushrooms

타입: doujinshi

시리즈: sword art online

캐릭터: chudelkin, eugeo, quinella

태그: female:big breasts

언어: Korean

[File Names]
[0001] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\01.jpg
[0002] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\02.jpg
[0003] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\03.jpg
[0004] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\04.jpg
[0005] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\05.jpg
[0006] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\06.jpg
[0007] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\07.jpg
[0008] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\08.jpg
[0009] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\09.jpg
[0010] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\10.jpg
[0011] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\11.jpg
[0012] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\12.jpg
[0013] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\13.jpg
[0014] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\14.jpg
[0015] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\15.jpg
[0016] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\16.jpg
[0017] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\17.jpg
[0018] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\18.jpg
[0019] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\19.jpg
[0020] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\20.jpg
[0021] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\21.jpg
[0022] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\22.jpg
[0023] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\23.jpg
[0024] hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\24.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/e/b8/c28bd74bd1ea7f50f1f8f4ff6c98f00a5fabaac68e6e80e028f731db09811b8e.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/a/40/7602f15eec0e40c14d84a27f62dfe4376dfa52ff4c8c73b1039b5c29f051940a.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/d/74/1c0879e2d4cbb861f1aff6dd48bd5b15106e2220eb2b1ad5f6b759dad6c7b74d.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/4/9d/28ef5538d02184346aaf9028bd74e374948e8a7229da143ea1742e64932a19d4.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://aa.hitomi.la/images/8/10/792815ff6ef03ae8ea2c56712f44485f488b2d3693153b962a14684694361108.jpg
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/6/41/0258943bb35f6fc96578e46d2318e3c005d35191afd3e30f526754c726fad416.jpg
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/0/3e/d29787c67ab4d2a5e289f658bbdf7dcb722efa4f5eb474decaa1f1c0683643e0.jpg
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/2/44/fc0718cfca108bd926aeab635f9df8bf0003f5fb55ffdc8def1239608b61d442.jpg
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/6/6d/363c7a98e87552e357edfe07c78b8e968fa448e6485d07ed115e9bfaab8a96d6.jpg
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://aa.hitomi.la/images/a/c9/421870cd4a79a70e756cb115aa3d18d0c269ff8b37522e1f892bdfc97780ec9a.jpg
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/a/29/0fd59e9f6a73f249554cf3ac8730b109e5cbbd1b180ceca80281b635633b329a.jpg
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://aa.hitomi.la/images/6/66/fe968edc0410fc8be2d0883eeb25048130ade567398714093e0b7646dc256666.jpg
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/2/be/f231221e8034301c3d4acac8cb7756bf8a66e5322629b86879a08a9fc7194be2.jpg
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/7/4d/af7fed083db52b5ebdd986d9849a54ec4bbcdb3c6f6a4210f90179acb13a24d7.jpg
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/7/11/7c296cbdba83d2b278181d648f5d34bdcda3c3114f1288672e7c903be46ef117.jpg
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/6/47/0d2752f3a978b562878b53d481541adb52a73437ea7a41251be7070f3f42c476.jpg
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/a/d6/a4c795974064a8d7e06f2fe1359caf4500ef2f270cafb84f862e1a4bf861ad6a.jpg
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://aa.hitomi.la/images/0/96/1d31ea1423212c18e54437fc8939cfab74b354ae2e6bd7b584b001cc3e6c4960.jpg
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ca.hitomi.la/images/5/8c/4e1422e27009e35c86465e07cd7775b69acf2de859a77d751e42936e6786f8c5.jpg
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/b/d0/a4c0786bc39c3f524ce7ea707f4ba74a9a26a1039e2e3ffde5de19063768cd0b.jpg
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://aa.hitomi.la/images/4/c0/aa08b8ba9df6c3a1656f5e36f8e2674813ef9b8f731e576ef482271fb391fc04.jpg
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/2/73/8949d1961465685f035d3e0164cf45ca471413613d1b2a8488c7795935e80732.jpg
[0023] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/1/40/8d0f080a006575fafaee06b609e56a42eeebc2ea6fc972a648652686d4533401.jpg
[0024] LazyUrl_hitomi(https://hitomi.la/reader/1759700.html) ---> https://ba.hitomi.la/images/0/c4/bf4a19a72c4c3ecce30f9c296d036f4af214844f4120df5f93dc182d3fbc8c40.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 24
get_title__

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\10.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\04.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\12.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\03.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\09.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\11.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\13.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\15.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\21.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\18.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\20.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\23.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\17.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\14.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\05.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\07.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\16.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\19.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\22.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\24.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\06.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\01.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\02.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\download\HItomi Downloader 0.5\hitomi_downloader_GUI_test\hitomi_downloaded\[4why, Chicke Iii] Ai no Toukakoukan ｜ 사랑의 등가교환 (1759700)\08.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/galleries/1759700.html

히XX 다운이 안됩니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631

**Comment by geniussjt** [comment]
정말 감사합니다^^
