### ISSUE TITLE
픽시브코믹, lhscan이 다운이 되질 않습니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#2645]
항상 감사히 잘 사용하고 있습니다
오류후 올려주신 테스트버전을 쓰고 있는데요
픽시브코믹은 다운로드가 다 안되구요
lhscan은 되는것도 있고 안되는것도 있습니다
각각 정보 올립니다

픽시브코믹

Invalid: [pixiv_comic] https://comic.pixiv.net/works/6968

version: 3.1 (20-10-23 08:11:20 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 2
group: False
input: https://comic.pixiv.net/works/6968
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/6968
valid: False
done: True
range: None
range_p: None
single: False
time: 1603625008.922464 (Oct 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1027, in start
File "utils", line 1079, in start_
File "extractor\pixiv_comic_downloader", line 73, in read
File "extractor\pixiv_comic_downloader", line 59, in name
File "extractor\pixiv_comic_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6968

lhscan의 정보입니다

ANI NO YOME TO KURASHITE IMASU. - RAW

version: 3.1 (20-10-23 08:11:20 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 1
group: False
input: https://loveheaven.net/manga-ani-no-yome-to-kurashite-imasu.-raw.html
dir: hitomi_downloaded_lhscan\ANI NO YOME TO KURASHITE IMASU. - RAW
zip: 
type: lhscan
artist: None
url: https://loveheaven.net/manga-ani-no-yome-to-kurashite-imasu.-raw.html
valid: True
done: True
range: None
range_p: [57]
single: False
time: 1603625158.8900416 (Oct 25)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
clf solved
stop
EOT: https://loveheaven.net/manga-ani-no-yome-to-kurashite-imasu.-raw.html

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
지금에야 봤습니다 이렇게 올려주셔서 정말 감사합니다
확인해보니 다 잘되네요 lhscan이 특히 안되는게 많았는데 이제 편안합니다
다시 한번 감사드립니다
