### ISSUE TITLE
페이스북 다운이 안되네요

### ISSUE THREAD

**Issue by wc892** [KurtBestor/Hitomi-Downloader#2646]
Invalid: [facebook] https://www.facebook.com / yiseul99

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.facebook.com/yiseul99
dir: 
zip: 
type: facebook
artist: None
url: https://www.facebook.com/yiseul99
valid: False
done: True
range: None
range_p: None
single: False
time: 1603634385.6697197 (Oct 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
No photo div
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\facebook_downloader", line 106, in read
File "extractor\facebook_downloader", line 147, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/yiseul99

No photo div
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\facebook_downloader", line 106, in read
File "extractor\facebook_downloader", line 147, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/yiseul99

No photo div
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\facebook_downloader", line 106, in read
File "extractor\facebook_downloader", line 147, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/yiseul99

어째저째 쿠키에서 파일추가하여 로그인오류는 잡았는데
그 이후 다운이 안되네요

**Comment by hujomaster** [comment]
I'm also having the same problem.

```
Restart in 9m 16s: https://www.facebook.com/Baby.99G

version: 3.4a (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 37 / False / 430c9f84f4124330a962396c643d130e
input: https://www.facebook.com/Baby.99G
type: facebook
single: False
url: https://www.facebook.com/Baby.99G
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~100000 / None
time: 1624598341.4661207 (Jun 25)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
Pages (facebook_Baby.99G)

stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\facebook_downloader", line 122, in read
File "extractor\facebook_downloader", line 163, in get_imgs
errors.LoginRequired

Invalid: fail=False
EOT: https://www.facebook.com/Baby.99G (1.8s)

BabyG Wong (facebook_Baby.99G)
No photo div
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\facebook_downloader", line 122, in read
File "extractor\facebook_downloader", line 169, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/Baby.99G (2.4s)

BabyG Wong (facebook_Baby.99G)
No photo div
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\facebook_downloader", line 122, in read
File "extractor\facebook_downloader", line 169, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/Baby.99G (2.6s)

BabyG Wong (facebook_Baby.99G)
No photo div
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\facebook_downloader", line 122, in read
File "extractor\facebook_downloader", line 169, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/Baby.99G (2.5s)
```

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2417
