### ISSUE TITLE
히토미 압축파일에 작가명이 중복되어 생성됩니다.

### ISSUE THREAD

**Issue by Drillmurata** [KurtBestor/Hitomi-Downloader#2648]
#2631 
설치한 이후로

[Hitomi] [Hitomi] Title.zip

히토미 압축 파일명이 이런식으로 작가명이 중복되서 생성되네요.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by Drillmurata** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.
[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)

version: 3.1 (20-10-23 21:23:43 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 53
group: False
input: [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원-3 (1762485)
dir: hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)
zip: 
type: ehen
artist: takatsu
url: https://exhentai.org/g/1762485/1f6f7f7360
valid: True
done: False
range: None
range_p: None
single: False
time: 1603776951.9407935 (Oct 27)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None


[Gallery]
갤러리 넘버: 1762485

제목: [Takatsu] Fuufunaka Chousain 3 | 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트]

작가: takatsu

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:mind control, female:loli, female:milf, female:oyakodon

언어: Korean


[File Names]
[0001] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000001.jpg
[0002] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000002.jpg
[0003] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000003.jpg
[0004] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000004.jpg
[0005] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000005.jpg
[0006] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000006.jpg
[0007] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000007.jpg
[0008] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000008.jpg
[0009] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000009.jpg
[0010] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000010.jpg
[0011] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000011.jpg
[0012] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000012.jpg
[0013] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000013.jpg
[0014] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000014.jpg
[0015] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000015.jpg
[0016] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000016.jpg
[0017] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000017.jpg
[0018] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000018.jpg
[0019] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000019.jpg
[0020] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000020.jpg
[0021] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000021.jpg
[0022] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000022.jpg
[0023] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000023.jpg
[0024] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000024.jpg
[0025] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000025.jpg
[0026] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000026.jpg
[0027] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000027.jpg
[0028] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000028.jpg
[0029] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000029.jpg
[0030] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000030.jpg
[0031] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000031.jpg
[0032] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000032.jpg
[0033] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000033.jpg
[0034] hitomi_downloaded\[Takatsu] [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원 3 (Saimin Fuufunaka Chousa) [Korean] [애니액트] (1762485)\00000034.jpg


[URLs]
[0001] LazyUrl_ehen(https://exhentai.org/s/9f4100a9c8/1762485-1) ---> https://aaqzhwy.mudrwbjjmsso.hath.network:45302/h/b101dc3eb344131c15959e64238fff6a8ce4d9a9-583080-1280-1860-jpg/keystamp=1603777500-e657e9e707;fileindex=85714625;xres=2400/00000001.jpg
[0002] LazyUrl_ehen(https://exhentai.org/s/9673bd8adc/1762485-2) ---> https://joszoul.zbawdtripyvh.hath.network:22222/h/9673bd8adc513fdaf4969926748f16b5b5b34528-922191-1280-1860-jpg/keystamp=1603777500-91e5275016;fileindex=85714626;xres=org/00000002.jpg
[0003] LazyUrl_ehen(https://exhentai.org/s/9b71abea8a/1762485-3)
[0004] LazyUrl_ehen(https://exhentai.org/s/37dff42713/1762485-4)
[0005] LazyUrl_ehen(https://exhentai.org/s/70d47b2ca2/1762485-5)
[0006] LazyUrl_ehen(https://exhentai.org/s/02a231fec1/1762485-6)
[0007] LazyUrl_ehen(https://exhentai.org/s/e5767fda09/1762485-7)
[0008] LazyUrl_ehen(https://exhentai.org/s/055e61249d/1762485-8)
[0009] LazyUrl_ehen(https://exhentai.org/s/d5a4d7cacf/1762485-9)
[0010] LazyUrl_ehen(https://exhentai.org/s/45e62ee12a/1762485-10)
[0011] LazyUrl_ehen(https://exhentai.org/s/0ccbdf4859/1762485-11)
[0012] LazyUrl_ehen(https://exhentai.org/s/3fb9255eda/1762485-12)
[0013] LazyUrl_ehen(https://exhentai.org/s/452e54d6af/1762485-13)
[0014] LazyUrl_ehen(https://exhentai.org/s/77e11d77fd/1762485-14)
[0015] LazyUrl_ehen(https://exhentai.org/s/171f393422/1762485-15)
[0016] LazyUrl_ehen(https://exhentai.org/s/fc1b71f577/1762485-16)
[0017] LazyUrl_ehen(https://exhentai.org/s/b7790461ee/1762485-17)
[0018] LazyUrl_ehen(https://exhentai.org/s/3450bd336b/1762485-18)
[0019] LazyUrl_ehen(https://exhentai.org/s/70b804b032/1762485-19)
[0020] LazyUrl_ehen(https://exhentai.org/s/1efe1e269a/1762485-20)
[0021] LazyUrl_ehen(https://exhentai.org/s/552ff4485a/1762485-21)
[0022] LazyUrl_ehen(https://exhentai.org/s/5e3cddbeed/1762485-22)
[0023] LazyUrl_ehen(https://exhentai.org/s/bf461af228/1762485-23)
[0024] LazyUrl_ehen(https://exhentai.org/s/d957d30f70/1762485-24)
[0025] LazyUrl_ehen(https://exhentai.org/s/dddfb8d303/1762485-25)
[0026] LazyUrl_ehen(https://exhentai.org/s/7b69269819/1762485-26)
[0027] LazyUrl_ehen(https://exhentai.org/s/648ec37969/1762485-27)
[0028] LazyUrl_ehen(https://exhentai.org/s/cebfaec4c7/1762485-28)
[0029] LazyUrl_ehen(https://exhentai.org/s/618c5da722/1762485-29)
[0030] LazyUrl_ehen(https://exhentai.org/s/7893ae66c8/1762485-30)
[0031] LazyUrl_ehen(https://exhentai.org/s/b4d34af6d9/1762485-31)
[0032] LazyUrl_ehen(https://exhentai.org/s/f130062802/1762485-32)
[0033] LazyUrl_ehen(https://exhentai.org/s/f02d75ee0f/1762485-33)
[0034] LazyUrl_ehen(https://exhentai.org/s/b4f3886cbb/1762485-34)


[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:False, url:1762485)
Find_ehen(id:1762485, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:True, url:1762485)
Find_ehen(id:1762485, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hiyobi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn.hiyobi.me/data/json/1762485_list.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 445, in get_imgs
File "hitomi_downloader", line 445, in <listcomp>
File "extractor\hiyobi_downloader", line 40, in pop_img_hiyobi
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:False, url:1762485)
Find_ehen(id:1762485, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hiyobi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn.hiyobi.me/data/json/1762485_list.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 445, in get_imgs
File "hitomi_downloader", line 445, in <listcomp>
File "extractor\hiyobi_downloader", line 40, in pop_img_hiyobi
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:True, url:1762485)
Find_ehen(id:1762485, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hiyobi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn.hiyobi.me/data/json/1762485_list.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 445, in get_imgs
File "hitomi_downloader", line 445, in <listcomp>
File "extractor\hiyobi_downloader", line 40, in pop_img_hiyobi
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:False, url:1762485)
Find_ehen(id:1762485, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hiyobi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn.hiyobi.me/data/json/1762485_list.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 445, in get_imgs
File "hitomi_downloader", line 445, in <listcomp>
File "extractor\hiyobi_downloader", line 40, in pop_img_hiyobi
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:True, url:1762485)
Find_ehen(id:1762485, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hiyobi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn.hiyobi.me/data/json/1762485_list.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 445, in get_imgs
File "hitomi_downloader", line 445, in <listcomp>
File "extractor\hiyobi_downloader", line 40, in pop_img_hiyobi
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:False, url:1762485)
Find_ehen(id:1762485, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 161, in ehen_imgs
Exception: URL not found

get_imgs server: hiyobi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn.hiyobi.me/data/json/1762485_list.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 445, in get_imgs
File "hitomi_downloader", line 445, in <listcomp>
File "extractor\hiyobi_downloader", line 40, in pop_img_hiyobi
File "downloader", line 346, in read_html
Exception: 404

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 640, in read
Exception: no imgs

stop
Invalid: fail=False
stop
EOT: #-*- [Takatsu] Fuufunaka Chousain 3 ｜ 부부사이 조사원-3 (1762485)

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:False, url:1762485)
Find_ehen(id:1762485, ex:False)
Find in HK...
not found in HK
max_page = 26369
Brute-force search: 1
Brute-force search: 2
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 447, in get_imgs
File "extractor\ehen_downloader", line 158, in ehen_imgs
File "extractor\ehen_downloader", line 100, in find_ehen
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://e-hentai.org/?page=26&f_doujinshi=on&f_manga=on&f_artistcg=on&f_gamecg=on&f_western=on&f_non-h=on&f_imageset=on&f_cosplay=on&f_asianporn=on&f_misc=on&advsearch=1&f_srdd=2&f_sname=on&f_stags=on&f_sh=on&f_apply=Apply+Filter

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 581, in read
File "hitomi_downloader", line 438, in get_imgs
File "hitomi", line 110, in pop_img
KeyError: 'name'

get_imgs server: ehen
ehen_imgs(ex:True, url:1762485)
Find_ehen(id:1762485, ex:True)
Find in HK...
not found in HK
max_page = 38671
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4.1
Brute-force search: 5.1
Brute-force search: 6.1
Brute-force search: 7.199999999999999
Brute-force search: 8.2
Brute-force search: 9.2
Brute-force search: 10.2
Brute-force search: 11.2
Brute-force search: 12.2
#### https://exhentai.org/g/1762485/1f6f7f7360 ----> https://exhentai.org/g/1762485/1f6f7f7360
get_title_ehen: https://exhentai.org/g/1762485/1f6f7f7360
FINAL SERVER: ehen
ehen_url: https://exhentai.org/g/1762485/1f6f7f7360
imgs: 34
E-Hentai: https://exhentai.org/g/1762485/1f6f7f7360

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2655
