### ISSUE TITLE
히토미 다운이 안 됩니다

### ISSUE THREAD

**Issue by axlebox** [KurtBestor/Hitomi-Downloader#2658]
제가 컴퓨터가 32bit라서 2.7h를 쓰고 있는데요..

혹시 구버젼은 오류 해결 못 하나요?

검색해보니까 우선순위 히토미 제거하면 된다는데

그러면 한 작품 다운받는데 10분 걸리고 
그나마 다운되면 다행이지 invaild 빨간글씨 뜨면서
다운 안되는게 너무 많아서 못 쓰고 있어요..
아니면 vpn 키고 다운받는데 이게 문제일까요?
아니면 구버젼은 그냥 답이 없나요?

**Comment by korhentai** [comment]
3,1 사용자도 같아요 근데 웹으로 열면 정상적으로 뜹니다.

아마 전송속도 나 파일 동시 전송으로 밴하는건 아닌거같아요

**Comment by korhentai** [comment]
그러다면 리퍼러로 걸러내는 걸까요 ?

**Comment by korhentai** [comment]
캡챠일수도 있겠네요 페이지갯수 로딩후 멈춰있다 꺼지니까요 .

**Comment by korhentai** [comment]
Fail_404 : \\?\C:\Users\Administrator\Desktop\hitomi_downloader_GUI\hitomi_downloaded\test\0001.jpg
Traceback (most recent call last):
File "downloader", line 796, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by legnalegna** [comment]
목록에서 히토미를 제거 하신 거라면 익헨에서 다운 받게 되어 있는 걸텐데
익헨은 다운로드 할 수 있는 갯수 재한이 있는걸로 알고 있습니다

**Comment by axlebox** [comment]
![fff](https://user-images.githubusercontent.com/73521912/97392881-4579e480-1926-11eb-810d-42f567c8c4e9.png)

갯수 제한이 있는거는 아는데 이거 지금 다운로드 며칠째 시도중인데 계속 안되거든요..
이게 만약 익헨에 없는 작품이라서 다운이 안 되는거면 그러면 히토미는 다운못받나요?
히토미 서버 설정하고 하면 한 60%만 받아지고 노란색으로 마무리되서..

**Comment by korhentai** [comment]
legnalegna commented 4 hours ago

> 목록에서 히토미를 제거 하신 거라면 익헨에서 다운 받게 되어 있는 걸텐데
> 익헨은 다운로드 할 수 있는 갯수 재한이 있는걸로 알고 있습니다

서버리스트를 안만졌다면 ? 안받아지는 이유가 있을가요 0/204 이런식으로 파일리스트는 나오는데 잠시뒤 노란색으로 바뀌면서 다운이 안됩니다. 
처음 2개는 받아졌습니다.

**Comment by eva3357** [comment]
테스트버전 받으셨나요? 전 그걸로 받으니 히토미에서 잘받고 하는데요??
이슈 란 맨위에 테스트버전 받아서 해보세요

**Comment by axlebox** [comment]
> 테스트버전 받으셨나요? 전 그걸로 받으니 히토미에서 잘받고 하는데요??
> 이슈 란 맨위에 테스트버전 받아서 해보세요

컴퓨터가 32비트라 저는 2.7h버젼밖에 못 써요.
