### ISSUE TITLE
카카오페이지 다운로드가 안됩니다.. 

### ISSUE THREAD

**Issue by keroberos-s** [KurtBestor/Hitomi-Downloader#2664]
다운로드에서 0.0KB/s 에서 넘어가질 않습니다 확인 부탁드리곘습니다

[회색] 무림제일폐：월한강천록[완전판]

version: 3.1 (20-09-24 01:14:13 GMT+0)
platform: Windows-10-10.0.15063-SP0
order: 0
group: False
input: https://page.kakao.com/home?seriesId=51172035
dir: hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]
zip: 
type: kakaopage
artist: 회색
url: https://page.kakao.com/home?seriesId=51172035
valid: True
done: False
range: None
range_p: [1]
single: False
time: 1604023925.2264588 (Oct 30)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0000.jpg
[0002] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0001.jpg
[0003] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0002.jpg
[0004] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0003.jpg
[0005] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0004.jpg
[0006] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0005.jpg
[0007] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0006.jpg
[0008] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0007.jpg
[0009] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0008.jpg
[0010] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0009.jpg
[0011] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0010.jpg
[0012] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0011.jpg
[0013] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0012.jpg
[0014] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0013.jpg
[0015] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0014.jpg
[0016] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0015.jpg
[0017] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0016.jpg
[0018] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0017.jpg
[0019] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0018.jpg
[0020] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0019.jpg
[0021] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0020.jpg
[0022] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0021.jpg
[0023] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0022.jpg
[0024] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0023.jpg
[0025] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0024.jpg
[0026] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0025.jpg
[0027] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0026.jpg
[0028] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0027.jpg
[0029] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0028.jpg
[0030] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0029.jpg
[0031] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0030.jpg
[0032] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0031.jpg
[0033] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0032.jpg
[0034] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0033.jpg
[0035] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0034.jpg
[0036] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0035.jpg
[0037] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0036.jpg
[0038] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0037.jpg
[0039] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0038.jpg
[0040] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0039.jpg
[0041] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0040.jpg
[0042] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0041.jpg
[0043] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0042.jpg
[0044] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0043.jpg
[0045] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0044.jpg
[0046] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0045.jpg
[0047] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0046.jpg
[0048] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0047.jpg
[0049] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0048.jpg
[0050] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0049.jpg
[0051] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0050.jpg
[0052] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0051.jpg
[0053] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0052.jpg
[0054] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0053.jpg
[0055] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0054.jpg
[0056] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0055.jpg
[0057] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0056.jpg
[0058] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0057.jpg
[0059] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0058.jpg
[0060] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0059.jpg
[0061] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0060.jpg
[0062] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0061.jpg
[0063] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0062.jpg
[0064] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0063.jpg
[0065] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0064.jpg
[0066] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0065.jpg
[0067] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0066.jpg
[0068] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0067.jpg
[0069] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0068.jpg
[0070] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0069.jpg
[0071] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0070.jpg
[0072] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0071.jpg
[0073] hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0072.jpg

[URLs]
[0001] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=2hu0hh0F1v6OeVtlRoFt5URyEwbfbxDXyp7-MMPSIC4-V3GPJmZ2cxCx4kbfRwO3&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099503987.jpeg&gid=Gwnf45jMxhqTYooS-nt1Fg&signature=W3iugU10%2Fyi5XKjUvTzWJXMDFh4%3D
[0002] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=13Yb8kODEDaYcg8GxUpSY9XGSVjORHphDQ8FlSJuwf_QFma5GFAIXLRwP-dHLSck&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504077.jpeg&gid=MBb_nTc_UQotv0T5StALpg&signature=mwfOWz3FsaK8Hqd%2B6WLUzKCqzMg%3D
[0003] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=7X-MA0T_c7ubXNGXh67JpkfZLYzR-rKTRVdBUgjMWQC1kIvPMLWfAkRoTUadx8Rv&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504149.jpeg&gid=d_TozXlGDP6XOF8RGRdVjQ&signature=kYTO%2BWbHah44iPY81C9MVDQhAug%3D
[0004] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=FZvR08OURc5cP2iF2QreSfroD9uFyfwF3P1_klobN5oOTiT5Ki4VxCSV_IKSybWo&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504235.jpeg&gid=O93Qbnz92hOvW72Z1cKudQ&signature=NxnkCRZ9JodwSntE6RSQcOghU68%3D
[0005] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=JTuwYW3LEaxADsCYCW4Jv4PIFtleyRtjzxDBfqeEzl-mEJj7VaUxALkKIAnUq0Ef&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504375.jpeg&gid=Ac8NVmoqPfauIsbwYJcXIw&signature=x3CyLZZYpGO9SIWI0TbDlBPUbvc%3D
[0006] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=Eoco2oF0_ajo1WZKCC7mBYfGRnPqQb-Yg0475I_oVrQSbejLRGuFjKYEiuQNh8wN&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504581.jpeg&gid=lLPWOB6J0YvnNZUOp_Q8Gg&signature=RSfljMZZ%2FjQJD1ARfNZazns%2Bg6k%3D
[0007] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=-pdSGKG68RSDDv8DTPSB3A4Fm1Mrg4RoKi_venjxT6JVSVofbn1oG9brKGLChqrC&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504653.jpeg&gid=wasAJfVudonUsUG4CrzXiQ&signature=0O12%2F4KwsZANjNMsBSrc68H1OKw%3D
[0008] LazyUrl(https://page.kakao.com/viewer?productId=51173579) ---> https://page-edge.kakao.com/sdownload/resource?kid=?kid=Jro8IBhpNrFkgWJMtGWhhphfLKtJeRk5S4wWHDv3aPY5r_H0bSoA0TpQtvD4gMAz&encWid=teh2PCGt-LTpFIWifkRiYA&pid=51172035&filename=4087802_1568099504779.jpeg&gid=ogxzVHPfy3CqKOdkdeUDGw&signature=fArL%2F5WmeLIZEyaC7pS06dpIX8I%3D
[0009] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0010] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0011] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0012] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0013] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0014] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0015] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0016] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0017] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0018] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0019] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0020] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0021] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0022] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0023] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0024] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0025] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0026] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0027] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0028] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0029] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0030] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0031] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0032] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0033] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0034] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0035] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0036] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0037] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0038] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0039] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0040] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0041] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0042] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0043] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0044] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0045] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0046] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0047] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0048] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0049] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0050] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0051] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0052] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0053] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0054] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0055] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0056] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0057] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0058] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0059] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0060] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0061] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0062] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0063] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0064] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0065] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0066] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0067] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0068] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0069] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0070] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0071] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0072] LazyUrl(https://page.kakao.com/viewer?productId=51173579)
[0073] LazyUrl(https://page.kakao.com/viewer?productId=51173579)

[Messages]
월한강천록 1화 73

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0001.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0003.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0002.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0005.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0006.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0004.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0007.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0000.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0003.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0002.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0001.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0005.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0000.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0007.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0006.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0004.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0003.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0001.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0005.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0000.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0007.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0002.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0004.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

Fail : \\?\C:\Users\ㅋㄹ\Downloads\hitomi_downloader_GUI\hitomi_downloaded_kakaopage\[회색] 무림제일폐：월한강천록[완전판]\월한강천록 1화\0006.jpg
Traceback (most recent call last):
File "downloader", line 826, in download
Exception: 404

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2618

**Comment by keroberos-s** [comment]
> 참고해주세요: #2618

물론 그대로 했습니다만 안됩니다. 수동으로 확인해보았는데 주소가 바뀐거 같습니다. 
https://page-edge-jz.kakao.com/sdownload/~~ jz부분이 추가되었더군요

**Comment by keroberos-s** [comment]
> 참고해주세요: #2618

감사합니다 잘 작동합니다
