### ISSUE TITLE
nijie 니지에 니제 다운로드 기능 보완 요청

### ISSUE THREAD

**Issue by bekay201** [KurtBestor/Hitomi-Downloader#2669]
nijie 사이트에서 작가url를 입력하고 그림을 다운받는데 게시물마다 여러 페이지로로 묶여있는것을 히토미 다운로더는 오직 각 게시물의 첫번째 이미지만 다운로드하고 끝납니다.
각 게시물의 모든 페이지를 다운받을 있게 하는 것이 좋을 것 같습니다.
그리고 몇몇 작가는 작가 닉네임이 기록되지않고 '이름없는~~~' 이런 식으로 기록됩니다.

**Comment by KurtBestor** [comment]
해당 작가 링크 알려주시면 확인해볼게요.

**Comment by bekay201** [comment]
우선 첫번쨰 얘기는 특정작가가 아니라 모든 작가 동일하게 나타나는 현상입니다.
가령 '367124_p0', 'png,380506_p0.gif', '387300_p0.jpg' 이런식으로 각 게시글의 첫페이지만 다운받아져요.

두번쨰 얘기를 말씀하시는거면

https://nijie.info/members.php?id=29341

https://nijie.info/members.php?id=412305

https://nijie.info/members.php?id=728995

https://nijie.info/members.php?id=49418

일단 위 4명의 작가의 것이 원래 작가 닉넴이 존재하는데도 불구하고 名無しのチンポップ 이런식으로  폴더이름이 생성됩니다.

**Comment by bekay201** [comment]
> 해당 작가 링크 알려주시면 확인해볼게요.

우선 첫번쨰 얘기는 특정작가가 아니라 모든 작가 동일하게 나타나는 현상입니다.
가령 '367124_p0', 'png,380506_p0.gif', '387300_p0.jpg' 이런식으로 각 게시글의 첫페이지만 다운받아져요.

두번쨰 얘기를 말씀하시는거면

https://nijie.info/members.php?id=29341

https://nijie.info/members.php?id=412305

https://nijie.info/members.php?id=728995

https://nijie.info/members.php?id=49418

일단 위 4명의 작가의 것이 원래 작가 닉넴이 존재하는데도 불구하고 名無しのチンポップ 이런식으로 폴더이름이 생성됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bekay201** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Login required; Update your cookies: https://nijie.info/members.php?id=1619299

version: 3.2a (20-11-12 15:18:42 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://nijie.info/members.php?id=1619299
dir: 
zip: 
type: nijie
artist: None
url: https://nijie.info/members.php?id=1619299
valid: False
done: True
range: None
range_p: None
single: False
time: 1605195852.8891573 (Nov 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
File "utils", line 986, in start
File "extractor\nijie_downloader", line 49, in init
errors.LoginRequired

Invalid: fail=False
EOT: https://nijie.info/members.php?id=1619299


stop
Traceback (most recent call last):
File "utils", line 986, in start
File "extractor\nijie_downloader", line 49, in init
errors.LoginRequired

Invalid: fail=False
EOT: https://nijie.info/members.php?id=1619299


안되네영..ㅠ 다운로드 테스트파일과 2개의 소스코드 압축파일 받은 후 테스트 파일만 압축풀고 안에 프로그램 실행시켜서 했습니다.

**Comment by KurtBestor** [comment]
로그인 쿠키 넣고 다운로드해야해요.

**Comment by bekay201** [comment]
넵 'Get cookies.txt'라는 크롬 확장프로그램으로 'nijie.info_cookies.txt'쿠키 입력하니 다운이 되었습니다.
이전보다는 분명 개선이 되었긴한데.... 몇몇 게시글은 변함없이 첫이미지만 다운받는 현상이 보이네요.
예를 들자면 'https://nijie.info/members_illust.php?id=728995'작가의 'https://nijie.info/view.php?id=311512' 게시글은 첫이미지만 다운받아졌네요.
아쉽게도 이만 자봐야해서 내일 이어서 도움될수 있는 일은 적극적으로 참여하겠습니다.
밤중에 고생이 많습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bekay201** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

테스트 해본 결과 일단 지난번에 일부 게시글이 첫번째 이미지만 다운받던 오류는 해결된 것으로 보여집니다.
모든 파일이 정상적으로 잘 받아지지만 사족으로 2가지 오류가 있는데
여러 작가들것을 다운로드 할 때 다운로드가 안되거나, 혹은 다운받던 중에 멈춰버리는 것입니다.
침착하게 하나씩 받거나 계속 중단되는 파일을 삭제하고 다시 다운을 받으면 해결은 되었지만 혹시나 해서 로그 적습니다.

★★★★★★★★★★★★★★★★★★★★★★다운 안받아지는 것★★★★★★★★★★★★★★★★★★★★★★★★★★

Invalid: [nijie] https://nijie.info/members.php?id=172420

version: 3.2a (20-11-14 13:09:13 UTC)
platform: Windows-10-10.0.18362-SP0
order: 4
group: False
input: https://nijie.info/members.php?id=172420
dir: 
zip: 
type: nijie
artist: None
url: https://nijie.info/members.php?id=172420
valid: False
done: True
range: None
range_p: None
single: False
time: 1605371340.5693963 (Nov 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
https://nijie.info/members_illust.php?id=172420&p=1
https://nijie.info/members_illust.php?id=172420&p=2
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\nijie_downloader", line 54, in read
File "extractor\nijie_downloader", line 141, in get_imgs
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://nijie.info/members.php?id=172420 (141.31606936454773s)

https://nijie.info/members_illust.php?id=172420&p=1
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\nijie_downloader", line 54, in read
File "extractor\nijie_downloader", line 141, in get_imgs
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://nijie.info/members.php?id=172420 (8.3665132522583s)








★★★★★★★★★★★★★★★★★★★다운 받던중에 계속 중간에 멈춰지는 것★★★★★★★★★★★★★★★★★★★

4분 59초 뒤 다시 시작: https://nijie.info/members.php?id=412305

version: 3.2a (20-11-14 13:09:13 UTC)
platform: Windows-10-10.0.18362-SP0
order: 2
group: False
input: https://nijie.info/members.php?id=412305
dir: hitomi_downloaded_nijie\半額 (nijie_412305)
zip: 
type: nijie
artist: None
url: https://nijie.info/members.php?id=412305
valid: False
done: True
range: None
range_p: None
single: False
time: 1605372447.6210568 (Nov 15)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_nijie\半額 (nijie_412305)\398549_p0.png
[0002] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p0.png
[0003] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p1.png
[0004] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p2.png
[0005] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p3.png
[0006] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p4.png
[0007] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p5.png
[0008] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p6.png
[0009] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p7.png
[0010] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p8.png
[0011] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p9.png
[0012] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p10.png
[0013] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p11.png
[0014] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p12.png
[0015] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p13.png
[0016] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p14.png
[0017] hitomi_downloaded_nijie\半額 (nijie_412305)\396477_p15.png
[0018] hitomi_downloaded_nijie\半額 (nijie_412305)\392033_p0.jpg
[0019] hitomi_downloaded_nijie\半額 (nijie_412305)\388131_p0.png
[0020] hitomi_downloaded_nijie\半額 (nijie_412305)\388131_p1.png
[0021] hitomi_downloaded_nijie\半額 (nijie_412305)\388006_p0.jpg
[0022] hitomi_downloaded_nijie\半額 (nijie_412305)\385929_p0.jpg
[0023] hitomi_downloaded_nijie\半額 (nijie_412305)\380005_p0.jpg
[0024] hitomi_downloaded_nijie\半額 (nijie_412305)\376042_p0.jpg
[0025] hitomi_downloaded_nijie\半額 (nijie_412305)\373507_p0.jpg
[0026] hitomi_downloaded_nijie\半額 (nijie_412305)\373072_p0.jpg
[0027] hitomi_downloaded_nijie\半額 (nijie_412305)\373072_p1.jpg
[0028] hitomi_downloaded_nijie\半額 (nijie_412305)\367017_p0.png
[0029] hitomi_downloaded_nijie\半額 (nijie_412305)\364336_p0.png
[0030] hitomi_downloaded_nijie\半額 (nijie_412305)\363701_p0.jpg
[0031] hitomi_downloaded_nijie\半額 (nijie_412305)\363701_p1.jpg
[0032] hitomi_downloaded_nijie\半額 (nijie_412305)\363701_p2.jpg
[0033] hitomi_downloaded_nijie\半額 (nijie_412305)\359770_p0.jpg
[0034] hitomi_downloaded_nijie\半額 (nijie_412305)\359770_p1.jpg
[0035] hitomi_downloaded_nijie\半額 (nijie_412305)\359770_p2.jpg
[0036] hitomi_downloaded_nijie\半額 (nijie_412305)\359770_p3.jpg
[0037] hitomi_downloaded_nijie\半額 (nijie_412305)\359770_p4.jpg
[0038] hitomi_downloaded_nijie\半額 (nijie_412305)\356437_p0.jpg
[0039] hitomi_downloaded_nijie\半額 (nijie_412305)\356437_p1.jpg
[0040] hitomi_downloaded_nijie\半額 (nijie_412305)\356437_p2.jpg
[0041] hitomi_downloaded_nijie\半額 (nijie_412305)\356437_p3.jpg
[0042] hitomi_downloaded_nijie\半額 (nijie_412305)
[0043] hitomi_downloaded_nijie\半額 (nijie_412305)\352889_p0.jpg
[0044] hitomi_downloaded_nijie\半額 (nijie_412305)\351847_p0.jpg
[0045] hitomi_downloaded_nijie\半額 (nijie_412305)\349494_p0.jpg
[0046] hitomi_downloaded_nijie\半額 (nijie_412305)\349494_p1.jpg
[0047] hitomi_downloaded_nijie\半額 (nijie_412305)\349494_p2.jpg
[0048] hitomi_downloaded_nijie\半額 (nijie_412305)\349494_p3.jpg
[0049] hitomi_downloaded_nijie\半額 (nijie_412305)\349494_p4.jpg
[0050] hitomi_downloaded_nijie\半額 (nijie_412305)\343489_p0.jpg
[0051] hitomi_downloaded_nijie\半額 (nijie_412305)\343489_p1.jpg
[0052] hitomi_downloaded_nijie\半額 (nijie_412305)\343489_p2.jpg
[0053] hitomi_downloaded_nijie\半額 (nijie_412305)\342113_p0.jpg
[0054] hitomi_downloaded_nijie\半額 (nijie_412305)\338738_p0.jpg
[0055] hitomi_downloaded_nijie\半額 (nijie_412305)\338738_p1.jpg
[0056] hitomi_downloaded_nijie\半額 (nijie_412305)\338345_p0.jpg
[0057] hitomi_downloaded_nijie\半額 (nijie_412305)\336416_p0.png
[0058] hitomi_downloaded_nijie\半額 (nijie_412305)\331853_p0.png
[0059] hitomi_downloaded_nijie\半額 (nijie_412305)\331570_p0.png
[0060] hitomi_downloaded_nijie\半額 (nijie_412305)\331570_p1.png
[0061] hitomi_downloaded_nijie\半額 (nijie_412305)\331570_p2.png
[0062] hitomi_downloaded_nijie\半額 (nijie_412305)\330906_p0.png
[0063] hitomi_downloaded_nijie\半額 (nijie_412305)\329220_p0.jpg
[0064] hitomi_downloaded_nijie\半額 (nijie_412305)\329220_p1.jpg
[0065] hitomi_downloaded_nijie\半額 (nijie_412305)\324695_p0.jpg
[0066] hitomi_downloaded_nijie\半額 (nijie_412305)\324542_p0.jpg
[0067] hitomi_downloaded_nijie\半額 (nijie_412305)
[0068] hitomi_downloaded_nijie\半額 (nijie_412305)\316115_p0.jpg
[0069] hitomi_downloaded_nijie\半額 (nijie_412305)\312529_p0.jpg
[0070] hitomi_downloaded_nijie\半額 (nijie_412305)\304975_p0.jpg
[0071] hitomi_downloaded_nijie\半額 (nijie_412305)\302439_p0.jpg
[0072] hitomi_downloaded_nijie\半額 (nijie_412305)\302439_p1.jpg
[0073] hitomi_downloaded_nijie\半額 (nijie_412305)\302439_p2.jpg
[0074] hitomi_downloaded_nijie\半額 (nijie_412305)\300596_p0.jpg
[0075] hitomi_downloaded_nijie\半額 (nijie_412305)\299982_p0.jpg
[0076] hitomi_downloaded_nijie\半額 (nijie_412305)\299982_p1.jpg
[0077] hitomi_downloaded_nijie\半額 (nijie_412305)\291980_p0.jpg


[URLs]
[0001] LazyUrl(https://nijie.info/view.php?id=398549) ---> 【local_lazy】 398549_p0.png
[0002] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p0.png
[0003] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p1.png
[0004] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p2.png
[0005] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p3.png
[0006] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p4.png
[0007] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p5.png
[0008] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p6.png
[0009] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p7.png
[0010] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p8.png
[0011] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p9.png
[0012] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p10.png
[0013] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p11.png
[0014] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p12.png
[0015] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p13.png
[0016] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p14.png
[0017] LazyUrl(https://nijie.info/view.php?id=396477) ---> 【local_lazy】 396477_p15.png
[0018] LazyUrl(https://nijie.info/view.php?id=392033) ---> 【local_lazy】 392033_p0.jpg
[0019] LazyUrl(https://nijie.info/view.php?id=388131) ---> 【local_lazy】 388131_p0.png
[0020] LazyUrl(https://nijie.info/view.php?id=388131) ---> 【local_lazy】 388131_p1.png
[0021] LazyUrl(https://nijie.info/view.php?id=388006) ---> 【local_lazy】 388006_p0.jpg
[0022] LazyUrl(https://nijie.info/view.php?id=385929) ---> 【local_lazy】 385929_p0.jpg
[0023] LazyUrl(https://nijie.info/view.php?id=380005) ---> 【local_lazy】 380005_p0.jpg
[0024] LazyUrl(https://nijie.info/view.php?id=376042) ---> 【local_lazy】 376042_p0.jpg
[0025] LazyUrl(https://nijie.info/view.php?id=373507) ---> 【local_lazy】 373507_p0.jpg
[0026] LazyUrl(https://nijie.info/view.php?id=373072) ---> 【local_lazy】 373072_p0.jpg
[0027] LazyUrl(https://nijie.info/view.php?id=373072) ---> 【local_lazy】 373072_p1.jpg
[0028] LazyUrl(https://nijie.info/view.php?id=367017) ---> 【local_lazy】 367017_p0.png
[0029] LazyUrl(https://nijie.info/view.php?id=364336) ---> 【local_lazy】 364336_p0.png
[0030] LazyUrl(https://nijie.info/view.php?id=363701) ---> 【local_lazy】 363701_p0.jpg
[0031] LazyUrl(https://nijie.info/view.php?id=363701) ---> 【local_lazy】 363701_p1.jpg
[0032] LazyUrl(https://nijie.info/view.php?id=363701) ---> 【local_lazy】 363701_p2.jpg
[0033] LazyUrl(https://nijie.info/view.php?id=359770) ---> 【local_lazy】 359770_p0.jpg
[0034] LazyUrl(https://nijie.info/view.php?id=359770) ---> 【local_lazy】 359770_p1.jpg
[0035] LazyUrl(https://nijie.info/view.php?id=359770) ---> 【local_lazy】 359770_p2.jpg
[0036] LazyUrl(https://nijie.info/view.php?id=359770) ---> 【local_lazy】 359770_p3.jpg
[0037] LazyUrl(https://nijie.info/view.php?id=359770) ---> 【local_lazy】 359770_p4.jpg
[0038] LazyUrl(https://nijie.info/view.php?id=356437) ---> 【local_lazy】 356437_p0.jpg
[0039] LazyUrl(https://nijie.info/view.php?id=356437) ---> 【local_lazy】 356437_p1.jpg
[0040] LazyUrl(https://nijie.info/view.php?id=356437) ---> 【local_lazy】 356437_p2.jpg
[0041] LazyUrl(https://nijie.info/view.php?id=356437) ---> 【local_lazy】 356437_p3.jpg
[0042] LazyUrl(https://nijie.info/view.php?id=353891)
[0043] LazyUrl(https://nijie.info/view.php?id=352889) ---> 【local_lazy】 352889_p0.jpg
[0044] LazyUrl(https://nijie.info/view.php?id=351847) ---> 【local_lazy】 351847_p0.jpg
[0045] LazyUrl(https://nijie.info/view.php?id=349494) ---> 【local_lazy】 349494_p0.jpg
[0046] LazyUrl(https://nijie.info/view.php?id=349494) ---> 【local_lazy】 349494_p1.jpg
[0047] LazyUrl(https://nijie.info/view.php?id=349494) ---> 【local_lazy】 349494_p2.jpg
[0048] LazyUrl(https://nijie.info/view.php?id=349494) ---> 【local_lazy】 349494_p3.jpg
[0049] LazyUrl(https://nijie.info/view.php?id=349494) ---> 【local_lazy】 349494_p4.jpg
[0050] LazyUrl(https://nijie.info/view.php?id=343489) ---> 【local_lazy】 343489_p0.jpg
[0051] LazyUrl(https://nijie.info/view.php?id=343489) ---> 【local_lazy】 343489_p1.jpg
[0052] LazyUrl(https://nijie.info/view.php?id=343489) ---> 【local_lazy】 343489_p2.jpg
[0053] LazyUrl(https://nijie.info/view.php?id=342113) ---> 【local_lazy】 342113_p0.jpg
[0054] LazyUrl(https://nijie.info/view.php?id=338738) ---> 【local_lazy】 338738_p0.jpg
[0055] LazyUrl(https://nijie.info/view.php?id=338738) ---> 【local_lazy】 338738_p1.jpg
[0056] LazyUrl(https://nijie.info/view.php?id=338345) ---> 【local_lazy】 338345_p0.jpg
[0057] LazyUrl(https://nijie.info/view.php?id=336416) ---> 【local_lazy】 336416_p0.png
[0058] LazyUrl(https://nijie.info/view.php?id=331853) ---> 【local_lazy】 331853_p0.png
[0059] LazyUrl(https://nijie.info/view.php?id=331570) ---> 【local_lazy】 331570_p0.png
[0060] LazyUrl(https://nijie.info/view.php?id=331570) ---> 【local_lazy】 331570_p1.png
[0061] LazyUrl(https://nijie.info/view.php?id=331570) ---> 【local_lazy】 331570_p2.png
[0062] LazyUrl(https://nijie.info/view.php?id=330906) ---> 【local_lazy】 330906_p0.png
[0063] LazyUrl(https://nijie.info/view.php?id=329220) ---> 【local_lazy】 329220_p0.jpg
[0064] LazyUrl(https://nijie.info/view.php?id=329220) ---> 【local_lazy】 329220_p1.jpg
[0065] LazyUrl(https://nijie.info/view.php?id=324695) ---> 【local_lazy】 324695_p0.jpg
[0066] LazyUrl(https://nijie.info/view.php?id=324542) ---> 【local_lazy】 324542_p0.jpg
[0067] LazyUrl(https://nijie.info/view.php?id=322069)
[0068] LazyUrl(https://nijie.info/view.php?id=316115) ---> 【local_lazy】 316115_p0.jpg
[0069] LazyUrl(https://nijie.info/view.php?id=312529) ---> 【local_lazy】 312529_p0.jpg
[0070] LazyUrl(https://nijie.info/view.php?id=304975) ---> 【local_lazy】 304975_p0.jpg
[0071] LazyUrl(https://nijie.info/view.php?id=302439) ---> 【local_lazy】 302439_p0.jpg
[0072] LazyUrl(https://nijie.info/view.php?id=302439) ---> 【local_lazy】 302439_p1.jpg
[0073] LazyUrl(https://nijie.info/view.php?id=302439) ---> 【local_lazy】 302439_p2.jpg
[0074] LazyUrl(https://nijie.info/view.php?id=300596) ---> 【local_lazy】 300596_p0.jpg
[0075] LazyUrl(https://nijie.info/view.php?id=299982) ---> 【local_lazy】 299982_p0.jpg
[0076] LazyUrl(https://nijie.info/view.php?id=299982) ---> 【local_lazy】 299982_p1.jpg
[0077] LazyUrl(https://nijie.info/view.php?id=291980) ---> 【local_lazy】 291980_p0.jpg


[Messages]
https://nijie.info/members_illust.php?id=412305&p=1
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\nijie_downloader", line 54, in read
File "extractor\nijie_downloader", line 141, in get_imgs
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://nijie.info/members.php?id=412305 (25.06846785545349s)

https://nijie.info/members_illust.php?id=412305&p=1
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1000, in start
File "utils", line 1047, in start_
File "extractor\nijie_downloader", line 54, in read
File "extractor\nijie_downloader", line 141, in get_imgs
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://nijie.info/members.php?id=412305 (5.986972808837891s)

https://nijie.info/members_illust.php?id=412305&p=1
https://nijie.info/members_illust.php?id=412305&p=2

LazyUrl error (https://nijie.info/view.php?id=392033):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=388006):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=380005):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=376042):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
valid=False 1
EOT: https://nijie.info/members.php?id=412305 (102.08104395866394s)

https://nijie.info/members_illust.php?id=412305&p=1
https://nijie.info/members_illust.php?id=412305&p=2

LazyUrl error (https://nijie.info/view.php?id=392033):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=331853):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=316115):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
valid=False 1
EOT: https://nijie.info/members.php?id=412305 (24.41931700706482s)

https://nijie.info/members_illust.php?id=412305&p=1
https://nijie.info/members_illust.php?id=412305&p=2

LazyUrl error (https://nijie.info/view.php?id=324695):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
valid=False 1
EOT: https://nijie.info/members.php?id=412305 (17.603031396865845s)

https://nijie.info/members_illust.php?id=412305&p=1
https://nijie.info/members_illust.php?id=412305&p=2

LazyUrl error (https://nijie.info/view.php?id=352889):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=338345):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


LazyUrl error (https://nijie.info/view.php?id=331853):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
valid=False 1
EOT: https://nijie.info/members.php?id=412305 (17.397581338882446s)

https://nijie.info/members_illust.php?id=412305&p=1
https://nijie.info/members_illust.php?id=412305&p=2

LazyUrl error (https://nijie.info/view.php?id=353891):
Traceback (most recent call last):
File "hitomi_downloader", line 234, in run
File "utils", line 661, in __call__
File "extractor\nijie_downloader", line 75, in get_single
File "<decorator-gen-59>", line 2, in get_imgs_post
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\nijie_downloader", line 88, in get_imgs_post
AttributeError: 'NoneType' object has no attribute 'findAll'


감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bekay201** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

여러개 동시에 다운로드 해도 전부 작동이 잘 됩니다! 감사합니다!
