### ISSUE TITLE
3.2에서 마나토끼가 갑자기 안되네요

### ISSUE THREAD

**Issue by als0001** [KurtBestor/Hitomi-Downloader#2670]
수정판에선 잘 되던게 업데이트 이후 안됩니다.

Invalid: [manatoki] https://manatoki83.net/comic/5961687

version: 3.2 (20-10-30 17:02:16 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://manatoki83.net/comic/5961687
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki83.net/comic/5961687
valid: False
done: True
range: None
range_p: None
single: True
time: 1604097103.055627 (Oct 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "<decorator-gen-77>", line 2, in init
File "constants", line 849, in wrapper
File "constants", line 820, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 38, in solve
AttributeError: 'NoneType' object has no attribute 'lock'

Invalid: fail=True
EOT: https://manatoki83.net/comic/5961687

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나온 내용 보여주세요
