### ISSUE TITLE
업데이트후 유튜브 다운로드가 않됩니다.

### ISSUE THREAD

**Issue by qkskfka** [KurtBestor/Hitomi-Downloader#2671]
Invalid: [youtube] https://www.youtube.com/watch?v=1Dn9VzwAPO0

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=1Dn9VzwAPO0
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=1Dn9VzwAPO0
valid: False
done: True
range: None
range_p: None
single: True
time: 1604123868.7505229 (Oct 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 2103, in _real_extract
File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

No videos
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=1Dn9VzwAPO0

쿠키로 불러오기를 했는데도 소용이 없네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by qkskfka** [comment]
다운신호는 가는데 600메가 바이트 이상 받아져서 파일이 깨지네요 쿠키 불러오기도 했는데요

MMD - Kirisame Marisa // 🎃Happy Halloween🎃 [4KUHD]

version: 3.2a (20-11-01 07:31:58 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=1Dn9VzwAPO0
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: PanzerMMD
url: https://www.youtube.com/watch?v=1Dn9VzwAPO0
valid: True
done: True
range: None
range_p: None
single: True
time: 1604231640.7308075 (Nov 1)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\MMD - Kirisame Marisa ／／ 🎃Happy Halloween🎃 [4KUHD] (1Dn9VzwAPO0).mp4


[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=1Dn9VzwAPO0) ---> https://r7---sn-3u-bh2s7.googlevideo.com/videoplayback?expire=1604253240&ei=2KGeX7aqBt3jqAG_o5nYAw&ip=121.160.88.30&id=o-AIvLwMABV3tEtNwkZhrn9gyeiJOnvzYAYUesv3hZmO_q&itag=315&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315&source=youtube&requiressl=yes&mh=kn&mm=31%2C26&mn=sn-3u-bh2s7%2Csn-npoe7nl6&ms=au%2Conr&mv=m&mvi=7&pl=17&initcwndbps=1195000&vprv=1&mime=video%2Fwebm&gir=yes&clen=691103396&dur=243.382&lmt=1604111844997919&mt=1604231551&fvip=2&keepalive=yes&c=WEB&txp=6216222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgO1BbBWtVjeq1rnA5g9G_Ko_5WqaBAT-L_PzhuxI5JIACIQC196xveliNX_8-gpJy6QJQ73PMf-oAzjhmZDRC3umLxg%3D%3D&sig=AOq0QJ8wRQIhAPlwP5lIw-t9P-TeYkI8Xhgdh-j8grdw-XiUIa9ZaT4vAiB4iMPKvg-KTTNZYpv3T837lM7OLd_KNqK86Qmnb2IgHg==&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (tiny)
[144p][30fps][None] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (144p)
[144p][30fps][None] webm [vp9 / None] ─ 278 - 256x144 (144p)
[240p][30fps][None] mp4 [avc1.4d4015 / None] ─ 133 - 426x240 (240p)
[240p][30fps][None] webm [vp9 / None] ─ 242 - 426x240 (240p)
[360p][30fps][None] webm [vp9 / None] ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[480p][30fps][None] webm [vp9 / None] ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 [avc1.4d401f / None] ─ 135 - 854x480 (480p)
[720p][30fps][None] webm [vp9 / None] ─ 247 - 1280x720 (720p)
[720p][30fps][None] mp4 [avc1.64001f / None] ─ 136 - 1280x720 (720p)
[720p][60fps][None] webm [vp9 / None] ─ 302 - 1280x720 (720p60)
[720p][60fps][None] mp4 [avc1.640020 / None] ─ 298 - 1280x720 (720p60)
[1080p][60fps][None] webm [vp9 / None] ─ 303 - 1920x1080 (1080p60)
[1080p][60fps][None] mp4 [avc1.64002a / None] ─ 299 - 1920x1080 (1080p60)
[1440p][60fps][None] webm [vp9 / None] ─ 308 - 2560x1440 (1440p60)
[2160p][60fps][None] webm [vp9 / None] ─ 315 - 3840x2160 (2160p60)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)


# stream_final <youtube_dl_test.Video object at 0x0000019D01367AC8> 315 - 3840x2160 (2160p60) 2160p webm None 60fps
[None][0fps][50kbps] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (tiny)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)

Resolution: None
Codec: None / mp4a.40.2
Abr: 128kbps
Subtype: m4a
FPS: 0

Download audio: https://r7---sn-3u-bh2s7.googlevideo.com/videoplayback?expire=1604253240&ei=2KGeX7aqBt3jqAG_o5nYAw&ip=121.160.88.30&id=o-AIvLwMABV3tEtNwkZhrn9gyeiJOnvzYAYUesv3hZmO_q&itag=140&source=youtube&requiressl=yes&mh=kn&mm=31%2C26&mn=sn-3u-bh2s7%2Csn-npoe7nl6&ms=au%2Conr&mv=m&mvi=7&pl=17&initcwndbps=1195000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3940811&dur=243.437&lmt=1604111774375545&mt=1604231551&fvip=2&keepalive=yes&c=WEB&txp=6211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgRwB0CP6hjYbj0JoepBbugNN85UyW579gQR3Jq7k8CxQCIEcSoPaj6HBvFIY354BPyF7kg0oXgc1W10FCfQOIkpIA&sig=AOq0QJ8wRQIgNXvzBCo19_pUXPgE_7p-AOaCOZqb2_K5Pf9NFMbdFrUCIQCZKNvdEv5UMP1t60L0TlPBJ5ZGSnhxO3xfhw_qI4yf-A==&ratebypass=yes
Convert: C:\Users\abc\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\MMD - Kirisame Marisa ／／ 🎃Happy Halloween🎃 [4KUHD] (1Dn9VzwAPO0).webm
rename (1): hitomi_downloaded_youtube\8980b4a303e0485d9a05235b9bcb0282_a.tmp -> C:\Users\abc\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\tmp5d37391ffd9a4499ae2b92e379d3867d_a.weba
rename (1): C:\Users\abc\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\MMD - Kirisame Marisa ／／ 🎃Happy Halloween🎃 [4KUHD] (1Dn9VzwAPO0).webm -> C:\Users\abc\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\tmp5d37391ffd9a4499ae2b92e379d3867d_v.webm
-i tmp5d37391ffd9a4499ae2b92e379d3867d_v.webm -i tmp5d37391ffd9a4499ae2b92e379d3867d_a.weba -c:v copy -c:a copy -strict experimental -preset ultrafast tmp5d37391ffd9a4499ae2b92e379d3867d_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, matroska,webm, from 'tmp5d37391ffd9a4499ae2b92e379d3867d_v.webm': 
Metadata: 
encoder : google/video-file 
Duration: 00:04:03.38, start: 0.000000, bitrate: 22716 kb/s 
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default) 
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp5d37391ffd9a4499ae2b92e379d3867d_a.weba': 
Metadata: 
major_brand : dash 
minor_version : 0 
compatible_brands: iso6mp41 
creation_time : 2020-10-31T02:34:24.000000Z 
Duration: 00:04:03.44, start: 0.000000, bitrate: 129 kb/s 
Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 5 kb/s (default) 
Metadata: 
creation_time : 2020-10-31T02:34:24.000000Z 
handler_name : ISO Media file produced by Google Inc. 
Output #0, mp4, to 'tmp5d37391ffd9a4499ae2b92e379d3867d_o.mp4': 
Metadata: 
encoder : Lavf58.20.100 
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 16k tbn, 1k tbc (default) 
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 5 kb/s (default) 
Metadata: 
creation_time : 2020-10-31T02:34:24.000000Z 
handler_name : ISO Media file produced by Google Inc. 
Stream mapping: 
Stream #0:0 -> #0:0 (copy) 
Stream #1:0 -> #0:1 (copy) 
Press [q] to stop, [?] for help 
frame=10779 fps=0.0 q=-1.0 size= 509184kB time=00:02:59.63 bitrate=23220.9kbits/s speed= 358x frame=14603 fps=0.0 q=-1.0 Lsize= 678950kB time=00:04:03.41 bitrate=22849.7kbits/s speed= 365x 
video:674792kB audio:3804kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.052181% 

Convert success: True
rename (1): C:\Users\abc\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\tmp5d37391ffd9a4499ae2b92e379d3867d_o.mp4 -> C:\Users\abc\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\MMD - Kirisame Marisa ／／ 🎃Happy Halloween🎃 [4KUHD] (1Dn9VzwAPO0).webm
rename ext .webm --> .mp4
stop
EOT: https://www.youtube.com/watch?v=1Dn9VzwAPO0
