### ISSUE TITLE
픽시브 코믹이 다운이 안됩니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#2672]
항상 감사히 잘 사용하고 있습니다
바쁘신거 같은데 자꾸 문의드려서 죄송합니다
픽시브코믹이 업데이트전에도 안되던데 업데이트후에도 계속 안되네요
정보 올립니다 잘 부탁드립니다

Invalid: [pixiv_comic] https://comic.pixiv.net/works/6957

version: 3.2 (20-10-30 17:02:16 UTC)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://comic.pixiv.net/works/6957
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/6957
valid: False
done: True
range: None
range_p: None
single: False
time: 1604130229.7651734 (Oct 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\pixiv_comic_downloader", line 73, in read
File "extractor\pixiv_comic_downloader", line 59, in name
File "extractor\pixiv_comic_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6957

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2645
