### ISSUE TITLE
jmana is not download ;;;  please help

### ISSUE THREAD

**Issue by puzdragon** [KurtBestor/Hitomi-Downloader#2679]
Invalid: [jmana] https://jmana.net/book?bookname=%EC%A7%80%EA%B3%A0%EC%BF%A0%EB%9D%BC%EC%BF%A0

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://jmana.net/book?bookname=%EC%A7%80%EA%B3%A0%EC%BF%A0%EB%9D%BC%EC%BF%A0
dir: 
zip: 
type: jmana
artist: None
url: https://jmana.net/book?bookname=%EC%A7%80%EA%B3%A0%EC%BF%A0%EB%9D%BC%EC%BF%A0
valid: False
done: True
range: None
range_p: None
single: True
time: 1604302920.6006324 (Nov 2)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "extractor\jmana_downloader", line 84, in init
File "extractor\jmana_downloader", line 22, in fix_url
File "clf2", line 38, in solve
AttributeError: 'NoneType' object has no attribute 'lock'

Invalid: fail=True
EOT: https://jmana.net/book?bookname=%EC%A7%80%EA%B3%A0%EC%BF%A0%EB%9D%BC%EC%BF%A0

다운이 안되요 ㅠㅠ

**Comment by UmojanProtectorate** [comment]
일반 회원입니다.
최신버전만 문제발생하고있으면 구버전은 정상적으로 작동합니다
문제 수정될때까지 당분간 이전 버전 사용하시기 바랍니다.
참고 기존 파일 삭제후 구버전 사용하시면 됩니다.
https://github.com/KurtBestor/Hitomi-Downloader/releases/download/v3.1/hitomi_downloader_GUI.zip

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2678#issuecomment-725968836
