### ISSUE TITLE
404 Client Error - Twitter 

### ISSUE THREAD

**Issue by wankio** [KurtBestor/Hitomi-Downloader#2691]
It stopped at : Apr 11, 2019 - https://twitter.com/Hentaitore/status/1116041907501764610?s=20
 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 454, in get_imgs_legacy
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://twitter.com/i/search/timeline?f=tweets&vertical=default&q=from%3AHentaitore%20max_id%3A1116041907501764609%20exclude%3Aretweets%20filter%3Amedia%20-filter%3Aperiscope&src=typd&include_available_features=1&include_entities=1&reset_error_state=false

retry... (15) https://twitter.com/i/search/timeline?f=tweets&vertical=default&q=from%3AHentaitore%20max_id%3A1116041907501764609%20exclude%3Aretweets%20filter%3Amedia%20-filter%3Aperiscope&src=typd&include_available_features=1&include_entities=1&reset_error_state=false
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 454, in get_imgs_legacy
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://twitter.com/i/search/timeline?f=tweets&vertical=default&q=from%3AHentaitore%20max_id%3A1116041907501764609%20exclude%3Aretweets%20filter%3Amedia%20-filter%3Aperiscope&src=typd&include_available_features=1&include_entities=1&reset_error_state=false
 
```

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/2534

**Comment by wankio** [comment]
oh ok, ty, forgot technical version
