### ISSUE TITLE
마나토끼 만화가 다운이 안됨니다

### ISSUE THREAD

**Issue by coolblueman** [KurtBestor/Hitomi-Downloader#2701]
Invalid: [manatoki] https://manatoki84.net/comic/110851

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://manatoki84.net/comic/110851
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki84.net/comic/110851
valid: False
done: True
range: None
range_p: None
single: True
time: 1604710489.7266524 (Nov 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

 
웹툰이나 유투브는 되는데 제이만화,마나토끼는 안되네요

[Messages]
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "<decorator-gen-77>", line 2, in init
File "constants", line 849, in wrapper
File "constants", line 820, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 38, in solve
AttributeError: 'NoneType' object has no attribute 'lock'

Invalid: fail=True
EOT: https://manatoki84.net/comic/110851

**Comment by coolblueman** [comment]
지금 4일째 계속 알아보는데 제이마나, 마나토끼만 다운이 안 됩니다.
유튜브 영상이나 웹툰은 잘되는데 만화만 안됩니다.
제발 도와주십시오. ㅠㅠ 메모장 열어서 수정하고 주소 바꿔 받지만 도 저의 안됩니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2678#issuecomment-725968836
