### ISSUE TITLE
마나토끼 다운이 안됩니다

### ISSUE THREAD

**Issue by kggj2010** [KurtBestor/Hitomi-Downloader#2712]
Browser required: https://manatoki84.net/comic/277920

version: 3.2a (20-11-08 16:04:19 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://manatoki84.net/comic/277920
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki84.net/comic/277920
valid: False
done: True
range: None
range_p: None
single: False
time: 1604893589.7988515 (Nov 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1001, in start
File "<decorator-gen-78>", line 2, in init
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 33, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://manatoki84.net/comic/277920

stop
Traceback (most recent call last):
File "utils", line 1001, in start
File "<decorator-gen-78>", line 2, in init
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 33, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://manatoki84.net/comic/277920

전에는 잘됐는데 이번에 받으려고 들어가니 안되네요
뭘 어떻게해야 하는지 알 수 있나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2678#issuecomment-725968836
