### ISSUE TITLE
제이마나의 만화가 안보여요

### ISSUE THREAD

**Issue by mac22222** [KurtBestor/Hitomi-Downloader#2714]
https://jmana04.aboutdron.net/book?bookname=%EC%A6%90%EA%B2%81%EA%B2%8C+%EB%86%80%EC%95%84%EB%B3%B4%EC%84%B8%28%EC%95%84%EC%86%8C%EB%B9%84%EC%95%84%EC%86%8C%EB%B0%94%EC%84%B8%29
인데 browser required 이 떳어요.

정보를 보니까
===================================================================================
Browser required: https://jmana04.aboutdron.net/book?bookname=%EC%A6%90%EA%B2%81%EA%B2%8C+%EB%86%80%EC%95%84%EB%B3%B4%EC%84%B8%28%EC%95%84%EC%86%8C%EB%B9%84%EC%95%84%EC%86%8C%EB%B0%94%EC%84%B8%29

version: 3.2a (20-11-08 16:04:19 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://jmana04.aboutdron.net/book?bookname=%EC%A6%90%EA%B2%81%EA%B2%8C+%EB%86%80%EC%95%84%EB%B3%B4%EC%84%B8%28%EC%95%84%EC%86%8C%EB%B9%84%EC%95%84%EC%86%8C%EB%B0%94%EC%84%B8%29
dir: 
zip: 
type: jmana
artist: None
url: https://jmana04.aboutdron.net/book?bookname=%EC%A6%90%EA%B2%81%EA%B2%8C+%EB%86%80%EC%95%84%EB%B3%B4%EC%84%B8%28%EC%95%84%EC%86%8C%EB%B9%84%EC%95%84%EC%86%8C%EB%B0%94%EC%84%B8%29
valid: False
done: True
range: None
range_p: None
single: False
time: 1604920541.6132555 (Nov 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1001, in start
File "extractor\jmana_downloader", line 85, in init
File "extractor\jmana_downloader", line 22, in fix_url
File "clf2", line 33, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://jmana04.aboutdron.net/book?bookname=%EC%A6%90%EA%B2%81%EA%B2%8C+%EB%86%80%EC%95%84%EB%B3%B4%EC%84%B8%28%EC%95%84%EC%86%8C%EB%B9%84%EC%95%84%EC%86%8C%EB%B0%94%EC%84%B8%29

===================================================================================

감사합니다.

**Comment by puzdragon** [comment]
다운로드 되나요? 저는 아예 다운로드도 안되던데 ㅠㅠ invalid만 떠요

**Comment by mac22222** [comment]
> 다운로드 되나요? 저는 아예 다운로드도 안되던데 ㅠㅠ invalid만 떠요

저두요 ㅠㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2678#issuecomment-725968836
