### ISSUE TITLE
유튜브 재생목록이 다운로드 되지 않습니다

### ISSUE THREAD

**Issue by choi9090177** [KurtBestor/Hitomi-Downloader#2716]
안녕하세요, 언제나 잘 사용하고 있습니다. 

유튜브 재생목록이 다운로드 되지 않아서 문의 드립니다.

해당 작업정보는 아래와 같습니다

Invalid: [youtube] https://www.youtube.com/playlist?list=PLmrVWPFHf_oEYRWao_jaU58rIea5HwlK-

version: 3.2a (20-11-01 07:31:58 UTC)
platform: Windows-10-10.0.19041-SP0
order: 2
group: False
input: https://www.youtube.com/playlist?list=PLmrVWPFHf_oEYRWao_jaU58rIea5HwlK-
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/playlist?list=PLmrVWPFHf_oEYRWao_jaU58rIea5HwlK-
valid: False
done: True
range: None
range_p: None
single: True
time: 1604966790.604722 (Nov 10)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'title'
stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "utils", line 1071, in start_
File "extractor\youtube_downloader", line 364, in read
File "<decorator-gen-23>", line 2, in get_videos
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\youtube_downloader", line 427, in get_videos
KeyError: 'title'

Invalid: fail=True
EOT: https://www.youtube.com/playlist?list=PLmrVWPFHf_oEYRWao_jaU58rIea5HwlK-

'title'
stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "utils", line 1071, in start_
File "extractor\youtube_downloader", line 364, in read
File "<decorator-gen-23>", line 2, in get_videos
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\youtube_downloader", line 427, in get_videos
KeyError: 'title'

Invalid: fail=True
EOT: https://www.youtube.com/playlist?list=PLmrVWPFHf_oEYRWao_jaU58rIea5HwlK-

**Comment by KurtBestor** [comment]
다음과 비슷한 경우인 것 같은데 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2699

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by choi9090177** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by choi9090177** [comment]
감사합니다! 잘 수정 되어 다운이 되네요!
