### ISSUE TITLE
마나토끼 다운문제

### ISSUE THREAD

**Issue by rkdgkswprkf** [KurtBestor/Hitomi-Downloader#2725]
Browser required; Use --safemode: https://manatoki85.net/comic/1020505

version: 3.2a (20-11-12 10:22:58 UTC)
platform: Windows-10-10.0.19041-SP0
order: 2
group: False
input: https://manatoki85.net/comic/1020505
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki85.net/comic/1020505
valid: False
done: True
range: None
range_p: None
single: False
time: 1605181974.538467 (Nov 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 986, in start
File "<decorator-gen-78>", line 2, in init
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 33, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://manatoki85.net/comic/1020505

이러면서 다운이 안됩니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2678#issuecomment-725968836
