### ISSUE TITLE
인스타그램 다운이 안되는것 같습니다

### ISSUE THREAD

**Issue by zayu2u** [KurtBestor/Hitomi-Downloader#2744]
Invalid: [insta] https://www.instagram.com/yg_ent_official

version: 3.2a (20-11-17 07:50:36 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.instagram.com/yg_ent_official
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/yg_ent_official
valid: False
done: True
range: None
range_p: None
single: False
time: 1605678116.391747 (Nov 18)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'ProfilePage'
stop
Traceback (most recent call last):
File "utils", line 986, in start
File "extractor\insta_downloader", line 36, in init
File "utils", line 468, in __get__
File "extractor\insta_downloader", line 42, in username
File "extractor\insta_downloader", line 148, in get_username
KeyError: 'ProfilePage'

Invalid: fail=True
EOT: https://www.instagram.com/yg_ent_official (1.6s)

'ProfilePage'
stop
Traceback (most recent call last):
File "utils", line 986, in start
File "extractor\insta_downloader", line 36, in init
File "utils", line 468, in __get__
File "extractor\insta_downloader", line 42, in username
File "extractor\insta_downloader", line 148, in get_username
KeyError: 'ProfilePage'

Invalid: fail=True
EOT: https://www.instagram.com/yg_ent_official (1.0s)

쿠키 초기화도 해봤는데 안되네요
도와주세요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2708#issuecomment-729487120

**Comment by zayu2u** [comment]
쿠키 불러오기로 인스타그램 쿠키 넣어서 해결했습니다. 감사합니다.
