### ISSUE TITLE
유튜브 일부 영상이 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by tkqhxkwn** [KurtBestor/Hitomi-Downloader#2765]
유튜브 일부 영상이 다운로드가 안 됩니다. 대부분 영상은 다운이 잘 됩니다만 안 되는 것은 거의 1달 가량 안 되고 있는데요.

물론 주기적으로 최신 테크니컬 프리뷰 버전을 받고 있습니다만 지금도 여전히 안 되는 건 안 됩니다. 11월 21일자 버전에서도 안 되네요.

작업 정보에서 표시되는 메시지는 다음과 같습니다.

 
 
  
 
 
3분 54초 뒤 다시 시작: https://www.youtube.com/watch?v=ZdxTAMk_LVQ

version: 3.2a (20-11-21 20:11:42 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=ZdxTAMk_LVQ
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: 레전드히어로 삼국전
url: https://www.youtube.com/watch?v=ZdxTAMk_LVQ
valid: False
done: True
range: None
range_p: None
single: True
time: 1606205664.5516737 (Nov 24)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=ZdxTAMk_LVQ) ---> https://r1---sn-3u-bh2z.googlevideo.com/videoplayback?expire=1606227267&ei=48C8X47xJouMlQTozLZ4&ip=211.225.115.135&id=o-AItwKjApOemLFIkgWSPnjshXvR47WKneeSEsPfCOWLzs&itag=22&source=youtube&requiressl=yes&mh=03&mm=31%2C26&mn=sn-3u-bh2z%2Csn-i3belne6&ms=au%2Conr&mv=m&mvi=1&pl=21&initcwndbps=1192500&vprv=1&mime=video%2Fmp4&ns=vVNJKyqFkDjKsozlgUIL_AcF&ratebypass=yes&dur=1454.544&lmt=1542136433101305&mt=1606205317&fvip=1&beids=9466586&c=WEB&txp=5531432&n=RXmzmlAGhrevdfj&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgAdTBOzmfungXjqgF-pzgZbXYlByDxt5B2UkmAYc5-QcCIBN3aqPZoVSOh_cTaaKp80AYEUjdVuuLchBCCJNJZvIT&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgCak-GK18gNVFUCUcyfLjdM8QN5jm5xQbb7EvZjRtrzMCIARniLM2WlaNgNTZHj4Xj5oLhG4sH864cD74pVdyoi1P

[Messages]
[None][0fps][50kbps] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (tiny)
[144p][24fps][None] webm [vp9 / None] ─ 278 - 256x144 (144p)
[144p][24fps][None] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (144p)
[240p][24fps][None] webm [vp9 / None] ─ 242 - 426x240 (240p)
[240p][24fps][None] mp4 [avc1.4d4015 / None] ─ 133 - 426x240 (240p)
[360p][24fps][None] webm [vp9 / None] ─ 243 - 640x360 (360p)
[360p][24fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[480p][24fps][None] webm [vp9 / None] ─ 244 - 854x480 (480p)
[480p][24fps][None] mp4 [avc1.4d401e / None] ─ 135 - 854x480 (480p)
[720p][24fps][None] webm [vp9 / None] ─ 247 - 1280x720 (720p)
[720p][24fps][None] mp4 [avc1.4d401f / None] ─ 136 - 1280x720 (720p)
[1080p][24fps][None] webm [vp9 / None] ─ 248 - 1920x1080 (1080p)
[1080p][24fps][None] mp4 [avc1.640028 / None] ─ 137 - 1920x1080 (1080p)
[360p][24fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][24fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x0000015814F15C88> 247 - 1280x720 (720p) 720p webm None 24fps
# stream_final <youtube_dl_test.Video object at 0x0000015814F15608> 136 - 1280x720 (720p) 720p mp4 None 24fps
# stream_final <youtube_dl_test.Video object at 0x0000015814F15188> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 24fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4
FPS: 24

downloader_v3 fail... p[1 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[2 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 207]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 715641 / 1048576

downloader_v3 fail... p[2 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[1 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 207]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 715641 / 1048576

### reset size ###
downloader_v3 fail... p[1 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[2 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 207]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 715641 / 1048576

downloader_v3 fail... p[2 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[3 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[1 / 207]
Traceback (most recent call last):
File "downloader_v3", line 70, in run
Exception: Not partial content: 404

downloader_v3 fail... p[0 / 207]
Traceback (most recent call last):
File "downloader_v3", line 73, in run
Exception: size mismatch: 785977 / 1048576

### reset size ###
use just download

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 715641 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

Fail : \\?\G:\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\레전드히어로 삼국전 - 21화 - 레인보우 이벤트 [ENG CC].mp4
Traceback (most recent call last):
File "downloader", line 946, in download
Exception: Size mismatch: 785977 / 216321204

stop
valid=False 1
EOT: https://www.youtube.com/watch?v=ZdxTAMk_LVQ (63.8s)

**Comment by tkqhxkwn** [comment]
최신 버전에서 해결됨을 확인
