### ISSUE TITLE
인스타 다운이안되요

### ISSUE THREAD

**Issue by Mimikkyu-778** [KurtBestor/Hitomi-Downloader#2773]
인스타 주소 넣으면 빨간색으로 표시되면서 다운이 안됨니다.

크롬에서 쿠키 지우고 인스타 로그인도 다시해봐도 똑같습니다.

========================================================
Invalid: [insta] https://www.instagram.com/turtles_vv

version: 3.2a (20-11-21 20:11:42 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.instagram.com/turtles_vv
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/turtles_vv
valid: False
done: True
range: None
range_p: None
single: False
time: 1606402155.7584627 (Nov 26)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'ProfilePage'
stop
Traceback (most recent call last):
File "utils", line 990, in start
File "extractor\insta_downloader", line 36, in init
File "utils", line 468, in __get__
File "extractor\insta_downloader", line 42, in username
File "extractor\insta_downloader", line 148, in get_username
KeyError: 'ProfilePage'

Invalid: fail=True
EOT: https://www.instagram.com/turtles_vv (1.0s)
========================================================

**Comment by s25jin** [comment]
인스타가 로그인 안하면 자료 볼수 없게 바뀌지 않았나요? 
4kstogram 추천해요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2708#issuecomment-740344824
