### ISSUE TITLE
트위터 몇몇 계정들에서 작동하지 않습니다.

### ISSUE THREAD

**Issue by is1225** [KurtBestor/Hitomi-Downloader#2789]
트위터 다운로드 쪽을 주로 사용 중인데 대부분의 경우에는 잘 되었으나 특정 계정에서 작동이 되지 않습니다.

따로 정지를 당하거나 삭제된 계정은 아니라 제 환경 문제인지 다운로더 문제인지 모르겠네요

Invalid: [twitter] https://twitter.com/k_mantae

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.17134-SP0
order: 0
group: False
input: https://twitter.com/k_mantae
dir: 
zip: 
type: twitter
artist: 만태
url: https://twitter.com/k_mantae
valid: False
done: True
range: None
range_p: None
single: False
time: 1606725152.372101 (Nov 30)
tags: []
goodbyedpi: True
lock: True
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
multiple tweets
cursor: None
retry... _pagination (1)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (2)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (3)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (4)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (5)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (6)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (7)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (8)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (9)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (10)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (11)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (12)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (13)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (14)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (15)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (16)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (17)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (18)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

retry... _pagination (19)
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\twitter_downloader", line 137, in read
File "extractor\twitter_downloader", line 358, in get_imgs
File "extractor\twitter_downloader", line 262, in _pagination
File "extractor\twitter_downloader", line 252, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 215, in _call
File "downloader", line 226, in read_json
File "downloader", line 336, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/785111616555659264.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true

Invalid: fail=True
EOT: https://twitter.com/k_mantae

-----

Invalid: [twitter] https://twitter.com/monaka6300

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.17134-SP0
order: 1
group: False
input: https://twitter.com/monaka6300
dir: 
zip: 
type: twitter
artist: もなか
url: https://twitter.com/monaka6300
valid: False
done: True
range: None
range_p: None
single: False
time: 1606725039.5077705 (Nov 30)
tags: []
goodbyedpi: True
lock: True
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
multiple tweets
cursor: None
enough
no imgs
stop
Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\twitter_downloader", line 137, in read
File "extractor\twitter_downloader", line 378, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/monaka6300

**Comment by fade-out-0770** [comment]
https://twitter.com/k_mantae 이사람은 계정이 비공개구요.
https://twitter.com/monaka6300 이사람은 잘되는데 다시 받아보시죠. (참고로 리트윗으로 가져온건 원래 다운 안되요.)

**Comment by is1225** [comment]
ㅇㅎ 팔로우상태라 비공개인지 몰랐네요...
