### ISSUE TITLE
유튜브와 폰허브 동영상이 다운이 안되요 

### ISSUE THREAD

**Issue by DHDH664** [KurtBestor/Hitomi-Downloader#2801]
폰허브랑 유튜브 동영상이 다운이 안되요.. 특정 파일이 안되는게 아니라 전부다 안되네요
혹시해서 이것저것 수십개 테스트 햇는데 다 빨갛게 나오고 다운이 안되네요..
왜 그럴까요..?

Invalid: [youtube] https://www.youtube.com/watch?v=eoIgcfl8JcI

version: 3.2a (20-11-09 12:36:50 UTC)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://www.youtube.com/watch?v=eoIgcfl8JcI
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=eoIgcfl8JcI
valid: False
done: True
range: None
range_p: None
single: True
time: 1607162326.8896484 (Dec 5)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

No videos
stop
Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=eoIgcfl8JcI

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

No videos
stop
Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=eoIgcfl8JcI

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_dl\YoutubeDL", line 797, in extract_info
File "youtube_dl\extractor\common", line 532, in extract
File "youtube_dl\extractor\youtube", line 1910, in _real_extract
youtube_dl.utils.ExtractorError: eoIgcfl8JcI: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 67, in get
File "youtube_dl_test", line 99, in __init__
File "youtube_dl_test", line 37, in extract_info
File "youtube_dl\YoutubeDL", line 820, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: eoIgcfl8JcI: YouTube said: Unable to extract video data

No videos
stop
Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=eoIgcfl8JcI

유튜브 파일 다운 안되는거 정보.

Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302

version: 3.2a (20-11-09 12:36:50 UTC)
platform: Windows-7-6.1.7601-SP1
order: 1
group: False
input: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302
valid: False
done: True
range: None
range_p: None
single: True
time: 1607162326.8896484 (Dec 5)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\pornhub_downloader", line 189, in read
File "<decorator-gen-26>", line 2, in get_video
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\pornhub_downloader", line 246, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302

('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\pornhub_downloader", line 189, in read
File "<decorator-gen-26>", line 2, in get_video
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\pornhub_downloader", line 246, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302

('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\pornhub_downloader", line 189, in read
File "<decorator-gen-26>", line 2, in get_video
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\pornhub_downloader", line 246, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302

('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\pornhub_downloader", line 189, in read
File "<decorator-gen-26>", line 2, in get_video
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\pornhub_downloader", line 246, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302

('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1015, in start
File "utils", line 1062, in start_
File "extractor\pornhub_downloader", line 189, in read
File "<decorator-gen-26>", line 2, in get_video
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\pornhub_downloader", line 246, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다', None, 10053, None))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e415263e8302

폰허브 파일 다운 안되는거 정보 입니다 

왜 안될까요..

**Comment by DBdeepsleeper** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
베타로 해보세요.
실행 파일 기존 거에 덮어쓰기도 하면 작업목록 등도 다 유지되네요.
