### ISSUE TITLE
폰허브 다운로드가 안 되네요

### ISSUE THREAD

**Issue by rogeuel523** [KurtBestor/Hitomi-Downloader#2802]
다른 부분은 다 잘 작동하는데 폰허브에서만 유난히 안 되네요.

--------------------------------------------------------------------------------------------------
Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph5f525dba4f154

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.pornhub.com/view_video.php?viewkey=ph5f525dba4f154
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5f525dba4f154
valid: False
done: True
range: None
range_p: None
single: True
time: 1607255848.122002 (Dec 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', OSError(0, 'Error'))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1028, in start
File "utils", line 1079, in start_
File "extractor\pornhub_downloader", line 189, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 849, in wrapper
File "constants", line 820, in wrapper
File "extractor\pornhub_downloader", line 246, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 105, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5f525dba4f154
--------------------------------------------------------------------------------------------------

위와 같은 에러로 시작하자마자 바로 중단되어버리네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2327
