### ISSUE TITLE
유튜브 관련해서 질문드립니다

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader#2806]
우선 다운로더 테스트 버전입니다 가장 최근꺼입니다
예전에 채널을 긁어서 다운하면 그 채널 영상 전부를 다운했었는데 이젠 30개 제한 걸려있는거 같네요
그리고 몇몇 영상이 안되서 정보 긁어서 올립니다

**Comment by rlacks1237** [comment]
Invalid: [youtube] https://www.youtube.com/watch?v=OJKU6_XjEMc

version: 3.2a (20-12-07 08:17:12 UTC)
platform: Windows-10-10.0.19041-SP0
order: 2
group: False
input: https://www.youtube.com/watch?v=OJKU6_XjEMc
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=OJKU6_XjEMc
valid: False
done: True
range: ~200000
range_p: None
single: True
time: 1607340905.1171875 (Dec 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
ytdl: 2020.12.07


[Gallery]
None


[File Names]



[URLs]



[Messages]
[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (DASH audio)
[144p][25fps][None] webm [vp9 / None] ─ 278 - 256x144 (DASH video)
[144p][25fps][None] mp4 [avc1.4d400b / None] ─ 160 - 256x144 (DASH video)
[240p][25fps][None] webm [vp9 / None] ─ 242 - 426x240 (DASH video)
[240p][25fps][None] mp4 [avc1.4d400c / None] ─ 133 - 426x240 (DASH video)
[360p][25fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (DASH video)
[360p][25fps][None] webm [vp9 / None] ─ 243 - 640x360 (DASH video)
[480p][25fps][None] webm [vp9 / None] ─ 244 - 854x480 (DASH video)
[480p][25fps][None] mp4 [avc1.4d4014 / None] ─ 135 - 854x480 (DASH video)
[720p][25fps][None] webm [vp9 / None] ─ 247 - 1280x720 (DASH video)
[720p][25fps][None] mp4 [avc1.4d400c / None] ─ 136 - 1280x720 (DASH video)
[1080p][25fps][None] mp4 [avc1.640028 / None] ─ 137 - 1920x1080 (DASH video)
[1080p][25fps][None] webm [vp9 / None] ─ 248 - 1920x1080 (DASH video)
[360p][25fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][25fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)


# stream_final <ytdl.Video object at 0x000001F94BEC1088> 137 - 1920x1080 (DASH video) 1080p mp4 None 25fps
[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (DASH audio)
[360p][25fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][25fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[360p][25fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][25fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)

No videos
stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "utils", line 1061, in start_
File "extractor\youtube_downloader", line 380, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=OJKU6_XjEMc (17.6s)

**Comment by rlacks1237** [comment]
Invalid: [youtube] https://www.youtube.com/watch?v=9GcCfgj8Kvk

version: 3.2a (20-12-07 08:17:12 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://www.youtube.com/watch?v=9GcCfgj8Kvk
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=9GcCfgj8Kvk
valid: False
done: True
range: ~200000
range_p: None
single: True
time: 1607340898.5418694 (Dec 7)
tags: ['red']
goodbyedpi: True
lock: True
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
ytdl: 2020.12.07


[Gallery]
None


[File Names]



[URLs]



[Messages]
[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (DASH audio)
[144p][30fps][None] webm [vp9 / None] ─ 278 - 256x144 (DASH video)
[144p][30fps][None] mp4 [avc1.4d400b / None] ─ 160 - 256x144 (DASH video)
[240p][30fps][None] webm [vp9 / None] ─ 242 - 426x240 (DASH video)
[240p][30fps][None] mp4 [avc1.4d400c / None] ─ 133 - 426x240 (DASH video)
[360p][30fps][None] webm [vp9 / None] ─ 243 - 640x360 (DASH video)
[360p][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (DASH video)
[480p][30fps][None] webm [vp9 / None] ─ 244 - 854x480 (DASH video)
[480p][30fps][None] mp4 [avc1.4d4014 / None] ─ 135 - 854x480 (DASH video)
[720p][30fps][None] webm [vp9 / None] ─ 247 - 1280x720 (DASH video)
[720p][30fps][None] mp4 [avc1.4d400c / None] ─ 136 - 1280x720 (DASH video)
[1080p][30fps][None] webm [vp9 / None] ─ 248 - 1920x1080 (DASH video)
[1080p][30fps][None] mp4 [avc1.640028 / None] ─ 137 - 1920x1080 (DASH video)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)


# stream_final <ytdl.Video object at 0x000001F9579C1F48> 248 - 1920x1080 (DASH video) 1080p webm None 30fps
# stream_final <ytdl.Video object at 0x000001F9579422C8> 137 - 1920x1080 (DASH video) 1080p mp4 None 30fps
[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm [None / opus] ─ 251 - audio only (DASH audio)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[360p][30fps][96kbps] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

[None][0fps][48kbps] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)

No videos
stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "utils", line 1061, in start_
File "extractor\youtube_downloader", line 380, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=9GcCfgj8Kvk (14.8s)

**Comment by KurtBestor** [comment]
최신 버전에서 해결됐을거예요.

**Comment by rlacks1237** [comment]
> 최신 버전에서 해결됐을거예요.

다운로드 문제는 해결됬습니다 감사합니다
그런데 혹시 예전엔 유튜브 동영상란을 복사하면 전부 다운했었는데 지금은 30개만 다운되네요 혹시 해결 방법이 있을까요?

**Comment by KurtBestor** [comment]
해당 주소 알려주세요

**Comment by rlacks1237** [comment]
> 해당 주소 알려주세요

https://www.youtube.com/c/Dazbeeee/videos
https://www.youtube.com/c/MrMoMMusic/videos
등 다른 채널도 동일합니다

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/101979555-5053c300-3ca1-11eb-82c0-f21625ca684f.png)

재현할 수가 없네요

**Comment by rlacks1237** [comment]
> ![image](https://user-images.githubusercontent.com/14768120/101979555-5053c300-3ca1-11eb-82c0-f21625ca684f.png)
> 
> 재현할 수가 없네요
음... 전 어떻게 해도 30이 최대네요 혹시모르니 싺 밀고 다시해보겠습니다

**Comment by rlacks1237** [comment]
오 설정파일을 다른곳에 넣고 다시 하니 됬습니다
신경써주셔서 감사합니다
설정은 바뀐게 없는데 왜 안된건지 모르겠네요 ㅋㅋ
