### ISSUE TITLE
기본데이터 다운로드에 실패합니다

### ISSUE THREAD

**Issue by bar1235** [KurtBestor/Hitomi-Downloader#2818]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2597, in dataDownload
  File "hitomi_searcher", line 340, in download_json
  File "tags", line 67, in finish
PermissionError: [Errno 13] Permission denied: 'F:\\hitomi_downloader_GUI\\hitomi_data\\tags.txt'

3.2b 버전에서 문제가 발생했습니다

**Comment by KurtBestor** [comment]
관리자 권한으로 실행해도 안 되나요?

**Comment by bar1235** [comment]
방금 관리자 권한으로 실행해 보았으나 똑같은 오류가 나왓습니다

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by bar1235** [comment]
방금 아바스트 종료하고 다시 해보니 해결 되었습니다
문의에 답변해주셔서 진심으로 감사합니다 
좋은 하루 되세요
