### ISSUE TITLE
Twitter: imported cookies break downloading

### ISSUE THREAD

**Issue by nisehime** [KurtBestor/Hitomi-Downloader#2820]
Reading... 桃タイ (@momotaaai) - 269
version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-8.1-6.3.9600-SP0
order: 0
group: False
input: https://twitter.com/momotaaai
dir:
zip:
type: twitter
artist: 桃タイ
url: https://twitter.com/momotaaai
valid: True
done: False
range: None
range_p: None
single: False
time: 1607639137.805875 (Dec 11)
tags: []
goodbyedpi: None
lock: False
color: reading
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
multiple tweets
cursor: HBaCwKqRuZfW/yEAAA==
cursor: HBaEwKPFr7O05x4AAA==
retry... _pagination (1)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/23386063.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%2ChighlightedLabel%2CcameraMoment&include_quote_count=true&cursor=HBaEwKPFr7O05x4AAA==

**Comment by nisehime** [comment]
At first I thought the error occurred because my session was outdated so I closed the issue, but after importing new cookies, I still get this. Look at the OP for example.

**Comment by nisehime** [comment]
Nvm, I missed others rereported it already.
