### ISSUE TITLE
3.2b 버전 마나토끼 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by xenohoya** [KurtBestor/Hitomi-Downloader#2821]
![1](https://user-images.githubusercontent.com/46372033/101838731-7f284700-3b84-11eb-8e97-8785ba27556f.jpg)

Browser required; Use --safemode: https://manatoki89.net/comic/6238931

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki89.net/comic/6238931
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki89.net/comic/6238931
valid: False
done: True
range: None
range_p: None
single: False
time: 1607639756.4149687 (Dec 11)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "<decorator-gen-84>", line 2, in init
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 34, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://manatoki89.net/comic/6238931 (10.0s)

3.2A 버전부터 지속적으로 안되던 마나토끼 3.2b에서도 다운로드가 되지 않습니다.

![2](https://user-images.githubusercontent.com/46372033/101838787-949d7100-3b84-11eb-9488-bc41cddc2593.jpg)

따로 챙겨놓고 있는 3.1 버전은 다운로드 됩니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2678#issuecomment-725968836
