### ISSUE TITLE
트위터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by kdh5480** [KurtBestor/Hitomi-Downloader#2828]
지운 부분은 일러스터 주소랑 닉네임 정도입니다.
정확하게 나타나는 오류코드가 뭔지 몰라서 일단 그대로 들고왔습니다.

이거랑 나머지 하나는 원격 호스트에서 접속을 끊었다. 같은게 뜨던데 연관이 있을지..

Invalid: [twitter]

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: 
dir: 
zip: 
type: twitter
artist: 
url: 
valid: False
done: True
range: None
range_p: None
single: False
time: 1607693678.4733276 (Dec 11)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
multiple tweets
cursor: HBaAgKfZscS7qyQAAA==
retry... _pagination (1)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (2)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (3)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (4)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (5)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (6)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (7)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (8)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (9)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (10)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (11)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (12)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (13)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (14)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (15)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (16)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (17)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (18)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (19)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

retry... _pagination (20)
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D
stop
Traceback (most recent call last):
File "downloader", line 288, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\twitter_downloader", line 107, in read
File "extractor\twitter_downloader", line 344, in get_imgs
File "extractor\twitter_downloader", line 243, in _pagination
File "extractor\twitter_downloader", line 233, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 185, in _call
File "downloader", line 228, in read_json
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/2/timeline/media/777557708467687424.json?tweet_mode=extended&include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=100&ext=mediaStats%252ChighlightedLabel%252CcameraMoment&include_quote_count=true&cursor=HBaAgKfZscS7qyQAAA%3D%3D

Invalid: fail=True
EOT: https://twitter.com/wnmpna_ (618.1s)

**Comment by momokoro1** [comment]
작동합니다 선생님

**Comment by memer606060** [comment]
선생님 정말 감사합니다 저도 다운로드가 전혀 되지 않는 빨간색 에러가 한 달쯤 전부터 계속 있었는데 
이건 작동합니다 정말 감사합니다 올해 마무리 잘하시길 바라며 좋은 일이 있으시길 바랍니다 건강하세요
