### ISSUE TITLE
트위터 다운로드가 안됩니다

### ISSUE THREAD

**Issue by sundorball** [KurtBestor/Hitomi-Downloader#2837]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2828#issuecomment-743702389
 글보고 참고하여 다운 받아서 해봤습니다만 다운로드가 안됩니다 ㅠ 혹시나 백신때문인가 싶어 끄고 해도 안되더라구요...
Invalid: [twitter] https://twitter.com/nahonanaho

version: 3.2b (20-12-12 04:36:48 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://twitter.com/nahonanaho
dir: 
zip: 
type: twitter
artist: None
url: https://twitter.com/nahonanaho
valid: False
done: True
range: None
range_p: None
single: False
time: 1607766051.5609565 (Dec 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.12

[Gallery]
None

[File Names]

[URLs]

[Messages]
'data'
stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "extractor\twitter_downloader", line 72, in init
File "<decorator-gen-23>", line 2, in get_artist_username
File "constants", line 864, in wrapper
File "constants", line 835, in wrapper
File "extractor\twitter_downloader", line 628, in get_artist_username
File "extractor\twitter_downloader", line 211, in user_by_screen_name
KeyError: 'data'

Invalid: fail=True
EOT: https://twitter.com/nahonanaho (18.0s)

**Comment by sundorball** [comment]
쿠키 초기화 하니 잘됩니다
