### ISSUE TITLE
인스타 다운로드 문의드립니다.

### ISSUE THREAD

**Issue by HukoOo** [KurtBestor/Hitomi-Downloader#2849]
언제나 프로그램 업데이트 감사드립니다.

이번 인스타 계정 차단방지 버전 업뎃 이후로 인스타 다운로드를 하면 아래의 오류들이 발생하고 다운이 되지않습니다.

[Messages]
no media.. retry... (1) Traceback (most recent call last):
File "extractor\insta_downloader", line 326, in get_imgs
File "<decorator-gen-14>", line 2, in get_query
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\insta_downloader", line 266, in get_query
File "requests\cookies", line 328, in __getitem__
File "requests\cookies", line 394, in _find_no_duplicates
requests.cookies.CookieConflictError: There are multiple cookies with name, 'csrftoken'

쿠키 문제인것같아 초기화하고 다시 쿠키불러오기해서 받아봐도 같은 에러들이 발생합니다.

한번 확인 부탁드리겠습니다.

감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by HukoOo** [comment]
동작 확인했습니다. 감사합니다!

**Comment by helpmepls08** [comment]
전에 사용하는거 삭제 하고 설치 해야하나요?
