### ISSUE TITLE
마이리딩망가 작동이 안됩니다.

### ISSUE THREAD

**Issue by Heremon** [KurtBestor/Hitomi-Downloader#2851]
Invalid: [mrm] https://

version: 3.2b (20-12-14 08:36:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://
dir: 
zip: 
type: mrm
artist: None
url: https://
valid: False
done: True
range: None
range_p: None
single: False
time: 1607997993.3720856 (Dec 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.14

[Gallery]
None

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://
stop
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1025, in start
File "extractor\mrm_downloader", line 46, in init
File "<decorator-gen-44>", line 2, in get_session
File "constants", line 865, in wrapper
File "constants", line 836, in wrapper
File "extractor\mrm_downloader", line 196, in get_session
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://

Invalid: fail=True
EOT: https:// (1.3s)

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by fpvmflzk** [comment]
> 지금도 안 되나요?

저도 안되네요 최신 파일로 깔았는데도 안됩니다

**Comment by KurtBestor** [comment]
안 되는 링크 하나 주시면 테스트 해볼게요

**Comment by fpvmflzk** [comment]
> 안 되는 링크 하나 주시면 테스트 해볼게요

https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes/ 

대충 하나 골라왔습니다 다른걸로도 테스트 해본 결과 이 링크뿐만 아니라 마리망의 모든 링크가 안되는것 같네요

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/102225005-06314280-3f2a-11eb-8c74-c4983c5cb763.png)

재현할 수가 없네요.

`옵션` - `설정` - `고급 설정` - `내장 웹브라우저` - `보기` 눌러서 주소창에 해당 링크 입력하고 <kbd>Enter</kbd> 눌러보세요. 어떻게 뜨나요?

**Comment by ditmdhaos** [comment]
> `옵션` - `설정` - `고급 설정` - `내장 웹브라우저` - `보기` 눌러서 주소창에 해당 링크 입력하고 Enter 눌러보세요. 어떻게 뜨나요?

![fas](https://user-images.githubusercontent.com/76063970/102249953-47cfe680-3f46-11eb-920b-c395ae9fb7c2.jpg)
![fas_00001](https://user-images.githubusercontent.com/76063970/102250101-7948b200-3f46-11eb-91cb-59224fbc9d59.jpg)


이런창이 뜹니다만 저 문항을 클릭해서 넘겨도 다운로드가 안됩니다

**Comment by KurtBestor** [comment]
캡챠 풀면 내장 웹브라우저에서 어떻게 보이나요?

**Comment by Heremon** [comment]
저는 내장 웹브라우저 키면 빈화면밖에 안뜨네요 ...

**Comment by fpvmflzk** [comment]
> 캡챠 풀면 내장 웹브라우저에서 어떻게 보이나요?

저도 허몬 님처럼 캡챠 뜨지도 않고 빈 화면만 나옵니다

**Comment by KurtBestor** [comment]
작업 목록에서 <kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나온 내용 보여주세요.

**Comment by fpvmflzk** [comment]
> 작업 목록에서 Ctrl + L 눌러서 나온 내용 보여주세요.

Checking for updates... HitomiDownloader2

NG8PHmKxOTkrQw=uxNdqFRZZykptldp2yWfaXuPP24IYdyAfsxTdGHv=TbFyh78oyt=g2AY+vXtZiNt48+y6o6=0lFz2QgJYKoS7Qse74TeztX334QILAPETdWi4T2GpnBIPeZCNsc1rkIRNJZkASUpu6Drj0NDS5Q2R4EnrIqH0DHWp0B6r+ebRN7VaiGSc91Cpq7YCawxCp3Vi37j6sg41769R2pz5cdP9SPs11qQ0pEcVJLBNM0R6JgIwj4f=0txFkPrcT=CwBH8NjLjYye1lFwEaTeCi5+UFMp68a70

PrefixPath: C:/Users/master/AppData/Local/Temp/_MEI20442/PyQt5/Qt
LibraryExecutablesPath: C:/Users/master/AppData/Local/Temp/_MEI20442/PyQt5/Qt/bin
BinariesPath: C:/Users/master/AppData/Local/Temp/_MEI20442/PyQt5/Qt/bin

Qt 5.14.1 / PyQt 5.14.1 / SIP 5.4.0 / youtube-dl None
{'debug': False, 'disable-gpu': True, 'no-browser': False, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': False, 'experimental': False}

C:\Users\master\AppData\Local\Temp
C:\Users\master\Downloads\downloader_GUI
[strip path] %TEMP%

winId: 2883878
handle: <PyQt.QtGui.QWindow object at 0x000001299031A678>
Font: Gulim -> 맑은 고딕
Supported Image Formats: [b'bmp', b'pbm', b'pgm', b'png', b'ppm', b'xbm', b'xpm']
v3.2b (latest: v3.2b)
Encodings: ['cp949', 'utf-8', 'ascii', 'utf-8', 'utf-8']
download youtube-dl
youtube_dl-2020.12.14.tar.gz#sha256=eaa859f15b6897bec21474b7787dc958118c8088e1f24d4ef1d58eab13188958
[append_datas] size: 0, elapsed time: 0.0015697000000010064
GoodbyeDPI activated

Styles:
    windowsvista
    Windows
    Fusion

start GoodbyeDPI
import youtube-dl
youtube-dl version: 2020.12.14

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 창 띄우고 다음 내용 입력하고 <kbd>Enter</kbd> 눌러서 나온 내용 보여주세요:
```
print(mybrowser._started);mybrowser.startup();print(mybrowser._started)
```

**Comment by Heremon** [comment]
![image](https://user-images.githubusercontent.com/59201541/102347410-b8791080-3fe3-11eb-808e-4a14a168ea1f.png)

**Comment by fpvmflzk** [comment]
> Ctrl + Alt + C 눌러서 콘솔 창 띄우고 다음 내용 입력하고 Enter 눌러서 나온 내용 보여주세요:
> 
> ```
> print(mybrowser._started);mybrowser.startup();print(mybrowser._started)
> ```

![캡처](https://user-images.githubusercontent.com/73017003/102347511-d777a280-3fe3-11eb-845b-9ff3d78f1186.JPG)

**Comment by KurtBestor** [comment]
내장 웹브라우저 켠 상태에서 다운로드 시도하면 어떻게 뜨나요?

**Comment by fpvmflzk** [comment]
> 내장 웹브라우저 켠 상태에서 다운로드 시도하면 어떻게 뜨나요?

링크 붙여넣고 엔터치고 계속 기다려도 빈화면 밖에 안뜹니다 다운로드 자체를 시도할수가 없어요...

**Comment by KurtBestor** [comment]
내장 웹브라우저에선 아무것도 안 뜨나요?

**Comment by fpvmflzk** [comment]
> 내장 웹브라우저에선 아무것도 안 뜨나요?

네, 빈화면만 뜹니다.

**Comment by KurtBestor** [comment]
> Ctrl + Alt + C 눌러서 콘솔 창 띄우고 다음 내용 입력하고 Enter 눌러서 나온 내용 보여주세요:
> 
> ```
> print(mybrowser._started);mybrowser.startup();print(mybrowser._started)
> ```

이렇게 해도 내장 웹브라우저에서 아무것도 안 뜨나요?

**Comment by fpvmflzk** [comment]
> > Ctrl + Alt + C 눌러서 콘솔 창 띄우고 다음 내용 입력하고 Enter 눌러서 나온 내용 보여주세요:
> > ```
> > print(mybrowser._started);mybrowser.startup();print(mybrowser._started)
> > ```
> 
> 이렇게 해도 내장 웹브라우저에서 아무것도 안 뜨나요?
![20201222_224338](https://user-images.githubusercontent.com/73017003/102894983-443ce200-44a7-11eb-9afa-8b482a39fd61.jpg)
 
마찬가지입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fpvmflzk** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

최신버전인데도 여전히 다운이 안되네요...

Invalid: [mrm] https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes
dir: 
zip: 
type: mrm
artist: None
url: https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes
valid: False
done: True
range: None
range_p: None
single: False
time: 1609068040.0644135 (Dec 27)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.26


[Gallery]
None


[File Names]



[URLs]



[Messages]
403 Client Error: Forbidden for url: https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes
stop
Traceback (most recent call last):
File "downloader", line 309, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1051, in start
File "extractor\mrm_downloader", line 43, in init
File "<decorator-gen-45>", line 2, in get_session
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\mrm_downloader", line 197, in get_session
File "downloader", line 342, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes

Invalid: fail=True
EOT: https://myreadingmanga.info/0vv0b-oscar-x-akira-helios-rising-heroes (0.8s)

**Comment by KurtBestor** [comment]
내장 브라우저에서 해당 주소 입력해서 페이지 로딩한 다음 캡챠를 풀지 않은 상태로 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 열고 다음 내용 입력한 다음 <kbd>Enter</kbd> 눌러서 나온 내용 보여주세요:
```
def f(mb):
    with open('test.txt', 'wb') as f:
        f.write(mb.read_html().encode('utf8'))
    os.startfile('test.txt')
threading.Thread(target=f, args=(mybrowser,), daemon=True).start()
```

**Comment by fpvmflzk** [comment]
> 내장 브라우저에서 해당 주소 입력해서 페이지 로딩한 다음 캡챠를 풀지 않은 상태로 Ctrl + Alt + C 눌러서 콘솔 열고 다음 내용 입력한 다음 Enter 눌러서 나온 내용 보여주세요:
> 
> ```
> def f(mb):
>     with open('test.txt', 'wb') as f:
>         f.write(mb.read_html().encode('utf8'))
>     os.startfile('test.txt')
> threading.Thread(target=f, args=(mybrowser,), daemon=True).start()
> ```

<!DOCTYPE html><html class="no-js" lang="en-US"><head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass">
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection">

<style type="text/css">body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



<script type="text/javascript">
  //<![CDATA[
  (function(){
    window._cf_chl_opt={
      cvId: "1",
      cType: "interactive",
      cNounce: "62421",
      cRay: "6086eab5debce9ec",
      cHash: "92b9495be9a9338",
      cFPWv: "g",
      cRq: {
        ru: "aHR0cHM6Ly9teXJlYWRpbmdtYW5nYS5pbmZvLzB2djBiLW9zY2FyLXgtYWtpcmEtaGVsaW9zLXJpc2luZy1oZXJvZXM=",
        ra: "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzg2LjAuNDI0MC4xMTEgU2FmYXJpLzUzNy4zNiBFZGcvODYuMC42MjIuNTY=",
        rm: "R0VU",
        d: "lZrHKtjO3KbWkgY/i9LF5+DhRtMUcKkvg2sKTHk1DkozC4DzPj2Nc18EfVs5/fC2hxxhujlCCss+UNJfikp7TemcRDgHznzl79zRNl46twmIZ/q7JClLJ29WgWKv7bdDfnBivUZDBn7v+fp9Ep9RtAJU8NnD92bwnGXpdVZ/HA5D5w/Em//FKWOqk2ZbEwjRORYpCYJ87F9rPoj3+Q6QZ3jWjjc2irtcWHCJonWmN5VuDRbufw3aKlPvWQYfrCkKZVYjgeunjq89oCuombRt562rDhSGKAE89jtr200DwlXqu01t6v96A9V59e3SrLBmMGCgIcFS/XTinyxpPLcWibjfTBqzFoL/ivW5uyAo6n+EiA8IrL7qsilvW/caj7L/+Rn4HGG+ctG2B/oVNpcnvgFQn6a0lYcALwzBLznJmCdOXwaGXBSRj/s8j/3ym3fibkixmMDEY4Cu0UbNFS7klJHu07oRQgjMniUuFoewMx03y/jq3DmbpPQ4zDQ2wZxJ34b2sF1obFliDFPFxZ1MVRuawN7HvTcfdQ1p7WnTvOXZdhr8hilS5PYsHAybYhqTYkzpf2el3YehBHkf41OlgajPWc4F04UusjvTch3TRQDfPAEtPv238V7Mb7LkUMeG1+qiggumKopWnuUT4sFUb1JP3nRDtMg5gxi+eI4Rh5OawbTHm/pfaxggX7xw2UXJVq5y05ct1rSUibIKh4k4tCq896d86AI9rYCAdbG2TxmXL2gwGUxyd38reTLCr9TIeisXDfnn2NoMQK0B9o6S0A==",
        t: "MTYwOTExMjc0My4zOTMwMDA=",
        m: "V+eCg3wcJX5jricAvjeD9RzYP9FkdPd7em8c+4TQgRA=",
        i1: "/N/75VMJ7Dt4hdmtg6dchA==",
        i2: "oHQ+SUuYNJPnon1HhzuoKA==",
        uh: "/NJGqcG0XAQsHK/RA4n1triAIEfidm9X4UEB3cfV7L8=",
        hh: "L1TaW2c4AHgYFR5WJCGb6rWYbuzDhJwqo+1zL/mrzrg=",
      }
    }
    window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var cookiesEnabled=(navigator.cookieEnabled)? true : false;
      var cookieSupportInfix=cookiesEnabled?'/nocookie':'/cookie';
      var cpo = document.createElement('script');
      cpo.type = 'text/javascript';
      cpo.src = "/cdn-cgi/challenge-platform/h/g/orchestrate/captcha/v1";
      var done = false;
      cpo.onload = cpo.onreadystatechange = function() {
        if (!done && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) {
          done = true;
          cpo.onload = cpo.onreadystatechange = null;
          window._cf_chl_enter()
        }
      };
      document.getElementsByTagName('head')[0].appendChild(cpo);
    }, false);
  })();
  //]]>
</script>

<style type="text/css">
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
<script type="text/javascript" src="/cdn-cgi/challenge-platform/h/g/orchestrate/captcha/v1"></script><script type="text/javascript" src="https://hcaptcha.com/1/api.js?render=explicit&amp;recaptchacompat=off&amp;onload=_cf_chl_hload"></script></head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> myreadingmanga.info</h2>
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/0vv0b-oscar-x-akira-helios-rising-heroes?__cf_chl_captcha_tk__=e3c66b2977361aeb499db6542d8e7776173f7e76-1609112743-0-AbDRa6RqaWvW_IO3rU3f1Z_aJnhk8SaAk27htY2Bwo_-ZLUL8ttQgUJiTyOLG6wDn9pf_q05FlTWoHjnoZss__Yo2I371UwSRc8WhZL8z-r3Ly-sNrkECMeXA27gTPCabHAKP3OMNJvsSPUQFQjnvbvHFCzxf5cDv1lhxvI2uOLdQ2-ckYz6epT8Ez2figpwlLDNw3zvI_Z02HQc4bKCiBqv2kd8-9CUN3hShCMvjOnOZzPx2vtz6GIiQAlPp-Cq9DJY8icJDKopLM20Zt_zOpgzfYdHAkWbfBYFjvDVOcnNup-yRqjuz3r5H-CUbLo-t8Yd2ORxLSI5PUDmp4FRDcUUPHzw1f0jmW1irnZcRYo9XUEidl41xjG9OXCyUjL7pHio7tUJg4AiZ_8Apx3hVKqg4HVbILldG0ely6QZCxn0oVBuo-pK08SqJwm4Y06aU69BRVGp8ah1AlKg2_rzi0VteHKYmDtBaFE_gCc0dsl_rol1JNNcyYSElAU-pTSiPJUje58DDZiQByjZ1FCKMcZxMUtpmf5-hDuBYJc1RtmgGUREcU2X7D_LvxkEkaPOrJDudC3resIgqJzqwV_VudEnBWTXdstaeoob-fY9N8aF16ookUsJXFrFf0ffyUoNQQ" method="POST" enctype="application/x-www-form-urlencoded">
  
    <div id="cf-please-wait" style="display: none;">
      <div id="spinner">
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
      </div>
      <p data-translate="please_wait" id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
      </div>
  
  <input type="hidden" name="r" value="4828363393daebea304e3235ad38336949e83437-1609112743-0-Aa5I8y+UQ36XAluzAavsAhOkg4YFx6XzWOuOyET+K8R75ycIr1zuhKFSt2lEJaCqglkXFcXZIhfmGTkauForI7cd7x/6UeQpTZeTpXSVTaHQFObDFhoPA2qMYOzaLpAsUQYxC+fPZ/RrHfvucapoMpQPzWYaiMz5NcJtj2bvKB9reylyFDbEU0etno4DGSfFqR00ekYA9eMQfJrUxdCtLh4Jcx6H6eCEmuQosIO4H8XxfJL9hYRnigdQNFidJ4bTAnWu7lxX7rxB7M2lxIJbzPXmwrnv5VEznlADlt3qr0qtBBdKKBtEZpijzW03F/n1I0g5Q2yy8YERJiJNxVmhSlUaHnrvaCDsWGOH9DGOr3Bf1aB7A/IOX+gWL5BRUavuIvCW4km2aSehHWJI/bcGCLjuQeNrDp6gF6vtln/od/OvHz58GAos0RRFJU9ruwQW68XlUviTASfDSyrBADSQzRsoR1t4OFdUUR2JNCRVl6InCIMpLSpybuMQDDabT7YkqRGMz+0eWNwmHlsAPzKMBqzdQBivqXSWKhkIBijS6Xm/OwsFQMnc1aRw3fLNOcyo68TYwRlzyIC0VpLivl7qpunn7v/FZa/zEb66u4+/c5mPUfwl7qnSD2Bi4U/7eG2FMuw4SGraG1ciE6smFMtMBedP4K30Tp8Cm1b+DoLreXDpaI7V5KgylOj3YhONjnGACL8eYCQUWVErFFTL38mpHaqHgV2GHRsyQuOoq+mXkkTlCcg8y48KDoaq5tNoV2G/X3FW8AIg8wHNI5UHxsZaZRjkc4B/R/qeoX6/tPLNqtcqlVAfTSRTDzlpaECmw21QXsLbNwJi2/79lynG5GArTYbGu0Au9aP7622FMNqOA5Y98yc21SVqJ0GRmXa8sDfexwdx28vam6EWoWD0km3sjRbOjEjttk4IqHpi5a/FqX6yI6jdaPVvFQKbqu5yHZgWais92kIpFs3MvQelUD0fJd3oPIY4VBl9Gy/6T+T04zUtR478E9dKBrVjwDamzmwxZh17sHzBteHogqnzwqQ4RaWl8MMynjtIq+wp9CW3bBoX9oN4AxPFDSlMO2vzGGX0L9fICRcP5dPVHjUOAfr8/1QrxNRzQ2wl/FWiNSgbNVPLnvd9sUvXEjMefWR3l1WUOeyg+kgCxgb4/BGTK8CN/1HfAnlc53aIZwwold/PCx7MDrSBwESqk6/bIJI734Z60QZ30JeZO5WXFuBDU4AzIXlBgwMDMfinS9NnGkVtGX0Kk1ZBIDcJhSNE4rl2fIMhk4MeagwG92kBAMSGpIuvqJosu3+9ZuRw/8wBujJK2NHjPjPoQQ1al7jqbsmNsn19Ly+Yi5XSuzXyQvZEHQNDiUdwPgIz+yM3mdDCxEj3GSOc+4ibeKOSpt/5GFzo1g0miNys6ypka1MF/u4NeUyrkC+ECPtee3J2+0Z6vFU1MaF8LT8p/z+8jWz+hCcorwuAlvxJpePLhdIwjkjPBNwoDvFwMNbp+nQgA4+hHFK1fiGFpXAWBWruo5ceE4gnRQwoJXVvP7/4oUT8KtLpfMPfcDZ+NlrFp9KuTr9tg/5PMF1hAP6D0REqF0CS24PCafK/aBRDgIECscM3P4kGgbrv7dQZg3ESpzJOtPQOGMbbS4gHrzsgXO/4wlDXxZwPONsbJovYOJraIVIK4+5LahUjDMJx1PT1i8ZSPHJHhTZzY9mf">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <input type="hidden" name="vc" value="9f7fe62254d4f1c8331c8b6851360068">
  
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script type="text/javascript">
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=6086eab5debce9ec')"></div>
<div id="cf-hcaptcha-container"><iframe src="https://assets.hcaptcha.com/captcha/v1/941dad8/static/hcaptcha-checkbox.html#id=0dopsvm2rax&amp;host=myreadingmanga.info&amp;sentry=true&amp;reportapi=https%3A%2F%2Faccounts.hcaptcha.com&amp;recaptchacompat=off&amp;sitekey=03196e24-ce02-40fc-aa86-4d6130e1c97a" title="widget containing checkbox for hCaptcha security challenge" tabindex="0" frameborder="0" scrolling="no" data-hcaptcha-widget-id="0dopsvm2rax" data-hcaptcha-response="" style="width: 303px; height: 78px; overflow: hidden;"></iframe><textarea id="h-captcha-response-0dopsvm2rax" name="h-captcha-response" style="display: none;"></textarea></div></form>

              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
              
              <p data-translate="resolve_captcha_privacy_pass"> Another way to prevent getting this page in the future is to use Privacy Pass. You may need to download version 2.0 now from the <a rel="noopener noreferrer" href="https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi">Chrome Web Store</a>.</p>
              
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6086eab5debce9ec</strong></span>
    <span class="cf-footer-separator sm:hidden">•</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 1.230.27.211</span>
    <span class="cf-footer-separator sm:hidden">•</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>




<div aria-hidden="true" style="background-color: rgb(255, 255, 255); border: 1px solid rgb(208, 208, 208); box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 4px; border-radius: 4px; left: -10000px; top: -10000px; z-index: -2147483648; position: absolute; transition: opacity 0.15s ease-out 0s; opacity: 0; visibility: hidden;"><div style="position: relative;"><iframe src="https://assets.hcaptcha.com/captcha/v1/941dad8/static/hcaptcha-challenge.html#id=0dopsvm2rax&amp;host=myreadingmanga.info&amp;sentry=true&amp;reportapi=https%3A%2F%2Faccounts.hcaptcha.com&amp;recaptchacompat=off&amp;sitekey=03196e24-ce02-40fc-aa86-4d6130e1c97a" title="Main content of the hCaptcha challenge" frameborder="0" scrolling="no" style="border: 0px; z-index: 2000000000; position: relative;"></iframe></div><div style="width: 100%; height: 100%; position: fixed; pointer-events: none; top: 0px; left: 0px; z-index: 0; background-color: rgb(255, 255, 255); opacity: 0.05;"></div><div style="border-width: 11px; position: absolute; pointer-events: none; margin-top: -11px; z-index: 1; right: 100%;"><div style="border-width: 10px; border-style: solid; border-color: transparent rgb(255, 255, 255) transparent transparent; position: relative; top: 10px; z-index: 1;"></div><div style="border-width: 11px; border-style: solid; border-color: transparent rgb(208, 208, 208) transparent transparent; position: relative; top: -11px; z-index: 0;"></div></div></div></body></html>

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fpvmflzk** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

계속 invaild가 뜨네요, 저만 계속 안되는 건지...
