### ISSUE TITLE
Technical-Preview 어제자 업데이트된걸로 인스타 스토리를 다운 못하는것 같습니다.

### ISSUE THREAD

**Issue by qpcnddl1** [KurtBestor/Hitomi-Downloader#2857]
안녕하세요 다운로더 정말 잘 사용하고 있습니다.

요즘 보안 패치를 인스타가 또 한건지 차단을 계속먹어서 최근 다운로더로 다운 해보았습니다.

어제 17일자 업데이트라고 나와있는 링크로 https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
해봤는데 다행히 일반 피드 게시물들은 다운이 잘 되지만 스토리들은 누락된 상태로 다운이 됩니다.

쿠키까지 잘 먹이고 다운했는데도 몇번이나 계속 이러네요..
그리고 기본3.2버전에 비해 b버전이 인스타 작업읽는 속도가 갑자기 확 느려진거같네요ㅎㅎ;;

확인해주실수있을까요?

항상 감사합니다 !

스토리들 패스하고 다운 받아진 작업 내역올립니다.

은별 (insta_byul._.97)

version: 3.2b (20-12-17 13:04:50 UTC)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://www.instagram.com/byul._.97
dir: hitomi_downloaded_insta\은별 (insta_byul._.97)
zip: 
type: insta
artist: 은별
url: https://www.instagram.com/byul._.97
valid: True
done: True
range: None
range_p: None
single: False
time: 1608258578.1409492 (Dec 18)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.14

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-10-03] CF3ucUsnmWF_p0.jpg
[0002] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-10-03] CF3ucUsnmWF_p1.jpg
[0003] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-08-17] CD-6mKYnSDH_p0.jpg
[0004] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-07-13] CCk95bJFMA7_p0.jpg
[0005] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-06-28] CB-SxCXFx8M_p0.jpg
[0006] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-06-28] CB-SxCXFx8M_p1.jpg
[0007] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-05-16] CAPMilelzEc_p0.jpg
[0008] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-17] B_E8VB6Ftur_p0.jpg
[0009] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-07] B-rA8uMl6FH_p0.jpg
[0010] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-03] B-hNpvUlTPs_p0.jpg
[0011] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-02] B-dfPkLlntc_p0.jpg
[0012] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-03-30] B-V3O_6lfez_p0.jpg
[0013] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-03-24] B-HD7xzFjRL_p0.jpg
[0014] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-03-21] B9_IysEFmV1_p0.jpg
[0015] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-02-12] B8dp2Ysn3hH_p0.jpg
[0016] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-02-05] B8LCOsiHr-l_p0.jpg
[0017] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-02-04] B8Itlu8HCvm_p0.jpg
[0018] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-01-14] B7Sm66XnPy__p0.jpg
[0019] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-10-03] CF3ucUsnmWF_p0.jpg
[0020] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-10-03] CF3ucUsnmWF_p1.jpg
[0021] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-08-17] CD-6mKYnSDH_p0.jpg
[0022] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-07-13] CCk95bJFMA7_p0.jpg
[0023] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-06-28] CB-SxCXFx8M_p0.jpg
[0024] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-06-28] CB-SxCXFx8M_p1.jpg
[0025] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-05-16] CAPMilelzEc_p0.jpg
[0026] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-17] B_E8VB6Ftur_p0.jpg
[0027] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-07] B-rA8uMl6FH_p0.jpg
[0028] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-03] B-hNpvUlTPs_p0.jpg
[0029] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-04-02] B-dfPkLlntc_p0.jpg
[0030] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-03-30] B-V3O_6lfez_p0.jpg
[0031] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-03-24] B-HD7xzFjRL_p0.jpg
[0032] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-03-21] B9_IysEFmV1_p0.jpg
[0033] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-02-12] B8dp2Ysn3hH_p0.jpg
[0034] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-02-05] B8LCOsiHr-l_p0.jpg
[0035] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-02-04] B8Itlu8HCvm_p0.jpg
[0036] hitomi_downloaded_insta\은별 (insta_byul._.97)\[20-01-14] B7Sm66XnPy__p0.jpg

[URLs]
[0001] LazyUrl(https://www.instagram.com/p/CF3ucUsnmWF/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/120539989_1685009021673463_4730641964988874772_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=107&_nc_ohc=9j8OozlcSncAX9_nhzk&tp=1&oh=3b3eda53c2032d6f804b31071928d7ba&oe=600494C8
[0002] LazyUrl(https://www.instagram.com/p/CF3ucUsnmWF/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/120577478_3050198151757045_7195864356007133443_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=101&_nc_ohc=hO-BJmaljZYAX_Qiq7m&tp=1&oh=32329ca65171f52f7411abe556880335&oe=60065639
[0003] LazyUrl(https://www.instagram.com/p/CD-6mKYnSDH/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/117577582_294221078503798_8386598576927513996_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=110&_nc_ohc=bGrP2zYQTRoAX9O9n6q&tp=1&oh=9ea1c0eca741d94e36061e982b385437&oe=6003FD9E
[0004] LazyUrl(https://www.instagram.com/p/CCk95bJFMA7/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/108298775_284097789504148_7956073122263128248_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=104&_nc_ohc=kDyeIULsBswAX9gMLcr&tp=1&oh=addd4be329e249c642bf5200a82bb494&oe=60043CE2
[0005] LazyUrl(https://www.instagram.com/p/CB-SxCXFx8M/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/106374360_700138814099238_5114986395825995398_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=106&_nc_ohc=nkDGOH88iWkAX9ttUXt&tp=1&oh=363010834e464693bf21d28059ac63fc&oe=60063792
[0006] LazyUrl(https://www.instagram.com/p/CB-SxCXFx8M/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/105978183_737784696988954_4345637026674121349_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=110&_nc_ohc=3PjXNgNGO1AAX9HgGch&tp=1&oh=e986b68f3d91fca124f0f65275656f85&oe=60050AEF
[0007] LazyUrl(https://www.instagram.com/p/CAPMilelzEc/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/97267853_318653582453257_280861575226322785_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=101&_nc_ohc=oxvWHT05VywAX-3VjJm&tp=1&oh=ba364fd90d45217cb339f921b7407410&oe=6003C9E1
[0008] LazyUrl(https://www.instagram.com/p/B_E8VB6Ftur/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/93761155_3000314013362354_3797934740461270139_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=102&_nc_ohc=92NHU3kDnDcAX9_yEqB&tp=1&oh=09c79432c0550e2a7d331f8fc9c0b4a6&oe=6003D0B5
[0009] LazyUrl(https://www.instagram.com/p/B-rA8uMl6FH/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/91784459_3636525453089451_271063831469513734_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=103&_nc_ohc=7ssQQo7MBq8AX_YP1qK&tp=1&oh=f2f3ed0bc6a6233eeba17df66e63fd0c&oe=6004C9D6
[0010] LazyUrl(https://www.instagram.com/p/B-hNpvUlTPs/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/92337154_671208293615290_4210887138948216015_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=110&_nc_ohc=ky8NOuyGD_8AX8YckOh&tp=1&oh=eb24ecab44751d7b83480156c9209515&oe=60063F7A
[0011] LazyUrl(https://www.instagram.com/p/B-dfPkLlntc/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/91498356_804620120023662_5174224121796580228_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=106&_nc_ohc=6PaOxX4x1QIAX8pIOat&tp=1&oh=d1341761124f23b3754ab4175e61a054&oe=6005E8E5
[0012] LazyUrl(https://www.instagram.com/p/B-V3O_6lfez/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/91184073_857340798114272_2137549772134674321_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=108&_nc_ohc=rS2nlGy-MCIAX_UV7P_&tp=1&oh=3b7cc40243f9fc64cead7edeb6d66022&oe=60059158
[0013] LazyUrl(https://www.instagram.com/p/B-HD7xzFjRL/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/90491112_2830231043698289_7640922792866896093_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=105&_nc_ohc=Jd02gGO-3xsAX-vtEQW&tp=1&oh=7bc5ab3781b9f6ee34a3a91a554bc357&oe=6003FB9B
[0014] LazyUrl(https://www.instagram.com/p/B9_IysEFmV1/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/83920337_209113323487972_7325021809474534187_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=104&_nc_ohc=TnSIbM9Y8rwAX-qYIvY&tp=1&oh=6ec3b2bb49f5fa1debf77e390678bc23&oe=60062C55
[0015] LazyUrl(https://www.instagram.com/p/B8dp2Ysn3hH/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/82232964_2908704479151403_3538293919001256736_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=107&_nc_ohc=Ni46efjmB48AX87MNQX&tp=1&oh=ade778148d30cfea08c9b361f5482d57&oe=6003C11A
[0016] LazyUrl(https://www.instagram.com/p/B8LCOsiHr-l/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/83526690_169209064406116_7454757722024235286_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=104&_nc_ohc=rrZvVCd-50AAX-0VcUE&tp=1&oh=6f55f042dfa36357786d5894d5222d28&oe=6006ED47
[0017] LazyUrl(https://www.instagram.com/p/B8Itlu8HCvm/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/82464215_1451361198383113_7411027313843873810_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=101&_nc_ohc=fQYxdjjXEmcAX-Xmdqh&tp=1&oh=3731264f5ec047f5c868984f6b1e0ade&oe=6006D4BB
[0018] LazyUrl(https://www.instagram.com/p/B7Sm66XnPy_/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/82096960_2618021724978165_5708187764956910536_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=109&_nc_ohc=iwfapPEAHlAAX-cLcbQ&tp=1&oh=6af35ff50ba1cfb0197ae66922c7c030&oe=600591CA
[0019] LazyUrl(https://www.instagram.com/p/CF3ucUsnmWF/) ---> 【local_lazy】 [20-10-03] CF3ucUsnmWF_p0.jpg
[0020] LazyUrl(https://www.instagram.com/p/CF3ucUsnmWF/) ---> 【local_lazy】 [20-10-03] CF3ucUsnmWF_p1.jpg
[0021] LazyUrl(https://www.instagram.com/p/CD-6mKYnSDH/) ---> 【local_lazy】 [20-08-17] CD-6mKYnSDH_p0.jpg
[0022] LazyUrl(https://www.instagram.com/p/CCk95bJFMA7/) ---> 【local_lazy】 [20-07-13] CCk95bJFMA7_p0.jpg
[0023] LazyUrl(https://www.instagram.com/p/CB-SxCXFx8M/) ---> 【local_lazy】 [20-06-28] CB-SxCXFx8M_p0.jpg
[0024] LazyUrl(https://www.instagram.com/p/CB-SxCXFx8M/) ---> 【local_lazy】 [20-06-28] CB-SxCXFx8M_p1.jpg
[0025] LazyUrl(https://www.instagram.com/p/CAPMilelzEc/) ---> 【local_lazy】 [20-05-16] CAPMilelzEc_p0.jpg
[0026] LazyUrl(https://www.instagram.com/p/B_E8VB6Ftur/) ---> 【local_lazy】 [20-04-17] B_E8VB6Ftur_p0.jpg
[0027] LazyUrl(https://www.instagram.com/p/B-rA8uMl6FH/) ---> 【local_lazy】 [20-04-07] B-rA8uMl6FH_p0.jpg
[0028] LazyUrl(https://www.instagram.com/p/B-hNpvUlTPs/) ---> 【local_lazy】 [20-04-03] B-hNpvUlTPs_p0.jpg
[0029] LazyUrl(https://www.instagram.com/p/B-dfPkLlntc/) ---> 【local_lazy】 [20-04-02] B-dfPkLlntc_p0.jpg
[0030] LazyUrl(https://www.instagram.com/p/B-V3O_6lfez/) ---> 【local_lazy】 [20-03-30] B-V3O_6lfez_p0.jpg
[0031] LazyUrl(https://www.instagram.com/p/B-HD7xzFjRL/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/90491112_2830231043698289_7640922792866896093_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=105&_nc_ohc=Jd02gGO-3xsAX-vtEQW&tp=1&oh=7bc5ab3781b9f6ee34a3a91a554bc357&oe=6003FB9B
[0032] LazyUrl(https://www.instagram.com/p/B9_IysEFmV1/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/83920337_209113323487972_7325021809474534187_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=104&_nc_ohc=TnSIbM9Y8rwAX-qYIvY&tp=1&oh=6ec3b2bb49f5fa1debf77e390678bc23&oe=60062C55
[0033] LazyUrl(https://www.instagram.com/p/B8dp2Ysn3hH/) ---> 【local_lazy】 [20-02-12] B8dp2Ysn3hH_p0.jpg
[0034] LazyUrl(https://www.instagram.com/p/B8LCOsiHr-l/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/83526690_169209064406116_7454757722024235286_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=104&_nc_ohc=rrZvVCd-50AAX-0VcUE&tp=1&oh=6f55f042dfa36357786d5894d5222d28&oe=6006ED47
[0035] LazyUrl(https://www.instagram.com/p/B8Itlu8HCvm/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/82464215_1451361198383113_7411027313843873810_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=101&_nc_ohc=fQYxdjjXEmcAX-Xmdqh&tp=1&oh=3731264f5ec047f5c868984f6b1e0ade&oe=6006D4BB
[0036] LazyUrl(https://www.instagram.com/p/B7Sm66XnPy_/) ---> https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/82096960_2618021724978165_5708187764956910536_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=109&_nc_ohc=iwfapPEAHlAAX-cLcbQ&tp=1&oh=6af35ff50ba1cfb0197ae66922c7c030&oe=600591CA

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1045, in start
File "extractor\insta_downloader", line 43, in init
File "extractor\insta_downloader", line 26, in get_session
errors.LoginRequired

Invalid: fail=False
EOT: https://www.instagram.com/byul._.97 (0.0s)

stop
EOT: https://www.instagram.com/byul._.97 (35.1s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by qpcnddl1** [comment]
어제 다시 업뎃해주셨군요 정말 감사합니다!! 확인해보니 스토리도 함께 잘 다운되네요 ㅎㅎ

근데 속도가 이제 이렇게 변한게 정상인가요ㅠㅠ?? 
이전 3.2버전에서 인스타 계정 사진 30장 다운받는데 20초면 됐던게 스레드 바르게 설정하고 해도 방금 해보니 6분이 넘게 걸리네요 ㄷㄷ

**Comment by KurtBestor** [comment]
네 너무 빠르면 차단당해서 줄여놓았어요

**Comment by qpcnddl1** [comment]
아 ㅎㅎ 개발자님 항상 감사합니다 ^^
