### ISSUE TITLE
xHamster 다운로드 오류

### ISSUE THREAD

**Issue by D3F4ULTtt** [KurtBestor/Hitomi-Downloader#2858]
2가지의 오류가 있는데, 하나는 아예 invalid라고 빨간 불 들어오면서 다운로드가 안되는 오류입니다.

Invalid: [xhamster] https://xhamster.com/users/shock4/videos

version: 3.2b (20-12-17 13:04:50 UTC)
platform: Windows-10-10.0.18362-SP0
order: 106
group: False
input: https://xhamster.com/users/shock4/videos
dir: 
zip: 
type: xhamster
artist: None
url: https://xhamster.com/users/shock4/videos
valid: False
done: True
range: None
range_p: None
single: True
time: 1608286218.164198 (Dec 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}
ytdl: 2020.12.14

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://xhamster.com/users/shock4/videos/1
https://xhamster.com/users/shock4/videos/2
https://xhamster.com/users/shock4/videos/3
https://xhamster.com/users/shock4/videos/4
https://xhamster.com/users/shock4/videos/5
https://xhamster.com/users/shock4/videos/6
https://xhamster.com/users/shock4/videos/7
https://xhamster.com/users/shock4/videos/8
https://xhamster.com/users/shock4/videos/9
https://xhamster.com/users/shock4/videos/10
https://xhamster.com/users/shock4/videos/11
https://xhamster.com/users/shock4/videos/12
https://xhamster.com/users/shock4/videos/13
https://xhamster.com/users/shock4/videos/14
https://xhamster.com/users/shock4/videos/15
https://xhamster.com/users/shock4/videos/16
https://xhamster.com/users/shock4/videos/17
https://xhamster.com/users/shock4/videos/18
https://xhamster.com/users/shock4/videos/19
https://xhamster.com/users/shock4/videos/20
403 Client Error: Forbidden for url: https://xhamster18.com/videos/korean-general-girl-lecture-room-xhiVwFR4
stop
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1059, in start
File "utils", line 1100, in start_
File "extractor\xhamster_downloader", line 43, in read
File "utils", line 1355, in process_playlist
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/korean-general-girl-lecture-room-xhiVwFR4

Invalid: fail=True
EOT: https://xhamster.com/users/shock4/videos (373.2s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1059, in start
File "utils", line 1100, in start_
File "extractor\xhamster_downloader", line 40, in read
File "extractor\xhamster_downloader", line 124, in read_channel
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://xhamster.com/users/shock4/videos (1.4s)

두 번째는 채널 하나 통째로 다운로드를 할 때, 모든 동영상을 다운로드 하지 못하고 일부만 다운로드 받은뒤 주황색 불 들어오고 일정 시간 이후 다시 시도하는 오류입니다. 계속 재시도를 하도록 가만히 두면 어쩌다가 전체 다운로드 성공하는 경우도 있는데, 한번 에러걸리는 채널은 계속 에러가 뜨는편입니다.

[Channel] dreamskyz

version: 3.2b (20-12-17 13:04:50 UTC)
platform: Windows-10-10.0.18362-SP0
order: 99
group: False
input: https://xhamster.com/users/dreamskyz/videos
dir: hitomi_downloaded_xhamster\[Channel] dreamskyz
zip: 
type: xhamster
artist: None
url: https://xhamster.com/users/dreamskyz/videos
valid: False
done: True
range: None
range_p: None
single: False
time: 1608285435.5130117 (Dec 18)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: True
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}
ytdl: 2020.12.14

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_xhamster\[Channel] dreamskyz\sg 2018 (9358961).mp4
[0002] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0003] hitomi_downloaded_xhamster\[Channel] dreamskyz\day day in (9300779).mp4
[0004] hitomi_downloaded_xhamster\[Channel] dreamskyz\girl friend 001 (9243584).mp4
[0005] hitomi_downloaded_xhamster\[Channel] dreamskyz\fcrv 2018 (9100575).mp4
[0006] hitomi_downloaded_xhamster\[Channel] dreamskyz\sex apps (8836683).mp4
[0007] hitomi_downloaded_xhamster\[Channel] dreamskyz\chinese chaning room (8460100).mp4
[0008] hitomi_downloaded_xhamster\[Channel] dreamskyz\tpol 2 (8392738).mp4
[0009] hitomi_downloaded_xhamster\[Channel] dreamskyz\crv 006 (8295280).mp4
[0010] hitomi_downloaded_xhamster\[Channel] dreamskyz\vid 001 (8168998).mp4
[0011] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0012] hitomi_downloaded_xhamster\[Channel] dreamskyz\Changing Room Voyeur 2 (8066402).mp4
[0013] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0014] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0015] hitomi_downloaded_xhamster\[Channel] dreamskyz\even day 001 (7967382).mp4
[0016] hitomi_downloaded_xhamster\[Channel] dreamskyz\222 (7462270).mp4
[0017] hitomi_downloaded_xhamster\[Channel] dreamskyz\hong kong sex (7101196).mp4
[0018] hitomi_downloaded_xhamster\[Channel] dreamskyz\ttt (6968254).mp4
[0019] hitomi_downloaded_xhamster\[Channel] dreamskyz\123 (6869536).mp4
[0020] hitomi_downloaded_xhamster\[Channel] dreamskyz\sex (6651274).mp4
[0021] hitomi_downloaded_xhamster\[Channel] dreamskyz\chinsese 3 (6365822).mp4
[0022] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0023] hitomi_downloaded_xhamster\[Channel] dreamskyz\17 APP (6361128).mp4
[0024] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0025] hitomi_downloaded_xhamster\[Channel] dreamskyz\YOLO APP SEX (5849252).mp4
[0026] hitomi_downloaded_xhamster\[Channel] dreamskyz\123 (5506961).mp4
[0027] hitomi_downloaded_xhamster\[Channel] dreamskyz\morning 2 u (4954968).mp4
[0028] hitomi_downloaded_xhamster\[Channel] dreamskyz\UNIQLO dressing room (4856694).mp4
[0029] hitomi_downloaded_xhamster\[Channel] dreamskyz
[0030] hitomi_downloaded_xhamster\[Channel] dreamskyz\love (4571791).mp4
[0031] hitomi_downloaded_xhamster\[Channel] dreamskyz\i love u (4428632).mp4
[0032] hitomi_downloaded_xhamster\[Channel] dreamskyz\you (4397431).mp4
[0033] hitomi_downloaded_xhamster\[Channel] dreamskyz\Couple (4393042).mp4
[0034] hitomi_downloaded_xhamster\[Channel] dreamskyz\Chinese (4393024).mp4
[0035] hitomi_downloaded_xhamster\[Channel] dreamskyz\sweetbecca (4388912).mp4
[0036] hitomi_downloaded_xhamster\[Channel] dreamskyz\Chinese young (4378865).mp4

[URLs]
[0001] LazyUrl(https://xhamster18.com/videos/sg-2018-9358961) ---> 【local_lazy】 sg 2018 (9358961).mp4
[0002] LazyUrl(https://xhamster18.com/videos/sg-2018-123-9358987)
[0003] LazyUrl(https://xhamster18.com/videos/day-day-in-9300779) ---> 【local_lazy】 day day in (9300779).mp4
[0004] LazyUrl(https://xhamster18.com/videos/girl-friend-001-9243584) ---> 【local_lazy】 girl friend 001 (9243584).mp4
[0005] LazyUrl(https://xhamster18.com/videos/fcrv-2018-9100575) ---> 【local_lazy】 fcrv 2018 (9100575).mp4
[0006] LazyUrl(https://xhamster18.com/videos/sex-apps-8836683) ---> 【local_lazy】 sex apps (8836683).mp4
[0007] LazyUrl(https://xhamster18.com/videos/chinese-chaning-room-8460100) ---> 【local_lazy】 chinese chaning room (8460100).mp4
[0008] LazyUrl(https://xhamster18.com/videos/tpol-2-8392738) ---> 【local_lazy】 tpol 2 (8392738).mp4
[0009] LazyUrl(https://xhamster18.com/videos/crv-006-8295280) ---> 【local_lazy】 crv 006 (8295280).mp4
[0010] LazyUrl(https://xhamster18.com/videos/vid-001-8168998) ---> 【local_lazy】 vid 001 (8168998).mp4
[0011] LazyUrl(https://xhamster18.com/videos/changing-room-voyeur-3-8066431)
[0012] LazyUrl(https://xhamster18.com/videos/changing-room-voyeur-2-8066402) ---> 【local_lazy】 Changing Room Voyeur 2 (8066402).mp4
[0013] LazyUrl(https://xhamster18.com/videos/crv-cutie-003-8052215)
[0014] LazyUrl(https://xhamster18.com/videos/crv-8038587)
[0015] LazyUrl(https://xhamster18.com/videos/even-day-001-7967382) ---> 【local_lazy】 even day 001 (7967382).mp4
[0016] LazyUrl(https://xhamster18.com/videos/222-7462270) ---> 【local_lazy】 222 (7462270).mp4
[0017] LazyUrl(https://xhamster18.com/videos/hong-kong-sex-7101196) ---> 【local_lazy】 hong kong sex (7101196).mp4
[0018] LazyUrl(https://xhamster18.com/videos/ttt-6968254) ---> 【local_lazy】 ttt (6968254).mp4
[0019] LazyUrl(https://xhamster18.com/videos/123-6869536) ---> 【local_lazy】 123 (6869536).mp4
[0020] LazyUrl(https://xhamster18.com/videos/sex-6651274) ---> 【local_lazy】 sex (6651274).mp4
[0021] LazyUrl(https://xhamster18.com/videos/chinsese-3-6365822) ---> 【local_lazy】 chinsese 3 (6365822).mp4
[0022] LazyUrl(https://xhamster18.com/videos/singaporean-6365028)
[0023] LazyUrl(https://xhamster18.com/videos/17-app-6361128) ---> 【local_lazy】 17 APP (6361128).mp4
[0024] LazyUrl(https://xhamster18.com/videos/friend-6074623)
[0025] LazyUrl(https://xhamster18.com/videos/yolo-app-sex-5849252) ---> 【local_lazy】 YOLO APP SEX (5849252).mp4
[0026] LazyUrl(https://xhamster18.com/videos/123-5506961) ---> 【local_lazy】 123 (5506961).mp4
[0027] LazyUrl(https://xhamster18.com/videos/morning-2-u-4954968) ---> 【local_lazy】 morning 2 u (4954968).mp4
[0028] LazyUrl(https://xhamster18.com/videos/uniqlo-dressing-room-4856694) ---> 【local_lazy】 UNIQLO dressing room (4856694).mp4
[0029] LazyUrl(https://xhamster18.com/videos/you-4571794)
[0030] LazyUrl(https://xhamster18.com/videos/love-4571791) ---> 【local_lazy】 love (4571791).mp4
[0031] LazyUrl(https://xhamster18.com/videos/i-love-u-4428632) ---> 【local_lazy】 i love u (4428632).mp4
[0032] LazyUrl(https://xhamster18.com/videos/you-4397431) ---> 【local_lazy】 you (4397431).mp4
[0033] LazyUrl(https://xhamster18.com/videos/couple-4393042) ---> 【local_lazy】 Couple (4393042).mp4
[0034] LazyUrl(https://xhamster18.com/videos/chinese-4393024) ---> 【local_lazy】 Chinese (4393024).mp4
[0035] LazyUrl(https://xhamster18.com/videos/sweetbecca-4388912) ---> 【local_lazy】 sweetbecca (4388912).mp4
[0036] LazyUrl(https://xhamster18.com/videos/chinese-young-4378865) ---> 【local_lazy】 Chinese young (4378865).mp4

[Messages]
https://xhamster.com/users/dreamskyz/videos/1
https://xhamster.com/users/dreamskyz/videos/2
https://xhamster.com/users/dreamskyz/videos/3

LazyUrl error (https://xhamster18.com/videos/sg-2018-123-9358987):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/sg-2018-123-9358987

LazyUrl error (https://xhamster18.com/videos/changing-room-voyeur-3-8066431):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/crv-cutie-003-8052215):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/crv-cutie-003-8052215

LazyUrl error (https://xhamster18.com/videos/crv-8038587):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/singaporean-6365028):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/friend-6074623):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 98, in get_info
Exception: Video was deleted

LazyUrl error (https://xhamster18.com/videos/you-4571794):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/you-4571794

stop
valid=False 1
EOT: https://xhamster.com/users/dreamskyz/videos (95.4s)

https://xhamster.com/users/dreamskyz/videos/1
https://xhamster.com/users/dreamskyz/videos/2
https://xhamster.com/users/dreamskyz/videos/3

LazyUrl error (https://xhamster18.com/videos/sg-2018-123-9358987):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/sg-2018-123-9358987

LazyUrl error (https://xhamster18.com/videos/changing-room-voyeur-3-8066431):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/crv-cutie-003-8052215):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/crv-8038587):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/singaporean-6365028):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/friend-6074623):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 98, in get_info
Exception: Video was deleted

LazyUrl error (https://xhamster18.com/videos/you-4571794):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/you-4571794

stop
valid=False 1
EOT: https://xhamster.com/users/dreamskyz/videos (81.0s)

https://xhamster.com/users/dreamskyz/videos/1
https://xhamster.com/users/dreamskyz/videos/2
https://xhamster.com/users/dreamskyz/videos/3

LazyUrl error (https://xhamster18.com/videos/sg-2018-123-9358987):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/sg-2018-123-9358987

LazyUrl error (https://xhamster18.com/videos/changing-room-voyeur-3-8066431):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/crv-cutie-003-8052215):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/crv-8038587):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/singaporean-6365028):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 102, in get_info
KeyError: 'videoModel'

LazyUrl error (https://xhamster18.com/videos/friend-6074623):
Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 98, in get_info
Exception: Video was deleted

LazyUrl error (https://xhamster18.com/videos/you-4571794):
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 229, in run
File "utils", line 686, in __call__
File "<decorator-gen-59>", line 2, in get
File "constants", line 868, in wrapper
File "constants", line 839, in wrapper
File "extractor\xhamster_downloader", line 74, in get
File "extractor\xhamster_downloader", line 93, in get_info
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://xhamster18.com/videos/you-4571794

stop
valid=False 1
EOT: https://xhamster.com/users/dreamskyz/videos (89.0s)

https://xhamster.com/users/dreamskyz/videos/1
list index out of range
stop
Traceback (most recent call last):
File "utils", line 1059, in start
File "utils", line 1100, in start_
File "extractor\xhamster_downloader", line 43, in read
File "utils", line 1354, in process_playlist
IndexError: list index out of range

Invalid: fail=True
EOT: https://xhamster.com/users/dreamskyz/videos (5.4s)

invalid; revert

제가 대충 보기에는 빨간불로 에러가 나오는 경우는 해당 채널의 가장 앞의 동영상이 friends only일 경우에 발생하는 것 같고,
주황색 불 들어오는 에러의 경우에는 채널 내에 public으로 공개된 동영상을 모두 받고나서 friends only나 password lock걸린 동영상의 다운로드에 실패해서 발생하는 에러인 것으로 생각하고 있습니다.
다운로드 불가한 동영상을 건너뛰고 완료할 수 있는 기능이 포함되면 좋을 것 같습니다.

항상 잘 이용하고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by D3F4ULTtt** [comment]
감사합니다! 아주 잘 됩니다.
