### ISSUE TITLE
텀블러 다운로드가 안되는 계정 (쿠키 정상적용중)

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2859]
안녕하세요 존경하는 KurtBestor 선생님!

쿠키 넣고 텀블러 다운로드 받는 중에 대부분은 잘되는데 가끔 안되는 케이스가 있어 질문올립니다.

시도한 계정 - makooooon.tumblr.com

로그인 하면 접속은 잘 되는 계정입니다.

아래는 출력된 메세지입니다.

---------------------------------------------------------------------------------------------------------------

Invalid: [tumblr] makooooon.tumblr.com

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: makooooon.tumblr.com
dir: 
zip: 
type: tumblr
artist: None
url: https://makooooon.tumblr.com
valid: False
done: True
range: ~4000
range_p: None
single: False
time: 1608333918.4479496 (Dec 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
404 Client Error: Not Found for url: https://makooooon.tumblr.com/api/read?num=0&start=0
stop
Traceback (most recent call last):
File "downloader", line 306, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\tumblr_downloader", line 84, in read
File "extractor\tumblr_downloader", line 106, in get_name
File "downloader", line 339, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://makooooon.tumblr.com/api/read?num=0&start=0

Invalid: fail=True
EOT: makooooon.tumblr.com (2.5s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
테스트 결과 보고드립니다!

위에 경우는 테스트 결과 잘 다운되게 바뀌어서 정상다운 되는데, 

이번엔 또 다른 계정으로 테스트 해보니 작동하지 않아서 남겨드려요.

(혹시 계정마다 고유하게 주소가 부여되어서 안되는게 생기는 걸까요?)

아래는 실패한 계정 로그입니다!

시도한 계정 : https://ryoryo-chan.tumblr.com

-----------------------------------------------------------------------------------------------------------------------

Invalid: [tumblr] ryoryo-chan.tumblr.com

version: 3.2b (20-12-19 09:28:30 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: ryoryo-chan.tumblr.com
dir: 
zip: 
type: tumblr
artist: None
url: https://ryoryo-chan.tumblr.com
valid: False
done: True
range: ~4000
range_p: None
single: False
time: 1608639417.9132736 (Dec 22)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.22


[Gallery]
None


[File Names]



[URLs]



[Messages]
'media'
stop
Traceback (most recent call last):
File "utils", line 1059, in start
File "utils", line 1100, in start_
File "extractor\tumblr_downloader", line 42, in read
File "extractor\tumblr_downloader", line 160, in get_imgs
File "extractor\tumblr_downloader", line 112, in posts
File "extractor\tumblr_downloader", line 139, in __init__
KeyError: 'media'

Invalid: fail=True
EOT: ryoryo-chan.tumblr.com (24.6s)

**Comment by KurtBestor** [comment]
최신버전에서 해결됐을거예요.

**Comment by tdi2020** [comment]
테스트 결과 보고드립니다!

역시 위에건 해결되어 잘받았는데 안되는 계정을 찾았어요.

최신버전이며 아래는 실패한 계정 로그입니다!

시도한 계정 : https://cindysoek.tumblr.com

---------------------------------------------------------------------------------------------------

Invalid: [tumblr] https://cindysoek.tumblr.com

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://cindysoek.tumblr.com
dir: 
zip: 
type: tumblr
artist: None
url: https://cindysoek.tumblr.com
valid: False
done: True
range: ~4000
range_p: None
single: False
time: 1609164934.8851397 (Dec 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.26


[Gallery]
None


[File Names]



[URLs]



[Messages]
{'type': 'link', 'url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'display_url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'title': 'Swimsuits', 'description': '\r\n\tSexy Swimsuits Vs Sexy Bikinis\r\n\n\n\tAre sexy one piece swimsuits or \n\t\t\r\n\t\t\tsexy bikinis\r\n\t\t in a two piece cut hotter? This can be consid', 'site_name': 'amiclubwear.com'}
stop
Traceback (most recent call last):
File "utils", line 1065, in start
File "utils", line 1109, in start_
File "extractor\tumblr_downloader", line 42, in read
File "extractor\tumblr_downloader", line 162, in get_imgs
File "extractor\tumblr_downloader", line 112, in posts
File "extractor\tumblr_downloader", line 147, in __init__
NotImplementedError: {'type': 'link', 'url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'display_url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'title': 'Swimsuits', 'description': '\r\n\tSexy Swimsuits Vs Sexy Bikinis\r\n\n\n\tAre sexy one piece swimsuits or \n\t\t\r\n\t\t\tsexy bikinis\r\n\t\t in a two piece cut hotter? This can be consid', 'site_name': 'amiclubwear.com'}

Invalid: fail=True
EOT: https://cindysoek.tumblr.com (8.4s)

{'type': 'link', 'url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'display_url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'title': 'Swimsuits', 'description': '\r\n\tSexy Swimsuits Vs Sexy Bikinis\r\n\n\n\tAre sexy one piece swimsuits or \n\t\t\r\n\t\t\tsexy bikinis\r\n\t\t in a two piece cut hotter? This can be consid', 'site_name': 'amiclubwear.com'}
stop
Traceback (most recent call last):
File "utils", line 1065, in start
File "utils", line 1109, in start_
File "extractor\tumblr_downloader", line 42, in read
File "extractor\tumblr_downloader", line 162, in get_imgs
File "extractor\tumblr_downloader", line 112, in posts
File "extractor\tumblr_downloader", line 147, in __init__
NotImplementedError: {'type': 'link', 'url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'display_url': 'https://t.umblr.com/redirect?z=https%3A%2F%2Fwww.amiclubwear.com%2Fswimsuit%2Fpage%2F9.html&t=NzQxNjk5MDE4MjI2OTczN2RlMzQ4ODgxZDM3ZDIyYmZlMDc0YjYzMiw0ZmVjZTEwMjViN2E2MmU3NjljMDQ5ZjAyNTA1YmVmZmIzZjk0M2Vh&ts=1599224175', 'title': 'Swimsuits', 'description': '\r\n\tSexy Swimsuits Vs Sexy Bikinis\r\n\n\n\tAre sexy one piece swimsuits or \n\t\t\r\n\t\t\tsexy bikinis\r\n\t\t in a two piece cut hotter? This can be consid', 'site_name': 'amiclubwear.com'}

Invalid: fail=True
EOT: https://cindysoek.tumblr.com (8.7s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
테스트 결과 보고드립니다!

위 계정이 테스트 버전에서 잘 다운 되었는데 이전과는 다르게 아예 리스트를 받고 멈춰버리는 계정도 있어 올려봅니다.

아래는 실패한 계정 로그입니다!

시도한 계정 : https://darkserika.tumblr.com

--------------------------------------------------------------

Misoras : All about Gravure (tumblr_darkserika)

version: 3.2c (20-12-28 17:41:04 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://darkserika.tumblr.com
dir: crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)
zip: 
type: tumblr
artist: None
url: https://darkserika.tumblr.com
valid: True
done: False
range: ~4000
range_p: None
single: False
time: 1609186795.6959028 (Dec 29)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.26


[Gallery]
None


(엄청 많은 파일네임들이 있고, 아래는 Fail 메세지입니다!)



Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620316703375360_p1.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620316703375360_p1.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620438448177152_p5.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620438448177152_p5.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620316703375360_p0.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620316703375360_p0.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620438448177152_p6.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620438448177152_p6.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620438448177152_p3.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620438448177152_p3.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620316703375360_p3.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620316703375360_p3.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638714178005237760_p4.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638714178005237760_p4.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620438448177152_p0.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620438448177152_p0.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620438448177152_p7.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620438448177152_p7.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620438448177152_p8.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620438448177152_p8.jpg'


Fail : \\?\crawl_tumblr\Misoras : All about Gravure (tumblr_darkserika)\638620535355539456_p9.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\crawl_tumblr\\Misoras : All about Gravure (tumblr_darkserika)\\638620535355539456_p9.jpg'

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
너무 늦게봤네요ㅠㅠ 잘되는 것 확인하였습니다 선생님 감사드립니다!!
