### ISSUE TITLE
업데이트 이후 마나토끼 무한 로딩이...다운이 안됩니다ㅠ_ㅠ

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2867]
읽는 중... https://manatoki91.net/comic/6313456

version: 3.2c (20-12-23 01:58:21 UTC)
platform: Windows-10-10.0.19041-SP0
order: 23
group: False
input: https://manatoki91.net/comic/6313456
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki91.net/comic/6313456
valid: True
done: False
range: None
range_p: None
single: True
time: 1608690355.9425132 (Dec 23)
tags: []
goodbyedpi: True
lock: False
color: reading
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.22

[Gallery]
None

[File Names]

[URLs]
어제까지는 정말 잘되는데...오늘 업데이트 이후로는 마나토끼는 게속 읽는 중 입니다

**Comment by geniussjt** [comment]
Invalid: [manatoki] https://manatoki91.net/comic/6313457

version: 3.2c (20-12-23 01:58:21 UTC)
platform: Windows-10-10.0.19041-SP0
order: 22
group: False
input: https://manatoki91.net/comic/6313457
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki91.net/comic/6313457
valid: False
done: True
range: None
range_p: None
single: False
time: 1608690362.9477723 (Dec 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.22


[Gallery]
None


[File Names]



[URLs]



[Messages]
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 1045, in start
File "<decorator-gen-85>", line 2, in init
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\manatoki_downloader", line 37, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 64, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki91.net/comic/6313457 (493.9s)
읽는 중에 
결국 다운이 안되네요
하루 빨리 해결해주세요ㅠ_ㅠ
운영자님 항상 진심으로 감사합니다ㅠㅠb척

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2863#issuecomment-749511073

**Comment by geniussjt** [comment]
옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기 눌러서 주소창에 해당 링크 입력하고 Enter 눌러보세요. 
했는데요 백지로 나옵니다
#
![thumb-CcvJtfOzsr8Q_240x280](https://user-images.githubusercontent.com/47520785/102954307-82251f00-4516-11eb-9a8a-bb4880eff188.jpg)

**Comment by geniussjt** [comment]
추가요 
![thumb-CcvJtfOzsr8Q_240x280](https://user-images.githubusercontent.com/47520785/102954776-a46b6c80-4517-11eb-863f-1e3b69c0d18b.jpg)

**Comment by KurtBestor** [comment]
일단 [v3.2b](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.2b) 로 롤백했어요.

**Comment by geniussjt** [comment]
정말 잘됩니다T^T 
정말로 감사합니다ㅠ_ㅠb척

**Comment by bewidu** [comment]
저도 정식 v3.2b에서는 잘 됩니다. 그리고 베타버전중에서도 12월12일에 나온 버전까지는 문제가 없었습니다.
