### ISSUE TITLE
히토미 폰헙 사용시에 질문이요 

### ISSUE THREAD

**Issue by wkfahffkdy** [KurtBestor/Hitomi-Downloader#2875]
예전에 아마 채널 주소만 긁으면 해당 채널의 영상들이 다 다운받아지는게 있었던거 같은데 지금 안보이더라구요

그래서 최신 버젼 다운받아서 해보니

[channel] 동영상 이름..    이런식으로만 뜨고

영상 1개밖에 다운이 안되는데 이게 맞는건가요 ? channel 이라고 붙어잇는거 보니 채널을 다 읽어 오려는거 같긴 한데 ㅇㅇ..

**Comment by wkfahffkdy** [comment]
지금 보니까, 폰헙이나 유튜브 같은 곳에서 주소 1개씩 긁어와서 하나씩 받아도

폴더 보면 맨 처음에 폴더 지정하고 처음으로 다운 받은 것만 폴더에 저장되고

나머지는 저장이 안되고 있습니다 ㅇㅇ..  맨 처음 저장한 것은 이름이 공란으로 되잇구요..

**Comment by zerox022** [comment]
저는 지금 폰헙에서 영상 자체가 다운이 안되고 있는데.... 로그인 쿠키도 정확하게 해서 진행했는데 안되더라구요... 아래 로그 입니다.

Invalid: [pornhub] https://www.pornhubpremium.com/view_video.php?viewkey=ph5f400343587e6

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.pornhubpremium.com/view_video.php?viewkey=ph5f400343587e6
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5f400343587e6
valid: False
done: True
range: None
range_p: None
single: True
time: 1609272375.7146862 (Dec 30)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.29


[Gallery]
None


[File Names]



[URLs]



[Messages]
is_login 2
www.pornhubpremium.com
stop
Traceback (most recent call last):
File "utils", line 1065, in start
File "utils", line 1109, in start_
File "extractor\pornhub_downloader", line 141, in read
NotImplementedError: www.pornhubpremium.com

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5f400343587e6 (4.5s)
