### ISSUE TITLE
3.2 업데이트 부터 제이마나 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by puzdragon** [KurtBestor/Hitomi-Downloader#2884]
Browser required; Use --safemode: https://jmana1.net/bookdetail?bookdetailid=409683

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://jmana1.net/bookdetail?bookdetailid=409683
dir: 
zip: 
type: jmana
artist: None
url: https://jmana1.net/bookdetail?bookdetailid=409683
valid: False
done: True
range: None
range_p: None
single: False
time: 1609123406.3254883 (Dec 28)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.26

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1051, in start
File "extractor\jmana_downloader", line 84, in init
File "extractor\jmana_downloader", line 22, in fix_url
File "clf2", line 34, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://jmana1.net/bookdetail?bookdetailid=409683 (0.0s)

### _cmd 에서 safemode로 사용해보니_

Invalid: [jmana] https://jmana1.net/bookdetail?bookdetailid=409683

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://jmana1.net/bookdetail?bookdetailid=409683
dir: 
zip: 
type: jmana
artist: None
url: https://jmana1.net/bookdetail?bookdetailid=409683
valid: False
done: True
range: None
range_p: None
single: False
time: 1609123608.589884 (Dec 28)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.26

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "downloader", line 291, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1065, in start
File "utils", line 1109, in start_
File "extractor\jmana_downloader", line 104, in read
File "extractor\jmana_downloader", line 97, in name
File "extractor\jmana_downloader", line 90, in soup
File "downloader", line 331, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 110, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://jmana1.net/bookdetail?bookdetailid=409683 (10.4s)

이렇게 뜹니다.

 여태까지는 3.1v 로 버텼는데 제이마나 업데이트 이후 그것도 안되네요 ㅠㅠ

**Comment by inki123** [comment]
제이마나 홈페이지 리뉴얼되면서 아예 적용이 안돼요....
