### ISSUE TITLE
Replace URLs 스크립트가 새로운 업데이트 후 사용이 안되는 것 같습니다.

### ISSUE THREAD

**Issue by alskdh** [KurtBestor/Hitomi-Downloader#2895]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 4562, in exec_script
  File "dynamic_module_3", line 45, in <module>
NameError: name 'icons_test' is not defined

**Comment by KurtBestor** [comment]
고쳤어요. 다시 다운로드해주세요.
