### ISSUE TITLE
Gelbooru 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by fjscl4869** [KurtBestor/Hitomi-Downloader#2924]
Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=list&tags=shishamo_%28masato_k%29

version: 3.2c (21-01-03 05:12:53 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://gelbooru.com/index.php?page=post&s=list&tags=shishamo_%28masato_k%29
dir: 
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=shishamo_%28masato_k%29
valid: False
done: True
range: None
range_p: None
single: False
time: 1609660671.40395 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.03

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=post&s=list&tags=shishamo_%28masato_k%29
https://gelbooru.com/index.php?page=post&s=list&tags=shishamo_%28masato_k%29
no imgs
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1119, in start_
File "extractor\gelbooru_downloader", line 60, in read
File "extractor\gelbooru_downloader", line 172, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=shishamo_%28masato_k%29 (3.5s)

**Comment by nikin78** [comment]
저도 동일한 사유로 gelbooru 이미지 다운로드가 막혔습니다
로그인 쿠키를 넣었을 때와 안 넣었을 때 무관하게 동일하게 발생하는 문제입니다
태그 검색 후 다운로드 및 단일 이미지 다운로드의 경우 두 가지 모두 발생합니다

`Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0
dir: 
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0
valid: False
done: True
range: None
range_p: None
single: False
time: 1609661406.2614777 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke
https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke
no imgs
stop
Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\gelbooru_downloader", line 61, in read
File "extractor\gelbooru_downloader", line 173, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0 (3.0s)
`

`Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke
dir: 
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke
valid: False
done: True
range: None
range_p: None
single: False
time: 1609661617.397554 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Not Implemented
stop
Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\gelbooru_downloader", line 61, in read
File "extractor\gelbooru_downloader", line 122, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke (0.4s)
`

**Comment by nikin78** [comment]
저도 동일한 사유로 gelbooru 이미지 다운로드가 막혔습니다
로그인 쿠키를 넣었을 때와 안 넣었을 때 무관하게 동일하게 발생하는 문제입니다
태그 검색 후 다운로드 및 단일 이미지 다운로드의 경우 두 가지 모두 발생합니다

`Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0
dir:
zip:
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0
valid: False
done: True
range: None
range_p: None
single: False
time: 1609661406.2614777 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke
https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke
no imgs
stop
Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\gelbooru_downloader", line 61, in read
File "extractor\gelbooru_downloader", line 173, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0 (3.0s)
`

`Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke
dir:
zip:
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke
valid: False
done: True
range: None
range_p: None
single: False
time: 1609661617.397554 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Not Implemented
stop
Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\gelbooru_downloader", line 61, in read
File "extractor\gelbooru_downloader", line 122, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke (0.4s)
`

**Comment by doublehenry57** [comment]
저도 동일한 사유로 gelbooru 이미지 다운로드가 막혔습니다
로그인 쿠키를 넣었을 때와 안 넣었을 때 무관하게 동일하게 발생하는 문제입니다
태그 검색 후 다운로드 및 단일 이미지 다운로드의 경우 두 가지 모두 발생합니다

`Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0
dir:
zip:
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0
valid: False
done: True
range: None
range_p: None
single: False
time: 1609661406.2614777 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke
https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke
no imgs
stop
Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\gelbooru_downloader", line 61, in read
File "extractor\gelbooru_downloader", line 173, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=takato_kurosuke&pid=0 (3.0s)
`

`Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke
dir:
zip:
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke
valid: False
done: True
range: None
range_p: None
single: False
time: 1609661617.397554 (Jan 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Not Implemented
stop
Traceback (most recent call last):
File "utils", line 1034, in start
File "utils", line 1075, in start_
File "extractor\gelbooru_downloader", line 61, in read
File "extractor\gelbooru_downloader", line 122, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=view&id=5786300&tags=takato_kurosuke (0.4s)
`

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by doublehenry57** [comment]
3.2c 버전에선 여전히 안 됐는데, 제공해주신 테스트 버전으로는 gelbooru 다운로드 문제 없이 잘 됩니다
감사합니다

**Comment by fjscl4869** [comment]
정상작동 확인했습니당. 감사드립니다!
