### ISSUE TITLE
마나토끼가 다운이 안 되네요

### ISSUE THREAD

**Issue by mudvayne2** [KurtBestor/Hitomi-Downloader#2929]
마나모아에서 마나토끼로 옮긴 이후로 버전이 업데이트되도 그동안 저는 한번도 다운이 안 됩니다 ㅠㅠ

Invalid: [manatoki] https://manatoki92.net/comic/790247

version: 3.2c (21-01-04 14:05:49 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki92.net/comic/790247
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki92.net/comic/790247
valid: False
done: True
range: None
range_p: None
single: False
time: 1609817903.7987866 (Jan 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.03

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 1061, in start
File "<decorator-gen-86>", line 2, in init
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\manatoki_downloader", line 37, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 64, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki92.net/comic/790247 (200.6s)

**Comment by mudvayne2** [comment]
아래 오류는 hitomi_downloader_GUI.exe --safemode로 실행했을때 오류입니다

Invalid: [manatoki] https://manatoki92.net/comic/6423888

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki92.net/comic/6423888
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki92.net/comic/6423888
valid: False
done: True
range: None
range_p: None
single: False
time: 1610308285.238173 (Jan 11)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 1051, in start
File "<decorator-gen-86>", line 2, in init
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\manatoki_downloader", line 37, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 64, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki92.net/comic/6423888 (201.9s)
