### ISSUE TITLE
서쳐 디폴트 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by LewisKris** [KurtBestor/Hitomi-Downloader#2951]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2629, in dataDownload
  File "hitomi_searcher", line 340, in download_json
  File "tags", line 67, in finish
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Windows 10\\Desktop\\hitomi\\hitomi_data\\tags.txt'

잘되다가 며칠전부터 안되는군요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2843
