### ISSUE TITLE
Problem downloading from Gelbooru

### ISSUE THREAD

**Issue by LailaYom** [KurtBestor/Hitomi-Downloader#2955]
First of all, here is a pic showing I have the latest version.
![Hitomi_-_Version](https://user-images.githubusercontent.com/77240476/104128731-e6970980-5371-11eb-8c4d-dc8cd3ff98ec.PNG)

I have a problem when I try to download from Gelbooru.
Usually when I try, I just click on a tag on the site, copy the url and paste it to HitomiDownloader.
When I try to do it now, I get an error.

Here is a Gelbooru link for example. 
https://gelbooru.com/index.php?page=post&s=list&tags=sakimichan

![Hitomi_-_Link](https://user-images.githubusercontent.com/77240476/104128709-d2eba300-5371-11eb-910e-8191f09648e5.PNG)

When I try to download this link. I get this error:
![Hitomi_-_Fail](https://user-images.githubusercontent.com/77240476/104128752-fe6e8d80-5371-11eb-9641-e01da8e6c191.PNG)
![Hitomi_-_Error](https://user-images.githubusercontent.com/77240476/104128755-02021480-5372-11eb-9a14-97ba3053bd16.PNG)

If there is anything else that you need that I didn't post, please tell me.

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/2924

**Comment by kkk2579** [comment]
겔부루가 어제부턴가 다운이 되질 않습니다
혹시 다른 사이트처럼 쿠키라도 불러오면 될까 시도해봤는데도 먹통이네요
원인이 뭔지 모르겠습니다


Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=list&tags=yutou75

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 03c708dd16e748f4b0948c1d4d3b5a44
input: https://gelbooru.com/index.php?page=post&s=list&tags=yutou75
type: gelbooru
single: False
url: https://gelbooru.com/index.php?page=post&s=list&tags=yutou75
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1653527597.1030626 (22-05-26 01:13:17 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
user_id: 1006606
https://gelbooru.com/index.php?page=post&s=list&tags=yutou75
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 410, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\gelbooru_downloader", line 61, in read
 File "extractor\gelbooru_downloader", line 147, in get_imgs
 File "downloader", line 437, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 211, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=yutou75  (3.1s)
