### ISSUE TITLE
티스토리 다운이 되지 않는 것이 있습니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2963]
안녕하세요, KurtBestor 선생님.

티스토리 다운로드 관련 문제들을 해결해 주셔서 감사합니다.

티스토리에서 다운로드 되지 않는 것들이 있습니다.

www.sunmism.com

은 티스토리 블로그인데 주소에 tistory가 들어가지 않아 

올려주셨던 티스토리 스크립트에서 tistory부분만 sunmism으로 바꿔서 

적용했더니 https://www.sunmism.com/3400 같이 다운로드가 되는 것도 있고

Invalid: [sunmism] https://www.sunmism.com/3

version: 3.2c (21-01-10 15:35:09 UTC)
platform: Windows-10-10.0.19041-SP0
order: 997
group: False
input: https://www.sunmism.com/3
dir: 
zip: 
type: sunmism
artist: None
url: https://www.sunmism.com/3
valid: False
done: True
range: None
range_p: None
single: False
time: 1610399180.2166579 (Jan 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1074, in start
File "utils", line 1116, in start_
File "dynamic_module_0", line 22, in read
File "dynamic_module_0", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://www.sunmism.com/3 (1.2s)

no views
stop
Traceback (most recent call last):
File "utils", line 1074, in start
File "utils", line 1116, in start_
File "dynamic_module_1", line 22, in read
File "dynamic_module_1", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://www.sunmism.com/3 (1.3s)

===================================================================================

Invalid: [sunmism] https://www.sunmism.com/4

version: 3.2c (21-01-10 15:35:09 UTC)
platform: Windows-10-10.0.19041-SP0
order: 996
group: False
input: https://www.sunmism.com/4
dir: 
zip: 
type: sunmism
artist: None
url: https://www.sunmism.com/4
valid: False
done: True
range: None
range_p: None
single: False
time: 1610399180.2705133 (Jan 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1074, in start
File "utils", line 1116, in start_
File "dynamic_module_0", line 22, in read
File "dynamic_module_0", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://www.sunmism.com/4 (1.4s)

no views
stop
Traceback (most recent call last):
File "utils", line 1074, in start
File "utils", line 1116, in start_
File "dynamic_module_1", line 22, in read
File "dynamic_module_1", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://www.sunmism.com/4 (1.3s)

===================================================================================

Invalid: [sunmism] https://www.sunmism.com/42

version: 3.2c (21-01-10 15:35:09 UTC)
platform: Windows-10-10.0.19041-SP0
order: 958
group: False
input: https://www.sunmism.com/42
dir: 
zip: 
type: sunmism
artist: None
url: https://www.sunmism.com/42
valid: False
done: True
range: None
range_p: None
single: False
time: 1610399182.3482451 (Jan 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1074, in start
File "utils", line 1116, in start_
File "dynamic_module_0", line 22, in read
File "dynamic_module_0", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://www.sunmism.com/42 (1.1s)

no views
stop
Traceback (most recent call last):
File "utils", line 1074, in start
File "utils", line 1116, in start_
File "dynamic_module_1", line 22, in read
File "dynamic_module_1", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://www.sunmism.com/42 (1.1s)

같이 다운로드가 진행되지 않는 것도 있습니다.
===================================================================================
https://www.sunmism.com/2764, https://www.sunmism.com/2776, https://www.sunmism.com/2778, https://www.sunmism.com/2788, https://www.sunmism.com/2791, https://www.sunmism.com/2797, https://www.sunmism.com/2804, https://www.sunmism.com/2806, https://www.sunmism.com/2807, https://www.sunmism.com/2819, https://www.sunmism.com/2837, https://www.sunmism.com/2844, https://www.sunmism.com/2845, https://www.sunmism.com/2846, https://www.sunmism.com/2847, https://www.sunmism.com/2858, https://www.sunmism.com/2863, https://www.sunmism.com/2864, https://www.sunmism.com/2875, https://www.sunmism.com/2883, https://www.sunmism.com/2886, https://www.sunmism.com/2890, https://www.sunmism.com/2906, https://www.sunmism.com/2908, https://www.sunmism.com/2909, https://www.sunmism.com/2919, https://www.sunmism.com/2920, https://www.sunmism.com/2921, https://www.sunmism.com/2923, https://www.sunmism.com/2925, https://www.sunmism.com/2931, https://www.sunmism.com/2932, https://www.sunmism.com/2933, https://www.sunmism.com/2934, https://www.sunmism.com/2935, https://www.sunmism.com/2936, https://www.sunmism.com/2937, https://www.sunmism.com/2938, https://www.sunmism.com/2939, https://www.sunmism.com/2940, https://www.sunmism.com/2948, https://www.sunmism.com/2955, https://www.sunmism.com/2956, https://www.sunmism.com/2959, https://www.sunmism.com/2961, https://www.sunmism.com/2962, https://www.sunmism.com/2963, https://www.sunmism.com/2965, https://www.sunmism.com/2966, https://www.sunmism.com/2968, https://www.sunmism.com/2969, https://www.sunmism.com/2970, https://www.sunmism.com/2971, https://www.sunmism.com/2973, https://www.sunmism.com/2975, https://www.sunmism.com/2980, https://www.sunmism.com/2981, https://www.sunmism.com/2982, https://www.sunmism.com/2983, https://www.sunmism.com/2984, https://www.sunmism.com/2985, https://www.sunmism.com/2986, https://www.sunmism.com/2987, https://www.sunmism.com/2988, https://www.sunmism.com/2989, https://www.sunmism.com/2990, https://www.sunmism.com/2991, https://www.sunmism.com/2992, https://www.sunmism.com/2993, https://www.sunmism.com/2994, https://www.sunmism.com/2995, https://www.sunmism.com/2996, https://www.sunmism.com/2997, https://www.sunmism.com/2998, https://www.sunmism.com/2999, https://www.sunmism.com/3000, https://www.sunmism.com/3001, https://www.sunmism.com/3002, https://www.sunmism.com/3003, https://www.sunmism.com/3004, https://www.sunmism.com/3005, https://www.sunmism.com/3006, https://www.sunmism.com/3007, https://www.sunmism.com/3008, https://www.sunmism.com/3009, https://www.sunmism.com/3010, https://www.sunmism.com/3011, https://www.sunmism.com/3012, https://www.sunmism.com/3013, https://www.sunmism.com/3014, https://www.sunmism.com/3015, https://www.sunmism.com/3016, https://www.sunmism.com/3017, https://www.sunmism.com/3018, https://www.sunmism.com/3019, https://www.sunmism.com/3020, https://www.sunmism.com/3021, https://www.sunmism.com/3022, https://www.sunmism.com/3023, https://www.sunmism.com/3024, https://www.sunmism.com/3025, https://www.sunmism.com/3026, https://www.sunmism.com/3027, https://www.sunmism.com/3028, https://www.sunmism.com/3029, https://www.sunmism.com/3030, https://www.sunmism.com/3031, https://www.sunmism.com/3033, https://www.sunmism.com/3034, https://www.sunmism.com/3036, https://www.sunmism.com/3038, https://www.sunmism.com/3039, https://www.sunmism.com/3040, https://www.sunmism.com/3041, https://www.sunmism.com/3042, https://www.sunmism.com/3043, https://www.sunmism.com/3044, https://www.sunmism.com/3045, https://www.sunmism.com/3046, https://www.sunmism.com/3047, https://www.sunmism.com/3048, https://www.sunmism.com/3049, https://www.sunmism.com/3050, https://www.sunmism.com/3051, https://www.sunmism.com/3052, https://www.sunmism.com/3053, https://www.sunmism.com/3054, https://www.sunmism.com/3056, https://www.sunmism.com/3057, https://www.sunmism.com/3058, https://www.sunmism.com/3059, https://www.sunmism.com/3060, https://www.sunmism.com/3061, https://www.sunmism.com/3062, https://www.sunmism.com/3063, https://www.sunmism.com/3064, https://www.sunmism.com/3065, https://www.sunmism.com/3066, https://www.sunmism.com/3067, https://www.sunmism.com/3068, https://www.sunmism.com/3069, https://www.sunmism.com/3070, https://www.sunmism.com/3071, https://www.sunmism.com/3072, https://www.sunmism.com/3073, https://www.sunmism.com/3074, https://www.sunmism.com/3075, https://www.sunmism.com/3076, https://www.sunmism.com/3077, https://www.sunmism.com/3078, https://www.sunmism.com/3079, https://www.sunmism.com/3080, https://www.sunmism.com/3081, https://www.sunmism.com/3082, https://www.sunmism.com/3083, https://www.sunmism.com/3084, https://www.sunmism.com/3085, https://www.sunmism.com/3086, https://www.sunmism.com/3087, https://www.sunmism.com/3088, https://www.sunmism.com/3089, https://www.sunmism.com/3090, https://www.sunmism.com/3091, https://www.sunmism.com/3092, https://www.sunmism.com/3093, https://www.sunmism.com/3094, https://www.sunmism.com/3095, https://www.sunmism.com/3096, https://www.sunmism.com/3098, https://www.sunmism.com/3099, https://www.sunmism.com/3100, https://www.sunmism.com/3101, https://www.sunmism.com/3102, https://www.sunmism.com/3103, https://www.sunmism.com/3104, https://www.sunmism.com/3105, https://www.sunmism.com/3106, https://www.sunmism.com/3108, https://www.sunmism.com/3109, https://www.sunmism.com/3110, https://www.sunmism.com/3112, https://www.sunmism.com/3113, https://www.sunmism.com/3114, https://www.sunmism.com/3115, https://www.sunmism.com/3116, https://www.sunmism.com/3117, https://www.sunmism.com/3118, https://www.sunmism.com/3119, https://www.sunmism.com/3120, https://www.sunmism.com/3121, https://www.sunmism.com/3122, https://www.sunmism.com/3123, https://www.sunmism.com/3124, https://www.sunmism.com/3125, https://www.sunmism.com/3126, https://www.sunmism.com/3127, https://www.sunmism.com/3128, https://www.sunmism.com/3129, https://www.sunmism.com/3130, https://www.sunmism.com/3131, https://www.sunmism.com/3132, https://www.sunmism.com/3133, https://www.sunmism.com/3134, https://www.sunmism.com/3135, https://www.sunmism.com/3136, https://www.sunmism.com/3137, https://www.sunmism.com/3138, https://www.sunmism.com/3139, https://www.sunmism.com/3141, https://www.sunmism.com/3142, https://www.sunmism.com/3144, https://www.sunmism.com/3145, https://www.sunmism.com/3146, https://www.sunmism.com/3147, https://www.sunmism.com/3148, https://www.sunmism.com/3149, https://www.sunmism.com/3150, https://www.sunmism.com/3151, https://www.sunmism.com/3152, https://www.sunmism.com/3154, https://www.sunmism.com/3155, https://www.sunmism.com/3157, https://www.sunmism.com/3158, https://www.sunmism.com/3159, https://www.sunmism.com/3160, https://www.sunmism.com/3161, https://www.sunmism.com/3162, https://www.sunmism.com/3163, https://www.sunmism.com/3164, https://www.sunmism.com/3165, https://www.sunmism.com/3166, https://www.sunmism.com/3167, https://www.sunmism.com/3168, https://www.sunmism.com/3169, https://www.sunmism.com/3170, https://www.sunmism.com/3171, https://www.sunmism.com/3172, https://www.sunmism.com/3173, https://www.sunmism.com/3175, https://www.sunmism.com/3176, https://www.sunmism.com/3177, https://www.sunmism.com/3178, https://www.sunmism.com/3181, https://www.sunmism.com/3182, https://www.sunmism.com/3183, https://www.sunmism.com/3184, https://www.sunmism.com/3185, https://www.sunmism.com/3187, https://www.sunmism.com/3188, https://www.sunmism.com/3190, https://www.sunmism.com/3191, https://www.sunmism.com/3192, https://www.sunmism.com/3194, https://www.sunmism.com/3198, https://www.sunmism.com/3199, https://www.sunmism.com/3200, https://www.sunmism.com/3201, https://www.sunmism.com/3202, https://www.sunmism.com/3203, https://www.sunmism.com/3205, https://www.sunmism.com/3206, https://www.sunmism.com/3207, https://www.sunmism.com/3208, https://www.sunmism.com/3209, https://www.sunmism.com/3210, https://www.sunmism.com/3212, https://www.sunmism.com/3213, https://www.sunmism.com/3218, https://www.sunmism.com/3223, https://www.sunmism.com/3224, https://www.sunmism.com/3226, https://www.sunmism.com/3227, https://www.sunmism.com/3228, https://www.sunmism.com/3229, https://www.sunmism.com/3230, https://www.sunmism.com/3231, https://www.sunmism.com/3233, https://www.sunmism.com/3235, https://www.sunmism.com/3238, https://www.sunmism.com/3239, https://www.sunmism.com/3240, https://www.sunmism.com/3241, https://www.sunmism.com/3242, https://www.sunmism.com/3243, https://www.sunmism.com/3246, https://www.sunmism.com/3247, https://www.sunmism.com/3248, https://www.sunmism.com/3249, https://www.sunmism.com/3256, https://www.sunmism.com/3257, https://www.sunmism.com/3258, https://www.sunmism.com/3260, https://www.sunmism.com/3261, https://www.sunmism.com/3262, https://www.sunmism.com/3263, https://www.sunmism.com/3264, https://www.sunmism.com/3265, https://www.sunmism.com/3266, https://www.sunmism.com/3267, https://www.sunmism.com/3268, https://www.sunmism.com/3270, https://www.sunmism.com/3271, https://www.sunmism.com/3273, https://www.sunmism.com/3274, https://www.sunmism.com/3275, https://www.sunmism.com/3276, https://www.sunmism.com/3277, https://www.sunmism.com/3279, https://www.sunmism.com/3280, https://www.sunmism.com/3281, https://www.sunmism.com/3282, https://www.sunmism.com/3283, https://www.sunmism.com/3284, https://www.sunmism.com/3285, https://www.sunmism.com/3286, https://www.sunmism.com/3287, https://www.sunmism.com/3288, https://www.sunmism.com/3289, https://www.sunmism.com/3291, https://www.sunmism.com/3292, https://www.sunmism.com/3293, https://www.sunmism.com/3294, https://www.sunmism.com/3295, https://www.sunmism.com/3296, https://www.sunmism.com/3297, https://www.sunmism.com/3298, https://www.sunmism.com/3299, https://www.sunmism.com/3300, https://www.sunmism.com/3301, https://www.sunmism.com/3302, https://www.sunmism.com/3303, https://www.sunmism.com/3305, https://www.sunmism.com/3306, https://www.sunmism.com/3307, https://www.sunmism.com/3308, https://www.sunmism.com/3309, https://www.sunmism.com/3312, https://www.sunmism.com/3313, https://www.sunmism.com/3314, https://www.sunmism.com/3315, https://www.sunmism.com/3316, https://www.sunmism.com/3320, https://www.sunmism.com/3321, https://www.sunmism.com/3322, https://www.sunmism.com/3323, https://www.sunmism.com/3324, https://www.sunmism.com/3325, https://www.sunmism.com/3326, https://www.sunmism.com/3327, https://www.sunmism.com/3328, https://www.sunmism.com/3329, https://www.sunmism.com/3330, https://www.sunmism.com/3336, https://www.sunmism.com/3339, https://www.sunmism.com/3340, https://www.sunmism.com/3341, https://www.sunmism.com/3342, https://www.sunmism.com/3343, https://www.sunmism.com/3344, https://www.sunmism.com/3345, https://www.sunmism.com/3346, https://www.sunmism.com/3347, https://www.sunmism.com/3348, https://www.sunmism.com/3349, https://www.sunmism.com/3350, https://www.sunmism.com/3351, https://www.sunmism.com/3352, https://www.sunmism.com/3353, https://www.sunmism.com/3355, https://www.sunmism.com/3356, https://www.sunmism.com/3357, https://www.sunmism.com/3358, https://www.sunmism.com/3359, https://www.sunmism.com/3361, https://www.sunmism.com/3362, https://www.sunmism.com/3363, https://www.sunmism.com/3364, https://www.sunmism.com/3365, https://www.sunmism.com/3366, https://www.sunmism.com/3367, https://www.sunmism.com/3369, https://www.sunmism.com/3370, https://www.sunmism.com/3371, https://www.sunmism.com/3372, https://www.sunmism.com/3375, https://www.sunmism.com/3376, https://www.sunmism.com/3377, https://www.sunmism.com/3378, https://www.sunmism.com/3379, https://www.sunmism.com/3380, https://www.sunmism.com/3381, https://www.sunmism.com/3382, https://www.sunmism.com/3383, https://www.sunmism.com/3384, https://www.sunmism.com/3385, https://www.sunmism.com/3386, https://www.sunmism.com/3387, https://www.sunmism.com/3388, https://www.sunmism.com/3389, https://www.sunmism.com/3390, https://www.sunmism.com/3392, https://www.sunmism.com/3393, https://www.sunmism.com/3394, https://www.sunmism.com/3395, https://www.sunmism.com/3396, https://www.sunmism.com/3397, https://www.sunmism.com/3398, https://www.sunmism.com/3399, https://www.sunmism.com/3400, https://www.sunmism.com/3401, https://www.sunmism.com/3402, https://www.sunmism.com/3403, https://www.sunmism.com/3404, https://www.sunmism.com/3405, https://www.sunmism.com/3406, https://www.sunmism.com/3407, https://www.sunmism.com/3408, https://www.sunmism.com/3409, https://www.sunmism.com/3410, https://www.sunmism.com/3411, https://www.sunmism.com/3412, https://www.sunmism.com/3413, https://www.sunmism.com/3414, https://www.sunmism.com/3416, https://www.sunmism.com/3418, https://www.sunmism.com/3420, https://www.sunmism.com/3421, https://www.sunmism.com/3422, https://www.sunmism.com/3423, https://www.sunmism.com/3424, https://www.sunmism.com/3425, https://www.sunmism.com/3427, https://www.sunmism.com/3428, https://www.sunmism.com/3430, https://www.sunmism.com/3431, https://www.sunmism.com/3432, https://www.sunmism.com/3433, https://www.sunmism.com/3434, https://www.sunmism.com/3435, https://www.sunmism.com/3436, https://www.sunmism.com/3437, https://www.sunmism.com/3438, https://www.sunmism.com/3439
정도만 다운로드 되고 나머지 https://www.sunmism.com/1~2760 정도는 다운로드 되지 않습니다. 

여담이지만 네이버 블로그에 150525부터 하루에 한 장을 거의 매일 올리신 것을 보고

시간을 제대로 쓰고 있지 못 하는 저 스스로가 너무 부끄럽게 느껴졌습니다.

이런 생각을 한 게 작년 9월 말 정도였는데, 전보다는 조금 나아졌지만 여전히 저는 무언가를 

매일같이 꾸준히 하고 있지는 않더군요. 그래도 KurtBestor님의 그림들을 볼 때 마다 '아, 나도 저런 사람이 되고 싶다' 라는

생각과 함께 스스로를 움직이게 됩니다.

다운로더의 이슈와 상관없는 이야기를 드려 죄송합니다.

제 삶에 긍정적 변화를 가져다 주셔서 감사의 인사를 드리고 싶었습니다.

개인적으로는 최근에 올리신 것 중 201117의 우산을 들고 있는 그림이 좋았습니다.

다운로더 잘 쓰고 있습니다. 

바쁘신 와중에도 항상 피드백 해 주셔서 감사합니다. 

모든 일이 뜻대로 이루어지기를 기원합니다.

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 넣어주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

이 주소로 접속하면 스크립트 수정하지 않아도 인식 돼요: https://sunmism.tistory.com

그림 요새 너무 안 그리고있는데 좀 부끄럽네요.. 덕분에 힘 얻고 가요! 나중에 더 좋은 그림 그리게 되도록 힘낼게요

**Comment by yuchan39** [comment]
스크립트 정상작동 확인했습니다.

글 재주는 없지만 제가 느낀 것을 미숙하게나마 표현함으로써 

KurtBestor님이 힘을 얻으셨다니 무척 기쁩니다.

감사합니다.
