### ISSUE TITLE
[핀터레스트] 일정갯수 이상의 핀게시판 다운불가 문제

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2967]
몇개부터 안되는지는 모르겠으나 핀이 약 3만개정도 되는 게시판이 안되는 것으로 보아서는 특정갯수부터 안되는것 같습니다!

테스트 시도했던 것은 47,386개 였어요.

테스트 핀게시판 : https://www.pinterest.co.kr/dlwhdgns/%EA%B7%B8%EB%A6%BC%EC%9E%90%EB%A3%8C/

로그 남겨드립니다.

-------------------------------------------------------------------------------------------------------------------

Invalid: [pinter] https://www.pinterest.co.kr/dlwhdgns/%EA%B7%B8%EB%A6%BC%EC%9E%90%EB%A3%8C/

version: 3.2c (20-12-29 08:02:33 UTC)
platform: Windows-10-10.0.19041-SP0
order: 38
group: False
input: https://www.pinterest.co.kr/dlwhdgns/%EA%B7%B8%EB%A6%BC%EC%9E%90%EB%A3%8C/
dir: 
zip: 
type: pinter
artist: None
url: https://www.pinterest.co.kr/dlwhdgns/%EA%B7%B8%EB%A6%BC%EC%9E%90%EB%A3%8C/
valid: False
done: True
range: ~4000
range_p: None
single: False
time: 1610279439.9665105 (Jan 10)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
type: board
API request failed: 504
stop
Traceback (most recent call last):
File "utils", line 1072, in start
File "utils", line 1116, in start_
File "extractor\pinter_downloader", line 76, in read
File "<decorator-gen-59>", line 2, in get_imgs
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\pinter_downloader", line 186, in get_imgs
File "extractor\pinter_downloader", line 147, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\pinter_downloader", line 143, in _call
Exception: API request failed: 504

Invalid: fail=True
EOT: https://www.pinterest.co.kr/dlwhdgns/%EA%B7%B8%EB%A6%BC%EC%9E%90%EB%A3%8C/ (23152.3s)

type: board
API request failed: 504
stop
Traceback (most recent call last):
File "utils", line 1072, in start
File "utils", line 1116, in start_
File "extractor\pinter_downloader", line 76, in read
File "<decorator-gen-59>", line 2, in get_imgs
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\pinter_downloader", line 186, in get_imgs
File "extractor\pinter_downloader", line 147, in _pagination
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\pinter_downloader", line 143, in _call
Exception: API request failed: 504

Invalid: fail=True
EOT: https://www.pinterest.co.kr/dlwhdgns/%EA%B7%B8%EB%A6%BC%EC%9E%90%EB%A3%8C/ (7949.3s)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/104486648-62fa4880-560f-11eb-923e-1468d49fd5f4.png)

재현할 수가 없네요

다시 시도해도 안 되면 알려주세요

**Comment by tdi2020** [comment]
앗 페이지 지정 다운로드 기본값이 낮기 때문이었습니다 선생님 
높여서 다운하니 해결되었습니다ㅠㅠ 감사합니다!
