### ISSUE TITLE
주소창에 한글이 포함되면 다운되지 않습니다.

### ISSUE THREAD

**Issue by waffleplain** [KurtBestor/Hitomi-Downloader#2969]
주소창이
https://diary-secret.tistory.com/category/우주소녀

라고 되어있어서 복사하고 다운로더에 붙여넣으면

https://diary-secret.tistory.com/category/%EC%9A%B0%EC%A3%BC%EC%86%8C%EB%85%80

와 같은 형태로 붙여넣기가 되어

정상적인 다운로드가 불가합니다.

고칠 방법이 있을까요?

**Comment by KurtBestor** [comment]
두 주소 모두 올바른 주소예요

**Comment by waffleplain** [comment]
Invalid: [tistory] https://diary-secret.tistory.com/category/%EC%9A%B0%EC%A3%BC%EC%86%8C%EB%85%80

version: 3.2d (21-01-16 02:30:20 UTC)
platform: Windows-10-10.0.17134-SP0
order: 0
group: False
input: https://diary-secret.tistory.com/category/%EC%9A%B0%EC%A3%BC%EC%86%8C%EB%85%80
dir: 
zip: 
type: tistory
artist: None
url: https://diary-secret.tistory.com/category/%EC%9A%B0%EC%A3%BC%EC%86%8C%EB%85%80
valid: False
done: True
range: None
range_p: None
single: False
time: 1610853682.148714 (Jan 17)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.16


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 22, in read
File "dynamic_module_0", line 56, in get_info
Exception: no views

Invalid: fail=True
EOT: https://diary-secret.tistory.com/category/%EC%9A%B0%EC%A3%BC%EC%86%8C%EB%85%80 (1.1s)

와 같은 형식으로 Invalid 가 떠버립니다...
