### ISSUE TITLE
티스토리 다운로드가 안됩니다

### ISSUE THREAD

**Issue by gingerman98** [KurtBestor/Hitomi-Downloader#2976]
Invalid: [tistory] https://ehasd6.tistory.com/152

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://ehasd6.tistory.com/152
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/152
valid: False
done: True
range: None
range_p: None
single: False
time: 1610687013.3890908 (Jan 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no view
stop
Traceback (most recent call last):
File "utils", line 1065, in start
File "utils", line 1109, in start_
File "dynamic_module_1", line 20, in read
File "dynamic_module_1", line 46, in get_info
Exception: no view

Invalid: fail=True
EOT: https://ehasd6.tistory.com/152 (0.6s)

이유를 알 수 있을까요? ㅠㅠ

**Comment by yuchan39** [comment]
Invalid: [tistory] https://ehasd6.tistory.com/3511

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://ehasd6.tistory.com/3511
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/3511
valid: False
done: True
range: None
range_p: None
single: False
time: 1610593263.034876 (Jan 14)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3511 (1.0s)

no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3511 (2.2s)

===================================================================================
Invalid: [tistory] https://ehasd6.tistory.com/3498

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 13
group: False
input: https://ehasd6.tistory.com/3498
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/3498
valid: False
done: True
range: None
range_p: None
single: False
time: 1610584748.868684 (Jan 14)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3498 (1.2s)
===================================================================================
Invalid: [tistory] https://ehasd6.tistory.com/1044

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 2467
group: False
input: https://ehasd6.tistory.com/1044
dir: 
zip: 
type: tistory
artist: None
url: https://ehasd6.tistory.com/1044
valid: False
done: True
range: None
range_p: None
single: False
time: 1610584433.007516 (Jan 14)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1044 (1.0s)
===================================================================================

Invalid: [tistory] https://translation-comics.tistory.com/124

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 320
group: False
input: https://translation-comics.tistory.com/124
dir: 
zip: 
type: tistory
artist: None
url: https://translation-comics.tistory.com/124
valid: False
done: True
range: None
range_p: None
single: False
time: 1610642474.7393684 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://translation-comics.tistory.com/124 (1.0s)
===================================================================================
Invalid: [tistory] https://translation-comics.tistory.com/125

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 319
group: False
input: https://translation-comics.tistory.com/125
dir: 
zip: 
type: tistory
artist: None
url: https://translation-comics.tistory.com/125
valid: False
done: True
range: None
range_p: None
single: False
time: 1610642474.7643023 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://translation-comics.tistory.com/125 (1.0s)
===================================================================================
Invalid: [tistory] https://megatonjang.tistory.com/623

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 197
group: False
input: https://megatonjang.tistory.com/623
dir: 
zip: 
type: tistory
artist: None
url: https://megatonjang.tistory.com/623
valid: False
done: True
range: None
range_p: None
single: False
time: 1610654317.0087595 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://megatonjang.tistory.com/623 (0.9s)
===================================================================================
Invalid: [tistory] https://megatonjang.tistory.com/608

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 212
group: False
input: https://megatonjang.tistory.com/608
dir: 
zip: 
type: tistory
artist: None
url: https://megatonjang.tistory.com/608
valid: False
done: True
range: None
range_p: None
single: False
time: 1610654316.4163446 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://megatonjang.tistory.com/608 (1.0s)
===================================================================================
Invalid: [tistory] https://kkk5701.tistory.com/137

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 933
group: False
input: https://kkk5701.tistory.com/137
dir: 
zip: 
type: tistory
artist: None
url: https://kkk5701.tistory.com/137
valid: False
done: True
range: None
range_p: None
single: False
time: 1610657027.8684578 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://kkk5701.tistory.com/137 (1.0s)
===================================================================================
Invalid: [tistory] https://yesbungalow.tistory.com/14

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 158
group: False
input: https://yesbungalow.tistory.com/14
dir: 
zip: 
type: tistory
artist: None
url: https://yesbungalow.tistory.com/14
valid: False
done: True
range: None
range_p: None
single: False
time: 1610655156.2173643 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://yesbungalow.tistory.com/14 (1.1s)
===================================================================================
Invalid: [tistory] https://yesbungalow.tistory.com/16

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 156
group: False
input: https://yesbungalow.tistory.com/16
dir: 
zip: 
type: tistory
artist: None
url: https://yesbungalow.tistory.com/16
valid: False
done: True
range: None
range_p: None
single: False
time: 1610655257.5116358 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://yesbungalow.tistory.com/16 (0.9s)

no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://yesbungalow.tistory.com/16 (0.9s)
===================================================================================

Invalid: [tistory] https://lllidan.tistory.com/4

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 39
group: False
input: https://lllidan.tistory.com/4
dir: 
zip: 
type: tistory
artist: None
url: https://lllidan.tistory.com/4
valid: False
done: True
range: None
range_p: None
single: False
time: 1610659531.3228061 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://lllidan.tistory.com/4 (2.2s)
===================================================================================
Invalid: [tistory] https://lllidan.tistory.com/15

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 28
group: False
input: https://lllidan.tistory.com/15
dir: 
zip: 
type: tistory
artist: None
url: https://lllidan.tistory.com/15
valid: False
done: True
range: None
range_p: None
single: False
time: 1610659531.7956867 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://lllidan.tistory.com/15 (8.5s)
===================================================================================

Invalid: [tistory] https://buchang12.tistory.com/681

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://buchang12.tistory.com/681
dir: 
zip: 
type: tistory
artist: None
url: https://buchang12.tistory.com/681
valid: False
done: True
range: None
range_p: None
single: False
time: 1610693375.8285463 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://buchang12.tistory.com/681 (0.8s)
===================================================================================

Invalid: [tistory] https://buchang12.tistory.com/667

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 14
group: False
input: https://buchang12.tistory.com/667
dir: 
zip: 
type: tistory
artist: None
url: https://buchang12.tistory.com/667
valid: False
done: True
range: None
range_p: None
single: False
time: 1610693375.353777 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08


[Gallery]
None


[File Names]



[URLs]



[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://buchang12.tistory.com/667 (0.9s)
===================================================================================

같이 다운로드가 되지 않는 것들이 있습니다.

번거롭게 해드려 죄송합니다.

바쁘신 와중에도 항상 피드백 해주셔서 감사합니다.

**Comment by gingerman98** [comment]
아닙니다 좋은 프로그렘 만들어주셔서 감사해요

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 넣어주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
