### ISSUE TITLE
티스토리 중 다운로드가 되지 않는 것이 있습니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2980]
안녕하세요, 선생님.

다운로더 잘 쓰고 있습니다.

티스토리 다운로드가 되지 않는 것들이 있습니다.

원래 #2976 에 같이 올렸었는데 해당 이슈 작성자를 헷갈리게 한 것 같아 새로운 이슈로 올립니다.

https://github.com/KurtBestor/Hitomi-Downloader/issues/2976#issuecomment-760781699
와 동일한 내용입니다.

Invalid: [tistory] https://ehasd6.tistory.com/3511

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://ehasd6.tistory.com/3511
dir:
zip:
type: tistory
artist: None
url: https://ehasd6.tistory.com/3511
valid: False
done: True
range: None
range_p: None
single: False
time: 1610593263.034876 (Jan 14)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3511 (1.0s)

no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3511 (2.2s)

===================================================================================
Invalid: [tistory] https://ehasd6.tistory.com/3498

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 13
group: False
input: https://ehasd6.tistory.com/3498
dir:
zip:
type: tistory
artist: None
url: https://ehasd6.tistory.com/3498
valid: False
done: True
range: None
range_p: None
single: False
time: 1610584748.868684 (Jan 14)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3498 (1.2s)
Invalid: [tistory] https://ehasd6.tistory.com/1044

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 2467
group: False
input: https://ehasd6.tistory.com/1044
dir:
zip:
type: tistory
artist: None
url: https://ehasd6.tistory.com/1044
valid: False
done: True
range: None
range_p: None
single: False
time: 1610584433.007516 (Jan 14)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://ehasd6.tistory.com/1044 (1.0s)
Invalid: [tistory] https://translation-comics.tistory.com/124

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 320
group: False
input: https://translation-comics.tistory.com/124
dir:
zip:
type: tistory
artist: None
url: https://translation-comics.tistory.com/124
valid: False
done: True
range: None
range_p: None
single: False
time: 1610642474.7393684 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://translation-comics.tistory.com/124 (1.0s)
Invalid: [tistory] https://translation-comics.tistory.com/125

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 319
group: False
input: https://translation-comics.tistory.com/125
dir:
zip:
type: tistory
artist: None
url: https://translation-comics.tistory.com/125
valid: False
done: True
range: None
range_p: None
single: False
time: 1610642474.7643023 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://translation-comics.tistory.com/125 (1.0s)
Invalid: [tistory] https://megatonjang.tistory.com/623

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 197
group: False
input: https://megatonjang.tistory.com/623
dir:
zip:
type: tistory
artist: None
url: https://megatonjang.tistory.com/623
valid: False
done: True
range: None
range_p: None
single: False
time: 1610654317.0087595 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://megatonjang.tistory.com/623 (0.9s)
Invalid: [tistory] https://megatonjang.tistory.com/608

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 212
group: False
input: https://megatonjang.tistory.com/608
dir:
zip:
type: tistory
artist: None
url: https://megatonjang.tistory.com/608
valid: False
done: True
range: None
range_p: None
single: False
time: 1610654316.4163446 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://megatonjang.tistory.com/608 (1.0s)
Invalid: [tistory] https://kkk5701.tistory.com/137

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 933
group: False
input: https://kkk5701.tistory.com/137
dir:
zip:
type: tistory
artist: None
url: https://kkk5701.tistory.com/137
valid: False
done: True
range: None
range_p: None
single: False
time: 1610657027.8684578 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://kkk5701.tistory.com/137 (1.0s)
Invalid: [tistory] https://kkk5701.tistory.com/134

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 936
group: False
input: https://kkk5701.tistory.com/134
dir:
zip:
type: tistory
artist: None
url: https://kkk5701.tistory.com/134
valid: False
done: True
range: None
range_p: None
single: False
time: 1610657027.7796948 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://kkk5701.tistory.com/134 (0.9s)

===================================================================================
Invalid: [tistory] https://yesbungalow.tistory.com/14

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 158
group: False
input: https://yesbungalow.tistory.com/14
dir:
zip:
type: tistory
artist: None
url: https://yesbungalow.tistory.com/14
valid: False
done: True
range: None
range_p: None
single: False
time: 1610655156.2173643 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://yesbungalow.tistory.com/14 (1.1s)
Invalid: [tistory] https://yesbungalow.tistory.com/16

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 156
group: False
input: https://yesbungalow.tistory.com/16
dir:
zip:
type: tistory
artist: None
url: https://yesbungalow.tistory.com/16
valid: False
done: True
range: None
range_p: None
single: False
time: 1610655257.5116358 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://yesbungalow.tistory.com/16 (0.9s)

no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://yesbungalow.tistory.com/16 (0.9s)
Invalid: [tistory] https://lllidan.tistory.com/4

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 39
group: False
input: https://lllidan.tistory.com/4
dir:
zip:
type: tistory
artist: None
url: https://lllidan.tistory.com/4
valid: False
done: True
range: None
range_p: None
single: False
time: 1610659531.3228061 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://lllidan.tistory.com/4 (2.2s)
Invalid: [tistory] https://lllidan.tistory.com/15

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 28
group: False
input: https://lllidan.tistory.com/15
dir:
zip:
type: tistory
artist: None
url: https://lllidan.tistory.com/15
valid: False
done: True
range: None
range_p: None
single: False
time: 1610659531.7956867 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://lllidan.tistory.com/15 (8.5s)
Invalid: [tistory] https://buchang12.tistory.com/681

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://buchang12.tistory.com/681
dir:
zip:
type: tistory
artist: None
url: https://buchang12.tistory.com/681
valid: False
done: True
range: None
range_p: None
single: False
time: 1610693375.8285463 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://buchang12.tistory.com/681 (0.8s)
Invalid: [tistory] https://buchang12.tistory.com/667

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 14
group: False
input: https://buchang12.tistory.com/667
dir:
zip:
type: tistory
artist: None
url: https://buchang12.tistory.com/667
valid: False
done: True
range: None
range_p: None
single: False
time: 1610693375.353777 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://buchang12.tistory.com/667 (0.9s)
Invalid: [tistory] https://dudtjrdl2009.tistory.com/141

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 7889
group: False
input: https://dudtjrdl2009.tistory.com/141
dir:
zip:
type: tistory
artist: None
url: https://dudtjrdl2009.tistory.com/141
valid: False
done: True
range: None
range_p: None
single: False
time: 1610713882.775256 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://dudtjrdl2009.tistory.com/141 (1.1s)
Invalid: [tistory] https://dudtjrdl2009.tistory.com/144

version: 3.2c (21-01-13 18:45:11 UTC)
platform: Windows-10-10.0.19041-SP0
order: 7886
group: False
input: https://dudtjrdl2009.tistory.com/144
dir:
zip:
type: tistory
artist: None
url: https://dudtjrdl2009.tistory.com/144
valid: False
done: True
range: None
range_p: None
single: False
time: 1610713882.8940816 (Jan 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.08

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 62, in get_info
Exception: no views

Invalid: fail=True
EOT: https://dudtjrdl2009.tistory.com/144 (1.1s)
===================================================================================
같이 다운로드가 되지 않는 것들이 있습니다.

번거롭게 해드려 죄송합니다.

바쁘신 와중에도 항상 피드백 해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2976#issuecomment-761579997

**Comment by yuchan39** [comment]
안녕하세요.

스크립트 수정해 주셔서 감사합니다. 

그런데 스크립트 수정과는 별개로 

https://dudtjrdl2009.tistory.com/8039

https://dudtjrdl2009.tistory.com/7631

의 경우 같이 티스토리 다운로드 중 폴더명이 같게 되어 

내용은 다른데 제목이 같아 다운로드가 되지 않는 것이 있습니다.

이런 경우에는 설정-일반에 있는 폴더명 형식을 어떻게 조정해야 하나요?
