### ISSUE TITLE
VPN 사용중에 히토미 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by Ingyeorism** [KurtBestor/Hitomi-Downloader#2983]
기본 데이터 다운로드 버튼을 누르면

Traceback (most recent call last):
  File "urllib\request", line 1350, in do_open
  File "http\client", line 1277, in request
  File "http\client", line 1323, in _send_request
  File "http\client", line 1272, in endheaders
  File "http\client", line 1032, in _send_output
  File "http\client", line 972, in send
  File "http\client", line 1439, in connect
  File "http\client", line 944, in connect
  File "socket", line 728, in create_connection
  File "socket", line 716, in create_connection
OSError: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 309, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 543, in _open
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 1393, in https_open
  File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connection", line 160, in _new_conn
  File "urllib3\util\connection", line 84, in create_connection
  File "urllib3\util\connection", line 74, in create_connection
OSError: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 309, in connect
  File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001DDF66F2548>: Failed to establish a new connection: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 449, in send
  File "urllib3\connectionpool", line 727, in urlopen
  File "urllib3\util\retry", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kurtbestorthonanywhere.com', port=443): Max retries exceeded with url: /h_data (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DDF66F2548>: Failed to establish a new connection: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 225, in download_json
  File "hitomi_searcher", line 387, in download_json_
  File "downloader", line 336, in read_html
  File "requests\api", line 76, in get
  File "requests\api", line 61, in request
  File "downloader", line 110, in session_request
  File "requests\sessions", line 530, in request
  File "requests\sessions", line 643, in send
  File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kurtbestorthonanywhere.com', port=443): Max retries exceeded with url: /h_data (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DDF66F2548>: Failed to establish a new connection: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다'))

라는 로그가 나오며 실패합니다.

VPN을 끄고, 다운로드 버튼을 누른 후 다시 VPN을 켜도 다운로드가 멈춥니다.

Surfshark VPN 사용중입니다.

유용한 프로그램 만들어주셔서 감사합니다.

**Comment by KurtBestor** [comment]
해당 VPN 에 문의해주세요
