### ISSUE TITLE
인스타그램 쿠키 어떻게 만드나요?

### ISSUE THREAD

**Issue by jy1154** [KurtBestor/Hitomi-Downloader#2993]
인스타그램 자꾸 실패뜨는데...

이슈 검색해보니까 로그인 관련 문제 같더라구요.

그런데 도저히 어떻게 해야 하는지 잘 모르겠습니다...
크롬 브라우저에서는 이미 로그인 되어있거든요.

설정 - 고급 - 쿠키 집어넣기 하려해도 쿠키 파일 자체를 어떻게 만들어야하는지 모르겠어요 ㅠㅠㅠ
초기화 해도 아무런 해결이 안되기도 하구요 ㅠㅠㅠㅠ;;

쿠키 업데이트 하라고만 뜨는데 어떻게 해야하나요???

Login required; Update your cookies
https://www.instagram.com/parkdon1154

version: 3.2d (21-01-16 02:30:20 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.instagram.com/parkdon1154
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/parkdon1154
valid: False
done: True
range: None
range_p: None
single: False
time: 1610980806.6407845 (Jan 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.16

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1061, in start
File "extractor\insta_downloader", line 43, in init
File "extractor\insta_downloader", line 26, in get_session
errors.LoginRequired

Invalid: fail=False
EOT: https://www.instagram.com/parkdon1154 (0.0s)

**Comment by 1367do** [comment]
실행창 보이시나요?

**Comment by helpmepls08** [comment]
크롬 쓰시면 확장프로그램에 겟 쿠키라고 영어로 쓰시면 나옵니다.
https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=ko
이거 들어가서 추가하신다음
인스타 들어가셔서 흰색 여백에 오른쪽 마우스 누르시면 겟쿠키 뜹니다.
누르시면 파일 다운로드 되고요. 그 파일을 쿠키 넣기 에 추가 하시면 됩니다.
