### ISSUE TITLE
Avgle 몇 일 전부터 작동하지 않습니다.

### ISSUE THREAD

**Issue by kellog77** [KurtBestor/Hitomi-Downloader#2998]
개발자님, 안녕하세요?
그동안 잘 사용하고 있던 avgle 이 2021.1.20. 현재 더이상 작동하지 않습니다.
다른 PC 환경은 변한 것이 없습니다. avgle 측에서 뭔가가 변경된 것이 아닌가 싶습니다.
훌륭한 프로그램 만들어 주셔서 감사드리며,  avgle 수정본이 올라오길 기대합니다~

'작업정보' 항목을 살펴보면 다음과 같은 문구가 뜹니다.
-----------------------------------------------------------------------------------
MMKZ-090 可愛い顔してデカ尻！！ 椿りか

version: 3.2d (21-01-19 13:13:17 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://avgle.com/video/zD25Z5cBx5_/mmkz-090-可愛い顔してデカ尻-椿りか
dir: \\mac\WD10TB\_Avgle_Download
zip: 
type: avgle
artist: None
url: https://avgle.com/video/zD25Z5cBx5_/mmkz-090-可愛い顔してデカ尻-椿りか
valid: True
done: False
range: None
range_p: None
single: True
time: 1611118976.242995 (Jan 20)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.16

[Gallery]
None

[File Names]
[0001] \\mac\WD10TB\_Avgle_Download\MMKZ-090 可愛い顔してデカ尻！！ 椿りか.mp4

[URLs]
[0001] LazyUrl(https://avgle.com/video/zD25Z5cBx5_/mmkz-090-可愛い顔してデカ尻-椿りか) ---> M3u8_stream(https://avgle.com/video/zD25Z5cBx5_/mmkz-090-%E5%8F%AF%E6%84%9B%E3%81%84%E9%A1%94%E3%81%97%E3%81%A6%E3%83%87%E3%82%AB%E5%B0%BB-%E6%A4%BF%E3%82%8A%E3%81%8B)

[Messages]
https://r3---sn-hk85l709.qooqlevideo.com/!C0BFE0JcGx0IRQMGW1YKXgYOAR4CAAtPSFgKRlsATl4HUV5NUglZHQpQSAkNKWwCUXFJRwoKMidrfQZvQV12eQ9THRAMSlFcBQgAAlNQCFQACwgGTQgMDFBDWAUYAVlDAgkAVQBXBQBUBgACTRJNB0FdBGkgAVAtaF8gGEUAXlIRUUNeVwlGUQQZH1UUBlUDG1tWXU4WAAdNVgIKAlMJB1oCBVceC1FWCFQMXA4SeElGS10BTlVSVhYCSgUEUgEDUgYDVh8LRAZORlRTT1AUEAQVWAFPEBY=
https://r3---sn-hk85l709.qooqlevideo.com/!C0BFE0JcGx0IRQMGW1YKXgYOAR4CAAtPSFgKRlsATl4HUV5NUglZHQpQSAkNKWwCUXFJRwoKMidrfQZvQV12eQ9THRAMSlFcBQgAAlNQCFQACwgGTQgMDFBDWAUYAVlDAgkAVQBXBQBUBgACTRJNB0FdBGkgAVAtaF8gGEUAXlIRUUNeVwlGUQQZH1UUBlUDG1tWXU4WAAdNVgIKAlMJB1oCBVceC1FWCFQMXA4SeElGS10BTlVSVhYCSgUEUgEDUgYDVh8LRAZORlRTT1MUEAQVWAFPEBY=
https://r3---sn-hk85l709.qooqlevideo.com/!C0BFE0JcGx0IRQMGW1YKXgYOAR4CAAtPSFgKRlsATl4HUV5NUglZHQpQSAkNKWwCUXFJRwoKMidrfQZvQV12eQ9THRAMSlFcBQgAAlNQCFQACwgGTQgMDFBDWAUYAVlDAgkAVQBXBQBUBgACTRJNB0FdBGkgAVAtaF8gGEUAXlIRUUNeVwlGUQQZH1UUBlUDG1tWXU4WAAdNVgIKAlMJB1oCBVceC1FWCFQMXA4SeElGS10BTlVSVhYCSgUEUgEDUgYDVh8LRAZORlRTT1IUEAQVWAFPEBY=
https://r3---sn-hk85l709.qooqlevideo.com/!C0BFE0JcGx0IRQMGW1YKXgYOAR4CAAtPSFgKRlsATl4HUV5NUglZHQpQSAkNKWwCUXFJRwoKMidrfQZvQV12eQ9THRAMSlFcBQgAAlNQCFQACwgGTQgMDFBDWAUYAVlDAgkAVQBXBQBUBgACTRJNB0FdBGkgAVAtaF8gGEUAXlIRUUNeVwlGUQQZH1UUBlUDG1tWXU4WAAdNVgIKAlMJB1oCBVceC1FWCFQMXA4SeElGS10BTlVSVhYCSgUEUgEDUgYDVh8LRAZORlRTT1UUEAQVWAFPEBY=

Fail : https://r3---sn-hk85l709.qooqlevideo.com/!C0BFE0JcGx0IRQMGW1YKXgYOAR4CAAtPSFgKRlsATl4HUV5NUglZHQpQSAkNKWwCUXFJRwoKMidrfQZvQV12eQ9THRAMSlFcBQgAAlNQCFQACwgGTQgMDFBDWAUYAVlDAgkAVQBXBQBUBgACTRJNB0FdBGkgAVAtaF8gGEUAXlIRUUNeVwlGUQQZH1UUBlUDG1tWXU4WAAdNVgIKAlMJB1oCBVceC1FWCFQMXA4SeElGS10BTlVSVhYCSgUEUgEDUgYDVh8LRAZORlRTT1UUEAQVWAFPEBY=
Traceback (most recent call last):
File "downloader", line 933, in download
Exception: HTML: Avgle

Fail : https://r3---sn-hk85l709.qooqlevideo.com/!C0BFE0JcGx0IRQMGW1YKXgYOAR4CAAtPSFgKRlsATl4HUV5NUglZHQpQSAkNKWwCUXFJRwoKMidrfQZvQV12eQ9THRAMSlFcBQgAAlNQCFQACwgGTQgMDFBDWAUYAVlDAgkAVQBXBQBUBgACTRJNB0FdBGkgAVAtaF8gGEUAXlIRUUNeVwlGUQQZH1UUBlUDG1tWXU4WAAdNVgIKAlMJB1oCBVceC1FWCFQMXA4SeElGS10BTlVSVhYCSgUEUgEDUgYDVh8LRAZORlRTT1MUEAQVWAFPEBY=
Traceback (most recent call last):
File "downloader", line 933, in download
Exception: HTML: Avgle

(이하 같은 문구 반복)

------------------------------------------------------------------------------------

**Comment by junsukim0301** [comment]
동일한 증상을 겪고 있습니다. 503 에러가 뜨네요ㅠ

**Comment by wlgus8909** [comment]
기다리면 업데이트가 되는건가요!?

**Comment by KurtBestor** [comment]
확장프로그램 다시 설치해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension

**Comment by jaejunghan** [comment]
확장프로그램 재설치 했는데 아직도 다운이 안됩니다.
