### ISSUE TITLE
도구-검색기-기본데이터다운로드 오류.

### ISSUE THREAD

**Issue by erebuseyny** [KurtBestor/Hitomi-Downloader#3000]
업데이트 이후, 
도구-검색기-기본데이터 다운로드에서
다음과 같은 오류가 발생했습니다.

Traceback (most recent call last):
  File "hitomi_searcher", line 232, in download_json
  File "zipfile", line 1258, in __init__
  File "zipfile", line 1363, in _RealGetContents
  File "C:\Users\kurtb\AppData\Local\Programs\Python\Python37\lib\encodings\__init__", line 100, in search_function
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMIN\\AppData\\Local\\Temp\\_MEI8362\\base_library.zip'

**Comment by KurtBestor** [comment]
백신에서 막는 것 같은데 확인 부탁드려요.

**Comment by KurtBestor** [comment]
백신에서 막는 것 같은데 어떤 백신 쓰시나요?

**Comment by erebuseyny** [comment]
> 백신에서 막는 것 같은데 어떤 백신 쓰시나요?

Kaspersky 씁니다.
백신이 막은 것 맞습니다. 
신뢰하는 어플리케이션으로 예외를 추가하니 정상작동합니다.

Avast는 괜찮았었는데... 최근에 바꿔서 그랬나봅니다.
감사합니다.
