### ISSUE TITLE
AVgle 주황글씨 문의드립니다

### ISSUE THREAD

**Issue by wlgus8909** [KurtBestor/Hitomi-Downloader#3012]
3일전부터 avgle만 주황글씨가 나와서 연락드립니다 

항상 잘쓰고있습니다 혹 업데이트가 언제되는지도 알수있을까요 !?

작업정보는

[HD中文字幕]チ●ポ大好き超即尺おしゃぶりメイド 橋本ありな

version: 3.2d (21-01-21 07:43:17 UTC)
platform: Windows-10-10.0.19041-SP0
uid: aaf64ed46a614b9d8c3716166fcd43d9
order: 0
group: False
input: https://avgle.com/video/Zt_gSgwo4gg/hd中文字幕-チ-ポ大好き超即尺おしゃぶりメイド-橋本ありな
dir: hitomi_downloaded_avgle
zip: 
type: avgle
artist: None
url: https://avgle.com/video/Zt_gSgwo4gg/hd中文字幕-チ-ポ大好き超即尺おしゃぶりメイド-橋本ありな
valid: False
done: True
range: ~2000
range_p: None
single: True
time: 1611483128.941672 (Jan 24)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.16
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_avgle\[HD中文字幕]チ●ポ大好き超即尺おしゃぶりメイド 橋本ありな.mp4

[URLs]
[0001] LazyUrl(https://avgle.com/video/Zt_gSgwo4gg/hd中文字幕-チ-ポ大好き超即尺おしゃぶりメイド-橋本ありな) ---> M3u8_stream(https://avgle.com/video/Zt_gSgwo4gg/hd%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95-%E3%83%81-%E3%83%9D%E5%A4%A7%E5%A5%BD%E3%81%8D%E8%B6%85%E5%8D%B3%E5%B0%BA%E3%81%8A%E3%81%97%E3%82%83%E3%81%B6%E3%82%8A%E3%83%A1%E3%82%A4%E3%83%89-%E6%A9%8B%E6%9C%AC%E3%81%82%E3%82%8A%E3%81%AA)

[Messages]
https://r2---sn-j91ndkqd.qooqlevideo.com/!DEdHSEcMFkpaEgZQAFMODAwJVEhaAgxMF11ZFwhWRFsAVlwWV1lUSlgHTltfCW1NR10CF35VEAtRC0QRIkZVBidEH0sJGlwLV18GUAJUDAEFAVdRFQoLDw9GC1RLV1NGBQ4CDgUHDVwDUwVRHBZMWUFVWD94VyotCUhYSRZWVFcWVkEFUllLBlZOGQdFAlRdG1MKCxYUBwQSU1FbUQUDAl0FBwwbW1wBWgMKDl8WeRcGB0pXDlFNVkkEAlVWCgAGUB1eSAAZSgBUTwZLRVQVWQQeERU=
https://r2---sn-j91ndkqd.qooqlevideo.com/!DEdHSEcMFkpaEgZQAFMODAwJVEhaAgxMF11ZFwhWRFsAVlwWV1lUSlgHTltfCW1NR10CF35VEAtRC0QRIkZVBidEH0sJGlwLV18GUAJUDAEFAVdRFQoLDw9GC1RLV1NGBQ4CDgUHDVwDUwVRHBZMWUFVWD94VyotCUhYSRZWVFcWVkEFUllLBlZOGQdFAlRdG1MKCxYUBwQSU1FbUQUDAl0FBwwbW1wBWgMKDl8WeRcGB0pXDlFNVkkEAlVWCgAGUB1eSAAZSgBUTwVLRVQVWQQeERU=
https://r2---sn-j91ndkqd.qooqlevideo.com/!DEdHSEcMFkpaEgZQAFMODAwJVEhaAgxMF11ZFwhWRFsAVlwWV1lUSlgHTltfCW1NR10CF35VEAtRC0QRIkZVBidEH0sJGlwLV18GUAJUDAEFAVdRFQoLDw9GC1RLV1NGBQ4CDgUHDVwDUwVRHBZMWUFVWD94VyotCUhYSRZWVFcWVkEFUllLBlZOGQdFAlRdG1MKCxYUBwQSU1FbUQUDAl0FBwwbW1wBWgMKDl8WeRcGB0pXDlFNVkkEAlVWCgAGUB1eSAAZSgBUTwRLRVQVWQQeERU=
https://r2---sn-j91ndkqd.qooqlevideo.com/!DEdHSEcMFkpaEgZQAFMODAwJVEhaAgxMF11ZFwhWRFsAVlwWV1lUSlgHTltfCW1NR10CF35VEAtRC0QRIkZVBidEH0sJGlwLV18GUAJUDAEFAVdRFQoLDw9GC1RLV1NGBQ4CDgUHDVwDUwVRHBZMWUFVWD94VyotCUhYSRZWVFcWVkEFUllLBlZOGQdFAlRdG1MKCxYUBwQSU1FbUQUDAl0FBwwbW1wBWgMKDl8WeRcGB0pXDlFNVkkEAlVWCgAGUB1eSAAZSgBUTwNLRVQVWQQeERU=

Fail : https://r2---sn-j91ndkqd.qooqlevideo.com/!DEdHSEcMFkpaEgZQAFMODAwJVEhaAgxMF11ZFwhWRFsAVlwWV1lUSlgHTltfCW1NR10CF35VEAtRC0QRIkZVBidEH0sJGlwLV18GUAJUDAEFAVdRFQoLDw9GC1RLV1NGBQ4CDgUHDVwDUwVRHBZMWUFVWD94VyotCUhYSRZWVFcWVkEFUllLBlZOGQdFAlRdG1MKCxYUBwQSU1FbUQUDAl0FBwwbW1wBWgMKDl8WeRcGB0pXDlFNVkkEAlVWCgAGUB1eSAAZSgBUTwRLRVQVWQQeERU=
Traceback (most recent call last):
File "downloader", line 933, in download
Exception: HTML: Avgle

Fail : https://r2---sn-j91ndkqd.qooqlevideo.com/!DEdHSEcMFkpaEgZQAFMODAwJVEhaAgxMF11ZFwhWRFsAVlwWV1lUSlgHTltfCW1NR10CF35VEAtRC0QRIkZVBidEH0sJGlwLV18GUAJUDAEFAVdRFQoLDw9GC1RLV1NGBQ4CDgUHDVwDUwVRHBZMWUFVWD94VyotCUhYSRZWVFcWVkEFUllLBlZOGQdFAlRdG1MKCxYUBwQSU1FbUQUDAl0FBwwbW1wBWgMKDl8WeRcGB0pXDlFNVkkEAlVWCgAGUB1eSAAZSgBUTwZLRVQVWQQeERU=
Traceback (most recent call last):
File "downloader", line 933, in download
Exception: HTML: Avgle

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2998#issuecomment-785545613
