### ISSUE TITLE
아프리카TV 19세 VOD다운관련 질문

### ISSUE THREAD

**Issue by yesblue12** [KurtBestor/Hitomi-Downloader#3016]
제 아이디로 성인인증을 한 상태인데 다운을 하려하면 invalid라 뜨는데 어떤 방법이 없을까요??

**Comment by yesblue12** [comment]
Invalid: [afreeca] http://vod.afreecatv.com/PLAYER/STATION/67118018

version: 3.2d (21-01-16 02:30:20 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/67118018
dir: 
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/67118018
valid: False
done: True
range: None
range_p: None
single: True
time: 1611521830.4881597 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2021.01.16


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'string'
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "extractor\afreeca_downloader", line 36, in read
File "<decorator-gen-46>", line 2, in get_video
File "constants", line 870, in wrapper
File "constants", line 841, in wrapper
File "extractor\afreeca_downloader", line 69, in get_video
AttributeError: 'NoneType' object has no attribute 'string'

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/67118018 (2.1s)
