### ISSUE TITLE
카카오페이지가 안되네요

### ISSUE THREAD

**Issue by charge24** [KurtBestor/Hitomi-Downloader#3044]
어제만 해도 잘 되었는데 User-Agent 값으르 입력하니까

    Traceback (most recent call last):
      File "console\Console", line 153, in execSingle
      File "<string>", line 1
        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
                              ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "console\Console", line 157, in execSingle
      File "<string>", line 1
        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
                              ^
    SyntaxError: invalid syntax

이렇게 뜨고 결제한 부분은 다운이 안 되고 무료분만 되네요
뭐가 문제인지 도저히 모르겠네요

**Comment by charge24** [comment]
> 어제만 해도 잘 되었는데 User-Agent 값으르 입력하니까
> 
> ```
> Traceback (most recent call last):
>   File "console\Console", line 153, in execSingle
>   File "<string>", line 1
>     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
>                           ^
> SyntaxError: invalid syntax
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "console\Console", line 157, in execSingle
>   File "<string>", line 1
>     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
>                           ^
> SyntaxError: invalid syntax
> ```
> 
> 이렇게 뜨고 결제한 부분은 다운이 안 되고 무료분만 되네요
> 뭐가 문제인지 도저히 모르겠네요
