### ISSUE TITLE
기본 데이터 다운로드가 안됩니다

### ISSUE THREAD

**Issue by fsagyfwrtbwouv** [KurtBestor/Hitomi-Downloader#3049]
데이터를 다운로드 중 실패했습니다 문구가 뜨며 이렇게 표시 되네요
1월에 업데이트하고 1주일 넘어서 하려니까 안됩니다
어떻게 해야 해결될까요

Traceback (most recent call last):
  File "downloader", line 309, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 641, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 225, in download_json
  File "hitomi_searcher", line 387, in download_json_
  File "downloader", line 342, in read_html
  File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://kurtbestorthonanywhere.com/h_data

**Comment by KurtBestor** [comment]
고쳤어요. 이제 잘 될 거예요.
