### ISSUE TITLE
기본 데이터 다운로드가 자꾸 실패합니다

### ISSUE THREAD

**Issue by Kid-Ant** [KurtBestor/Hitomi-Downloader#3050]
Traceback (most recent call last):
  File "downloader", line 309, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 641, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 225, in download_json
  File "hitomi_searcher", line 387, in download_json_
  File "downloader", line 342, in read_html
  File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://kurtbestorthonanywhere.com/h_data

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3049
