### ISSUE TITLE
유튜브 다운이 안됩니다 

### ISSUE THREAD

**Issue by kuro10002** [KurtBestor/Hitomi-Downloader#3052]
Invalid: [youtube] https://youtu.be/HNOX-xrKSfg

version: 3.2d (21-01-16 02:30:20 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://youtu.be/HNOX-xrKSfg
dir: 
zip: 
type: youtube
artist: None
url: https://youtu.be/HNOX-xrKSfg
valid: False
done: True
range: None
range_p: None
single: True
time: 1612412084.8978364 (Feb 4)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
ytdl: 2021.02.04

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][None] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][None] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][None] webm [None / opus] ─ 251 - audio only (tiny)
[None][0fps][None] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[144p][30fps][None] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (144p)
[144p][30fps][None] webm [vp9 / None] ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 [av01.0.00M.08 / None] ─ 394 - 256x144 (144p)
[240p][30fps][None] mp4 [avc1.4d4015 / None] ─ 133 - 426x240 (240p)
[240p][30fps][None] mp4 [av01.0.00M.08 / None] ─ 395 - 426x240 (240p)
[240p][30fps][None] webm [vp9 / None] ─ 242 - 426x240 (240p)
[360p][30fps][None] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[360p][30fps][None] mp4 [av01.0.01M.08 / None] ─ 396 - 640x360 (360p)
[360p][30fps][None] webm [vp9 / None] ─ 243 - 640x360 (360p)
[480p][30fps][None] mp4 [avc1.4d401f / None] ─ 135 - 854x480 (480p)
[480p][30fps][None] mp4 [av01.0.04M.08 / None] ─ 397 - 854x480 (480p)
[480p][30fps][None] webm [vp9 / None] ─ 244 - 854x480 (480p)
[720p][30fps][None] mp4 [avc1.4d401f / None] ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm [vp9 / None] ─ 247 - 1280x720 (720p)
[720p][60fps][None] mp4 [av01.0.08M.08 / None] ─ 398 - 1280x720 (720p60)
[720p][60fps][None] webm [vp9 / None] ─ 302 - 1280x720 (720p60)
[720p][60fps][None] mp4 [avc1.4d4020 / None] ─ 298 - 1280x720 (720p60)
[1080p][60fps][None] mp4 [av01.0.09M.08 / None] ─ 399 - 1920x1080 (1080p60)
[1080p][60fps][None] webm [vp9 / None] ─ 303 - 1920x1080 (1080p60)
[1080p][60fps][None] mp4 [avc1.64002a / None] ─ 299 - 1920x1080 (1080p60)
[360p][30fps][None] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][None] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

# stream_final <ytdl.Video object at 0x000001E5C11E6E08> 399 - 1920x1080 (1080p60) 1080p mp4 None 60fps

No videos
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1117, in start_
File "extractor\youtube_downloader", line 379, in read
Exception: No videos

Invalid: fail=True
EOT: https://youtu.be/HNOX-xrKSfg (2.2s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kuro10002** [comment]
테스트버전 다운 잘됩니다
