### ISSUE TITLE
카카오 페이지 다운 안됌.

### ISSUE THREAD

**Issue by leesangmin1990** [KurtBestor/Hitomi-Downloader#3065]
카카오페이지 로그인상태로 get cookei로 받은 테스트파일을 설정으로 들어와 불로오기 했지만 다운이 안됩니다. 그래서 과거 ctrl+alt+C를 이용한 from extractor import kakaopage_downloader;kakaopage_downloader.UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/***.36 (KHTML, like Gecko) Chrome/**.0.****.*** Safari/***.**' ( 숫자는 "*"처리 ) 하고 들어갔지만

 Traceback (most recent call last):
      File "console\Console", line 153, in execSingle
      File "<string>", line 1
        https://page.kakao.com/home?seriesId=56312600
             ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "console\Console", line 157, in execSingle
      File "<string>", line 1
        https://page.kakao.com/home?seriesId=56312600
               ^
    SyntaxError: invalid syntax
결과만뜨고 결제한 유료부분이 다운이 안돼네요.

**Comment by keroberos-s** [comment]
아직 저는 잘 되는데 차례대로 다시 해보세요 
#2249
