### ISSUE TITLE
티스토리 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#3075]
KurtBestor 님, 안녕하세요.

티스토리 다운로드가 되지 않는 것이 있습니다.

Invalid: [tistory] https://ehasd6.tistory.com/3642

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 5 / False / ebf80351d2e34422a2300f919885bda7
input: https://ehasd6.tistory.com/3642
type: tistory
single: False
url: https://ehasd6.tistory.com/3642
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1612763101.7166073 (Feb 8)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.02.04.1
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3642 (1.2s)

no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3642 (0.9s)

===================================================================================

Invalid: [tistory] https://ehasd6.tistory.com/3636

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 11 / False / 6bce721e3c0c47d6b5be3706e2507723
input: https://ehasd6.tistory.com/3636
type: tistory
single: False
url: https://ehasd6.tistory.com/3636
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1612763101.4243572 (Feb 8)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.02.04.1
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3636 (1.6s)

no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3636 (1.2s)

===================================================================================

Invalid: [tistory] https://ehasd6.tistory.com/3646

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 1720cb17b9d54adeb5b379e72aee1c21
input: https://ehasd6.tistory.com/3646
type: tistory
single: False
url: https://ehasd6.tistory.com/3646
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1612767631.5887794 (Feb 8)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.02.04.1
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3646 (1.0s)

no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3646 (1.1s)

no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_1", line 27, in read
File "dynamic_module_1", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3646 (1.5s)

===================================================================================

Invalid: [tistory] https://ehasd6.tistory.com/3641

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 6 / False / 0e184fe2f77a4487a31bf2d137fe84ca
input: https://ehasd6.tistory.com/3641
type: tistory
single: False
url: https://ehasd6.tistory.com/3641
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1612763101.6766818 (Feb 8)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.02.04.1
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3641 (1.2s)

no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3641 (1.0s)

===================================================================================

혹시 다른 티스토리 블로그도 안 되는 것이 있나 확인해 보았지만

전에 수정해주셨던 티스토리 스크립트를 적용했을 때

#2980 의 다른 티스토리 블로그들은 모두 정상적으로 작동이 되는 것을 확인했습니다.

https://ehasd6.tistory.com

에서만 티스토리 스크립트를 적용하여 다운을 진행하였을 때 오류가 발생하였습니다.

이전에 #2728,#1205 (comment), #2209 (comment) 에서 말씀하셨던 것을 참고하고

파이썬 기본 문법을 https://wikidocs.net/book/2와 다른 자료들을 통해 혼자 공부하고 있지만

메모장으로 스크립트를 열어 보아도 일부만 간신히 이해가 될 뿐 스크립트에 손을 대기에는 아직 너무 멀게만 느껴집니다. 

항상 번거롭게 해 드려 죄송합니다.

다운로더 잘 쓰고 있습니다.

바쁘신 와중에도 피드백 해 주셔서 감사합니다. 

편안한 새해가 되시기를 바랍니다.

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 넣어주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
KurtBestor님, 안녕하세요.

티스토리 스크립트 수정해주셔서 감사합니다.

Invalid: [tistory] https://ehasd6.tistory.com/3642

version: 3.3 (21-02-27 02:25:08 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 4cc670c7bcf8466f960758b0307bb1b1
input: https://ehasd6.tistory.com/3642
type: tistory
single: False
url: https://ehasd6.tistory.com/3642
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614436407.398423 (Feb 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3642 (3.0s)
===================================================================================
Invalid: [tistory] https://ehasd6.tistory.com/3642#gsc.tab=0

version: 3.3 (21-02-27 02:25:08 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 88be181f64054388abceddc63a114a16
input: https://ehasd6.tistory.com/3642#gsc.tab=0
type: tistory
single: False
url: https://ehasd6.tistory.com/3642#gsc.tab=0
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614436392.0811644 (Feb 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3642#gsc.tab=0 (1.1s)
===================================================================================
Invalid: [tistory] https://ehasd6.tistory.com/3641

version: 3.3 (21-02-27 02:25:08 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 94585a5c747a48aa899aefbf34f65d70
input: https://ehasd6.tistory.com/3641
type: tistory
single: False
url: https://ehasd6.tistory.com/3641
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614436673.9014 (Feb 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "dynamic_module_1", line 27, in read
File "dynamic_module_1", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3641 (2.2s)

===================================================================================
Invalid: [tistory] https://ehasd6.tistory.com/3641#gsc.tab=0

version: 3.3 (21-02-27 02:25:08 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 8007366a3bc54eadadca68b424802718
input: https://ehasd6.tistory.com/3641#gsc.tab=0
type: tistory
single: False
url: https://ehasd6.tistory.com/3641#gsc.tab=0
dir: 
zip: 
artist: None
valid / done: False / False
range / range_p: None / None
time: 1614436640.8685398 (Feb 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "dynamic_module_1", line 27, in read
File "dynamic_module_1", line 95, in get_info
Exception: no imgs

Invalid: fail=True
===================================================================================

와 같이 다운로드가 되지 않습니다.

번거롭게 해 드려 죄송합니다.

감사합니다.
