### ISSUE TITLE
마토다운이 오류가 나옵니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#3091]
[쿠보켄] 이세계 식멸의 상어

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 2 / False / 3e19b0ba36884c54a03107754c626471
input: https://manatoki95.net/comic/6776610
type: manatoki
single: False
url: https://manatoki95.net/comic/5819034
dir: hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어
zip: 
artist: 쿠보켄
valid / done: True / True
range / range_p: None / [8]
time: 1612975278.2428994 (Feb 11)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.04.1
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0000.jpg
[0002] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0001.jpg
[0003] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0002.jpg
[0004] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0003.jpg
[0005] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0004.jpg
[0006] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0005.jpg
[0007] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0006.jpg
[0008] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0007.jpg
[0009] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0008.jpg
[0010] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0009.jpg
[0011] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0010.jpg
[0012] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0011.jpg
[0013] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0012.jpg
[0014] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0013.jpg
[0015] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0014.jpg
[0016] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0015.jpg
[0017] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0016.jpg
[0018] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0017.jpg
[0019] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0018.jpg
[0020] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0019.jpg
[0021] hitomi_downloaded_manatoki\[쿠보켄] 이세계 식멸의 상어\이세계 식멸의 상어 5-2화\0020.jpg

[URLs]
[0001] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/LHNgy9d3ouRi.jpg
[0002] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/_GdRbqJ0Y9K5.jpg
[0003] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/7YRZhjrz_STN.jpg
[0004] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/5TYgcoz3Z80V.jpg
[0005] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/IHZyM9pLtur6.jpg
[0006] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/_xuWyPcfgN8o.jpg
[0007] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/V1_ltpEB5f08.jpg
[0008] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/sn85KLyeiNVB.jpg
[0009] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/BNYSUucabxL0.jpg
[0010] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/GlZ81yePbL5D.jpg
[0011] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/krbN1aEtcMwH.jpg
[0012] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/SaCyj31JuYcW.jpg
[0013] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/IpWcD18kxsE0.jpg
[0014] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/uc32z7lfNJL8.jpg
[0015] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/e2hR3sqtnXYc.jpg
[0016] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/1BS6_8pWeFOy.jpg
[0017] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/875uaAkRClfS.jpg
[0018] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/RzBtE2SMdALF.jpg
[0019] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/A2EzNXdaZFfH.jpg
[0020] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/FhrBqindAaD1.jpg
[0021] LazyUrl(https://manatoki95.net/comic/6776610?spage=1) ---> https://newtoki7.org/data/file/comic/5819034/6776610/aq9ygmzAD0JT.jpg

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1063, in start
File "<decorator-gen-85>", line 2, in init
File "constants", line 870, in wrapper
File "constants", line 841, in wrapper
File "extractor\manatoki_downloader", line 61, in init
File "utils", line 508, in __get__
File "extractor\manatoki_downloader", line 77, in name
File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki95.net/comic/6776610 (34.2s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1063, in start
File "<decorator-gen-85>", line 2, in init
File "constants", line 870, in wrapper
File "constants", line 841, in wrapper
File "extractor\manatoki_downloader", line 61, in init
File "utils", line 508, in __get__
File "extractor\manatoki_downloader", line 77, in name
File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki95.net/comic/6776610 (76.5s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1063, in start
File "<decorator-gen-85>", line 2, in init
File "constants", line 870, in wrapper
File "constants", line 841, in wrapper
File "extractor\manatoki_downloader", line 61, in init
File "utils", line 508, in __get__
File "extractor\manatoki_downloader", line 77, in name
File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki95.net/comic/6776610 (55.4s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1063, in start
File "<decorator-gen-85>", line 2, in init
File "constants", line 870, in wrapper
File "constants", line 841, in wrapper
File "extractor\manatoki_downloader", line 61, in init
File "utils", line 508, in __get__
File "extractor\manatoki_downloader", line 77, in name
File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki95.net/comic/6776610 (31.0s)

dirFormat: [artist] title
hash: n15b28f8579
이세계 식멸의 상어 5-2화 21
stop
EOT: https://manatoki95.net/comic/6776610 (136.1s)

이미지가 이상하게 있습니다

**Comment by geniussjt** [comment]
![0018](https://user-images.githubusercontent.com/47520785/107542546-a4c8df80-6c0b-11eb-8f6d-ed928ff8d42c.jpg)
이렇게 나옵니다 그리고 지금 다운이 잘 안되네요

**Comment by geniussjt** [comment]
지금 사이트 상태가 메롱이야서 그런건가요? 위에 있는 이미지 꽤 나오네요ㅠ_ㅠ
아무튼 운영자님 즐거운 설명절 잘 보내세요^^
