### ISSUE TITLE
유튜브 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#3094]
안녕하세요, KurtBestor님. 

픽시브 다운로드 관련 수정해주셔서 감사합니다.

새벽에 잠도 못 주무신 것 같던데 고생많으셨습니다.

정말 감사합니다.

외람되오나 이미 알고 계실지도 모르겠습니다만 새로 올려주신 다운로더를 사용했을 때

유튜브 영상이 다운로드가 되지 않습니다.

Invalid: [youtube] https://www.youtube.com/watch?v=9keIVyDRtKg

version: 3.3 (21-02-11 08:24:40 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 62e78a4d19f245afbd91ce33b1a41ec6
input: https://www.youtube.com/watch?v=9keIVyDRtKg
type: youtube
single: True
url: https://www.youtube.com/watch?v=9keIVyDRtKg
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1613033617.6631372 (Feb 11)
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
goodbyedpi: False
ytdl: 2021.02.10
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\youtube_dl_module\youtube_dl\extractor\__init__", line 4, in <module>
from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 441, in __init__
File "ytdl", line 273, in YoutubeDL
File "<decorator-gen-88>", line 2, in get_ytdl
File "locker", line 71, in _wrapper
File "ytdl", line 261, in get_ytdl
File "ytdl", line 251, in get_ytdl
File "imp", line 171, in load_source
File "<frozen importlib._bootstrap>", line 696, in _load
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\youtube_dl_module\youtube_dl\__init__", line 43, in <module>
from .extractor import gen_extractors, list_extractors
File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\youtube_dl_module\youtube_dl\extractor\__init__", line 9, in <module>
from .extractors import *
File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\youtube_dl_module\youtube_dl\extractor\extractors", line 1032, in <module>
File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\youtube_dl_module\youtube_dl\extractor\scrippsnetworks", line 8, in <module>
from .aws import AWSIE
ModuleNotFoundError: No module named 'youtube_dl.extractor.aws'

### youtube retry...
Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 441, in __init__
File "ytdl", line 273, in YoutubeDL
File "<decorator-gen-88>", line 2, in get_ytdl
File "locker", line 71, in _wrapper
File "ytdl", line 247, in get_ytdl
File "ytdl", line 193, in download_ytdl
File "ytdl", line 232, in rename
File "ytdl", line 224, in rename
File "shutil", line 564, in move
shutil.Error: Destination path 'C:\Users\Public\Documents\ESTsoft\CreatorTemp\youtube_dl_module\youtube_dl-2021.2.10' already exists

[None][0fps][49.049kbps][49.049] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][63.911kbps][63.911] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][127.175kbps][127.175] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][128.465kbps][128.465] webm [None / opus] ─ 251 - audio only (tiny)
[360p][30fps][None][188.735] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[360p][30fps][96.0kbps(fixed)][362.203] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

# stream_final <ytdl.Video object at 0x000001EB2915FEC8> 134 - 640x360 (360p) 360p mp4 None 30fps
# stream_final <ytdl.Video object at 0x000001EB54461C48> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 30fps
stream is not valid
# stream_final <ytdl.Video object at 0x000001EB2915FEC8> 134 - 640x360 (360p) 360p mp4 None 30fps
stream is not valid
Traceback (most recent call last):
File "extractor\youtube_downloader", line 378, in read
File "utils", line 701, in __call__
File "extractor\youtube_downloader", line 155, in get
Exception: No videos

No videos
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "extractor\youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=9keIVyDRtKg (169.9s)

[None][0fps][49.049kbps][49.049] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][63.911kbps][63.911] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][127.175kbps][127.175] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][128.465kbps][128.465] webm [None / opus] ─ 251 - audio only (tiny)
[360p][30fps][None][188.735] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[360p][30fps][96.0kbps(fixed)][362.203] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

# stream_final <ytdl.Video object at 0x000001C4126622C8> 134 - 640x360 (360p) 360p mp4 None 30fps
# stream_final <ytdl.Video object at 0x000001C4126623C8> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 30fps
stream is not valid
# stream_final <ytdl.Video object at 0x000001C4126622C8> 134 - 640x360 (360p) 360p mp4 None 30fps
stream is not valid
Traceback (most recent call last):
File "extractor\youtube_downloader", line 378, in read
File "utils", line 701, in __call__
File "extractor\youtube_downloader", line 155, in get
Exception: No videos

No videos
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "extractor\youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=9keIVyDRtKg (4.2s)

[None][0fps][49.049kbps][49.049] webm [None / opus] ─ 249 - audio only (tiny)
[None][0fps][63.911kbps][63.911] webm [None / opus] ─ 250 - audio only (tiny)
[None][0fps][127.175kbps][127.175] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][128.465kbps][128.465] webm [None / opus] ─ 251 - audio only (tiny)
[360p][30fps][None][188.735] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[360p][30fps][96.0kbps(fixed)][362.203] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

# stream_final <ytdl.Video object at 0x000001DC3F3A8E48> 134 - 640x360 (360p) 360p mp4 None 30fps
# stream_final <ytdl.Video object at 0x000001DC23CCE188> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 30fps
stream is not valid
# stream_final <ytdl.Video object at 0x000001DC3F3A8E48> 134 - 640x360 (360p) 360p mp4 None 30fps
stream is not valid
Traceback (most recent call last):
File "extractor\youtube_downloader", line 378, in read
File "utils", line 699, in __call__
File "extractor\youtube_downloader", line 155, in get
Exception: No videos

No videos
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1118, in start_
File "extractor\youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=9keIVyDRtKg (3.6s)
===================================================================================

version: 3.3 (21-02-04 08:00:03 UTC) 에서는 유튜브 영상이 다운로드됩니다.

픽시브 다운로드 수정해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by yuchan39** [comment]
정상작동 확인했습니다. 

감사합니다
