### ISSUE TITLE
픽시브 '다시 시작 실패; 복구됨' 에러

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#3120]
픽시브 작업 중 최근 업데이트 이전에 다운받은 작업들은 다시 시작 시 '다시 시작 실패; 복구됨' 에러가 뜹니다.

업데이트 후 쿠키를 이용해서 다운받은 작업들은 문제없이 다시 시작 가능합니다.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주시면 분석해볼게요.

**Comment by githitoman** [comment]
tarou2 (pixiv_1410598)

version: 3.2d (21-02-11 20:48:27 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 63 / False / 544e68b6ff78448aa26e318952b29841
input: pixiv_1410598
type: pixiv
single: False
url: https://www.pixiv.net/member_illust.php?id=1410598
dir: hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)
zip: 
artist: tarou2
valid / done: False / True
range / range_p: None / None
time: 1612091364.7146702 (Jan 31)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.10
changed: True


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\80881747_p0.jpg
[0002] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\80778525_p0.jpg
[0003] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\80757043_p0.jpg
[0004] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\79769523_p0.jpg
[0005] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\78457013_p0.jpg
[0006] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\77908572_p0.jpg
[0007] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\77130482_p0.jpg
[0008] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\76726061_p0.jpg
[0009] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\72308765_p0.jpg
[0010] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\70767933_p0.jpg
[0011] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\70182590_p0.jpg
[0012] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\70021194_p0.jpg
[0013] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\70006019_p0.jpg
[0014] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\69793252_p0.jpg
[0015] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\69793230_p0.jpg
[0016] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\69098966_p0.jpg
[0017] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\69048655_p0.jpg
[0018] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\69044786_p0.jpg
[0019] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\69044759_p0.jpg
[0020] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\43672263_p0.jpg
[0021] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\43640591_p0.jpg
[0022] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\36572214_p0.jpg
[0023] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\28890374_p0.jpg
[0024] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\23685165_p0.jpg
[0025] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\23550641_p0.jpg
[0026] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\20968278_p0.jpg
[0027] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\19945477_p0.jpg
[0028] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\8998716_p0.png
[0029] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\8978029_p0.png
[0030] hitomi_downloaded_pixiv\tarou2 (pixiv_1410598)\8008087_p0.jpg


[URLs]



[Messages]
tags: []
tags_ex: []

stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1118, in start_
File "extractor\pixiv_downloader", line 53, in read
File "extractor\pixiv_downloader", line 312, in get_info
NotImplementedError

Invalid: fail=True
invalid; revert
EOT: pixiv_1410598 (0.8s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3083

**Comment by githitoman** [comment]
해당 이슈의 어떤 부분을 참고하면 될까요? 쭉 읽어보니 다른 분들 답변을 보니까 해당 문제는 다 해결하신것 같은데 저는 가장 최신 Technical Preview 버전을 다운받아도 같은 문제가 생깁니다.

**Comment by KurtBestor** [comment]
최신 버전 받은 것 맞나요? 작업 정보 보면 아닌 것 같은데요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by githitoman** [comment]
문제 해결되었네요, 감사합니다!
