### ISSUE TITLE
마나토끼 일부만화다운로드시 'NoneType' object has no attribute 'text' 라는 메세지를 띄우며 다운이 안됩니다.

### ISSUE THREAD

**Issue by LimGunz** [KurtBestor/Hitomi-Downloader#3121]
[마츠모토 나오야] 괴수 8호

version: 3.0b (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 15 / False / ca1ad40ae27244cba3855d709bfe79c4
input: https://manatoki73.net/comic/2786463
type: manatoki
single: False
url: https://manatoki94.net/comic/2786463
dir: hitomi_downloaded_manatoki\[마츠모토 나오야] 괴수 8호
zip: 
artist: 마츠모토 나오야
valid / done: False / True
range / range_p: None / None
time: 1611300868.1711442 (Jan 22)
tags: []
lock: True
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.10
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_manatoki\[마츠모토 나오야] 괴수 8호\괴수 8호 1화\0000.jpeg
[0002] hitomi_downloaded_manatoki\[마츠모토 나오야] 괴수 8호\괴수 8호 1화\0001.jpeg
.
.
.

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1061, in start
File "<decorator-gen-85>", line 2, in init
File "constants", line 870, in wrapper
File "constants", line 841, in wrapper
File "extractor\manatoki_downloader", line 61, in init
File "utils", line 508, in __get__
File "extractor\manatoki_downloader", line 77, in name
File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki73.net/comic/2786463 (32.7s)

확인 부탁드립니다.

**Comment by korhentai** [comment]
토끼95 로 해보셨나요 ?

**Comment by LimGunz** [comment]
> 토끼95 로 해보셨나요 ?
> 
> 최근거는 잘 되던데...

우왕.. 감사합니다.  INPUT 주소 95로 바꾸니까 되네요
