### ISSUE TITLE
기본데이터 다운로드시 오류가 발생합니다

### ISSUE THREAD

**Issue by ggoobi** [KurtBestor/Hitomi-Downloader#3139]
삭제된 데이터 다운로드는 멀쩡한데 기본데이터 다운로드시에만 발생하네요
vpn이나 우회프로그램켜도 똑같고 설정에서 dpi우회도 켜놨습니다.

Traceback (most recent call last):
  File "hitomi_searcher", line 225, in download_json
  File "hitomi_searcher", line 427, in download_json_
Exception: http://kurtbestorthonanywhere.com/static2/h_data/galleries0.zip
WTF

**Comment by STR-HK** [comment]
저는 잘 됩니다...
혹시 최신버전이신가요?

**Comment by ggoobi** [comment]
네.. 업데이트 나올때마다 했어요
