### ISSUE TITLE
마리망 오류 해결 간절하게 부탁드립니다

### ISSUE THREAD

**Issue by fpvmflzk** [KurtBestor/Hitomi-Downloader#3142]
이전에도 계속 문의글 올렸었지만 여전히 마리망 다운이 안됩니다. 최신 베타버전으로 재설치해봤고 내장브라우저 키고 캡차 푼 상태에서도 시도해봤고 지시해주신대로(#2851) 다 해봤는데 여전히 안됩니다. 몇달째 인지 모르겠네요 다른 분들은 마리망 이슈 올라오는게 거의 없는것 같은데 저만 발생하는 문제인건지...ㅠ

Invalid: [mrm] https://myreadingmanga.info/nodu-udon-kuro-neko-wa-ookami-ouji-sama-no-yume-o-miru-ka-eng

version: 3.3 (21-02-11 20:48:27 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / cb9299dd9670403093d36ac8a79fca9d
input: https://myreadingmanga.info/nodu-udon-kuro-neko-wa-ookami-ouji-sama-no-yume-o-miru-ka-eng
type: mrm
single: False
url: https://myreadingmanga.info/nodu-udon-kuro-neko-wa-ookami-ouji-sama-no-yume-o-miru-ka-eng
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614181881.6367524 (Feb 25)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://myreadingmanga.info/nodu-udon-kuro-neko-wa-ookami-ouji-sama-no-yume-o-miru-ka-eng
stop
Traceback (most recent call last):
File "downloader", line 311, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1061, in start
File "extractor\mrm_downloader", line 43, in init
File "<decorator-gen-45>", line 2, in get_session
File "constants", line 867, in wrapper
File "constants", line 838, in wrapper
File "extractor\mrm_downloader", line 197, in get_session
File "downloader", line 344, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myreadingmanga.info/nodu-udon-kuro-neko-wa-ookami-ouji-sama-no-yume-o-miru-ka-eng

Invalid: fail=True
EOT: https://myreadingmanga.info/nodu-udon-kuro-neko-wa-ookami-ouji-sama-no-yume-o-miru-ka-eng (1.7s)

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fpvmflzk** [comment]
> 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

기본 상태에선마찬가지로 invaild 뜨면서 안됐는데 내장브라우저로 캡차 풀고 시도하니까 정상적으로 다운이 됩니다 번거로우셨을텐데 끝까지 문제 해결해주셔서 정말 감사드립니다^^

**Comment by eroego21** [comment]
내장 브라우저로 링크 주소를 입력해도 캡차 화면이 뜨지 않고 This site can’t be reached 화면만 뜨는 경우는 어떻게 해결해야하나요? 캡차 화면이라도 뜨면 어떻게 이전 사례들로 해결할텐데 되지 않아 답답할 따름입니다.

**Comment by KurtBestor** [comment]
@eroego21 해당 작업 정보 보여주세요

**Comment by eroego21** [comment]
Invalid: [mrm] https://myreadingmanga.info/muki-pomera-mitsuashi-yakutou-nondara-kou-natta-hon-onmyoji-dj-jp

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / e86afff25c6a45c99798750929565c71
input: https://myreadingmanga.info/muki-pomera-mitsuashi-yakutou-nondara-kou-natta-hon-onmyoji-dj-jp
type: mrm
single: False
url: https://myreadingmanga.info/muki-pomera-mitsuashi-yakutou-nondara-kou-natta-hon-onmyoji-dj-jp
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1626530790.6249585 (Jul 17)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: None
pinned: False
extras: {}
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
cf protection
no html
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1087, in start
File "utils", line 1157, in start_
File "extractor\mrm_downloader", line 70, in read
File "extractor\mrm_downloader", line 66, in name
File "extractor\mrm_downloader", line 81, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://myreadingmanga.info/muki-pomera-mitsuashi-yakutou-nondara-kou-natta-hon-onmyoji-dj-jp (11.6s)


> @eroego21 해당 작업 정보 보여주세요
