### ISSUE TITLE
티스토리 다운이 안 되는 것들이 있어 문의드립니다

### ISSUE THREAD

**Issue by Winneaker5261** [KurtBestor/Hitomi-Downloader#3150]
https://ehasd6.tistory.com/3732?category=857558

가장 최신화만 되고 나머진 안 됩니다

수정 가능하실까요?

Invalid: [tistory] https://ehasd6.tistory.com/3584?category=857558

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: -181 / False / caf000c377b44aaab3ac6893f592b62a
input: https://ehasd6.tistory.com/3584?category=857558
type: tistory
single: False
url: https://ehasd6.tistory.com/3584?category=857558
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614379636.894916 (Feb 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "dynamic_module_1", line 27, in read
File "dynamic_module_1", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3584?category=857558 (0.9s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3075#issuecomment-786983703
