### ISSUE TITLE
픽시브 몇몇 안긁히는 에러

### ISSUE THREAD

**Issue by nopiaioi** [KurtBestor/Hitomi-Downloader#3157]
예시 https://www.pixiv.net/users/49226693/artworks
오로지 시리즈보기로 되있고 다운이 안됩니다

다른 픽시브에도 위와같은형태는 안긁힙니다.

Invalid: [pixiv] https://www.pixiv.net/users/49226693/artworks

version: 3.3 (21-02-11 10:01:39 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 6 / False / c67efb3cbf3e401b97afae820d6d16ad
input: https://www.pixiv.net/users/49226693/artworks
type: pixiv
single: False
url: https://www.pixiv.net/users/49226693/artworks
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~10000 / None
time: 1614479528.7412333 (Feb 28)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.02.22
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
tags: []
tags_ex: []
'list' object has no attribute 'keys'
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1118, in start_
File "extractor\pixiv_downloader", line 48, in read
File "extractor\pixiv_downloader", line 281, in get_info
File "extractor\pixiv_downloader", line 311, in process_profile
AttributeError: 'list' object has no attribute 'keys'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49226693/artworks (0.8s)

tags: []
tags_ex: []
'list' object has no attribute 'keys'
stop
Traceback (most recent call last):
File "utils", line 1075, in start
File "utils", line 1118, in start_
File "extractor\pixiv_downloader", line 48, in read
File "extractor\pixiv_downloader", line 281, in get_info
File "extractor\pixiv_downloader", line 311, in process_profile
AttributeError: 'list' object has no attribute 'keys'

Invalid: fail=True
EOT: https://www.pixiv.net/users/49226693/artworks (0.6s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3096
