### ISSUE TITLE
트위터 invalid 에러

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#3165]
최신 Technical Preview에서 일부 트위터 작업 다시 시작 시 에러가 발생합니다.

**Comment by githitoman** [comment]
鯛 (@e3d1p)

version: 3.2d (21-02-28 14:19:59 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 220 / False / 9e333780e39846e598e0c1eb64121ce4
input: twitter.com/e3d1p
type: twitter
single: False
url: twitter.com/e3d1p
dir: hitomi_downloaded_twitter\鯛 (@e3d1p)
zip: 
artist: 鯛
valid / done: False / True
range / range_p: None / None
time: 1613186850 (Feb 13)
tags: ['red']
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.02.22
changed: True


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-02-03] 1356949558169804805_p0.jpg
[0002] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-02-02] 1356590190307942400_p0.jpg
[0003] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-25] 1353686612568281088_p0.jpg
[0004] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-23] 1352899064673693696_p0.jpg
[0005] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-22] 1352602268189659136_p0.jpg
[0006] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-22] 1352486795703848962_p0.jpg
[0007] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-17] 1350771791149449221_p0.jpg
[0008] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-17] 1350771791149449221_p1.jpg
[0009] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-11] 1348610107400097794_p0.jpg
[0010] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-08] 1347524705582985218_p0.jpg
[0011] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-06] 1346802949582970881_p0.jpg
[0012] hitomi_downloaded_twitter\鯛 (@e3d1p)\[21-01-06] 1346717778758127616_p0.jpg
[0013] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-30] 1344268751072497664_p0.jpg
[0014] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-29] 1343894535491911681_p0.jpg
[0015] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-28] 1343399422068027392_p0.jpg
[0016] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-27] 1343195428997771266_p0.jpg
[0017] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-21] 1340706856335941632_p0.jpg
[0018] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-19] 1340253926696701952_p0.jpg
[0019] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-18] 1339890652981694464_p0.jpg
[0020] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-17] 1339541099862437891_p0.jpg
[0021] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-11] 1337362494034223106_p0.jpg
[0022] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-11] 1337362494034223106_p1.jpg
[0023] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-12-03] 1334479433193857025_p0.jpg
[0024] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-11-29] 1333032236145250305_p0.jpg
[0025] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-11-29] 1333016725957197829_p0.jpg
[0026] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-11-22] 1330511242323226624_p0.jpg
[0027] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-11-19] 1329080940413341698_p0.jpg
[0028] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-11-13] 1327216021543952384_p0.jpg
[0029] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-11-04] 1323907193888886785_p0.jpg
[0030] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-10-29] 1321804433169158150_p0.jpg
[0031] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-10-27] 1320953444870483969_p0.jpg
[0032] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-08-29] 1299387191143985152_p0.jpg
[0033] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-08-27] 1298866661987033088_p0.jpg
[0034] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-08-17] 1295024926596857856_p0.png
[0035] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-07-08] 1280548116572147712_p0.jpg
[0036] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-06-10] 1270393921919541250_p0.jpg
[0037] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-06-01] 1267109515306000386_p0.jpg
[0038] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-04-17] 1251150367322066945_p0.jpg
[0039] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-02-11] 1227225412729593857_p0.jpg
[0040] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-01-31] 1223259638755254275_p0.png
[0041] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-01-30] 1222547445336272897_p0.jpg
[0042] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-01-23] 1220351750986584069_p0.jpg
[0043] hitomi_downloaded_twitter\鯛 (@e3d1p)\[20-01-05] 1213809234908868608_p0.jpg
[0044] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-12-23] 1209080015230390272_p0.jpg
[0045] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-12-02] 1201176661951041536_p0.jpg
[0046] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-11-22] 1197789839006912513_p0.jpg
[0047] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-11-06] 1191753836978814977_p0.jpg
[0048] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-10-21] 1186196615050059776_p0.jpg
[0049] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-10-17] 1184806789331607552_p0.jpg
[0050] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-10-17] 1184803094002982913_p0.jpg
[0051] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-10-14] 1183405076620005376_p0.jpg
[0052] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-10-08] 1181427297431232512_p0.jpg
[0053] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-09-28] 1177863544802406401_p0.jpg
[0054] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-09-24] 1176414509923069953_p0.jpg
[0055] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-08-23] 1164914694580080646_p0.jpg
[0056] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-08-14] 1161575146517221377_p0.jpg
[0057] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-08-06] 1158616504067215360_p0.jpg
[0058] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-07-21] 1152822041826828289_p0.jpg
[0059] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-06-02] 1135161358331199488_p0.jpg
[0060] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-05-17] 1129393961267630081_p0.jpg
[0061] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-01-27] 1089244477020024837_p0.jpg
[0062] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-01-27] 1089244477020024837_p1.jpg
[0063] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-01-27] 1089244477020024837_p2.jpg
[0064] hitomi_downloaded_twitter\鯛 (@e3d1p)\[19-01-04] 1080857692783075328_p0.jpg
[0065] hitomi_downloaded_twitter\鯛 (@e3d1p)\[18-12-21] 1075769670370680838_p0.jpg
[0066] hitomi_downloaded_twitter\鯛 (@e3d1p)\[18-12-15] 1073803980998754306_p0.jpg
[0067] hitomi_downloaded_twitter\鯛 (@e3d1p)\[18-11-17] 1063658690706882560_p0.jpg
[0068] hitomi_downloaded_twitter\鯛 (@e3d1p)\[16-10-22] 789811538844540929_p0.jpg


[URLs]



[Messages]
'user'
stop
Traceback (most recent call last):
File "utils", line 1064, in start
File "extractor\twitter_downloader", line 71, in init
File "<decorator-gen-25>", line 2, in get_artist_username
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\twitter_downloader", line 616, in get_artist_username
File "extractor\twitter_downloader", line 211, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
invalid; revert
EOT: twitter.com/e3d1p (8.6s)

'user'
stop
Traceback (most recent call last):
File "utils", line 1064, in start
File "extractor\twitter_downloader", line 71, in init
File "<decorator-gen-25>", line 2, in get_artist_username
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\twitter_downloader", line 616, in get_artist_username
File "extractor\twitter_downloader", line 211, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
invalid; revert
EOT: twitter.com/e3d1p (7.3s)

'user'
stop
Traceback (most recent call last):
File "utils", line 1064, in start
File "extractor\twitter_downloader", line 71, in init
File "<decorator-gen-25>", line 2, in get_artist_username
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\twitter_downloader", line 616, in get_artist_username
File "extractor\twitter_downloader", line 211, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
invalid; revert
EOT: twitter.com/e3d1p (7.5s)

'user'
stop
Traceback (most recent call last):
File "utils", line 1064, in start
File "extractor\twitter_downloader", line 71, in init
File "<decorator-gen-25>", line 2, in get_artist_username
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\twitter_downloader", line 616, in get_artist_username
File "extractor\twitter_downloader", line 211, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
invalid; revert
EOT: twitter.com/e3d1p (7.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by githitoman** [comment]
에러가 발생했던 작업은 다시 시작시 처음부터 다 다운받는 문제가 있긴 한데 나머지는 잘 작동하네요, 감사합니다!
