### ISSUE TITLE
스크립트 작업에 대해 수정하신 부분이 있나요?

### ISSUE THREAD

**Issue by lakals** [KurtBestor/Hitomi-Downloader#3167]
iwara에서 아티스트명을 따오기 위해서 스크립트를 사용하고 있습니다.
다운로드 이후에 작동하는 스크립트인데, iwara의 서버 문제로 연결에 실패하는 경우가 가끔 있습니다.

이전에는 연결에 실패했을 경우, 작업이 invalid 처리되었는데 업데이트 후(혹은 테크니컬 프리뷰만...?) 스크립트가 죽은 경우에는 그냥 성공 처리되더군요.

기존에는 다운로드 성공 - 스크립트 실행 - 실패 시 성공에서 invalid 로 변경 이런 식이었습니다.
현재는 실패해도 그냥 성공(완료) 로 남아있어서 어떤 작업이 태깅에 실패한 건지 구분하기 어렵습니다.

혹시 스크립트 작업에 대해 수정하신 내용이 있나요?
서버 환경의 변화인지, 업데이트하면서 발생한 사이드 이펙트인지 궁금해서 여쭤봅니다.

항상 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by lakals** [comment]
테스트 버전으로 해 본 결과 정상적으로 작동합니다.

다만 기존 질문에 이어서 하나 더 여쭤보고 싶은 부분이 생겼습니다.
https://github.com/KurtBestor/Hitomi-Downloader/issues/3140#issue-814651301

연결 실패로 인한 invalid 는 재시작이 되는데, 다운로드 성공 후 스크립트 실패로 인한 invalid는 자동 재시작이 안 되네요.
그 두가지에 차이점이 있는 것인가요? 혹시 가능하다면 해당 경우에도 자동 재시작이 가능해도록 해주시면 감사하겠습니다.

스크립트 실패로 인한 로그는 다음과 같습니다.

Invalid: [iwara] https://ecchi.iwara.tv/videos/jdgges0zmqieqyeog

version: 3.3a (21-03-07 06:19:16 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 1 / False / 8aa12a8d772d46579931d65ea1ae4bfe
input: https://ecchi.iwara.tv/videos/jdgges0zmqieqyeog
type: iwara
single: True
url: https://ecchi.iwara.tv/videos/jdgges0zmqieqyeog
dir: hitomi_downloaded_iwara
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1615481709.43066 (Mar 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.03
changed: True


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_iwara\【Genshin Impact】Chocolate Cream.mp4


[URLs]
[0001] LazyUrl(https://ecchi.iwara.tv/videos/jdgges0zmqieqyeog) ---> https://uni.iwara.tv/file.php?expire=1615503389&hash=106203a0fb739f86393a02031b39645727ebda89&file=2021%2F03%2F07%2F1615107105_jDgGes0ZMQIeQyeOG_Source.mp4&op=dl&r=0


[Messages]
type: video
stop
The read operation timed out
stop
Traceback (most recent call last):
File "utils", line 1089, in start
File "utils", line 1312, in finish
File "dynamic_module_0", line 76, in hook_rename
File "dynamic_module_0", line 51, in getArtistName
File "dynamic_module_0", line 15, in find_iwara_artist_name
File "urllib\request", line 222, in urlopen
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1353, in do_open
File "http\client", line 1369, in getresponse
File "http\client", line 310, in begin
File "http\client", line 271, in _read_status
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

Invalid: fail=True
EOT: https://ecchi.iwara.tv/videos/jdgges0zmqieqyeog (168.9s)
