### ISSUE TITLE
기본데이터 다운이 안됩니다.

### ISSUE THREAD

**Issue by y5624711** [KurtBestor/Hitomi-Downloader#3177]
최신버전이구 
요렇게 뜹니당

Traceback (most recent call last):
  File "downloader", line 311, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 641, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 225, in download_json
  File "hitomi_searcher", line 387, in download_json_
  File "downloader", line 344, in read_html
  File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://kurtbestorthonanywhere.com/h_data

**Comment by KurtBestor** [comment]
이제 제대로 될 거예요
