### ISSUE TITLE
뉴토x가 다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#3182]
Invalid: [manatoki] https://newtoki95.com/webtoon/11235565/%EC%B2%9C%EC%82%AC%EC%9D%98

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 2 / False / 939ec094af74471fa207135a29c0090f
input: https://newtoki95.com/webtoon/11235565/%EC%B2%9C%EC%82%AC%EC%9D%98
type: manatoki
single: False
url: https://newtoki95.com/bbs/captcha.php
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614865655.7670965 (Mar 4)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.03
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1064, in start
File "<decorator-gen-86>", line 2, in init
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\manatoki_downloader", line 60, in init
File "utils", line 506, in __get__
File "extractor\manatoki_downloader", line 76, in name
File "extractor\manatoki_downloader", line 98, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://newtoki95.com/webtoon/11235565/%EC%B2%9C%EC%82%AC%EC%9D%98 (23.6s)

![ㅠㅠ](https://user-images.githubusercontent.com/47520785/109973948-5efbc480-7d3c-11eb-8824-e9c6a6491d50.jpg)

웹툰이 다운이 안됩니다ㅠ_ㅠ

**Comment by fade-out-0770** [comment]
저도 같은문제였는데 쿠키 쓰니까 해결됐습니다. 사용법은 도움말에 있으니 참고하세요.

**Comment by geniussjt** [comment]
github.com_cookies 다운고  옵션 - 설정 - 고급 설정 - 쿠키 - 불러오기...했는데...요
여전히 다운이 안됩니다ㅠ_ㅠ

**Comment by geniussjt** [comment]
정말 감사합니다ㅠㅠ덕분에 잘됩니다
