### ISSUE TITLE
티스토리 다운이 안 되어 문의드립니다.

### ISSUE THREAD

**Issue by naem23412** [KurtBestor/Hitomi-Downloader#3193]
https://editorene.tistory.com/770
https://editorene.tistory.com/

블로그 전체적으로 다운이 안 되어 문의드립니다.
수정이 가능하실까요?

Invalid: [tistory] https://editorene.tistory.com/770

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 96fbb2c8eb9b4268b9a2ee4a45c9aede
input: https://editorene.tistory.com/770
type: tistory
single: False
url: https://editorene.tistory.com/770
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1615130271.2092524 (Mar 8)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.03
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no views
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "dynamic_module_0", line 27, in read
File "dynamic_module_0", line 79, in get_info
Exception: no views

Invalid: fail=True
EOT: https://editorene.tistory.com/770 (0.6s)

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 불러와주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
