### ISSUE TITLE
티스토리 다운이 되지 않는 것이 있습니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#3204]
안녕하세요.

다운로더 잘 쓰고 있습니다.

티스토리 다운로드가 되지 않는 것이 있습니다.

Invalid: [tistory] https://siktit.tistory.com/50

version: 3.3a (21-03-07 06:19:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 2 / False / 89643382278e43a090d6ed1139ad0e8b
input: https://siktit.tistory.com/50
type: tistory
single: False
url: https://siktit.tistory.com/50
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1615512925.2369728 (Mar 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.03
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1127, in start_
File "dynamic_module_3", line 27, in read
File "dynamic_module_3", line 58, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/50 (1.1s)
===================================================================================

Invalid: [tistory] https://siktit.tistory.com/261

version: 3.3a (21-03-07 06:19:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 44a90ebd805b40019f892f90d21dd63d
input: https://siktit.tistory.com/261
type: tistory
single: False
url: https://siktit.tistory.com/261
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1615513005.0086966 (Mar 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.03
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1127, in start_
File "dynamic_module_3", line 27, in read
File "dynamic_module_3", line 58, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/261 (1.1s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1127, in start_
File "dynamic_module_3", line 27, in read
File "dynamic_module_3", line 58, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/261 (1.0s)
===================================================================================
Invalid: [tistory] https://siktit.tistory.com/256

version: 3.3a (21-03-07 06:19:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 77e5dfc7b93948cd8f12ae1b36cf863d
input: https://siktit.tistory.com/256
type: tistory
single: False
url: https://siktit.tistory.com/256
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1615513033.7444437 (Mar 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.03
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1127, in start_
File "dynamic_module_3", line 27, in read
File "dynamic_module_3", line 58, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/256 (1.0s)
===================================================================================

Invalid: [tistory] https://ehasd6.tistory.com/3441

version: 3.3a (21-03-07 06:19:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 68f0522f1e244a88bb9eb47071ee4fdb
input: https://ehasd6.tistory.com/3441
type: tistory
single: False
url: https://ehasd6.tistory.com/3441
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1615513583.9848547 (Mar 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.03
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no imgs
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1127, in start_
File "dynamic_module_3", line 27, in read
File "dynamic_module_3", line 95, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://ehasd6.tistory.com/3441 (1.5s)
===================================================================================

https://siktit.tistory.com/m

전체가 다운이 되지 않는 것 같습니다.

바쁘신 와중에도 항상 피드백 해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 불러와주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
ehasd6.tistory.com

editorene.tistory.com

정상적으로 다운되는 것을 확인했습니다.

수정해주셔서 감사합니다.

===================================================================================
Invalid: [tistory] https://siktit.tistory.com/50

version: 3.3a (21-03-20 04:12:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 8eead1cb5d954aeabf3d6f743ea19ffc
input: https://siktit.tistory.com/50
type: tistory
single: False
url: https://siktit.tistory.com/50
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1616241016.1039557 (Mar 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.14
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_4", line 19, in read
File "dynamic_module_4", line 51, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/50 (1.1s)

===================================================================================
Invalid: [tistory] https://siktit.tistory.com/261

version: 3.3a (21-03-20 04:12:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 7b611ad38e7948468fcc2f17c5b5df89
input: https://siktit.tistory.com/261
type: tistory
single: False
url: https://siktit.tistory.com/261
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~999999 / None
time: 1616242929.9459307 (Mar 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.14
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_4", line 19, in read
File "dynamic_module_4", line 51, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/261 (1.4s)
===================================================================================

와 같이 https://siktit.tistory.com 는 다운로드가 되지 않습니다.

번거롭게 해 드려 죄송합니다.

감사합니다.

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 불러와주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
siktit.tistory.com 

정상작동 확인했습니다.

수정해주셔서 감사합니다.

**Comment by yuchan39** [comment]
아뢰옵기 송구하오나 

siktit.tistory.com 에서

쿠키를 적용해도 다운되지 않는 페이지가 있습니다.

===================================================================================

Invalid: [tistory] https://siktit.tistory.com/252

version: 3.3a (21-03-20 04:12:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 11 / False / 47f695bceaa0460d823463e53a618bde
input: https://siktit.tistory.com/252
type: tistory
single: False
url: https://siktit.tistory.com/252
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616247528.2814744 (Mar 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 51, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/252 (0.8s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/252 (0.8s)
===================================================================================

Invalid: [tistory] https://siktit.tistory.com/254

version: 3.3a (21-03-20 04:12:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 9 / False / 2cb39413b7f040f1bee063b632e304ca
input: https://siktit.tistory.com/254
type: tistory
single: False
url: https://siktit.tistory.com/254
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616247528.2904503 (Mar 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 51, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/254 (0.8s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/254 (1.0s)
===================================================================================
Invalid: [tistory] https://siktit.tistory.com/255

version: 3.3a (21-03-20 04:12:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 8 / False / f26c38a5b89c429585ceb8feed275548
input: https://siktit.tistory.com/255
type: tistory
single: False
url: https://siktit.tistory.com/255
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616256152.3284268 (Mar 21)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 51, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (0.8s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (0.8s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (2.1s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (1.5s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (1.3s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (1.5s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (1.5s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/255 (1.7s)
===================================================================================

Invalid: [tistory] https://siktit.tistory.com/256

version: 3.3a (21-03-20 04:12:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 7 / False / 53044acd919546bdb241a3d5fd85740c
input: https://siktit.tistory.com/256
type: tistory
single: False
url: https://siktit.tistory.com/256
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616256149.9267938 (Mar 21)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 51, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://siktit.tistory.com/256 (0.8s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/256 (0.8s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_1", line 19, in read
File "dynamic_module_1", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/256 (1.5s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/256 (1.5s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 19, in read
File "dynamic_module_0", line 49, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://siktit.tistory.com/256 (1.4s)
===================================================================================

1111 

제가 조금 더 확인하고 말씀드렸어야 하는데

번거롭게 해드려 죄송합니다.

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해서 불러와주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
정상작동확인했습니다.

수정해주셔서 감사합니다.
