### ISSUE TITLE
트위터 일부 계정을 일정량 이상 못읽고 실패하는 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#3216]
안녕하세요 존경하는 KurtBestor 선생님. 항상 신세를 지고 있습니다.

현상은 제목과 같고 혹시 싶어서 다운로드 한계점을 999999 이런식으로 바꿔 시도해보았으나 결과가 같았습니다.
읽어들일 당시 프로그램 창을 지켜보니 약 18600 번대까지 읽다가 붉게변하면서 실패하는 것을 확인했습니다.

시도한 주소 : https://twitter.com/sailor_complexx

아래는 로그입니다.

--------------------------------------------------------------------------------------------------------
Invalid: [twitter] https://twitter.com/sailor_complexx

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 35 / False / d9b5809b871846c4bf40a2c7929848b2
input: https://twitter.com/sailor_complexx
type: twitter
single: False
url: https://twitter.com/sailor_complexx
dir: 
zip: 
artist: 세라봇
valid / done: False / True
range / range_p: ~9999999 / None
time: 1615735113.355535 (Mar 15)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
multiple tweets
cursor: HBaIgKmxpYDc+SUAAA==
cursor: HBaOwKORuZrm6yUAAA==
cursor: HBaAgKOF5Les3CUAAA==
cursor: HBaAwKK1vrbJySUAAA==
cursor: HBaCwKOh9NWEuyUAAA==
cursor: HBaCgKOJ6f3orCUAAA==
cursor: HBaAwKi529D7oCUAAA==
cursor: HBaCwKiFhYfulSUAAA==
cursor: HBaEgKbB7vS7kCUAAA==
imgs: 875, types: video, img
cursor: scroll:thGAVUV0VFVBaCgKrd6qSehCUWgoCq3eqknoQlEnEV2Ih6FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKyxqOWS9yQWgsCjnZ3EkIQlEnEV7Ih6FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKbB4ZHC3yQWgMC3nfaQleokEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgKOBkej5ySQWhMCmmbaN19QkEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKz9mKSItCQWgICn6dnr174kEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKblr_u_niQWgICska_Fj6kkEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKe9jOajhiQWhMChnfTojpEkEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaGgKfVo5rp8CMWjsCmlYvjuPsjEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKjR9rid2yMWgMCg7ZKX_uUjEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKihk5HVxSMWgoCjkfXYpNAjEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKutwKHCriMWkMCm_b7qkbkjEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaKgKPRgPrKkCMWgMCjwf7J3aAjEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKPpu9-V-SIWgoCooaqozIQjEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKf5_92I4yIWgsChnYfO-u0iEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKbxhfqdzSIWhoCmvc279NciEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKC1hMnctyIWgsCinbeRrMIiEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKrJgYXroSIWgoCmmebm46wiEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKKNwbiwjCIWgMCjraX9_5YiEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaOwKrth67a9iEWgsCi_ffUt4EiEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKaVq5u84CEWgMCgjd7ni-shEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKed_NKByyEWgMCn4Zqb0dUhEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKj9s5GQtSEWgsCjpdPuiMAhEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKilzsbVnyEWgoCnlbuLpaohEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKel-rv_iSEWgMCmhYjD6pQhEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKedy_Td8yAWhMCjqb-i6_4gEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKi1s6ej3iAWgICmzaDx8uggEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKr5l62WyCAWgsCnrbGNj9MgEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKPt9t_bsiAWgMCmlcGqq70gEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKHNsf73nCAWhICm8f7e8KcgEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKDJv9WvhyAWgIColaed_5EgEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKaVjLjJ8B8WgMCmoeXZpvsfEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKfFvdDl2h8WgMCjqa-YteUfEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaKgK_5yoqrxR8WgMCjheLR-s8fEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKaJzPekrx8WhMCguYGHwLofEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKPZ5NLcmR8WgsCj2ZaZrKQfEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEwKfdlYeihB8WgsCmyZzM8Y4fEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKaNyYHM7h4WgMCi3Y3Gm_keEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKPhk7SR2R4WhICjxYP_4OMeEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKP54Pe3wx4WgICj8ej7os4eEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKOhj639rR4WgMCiiZ30zLgeEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKjNheLCmB4WgMCtvfSqkqMeEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgK-pstvsgh4WgMCipYGkvI0eEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaKwKOd1pKy7R0WgICjwcTagfgdEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgK_tx4zc1x0WhMC1gcqRx-IdEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgL2NnuSTwh0WgICvzduJ8cwdEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgK_x1bW0qx0WgsCm8aLiqLcdEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKa526_elR0WgMCt_Zz3raAdEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKeB5-ajgB0WgICvtd-r84odEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKOpvt7N6hwWgICo4bLhuPUcEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgK-F_JaT1RwWgMCijY7c4t8cEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEwKKpkMvYvxwWgMCnxd-UqMocEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKjJwcmCqhwWgMCtlbeL0rQcEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgK-lyOGelBwWgsCp4fmm7p4cEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgKONxdjI_hsWgICvrancs4kcEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKPV84-O6RsWgoCv2frW3fMbEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKih54ig0xsWgICv2eKKo94bEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKnZ34DKvRsWgMCnzcLHmcgbEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwLbJioL0pxsWgMCp8YGd0bIbEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKf9zZaQkhsWgoCogeOX-5wbEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKqh5cnV_BoWgICutbiWpYcbEnEVjPt5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKfVxtHg5hoWgICiqenK6vEaEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKG11MuK0RoWgoCv5aGS2tsaEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKfNwYLQuxoWgsCnjabKn8YaEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgKHhgPz5pRoWgMCp1aP95LAaEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKCppLG_kBoWgIC_4b74jpsaEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKfRhOeE-xkWgICqjdSt1IUaEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKDR9-Lg4xkWgsCh5dip_u8ZEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKDN75amzhkWgICoocnd9dgZEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgKHtnpLQuBkWgICh3ci0rcMZEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgK6ZpseVoxkWgoChhYKR5a0ZEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKGRz6HNjRkWhICoiY7HqpgZEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgKGZ6-jz9xgWgICirYW_1IIZEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKCx5Ze54hgWgoCirejeiO0YEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwK7pk-vjzBgWgMChpdy9wNcYEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEwKb1i6PCthgWgICt5aPnkcEYEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKv9wPf5oBgWgoChzcyg16sYEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaIwK7BmqyPixgWgsCmnaOcgZYYEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKCV3_Ht9BcWgICtzYS5vf8XEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKb1tfPC3RcWgICm3eqM9ekXEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKLp38D6xxcWgoChpfny19IXEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEwKbZ-aayshcWgMCpvbPTj70XEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKitz4LqnBcWgMCprbLKuacXEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKvxgdihhxcWgsCq7ciZ8ZEXEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKm169LL8RYWgMCrvbbwqPwWEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKLxmLnk2xYWgMCjsb7Q4OYWEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwLq9qIycxhYWgoCiwbGx-dAWEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKKh_KaIsBYWgMCi3YLY3roWEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKTtoe3GmhYWgMCi3dL1maUWEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKL1kO3whBYWgICp2diTzo8WEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKnNxOKy7xUWgMCpqeDjhfoVEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKCt-tys2RUWgMCptYL8ieQVEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKvJisTdwxUWgMCkrca4sM4VEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaIwKWNjZ2PrRUWgMCq8dr29rcVEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKGJ9oOQlxUWgsCliaSW9KEVEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKDxxfbxgBUWgMClgdTwxIsVEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKGtiprw6RQWgMCgrf_FzPUUEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaEgKjRjbfc0xQWgICjxevQud4UEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKS94-rxvRQWgMCiha3h48gUEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKPdmc2DqBQWgICo9fOi8LIUEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKS50e6-khQWgoCj1brZkZ0UEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKKt2cy4_BMWgIC5zZ6IzYcUEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKKN-IPc5hMWiMCisdKmyvETEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKO9gL-s0BMWgsCgqYz5-9oTEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaKgKD9nNipuhMWgMCggfbcrMUTEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKnp08HhpBMWgMCk5c-eu68TEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKK9j-SujhMWhMC0lcLa15kTEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKCt1bzf-BIWiMCh3ZH9roMTEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKTpnd_74hIWgICgjYXW1e0SEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKbtyaebzRIWgsCgldam7NcSEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKDBqJ3pthIWgICmgcKBpsISEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaIwKjNhPOwnhIWgICg-bPtiaoSEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKCR6OKshBIWgMCgkdy725ESEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKTt_Luw7REWgMCjsaup0vgREnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKON65eD1REWgMCjwYu-v-EREnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwKHF1-OOtxEWgICxycO498YREnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKCNuNyZmxEWgMCl3bDbq6gREnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKCtqKOZghEWgICjvfP5_40REnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKmpvJOj6hAWgsCoqanCifYQEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAwKjJ-tOr0xAWgoCl4faAnd8QEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgKnxs8C6uhAWgMCkpaWDjccQEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaGwKS55N6foxAWhMClucn_xK4QEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKLhpIjXihAWgICp3ci56pUQEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgKeFrtuu9A8WgsCiibO20P8PEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwJLs6e-k3g8WgMChtfenmukPEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgJP80O_pxQ8WgICQsIL2o9IPEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCwJOQr_G9rw8WgMCRmKrP7boPEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgJK47t2Qlw8WgoCTwN-swKIPEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaCgJCwhb3t_g4WgMCR6Of23YsPEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgJHo5oX86A4WgsCQ9J-00vMOEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgJDowqvE0A4WgICTxJXfxN0OEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgJHgjvrFuQ4WgICQlMmpisUOEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
cursor: scroll:thGAVUV0VFVBaAgJCY0__fog4WgMCQjJ2Ztq0OEnEVnPl5FYCJehgHREVGQVVMVDUBFQAVAAA=
[{'message': 'Rate limit exceeded', 'code': 88}]
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\twitter_downloader", line 107, in read
File "extractor\twitter_downloader", line 377, in get_imgs
File "extractor\twitter_downloader", line 407, in get_imgs_more
File "extractor\twitter_downloader", line 255, in _pagination
File "extractor\twitter_downloader", line 245, in _pagination
Exception: [{'message': 'Rate limit exceeded', 'code': 88}]

Invalid: fail=True
EOT: https://twitter.com/sailor_complexx (880.8s)

**Comment by KurtBestor** [comment]
다시 시도해도 그런가요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/111858511-0acc2380-897d-11eb-9887-fff955f98942.png)

재현할 수가 없네요

**Comment by jaejunghan** [comment]
![fdsfsdfaa](https://user-images.githubusercontent.com/41049446/111869976-47237200-89c5-11eb-981b-4113a1b95f61.PNG)
위에 나온 링크를 다운받았는데 저는 페이지 제한을 걸지 않았음에도 2000장까지만 다운이됩니다. 신기한게 단보루 히토미 픽시브등 다른사이트들은 2000장 이상 다운이 가능합니다.

세라봇 (@sailor_complexx)

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 1cb93b4e73da4de9a73da4c0b59a4a34
input: https://twitter.com/sailor_complexx
type: twitter
single: False
url: https://twitter.com/sailor_complexx
dir: hitomi_downloaded_twitter\세라봇 (@sailor_complexx)
zip: 
artist: 세라봇
valid / done: True / True
range / range_p: None / None
time: 1616243975.9668534 (Mar 20)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

글자수 제한때문에 작업정보를 txt파일로 남깁니다.
[작업정보.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/6175571/default.txt)

**Comment by KurtBestor** [comment]
폴더 지우고 다시 시도해보시고 2000 장 제한은 다음 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/382#issuecomment-450846793

**Comment by jaejunghan** [comment]
382 대로 해봣는데, 그래도 2000장까지만 됩니다

**Comment by jaejunghan** [comment]
픽시브나 단보루 등등 2000장 넘는곳에서 다운시도하면, 2000장이상 읽는데

트위터는 2000장 넘는 트윗들은 2000장까지만 읽고 다운을 받습니다.

이게 최신버전들은 모두그러는 와중에, 몇달전 버전은 그렇지 않거든요.

**Comment by KurtBestor** [comment]
픽시브랑 단부루도 똑같이 기본 2000장 제한이에요.

**Comment by jaejunghan** [comment]
트위터나 픽시브는 다운 받기전에 2000장 넘는지 안넘는지 모르는데,

나중에 한번 다운받아야 2000장으로 찍혀있으면 그제서야 수동으로 하나하나 페이지 몇천장씩 하면서 다운받아야 하는데

이미지파일을 읽어오는 제한을 2000장이 아니라 아예 제한을 없애주시면 안될까요?

**Comment by jaejunghan** [comment]
전에는 제한없이 2만장짜리 트위터도 잘만 다운받았는데, 갑자기 왜그렇게 패치된건지 모르겟습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1907

**Comment by xel04** [comment]
안녕하세요.
페이지 지정 다운로드 기본값을 ~8000으로 설정하고 https://twitter.com/sailor_complexx 이 계정 다운로드를 기존 폴더 지우고 재시도해봤는데 마찬가지였습니다. 3.1만개의 이미지가 있는데 875개만 받고 완료가 되네요. 3월 22일에 올려주신 테스트 버전으로 수행하였습니다.

![2021-04-03 223121](https://user-images.githubusercontent.com/69039460/113479985-f46dae00-94cc-11eb-91fd-585f3013ee65.png)


세라봇 (@sailor_complexx)

version: 3.3a (21-03-22 11:13:37 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / a0026d73cf394f9791950807fd6303e5
input: https://twitter.com/sailor_complexx
type: twitter
single: False
url: https://twitter.com/sailor_complexx
dir: hitomi_downloaded_twitter\세라봇 (@sailor_complexx)
zip: 
artist: 세라봇
valid / done: True / True
range / range_p: ~8000 / None
time: 1617456238.586987 (Apr 3)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.01
changed: True


[Gallery]
None


[File Names]
(텍스트 파일로 대체)
[sailor_complexx.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/6252629/sailor_complexx.txt)

**Comment by xel04** [comment]
코멘트를 썼다가 삭제했습니다. 확인해보니 해당 트위터 계정(@sailor_complexx)은 실제 유효 사진 갯수가 800개 가량인 것으로 보이네요. 번거롭게 해드려 죄송합니다.

**Comment by tdi2020** [comment]
궁금증이 윗 글들로 많이 해결되었습니다! 늘 감사합니다 존경합니다 선생님!
