### ISSUE TITLE
항상 수고많으십니다. Jmana사이트에서 다운이 안됩니다. 

### ISSUE THREAD

**Issue by TopGuunN** [KurtBestor/Hitomi-Downloader#3220]
어제까지만해도 분명 잘되고있어서 

잘 받고있었는데 오늘 켜보니 아래와 같이 문구가 나오면서 

무한 다시하기 반복중입니다. 

그래서 Github에 이것저것 찾아보면서 Cookie등록도 해보고 

나름 이것저것 시도해보았는데도 차도가 없어서 이렇게 문의드립니다.  

뉴토끼는 확인해본결과 정상작동합니다.. 

----------------------------------------------------------------------------------------------
3분 18초 뒤 다시 시작: https://jmana1.net/comic_list_title?bookname=%EC%83%A4%EB%A8%BC%ED%82%B9

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 6df2640059f94ff9bf1cc14f2467560b
input: https://jmana1.net/comic_list_title?bookname=%EC%83%A4%EB%A8%BC%ED%82%B9
type: jmana
single: False
url: https://jmana1.net/comic_list_title?bookname=%EC%83%A4%EB%A8%BC%ED%82%B9
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1615957718.533436 (Mar 17)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\jmana_downloader", line 84, in read
File "extractor\jmana_downloader", line 78, in name
File "extractor\jmana_downloader", line 98, in get_title
File "ree", line 15, in find
ree.NotFound: no title

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%83%A4%EB%A8%BC%ED%82%B9 (2.8s)

no title
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\jmana_downloader", line 84, in read
File "extractor\jmana_downloader", line 78, in name
File "extractor\jmana_downloader", line 98, in get_title
File "ree", line 15, in find
ree.NotFound: no title

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%83%A4%EB%A8%BC%ED%82%B9 (3.8s)

--------------------------------------------------------------------------------------------------------------------------

그리고 이 밑부터는 쿠기 등록하고 나서 추가적으로 뜨는 에러메세지입니다. 

---------------------------------------------------------------------------------------------------------------------------
Unknown site: Invalid:

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 2 / False / e5286357b027412faa89e36bc43f26ab
input: Invalid:
type: None
single: False
url: Invalid:
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1615957415.6216476 (Mar 17)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: Invalid: (0.0s)

-------------------------------------------------------------------------------------------------------------------------

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by TopGuunN** [comment]
감사합니다.!! 수고해주신 덕분에 무척이나 잘 받아집니다!!
