### ISSUE TITLE
rule34 사이트 관련 문의

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader#3221]
rule34 에서

특정 태그만 다운받는건 어렵나요?

검색해서 특정 태그만 분류해서 다운로드를 시도했는데 오류가 발생합니다.

작업정보를 올립니다.

Invalid: [rule34_xxx] https://rule34.xxx/index.php?page=post&s=list&tags=d.va

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 02004e6a6e5e49a0a50c42b2912b038a
input: https://rule34.xxx/index.php?page=post&s=list&tags=d.va
type: rule34_xxx
single: False
url: https://rule34.xxx/index.php?page=post&s=list&tags=d.va
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1615987451.6434338 (Mar 17)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags=d.va&pid=0&limit=100
('Connection aborted.', OSError(0, 'Error'))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 311, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 0] Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\rule34_xxx_downloader", line 61, in read
File "extractor\rule34_xxx_downloader", line 111, in get_imgs
File "downloader", line 338, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 112, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

Invalid: fail=True
EOT: https://rule34.xxx/index.php?page=post&s=list&tags=d.va (1.6s)

https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags=d.va&pid=0&limit=100
('Connection aborted.', OSError(0, 'Error'))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 311, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 0] Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\rule34_xxx_downloader", line 61, in read
File "extractor\rule34_xxx_downloader", line 111, in get_imgs
File "downloader", line 338, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 112, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

Invalid: fail=True
EOT: https://rule34.xxx/index.php?page=post&s=list&tags=d.va (1.5s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2843

**Comment by inchaos4315** [comment]
감사합니다

**Comment by pokemonchun** [comment]
hitomi_downloader_GUI.exe --safemode
실행이 안됩니다
![image](https://user-images.githubusercontent.com/77759901/112458613-511beb00-8da0-11eb-8032-936d82f300ea.png)

**Comment by pokemonchun** [comment]
> 감사합니다

실례가 안된다면 어떻게 해결하였는지 알려주실 수 있나요?
