### ISSUE TITLE
유튜브 mp3 다운로드가 안돼네요..

### ISSUE THREAD

**Issue by zifm** [KurtBestor/Hitomi-Downloader#3222]
Invalid: [youtube] https://www.youtube.com/watch?v=vi871b_MCto

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 8e580558036f4f51ab09b3f11ce46cf5
input: https://www.youtube.com/watch?v=vi871b_MCto
type: youtube
single: True
url: https://www.youtube.com/watch?v=vi871b_MCto
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616043236.037563 (Mar 18)
tags: []
lock: False
color: invalid
paused: False
format: mp3
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

### youtube retry...
Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

Traceback (most recent call last):
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 302, in get_code
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 319, in extract
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod02_archive", line 96, in __enter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Desktop\\hitomi_downloader_GUI.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 378, in read
File "utils", line 699, in __call__
File "extractor\youtube_downloader", line 73, in get
File "extractor\youtube_downloader", line 65, in get
File "ytdl", line 442, in __init__
File "ytdl", line 314, in extract_info
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 799, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 806, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 827, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\youtube", line 1716, in _real_extract
or search_meta('uploadDate')),
File "C:\Users\admin\AppData\Local\Temp\youtube_dl_module\youtube_dl\utils", line 2945, in unified_strdate
upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 473, in exec_module
File "c:\users\kurtb\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers", line 306, in get_code
ImportError: Loader FrozenImporter cannot handle module _strptime

No videos
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\youtube_downloader", line 384, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=vi871b_MCto (20.2s)

이렇게 나오네요
불철주야 고생이 많으십니다.

**Comment by KurtBestor** [comment]
무슨 백신 쓰시나요?

**Comment by zifm** [comment]
카스퍼스키 씁니당

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나온 내용 보여주세요

**Comment by zifm** [comment]
다시해보니까 잘되네요!
