### ISSUE TITLE
니코동 영상이 다운로드 실패 합니다.

### ISSUE THREAD

**Issue by catki1348** [KurtBestor/Hitomi-Downloader#3228]
한 4일정도까지만 해도 정상이었는데 갑자기 다운이 안됩니다.

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 4 / False / a17c82536da54498ac85723840d7121f
input: https://www.nicovideo.jp/watch/so38369801
type: nico
single: True
url: https://www.nicovideo.jp/watch/so38369801
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616243550.5477839 (Mar 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
nico retry...
nico retry...
No active exception to reraise
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\nico_downloader", line 71, in read
File "extractor\nico_downloader", line 96, in get_video
RuntimeError: No active exception to reraise

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/so38369801 (5.6s)

nico retry...
nico retry...
No active exception to reraise
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\nico_downloader", line 71, in read
File "extractor\nico_downloader", line 96, in get_video
RuntimeError: No active exception to reraise

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/so38369801 (5.6s)

**Comment by catki1348** [comment]
이미 해결된 내용 있더군요
죄송합니다.
