### ISSUE TITLE
텀블러 다운로드 오류

### ISSUE THREAD

**Issue by BAEJD** [KurtBestor/Hitomi-Downloader#3235]
기본 다운로드(~ 2000) : 정상 다운로드
~ 3000 : 정상 다운로드
3001 ~ 5000, ~5000, ~4000 등에서  : 다운로드 오류가 납니다.

Invalid: [tumblr] tumblr_photoman1004

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.17134-SP0 / ko
order / group / uid: 0 / False / bf1864e423494f58bde4fbb851fbf727
input: tumblr_photoman1004
type: tumblr
single: False
url: https://photoman1004.tumblr.com
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~ 4000 / None
time: 1616382835.305797 (Mar 22)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
unknown ext
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\tumblr_downloader", line 41, in read
File "extractor\tumblr_downloader", line 162, in get_imgs
File "extractor\tumblr_downloader", line 112, in posts
File "extractor\tumblr_downloader", line 143, in __init__
File "extractor\tumblr_downloader", line 17, in __init__
File "downloader", line 1037, in get_ext
Exception: unknown ext

Invalid: fail=True
EOT: tumblr_photoman1004 (503.4s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ZeroOne0818** [comment]
텀블러 포스트수 2000개가 넘어가니 다운로드가 안됩니다... 어떻게 해야할까요?
제목 없음 (tumblr_towa08)

version: 3.4 (21-06-18 00:18:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / dc99ca6bd22b43f8afeba8fe0fbfaf22
input: https://towa08.tumblr.com
type: tumblr
single: False
url: https://towa08.tumblr.com
dir: hitomi_downloaded_tumblr\제목 없음 (tumblr_towa08)
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1623981075.0052598 (Jun 18)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None
