### ISSUE TITLE
유튜브 특정 동영상에서 1080p 다운로드가 안됩니다

### ISSUE THREAD

**Issue by asval9x39** [KurtBestor/Hitomi-Downloader#3236]
개발자님 감사합니다. 평소에 정말 잘 쓰고 있습니다.
다름이 아니라 유튜브에서 볼때는 1080p HD가 설정되지만 
해당 동영상을 다운로드 받을 시 Messages에 720p 까지만 표시됩니다
다른 1080p 동영상은 정상적으로 받아집니다.
https://www.youtube.com/watch?v=c7XE-4Ibf8A&ab_channel=JPMUSIK
해당 영상의 문제인가요 아니면 제 문제인가요?

```
► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 1e011a32abbd46f6aa25dee0ae9ed720
input: https://youtu.be/c7XE-4Ibf8A
type: youtube
single: True
url: https://youtu.be/c7XE-4Ibf8A
dir: hitomi_downloaded_youtube
zip: 
artist: JP MUSIK
valid / done: True / True
range / range_p: None / None
time: 1616394030.2509067 (Mar 22)
tags: []
lock: False
color: done
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
goodbyedpi: True
ytdl: 2021.03.14
changed: True


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4


[URLs]
[0001] LazyUrl(https://youtu.be/c7XE-4Ibf8A) ---> 【local_lazy】 ► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4


[Messages]
[None][0fps][127.175kbps][127.175] m4a [None / mp4a.40.2] ─ 140 - audio only (tiny)
[None][0fps][132.289kbps][132.289] webm [None / opus] ─ 251 - audio only (tiny)
[360p][30fps][None][602.801] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (360p)
[360p][30fps][96.0kbps(fixed)][735.403] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192.0kbps(fixed)][2789.968] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)


# stream_final <ytdl.Video object at 0x00000206092C4C88> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 30fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192.0
Subtype: mp4
FPS: 30

Traceback (most recent call last):
File "downloader_v3", line 146, in download
File "requests\sessions", line 543, in get
File "downloader", line 112, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 637, in send
File "requests\sessions", line 730, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'H:\\hitomi_downloader_GUI\\hitomi_downloaded_youtube\\► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4'

### reset size ###
Traceback (most recent call last):
File "downloader_v3", line 146, in download
File "requests\sessions", line 543, in get
File "downloader", line 112, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 637, in send
File "requests\sessions", line 730, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'H:\\hitomi_downloader_GUI\\hitomi_downloaded_youtube\\► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4'

### reset size ###
use just download
stop
EOT: https://youtu.be/c7XE-4Ibf8A (3.0s)

```

**Comment by KurtBestor** [comment]
지금도 그런가요?

**Comment by asval9x39** [comment]
마지막에 ffmpeg 로드 후 변환 중에 오류가 납니다.

```
### reset size ###
### reset size ###
use just download
Convert: H:\hitomi_downloader_GUI\hitomi_downloaded_youtube\► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4
rename (1): H:\hitomi_downloader_GUI\hitomi_downloaded_youtube\► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4 -> H:\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpf32752796d18497785751f8d3a98c27e_i.mp4
-i tmpf32752796d18497785751f8d3a98c27e_i.mp4 -acodec copy -vcodec copy tmpf32752796d18497785751f8d3a98c27e_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
1
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, matroska,webm, from 'tmpf32752796d18497785751f8d3a98c27e_i.mp4': 
Metadata: 
encoder : google/video-file 
http://youtube.com/streaming/otf/durations/112015: Segment-Count: 42 
: Segment-Durations-Ms: 5339,5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5138, 
: 
: 
Duration: N/A, start: 0.000000, bitrate: N/A 
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default) 
Output #0, mp4, to 'tmpf32752796d18497785751f8d3a98c27e_o.mp4': 
Metadata: 
http://youtube.com/streaming/otf/durations/112015: Segment-Count: 42 
: Segment-Durations-Ms: 5339,5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5138, 
: 
: 
encoder : Lavf58.20.100 
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 16k tbn, 1k tbc (default) 
Stream mapping: 
Stream #0:0 -> #0:0 (copy) 
Press [q] to stop, [?] for help 
[mp4 @ 04f89340] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 85424 >= 85424 
av_interleaved_write_frame(): Invalid argument 
frame= 162 fps=0.0 q=-1.0 Lsize= 1335kB time=00:00:05.33 bitrate=2047.7kbits/s speed=1.82e+03x 
video:1359kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 
Conversion failed! 

rename (1): H:\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpf32752796d18497785751f8d3a98c27e_i.mp4 -> H:\hitomi_downloader_GUI\hitomi_downloaded_youtube\► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4

Fail m3u8 pp : ► Madeon - Pop Culture ＡＭＶ「Anime Mix」1080p ᴴᴰ 】.mp4
Traceback (most recent call last):
File "downloader", line 720, in download
File "m3u8_tools", line 206, in _pp
File "ffmpeg", line 242, in convert
File "ffmpeg", line 234, in convert
Exception: Failed to convert; exit code: 1

stop
valid=False 1
EOT: https://www.youtube.com/watch?v=c7XE-4Ibf8A (6.7s)
```

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by asval9x39** [comment]
와우 감사합니다
