### ISSUE TITLE
Iwara 작가 전체 다운로드시 등록이 안되는 경우가 있습니다.

### ISSUE THREAD

**Issue by Asterlsk** [KurtBestor/Hitomi-Downloader#3239]
늘 감사히 잘 쓰고있습니다.
바쁘실텐데 죄송하지만 Iwara쪽 다운로드에 문제가 생겨 제보합니다.

일부 작가들의 페이지를 다운받으려하면 다운로드가 안되는 현상이 있습니다.

https://ecchi.iwara.tv/users/Mister%20Pink/videos
https://ecchi.iwara.tv/users/forget-skyrim

원인은 모르겠지만 메인페이지가 아니라 video 아래쪽의 see all 버튼을 누르고 비디오만 나와있는 창에서 다운로드하면 문제없이 잘 됩니다.

일부작가들은 해당방법을 사용해도 등록되지 않습니다.

https://ecchi.iwara.tv/users/nana77-shinshi

[Messages]
https://ecchi.iwara.tv/users/nana77-shinshi/videos?page=0
no videos
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\iwara_downloader", line 73, in read
File "utils", line 1401, in process_playlist
Exception: no videos

Invalid: fail=True
EOT: https://ecchi.iwara.tv/users/nana77-shinshi (2.7s)

https://ecchi.iwara.tv/users/nana77-shinshi/videos?page=0
no videos
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\iwara_downloader", line 73, in read
File "utils", line 1401, in process_playlist
Exception: no videos

Invalid: fail=True
EOT: https://ecchi.iwara.tv/users/nana77-shinshi (2.1s)

https://ecchi.iwara.tv/users/nana77-shinshi/videos?page=0
no videos
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\iwara_downloader", line 73, in read
File "utils", line 1401, in process_playlist
Exception: no videos

Invalid: fail=True
EOT: https://ecchi.iwara.tv/users/nana77-shinshi (1.6s)

https://ecchi.iwara.tv/users/steven-purgatory

[Messages]
https://ecchi.iwara.tv/users/steven-purgatory/videos?page=0
no videos
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\iwara_downloader", line 73, in read
File "utils", line 1401, in process_playlist
Exception: no videos

Invalid: fail=True
EOT: https://ecchi.iwara.tv/users/steven-purgatory (2.2s)

https://ecchi.iwara.tv/users/toutetu03

[Messages]
https://ecchi.iwara.tv/users/toutetu03/videos?page=0
no videos
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\iwara_downloader", line 73, in read
File "utils", line 1401, in process_playlist
Exception: no videos

Invalid: fail=True
EOT: https://ecchi.iwara.tv/users/toutetu03 (2.6s)

이 외에도 다수 찾았는데 대부분 닉네임에 하이픈이나 언더바가 들어가있는게 문제같습니다.
하이픈을 +로 바꿔주면 된다는 쓰레드도 봤지만 언더바가 들어있는 경우나

https://ecchi.iwara.tv/users/misaultra

처럼 주소창엔 아무것도 없지만 닉네임에 들어있는 경우도 있습니다.
해결 방법이 있을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Asterlsk** [comment]
확인했습니다.
이제 대부분의 경우 정상적으로 작동합니다.

https://ecchi.iwara.tv/user/91338

이런 예외도 몇몇 보이긴하는데 이부분은 user/ 뒷부분을 닉네임으로 맞춰주면 대부분 followers 페이지로 연결되어 해결됩니다.
이용자분들이 참고하시면 될 것 같습니다. 감사합니다.
