### ISSUE TITLE
지원하는 사이트 중에서

### ISSUE THREAD

**Issue by postnumberpit** [KurtBestor/Hitomi-Downloader#3240]
안녕하세요, 한 가지 여쭤볼 것이 있어서 글을 남깁니다

지원하는 서포트 사이트 들 중에서 

AsianSister 이 사이트는 다운이 안되더군요. 쿠키생성 및 적용해서 해봐도 안되네요.

한번 확인 부탁드립니다.

Invalid: [asiansister] https://asiansister.com/view_2057_ATFMaker____60Pn

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 61 / False / 9368e78aedba41b78376a804d90aab16
input: https://asiansister.com/view_2057_ATFMaker____60Pn
type: asiansister
single: False
url: https://asiansister.com/view_2057_ATFMaker____60Pn
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616461217.0616486 (Mar 23)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 311, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 403, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 384, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1064, in start
File "<decorator-gen-63>", line 2, in init
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\asiansister_downloader", line 16, in init
File "downloader", line 338, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 112, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
quality: 75%
EOT: https://asiansister.com/view_2057_ATFMaker____60Pn (2.3s)

감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2237
