### ISSUE TITLE
제이마나 다운로드 문의

### ISSUE THREAD

**Issue by helpmepls08** [KurtBestor/Hitomi-Downloader#3241]
마지널 오퍼레이션 이라는 만화 제이마나에 있기에 다운로드를 하였습니다.
210312금요일에는 다운로드가 되더라고요. 그런데 몇몇 페이지가 흰색만 있기에 오늘 확인하고 다시 다운로드 해보니까 invalid 가 뜹니다.

https://jmana1.net/comic_list_title?bookname=%EB%A7%88%EC%A7%80%EB%84%90+%EC%98%A4%ED%8D%BC%EB%A0%88%EC%9D%B4%EC%85%98

https://jmana1.net/book?bookid=2785

아예 다른 만화가 다운되건 사이트 문제인가요?

**Comment by duach** [comment]
저도 오늘 사용해보니 제이마나 사이트 아무것도 다운로드가 안되네요;;

Invalid: [jmana] https://jmana1.net/bookdetail?bookdetailid=372224

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 92038c8169934c33977b50bf1825791f
input: https://jmana1.net/bookdetail?bookdetailid=372224
type: jmana
single: False
url: https://jmana1.net/book?bookid=9438
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [0]
time: 1617033069.6618872 (Mar 30)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.25
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no title
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\jmana_downloader", line 84, in read
File "extractor\jmana_downloader", line 78, in name
File "extractor\jmana_downloader", line 98, in get_title
File "ree", line 15, in find
ree.NotFound: no title

Invalid: fail=True
EOT: https://jmana1.net/bookdetail?bookdetailid=372224 (3.4s)
