### ISSUE TITLE
sankaku 404 Client error 여쭤봅니다

### ISSUE THREAD

**Issue by momokoro1** [KurtBestor/Hitomi-Downloader#3244]
안녕하세요. 항상 잘 쓰고 있습니다. 
읽은 장 수가 500을 넘어가면 Invalid를 뿜습니다. 
300 장 아래로 된 작업은 제대로 진행이 되는데, 너무 많으면 문제가 있을까요.
아래에 첨부합니다.

=====================================================

Invalid: [sankaku] https://chan.sankakucomplex.com/?tags=sollyz

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 622 / False / adf5c779fae24aad87a1c116ca5619bb
input: https://chan.sankakucomplex.com/?tags=sollyz
type: sankaku
single: False
url: https://chan.sankakucomplex.com/?tags=sollyz
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616656592.7820518 (Mar 25)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.03.25
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/?tags=sollyz
https://chan.sankakucomplex.com/?next=24758914&tags=sollyz&page=2
https://chan.sankakucomplex.com/?next=24702102&tags=sollyz&page=3
https://chan.sankakucomplex.com/?next=24503194&tags=sollyz&page=4
https://chan.sankakucomplex.com/?next=24503162&tags=sollyz&page=5
https://chan.sankakucomplex.com/?next=24497705&tags=sollyz&page=6
https://chan.sankakucomplex.com/?next=24497006&tags=sollyz&page=7
https://chan.sankakucomplex.com/?next=24496975&tags=sollyz&page=8
https://chan.sankakucomplex.com/?next=24417887&tags=sollyz&page=9
https://chan.sankakucomplex.com/?next=24406790&tags=sollyz&page=10
https://chan.sankakucomplex.com/?next=24311398&tags=sollyz&page=11
https://chan.sankakucomplex.com/?next=24026445&tags=sollyz&page=12
https://chan.sankakucomplex.com/?next=23893327&tags=sollyz&page=13
https://chan.sankakucomplex.com/?next=23893297&tags=sollyz&page=14
https://chan.sankakucomplex.com/?next=23774110&tags=sollyz&page=15
https://chan.sankakucomplex.com/?next=23725991&tags=sollyz&page=16
https://chan.sankakucomplex.com/?next=23122318&tags=sollyz&page=17
https://chan.sankakucomplex.com/?next=23053160&tags=sollyz&page=18
https://chan.sankakucomplex.com/?next=23050458&tags=sollyz&page=19
https://chan.sankakucomplex.com/?next=23027021&tags=sollyz&page=20
https://chan.sankakucomplex.com/?next=23026980&tags=sollyz&page=21
https://chan.sankakucomplex.com/?next=23016602&tags=sollyz&page=22
https://chan.sankakucomplex.com/?next=23001406&tags=sollyz&page=23
https://chan.sankakucomplex.com/?next=22959258&tags=sollyz&page=24
https://chan.sankakucomplex.com/?next=22959238&tags=sollyz&page=25
https://chan.sankakucomplex.com/?next=22959216&tags=sollyz&page=26
404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error
stop
Traceback (most recent call last):
File "downloader", line 293, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\sankaku_downloader", line 107, in read
File "extractor\sankaku_downloader", line 255, in get_imgs
File "downloader", line 344, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=sollyz (47.6s)

types: img, gif, video
https://chan.sankakucomplex.com/?tags=sollyz
https://chan.sankakucomplex.com/?next=24758914&tags=sollyz&page=2
https://chan.sankakucomplex.com/?next=24702102&tags=sollyz&page=3
https://chan.sankakucomplex.com/?next=24503194&tags=sollyz&page=4
https://chan.sankakucomplex.com/?next=24503162&tags=sollyz&page=5
https://chan.sankakucomplex.com/?next=24497705&tags=sollyz&page=6
https://chan.sankakucomplex.com/?next=24497006&tags=sollyz&page=7
https://chan.sankakucomplex.com/?next=24496975&tags=sollyz&page=8
https://chan.sankakucomplex.com/?next=24417887&tags=sollyz&page=9
https://chan.sankakucomplex.com/?next=24406790&tags=sollyz&page=10
https://chan.sankakucomplex.com/?next=24311398&tags=sollyz&page=11
https://chan.sankakucomplex.com/?next=24026445&tags=sollyz&page=12
https://chan.sankakucomplex.com/?next=23893327&tags=sollyz&page=13
https://chan.sankakucomplex.com/?next=23893297&tags=sollyz&page=14
https://chan.sankakucomplex.com/?next=23774110&tags=sollyz&page=15
https://chan.sankakucomplex.com/?next=23725991&tags=sollyz&page=16
https://chan.sankakucomplex.com/?next=23122318&tags=sollyz&page=17
https://chan.sankakucomplex.com/?next=23053160&tags=sollyz&page=18
https://chan.sankakucomplex.com/?next=23050458&tags=sollyz&page=19
https://chan.sankakucomplex.com/?next=23027021&tags=sollyz&page=20
https://chan.sankakucomplex.com/?next=23026980&tags=sollyz&page=21
https://chan.sankakucomplex.com/?next=23016602&tags=sollyz&page=22
https://chan.sankakucomplex.com/?next=23001406&tags=sollyz&page=23
https://chan.sankakucomplex.com/?next=22959258&tags=sollyz&page=24
https://chan.sankakucomplex.com/?next=22959238&tags=sollyz&page=25
https://chan.sankakucomplex.com/?next=22959216&tags=sollyz&page=26
404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error
stop
Traceback (most recent call last):
File "downloader", line 293, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\sankaku_downloader", line 107, in read
File "extractor\sankaku_downloader", line 255, in get_imgs
File "downloader", line 344, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error,%20http://chan.sankakucomplex.com/post/error

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=sollyz (60.9s)

**Comment by momokoro1** [comment]
기존에 등록해뒀던 쿠키가 작동하지 않아서 발생한 문제 같습니다. 
새로이 쿠키를 불러오기하여 작동하는 것을 확인했습니다.
