### ISSUE TITLE
니코동 다운로드가 막힌건가요

### ISSUE THREAD

**Issue by KKK765** [KurtBestor/Hitomi-Downloader#3268]
니코동 회원 전용 동영상이 이전에는 다운로드가 가능했는데 지금은 불가능하게 됐네요
쿠키를 다시 설정하거나 하여도 동일한거 같습니다.

Invalid: [nico] https://www.nicovideo.jp/watch/so38413899

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / b557a715b55a4a21957c4cf4db3f49c3
input: https://www.nicovideo.jp/watch/so38413899
type: nico
single: True
url: https://www.nicovideo.jp/watch/so38413899
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1617328978.7584565 (Apr 2)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.04.01
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
nico retry...
nico retry...
No active exception to reraise
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\nico_downloader", line 71, in read
File "extractor\nico_downloader", line 96, in get_video
RuntimeError: No active exception to reraise

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/so38413899 (3.5s)

**Comment by KKK765** [comment]
회원 전용이 아니여도 안되는 거 같습니다


Invalid: [nico] https://www.nicovideo.jp/watch/sm14044008

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a97345e9dca249c982483d65997e1d68
input: https://www.nicovideo.jp/watch/sm14044008
type: nico
single: True
url: https://www.nicovideo.jp/watch/sm14044008
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1617329154.5972815 (Apr 2)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.04.01
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
nico retry...
nico retry...
No active exception to reraise
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\nico_downloader", line 71, in read
File "extractor\nico_downloader", line 96, in get_video
RuntimeError: No active exception to reraise

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/sm14044008 (3.3s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3215
