### ISSUE TITLE
pornhub 다운오류

### ISSUE THREAD

**Issue by traumang** [KurtBestor/Hitomi-Downloader#3278]
항상 잘쓰고 있습니다~

폰허브 일반, 프리미엄 모두 어제까진 잘됐는데 오늘 갑자기 안되네요

Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph5d4decb7d62ff

version: 3.3a (21-03-22 11:13:37 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 2decad549d094560af5c5b405f77be03
input: https://www.pornhub.com/view_video.php?viewkey=ph5d4decb7d62ff
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph5d4decb7d62ff
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1617741684.4705172 (Apr 7)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.01
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
decode
No videos
stop
Traceback (most recent call last):
File "utils", line 1080, in start
File "utils", line 1131, in start_
File "extractor\pornhub_downloader", line 245, in read
File "utils", line 700, in __call__
File "extractor\pornhub_downloader", line 129, in get
Exception: No videos

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5d4decb7d62ff (4.4s)

**Comment by Miki57** [comment]
I have the exact same issue. it was working perfectly, I was downloading files for 2 hours and suddenly it stopped working. Maybe the issue is with Pornhub.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hoohoohoo507** [comment]
테스트 해봤는데  폰허브 이젠 잘 받아지네요  대단하시네요... 창과 방패의 대결입니다...

**Comment by traumang** [comment]
고맙습니다~~

**Comment by abbs112** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

테스트 히토미 새로 나온 버전 받고 나서부터 exe파일 자체가 실행이 안되는데 해결방법이 있을까요?
작업관리자로 실행해도 동작 자체가 안되고 작업관리자에도 아예 안뜨네요

**Comment by dhffk** [comment]
테스트 버전 실행이 안되고 바이러스가 검출된다고 나오네요. virustotal에서도 마찬가지로 바이러스가 있다고 나옵니다.

**Comment by hoohoohoo507** [comment]
전 테스트 버전 받고 바로 실행 잘되고 노턴 시큐리티 백신 쓰는데  아무이상없이 아무 바이러스 없고 잘 실행 됬네요...

**Comment by Miki57** [comment]
It works perfectly again, thank you! And no virus was detected on my machine.

**Comment by KurtBestor** [comment]
바이러스 있다고 나오는 VirusTotal 링크 주세요.

**Comment by dhffk** [comment]
https://www.virustotal.com/gui/file/7fa254a724d59b9f1c8026cb6af7f9ab1ce8d2278f1ce081d0694829f4e9d62c/detection

**Comment by good1hub2** [comment]
테스트 버전 실행하면 왜 안될까요?

**Comment by KurtBestor** [comment]
@dhffk 
`Jiangmin`, `Yandex`, `Zillya` 백신만 바이러스 있다고 오진하네요. 어떤 백신 쓰시나요?

**Comment by dhffk** [comment]
v3를 쓰지만 거기서도 바이러스로 탐지하네요. 위의 백신에서 나온 trojan 바이러스는 무엇인가요?

**Comment by KurtBestor** [comment]
V3는 탐지 안된다고 나오네요.

**Comment by WadeParker** [comment]
저도 v3쓰는데 멀웨어 뜨면서 파일이 열리지않습니다 v3에서 진단예외로 하고 파일실행해도 되는건가요?

**Comment by KurtBestor** [comment]
바이러스 오진 문제는 제가 어떻게 해드릴 수 있는 게 없어요. 이미 바이러스가 아닌데 뭘 어떻게 하겠어요. 잘못 진단한 백신 잘못이고 해당 백신에 오진이라고 보고 부탁드려요.
