### ISSUE TITLE
다운로더 데이터 다운실패 합니다.

### ISSUE THREAD

**Issue by y5624711** [KurtBestor/Hitomi-Downloader#3287]
Traceback (most recent call last):
  File "hitomi_searcher", line 225, in download_json
  File "hitomi_searcher", line 388, in download_json_
  File "json\__init__", line 348, in loads
  File "json\decoder", line 337, in decode
  File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

갑자기 요렇게 뜨네요

**Comment by KurtBestor** [comment]
재현 불가
