### ISSUE TITLE
이번 업데이트 후 픽시브 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by rlarkakstp** [KurtBestor/Hitomi-Downloader#3289]
항상 감사히 잘 쓰고 있습니다.
이번 업데이트 후 픽시브 다운로드가 안되고 있습니다. 아래와 같은건지는 모르겠습니다..

9분 58초 뒤 다시 시작: https://www.pixiv.net/users/167786

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 0 / False / 62d65f36b46e43ceb902af36916e8866
input: https://www.pixiv.net/users/167786
type: pixiv
single: False
url: https://www.pixiv.net/users/167786
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1617970874.1032798 (Apr 9)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.04.07
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\pixiv_downloader", line 53, in read
File "extractor\pixiv_downloader", line 330, in get_info
File "extractor\pixiv_downloader", line 367, in process_ids
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 227, in get_info
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pixiv.net/users/167786 (0.7s)

**Comment by hoohoohoo507** [comment]
픽시브는 안되네요 이전버전도 다운로드 파일 인식없이 바로 완료되었다고만 나오네요...
