### ISSUE TITLE
 유튜브 영상 오디오 없음 convert 오류 완료 현상.

### ISSUE THREAD

**Issue by erebuseyny** [KurtBestor/Hitomi-Downloader#3322]
유뷰트 영상 다운로드에서 
오디오 없이 영상 다운로드 되는 현상 있습니다.

https://github.com/KurtBestor/Hitomi-Downloader/issues/1701#issuecomment-590234822
를 참고하였으나, 
코덱과 플레이어 문제는 아닌 것 같습니다.
https://github.com/Nevcairiel/LAVFilters/releases/tag/0.75
최신버전으로 설치 후 다시 실행해도 동일한 현상 나옵니다.

샤나 인코더(인코딩 프로그램)에서 파일 정보를 보았을 때, 
팟플레이어서 재생 후, 파일정보를 보았을 때

오디오 없음으로 나옵니다.

현상.
1.  파일 모두 100% 에서  ! 표시가 뜨면서, 다시 시작합니다.  재시작 후 바로 완료.
2. 완료 후, 다운로드 폴더 내에 tmp~~~~_o.mp4 파일들 존재.
3. 작업정보에서 convert 오류 관련 기록

Convert: P:\00_Downloader_P\hitomi_downloaded_youtube\경제학 강의\2020년 감정평가사 경제학원론 41~43번 풀이 (2020. 6. 13. 시행) (fRouP27wFKM).mp4
rename (1): P:\00_Downloader_P\hitomi_downloaded_youtube\경제학 강의\2020년 감정평가사 경제학원론 41~43번 풀이 (2020. 6. 13. 시행) (fRouP27wFKM).mp4 -> P:\00_Downloader_P\hitomi_downloaded_youtube\경제학 강의\tmp03c72b0301cf495796277ff6ad6ac881_i.mp4
-i tmp03c72b0301cf495796277ff6ad6ac881_i.mp4 -acodec copy -vcodec copy tmp03c72b0301cf495796277ff6ad6ac881_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
1
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, matroska,webm, from 'tmp03c72b0301cf495796277ff6ad6ac881_i.mp4': 
Metadata: 
encoder : google/video-file 
http://youtube.com/streaming/otf/durations/112015: Segment-Count: 147 
: Segment-Durations-Ms: 5339,5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),533 
: 
: 
Duration: N/A, start: 0.000000, bitrate: N/A 
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default) 
Output #0, mp4, to 'tmp03c72b0301cf495796277ff6ad6ac881_o.mp4': 
Metadata: 
http://youtube.com/streaming/otf/durations/112015: Segment-Count: 147 
: Segment-Durations-Ms: 5339,5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),5338,5339(r=1),533 
: 
: 
encoder : Lavf58.20.100 
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 16k tbn, 1k tbc (default) 
Stream mapping: 
Stream #0:0 -> #0:0 (copy) 
Press [q] to stop, [?] for help 
[mp4 @ 06978f40] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 85424 >= 85424 
av_interleaved_write_frame(): Invalid argument 
frame= 162 fps=0.0 q=-1.0 Lsize= 167kB time=00:00:05.33 bitrate= 255.6kbits/s speed= 281x 
video:200kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 
Conversion failed! 

rename (1): P:\00_Downloader_P\hitomi_downloaded_youtube\경제학 강의\tmp03c72b0301cf495796277ff6ad6ac881_i.mp4 -> P:\00_Downloader_P\hitomi_downloaded_youtube\경제학 강의\2020년 감정평가사 경제학원론 41~43번 풀이 (2020. 6. 13. 시행) (fRouP27wFKM).mp4

Fail m3u8 pp : 2020년 감정평가사 경제학원론 41~43번 풀이 (2020. 6. 13. 시행) (fRouP27wFKM).mp4
Traceback (most recent call last):
File "downloader", line 720, in download
File "m3u8_tools", line 206, in _pp
File "ffmpeg", line 242, in convert
File "ffmpeg", line 234, in convert
Exception: Failed to convert; exit code: 1

stop

감사합니다.

**Comment by STR-HK** [comment]
저는 정상적으로 변환 완료 후에
팟플레이어로 테스트해보니 잘 나옵니다.
다운로더 문제는 아닌 것 같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3282

**Comment by erebuseyny** [comment]
> 참고해주세요: #3282

감사합니다. 잘 됩니다.

**Comment by erebuseyny** [comment]
> 저는 정상적으로 변환 완료 후에
> 팟플레이어로 테스트해보니 잘 나옵니다.
> 다운로더 문제는 아닌 것 같습니다.

감사합니다. 잘 됩니다.
