### ISSUE TITLE
같은 사이트의 목록 주소를 넣었는데 다르게 작동합니다.

### ISSUE THREAD

**Issue by 666hyun** [KurtBestor/Hitomi-Downloader#3324]
luvhug.net 의 목록 주소를 넣으면 다른 목록은 다 정상으로 다운을 받는데 딱 한개 목록이 받아지지 않습니다.
대충 20개 정도를 시험해 봤는데

https://lovehug.net/332/

이 목록만 지원하지 않는 사이트 주소를 입력한 것 처럼 목록 주소를 입력하라고 뜹니다.

목록 주소를 입력해주세요: https://lovehug.net/332/

version: 3.3a (21-04-14 14:32:07 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 1 / False / 1d224cf20d7849ef82020f56ce24f2cb
input: https://lovehug.net/332/
type: lhscan
single: False
url: https://lovehug.net/332/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1619180708.1139102 (Apr 23)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.17
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (3.6s)

stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (3.7s)

stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (3.7s)

stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (3.8s)

stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (3.8s)

stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (3.6s)

stop
Invalid: fail=False
EOT: https://lovehug.net/332/ (4.0s)

**Comment by STR-HK** [comment]
https://lovehug.net/332/ 들어가면 그냥 메인 페이지로 이동되는 것 같아요

**Comment by 666hyun** [comment]
> https://lovehug.net/332/ 들어가면 그냥 메인 페이지로 이동되는 것 같아요

제가 들어가면 나의 히어로 아카데미아 목록으로 넘어가집니다.
예전에는 저도 목록주소가 메인 페이지로 넘어가버리는걸 두어번 보긴 했는데
언제부터인지 정상으로 목록이 봐지더라구요.

**Comment by STR-HK** [comment]
![image](https://user-images.githubusercontent.com/78652371/116052079-406ad780-a6b4-11eb-85c7-90ac4a821c61.png)

검색해서 들어가니
https://lovehug.net/332/50629/ 링크가 나오는데
이 링크도 메인페이지로 자동으로 리다이렉트 되는 것 같네요

**Comment by 666hyun** [comment]
> ![image](https://user-images.githubusercontent.com/78652371/116052079-406ad780-a6b4-11eb-85c7-90ac4a821c61.png)
> 
> 검색해서 들어가니
> https://lovehug.net/332/50629/ 링크가 나오는데
> 이 링크도 메인페이지로 자동으로 리다이렉트 되는 것 같네요
> 
> 해결 여부는 불확실하지만
> 혹시 view-source:https://lovehug.net/332/50629/ 로 들어가서 나오는 것 보여주실 수 있을까요
> ( 크롬기준 )

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbBPn4w%2Fbtq3zoxEaeM%2F4LqQwiYeTMdI67qkwBFDik%2Fimg.png)

만화 페이지가 정상 출력됩니다.

**Comment by KurtBestor** [comment]
로그인이 필요한 페이지네요. 로그인을 하지 않으면 에러 메시지를 띄우게 했어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by charlificate** [comment]
될듯 하다가 또 안되네요... Reading에서 챕터10 까지만 읽더니 Invalid: [lhscan] 오류가 떠요. 로그인 한 쿠키 적용해서 시도했었습니다.

Invalid: [lhscan] https://welovemanga.net/599/

version: 3.6 (21-10-10 16:46:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 0 / False / 7591ae9fe6e8419f830a418769d8c818
input: https://welovemanga.net/599/
type: lhscan
single: False
url: https://welovemanga.net/599/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1633921766.1513026 (11 Oct)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
https://welovemanga.net/599/ -> https://welovemanga.net/599/
Please type a list URL: https://welovemanga.net/599/
stop
Traceback (most recent call last):
File "utils", line 1124, in start
File "extractor\lhscan_downloader", line 63, in init
errors.Invalid: Please type a list URL: https://welovemanga.net/599/

Invalid: fail=False
EOT: https://welovemanga.net/599/ (6.4s)

no html
no html
https://welovemanga.net/599/ -> https://welovemanga.net/599/
Chapter 1
https://s2.ihlv1.xyz/images/20190914/0a03f57c958fd7e71706ee78ced0ba72001.jpg

Chapter 2
https://s2.ihlv1.xyz/images/20190914/a068a188592719b591707abf1d9f2ce2001.jpg

Chapter 3
https://s2.ihlv1.xyz/images/20210122/35a4c6e0fcd3be58c8f5128b1d47b1ea055.jpg

Chapter 4
https://s2.ihlv1.xyz/images/20210122/5fbf7c398ea9418c40b73506e371868f075.jpg

Chapter 5
https://s2.ihlv1.xyz/images/20210122/6aacede33803d0f2ba8645a6846a28e1093.jpg

Chapter 6
https://s2.ihlv1.xyz/images/20210122/1b7b80ecfc61de501141b6d9253e38d5111.jpg

Chapter 7
https://s2.ihlv1.xyz/images/20210122/5b3d529a8ecb4883b535414a9aea77f9129.jpg

Chapter 8
https://s2.ihlv1.xyz/images/20210122/ab6c9006bb3a0616a63d86691bf08140147.jpg

Chapter 9
https://s2.ihlv1.xyz/images/20210122/aacd241d39b1b30e809dbe513717d651165.jpg

Chapter 10
https://s2.ihlv1.xyz/images/20210122/dbeeb88e1732ac017d986f7dab905288005.jpg

Chapter 11
Chapter 11
Chapter 11
Chapter 11
Chapter 11
Chapter 11
Chapter 11
Chapter 11
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
empty html
stop
Traceback (most recent call last):
File "utils", line 1138, in start
File "utils", line 1208, in start_
File "extractor\lhscan_downloader", line 93, in read
File "<decorator-gen-45>", line 2, in get_imgs
File "constants", line 909, in wrapper
File "constants", line 880, in wrapper
File "extractor\lhscan_downloader", line 185, in get_imgs
File "<decorator-gen-43>", line 2, in get_imgs_page
File "constants", line 909, in wrapper
File "constants", line 880, in wrapper
File "extractor\lhscan_downloader", line 108, in get_imgs_page
Exception: empty html

Invalid: fail=True
EOT: https://welovemanga.net/599/ (26.3s)

**Comment by KurtBestor** [comment]
이거 그냥 크롬으로 봐도 됐다 안됐다 하네요. 

디스코드 들어가니까 그런 경우는 공식 앱을 쓰라는데:
![image](https://user-images.githubusercontent.com/14768120/137421554-709b55a0-fb42-43d8-a1eb-2b50e34b03b8.png)

공식 앱 뜯어보니 https://beta.lovehug.net 여기서 가져오네요.
이건 문제 없이 작동해요.
