### ISSUE TITLE
카카페 변경된 데이터방식에 대해

### ISSUE THREAD

**Issue by ggasdf99** [KurtBestor/Hitomi-Downloader#3334]
카카페도 소설을 점점 epub형식으로 올리기 시작해서
이런 작품들은 기존 방식으로 다운이 안되는데
호환 업데이트 부탁드릴수있을까요
업데이트 예정이시라면 대략 언제까지 가능할지도 알고싶습니다

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by ggasdf99** [comment]
Invalid: [kakaopage] https://page.kakao.com/home?seriesId=56017429

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 3e8434d497284dd3a50344e9d41f42d1
input: https://page.kakao.com/home?seriesId=56017429
type: kakaopage
single: False
url: https://page.kakao.com/home?seriesId=56017429
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [0, 1]
time: 1619586064.3836932 (Apr 28)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.26
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
tid: edb0a06e59f246678454cd08a89133f7
Dr. 신선한 미래를 보는 의사 1화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 120, in get_imgs_page
KeyError: 'secureUrl'

Dr. 신선한 미래를 보는 의사 2화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 120, in get_imgs_page
KeyError: 'secureUrl'

no imgs
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 179, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/home?seriesId=56017429 (7.4s)

**Comment by ggasdf99** [comment]
epub 형식의 다른작품에서 다른 로그가 보여 첨부합니다


[카규 쿠모] 고블린 슬레이어 [단독선공개]

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 58 / False / 2b999b56fd2e49f6813e69b1b0f0db4d
input: https://page.kakao.com/home?seriesId=51859696
type: kakaopage
single: False
url: https://page.kakao.com/home?seriesId=51859696
dir: downloaded_kaka\[카규 쿠모] 고블린 슬레이어 [단독선공개]
zip: 
artist: 카규 쿠모
valid / done: False / True
range / range_p: None / None
time: 1620086121.521514 (May 4)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.26
pinned: False
extras: {}
changed: True


[Gallery]
None

.
.
.


[URLs]



[Messages]
tid: edb0a06e59f246678454cd08a89133f7
고블린 슬레이어 12권 1화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 117, in get_imgs_page
Exception: 웹에서 볼 수 없는 상품입니다.

고블린 슬레이어 12권 2화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 117, in get_imgs_page
Exception: 웹에서 볼 수 없는 상품입니다.
.
.
.


고블린 슬레이어 13권 70화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 117, in get_imgs_page
Exception: 웹에서 볼 수 없는 상품입니다.

no imgs
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 179, in get_info
Exception: no imgs

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/home?seriesId=51859696 (260.7s)

**Comment by KurtBestor** [comment]
현재는 웹에서 볼 수 있는 작품만 지원하고 있어요
