### ISSUE TITLE
기본데이터가 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by Lecture911** [KurtBestor/Hitomi-Downloader#3335]
Traceback (most recent call last):
  File "hitomi_searcher", line 205, in download_json
  File "hitomi_searcher", line 355, in download_json_
  File "os", line 223, in makedirs
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'D:\\Mine\\SSSS\\(1)hitomi_downloader_GUI\\hitomi_data'

어느날 갑자기 기존 작업들도 목록에서 다 사라진 뒤 기본 데이터가 다운로드 되지 않습니다.

**Comment by KurtBestor** [comment]
백신이 막고있는 것 같은데 예외 목록에 추가해주세요
