### ISSUE TITLE
픽시브 다운받는데 중간에서 멈춥니다.

### ISSUE THREAD

**Issue by e233kei** [KurtBestor/Hitomi-Downloader#3339]
전에 중간에서 멈추지 않았던데, 요새따라 중간에서 계속 멈추네요.
쿠키 파일도 재업데이트 해봤지만 역부족이었습니다.

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 4 / False / 7250d40b12bf4dd8aa6b5f9218aade26
input: https://www.pixiv.net/users/12178176/bookmarks/artworks
type: pixiv
single: False
url: https://www.pixiv.net/users/12178176/bookmarks/artworks
dir: hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)
zip: 
artist: None
valid / done: True / True
range / range_p: ~ 400000 / None
time: 1619354958.8418992 (Apr 25)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.04.17
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\86784778_p0.jpg
[0002] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\85209046_p0.jpg
[0003] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\89296548_p0.jpg
.
.
.
[2354] LazyUrl(https://www.pixiv.net/en/artworks/79466990) ---> 【local_lazy】 79466990_p0.jpg
[2355] LazyUrl(https://www.pixiv.net/en/artworks/86624891) ---> 【local_lazy】 86624891_p0.png
[2356] LazyUrl(https://www.pixiv.net/en/artworks/86220940) ---> 【local_lazy】 86220940_p0.png

[Messages]
tags: []
tags_ex: []
process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 403 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 403 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 364, in process_ids
File "extractor\pixiv_downloader", line 224, in get_info
File "extractor\pixiv_downloader", line 94, in illust
File "<decorator-gen-12>", line 2, in call
File "constants", line 876, in wrapper
File "constants", line 847, in wrapper
File "extractor\pixiv_downloader", line 87, in call
extractor.pixiv_downloader.HTTPError: 403 Client Error

stop
EOT: https://www.pixiv.net/users/12178176/bookmarks/artworks (588.6s)

**Comment by KurtBestor** [comment]
삭제되거나 비공개 처리된 이미지는 다운로드하지 못해요.
