### ISSUE TITLE
video.fc2 unable to establish connection for download

### ISSUE THREAD

**Issue by khowjy** [KurtBestor/Hitomi-Downloader#3349]
Unable to download from video.fc2, system failed to establish connection. Tried with both VPN active and disabled. Video is a public video labeled "Everyone", so the paid system shouldn't be the factor.

Sample:

Invalid: [fc2] https://video.fc2.com/a/content/20210204GTKKnAbQ

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 0 / False / 57e069eb6e19491898ab2810fc9eaa53
input: https://video.fc2.com/a/content/20210204GTKKnAbQ
type: fc2
single: True
url: https://video.fc2.com/a/content/20210204GTKKnAbQ
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1619534363.899521 (Apr 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.26
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
HTTPSConnectionPool(host='video.fc2.com', port=443): Max retries exceeded with url: /a/content/20210204GTKKnAbQ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5DABB20C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1439, in connect
File "http\client", line 944, in connect
File "socket", line 728, in create_connection
File "socket", line 716, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connection", line 170, in _new_conn
File "urllib3\util\connection", line 96, in create_connection
File "urllib3\util\connection", line 86, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 353, in connect
File "urllib3\connection", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001E5DABB20C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 756, in urlopen
File "urllib3\util\retry", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='video.fc2.com', port=443): Max retries exceeded with url: /a/content/20210204GTKKnAbQ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5DABB20C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\fc2_downloader", line 26, in read
File "extractor\fc2_downloader", line 59, in get_info
File "downloader", line 330, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video.fc2.com', port=443): Max retries exceeded with url: /a/content/20210204GTKKnAbQ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5DABB20C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Invalid: fail=True
EOT: https://video.fc2.com/a/content/20210204GTKKnAbQ (7.1s)

**Comment by KurtBestor** [comment]
That video is no longer available.

**Comment by khowjy** [comment]
Account of uploader was removed it seems. Testing with another video. 

Invalid: [fc2] https://video.fc2.com/a/content/20210425HPsedbGb

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 0 / False / 92799dec8b56444bbe88fe9fdc342647
input: https://video.fc2.com/a/content/20210425HPsedbGb
type: fc2
single: True
url: https://video.fc2.com/a/content/20210425HPsedbGb
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1621010862.8547816 (May 15)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.26
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
HTTPSConnectionPool(host='video.fc2.com', port=443): Max retries exceeded with url: /a/content/20210425HPsedbGb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C1328C7788>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1439, in connect
File "http\client", line 944, in connect
File "socket", line 728, in create_connection
File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connection", line 170, in _new_conn
File "urllib3\util\connection", line 96, in create_connection
File "urllib3\util\connection", line 86, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 353, in connect
File "urllib3\connection", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C1328C7788>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 756, in urlopen
File "urllib3\util\retry", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='video.fc2.com', port=443): Max retries exceeded with url: /a/content/20210425HPsedbGb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C1328C7788>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\fc2_downloader", line 26, in read
File "extractor\fc2_downloader", line 59, in get_info
File "downloader", line 330, in read_html
File "requests\api", line 76, in get
File "requests\api", line 61, in request
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video.fc2.com', port=443): Max retries exceeded with url: /a/content/20210425HPsedbGb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C1328C7788>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Invalid: fail=True
EOT: https://video.fc2.com/a/content/20210425HPsedbGb (15.4s)

**Comment by KurtBestor** [comment]
Can't reproduce on my end:
![image](https://user-images.githubusercontent.com/14768120/118319146-58a47880-b535-11eb-8b8c-5a7739e3011e.png)

**Comment by khowjy** [comment]
Seems to be a VPN connection issue. Using the VPNGate client to test seems to work fine then.
