### ISSUE TITLE
카카페 연령제한 재다운오류

### ISSUE THREAD

**Issue by ggasdf99** [KurtBestor/Hitomi-Downloader#3368]
연령제한작품을 유저에이전트 입력해서 다운완료한뒤
다음날쯤 다시시작으로 재다운로드를 시도하면 항상 실패합니다

유저에이전트가 변경되지도 않았고 다시 콘솔에 입력한뒤 시도했구요
기존작업을 지우고 새로 링크를 입력하면 성공하지만
다시시작이 가능하게 되었으면 합니다
그리고 변경된 유저에이전트를 입력후 재시도했을때도 가능했으면 좋겠습니다

작업정보 첨부합니다

[카규 쿠모] 고블린 슬레이어 [단독선공개]

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 58 / False / 2b999b56fd2e49f6813e69b1b0f0db4d
input: https://page.kakao.com/home?seriesId=51859696
type: kakaopage
single: False
url: https://page.kakao.com/home?seriesId=51859696
dir: downloaded_kaka\[카규 쿠모] 고블린 슬레이어 [단독선공개]
zip: 
artist: 카규 쿠모
valid / done: False / True
range / range_p: None / None
time: 1620086121.521514 (May 4)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.26
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]
[0001] downloaded_kaka\[카규 쿠모] 고블린 슬레이어 [단독선공개]\고블린 슬레이어 1권 1화\0000.jpg
[0002] downloaded_kaka\[카규 쿠모] 고블린 슬레이어 [단독선공개]\고블린 슬레이어 1권 1화\0001.jpg
[0003] downloaded_kaka\[카규 쿠모] 고블린 슬레이어 [단독선공개]\고블린 슬레이어 1권 1화\0002.jpg
.
.
.

[URLs]

[Messages]
tid: edb0a06e59f246678454cd08a89133f7
고블린 슬레이어 1권 1화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 117, in get_imgs_page
Exception: 연령 제한 실패

고블린 슬레이어 1권 2화 0
Traceback (most recent call last):
File "extractor\kakaopage_downloader", line 166, in get_info
File "<decorator-gen-76>", line 2, in get_imgs_page
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\kakaopage_downloader", line 117, in get_imgs_page
Exception: 연령 제한 실패
.
.
.

no imgs
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 179, in get_info
Exception: no imgs

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/home?seriesId=51859696 (260.7s)

**Comment by ggasdf99** [comment]
그렇게 하는게 맞습니다.   ' ' 사이에 유저에이전트
엣지는 안되고 크롬은 정상작동하더라구요. 다른브라우저 쓰시면 크롬으로 해보시고
유저에이전트는 바뀔수있으니 그때그때 확인해서 넣어보세요
저도 이정도밖에는 모르겠네요

**Comment by jmj050716** [comment]
혹시 콘솔에 유저에이전트 넣으면 어떻게 되는지 사진으로 볼 수 있을까요? 저는 크롬으로 제대로 몇번이고 해도 자꾸 SyntaxError: Unexpected identifier이게 뜨네요ㅠㅠㅠ 도대체 뭐가 잘못된건지 잘 모르겠네요...

**Comment by jmj050716** [comment]
에러는 유저에이전트를 집어넣고 엔터키를 누르면 바로 나옵니다...

**Comment by KurtBestor** [comment]
다시 로그인하면 쿠키가 달라지기 때문에 다시 넣어야하고, 작업 지우지 않고 다시 시작해도 돼요.

**Comment by ggasdf99** [comment]
당연히 쿠키도 유저에이전트도 다시 갱신해서 넣었습니다

크롬으로 로그인, 쿠키랑 유저에이전트 새로 따놓고
프로그램 키고 쿠키랑 유저에이전트 적용하고

바로 기존 연령제한 목록 다시시작 > 실패

신규 연령제한 작업 추가 > 성공

이후 기존 연령제한 목록 다시시작 > 성공


시간 순서대로 작동한 결과입니다
이처럼 처음엔 다시시작이 실패했다가
신규작업 하나 걸어서 성공시키고나면 제대로 작동합니다
무조건 실패도 성공도 아닌걸로 봐서는 절차의 문제가 아니라고 생각됩니다

**Comment by KurtBestor** [comment]
테스트해봤는데 제현할 수가 없네요.

**Comment by ggasdf99** [comment]
그럼 어쩔수없네요ㅠ 그냥 써야할듯
감사합니다

**Comment by ggasdf99** [comment]
이젠 신규작업 추가해도 안되네요
로그에는 그냥 연령제한 실패라고만 뜨고..
