### ISSUE TITLE
이렇게 나오면서 더이상 다운로드가 진행되지않습니다

### ISSUE THREAD

**Issue by dxoer** [KurtBestor/Hitomi-Downloader#3385]
: \\?\F:\hitomi_downloader_GUI (2)\hitomi_downloaded_manamoa\[미야지마 레이지] 여친, 빌리겠습니다\여친, 빌리겠습니다 69화\0004.jpg
Traceback (most recent call last):
File "downloader", line 855, in download
Exception: 403

**Comment by dxoer** [comment]
Fail : \\?\F:\hitomi_downloader_GUI (2)\hitomi_downloaded_manamoa\[미야지마 레이지] 여친, 빌리겠습니다\여친, 빌리겠습니다 69화\0003.jpg
Traceback (most recent call last):
File "downloader", line 855, in download
Exception: 403

**Comment by dxoer** [comment]
진행이 느린거지 다운로드가 안되는건 아니었네요 죄송합니다
