### ISSUE TITLE
Hanime.TV의 영상들이 다운로드가 안됩니다. I can't download videos from Hanime.TV.

### ISSUE THREAD

**Issue by wozms456** [KurtBestor/Hitomi-Downloader#3397]
히토미 다운로더 버전은 최근 것으로 업데이트 했는데, Hanime.TV의 영상들이 다운로드 안됩니다. 밑에 오류가 난 작업정보들인데 뭐가 문제인 것인가요?? 제가 무언가 조건을 채우지 않아서 작동을 하지 않는건가요??

I updated Hitomi Downloader version to the latest version, but Hanime cannot be downloaded. I'm attaching the task information below. Is it not working because I didn't meet the download requirements?

nvalid: [hanime] https://hanime.tv/videos/hentai/kuroinu-1

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 2a10363d7b964de98642121efddd85ee
input: https://hanime.tv/videos/hentai/kuroinu-1
type: hanime
single: True
url: https://hanime.tv/videos/hentai/kuroinu-1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1621150356.347679 (May 16)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.04.26
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 421, in connect
File "urllib3\util\ssl_", line 429, in ssl_wrap_socket
File "urllib3\util\ssl_", line 472, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 756, in urlopen
File "urllib3\util\retry", line 532, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 421, in connect
File "urllib3\util\ssl_", line 429, in ssl_wrap_socket
File "urllib3\util\ssl_", line 472, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\hanime_downloader", line 45, in read
File "<decorator-gen-56>", line 2, in get_video
File "constants", line 882, in wrapper
File "constants", line 853, in wrapper
File "extractor\hanime_downloader", line 61, in get_video
File "downloader", line 325, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://hanime.tv/videos/hentai/kuroinu-1 (2.5s)

**Comment by STR-HK** [comment]
DPI 우회 키시고 시도해 보시겠어요?
