### ISSUE TITLE
마나토끼에서 받는 자료 대다수가 다 96~98%에서 멈춰버립니다.

### ISSUE THREAD

**Issue by mooncros** [KurtBestor/Hitomi-Downloader#3408]
그래서 혹시 페이지에 문제가 있나 싶어서 가보면 이미지 멀쩡히 잘 로드 되어서 뭐가 문제인지 모르겠습니다

Fail : \\?\D:\New Folder\downloader_GUI\hitomi_downloaded_manatoki\[오카모토 린] 패러렐 파라다이스\패러렐 파라다이스 64화\0010.gif
Traceback (most recent call last):
File "downloader", line 858, in download
Exception: 404

Fail : \\?\D:\New Folder\downloader_GUI\hitomi_downloaded_manatoki\[오카모토 린] 패러렐 파라다이스\패러렐 파라다이스 64화\0011.jpg
Traceback (most recent call last):
File "downloader", line 858, in download
Exception: 403

대부분 이렇게 에러가 나더라고요
도움 주시면 감사하겠습니다!

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by mooncros** [comment]
마나토끼 서버가 오류나서 사이트가 멈췄을때 뭔가 이상한 느낌으로 완료되고 나중에 보니 파일없고 그러더군요. 제대로 받아지는건 받아지는데 320여개 중에 한 20여개가 사이트도 말쩡한데 다운이 안되네요(내부 창으로 확인했을때 멀쩡했어요)
