### ISSUE TITLE
weibo가 안되네요

### ISSUE THREAD

**Issue by fuck1234321** [KurtBestor/Hitomi-Downloader#3409]
no html
uid: 6026734981, oid:1005056026734981
p:1, albums:2
p:2, albums:2
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
File "utils", line 1083, in start
File "utils", line 1134, in start_
File "extractor\weibo_downloader", line 48, in read
File "extractor\weibo_downloader", line 164, in get_imgs
File "<decorator-gen-123>", line 2, in get_album_imgs
File "constants", line 898, in wrapper
File "constants", line 869, in wrapper
File "extractor\weibo_downloader", line 119, in get_album_imgs
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://weibo.com/u/6026734981 (15.9s)

검색했는데 비슷한 이슈 있어서 QR코드 로그인이 아닌 아이디 계정 로그인하고 쿠키를 사용했음에도 작동을 안하네요...
https://weibo.com/u/6026734981 여기 코스프레 사진들 퍼오려고 했는데 안됐습니다...
4월 업데이트 최신버젼에서 버젼 문제일까 하고 현재 버젼은 5.17업데이트 테스트 버젼으로 올렸는데도 안되네요

프로그램 굉장히 감사히 잘 사용하고 있으며,
저만 문제가 있는건지도 모르고, 해결해달라는 것도 아니며
그냥 버그 리포트의 개념으로만 글 남깁니다.
감사합니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/120748461-c5f86780-c53d-11eb-8fd9-7da514df75a0.png)

재현할 수가 없네요
