### ISSUE TITLE
쏘걸 일부 카테고리 영상 작업 에러 

### ISSUE THREAD

**Issue by asdfdf05** [KurtBestor/Hitomi-Downloader#3412]
특정 카테고리 안에 있는 영상은 좌표를 찍어도 사이트를 못찾는다고 다운이 안됨니다. 

ex) https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/

- [ ] `작업에러 `

Unknown site: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 9 / False / 1af1f3d3a73b432babf6b5f41411db2e
input: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
type: sogirl
single: False
url: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1621533108.824899 (May 21)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 24, in read
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (1.7s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 24, in read
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (1.9s)

stop
Invalid: fail=False
EOT: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (0.0s)

stop
Invalid: fail=False
EOT: https://kr19.sogirl.co/jul-572-%eb%ac%b4%ed%86%a0%ec%9a%b0-%ec%95%84%ec%95%bc%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (0.0s)

**Comment by shyeen9999** [comment]
쏘걸 6월8일 상단과 동일한 증상으로 다운이 안됩니다
