### ISSUE TITLE
픽시브 다운로드가 안됩니다....;;

### ISSUE THREAD

**Issue by nell8988** [KurtBestor/Hitomi-Downloader#3414]
Login required; Update your cookies
https://www.pixiv.net/users/42202365/artworks

version: 3.3b (21-05-17 19:58:29 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 778cbd0d19a444b2bf9b9d82e4ff6d1b
input: https://www.pixiv.net/users/42202365/artworks
type: pixiv
single: False
url: https://www.pixiv.net/users/42202365/artworks
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1621629320.6561167 (May 22)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
8 / 32
process_ids error (id: 88726659, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 87541123, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 87211399, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 85659494, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 86944092, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 85951431, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 85900595, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 86696473, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 85533127, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 84364602, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 83806385, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 83596407, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 85044747, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 83618637, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 83573276, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 82942782, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 82818095, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 79879247, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 79834638, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 80691437, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 80398012, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 80720012, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 79386492, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 78327821, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 78260239, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 77289589, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 77143227, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 77043601, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 76911229, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 78153156, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 77450911, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

process_ids error (id: 77828518, d:0):
Traceback (most recent call last):
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

stop
Traceback (most recent call last):
File "utils", line 1083, in start
File "utils", line 1134, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 389, in get_info
File "extractor\pixiv_downloader", line 467, in process_ids
File "extractor\pixiv_downloader", line 442, in run
File "extractor\pixiv_downloader", line 257, in get_info
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pixiv.net/users/42202365/artworks (1.7s)

**Comment by STR-HK** [comment]
픽시브 쿠키 추가가 필요한 것으로 보입니다.
방법은 `도움말` 또는 #3178 참고해 주세요.
