### ISSUE TITLE
다운로드가 불가능한 현상

### ISSUE THREAD

**Issue by NounKim** [KurtBestor/Hitomi-Downloader#3416]
히토미에서 받는 모든 자료에 대해서 다운로드가 안됩니다.

아래는 로그 중 하나입니다.

5분 21초 뒤 다시 시작: [Kaede] ラナリア-ロリサキュバスとの甘々ライフ♥ (1888027)

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1221 / False / a17d5322c80444efbb597fcd5c32a602
input: [Kaede] ラナリア-ロリサキュバスとの甘々ライフ♥ (1888027)
type: ehen
single: False
url: 1888027
dir: hitomi_downloaded\[Kaede] [Anemone＊ (Yuka)] Lanalia - Loli Succubus to no ama ama life♥ (1888027)
zip: 
artist: kaede
valid / done: False / True
range / range_p: None / None
time: 1621679985.3889349 (May 22)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: False

[Gallery]
갤러리 넘버: 1888027

제목: [Anemone* (Yuka)] Lanalia - Loli Succubus to no ama ama life♥

작가: kaede

그룹: anemone

타입: artistcg

시리즈: N/A

캐릭터: N/A

태그: male:sole male, female:demon girl, female:loli, female:sole female, female:assjob, female:blowjob, female:handjob, female:tailjob, mosaic censorship, female:nakadashi, female:stockings, female:urination

언어: N/A

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/cg/%E3%83%A9%E3%83%8A%E3%83%AA%E3%82%A2-%E3%83%AD%E3%83%AA%E3%82%B5%E3%82%AD%E3%83%A5%E3%83%90%E3%82%B9%E3%81%A8%E3%81%AE%E7%94%98%E3%80%85%E3%83%A9%E3%82%A4%E3%83%95%E2%99%A5-%E6%97%A5%E6%9C%AC%E8%AA%9E-1888027.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi", line 109, in pop_img
File "gallery", line 392, in get_gallery_url
File "gallery", line 374, in solve_redirect
File "downloader", line 346, in read_html
Exception: 404

Traceback (most recent call last):
File "downloader", line 303, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 336, in read_html
File "requests\models", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1888027.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 563, in read
File "hitomi_downloader", line 431, in get_imgs
File "hitomi", line 119, in pop_img
File "hitomi", line 34, in get_data
File "downloader", line 346, in read_html
Exception: 404

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 621, in read
Exception: no imgs

stop
Invalid: fail=False
stop
EOT: #-*- [Kaede] ラナリア-ロリサキュバスとの甘々ライフ♥ (1888027) (33.6s)

**Comment by KurtBestor** [comment]
디스코드에서 처리 완료
