### ISSUE TITLE
사용자 리트윗 항목 포함 다운로드 옵션 건의

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#3429]
검색해보니 이 부분은 질문하신 분이 없어서 한번 질문 올려봅니다!🙏

트위터를 다운받을때 사용자가 리트윗한 항목까지 모두 크롤링 할수 있는 기능도 옵션으로 구현이 가능할까요?

**Comment by tdi2020** [comment]
앗 혹시 다음 업데이트에 추가될 예정이 있는지 궁금합니다! 😭

**Comment by KurtBestor** [comment]
아마 이번 년도 안엔 되지 않을까 싶어요

**Comment by tdi2020** [comment]
도르륵... 혹시 이 기능이 이번 년도 안에 업데이트 될 가능성도 있을까요? 여전히 기다리고 있지만 아직 소식이 없어서요😭
항상 잘 사용하고 있습니다 선생님!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
헉 감사합니다! 두가지 타입의 계정을 테스트 해본 결과입니다.

1) 기존에 쿠키로 다운되던 계정들
일반 다운로드는 잘 되지만, 리트윗한 것은 다운받지 않았습니다! 기존 다운로드 기능과 동일한 모습이에요.
(쿠키 넣은 후 작동)

2) 본인 계정에 올린 것이 없고 리트윗만 존재하는 계정 (테스트 계정: https://twitter.com/Tham47844662 )
Login required; Update your cookies 가 표시되면서 아무것도 읽지 못합니다.
역시 1번과 동일한 쿠키이니까 쿠키에는 문제가 없는것 같아요.

+ 그런데 실제 구현이 될때는 리트윗을 포함해서 받을지, 아닐지 선택할 수 있는 부분이 당연히 생성되나요?
지금은 보이지 않아서 그냥 다운로드를 시도한 결과입니다!



아래는 시도했던 로그입니다.--------------------------------------------------

Login required; Update your cookies
https://twitter.com/Tham47844662

version: 3.7m (22-06-11 05:23:32 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 274bacb038ec44188deac30a347abcd7
input: https://twitter.com/Tham47844662
type: twitter
single: False
url: https://twitter.com/Tham47844662
dir: 
zip: 
artist: Tham
valid / done: False / True
range / range_p: None / None
time: 1654932535.2292395 (22-06-11 07:28:55 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
type: user
multiple tweets rt:False
mc: 0

stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\twitter_downloader", line 115, in read
 File "extractor\twitter_downloader", line 633, in get_imgs
 File "utils", line 3415, in check_alive_iter
 File "extractor\twitter_downloader", line 400, in _pagination_tweets
errors.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/Tham47844662  (6.3s)

**Comment by KurtBestor** [comment]
설정에 보시면 트위터 탭 있어요 거기서 설정하시면 돼요

**Comment by tdi2020** [comment]
헉... 무려 설정탭에!!  ON을 하니 너무너무 잘됩니다!! 이런 멋진 기능을 구현해주셔서 감사드립니다 선생님!😭 최고에요!
