### ISSUE TITLE
기본 데이터가 다운로드가 안됩니다 저만그런가요..?

### ISSUE THREAD

**Issue by fdsafs343** [KurtBestor/Hitomi-Downloader#3431]
Traceback (most recent call last):
  File "hitomi_searcher", line 205, in download_json
  File "hitomi_searcher", line 366, in download_json_
  File "json\__init__", line 348, in loads
  File "json\decoder", line 337, in decode
  File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

어떻게 해결해야하나용

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by dudals618** [comment]
> 지금도 안 되나요?

저도 같은 증상이 발생합니다. 지금도 기본 데이터 다운이 안 됩니다.

**Comment by ddt5244** [comment]
저도 히토미 다운로더  실행하자마자  Err
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1443, in _read_config
sqlite3.OperationalError: no such table: Saved

가 뜨고 기본데이터가 안되는건 아닌데 너무 오래 걸립니다.

**Comment by drdwing** [comment]
저도 같은 증상이 생겼네요

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 372, in download_json_
  File "myjson", line 14, in loads
  File "json\__init__", line 357, in loads
  File "json\decoder", line 337, in decode
  File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

이거 전에 했던 행동이라곤 검색 도중 취소를 누른 거 외엔 없는데 이렇게 됐네요
