### ISSUE TITLE
트위치 다운로드가 안되는 현상이 생겼습니다.

### ISSUE THREAD

**Issue by tadahno1** [KurtBestor/Hitomi-Downloader#3448]
제가 구독중인 트위치 스트리머의 클립이 다운받기 위해 실행했습니다만....다운이 안됩니다.

다른 몇몇 스트리머로 테스트하여도 동일한 현상입니다.

쿠키도 비로그인과 로그인으로 나누어서 실행하여 로그인된 쿠키로 정상등록하여 실행하였습니다.

아래는 작업 로그 첨부합니다.

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / cd7eab90b69d41d891955cb2a1439e89
input: https://www.twitch.tv/0guiling0/clip/SoftCleverKittenNotATK-3h7vu2yYnc_j7mAg
type: twitch
single: True
url: https://www.twitch.tv/0guiling0/clip/SoftCleverKittenNotATK-3h7vu2yYnc_j7mAg
dir: hitomi_downloaded_twitch
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1622828162.1942508 (Jun 5)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_twitch\노라조노래 (1172535144).mp4

[URLs]
[0001] LazyUrl(https://www.twitch.tv/0guiling0/clip/SoftCleverKittenNotATK-3h7vu2yYnc_j7mAg) ---> https://production.assets.clips.twitchcdn.net/AT-cm%7C1172535144.mp4

[Messages]

Fail_404 : \\?\J:\Jae Hyun Shim\Utility\0531-iptd899\각종 사이트 downloader_GUI\hitomi_downloaded_twitch\노라조노래 (1172535144).mp4
Traceback (most recent call last):
File "downloader", line 822, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: 

stop
valid=False 1
EOT: https://www.twitch.tv/0guiling0/clip/SoftCleverKittenNotATK-3h7vu2yYnc_j7mAg (2.4s)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/121538847-13923a00-ca40-11eb-8453-d65933ac0a0d.png)

재현할 수가 없네요

**Comment by tadahno1** [comment]
답볍주셔서 감사합니다.  이번에 업데이트하고 난 후부터 어떤 문제인지는 모르겠지만...클립이 다운로드가 정상적으로 되어서 슨생님이 수정하신줄 알았습니다.ㅎㅎㅎ 동일한 문제 발생시 조금 더 정확한 로그나 상황을 기록해보겠습니다.
