### ISSUE TITLE
애니24 스크립트 고치는중 막힘 고수님들 도와주세요ㅠㅠ

### ISSUE THREAD

**Issue by originalchitomi** [KurtBestor/Hitomi-Downloader#3450]
아무리 해도 안되고 자꾸 오류가 뜸니다. 뭐가 문제인지 모르겠어요ㅠㅠ
사이트는 추가되고 스크립트도 문제없이 뜨는대 다운이 안되요

Invalid: [ohli24] https://ohli24.net/bbs/board.php?bo_table=fin&wr_id=2296

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 251 / False / 3ebe786de6484f41becdc77d0b2e756c
input: https://ohli24.net/bbs/board.php?bo_table=fin&wr_id=2296
type: ohli24
single: False
url: https://ohli24.net/bbs/board.php?bo_table=fin&wr_id=2296
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1622903818.3022811 (Jun 5)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.05.16
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "dynamic_module_0", line 64, in read
File "dynamic_module_0", line 144, in get_videos
File "dynamic_module_0", line 109, in get_pages
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://ohli24.net/bbs/board.php?bo_table=fin&wr_id=2296 (1.9s)

**Comment by STR-HK** [comment]
Ani24 스크립트인데 Ohli24 라는 사이트를 넣으셨네요

**Comment by originalchitomi** [comment]
감사합니다^^

**Comment by wheatflor22** [comment]
혹시 고치셨나요?
고치셨으면 저도 스크립트좀..공유받을 수 있을까요.
저도 개인적으로 고쳐보려다가 스크립트는 전혀 모르다보니까 답이 없더라고요.

**Comment by originalchitomi** [comment]
아직 못고쳤습니다 ㅠㅠ 자꾸만 오류가 뜨네요

**Comment by STR-HK** [comment]
OHLI24는 동영상 전송 방식이 괴랄해서 저는 제작 포기했습니다 ㅠㅠ

**Comment by Psychopath7** [comment]
> 혹시 고치셨나요? 고치셨으면 저도 스크립트좀..공유받을 수 있을까요. 저도 개인적으로 고쳐보려다가 스크립트는 전혀 모르다보니까 답이 없더라고요.

https://github.com/Psychopath7/ohli24_script

**Comment by Psychopath7** [comment]
> 아직 못고쳤습니다 ㅠㅠ 자꾸만 오류가 뜨네요

https://github.com/Psychopath7/ohli24_script
