### ISSUE TITLE
산카쿠 다운로드가 되지 않아요

### ISSUE THREAD

**Issue by Ojdd** [KurtBestor/Hitomi-Downloader#3459]
링크를 복사 붙혀넣기 하고 다운로드 했는데도 계속 invalid가 떠요

Invalid: [sankaku] https://chan.sankakucomplex.com/ko/?tags=klee_%28genshin_impact%29

version: 3.3b (21-04-27 04:32:29 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / c4b2b304618747e888d5edb845bd2789
input: https://chan.sankakucomplex.com/ko/?tags=klee_%28genshin_impact%29
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/?tags=klee_%28genshin_impact%29
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1623142837.217377 (Jun 8)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/ko/?tags=klee_%28genshin_impact%29
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "downloader", line 285, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 421, in connect
File "urllib3\util\ssl_", line 429, in ssl_wrap_socket
File "urllib3\util\ssl_", line 472, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 756, in urlopen
File "urllib3\util\retry", line 532, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 421, in connect
File "urllib3\util\ssl_", line 429, in ssl_wrap_socket
File "urllib3\util\ssl_", line 472, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1079, in start
File "utils", line 1130, in start_
File "extractor\sankaku_downloader", line 109, in read
File "extractor\sankaku_downloader", line 277, in get_imgs
File "downloader", line 325, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/?tags=klee_%28genshin_impact%29 (1.5s)

**Comment by pokemonchun** [comment]
저도 똑같이 invalid가 뜨면서 다운이 되질 않습니다
