### ISSUE TITLE
Pixiv user bookmarks download error

### ISSUE THREAD

**Issue by 2Concreazum** [KurtBestor/Hitomi-Downloader#3460]
Error on version 3.4 and older. Program require cookies for download user bookmarks gallery, although they're already loaded. Separate units of R-18 in format '/artworks/123456...' downloads fine with loaded cookies. The problem appears just today - yesterday bookmarks downloaded normally. Reloading cookies and deleting config file doesn't resolve the problem. Logs for both bookmarks and single download attached below.
Add: for extracting cookies has been used extension "Get cookies.txt".
![1](https://user-images.githubusercontent.com/77178859/121199957-04628f00-c87c-11eb-95b2-d42310fde4d9.jpg)
[log_bookmarks.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/6617237/log_bookmarks.txt)
[log_single.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/6617238/log_single.txt)

**Comment by KurtBestor** [comment]
What is `*redacted user id*`? I can't reproduce on my end.

**Comment by 2Concreazum** [comment]
I'm self-censor my user number for privacy, but now I realized that I cannot download only my bookmarks. Other users' bookmarks downloads normally. Can I send my link to your PM?

**Comment by KurtBestor** [comment]
Sure

**Comment by 2Concreazum** [comment]
Done, check in your email

**Comment by KurtBestor** [comment]
I've got nothing in my email

**Comment by 2Concreazum** [comment]
Wait, email on @gmail from commits log isn't yours? To where can I write then?

**Comment by KurtBestor** [comment]
Oh, It's in the spam folder. Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 2Concreazum** [comment]
Same error as on release version
> Login required; Update your cookies: Invalid request.
> https://www.pixiv.net/en/users/********/bookmarks/artworks
> 
> version: 3.4 (21-06-12 19:06:50 UTC)
> platform / locale: Windows-10-10.0.19041-SP0 / en
> order / group / uid: 0 / False / fbb7a992e318425cb02990de6e6aa580
> input: https://www.pixiv.net/en/users/********/bookmarks/artworks
> type: pixiv
> single: False
> url: https://www.pixiv.net/en/users/********/bookmarks/artworks
> dir: 
> zip: 
> artist: None
> valid / done: False / True
> range / range_p: ~500 / None
> time: 1623528405.9720964 (Jun 12)
> tags: []
> lock: False
> color: invalid
> paused: False
> format: None
> p2f: None
> segment: None
> goodbyedpi: True
> ytdl: 2021.06.06
> pinned: False
> extras: {}
> changed: True
> 
> 
> [Gallery]
> None
> 
> 
> [File Names]
> 
> 
> 
> [URLs]
> 
> 
> 
> [Messages]
> Invalid request.
> stop
> Traceback (most recent call last):
> File "utils", line 1083, in start
> File "utils", line 1141, in start_
> File "extractor\pixiv_downloader", line 63, in read
> File "extractor\pixiv_downloader", line 311, in get_info
> File "extractor\pixiv_downloader", line 125, in bookmarks
> File "<decorator-gen-14>", line 2, in call
> File "constants", line 899, in wrapper
> File "constants", line 870, in wrapper
> File "ratelimit\decorators", line 113, in wrapper
> File "ratelimit\decorators", line 80, in wrapper
> File "extractor\pixiv_downloader", line 102, in call
> extractor.pixiv_downloader.PixivAPIError: Invalid request.
> 
> Invalid: fail=False
> EOT: https://www.pixiv.net/en/users/********/bookmarks/artworks (16.9s)
>

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/121794553-31c88780-cc44-11eb-9138-560ec54b982a.png)

I can't reproduce on my end

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/121794573-515fb000-cc44-11eb-9159-7b3d40984901.png)

I can't reproduce on my end

**Comment by 2Concreazum** [comment]
Okay, thank you for help. Actually it's helped me to find way to "resolve" problem. It seems, like I can't download my bookmarks with cookies from account with them. I tried on different machines, browsers, deleting sites data, changing password, but nothing worked out. Also I'm noticed, that sometimes there are an error `403 Client Error` in logs. Then I registered alt-account on pixiv and copy-pasted cookies from there in downloader. And now it's works again, but only in that strange way.
![1](https://user-images.githubusercontent.com/77178859/121814259-b7662a80-cc78-11eb-8ecf-379253a23d20.jpg)
[403_client_error_log.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/6644216/403_client_error_log.txt)

**Comment by NKTNIK** [comment]
픽시브 다운로드가 안됩니다.
쿠키 불러오기로 적용시켰는데도 login required만 계속해서 뜨네요ㅠ
비슷한 경우 있나 찾아보다가 
https://github.com/KurtBestor/Hitomi-Downloader/issues/3475#issuecomment-860066789
여기서 부계 사용하면 된다길래 새 계정 가입후 그걸로 쿠키 바꿔봤는데 똑같은 오류뜨고
위 링크에 Technical Preview 버전파일 다운받아 실행시켜봐도 안되네요..
 
작업정보 첨부합니다

Login required; Update your cookies
https://www.pixiv.net/artworks/86919624

version: 3.4a (21-06-27 04:50:02 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / b108af5817ec44aa92dddf85f52d712f
input: https://www.pixiv.net/artworks/86919624
type: pixiv
single: False
url: https://www.pixiv.net/artworks/86919624
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1625061202.4936266 (Jun 30)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: None
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
File "utils", line 1085, in start
File "utils", line 1144, in start_
File "extractor\pixiv_downloader", line 63, in read
File "extractor\pixiv_downloader", line 271, in get_info
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pixiv.net/artworks/86919624 (0.2s)
