### ISSUE TITLE
ini 파일 오류

### ISSUE THREAD

**Issue by aa541** [KurtBestor/Hitomi-Downloader#3468]
다운로더를 실행하면 이런 오류가 나타나고선 설정파일이 불러와지지 않습니다
Traceback (most recent call last):
  File "MyConfigParser", line 34, in read
  File "configparser", line 762, in readfp
  File "configparser", line 717, in read_file
  File "configparser", line 1014, in _read
  File "c:\users\kurtb\appdata\local\programs\python\python37\lib\codecs", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 8296, in <module>
  File "hitomi_downloader_GUI", line 787, in read_config
  File "MyConfigParser", line 39, in read
  File "configparser", line 696, in read
  File "configparser", line 1014, in _read
UnicodeDecodeError: 'cp949' codec can't decode byte 0x81 in position 0: illegal multibyte sequence

**Comment by KurtBestor** [comment]
해당 INI 파일 보내주시면 분석해볼게요

**Comment by aa541** [comment]
hitomi_downloader_GUI.ini
<https://drive.google.com/file/d/1OLpCOdW1BuT9asCyZE5G5Z3WG7D-_pga/view?usp=drive_web>
해당 ini 파일입니다!
감사합니다

2021년 6월 10일 (목) 오후 11:16, Kurt Bestor ***@***.***>님이 작성:

**Comment by KurtBestor** [comment]
파일이 잠겨있어요

**Comment by aa541** [comment]
따로 파일 만지거나 한 건 없었는데, 바이러스인가요?

2021년 6월 10일 (목) 오후 11:25, Kurt Bestor ***@***.***>님이 작성:

**Comment by KurtBestor** [comment]
파일 공유를 해주셔야 제가 볼 수 있어요..

**Comment by aa541** [comment]
죄송합니다 권한 수정했어요..

2021년 6월 10일 (목) 오후 11:26, sss s ***@***.***>님이 작성:

**Comment by aa541** [comment]
https://drive.google.com/file/d/1OLpCOdW1BuT9asCyZE5G5Z3WG7D-_pga/view?usp=sharing

2021년 6월 10일 (목) 오후 11:28, Kurt Bestor ***@***.***>님이 작성:

**Comment by KurtBestor** [comment]
파일이 깨져있네요. 디스크 오류로 깨진 것 같아요. 보통 컴퓨터 강종으로 인한 증상이에요.

**Comment by aa541** [comment]
그렇다면 설정 파일을 처음부터 만드는 것 말고는 다른 해결방법이 없을까요?

2021년 6월 10일 (목) 오후 11:34, Kurt Bestor ***@***.***>님이 작성:

**Comment by KurtBestor** [comment]
네 일부분이 아니라 대부분이 깨져있어서 복구 할 수도 없을 것 같아요

**Comment by aa541** [comment]
어쩔 수 없죠 ㅎㅎ 늦은 시간인데 감사합니다! 좋은 주말 보내셔요

2021년 6월 10일 (목) 오후 11:40, Kurt Bestor ***@***.***>님이 작성:
