### ISSUE TITLE
폰허브 프리미엄 다운로드 오류 

### ISSUE THREAD

**Issue by li4ac1212** [KurtBestor/Hitomi-Downloader#3469]
폰허브 프리미엄을 등록하고 시킨대로 쿠키를 넣었는데 

Invalid: [pornhub] https://www.pornhubpremium.com/view_video.php?viewkey=ph5f3f3fbfe037d

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 63ba90b9604a41deba5277e882d6488e
input: https://www.pornhubpremium.com/view_video.php?viewkey=ph5f3f3fbfe037d
type: pornhub
single: True
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5f3f3fbfe037d
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1623256908.0378504 (Jun 10)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
is_login 2
Video
ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org
stop
Traceback (most recent call last):
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\pornhub", line 431, in _real_extract
medias = self._download_json(video_url, video_id, fatal=False)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 899, in _download_json
expected_status=expected_status)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 877, in _download_json_handle
expected_status=expected_status)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\pornhub", line 53, in _download_webpage_handle
phantom = PhantomJSwrapper(self, required_version='2.0')
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\openload", line 117, in __init__
expected=True)
youtube_dl.utils.ExtractorError: PhantomJS executable not found in PATH, download it from http://phantomjs.org

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pornhub_downloader", line 244, in read
File "utils", line 703, in __call__
File "extractor\pornhub_downloader", line 113, in get
File "ytdl", line 318, in extract_info
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\li4ac\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 289, in report_error
youtube_dl.utils.DownloadError: ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5f3f3fbfe037d (6.9s)

다음과 같이 뜨기만 합니다.

**Comment by KurtBestor** [comment]
제가 프리미엄 계정이 없어서 그런데 계정 주시면 확인해볼게요
