### ISSUE TITLE
이번 업데이트 후로 픽시브 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by carot1228** [KurtBestor/Hitomi-Downloader#3474]
쿠키에 문제가 생겼나 싶어서 초기화하고 다시 받아서 적용해봤는데도 그러네요...

Invalid: [pixiv] https://www.pixiv.net/en/users/850805/artworks

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / f94b9c0d487646d0a7e47740791cb2f2
input: https://www.pixiv.net/en/users/850805/artworks
type: pixiv
single: False
url: https://www.pixiv.net/en/users/850805/artworks
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1623327908.8871298 (Jun 10)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
types: ['artworks'], tag: None
'artworks'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 406, in get_info
KeyError: 'artworks'

Invalid: fail=True
EOT: https://www.pixiv.net/en/users/850805/artworks (0.9s)

types: ['artworks'], tag: None
'artworks'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 406, in get_info
KeyError: 'artworks'

Invalid: fail=True
EOT: https://www.pixiv.net/en/users/850805/artworks (1.1s)

types: ['artworks'], tag: None
'artworks'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 406, in get_info
KeyError: 'artworks'

Invalid: fail=True
EOT: https://www.pixiv.net/en/users/850805/artworks (0.9s)

types: ['artworks'], tag: None
'artworks'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 406, in get_info
KeyError: 'artworks'

Invalid: fail=True
EOT: https://www.pixiv.net/en/users/850805/artworks (0.8s)

types: ['artworks'], tag: None
'artworks'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 406, in get_info
KeyError: 'artworks'

Invalid: fail=True
EOT: https://www.pixiv.net/en/users/850805/artworks (0.7s)

types: ['artworks'], tag: None
'artworks'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 406, in get_info
KeyError: 'artworks'

Invalid: fail=True
EOT: https://www.pixiv.net/en/users/850805/artworks (0.9s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by carot1228** [comment]
오 이제 됩니다. 감사합니다!
