### ISSUE TITLE
픽시브 북마크 다운로드가 안됩니다

### ISSUE THREAD

**Issue by watatsumi123** [KurtBestor/Hitomi-Downloader#3475]
쿠키를 업데이트하라고 해서 계속 바꿔주고 크롬에서 쿠키 삭제했다가 다시 로그인해서 생긴 쿠키를 넣어봐도 안 되네요.
작업 내역 첨부합니다.

Login required; Update your cookies: Invalid request.
https://www.pixiv.net/users/8908003/bookmarks/artworks/R-15

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 98250fbc506a483bb6863584dcc69a34
input: https://www.pixiv.net/users/8908003/bookmarks/artworks/R-15
type: pixiv
single: False
url: https://www.pixiv.net/users/8908003/bookmarks/artworks/R-15
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1623401670.5460434 (Jun 11)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid request.
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\pixiv_downloader", line 59, in read
File "extractor\pixiv_downloader", line 307, in get_info
File "extractor\pixiv_downloader", line 121, in bookmarks
File "<decorator-gen-14>", line 2, in call
File "constants", line 899, in wrapper
File "constants", line 870, in wrapper
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\pixiv_downloader", line 98, in call
extractor.pixiv_downloader.PixivAPIError: Invalid request.

Invalid: fail=False
EOT: https://www.pixiv.net/users/8908003/bookmarks/artworks/R-15 (1.8s)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/121778363-8bdc3500-cbd1-11eb-9ab5-cc149177e546.png)

재현할 수가 없네요

**Comment by Optick951** [comment]
동일 증상입니다.

특이한건 이슈 올리신 분 포함해서 다른 유저들 북마크는 다 다운로드 되는데

자기 계정 북마크만 다운로드가 안되네요.

크롬 어플리케이션, 로그인, 쿠키 삭제로는 문제 해결 못했네요 :(

다운로더 쿠키 초기화하고도 진행해봤는데 당연히 픽시브 다운로드 전체가 막혔습니다.

*다른 사이트들은 정상작동 합니다.
*픽시브 개인 북마크는 6월 5일까지는 정상적으로 작동했습니다.

![Cap 2021-06-13 00-03-16-647_censored](https://user-images.githubusercontent.com/85797493/121780439-43c21000-cbdb-11eb-9095-29c9c3acf82a.jpg)

**Comment by watatsumi123** [comment]
@Optick951 한 번 해보겠습니다. 감사합니다.

**Comment by watatsumi123** [comment]
부계정으로 해보니 잘 되었습니다!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3460#issuecomment-862571792

**Comment by andigh20** [comment]
다운로더에서 쿠키 초기화후, 부계 쿠키를 불러온 후 진행하시면 됩니다.
혹시 그외 같은 증상이신 분들은 일단 이렇게 다운로드 받으시면 될듯.

위에 적어주신 방법대로

쿠키초기화후에 부계쿠키 불러와서 진행했는데 다운이 안됩니다..


 
![asd](https://user-images.githubusercontent.com/86735495/123996383-3e9df700-da0a-11eb-80f1-e202a7cd515c.png)

작업정보 ↓


Invalid: [pixiv] https://www.pixiv.net/users/66471659/bookmarks/artworks

version: 3.4a (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 5adbc16d4eb145458a9f5a60d361733a
input: https://www.pixiv.net/users/66471659/bookmarks/artworks
type: pixiv
single: False
url: https://www.pixiv.net/users/66471659/bookmarks/artworks
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1625069721.4487243 (Jul 1)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\pixiv_downloader", line 63, in read
File "extractor\pixiv_downloader", line 301, in get_info
File "extractor\pixiv_downloader", line 439, in my_id
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pixiv.net/users/66471659/bookmarks/artworks (0.0s)

no userid
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\pixiv_downloader", line 63, in read
File "extractor\pixiv_downloader", line 301, in get_info
File "extractor\pixiv_downloader", line 440, in my_id
File "ree", line 15, in find
ree.NotFound: no userid

Invalid: fail=True
EOT: https://www.pixiv.net/users/66471659/bookmarks/artworks (0.5s)

no userid
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\pixiv_downloader", line 63, in read
File "extractor\pixiv_downloader", line 301, in get_info
File "extractor\pixiv_downloader", line 440, in my_id
File "ree", line 15, in find
ree.NotFound: no userid

Invalid: fail=True
EOT: https://www.pixiv.net/users/66471659/bookmarks/artworks (0.4s)
