### ISSUE TITLE
Error in myreadingmanga

### ISSUE THREAD

**Issue by MePlayz** [KurtBestor/Hitomi-Downloader#3484]
i tried download anything in myreadingmanga.info but error

------
Invalid: [mrm] https://myreadingmanga.info/modu9-otoshi-ai-eng

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 0 / False / 395739223320494f9b1987778e4403d5
input: https://myreadingmanga.info/modu9-otoshi-ai-eng
type: mrm
single: False
url: https://myreadingmanga.info/modu9-otoshi-ai-eng
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1623512921.4237657 (Jun 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
cf protection
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1142, in start_
File "extractor\mrm_downloader", line 70, in read
File "extractor\mrm_downloader", line 66, in name
File "extractor\mrm_downloader", line 81, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://myreadingmanga.info/modu9-otoshi-ai-eng (11.0s)

-------

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
