### ISSUE TITLE
asiansister invalid

### ISSUE THREAD

**Issue by amdradeon** [KurtBestor/Hitomi-Downloader#3485]
언제부턴가 불가능해졌는데 제가 이상한건지 모르겠습니다.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by amdradeon** [comment]
Invalid: [asiansister] https://asiansister.com/view_2095__Maid_Cherry_Club__51Pn

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 56fc3eeef6c040bbad5ec727387fdd38
input: https://asiansister.com/view_2095__Maid_Cherry_Club__51Pn
type: asiansister
single: False
url: https://asiansister.com/view_2095__Maid_Cherry_Club__51Pn
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1623625880.5018692 (Jun 14)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
('Connection aborted.', OSError(0, 'Error'))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 310, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 0] Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 421, in connect
File "urllib3\util\ssl_", line 429, in ssl_wrap_socket
File "urllib3\util\ssl_", line 472, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 756, in urlopen
File "urllib3\util\retry", line 532, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 382, in _make_request
File "urllib3\connectionpool", line 1010, in _validate_conn
File "urllib3\connection", line 421, in connect
File "urllib3\util\ssl_", line 429, in ssl_wrap_socket
File "urllib3\util\ssl_", line 472, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1070, in start
File "<decorator-gen-66>", line 2, in init
File "constants", line 899, in wrapper
File "constants", line 870, in wrapper
File "extractor\asiansister_downloader", line 16, in init
File "downloader", line 337, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

Invalid: fail=True
EOT: https://asiansister.com/view_2095__Maid_Cherry_Club__51Pn (7.4s)

**Comment by amdradeon** [comment]
해결했습니다. 공지를 못봤네요 죄송합니다.
