### ISSUE TITLE
히토미만 다운로드 중 오랫동안 멈춥니다

### ISSUE THREAD

**Issue by ExNaGNe** [KurtBestor/Hitomi-Downloader#3489]
히토미에서만
어떤작품이든 약 90퍼센트는 다운로드 중 몇분동안  멈춰버립니다.
픽시브나 다른 사이트도 실험해 봤는데 히토미만 그렇더군요
서버를 익헨으로 바꾸면 괜찮던데 히토미 서버 자체 문제인건가요?

그리고 멈추는 지점이 80~90 퍼센트로 동일합니다.

**Comment by KurtBestor** [comment]
어떤 ISP 쓰시나요?

**Comment by ExNaGNe** [comment]
> 어떤 ISP 쓰시나요?

SKT 인터넷 사용 중인데 건물 전체 인터넷이라 정확하진 않지만 기가급은 아닙니다.

**Comment by ExNaGNe** [comment]
> 어떤 ISP 쓰시나요?



> > 어떤 ISP 쓰시나요?
> 
> SKT 인터넷 사용 중인데 건물 전체 인터넷이라 정확하진 않지만 기가급은 아닙니다.
> 아 그리고 정확히는 80-90% 정도 부분에서 속도가 0에 수렴하다가 아주 가끔 느린속도로 1장씩 다운로드를 받고 속도가 0으로 바뀌고를 반복해서 결국 한 작품에 10분정도 속도로 받아지긴합니다. 가끔 마지막 1장에서 오래걸리던 현상이랑 비슷해보이기도합니다. 실제로 마지막 1-2장에서 제일 오래걸리네요.

**Comment by ExNaGNe** [comment]
> 어떤 ISP 쓰시나요?

SKT 인터넷 사용 중인데 건물 전체 인터넷이라 정확하진 않지만 기가급은 아닙니다.
아 그리고 정확히는 80-90% 정도 부분에서 속도가 0에 수렴하다가 아주 가끔 느린속도로 1장씩 다운로드를 받고 속도가 0으로 바뀌고를 반복해서 결국 한 작품에 10분정도 속도로 받아지긴합니다. 가끔 마지막 1장에서 오래걸리던 현상이랑 비슷해보이기도합니다. 실제로 마지막 1-2장에서 제일 오래걸리네요.

**Comment by lakals** [comment]
저도 동일한 이슈가 있습니다.
8~90%쯤 다운한 뒤에 속도가 0이 되고, 잡이 실패하네요. 그후 재시작되고 실패하고 반복하고 이런 식입니다.

작업 정보 하나를 첨부합니다.

[N／A] chocojaxg]Dimitori X beresu (1475039)

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 4 / False / 67e24e9ba0fd4848b3869ff41916a9e8
input: https://hitomi.la/doujinshi/chocojaxg-dimitori-x-beresu-english-1475039.html
type: hitomi
single: False
url: https://hitomi.la/doujinshi/chocojaxg-dimitori-x-beresu-english-1475039.html
dir: hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)
zip: 
artist: N／A
valid / done: True / False
range / range_p: ~2000 / None
time: 1623951137.9545035 (Jun 18)
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False


[Gallery]
갤러리 넘버: 1475039

제목: chocojaxg]Dimitori X beresu

작가: N/A

그룹: N/A

타입: doujinshi

시리즈: fire emblem three houses

캐릭터: byleth eisner, dimitri alexandre blaiddyd

태그: female:rape, female:sole female, male:eyepatch, male:sole male

언어: English


[File Names]
[0001] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\01_76432827_p0.jpg
[0002] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\02_76432827_p1.jpg
[0003] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\03_76432827_p2.jpg
[0004] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\04_76432827_p3.jpg
[0005] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\05_76432827_p4.jpg
[0006] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\06_76432827_p5.jpg
[0007] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\07_76432827_p6.jpg
[0008] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\08_76432827_p7.jpg
[0009] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\09_76432827_p8.jpg
[0010] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\10_76432827_p9.jpg
[0011] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\11_76432827_p10.jpg
[0012] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\12_76432827_p11.jpg
[0013] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\13_76432827_p12.jpg
[0014] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\14_76432827_p13.jpg
[0015] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\15_76432827_p14.jpg
[0016] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\16_76432827_p15.jpg
[0017] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\17_76432827_p16.jpg
[0018] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\18_76432827_p17.jpg
[0019] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\19_76432827_p18.jpg
[0020] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\20_76432827_p19.jpg
[0021] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\21_76432827_p20.jpg
[0022] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\22_76432827_p21.jpg
[0023] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\23_76432827_p22.jpg


[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 01_76432827_p0.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 02_76432827_p1.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 03_76432827_p2.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 04_76432827_p3.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 05_76432827_p4.jpg
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> https://bb.hitomi.la/images/f/54/63d4dbdf7c4db523d315ad748d0945979222427b570e90cde991774d0267754f.jpg
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 07_76432827_p6.jpg
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 08_76432827_p7.jpg
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 09_76432827_p8.jpg
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 10_76432827_p9.jpg
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 11_76432827_p10.jpg
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 12_76432827_p11.jpg
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 13_76432827_p12.jpg
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 14_76432827_p13.jpg
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 15_76432827_p14.jpg
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 16_76432827_p15.jpg
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 17_76432827_p16.jpg
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 18_76432827_p17.jpg
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 19_76432827_p18.jpg
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> https://bb.hitomi.la/images/a/56/9a111711205f702de24c77867b59c7614b743641737bff1ddd7133f5c2b1b56a.jpg
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 21_76432827_p20.jpg
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> https://bb.hitomi.la/images/7/50/3f20e100823b4fcdbea0f41c653a43f2363df66437298528668fa69b69184507.jpg
[0023] LazyUrl_hitomi(https://hitomi.la/reader/1475039.html) ---> 【local_lazy】 23_76432827_p22.jpg


[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 23
get_title__


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\06_76432827_p5.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\20_76432827_p19.jpg
Traceback (most recent call last):
File "downloader", line 863, in download
Exception: 404


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\20_76432827_p19.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\22_76432827_p21.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\07_76432827_p6.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\18_76432827_p17.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\04_76432827_p3.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\16_76432827_p15.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\16_76432827_p15.jpg
Traceback (most recent call last):
File "downloader", line 961, in download
Exception: Size mismatch: 618929 / 1161532


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\04_76432827_p3.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\08_76432827_p7.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/chocojaxg-dimitori-x-beresu-english-1475039.html (625.1s)

get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 23


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\22_76432827_p21.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\06_76432827_p5.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\20_76432827_p19.jpg
Traceback (most recent call last):
File "downloader", line 863, in download
Exception: 404


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\20_76432827_p19.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/chocojaxg-dimitori-x-beresu-english-1475039.html (193.6s)

get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 23


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\06_76432827_p5.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail_404 : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\22_76432827_p21.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\jsl\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\20_76432827_p19.jpg
Traceback (most recent call last):
File "downloader", line 863, in download
Exception: 404

**Comment by KurtBestor** [comment]
@lakals 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3498#issuecomment-863646313

**Comment by ExNaGNe** [comment]
> @lakals 참고해주세요: [#3498 (comment)](https://github.com/KurtBestor/Hitomi-Downloader/issues/3498#issuecomment-863646313)

테크니컬 테스트 버전이 3.4a 버전으로 올라간건가요? 여전히 마지막 90%쯤에서 멈춥니다.
그 상태에서 껏다 키면 완료되는것도 있긴한데 여전히 멈춰있는것도 있습니다.

**Comment by lakals** [comment]
> @lakals 참고해주세요: [#3498 (comment)](https://github.com/KurtBestor/Hitomi-Downloader/issues/3498#issuecomment-863646313)

해당 버전으로도 큰 차이는 없는 것 같습니다.
5분 자동 재시작으로 이전 버전, 올려주신 버전 합쳐서 약 2일간 돌려놨는데 대부분이 완료가 안됐네요...
완료된 작품도 몇 있고, 익헨으로 바뀌어서 완료된 것도 있습니다.

위에 올렸던 로그의 경우 익헨으로 바뀌어서 완료되었네요.
로그를 첨부합니다.

[N／A] chocojaxg]Dimitori X beresu(fire emblem three houses) (1475039)

version: 3.4 (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 21 / False / 67e24e9ba0fd4848b3869ff41916a9e8
input: https://hitomi.la/doujinshi/chocojaxg-dimitori-x-beresu-english-1475039.html
type: ehen
single: False
url: https://exhentai.org/g/1475039/869cf6c547
dir: hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)
zip: hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039).zip
artist: N／A
valid / done: True / True
range / range_p: ~2000 / None
time: 1624002587.4764836 (Jun 18)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False


[Gallery]
갤러리 넘버: 1475039

제목: chocojaxg]Dimitori X beresu(fire emblem three houses)

작가: N/A

그룹: N/A

타입: doujinshi

시리즈: fire emblem three houses

캐릭터: byleth eisner, dimitri alexandre blaiddyd

태그: male:eyepatch, male:sole male, female:sole female, female:rape

언어: English


[File Names]
[0001] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p0.jpg
[0002] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p1.jpg
[0003] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p2.jpg
[0004] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p3.jpg
[0005] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p4.jpg
[0006] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p5.jpg
[0007] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p6.jpg
[0008] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p7.jpg
[0009] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p8.jpg
[0010] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p9.jpg
[0011] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p10.jpg
[0012] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p11.jpg
[0013] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p12.jpg
[0014] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p13.jpg
[0015] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p14.jpg
[0016] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p15.jpg
[0017] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p16.jpg
[0018] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p17.jpg
[0019] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p18.jpg
[0020] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p19.jpg
[0021] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p20.jpg
[0022] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p21.jpg
[0023] hitomi_downloaded\[N／A] chocojaxg]Dimitori X beresu (1475039)\76432827_p22.jpg


[URLs]

**Comment by ExNaGNe** [comment]
> 어떤 ISP 쓰시나요?

 고향에 내려와서 KT 기가인터넷으로 써보니 잘 돌아가네요
다시 올라가서 SKT 인터넷으로 확인해봐야겠습니다.

**Comment by ExNaGNe** [comment]
> > 어떤 ISP 쓰시나요?
> 
> 고향에 내려와서 KT 기가인터넷으로 써보니 잘 돌아가네요
> 다시 올라가서 SKT 인터넷으로 확인해봐야겠습니다.

방으로 돌아와서 확인해보니 SKT 100M급 인터넷에서는 80%정도에서 멈춥니다.
KT 기가인터넷 쓸때는 이런 증상이 없구요.

**Comment by ExNaGNe** [comment]
뭐지 6월 29일 이후로 고쳐졌습니다
진짜 이유를 모르겠네요 ㄷ
