### ISSUE TITLE
히토미 일부 다운불가

### ISSUE THREAD

**Issue by tlzmflt** [KurtBestor/Hitomi-Downloader#3498]
Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션

version: 3.4 (21-06-08 11:44:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 351cbc4556c44b5687d04d8cb880b92e
input: https://hitomi.la/doujinshi/tokimeki-nonfiction-|-%EB%91%90%EA%B7%BC%EB%91%90%EA%B7%BC-%E2%98%86-%EB%85%BC%ED%94%BD%EC%85%98-%ED%95%9C%EA%B5%AD%EC%96%B4-1936244.html
type: hitomi
single: False
url: https://hitomi.la/doujinshi/tokimeki-nonfiction-|-두근두근-☆-논픽션-한국어-1936244.html
dir: hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션
zip: 
artist: kitaku
valid / done: False / True
range / range_p: ~2000 / None
time: 1623950184.698112 (Jun 18)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
갤러리 넘버: 1936244

제목: Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션

작가: kitaku

그룹: kitaku jikan

타입: doujinshi

시리즈: love live nijigasaki high school idol club

캐릭터: art, ayumu uehara, setsuna yuki, yu takasaki

태그: female:females only, female:fff threesome, female:yuri

언어: Korean

[File Names]
[0001] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\01.jpg
[0002] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\02.jpg
[0003] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\03.jpg
[0004] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\04.jpg
[0005] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\05.jpg
[0006] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\06.jpg
[0007] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\07.jpg
[0008] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\08.jpg
[0009] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\09.jpg
[0010] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\10.jpg
[0011] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\11.jpg
[0012] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\12.jpg
[0013] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\13.jpg
[0014] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\14.jpg
[0015] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\15.jpg
[0016] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\16.jpg
[0017] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\17.jpg
[0018] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\18.jpg
[0019] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\19.jpg
[0020] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\20.jpg
[0021] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\21.jpg
[0022] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\22.jpg
[0023] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\23.jpg
[0024] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\24.jpg
[0025] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\25.jpg
[0026] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\26.jpg
[0027] hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\27.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/e/bb/9725ce0cadf97fbd9024eb25e0a482040a8c977d47baffe8eaaa0a57d9237bbe.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/7/58/551d6d74ecc25bc0898f535090bd224ddc1b88c4cd59584bed01ddd81bcf4587.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://cb.hitomi.la/images/a/bf/725d64ee4176d7dfce56b5ae294d872b3c2ddaea9589a8464ab66a685ba0fbfa.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/b/fc/bffdd3a987271f99535e23b4e8136341df71a836e8e0240c2638f46c406b7fcb.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/8/55/6f4eb815ce1253bd68d50ad08d5a7ea1360d16544dbc2c5ef64ce6ba98137558.jpg
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/1/9c/d49fc8013d7e4b1bb9f190b893e6cf6b844183b1aa782a681cf3a7647d34d9c1.jpg
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/c/70/cb459c978bc68d2aa892c13ec965633e1f01779e991d7e8bad4fea9df1df470c.jpg
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/6/78/b84508c9599c2f8c8f596147383234cb04aad6d0fecea0792d583bd08f8a8786.jpg
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/8/c7/37f12902cc866264d75e2ac53bba4fa04e3ab14643bc71a995da6fd204423c78.jpg
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/a/a5/b8394560a82abad1e72c7cc93f1a2d6bdbd2cbc9880251beb8afab47239a3a5a.jpg
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://cb.hitomi.la/images/9/95/38aed0c8a87e9ded0c76d800aa9ea130b1410fff0719f6173d0ca6eca9956959.jpg
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/9/26/18a2e256ae07ad9a83b76e80df0e6c770bc941a201c90428929253807117b269.jpg
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/0/ed/5f90a82778c7ef98aed902dd2fa3e8b964d519ddf46390d589df0216b32cfed0.jpg
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://cb.hitomi.la/images/c/e9/43d292d21780c0b406b29e38386ddc0ab3dad793ffe0a51ea1794ceee3e22e9c.jpg
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://cb.hitomi.la/images/2/fe/48b350a7236f581b2a32a36b9a2309479d6ce5144450f7d888fcc000a13f8fe2.jpg
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/8/44/72c7439a7bdb7d273640b7d473cbdf0f6e4bdae1687d46b28811084f46961448.jpg
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/d/5d/b23e3f86f589df33e7592348034085adb412248a7b8cea7f98400e484a9e95dd.jpg
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://cb.hitomi.la/images/c/86/df4808fd3ef26fd29ae3ba6ac0a2894e78891a4c718c6be84af06690f8ab186c.jpg
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/d/91/c367b84d890c74fd70680e0e2fd7a3ea27956f3e7c4c83d3b4a06bef3660191d.jpg
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/2/a6/68c1fa3f8ff4354d52ec6060f9d383c3923d1fea461099f4641b4722dec2ca62.jpg
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://ab.hitomi.la/images/1/c3/818d5e16a48b90de37682be2c297679c8dbdd11aeef540024489cfd3060ebc31.jpg
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/f/3e/aede76c223f8f1320039051671cba24ac2d08465e4815ae85a0f034b214ff3ef.jpg
[0023] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/6/06/2e2c5811c38f98d545b2dd9a629b9a4235085864e8a960247300058b9dff9066.jpg
[0024] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/f/69/fb9d63c030a8ce49caac49c3a43882faf217a031356ba6405baa9c11d16d469f.jpg
[0025] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/0/0a/b1cf4ea80113f991908d80237ac543176c6660cb53cf071a27b21e49da05e0a0.jpg
[0026] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://cb.hitomi.la/images/1/fb/3c1267ec6a3eb13fb629f9da25e0ac396044b9c2b2af738e9800e735c06aafb1.jpg
[0027] LazyUrl_hitomi(https://hitomi.la/reader/1936244.html) ---> https://bb.hitomi.la/images/d/f4/59b26dfed84497caa14225bf53cd4294b9047bfc9102ce8e024b411bd4b9af4d.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 27
get_title__

Fail_404 : \\?\D:\다운로드\hitomi_downloader_GUI\hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\02.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\D:\다운로드\hitomi_downloader_GUI\hitomi_downloaded\Tokimeki Nonfiction ｜ 두근두근 ☆ 논픽션\07.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/tokimeki-nonfiction-|-%EB%91%90%EA%B7%BC%EB%91%90%EA%B7%BC-%E2%98%86-%EB%85%BC%ED%94%BD%EC%85%98-%ED%95%9C%EA%B5%AD%EC%96%B4-1936244.html (100.3s)

해결부탁드립니다.

**Comment by kongskongs** [comment]
동일하게 hitomi.la 서버에서 받을 파일에 이빨이 빠지네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tlzmflt** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘됩니다 감사합니다.
