### ISSUE TITLE
자꾸 다운로드 속도가 0까지 떨어지네요...

### ISSUE THREAD

**Issue by miroung** [KurtBestor/Hitomi-Downloader#3514]
히토미에서 다운로드 시작하고 곧 0.0까지 떨어졌다가 몇분 지나서 200~300KB/s까지 확 오르고 곧바로 0까지 하락하는 식으로 계속 반복됩니다.
 인터넷은 skt껄 쓰고 있는데 그래서 일까요?

아래는 로그입니다.
[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus

version: 3.4a (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 19 / False / c1553cb413404a6a83d3ca2ef1ab473f
input: [Kawasaki Tadataka] Misaki-senpai in the morning +Bonus (1840041)
type: hitomi
single: False
url: https://hitomi.la/galleries/1840041.html
dir: d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus
zip: 
artist: kawasaki tadataka
valid / done: True / False
range / range_p: None / None
time: 1624553230.8302538 (Jun 25)
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False

[Gallery]
갤러리 넘버: 1840041

제목: Misaki-senpai in the morning +Bonus

작가: kawasaki tadataka

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: N/A

언어: Korean

[File Names]
[0001] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\1.jpg
[0002] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\2.jpg
[0003] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\3.jpg
[0004] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\4.jpg
[0005] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\5.jpg
[0006] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\6.jpg
[0007] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\7.jpg
[0008] d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\8.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://ab.hitomi.la/images/a/a2/104e74268fe2df8b770a2294d0aa5ac19b77909317fad3edc867ff5292b9fa2a.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://cb.hitomi.la/images/1/cb/164b16231be8718f3a7eb073302aa66f673e51618ec9d1217cbf5494a0e67cb1.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://cb.hitomi.la/images/1/dd/3be472a0270af3c25e1c70eb0caea69b0cca9910e7890a9ad7f07c5e0e317dd1.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://ab.hitomi.la/images/4/75/850c1941b1dd7505b21e893c48f83f11806e2a848b01c9269bdebe64c1fcc754.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://ab.hitomi.la/images/e/6c/ccedb501fbc01efedae33209f991ccb727ab5d4fcefd28cf268b17df543836ce.jpg
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://bb.hitomi.la/images/f/6d/4f366a3c1a32d72099b025f46802a94dfe9a70ef800adf3cf194d8412aa856df.jpg
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://bb.hitomi.la/images/1/0f/5259bf6b75758f2b850a340b0198c00dd0b721921c6d505c61f8ae4c3f7600f1.jpg
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1840041.html) ---> https://ab.hitomi.la/images/c/e4/0a48d43d8dcae1c2d1216daefc9e4bd172cae0cde8e2732387e8653c1e058e4c.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 8

Fail : \\?\E:\Hello\data\2016\my sql\asd\12\hitomi_downloader_GUI\d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\2.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

Fail : \\?\E:\Hello\data\2016\my sql\asd\12\hitomi_downloader_GUI\d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\5.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

Fail : \\?\E:\Hello\data\2016\my sql\asd\12\hitomi_downloader_GUI\d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\6.jpg
Traceback (most recent call last):
File "downloader", line 961, in download
Exception: Size mismatch: 474794 / 724666

Fail : \\?\E:\Hello\data\2016\my sql\asd\12\hitomi_downloader_GUI\d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\4.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

Fail : \\?\E:\Hello\data\2016\my sql\asd\12\hitomi_downloader_GUI\d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\7.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

Fail : \\?\E:\Hello\data\2016\my sql\asd\12\hitomi_downloader_GUI\d\down\kawasaki_tadataka\[Kawasaki Tadataka](1840041)Misaki-senpai in the morning +Bonus\5.jpg
Traceback (most recent call last):
File "downloader", line 906, in download
File "downloader", line 899, in Stream
File "http\client", line 461, in read
File "http\client", line 505, in readinto
File "socket", line 589, in readinto
File "ssl", line 1071, in recv_into
File "ssl", line 929, in read
socket.timeout: The read operation timed out

**Comment by ExNaGNe** [comment]
저도 skt 인터넷 쓰는 방에서는 자꾸 멈췄었는데
KT 기가랜 쓰는 집에서는 그런 증상이 없더라구요
6월 초에는 안그랬는데 갑자기 이럽니다.
