### ISSUE TITLE
트위터 다운로드가 되지않습니다

### ISSUE THREAD

**Issue by hokess5** [KurtBestor/Hitomi-Downloader#3525]
안녕하세요 개발자님
트위터 다운로드가 정상적으로 진행되지않아서 문의드려봅니다
최신 버젼을 적용했는데도 다운로드가 되지않더군요
아래 오류사항을 첨부하였습니다
여유가 되실때 해결해주시면 감사하겠습니다
문의를 읽어주셔서 감사합니다

Invalid: [twitter] https://twitter.com/Ryobi_S2_Chabi

version: 3.4a (21-06-27 04:50:02 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 74554b9ae35440ccbec8c4f46efbfdb9
input: https://twitter.com/Ryobi_S2_Chabi
type: twitter
single: True
url: https://twitter.com/Ryobi_S2_Chabi
dir: 
zip: 
artist: None
valid / done: False / False
range / range_p: None / None
time: 1625115099.207032 (Jul 1)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Value for header {x-guest-token: 1410459548847022083} must be of type str or bytes, not <class 'int'>
stop
Traceback (most recent call last):
File "requests\utils", line 957, in check_header_validity
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1071, in start
File "extractor\twitter_downloader", line 53, in init
File "<decorator-gen-27>", line 2, in get_artist_username
File "constants", line 903, in wrapper
File "constants", line 874, in wrapper
File "extractor\twitter_downloader", line 611, in get_artist_username
File "extractor\twitter_downloader", line 202, in user_by_screen_name
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\twitter_downloader", line 177, in _call
File "requests\sessions", line 555, in get
File "downloader", line 108, in session_request
File "requests\sessions", line 528, in request
File "requests\sessions", line 466, in prepare_request
File "requests\models", line 317, in prepare
File "requests\models", line 451, in prepare_headers
File "requests\utils", line 961, in check_header_validity
requests.exceptions.InvalidHeader: Value for header {x-guest-token: 1410459548847022083} must be of type str or bytes, not <class 'int'>

Invalid: fail=True

**Comment by SoyaNyan** [comment]
저도 트위터 다운로드 시도시 동일한 오류가 발생합니다.

**Comment by lime111** [comment]
저도 어제부터 트위터가  다운로드 되지 않습니다.

**Comment by hw5511** [comment]
저도 트위터가 다운로드 되지 않습니다 ㅠ

**Comment by crse** [comment]
Same, all of my download list are now broken :(

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hw5511** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

작동됨을 확인하였습니다. 감사합니다!

**Comment by hokess5** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

확인 결과 작동이 잘됩니다
고쳐주셔서 감사합니다

혹시 실례가 안된다면 어떤부분이 문제가 돼서 어떤부분을 수정했는지 알려주실수있나요? 
곧 있으면 프로그램 코딩공부를 시작할려고 하는데 나중에도 이런경우가 생기면 한번 직접 고쳐보고싶어서요
이쪽으로는 완전 문외한이라 이번경우에는 도대체 어디서 문제가 생겼고 무엇을 수정했는지 관련지식이 하나도 없으니 도통 알 길이 없네요...

**Comment by KurtBestor** [comment]
@hokess5
Twitter 에서 게스트 토큰을 string 으로 줬는데 지금은 가끔씩 integer 로 줄 때가 있게 바뀌었어요. Javascript 에선 자동으로 integer -> string 으로 형변환해서 오류가 안 생기는데 Python 은 그렇지 않아서 해당 부분 고쳤어요.
