### ISSUE TITLE
히토미 삭제된 데이터 다운로드불가

### ISSUE THREAD

**Issue by norado** [KurtBestor/Hitomi-Downloader#3527]
히토미 삭제된 데이터 다운로드불가
1. SANTA korean 삭제된 데이터 다운로드 안됩니다.
2. [Hakano Shinshi] Maple Virgin 다운로드 안됩니다. 원본은 삭제됐지만 히토미에는 삭제되지 않았는데요. 히토미 웹사이트는 다운로드는 됩니다.

Invalid: [hitomi] https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html

version: 3.4a (21-07-01 12:45:55 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 0 / False / 4d3291e231104e91a4d93365b4c6eccc
input: https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html
type: hitomi
single: False
url: https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1625198018.32344 (Jul 2)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:931692)
Find_ehen(id:931692, ex:False)
Find in HK...
not found in HK
max_page = 29498
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.0
BFS: 11.1
BFS: 12.1
BFS: 13.1
BFS: 14.1
BFS: 15.3
BFS: 16.3
BFS: 17.3
BFS: 18.8
BFS: 19.9
BFS: 21.6
BFS: 23.8
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:931692)
Find_ehen(id:931692, ex:True)
Find in HK...
not found in HK
max_page = 42633
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.1
BFS: 11.1
BFS: 12.2
BFS: 13.5
BFS: 15.1
BFS: 17.4
BFS: 22.6
BFS: 24.3
BFS: 32.8
BFS: 39.3
BFS: 40.7
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 608, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 610, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

stop
Invalid: fail=False
stop
EOT: 931692 (100.4s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html)
Find_ehen(id:931692, ex:False)
Find in HK...
not found in HK
max_page = 29498
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.0
BFS: 11.0
BFS: 12.0
BFS: 13.0
BFS: 14.0
BFS: 15.0
BFS: 16.0
BFS: 17.2
BFS: 18.8
BFS: 19.8
BFS: 21.8
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html)
Find_ehen(id:931692, ex:True)
Find in HK...
not found in HK
max_page = 42633
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.3
BFS: 8.3
BFS: 9.3
BFS: 10.3
BFS: 11.3
BFS: 12.3
BFS: 13.4
BFS: 14.5
BFS: 15.5
BFS: 16.5
BFS: 17.7
BFS: 19.4
BFS: 20.9
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 608, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 610, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html (98.9s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html)
Find_ehen(id:931692, ex:False)
Find in HK...
not found in HK
max_page = 29498
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.0
BFS: 11.1
BFS: 12.1
BFS: 13.1
BFS: 14.1
BFS: 15.3
BFS: 16.3
BFS: 17.3
BFS: 18.3
BFS: 19.3
BFS: 20.4
BFS: 21.6
BFS: 23.7
BFS: 24.8
BFS: 31.0
BFS: 88.8
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html)
Find_ehen(id:931692, ex:True)
Find in HK...
not found in HK
max_page = 42633
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.1
BFS: 11.1
BFS: 12.1
BFS: 13.1
BFS: 14.5
BFS: 16.3
BFS: 19.2
BFS: 27.3
BFS: 28.4
BFS: 29.5
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 608, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 610, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html (103.7s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html)
Find_ehen(id:931692, ex:False)
Find in HK...
not found in HK
max_page = 29498
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.1
BFS: 11.1
BFS: 12.3
BFS: 13.3
BFS: 14.3
BFS: 15.4
BFS: 16.5
BFS: 17.6
BFS: 18.7
BFS: 21.3
BFS: 29.1
BFS: 36.2
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html)
Find_ehen(id:931692, ex:True)
Find in HK...
not found in HK
max_page = 42633
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.1
BFS: 7.1
BFS: 8.1
BFS: 9.5
BFS: 10.5
BFS: 11.6
BFS: 12.6
BFS: 14.0
BFS: 15.0
BFS: 21.1
BFS: 38.0
BFS: 94.2
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 608, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 610, in read
File "hitomi_downloader", line 437, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/manga/maple-virgin-%ED%95%9C%EA%B5%AD%EC%96%B4-931692.html (93.2s)

**Comment by KurtBestor** [comment]
이렇게 해주세요:
![image](https://user-images.githubusercontent.com/14768120/124221224-4c529a00-db3a-11eb-93be-015495c4c91b.png)

E(x)Hentai 에 없으면 갤러리 정보 못 가져와서 다운로드 못 해요
