### ISSUE TITLE
인스타 다운이 안되네요

### ISSUE THREAD

**Issue by kzts97** [KurtBestor/Hitomi-Downloader#3534]
쿠키 업데이트후 해봐도 안되네요.  4일전부터 갑자기 다운이안되네요

끝까지 (n/n)번까지 읽다가 다읽고나서 주황색으로 안된다고 되네요 

중간에 한글은 들어있는것은 개인 닉네임이 나와서 바꿧습니다 죄송합니다

(insta_닉네임)

version: 3.3b (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / e8273f658d6b4c25afa8261fc5f8377a
input: https://www.instagram.com/닉네임
type: insta
single: False
url: https://www.instagram.com/닉네임
dir: hitomi_downloaded_insta\ (insta_닉네임)
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1625041505.882438 (Jun 30)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: True
extras: {}
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_insta\ (insta_닉네임)\stories_2607319072863321323.jpg
[0002] hitomi_downloaded_insta\ (insta_닉네임)\stories_2607194096998933197.jpg
[0003] hitomi_downloaded_insta\ (insta_닉네임)\stories_2607190150184123450.jpg
[0004] hitomi_downloaded_insta\ (insta_닉네임)\stories_2581025872930465665.mp4
[0005] hitomi_downloaded_insta\ (insta_닉네임)\stories_2581025857914963033.mp4
[0006] hitomi_downloaded_insta\ (insta_닉네임)\stories_2578906917822664511.mp4
[0007] hitomi_downloaded_insta\ (insta_닉네임)\stories_2576723839171942098.jpg
[0008] hitomi_downloaded_insta\ (insta_닉네임)\stories_2572380156813149288.mp4
[0009] hitomi_downloaded_insta\ (insta_닉네임)\stories_2560197554362690558.jpg
[0010] hitomi_downloaded_insta\ (insta_닉네임)\stories_2560073159745059877.mp4
[0011] hitomi_downloaded_insta\ (insta_닉네임)\stories_2555802509564015968.mp4
[0012] hitomi_downloaded_insta\ (insta_닉네임)\stories_2555802495555130561.mp4
[0013] hitomi_downloaded_insta\ (insta_닉네임)\stories_2553569105464309500.mp4
[0014] hitomi_downloaded_insta\ (insta_닉네임)\stories_2553567984494625291.mp4
[0015] hitomi_downloaded_insta\ (insta_닉네임)\stories_2553567982145887093.mp4
[0016] hitomi_downloaded_insta\ (insta_닉네임)\stories_2553567966417186321.mp4
[0017] hitomi_downloaded_insta\ (insta_닉네임)\stories_2525300127973670448.mp4
[0018] hitomi_downloaded_insta\ (insta_닉네임)\stories_2525300102069656390.mp4
[0019] hitomi_downloaded_insta\ (insta_닉네임)\stories_2525300088404664954.mp4
[0020] hitomi_downloaded_insta\ (insta_닉네임)\stories_2525236410439305765.jpg
[0021] hitomi_downloaded_insta\ (insta_닉네임)\stories_2515314879613510610.mp4
[0022] hitomi_downloaded_insta\ (insta_닉네임)\stories_2515314867902975586.mp4
[0023] hitomi_downloaded_insta\ (insta_닉네임)\stories_2483472505916800636.mp4
[0024] hitomi_downloaded_insta\ (insta_닉네임)\stories_2483472494575263624.mp4
[0025] hitomi_downloaded_insta\ (insta_닉네임)\stories_2483472479945696346.mp4
[0026] hitomi_downloaded_insta\ (insta_닉네임)\stories_2476323480423688209.jpg
[0027] hitomi_downloaded_insta\ (insta_닉네임)\stories_2472626661076428559.jpg
[0028] hitomi_downloaded_insta\ (insta_닉네임)\stories_2460853591970087285.mp4
[0029] hitomi_downloaded_insta\ (insta_닉네임)\stories_2460853581635230770.mp4
[0030] hitomi_downloaded_insta\ (insta_닉네임)\stories_2460853564639865032.mp4
[0031] hitomi_downloaded_insta\ (insta_닉네임)\stories_2450800249218767464.jpg
[0032] hitomi_downloaded_insta\ (insta_닉네임)\stories_2446310620029311939.mp4
[0033] hitomi_downloaded_insta\ (insta_닉네임)\stories_2446310610625643992.mp4
[0034] hitomi_downloaded_insta\ (insta_닉네임)\stories_2446310597925513536.mp4
[0035] hitomi_downloaded_insta\ (insta_닉네임)\stories_2403800567833933150.jpg
[0036] hitomi_downloaded_insta\ (insta_닉네임)\stories_2403096919935838218.jpg
[0037] hitomi_downloaded_insta\ (insta_닉네임)\stories_2360109435803404872.mp4
[0038] hitomi_downloaded_insta\ (insta_닉네임)\stories_2352856960151293694.jpg
[0039] hitomi_downloaded_insta\ (insta_닉네임)\stories_2352855545706044288.jpg
[0040] hitomi_downloaded_insta\ (insta_닉네임)\stories_2351681747652906477.jpg
[0041] hitomi_downloaded_insta\ (insta_닉네임)\stories_2350816696091853678.mp4
[0042] hitomi_downloaded_insta\ (insta_닉네임)\stories_2350816675430838290.mp4
[0043] hitomi_downloaded_insta\ (insta_닉네임)\stories_2350259091955004743.jpg
[0044] hitomi_downloaded_insta\ (insta_닉네임)\stories_2350015832699900843.mp4
[0045] hitomi_downloaded_insta\ (insta_닉네임)\stories_2349373201229768848.jpg
[0046] hitomi_downloaded_insta\ (insta_닉네임)\stories_2348695364633972645.jpg
[0047] hitomi_downloaded_insta\ (insta_닉네임)\stories_2348649103457390175.jpg
[0048] hitomi_downloaded_insta\ (insta_닉네임)\stories_2346534334944500727.jpg
[0049] hitomi_downloaded_insta\ (insta_닉네임)\stories_2344938736826887712.mp4
[0050] hitomi_downloaded_insta\ (insta_닉네임)\stories_2344938722465636164.mp4
[0051] hitomi_downloaded_insta\ (insta_닉네임)\stories_2344938693961061377.mp4
[0052] hitomi_downloaded_insta\ (insta_닉네임)\stories_2342947551954433800.mp4
[0053] hitomi_downloaded_insta\ (insta_닉네임)\stories_2342947542651456102.mp4
[0054] hitomi_downloaded_insta\ (insta_닉네임)\stories_2342929200523906222.mp4
[0055] hitomi_downloaded_insta\ (insta_닉네임)\stories_2342929186858885554.mp4
[0056] hitomi_downloaded_insta\ (insta_닉네임)\stories_2342929177262230501.mp4
[0057] hitomi_downloaded_insta\ (insta_닉네임)\stories_2341992711879345862.mp4
[0058] hitomi_downloaded_insta\ (insta_닉네임)\stories_2341992693097265281.mp4
[0059] hitomi_downloaded_insta\ (insta_닉네임)\stories_2340610946031831034.jpg
[0060] hitomi_downloaded_insta\ (insta_닉네임)\stories_2340501022568123834.mp4
[0061] hitomi_downloaded_insta\ (insta_닉네임)\stories_2340498882156219354.mp4
[0062] hitomi_downloaded_insta\ (insta_닉네임)\stories_2340498861612347055.mp4
[0063] hitomi_downloaded_insta\ (insta_닉네임)\stories_2339277960854318877.mp4
[0064] hitomi_downloaded_insta\ (insta_닉네임)\stories_2339277920144228632.mp4
[0065] hitomi_downloaded_insta\ (insta_닉네임)\stories_2336897201736568627.mp4
[0066] hitomi_downloaded_insta\ (insta_닉네임)\stories_2336897181973054382.mp4
[0067] hitomi_downloaded_insta\ (insta_닉네임)\stories_2334133348288190449.jpg
[0068] hitomi_downloaded_insta\ (insta_닉네임)\stories_2333233295394610291.mp4
[0069] hitomi_downloaded_insta\ (insta_닉네임)\stories_2333233266529477883.mp4
[0070] hitomi_downloaded_insta\ (insta_닉네임)\stories_2331874612454825574.jpg
[0071] hitomi_downloaded_insta\ (insta_닉네임)\stories_2331269007511747899.jpg
[0072] hitomi_downloaded_insta\ (insta_닉네임)\stories_2330618077200011311.jpg
[0073] hitomi_downloaded_insta\ (insta_닉네임)\stories_2328056280060448613.jpg
[0074] hitomi_downloaded_insta\ (insta_닉네임)\stories_2323107917468538712.jpg
[0075] hitomi_downloaded_insta\ (insta_닉네임)\stories_2322364825664903663.mp4
[0076] hitomi_downloaded_insta\ (insta_닉네임)\stories_2322364808711400140.mp4
[0077] hitomi_downloaded_insta\ (insta_닉네임)\stories_2322364684442601627.mp4
[0078] hitomi_downloaded_insta\ (insta_닉네임)\stories_2316424656591941898.mp4
[0079] hitomi_downloaded_insta\ (insta_닉네임)\stories_2308011607065458265.mp4
[0080] hitomi_downloaded_insta\ (insta_닉네임)\stories_2308011594256101487.mp4
[0081] hitomi_downloaded_insta\ (insta_닉네임)\stories_2308011574249208453.mp4
[0082] hitomi_downloaded_insta\ (insta_닉네임)\stories_2305020652473326078.jpg
[0083] hitomi_downloaded_insta\ (insta_닉네임)\stories_2301382073545215590.mp4
[0084] hitomi_downloaded_insta\ (insta_닉네임)\stories_2301382050837261351.mp4
[0085] hitomi_downloaded_insta\ (insta_닉네임)\stories_2300737850915652372.jpg
[0086] hitomi_downloaded_insta\ (insta_닉네임)\stories_2289750356778580475.jpg
[0087] hitomi_downloaded_insta\ (insta_닉네임)\stories_2288590699729056495.mp4
[0088] hitomi_downloaded_insta\ (insta_닉네임)\stories_2278155567402674176.mp4
[0089] hitomi_downloaded_insta\ (insta_닉네임)\stories_2278155551447613206.mp4
[0090] hitomi_downloaded_insta\ (insta_닉네임)\stories_2276731658648294279.mp4
[0091] hitomi_downloaded_insta\ (insta_닉네임)\stories_2276731638003842323.mp4
[0092] hitomi_downloaded_insta\ (insta_닉네임)\stories_2276729432437504151.jpg
[0093] hitomi_downloaded_insta\ (insta_닉네임)\stories_2265892057088029548.jpg
[0094] hitomi_downloaded_insta\ (insta_닉네임)\stories_2263231543807693501.mp4
[0095] hitomi_downloaded_insta\ (insta_닉네임)\stories_2263231529261933879.mp4
[0096] hitomi_downloaded_insta\ (insta_닉네임)\stories_2263215944830308254.jpg
[0097] hitomi_downloaded_insta\ (insta_닉네임)\stories_2263210655687267597.jpg
[0098] hitomi_downloaded_insta\ (insta_닉네임)\[21-06-30] CQun3vhnBGFgeBHErcTonLviElLPO2FpDwWFoI0_p0.jpg
[0099] hitomi_downloaded_insta\ (insta_닉네임)\[21-06-30] CQuf8XAHxQr3b8J6RVDXhvEwLRDmiy0h9ZDyUM0_p0.jpg

[URLs]

[Messages]
stories: True
Failed to get stories: None
Traceback (most recent call last):
File "extractor\insta_downloader", line 309, in get_imgs
Exception: Invalid page

Traceback (most recent call last):
File "extractor\insta_downloader", line 309, in get_imgs
Exception: Invalid page

Traceback (most recent call last):
File "extractor\insta_downloader", line 309, in get_imgs
Exception: Invalid page

Traceback (most recent call last):
File "extractor\insta_downloader", line 309, in get_imgs
Exception: Invalid page

Invalid page
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\insta_downloader", line 88, in read
File "extractor\insta_downloader", line 461, in get_imgs_all
File "extractor\insta_downloader", line 315, in get_imgs
File "extractor\insta_downloader", line 309, in get_imgs
Exception: Invalid page

Invalid: fail=True
quality: 75%
invalid; revert
EOT: https://www.instagram.com/닉네임 (27.0s)

stories: True
stories: None
stories: 18127244413205390
stories: 17916643720696712
stories: 17916560944701968
stories: 17935890361521048
stories: 18086884033262122
stories: 17890723688102929
stories: 17896111108915010
stories: 17885582345078751
stories: 17863511294460263
stories: 17873541026360255
stories: 17929100950516527
stories: 17879913278183884
stories: 17902789951883022
stories: 18074849062258719
stories: 17863286693457326
stories: 17870545529283377
stories: 17898533050806397
stories: 17895451153833053
stories: 18156789820114241
stories: 17892140701843358
stories: 17887608832899249
stories: 17873360468109302
stories: 17950398964401024
stories: 18064965205250629
stories: 17877604249969691
stories: 17852579381396661
stories: 17980600774325623
stories: 17847928772425359
stories: 17851755494377912
stories: 17892070504731757
stories: 17965728874351316
stories: 18070874482228293
stories: 17959855081350883
stories: 17891032837595299
stories: 18118342654139363
stories: 17959059724332472
stories: 18124866661107360
stories: 18094628146170392
stories: 17929766437396753
stories: 17875360798755304
stories: 17858338955055730
stories: 17955054289341810
stories: 17855199062087127
stories: 17891095663563460
stories: 18035673142270320
stories: 17954905657337135
stories: 17856415529059398
stories: 18105673624145420
stories: 17894008717539635
stories: 17948504053356685
stories: 18103936519153144
stories: 17892903169558871
stories: 18147881014004627
stories: 17858625320020205
stories: 17865141682886745
stories: 17907212557459938
stories: 18150887236030415
stories: 18043077700247217
stories: 17880526513650613
stories: 17940768784371208
stories: 17850497540120530
stories: 18121154431106100
stories: 17878991284674202
stories: 17890673020545077
stories: 18091421338172050
stories: 17862564181921620
stories: 17856262898026069
stories: 18091615453174942
stories: 17855702975052314
stories: 17859939274962537
stories: 17851391342079080
stories: 17917979596421686
stories: 17959186612325169
stories: 17890021660553414
stories: 18105622300089648
stories: 17851951373052899
stories: 17852994638005535
stories: 17864308078821036
stories: 17842273310175070
stories: 17847209009102471
stories: 18141879262053164
stories: 17850742634045526
stories: 17847374927066504
stories: 17876763943613013
stories: 17864234587775999
stories: 17850407803957030
stories: 18082663627174481
stories: 18043544875245260
stories: 18098209663138425
stories: 17859652711807239
stories: 17850989056957717
stories: 18122382028074310
stories: 17868706465647796
stories: 17885746648507860
stories: 17870997754621223
stories: 18025798213261688
stories: 18046031425235916
Too short: 0 / 0
stop
Traceback (most recent call last):
File "utils", line 1084, in start
File "utils", line 1143, in start_
File "extractor\insta_downloader", line 88, in read
File "extractor\insta_downloader", line 461, in get_imgs_all
File "extractor\insta_downloader", line 382, in get_imgs
Exception: Too short: 0 / 0

Invalid: fail=True
quality: 75%
invalid; revert
EOT: https://www.instagram.com/닉네임 (1993.0s)

**Comment by KurtBestor** [comment]
주소를 알려주세요

**Comment by kzts97** [comment]
이틀전부터 다시 잘되네요; 아무튼 해결됫네요ㅎㅎ;
