### ISSUE TITLE
히토미 다운로드가 중간에서 멈춥니다

### ISSUE THREAD

**Issue by legnalegna** [KurtBestor/Hitomi-Downloader#3545]
안녕하세요 늘 고생 많으십니다.

지금 정식버전하고 프리뷰 버전 둘다 동일한 증상인거 같은데요
히토미 데이터를 다운로드를 하려면 몇 장 다운로드 하다가 멈춰 버립니다
저번달 쯤인가.. 비슷한 증상이 있을때 업데이트 되고 해결이 됐는데 비슷한 케이스 인거 같습니다.

==============

Kinoko no Monogatari

version: 3.4a (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 64a50a9f9afc48acafa3a0a19a954207
input: https://hitomi.la/doujinshi/kinoko-no-monogatari-%ED%95%9C%EA%B5%AD%EC%96%B4-1953951.html
type: hitomi
single: False
url: https://hitomi.la/doujinshi/kinoko-no-monogatari-한국어-1953951.html
dir: hitomi_downloaded\Kinoko no Monogatari
zip: 
artist: kakuchou no okina
valid / done: False / True
range / range_p: None / None
time: 1625801758.0714529 (Jul 9)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
갤러리 넘버: 1953951

제목: Kinoko no Monogatari

작가: kakuchou no okina

그룹: toubu rengou daigaku

타입: doujinshi

시리즈: monster hunter

캐릭터: N/A

태그: female:anal, female:bestiality

언어: Korean

[File Names]
[0001] hitomi_downloaded\Kinoko no Monogatari\01.jpg
[0002] hitomi_downloaded\Kinoko no Monogatari\02.jpg
[0003] hitomi_downloaded\Kinoko no Monogatari\03.jpg
[0004] hitomi_downloaded\Kinoko no Monogatari\04.jpg
[0005] hitomi_downloaded\Kinoko no Monogatari\05.jpg
[0006] hitomi_downloaded\Kinoko no Monogatari\06.jpg
[0007] hitomi_downloaded\Kinoko no Monogatari\07.jpg
[0008] hitomi_downloaded\Kinoko no Monogatari\08.jpg
[0009] hitomi_downloaded\Kinoko no Monogatari\09.jpg
[0010] hitomi_downloaded\Kinoko no Monogatari\10.jpg
[0011] hitomi_downloaded\Kinoko no Monogatari\11.jpg
[0012] hitomi_downloaded\Kinoko no Monogatari\12.jpg
[0013] hitomi_downloaded\Kinoko no Monogatari\13.jpg
[0014] hitomi_downloaded\Kinoko no Monogatari\14.jpg
[0015] hitomi_downloaded\Kinoko no Monogatari\15.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/3/34/2b0f9e44f04f912ca80483db31f95ce39da88b78d687ef3379e8080c42b2a343.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/8/2e/2bbcdf03c88dec1210cbd3de8afe93555b0db7937cc24a4adde8a5e8fb6012e8.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://ab.hitomi.la/images/9/5e/55fc6d9834c889014651bf54eef7e4e7968cfa3d40d547b33e440d67d5cae5e9.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/f/57/052b5fa7be6c6409c21cb20a15b3c75adfa1829975cfeacd9a003f5efbc3e57f.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/7/b8/39c1880f05031a159c872046f4ec183170afdf23b7a4cdb63e9c93d94d6ceb87.jpg
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/b/79/784abb87d0fbd872151919ab9c8d356ca873122a1562ab86886678dfe0b4979b.jpg
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/2/39/aba99f22abb9c38176c1c01d8c400d58544cbaf1af253b7d659afbec4333b392.jpg
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://cb.hitomi.la/images/c/d4/2ad0239cd0516d442019b3d428ba8d956c36a4b586748a3ba1ad88210d605d4c.jpg
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/5/3c/fd070d4307fc66c8e55f255d818567f250b1fbd493b5cd6137e3797ce2fdf3c5.jpg
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://ab.hitomi.la/images/f/78/429b166380571a3c2a503f5d50c60e9d6153eeb1af47d1bafab85d954ac8578f.jpg
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/c/dc/66ecd16d9e016bf0741f57717d9b1c529bd0b4b8227f9cc54b9ed901d9de0dcc.jpg
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/a/65/5c6900f9d0d26a6498a4fbb0b4d8bfc7d0208556c50e0be61220de041f89d65a.jpg
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/6/c4/07f79e5641a7405c0ccc2e3163e7693b984d6105160433abd24d70c5e496fc46.jpg
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/f/2d/ed9e8961b5e9984c604c52491095349bcf3085f82e395ae162fa1e43198722df.jpg
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1953951.html) ---> https://bb.hitomi.la/images/c/46/1ba7e8a2f9fad1cf65ba4d86654cb4c289c190ea0870870c0bfec9498388f46c.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 15
get_title__

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\01.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\05.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\02.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\03.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\07.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\08.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\09.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\10.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\14.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\11.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\20212021\Downloads\hitomi_downloader_GUI\hitomi_downloaded\Kinoko no Monogatari\13.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/kinoko-no-monogatari-%ED%95%9C%EA%B5%AD%EC%96%B4-1953951.html (8.1s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by legnalegna** [comment]
대단히 감사합니다!
