### ISSUE TITLE
히토미 다운 문제

### ISSUE THREAD

**Issue by skypasser** [KurtBestor/Hitomi-Downloader#3547]
안녕하세요, 문제가 있어서 적습니다.

제가 히토미를 다운받을려고 하는데 모든 링크들이 끝까지 다운이 안됩니다.
옛날 만화라 안되나 싶어서 제일 최근 것도 다운해봤지만, 똑같이 다운이 안된다고 뜨네요.

무엇이 문제인지 잘 모르겠어서, 무엇을 해야될지 모르겠네요.

이미지가 삭제됬나 싶었는데, 히토미에서는 아주 잘 보입니다, 모든 이미지들이.

[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)

version: 3.4a (21-06-18 02:43:13 UTC)
platform / locale: Windows-10-10.0.17763-SP0 / en
order / group / uid: 0 / False / 671c71c11f2446649cf066dd393700e8
input: https://hitomi.la/doujinshi/chaldea-sex-rotation-%7C-%EC%B9%BC%EB%8D%B0%EC%95%84-%EC%84%B9%EC%8A%A4-%EB%A1%9C%ED%85%8C%EC%9D%B4%EC%85%98-%ED%95%9C%EA%B5%AD%EC%96%B4-1950051.html
type: hitomi
single: False
url: https://hitomi.la/doujinshi/chaldea-sex-rotation-|-칼데아-섹스-로테이션-한국어-1950051.html
dir: hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)
zip: 
artist: unadon
valid / done: False / True
range / range_p: None / None
time: 1625815440.7763073 (Jul 9)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
Gallery ID: 1950051

Title: Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션

Artists: unadon

Groups: deastim

Types: doujinshi

Series: fate grand order

Characters: bb, gudao, jeanne alter, jeanne darc

Tags: female:big breasts, female:bikini, female:blowjob, female:dark skin, female:harem, female:paizuri, female:swimsuit, group, male:sole male, multi-work series

Language: Korean

[File Names]
[0001] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\01_01_1.png
[0002] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\02_01.jpg
[0003] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\03_02.jpg
[0004] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\04_03.jpg
[0005] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\05_04.png
[0006] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\06_05.png
[0007] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\07_06.png
[0008] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\08_07.png
[0009] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\09_08.png
[0010] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\10_09.png
[0011] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\11_10.png
[0012] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\12_11.png
[0013] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\13_12.png
[0014] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\14_13.png
[0015] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\15_14.png
[0016] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\16_15.png
[0017] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\17_16.png
[0018] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\18_17.png
[0019] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\19_18.png
[0020] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\20_19.png
[0021] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\21_20.png
[0022] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\22_21.png
[0023] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\23_22.png
[0024] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\24_23.png
[0025] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\25_24.png
[0026] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\26_25.png
[0027] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\27_26.png
[0028] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\28_27.png
[0029] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\29_28.png
[0030] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\30_29.png
[0031] hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\31_30.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/4/3e/3db4bdacbd011c602cf082159078eec0410a30e4c9eb7e779a4227a2923363e4.png
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://cb.hitomi.la/images/e/a4/8df4c56e51d1424eaa8b649cf6f80ba62783af33690770d791e8ce1e8ddb4a4e.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/7/69/20def4185ccfc2f861a879fec130b051d079ca443ae2310f422ae63d446b5697.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/f/d5/489c82b51a67553f42f9982468cb45110d37d00d13921d2813ca3e46fa3a7d5f.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/9/0e/f8f5921972fae01769167be307595ccf4e014c96887c4d9fea39f284ea1e30e9.png
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/3/ae/54b28e4424e960b3ab8a6c0dd157c130cefa208c52ee7d211f4e89cb89b59ae3.png
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/4/5e/33736c766fd6e16c78e46061bbe2bb0d9a039d5dcae0e06001f9616a426c25e4.png
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/f/33/f4fc28a4e26446b27784ee4f5f7cc1c0b3f6c8c698eced307294fa947b2d133f.png
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://cb.hitomi.la/images/c/b6/ad78b6610426817672e3ae765e8020637f9fde9e03c59af4a9e380d9568ccb6c.png
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/3/4d/5fbe0f70a206abb398a78edbcc97805c9235e55bef6aa19a78c07597a4b294d3.png
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/6/48/5409376aeffe6a2e9a4d1b38780761dfbba4cf4a83a003c43a021f8b97c6d486.png
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/3/44/9ba4406ca26e47b021e93d7f3c69e72919fda0b9c849284adcf9cc34f0dc1443.png
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/9/08/6f0cf2a72c6dc9e8ad3f7587d458194edd99a7a31da59d851a78fd29c36cf089.png
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/1/20/fc7e3c091223df65694a36788ebdae9cb1b8f7d944ab4d6bfc81e687c98f5201.png
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/e/7c/63f4323a53fc2d18c00029190a516a1a274d4063d578ca4c6ef51fbe15c1b7ce.png
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/9/b4/3ad7349b31d0c2dbd5e556cc1a34dc94410124d4d76bade7dfc08a6f06913b49.png
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://cb.hitomi.la/images/8/e0/d41b263bbfa3b6f0573b0adf3c2739ba5f12a16dfd73f44378499557c8f32e08.png
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/9/fa/c4974fb1828e26d0a118ed170e4a37301be24f9ca446274fbc4f78619838afa9.png
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/9/4f/053f4445e4b15beb1ec4cad3fe7923d283cdc84e0bba30c215264093c60f34f9.png
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/8/3d/ea0f08ce62d28ad4b977dc5bdfc8ffebca7fe267a0e4ef6184d0086c9d4093d8.png
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/5/52/b4bb2cb915d2f8bdf3ef68cb663c287d8d1a7a5468fade8d1176d24fd0f20525.png
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/d/6a/99b7195da2468ffb7cf7bbb87c0393ff24042372457de5b91400885de1d4b6ad.png
[0023] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/e/9c/a828fdb6c61ab850a8f3e4cabeb40d45a392efce0d25741ca50cc4f3ab3c79ce.png
[0024] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/a/7e/ab81d2843077e512398b6e6b641499093aa12ccfec035c8b646d0f5cc1f847ea.png
[0025] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://cb.hitomi.la/images/b/dd/7952ab60c50b4fb3b52df3b3f703f0dfef203c038691f9a602ee3a66ce447ddb.png
[0026] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/2/54/db5b196876ca15eb56a9800342d783dfba4ee8b8b986af9d136d17d7ca47b542.png
[0027] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/2/44/aa81dab2bdd74718aa04d2ff03d7cde3feb2fa652dbcecae14a815e109cb8442.png
[0028] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://ab.hitomi.la/images/b/78/7675e003fa2a27909fa2dd6e201def49b985d5600aa3195ac32e948b264e778b.png
[0029] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/4/88/6f7bf34ea81116c852794228c9bd8971c2436e57faacd9d10d7919e4a8d42884.png
[0030] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/f/c7/83c7956e96962263199a0c19249214ebdcfa147683487574cf74e11e71056c7f.png
[0031] LazyUrl_hitomi(https://hitomi.la/reader/1950051.html) ---> https://bb.hitomi.la/images/3/24/85375b346f3db75864a7f6090fe171d7690dc1d24238c4ecb184d0744661b243.jpg

[Messages]
get_imgs server: hitomi:la
FINAL SERVER: hitomi
ehen_url: None
imgs: 31
get_title__

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\01_01_1.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\07_06.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\09_08.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\02_01.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\14_13.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\05_04.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\13_12.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\17_16.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\21_20.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\08_07.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\22_21.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\18_17.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\24_23.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\20_19.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\26_25.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\25_24.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\28_27.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\29_28.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\30_29.png
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : \\?\C:\Users\phill\Downloads\hitomi_downloader_GUI\hitomi_downloaded\[Unadon] Chaldea SEX Rotation ｜ 칼데아 섹스 로테이션 (1950051)\31_30.jpg
Traceback (most recent call last):
File "downloader", line 829, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/chaldea-sex-rotation-%7C-%EC%B9%BC%EB%8D%B0%EC%95%84-%EC%84%B9%EC%8A%A4-%EB%A1%9C%ED%85%8C%EC%9D%B4%EC%85%98-%ED%95%9C%EA%B5%AD%EC%96%B4-1950051.html (9.9s)

**Comment by longanisa** [comment]
저두요 ㅠ 비슷한 일 때문에 새로운 버전 깔고 잘 되나 싶었는데 2주도 안돼서 또 그러네요...ㅠ

**Comment by Mango202** [comment]
타 어플들로 테스트 해보았는데 다른 어플들도 지금 비슷한 상황입니다.  아무래도 프로그램 문제가 아니고 락이나 조치를 걸어놓은 것 같습니다.

**Comment by k750627** [comment]
저도 갑자기 안되네요..

**Comment by hohoe** [comment]
#3539 테스트버전 받으세요~
