### ISSUE TITLE
업데이트 시도를 했더니 에러와 함께 기존 목록이 타노스되었습니다.

### ISSUE THREAD

**Issue by qgftrk** [KurtBestor/Hitomi-Downloader#3557]
'새 버전이 있습니다(v3.5)'라는 창을 보고 자동 업데이트를 선택했더니, 목록이 원래 2800개 정도였는데 에러 메시지가 뜨면서 1361개로 줄었고, 정작 v3.5로 업데이트는 안 됐네요.
그렇게 목록이 절반으로 줄어든 다음에 다시 업데이트를 시도해서 업데이트는 성공했습니다만..

이렇게 날아간 목록을 복원할 방법은 있을까요? 복원이 불가능하더라도, 이렇게 기존 목록이 갑자기 날아가는 일이 재발하지 않게 할 방법은 있을까요?

대충 읽어보니 아래 두 종류의 메세지가 반복되는 것 같네요.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 3676, in append_datas_
  File "json\__init__", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1455, in foo
  File "MyConfigParser", line 69, in get
IndexError: list index out of range

혹시나 해서 오류 메세지를 ctrl+a로 선택해서 텍스트 파일로 저장한 것도 첨부합니다.
[error m.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/6797066/error.m.txt)

(기존 다운로드받은 목록 정보에서 필터 검색으로 원하는 작업물 선택, 개별 작업 선택해서 해당 폴더 열기, 개별 작업의 링크 주소 복사 후 인터넷 접속, 새로 다운받는 페이지의 중복 확인 등의 여러 이유로 다운로드받은 작업 정보를 저장해두는 게 편해서 삭제를 안 하고 가급적 쌓아두다보니 갯수가 꽤나 많습니다만, 목록이 너무 많다보니 에러가 발생하는 것일 수도 있겠네요.)

**Comment by KurtBestor** [comment]
어떤 버전에서 업데이트 했나요?
해당 설정 파일 (*.INI) 보내주시면 분석해볼게요

**Comment by qgftrk** [comment]
hitomi_downloader_GUI.ini
<https://drive.google.com/file/d/1gpFEXQaH0IYvDSvf9ryC9jzibyaPdjqU/view?usp=drive_web>

여기요

2021년 7월 12일 (월) 오전 12:10, Kurt Bestor ***@***.***>님이 작성:

**Comment by KurtBestor** [comment]
접근 권한이 없어서 못 봐요

**Comment by qgftrk** [comment]
아, 죄송합니다. 아래 링크로 다시 확인바랍니다.
https://drive.google.com/file/d/1gpFEXQaH0IYvDSvf9ryC9jzibyaPdjqU/view?usp=sharing

**Comment by KurtBestor** [comment]
그룹이 110 개, 작업이 1398 개 있고 특이한 건 없네요
데이터 덮어씌우신 것 같은데 그러면 문제점을 찾을 수 없어요
