### ISSUE TITLE
[etc 사이트][spankbang.com] Invalid로 인한 다운로드 중지, 그로 인한 해결 방안 문의 건

### ISSUE THREAD

**Issue by kil1113** [KurtBestor/Hitomi-Downloader#3566]
항상 고생하십니다.
#2936 을 읽고난 뒤 지속적으로 베타 파일을 통해 다운로드를 시도 하였으나, 해결 되지 아니하여 해결 할 수 있는 방법 문의드립니다.
쿠키도 추가 해보고, 프로그램 내 dpi 및 외부 사용 등 가능한 행동을 하였으나 해결 되지 않더군요, 아쉽습니다.

즐거운 하루 되시길 바랍니다. 금일 고생하셨습니다.

Invalid: [etc] https://spankbang.com/5nuw2/video/hmv+slumber+party+by+nikita+4w

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 008c4b8d198942c19ec4cdc24eee3592
input: https://spankbang.com/5nuw2/video/hmv+slumber+party+by+nikita+4w
type: etc
single: True
url: https://spankbang.com/5nuw2/video/hmv+slumber+party+by+nikita+4w
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1626356931.649952 (Jul 15)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
extractor: spankbang
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 634, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 2288, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\spankbang", line 77, in _real_extract
video_id, headers={'Cookie': 'country=US'})
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 801, in _download_webpage
expected_status=expected_status)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 667, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 652, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1087, in start
File "utils", line 1157, in start_
File "extractor\etc_downloader", line 27, in read
File "<decorator-gen-91>", line 2, in get_video
File "constants", line 907, in wrapper
File "constants", line 878, in wrapper
File "extractor\etc_downloader", line 67, in get_video
File "ytdl", line 314, in extract_info
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 285, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://spankbang.com/5nuw2/video/hmv+slumber+party+by+nikita+4w (2.9s)

extractor: spankbang
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 634, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 2288, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\spankbang", line 77, in _real_extract
video_id, headers={'Cookie': 'country=US'})
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 801, in _download_webpage
expected_status=expected_status)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 667, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 652, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1087, in start
File "utils", line 1157, in start_
File "extractor\etc_downloader", line 27, in read
File "<decorator-gen-91>", line 2, in get_video
File "constants", line 907, in wrapper
File "constants", line 878, in wrapper
File "extractor\etc_downloader", line 67, in get_video
File "ytdl", line 314, in extract_info
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 285, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://spankbang.com/5nuw2/video/hmv+slumber+party+by+nikita+4w (2.9s)

extractor: spankbang
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 634, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 2288, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\spankbang", line 77, in _real_extract
video_id, headers={'Cookie': 'country=US'})
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 801, in _download_webpage
expected_status=expected_status)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 667, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 652, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1087, in start
File "utils", line 1157, in start_
File "extractor\etc_downloader", line 27, in read
File "<decorator-gen-91>", line 2, in get_video
File "constants", line 907, in wrapper
File "constants", line 878, in wrapper
File "extractor\etc_downloader", line 67, in get_video
File "ytdl", line 314, in extract_info
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\kil11\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 285, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://spankbang.com/5nuw2/video/hmv+slumber+party+by+nikita+4w (24.1s)

**Comment by fade-out-0770** [comment]
오 spankbang도 지원이 됐었군요. ㅎㅎ

**Comment by kil1113** [comment]
> 오 spankbang도 지원이 됐었군요. ㅎㅎ

youtube 다운로드 방식을 사용하는 것 같은데 될 때도 있고 안될 때도 있더군요. 될 때는 폰헙 대용으로 충분한거 같습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/ytdl-org/youtube-dl/issues/29266

**Comment by kil1113** [comment]
> 참고해주세요: [ytdl-org/youtube-dl#29266](https://github.com/ytdl-org/youtube-dl/issues/29266)

고맙읍니다 선생님.... 항상 좋은 일만 가득하실 겁니다..
