### ISSUE TITLE
핀터레스트에서 다운로드가 안되는 것 같습니다 ㅠㅠ

### ISSUE THREAD

**Issue by akahhh** [KurtBestor/Hitomi-Downloader#3567]
현재 일반판 테스트판 두가지 사용해보았는데 핀터레스트에서 사용이 안되는 것 같습니다 ㅠㅠ

Invalid: [pinter] https://www.pinterest.co.kr/IUstar165/_saved/

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a2fe678f338c4a3993b6e60498be9ca1
input: https://www.pinterest.co.kr/IUstar165/_saved/
type: pinter
single: False
url: https://www.pinterest.co.kr/IUstar165/_saved/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1626414151.605145 (Jul 16)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
type: board
type: board
type: board
type: board
Not Found
stop
Traceback (most recent call last):
File "utils", line 1073, in start
File "<decorator-gen-60>", line 2, in init
File "constants", line 907, in wrapper
File "constants", line 878, in wrapper
File "extractor\pinter_downloader", line 32, in init
File "extractor\pinter_downloader", line 80, in get_info
File "extractor\pinter_downloader", line 106, in board
File "<decorator-gen-61>", line 2, in _call
File "constants", line 907, in wrapper
File "constants", line 878, in wrapper
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\pinter_downloader", line 144, in _call
Exception: Not Found

Invalid: fail=True
EOT: https://www.pinterest.co.kr/IUstar165/_saved/ (60.9s)

**Comment by KurtBestor** [comment]
다음과 같이 보드를 특정해야해요: https://www.pinterest.com/IUstar165/lilac/
