### ISSUE TITLE
페이스북 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by end9990** [KurtBestor/Hitomi-Downloader#3583]
4분 59초 뒤 다시 시작: https://www.facebook.com/MusumeCosplayModel

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 1a021e37fbef4ed584ffa7519e0b0cbb
input: https://www.facebook.com/MusumeCosplayModel
type: facebook
single: False
url: https://www.facebook.com/MusumeCosplayModel
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1626961824.8545892 (Jul 22)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
is_latency_sensitive_broadcast (facebook_MusumeCosplayModel)
No photo div
stop
Traceback (most recent call last):
File "utils", line 1087, in start
File "utils", line 1157, in start_
File "extractor\facebook_downloader", line 122, in read
File "extractor\facebook_downloader", line 169, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/MusumeCosplayModel (2.8s)

요래 뜨면서 안됩니다.

쿠키 붙여넣기도 했는데 페북의 어떤 링크를 붙혀넣어도 다운로드가 안됩니다.

해결방법이 있나요?

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2417

**Comment by end9990** [comment]
아 넵 감사합니다
