### ISSUE TITLE
Seacher에서 기본데이터가 다운되지 않습니다.

### ISSUE THREAD

**Issue by Ende7** [KurtBestor/Hitomi-Downloader#3592]
자주 묻는 질문의 버그와는 좀 틀리네요.
Traceback (most recent call last):
  File "hitomi_searcher", line 205, in download_json
  File "hitomi_searcher", line 366, in download_json_
  File "myjson", line 8, in loads
  File "simdjson\__init__", line 52, in loads
  File "simdjson/csimdjson", line 468, in csimdjson.Parser.parse
ValueError: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.

**Comment by KurtBestor** [comment]
지금도 그런가요?

**Comment by Ende7** [comment]
아니오 지금은 그렇지 않습니다. 일시적인 오류였나봐요.
Born in the Darkness Shining in the tempest
010-6369-9060


2021년 8월 2일 (월) 오후 5:06, Kurt Bestor ***@***.***>님이 작성:
