### ISSUE TITLE
니코동 회원영상 다운로드 실패합니다

### ISSUE THREAD

**Issue by 500376** [KurtBestor/Hitomi-Downloader#3601]
유튜브나 니코동 일반영상은 정상적으로 다운로드 됩니다.
처음 20프로 정도 잘 되다가 멈추면서 주황색으로 오류뜹니다.
최신버전, 테스트버전 모두 사용해보았고 쿠키 불러오기 로그인도 해봤습니다.

version: 3.5 (21-07-19 17:09:59 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / ae37706eae8a4719999be06d42a5ad75
input: https://www.nicovideo.jp/watch/1572956463
type: nico
single: True
url: https://www.nicovideo.jp/watch/1572956463
dir: hitomi_downloaded_nico
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1627712339.9585793 (Jul 31)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4

[URLs]
[0001] LazyUrl(https://www.nicovideo.jp/watch/so35913913) ---> http://pf00289a4ae.dmc.nico/vod/ht2_nicovideo/nicovideo-so35913913_a9a67959e92bf1f75f8d7cf7a675594ee728e7c77ba540f52ec56e8b07ff306c?ht2_nicovideo=39003061.gs0kn6z9pz_qx3ivt_3fpggpuw61wp0

[Messages]
downloader_v3 fail... p[238 / 1122]
Traceback (most recent call last):
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 445, in _make_request
File "<string>", line 3, in raise_from
File "urllib3\connectionpool", line 440, in _make_request
File "http\client", line 1369, in getresponse
File "http\client", line 310, in begin
File "http\client", line 279, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 756, in urlopen
File "urllib3\util\retry", line 532, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 706, in urlopen
File "urllib3\connectionpool", line 445, in _make_request
File "<string>", line 3, in raise_from
File "urllib3\connectionpool", line 440, in _make_request
File "http\client", line 1369, in getresponse
File "http\client", line 310, in begin
File "http\client", line 279, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader_v3", line 67, in run
File "requests\sessions", line 555, in get
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

downloader_v3 fail... p[237 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

downloader_v3 fail... p[239 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

downloader_v3 fail... p[240 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

downloader_v3 fail... p[238 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

downloader_v3 fail... p[237 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

downloader_v3 fail... p[239 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

downloader_v3 fail... p[240 / 1122]
Traceback (most recent call last):
File "downloader_v3", line 75, in run
Exception: Not partial content: 403

### reset size ###
use just download: overwrite=False

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

Fail : \\?\C:\Users\500376\Desktop\프로그램\hitomi_downloader_GUI\hitomi_downloaded_nico\⛔[実写ASMR／耳舐め] 制服♡先生と生徒のいけない関係♡【KU100／カメラ】 (so35913913).mp4
Traceback (most recent call last):
File "downloader", line 843, in download
Exception: 403

stop
valid=False 1
EOT: https://www.nicovideo.jp/watch/1572956463 (78.4s)

**Comment by KurtBestor** [comment]
제가 구독하고있는 채널이 없어서 테스트 해볼 수 없는데 계정 주시면 테스트 해볼게요

**Comment by rritte** [comment]
> 제가 구독하고있는 채널이 없어서 테스트 해볼 수 없는데 계정 주시면 테스트 해볼게요

저도 같은 현상이 생기는데 제 계정 빌려드릴까요?

**Comment by KurtBestor** [comment]
@rritte 디스코드 DM 으로 보내주세요

**Comment by rritte** [comment]
> @rritte 디스코드 DM 으로 보내주세요

디코 써본적이 없어서;; 깔긴 했는데 어떻게 보내드리면 될까요?

**Comment by KurtBestor** [comment]
프로그램 우측 하단 디스코드 아이콘 눌러서 서버 들어오면 저 있어요

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/131779500-864f2a75-3b69-4c38-8838-4854eacfb7bd.png)

테스트 해봤는데 재현할 수가 없네요

**Comment by YoonMeonol** [comment]
개발자님, 아직도 이 문제가 지속되는 것 같습니다.
![image](https://user-images.githubusercontent.com/96647450/147380969-a21fa633-9c4d-4e4c-972a-b72f149e44c9.png)
저도 니코동 쿠키 불러오고, 테스트 버전, 일반 버전 프로그램 2개다 해봤는데요,
길이가 짧은 영상은 다운로드가 잘되는데, 좀 긴 영상들은 저렇게 중간에 다운이 멈춥니다.  답변주시면 감사드리겠습니다.
제 니코동 계정으로 테스트해보셔도 됩니다.

**Comment by YoonMeonol** [comment]
![image](https://user-images.githubusercontent.com/96647450/147381036-7d150885-be3b-4235-9420-67b0ddc53a08.png)
엥.. 2번째로 시도해보았는데 해결되었습니다..
처음에는 왜 안됬는지 모르겠네요.. 이렇게 되다가 안되다가 합니다..
