### ISSUE TITLE
저장된 작업 파일이 어느 정도 크기를 넘어갈 시 불러오기에 문제가 생깁니다.

### ISSUE THREAD

**Issue by ppliff2125** [KurtBestor/Hitomi-Downloader#3623]
---------------------------
Error
---------------------------
가져오기 실패
---------------------------
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 7553, in importTasks
  File "myjson", line 5, in load
  File "simdjson\__init__", line 38, in load
  File "simdjson/csimdjson", line 455, in csimdjson.Parser.parse
ValueError: This parser can't support a document that big

---------------------------
OK   
---------------------------

다음과 같은 오류가 생기네요. 이슈에 해당 오류는 올라온 것 같지 않아 제보합니다.

**Comment by KurtBestor** [comment]
작업 파일 크기가 얼마나 되나요?

**Comment by ppliff2125** [comment]
작업 개수는 4천 개 남짓이었던 걸로 기억하고, 저장된 파일 크기는 총 765메가바이트입니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ppliff2125** [comment]
정상적으로 불러오기가 됐습니다. 언제나 감사합니다! :)
