### ISSUE TITLE
urllib problem with proxy

### ISSUE THREAD

**Issue by Emagelle** [KurtBestor/Hitomi-Downloader#3632]
When using newest version of Hitomi-Downloader I found that it won't work with e-hentai and instagram. As I look up at the log it says :

ValueError: check_hostname requires server_hostname

This bug also common when using pip install with proxy.

Then I looked up over the Internet trying to find a solution. It seems caused by proxy software. I have to set up hitomi proxy to 127.0.0.1:10809 for downloading, and it seems like it'll cause the bug while it using urllib version after 1.25.11.

Now I tried a ramdom old release (released in last year) and the problem gone. I wonder if you would fix this in the future release. and could you please tell me the least release using urllib 1.25.11? 

Thanks

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Emagelle** [comment]
Tried the link provided. Still not working. Attached the log.

[Messages]
stories: False
Traceback (most recent call last):
File "downloader", line 291, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\insta_downloader", line 306, in get_imgs
File "extractor\insta_downloader", line 115, in read_html
File "downloader", line 331, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 108, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 696, in urlopen
File "urllib3\connectionpool", line 964, in _prepare_proxy
File "urllib3\connection", line 359, in connect
File "urllib3\connection", line 506, in _connect_tls_proxy
File "urllib3\util\ssl_", line 432, in ssl_wrap_socket
File "urllib3\util\ssl_", line 474, in _ssl_wrap_socket_impl
File "ssl", line 423, in wrap_socket
File "ssl", line 827, in _create
ValueError: check_hostname requires server_hostname

**Comment by KurtBestor** [comment]
Take a screenshot and show me your proxy settings in `Options` - `Preferences` - `Advanced` - `Proxy`.

**Comment by Emagelle** [comment]
![image](https://user-images.githubusercontent.com/49598414/128904436-39648555-6761-40a5-8789-69b8a8d68872.png)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Emagelle** [comment]
It works! Good Job! Thanks!!!
