### ISSUE TITLE
지금 히토미 쪽 다운로드가 정상적으로 완료되지 않습니다.

### ISSUE THREAD

**Issue by ggoke123** [KurtBestor/Hitomi-Downloader#3638]
파일 한 두개씩 비정상적으로 다운로드가 되질 않습니다.

모든 링크가 그런거 같진 않습니다

에러 난 거 하나 올려봅니다
[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 44 / False / 4ae6bfa723dc4e639f1733a1f41763d4
input: https://hitomi.la/doujinshi/kakushitai-koto-%7C-%EA%B0%90%EC%B6%94%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EA%B2%83-%ED%95%9C%EA%B5%AD%EC%96%B4-1980956.html
type: hitomi
single: False
url: https://hitomi.la/doujinshi/kakushitai-koto-|-감추고-싶은-것-한국어-1980956.html
dir: hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)
zip: 
artist: ame
valid / done: False / True
range / range_p: None / None
time: 1628613035.659658 (Aug 11)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False

[Gallery]
갤러리 넘버: 1980956

제목: Kakushitai Koto ｜ 감추고 싶은 것

작가: ame

그룹: orangemaru

타입: doujinshi

시리즈: the idolmaster

캐릭터: madoka higuchi, producer

태그: female:beauty mark, female:sole female, female:stockings, male:sole male

언어: Korean

[File Names]
[0001] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\01.png
[0002] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\02.png
[0003] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\03.png
[0004] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\04.png
[0005] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\05.png
[0006] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\06.png
[0007] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\07.png
[0008] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\08.png
[0009] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\09.png
[0010] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\10.png
[0011] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\11.png
[0012] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\12.png
[0013] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\13.png
[0014] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\14.png
[0015] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\15.png
[0016] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\16.png
[0017] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\17.png
[0018] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\18.png
[0019] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\19.png
[0020] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\20.png
[0021] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\21.png
[0022] hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\22.png

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 01.png
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 02.png
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 03.png
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 04.png
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 05.png
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 06.png
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 07.png
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> https://ab.hitomi.la/images/5/80/f7938d6c68416da853aeee14a4bbd0410b111e08875bb0db36072639f7238805.png
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 09.png
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 10.png
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 11.png
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 12.png
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 13.png
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 14.png
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 15.png
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 16.png
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 17.png
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 18.png
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 19.png
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 20.png
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 21.png
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1980956.html) ---> 【local_lazy】 22.png

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 22
get_title__

Fail_404 : \\?\G:\hitomi_downloader_GUI\hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\08.png
Traceback (most recent call last):
File "downloader", line 809, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/kakushitai-koto-%7C-%EA%B0%90%EC%B6%94%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EA%B2%83-%ED%95%9C%EA%B5%AD%EC%96%B4-1980956.html (24.8s)

get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 22

Fail_404 : \\?\G:\hitomi_downloader_GUI\hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\08.png
Traceback (most recent call last):
File "downloader", line 809, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/kakushitai-koto-%7C-%EA%B0%90%EC%B6%94%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EA%B2%83-%ED%95%9C%EA%B5%AD%EC%96%B4-1980956.html (5.3s)

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/kakushitai-koto-%7C-%EA%B0%90%EC%B6%94%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EA%B2%83-%ED%95%9C%EA%B5%AD%EC%96%B4-1980956.html)
Find_ehen(id:1980956, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 568, in read
File "hitomi_downloader", line 445, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
File "extractor\ehen_downloader", line 86, in find_ehen
Exception: out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/kakushitai-koto-%7C-%EA%B0%90%EC%B6%94%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EA%B2%83-%ED%95%9C%EA%B5%AD%EC%96%B4-1980956.html)
Find_ehen(id:1980956, ex:True)
Find in HK...
not found in HK
max_page = 43344
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.1
BFS: 5.2
BFS: 6.3
BFS: 7.9
BFS: 9.6
BFS: 11.8
BFS: 16.4
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 568, in read
File "hitomi_downloader", line 445, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 22

Fail_404 : \\?\G:\hitomi_downloader_GUI\hitomi_downloaded\[Ame] Kakushitai Koto ｜ 감추고 싶은 것 (1980956)\08.png
Traceback (most recent call last):
File "downloader", line 809, in download
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

stop
valid=False 1
EOT: https://hitomi.la/doujinshi/kakushitai-koto-%7C-%EA%B0%90%EC%B6%94%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EA%B2%83-%ED%95%9C%EA%B5%AD%EC%96%B4-1980956.html (32.6s)

**Comment by duach** [comment]
같은 상황입니다.  파일 3~5개씩 누락됩니다.

**Comment by ToumaKun** [comment]
> 같은 상황입니다. 파일 3~5개씩 누락됩니다.

same problem
![image](https://user-images.githubusercontent.com/88413286/128935808-cc57395d-1690-4155-acfe-1d16299c5889.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by pageone-easy** [comment]
최초 질문자는 아니지만 테스트 올려주신 버전은 잘 받아집니다. 감사합니다.
