### ISSUE TITLE
인스타그램 다운로드

### ISSUE THREAD

**Issue by helpmepls08** [KurtBestor/Hitomi-Downloader#3640]
Invalid: [insta] https://www.instagram.com/soyeon._.s2

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 4 / False / 16345a672b214d799e32f6097b6b1c73
input: https://www.instagram.com/soyeon._.s2
type: insta
single: False
url: https://www.instagram.com/soyeon._.s2
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1628594088.988134 (Aug 10)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 1073, in start
File "extractor\insta_downloader", line 49, in init
File "utils", line 505, in __get__
File "extractor\insta_downloader", line 53, in username
File "extractor\insta_downloader", line 200, in get_username
File "extractor\insta_downloader", line 171, in get_sd
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://www.instagram.com/soyeon._.s2 (9.9s)

작업정보에요.
다운로드 하려니까 안되네요.
무한로딩만 하거나 이렇게 안되거나 해요.
인스타 계정이 잠겼어요.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/129133675-e35d179f-65a4-41f7-8821-ed498fe149b9.png)

재현할 수가 없네요

웹브라우저에선 제대로 보이나요?

**Comment by helpmepls08** [comment]
예 정상적으로 웹에선 보입니다. 크롬입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
