### ISSUE TITLE
픽시브코믹이 다운이 안되네요

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#3700]
항상 감사히 잘 쓰고 있습니다
픽시브코믹이 갑자기 안되네요
정보 올립니다

4분 55초 뒤 다시 시작: https://comic.pixiv.net/works/6396

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 1 / False / 058b7bcb68174ec99754c885395d9e42
input: https://comic.pixiv.net/works/6396
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/6396
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1628916442.7085593 (Aug 14)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (8.2s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (3.1s)

no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (9.6s)

no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (7.4s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (6.4s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (8.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (8.2s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (7.9s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (7.9s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (8.2s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (7.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (10.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/6396 (8.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
오 잘되네요 정말 감사합니다
