### ISSUE TITLE
av 쏘걸 자막영상 관련 이슈입니다

### ISSUE THREAD

**Issue by acidbbbb** [KurtBestor/Hitomi-Downloader#3703]
Invalid: [sogirl] https://kr22.sogirl.co/stars-368-%ec%95%84%ec%98%a4%ec%a1%b0%eb%9d%bc-%ed%9e%88%ec%b9%b4%eb%a6%ac-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / b2a26bad7729453383533106aebd5821
input: https://kr22.sogirl.co/stars-368-%ec%95%84%ec%98%a4%ec%a1%b0%eb%9d%bc-%ed%9e%88%ec%b9%b4%eb%a6%ac-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/
type: sogirl
single: True
url: https://kr22.sogirl.co/stars-368-%ec%95%84%ec%98%a4%ec%a1%b0%eb%9d%bc-%ed%9e%88%ec%b9%b4%eb%a6%ac-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1628960162.804089 (Aug 15)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "dynamic_module_0", line 24, in read
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kr22.sogirl.co/stars-368-%ec%95%84%ec%98%a4%ec%a1%b0%eb%9d%bc-%ed%9e%88%ec%b9%b4%eb%a6%ac-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/ (1.4s)

자막 관련된 영상은 다른 플레이어를 사용중이어서 그런건지 스크립트 적용해도 제대로 다운이 되지 않습니다.

고생많으십니다. 확인한번만 부탁드립니다.

**Comment by juso123** [comment]
플레이어 암호 풀어도 어차피  referrer 도메인이 kr22.sogirl.co 아니면 크롤링해서 스트리밍불가.
버니호스팅은 mp4나 m3u8파일이면 ts파일 다운해서 FFMPEG로 mp4파일로 복구가능 (일단 버거로움)
