### ISSUE TITLE
avgle 다운불가

### ISSUE THREAD

**Issue by hun0817** [KurtBestor/Hitomi-Downloader#3722]
아래 처럼 뜨고 다운이 되질 않습니다. 
Chrome Extension의 재설치와 히토미 다운로더 또한 재설치 하였지만 소용이 없네요

Invalid: [avgle] https://avgle.com/video/QtuHwHmigHl/WAVR-132

version: 3.6 (21-08-19 10:37:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 13fd34ae31024ec38c162e7544f3a8ce
input: https://avgle.com/video/QtuHwHmigHl/WAVR-132
type: avgle
single: True
url: https://avgle.com/video/QtuHwHmigHl/WAVR-132
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1629467400.11868 (Aug 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
version: 0.2
https://cdn.qooqlevideo.com/key=i-YgL+cYI9aT2xWvqHIygg,end=1629470814,limit=2/ip=14.53.253.43/referer=force,.avgle.com/data=1629470814/media=hlsA/487799.mp4/seg-1-v1-a1.ts
https://cdn.qooqlevideo.com/key=i-YgL+cYI9aT2xWvqHIygg,end=1629470814,limit=2/ip=14.53.253.43/referer=force,.avgle.com/data=1629470814/media=hlsA/487799.mp4/seg-2-v1-a1.ts
https://ip219431340.cdn.qooqlevideo.com/key=a+U3PdoKwIey8Rm72gQiMA,s=,end=1629470814,limit=2/data=1629470814/state=YR+uDjX9/referer=force,.avgle.com/reftag=56109644/media=hlsA/35/177/1/240011831.mp4/seg-3-v1-a1.ts
https://ip219431340.cdn.qooqlevideo.com/key=a+U3PdoKwIey8Rm72gQiMA,s=,end=1629470814,limit=2/data=1629470814/state=YR+uDjX9/referer=force,.avgle.com/reftag=56109644/media=hlsA/35/177/1/240011831.mp4/seg-4-v1-a1.ts
version: 0.2
https://cdn.qooqlevideo.com/key=i-YgL+cYI9aT2xWvqHIygg,end=1629470814,limit=2/ip=14.53.253.43/referer=force,.avgle.com/data=1629470814/media=hlsA/487799.mp4/seg-1-v1-a1.ts
https://cdn.qooqlevideo.com/key=i-YgL+cYI9aT2xWvqHIygg,end=1629470814,limit=2/ip=14.53.253.43/referer=force,.avgle.com/data=1629470814/media=hlsA/487799.mp4/seg-2-v1-a1.ts
https://ip219431340.cdn.qooqlevideo.com/key=a+U3PdoKwIey8Rm72gQiMA,s=,end=1629470814,limit=2/data=1629470814/state=YR+uDjX9/referer=force,.avgle.com/reftag=56109644/media=hlsA/35/177/1/240011831.mp4/seg-3-v1-a1.ts
https://ip219431340.cdn.qooqlevideo.com/key=a+U3PdoKwIey8Rm72gQiMA,s=,end=1629470814,limit=2/data=1629470814/state=YR+uDjX9/referer=force,.avgle.com/reftag=56109644/media=hlsA/35/177/1/240011831.mp4/seg-4-v1-a1.ts
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
File "urllib\request", line 1350, in do_open
File "http\client", line 1277, in request
File "http\client", line 1323, in _send_request
File "http\client", line 1272, in endheaders
File "http\client", line 1032, in _send_output
File "http\client", line 972, in send
File "http\client", line 1447, in connect
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "downloader", line 314, in read_html
File "urllib\request", line 525, in open
File "urllib\request", line 543, in _open
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 1393, in https_open
File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 410, in increment
File "urllib3\packages\six", line 734, in reraise
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1167, in start_
File "extractor\avgle_downloader", line 28, in read
File "<decorator-gen-73>", line 2, in get_video
File "constants", line 895, in wrapper
File "constants", line 866, in wrapper
File "extractor\avgle_downloader", line 59, in get_video
File "downloader", line 341, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 113, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://avgle.com/video/QtuHwHmigHl/WAVR-132 (0.7s)

**Comment by isnteasy** [comment]
avgle 영상 다운하면 Invalid: [avgle] https://~~ 이런 식으로 오류가 뜹니다 개발자님!!
