### ISSUE TITLE
유튜브 재생목록 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by end9990** [KurtBestor/Hitomi-Downloader#3733]

**Comment by end9990** [comment]
재생목록을 링크 복사하면 그 재생목록의 첫번째 영상만 다운로드되며, 재생목록 그 자체 제목의 링크를 복사하면 오류로 작업이 안됩니다.
옛날엔 됐던거같은데ㅠㅠ

**Comment by end9990** [comment]
오류는 이렇게 뜹니다


3분 17초 뒤 다시 시작: https://www.youtube.com/playlist?list=PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 20d4cfcca64947728202da92e7fe9a7d
input: https://www.youtube.com/playlist?list=PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD
type: youtube
single: True
url: https://www.youtube.com/playlist?list=PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: 9999999999999999999 / None
time: 1629731623.7849245 (Aug 24)
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
[youtube:tab] PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD: Downloading webpage
[download] Downloading playlist: 호쇼 마린
[youtube:tab] PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD: Downloading webpage
[download] Downloading playlist: 호쇼 마린
[youtube:tab] PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD: Downloading webpage
[download] Downloading playlist: 호쇼 마린
[youtube:tab] PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD: Downloading webpage
[download] Downloading playlist: 호쇼 마린
Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\youtube_downloader", line 373, in read
File "<decorator-gen-31>", line 2, in get_videos
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\youtube_downloader", line 427, in get_videos
File "<decorator-gen-32>", line 2, in read_playlist
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\youtube_downloader", line 459, in read_playlist
File "ytdl", line 336, in extract_info
File "C:\Users\ENDER\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\ENDER\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\ENDER\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 847, in __extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "C:\Users\ENDER\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 933, in process_ie_result
return self.__process_playlist(ie_result, download)
File "C:\Users\ENDER\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 1030, in __process_playlist
ie_entries, playliststart, playlistend))
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.

Invalid: fail=True
EOT: https://www.youtube.com/playlist?list=PLMzmnFW-auWAIGS7mHBiwcP68jJ-3EksD (3.8s)

**Comment by end9990** [comment]
#2716

아 혹시나 해서 글 찾아봤더니 여기나온 테스트 프로그램으로 다운받으니 되네요 

언제나 감사합니다 ㅎㅎ
