### ISSUE TITLE
인스타 쿠키추가 했는데도 자꾸 쿠키 추가하래요 ㅜㅜ

### ISSUE THREAD

**Issue by nell8988** [KurtBestor/Hitomi-Downloader#3734]
Login required; Update your cookies
https://www.instagram.com/yuji_moriguchi

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 5fa42051b97c4b209ba04e3136a5b532
input: https://www.instagram.com/yuji_moriguchi
type: insta
single: False
url: https://www.instagram.com/yuji_moriguchi
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1629734864.6628168 (Aug 24)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1082, in start
File "extractor\insta_downloader", line 43, in init
File "extractor\insta_downloader", line 26, in get_session
errors.LoginRequired

Invalid: fail=False
EOT: https://www.instagram.com/yuji_moriguchi (0.0s)

쿠키 따서 불러오기 열번을 반복해도 계속 쿠키업뎃 하라네요 ㅜㅜㅜㅜㅜ

**Comment by nell8988** [comment]
아...해결됐습니다. 인스타 '메인화면'에서 쿠키를 따야 작동하는거군요....하 엄청 헤멨네.....ㅜㅜ
