### ISSUE TITLE
비리비리 영상 다운 문의

### ISSUE THREAD

**Issue by abcs122** [KurtBestor/Hitomi-Downloader#3777]
안녕하세요 
비리비리 영상에 다운로더를 사용하고 있는데 오늘 갑자기 다운이 안되네요..
 
영상이 나눠져 있는데 첫 번째 영상만 받아집니다...
https://www.bilibili.com/video/BV1ov411A7az?p=2
나머지 영상은 오류가 뜨면서 다운이 안되요
다른 영상들도 확인해봤는데 다 첫번째 영상만 가능해요

#52나 비리비리 관련 문의 보면서 다 해봤는데 안되네요...

어떻게 해야할까요...ㅠㅠ

===========================================

Invalid: [bili] https://www.bilibili.com/video/BV1ov411A7az?p=2

version: 3.6 (21-09-02 08:55:15 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / e0c07668e8b24619b169e0cd2d13a2b8
input: https://www.bilibili.com/video/BV1ov411A7az?p=2
type: bili
single: True
url: https://www.bilibili.com/video/BV1ov411A7az/?p=2
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1630588534.8304806 (2 Sep)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1ov411A7az?p=2 -> https://www.bilibili.com/video/BV1ov411A7az/?p=2
Unterminated string starting at: line 1 column 6517 (char 6516)
stop
Traceback (most recent call last):
File "utils", line 1103, in start
File "utils", line 1173, in start_
File "extractor\bili_downloader", line 89, in read
File "extractor\bili_downloader", line 175, in get_videos
File "extractor\bili_downloader", line 251, in get_pages
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 353, in raw_decode
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 6517 (char 6516)

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1ov411A7az?p=2 (1.3s)
===========================================

**Comment by STR-HK** [comment]
링크를
https://www.bilibili.com/video/BV1ov411A7az/?p=2 에서
https://www.bilibili.com/video/BV1ov411A7az 로 바꿔서 해보시겠어요?

저는 일단 그렇게 하니까 되네요

**Comment by abcs122** [comment]
오른쪽 목록을 보시면 영상이 2가지 있는데 첫번째 영상은 다운이 되는데 2번째 영상이 다운이 안되요ㅠㅠㅠㅠ
다른 영상들도 첫번째 영상은 가능한데 두번째,세번째,네번째 영상이 다운이 안되요...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
