### ISSUE TITLE
네이버 블로그 중복이름 다운 안되는 문제..

### ISSUE THREAD

**Issue by luou2044** [KurtBestor/Hitomi-Downloader#3788]
안녕하세요. 정말 좋은 프로그램 만들어 주셔서 감사합니다

다름이 아니라
네이버 블로그에서 이미지를 다운받고 싶은데,

다운받는 이미지 파일이 동일 파일 이름이면 , 다운이 안되는 문제가 있습니다.
ex) 1.jpg  , 1jpg  < 이런 파일은 두개 다 다운로드가 안되네요

동일 파일명이라도 1.jpg 1(1).jpg 이렇게 다운로드 가능하게 혹시 가능하신가요?
부탁드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by luou2044** [comment]
감사합니다 . 잘되네요. ㅠㅠ 
바쁘신 와중에도 고쳐주신거 너무 또 한번 감사드려요.

**Comment by kkecall** [comment]
네이버가 주기적으로 관리하는 건가??
베이버 블로그 다운로드가 다시 안 되어 여기에도 글 남겨봅니다.^^;

Invalid format: https://blog.naver.com/skp1659

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / e6a80868747849e0bccf1311d1b4154c
input: https://blog.naver.com/skp1659
type: naver
single: False
url: https://blog.naver.com/skp1659
dir:
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1735911925.381489 (25-01-03 13:45:25 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 2160
goodbyedpi: True
ytdl: yt_dlp 2024.12.13+
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Invalid format: https://blog.naver.com/skp1659
stop
Traceback (most recent call last):
File "utils", line 1387, in start
File "extractor\naver_downloader", line 34, in init
errors.Invalid: Invalid format: https://blog.naver.com/skp1659

Invalid: fail=False
EOT: https://blog.naver.com/skp1659 (0.0s)
