### ISSUE TITLE
픽시브 다운로드 받는 게시물 제목 오류+움짤 다운로드 오류

### ISSUE THREAD

**Issue by hehrjrvs** [KurtBestor/Hitomi-Downloader#3797]
이미지가 엑박이 아닌데도 다운로드가 안 되는 경우가 있어서 확인해보니
https://www.pixiv.net/artworks/65395286
https://www.pixiv.net/artworks/89028355
https://www.pixiv.net/artworks/25705002
https://www.pixiv.net/artworks/55815276
제목에 \ 가 들어가더라구요 
그리고 요근래에 생긴 문제인데 픽시브 움짤을 다운로드 받을 경우 압축파일로 이미지 한장한장 나눠진 상태로 받아지던데
이 두가지 문제 확인 부탁드립니다

**Comment by FenixRevival** [comment]
>그리고 요근래에 생긴 문제인데 픽시브 움짤을 다운로드 받을 경우 압축파일로 이미지 한장한장 나눠진 상태로 받아지던데

F5 클릭 > 픽시브 (Pixiv) > 우고이라  (Ugoira) > WEBP 또는 GIF 형식

**Comment by hehrjrvs** [comment]
설정을 확인해봤는데 gif입니다 애초에 설정을 건드리지도 않았고요
혹시나 싶어서 다운로더를 다시 받아서 기존 파일에 덮어씌워 봤는데 소용없네요

I checked the settings, but it's gif. I didn't touch it in the first place
Just in case, I downloaded Downloader again and overlaid it on the existing file, but this is useless

**Comment by ZorroGuevara** [comment]
Can you share a link? I'll try to download it.

링크를 공유할 수 있습니까? 다운로드 해 보겠습니다.

**Comment by hehrjrvs** [comment]
움짤이면 무조건 압축파일로 저장되는 것 같습니다
실험삼아 다운 받았던 움짤 링크들을 알려드리겠습니다

As long as it's a GIF, I think it's saved as a compressed file
I'll tell you the gifs that I downloaded individually as an experiment.

https://www.pixiv.net/artworks/92691507
https://www.pixiv.net/artworks/92690277
https://www.pixiv.net/artworks/92688540

**Comment by hehrjrvs** [comment]
壊れロボ娘 (pixiv_illust_92691507)

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: -659 / False / 8c78fe1eb1a54c398ed950f7d0f38990
input: https://www.pixiv.net/artworks/92691507
type: pixiv
single: False
url: https://www.pixiv.net/artworks/92691507
dir: hitomi_downloaded_pixiv\壊れロボ娘 (pixiv_illust_92691507)
zip: 
artist: None
valid / done: False / True
range / range_p: ~100000 / None
time: 1631464445.483474 (Sep 13)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {pixiv_tag_cache: {'tags': [], 'tags_ex': []}}
changed: True


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_pixiv\壊れロボ娘 (pixiv_illust_92691507)\92691507_p0 壊れロボ娘.zip


[URLs]
[0001] LazyUrl(https://www.pixiv.net/artworks/92691507) ---> https://i.pximg.net/img-zip-ugoira/img/2021/09/12/15/09/48/92691507_ugoira1920x1080.zip


[Messages]
tags: []
tags_ex: []
Convert: \\?\F:\pixiv-수정본\hitomi_downloaded_pixiv\壊れロボ娘 (pixiv_illust_92691507)\92691507_p0 壊れロボ娘.zip
【ffmpeg】 load...
【ffmpeg】 loaded
Convert: force...
Convert: \\?\F:\pixiv-수정본\hitomi_downloaded_pixiv\壊れロボ娘 (pixiv_illust_92691507)\92691507_p0 壊れロボ娘.zip
【ffmpeg】 load...
【ffmpeg】 loaded
Lazyurl pp Error: \\?\F:\pixiv-수정본\hitomi_downloaded_pixiv\壊れロボ娘 (pixiv_illust_92691507)\92691507_p0 壊れロボ娘.zip
Traceback (most recent call last):
File "ffmpeg", line 278, in gif
File "ffmpeg", line 388, in gif_
File "ffmpeg", line 107, in run
File "patch_subprocess", line 15, in __init__
File "subprocess", line 800, in __init__
File "subprocess", line 1207, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "hitomi_downloader", line 312, in run
File "extractor\pixiv_downloader", line 218, in pp
File "ffmpeg", line 281, in gif
File "ffmpeg", line 388, in gif_
File "ffmpeg", line 107, in run
File "patch_subprocess", line 15, in __init__
File "subprocess", line 800, in __init__
File "subprocess", line 1207, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

stop
EOT: https://www.pixiv.net/artworks/92691507 (3.7s)

게시물 하나만 받았을 때 작업정보입니다

**Comment by KurtBestor** [comment]
관리자 권한으로 실행해보세요

**Comment by hehrjrvs** [comment]
얼마전에 찾아보다가 알게된건데 admin 폴더를 실수로 지워버린 이후에 이렇게 됐습니다
다운로더 사용에 필요한 것들이 지워져서 이런게 아닌가 싶은데 
밑에 작업정보 보시고 어디가 문제인지 확인 부탁드립니다

**Comment by hehrjrvs** [comment]
윈도우즈 재설치 후 다운로더 재설치 하니까 움짤 문제는 해결되었습니다 특수문자 문제 좀 확인해주세요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hehrjrvs** [comment]
확인했습니다 정상 작동됩니다!
