### ISSUE TITLE
카카오tv 유료결제한 파일 안되요.

### ISSUE THREAD

**Issue by avajet** [KurtBestor/Hitomi-Downloader#3802]
결제 완료하고, 쿠키 추가, user agent  입력했습니다.
 from extractor import kakaopage_downloader;kakaopage_downloader.UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36' 

무료 파일은 잘 됩니다.
dpi  혹은 우회를 해도 안되는데 이유를 알 수 있을까요?

Invalid: [kakaotv] https://tv.kakao.com/channel/3804524/cliplink/422084650

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a576bd4b9d7f4c3486c319caaaca38c1
input: https://tv.kakao.com/channel/3804524/cliplink/422084650
type: kakaotv
single: True
url: https://tv.kakao.com/channel/3804524/cliplink/422084650
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1631545042.1301992 (Sep 13)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[Kakao] 422084650: Downloading video info
[Kakao] 422084650: Downloading video info
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 634, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 2288, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\kakao", line 84, in _real_extract
query=query, headers=player_header)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 899, in _download_json
expected_status=expected_status)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 877, in _download_json_handle
expected_status=expected_status)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 667, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 652, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\kakaotv_downloader", line 21, in read
File "utils", line 710, in __call__
File "<decorator-gen-86>", line 2, in get
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\kakaotv_downloader", line 45, in get
File "ytdl", line 336, in extract_info
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\Ryeol\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 306, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://tv.kakao.com/channel/3804524/cliplink/422084650 (1.2s)

**Comment by KurtBestor** [comment]
해당 계정 주시면 테스트해볼게요
