### ISSUE TITLE
레딧이 갑자기 안되는데 무슨일 있는 건가요?

### ISSUE THREAD

**Issue by harusika** [KurtBestor/Hitomi-Downloader#3811]
레딧이 최근까지는 되다가 오늘부터 안되는데 무슨일 있는 건가요?

**Comment by KurtBestor** [comment]
해당 작업 보여주세요

**Comment by KurtBestor** [comment]
해당 작업 내용 보여주세요

**Comment by harusika** [comment]
> 해당 작업 내용 보여주세요

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 16e8e9654e334a638baab6208768de71
input: https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
type: etc
single: True
url: https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1632873760.3237853 (Sep 29)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
extractor: reddit
get_video: True, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
get_video: True, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
get_video: True, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
get_video: True, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
get_video: False, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
get_video: False, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
get_video: False, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
get_video: False, https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3
[RedditR] poz0jb: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 634, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 2288, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\reddit", line 107, in _real_extract
url + '/.json', video_id)[0]['data']['children'][0]['data']
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 899, in _download_json
expected_status=expected_status)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 877, in _download_json_handle
expected_status=expected_status)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 667, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 652, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\etc_downloader", line 60, in get_video
File "<decorator-gen-91>", line 2, in _get_video
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\etc_downloader", line 80, in _get_video
File "ytdl", line 336, in extract_info
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 306, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\etc_downloader", line 27, in read
File "extractor\etc_downloader", line 68, in get_video
File "<decorator-gen-91>", line 2, in _get_video
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\etc_downloader", line 80, in _get_video
File "ytdl", line 336, in extract_info
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\TOP\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 306, in report_error
youtube_dl.utils.DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.reddit.com/r/cats/comments/poz0jb/what_does_he_think_of_his_leg/?utm_source=share&utm_medium=web2x&context=3 (1.4s)

**Comment by KurtBestor** [comment]
[youtube-dl](https://youtube-dl.org/) 문제는 [여기에서](https://yt-dl.org/bug) 제보해주세요
