### ISSUE TITLE
픽시브코믹, welovemanga가 다운이 안됩니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#3815]
항상 감사히 잘 쓰고 있습니다
이 두 군데가 다운이 안되네요
픽시브코믹은 며칠전부터 그랬구요
2곳의 정보 올려봅니다

43초 뒤 다시 시작: https://comic.pixiv.net/works/7769

version: 3.6 (21-08-18 01:55:42 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 2 / False / 15a0d9621c7948f1867e8d02421b20c7
input: https://comic.pixiv.net/works/7769
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/7769
dir: 
zip: 
artist: 芳川カズ
valid / done: False / True
range / range_p: None / None
time: 1631874056.3639123 (Sep 17)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
dirFormat: [artist] title
empty urls
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1181, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7769 (8.3s)

dirFormat: [artist] title
empty urls
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1181, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7769 (3.8s)

dirFormat: [artist] title
empty urls
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1181, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7769 (8.1s)

dirFormat: [artist] title
empty urls
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1181, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7769 (8.5s)

-welovemanga사이트 정보입니다

1분 45초 뒤 다시 시작: https://welovemanga.net/253/

version: 3.6 (21-08-18 01:55:42 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 0 / False / b8bdc3ed4f554ce2b3d3040e65e697dc
input: https://welovemanga.net/253/
type: lhscan
single: False
url: https://welovemanga.net/253/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [78]
time: 1631874125.939892 (Sep 17)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
no chapter-content
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1167, in start_
File "extractor\lhscan_downloader", line 83, in read
File "<decorator-gen-44>", line 2, in get_imgs
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 170, in get_imgs
File "<decorator-gen-42>", line 2, in get_imgs_page
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 101, in get_imgs_page
Exception: no chapter-content

Invalid: fail=True
EOT: https://welovemanga.net/253/ (19.5s)

Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
no chapter-content
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1167, in start_
File "extractor\lhscan_downloader", line 83, in read
File "<decorator-gen-44>", line 2, in get_imgs
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 170, in get_imgs
File "<decorator-gen-42>", line 2, in get_imgs_page
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 101, in get_imgs_page
Exception: no chapter-content

Invalid: fail=True
EOT: https://welovemanga.net/253/ (19.8s)

Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
no chapter-content
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1167, in start_
File "extractor\lhscan_downloader", line 83, in read
File "<decorator-gen-44>", line 2, in get_imgs
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 170, in get_imgs
File "<decorator-gen-42>", line 2, in get_imgs_page
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 101, in get_imgs_page
Exception: no chapter-content

Invalid: fail=True
EOT: https://welovemanga.net/253/ (21.6s)

Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
Chapter 80
no chapter-content
stop
Traceback (most recent call last):
File "utils", line 1097, in start
File "utils", line 1167, in start_
File "extractor\lhscan_downloader", line 83, in read
File "<decorator-gen-44>", line 2, in get_imgs
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 170, in get_imgs
File "<decorator-gen-42>", line 2, in get_imgs_page
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\lhscan_downloader", line 101, in get_imgs_page
Exception: no chapter-content

Invalid: fail=True
EOT: https://welovemanga.net/253/ (21.0s)

**Comment by wlskekrk** [comment]
welovemanga를 오늘 다시 다운받아보니 로딩할때 나타나는 gif들만 다운되네요 
다시 한번 정보 올려봅니다

KOE GA DASENAI SHOUJO WA

version: 3.6 (21-08-18 01:55:42 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 0 / False / 2f09e5e6b06d46319d58ac318d0c01c9
input: https://welovemanga.net/253/
type: lhscan
single: False
url: https://welovemanga.net/253/
dir: hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA
zip: 
artist: None
valid / done: True / True
range / range_p: None / [78]
time: 1632308856.2229125 (Sep 22)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0000.gif
[0002] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0001.gif
[0003] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0002.gif
[0004] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0003.gif
[0005] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0004.gif
[0006] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0005.gif
[0007] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0006.gif
[0008] hitomi_downloaded_lhscan\KOE GA DASENAI SHOUJO WA\Chapter 80\0007.gif


[URLs]
[0001] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0002] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0003] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0004] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0005] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0006] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0007] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif
[0008] LazyUrl(https://welovemanga.net/253/63663/) ---> https://welovemanga.net/uploads/lazy_loading.gif


[Messages]
Chapter 80
/uploads/lazy_loading.gif
stop
EOT: https://welovemanga.net/253/ (7.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
오 두곳다 잘되는군요 정말 감사드립니다

**Comment by seica2031** [comment]
https://weloma.net/ 
이 주소로 바뀐건지 다시 안되는거 같습니다.

**Comment by KurtBestor** [comment]
@seica2031 주소만 비슷한 유사 사이트예요

**Comment by seica2031** [comment]
아 그러네요. 감사합니다.
다만 해당 사이트에서도 되는 게 있고 계속 안되는게 있는데 괜찮으시다면 확인 한번 부탁드립니다,

목록 주소를 입력해주세요: https://welovemanga.net/475/

version: 3.6 (21-10-03 16:09:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 77e9294640be4e76bc59a28e4a5fccb1
input: https://welovemanga.net/475/
type: lhscan
single: False
url: https://welovemanga.net/475/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1633443067.1631918 (5 Oct)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
no html
목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (12.2s)

목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (17.6s)

no html
목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (20.2s)

no html
목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (9.0s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3324#issuecomment-939504904
