### ISSUE TITLE
네이버 블로그 접힌글로 열리는 페이지의 이미지들이 다운되지 않고 넘어갑니다.

### ISSUE THREAD

**Issue by hskim890** [KurtBestor/Hitomi-Downloader#3817]
https://blog.naver.com/tltmxvpm01/220412386300

옛날에 봤던 만화가 그리워져서 원본소장하려고 다운로드를 했는데,

네이버블로그에서 원본이 다운로드 되지만 접힌글을 펼쳐야 보이는 이미지들은 다운로드가 안 되더라구요.

분명히 다운로드 때는 접힌글을 포함해서 전체 이미지 개수가 뜨지만 실제 다운로드 되는 것은 접힌글을 펼치기 전에

보이는 이미지들만이 다운로드 되어 있습니다.

히토미 다운로더 덕분에 정말 여러모로 도움을 받고 있습니다. 언제나 고맙습니다. 읽어주셔서 감사드립니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3788

**Comment by kkecall** [comment]
네이버가 주기적으로 관리하는 건가??
베이버 블로그 다운로드가 다시 안 되어 글 남겨봅니다.

Invalid format: https://blog.naver.com/skp1659

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / e6a80868747849e0bccf1311d1b4154c
input: https://blog.naver.com/skp1659
type: naver
single: False
url: https://blog.naver.com/skp1659
dir:
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1735911925.381489 (25-01-03 13:45:25 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 2160
goodbyedpi: True
ytdl: yt_dlp 2024.12.13+
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Invalid format: https://blog.naver.com/skp1659
stop
Traceback (most recent call last):
File "utils", line 1387, in start
File "extractor\naver_downloader", line 34, in init
errors.Invalid: Invalid format: https://blog.naver.com/skp1659

Invalid: fail=False
EOT: https://blog.naver.com/skp1659 (0.0s)
