### ISSUE TITLE
인스타가 막힌 것 같습니다.

### ISSUE THREAD

**Issue by wkdgur542** [KurtBestor/Hitomi-Downloader#3819]
혹시 해당 사진만 그런가 싶어 다른 계정의 사진들 몇 개를 더 시도하였는데도
같은 결과가 나왔습니다.

**Comment by wkdgur542** [comment]
Invalid: [insta] https://www.instagram.com/p/CT7rsogB2d_

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 9dc64714084b411b9094649a7adbc77c
input: https://www.instagram.com/p/CT7rsogB2d_
type: insta
single: False
url: https://www.instagram.com/p/CT7rsogB2d_
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1632072207.592676 (Sep 20)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
single post
no _sharedData
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\insta_downloader", line 75, in read
File "extractor\insta_downloader", line 71, in id_
File "utils", line 506, in __get__
File "extractor\insta_downloader", line 67, in name
File "extractor\insta_downloader", line 211, in get_name
File "extractor\insta_downloader", line 157, in get_sd
Exception: no _sharedData

Invalid: fail=True
EOT: https://www.instagram.com/p/CT7rsogB2d_ (31.3s)

**Comment by KurtBestor** [comment]
이미 삭제된 포스트네요
