### ISSUE TITLE
검색기 데이터 다운로드

### ISSUE THREAD

**Issue by zxcwas** [KurtBestor/Hitomi-Downloader#3821]
히토미 다운로더 검색기에서 기본 데이터 다운로드랑 삭제된 데이터 다운로드 하려면 안되고 '예상치 못한 오류로 다운로드에 실패했습니다.' 라고 뜨고 다운로드가 안됩니다. 해결방법이 있을까요?

**Comment by Elements8** [comment]
히토미 다운로더 이외의 goodbye dpi나 vpn켜신거 있으면 끄고 다운로드 해보세요. 저는 이렇게 하니까 해결됐어요.

**Comment by KurtBestor** [comment]
`자세한 정보 보기` 눌러서 나온 내용 보여주세요

**Comment by qweqr23456345** [comment]
다운로드 눌러도 0%에서 진행이 안됩니다

**Comment by zxcwas** [comment]
> `자세한 정보 보기` 눌러서 나온 내용 보여주세요

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2941, in dataDownload_forbidden
  File "hitomi_searcher", line 183, in download_json
  File "hitomi_searcher", line 149, in download_json_forbidden
  File "tags", line 67, in finish
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\USER\\Desktop\\H\\hitomi_downloader_GUI\\hitomi_data\\tags_forbidden.txt'
