### ISSUE TITLE
유튜브 성인인증 영상은 성인인증 해야 다운 되나요?

### ISSUE THREAD

**Issue by rufeineqofjpjih** [KurtBestor/Hitomi-Downloader#3822]
Invalid: [youtube] https://www.youtube.com/watch?v=Glao1u1lUSM

version: 3.6 (21-09-16 17:50:36 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / aa6a9a4739f34efba1eb5508c494af96
input: https://www.youtube.com/watch?v=Glao1u1lUSM
type: youtube
single: True
url: https://www.youtube.com/watch?v=Glao1u1lUSM
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1632192197.38532 (21 Sep)
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

[youtube] Glao1u1lUSM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 362, in read
File "utils", line 744, in __call__
File "extractor\youtube_downloader", line 72, in get
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.
stop
Traceback (most recent call last):
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\extractor\youtube", line 1713, in _real_extract
raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1132, in start
File "utils", line 1202, in start_
File "extractor\youtube_downloader", line 369, in read
File "extractor\youtube_downloader", line 362, in read
File "utils", line 744, in __call__
File "extractor\youtube_downloader", line 72, in get
File "extractor\youtube_downloader", line 64, in get
File "ytdl", line 475, in __init__
File "ytdl", line 341, in extract_info
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\강세훈\AppData\Local\Temp\ytdl_b43d6420\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 311, in report_error
youtube_dl.utils.DownloadError: ERROR: 본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.

Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1601, in finish
IndexError: list index out of range

EOT: https://www.youtube.com/watch?v=Glao1u1lUSM (23.3s)

**Comment by AngleGN** [comment]
[자주 묻는 질문](https://github.com/KurtBestor/Hitomi-Downloader/issues/2843)
로그인이 필요한 페이지 다운로드란을 참고하세요
