### ISSUE TITLE
sankaku channel not working

### ISSUE THREAD

**Issue by unduesnow** [KurtBestor/Hitomi-Downloader#3843]
https://chan.sankakucomplex.com/ doesnt wrok, it keeps restarting, shows invalid, after a long time it occasinally works but doesnt download all the pics

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by unduesnow** [comment]
Restart in 2m 34s: https://chan.sankakucomplex.com/

version: 3.7b (21-10-29 03:12:23 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 0 / False / f3011ab755c647c49adaccac6a6ec458
input: https://chan.sankakucomplex.com/
type: sankaku
single: False
url: https://chan.sankakucomplex.com/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636186800.006264 (6 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/
Traceback (most recent call last):
File "downloader", line 369, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connection", line 160, in _new_conn
File "urllib3\util\connection", line 61, in create_connection
File "socket", line 752, in getaddrinfo
File "<decorator-gen-1>", line 2, in getaddrinfo
File "locker", line 128, in _wrapper
File "locker", line 63, in exec_
File "locker", line 39, in run
File "locker", line 128, in <lambda>
File "downloader", line 84, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 309, in connect
File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000027BBFA82088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chan.sankakucomplex.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BBFA82088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\sankaku_downloader", line 278, in get_imgs
File "downloader", line 409, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 182, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chan.sankakucomplex.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BBFA82088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

no images
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\sankaku_downloader", line 109, in read
File "extractor\sankaku_downloader", line 347, in get_imgs
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ (3.3s)

**Comment by unduesnow** [comment]
i tried updating cookies too 
nothing seemed to work

**Comment by KurtBestor** [comment]
Check your firewall settings

**Comment by unduesnow** [comment]
no luck, i turned it off and its still the same
