### ISSUE TITLE
픽시브 코믹스 에러관련 문의

### ISSUE THREAD

**Issue by wheatflor22** [KurtBestor/Hitomi-Downloader#3845]
Invalid: [pixiv_comic] https://comic.pixiv.net/works/5775

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 28ead3bda4324b748bbc8d6ab54de1c8
input: https://comic.pixiv.net/works/5775
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/5775
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~50000 / None
time: 1633023969.6351337 (Oct 1)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/5775 (8.3s)

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Invalid: [pixiv_comic] https://comic.pixiv.net/works/7587

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 2 / False / 066e9a78e2014d37b40ed8754b949600
input: https://comic.pixiv.net/works/7587
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/7587
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~50000 / None
time: 1633023893.4174092 (Oct 1)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pixiv_comic_downloader", line 67, in read
File "extractor\pixiv_comic_downloader", line 53, in name
File "extractor\pixiv_comic_downloader", line 95, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7587 (7.8s)

작업정보입니다.

로그인하고 쿠키등록도 해봤는데 별 효과가 없네요.
픽시브는 잘 다운됩니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3815#issuecomment-929287505
