### ISSUE TITLE
welovemanga 다운 오류 입니다.

### ISSUE THREAD

**Issue by seica2031** [KurtBestor/Hitomi-Downloader#3877]
되는거 있고 안되는 거 있는거 같은데 아마 로그인해야 보이는가 아닌가의 차이 같습니다.
한번 확인해주시면 감사하겠습니다.

읽는 중... https://welovemanga.net/475/

version: 3.6 (21-10-03 16:09:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 5 / False / 77e9294640be4e76bc59a28e4a5fccb1
input: https://welovemanga.net/475/
type: lhscan
single: False
url: https://welovemanga.net/475/
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1633759910.5757625 (9 Oct)
tags: []
lock: False
color: reading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
no html
목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (12.2s)

목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False

EOT: https://welovemanga.net/475/ (17.6s)

no html
목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (20.2s)

no html
목록 주소를 입력해주세요: https://welovemanga.net/475/
stop
Traceback (most recent call last):
File "utils", line 1121, in start
File "extractor\lhscan_downloader", line 60, in init
errors.Invalid: 목록 주소를 입력해주세요: https://welovemanga.net/475/

Invalid: fail=False
EOT: https://welovemanga.net/475/ (9.0s)

no html

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3324#issuecomment-939504904

**Comment by KurtBestor** [comment]
네 베타 버전이라서 아직 지원하긴 이른 것 같아서 안 하려구요
