### ISSUE TITLE
폰허브 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by HMMMMMHMMMM** [KurtBestor/Hitomi-Downloader#3892]
업데이트 이후부터 안되는거같은데 확인 가능한가요..?

**Comment by zerox022** [comment]
저도 그렇네요 메세지는 아래와 같이 나오네요

Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph60c39c88824b2

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / f6d482911c284ef4881f7fcbfab4186f
input: https://www.pornhub.com/view_video.php?viewkey=ph60c39c88824b2
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph60c39c88824b2
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1634384364.299941 (Oct 16)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: False
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
id: ph60c39c88824b2
Video
[PornHub] ph60c39c88824b2: Downloading pc webpage
[PornHub] ph60c39c88824b2: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 815, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 836, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 534, in extract
ie_result = self._real_extract(url)
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\pornhub", line 443, in _real_extract
self._sort_formats(formats)
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\extractor\common", line 1374, in _sort_formats
raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1096, in start
File "utils", line 1166, in start_
File "extractor\pornhub_downloader", line 265, in read
File "utils", line 710, in __call__
File "extractor\pornhub_downloader", line 126, in get
File "ytdl", line 336, in extract_info
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 808, in extract_info
return self.__extract_info(url, ie, download, extra_info, process)
File "C:\Users\Acer\AppData\Local\Temp\youtube_dl_module\youtube_dl\YoutubeDL", line 824, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 306, in report_error
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph60c39c88824b2 (6.1s)

**Comment by KurtBestor** [comment]
이전 버전 쓰고싶으면 쓰세요: https://github.com/KurtBestor/Hitomi-Downloader/releases
