### ISSUE TITLE
3.7 업데이트 이후 트위터 영상 다운로드가 안됩니다

### ISSUE THREAD

**Issue by saco88** [KurtBestor/Hitomi-Downloader#3970]
3.6 버전에서는 잘 다운이 됐었는데
3.7 a,b 모두 트위터 영상이 다운이 안됩니다.
히토미 프로그램을 삭제했다가 다시 설치하고 싶어도
제어판에 목록이 안떠서 삭제하는 방법도 모르고 답답하네요
작업정보는 아래와 같습니다.
감사합니다

version: 3.7b (21-10-29 03:12:23 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / d6d7389274ed48739a63df82f88e1bf3
input: https://twitter.com/i/status/1426404384531959809
type: twitter
single: False
url: https://twitter.com/i/status/1426404384531959809
dir: D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)
zip: 
artist: 50°先生
valid / done: False / True
range / range_p: None / None
time: 1635612033.5275748 (31 Oct)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)\[21-08-14] 1426404384531959809_p0.mp4

[URLs]
[0001] LazyUrl_twitter(https://twitter.com/i/status/1426404384531959809) ---> M3u8_stream(https://video.twimg.com/ext_tw_video/1426402581404798978/pu/pl/720x1280/VQsgaWNd4IAUXrQC.m3u8?container=fmp4)

[Messages]
single tweet
[twitter] 1426404384531959809: Downloading JSON metadata
[twitter] 1426404384531959809: Downloading m3u8 information
get_video: https://video.twimg.com/ext_tw_video/1426402581404798978/pu/pl/720x1280/VQsgaWNd4IAUXrQC.m3u8?container=fmp4 .m3u8
Convert: D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)\[21-08-14] 1426404384531959809_p0.mp4
rename (1): D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)\[21-08-14] 1426404384531959809_p0.mp4 -> D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)\tmp20f6dc1bb3574138a73b19879be599ab_i.mp4
-i tmp20f6dc1bb3574138a73b19879be599ab_i.mp4 -acodec copy -vcodec copy -threads 0 tmp20f6dc1bb3574138a73b19879be599ab_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 044a46c0] could not find corresponding trex
[mov,mp4,m4a,3gp,3g2,mj2 @ 044a46c0] error reading header
tmp20f6dc1bb3574138a73b19879be599ab_i.mp4: Invalid data found when processing input
[code]
1
rename (1): D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)\tmp20f6dc1bb3574138a73b19879be599ab_i.mp4 -> D:\동영상_다운\히토미 다운_twitter\50°先生 (@lonefir2)\[21-08-14] 1426404384531959809_p0.mp4

Fail m3u8 pp : [21-08-14] 1426404384531959809_p0.mp4
Traceback (most recent call last):
File "downloader", line 796, in download
File "m3u8_tools", line 218, in _pp
File "ffmpeg", line 304, in convert
File "ffmpeg", line 294, in convert
Exception: Failed to convert; exit code: 1

stop
valid=False 1
EOT: https://twitter.com/i/status/1426404384531959809 (30.1s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by saco88** [comment]
정말 감사합니다. 이제 되네요 ^^
