### ISSUE TITLE
안녕하세요 spankbang 다운이 안됩니다

### ISSUE THREAD

**Issue by leneblanc** [KurtBestor/Hitomi-Downloader#3979]
그제까진 잘 됬는데 갑자기 안되네요;; 빨간색 invalid가 뜹니다

Invalid: [etc] https://spankbang.com/5q3ey/video/yuuna+himekawa

version: 3.7b (21-10-29 03:12:23 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / bad65ef5cd0a41acad45ccae55779e09
input: https://spankbang.com/5q3ey/video/yuuna+himekawa
type: etc
single: True
url: https://spankbang.com/5q3ey/video/yuuna+himekawa
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1635865940.8726301 (3 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
extractor: spankbang
get_video: True, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
get_video: True, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
get_video: True, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
get_video: True, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
ERROR: [SpankBang] 5q3ey: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
get_video: False, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
get_video: False, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
get_video: False, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
get_video: False, https://spankbang.com/5q3ey/video/yuuna+himekawa
[SpankBang] 5q3ey: Downloading webpage
ERROR: [SpankBang] 5q3ey: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\common", line 702, in _request_webpage
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 3252, in urlopen
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\common", line 593, in extract
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\spankbang", line 78, in _real_extract
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\common", line 870, in _download_webpage
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\common", line 735, in _download_webpage_handle
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\common", line 720, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 1280, in wrapper
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 1305, in __extract_info
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\extractor\common", line 610, in extract
yt_dlp.utils.ExtractorError: [SpankBang] 5q3ey: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\etc_downloader", line 60, in get_video
File "<decorator-gen-93>", line 2, in _get_video
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\etc_downloader", line 80, in _get_video
File "ytdl", line 385, in extract_info
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 1272, in extract_info
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 1289, in wrapper
File "ytdl", line 355, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 5q3ey: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\etc_downloader", line 27, in read
File "extractor\etc_downloader", line 68, in get_video
File "<decorator-gen-93>", line 2, in _get_video
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\etc_downloader", line 80, in _get_video
File "ytdl", line 385, in extract_info
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 1272, in extract_info
File "C:\Users\hunhu\AppData\Local\Temp\_MEI95042\ytdl_30908006\yt_dlp\yt_dlp\YoutubeDL", line 1289, in wrapper
File "ytdl", line 355, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 5q3ey: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://spankbang.com/5q3ey/video/yuuna+himekawa (2.6s)

이렇게 뜹니다 
검색했을때 파이썬 버전을 3.9이상으로 하니 된다는 글 보고 업데이트 했는데 안되네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/yt-dlp/yt-dlp/issues/1524
