### ISSUE TITLE
픽시브코믹이 문제가 있는데 좀 신기합니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#3983]
항상 감사히 잘 사용하고 있습니다

어제부턴가 픽시브코믹이 다운이 안되더라구요
그래서 #3982 여기서 새로운 버전을 다운받아서 함 해봤습니다
그런데 신기한게 시험삼아 드라이브 E에 다운받아 바로 압축풀고 실행했을때는 다운이 잘 되더라구요
그래서 아 이걸로 하면 되겠구나 싶어서 드라이브 D에 원래 있던 폴더에 
hitomi_downloader_GUI.exe 파일을 옮겨서 똑같은 파일을 다시 다운받았습니다
그러니까 다운이 안됩니다 몇번이나 해도 E에선 다운되는데 D에선 안되네요
안되는건 아니니까 상관없긴한데 이상해서 문의해봅니다
일단 안되는 작업정보 올려볼게요

1분 48초 뒤 다시 시작: https://comic.pixiv.net/works/7894

version: 3.7b (21-11-04 08:37:27 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 1 / False / b971cfd047724b25b2599e763414e699
input: https://comic.pixiv.net/works/7894
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/7894
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636030701.9358244 (4 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
dirFormat: [artist] title
no pages
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\pixiv_comic_downloader", line 66, in read
File "extractor\pixiv_comic_downloader", line 151, in get_imgs
File "extractor\pixiv_comic_downloader", line 129, in get_pages
Exception: no pages

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7894 (5.2s)

no html
dirFormat: [artist] title
no pages
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\pixiv_comic_downloader", line 66, in read
File "extractor\pixiv_comic_downloader", line 151, in get_imgs
File "extractor\pixiv_comic_downloader", line 129, in get_pages
Exception: no pages

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7894 (6.2s)

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 눌러서 해당 페이지 들어가면 어떻게 뜨나요?

**Comment by wlskekrk** [comment]
E에서는 해당페이지로 문제없이 들어가지는데
D에서는

This page isn’t workingcomic.pixiv.net redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

이렇게 뜨네요

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 설정 - 쿠기 - 초기화` 누르고 다시 시도해보세요

**Comment by wlskekrk** [comment]
오오 잘 되는군요 정말 감사합니다
