### ISSUE TITLE
니코동 구독자 전용영상 다운로드 불가능

### ISSUE THREAD

**Issue by Kapustin4202** [KurtBestor/Hitomi-Downloader#3986]
live방송 다시보기 구독자 영상을 다운로드 불가능한 현상이 있습니다.
https://live.nicovideo.jp/watch/~~~

로  URL받기하면
자동으로 
nicovideo.jp/watch/~~~로 바뀌어서 다운해서 받기가 불가능하네요

도구-설정해서 로그인해도 같은현상이 일어납니다

작업수정을 눌러서 URL재 설정후에 다시시작을 눌러도 강제로 URL이 nicovideo로 바뀌면서 다운불가능함..

===========================================================================

Invalid: [nico] https://www.nicovideo.jp/watch/lv334228146

version: 3.7b (21-10-29 03:12:23 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / d99ba193b13d419c841def1866006a44
input: https://www.nicovideo.jp/watch/lv334228146
type: nico
single: True
url: https://www.nicovideo.jp/watch/lv334228146
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636096551.8488433 (5 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Err
stop
Traceback (most recent call last):
File "extractor\nico_downloader", line 116, in get_video
File "nndownload", line 369, in request_video
File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.nicovideo.jp/watch/lv334228146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\nico_downloader", line 98, in read
File "<decorator-gen-38>", line 2, in get_video
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\nico_downloader", line 118, in get_video
Exception: Err

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/lv334228146 (2.4s)

Err
stop
Traceback (most recent call last):
File "extractor\nico_downloader", line 116, in get_video
File "nndownload", line 369, in request_video
File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.nicovideo.jp/watch/lv334228146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\nico_downloader", line 98, in read
File "<decorator-gen-38>", line 2, in get_video
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\nico_downloader", line 118, in get_video
Exception: Err

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/lv334228146 (3.0s)

Err
stop
Traceback (most recent call last):
File "extractor\nico_downloader", line 116, in get_video
File "nndownload", line 369, in request_video
File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.nicovideo.jp/watch/lv334228146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\nico_downloader", line 98, in read
File "<decorator-gen-38>", line 2, in get_video
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\nico_downloader", line 118, in get_video
Exception: Err

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/lv334228146 (3.0s)

**Comment by KurtBestor** [comment]
아직 니코니코는 니코니코동화만 지원해요
