### ISSUE TITLE
마나토끼 다운이 안됩니다 ㅠㅠ

### ISSUE THREAD

**Issue by YUies** [KurtBestor/Hitomi-Downloader#3988]
URL 주소창에 현재 마나토끼 주소를 입력해서 선택 화 다운로드를 누르면 목록주소를 입력해주세요 라는 메세지가 뜨면서 다운로드가 되지않습니다.
버전은 3.7b입니다

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by melong1001** [comment]
> 해당 작업 정보 보여주세요

글쓴분은 아니지만 같은 현상 겪고 있기에 정보 로그 제출합니다

Invalid: [manatoki] https://manatoki111.net/comic/119986

version: 3.7c (21-11-06 14:51:54 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 7d107a7a53584781a0502cfad3efa8d8
input: https://manatoki111.net/comic/119986
type: manatoki
single: False
url: https://manatoki111.net/comic/119986
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636289750.1317685 (7 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "<decorator-gen-89>", line 2, in init
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\manatoki_downloader", line 36, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 141, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki111.net/comic/119986 (199.7s)

**Comment by KurtBestor** [comment]
@melong1001  다른 현상이고 DPI 우회 켜주세요

**Comment by melong1001** [comment]
> @melong1001 다른 현상이고 DPI 우회 켜주세요

아.. 다른 현상이군요.

상황을 너무 간단하게 적었는데

일단 DPI 우회는 윈도우 10에서 GoodbyeDPI 별도 실행해서 해결하고 있었습니다 

혹시 몰라서 GoodbyeDPI 종료하고 다운로더 자체 DPI 우회키능 ON 해서 시도해봤는데
여전히 다운로드 되지 않습니다.

정보 로그 제출합니다

Invalid: [manatoki] https://manatoki111.net/comic/119986

version: 3.7c (21-11-06 14:51:54 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 84a7304f0713458e8fea91d5e58264cf
input: https://manatoki111.net/comic/119986
type: manatoki
single: False
url: https://manatoki111.net/comic/119986
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636290538.778134 (7 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "<decorator-gen-89>", line 2, in init
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\manatoki_downloader", line 36, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 141, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki111.net/comic/119986 (199.8s)

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 눌러서 해당 웹페이지 들어가서 어떻게 보이는지 보여주세요

**Comment by melong1001** [comment]
> `옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 눌러서 해당 웹페이지 들어가서 어떻게 보이는지 보여주세요

음. 일단 해당 페이지 아무것도 안나오고
혹시나 해서 포털 사이트 접속해봐도 아무것도 표시가 안됩니다

[https://ibb.co/brbZMZs](url)

(이미지 삭제 기한은 1일 후)

**Comment by KurtBestor** [comment]
[v3.6](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.6) 은 어떤가요?

**Comment by melong1001** [comment]
> [v3.6](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.6) 은 어떤가요?

3.6 동일합니다

로그 및 스크린샷 제출합니다

Invalid: [manatoki] https://manatoki111.net/comic/119986

version: 3.6 (21-08-12 05:47:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 4f8f7f3885034179a5148f89eae1d00a
input: https://manatoki111.net/comic/119986
type: manatoki
single: False
url: https://manatoki111.net/comic/119986
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636292448.2105799 (Nov 7)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 1082, in start
File "<decorator-gen-89>", line 2, in init
File "constants", line 896, in wrapper
File "constants", line 867, in wrapper
File "extractor\manatoki_downloader", line 36, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 64, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki111.net/comic/119986 (200.7s)

------------------

https://ibb.co/cgtHm9g

참고가 되실지 모르겠는데. 제이마나는 정상적으로 다운로드 가능합니다
