### ISSUE TITLE
pawoo 다운로드에 문제가 있는 거 같습니다.

### ISSUE THREAD

**Issue by cocokakao** [KurtBestor/Hitomi-Downloader#3989]
최신버젼과 이전버젼 모두 시도해 봤는데 트래픽관련 문제인거 같습니다. 여러 항목을 다운하면 진행되었다가 안되었다 하는데 읽어야할 이미지가 많을 수록 제한이 걸리게 된거 같습니다. 

고급설정에 페이지 지정 다운로드를 이용해 봐도 전체 페이지를 읽어들여서 중단되는데 제가 설정을 잘못한건지 pawoo는 해당 기능 사용에 문제가 있는건지 잘 모르겠습니다.

읽어주셔서 감사합니다.

Invalid: [pawoo] https://pawoo.net/@alapy334

version: 3.7b (21-10-29 03:12:23 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 388 / False / ff36d7249976496692fb521d023e9ce0
input: https://pawoo.net/@alapy334
type: pawoo
single: False
url: https://pawoo.net/@alapy334
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~200000 / None
time: 1636110795.7105596 (5 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
HTTPSConnectionPool(host='pawoo.net', port=443): Max retries exceeded with url: /@alapy334/media?max_id=106706738616600346 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
stop
Traceback (most recent call last):
File "downloader", line 387, in read_html
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib3\connectionpool", line 677, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in _validate_conn
File "urllib3\connection", line 371, in connect
File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
File "ssl", line 423, in wrap_socket
File "ssl", line 870, in _create
File "ssl", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 449, in send
File "urllib3\connectionpool", line 727, in urlopen
File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pawoo.net', port=443): Max retries exceeded with url: /@alapy334/media?max_id=106706738616600346 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\pawoo_downloader", line 37, in read
File "mastodon", line 31, in get_imgs
File "downloader", line 414, in read_html
File "requests\sessions", line 555, in get
File "downloader", line 182, in session_request
File "requests\sessions", line 542, in request
File "requests\sessions", line 655, in send
File "requests\adapters", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='pawoo.net', port=443): Max retries exceeded with url: /@alapy334/media?max_id=106706738616600346 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))

Invalid: fail=True
EOT: https://pawoo.net/@alapy334 (3.6s)

**Comment by cocokakao** [comment]
이번 업데이트 이후 작동 확인되었습니다.
