### ISSUE TITLE
sankaku가 되지 않습니다.

### ISSUE THREAD

**Issue by pink0258** [KurtBestor/Hitomi-Downloader#3990]
쿠키를 불러와 봤는데도 마찬가지 증상이네요

2분 29초 뒤 다시 시작: https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae

version: 3.7c (21-11-05 11:01:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 8720dd8ed37741408585d5ba20d9161d
input: https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae
type: sankaku
single: True
url: https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae
dir: hitomi_downloaded_sankaku
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636114646.7852614 (5 Nov)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_sankaku

[URLs]
[0001] LazyUrl_sankaku(https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae)

[Messages]
types: img, gif, video
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable

LazyUrl error (https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae):
Traceback (most recent call last):
File "hitomi_downloader", line 236, in run
File "utils", line 753, in __call__
File "extractor\sankaku_downloader", line 202, in get
Exception: can not find image (id:None)
Traceback (most recent call last):
File "extractor\sankaku_downloader", line 186, in get
TypeError: 'NoneType' object is not subscriptable

stop
valid=False 1
-show_streams -print_format json -v error "hitomi_downloaded_sankaku"
【ffprobe】 load...
【ffprobe】 loaded
{

}
hitomi_downloaded_sankaku: Permission denied
Traceback (most recent call last):
File "utils", line 1612, in finish
File "ffmpeg", line 661, in get_info
File "ffmpeg", line 658, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae (29.2s)

types: img, gif, video
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable
[Sankaku] failed to read image (id:None): 'NoneType' object is not subscriptable

LazyUrl error (https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae):
Traceback (most recent call last):
File "hitomi_downloader", line 236, in run
File "utils", line 753, in __call__
File "extractor\sankaku_downloader", line 202, in get
Exception: can not find image (id:None)
Traceback (most recent call last):
File "extractor\sankaku_downloader", line 186, in get
TypeError: 'NoneType' object is not subscriptable

stop
valid=False 1
-show_streams -print_format json -v error "hitomi_downloaded_sankaku"
【ffprobe】 load...
【ffprobe】 loaded
{

}
hitomi_downloaded_sankaku: Permission denied
Traceback (most recent call last):
File "utils", line 1612, in finish
File "ffmpeg", line 661, in get_info
File "ffmpeg", line 658, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://chan.sankakucomplex.com/post/index?tags=blue_bone_studio+-rating%3As+rating%3Ae (29.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by pink0258** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

작동 잘 됩니다! 감사합니다!
