### ISSUE TITLE
welovemanga 다운로드할 수 없게 됨

### ISSUE THREAD

**Issue by mamanngaga01** [KurtBestor/Hitomi-Downloader#3992]
When you download the capture

Feiled to read pages: AttributeError. 'None Type' object has no attribute 'findAll'

**Comment by charlificate** [comment]
이전이랑은 오류 메시지가 달라졌어요.
그래도 10챕터는 읽히던게 아예 안읽히게 되었네요

Please type a list URL: https://welovemanga.net/599/

version: 3.7b (21-10-29 03:12:23 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en
order / group / uid: 0 / False / 881d4133591d4e0fa43cb5b75169dfa4
input: https://welovemanga.net/599/
type: lhscan
single: False
url: https://welovemanga.net/599/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636237273.5166638 (7 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
https://welovemanga.net/599/ -> https://welovemanga.net/599/
Please type a list URL: https://welovemanga.net/599/
stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "extractor\lhscan_downloader", line 63, in init
errors.Invalid: Please type a list URL: https://welovemanga.net/599/

Invalid: fail=False
EOT: https://welovemanga.net/599/ (2.4s)

no html
https://welovemanga.net/599/ -> https://welovemanga.net/599/
Please type a list URL: https://welovemanga.net/599/
stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "extractor\lhscan_downloader", line 63, in init
errors.Invalid: Please type a list URL: https://welovemanga.net/599/

Invalid: fail=False
EOT: https://welovemanga.net/599/ (4.5s)

no html
https://welovemanga.net/599/ -> https://welovemanga.net/599/
Please type a list URL: https://welovemanga.net/599/
stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "extractor\lhscan_downloader", line 63, in init
errors.Invalid: Please type a list URL: https://welovemanga.net/599/

Invalid: fail=False
EOT: https://welovemanga.net/599/ (6.4s)
