### ISSUE TITLE
유튜브가 invalid 상태로 다운이 받아지지 않습니다.

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#4003]
Invalid: [youtube] https://www.youtube.com/channel/UCgipy6-EqjT-1BCDndXX1PA

version: 3.7c (21-11-05 11:01:05 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / a280e12e2ab644c4be2dc950bebc8c9d
input: https://www.youtube.com/channel/UCgipy6-EqjT-1BCDndXX1PA
type: youtube
single: True
url: https://www.youtube.com/channel/UCgipy6-EqjT-1BCDndXX1PA
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~200000 / None
time: 1636381594.5668933 (8 Nov)
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA: Downloading webpage
[download] Downloading playlist: back number - Videos
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #1)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #2)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #3)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA: Downloading webpage
[download] Downloading playlist: back number - Videos
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #1)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #2)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #3)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA: Downloading webpage
[download] Downloading playlist: back number - Videos
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #1)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #2)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #3)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA: Downloading webpage
[download] Downloading playlist: back number - Videos
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #1)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #2)
[youtube:tab] UCgipy6-EqjT-1BCDndXX1PA page 1: Downloading API JSON (retry #3)
ERROR: Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
stop
Traceback (most recent call last):
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\common", line 702, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 3252, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "urllib\request", line 531, in open
File "urllib\request", line 641, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 503, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1280, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1516, in <lambda>
lambda self, i: ie_entries[i - 1]
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\utils", line 4086, in __getitem__
self.__cache.extend(itertools.islice(self.__iterable, n))
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\youtube", line 4111, in _smuggle_data
for entry in entries:
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\youtube", line 3743, in _entries
check_get_keys=('continuationContents', 'onResponseReceivedActions', 'onResponseReceivedEndpoints'))
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\youtube", line 617, in _extract_response
note='%s%s' % (note, ' (retry #%d)' % count if count else ''))
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\youtube", line 384, in _call_api
query={'key': api_key or self._extract_api_key()})
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\common", line 968, in _download_json
expected_status=expected_status)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\common", line 946, in _download_json_handle
expected_status=expected_status)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\common", line 735, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\extractor\common", line 720, in _request_webpage
raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
yt_dlp.utils.ExtractorError: Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\youtube_downloader", line 347, in read
File "<decorator-gen-31>", line 2, in get_videos
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\youtube_downloader", line 397, in get_videos
File "extractor\youtube_downloader", line 419, in read_channel
File "<decorator-gen-32>", line 2, in read_playlist
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\youtube_downloader", line 435, in read_playlist
File "ytdl", line 385, in extract_info
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1272, in extract_info
return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1280, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1318, in __extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1436, in process_ie_result
return self.__process_playlist(ie_result, download)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1528, in __process_playlist
entry = get_entry(i)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1517, in get_entry
)(self, i)
File "C:\Users\jae3382\AppData\Local\Temp\_MEI278162\ytdl_5069bc9c\yt_dlp\yt_dlp\YoutubeDL", line 1289, in wrapper
self.report_error(compat_str(e), e.format_traceback())
File "ytdl", line 355, in report_error
yt_dlp.utils.DownloadError: ERROR: Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type yt-dlp -U to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://www.youtube.com/channel/UCgipy6-EqjT-1BCDndXX1PA (7.4s)

작업기록입니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3973
