### ISSUE TITLE
오랜만에 인스타그램 이미지 다운 시도해 봤는데 안되네요.

### ISSUE THREAD

**Issue by hhhssj** [KurtBestor/Hitomi-Downloader#4014]
오랜만에 인스타그램 이미지 다운 시도해 봤는데 안되네요. 최근 혹시 다운로더 업데이트가 원인일까요?

Invalid: [insta] https://www.instagram.com/p/CV7YOY2PAuB

version: 3.7c (21-11-05 11:01:05 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko
order / group / uid: 22 / False / 0afc3ddca74e4bf59eda8694494cfd52
input: https://www.instagram.com/p/CV7YOY2PAuB
type: insta
single: False
url: https://www.instagram.com/p/CV7YOY2PAuB
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636815702.4988637 (14 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
single post
no _sharedData
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\insta_downloader", line 75, in read
File "extractor\insta_downloader", line 71, in id_
File "utils", line 549, in __get__
File "extractor\insta_downloader", line 67, in name
File "extractor\insta_downloader", line 214, in get_name
File "extractor\insta_downloader", line 157, in get_sd
Exception: no _sharedData

Invalid: fail=True
EOT: https://www.instagram.com/p/CV7YOY2PAuB (122.4s)

**Comment by KurtBestor** [comment]
쿠키를 업데이트해주세요
