### ISSUE TITLE
히토미에서 다운로드가 안됩니다

### ISSUE THREAD

**Issue by mbc117** [KurtBestor/Hitomi-Downloader#4015]
Invalid: [hito![K-001](https://user-images.githubusercontent.com/37955672/141672181-65ce3f63-ff50-4a6f-8535-5b8821fc285b.png)i] https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1

version: 3.7c (21-11-05 11:01:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / b8c1f8c2da3b46cd9cf94dd9e3e833bf
input: https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1
type: hitomi
single: False
url: https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636873218.0737562 (14 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:False)
Find in HK...
not found in HK
max_page = 31475
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.4
BFS: 7.4
BFS: 8.5
BFS: 9.7
BFS: 10.8
BFS: 11.9
BFS: 13.0
BFS: 15.2
BFS: 36.8
BFS: 39.5
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:False)
Find in HK...
not found in HK
max_page = 31475
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.1
BFS: 9.2
BFS: 10.2
BFS: 11.3
BFS: 12.4
BFS: 24.7
BFS: 25.8
BFS: 26.9
BFS: 27.9
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:True)
Find in HK...
not found in HK
max_page = 45051
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.2
BFS: 7.4
BFS: 8.4
BFS: 9.6
BFS: 10.6
BFS: 12.1
BFS: 13.2
BFS: 17.0
BFS: 18.2
BFS: 20.5
BFS: 21.5
BFS: 41.3
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:False)
Find in HK...
not found in HK
max_page = 31475
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.1
BFS: 5.1
BFS: 6.1
BFS: 7.1
BFS: 8.2
BFS: 9.2
BFS: 10.2
BFS: 11.3
BFS: 12.4
BFS: 13.8
BFS: 17.0
BFS: 23.6
BFS: 59.7
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:True)
Find in HK...
not found in HK
max_page = 45051
BFS: 1.0
BFS: 2.0
BFS: 3.1
BFS: 4.1
BFS: 5.1
BFS: 6.2
BFS: 7.2
BFS: 8.3
BFS: 9.5
BFS: 10.5
BFS: 11.7
BFS: 12.8
BFS: 14.2
BFS: 15.3
BFS: 18.8
BFS: 28.5
BFS: 40.2
BFS: 76.3
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1)
Find_ehen(id:2059786, ex:False)
Find in HK...
not found in HK
max_page = 31475
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.1
BFS: 7.6
BFS: 8.6
BFS: 10.3
BFS: 11.5
BFS: 12.5
BFS: 14.8
BFS: 17.5
BFS: 18.5
BFS: 20.0
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 582, in read
File "hitomi_downloader", line 459, in get_imgs
File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 640, in read
Exception: no imgs

stop
Invalid: fail=False
stop
EOT: https://hito![K-001](https://user-images.githubusercontent.com/37955672/141672181-65ce3f63-ff50-4a6f-8535-5b8821fc285b.png)i.la/doujinshi/mikakinosan-no-daigaku-seikatsu-%ED%95%9C%EA%B5%AD%EC%96%B4-2059786.html#1 (131.9s)

**Comment by KurtBestor** [comment]
옵션 - 설정 - 서버 - 우선수위 에서 `Hitomi.la` 를 끄셨네요

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 서버 - 우선순위` 에서 `Hitomi.la` 를 끄셨으니 당연히 히토미에서 다운로드가 안 돼죠..
