### ISSUE TITLE
문제

### ISSUE THREAD

**Issue by tomodazzi** [KurtBestor/Hitomi-Downloader#4022]
Invalid: [insta] https://www.instagram.com/222

version: 3.7c (21-11-14 21:00:41 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 1782dc397e4d4c51bb21b67381caa096
input: https://www.instagram.com/222
type: insta
single: False
url: https://www.instagram.com/222
dir: 
zip: 
artist: 
valid / done: False / True
range / range_p: None / None
time: 1636952144.4109411 (15 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
stories: False
Too short: 0 / 12
stop
Traceback (most recent call last):
 File "utils", line 1150, in start
 File "utils", line 1220, in start_
 File "extractor\insta_downloader", line 88, in read
 File "extractor\insta_downloader", line 464, in get_imgs_all
 File "extractor\insta_downloader", line 385, in get_imgs
Exception: Too short: 0 / 12

Invalid: fail=True
EOT: https://www.instagram.com/222  (23.4s)

stories: True
Failed to get stories: None
Too short: 0 / 12
stop
Traceback (most recent call last):
 File "utils", line 1150, in start
 File "utils", line 1220, in start_
 File "extractor\insta_downloader", line 88, in read
 File "extractor\insta_downloader", line 464, in get_imgs_all
 File "extractor\insta_downloader", line 385, in get_imgs
Exception: Too short: 0 / 12

Invalid: fail=True
EOT: https://www.instagram.com/222  (54.1s)

stories: True
Failed to get stories: None
Too short: 0 / 12
stop
Traceback (most recent call last):
 File "utils", line 1150, in start
 File "utils", line 1220, in start_
 File "extractor\insta_downloader", line 88, in read
 File "extractor\insta_downloader", line 464, in get_imgs_all
 File "extractor\insta_downloader", line 385, in get_imgs
Exception: Too short: 0 / 12

Invalid: fail=True
EOT: https://www.instagram.com/222  (54.9s)

stories: True
Failed to get stories: None
Too short: 0 / 12
stop
Traceback (most recent call last):
 File "utils", line 1150, in start
 File "utils", line 1220, in start_
 File "extractor\insta_downloader", line 88, in read
 File "extractor\insta_downloader", line 464, in get_imgs_all
 File "extractor\insta_downloader", line 385, in get_imgs
Exception: Too short: 0 / 12

Invalid: fail=True
EOT: https://www.instagram.com/222  (54.1s)

stories: True
Failed to get stories: None
Too short: 0 / 12
stop
Traceback (most recent call last):
 File "utils", line 1150, in start
 File "utils", line 1220, in start_
 File "extractor\insta_downloader", line 88, in read
 File "extractor\insta_downloader", line 464, in get_imgs_all
 File "extractor\insta_downloader", line 385, in get_imgs
Exception: Too short: 0 / 12

Invalid: fail=True
EOT: https://www.instagram.com/222  (54.1s)

**Comment by KurtBestor** [comment]
아무 게시물도 없는 계정이네요
