### ISSUE TITLE
폰허브 프리미엄, 폰허브 다운이 현재 안되고 있습니다.

### ISSUE THREAD

**Issue by mookakihi4** [KurtBestor/Hitomi-Downloader#4051]
평소랑 똑같이 쿠키 넣고 다운받을려는데 Invalid뜨면서 안되네요. 

확실한 계정으로 로그인하고 새로 쿠키 데이터 뽑아 넣었는데도 안됩니다. 혹시 몰라 크롬으로도 해보고 파이어폭스로도 

새로 쿠키뽑아 했는데 Invalid뜨면서 안되네요. 

Invalid: [pornhub] https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1

version: 3.7c (21-11-05 11:01:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 395 / False / 41437e01576644f388c1bd8c2c2f618a
input: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1
type: pornhub
single: True
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1637533912.8557982 (22 Nov)
tags: ['red']
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
is_login 2
invalid soup: https://www.pornhubpremium.com
is_login 1
invalid soup: https://www.pornhubpremium.com
is_login 0

stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "extractor\pornhub_downloader", line 330, in init
errors.LoginRequired

Invalid: fail=False
quality: 100%
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1 (36.6s)

is_login 2
invalid soup: https://www.pornhubpremium.com
no html
id: ph59d13e6c974a1
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph59d13e6c974a1
Video
id: ph59d13e6c974a1
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph59d13e6c974a1
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\pornhub_downloader", line 400, in read
File "utils", line 753, in __call__
File "<decorator-gen-33>", line 2, in get
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
quality: 100%
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1 (64.7s)

is_login 2
invalid soup: https://www.pornhubpremium.com
is_login 1
invalid soup: https://www.pornhubpremium.com
is_login 0

stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "extractor\pornhub_downloader", line 330, in init
errors.LoginRequired

Invalid: fail=False
quality: 100%
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1 (18.5s)

is_login 2
id: ph59d13e6c974a1
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph59d13e6c974a1
no html
Video
id: ph59d13e6c974a1
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph59d13e6c974a1
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\pornhub_downloader", line 400, in read
File "utils", line 753, in __call__
File "<decorator-gen-33>", line 2, in get
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
quality: 100%
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1 (24.4s)

is_login 2
id: ph59d13e6c974a1
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph59d13e6c974a1
Video
id: ph59d13e6c974a1
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph59d13e6c974a1
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1142, in start
File "utils", line 1212, in start_
File "extractor\pornhub_downloader", line 400, in read
File "utils", line 753, in __call__
File "<decorator-gen-33>", line 2, in get
File "constants", line 918, in wrapper
File "constants", line 889, in wrapper
File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
quality: 100%
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph59d13e6c974a1 (19.6s)

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 누르고 해당 웹페이지 들어가면 어떻게 보이나요?

**Comment by mookakihi4** [comment]
? 퇴근하고 다시 프로그램 실행했는데 잘되었네요. ㄷㄷ. 앞으로는 좀 더 추이를 지켜봐야겠네요.
신경 쓰셨다면 죄송합니다.
