### ISSUE TITLE
Facebook mp4 video downloaded but fail in convert, cause rename bug (original filename missing)

### ISSUE THREAD

**Issue by GoetheGo** [KurtBestor/Hitomi-Downloader#4064]
Find out that when download facebook video such as "https://www.facebook.com/cablechinadesk/videos/305612540732666", it seems everything's going well until downloading is finished.

And then it starts to convert the .mp4 video (with audio), the bug shows up with code(
 File "c:\users\kurtb\appdata\local\programs\python\python37\lib\codecs", line 322, in decode
   data = self.buffer + input
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 173: invalid start byte
)

I check out the message ('utf-8' codec can't decode byte 0xb5 in position 173: invalid start byte), it seems to be random about position xxx, usually caused by video which is kind of broken (although it can be played normally).
At the end the video lost its original filename and bring in additional file unexpectedly.

I start another similar facebook task, and it succeeds without any convert at the end. When I check out the task messages and compare them, seems like that downloading videos from facebook with audio download provideded (not [audio: None]) will convert no matter video is with audio or not .(Check [youtube_downloader.py] function about "os.rename").
suggest that stop convert video file(.mp4) which is with audio inside.

Here comes the task(Failed) message
===========================
[Facebook] 節目重温：2020-08-13(四)

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-8.1-6.3.9600-SP0 / zh
order / group / uid: 0 / False / cc099c672cc5428ca19daf7958dae328
input: https://www.facebook.com/cablechinadesk/videos/305612540732666
type: etc
single: True
url: https://www.facebook.com/cablechinadesk/videos/305612540732666
dir: Z:\HitomiDownload
zip: 
artist: 有線中國組
valid / done: False / True
range / range_p: None / None
time: 1637740360.3462503 (11月 24日)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
[0001] Z:\HitomiDownload\[Facebook] 節目重温：2020-08-13(四).mp4

[URLs]
[0001] LazyUrl(https://www.facebook.com/cablechinadesk/videos/305612540732666)    --->    https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_868865354025826_3749547242059030388_n.mp4?_nc_cat=101&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfaHEyX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=gELQKtiE_CIAX9Vykex&_nc_ht=video-nrt1-1.xx&oh=1c0cd324dde374812416eebaac3ba52b&oe=61A39A94

[Messages]
extractor: facebook
get_video: True, https://www.facebook.com/cablechinadesk/videos/305612540732666
[facebook] 305612540732666: Downloading webpage
980525379058955a - audio only (DASH audio) - 0 - 65.259 - https://video-nrt1-1.xx.fbcdn.net/v/t42.1790-2/10000000_980525389058954_828151362742453762_n.mp4?_nc_cat=102&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mcmFnXzJfYXVkaW8ifQ==&_nc_ohc=rIUtEejynRUAX8b6_ZS&_nc_ht=video-nrt1-1.xx&oh=8e7b557c75395a6640e5fe6bab097595&oe=619E178F
sd - unknown - 0 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t42.9040-2/10000000_663950251137958_2327122388677681804_n.mp4?_nc_cat=103&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjQyNiwicmxhIjo0MDk2LCJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=I6TQv-KkA-AAX8wSooH&rl=426&vabr=237&_nc_ht=video-nrt1-1.xx&oh=1e8d9ff75fe364abb97a37ec2fd18c21&oe=619E113B
hd - unknown - 0 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_868865354025826_3749547242059030388_n.mp4?_nc_cat=101&vs=f40b99bfce0f2b1f&_nc_vs=HBksFQAYJEdJQ1dtQUJpeThoNk9oWURBSFJmZWNkWkVRazBibWRqQUFBRhUAAsgBABUAGCRHR1BvQXdld3QzMmhicEVDQUdvaFdNYXUwQmQ3YnY0R0FBQUYVAgLIAQBLBogScHJvZ3Jlc3NpdmVfcmVjaXBlATENc3Vic2FtcGxlX2ZwcwAQdm1hZl9lbmFibGVfbnN1YgAgbWVhc3VyZV9vcmlnaW5hbF9yZXNvbHV0aW9uX3NzaW0AKGNvbXB1dGVfc3NpbV9vbmx5X2F0X29yaWdpbmFsX3Jlc29sdXRpb24AEWRpc2FibGVfcG9zdF9wdnFzABUAJQAcAAAmzMaT4v78igEVAigCQzMYC3Z0c19wcmV2aWV3HBdAkGXCj1wo9hgnZGFzaF9nZW4zYmFzaWNfNXNlY2dvcF9ocTJfZnJhZ18yX3ZpZGVvEgAYGHZpZGVvcy52dHMuY2FsbGJhY2sucHJvZDgSVklERU9fVklFV19SRVFVRVNUGwiIFW9lbV90YXJnZXRfZW5jb2RlX3RhZwZvZXBfaGQTb2VtX3JlcXVlc3RfdGltZV9tcw0xNjM3NzQwMzY0NzA0DG9lbV9jZmdfcnVsZQd1bm11dGVkE29lbV9yb2lfcmVhY2hfY291bnQGNDE5ODIzDG9lbV92aWRlb19pZA8zMDU2MTI1NDA3MzI2NjYSb2VtX3ZpZGVvX2Fzc2V0X2lkDzMwNTYxMjUzMDczMjY2NxVvZW1fdmlkZW9fcmVzb3VyY2VfaWQPMzA1NjEyNTI3Mzk5MzM0HG9lbV9zb3VyY2VfdmlkZW9fZW5jb2RpbmdfaWQPNjA3MjYwNzMzOTc5MzIyJQIcACW%2BARsHiAFzBDI4MTMCY2QKMjAyMC0wOC0xMwNyY2IGNDE5ODAwA2FwcAZWaWRlb3MCY3QZQ09OVEFJTkVEX1BPU1RfQVRUQUNITUVOVBNvcmlnaW5hbF9kdXJhdGlvbl9zBzEwNDkuNDgCdHMPb2VwX3Byb2dyZXNzaXZlAA%3D%3D&ccb=1-5&_nc_sid=894f7d&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ohc=gELQKtiE_CIAX9Vykex&_nc_ht=video-nrt1-1.xx&oh=ce93a9421800eca5cfd85e717e3dd089&oe=61A39A94&_nc_rid=9a0a32e991424d7
342889130858764v - 256x144 (DASH video) - 92.837 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_376577244037011_5463148211149346432_n.mp4?_nc_cat=106&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfMjU2X2NyZl8yN19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&_nc_ohc=9LCobzYg4okAX9CAOj0&_nc_ht=video-nrt1-1.xx&oh=949d6ac3da08568905726b98e6802481&oe=61A227E7
2059703890851280v - 426x240 (DASH video) - 211.74 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_264294815516415_315008480329023606_n.mp4?_nc_cat=106&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfNDI2X2NyZl8yN19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&_nc_ohc=Zbm37pv-SvIAX9tpVJe&_nc_ht=video-nrt1-1.xx&oh=06f44ffda93829482dbba9d297e77eaf&oe=61A301C9
640307623574136v - 640x360 (DASH video) - 500.217 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_674526340607292_4771863853042362511_n.mp4?_nc_cat=109&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfaHExX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=AcKY037eickAX-O0B46&_nc_ht=video-nrt1-1.xx&oh=05518ba08062f1f3706ad0d3d968b550&oe=61A396C8
607260733979322v - 1280x720 (DASH video) - 1901.144 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_868865354025826_3749547242059030388_n.mp4?_nc_cat=101&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfaHEyX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=gELQKtiE_CIAX9Vykex&_nc_ht=video-nrt1-1.xx&oh=1c0cd324dde374812416eebaac3ba52b&oe=61A39A94
video0: 607260733979322v - 1280x720 (DASH video) - 1901.144 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_868865354025826_3749547242059030388_n.mp4?_nc_cat=101&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfaHEyX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=gELQKtiE_CIAX9Vykex&_nc_ht=video-nrt1-1.xx&oh=1c0cd324dde374812416eebaac3ba52b&oe=61A39A94
video: 607260733979322v - 1280x720 (DASH video) - 1901.144 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t39.25447-2/10000000_868865354025826_3749547242059030388_n.mp4?_nc_cat=101&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfZ2VuM2Jhc2ljXzVzZWNnb3BfaHEyX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=gELQKtiE_CIAX9Vykex&_nc_ht=video-nrt1-1.xx&oh=1c0cd324dde374812416eebaac3ba52b&oe=61A39A94
audio: 980525379058955a - audio only (DASH audio) - 0 - 65.259 - https://video-nrt1-1.xx.fbcdn.net/v/t42.1790-2/10000000_980525389058954_828151362742453762_n.mp4?_nc_cat=102&ccb=1-5&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mcmFnXzJfYXVkaW8ifQ==&_nc_ohc=rIUtEejynRUAX8b6_ZS&_nc_ht=video-nrt1-1.xx&oh=8e7b557c75395a6640e5fe6bab097595&oe=619E178F
url_thumb: https://scontent-nrt1-1.xx.fbcdn.net/v/t15.5256-10/117885903_305614077399179_3625221745213011159_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=08861d&_nc_ohc=f10ieAPqB6gAX-QQddw&_nc_ht=scontent-nrt1-1.xx&oh=82c2e6452389deccc04004a69baa1f42&oe=61A28EC3
Convert: Z:\HitomiDownload\[Facebook] 節目重温：2020-08-13(四).mp4
rename (1): Z:\HitomiDownload\[Facebook] 節目重温：2020-08-13(四).mp4 -> Z:\HitomiDownload\tmp01d048b24b574b9db85e3e2f3cfda8e9_v.mp4
-i tmp01d048b24b574b9db85e3e2f3cfda8e9_v.mp4 -i tmp01d048b24b574b9db85e3e2f3cfda8e9_a.weba -c:v copy -c:a copy -strict experimental -preset ultrafast -threads 0 tmp01d048b24b574b9db85e3e2f3cfda8e9_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
ffmpeg version N-104454-gd92fdc7144-20211030 Copyright (c) 2000-2021 the FFmpeg developers
 built with gcc 10-win32 (GCC) 20210610
 configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20211030
 libavutil      57.  7.100 / 57.  7.100
 libavcodec     59. 12.100 / 59. 12.100
 libavformat    59.  8.100 / 59.  8.100
 libavdevice    59.  0.101 / 59.  0.101
 libavfilter     8. 16.100 /  8. 16.100
 libswscale      6.  1.100 /  6.  1.100
 libswresample   4.  0.100 /  4.  0.100
 libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp01d048b24b574b9db85e3e2f3cfda8e9_v.mp4':
 Metadata:
   major_brand     : iso5
   minor_version   : 1
   compatible_brands: avc1iso5dsmsmsixdash
   title           : 305612527399334
   encoder         : Lavf58.20.100
 Duration: 00:17:29.44, start: 0.000000, bitrate: 1901 kb/s
Lazyurl pp Error: Z:\HitomiDownload\[Facebook] 節目重温：2020-08-13(四).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "extractor\etc_downloader", line 207, in pp
 File "ffmpeg", line 235, in merge
 File "ffmpeg", line 148, in run
 File "c:\users\kurtb\appdata\local\programs\python\python37\lib\codecs", line 322, in decode
   data = self.buffer + input
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 173: invalid start byte

utime Error: Z:\HitomiDownload\[Facebook] 節目重温：2020-08-13(四).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 336, in run
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'Z:\\HitomiDownload\\[Facebook] 節目重温：2020-08-13(四).mp4'

stop
-show_streams -print_format json -v error "[Facebook] 節目重温：2020-08-13(四).mp4"
【ffprobe】 load...
【ffprobe】 loaded
{

}
[Facebook] 節目重温：2020-08-13(四).mp4: Invalid argument
Traceback (most recent call last):
 File "utils", line 1622, in finish
 File "ffmpeg", line 662, in get_info
 File "ffmpeg", line 659, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.facebook.com/cablechinadesk/videos/305612540732666  (52.9s)

====================

And here is the successful task message (another facebook video but no online audio download provided [audio: None])
====================
[Facebook] 節目重溫：22-1-2016(五)

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-8.1-6.3.9600-SP0 / zh
order / group / uid: 1 / False / e569c79f8f2b4b50aa66900d7b35fc68
input: https://www.facebook.com/cablechinadesk/videos/926843154126838
type: etc
single: True
url: https://www.facebook.com/cablechinadesk/videos/926843154126838
dir: Z:\HitomiDownload
zip: 
artist: 有線中國組
valid / done: True / True
range / range_p: None / None
time: 1637740456.0856173 (11月 24日)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
[0001] Z:\HitomiDownload\[Facebook] 節目重溫：22-1-2016(五).mp4

[URLs]
[0001] LazyUrl(https://www.facebook.com/cablechinadesk/videos/926843154126838)    --->    【local_lazy】 [Facebook] 節目重溫：22-1-2016(五).mp4

[Messages]
extractor: facebook
get_video: True, https://www.facebook.com/cablechinadesk/videos/926843154126838
[facebook] 926843154126838: Downloading webpage
sd - unknown - 0 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t42.1790-2/12636070_1664248847158712_1915459560_n.mp4?_nc_cat=107&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjMzMSwicmxhIjozMTY0LCJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=piR4dYoKjkEAX8ZSuCu&rl=331&vabr=184&_nc_ht=video-nrt1-1.xx&oh=61947e102c9d1c363468d6e6a1dc62aa&oe=619E0F82
hd - unknown - 0 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t42.1790-2/12645535_1686439108300960_510828202_n.mp4?_nc_cat=111&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJ2M182NDBfY3JmXzIzX21haW5fMy4wX3NkIn0%3D&_nc_ohc=zvei_2itLx0AX8BEV-l&rl=1500&vabr=616&_nc_ht=video-nrt1-1.xx&oh=c91c0bca282a27aa4a117209d503f53e&oe=619E11AF
video0: hd - unknown - 0 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t42.1790-2/12645535_1686439108300960_510828202_n.mp4?_nc_cat=111&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJ2M182NDBfY3JmXzIzX21haW5fMy4wX3NkIn0%3D&_nc_ohc=zvei_2itLx0AX8BEV-l&rl=1500&vabr=616&_nc_ht=video-nrt1-1.xx&oh=c91c0bca282a27aa4a117209d503f53e&oe=619E11AF
trying to get f_video with audio
failed to get f_video with audio: list index out of range
video: hd - unknown - 0 - 0 - https://video-nrt1-1.xx.fbcdn.net/v/t42.1790-2/12645535_1686439108300960_510828202_n.mp4?_nc_cat=111&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJ2M182NDBfY3JmXzIzX21haW5fMy4wX3NkIn0%3D&_nc_ohc=zvei_2itLx0AX8BEV-l&rl=1500&vabr=616&_nc_ht=video-nrt1-1.xx&oh=c91c0bca282a27aa4a117209d503f53e&oe=619E11AF
audio: None
url_thumb: https://scontent-nrt1-1.xx.fbcdn.net/v/t15.5256-10/12594336_2161566747317372_223186538_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=ed1892&_nc_ohc=rc-2Vz9Tbw4AX_G-hxd&_nc_ht=scontent-nrt1-1.xx&oh=3e88c2defc3effae2244e8f77e81fbdc&oe=61A35C8A
stop
-show_streams -print_format json -v error "[Facebook] 節目重溫：22-1-2016(五).mp4"
【ffprobe】 load...
【ffprobe】 loaded
EOT: https://www.facebook.com/cablechinadesk/videos/926843154126838  (3.7s)

====================

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by GoetheGo** [comment]
> Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

thx, it works well!
