### ISSUE TITLE
제이마나 다운이 안됩니다

### ISSUE THREAD

**Issue by williams2222** [KurtBestor/Hitomi-Downloader#4070]
오류메시지 첨부 합니다 확인 부탁드려요

Invalid: [jmana] https://jmana1.net/book?bookid=1865

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 4287d660e3c64211835fe84098b70e89
input: https://jmana1.net/book?bookid=1865
type: jmana
single: False
url: https://jmana1.net/book?bookid=1865
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1637786683.78397 (11월 25일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://jmana1.net/book?bookid=1865
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.net/book?bookid=1865

Invalid: fail=True
EOT: https://jmana1.net/book?bookid=1865  (1.3s)

항상 잘 사용하고 있습니다
감사합니다

**Comment by williams2222** [comment]
또 갑자기 되네요 ㅎㅎ;; 
사이트 문제였나 봅니다
제가 오류 메시지를 볼줄 몰라서... 번거롭게 해서 죄송합니다

**Comment by Orange6539** [comment]
물론 제이마나가 요즘 만화 이미지 서버가 자주 뻗긴한데 안그런 경우 발생하네요
저는 https://jmana1.jjmana.net/book?bookid=1152 이 주소인데
사이트 먹통도 아닌데도(각 화수 클릭하면 만화 이미지 출력 잘됨)
주소 입력하자 마자 바로 빨간불 들어옴


4분 58초 뒤 다시 시작: https://jmana1.jjmana.net/book?bookid=1152

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 9a7486a94ef94a2a8a07aae741f9ce34
input: https://jmana1.jjmana.net/book?bookid=1152
type: jmana
single: False
url: https://jmana1.jjmana.net/book?bookid=1152
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1638271418.2601671 (11월 30일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.0s)

403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.1s)

403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.0s)

403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.6s)

403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.0s)

403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.0s)

403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152
stop
Traceback (most recent call last):
 File "downloader", line 370, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jmana1.jjmana.net/book?bookid=1152

Invalid: fail=True
EOT: https://jmana1.jjmana.net/book?bookid=1152  (1.2s)

**Comment by KurtBestor** [comment]
@Orange6539 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Orange6539** [comment]
> @Orange6539 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

문제가 됐었던 링크가 정상작동 함을 확인 하였습니다
매번 감사합니다
