### ISSUE TITLE
Instagram doesn‘t WinError 10060

### ISSUE THREAD

**Issue by xueziang** [KurtBestor/Hitomi-Downloader#4075]
Invalid: [insta] https://www.instagram.com/zhaozhizhizhale

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / zh
order / group / uid: 1 / False / 388914b306e94a2b8193759e167f913e
input: https://www.instagram.com/zhaozhizhizhale
type: insta
single: False
url: https://www.instagram.com/zhaozhizhizhale
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1637961504.7754922 (11月 27日)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002716E9CEEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002716E9CEEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002716E9CEEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002716E9CEEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.1s)

HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000271717B3A88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000271717B3A88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000271717B3A88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000271717B3A88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.1s)

HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000254544DDEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000254544DDEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000254544DDEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000254544DDEC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.1s)

HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025449C6FD48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000025449C6FD48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025449C6FD48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025449C6FD48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.1s)

HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000254531484C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000254531484C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000254531484C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000254531484C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.0s)

HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001666437CF48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001666437CF48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001666437CF48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001666437CF48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.0s)

HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016664386508>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000016664386508>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016664386508>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 561, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 206, in get_username
 File "extractor\insta_downloader", line 149, in get_sd
 File "extractor\insta_downloader", line 115, in read_html
 File "downloader", line 415, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 183, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /zhaozhizhizhale (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016664386508>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Invalid: fail=True
EOT: https://www.instagram.com/zhaozhizhizhale  (43.1s)

**Comment by KurtBestor** [comment]
Check your firewall settings.
