### ISSUE TITLE
Hiyobi에만 있는 갤러리의 경우 다운로드 불가

### ISSUE THREAD

**Issue by exhvis** [KurtBestor/Hitomi-Downloader#4076]
```Invalid: [hitomi] https://hiyobi.me/reader/jmLYZR

version: 3.7d (21-11-25 02:47:42 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / b6b7ef6032b745dda52a63f231ab0bc5
input: https://hiyobi.me/reader/jmLYZR
type: hiyobi
single: False
url: https://hiyobi.me/reader/jmLYZR
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1637981117.1297235 (11월 27일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 640, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://hiyobi.me/reader/jmLYZR  (0.1s)

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 450, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

get_imgs server: ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
ValueError: invalid literal for int() with base 10: 'jmLYZR'

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 640, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://hiyobi.me/reader/jmLYZR  (0.0s)
```

--------------------
다운로드 시도 링크 : https://hiyobi.me/reader/jmLYZR
지금은 히요비에만 업로드된 자료는 다운로드 불가능한가요?

**Comment by KurtBestor** [comment]
네, 곧 없어질 사이트라서 뺐어요

**Comment by blazepsyki** [comment]
다시 사이트 운영이 되고 있는 것 같은데 이부분 실시간으로 대응해주시길 바라는 건 무리인 거 같고 v3.3으로 해보니 잘 되는 것 같은데 이때 내부에서 돌아가던 extractor만 따로 스크립트로 올려주실수 있나요?
(혹시 스크립트가 제가 생각하는 것처럼 작동하는게 아니면 무시해주시면 됩니다...)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/146668475-ffe36b64-9a2f-443f-b69e-2b1258fe2bd4.png)

그렇다네요

**Comment by blazepsyki** [comment]
아하... 답변 감사합니다. 거참 사정 복잡하네요....
