### ISSUE TITLE
픽시브가 다운로드되지않습니다

### ISSUE THREAD

**Issue by Toresda** [KurtBestor/Hitomi-Downloader#4077]
Invalid: [pixiv] https://www.pixiv.net/bookmark_new_illust.php

version: 3.7d (21-11-25 02:47:42 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko
order / group / uid: 0 / False / 68775514834c43f0a2e98f52a813ade3
input: https://www.pixiv.net/bookmark_new_illust.php
type: pixiv
single: False
url: https://www.pixiv.net/bookmark_new_illust.php
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1637983075.2027123 (11월 27일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\pixiv_downloader", line 67, in read
 File "extractor\pixiv_downloader", line 388, in get_info
 File "extractor\pixiv_downloader", line 452, in my_id
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pixiv.net/bookmark_new_illust.php  (0.0s)

8 / 32
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1239, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://www.pixiv.net/bookmark_new_illust.php  (1.5s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
