### ISSUE TITLE
xvideos.com 다운로드 안되는 영상들이 가끔 있습니다.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#4083]
이번에는 2개 입니다.

혹시 방법이 있을까요?

1. 1. 4분 9초 뒤 다시 시작: https://www.xvideos.com/video66018059/mi_hermana_se_da_cuenta_que_me_masturbo_viendo_su_culo_y_me_amenaza_con_decirle_mi_madre_mi_hermana_termina_ayudandome_a_eyacular

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 17382427349744e5ad9fcf8fe0084f77
input: https://www.xvideos.com/video66018059/mi_hermana_se_da_cuenta_que_me_masturbo_viendo_su_culo_y_me_amenaza_con_decirle_mi_madre_mi_hermana_termina_ayudandome_a_eyacular
type: xvideo
single: True
url: https://www.xvideos.com/video66018059/mi_hermana_se_da_cuenta_que_me_masturbo_viendo_su_culo_y_me_amenaza_con_decirle_mi_madre_mi_hermana_termina_ayudandome_a_eyacular
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1638088614.066363 (11월 28일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
404
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cdn77-vid.xvideos-cdn.com/IRBj1vsniYkuhnDqKXg2qQ==,1638099488/videos_new/hls/89/1e/67/891e67fab861cced217a92ead5443727/hls-1080p-35142.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\xvideo_downloader", line 78, in read
 File "utils", line 765, in __call__
 File "<decorator-gen-21>", line 2, in get
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "extractor\xvideo_downloader", line 34, in get
 File "m3u8_tools", line 293, in playlist2stream
 File "<decorator-gen-9>", line 2, in __init__
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 118, in __init__
 File "downloader", line 431, in read_html
Exception: 404

Invalid: fail=True
EOT: https://www.xvideos.com/video66018059/mi_hermana_se_da_cuenta_que_me_masturbo_viendo_su_culo_y_me_amenaza_con_decirle_mi_madre_mi_hermana_termina_ayudandome_a_eyacular  (78.6s)

2. 2분 47초 뒤 다시 시작: https://www.xvideos.com/video65298807/stunning_close-up_blowjob_with_cum_in_mouth

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 77103777399941b9aab1bd62ae295366
input: https://www.xvideos.com/video65298807/stunning_close-up_blowjob_with_cum_in_mouth
type: xvideo
single: True
url: https://www.xvideos.com/video65298807/stunning_close-up_blowjob_with_cum_in_mouth
dir: F:\Torrent\Y\xhamster
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1638088661.3721418 (11월 28일)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.11.10.1
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
[0001] F:\Torrent\Y\xhamster\Stunning close-up blowjob with cum in mouth (65298807).mp4

[URLs]
[0001] LazyUrl(https://www.xvideos.com/video65298807/stunning_close-up_blowjob_with_cum_in_mouth)    --->    M3u8_stream(https://cdn77-vid.xvideos-cdn.com/begCyBv0_zqANXnvN22ZMQ==,1638099484/videos_new/hls/b3/bb/ae/b3bbae1210de919d1a5a1806b2d66b36/hls-1080p-78868.m3u8)

[Messages]

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Traceback (most recent call last):
 File "m3u8_tools", line 48, in run
 File "<decorator-gen-10>", line 2, in _read
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 207, in _read
 File "m3u8_tools", line 200, in _read
Exception: Failed to download

Fail : Stunning close-up blowjob with cum in mouth (65298807).mp4
Traceback (most recent call last):
 File "downloader", line 774, in download
 File "m3u8_tools", line 180, in read
 File "m3u8_tools", line 48, in run
 File "<decorator-gen-10>", line 2, in _read
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 207, in _read
 File "m3u8_tools", line 200, in _read
Exception: Failed to download

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Traceback (most recent call last):
 File "m3u8_tools", line 48, in run
 File "<decorator-gen-10>", line 2, in _read
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 207, in _read
 File "m3u8_tools", line 200, in _read
Exception: Failed to download

Traceback (most recent call last):
 File "m3u8_tools", line 48, in run
 File "<decorator-gen-10>", line 2, in _read
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 207, in _read
 File "m3u8_tools", line 200, in _read
Exception: Failed to download

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Traceback (most recent call last):
 File "m3u8_tools", line 48, in run
 File "<decorator-gen-10>", line 2, in _read
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 207, in _read
 File "m3u8_tools", line 200, in _read
Exception: Failed to download

Fail_404 : None
Traceback (most recent call last):
 File "downloader", line 950, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Traceback (most recent call last):
 File "m3u8_tools", line 48, in run
 File "<decorator-gen-10>", line 2, in _read
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "m3u8_tools", line 207, in _read
 File "m3u8_tools", line 200, in _read
Exception: Failed to download

stop
valid=False 1
-show_streams -print_format json -v error "Stunning close-up blowjob with cum in mouth (65298807).mp4"
【ffprobe】 load...
【ffprobe】 loaded
{

}
Stunning close-up blowjob with cum in mouth (65298807).mp4: No such file or directory
Traceback (most recent call last):
 File "utils", line 1622, in finish
 File "ffmpeg", line 662, in get_info
 File "ffmpeg", line 659, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.xvideos.com/video65298807/stunning_close-up_blowjob_with_cum_in_mouth  (27.7s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by DBdeepsleeper** [comment]
잘 되네요. 고맙습니다.
