### ISSUE TITLE
bilibili 플레이리스트 다운로드 오류

### ISSUE THREAD

**Issue by wls123212** [KurtBestor/Hitomi-Downloader#4117]
biliibili에서 같은 플레이리스트 내의 영상을 여러개 동시에 다운로드 시 에러가 납니다.

보통 가장 마지막으로 추가한 파일이 정상 다운되고 나머지는 에러가 납니다.

같은 플레이리스트의 영상 주소는 다음과 같이 

https://www.bilibili.com/video/BV1MK411A7sj?p=1
https://www.bilibili.com/video/BV1MK411A7sj?p=2
https://www.bilibili.com/video/BV1MK411A7sj?p=3
https://www.bilibili.com/video/BV1MK411A7sj?p=4

p= 뒤의 숫자만 달라지는데, 이 때문에 모든 영상들의 임시 다운로드 이름 파일이 

1MK411A7sj.part0
와 같은 식으로 겹쳐서 발생하는 현상 같습니다.

플레이리스트의 각 파일 별로 임시 파일의 파일 이름을 겹치지 않게 해주시면 좋을 것 같습니다.

그리고 https://www.bilibili.com/video/BV1MK411A7sj

와 같은 플레이리스트 자체 주소를 넣었을 때 플레이리스트 내의 영상이 일괄 다운되면 좋을 것 같습니다.

감사합니다.

아래는 오류났을 때의 작업정보입니다.

4분 53초 뒤 다시 시작: https://www.bilibili.com/video/BV1MK411A7sj?p=2

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko
order / group / uid: 0 / False / b14af0ba290f49f9ba941e1eb9f7e4e0
input: https://www.bilibili.com/video/BV1MK411A7sj?p=2
type: bili
single: True
url: https://www.bilibili.com/video/BV1MK411A7sj/?p=2
dir: hitomi_downloaded_bili
zip: 
artist: None
valid / done: False / True
range / range_p: ~4000 / None
time: 1638929481.5818012 (12월 8일)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 8, 'overwrite': True}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_bili\1MK411A7sj.part0.flv

[URLs]
[0001] LazyUrl(https://www.bilibili.com/video/BV1MK411A7sj/?p=2)    --->    http://upos-hz-mirrorakam.akamaized.net/upgcxcode/39/08/243730839/243730839_nb2-1-32.flv?e=ig8euxZM2rNcNbRVhwdVhoM1hwdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1638936682&gen=playurl&nbs=1&oi=1994211882&os=akam&platform=pc&trid=29af41f7b120420295eb8cf4abbcec52&uipk=5&upsig=e8c46bef0314c90b2222f9f0067cc97c&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1638936682~hmac=d28090bf0b8f98297df9cb5e75599a66ec68f6f83cd91693420a5f95a6f24f7c&mid=0

[Messages]
redirect: https://www.bilibili.com/video/BV1MK411A7sj?p=2 -> https://www.bilibili.com/video/BV1MK411A7sj/?p=2
cid: 243730839
resolution: 480p
n_threads: 8
stop
Traceback (most recent call last):
 File "utils", line 1396, in finish
 File "extractor\bili_downloader", line 112, in post_processing
 File "ffmpeg", line 475, in join
 File "ffmpeg", line 183, in rename
Exception: No file

-show_streams -print_format json -v error "1MK411A7sj.part0.flv"
【ffprobe】 load...
【ffprobe】 loaded
{

}
1MK411A7sj.part0.flv: No such file or directory
Traceback (most recent call last):
 File "utils", line 1622, in finish
 File "ffmpeg", line 662, in get_info
 File "ffmpeg", line 659, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.bilibili.com/video/BV1MK411A7sj?p=2  (22.6s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wls123212** [comment]
잘 됩니다, 감사합니다

**Comment by rohit7044** [comment]
Hi!
I have a playlist that I want to download, but they're in p1 - pN. Is there anyway where just by giving the link, I can download the whole playlist? I am going through the issues but can't seem to find a solution to this. I have downloaded the latest version as of date. If someone can guide me through the steps via link or something, then also it would be great!

Thank you for your trememndous work @KurtBestor and team.
