### ISSUE TITLE
루리웹 성유게 성인게임 사진을 다운로드가 안돼요 적용도 해보았는데요 잘 안돼는거 같아요

### ISSUE THREAD

**Issue by dkfle222** [KurtBestor/Hitomi-Downloader#4118]
Invalid: [ruliweb] https://bbs.ruliweb.com/community/board/310007/read/228914?

version: 3.7d (21-12-08 06:06:02 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 345b84be93384d749a296b278d578182
input: https://bbs.ruliweb.com/community/board/310007/read/228914?
type: ruliweb
single: False
url: https://bbs.ruliweb.com/community/board/310007/read/228914?
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1638965066.345741 (12월 8일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "dynamic_module_0", line 59, in read
 File "dynamic_module_0", line 54, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://bbs.ruliweb.com/community/board/310007/read/228914?  (0.9s)

**Comment by KurtBestor** [comment]
로그인이 필요한 페이지는 쿠키 업데이트 경고 띄우게 수정했어요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
