### ISSUE TITLE
노벨피아를 시도하려고 했는데 안됩니다.

### ISSUE THREAD

**Issue by ehch103** [KurtBestor/Hitomi-Downloader#4122]
쿠키를 업데이트 하라고 해서 여러번 했고 테스트 버전도 플레이 했는데 다운이 불가능하더군요.

Login required; Update your cookies
https://novelpia.com/novel/875

version: 3.7d (21-12-08 17:53:10 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a53846c3a9344f189ce9e3912a8d6dea
input: https://novelpia.com/novel/875
type: novelpia
single: False
url: https://novelpia.com/novel/875
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639027740.74063 (12월 9일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.7s)

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.7s)

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.7s)

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.7s)

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.8s)

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.7s)

stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/875  (0.9s)

제 상태는 이러합니다만 어떻게 해야하나요?

**Comment by blazepsyki** [comment]
저도 시험삼아 해봤는데 안되는 것 같아 남겨봅니다.
미결제 상태이고 공모전 작품이라 액세스는 가능한 상태이며, SNS(카카오 계정)을 통해 로그인한 상태입니다. 쿠키는 전체 사이트를 export해서 집어넣었습니다.

Login required; Update your cookies
https://novelpia.com/novel/50664

version: 3.7d (21-12-12 09:44:45 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a79bd0455e2444ff95ee5754953816cf
input: https://novelpia.com/novel/50664
type: novelpia
single: False
url: https://novelpia.com/novel/50664
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639339416.072587 (12월 13일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/50664  (0.4s)


stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/50664  (0.3s)


stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/50664  (0.3s)


stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/50664  (0.4s)
