### ISSUE TITLE
baraag 에서 안되는 계정이 있습니다.

### ISSUE THREAD

**Issue by sosoeun** [KurtBestor/Hitomi-Downloader#4125]
Invalid: [baraag] https://baraag.net/@xentho

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 6 / False / 8a0d83638d6e4970a24883a4ee78d969
input: https://baraag.net/@xentho
type: baraag
single: False
url: https://baraag.net/@xentho
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: -100,1~ / None
time: 1639063385.1162257 (12월 10일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\baraag_downloader", line 45, in read
 File "mastodon", line 31, in get_imgs
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085

Invalid: fail=True
EOT: https://baraag.net/@xentho  (116.5s)

403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\baraag_downloader", line 45, in read
 File "mastodon", line 31, in get_imgs
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085

Invalid: fail=True
EOT: https://baraag.net/@xentho  (10.0s)

403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\baraag_downloader", line 45, in read
 File "mastodon", line 31, in get_imgs
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085

Invalid: fail=True
EOT: https://baraag.net/@xentho  (6.7s)

403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\baraag_downloader", line 45, in read
 File "mastodon", line 31, in get_imgs
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085

Invalid: fail=True
EOT: https://baraag.net/@xentho  (80.7s)

403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\baraag_downloader", line 45, in read
 File "mastodon", line 31, in get_imgs
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://baraag.net/@xentho/media?max_id=107299610473013085

Invalid: fail=True
EOT: https://baraag.net/@xentho  (10.3s)

다른 계정은 정상적으로 작동됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by sosoeun** [comment]
완벽합니다. 

감사합니다.
