### ISSUE TITLE
welovemanga 다운이 되지 않습니다.

### ISSUE THREAD

**Issue by esulbitea** [KurtBestor/Hitomi-Downloader#4127]
해당 사이트에서 십여일전부터 다운이 되지 않고 있습니다.

Invalid: [lhscan] https://welovemanga.net/luvmg-1854/

version: 3.7d (21-11-25 02:47:42 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 0d033f8ca0e8444e88a2921a9891e699
input: https://welovemanga.net/luvmg-1854/
type: lhscan
single: False
url: https://welovemanga.net/luvmg-1854/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [19, 20]
time: 1639092396.1455843 (12월 10일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
https://welovemanga.net/luvmg-1854/ -> https://welovemanga.net/luvmg-1854/
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
Chapter 19
no cn
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\lhscan_downloader", line 93, in read
 File "<decorator-gen-47>", line 2, in get_imgs
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "extractor\lhscan_downloader", line 185, in get_imgs
 File "<decorator-gen-45>", line 2, in get_imgs_page
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "extractor\lhscan_downloader", line 109, in get_imgs_page
 File "ree", line 15, in find
ree.NotFound: no cn

Invalid: fail=True
EOT: https://welovemanga.net/luvmg-1854/  (20.4s)

**Comment by wlskekrk** [comment]
저도 안됐었는데 설정에서 쿠키 초기화를 하니까 잘되더라구요 한번 해보시면?

**Comment by esulbitea** [comment]
정말 감사합니다. 말씀처럼 설정에서 쿠키를 초기화 하니까 잘 됩니다.
오랜동안 안되어서 곤란했는데 진심으로 감사드립니다.
