### ISSUE TITLE
가끔 소설가가 되자랑 카쿠요무에서 파일 합치기가 되질 않습니다.

### ISSUE THREAD

**Issue by Im-IKAROS** [KurtBestor/Hitomi-Downloader#4137]
다른것들은 잘되는 편인데 가끔씩 카쿠요무랑 소설가가 되자 마지막에 파일합쳐지기가 안되는 사이트가 있습니다.
https://ncode.syosetu.com/n2172gb/
https://kakuyomu.jp/works/1177354054893179985
https://ncode.syosetu.com/n8456gx/
지금은 이렇게 3개가 있습니다. 마지막에 합쳐지는게 번역기로 번역할때 편하기는 합니다.

마지막 사이트 같은 경우 작업정보가
[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク (n8456gx)

version: 3.5 (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 10 / False / f617ef4f4d144615844e4293cb57838e
input: https://novel18.syosetu.com/n8456gx/
type: syosetu
single: False
url: https://ncode.syosetu.com/n8456gx/
dir: hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク
zip: 
artist: FUNACHI
valid / done: False / True
range / range_p: None / None
time: 1638967084.3587282 (12월 8일)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0001] 白き追憶.txt
[0002] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0002] 第1話 死の南風.txt
[0003] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0003] 第2話 一大決心直後に赤さんに殺されるザコ.txt
[0004] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0004] 第3話 さあ行こう！死の街へ①.txt
[0005] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0005] 第4話 さあ行こう！死の街へ②.txt
[0006] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0006] 第5話 さあ行こう！死の街へ③.txt
[0007] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0007] 第6話 死の街からの戦利品.txt
[0008] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0008] 第7話 セナちゃん☆.txt
[0009] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0009] 第8話 初妻『幻夢』橋田 瀬凪(はしだ せなぎ)☆.txt
[0010] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0010] 第1話 2日ぶりの地上.txt
[0011] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0011] 第2話 ケモミミ太ももネコミミ.txt
[0012] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0012] 第3話 死人の津波 氷晶姫の覚醒.txt
[0013] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0013] 第4話  3番目の妻、発見w.txt
[0014] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0014] 第5話 結局ゾンビにするけどネコミミちゃんを攻略した(つもり).txt
[0015] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0015] 第6話 戦略的撤退.txt
[0016] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0016] 第7話 初妻の破瓜★.txt
[0017] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0017] 第8話 これなら勝てる★.txt
[0018] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0018] 第9話 幻氷の百合☆.txt
[0019] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0019] 第10話 幻夢の力☆.txt
[0020] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0020] 第11話 幻夢の中で溶け合う2人★(催眠セックス).txt
[0021] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0021] 第12話 世界の真実に至りし者☆.txt
[0022] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0022] 第13話 戦略的撤退(本日2度目).txt
[0023] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0023] 第14話 氷姫の雪見大福←おっぱい※激柔(良い匂い)美巨乳☆.txt
[0024] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0024] 第15話 氷の天屍の母性☆.txt
[0025] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0025] 第16話 崩壊世界の雪見晩酌☆.txt
[0026] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0026] 第17話 参妻『氷晶姫』唐島 氷露 リシェンコ(からしま ひづゆ りしぇんこ)★.txt
[0027] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0027] 第1話 おてんば氷姫☆.txt
[0028] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0028] 第2話 命令拒否☆.txt
[0029] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0029] 第3話 完全支配を超えるナニカ★.txt
[0030] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0030] 第4話 氷姫の珠玉.txt
[0031] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0031] 第5話 とある救急隊員のパンデミック.txt
[0032] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0032] 第6話 公安職の人は大変だねー緊急車両乗って.txt
[0033] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0033] 第7話 凍眠姫解凍式典★.txt
[0034] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0034] 第8話 真面目ぶった救急隊員くんを揺さぶる.txt
[0035] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0035] 第9話 信念ブレイカー.txt
[0036] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0036] 第10話 みんなもいっしょに考えてみよう☆.txt
[0037] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0037] 第11話 ロシアンハーフ超絶美少女JS開封レビュー☆.txt
[0038] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0038] 第12話 尊厳フミ☆ニジ.txt
[0039] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0039] 第1話 砕けた少女.txt
[0040] hitomi_downloaded_syosetu\[FUNACHI] 【7／25 挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\[0040] 第2話 君が欲しかった☆.txt

[URLs]
[0001] LazyUrl(https://ncode.syosetu.com/n8456gx/1/)    --->    【local_lazy】 [0001] 白き追憶.txt
[0002] LazyUrl(https://ncode.syosetu.com/n8456gx/2/)    --->    【local_lazy】 [0002] 第1話 死の南風.txt
[0003] LazyUrl(https://ncode.syosetu.com/n8456gx/3/)    --->    【local_lazy】 [0003] 第2話 一大決心直後に赤さんに殺されるザコ.txt
[0004] LazyUrl(https://ncode.syosetu.com/n8456gx/4/)    --->    【local_lazy】 [0004] 第3話 さあ行こう！死の街へ①.txt
[0005] LazyUrl(https://ncode.syosetu.com/n8456gx/5/)    --->    【local_lazy】 [0005] 第4話 さあ行こう！死の街へ②.txt
[0006] LazyUrl(https://ncode.syosetu.com/n8456gx/6/)    --->    【local_lazy】 [0006] 第5話 さあ行こう！死の街へ③.txt
[0007] LazyUrl(https://ncode.syosetu.com/n8456gx/7/)    --->    【local_lazy】 [0007] 第6話 死の街からの戦利品.txt
[0008] LazyUrl(https://ncode.syosetu.com/n8456gx/8/)    --->    【local_lazy】 [0008] 第7話 セナちゃん☆.txt
[0009] LazyUrl(https://ncode.syosetu.com/n8456gx/9/)    --->    【local_lazy】 [0009] 第8話 初妻『幻夢』橋田 瀬凪(はしだ せなぎ)☆.txt
[0010] LazyUrl(https://ncode.syosetu.com/n8456gx/10/)    --->    【local_lazy】 [0010] 第1話 2日ぶりの地上.txt
[0011] LazyUrl(https://ncode.syosetu.com/n8456gx/11/)    --->    【local_lazy】 [0011] 第2話 ケモミミ太ももネコミミ.txt
[0012] LazyUrl(https://ncode.syosetu.com/n8456gx/12/)    --->    【local_lazy】 [0012] 第3話 死人の津波 氷晶姫の覚醒.txt
[0013] LazyUrl(https://ncode.syosetu.com/n8456gx/13/)    --->    【local_lazy】 [0013] 第4話  3番目の妻、発見w.txt
[0014] LazyUrl(https://ncode.syosetu.com/n8456gx/14/)    --->    【local_lazy】 [0014] 第5話 結局ゾンビにするけどネコミミちゃんを攻略した(つもり).txt
[0015] LazyUrl(https://ncode.syosetu.com/n8456gx/15/)    --->    【local_lazy】 [0015] 第6話 戦略的撤退.txt
[0016] LazyUrl(https://ncode.syosetu.com/n8456gx/16/)    --->    【local_lazy】 [0016] 第7話 初妻の破瓜★.txt
[0017] LazyUrl(https://ncode.syosetu.com/n8456gx/17/)    --->    【local_lazy】 [0017] 第8話 これなら勝てる★.txt
[0018] LazyUrl(https://ncode.syosetu.com/n8456gx/18/)    --->    【local_lazy】 [0018] 第9話 幻氷の百合☆.txt
[0019] LazyUrl(https://ncode.syosetu.com/n8456gx/19/)    --->    【local_lazy】 [0019] 第10話 幻夢の力☆.txt
[0020] LazyUrl(https://ncode.syosetu.com/n8456gx/20/)    --->    【local_lazy】 [0020] 第11話 幻夢の中で溶け合う2人★(催眠セックス).txt
[0021] LazyUrl(https://ncode.syosetu.com/n8456gx/21/)    --->    【local_lazy】 [0021] 第12話 世界の真実に至りし者☆.txt
[0022] LazyUrl(https://ncode.syosetu.com/n8456gx/22/)    --->    【local_lazy】 [0022] 第13話 戦略的撤退(本日2度目).txt
[0023] LazyUrl(https://ncode.syosetu.com/n8456gx/23/)    --->    【local_lazy】 [0023] 第14話 氷姫の雪見大福←おっぱい※激柔(良い匂い)美巨乳☆.txt
[0024] LazyUrl(https://ncode.syosetu.com/n8456gx/24/)    --->    【local_lazy】 [0024] 第15話 氷の天屍の母性☆.txt
[0025] LazyUrl(https://ncode.syosetu.com/n8456gx/25/)    --->    【local_lazy】 [0025] 第16話 崩壊世界の雪見晩酌☆.txt
[0026] LazyUrl(https://ncode.syosetu.com/n8456gx/26/)    --->    【local_lazy】 [0026] 第17話 参妻『氷晶姫』唐島 氷露 リシェンコ(からしま ひづゆ りしぇんこ)★.txt
[0027] LazyUrl(https://ncode.syosetu.com/n8456gx/27/)    --->    【local_lazy】 [0027] 第1話 おてんば氷姫☆.txt
[0028] LazyUrl(https://ncode.syosetu.com/n8456gx/28/)    --->    【local_lazy】 [0028] 第2話 命令拒否☆.txt
[0029] LazyUrl(https://ncode.syosetu.com/n8456gx/29/)    --->    【local_lazy】 [0029] 第3話 完全支配を超えるナニカ★.txt
[0030] LazyUrl(https://ncode.syosetu.com/n8456gx/30/)    --->    【local_lazy】 [0030] 第4話 氷姫の珠玉.txt
[0031] LazyUrl(https://ncode.syosetu.com/n8456gx/31/)    --->    【local_lazy】 [0031] 第5話 とある救急隊員のパンデミック.txt
[0032] LazyUrl(https://ncode.syosetu.com/n8456gx/32/)    --->    【local_lazy】 [0032] 第6話 公安職の人は大変だねー緊急車両乗って.txt
[0033] LazyUrl(https://ncode.syosetu.com/n8456gx/33/)    --->    【local_lazy】 [0033] 第7話 凍眠姫解凍式典★.txt
[0034] LazyUrl(https://ncode.syosetu.com/n8456gx/34/)    --->    【local_lazy】 [0034] 第8話 真面目ぶった救急隊員くんを揺さぶる.txt
[0035] LazyUrl(https://ncode.syosetu.com/n8456gx/35/)    --->    【local_lazy】 [0035] 第9話 信念ブレイカー.txt
[0036] LazyUrl(https://ncode.syosetu.com/n8456gx/36/)    --->    【local_lazy】 [0036] 第10話 みんなもいっしょに考えてみよう☆.txt
[0037] LazyUrl(https://ncode.syosetu.com/n8456gx/37/)    --->    【local_lazy】 [0037] 第11話 ロシアンハーフ超絶美少女JS開封レビュー☆.txt
[0038] LazyUrl(https://ncode.syosetu.com/n8456gx/38/)    --->    【local_lazy】 [0038] 第12話 尊厳フミ☆ニジ.txt
[0039] LazyUrl(https://ncode.syosetu.com/n8456gx/39/)    --->    【local_lazy】 [0039] 第1話 砕けた少女.txt
[0040] LazyUrl(https://ncode.syosetu.com/n8456gx/40/)    --->    【local_lazy】 [0040] 第2話 君が欲しかった☆.txt

[Messages]
get_session
single: False
stop
Traceback (most recent call last):
 File "utils", line 1396, in finish
 File "extractor\syosetu_downloader", line 122, in post_processing
FileNotFoundError: [Errno 2] No such file or directory: 'hitomi_downloaded_syosetu\\[FUNACHI] 【7／25\u3000挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク\\[merged] [FUNACHI] 【7／25\u3000挿絵の髪の描込み作業進行！1章第5話】ゾンビパンデミックで俺だけゾンビに襲われないのでゾンビの巣窟と化した街で美少女ゾンビ嫁をお持ち帰りコレク (n8456gx).txt'

EOT: https://novel18.syosetu.com/n8456gx/  (39.6s) 이렇게 나옵니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Im-IKAROS** [comment]
감사합니다.~~
