### ISSUE TITLE
브라우저로 보기 local host 6979 오류

### ISSUE THREAD

**Issue by hyggelovent** [KurtBestor/Hitomi-Downloader#4141]
![localhosterror](https://user-images.githubusercontent.com/96055372/145803730-74e7b758-0b77-4ec8-b9af-374debace2a2.PNG)

이번에 업데이트하고 생긴 문제입니다

글씨체가 변하였습니다

#4121 참고해봤지만 해결되지 않았습니다..!

비슷한 글을 참고해봤지만

HTTP API 얘는 키가 비활성화(회색) 상태라 누를 수도 없었습니다

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 뜬 내용 보여주세요

**Comment by hyggelovent** [comment]
> Ctrl + L 눌러서 뜬 내용 보여주세요

Checking for updates... HitomiDownloader2

VQevpeBWYebhe4bIk7enP6MFuUDljWTsQPWrwsW0aLCsmKAKa75D5HLIJsVLLi654+4NeDJA8h9pgFt57jMb9CmE900Zy7t0qeH4SqYbzPuVguAeb=dLZBQjtzErac7yIvnhsemDxOWe6f0wCjUudQXSC2FRJF8zOX6=hPLuNYFfLhKFEY8++kR7nX70fx2p2AoMuEF0Er4uzchxUiHqlWTALsHoCzTEcb+autEzUPmS+AAiuiIPKKM=fY0qY2O4jRT8vEI55Tb=5ETdMbByAw4=lUjkc1E+7AvA1BFhNSdrLknaC1Hl6zpNjSoUosTZ

PrefixPath: C:/Users/ADMINI~1/AppData/Local/Temp/_MEI33642/PyQt/Qt
LibraryExecutablesPath: C:/Users/ADMINI~1/AppData/Local/Temp/_MEI33642/PyQt/Qt/bin
BinariesPath: C:/Users/ADMINI~1/AppData/Local/Temp/_MEI33642/PyQt/Qt/bin

webp: False
webp_anim: True

Font: Gulim -> Hitomi Font
System: Windows
Temp: C:\Users\ADMINI~1\AppData\Local\Temp
Qt 5.14.1 / PyQt 5.14.1 / SIP 6.1.0.dev2104271705
Torrent: 1.2.14.0
{'debug': False, 'disable-gpu': True, 'no-browser': False, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': False, 'experimental': False, 'auto-scale': False, 'scale': 1, 'round-menu': True}

C:\Users\ADMINI~1\AppData\Local\Temp
C:\Users\administer\Desktop\Univ\별자리운세\양식\별자리\miothi\imotih2
[strip path] %TEMP%

winId: 2426540
handle: <PyQt.QtGui.QWindow object at 0x000001C1ACE8D558>
Supported Image Formats: [b'bmp', b'pbm', b'pgm', b'png', b'ppm', b'xbm', b'xpm']
v3.7d (latest: v3.7d)
Encodings: ['cp949', 'utf-8', 'ascii', 'utf-8', 'utf-8']
download yt_dlp
Saved: exists
yt-dlp-2021.12.1.tar.gz#sha256=58da5b96d4834fe8130c960b9dfd670cd2d0e53b650cd92e5c4381724151b80f
[append_datas] size: 135, elapsed time: 0.1635890007019043
db: True
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9133, in <module>
  File "hitomi_server\__init__", line 385, in start
  File "hitomi_server\__init__", line 346, in join
  File "hitomi_server\__init__", line 339, in run
  File "<decorator-gen-114>", line 2, in switch
  File "locker", line 71, in _wrapper
  File "hitomi_server\__init__", line 368, in switch
  File "hitomi_server\__init__", line 361, in switch
  File "hitomi_server\__init__", line 102, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 139, in server_bind
  File "socket", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte


Styles:
    windowsvista
    Windows
    Fusion

import youtube-dl
youtube-dl version: 2021.12.01

**Comment by KurtBestor** [comment]
`cmd` 에서 다음과 같이 입력하고 <kbd>Enter</kbd> 눌러서 나온 내용 보여주세요:
```
hostname
```

**Comment by hyggelovent** [comment]
> 

일신A

입니다

**Comment by KurtBestor** [comment]
컴퓨터 이름을 한글이 들어가지 않게 바꿔주세요
