### ISSUE TITLE
며칠전부터 av쏘걸 다운이 안대요.

### ISSUE THREAD

**Issue by jajajajo3** [KurtBestor/Hitomi-Downloader#4149]
이렇게뜨면서 안대네요.
바뀐주소로 직접 수정해서 한동안은 댓엇는데 최근엔 안대네요.

10분 0초 뒤 다시 시작: https://kr29.sogirl.so/abw-179-%ec%8a%a4%ec%a6%88%eb%aa%a8%eb%a6%ac-%eb%a0%88%eb%ac%b4-hd/

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a2aaa5b1cfb441909905a3c0b442c148
input: https://kr29.sogirl.so/abw-179-%ec%8a%a4%ec%a6%88%eb%aa%a8%eb%a6%ac-%eb%a0%88%eb%ac%b4-hd/
type: sogirl
single: True
url: https://kr29.sogirl.so/abw-179-%ec%8a%a4%ec%a6%88%eb%aa%a8%eb%a6%ac-%eb%a0%88%eb%ac%b4-hd/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639583903.9138935 (12월 16일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://kr29.sogirl.so/abw-179-%EC%8A%A4%EC%A6%88%EB%AA%A8%EB%A6%AC-%EB%A0%88%EB%AC%B4-hd/
stop
Traceback (most recent call last):
 File "downloader", line 388, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "dynamic_module_0", line 18, in read
 File "downloader", line 316, in read_soup
 File "downloader", line 421, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://kr29.sogirl.so/abw-179-%EC%8A%A4%EC%A6%88%EB%AA%A8%EB%A6%AC-%EB%A0%88%EB%AC%B4-hd/

Invalid: fail=True
EOT: https://kr29.sogirl.so/abw-179-%ec%8a%a4%ec%a6%88%eb%aa%a8%eb%a6%ac-%eb%a0%88%eb%ac%b4-hd/  (2.2s)

**Comment by ppadamayo** [comment]
누가 쏘걸 스크립트좀 업데이트 해주시면 저같은 컴맹이 대단히 감사드리겠습니다 ㅠ

**Comment by hjsg1010** [comment]
저도 스크립트 부탁드립니다..ㅜㅜ
