### ISSUE TITLE
히토미 다운이 안 됩니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#4150]
히토미 다운이 안 됩니다
아예 빨간색으로 안 된다는 경우도 있고
중간까지 다운 받다가 안 되는 경우도 있습니다

작업 정보입니다

Invalid: [hitomi] #-*- [Ranyues] Princess and wizard ／ 공주와 마법사 2.5화 (2083517)

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.17134-SP0 / ko
order / group / uid: 16 / False / eabee985c8c0406283b2787a25302d5e
input: [Ranyues] Princess and wizard ／ 공주와 마법사 2.5화 (2083517)
type: hitomi
single: False
url: 2083517
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639613636.9399781 (12월 16일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: False

[Gallery]
갤러리 넘버: 2083517

제목: Princess and wizard ／ 공주와 마법사 2.5화

작가: ranyues

그룹: N/A

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: female:loli, female:piercing

언어: Korean

[File Names]

[URLs]

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:2083517)
Find_ehen(id:2083517, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: ehen
ehen_imgs(ex:True, url:2083517)
Find_ehen(id:2083517, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:2083517)
Find_ehen(id:2083517, ex:False)
Find in HK...
not found in HK
get_imgs server: ehen
ehen_imgs(ex:True, url:2083517)
Find_ehen(id:2083517, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 631, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 633, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=True
stop
quality: 75%
EOT: #-*- [Ranyues] Princess and wizard ／ 공주와 마법사 2.5화 (2083517)  (11.3s)

get_imgs server: ehen
ehen_imgs(ex:False, url:2083517)
Find_ehen(id:2083517, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: ehen
ehen_imgs(ex:True, url:2083517)
Find_ehen(id:2083517, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 582, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:2083517)
Find_ehen(id:2083517, ex:False)
Find in HK...
not found in HK
get_imgs server: ehen
ehen_imgs(ex:True, url:2083517)
Find_ehen(id:2083517, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 631, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 633, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=True
stop
quality: 75%
EOT: #-*- [Ranyues] Princess and wizard ／ 공주와 마법사 2.5화 (2083517)  (11.7s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:2083517)
Find_ehen(id:2083517, ex:False)
Find in HK...
not found in HK
max_page = 31983
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.1
BFS: 8.1
BFS: 9.2
BFS: 10.2
BFS: 11.3
BFS: 12.4
BFS: 13.4
BFS: 14.4
BFS: 15.6
BFS: 16.6
BFS: 18.1
BFS: 19.4
BFS: 21.0
BFS: 23.4
BFS: 66.0
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:2083517)
Find_ehen(id:2083517, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 631, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 633, in read
 File "hitomi_downloader", line 459, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=True
stop
quality: 75%
EOT: #-*- [Ranyues] Princess and wizard ／ 공주와 마법사 2.5화 (2083517)  (36.1s)

**Comment by Drillmurata** [comment]
같은 증상이라 재시작 해보니 일단 완료는 됩니다. 다만 압축 파일명이 이중으로 생성되네요
