### ISSUE TITLE
히토미 다운이 안되네요

### ISSUE THREAD

**Issue by Re0Ma** [KurtBestor/Hitomi-Downloader#4152]
올려주신 테스트 버전이었고, 익헨으로 변경되거나 다운이 안되네요

Invalid: [hitomi] https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html

version: 3.7d (21-12-12 19:40:07 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / f8e12d3c0e6e46c694cabf2894a1b4b6
input: https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html
type: hitomi
single: False
url: https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639703480.2241702 (12월 17일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:False)
Find in HK...
Found in HK: 13a8fbccb8
#### https://e-hentai.org/g/1332035/13a8fbccb8    ---->    https://e-hentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 380, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 135, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 407, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 184, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:True)
Find in HK...
Found in HK: 13a8fbccb8
#### https://exhentai.org/g/1332035/13a8fbccb8    ---->    https://exhentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 380, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 135, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 407, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 184, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:False)
Find in HK...
Found in HK: 13a8fbccb8
#### https://e-hentai.org/g/1332035/13a8fbccb8    ---->    https://e-hentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:True)
Find in HK...
Found in HK: 13a8fbccb8
#### https://exhentai.org/g/1332035/13a8fbccb8    ---->    https://exhentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:False)
Find in HK...
Found in HK: 13a8fbccb8
#### https://e-hentai.org/g/1332035/13a8fbccb8    ---->    https://e-hentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:True)
Find in HK...
Found in HK: 13a8fbccb8
#### https://exhentai.org/g/1332035/13a8fbccb8    ---->    https://exhentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 155, in pop_img
 File "hitomi", line 119, in url_from_url_from_hash
 File "hitomi", line 100, in url_from_url
 File "hitomi", line 44, in subdomain_from_url
 File "js2py\base", line 1203, in __call__
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 16, in PyJsHoisted_subdomain_from_url_
 File "js2py\base", line 996, in callprop
 File "js2py\base", line 1464, in call
 File "<EvalJS snippet>", line 168, in PyJs_anonymous_0_
 File "js2py\base", line 995, in callprop
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function (tried calling property 'padStart' of 'String')

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html)
Find_ehen(id:1332035, ex:False)
Find in HK...
Found in HK: 13a8fbccb8
#### https://e-hentai.org/g/1332035/13a8fbccb8    ---->    https://e-hentai.org/g/1332035/13a8fbccb8
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 643, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://hitomi.la/gamecg/kyonyuu-elf-oyako-saimin--hai......-ningen-sama-no-ochinpo-o-oyako-de-shabusarete-itadakimasu......--1332035.html  (45.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by dldydgksp** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘 되네요 감사합니다

**Comment by Re0Ma** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘 됩니다, 감사합니다

**Comment by q2343454** [comment]
일단 잘 되는 것 같습니다 감사드립니다
