### ISSUE TITLE
도쿄모션 private 영상은 다운로드 안되나요??

### ISSUE THREAD

**Issue by eracoon** [KurtBestor/Hitomi-Downloader#4154]
안되네요.. ㅠㅠ

작업정보입니다. 

Invalid: [tokyomotion] https://www.tokyomotion.net/video/1230985/%E9%9C%B2%E5%87%BA-%E7%BE%9E%E6%81%A5-%E7%AC%B9%E5%8E%9F%E3%83%9F%E3%82%AF-%EF%BC%91

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / f3c34ab9191a4ec9b9a09a7b33e1b4ba
input: https://www.tokyomotion.net/video/1230985/%E9%9C%B2%E5%87%BA-%E7%BE%9E%E6%81%A5-%E7%AC%B9%E5%8E%9F%E3%83%9F%E3%82%AF-%EF%BC%91
type: tokyomotion
single: True
url: https://www.tokyomotion.net/video/1230985/%E9%9C%B2%E5%87%BA-%E7%BE%9E%E6%81%A5-%E7%AC%B9%E5%8E%9F%E3%83%9F%E3%82%AF-%EF%BC%91
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639726276.3143203 (12월 17일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\tokyomotion_downloader", line 34, in read
 File "extractor\tokyomotion_downloader", line 71, in get_video
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.tokyomotion.net/video/1230985/%E9%9C%B2%E5%87%BA-%E7%BE%9E%E6%81%A5-%E7%AC%B9%E5%8E%9F%E3%83%9F%E3%82%AF-%EF%BC%91  (4.0s)

**Comment by FrostJackk** [comment]
Hi is it available until now??
i logged on tokyomotion and downloaed cookie and loaded that file in the program but same result

**Comment by dino1234500** [comment]
도쿄모션 다운로드 어떻게 하셨나요? 전 invaild 뜨면서 막힘니다..

**Comment by akkim-1122** [comment]
How to download a private video.
1) tokyomotion sign up for a site.
2) tokyomotion login.
3) Become friends with the owner of the private video and obtain permission to view the video.
4) chrome extension install Get cookies.txt and Export All Cookies -> Automatic download cookies.txt your download folder 
5) hitomi downloader application start.
6) perferences - Network - cookies - load - cookies.txt select.
7) private video URL Enter.
8) download success.

**Comment by walkers7622** [comment]
이거 작동 안되던데 다시 확인 가능할까요?
