### ISSUE TITLE
danbooru 단부루사이트 다운로드가 되지않습니다.

### ISSUE THREAD

**Issue by bbggmm** [KurtBestor/Hitomi-Downloader#4160]
Invalid: [danbooru] https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / f19e2004d3204d75aad760bcb59079b9
input: https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week
type: danbooru
single: False
url: https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1639906160.6434007 (12월 19일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week&page=1
'data-file-url'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 132, in get_imgs
KeyError: 'data-file-url'

Invalid: fail=True
EOT: https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week  (1.4s)

https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week&page=1
'data-file-url'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 132, in get_imgs
KeyError: 'data-file-url'

Invalid: fail=True
EOT: https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week  (1.4s)

https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week&page=1
'data-file-url'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 132, in get_imgs
KeyError: 'data-file-url'

Invalid: fail=True
EOT: https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week  (1.8s)

https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week&page=1
'data-file-url'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 132, in get_imgs
KeyError: 'data-file-url'

Invalid: fail=True
EOT: https://danbooru.donmai.us/explore/posts/popular?date=2021-12-19&scale=week  (1.5s)

**Comment by D41G0** [comment]
I have the same problem with danbooru since Saturday. I thought it was something fleeting and when I tried it today I got the same result.


version: 3.3b (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / pt
order / group / uid: 5 / False / 108e098f4e224ea4bfaecf6f734242af
input: https://danbooru.donmai.us/posts?d=1&tags=order%3Arank
type: danbooru
single: False
url: https://danbooru.donmai.us/posts?d=1&tags=order%3Arank
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~ 300 / None
time: 1638727186.6475942 (Dec 5)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None



[URLs]



[Messages]
https://danbooru.donmai.us/posts?d=1&tags=order%3Arank&page=1
'data-file-url'
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 132, in get_imgs
KeyError: 'data-file-url'

Invalid: fail=True
invalid; revert
EOT: https://danbooru.donmai.us/posts?d=1&tags=order%3Arank  (1.7s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
