### ISSUE TITLE
avsogirl 특정 영상 다운 안됨

### ISSUE THREAD

**Issue by hjsg1010** [KurtBestor/Hitomi-Downloader#4182]
안녕하세요

스크립트 수정해서 sogirl 영상 잘 받고 있는데

특정 영상은 다운이 안됩니다.

로그 첨부합니다

Invalid: [sogirl] https://kr29.sogirl.so/mide-991-%ec%95%bc%ea%b8%b0-%eb%82%98%eb%82%98-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/

version: 3.7d (21-12-17 02:28:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 5a652510795246ae912d60bc4ed92513
input: https://kr29.sogirl.so/mide-991-%ec%95%bc%ea%b8%b0-%eb%82%98%eb%82%98-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/
type: sogirl
single: True
url: https://kr29.sogirl.so/mide-991-%ec%95%bc%ea%b8%b0-%eb%82%98%eb%82%98-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1640320884.0536466 (12월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "dynamic_module_0", line 24, in read
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kr29.sogirl.so/mide-991-%ec%95%bc%ea%b8%b0-%eb%82%98%eb%82%98-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89-hd/  (1.5s)

**Comment by helpmepls08** [comment]
스크립트 변경하려면 전문지식 있어야 하나요? 봐도 모르겠더라고요. 저도 소걸 넣고 싶어요.
