### ISSUE TITLE
트위터 일부 영상이 안 받아지는 문제

### ISSUE THREAD

**Issue by hehrjrvs** [KurtBestor/Hitomi-Downloader#4185]
https://twitter.com/sirosiro_kuro14
해당유저 게시물들을 다운로더로 받고 있는데
일부 영상이 받아지지 않는 현상이 발생
트위터 오류로 영상이 안 나오는가 싶었더니 주소를 찾아서 들어가 보니까 영상은 제대로 나오는 상황입니다
https://twitter.com/sirosiro_kuro14/status/1271081109636300800
https://twitter.com/sirosiro_kuro14/status/1270670663229952000
https://twitter.com/sirosiro_kuro14/status/1270005874086432768
안 나오는 영상들 중 일부

つくねみ (@sirosiro_kuro14)

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / e386a50ec06845f7afd2a7e11374f087
input: https://twitter.com/sirosiro_kuro14/status/1271081109636300800
type: twitter
single: False
url: https://twitter.com/sirosiro_kuro14/status/1271081109636300800
dir: hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)
zip: 
artist: つくねみ
valid / done: False / True
range / range_p: ~100000 / None
time: 1640356678.6642177 (12월 24일)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4

[URLs]
[0001] LazyUrl_twitter(https://twitter.com/sirosiro_kuro14/status/1271081109636300800)    --->    https://video.twimg.com/ext_tw_video/1271080667988647936/pu/vid/1280x720/fGaDeyo3Cig8h4kl.mp4?tag=10

[Messages]
single tweet
[twitter] 1271081109636300800: Downloading guest token
[twitter] 1271081109636300800: Downloading JSON metadata
[twitter] 1271081109636300800: Downloading m3u8 information
270 m3u8_native - https://video.twimg.com/ext_tw_video/1271080667988647936/pu/pl/480x270/mfOmAwrx9XWiIlno.m3u8
270 https - https://video.twimg.com/ext_tw_video/1271080667988647936/pu/vid/480x270/ZitZq-mJVdURsQDg.mp4?tag=10
360 m3u8_native - https://video.twimg.com/ext_tw_video/1271080667988647936/pu/pl/640x360/p4ZqXTjiRHaX9VHc.m3u8
360 https - https://video.twimg.com/ext_tw_video/1271080667988647936/pu/vid/640x360/7QNX4p-PrazoIPBl.mp4?tag=10
720 m3u8_native - https://video.twimg.com/ext_tw_video/1271080667988647936/pu/pl/1280x720/rr-K41cljph81YVV.m3u8
720 https - https://video.twimg.com/ext_tw_video/1271080667988647936/pu/vid/1280x720/fGaDeyo3Cig8h4kl.mp4?tag=10
get_video: https://video.twimg.com/ext_tw_video/1271080667988647936/pu/vid/1280x720/fGaDeyo3Cig8h4kl.mp4?tag=10 .mp4

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (1)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (2)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (3)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (4)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (5)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (6)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (7)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (8)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (9)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (10)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (11)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (12)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (13)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (14)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (15)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (16)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (17)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (18)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (19)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (20)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (21)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (22)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

retry (23)

Fail : \\?\D:\pixiv-수정본\hitomi_downloaded_twitter\つくねみ (@sirosiro_kuro14)\[20-06-11] 1271081109636300800_p0.mp4
Traceback (most recent call last):
 File "downloader", line 1086, in download
OSError: Size = 0

stop
valid=False 1
EOT: https://twitter.com/sirosiro_kuro14/status/1271081109636300800  (38.4s)

트위터 전체 작업정보를 올리려 했으나 내용이 너무 많아 글 업로드가 안 되길래
https://twitter.com/sirosiro_kuro14/status/1271081109636300800
이거 하나만 돌린 걸 올립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hehrjrvs** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

제대로 다운받아집니다 감사합니다
