### ISSUE TITLE
트위치 전체클립 다운 불가

### ISSUE THREAD

**Issue by heonchul** [KurtBestor/Hitomi-Downloader#4191]
Twitch 클립을 개별로는 다운이 가능하나, 전체클립(기간 포함) 다운이 안됩니다.
빨갛게 Invaild 에러가 납니다.

Invalid: [twitch] https://www.twitch.tv/pjs9073/clips?filter=clips&range=30d

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 97653b1cbf82449cac1274811184204f
input: https://www.twitch.tv/pjs9073/clips?filter=clips&range=30d
type: twitch
single: True
url: https://www.twitch.tv/pjs9073/clips?filter=clips&range=30d
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1640419127.4051123 (12월 25일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.25
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
0
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\twitch_downloader", line 56, in read
 File "<decorator-gen-55>", line 2, in get_videos
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "extractor\twitch_downloader", line 95, in get_videos
KeyError: 0

Invalid: fail=True
EOT: https://www.twitch.tv/pjs9073/clips?filter=clips&range=30d  (1.8s)

0
stop
Traceback (most recent call last):
 File "utils", line 1154, in start
 File "utils", line 1224, in start_
 File "extractor\twitch_downloader", line 56, in read
 File "<decorator-gen-55>", line 2, in get_videos
 File "constants", line 922, in wrapper
 File "constants", line 893, in wrapper
 File "extractor\twitch_downloader", line 95, in get_videos
KeyError: 0

Invalid: fail=True
EOT: https://www.twitch.tv/pjs9073/clips?filter=clips&range=30d  (1.7s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by heonchul** [comment]
감사합니다. 잘 작동되네요
