### ISSUE TITLE
마나모아 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by Mango202** [KurtBestor/Hitomi-Downloader#4196]
Invalid: [manatoki] https://manatoki118.net/comic/1020494

version: 3.7d (21-12-17 02:28:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 13 / False / f823190caed54f358dad6ebd4a055a5a
input: https://manatoki118.net/comic/1020494
type: manatoki
single: False
url: https://manatoki118.net/comic/1020494
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1640600902.3243911 (12월 27일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1141, in start
 File "<decorator-gen-89>", line 2, in init
 File "constants", line 924, in wrapper
 File "constants", line 895, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 562, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki118.net/comic/1020494  (28.4s)

Invalid: [manatoki] https://manatoki118.net/comic/146497

version: 3.7d (21-12-17 02:28:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 15 / False / 574f2f97ca2d49a592bb4e7eb1226348
input: https://manatoki118.net/comic/146497
type: manatoki
single: False
url: https://manatoki118.net/comic/146497
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1640600902.2914567 (12월 27일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1141, in start
 File "<decorator-gen-89>", line 2, in init
 File "constants", line 924, in wrapper
 File "constants", line 895, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 562, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki118.net/comic/146497  (68.4s)

한 10개 정도 페이지 시도해봤는데 전부 다 다운로드가 안 됩니다

**Comment by zema67** [comment]
저도 하나 받을려는 데 다운이 안되면서 기간벤을 먹이더군요;

**Comment by woojien** [comment]
저도 다운로드가 안되어서 새로고침 했더니 [귀하는 240시간동안 접근 불가합니다. (2022-01-06 18:52:13 이후 접근 가능)]라는 메시지가 떴어요. 방법이 없을까요?

**Comment by dlandnjs18** [comment]
공유기 사용중이시면 맥주소변경으로 사이트 접근은 되는데......
다운로드하면 다시 밴처리하는거 같네요

**Comment by KurtBestor** [comment]
User agent 확인해서 Qt 기반 브라우저면 바로 밴 하네요. 모든 Qt 기반 브라우저 유저를 밴하려는 건지..

일단 Qt 기반 브라우저로 보이지 않게 수정했어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

차단된 분은 IP 바꿔서 시도해주세요.

**Comment by zema67** [comment]
vpn을 키고 해봤는데 다운로드는 되지가 않네요.. 다른 분들 중 되시는분 계시나요?

**Comment by nightow** [comment]
잘 됩니다.
vpn사용하실때 ip바뀐거 맞는지 확인하세요.
softether는 문제있는지 ip안바뀝니다.

**Comment by fade-out-0770** [comment]
vpn켜니까 잘되네요. 그림도 잘그리시고 파이선도 잘하시고... 대단하심. 부럽습니다.

**Comment by geniussjt** [comment]
벤 당해서 vpn 설치하고 켜는데요 사이트는 접근은 되는데... 다운은 안됩니다ㅠㅠ

**Comment by 666hyun** [comment]
저도 다운 시도하면 바로 밴 먹었었는데(MAC주소 바꿔가며 3번 시도해봄)
지금은 MAC 주소 바꾸고 테스트판으로 사이트 접속, 다운로드 문제 없이 다 잘 됩니다.

**Comment by helpmepls08** [comment]
> vpn 켤 수 있습니다. 그림도 잘그리드 파이선도 잘... 부럽습니다.

개발자님 그림도 그리세여ㅛ?
