### ISSUE TITLE
3.7e 업데이트 이후 히토미 다운로드가 불가능합니다

### ISSUE THREAD

**Issue by naturegreen42** [KurtBestor/Hitomi-Downloader#4214]
다운로드 시 404 에러가 발생하며 다회의 재시도 후 다운로딩을 마치지 못한 채 끝납니다.
이름과 페이지 수 같은 갤러리 정보는 리스트엔 출력되나 단 한 장도 다운로드 하지 못하며,
다수의 갤러리를 다운받는 도중 위의 상황이 발생하여 리스트에서 삭제할 경우 프로그램이 과부하가 걸리는 상황도 발생했습니다.

**Comment by Drillmurata** [comment]
저도 업데이트 후 다운로드 완료가 안되서 v3.7d로 롤백하니 다시 되네요.

**Comment by 123cmdcmd** [comment]
저도 익헨 작품은 받아지는데 히토미는 다운이 시작되질 않네요.

**Comment by Shrimpizza** [comment]
저도 히토미 다운로드가 안되네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Shrimpizza** [comment]
잘되네요

2021년 12월 29일 (수) 12:12, Kurt Bestor ***@***.***>님이 작성:

**Comment by Lunartic85** [comment]
dir: 
zip: 
artist: ruschuto
valid / done: False / True
range / range_p: None / None
time: 1640763848.7511132 (12월 29일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True


[Gallery]
갤러리 넘버: 1895737

제목: TSURU-NO-RAN｜학의 난

작가: ruschuto

그룹: r.i.s factory

타입: doujinshi

시리즈: kantai collection

캐릭터: shoukaku, teitoku, zuikaku

태그: female:big areolae, female:big breasts, female:ponytail, female:small breasts, female:twintails, ffm threesome, full color, group, male:dark skin, male:sole male

언어: Korean


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 17
get_title__

'Image' object has no attribute 'filename'
stop
Traceback (most recent call last):
 File "utils", line 1172, in start
 File "utils", line 1242, in start_
 File "hitomi_downloader", line 699, in read
AttributeError: 'Image' object has no attribute 'filename'

Invalid: fail=True
EOT: https://hitomi.la/doujinshi/tsuru-no-ran%EF%BD%9C%ED%95%99%EC%9D%98-%EB%82%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1895737.html  (4.3s)

루프는 돌지 않지만 그대로 에러상태로 넘어가네요

**Comment by naturegreen42** [comment]
잘 작동합니다 감사합니다

**Comment by KurtBestor** [comment]
@Lunartic85 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Lunartic85** [comment]
> @Lunartic85 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

해결되었습니다. 감사합니다.

**Comment by ssdfg234** [comment]
> @Lunartic85 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

혹시 틱톡도 해결해주실수 있나요.. 안되네요..

**Comment by zxcvbmm** [comment]
3.7e 버전이 히토미는 다운이 안되고, 익헨으로 바뀌면서 다운로드가 되네요
