### ISSUE TITLE
hitomi.la 무한롣잉 걸립니다.

### ISSUE THREAD

**Issue by GH6** [KurtBestor/Hitomi-Downloader#4216]
분명 page는 있습니다만, 파일이 안 받아집니다.
아래는 작업정보입니다.

3.7e 버전이고
모든 hitomi.la 페이지에서 그렇슴.
[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)

version: 3.7e (21-12-27 16:14:26 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / fcf2043a308a4ea19d5011bab69af0b7
input: https://exhentai.org/g/1424466/70a2c9f8d3/
type: hitomi
single: False
url: https://hitomi.la/doujinshi/kagai-jugyou-sakuya-hen-|-과외수업-사쿠야편-한국어-1424466.html
dir: hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)
zip: 
artist: fukuyama naoto
valid / done: True / False
range / range_p: None / None
time: 1640741058.4131932 (12월 29일)
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: False

[Gallery]
갤러리 넘버: 1424466

제목: Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편

작가: fukuyama naoto

그룹: akausagi

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: female:ahegao, female:clit growth, female:sole female, female:sweating

언어: Korean

[File Names]
[0001] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00066.jpg
[0002] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00067.jpg
[0003] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00068.jpg
[0004] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00069.jpg
[0005] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00070.jpg
[0006] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00071.jpg
[0007] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00072.jpg
[0008] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00073.jpg
[0009] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00074.jpg
[0010] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00075.jpg
[0011] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00076.jpg
[0012] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00077.jpg
[0013] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00078.jpg
[0014] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00079.jpg
[0015] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00080.jpg
[0016] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00081.jpg
[0017] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00082.jpg
[0018] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00083.jpg
[0019] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00084.jpg
[0020] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00085.jpg
[0021] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00086.jpg
[0022] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00087.jpg
[0023] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00088.jpg
[0024] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00089.jpg
[0025] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00090.jpg
[0026] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00091.jpg
[0027] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00092.jpg
[0028] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00093.jpg
[0029] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00094.jpg
[0030] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00095.jpg
[0031] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00096.jpg
[0032] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00097.jpg
[0033] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00098.jpg
[0034] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00099.jpg
[0035] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00100.jpg
[0036] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00101.jpg
[0037] hitomi_download_일반\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00102.jpg

[URLs]
[0001] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg
[0002] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg
[0003] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://bb.hitomi.la/images/a/65/47866a9851f0043f1187baa304ebdd55fd1b3cd3ebc44e4dd344e6307233365a.jpg
[0004] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://ab.hitomi.la/images/4/7e/88606f6d11d09ba7f61487144a03c81d4983a36b4077f9567a52f954fcf067e4.jpg
[0005] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg
[0006] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://bb.hitomi.la/images/c/2d/7809e83b2632a24afa871845b5a3381a26fe9627a3d76adb41312d32a6a712dc.jpg
[0007] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)    --->    https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg
[0008] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0009] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0010] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0011] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0012] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0013] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0014] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0015] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0016] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0017] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0018] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0019] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0020] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0021] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0022] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0023] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0024] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0025] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0026] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0027] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0028] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0029] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0030] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0031] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0032] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0033] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0034] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0035] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0036] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)
[0037] LazyUrl_hitomi(https://hitomi.la/reader/1424466.html)

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 37
get_title__

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00067.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00068.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00072.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00070.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)
use alternative url: https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg --> https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00067.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (2)
use alternative url: https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg --> https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00067.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (3)
use alternative url: https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg --> https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00072.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (2)
use alternative url: https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg --> https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00072.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (3)

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00066.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)
use alternative url: https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg --> https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00070.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (2)
use alternative url: https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg --> https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00070.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (3)
use alternative url: https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg --> https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00066.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (2)
use alternative url: https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg --> https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00066.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (3)
use alternative url: https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg --> https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00070.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (4)
use alternative url: https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg --> https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00067.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (4)
use alternative url: https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg --> https://ab.hitomi.la/images/1/b0/d0afa24a2d58033ec8d8fa6f965453298127d3eac8336a55cffc31010c790b01.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00070.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (5)
use alternative url: https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg --> https://bb.hitomi.la/images/6/17/03f81c7d3af53e7b2f971530490c4501164eaa601ff9b794e17a257710b77176.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00072.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (4)
use alternative url: https://bb.hitomi.la/images/a/65/47866a9851f0043f1187baa304ebdd55fd1b3cd3ebc44e4dd344e6307233365a.jpg --> https://bb.hitomi.la/images/a/65/47866a9851f0043f1187baa304ebdd55fd1b3cd3ebc44e4dd344e6307233365a.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00068.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (2)

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00071.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00069.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (1)
use alternative url: https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg --> https://ab.hitomi.la/images/f/eb/eea03c0f7fe1f2c3c3c91206f052ac17ea1e7b979624dcbb55da8246a85c8ebf.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00067.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (5)
use alternative url: https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg --> https://bb.hitomi.la/images/8/1c/5995dbfd29d807e76874483fec40669ff21c76699c9560ac636788379eb651c8.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00066.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (4)
use alternative url: https://ab.hitomi.la/images/4/7e/88606f6d11d09ba7f61487144a03c81d4983a36b4077f9567a52f954fcf067e4.jpg --> https://ab.hitomi.la/images/4/7e/88606f6d11d09ba7f61487144a03c81d4983a36b4077f9567a52f954fcf067e4.jpg

Fail_404 : \\?\개인정보검열\[Fukuyama Naoto] Kagai Jugyou Sakuya Hen ｜ 과외수업 사쿠야편 (1424466)\00069.jpg
Traceback (most recent call last):
 File "downloader", line 960, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

retry (2)
use alternative url: https://bb.hitomi.la/images/c/2d/7809e83b2632a24afa871845b5a3381a26fe9627a3d76adb41312d32a6a712dc.jpg --> https://bb.hitomi.la/images/c/2d/7809e83b2632a24afa871845b5a3381a26fe9627a3d76adb41312d32a6a712dc.jpg

**Comment by GH6** [comment]
다시 잘 작동하네여. 사이트 문젠가..
