### ISSUE TITLE
현재 히토미 루트는 완전 먹통입니다

### ISSUE THREAD

**Issue by myayusyo** [KurtBestor/Hitomi-Downloader#4218]
아래 글에서 테스트 해달라며 올려주신 버전으로 진행했습니다.

현재 검색기 혹은 히토미 링크로 다운로드를 시도하면 바로 다운로드 실패 상태가 됩니다.

기존에 다운 받았던 파일이나, 이헨쪽의 동일한 파일을 히토미 링크로 재 다운로드를 했을 경우에도 별다른 검색 시간 들이지 않고 바로 '다시 시작 실패: 복구됨' 상태가 됩니다.

**＊히토미 링크 사용시 다운로드 실패**

Invalid: [hitomi] #-*- [Kyaradain] ふたりの身体のなん％かはザーメンで出来ている (2097531)

version: 3.7e (21-12-29 03:56:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 6 / False / 6a16f16e12444c8d9fd55320195b86d5
input: [Kyaradain] ふたりの身体のなん％かはザーメンで出来ている (2097531)
type: hitomi
single: False
url: https://hitomi.la/galleries/2097531.html
dir: 
zip: 
artist: kyaradain
valid / done: False / True
range / range_p: None / None
time: 1640764281.1649454 (12월 29일)
tags: ['red', 'orange', 'yellow']
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 2097531

제목: ふたりの身体のなん％かはザーメンで出来ている

작가: kyaradain

그룹: kyaradain

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: group, mosaic censorship, female:bukkake, female:loli, female:school swimsuit, female:tanlines, female:thick eyebrows, female:twintails, male:bald, male:muscle

언어: Japanese

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 47

'Image' object has no attribute 'filename'
stop
Traceback (most recent call last):
 File "utils", line 1172, in start
 File "utils", line 1242, in start_
 File "hitomi_downloader", line 699, in read
AttributeError: 'Image' object has no attribute 'filename'

Invalid: fail=True
EOT: #-*- [Kyaradain] ふたりの身体のなん％かはザーメンで出来ている (2097531)  (3.1s)

get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 47

'Image' object has no attribute 'filename'
stop
Traceback (most recent call last):
 File "utils", line 1172, in start
 File "utils", line 1242, in start_
 File "hitomi_downloader", line 699, in read
AttributeError: 'Image' object has no attribute 'filename'

Invalid: fail=True
EOT: #-*- [Kyaradain] ふたりの身体のなん％かはザーメンで出来ている (2097531)  (4.1s)

**＊재 다운로드 시도시 '다시 시작 실패: 복구됨' 상태**

[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di

version: 3.7d (21-12-29 03:56:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 63 / False / c64aa76c544c4953941853b7c1d62994
input: [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (2097087)
type: ehen
single: False
url: https://e-hentai.org/g/2097087/1618931c57
dir: K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di
zip: 
artist: morikoke
valid / done: False / True
range / range_p: None / None
time: 1640720296.959039 (12월 29일)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 2097087

제목: [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 | 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Digital]

작가: morikoke

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:big breasts, female:elf, female:lingerie, female:blowjob, male:old man

언어: Korean

[File Names]
[0001] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0000.png
[0002] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0001.png
[0003] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0002.png
[0004] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0003.png
[0005] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0004.png
[0006] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0005.png
[0007] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0006.png
[0008] K:\hitomi_downloader_GUI\hitomi_downloaded\[Morikoke][N／A](2097087)[Korean] [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (COMIC BAVEL 2022-01) [Korean] [Di\0007.png

[URLs]

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 8

'Image' object has no attribute 'filename'
stop
Traceback (most recent call last):
 File "utils", line 1172, in start
 File "utils", line 1242, in start_
 File "hitomi_downloader", line 699, in read
AttributeError: 'Image' object has no attribute 'filename'

Invalid: fail=True
invalid; revert
EOT: #-*- [Morikoke] Chijoku no Mori -Elf Kanraku- ACT.8 ｜ 치욕의 숲 엘프함락 ACT.8 (2097087)  (2.6s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4214#issuecomment-1002456164
