### ISSUE TITLE
익헨 praviet 다운로드 문의

### ISSUE THREAD

**Issue by nakadashi74** [KurtBestor/Hitomi-Downloader#4223]

**Comment by nakadashi74** [comment]
Invalid: [hitomi] https://exhentai.org/g/2093308/4a3b82aa7b/

version: 3.7e (21-12-29 08:20:39 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 339efb44663644c88db9a531185b0cbd
input: https://exhentai.org/g/2093308/4a3b82aa7b/
type: ehen
single: False
url: https://exhentai.org/g/2093308/4a3b82aa7b/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1640871782.1076057 (12월 30일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://e-hentai.org/g/2093308/4a3b82aa7b    ---->    https://e-hentai.org/g/2093308/4a3b82aa7b
MPV: False
get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (1)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (2)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (3)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (4)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (5)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (6)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (7)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (8)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 465, in get_imgs
 File "gallery", line 232, in get_gal_ehen
Exception: Cant get title - ehen (https://e-hentai.org/g/2093308/4a3b82aa7b)
NoneType: None


get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://exhentai.org/g/2093308/4a3b82aa7b    ---->    https://exhentai.org/g/2093308/4a3b82aa7b
MPV: False
get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (1)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (2)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (3)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (4)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (5)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (6)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (7)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://exhentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (8)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 465, in get_imgs
 File "gallery", line 232, in get_gal_ehen
Exception: Cant get title - ehen (https://exhentai.org/g/2093308/4a3b82aa7b)
NoneType: None


get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://e-hentai.org/g/2093308/4a3b82aa7b    ---->    https://e-hentai.org/g/2093308/4a3b82aa7b
MPV: False
get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (1)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (2)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (3)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (4)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (5)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (6)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (7)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (8)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 465, in get_imgs
 File "gallery", line 232, in get_gal_ehen
Exception: Cant get title - ehen (https://e-hentai.org/g/2093308/4a3b82aa7b)
NoneType: None


get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://exhentai.org/g/2093308/4a3b82aa7b    ---->    https://exhentai.org/g/2093308/4a3b82aa7b
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://e-hentai.org/g/2093308/4a3b82aa7b    ---->    https://e-hentai.org/g/2093308/4a3b82aa7b
MPV: False
get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (1)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (2)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (3)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (4)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (5)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (6)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (7)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (8)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 465, in get_imgs
 File "gallery", line 232, in get_gal_ehen
Exception: Cant get title - ehen (https://e-hentai.org/g/2093308/4a3b82aa7b)
NoneType: None


get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://exhentai.org/g/2093308/4a3b82aa7b    ---->    https://exhentai.org/g/2093308/4a3b82aa7b
Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 462, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hitomi.la/galleries/2093308.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi", line 142, in pop_img
 File "gallery", line 392, in get_gallery_url
 File "gallery", line 374, in solve_redirect
 File "downloader", line 424, in read_html
Exception: 404

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2093308.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "hitomi", line 152, in pop_img
 File "hitomi", line 123, in get_data
 File "downloader", line 424, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/2093308/4a3b82aa7b/)
#### https://e-hentai.org/g/2093308/4a3b82aa7b    ---->    https://e-hentai.org/g/2093308/4a3b82aa7b
MPV: False
get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (1)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (2)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (3)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (4)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (5)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (6)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (7)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

get_title_ehen: https://e-hentai.org/g/2093308/4a3b82aa7b
TITLE FAILED : ehen (8)
Traceback (most recent call last):
 File "gallery", line 223, in get_gal_ehen
 File "gallery", line 317, in get_gal__ehen
KeyError: 'onclick'

Traceback (most recent call last):
 File "hitomi_downloader", line 585, in read
 File "hitomi_downloader", line 465, in get_imgs
 File "gallery", line 232, in get_gal_ehen
Exception: Cant get title - ehen (https://e-hentai.org/g/2093308/4a3b82aa7b)
NoneType: None


FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 643, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://exhentai.org/g/2093308/4a3b82aa7b/  (87.9s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by nakadashi74** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘되네염 굿
