### ISSUE TITLE
뉴토끼(마나모아) 다운로드가 여전히 안됩니다.

### ISSUE THREAD

**Issue by inspection96** [KurtBestor/Hitomi-Downloader#4230]
Invalid: [manatoki] https://newtoki118.com/webtoon/18340878/%EA%B9%8C%EC%B9%A0%ED%95%9C-%EC%97%AC%ED%9B%84%EB%B0%B0-%EB%84%A3%EC%96%B4%EC%84%9C-%EC%B2%A0%EB%B2%BD%ED%95%B4%EC%A0%9C

version: 3.7e (21-12-28 14:38:14 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 17ff34bc53b8432b8fc7c8edb54fea78
input: https://newtoki118.com/webtoon/18340878/%EA%B9%8C%EC%B9%A0%ED%95%9C-%EC%97%AC%ED%9B%84%EB%B0%B0-%EB%84%A3%EC%96%B4%EC%84%9C-%EC%B2%A0%EB%B2%BD%ED%95%B4%EC%A0%9C
type: manatoki
single: False
url: https://newtoki118.com/webtoon/18340878/까칠한-여후배-넣어서-철벽해제
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1641015458.1380172 (1월 1일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1141, in start
 File "<decorator-gen-89>", line 2, in init
 File "constants", line 924, in wrapper
 File "constants", line 895, in wrapper
 File "extractor\manatoki_downloader", line 36, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 109, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki118.com/webtoon/18340878/%EA%B9%8C%EC%B9%A0%ED%95%9C-%EC%97%AC%ED%9B%84%EB%B0%B0-%EB%84%A3%EC%96%B4%EC%84%9C-%EC%B2%A0%EB%B2%BD%ED%95%B4%EC%A0%9C  (26.0s)

stop
Traceback (most recent call last):
 File "utils", line 1141, in start
 File "<decorator-gen-89>", line 2, in init
 File "constants", line 924, in wrapper
 File "constants", line 895, in wrapper
 File "extractor\manatoki_downloader", line 36, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 109, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki118.com/webtoon/18340878/%EA%B9%8C%EC%B9%A0%ED%95%9C-%EC%97%AC%ED%9B%84%EB%B0%B0-%EB%84%A3%EC%96%B4%EC%84%9C-%EC%B2%A0%EB%B2%BD%ED%95%B4%EC%A0%9C  (15.6s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1158, in start
 File "<decorator-gen-90>", line 2, in init
 File "constants", line 924, in wrapper
 File "constants", line 895, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 577, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://newtoki118.com/webtoon/18340878/%EA%B9%8C%EC%B9%A0%ED%95%9C-%EC%97%AC%ED%9B%84%EB%B0%B0-%EB%84%A3%EC%96%B4%EC%84%9C-%EC%B2%A0%EB%B2%BD%ED%95%B4%EC%A0%9C  (13.3s)

이전에 올라왔던 사이트 체인지 라벨이 달린 글을 보고, MAC주소도 바꾸고 VPN도 켰지만 사이트 접속도 안되고 다운로드도 되지 않습니다.

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 눌러서 웹브라우저 열고 해당 링크 들어가면 어떻게 뜨나요?

**Comment by inspection96** [comment]
![20220102_135139](https://user-images.githubusercontent.com/69160875/147866577-bc6107cd-888e-4ce3-aba1-8936b9fb3afd.png)

**Comment by KurtBestor** [comment]
일반 브라우저로도 접속 안 되면 IP 변경이 안 된 거예요
