### ISSUE TITLE
Browser required; Use --safemode 라고 뜨면서 다운로드 안 됨

### ISSUE THREAD

**Issue by erobird** [KurtBestor/Hitomi-Downloader#4244]
이게 떠서 자주 묻는 질문에 있는 링크글 참조 해서 해봤는데도 안되네요
뭐를 잘못하고 있는건지 몰라서 질문드립니다
![1](https://user-images.githubusercontent.com/96917644/147868617-c35084d3-86b7-4eba-af4d-7af46eac59b7.jpg)

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by erobird** [comment]
> 어떤 백신 쓰시나요?

따로 쓰는 백신은 없고 윈도우 기본만 쓰고 있습니다

**Comment by KurtBestor** [comment]
프로그램 끈 상태로 `hitomi_downloader_GUI.exe --safemode` 실행한 것 맞나요?

**Comment by erobird** [comment]
> 프로그램 끈 상태로 `hitomi_downloader_GUI.exe --safemode` 실행한 것 맞나요?

아 끄고 해야하는지 몰랐습니다
끄고 하니 자동으로 다운로더가 실해됐습니다
그럼 이거 실행할때마다 디펜더 끄고 cmd로 실행해야 하나요?

**Comment by KurtBestor** [comment]
디펜더에 오진이라고 보고해주시거나 다음 참고해서 예외 등록해주세요: https://support.microsoft.com/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by erobird** [comment]
> 디펜더에 오진이라고 보고해주시거나 다음 참고해서 예외 등록해주세요: https://support.microsoft.com/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

히토미나 히요비는 이제 잘 되는데 뉴토끼는 여전히 저 메세지가 뜹니다
어떻게 해결해야 하나요?

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by erobird** [comment]
> 해당 작업 정보 보여주세요

Browser required; Use --safemode
https://newtoki118.com/webtoon/18589284

version: 3.7e (21-12-27 16:14:26 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / d242640279004f208dae2bba3166f5bf
input: https://newtoki118.com/webtoon/18589284
type: manatoki
single: False
url: https://newtoki118.com/webtoon/18589284
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1641129126.6190789 (1월 2일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1141, in start
 File "<decorator-gen-89>", line 2, in init
 File "constants", line 924, in wrapper
 File "constants", line 895, in wrapper
 File "extractor\manatoki_downloader", line 36, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 109, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki118.com/webtoon/18589284  (10.1s)

**Comment by KurtBestor** [comment]
`hitomi_downloader_GUI.exe --safemode` 로 실행해주세요...

**Comment by erobird** [comment]
> `hitomi_downloader_GUI.exe --safemode` 로 실행해주세요...

뉴토끼는 cmd 통해서 실행시키는 방법 밖에 없는건가요?

**Comment by KurtBestor** [comment]
사용자 이름에 논아스키문자(한글, 한자, 히라가나 등)가 있어서 생기는 문제인데, 바로가기 만들어서 실행하면 편할거예요

**Comment by erobird** [comment]
> 사용자 이름에 논아스키문자(한글, 한자, 히라가나 등)가 있어서 생기는 문제인데, 바로가기 만들어서 실행하면 편할거예요

아하 그렇군요 감사합니다
일단 오늘은 못해서 내일 해보도록 하겠습니다

**Comment by erobird** [comment]
> 사용자 이름에 논아스키문자(한글, 한자, 히라가나 등)가 있어서 생기는 문제인데, 바로가기 만들어서 실행하면 편할거예요

아 혹시 사용자 이름이라는게 맨 위에 올린 사진은 바탕화면에 있는 경로에 있는 걸 말씀하시는건가요?
제 실명 한글로 되있어서 그런데 혹시 다운로더를 한글이 없는 다른 위치로 바꾸면 해결 가능한건가요?
