### ISSUE TITLE
AV쏘걸 Just moment site

### ISSUE THREAD

**Issue by kkomaya** [KurtBestor/Hitomi-Downloader#4261]
AV쏘걸을 접속하면 Ddos 공격 예방 차원인지, 체크하는 사이트 표시가 되고 좀 후에 해당 Main Page로 접속이 됩니다.

그 이유 때문인지 다운로드를 하면 다음과 같은 메시지를 출력하면서 Invalid를 표시 합니다.

Invalid: [sogirl] https://kr30.sogirl.so/518asgm-011/

version: 3.7d (22-01-03 11:24:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 170 / False / 09a43e15923d4e97a78f2b6d2469d8d4
input: https://kr30.sogirl.so/518asgm-011/
type: sogirl
single: True
url: https://kr30.sogirl.so/518asgm-011/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1640564912.4302878 (12월 27일, 2021)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1172, in start
 File "utils", line 1242, in start_
 File "dynamic_module_0", line 20, in read
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://kr30.sogirl.so/518asgm-011/  (1.1s)

내장 웹브라우저로 접속을 했을 경우, 접속은 되지만 동영상은 플레이가 되지 않습니다.

![image](https://user-images.githubusercontent.com/94282707/147988752-6420e8c2-3aae-48fb-a2e7-91828b4ad030.png)

**Comment by fuzzypurge** [comment]
듀플 거신거 보면 해결책이 있다는건데 쏘걸 sogirl 다 검색해봐도 안보이네요ㅠㅠ

**Comment by ppadamayo** [comment]
요즘 쏘걸 다운이 안되서 정말 도움이 간절히 필요합니다..

**Comment by kkomaya** [comment]
그러게요...어떻게 찾아얄지를 모르겠네요~ㅠ
