### ISSUE TITLE
픽시브 북마크 다운 시 계속 쿠키를 업데이트 하라네요

### ISSUE THREAD

**Issue by e233kei** [KurtBestor/Hitomi-Downloader#4292]
픽시브 북마크 다운 받으려고 하는데 계속 오류나네요.

tapioka (pixiv_bmk_12178176)

version: 3.3a (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 51 / False / 7250d40b12bf4dd8aa6b5f9218aade26
input: https://www.pixiv.net/users/12178176/bookmarks/artworks
type: pixiv
single: False
url: https://www.pixiv.net/users/12178176/bookmarks/artworks
dir: hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)
zip: 
artist: None
valid / done: False / True
range / range_p: 500000 / None
time: 1629255874.1922283 (8월 18일, 2021)
tags: ['red']
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {pixiv_tag_cache: {'tags': [], 'tags_ex': []}}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\92065314_p0.jpg
[0002] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\92031060_p0.jpg
[0003] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\92062186_p0.jpg
.
.
.
[20158] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\75119589_p0.png
[20159] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\75442404_p0.jpg
[20160] hitomi_downloaded_pixiv\tapioka (pixiv_bmk_12178176)\73612733_p0.png

[URLs]
[0001] LazyUrl(https://www.pixiv.net/en/artworks/92065314)    --->    https://i.pximg.net/img-original/img/2021/08/18/00/00/08/92065314_p0.jpg
[0002] LazyUrl(https://www.pixiv.net/en/artworks/92031060)    --->    https://i.pximg.net/img-original/img/2021/08/16/17/23/25/92031060_p0.jpg
[0003] LazyUrl(https://www.pixiv.net/en/artworks/92062186)    --->    https://i.pximg.net/img-original/img/2021/08/17/22/11/35/92062186_p0.jpg
.
.
.
[0739] LazyUrl(https://www.pixiv.net/en/artworks/84917950)    --->    https://i.pximg.net/img-zip-ugoira/img/2020/10/10/13/26/12/84917950_ugoira1920x1080.zip
[0740] LazyUrl(https://www.pixiv.net/en/artworks/88440391)    --->    https://i.pximg.net/img-zip-ugoira/img/2021/03/14/14/38/08/88440391_ugoira1920x1080.zip
[0741] LazyUrl(https://www.pixiv.net/en/artworks/89400434)    --->    https://i.pximg.net/img-zip-ugoira/img/2021/04/26/05/45/30/89400434_ugoira1920x1080.zip
[0742] LazyUrl(https://www.pixiv.net/en/artworks/91610754)    --->    【local_lazy】 91610754_p0.png
[0743] LazyUrl(https://www.pixiv.net/en/artworks/91610754)    --->    【local_lazy】 91610754_p1.png
[0744] LazyUrl(https://www.pixiv.net/en/artworks/91535748)    --->    【local_lazy】 91535748_p0.png
.
.
.
[20158] LazyUrl(https://www.pixiv.net/en/artworks/75119589)    --->    【local_lazy】 75119589_p0.png
[20159] LazyUrl(https://www.pixiv.net/en/artworks/75442404)    --->    【local_lazy】 75442404_p0.jpg
[20160] LazyUrl(https://www.pixiv.net/en/artworks/73612733)    --->    【local_lazy】 73612733_p0.png

[Messages]
8 / 32
process_ids error (id: 92065244, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 487, in run
 File "extractor\pixiv_downloader", line 282, in get_info
 File "extractor\pixiv_downloader", line 113, in illust
 File "<decorator-gen-13>", line 2, in call
 File "constants", line 896, in wrapper
 File "constants", line 867, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 106, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (id: 77513507, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 487, in run
 File "extractor\pixiv_downloader", line 282, in get_info
 File "extractor\pixiv_downloader", line 113, in illust
 File "<decorator-gen-13>", line 2, in call
 File "constants", line 896, in wrapper
 File "constants", line 867, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 106, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (id: 91226029, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 487, in run
 File "extractor\pixiv_downloader", line 282, in get_info
 File "extractor\pixiv_downloader", line 113, in illust
 File "<decorator-gen-13>", line 2, in call
 File "constants", line 896, in wrapper
 File "constants", line 867, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 106, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

.
.
.

process_ids error (id: 73667048, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 478, in run
 File "extractor\pixiv_downloader", line 272, in get_info
 File "extractor\pixiv_downloader", line 113, in illust
 File "<decorator-gen-14>", line 2, in call
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 106, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (id: 43038474, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 478, in run
 File "extractor\pixiv_downloader", line 272, in get_info
 File "extractor\pixiv_downloader", line 113, in illust
 File "<decorator-gen-14>", line 2, in call
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 106, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

process_ids error (id: 73164839, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 478, in run
 File "extractor\pixiv_downloader", line 272, in get_info
 File "extractor\pixiv_downloader", line 113, in illust
 File "<decorator-gen-14>", line 2, in call
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 106, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

stop
invalid; revert
EOT: https://www.pixiv.net/users/12178176/bookmarks/artworks  (1271.6s)

**Comment by KurtBestor** [comment]
쿠키 업데이트 해도 안 되나요?

**Comment by e233kei** [comment]
네. 한 번 업데이트 있어서 업데이트까지 해보고 다시 시도했는데도 안됩니다.

**Comment by KurtBestor** [comment]
페이지 지정이 `500000` 으로 되어있네요 이러면 50만 번째 이미지만 다운로드 해요
첫번째부터 50만번째까지 다운로드 하려면 `~500000` 으로 바꿔주세요
