### ISSUE TITLE
FC2 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by Dumbisted** [KurtBestor/Hitomi-Downloader#4297]
Invalid: [fc2] https://video.fc2.com/a/content/20180315VCxyuhwK

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a9a4465a10e14981862b5c171553ed9d
input: https://video.fc2.com/a/content/20180315VCxyuhwK
type: fc2
single: True
url: https://video.fc2.com/a/content/20180315VCxyuhwK
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1642073933.3992145 (1월 13일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
404 Client Error: Not Found for url: https://video.fc2.com/a/err.php?type=1
stop
Traceback (most recent call last):
 File "downloader", line 363, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\fc2_downloader", line 28, in read
 File "extractor\fc2_downloader", line 62, in get_info
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://video.fc2.com/a/err.php?type=1

Invalid: fail=True
EOT: https://video.fc2.com/a/content/20180315VCxyuhwK  (3.0s)

404 Client Error: Not Found for url: https://video.fc2.com/a/err.php?type=1
stop
Traceback (most recent call last):
 File "downloader", line 363, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\fc2_downloader", line 28, in read
 File "extractor\fc2_downloader", line 62, in get_info
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://video.fc2.com/a/err.php?type=1

Invalid: fail=True
EOT: https://video.fc2.com/a/content/20180315VCxyuhwK  (3.2s)

----------------------------------------------------------------------------------------------------------------------------------------

요즘 몇 번 사이트를 뜯어고친거 같더니 다운로드가 되질 않습니다. 

(아마도)자매 사이트인 LAXD는 다운로더에서 지원하지 않네요.

**Comment by KurtBestor** [comment]
삭제된 동영상이네요

**Comment by Dumbisted** [comment]
왠지는 모르겠지만 저에겐 멀쩡히 잘 보입니다. 다운로더에 딱히 FC2 쿠키같은 것도 없는데도요...

**Comment by KurtBestor** [comment]
전체공개가 아닌 영상인가요?

**Comment by Dumbisted** [comment]
아뇨, 비회원으로도 볼 수 있고 全員라고 라벨이 붙어있으니까 전체공개인건 확실해보입니다.  fc2 때에도 그랬구요.

그건 그렇고 로그의 fc2 링크를 클릭해 보니까 계속 LAXD 사이트로 연결되네요.
