### ISSUE TITLE
proxy setting is not working

### ISSUE THREAD

**Issue by netoearth** [KurtBestor/Hitomi-Downloader#4307]
hello，i have a proxy ,and setting it ,bit download it's not working,just display Reding the url ,pls add http proxy and sockt5 proxy Features，thank you!!!

![QQ截图20220115142537](https://user-images.githubusercontent.com/3488120/149611730-32f7a5bd-229e-42fa-bc24-fec6d2a7ead0.png)

**Comment by KurtBestor** [comment]
You can specify the protocol like this:
- Host `socks5://127.0.0.1` &nbsp; &nbsp; &nbsp;Port `9909`
- Host `http://127.0.0.1` &nbsp; &nbsp; &nbsp; &nbsp; Port `9910`

**Comment by netoearth** [comment]
Traceback (most recent call last):
  File "urllib\request", line 1350, in do_open
  File "http\client", line 1277, in request
  File "http\client", line 1323, in _send_request
  File "http\client", line 1272, in endheaders
  File "http\client", line 1032, in _send_output
  File "http\client", line 972, in send
  File "http\client", line 1439, in connect
  File "http\client", line 948, in connect
  File "http\client", line 922, in _tunnel
  File "http\client", line 271, in _read_status
  File "socket", line 589, in readinto
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 381, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 543, in _open
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 1393, in https_open
  File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\contrib\socks", line 99, in _new_conn
  File "socks", line 209, in create_connection
  File "socks", line 199, in create_connection
  File "socks", line 47, in wrapper
  File "socks", line 814, in connect
socks.GeneralProxyError: Socket error: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 309, in connect
  File "urllib3\contrib\socks", line 122, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001E35D88C3C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 449, in send
  File "urllib3\connectionpool", line 727, in urlopen
  File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /KurtBestor/Hitomi-Downloader/master/translation/changelog_en.txt (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001E35D88C3C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2581, in clicked
  File "downloader", line 408, in read_html
  File "requests\sessions", line 555, in get
  File "downloader", line 185, in session_request
  File "requests\sessions", line 542, in request
  File "requests\sessions", line 655, in send
  File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /KurtBestor/Hitomi-Downloader/master/translation/changelog_en.txt (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001E35D88C3C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
