### ISSUE TITLE
틱톡 모바일링크 호환 불가

### ISSUE THREAD

**Issue by heonchul** [KurtBestor/Hitomi-Downloader#4324]
Invalid: [tiktok] https://vt.tiktok.com/ZSeCQwCmG

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / fa22e1c8bd4540d880495af9d36cc4e9
input: https://vt.tiktok.com/ZSeCQwCmG
type: tiktok
single: True
url: https://vt.tiktok.com/ZSeCQwCmG
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1642532293.6763127 (1월 19일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
Traceback (most recent call last):
 File "extractor\tiktok_downloader", line 113, in f
AttributeError: 'NoneType' object has no attribute 'text'

items: 0
empty
not f
Traceback (most recent call last):
 File "extractor\tiktok_downloader", line 113, in f
AttributeError: 'NoneType' object has no attribute 'text'

items: 0
empty
not f
Traceback (most recent call last):
 File "extractor\tiktok_downloader", line 113, in f
AttributeError: 'NoneType' object has no attribute 'text'

items: 0
empty
not f
Traceback (most recent call last):
 File "extractor\tiktok_downloader", line 113, in f
AttributeError: 'NoneType' object has no attribute 'text'

items: 0
empty
not f
Traceback (most recent call last):
 File "extractor\tiktok_downloader", line 113, in f
AttributeError: 'NoneType' object has no attribute 'text'

items: 0
empty
no items
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\tiktok_downloader", line 47, in read
 File "extractor\tiktok_downloader", line 165, in read_channel
Exception: no items

Invalid: fail=True
EOT: https://vt.tiktok.com/ZSeCQwCmG  (93.3s)

위와 같이 '모바일 앱 - 공유 - 주소 복사' 를 통해 얻은 링크는 다운이 안되고 히토미 다운로더 브라우저가 켜집니다.
PC링크로는 잘 작동합니다.
모바일 주소도 바로 다운이 가능하게 만들어주실 수 있나요?
브라우저로 나온 주소는 같은 영상의 pc주소이고, 웹상의 다른 틱톡 온라인 다운로더를 통해도 정상적으로 다운되는 걸 보면 구현은 가능할 듯 합니다.
아니면 브라우저로 나오는 기능이 있는 걸 보니, 다른 사용방법이 있는 건가요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by heonchul** [comment]
잘 해결 되었습니다. 감사합니다.
