### ISSUE TITLE
xwebsite 다운로드가 되질 않습니다

### ISSUE THREAD

**Issue by moonslover** [KurtBestor/Hitomi-Downloader#4325]
다른분들이 이슈에 글올리신걸 보니 뭔가 소스같은것을  같이 올리시던데
뭔가 그런 양식이 있는건지요...
혹시 제가 그런 양식에 맞지 않는 이슈를 작성하였다면 양해 부탁드립니다.
이슈를 어떻게 올리는지 잘몰라서요 ㅠㅠ
혹시 이게 그 소스인건지 모르겠어서 올려 봅니다.

Invalid: [xhamster] https://ko.xhwebsite.com/videos/courtney-eaton-gods-of-egypt-2016-xh4qpxe

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 6ba158c2cae34f4dbf486ea45805f73e
input: https://ko.xhwebsite.com/videos/courtney-eaton-gods-of-egypt-2016-xh4qpxe
type: xhamster
single: True
url: https://ko.xhwebsite.com/videos/courtney-eaton-gods-of-egypt-2016-xh4qpxe
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1642456651.54599 (1월 18일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\xhamster_downloader", line 58, in read
 File "utils", line 781, in __call__
 File "<decorator-gen-64>", line 2, in get
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "extractor\xhamster_downloader", line 76, in get
 File "extractor\xhamster_downloader", line 100, in get_info
 File "downloader", line 408, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 185, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://ko.xhwebsite.com/videos/courtney-eaton-gods-of-egypt-2016-xh4qpxe  (2.2s)

('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\xhamster_downloader", line 58, in read
 File "utils", line 781, in __call__
 File "<decorator-gen-64>", line 2, in get
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "extractor\xhamster_downloader", line 76, in get
 File "extractor\xhamster_downloader", line 100, in get_info
 File "downloader", line 408, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 185, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://ko.xhwebsite.com/videos/courtney-eaton-gods-of-egypt-2016-xh4qpxe  (2.0s)

위 내용을 올리는게 아니라면 죄송합니다 ㅠ

x웹이 며칠전에 막혔다가 다시 풀렸는데 다운로드가 안되서 며칠 기다리다가 여기에 글을 올리게 되었습니다.
개발자님 업데이트 좀 부탁드려도 될까요..

**Comment by KurtBestor** [comment]
관리자 권한으로 실행해서 `DPI 우회` 를 켜세요

**Comment by moonslover** [comment]
아...DPI 우회를 켜야 되는거였군요...이거하면 해킹당하는줄로만 알고 있었던...ㅡㅡ;;; 근데 아니었네요 암것도 모르고...
윈도우에서 시스템 변경을 실행하시겠습니까 만 뜨면 덜컥 겁부터 나서....
암튼 도움 주셔서 감사합니다 운영자님^^ 수고하십시요~~~
