### ISSUE TITLE
http 오류가 뜹니다

### ISSUE THREAD

**Issue by gkdldy2** [KurtBestor/Hitomi-Downloader#4339]
프로그램 실행시 항상 http 서버에 연결할수 없다는 알림이뜹니다
사용에는 지장없는 것 같지만 이유를 알 수있을까요

**Comment by KurtBestor** [comment]
다음 테스트 버전으로 실행해서: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

오류 창 뜨면 `자세한 정보 보기` 눌러서 뜬 내용 보여주세요

**Comment by gkdldy2** [comment]
> 다음 테스트 버전으로 실행해서: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> 오류 창 뜨면 `자세한 정보 보기` 눌러서 뜬 내용 보여주세요

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9136, in <module>
  File "hitomi_server\__init__", line 387, in start
  File "hitomi_server\__init__", line 346, in join
  File "hitomi_server\__init__", line 339, in run
  File "<decorator-gen-120>", line 2, in switch
  File "locker", line 71, in _wrapper
  File "hitomi_server\__init__", line 370, in switch
  File "hitomi_server\__init__", line 362, in switch
  File "hitomi_server\__init__", line 102, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 139, in server_bind
  File "socket", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 0: invalid start byte


이렇게뜨네요ㅜㅜ

**Comment by KurtBestor** [comment]
컴퓨터 이름에 한글이나 기타 특수문자가 들어가지 않게 바꿔주세요

**Comment by gkdldy2** [comment]
> 컴퓨터 이름에 한글이나 기타 특수문자가 들어가지 않게 바꿔주세요

넵 감사합니당 근데 http 오류가 뜨면 사용시 문제가 있을까요?

**Comment by KurtBestor** [comment]
다음 기능 사용이 제한돼요:
- 브라우저로 보기
- HTTP API

**Comment by woojh3690** [comment]
경로가 다 영어인데도 똑같은 에러가 뜨네요.
관리자 권한으로 실행했고, 백신 검사 예외 처리도 했습니다.
버전은 가장 최신 버전인 https://github.com/KurtBestor/Hitomi-Downloader/commit/5f2aa5d26b3886e348bb9029f55fed815f6759f5 사용해서 테스트했습니다.

아래는 자세한 에러 메시지 입니다.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9695, in <module>
  File "hitomi_server\__init__", line 389, in start
  File "hitomi_server\__init__", line 348, in join
  File "hitomi_server\__init__", line 341, in run
  File "decorator", line 232, in fun
  File "locker", line 70, in _wrapper
  File "hitomi_server\__init__", line 372, in switch
  File "hitomi_server\__init__", line 364, in switch
  File "hitomi_server\__init__", line 101, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 139, in server_bind
  File "socket", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

**Comment by KurtBestor** [comment]
경로가 아니라 "컴퓨터 이름" 이에요

**Comment by KurtBestor** [comment]
@woojh3690 경로가 아니라 "컴퓨터 이름" 이에요

**Comment by woojh3690** [comment]
@KurtBestor 헛 그렇군요. 저는 경로에 포함되는 유저 이름인 줄 알았습니다. 지금 확인해보니 에러 없이 잘 되는거 확인하였습니다. 혹시 저는 이제 상관 없지만 추후에라도 영어가 아닌 UTF-8 문자열 이름도 지원가능하게 업데이트하실 계획은 없으신건가요? 지금까지 수정 안 하시는거 보면은 뭔가 이유가 있을 거 같아서 여쭤봅니다.

**Comment by KurtBestor** [comment]
Python 버그예요: https://bugs.python.org/issue26227

**Comment by woojh3690** [comment]
> Python 버그예요: https://bugs.python.org/issue26227

fixed 됐다고 뜨는데 파이썬 버전 업데이트하는게 안되나 보군요.
