### ISSUE TITLE
can't download japanese title

### ISSUE THREAD

**Issue by moeki** [KurtBestor/Hitomi-Downloader#4356]
不能下载日语作品名
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9136, in <module>
  File "hitomi_server\__init__", line 387, in start
  File "hitomi_server\__init__", line 346, in join
  File "hitomi_server\__init__", line 339, in run
  File "<decorator-gen-120>", line 2, in switch
  File "locker", line 71, in _wrapper
  File "hitomi_server\__init__", line 370, in switch
  File "hitomi_server\__init__", line 362, in switch
  File "hitomi_server\__init__", line 102, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 139, in server_bind
  File "socket", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte

**Comment by KurtBestor** [comment]
You may have Non-ASCII characters in your username

**Comment by moeki** [comment]
> 

it worked well until new tech version

**Comment by afterdelight** [comment]
what video are you trying to download, please show the link

**Comment by moeki** [comment]
not video,but the manga of hitomi.la
