### ISSUE TITLE
kemono.party 다운로드가 안 돼요

### ISSUE THREAD

**Issue by kasar24** [KurtBestor/Hitomi-Downloader#4358]
version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 10e9a285e83243efa7baece4f8bbae40
input: https://kemono.party/fanbox/user/3316400
type: kemono.party
single: False
url: https://kemono.party/fanbox/user/3316400
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643023970.0451732 (1월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Not a post
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "dynamic_module_2", line 42, in read
 File "dynamic_module_2", line 59, in read_info
NotImplementedError: Not a post

Invalid: fail=True
EOT: https://kemono.party/fanbox/user/3316400  (0.9s)

Not a post
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "dynamic_module_2", line 42, in read
 File "dynamic_module_2", line 59, in read_info
NotImplementedError: Not a post

Invalid: fail=True
EOT: https://kemono.party/fanbox/user/3316400  (0.9s)

스크립트도 넣고 쿠키도 넣어봤는데 다운이 안 되네요..ㅠㅠ

예전에는 지원이 됐던 거 같은데 이젠 막힌 건가요?

**Comment by KurtBestor** [comment]
단일 포스트만 가능해요
