### ISSUE TITLE
다X 웹툰 다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#4360]
Invalid: [kakaowebtoon] https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 3 / False / c0114360b550420aa00825b560e7faba
input: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998
type: kakaowebtoon
single: False
url: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [82]
time: 1643031605.2959487 (1월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (11.0s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (22.3s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (21.9s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (24.4s)

read pages... 0
read pages... 1
read pages... 2
last
no html
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (18.4s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (17.2s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (24.9s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (15.7s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (22.7s)

read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (25.2s)

no html
read pages... 0
read pages... 1
read pages... 2
last
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
imgs (0083 - 82화 너와 함께): 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1260, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://webtoon.kakao.com/content/%EC%82%AC%EB%9E%91%ED%95%98%EB%8A%94-%EC%A1%B4%EC%9E%AC/1998  (36.4s)
다음 웹툰 다운이 안됩니다ㅠ_ㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
정말 잘됩니다 정말 감사합니다^o^b척
