### ISSUE TITLE
히토미쪽 다운로드가 안되네요

### ISSUE THREAD

**Issue by himan250** [KurtBestor/Hitomi-Downloader#4362]
Invalid: [hitomi] #-*- [Rhasta] Taihou Himitsu no Akushukai (1841820)

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko
order / group / uid: 43 / False / 9c2cd64949ba4d9c92c03f7aa9bdc03c
input: [Rhasta] Taihou Himitsu no Akushukai (1841820)
type: hitomi
single: False
url: 1841820
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643093869.7631738 (1월 25일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 1841820

제목: Taihou Himitsu no Akushukai

작가: rhasta

그룹: N/A

타입: artistcg

시리즈: azur lane

캐릭터: taihou

태그: uncensored, variant set, female:anal, female:anal intercourse, female:big breasts, female:double penetration, female:pantyhose, female:sole female

언어: Korean

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:1841820)
Find_ehen(id:1841820, ex:False)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1841820/1716d66bf6    ---->    https://e-hentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "downloader", line 363, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 179, in ehen_imgs
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1841820/1716d66bf6

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:True, url:1841820)
Find_ehen(id:1841820, ex:True)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://exhentai.org/g/1841820/1716d66bf6    ---->    https://exhentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:1841820)
Find_ehen(id:1841820, ex:False)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1841820/1716d66bf6    ---->    https://e-hentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "downloader", line 363, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 179, in ehen_imgs
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1841820/1716d66bf6

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:True, url:1841820)
Find_ehen(id:1841820, ex:True)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://exhentai.org/g/1841820/1716d66bf6    ---->    https://exhentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:1841820)
Find_ehen(id:1841820, ex:False)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1841820/1716d66bf6    ---->    https://e-hentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "downloader", line 363, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 179, in ehen_imgs
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1841820/1716d66bf6

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:True, url:1841820)
Find_ehen(id:1841820, ex:True)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://exhentai.org/g/1841820/1716d66bf6    ---->    https://exhentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 182, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'findAll'

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_0", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:1841820)
Find_ehen(id:1841820, ex:False)
Find in HK...
Found in HK: 1716d66bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1841820/1716d66bf6    ---->    https://e-hentai.org/g/1841820/1716d66bf6
Traceback (most recent call last):
 File "downloader", line 363, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 179, in ehen_imgs
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1841820/1716d66bf6

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 645, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: #-*- [Rhasta] Taihou Himitsu no Akushukai (1841820)  (26.7s)

링크타면 사이트는 잘열리는데 다운로더로 받으면 오류가 나는거도있고 EH로 아주 느리게 다운됩니다.

**Comment by himan250** [comment]
Invalid: [hitomi] #-*- [Rico] Kawai ku Zenbu Ai Shite ne (845082)

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko
order / group / uid: 23 / False / f9f0dc72e7284036bc41e8eacffdc2cd
input: [Rico] Kawai ku Zenbu Ai Shite ne (845082)
type: hitomi
single: False
url: 845082
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643091931.7852905 (1월 25일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True


[Gallery]
갤러리 넘버: 845082

제목: Kawai ku Zenbu Ai Shite ne

작가: rico

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:lingerie, female:nakadashi, female:stockings

언어: Korean


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:845082)
Find_ehen(id:845082, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
max_page = 32628
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.2
BFS: 8.2
BFS: 9.2
BFS: 10.2
BFS: 11.2
BFS: 12.2
BFS: 13.2
BFS: 14.2
BFS: 15.2
BFS: 16.2
BFS: 17.3
BFS: 18.3
BFS: 19.3
BFS: 20.3
BFS: 21.6
BFS: 23.1
BFS: 24.4
BFS: 32.7
BFS: 35.1
BFS: 47.1
can not founded in 100 attempts
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:True, url:845082)
Find_ehen(id:845082, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:845082)
Find_ehen(id:845082, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
max_page = 32628
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.0
BFS: 11.0
BFS: 12.0
BFS: 13.0
BFS: 14.0
BFS: 15.0
BFS: 16.0
BFS: 17.0
BFS: 18.0
BFS: 19.0
BFS: 20.0
BFS: 21.0
BFS: 22.0
BFS: 23.0
BFS: 24.1
BFS: 25.1
BFS: 26.1
BFS: 27.1
BFS: 28.1
BFS: 29.3
BFS: 30.3
BFS: 31.3
BFS: 32.3
BFS: 33.3
BFS: 34.4
BFS: 35.6
Traceback (most recent call last):
 File "downloader", line 381, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 159, in ehen_imgs
 File "extractor\ehen_downloader", line 103, in find_ehen
 File "downloader", line 414, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://e-hentai.org/?page=20032&f_doujinshi=on&f_manga=on&f_artistcg=on&f_gamecg=on&f_western=on&f_non-h=on&f_imageset=on&f_cosplay=on&f_asianporn=on&f_misc=on&advsearch=1&f_srdd=2&f_sname=on&f_stags=on&f_sh=on&f_apply=Apply+Filter

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:True, url:845082)
Find_ehen(id:845082, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:845082)
Find_ehen(id:845082, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
max_page = 32628
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.0
BFS: 11.1
BFS: 12.1
BFS: 13.1
BFS: 14.1
BFS: 15.3
BFS: 16.3
BFS: 17.7
BFS: 19.1
BFS: 21.8
BFS: 28.3
can not founded in 100 attempts
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:True, url:845082)
Find_ehen(id:845082, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

get_imgs server: hitomi
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 417, in pop_img
 File "dynamic_hitomi_1", line 223, in _pop_img
Exception: Outdated version

get_imgs server: ehen
ehen_imgs(ex:False, url:845082)
Find_ehen(id:845082, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
max_page = 32628
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.2
BFS: 10.3
BFS: 11.3
BFS: 12.3
BFS: 13.7
BFS: 14.7
BFS: 16.1
BFS: 18.0
BFS: 19.2
BFS: 21.9
BFS: 23.0
BFS: 32.3
can not founded in 100 attempts
Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 159, in ehen_imgs
TypeError: cannot unpack non-iterable NoneType object

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 645, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: #-*- [Rico] Kawai ku Zenbu Ai Shite ne (845082)  (168.1s)

**Comment by himan250** [comment]
흠....왠진 모르지만 25일자 테스트버전으로 실행파일 덮고 다시 키니까 정상다운됩니다.

이제 껏다켜서 그런지 25일자 테스트버전 덕인지는 모르겠네용

**Comment by fnatvr** [comment]
혹시 테스트 버전은 어떻게 다운 받나요?
