### ISSUE TITLE
인스타그램 다운로드가 막힌듯 합니다.

### ISSUE THREAD

**Issue by karitz** [KurtBestor/Hitomi-Downloader#4365]
테스트 버전으로도 해봤는데 다운이 안됩니다.

Invalid: [insta] https://www.instagram.com/p/CY8jyUTPryd

version: 3.7h (22-01-25 05:31:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 5 / False / 99b0f1613bd8416ca1cf9a6fc56d22b6
input: https://www.instagram.com/p/CY8jyUTPryd
type: insta
single: False
url: https://www.instagram.com/p/CY8jyUTPryd
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643101712.6159332 (1월 25일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 218, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (1.6s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 219, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (2.9s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 219, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (2.6s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 219, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (2.0s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 219, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (2.2s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 219, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (1.8s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 218, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (1.7s)

single post
'graphql'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\insta_downloader", line 75, in read
 File "extractor\insta_downloader", line 71, in id_
 File "utils", line 577, in __get__
 File "extractor\insta_downloader", line 67, in name
 File "extractor\insta_downloader", line 218, in get_name
KeyError: 'graphql'

Invalid: fail=True
EOT: https://www.instagram.com/p/CY8jyUTPryd  (6.6s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4336#issuecomment-1021032088
