### ISSUE TITLE
https://imgur.com 여기 다운이 안되네요

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#4372]
항상 감사히 잘 사용하고 있습니다
https://imgur.com 여기서 다운받는게 가끔 있었는데 잘 안되더라구요
한번 문의해 봅니다
정보 올릴게요

55분 0초 뒤 다시 시작: https://imgur.com/a/GT7sAYh

version: 3.7h (22-01-24 05:43:02 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko_kr
order / group / uid: 1 / False / b66fa63b5937430cbac1a9d0667972c6
input: https://imgur.com/a/GT7sAYh
type: imgur
single: False
url: https://imgur.com/a/GT7sAYh
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643204413.5813384 (1월 26일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "extractor\imgur_downloader", line 19, in init
 File "<decorator-gen-67>", line 2, in get_info
 File "constants", line 931, in wrapper
 File "constants", line 902, in wrapper
 File "extractor\imgur_downloader", line 63, in get_info
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://imgur.com/a/GT7sAYh  (6.7s)

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by wlskekrk** [comment]
아 이제 잘 되는군요 정말 감사합니다
