### ISSUE TITLE
1.27 업데이트 이후 프로그램 실행 시 failed to start HTTP server 라고 에러가 뜹니다.

### ISSUE THREAD

**Issue by aruriru** [KurtBestor/Hitomi-Downloader#4375]
안녕하세요. 1.27 업데이트 이후 프로그램 실행 시
failed to start HTTP server 라고 에러가 뜹니다.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9137, in <module>
  File "hitomi_server\__init__", line 387, in start
  File "hitomi_server\__init__", line 346, in join
  File "hitomi_server\__init__", line 339, in run
  File "<decorator-gen-120>", line 2, in switch
  File "locker", line 71, in _wrapper
  File "hitomi_server\__init__", line 370, in switch
  File "hitomi_server\__init__", line 362, in switch
  File "hitomi_server\__init__", line 102, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 139, in server_bind
  File "socket", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 2: invalid start byte

이런 쪽은 문외한이라 뭐가 이상인지 아예 모르겠습니다.
조언 부탁드립니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4339

**Comment by aruriru** [comment]
정말 감사합니다!!
