### ISSUE TITLE
Site Error

### ISSUE THREAD

**Issue by CashOver** [KurtBestor/Hitomi-Downloader#4379]
I don't know why it's giving an error on the sites:

* Facebook
* Tumblr
* Luscious

I would like to know if you could create access to download Twitter favorites

**Comment by KurtBestor** [comment]
Please provide your task info. You can find it on `Right click on the task` - `Info...`

**Comment by CashOver** [comment]
Luscious error: 
Invalid: [luscious] https://www.luscious.net/albums/lu-s-cat-lingerie-collection_275528/

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / pt_br
order / group / uid: 0 / False / 2abb964cff124a9ca899f3d4626a4450
input: https://www.luscious.net/albums/lu-s-cat-lingerie-collection_275528/
type: luscious
single: False
url: https://www.luscious.net/albums/lu-s-cat-lingerie-collection_275528/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~8500000 / None
time: 1643986769.6366603 (Feb 4)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
retry...
retry...
retry...
retry...
retry...
retry...
retry...
retry...
No active exception to reraise
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\luscious_downloader", line 58, in read
RuntimeError: No active exception to reraise

Invalid: fail=True
EOT: https://www.luscious.net/albums/lu-s-cat-lingerie-collection_275528/  (6.7s)

**Comment by CashOver** [comment]
Facebook error:
Invalid: [facebook] https://facebook.com/Artistas-H-con-Salsas-100705965414212

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / pt_br
order / group / uid: 0 / False / 7c461b28ae8e4c95b9738c8bc5cf06b8
input: https://facebook.com/Artistas-H-con-Salsas-100705965414212
type: facebook
single: False
url: https://facebook.com/Artistas-H-con-Salsas-100705965414212
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~8500000 / None
time: 1643987024.3831558 (Feb 4)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
not f
'token'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\facebook_downloader", line 73, in read
 File "extractor\facebook_downloader", line 246, in get_imgs
 File "clf2", line 157, in solve
 File "extractor\facebook_downloader", line 211, in f
KeyError: 'token'

Invalid: fail=True
EOT: https://facebook.com/Artistas-H-con-Salsas-100705965414212  (13.2s)

**Comment by CashOver** [comment]
Tumblr error
Invalid: [tumblr] https://xboxherz.tumblr.com

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / pt_br
order / group / uid: 0 / False / c0cbc1d23e1d40a4972637130ee57ee1
input: https://xboxherz.tumblr.com
type: tumblr
single: False
url: https://xboxherz.tumblr.com
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~8500000 / None
time: 1643987180.2072632 (Feb 4)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'content'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\tumblr_downloader", line 53, in read
 File "extractor\tumblr_downloader", line 172, in get_imgs
 File "extractor\tumblr_downloader", line 122, in posts
 File "extractor\tumblr_downloader", line 141, in __init__
KeyError: 'content'

Invalid: fail=True
EOT: https://xboxherz.tumblr.com  (6.9s)
