### ISSUE TITLE
Pawoo error with some profiles

### ISSUE THREAD

**Issue by iPietroS** [KurtBestor/Hitomi-Downloader#4381]
Cant download some profiles from pawoo.net

This is the info it shows:

Invalid: [pawoo] https://pawoo.net/@noise

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 55 / False / a19bab6bdc77420fbe81e8fc3e0a411c
input: https://pawoo.net/@noise
type: pawoo
single: False
url: https://pawoo.net/@noise
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643334242.943998 (Jan 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'media'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pawoo_downloader", line 37, in read
 File "mastodon", line 59, in get_imgs
KeyError: 'media'

Invalid: fail=True
EOT: https://pawoo.net/@noise  (33.8s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
