### ISSUE TITLE
산카쿠에서 다운로드가 잘 되지 않네요

### ISSUE THREAD

**Issue by donato-alpa** [KurtBestor/Hitomi-Downloader#4382]
[chan] rororogi_mogera

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 7 / False / f5b2228006504c3e9a73289d01c16a00
input: https://chan.sankakucomplex.com/?tags=rororogi_mogera
type: sankaku
single: False
url: https://chan.sankakucomplex.com/?tags=rororogi_mogera
dir: hitomi_downloaded_sankaku\[chan] rororogi_mogera
zip: 
artist: None
valid / done: True / True
range / range_p: ~4000 / None
time: 1643343625.031139 (1월 28일)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_sankaku\[chan] rororogi_mogera\30117615.jpg
[0002] hitomi_downloaded_sankaku\[chan] rororogi_mogera\30181358.jpg
[0003] hitomi_downloaded_sankaku\[chan] rororogi_mogera\29684752.jpg
[0004] hitomi_downloaded_sankaku\[chan] rororogi_mogera\29653504.jpg
[0005] hitomi_downloaded_sankaku\[chan] rororogi_mogera\29499009.png
[0006] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25461960.jpg
[0007] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25372940.jpg
[0008] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303870.jpg
[0009] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303819.jpg
[0010] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303796.jpg
[0011] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303771.jpg
[0012] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303747.jpg
[0013] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25001791.jpg
[0014] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985861.jpg
[0015] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985858.jpg
[0016] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985856.jpg
[0017] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985853.jpg
[0018] hitomi_downloaded_sankaku\[chan] rororogi_mogera\6511601.jpg

[URLs]
[0001] hitomi_downloaded_sankaku\[chan] rororogi_mogera\30117615.jpg    --->    【local_lazy】 30117615.jpg
[0002] hitomi_downloaded_sankaku\[chan] rororogi_mogera\30181358.jpg    --->    【local_lazy】 30181358.jpg
[0003] hitomi_downloaded_sankaku\[chan] rororogi_mogera\29684752.jpg    --->    【local_lazy】 29684752.jpg
[0004] hitomi_downloaded_sankaku\[chan] rororogi_mogera\29653504.jpg    --->    【local_lazy】 29653504.jpg
[0005] hitomi_downloaded_sankaku\[chan] rororogi_mogera\29499009.png    --->    【local_lazy】 29499009.png
[0006] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25461960.jpg    --->    【local_lazy】 25461960.jpg
[0007] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25372940.jpg    --->    【local_lazy】 25372940.jpg
[0008] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303870.jpg    --->    【local_lazy】 25303870.jpg
[0009] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303819.jpg    --->    【local_lazy】 25303819.jpg
[0010] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303796.jpg    --->    【local_lazy】 25303796.jpg
[0011] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303771.jpg    --->    【local_lazy】 25303771.jpg
[0012] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25303747.jpg    --->    【local_lazy】 25303747.jpg
[0013] hitomi_downloaded_sankaku\[chan] rororogi_mogera\25001791.jpg    --->    【local_lazy】 25001791.jpg
[0014] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985861.jpg    --->    【local_lazy】 24985861.jpg
[0015] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985858.jpg    --->    【local_lazy】 24985858.jpg
[0016] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985856.jpg    --->    【local_lazy】 24985856.jpg
[0017] hitomi_downloaded_sankaku\[chan] rororogi_mogera\24985853.jpg    --->    【local_lazy】 24985853.jpg
[0018] hitomi_downloaded_sankaku\[chan] rororogi_mogera\6511601.jpg    --->    【local_lazy】 6511601.jpg

[Messages]
login... 6
Failed to login: Traceback (most recent call last):
 File "sankaku_login", line 42, in login
 File "sankaku_login", line 69, in login_
 File "sankaku_login", line 61, in login_
Exception: Failed to login

login... 2
types: img, gif, video
https://chan.sankakucomplex.com/?tags=rororogi_mogera
Traceback (most recent call last):
 File "extractor\sankaku_downloader", line 331, in get_imgs
KeyError: 'next-page-url'

stop
EOT: https://chan.sankakucomplex.com/?tags=rororogi_mogera  (203.9s)

login... 5
Failed to login: Traceback (most recent call last):
 File "sankaku_login", line 42, in login
 File "sankaku_login", line 69, in login_
 File "sankaku_login", line 61, in login_
Exception: Failed to login

login... 4
types: img, gif, video
https://chan.sankakucomplex.com/?tags=rororogi_mogera
Traceback (most recent call last):
 File "extractor\sankaku_downloader", line 331, in get_imgs
KeyError: 'next-page-url'

stop
EOT: https://chan.sankakucomplex.com/?tags=rororogi_mogera  (5.8s)

페이지 지정 다운로드로 작업해봤지만,
3633개 전부 다운로드 되지 않고 18개만 다운로드 되고 끝납니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2854
