### ISSUE TITLE
The remote host forcibly closed an existing connection.

### ISSUE THREAD

**Issue by frannns** [KurtBestor/Hitomi-Downloader#4390]
Invalid: [bili] https://www.bilibili.com/video/BV1dL4y1x74t?spm_id_from=333.851.b_7265636f6d6d656e64.1

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_cn
order / group / uid: 0 / False / 18b5b18df0f24b0fbf2a367bf00d3d6e
input: https://www.bilibili.com/video/BV1dL4y1x74t?spm_id_from=333.851.b_7265636f6d6d656e64.1
type: bili
single: True
url: https://www.bilibili.com/video/BV1dL4y1x74t?spm_id_from=333.851.b_7265636f6d6d656e64.1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643454246.687312 (一月 29)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
stop
Traceback (most recent call last):
 File "downloader", line 383, in read_html
Exception: urllib2 not in methods

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1162, in start
 File "extractor\bili_downloader", line 75, in init
 File "<decorator-gen-39>", line 2, in fix_url
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\bili_downloader", line 50, in fix_url
 File "downloader", line 426, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 201, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1dL4y1x74t?spm_id_from=333.851.b_7265636f6d6d656e64.1  (0.9s)

**Comment by frannns** [comment]
读取中...  https://www.youtube.com/watch?v=Fln_WNK4wYM

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_cn
order / group / uid: 0 / False / c27940363ca24e0cbde0332c740bea26
input: https://www.youtube.com/watch?v=Fln_WNK4wYM
type: youtube
single: True
url: https://www.youtube.com/watch?v=Fln_WNK4wYM
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1643456447.8627322 (Jan 29)
tags: []
lock: False
color: reading
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
[youtube] Fln_WNK4wYM: Downloading webpage
[youtube] Fln_WNK4wYM: Downloading android player API JSON
[youtube] Fln_WNK4wYM: Downloading android player API JSON (retry #1)
[youtube] Fln_WNK4wYM: Downloading android player API JSON (retry #2)
[youtube] Fln_WNK4wYM: Downloading android player API JSON (retry #3)
[youtube] Fln_WNK4wYM: Downloading iframe API JS
[youtube] Fln_WNK4wYM: Downloading web player API JSON
[youtube] Fln_WNK4wYM: Downloading web player API JSON (retry #1)
[youtube] Fln_WNK4wYM: Downloading web player API JSON (retry #2)
[youtube] Fln_WNK4wYM: Downloading web player API JSON (retry #3)
### youtube retry...
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 730, in _request_webpage
   return self._downloader.urlopen(url_or_request)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\YoutubeDL", line 3526, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\utils", line 1508, in https_open
   req, **kwargs)
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 612, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 3149, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 3127, in _download_player_responses
   video_id, webpage, master_ytcfg)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 2925, in _extract_player_responses
   raise last_error
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 2907, in _extract_player_responses
   client, video_id, player_ytcfg or master_ytcfg, player_ytcfg, player_url if require_js_player else None, initial_pr)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 2825, in _extract_player_response
   note='Downloading %s player API JSON' % client.replace('_', ' ').strip()
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 760, in _extract_response
   note='%s%s' % (note, ' (retry #%d)' % count if count else ''))
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\youtube", line 461, in _call_api
   query={'key': api_key or self._extract_api_key()})
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 996, in _download_json
   expected_status=expected_status)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 974, in _download_json_handle
   expected_status=expected_status)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 763, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 748, in _request_webpage
   raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
yt_dlp.utils.ExtractorError: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\YoutubeDL", line 1367, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\YoutubeDL", line 1437, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\extractor\common", line 638, in extract
   raise type(e)(e.msg, **kwargs)
yt_dlp.utils.ExtractorError: [youtube] Fln_WNK4wYM: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out'))) (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 63, in get
 File "ytdl", line 525, in __init__
 File "ytdl", line 386, in extract_info
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\YoutubeDL", line 1358, in extract_info
   return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
 File "C:\Users\A'R'CH~1\AppData\Local\Temp\_MEI41362\ytdl_d6008459\yt_dlp\yt_dlp\YoutubeDL", line 1385, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 356, in report_error
yt_dlp.utils.DownloadError: ERROR: [youtube] Fln_WNK4wYM: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out'))) (caused by URLError(timeout('timed out')))

[youtube] Fln_WNK4wYM: Downloading webpage
[youtube] Fln_WNK4wYM: Downloading android player API JSON
[youtube] Fln_WNK4wYM: Downloading android player API JSON (retry #1)
[youtube] Fln_WNK4wYM: Downloading android player API JSON (retry #2)
[youtube] Fln_WNK4wYM: Downloading android player API JSON (retry #3)

**Comment by frannns** [comment]
Reading...  https://exhentai.org/g/2106789/3f71d5670d/

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_cn
order / group / uid: 0 / False / 5d8cd72cfec1430dbbfb6eac1d4996b9
input: https://exhentai.org/g/2106789/3f71d5670d/
type: ehen
single: False
url: https://exhentai.org/g/2106789/3f71d5670d/
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1643456925.6800394 (Jan 29)
tags: []
lock: False
color: reading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002336C055408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hitomi.la', port=443): Max retries exceeded with url: /galleries/2106789.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336C055408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "dynamic_hitomi_0", line 231, in _pop_img
 File "dynamic_hitomi_0", line 440, in _get_gallery_url
 File "dynamic_hitomi_0", line 422, in solve_redirect
 File "downloader", line 421, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 201, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hitomi.la', port=443): Max retries exceeded with url: /galleries/2106789.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336C055408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002336BCCF188>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ltn.hitomi.la', port=443): Max retries exceeded with url: /galleries/2106789.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336BCCF188>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 421, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 201, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ltn.hitomi.la', port=443): Max retries exceeded with url: /galleries/2106789.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336BCCF188>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

get_imgs server: hitomi
