### ISSUE TITLE
히토미 Invalid 현상

### ISSUE THREAD

**Issue by LeinForce** [KurtBestor/Hitomi-Downloader#4400]
Invalid: [hitomi] https://hitomi.la/doujinshi/%E9%9A%A3%E3%81%AB%E4%BD%8F%E3%82%80%E5%84%AA%E3%81%97%E3%81%84%E3%81%8A%E5%A7%89%E3%81%A1%E3%82%83%E3%82%93%E3%81%AB%E5%91%8A%E7%99%BD%E3%81%97%E3%81%9F%E3%82%89%E2%80%A6-!-%E6%97%A5%E6%9C%AC%E8%AA%9E-384098-2087790.html#1

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e88f74a9b9f5441cb00fd9e1c442ff93
input: https://hitomi.la/doujinshi/%E9%9A%A3%E3%81%AB%E4%BD%8F%E3%82%80%E5%84%AA%E3%81%97%E3%81%84%E3%81%8A%E5%A7%89%E3%81%A1%E3%82%83%E3%82%93%E3%81%AB%E5%91%8A%E7%99%BD%E3%81%97%E3%81%9F%E3%82%89%E2%80%A6-!-%E6%97%A5%E6%9C%AC%E8%AA%9E-384098-2087790.html#1
type: hitomi
single: False
url: https://hitomi.la/doujinshi/%E9%9A%A3%E3%81%AB%E4%BD%8F%E3%82%80%E5%84%AA%E3%81%97%E3%81%84%E3%81%8A%E5%A7%89%E3%81%A1%E3%82%83%E3%82%93%E3%81%AB%E5%91%8A%E7%99%BD%E3%81%97%E3%81%9F%E3%82%89%E2%80%A6-!-%E6%97%A5%E6%9C%AC%E8%AA%9E-384098-2087790.html#1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643552263.914241 (1월 30일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ltn.hitomi.la/galleries/2087790.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 455, in get_imgs
 File "hitomi", line 565, in pop_img
 File "dynamic_hitomi_0", line 242, in _pop_img
 File "dynamic_hitomi_0", line 209, in get_data
 File "downloader", line 440, in read_html
Exception: 403

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 645, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://hitomi.la/doujinshi/%E9%9A%A3%E3%81%AB%E4%BD%8F%E3%82%80%E5%84%AA%E3%81%97%E3%81%84%E3%81%8A%E5%A7%89%E3%81%A1%E3%82%83%E3%82%93%E3%81%AB%E5%91%8A%E7%99%BD%E3%81%97%E3%81%9F%E3%82%89%E2%80%A6-!-%E6%97%A5%E6%9C%AC%E8%AA%9E-384098-2087790.html#1  (9.9s)

20220130 2100 즈음부터 계속 0kb를 띄우기 시작하더니 결국 뻗네요.
자세한 증상은 주소입력하고 다운로드를 시작하면, 주소를 읽어들이다가 Invalid를 띄우면서 빨간색으로 죽어버립니다

요즘 히토미가 자주 뻘짓을 하는거같네요. 다운로더들을 막고있는건가 싶기도 하고...

**Comment by mastaer88** [comment]
히토미 안받아지고 익헨으로 받내요

**Comment by KurtBestor** [comment]
고쳤어요. 30분 뒤에 다시 시도하거나 껐다 켜면 제대로 동작할 거예요

**Comment by doaldi** [comment]
요즘 주기적으로 막고 있는거 같아요 다운 잘되다가 갑자기 노란색으로 변하는 경우가 잦네요
