### ISSUE TITLE
Xvideo problem

### ISSUE THREAD

**Issue by Deltako806** [KurtBestor/Hitomi-Downloader#4401]
It worked before but now, I can't download channel, profiles, pornstar-channels and amateur-channels
I don't know why, I just know it doesn't work
but classic video seems to work

**Comment by KurtBestor** [comment]
Please provide your task info. You can find it on `Right click on the task` - `Info...`

**Comment by Deltako806** [comment]
I will give one example, if you need more, I will give more.
I would also like to point out that the pornstar channels were the first to no longer be downloaded, then (after an update, if I remember correctly), all the others became stuck, even those who was downloading before. 


version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / fr_fr
order / group / uid: 80 / False / 3561d01f7f8e4d2b886d7a9945be250f
input: https://www.xvideos.com/channels/little-caprice-channel
type: xvideo
single: True
url: https://www.xvideos.com/channels/little-caprice-channel
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~2000 / None
time: 1644658596.3415682 (Feb 12)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
empty
no videos
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\xvideo_downloader", line 73, in read
 File "extractor\xvideo_downloader", line 129, in read_channel
Exception: no videos

Invalid: fail=True
EOT: https://www.xvideos.com/channels/little-caprice-channel  (3.6s)

**after this "empty message", it repeat again and again, until the next message :**



HTTPSConnectionPool(host='www.xvideos.com', port=443): Max retries exceeded with url: /channels/little/videos/best/0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D468203208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
stop
Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 752, in getaddrinfo
 File "<decorator-gen-2>", line 2, in getaddrinfo
 File "locker", line 128, in _wrapper
 File "locker", line 63, in exec_
 File "locker", line 39, in run
 File "locker", line 128, in <lambda>
 File "downloader", line 86, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D468203208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.xvideos.com', port=443): Max retries exceeded with url: /channels/little/videos/best/0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D468203208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\xvideo_downloader", line 73, in read
 File "extractor\xvideo_downloader", line 102, in read_channel
 File "requests\sessions", line 590, in post
 File "downloader", line 201, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.xvideos.com', port=443): Max retries exceeded with url: /channels/little/videos/best/0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D468203208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Invalid: fail=True
EOT: https://www.xvideos.com/channels/little-caprice-channel  (116.8s)

**and the "empty message" repeat here, like 50 times, I think, until the end**

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/issues/4410
