### ISSUE TITLE
Manamoa 다운로드 에러

### ISSUE THREAD

**Issue by Lunartic85** [KurtBestor/Hitomi-Downloader#4402]
2시 경 자료부터 다운로드가 안되네요.
그 이전 자료는 여전히 문제없이 다운로드 되고있습니다.

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-8.1-6.3.9600-SP0 / ko_kr
order / group / uid: 536 / False / 3b17a2203ddd4969a35689a101ef1276
input: https://jmana1.net/bookdetail?bookdetailid=499586
type: jmana
single: False
url: https://jmana1.net/bookdetail?bookdetailid=499586
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643590150.1397307 (1월 31일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
no selected option
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "extractor\jmana_downloader", line 49, in init
Exception: no selected option

Invalid: fail=True
EOT: https://jmana1.net/bookdetail?bookdetailid=499586  (10.7s)

**Comment by Lunartic85** [comment]
해결되었네요. 마나모아 자체 문제였나봅니다.
