### ISSUE TITLE
Unable to download keeps showing reading in progress

### ISSUE THREAD

**Issue by jwwsjlm** [KurtBestor/Hitomi-Downloader#4404]
读取中...  https://www.youtube.com/watch?v=5ZTRTlCFK4A

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / zh_cn
order / group / uid: 0 / False / 45a44e61beae448f81418fb400fe670a
input: https://www.youtube.com/watch?v=5ZTRTlCFK4A
type: youtube
single: True
url: https://www.youtube.com/watch?v=5ZTRTlCFK4A
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1643602543.203321 (一月 31)
tags: []
lock: False
color: reading
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
[youtube] 5ZTRTlCFK4A: Downloading webpage
[youtube] 5ZTRTlCFK4A: Downloading android player API JSON
[youtube] 5ZTRTlCFK4A: Downloading android player API JSON (retry #1)
[youtube] 5ZTRTlCFK4A: Downloading android player API JSON (retry #2)
[youtube] 5ZTRTlCFK4A: Downloading android player API JSON (retry #3)
[youtube] 5ZTRTlCFK4A: Downloading iframe API JS
[youtube] 5ZTRTlCFK4A: Downloading web player API JSON
[youtube] 5ZTRTlCFK4A: Downloading web player API JSON (retry #1)
why?
![image](https://user-images.githubusercontent.com/48446617/151739301-1b985c64-8693-45d8-80db-a8ec71b86268.png)
![image](https://user-images.githubusercontent.com/48446617/151739339-78f73ec5-677b-487a-868e-0e08ddba5d0d.png)

**Comment by jwwsjlm** [comment]
读取中...  https://www.youtube.com/watch?v=B3OA78gVzQY

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / zh_cn
order / group / uid: 0 / False / ab33a959948c48f8b1a7750d9a46a2d8
input: https://www.youtube.com/watch?v=B3OA78gVzQY
type: youtube
single: True
url: https://www.youtube.com/watch?v=B3OA78gVzQY
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1643603713.6627927 (一月 31)
tags: []
lock: False
color: reading
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
[youtube] B3OA78gVzQY: Downloading webpage
[youtube] B3OA78gVzQY: Downloading android player API JSON
[youtube] B3OA78gVzQY: Downloading android player API JSON (retry #1)
[youtube] B3OA78gVzQY: Downloading android player API JSON (retry #2)
[youtube] B3OA78gVzQY: Downloading android player API JSON (retry #3)
[youtube] B3OA78gVzQY: Downloading iframe API JS
[youtube] B3OA78gVzQY: Downloading web player API JSON
[youtube] B3OA78gVzQY: Downloading web player API JSON (retry #1)
[youtube] B3OA78gVzQY: Downloading web player API JSON (retry #2)
[youtube] B3OA78gVzQY: Downloading web player API JSON (retry #3)
### youtube retry...
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 730, in _request_webpage
   return self._downloader.urlopen(url_or_request)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\YoutubeDL", line 3526, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\utils", line 1508, in https_open
   req, **kwargs)
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 612, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 3149, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 3127, in _download_player_responses
   video_id, webpage, master_ytcfg)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 2925, in _extract_player_responses
   raise last_error
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 2907, in _extract_player_responses
   client, video_id, player_ytcfg or master_ytcfg, player_ytcfg, player_url if require_js_player else None, initial_pr)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 2825, in _extract_player_response
   note='Downloading %s player API JSON' % client.replace('_', ' ').strip()
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 760, in _extract_response
   note='%s%s' % (note, ' (retry #%d)' % count if count else ''))
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\youtube", line 461, in _call_api
   query={'key': api_key or self._extract_api_key()})
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 996, in _download_json
   expected_status=expected_status)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 974, in _download_json_handle
   expected_status=expected_status)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 763, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 748, in _request_webpage
   raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
yt_dlp.utils.ExtractorError: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\YoutubeDL", line 1367, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\YoutubeDL", line 1437, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\extractor\common", line 638, in extract
   raise type(e)(e.msg, **kwargs)
yt_dlp.utils.ExtractorError: [youtube] B3OA78gVzQY: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out'))) (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 63, in get
 File "ytdl", line 525, in __init__
 File "ytdl", line 386, in extract_info
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\YoutubeDL", line 1358, in extract_info
   return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
 File "C:\Users\54305\AppData\Local\Temp\_MEI235002\ytdl_7fef0ab8\yt_dlp\yt_dlp\YoutubeDL", line 1385, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 356, in report_error
yt_dlp.utils.DownloadError: ERROR: [youtube] B3OA78gVzQY: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out'))) (caused by URLError(timeout('timed out')))

[youtube] B3OA78gVzQY: Downloading webpage
