### ISSUE TITLE
히토미 다운로드 오류

### ISSUE THREAD

**Issue by Horung** [KurtBestor/Hitomi-Downloader#4409]
Join me on! by Butcha-u (2128647) #Doujinshi

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 95 / False / bcbef04e69c940c79616b8f977ef06f1
input: https://hitomi.la/doujinshi/join-me-on!-%ED%95%9C%EA%B5%AD%EC%96%B4-2128647.html#1
type: hitomi
single: False
url: https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html
dir: 히토미\Join me on! by Butcha-u (2128647) #Doujinshi
zip: 
artist: butcha-u
valid / done: True / False
range / range_p: ~10000 / None
time: 1643711812.9807978 (2월 1일)
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False

[Gallery]
갤러리 넘버: 2128647

제목: Join me on!

작가: butcha-u

그룹: N/A

타입: doujinshi

시리즈: resident evil

캐릭터: ashley graham

태그: female:anal, female:filming, female:focus anal, female:gaping, female:masturbation, female:sex toys, female:sole female, female:tentacles, male:monster

언어: Korean

[File Names]
[0001] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\01.webp
[0002] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\02.jpg
[0003] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\03.jpg
[0004] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\04.jpg
[0005] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\05.jpg
[0006] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\06.jpg
[0007] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\07.jpg
[0008] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\08.jpg
[0009] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\09.jpg
[0010] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\10.jpg
[0011] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\11.jpg
[0012] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\12.jpg
[0013] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\13.jpg
[0014] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\14.jpg
[0015] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\15.jpg
[0016] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\16.jpg
[0017] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\17.jpg
[0018] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\18.jpg
[0019] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\19.jpg
[0020] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\20.jpg
[0021] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\21.jpg
[0022] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\22.jpg
[0023] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\23.jpg
[0024] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\24.jpg
[0025] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\25.jpg
[0026] 히토미\Join me on! by Butcha-u (2128647) #Doujinshi\26.jpg

[URLs]
[0001] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://aa.hitomi.la/webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp
[0002] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/1889/d905fb08963fcdd950dc6c972ae4888697e101e9ecdb99ada0b92eb73f62c617.jpg
[0003] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/3015/b3c61e9da50f78446c319f9c14184afae1350ae20c6685aa5bffbca5c6bf4c7b.jpg
[0004] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/2628/df0f1aa35359a28995c8bb63c36fa723848b2db2e260d358805448aa09e0944a.jpg
[0005] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/272/10d8727c4a19c08943e05dabf9827b0f7fc2d762a24a2ba6dee8ad6c22ebc101.jpg
[0006] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/1307/8f99a57701639a68fbcd5ccb1a9b1a010dd740664151cd718ec9f056fc5271b5.jpg
[0007] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/1106/64a83a9d801cca993b0cb187fdb68f20aae6b172a22679fc3d8507fded822524.jpg
[0008] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/2618/c65942206c14356aeb2914702cc33c56499732f7f2c38736c1b31a2e40d713aa.jpg
[0009] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/2141/1bc09946c00429f58688dcc25ac7ef03c601079eeccfd5eef27187b9a28445d8.jpg
[0010] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/3684/76b22fa30c3535fe0482d78da026fca43516c8ef06dea341fb6e0ae288b1e64e.jpg
[0011] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/223/3550762d55b6dba6fbc01945194ac7f5ee872c012a0ec9e7d9413103e5c34df0.jpg
[0012] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/2893/99d275ebb62ba12da53c8cf50024ed1966a1e80eed8076e76c15ab76243134db.jpg
[0013] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/3445/3995d111bbd7f662e021e264eacaf651e10dcc1c8fb27d8a15c487ccf9a1775d.jpg
[0014] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/1359/53f08ec6fdf5fa045c890903069ac5d5f2d1e80fa4d96428162b3b9baa3124f5.jpg
[0015] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/1787/2fbc2cae658740c7376a8b020ab9e4b85ea8b0c785e8277c5f5ffa8af014dfb6.jpg
[0016] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/507/4a667c46c7f63c42c8ba664cae27c3f6898764df4a18a40d965dbd6be669cfb1.jpg
[0017] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/169/f4bf9441679e273afa60a3f6ce43d61d637466e35df5d4fc029109c637c1aa90.jpg
[0018] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/2555/d0be8d2844293c19ea9799e3c3259eab9415156bc3252ead39cd39dec2674fb9.jpg
[0019] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/329/8586b2715bd9a9089db9ac62071945a0d05d65ebb5db5cbac02f1eac12231491.jpg
[0020] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/22/86437ea12d8837ad2fd9c24a8033f92b79d6b42cf926c4df9a7544eadd89f160.jpg
[0021] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/838/fc823105dff3ee63165f46ad116fd7ff64729edb1f6b21954f4a26dead1e6463.jpg
[0022] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/3931/c0a9615b699866d4af7971d66f80135a07f9b19c888816d4a57e2553490645bf.jpg
[0023] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/672/82ea5e6ce34c8180d43973d0df8ac13c5c9bd10a19ede3d856f5689dd76c6a02.jpg
[0024] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/535/daf92a2a9a1873a57bcba48a30ad946df61ef671d4c33cbff2b0f048d5b9c172.jpg
[0025] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://ab.hitomi.la/images/1643551173/471/9c76a2bff76b920a7ed685e0d1bdb5905b3fb1276223a0901f9d23e1294e5d71.jpg
[0026] LazyUrl(https://hitomi.la/doujinshi/join-me-on!-한국어-2128647.html)    --->    https://bb.hitomi.la/images/1643551173/2488/235135ec2b5f683761bb8122cd75b5516c20d79bbb229dd0e4ee1bc49f87ab89.jpg

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 26

Fail : \\?\E:\HD\히토미\Join me on! by Butcha-u (2128647) #Doujinshi\01.webp
Traceback (most recent call last):
 File "downloader", line 966, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001A853C08D88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aa.hitomi.la', port=443): Max retries exceeded with url: /webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A853C08D88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1003, in download
 File "requests\sessions", line 555, in get
 File "downloader", line 201, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='aa.hitomi.la', port=443): Max retries exceeded with url: /webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A853C08D88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1011, in download
Exception: https://aa.hitomi.la/webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp
Traceback (most recent call last):
 File "downloader", line 966, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001A853C08D88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aa.hitomi.la', port=443): Max retries exceeded with url: /webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A853C08D88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1003, in download
 File "requests\sessions", line 555, in get
 File "downloader", line 201, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='aa.hitomi.la', port=443): Max retries exceeded with url: /webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A853C08D88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

retry (1)
use alternative url: https://aa.hitomi.la/webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp --> https://aa.hitomi.la/webp/1643551173/1772/66fcf5d3f12402b6cfc254f52fb1af65824619a3f593a9d863ebce3d5bc0cec6.webp

**Comment by Horung** [comment]
[error.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/7983489/error.txt)

cg 다운로드는 더 심하네요
