### ISSUE TITLE
트위터에서 사진을 다운로드 하려고 하면 로그인 하라고 뜹니다

### ISSUE THREAD

**Issue by yeonggille** [KurtBestor/Hitomi-Downloader#4438]
Login required; Update your cookies
https://twitter.com/MCgunngu/status/1489903304800759809

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / f5174b8550684eeca44352fbf6037d57
input: https://twitter.com/MCgunngu/status/1489903304800759809
type: twitter
single: False
url: https://twitter.com/MCgunngu/status/1489903304800759809
dir: 
zip: 
artist: MC.ぐんぐ@skeb募集中(本名：郡司正志)
valid / done: False / True
range / range_p: None / None
time: 1644064288.5305395 (2월 5일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
generate csrf
single tweet
id: 1489903162655793160

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 89, in read
 File "extractor\twitter_downloader", line 466, in get_imgs_single
errors.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/MCgunngu/status/1489903304800759809  (4.5s)

single tweet
id: 1489903162655793160

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 89, in read
 File "extractor\twitter_downloader", line 466, in get_imgs_single
errors.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/MCgunngu/status/1489903304800759809  (4.8s)

single tweet
id: 1489903162655793160

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 89, in read
 File "extractor\twitter_downloader", line 466, in get_imgs_single
errors.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/MCgunngu/status/1489903304800759809  (4.8s)

single tweet
id: 1489903162655793160

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 89, in read
 File "extractor\twitter_downloader", line 466, in get_imgs_single
errors.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/MCgunngu/status/1489903304800759809  (4.8s)

분명히 로그인해서 쿠키를 추출하고 다운로더에 불러오기해서 먹였는데 자꾸 로그인하라는 메세지가 뜹니다. 어떻게 하면 좋을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by yeonggille** [comment]
[invaild] 라고 뜹니다

Invalid: [twitter] https://twitter.com/MCgunngu/status/1489903304800759809

version: 3.7i (22-02-08 08:38:27 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / 0d9e472604fd4d79875a9dd1d91d0c90
input: https://twitter.com/MCgunngu/status/1489903304800759809
type: twitter
single: False
url: https://twitter.com/MCgunngu/status/1489903304800759809
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1644318321.1993773 (22-02-08 11:05:21 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
401 Unauthorized (Could not authenticate you)
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "extractor\twitter_downloader", line 56, in init
 File "<decorator-gen-27>", line 2, in get_artist_username
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\twitter_downloader", line 829, in get_artist_username
 File "extractor\twitter_downloader", line 289, in tweet
 File "extractor\twitter_downloader", line 316, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 257, in _call
Exception: 401 Unauthorized (Could not authenticate you)

Invalid: fail=True
EOT: https://twitter.com/MCgunngu/status/1489903304800759809  (6.8s)

401 Unauthorized (Could not authenticate you)
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "extractor\twitter_downloader", line 56, in init
 File "<decorator-gen-27>", line 2, in get_artist_username
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\twitter_downloader", line 829, in get_artist_username
 File "extractor\twitter_downloader", line 289, in tweet
 File "extractor\twitter_downloader", line 316, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 257, in _call
Exception: 401 Unauthorized (Could not authenticate you)

Invalid: fail=True
EOT: https://twitter.com/MCgunngu/status/1489903304800759809  (6.8s)

**Comment by yeonggille** [comment]
트위터에서 로그아웃했다가 로그인하고 쿠키를 다시 불러오니 해결되었습니다. 감사합니다!
