### ISSUE TITLE
노벨피아 다운로드 시도시 쿠키를 업데이트 하라면서 다운이 안됩니다

### ISSUE THREAD

**Issue by kokokoneko** [KurtBestor/Hitomi-Downloader#4477]
크롬 브라우저의 get cookies.txt 확장 프로그램을 이용하여 쿠키를 다운, 다운로더에 적용하였으며
로그인은 네이버 계정을 이용하여 하고 있습니다.

Login required; Update your cookies
https://novelpia.com/novel/1149

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e61b4ade3f4c4212b832cdd0b58245a4
input: https://novelpia.com/novel/1149
type: novelpia
single: False
url: https://novelpia.com/novel/1149
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1644846612.9454486 (2월 14일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\novelpia_downloader", line 43, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/1149  (0.5s)

**Comment by rybshgsd** [comment]
와 나돈데 ㅆㅂ.. 개발자 죽었냐? 테스트 부탁드려요 라도 해주면
넙죽 받아먹을텐데

**Comment by KurtBestor** [comment]
죽은 듯

**Comment by KurtBestor** [comment]
개발자 죽은 듯

**Comment by SaidBySolo** [comment]
assign 해주시지....
