### ISSUE TITLE
히토미 다운로드가 시작되지 않습니다.

### ISSUE THREAD

**Issue by bigpig200** [KurtBestor/Hitomi-Downloader#4481]
히토미 사이트에는 문제 없이 접속되는데
히토미 서버에 접속이 되지 않는것같습니다.
아래는 다운로드 실패 로그입니다.
바쁘신 와중에 죄송합니다. 잘부탁드려요

> nvalid: [hitomi] https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html
> 
> version: 3.7i (22-02-08 08:38:27 UTC)
> platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
> order / group / uid: 2 / False / e571c94ee0d2466f85401417eb8b4b54
> input: https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html
> type: hitomi
> single: False
> url: https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html
> dir: 
> zip: 
> artist: None
> valid / done: False / True
> range / range_p: ~99999 / None
> time: 1644920610.0050573 (22-02-15 10:23:30 UTC)
> tags: []
> lock: False
> color: invalid
> paused: False
> format: None
> p2f: None
> segment: None
> admin: True
> goodbyedpi: True
> ytdl: yt_dlp 2022.02.04
> pinned: False
> extras: {}
> live: False
> changed: True
> 
> 
> [Gallery]
> None
> 
> 
> [File Names]
> 
> 
> 
> [URLs]
> 
> 
> 
> [Messages]
> get_imgs server: ehen
> ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html)
> Find_ehen(id:2142280, ex:False)
> Find in HK...
> not found in HK
> Traceback (most recent call last):
>  File "hitomi_downloader", line 564, in read
>  File "hitomi_downloader", line 441, in get_imgs
>  File "extractor\ehen_downloader", line 162, in ehen_imgs
> Exception: URL not found
> 
> get_imgs server: ehen
> ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html)
> Find_ehen(id:2142280, ex:True)
> Find in HK...
> not found in HK
> Traceback (most recent call last):
>  File "hitomi_downloader", line 564, in read
>  File "hitomi_downloader", line 441, in get_imgs
>  File "extractor\ehen_downloader", line 162, in ehen_imgs
> Exception: URL not found
> 
> get_imgs server: hitomi
> FINAL SERVER: hitomi
> always use ehen
> get_imgs server: ehen
> ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html)
> Find_ehen(id:2142280, ex:False)
> Find in HK...
> not found in HK
> get_imgs server: ehen
> ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html)
> Find_ehen(id:2142280, ex:True)
> Find in HK...
> not found in HK
> Traceback (most recent call last):
>  File "hitomi_downloader", line 613, in read
>  File "hitomi_downloader", line 441, in get_imgs
>  File "extractor\ehen_downloader", line 162, in ehen_imgs
> Exception: URL not found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "hitomi_downloader", line 615, in read
>  File "hitomi_downloader", line 441, in get_imgs
>  File "extractor\ehen_downloader", line 162, in ehen_imgs
> Exception: URL not found
> 
> stop
> Invalid: fail=True
> stop
> EOT: https://hitomi.la/doujinshi/vr%E4%B8%80%E3%83%8E%E7%80%AC%E5%A7%89%E5%A6%B9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2142280.html  (11.4s)
>

**Comment by eva3357** [comment]
다운로드 아주 잘되고있습니다만??

**Comment by KurtBestor** [comment]
옵션에서 `갤러리 정보`를 `E(x)Hentai` 로 하셨네요
