### ISSUE TITLE
cant download from webtoon

### ISSUE THREAD

**Issue by raihanirfan** [KurtBestor/Hitomi-Downloader#4504]
version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / 2812fd75cd92423d82100a1b57efd464
input: https://www.webtoons.com/id/horror/guidao/list?title_no=874
type: webtoon
single: False
url: https://www.webtoons.com/id/horror/guidao/list?title_no=874
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1645639620.8056142 (Feb 24)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
motiontoon
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\webtoon_downloader", line 29, in read
 File "extractor\webtoon_downloader", line 138, in get_imgs_all
 File "<decorator-gen-92>", line 2, in get_imgs
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\webtoon_downloader", line 59, in get_imgs
NotImplementedError: motiontoon

Invalid: fail=True
quality: 100%
EOT: https://www.webtoons.com/id/horror/guidao/list?title_no=874  (2.6s)

motiontoon
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\webtoon_downloader", line 29, in read
 File "extractor\webtoon_downloader", line 138, in get_imgs_all
 File "<decorator-gen-92>", line 2, in get_imgs
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\webtoon_downloader", line 59, in get_imgs
NotImplementedError: motiontoon

Invalid: fail=True
quality: 100%
EOT: https://www.webtoons.com/id/horror/guidao/list?title_no=874  (2.9s)

how to solve ? thanks

**Comment by raihanirfan** [comment]
and this

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / 12fceed7d2b74b5bbd57bd5479bf4b1f
input: https://www.webtoons.com/id/horror/chiller/list?title_no=558
type: webtoon
single: False
url: https://www.webtoons.com/id/horror/chiller/list?title_no=558
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1645639727.0821202 (Feb 24)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

**Comment by raihanirfan** [comment]
this again

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / 5e9409571e884b149fc0ae9bc1bff3de
input: https://www.webtoons.com/id/horror/shriek/list?title_no=821
type: webtoon
single: False
url: https://www.webtoons.com/id/horror/shriek/list?title_no=821
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1645639767.6577423 (Feb 24)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
motiontoon
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\webtoon_downloader", line 29, in read
 File "extractor\webtoon_downloader", line 138, in get_imgs_all
 File "<decorator-gen-92>", line 2, in get_imgs
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\webtoon_downloader", line 59, in get_imgs
NotImplementedError: motiontoon

Invalid: fail=True
quality: 100%
EOT: https://www.webtoons.com/id/horror/shriek/list?title_no=821  (3.9s)

**Comment by raihanirfan** [comment]
version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / cd31c405345c4258a53b98ffb0427652
input: https://www.webtoons.com/id/horror/pandemi/list?title_no=2295
type: webtoon
single: False
url: https://www.webtoons.com/id/horror/pandemi/list?title_no=2295
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1645640120.5106323 (Feb 24)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
motiontoon
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\webtoon_downloader", line 29, in read
 File "extractor\webtoon_downloader", line 138, in get_imgs_all
 File "<decorator-gen-92>", line 2, in get_imgs
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\webtoon_downloader", line 59, in get_imgs
NotImplementedError: motiontoon

Invalid: fail=True
quality: 100%
EOT: https://www.webtoons.com/id/horror/pandemi/list?title_no=2295  (2.9s)

**Comment by KurtBestor** [comment]
Motion toon is not implemented
