### ISSUE TITLE
syosetu error

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#4507]
Invalid: [syosetu] https://ncode.syosetu.com/n0037/

version: 3.7i (22-02-04 05:01:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 4257 / False / 4c1357dc3b1146d79d4ed3f75f227d8a
input: https://ncode.syosetu.com/n0037/
type: syosetu
single: False
url: https://ncode.syosetu.com/n0037/
dir: 
zip: 
artist: 電光石火スパイラル
valid / done: False / True
range / range_p: ~200000 / None
time: 1645679706.0951135 (22-02-24 05:15:06 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_session
skip: https://ncode.syosetu.com/n0037a/1/
skip: https://ncode.syosetu.com/n0037a/2/
skip: https://ncode.syosetu.com/n0037a/3/
single: False
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1261, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://ncode.syosetu.com/n0037/  (1.4s)

get_session
skip: https://ncode.syosetu.com/n0037a/1/
skip: https://ncode.syosetu.com/n0037a/2/
skip: https://ncode.syosetu.com/n0037a/3/
single: False
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1261, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://ncode.syosetu.com/n0037/  (1.7s)

get_session
skip: https://ncode.syosetu.com/n0037a/1/
skip: https://ncode.syosetu.com/n0037a/2/
skip: https://ncode.syosetu.com/n0037a/3/
single: False
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1261, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://ncode.syosetu.com/n0037/  (3.2s)

get_session
skip: https://ncode.syosetu.com/n0037a/1/
skip: https://ncode.syosetu.com/n0037a/2/
skip: https://ncode.syosetu.com/n0037a/3/
single: False
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1261, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://ncode.syosetu.com/n0037/  (2.1s)

**Comment by KurtBestor** [comment]
You have to input the list URL: https://ncode.syosetu.com/n9999b
