### ISSUE TITLE
시작과 저장시 오류가 납니다

### ISSUE THREAD

**Issue by potatotatota** [KurtBestor/Hitomi-Downloader#4509]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 3897, in append_datas_
Exception: No data

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 3897, in append_datas_
Exception: No data

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1559, in foo
  File "MyConfigParser", line 78, in get
sqlite3.DatabaseError: database disk image is malformed

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1559, in foo
  File "MyConfigParser", line 78, in get
sqlite3.DatabaseError: database disk image is malformed

시작시에는 이런식으로 나오고
![image](https://user-images.githubusercontent.com/66310348/155574793-4463f1ec-79b0-4802-b9a6-75361f8fc13a.png)

저장시에는 이런식으로 나오네요
완전히 지우는것 말고는 방법이 없을까요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1512

**Comment by potatotatota** [comment]
답변 감사합니다
