### ISSUE TITLE
익헨에만 남아있는 작품들이 다운 되지 않습니다.

### ISSUE THREAD

**Issue by sadboiikari** [KurtBestor/Hitomi-Downloader#4539]
안녕하세요. 항상 잘 이용하고 있습니다만 이헨과 히토미에서 잘린 작품들이 다운되지 않는 현상을 겪어 문의 드립니다.
익헨과 히요비에서는 작품 감상이 가능한 상태입니다.

Invalid: [hitomi] https://exhentai.org/s/ba94de2976/2133853

version: 3.7i (22-02-17 16:08:32 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 7e80f961a17f49f0acf6115268dbf256
input: https://exhentai.org/s/ba94de2976/2133853
type: ehen
single: False
url: https://exhentai.org/s/ba94de2976/2133853
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1646520437.380578 (22-03-05 22:47:17 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
using custom cookies
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

FINAL SERVER: ehen
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 622, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://exhentai.org/s/ba94de2976/2133853  (22.3s)

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/s/ba94de2976/2133853)
Traceback (most recent call last):
 File "hitomi_downloader", line 578, in read
 File "hitomi_downloader", line 441, in get_imgs
 File "extractor\ehen_downloader", line 156, in ehen_imgs
IndexError: list index out of range

FINAL SERVER: ehen
ehen_url: None
imgs: 0
Traceback (most recent call last):
 File "hitomi_downloader", line 622, in read
Exception: no imgs

stop
Invalid: fail=True
stop
EOT: https://exhentai.org/s/ba94de2976/2133853  (65.4s)

**Comment by KurtBestor** [comment]
주소가 잘못되었는데 https://e-hentai.org/s/ba94de2976/2133853 말고 https://exhentai.org/s/ba94de2976/2133853-37 로 입력해주세요
