### ISSUE TITLE
pawoo 에러.

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader#4553]
pixiv연계사이트인 pawoo다운이 에러뜨면서 안됩니다.
어떻게 해야 하나요;

Invalid: [pawoo] https://pawoo.net/@suos1080

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 413 / False / f6adb8910b3d439eb06a6142ba19bde0
input: https://pawoo.net/@suos1080
type: pawoo
single: False
url: https://pawoo.net/@suos1080
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~90000000 / None
time: 1646812712.955203 (3월 9일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.03.08.2
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'media'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pawoo_downloader", line 37, in read
 File "mastodon", line 59, in get_imgs
KeyError: 'media'

Invalid: fail=True
EOT: https://pawoo.net/@suos1080  (7.4s)

'media'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pawoo_downloader", line 37, in read
 File "mastodon", line 59, in get_imgs
KeyError: 'media'

Invalid: fail=True
EOT: https://pawoo.net/@suos1080  (6.4s)

'media'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pawoo_downloader", line 37, in read
 File "mastodon", line 59, in get_imgs
KeyError: 'media'

Invalid: fail=True
EOT: https://pawoo.net/@suos1080  (6.7s)

'media'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pawoo_downloader", line 37, in read
 File "mastodon", line 59, in get_imgs
KeyError: 'media'

Invalid: fail=True
EOT: https://pawoo.net/@suos1080  (6.9s)

'media'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pawoo_downloader", line 37, in read
 File "mastodon", line 59, in get_imgs
KeyError: 'media'

Invalid: fail=True
EOT: https://pawoo.net/@suos1080  (6.8s)

**Comment by jinjins7** [comment]
위에것은 최신버전이고 이전 3.7d버전으로 한번 해봤는데 거기서는 또 됩니다. 무슨차이일까요;
