### ISSUE TITLE
히토미 다운로더 검색기 기본 데이터 다운로드 실패

### ISSUE THREAD

**Issue by Gyuuki3307** [KurtBestor/Hitomi-Downloader#4557]
![깃허브](https://user-images.githubusercontent.com/95686692/157866063-bc389ff7-9d40-4b3d-8f58-22fa0096d193.png)

검색기 기본 데이터 다운로드시 마무리 중... 20/20 에서 예상치 못환 오류로 실패했다고 뜹니다 (수차례 시도 해봐도 안 됨)

다운로더 새 버전으로 다운로드 해봐도 똑같은 현상이네요

아래는 오류 내용 입니다

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 3073, in dataDownload
  File "hitomi_searcher", line 323, in download_json
  File "tags", line 67, in finish
PermissionError: [Errno 13] Permission denied: 'E:\\hitomi_downloader_GUI\\hitomi_data\\tags.txt'

**Comment by Gyuuki3307** [comment]
해결완료 AVG 인터넷 시큐리티 사용중이며 백신 감시를 껏더니 데이터 다운이 정상으로 되길래 백신 설정에서 히토미 다운로더 파일을 예외로 등록 해뒀더니 백신 감시 켜놔도 다운로드 정상적으로 됩니다.

**Comment by rotlqkfsusdk** [comment]
저도 같은 오류인데 백신 꺼보고 예외 추가하고 경로 영어 확인도 해봤는데도 계속 문제가 생기네요
어떻게 해결해야 할까요?
