### ISSUE TITLE
익헨 원본이미지 다운로드를 키고 다운하면 파일이 정상적으로 다운되지 않습니다

### ISSUE THREAD

**Issue by Ojdd** [KurtBestor/Hitomi-Downloader#4563]
쿠키도 제대로 입력했는데 다운로드를 하면 파일이 죄다 손상된 파일로 다운되서 이미지가 보이지 않습니다 왜그런건가요?
![화면 캡처 2022-03-15 131327](https://user-images.githubusercontent.com/65504917/158305054-0e351406-b33f-48a1-a0f7-e736447bc376.png)

[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / ed956421d9d14fdfa6627d56b8a5c54d
input: 679308
type: ehen
single: False
url: https://exhentai.org/g/679308/7af09422c6
dir: 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)
zip: 
artist: akatsuki kochi
valid / done: True / True
range / range_p: None / None
time: 1647317192.4262557 (3월 15일)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.03.08.2
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 679308

제목: [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean]

작가: akatsuki kochi

그룹: cherry bomb g

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: female:defloration, female:loli, female:maid, female:netorare, female:stockings

언어: Korean

[File Names]
[0001] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0000.jpg
[0002] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0001.jpg
[0003] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0002.jpg
[0004] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0003.jpg
[0005] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0004.jpg
[0006] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0005.jpg
[0007] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0006.jpg
[0008] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0007.jpg
[0009] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0008.jpg
[0010] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0009.jpg
[0011] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0010.jpg
[0012] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0011.jpg
[0013] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0012.jpg
[0014] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0013.jpg
[0015] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0014.jpg
[0016] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0015.jpg
[0017] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0016.jpg
[0018] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0017.jpg
[0019] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0018.jpg
[0020] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0019.jpg
[0021] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0020.jpg
[0022] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0021.jpg
[0023] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0022.jpg
[0024] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0023.jpg
[0025] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0024.jpg
[0026] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0025.jpg
[0027] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0026.jpg
[0028] 다운로드\[Akatsuki Kochi] [Cherry Bomb G (Akatsuki Kochi)] Little Maiden [Korean] (679308)\0027.jpg

[URLs]
[0001] LazyUrl_ehen(https://exhentai.org/s/bfe6171e6c/679308-1)    --->    https://exhentai.org/fullimg.php?gid=679308&page=1&key=jg24us69t2s
[0002] LazyUrl_ehen(https://exhentai.org/s/1c6b675c02/679308-2)    --->    https://exhentai.org/fullimg.php?gid=679308&page=2&key=fi5cupl9t2s
[0003] LazyUrl_ehen(https://exhentai.org/s/29cb74c6cc/679308-3)    --->    https://exhentai.org/fullimg.php?gid=679308&page=3&key=he2gpdx9t2s
[0004] LazyUrl_ehen(https://exhentai.org/s/37cb0558f1/679308-4)    --->    https://exhentai.org/fullimg.php?gid=679308&page=4&key=c32pka39t2s
[0005] LazyUrl_ehen(https://exhentai.org/s/b629568130/679308-5)    --->    https://exhentai.org/fullimg.php?gid=679308&page=5&key=ad4xr1b9t2s
[0006] LazyUrl_ehen(https://exhentai.org/s/4db8e17e87/679308-6)    --->    https://exhentai.org/fullimg.php?gid=679308&page=6&key=ovs6dci9t2s
[0007] LazyUrl_ehen(https://exhentai.org/s/9f15c692a1/679308-7)    --->    https://exhentai.org/fullimg.php?gid=679308&page=7&key=mdzl4aa9t2s
[0008] LazyUrl_ehen(https://exhentai.org/s/97a791afea/679308-8)    --->    https://exhentai.org/fullimg.php?gid=679308&page=8&key=5m5mroj9t2s
[0009] LazyUrl_ehen(https://exhentai.org/s/35974b8a8d/679308-9)    --->    https://exhentai.org/fullimg.php?gid=679308&page=9&key=e8rad2d9t2s
[0010] LazyUrl_ehen(https://exhentai.org/s/1ef88091ed/679308-10)    --->    https://exhentai.org/fullimg.php?gid=679308&page=10&key=k7m4qix9t2s
[0011] LazyUrl_ehen(https://exhentai.org/s/9e04c1a288/679308-11)    --->    https://exhentai.org/fullimg.php?gid=679308&page=11&key=78k2ltz9t2s
[0012] LazyUrl_ehen(https://exhentai.org/s/51a1eb13e4/679308-12)    --->    https://exhentai.org/fullimg.php?gid=679308&page=12&key=598bljk9t2s
[0013] LazyUrl_ehen(https://exhentai.org/s/ab59d4503c/679308-13)    --->    https://exhentai.org/fullimg.php?gid=679308&page=13&key=fez0o6g9t2s
[0014] LazyUrl_ehen(https://exhentai.org/s/3500697825/679308-14)    --->    https://exhentai.org/fullimg.php?gid=679308&page=14&key=uyfaad39t2s
[0015] LazyUrl_ehen(https://exhentai.org/s/676d15e3b8/679308-15)    --->    https://exhentai.org/fullimg.php?gid=679308&page=15&key=1sz5ucz9t2s
[0016] LazyUrl_ehen(https://exhentai.org/s/2c1a92afc7/679308-16)    --->    https://exhentai.org/fullimg.php?gid=679308&page=16&key=6b1gx8o9t2s
[0017] LazyUrl_ehen(https://exhentai.org/s/1a7a746c92/679308-17)    --->    https://exhentai.org/fullimg.php?gid=679308&page=17&key=hm2m2o99t2s
[0018] LazyUrl_ehen(https://exhentai.org/s/a20ea9be40/679308-18)    --->    https://exhentai.org/fullimg.php?gid=679308&page=18&key=17nthc19t2s
[0019] LazyUrl_ehen(https://exhentai.org/s/27de338a40/679308-19)    --->    https://exhentai.org/fullimg.php?gid=679308&page=19&key=71jisz99t2s
[0020] LazyUrl_ehen(https://exhentai.org/s/c98b19f657/679308-20)    --->    https://exhentai.org/fullimg.php?gid=679308&page=20&key=0q3q8sd9t2s
[0021] LazyUrl_ehen(https://exhentai.org/s/7e3514764e/679308-21)    --->    https://exhentai.org/fullimg.php?gid=679308&page=21&key=2yebft09t2s
[0022] LazyUrl_ehen(https://exhentai.org/s/f8cc9b9679/679308-22)    --->    https://exhentai.org/fullimg.php?gid=679308&page=22&key=uvh7ux09t2s
[0023] LazyUrl_ehen(https://exhentai.org/s/9d422b4fbd/679308-23)    --->    https://exhentai.org/fullimg.php?gid=679308&page=23&key=n2lygb79t2s
[0024] LazyUrl_ehen(https://exhentai.org/s/676b0f5bd8/679308-24)    --->    https://exhentai.org/fullimg.php?gid=679308&page=24&key=ltcfcl49t2s
[0025] LazyUrl_ehen(https://exhentai.org/s/50199ca877/679308-25)    --->    https://exhentai.org/fullimg.php?gid=679308&page=25&key=f3msqei9t2s
[0026] LazyUrl_ehen(https://exhentai.org/s/a1bcb56cbd/679308-26)    --->    https://exhentai.org/fullimg.php?gid=679308&page=26&key=j7b5dij9t2s
[0027] LazyUrl_ehen(https://exhentai.org/s/5ba8d0c733/679308-27)    --->    https://exhentai.org/fullimg.php?gid=679308&page=27&key=ap42jh79t2s
[0028] LazyUrl_ehen(https://exhentai.org/s/f154a96207/679308-28)    --->    https://exhentai.org/fullimg.php?gid=679308&page=28&key=bo26w8t9t2s

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:679308)
Find_ehen(id:679308, ex:False)
Find in HK...
Found in HK: 7af09422c6
using custom cookies in find_ehen
#### https://e-hentai.org/g/679308/7af09422c6    ---->    https://e-hentai.org/g/679308/7af09422c6
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 587, in read
 File "hitomi_downloader", line 464, in get_imgs
 File "extractor\ehen_downloader", line 179, in ehen_imgs
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/679308/7af09422c6

get_imgs server: ehen
ehen_imgs(ex:True, url:679308)
Find_ehen(id:679308, ex:True)
Find in HK...
Found in HK: 7af09422c6
using custom cookies in find_ehen
#### https://exhentai.org/g/679308/7af09422c6    ---->    https://exhentai.org/g/679308/7af09422c6/?p=1
MPV: False
get_title_ehen: https://exhentai.org/g/679308/7af09422c6
FINAL SERVER: ehen
ehen_url: https://exhentai.org/g/679308/7af09422c6
imgs: 28
E-Hentai: https://exhentai.org/g/679308/7af09422c6

-ss 0.0 -noaccurate_seek -i "0000.jpg" -vframes 1 "C:\Users\kimbi\AppData\Local\Temp\tmp9fedf19a47364cc89a31809088b64386_o.png"
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
[mjpeg @ 000001faa47a4640] No JPEG data found in image 
[image2 @ 000001faa4792540] decoding for stream 0 failed 
[image2 @ 000001faa4792540] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size 
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options 
Input #0, image2, from '0000.jpg': 
 Duration: 00:00:00.04, start: 0.000000, bitrate: 14 kb/s 
 Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 fps, 25 tbr, 25 tbn 
Stream mapping: 
 Stream #0:0 -> #0:0 (mjpeg (native) -> png (native)) 
Press [q] to stop, [?] for help 
Cannot determine format of input stream 0:0 after EOF 
Error marking filters as finished 
Conversion failed! 
[code]
1
-ss 0.0 -noaccurate_seek -i "0000.jpg" -vframes 1 "C:\Users\kimbi\AppData\Local\Temp\tmpdcbe5ca2d1d84c649d4733d60adfe1ce_o.png"
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
[mjpeg @ 000001e314164640] No JPEG data found in image 
[image2 @ 000001e314152540] decoding for stream 0 failed 
[image2 @ 000001e314152540] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size 
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options 
Input #0, image2, from '0000.jpg': 
 Duration: 00:00:00.04, start: 0.000000, bitrate: 14 kb/s 
 Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 fps, 25 tbr, 25 tbn 
Stream mapping: 
 Stream #0:0 -> #0:0 (mjpeg (native) -> png (native)) 
Press [q] to stop, [?] for help 
Cannot determine format of input stream 0:0 after EOF 
Error marking filters as finished 
Conversion failed! 
[code]
1
stop
EOT: 679308  (46.4s)

**Comment by KurtBestor** [comment]
해당 파일 보내주시면 분석해볼게요

**Comment by Ojdd** [comment]
[[Herokey] [Kowareta Radio (Herokey)] Randoseru Enkou Nisshi ~Totsuka Torisha no Baai~ ｜ 란도셀 원교 일기 ~토츠카 트리샤의 경우 (1552324).zip](https://github.com/KurtBestor/Hitomi-Downloader/files/8308730/Herokey.Kowareta.Radio.Herokey.Randoseru.Enkou.Nisshi.Totsuka.Torisha.no.Baai.1552324.zip)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/159110517-0d7ce2e4-c204-4906-8b93-2cc5b9af60be.png)


계정이 정지되었다고 뜨네요
