### ISSUE TITLE
트위터 스페이스 라는게 있는데요 

### ISSUE THREAD

**Issue by dkfle222** [KurtBestor/Hitomi-Downloader#4578]
다운로드가 잘 안돼요

**Comment by jazzjackass** [comment]
https://github.com/HoloArchivists/twspace-dl
이거 쓰시면 됩니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by rokmc-hgc** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

악! 오류가 발생합니다!

현재 버전에서는 작동하지 않는 듯 합니다!

![Image](https://github.com/user-attachments/assets/17dfd1a0-4d35-4d75-b933-76ab4598f273)

```python
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 425, in _read
 File "m3u8_tools", line 412, in _read
ValueError: not mpegts
```

```python
setIcon failed:
Traceback (most recent call last):
 File "customWidget_new", line 2113, in setIcon
 File "customWidget_new", line 2124, in setIcon_
Exception: empty pixmap
```

```python
stop
quality: 100%
{

}
```

```python
Traceback (most recent call last):
 File "ffmpeg", line 878, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2018, in finish
 File "ffmpeg", line 881, in get_info
 File "ffmpeg", line 878, in get_info
Exception: Failed to convert; exit code: 1
```
