### ISSUE TITLE
트위치 다운이 안되네요.

### ISSUE THREAD

**Issue by ddsa2333** [KurtBestor/Hitomi-Downloader#4585]
Invalid: [twitter] https://twitter.com/erodougayaro

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / 795ebbf72a764aa48859e91e38ba1072
input: https://twitter.com/erodougayaro
type: twitter
single: False
url: https://twitter.com/erodougayaro
dir: 
zip: 
artist: エロ動画ヤロー
valid / done: False / True
range / range_p: None / None
time: 1647954081.129256 (3월 22일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.03.08.2
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
token type: <class 'str'>
generate csrf
multiple tweets
cursor: HBaKwNS9zNqBrCkAAA==
cursor: HBaIwNLxk+iP5SgAAA==
Skipping unavailable Tweet 1460199966865903622
Skipping unavailable Tweet 1459711234224259073
cursor: HBaIwLn13cOXvCgAAA==
Skipping unavailable Tweet 1456280166875820039
Skipping unavailable Tweet 1456205290592825344
Skipping unavailable Tweet 1455917786912280587
Skipping unavailable Tweet 1455872516711325696
Skipping unavailable Tweet 1455464783273074692
Skipping unavailable Tweet 1455162378522226689
Skipping unavailable Tweet 1455128155417505793
Skipping unavailable Tweet 1455102337584828423
Skipping unavailable Tweet 1455033531252424707
Skipping unavailable Tweet 1454830559260123147
Skipping unavailable Tweet 1454815443084931078
Skipping unavailable Tweet 1454785253210427412
Skipping unavailable Tweet 1454422866229805061
Skipping unavailable Tweet 1454392901710991368
Skipping unavailable Tweet 1454377547798487045
Skipping unavailable Tweet 1454105795612663812
Skipping unavailable Tweet 1454060611059412999
Skipping unavailable Tweet 1454015218439258115
Skipping unavailable Tweet 1453743458942742531
Skipping unavailable Tweet 1453698228986138626
Skipping unavailable Tweet 1453667996291850244
Skipping unavailable Tweet 1453652785958817802
Skipping unavailable Tweet 1453365890242650112
Skipping unavailable Tweet 1453335768659742722
Skipping unavailable Tweet 1453305604735393804
Skipping unavailable Tweet 1453290390933721093
Skipping unavailable Tweet 1453003508920328197
Skipping unavailable Tweet 1452928002409385987
Skipping unavailable Tweet 1452656433888063492
Skipping unavailable Tweet 1452641114964455427
cursor: HBaIgKzplq/GqCgAAA==
Skipping unavailable Tweet 1452293849108283393
Skipping unavailable Tweet 1451840842134528013
Skipping unavailable Tweet 1451569071716110340
Skipping unavailable Tweet 1451553955826188296
Skipping unavailable Tweet 1451493666032283650
Skipping unavailable Tweet 1451206713164529677
Skipping unavailable Tweet 1451161527420026882
Skipping unavailable Tweet 1451131655280685063
Skipping unavailable Tweet 1451025527792275457
Skipping unavailable Tweet 1450753681565962243
Skipping unavailable Tweet 1448603029784064000
Skipping unavailable Tweet 1448242063649116162
Skipping unavailable Tweet 1448084831229779971
cursor: HBaEwKit1qD3kigAAA==
cursor: HBaAgKmR+/n0+CcAAA==
Skipping unavailable Tweet 1437420833731797000
Skipping unavailable Tweet 1437254733836685312
Skipping unavailable Tweet 1436696069929246720
Skipping unavailable Tweet 1427103513574666244
Skipping unavailable Tweet 1427103503915261953
Skipping unavailable Tweet 1427065907587665920
cursor: HBaAwKrNubj6zScAAA==
Skipping unavailable Tweet 1427065899186413573
Skipping unavailable Tweet 1426812725645123584
Skipping unavailable Tweet 1426812409394593794
Skipping unavailable Tweet 1426725847067594755
Skipping unavailable Tweet 1426725836435050501
Skipping unavailable Tweet 1426541888182513668
Skipping unavailable Tweet 1426480442308325381
Skipping unavailable Tweet 1426050580955295747
Skipping unavailable Tweet 1423788542346481667
Skipping unavailable Tweet 1417991924334534656
Skipping unavailable Tweet 1417991881678417924
Skipping unavailable Tweet 1417438053707096065
Skipping unavailable Tweet 1417429353332285443
Skipping unavailable Tweet 1416636551136628739
Skipping unavailable Tweet 1416607657444601856
cursor: HBaGgKPlr+/0pycAAA==
Skipping unavailable Tweet 1415980267311747072
Skipping unavailable Tweet 1414546921104961540
Skipping unavailable Tweet 1414538700151607296
Skipping unavailable Tweet 1413671068515016708
Skipping unavailable Tweet 1412764567139012611
Skipping unavailable Tweet 1412019808439214080
cursor: HBaUwKuRsOOmkycAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/erodougayaro  (23.2s)

어느날부터 Invalid 뜨면서 안되요 ㅠ ㅠ

**Comment by ddsa2333** [comment]
트위치가 아니라 트위터 ...
