### ISSUE TITLE
Downloading from AfreecaTV fails

### ISSUE THREAD

**Issue by rexify0** [KurtBestor/Hitomi-Downloader#4599]
Starting from yesterday, AfreecaTV videos cannot be downloaded.  It seems AfreecaTV might have changed some url locations or parsing mechanism.

Attached please find the task info of a failed example for your information: 

Invalid: [afreeca] https://vod.afreecatv.com/player/83712825

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_tw
order / group / uid: 0 / False / fc2045a68179414da055cdb6a4aa2cc8
input: https://vod.afreecatv.com/player/83712825
type: afreeca
single: True
url: https://vod.afreecatv.com/player/83712825
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1648528399.5736852 (Mar 29)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.03.08.2
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
url_thumb: http://iflv14.afreecatv.com/save/afreeca/station/2022/0212/07/thumb/1644618861560425_L_7.jpg
404
stop
Traceback (most recent call last):
 File "downloader", line 381, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://stbbs.afreecatv.com:8080/api/video/get_video_info.php?type=station&isAfreeca=true&autoPlay=true&showChat=true&mutePlay=false&expansion=true&szBjId=ynpig12&nStationNo=21108140&nBbsNo=68726010&nTitleNo=83712825&szCategory=00210000&szVodCategory=00130000&szPart=NORMAL&nPlaylistIdx=0&path1=etc&path_key=f0a72abac24a26a52986e1042672b6e7_83712825_1648528443638&adultView=ADULT_VIEW&_=1648528406590

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\afreeca_downloader", line 37, in read
 File "<decorator-gen-50>", line 2, in get_video
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\afreeca_downloader", line 69, in get_video
 File "downloader", line 442, in read_html
Exception: 404

Invalid: fail=True
EOT: https://vod.afreecatv.com/player/83712825  (7.5s)

**Comment by gibson-kim** [comment]
Having the same problem with https://vod.afreecatv.com/player/85602958 (requires adult verified account. these kinds of clips used to download easily with hitomi downloader)
Loaded site cookies again but still doesn't work.
Afreeca recently changed its clip discovery system, might be the reason why.

**Comment by rexify0** [comment]
It seems to work again...
