### ISSUE TITLE
현재, Danbooru 안 되네요.

### ISSUE THREAD

**Issue by saulmir** [KurtBestor/Hitomi-Downloader#4602]
겔부루는 잘 됩니다만, 단부루는 로그인도 해 봤지만 안 되네요.

Invalid: [danbooru] https://danbooru.donmai.us/posts/5233332

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / b0129d0de3ec4fbfa892bb7635858149
input: https://danbooru.donmai.us/posts/5233332
type: danbooru
single: False
url: https://danbooru.donmai.us/posts/5233332
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1648614339.0609386 (3월 30일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.03.08.2
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Not Implemented
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 117, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://danbooru.donmai.us/posts/5233332  (0.7s)

**Comment by KurtBestor** [comment]
단일 포스트는 지원하지 않아요

**Comment by saulmir** [comment]
아, 그렇네요. 확인하니 tags에 대해서 인식하는 거였군요. 감사합니다.
