### ISSUE TITLE
제이마나 다운이 안되네요

### ISSUE THREAD

**Issue by grapite** [KurtBestor/Hitomi-Downloader#4619]
막힌것 같습니다

**Comment by duach** [comment]
가뭄에 콩나듯이 되네요 ㅎㅎ;;

**Comment by romi242** [comment]
제이마나 몇일전부터  아예 다운이 안되네요..  방금 여러개 테스트 해봤는데  다 빨간색에서       재시작 10번 이상 했는데  그대로네요...

에러 로그 남깁니다.



1분 51초 뒤 다시 시작: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84

version: 3.7i (21-12-27 16:14:26 UTC)

input: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84
type: jmana
single: False
url: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1649671457.846145 (4월 11일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (11.3s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (15.0s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (10.1s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (10.3s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (9.6s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (9.4s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (9.9s)

('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "downloader", line 369, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1142, in start
 File "utils", line 1212, in start_
 File "extractor\jmana_downloader", line 85, in read
 File "extractor\jmana_downloader", line 79, in name
 File "extractor\jmana_downloader", line 72, in soup
 File "downloader", line 409, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 182, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (1.4s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (9.6s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (9.5s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1155, in start
 File "utils", line 1225, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EC%A0%95%EB%A7%90+%EB%82%B4%EA%B0%80+%EC%A2%8B%EC%95%84  (9.4s)
