### ISSUE TITLE
마나토끼에서 다운이 안되는 것 같습니다. 

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#4654]
Invalid: [manatoki] https://manatoki127.net/comic/11944521

version: 3.7i (22-04-12 02:09:41 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / 8a0c1b187e1d49dca70236f5f5054911
input: https://manatoki127.net/comic/11944521
type: manatoki
single: False
url: https://manatoki127.net/comic/11944521
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1649937915.1745677 (22-04-14 12:05:15 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "<decorator-gen-93>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 577, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki127.net/comic/11944521  (13.7s)

**Comment by mita5549** [comment]
오랜만에 하려고 했더니 잘 안되네요.
무엇이 문제인가요?ㄷㄷ

**Comment by mita5549** [comment]
문제가 저절로 해결되었습니다; 
 오늘, 다운로드 링크 주소의 일부가 toki127에서, toki128로 변경되었는데, 변경 된 128로 시도를 하니 되네요! 
 다행히 사이트 문제였던 것 같아요. 즐거운 하루 되세요!
