### ISSUE TITLE
마나토끼 다운이 안됩니다.

### ISSUE THREAD

**Issue by hohoe** [KurtBestor/Hitomi-Downloader#4661]
오늘 들어가 보니 만화목록을 누르면 없던 캡챠인증이 생겼네요
그 이후 다운이 안됩니다
작업정보는 다음과 같습니다.

Invalid: [manatoki] https://manatoki128.net/comic/242519

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / c45064d605e44b53b970996cc564c891
input: https://manatoki128.net/comic/242519
type: manatoki
single: False
url: https://manatoki128.net/bbs/captcha.php
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1650278504.891309 (4월 18일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 577, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki128.net/comic/242519  (17.8s)

**Comment by Mango202** [comment]
이미지 수집 프로그램을 사용하는 경우가 많아져서 서버에 부하를 가중시키는 요인이 되고 있습니다.
이를 차단하기 위해 적용되었으며, 로그인한 경우는 캡챠 입력없이 사이트 이용이 가능합니다.
비로그인 상태인 경우 최신 만화에 한해 캡챠를 통과해야 합니다. 한번 통과하면 3시간 동안 유효합니다.

이렇다고 합니다. 서버 부하 줄인다고 캡차 도입했네요.

**Comment by hohoe** [comment]
답변 감사합니다. 공교롭게 아래글과 거의 동시에 올라와서:::

아래글 #4660 답변에 해결책도 있고 따라서 하니 잘되네요. 여기도 이제 가입 및 로그인해야 원활하게 사용 할 수 있을 듯 합니다.
