### ISSUE TITLE
기본 데이터 다운로드 오류

### ISSUE THREAD

**Issue by ssllyy22** [KurtBestor/Hitomi-Downloader#4675]
Traceback (most recent call last):
  File "downloader", line 399, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 641, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 210, in download_json
  File "hitomi_searcher", line 372, in download_json_
  File "downloader", line 432, in read_html
  File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://kurtpyanywhere.com/h_data

오늘 갑자기 뜬 오류 내용인데 해결방법이 있을까요?

**Comment by movomo** [comment]
저도 마찬가지입니다.

**Comment by imKota** [comment]
@ssllyy22 same problem

**Comment by melan1729** [comment]
저도 동일한 오류가 뜹니다.

**Comment by imKota** [comment]
Domine not registred 
![image](https://user-images.githubusercontent.com/24241471/164642040-e4c66985-eb2b-4c4f-9fdc-82b34d02571f.png)

**Comment by KurtBestor** [comment]
고쳤어요

**Comment by geohanjokyo** [comment]
업데이트는 언재 적용될 예정일까요?

**Comment by KurtBestor** [comment]
업데이트 필요 없는 문제예요 지금 바로 될거예요

**Comment by moon70717** [comment]
재발생하였습니다.
