### ISSUE TITLE
be noticed "invalid" or get stuck at "reading"

### ISSUE THREAD

**Issue by 0519-Echo** [KurtBestor/Hitomi-Downloader#4677]
creating missions by pasting URLs from BILIBILI.COM, I'm frequently noticed that it's [invalid], or the mission just gets stuck at [reading...] forEVER (as shown in the pics)
![微信图片_20220421230038](https://user-images.githubusercontent.com/104153307/164590392-5d3d8deb-b7ae-4461-b8ee-48ef63a8c049.png)
![微信图片_202204212300381](https://user-images.githubusercontent.com/104153307/164590393-a86f274c-8be3-43be-b82f-3f94f9039558.png)

Task info for [invalid] is like this↓
————————————————————————
[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1ax411D7cG?p=3 -> https://www.bilibili.com/video/BV1ax411D7cG/?p=3
cid: 16382404
403 Client Error: Forbidden for url: http://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=16382404&otype=json&qn=116&quality=116&type=&sign=6508c1da00fa664973bf448b4bcc3285
stop
Traceback (most recent call last):
 File "downloader", line 399, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\bili_downloader", line 89, in read
 File "extractor\bili_downloader", line 190, in get_videos
 File "downloader", line 432, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=16382404&otype=json&qn=116&quality=116&type=&sign=6508c1da00fa664973bf448b4bcc3285

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1ax411D7cG?p=3  (1.5s)
——————————————————
Is it due to my net connection? cuz some other times it's rather smooth...

**Comment by shellcmd89** [comment]
i got some strange question too. i can download your bilibili link video. maybe you should delete your task and retry ,maybe it will work.

**Comment by 0519-Echo** [comment]
> i got some strange question too. i can download your bilibili link video. maybe you should delete your task and retry ,maybe it will work.

it's really weird when it comes to retrying... For the same video link, sometimes I refresh the task within Hitomi and then it works, or in rare occasions refreshing the bilibili website and pasting again also helps. But in most cases, a particular link just can't get through no matter how many times I retry/refresh >.<

**Comment by shellcmd89** [comment]
en , several  little bugs . i usually delete the task , close the hitomi gui and retry , when yt-dlp is loading (left lower corner) it maybe not work 。you should paste the link when yt-dlp loaded and  start yout download . if not work , close the gui and  retry again and again.  :D
