### ISSUE TITLE
제이마나도 안되네요. 도움...!!!!;ㅁ; 

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#4681]
뭔가 액이 꼈나. 오전엔 딜레이 없이 팍팍 되더니, 퇴근하고 오니까 죄다 뻘건줄이 가득하네요.
프로그램 실행 없이 들어가지는걸 보니까 사이트 차단은 아니던데, 구조가 바뀐걸까요?
 
 ==============
 Invalid: [jmana] https://www.jmana1.net/bookdetail?bookdetailid=519559

version: 3.7i (22-04-22 06:05:43 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / eebf9a097fd4484fac28e897aa460ca3
input: https://www.jmana1.net/bookdetail?bookdetailid=519559
type: jmana
single: False
url: https://www.jmana1.net/bookdetail?bookdetailid=519559
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1650627452.833846 (22-04-22 11:37:32 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://www.jmana1.net/bookdetail?bookdetailid=519559  (8.2s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://www.jmana1.net/bookdetail?bookdetailid=519559  (9.1s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://www.jmana1.net/bookdetail?bookdetailid=519559  (3.5s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://www.jmana1.net/bookdetail?bookdetailid=519559  (3.3s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://www.jmana1.net/bookdetail?bookdetailid=519559  (3.3s)

**Comment by mita5549** [comment]
어?ㅡㅡ;;;아?;;;
지인이 주소를 잘못 알려줬나봐요. 
https://www.jmana1.net/ 가 아니라 https://jjmana.net/네요... 
접속은 되는데 뭐지.... 죄송합니다;;;

**Comment by mita5549** [comment]
어...... 어떻게 찾다보니까 해결이 됐습니다.

구글에서 제이마나로 들어가면 https://jmana1.net/ 로 링크가 나오는데, 접속은 되지만, 다운로드를 하려고 링크를 집어넣으면 다운로드가 안됩니다.
그런데 어쩌다 찾은 https://jjmana.net/comic_recent 사이트로 링크를 바꾸니까 다운로드가 되네요.....?|
뭔 상황인지 모르겠습니다만 해결이 ... 됐습니다. 

https://jmana1.net/bookdetail?bookdetailid=519560
https://jjmana.net/bookdetail?bookdetailid=519560
