### ISSUE TITLE
트위터 일부 다운이 안됩니다

### ISSUE THREAD

**Issue by bovineserum** [KurtBestor/Hitomi-Downloader#4683]
어떤 기준인지 모르겠는데 되는게 있고 안되는게 있습니다 같은방식으로했는데

**Comment by mechu1205** [comment]
작업 실패 로그 몇개 첨부합니다
```
Invalid: [twitter] https://twitter.com/redhod2os

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 50 / False / 5d1bb0e2ec0046959ab53f84bf0773bf
input: https://twitter.com/redhod2os
type: twitter
single: False
url: https://twitter.com/redhod2os
dir: 
zip: 
artist: Dormicum
valid / done: False / True
range / range_p: None / None
time: 1650732384.3029428 (4월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
generate csrf
multiple tweets
Skipping unavailable Tweet 1481952392946266113
Skipping unavailable Tweet 1474429384195198977
Skipping unavailable Tweet 1380939020650172416
Skipping unavailable Tweet 1373262381711716352
Skipping unavailable Tweet 1351827579775328257
Skipping unavailable Tweet 1340330172004720641
Skipping unavailable Tweet 1332679687789715456
cursor: HBaCgKP54Zic7yQAAA==
Skipping unavailable Tweet 1317887860528144384
Skipping unavailable Tweet 1306657370261520385
Skipping unavailable Tweet 1286461679929184257
Skipping unavailable Tweet 1281978941461327872
Skipping unavailable Tweet 1274162379916341252
Skipping unavailable Tweet 1273964335476305920
Skipping unavailable Tweet 1273584307093647360
Skipping unavailable Tweet 1272523181882920960
Skipping unavailable Tweet 1266318769749540864
Skipping unavailable Tweet 1263132193678749702
Skipping unavailable Tweet 1260768272955269120
Skipping unavailable Tweet 1251154411310608391
cursor: HBamwLW5+MX6gSIAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/redhod2os  (41.7s)

generate csrf
multiple tweets
Skipping unavailable Tweet 1481952392946266113
Skipping unavailable Tweet 1474429384195198977
Skipping unavailable Tweet 1401205198035423240
Skipping unavailable Tweet 1396393278027616257
Skipping unavailable Tweet 1396286353390768129
Skipping unavailable Tweet 1391373602944032768
Skipping unavailable Tweet 1380939020650172416
Skipping unavailable Tweet 1373262381711716352
Skipping unavailable Tweet 1351827579775328257
Skipping unavailable Tweet 1342715993936695296
Skipping unavailable Tweet 1340330172004720641
cursor: HBaCgKOBlcznmSUAAA==
Skipping unavailable Tweet 1332679687789715456
Skipping unavailable Tweet 1330728184531206147
Skipping unavailable Tweet 1326906932154740739
Skipping unavailable Tweet 1317887860528144384
Skipping unavailable Tweet 1306657370261520385
Skipping unavailable Tweet 1286461679929184257
Skipping unavailable Tweet 1281978941461327872
Skipping unavailable Tweet 1274162379916341252
Skipping unavailable Tweet 1273964335476305920
Skipping unavailable Tweet 1273584307093647360
Skipping unavailable Tweet 1272523181882920960
Skipping unavailable Tweet 1266318769749540864
Skipping unavailable Tweet 1263132193678749702
Skipping unavailable Tweet 1260768272955269120
Skipping unavailable Tweet 1251154411310608391
cursor: HBamwLW5+MX6gSIAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/redhod2os  (24.3s)

Invalid: [twitter] https://twitter.com/redhod2os

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 50 / False / 5d1bb0e2ec0046959ab53f84bf0773bf
input: https://twitter.com/redhod2os
type: twitter
single: False
url: https://twitter.com/redhod2os
dir: 
zip: 
artist: Dormicum
valid / done: False / True
range / range_p: None / None
time: 1650732384.3029428 (4월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
generate csrf
multiple tweets
Skipping unavailable Tweet 1481952392946266113
Skipping unavailable Tweet 1474429384195198977
Skipping unavailable Tweet 1380939020650172416
Skipping unavailable Tweet 1373262381711716352
Skipping unavailable Tweet 1351827579775328257
Skipping unavailable Tweet 1340330172004720641
Skipping unavailable Tweet 1332679687789715456
cursor: HBaCgKP54Zic7yQAAA==
Skipping unavailable Tweet 1317887860528144384
Skipping unavailable Tweet 1306657370261520385
Skipping unavailable Tweet 1286461679929184257
Skipping unavailable Tweet 1281978941461327872
Skipping unavailable Tweet 1274162379916341252
Skipping unavailable Tweet 1273964335476305920
Skipping unavailable Tweet 1273584307093647360
Skipping unavailable Tweet 1272523181882920960
Skipping unavailable Tweet 1266318769749540864
Skipping unavailable Tweet 1263132193678749702
Skipping unavailable Tweet 1260768272955269120
Skipping unavailable Tweet 1251154411310608391
cursor: HBamwLW5+MX6gSIAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/redhod2os  (41.7s)

generate csrf
multiple tweets
Skipping unavailable Tweet 1481952392946266113
Skipping unavailable Tweet 1474429384195198977
Skipping unavailable Tweet 1401205198035423240
Skipping unavailable Tweet 1396393278027616257
Skipping unavailable Tweet 1396286353390768129
Skipping unavailable Tweet 1391373602944032768
Skipping unavailable Tweet 1380939020650172416
Skipping unavailable Tweet 1373262381711716352
Skipping unavailable Tweet 1351827579775328257
Skipping unavailable Tweet 1342715993936695296
Skipping unavailable Tweet 1340330172004720641
cursor: HBaCgKOBlcznmSUAAA==
Skipping unavailable Tweet 1332679687789715456
Skipping unavailable Tweet 1330728184531206147
Skipping unavailable Tweet 1326906932154740739
Skipping unavailable Tweet 1317887860528144384
Skipping unavailable Tweet 1306657370261520385
Skipping unavailable Tweet 1286461679929184257
Skipping unavailable Tweet 1281978941461327872
Skipping unavailable Tweet 1274162379916341252
Skipping unavailable Tweet 1273964335476305920
Skipping unavailable Tweet 1273584307093647360
Skipping unavailable Tweet 1272523181882920960
Skipping unavailable Tweet 1266318769749540864
Skipping unavailable Tweet 1263132193678749702
Skipping unavailable Tweet 1260768272955269120
Skipping unavailable Tweet 1251154411310608391
cursor: HBamwLW5+MX6gSIAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/redhod2os  (24.3s)
```
```
Invalid: [twitter] https://twitter.com/tokuma_kumma

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 49 / False / b9c3d0e9213e4755b94b7b3191645554
input: https://twitter.com/tokuma_kumma
type: twitter
single: False
url: https://twitter.com/tokuma_kumma
dir: 
zip: 
artist: とくま🐻
valid / done: False / True
range / range_p: None / None
time: 1650732400.709943 (4월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
generate csrf
multiple tweets
cursor: HBaKwKPd8YjvgSYAAA==
Skipping unavailable Tweet 1366262409573269506
Skipping unavailable Tweet 1366004625669640195
Skipping unavailable Tweet 1365612411781214219
Skipping unavailable Tweet 1364183944166395906
Skipping unavailable Tweet 1363799464306036743
Skipping unavailable Tweet 1363445383850942467
Skipping unavailable Tweet 1362693961173721095
Skipping unavailable Tweet 1358720489137590274
Skipping unavailable Tweet 1356543600801185795
Skipping unavailable Tweet 1354404146997125125
Skipping unavailable Tweet 1350778276596256769
Skipping unavailable Tweet 1349333186954711042
Skipping unavailable Tweet 1346804231412432897
Skipping unavailable Tweet 1342066805859209216
Skipping unavailable Tweet 1341626603579686914
Skipping unavailable Tweet 1336619862517555200
Skipping unavailable Tweet 1335888039906709506
Skipping unavailable Tweet 1335537431009882116
Skipping unavailable Tweet 1335197124821090304
Skipping unavailable Tweet 1330873116541652998
Skipping unavailable Tweet 1329042132707942401
Skipping unavailable Tweet 1327953960477417472
Skipping unavailable Tweet 1327224367487410177
Skipping unavailable Tweet 1326460439312490497
Skipping unavailable Tweet 1325280782781276161
Skipping unavailable Tweet 1322156118492110848
Skipping unavailable Tweet 1321735677684273152
Skipping unavailable Tweet 1319620844692275200
Skipping unavailable Tweet 1318536007050883073
Skipping unavailable Tweet 1317083665818554375
Skipping unavailable Tweet 1313817661101412352
Skipping unavailable Tweet 1312737298237190148
Skipping unavailable Tweet 1311652057720348672
Skipping unavailable Tweet 1305796866903126020
Skipping unavailable Tweet 1304645543923077120
Skipping unavailable Tweet 1304021887136063493
Skipping unavailable Tweet 1300744168310857728
Skipping unavailable Tweet 1298022296121155584
Skipping unavailable Tweet 1297375274741510145
Skipping unavailable Tweet 1296937665804156928
Skipping unavailable Tweet 1296425121486442496
Skipping unavailable Tweet 1290875437309022208
cursor: HBaAwKah3peO6iMAAA==
Skipping unavailable Tweet 1282290391367049216
Skipping unavailable Tweet 1281194144459747329
Skipping unavailable Tweet 1280079301325385730
Skipping unavailable Tweet 1279451878854553600
Skipping unavailable Tweet 1267042405531807744
cursor: HBaAwKC91OO4kCMAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/tokuma_kumma  (76.6s)

generate csrf
multiple tweets
Skipping unavailable Tweet 1503724164141940740
Skipping unavailable Tweet 1392797151441285123
cursor: HBaAgKORq+zLiSYAAA==
Skipping unavailable Tweet 1363445383850942467
cursor: HBaAwKC91OO4kCMAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/tokuma_kumma  (24.3s)
```
```
Invalid: [twitter] https://twitter.com/huhuhu13422

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 48 / False / 06ce1ecb35bd4fd88a5fb7736fcf001b
input: https://twitter.com/huhuhu13422
type: twitter
single: False
url: https://twitter.com/huhuhu13422
dir: 
zip: 
artist: ミコジン
valid / done: False / True
range / range_p: None / None
time: 1650732281.8169432 (4월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
generate csrf
multiple tweets
cursor: HBaIgKql3vS02CgAAA==
cursor: HBaMgK3hksLQjCcAAA==
cursor: HBaCgKydzKH6iCUAAA==
cursor: HBaAgKatj4aq8CMAAA==
cursor: HBaWwKb13NuIxyIAAA==
cursor: HBaAgK+d9dfrmRsAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 559, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/huhuhu13422  (58.6s)
```
