### ISSUE TITLE
다시 다운받았던 내용이 다시 없어졌습니다.

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4688]
얼마 전에 절반 날아간 사람입니다. 디스코드로 주로 대화했었던 걸 기억하실겁니다. 심지어 어제인가 그저께
https://github.com/KurtBestor/Hitomi-Downloader/issues/4682
이것도 올렸었으니까요.

위의 링크에서 다운로더를 새로 수정해서 올려주셨기에 저는 기존 프로그램에서 당연히 저장을 해놓고, 프로그램을 종료한 후 위의 것을 다운로드 하여 적용하였습니다.

보기에는 평소랑 똑같이 실행되었습니다만..

![image](https://user-images.githubusercontent.com/74286087/164966537-9937bfb7-2f5d-4d3c-b29c-26fe1389b2d0.png)

매우 당황스럽습니다. 기억하실지는 모르겠지만, 지금 사라진 내용이 정확히 저번에 사라졌던 부분까지 사라졌습니다. 

저번에 제가 밑부분은 사라지지 않고 윗부분만 통째로 날아갔다고 말씀드렸었는데, 

즉 이번에도 제가 제일 밑쪽에 정리해 놓은 부분은 사라지지 않았습니다.

![image](https://user-images.githubusercontent.com/74286087/164966802-4c59240a-5861-4388-8887-288f9f5f1e75.png)

다운로더를 새로 적용하기 30분 전 즈음에 다운로드 받아놓았던 히토미입니다.

![image](https://user-images.githubusercontent.com/74286087/164966557-3bdcd1c9-f2d3-42f6-8a68-d3a7472aefa9.png)

이번에는 그래도 사라진 내용이 많지가 않아서 detail은 적은 것 같습니다만,,

일단 알게 된 것이 저번에 저는 Err이 뜬 이후 자동저장이 되어서 로딩되지 못한 윗부분이 없는 채로 ini파일에 저장되었다.라고 생각했습니다만, 이번에 제대로 확인한 게 Err이 뜬 이후부터는 저장을 하지 않아도 계속 윗부분이 없어져있는 상태, 즉 Err뜨는 순간 ini파일이 수정되는 것처럼 보였습니다.

지속적으로 이런 일이 발생하는 이유를 모르겠습니다.

이정도면 한번 조사해 주시면 안되겠습니까? 아니면 ini파일을 복구할 수 있게라도 조치를 해주시면 안되겠습니까?

이렇게 주기적으로 사라지는 건 솔직히 버그라고 봅니다;;

**Comment by KurtBestor** [comment]
다른 사용자에게서 같은 증상이 보고된 적이 없고, 저도 5년 이상 썼는데 한번도 그런 적이 없어서 어떻게 할 수가 없네요

오류 내용으로 보자면 목록 ID는 읽었는데 ID 에 대응하는 데이터 (제목, 파일 리스트, etc.) 를 읽을 때 오류가 뜨는데요

설정 파일 DB는 SQLite 를 쓰는데 검색해봐도 해당 증상은 없고 일부가 소실되는 게 아닌 정확히 특정 시점으로 돌아가는 걸로 봐서, 제가 생각하기엔 다음과 같은 경우가 있을 것 같아요:
- 프로그램 실행
- 설정 파일에서 목록 ID 읽음
- 백신이 의심스러운 프로그램의 파일 읽기/쓰기를 감지하고 해당 파일을 예전에 백업했던 파일로 복구함
- 새로운 ID 에 대응하는 데이터를 읽지 못하고 오류 발생

**Comment by hwnnhji** [comment]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 10444, in <module>
  File "hitomi_server\__init__", line 389, in start
  File "hitomi_server\__init__", line 348, in join
  File "hitomi_server\__init__", line 341, in run
  File "decorator", line 232, in fun
  File "locker", line 63, in _wrapper
  File "hitomi_server\__init__", line 372, in switch
  File "hitomi_server\__init__", line 364, in switch
  File "hitomi_server\__init__", line 101, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 137, in server_bind
  File "socketserver", line 466, in server_bind
OSError: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다

![제목 없음](https://user-images.githubusercontent.com/74286087/232412479-1ec517ff-14ce-467e-94d8-e683e7f9f693.jpg)

항상 좋은 프로그램 만들어 주셔서 감사합니다. 너무 프로그램 잘 사용하고 있습니다. 개발자님 덕분에 도움받는 사람들이 많은 것 같습니다. 감사합니다.

처음에 Err에러가 떴을 때 거의 2년 가까이 자료를 모아놓고, 나름 엄청 좋은 프로그램이라고 생각해서 평소 사용하는 자료 자체를 이 프로그램을 이용해서 관리를 했었다가 Err에러와 함께 작업목록 절반이 통으로 날아가는 바람에 진짜 멘탈 완전 털리고 너무 당황해서
https://github.com/KurtBestor/Hitomi-Downloader/issues/4596
https://github.com/KurtBestor/Hitomi-Downloader/issues/4682
4596과 4682, 현재 4688 이렇게 3개를 당시 이슈로 올렸었습니다. 이때는 진짜 너무 멘탈이 터져서 디스코드 dm까지 보내고 어떻게 해결 방법이 없겠냐 하는 마음에 귀찮게 해드렸습니다만,, 그땐 죄송했습니다.

다시 이 말을 꺼내는 이유가 이번에는 예전의 작업목록 읽기랑은 다른 종류의 문제라고는 생각합니다만 http서버 시작에 실패했다는 문구와 함께 작업목록이 전체적으로 섞였습니다. 엄청 심하게 뒤섞였단 느낌보단 

![image](https://user-images.githubusercontent.com/74286087/232415038-c74fc5e8-4397-4946-8cc0-e9ef3e8d0cd8.png)

중간에 manatoki 밑의 히토미 부터는 전 따로 그룹을 만들어서 관리를 해서 전부 정리를 해놨던 상황입니다만, Err과 함께 위로 올라왔습니다. 따로 사라진 목록은 아직까진 찾지 못했습니다. 어제 다운받은 내용도 사라지지 않아서요.
단순히 예전에 말씀하신 것처럼, 그냥 목록 다 있으면 상관 없는 거 아냐? 다른 사람은 이런 오류 안뜨던데? 라고 말씀하신다면 전 할 말이 없긴 합니다만,, 그래도 작업목록이 이렇게 건드려진다는 게 ptsd가 온다고 해야할까요. 다시 한번 작업목록이 삭제되는 문제가 발생할 수도 있다는 생각에 질문드립니다.

결론적으로론 제가 이번에 궁금한 것은
1. 이번의 Err에러는 작업목록 읽기의 문제보단 단순히 http, 웹 연결의 에러일텐데 이런 오류에도 왜 작업목록이 건드려 지는 것인지가 궁금합니다. 
2. 이번의 Err 같은 경우도 저번과 동일하게 Err에러가 뜨자마자 나갔는데도 이미 작업목록이 뒤틀린 상황이 저장되어 있었습니다. 전 저장을 하지 않고 껐는데 왜 뒤틀린 상태가 저장되어 있는건지 알 수 있나요?


이전의 Err은 제 나름 생각으로는 램이 부족해서 그렇다고 원인을 생각중입니다. 그때 당시에 16기가 램을 사용하면서 커밋을 34기가로 해놓고 쓰고 있었거든요. 당장에 프로그램을 처리해야 오류가 안생길텐데 램 용량이 부족하니 앞부분만 읽고 뒷부분은 자른거라고 생각합니다. 지금은 이 프로그램 사용하면서 제 작업 한다고 64기가 램을 달아 사용중입니다.

개발자님께선 지금까지 이런 오류가 없었다고 하셨는데 혹시 개발자님 컴퓨터 환경을 좀 물어도 될까요? 아무래도 개발자님과 같은 환경에서 가장 최적화될 거라고 생각해서 추가 질문 드립니다.

**Comment by hwnnhji** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/discussions/5770

저같은 분이 또 계신 거 같아요.
