### ISSUE TITLE
마나토끼 다운로드 오류 관련..

### ISSUE THREAD

**Issue by TTY54** [KurtBestor/Hitomi-Downloader#4695]
선생님이 만들어주신 다운로더 항상 감사한 마음으로 사용하고 있습니다.

저번주에 마나토끼 다운로드 하다가 차단을 먹고 그 후부터 다운로드가 안되고 있는 상황입니다.

https://github.com/KurtBestor/Hitomi-Downloader/issues/4664 댓글에 나와있는 

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview 이 버전 히토미 다운로더로 마나토끼 다운을 해보려고 했는데 오류가 뜹니다.

쿠키도 넣고 해봤는데 방법을 찾지 못해서 글을 올립니다.

작업 정보

Invalid: [manatoki] https://manatoki129.net/comic/11966346

version: 3.7i (22-04-24 07:35:35 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 8e8198525c5f44f48bace00635bfcfb8
input: https://manatoki129.net/comic/11966346
type: manatoki
single: False
url: https://manatoki129.net/comic/11966346
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1650968053.0555015 (22-04-26 10:14:13 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "<decorator-gen-93>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 581, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki129.net/comic/11966346  (13.1s)

항상 감사합니다.

**Comment by KurtBestor** [comment]
웹브라우저로는 접속이 되나요?
