### ISSUE TITLE
마나토끼 어드레스 130으로 바뀐 이후 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by Mango202** [KurtBestor/Hitomi-Downloader#4708]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

버전은 위 버전을 사용중입니다. 129 때는 다운로드가 되었는데 130으로 바뀐 이후 다운로드가 안 되네요.

Invalid: [manatoki] https://manatoki130.net/comic/5846071

version: 3.7i (22-04-22 06:05:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 16 / False / c74ae408607249f19e01fa6236fbad4f
input: https://manatoki130.net/comic/5846071
type: manatoki
single: False
url: https://manatoki130.net/comic/5846071
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1651264454.2040393 (22-04-29 20:34:14 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1166, in start
 File "<decorator-gen-93>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 42, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 122, in get_soup
 File "clf2", line 143, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki130.net/comic/5846071  (203.0s)

**Comment by Mango202** [comment]
아 죄송합니다 그 새 되네요..
