### ISSUE TITLE
마나토끼가 또 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by kuronoaing** [KurtBestor/Hitomi-Downloader#4711]
이 전에 다른분이 말해주신 방법으로 회원가입에 쿠키까지 재등록 해봣는데 되질 않네요

Invalid: [manatoki] https://manatoki130.net/comic/12120159

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / b4f7234a505a41e8bcb7d40e6c9bbf7f
input: https://manatoki130.net/comic/12120159
type: manatoki
single: False
url: https://manatoki130.net/bbs/captcha.php
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1651311308.025559 (4월 30일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 577, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki130.net/comic/12120159  (13.1s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 577, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki130.net/comic/12120159  (13.2s)

**Comment by hohoe** [comment]
#4664 댓글에 있는 테스트버전받으시면 돼요.

**Comment by kuronoaing** [comment]
고맙습니다! 잘 되네요!ㅜㅜ

**Comment by nightow** [comment]
안녕하세요, #4664 에 있는 테스트 버전으로 적용을 해봤는데
어제부터 다운로드가 다시 안되네요.
확인 부탁드립니다.
