### ISSUE TITLE
노벨피아 최신화까지 다운이 안됩니다.

### ISSUE THREAD

**Issue by Legercy** [KurtBestor/Hitomi-Downloader#4713]
https://github.com/KurtBestor/Hitomi-Downloader/issues/4664
여기 댓글에서 다운받고 쿠키 불러오는것 까진 따라해서 받았는데 30~40화 정도 다운이 안됩니다...

**Comment by lmn999** [comment]
같은 증상입니다 
잘리는 화수는 웹에서 보이는 목록의 최신 1~2페이지가 잘리는것같고 
총 150화면 그중 120화만 인식하고 긁어오는 느낌

**Comment by KurtBestor** [comment]
@SaidBySolo

**Comment by SaidBySolo** [comment]
작품 링크좀 주실수있나요?
@Legercy @lmn999

**Comment by lmn999** [comment]
@SaidBySolo

https://novelpia.com/novel/50356

그리고 혹시 다운방식 변경 가능한가요? 
테스트로 몇번 굴렸더니 ip 차단먹은거같습니다

**Comment by SaidBySolo** [comment]
작업정보도 같이 주실수있으신가요?

**Comment by lmn999** [comment]
다른작품이지만 작업정보입니다
urls 밑은 없었습니다 

version: 3.7i (22-04-24 07:35:35 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / 4327e4ef71f847c18cbc4f4404f29d6b
input: https://novelpia.com/novel/1275
type: novelpia
single: False
url: https://novelpia.com/novel/1275
dir: hitomi_downloaded_novelpia\오궁도화
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1651457835.5631633 (22-05-02 02:17:15 UTC)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_novelpia\오궁도화\cover.jpg
[0002] hitomi_downloaded_novelpia\오궁도화\Prologue： Prologue프롤로그.txt
[0003] hitomi_downloaded_novelpia\오궁도화\cover.jpg
[0004] hitomi_downloaded_novelpia\오궁도화\EP.1： EP.1재기.txt
[0005] hitomi_downloaded_novelpia\오궁도화\EP.2： EP.2재기.txt
[0006] hitomi_downloaded_novelpia\오궁도화\EP.3： EP.3내기바둑.txt
[0007] hitomi_downloaded_novelpia\오궁도화\EP.4： EP.4내기바둑.txt
[0008] hitomi_downloaded_novelpia\오궁도화\EP.5： EP.5내기바둑.txt
[0009] hitomi_downloaded_novelpia\오궁도화\EP.6： EP.6WY배 아마대회.txt
[0010] hitomi_downloaded_novelpia\오궁도화\EP.7： EP.7WY배 아마대회.txt
[0011] hitomi_downloaded_novelpia\오궁도화\EP.8： EP.8WY배 아마대회.txt
[0012] hitomi_downloaded_novelpia\오궁도화\EP.9： EP.9WY배 아마대회.txt
[0013] hitomi_downloaded_novelpia\오궁도화\EP.10： EP.10WY배 아마대회.txt
[0014] hitomi_downloaded_novelpia\오궁도화\EP.11： EP.11WY배 아마대회.txt
[0015] hitomi_downloaded_novelpia\오궁도화\EP.12： EP.12NJ 화재배 통합예선.txt
[0016] hitomi_downloaded_novelpia\오궁도화\EP.13： EP.13NJ 화재배 통합예선.txt
[0017] hitomi_downloaded_novelpia\오궁도화\EP.14： EP.14NJ 화재배 통합예선.txt
[0018] hitomi_downloaded_novelpia\오궁도화\EP.15： EP.15NJ 화재배 통합예선.txt
[0019] hitomi_downloaded_novelpia\오궁도화\EP.16： EP.16윤슬 바둑도장.txt
[0020] hitomi_downloaded_novelpia\오궁도화\EP.17： EP.17윤슬 바둑도장.txt
[0021] hitomi_downloaded_novelpia\오궁도화\EP.18： EP.18체력특훈.txt
[0022] hitomi_downloaded_novelpia\오궁도화\EP.19： EP.19체력특훈.txt
[0023] hitomi_downloaded_novelpia\오궁도화\EP.20： EP.20프로 데뷔.txt
[0024] hitomi_downloaded_novelpia\오궁도화\EP.21： EP.21프로 데뷔.txt
[0025] hitomi_downloaded_novelpia\오궁도화\EP.22： EP.22프로 데뷔.txt
[0026] hitomi_downloaded_novelpia\오궁도화\EP.23： EP.23화이허배 세계 여자바둑 대항전.txt
[0027] hitomi_downloaded_novelpia\오궁도화\EP.24： EP.24화이허배 여자바둑 대항전.txt
[0028] hitomi_downloaded_novelpia\오궁도화\EP.25： EP.25화이허배 여자바둑 대항전.txt
[0029] hitomi_downloaded_novelpia\오궁도화\EP.26： EP.26화이허배 세계 여자바둑 대항전.txt
[0030] hitomi_downloaded_novelpia\오궁도화\EP.27： EP.27화이허배 세계 여자바둑 대항전.txt
[0031] hitomi_downloaded_novelpia\오궁도화\EP.28： EP.28입단대회.txt
[0032] hitomi_downloaded_novelpia\오궁도화\EP.29： EP.29입단대회.txt
[0033] hitomi_downloaded_novelpia\오궁도화\EP.30： EP.30입단대회.txt
[0034] hitomi_downloaded_novelpia\오궁도화\EP.31： EP.31연승전.txt
[0035] hitomi_downloaded_novelpia\오궁도화\EP.32： EP.32연승전.txt
[0036] hitomi_downloaded_novelpia\오궁도화\EP.33： EP.33연승전.txt
[0037] hitomi_downloaded_novelpia\오궁도화\EP.34： EP.34연승전.txt
[0038] hitomi_downloaded_novelpia\오궁도화\EP.35： EP.35연승전.txt
[0039] hitomi_downloaded_novelpia\오궁도화\EP.36： EP.36연승전.txt
[0040] hitomi_downloaded_novelpia\오궁도화\EP.37： EP.37연승전.txt
[0041] hitomi_downloaded_novelpia\오궁도화\EP.38： EP.38연승전.txt
[0042] hitomi_downloaded_novelpia\오궁도화\EP.39： EP.39페어바둑.txt
[0043] hitomi_downloaded_novelpia\오궁도화\EP.40： EP.40페어바둑.txt
[0044] hitomi_downloaded_novelpia\오궁도화\EP.41： EP.41페어바둑.txt
[0045] hitomi_downloaded_novelpia\오궁도화\EP.42： EP.42페어바둑.txt
[0046] hitomi_downloaded_novelpia\오궁도화\EP.43： EP.43페어바둑.txt
[0047] hitomi_downloaded_novelpia\오궁도화\EP.44： EP.44페어바둑.txt
[0048] hitomi_downloaded_novelpia\오궁도화\EP.45： EP.45페어바둑.txt
[0049] hitomi_downloaded_novelpia\오궁도화\EP.46： EP.46페어바둑.txt
[0050] hitomi_downloaded_novelpia\오궁도화\EP.47： EP.47선발전.txt
[0051] hitomi_downloaded_novelpia\오궁도화\EP.48： EP.48선발전.txt
[0052] hitomi_downloaded_novelpia\오궁도화\EP.49： EP.49선발전.txt
[0053] hitomi_downloaded_novelpia\오궁도화\EP.50： EP.50선발전.txt
[0054] hitomi_downloaded_novelpia\오궁도화\EP.51： EP.51선발전.txt
[0055] hitomi_downloaded_novelpia\오궁도화\EP.52： EP.52명인.txt
[0056] hitomi_downloaded_novelpia\오궁도화\EP.53： EP.53명인.txt
[0057] hitomi_downloaded_novelpia\오궁도화\EP.54： EP.54명인.txt
[0058] hitomi_downloaded_novelpia\오궁도화\EP.55： EP.55명인.txt
[0059] hitomi_downloaded_novelpia\오궁도화\EP.56： EP.56양장치배.txt
[0060] hitomi_downloaded_novelpia\오궁도화\EP.57： EP.57양장치배.txt
[0061] hitomi_downloaded_novelpia\오궁도화\EP.58： EP.58양장치배.txt
[0062] hitomi_downloaded_novelpia\오궁도화\EP.59： EP.59양장치배.txt
[0063] hitomi_downloaded_novelpia\오궁도화\EP.60： EP.60양장치배.txt
[0064] hitomi_downloaded_novelpia\오궁도화\EP.61： EP.61양장치배.txt
[0065] hitomi_downloaded_novelpia\오궁도화\EP.62： EP.62양장치배.txt
[0066] hitomi_downloaded_novelpia\오궁도화\EP.63： EP.63양장치배.txt
[0067] hitomi_downloaded_novelpia\오궁도화\EP.64： EP.64세영중학교.txt
[0068] hitomi_downloaded_novelpia\오궁도화\EP.65： EP.65세영중학교.txt
[0069] hitomi_downloaded_novelpia\오궁도화\EP.66： EP.66세영중학교.txt
[0070] hitomi_downloaded_novelpia\오궁도화\EP.67： EP.67세영중학교.txt
[0071] hitomi_downloaded_novelpia\오궁도화\EP.68： EP.68왕좌전.txt
[0072] hitomi_downloaded_novelpia\오궁도화\EP.69： EP.69왕좌전.txt
[0073] hitomi_downloaded_novelpia\오궁도화\EP.70： EP.70왕좌전.txt
[0074] hitomi_downloaded_novelpia\오궁도화\EP.71： EP.71왕좌전.txt
[0075] hitomi_downloaded_novelpia\오궁도화\EP.72： EP.72왕좌전.txt
[0076] hitomi_downloaded_novelpia\오궁도화\EP.73： EP.73한중일 왕중왕 쟁패전.txt
[0077] hitomi_downloaded_novelpia\오궁도화\EP.74： EP.74한중일 왕중왕 쟁패전.txt
[0078] hitomi_downloaded_novelpia\오궁도화\EP.75： EP.75한중일 왕중왕 쟁패전.txt
[0079] hitomi_downloaded_novelpia\오궁도화\EP.76： EP.76한중일 왕중왕 쟁패전.txt
[0080] hitomi_downloaded_novelpia\오궁도화\EP.77： EP.77한중일 왕중왕 쟁패전.txt
[0081] hitomi_downloaded_novelpia\오궁도화\EP.78： EP.78한중일 왕중왕 쟁패전.txt
[0082] hitomi_downloaded_novelpia\오궁도화\EP.79： EP.79한중일 왕중왕 쟁패전.txt
[0083] hitomi_downloaded_novelpia\오궁도화\EP.80： EP.80한중일 왕중왕 쟁패전.txt
[0084] hitomi_downloaded_novelpia\오궁도화\EP.81： EP.81한중일 왕중왕 쟁패전.txt
[0085] hitomi_downloaded_novelpia\오궁도화\EP.82： EP.82한중일 왕중왕 쟁패전.txt
[0086] hitomi_downloaded_novelpia\오궁도화\EP.83： EP.83한중일 왕중왕 쟁패전.txt
[0087] hitomi_downloaded_novelpia\오궁도화\EP.84： EP.84은둔 고수.txt
[0088] hitomi_downloaded_novelpia\오궁도화\EP.85： EP.85은둔 고수.txt
[0089] hitomi_downloaded_novelpia\오궁도화\EP.86： EP.86은둔 고수.txt
[0090] hitomi_downloaded_novelpia\오궁도화\EP.87： EP.87은둔 고수.txt
[0091] hitomi_downloaded_novelpia\오궁도화\EP.88： EP.88은둔 고수.txt
[0092] hitomi_downloaded_novelpia\오궁도화\EP.89： EP.89은둔 고수.txt
[0093] hitomi_downloaded_novelpia\오궁도화\EP.90： EP.90반역의 시대.txt
[0094] hitomi_downloaded_novelpia\오궁도화\EP.91： EP.91반역의 시대.txt
[0095] hitomi_downloaded_novelpia\오궁도화\EP.92： EP.92반역의 시대.txt
[0096] hitomi_downloaded_novelpia\오궁도화\EP.93： EP.93반역의 시대.txt
[0097] hitomi_downloaded_novelpia\오궁도화\EP.94： EP.94반역의 시대.txt
[0098] hitomi_downloaded_novelpia\오궁도화\EP.95： EP.95반역의 시대.txt
[0099] hitomi_downloaded_novelpia\오궁도화\EP.96： EP.96반역의 시대.txt
[0100] hitomi_downloaded_novelpia\오궁도화\EP.97： EP.97반역의 시대.txt
[0101] hitomi_downloaded_novelpia\오궁도화\EP.98： EP.98반역의 시대.txt
[0102] hitomi_downloaded_novelpia\오궁도화\EP.99： EP.99탐색전.txt


[URLs]

**Comment by Legercy** [comment]
작업정보 올리려고 다시 다운받는데 이번엔 아예 다운 자체가 안되버립니다..ㅠ

Invalid: [novelpia] https://novelpia.com/novel/23

version: 3.7i (22-04-24 07:35:35 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 2f37c90ffd44456889902df4242bbf5b
input: https://novelpia.com/novel/23
type: novelpia
single: False
url: https://novelpia.com/novel/23
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1651580845.8374124 (22-05-03 12:27:25 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1180, in start
 File "utils", line 1250, in start_
 File "extractor\novelpia_downloader", line 98, in read
 File "extractor\novelpia_downloader", line 77, in __get_all_viewer_numbers
 File "extractor\novelpia_downloader", line 66, in __get_total_episode_list
IndexError: list index out of range

Invalid: fail=True
EOT: https://novelpia.com/novel/23  (0.8s)
