### ISSUE TITLE
[히토미 다운로더]폰허브에서 다운로드가 왜 안되는거죠??

### ISSUE THREAD

**Issue by Snuff1** [KurtBestor/Hitomi-Downloader#4767]
Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 549c32db0e4b46038b333e08cb74979b
input: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1652540782.973246 (22-05-14 15:06:22 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.4s)

id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.1s)

id: ph5ed2b3d5e09c8
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (44.0s)

id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.2s)

id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.2s)

id: ph5ed2b3d5e09c8
id: ph5ed2b3d5e09c8
list index out of range
stop
Traceback (most recent call last):
 File "extractor\pornhub_downloader", line 83, in get
 File "downloader", line 380, in read_html
 File "downloader", line 638, in fix_header
 File "hitomi", line 664, in fix_header
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 91, in get
 File "downloader", line 380, in read_html
 File "downloader", line 638, in fix_header
 File "hitomi", line 664, in fix_header
IndexError: list index out of range

Invalid: fail=True
EOT: www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (0.7s)

id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.1s)

id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.0s)

id: ph5ed2b3d5e09c8
Video
id: ph5ed2b3d5e09c8
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 785, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ed2b3d5e09c8  (45.1s)

**Comment by onanana** [comment]
저도 안되네요
