### ISSUE TITLE
며칠전부터 히토미가 무한로딩으로 먹통입니다

### ISSUE THREAD

**Issue by msgman** [KurtBestor/Hitomi-Downloader#4769]
새로운 버전 다 받아보고 프리뷰 버전도 받아보고 재설치하고 했는데도 여전히 먹통이네요

0.0kb/s 에서 올라가지 않고 무한로딩만 돌아갑니다

[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)

version: 3.7k (22-05-13 07:18:32 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e987e8805ac5435690ec22a1fb4acc1d
input: [Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)
type: hitomi
single: False
url: https://hitomi.la/galleries/2221283.html
dir: hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)
zip: 
artist: windart
valid / done: True / False
range / range_p: None / None
time: 1652627993.7952042 (22-05-15 15:19:53 UTC)
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: False

[Gallery]
갤러리 넘버: 2221283

제목: Idol Saiin Rakuen VR CASE2 Kurosawa Shimai

작가: windart

그룹: windarteam

타입: doujinshi

시리즈: love live sunshine

캐릭터: dia kurosawa

태그: multi-work series, female:anal, female:latex, female:mind break, female:mind control, female:slave

언어: Korean

[File Names]
[0001] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\01.webp
[0002] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\02.webp
[0003] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\03.webp
[0004] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\04.webp
[0005] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\05.webp
[0006] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\06.webp
[0007] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\07.webp
[0008] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\08.webp
[0009] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\09.webp
[0010] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\10.webp
[0011] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\11.webp
[0012] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\12.webp
[0013] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\13.webp
[0014] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\14.webp
[0015] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\15.webp
[0016] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\16.webp
[0017] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\17.webp
[0018] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\18.webp
[0019] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\19.webp
[0020] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\20.webp
[0021] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\21.webp
[0022] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\22.webp
[0023] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\23.webp
[0024] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\24.webp
[0025] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\25.webp
[0026] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\26.webp
[0027] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\27.webp
[0028] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\28.webp
[0029] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\29.webp
[0030] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\30.webp
[0031] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\31.webp
[0032] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\32.webp
[0033] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\33.webp
[0034] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\34.webp
[0035] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\35.webp
[0036] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\36.webp
[0037] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\37.webp
[0038] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\38.webp
[0039] hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\39.webp

[URLs]
[0001] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/3325/ccd5754aa930e87697fcd9b9e83f94f3c0fe5bec81419df680b0c81306ec8fdc.webp
[0002] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/2322/06ca05978bdf5c9a6e5b70bd4ab593e9ac1bd47a9a1a85fa0b0b4e943f8cc129.webp
[0003] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/1815/910acdd0c7fa2048bd16c2c0109d2d6d666dfad65376c4882930e9ee5cc0b177.webp
[0004] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/1982/eca4b1b87d7c553fa5e24148997cb0707c4f4360cf20075fedb8c4cc77e3abe7.webp
[0005] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/2195/89848f2740c10a55363d7a3ae1a19104381e42f16abc84949a5f61ec87075938.webp
[0006] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/527/ef20c0a2cea2009d1a12322411aee815dcf19d43e0aaebb483d2180fa5bde0f2.webp
[0007] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/1641/dc8a2bdaf877968fa97b9e1829e497ebace85ca443fa8f9d6683ecef5b6cf696.webp
[0008] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/1493/b1a150f5503e678dccbe5d16ee1b618b3b5ac6c23e5ee1fa31a3e8804eeccd55.webp
[0009] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/3156/41c8dddc6bd1c6ff12351a14b3f4095241fec00db507ede0922638aa2fa1b54c.webp
[0010] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/3211/d9f6d446a7c1c22afbe920d71f53e1fce144f96778006e8c12b01b1c9d6088bc.webp
[0011] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/456/e2291a7c248eece857523e08fff834037d0144348bbe14acd95945c51f25ec81.webp
[0012] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/1032/2da278d492cbc935c8719d965d15c797586729a731134ac673b1a3da4d5c8084.webp
[0013] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/2974/94997a940ceed9bbd332d34ceafca88153049547ea099f0e76ccda2db055f9eb.webp
[0014] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/2376/07710becdb1d382b9b82ef43a161567d712049b5dd4714fec6dab7f6a6390489.webp
[0015] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://ba.hitomi.la/webp/1652626801/1765/15d7f26bcd88f5badae4dced7564b197e631c0becd33cfa45d1d851dfb068e56.webp
[0016] LazyUrl(https://hitomi.la/reader/2221283.html)    --->    https://aa.hitomi.la/webp/1652626801/1237/4c984e173a4de07763f91ee3d62bfa639261b06c599a68740f4fb8abab68dd54.webp
[0017] LazyUrl(https://hitomi.la/reader/2221283.html)
[0018] LazyUrl(https://hitomi.la/reader/2221283.html)
[0019] LazyUrl(https://hitomi.la/reader/2221283.html)
[0020] LazyUrl(https://hitomi.la/reader/2221283.html)
[0021] LazyUrl(https://hitomi.la/reader/2221283.html)
[0022] LazyUrl(https://hitomi.la/reader/2221283.html)
[0023] LazyUrl(https://hitomi.la/reader/2221283.html)
[0024] LazyUrl(https://hitomi.la/reader/2221283.html)
[0025] LazyUrl(https://hitomi.la/reader/2221283.html)
[0026] LazyUrl(https://hitomi.la/reader/2221283.html)
[0027] LazyUrl(https://hitomi.la/reader/2221283.html)
[0028] LazyUrl(https://hitomi.la/reader/2221283.html)
[0029] LazyUrl(https://hitomi.la/reader/2221283.html)
[0030] LazyUrl(https://hitomi.la/reader/2221283.html)
[0031] LazyUrl(https://hitomi.la/reader/2221283.html)
[0032] LazyUrl(https://hitomi.la/reader/2221283.html)
[0033] LazyUrl(https://hitomi.la/reader/2221283.html)
[0034] LazyUrl(https://hitomi.la/reader/2221283.html)
[0035] LazyUrl(https://hitomi.la/reader/2221283.html)
[0036] LazyUrl(https://hitomi.la/reader/2221283.html)
[0037] LazyUrl(https://hitomi.la/reader/2221283.html)
[0038] LazyUrl(https://hitomi.la/reader/2221283.html)
[0039] LazyUrl(https://hitomi.la/reader/2221283.html)

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 39

Fail : \\?\C:\Users\wonjo\Desktop\123\hitomi_downloaded\[Windart] Idol Saiin Rakuen VR CASE2 Kurosawa Shimai (2221283)\01.webp
Traceback (most recent call last):
 File "downloader", line 991, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

**Comment by msgman** [comment]
추가적으로 에러 10060 찾아보고 왔으나 

전 프록시나 우회같은건 히토미 다운로더 기능중 dpi우회 를 사용하는걸 제외하면 사용하지않습니다

**Comment by msgman** [comment]
다방면으로 검색하고 확인해보고 시도하고 있으나 여전히 무한로딩입니다 ㅜㅜ

**Comment by KurtBestor** [comment]
1. 방화벽 예외 프로그램 추가
2. 백신 예외 프로그램 추가
3. hosts 파일 체크: https://github.com/KurtBestor/Hitomi-Downloader/issues/4425

**Comment by KurtBestor** [comment]
해결 하셨나요?

**Comment by msgman** [comment]
호스트 문제가 맞았네요! 해결됐습니다 감사합니다 :)
