### ISSUE TITLE
인스타 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by highbee123** [KurtBestor/Hitomi-Downloader#4774]
쿠키 적용은 설정-내장 웹브라우저에 들어가서 인스타 로그인 되어있고 볼수 있는거보면 잘 된것 같은데 안되네요.

작업정보입니다. 
Invalid: [insta] https://www.instagram.com/inkyung97

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e67a43a837ed474f87ead42414d2c831
input: https://www.instagram.com/inkyung97
type: insta
single: False
url: https://www.instagram.com/inkyung97
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1652782829.456708 (22-05-17 10:20:29 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no _sharedData
stop
Traceback (most recent call last):
 File "utils", line 1169, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 581, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 205, in get_username
 File "extractor\insta_downloader", line 159, in get_sd
Exception: no _sharedData

Invalid: fail=True
EOT: https://www.instagram.com/inkyung97  (32.1s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4829

**Comment by BearTree7** [comment]
6분 20초 뒤 다시 시작: https://www.instagram.com/inkyung97

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 9187220957d8487eb1c4a761de538bd4
input: https://www.instagram.com/inkyung97
type: insta
single: False
url: https://www.instagram.com/inkyung97
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1663752284.8947802 (22-09-21 09:24:44 UTC) - 316s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "extractor\insta_downloader", line 41, in init
 File "extractor\insta_downloader", line 28, in get_session
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.instagram.com/inkyung97  (95.1s)
-------------------
인스타 다운로드가 안되네요 쿠키 추가나 스토리포함 끄기등 해봐도 동일합니다
