### ISSUE TITLE
다운로드가 안됩니다 

### ISSUE THREAD

**Issue by qoqoqi** [KurtBestor/Hitomi-Downloader#4779]
Invalid: [manatoki] https://manatoki131.net/comic/155996

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / 3c4f9e6208f048fc937d87789864cc7b
input: https://manatoki131.net/comic/155996
type: manatoki
single: False
url: https://manatoki131.net/comic/155996
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1652846624.3665588 (22-05-18 04:03:44 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1169, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 581, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki131.net/comic/155996  (13.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1169, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 581, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki131.net/comic/155996  (13.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1169, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 581, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki131.net/comic/155996  (14.6s)

로그를 첨부합니다.

**Comment by qoqoqi** [comment]
다시확인해보니 되네요 어젠 왜그랬지
