### ISSUE TITLE
인스타 다운로드 불가 현상

### ISSUE THREAD

**Issue by Infi9613** [KurtBestor/Hitomi-Downloader#4829]
Invalid: [insta] https://www.instagram.com/lilyiu_

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / ef6b51e440514784a1678c3f803c5f6d
input: https://www.instagram.com/lilyiu_
type: insta
single: False
url: https://www.instagram.com/lilyiu_
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1654104354.5424747 (22-06-01 17:25:54 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no _sharedData
stop
Traceback (most recent call last):
 File "utils", line 1169, in start
 File "extractor\insta_downloader", line 49, in init
 File "utils", line 581, in __get__
 File "extractor\insta_downloader", line 53, in username
 File "extractor\insta_downloader", line 205, in get_username
 File "extractor\insta_downloader", line 159, in get_sd
Exception: no _sharedData

Invalid: fail=True
EOT: https://www.instagram.com/lilyiu_  (31.6s)

쿠키 입력 완료한 상태 입니다

**Comment by fdsa1538** [comment]
저도 
no _sharedData
이거 나오네요.. 로그아웃 하고 쿠키 업데이트 해봐도..
저는 포맷하고 처음작동시켜봤는데 혹시 포맷 하셨나요?

**Comment by KimDaesap** [comment]
저도 같은 현상입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
옵션에서 `스토리 포함` 끄고 해보세요

**Comment by KimDaesap** [comment]
해결됬습니다.
감사합니다 ^-^

**Comment by Ellencia** [comment]
최신버전으로 스토리 포함 끄고 하는데 다운 받기전에 목록 로딩 하는게 엄청 느린데 제 컴 문제이려나요?
다운로드 시도 실패도 아니니까 로그같은것도 안나와서 뭐 올릴것도 없고
36/2000 이런상태에서 한시간 있다가 72/2000 되고 또 한참 기다리고 그러네요
url 복사해서 다운 시도하면 읽는중... 이것도 엄청 오래 걸리고 그래서... 구체적이지 못해 미안합니다.

**Comment by Ellencia** [comment]
Invalid: [insta] https://www.instagram.com/hello__rina

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / a1ac3e27abb74061b93ccd663bdbced7
input: https://www.instagram.com/hello__rina
type: insta
single: False
url: https://www.instagram.com/hello__rina
dir: 
zip: 
artist: model RINA 𖤐 서리나
valid / done: False / True
range / range_p: None / None
time: 1654930932.0787845 (22-06-11 07:02:12 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
username: hello__rina
stories: True
Fail: Please wait a few minutes before you try again. {'user_id': '1064144259', 'include_chaining': True, 'include_reel': True, 'include_suggested_users': False, 'include_logged_out_extras': False, 'include_highlight_reels': True, 'include_live_status': True}
Fail: Please wait a few minutes before you try again. {'user_id': '1064144259', 'include_chaining': True, 'include_reel': True, 'include_suggested_users': False, 'include_logged_out_extras': False, 'include_highlight_reels': True, 'include_live_status': True}
Fail: Please wait a few minutes before you try again. {'user_id': '1064144259', 'include_chaining': True, 'include_reel': True, 'include_suggested_users': False, 'include_logged_out_extras': False, 'include_highlight_reels': True, 'include_live_status': True}
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\insta_downloader", line 76, in read
 File "extractor\insta_downloader", line 466, in get_imgs_all
 File "extractor\insta_downloader", line 498, in get_stories
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\insta_downloader", line 322, in get_query
Exception: Fail: Please wait a few minutes before you try again. {'user_id': '1064144259', 'include_chaining': True, 'include_reel': True, 'include_suggested_users': False, 'include_logged_out_extras': False, 'include_highlight_reels': True, 'include_live_status': True}

Invalid: fail=True
EOT: https://www.instagram.com/hello__rina  (3623.8s)
