### ISSUE TITLE
어....트위터 다운이 안됩니다....

### ISSUE THREAD

**Issue by OIRIM** [KurtBestor/Hitomi-Downloader#4839]
Invalid: [twitter] https://twitter.com/guftrup

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / ec9949a0f65748e88e43ea91a774e03a
input: https://twitter.com/guftrup
type: twitter
single: False
url: https://twitter.com/guftrup
dir: 
zip: 
artist: guftrup
valid / done: False / True
range / range_p: None / None
time: 1654423247.011689 (22-06-05 10:00:47 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
token type: <class 'str'>
generate csrf
multiple tweets
cursor: HBaMwL31rc3qoygAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 569, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/guftrup  (8.5s)

generate csrf
multiple tweets
cursor: HBaMwL31rc3qoygAAA==
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\twitter_downloader", line 92, in read
 File "extractor\twitter_downloader", line 569, in get_imgs
Exception: no imgs

Invalid: fail=True
EOT: https://twitter.com/guftrup  (7.9s)

이렇게 쓰는거 맞나요?
트위터계정주소 복사해서 이미지랑 영상 한번에 받으려는데....

안되네요.... 제가 잘못하고 있는건가요?

**Comment by KurtBestor** [comment]
로그인이 필요한 페이지의 경우 로그인 쿠키가 필요해요

**Comment by OIRIM** [comment]
어...그러면 인스타다운할때는 인스타 쿠키가 필요하고, 트위터 다운할때는 트위터 쿠키가 또 필요한건가요?
그러면 트위터 로그인 쿠키가 들어가면 잠금계정들도 다운 받을 수 있나요?

**Comment by SCPYO** [comment]
해결하셨는지 모르겠으나 트위터에 로그인하고  export를 업데이트하니 정상적으로 작동됩니다
