### ISSUE TITLE
제이마나 다운이 안됩니다.

### ISSUE THREAD

**Issue by seomen** [KurtBestor/Hitomi-Downloader#4860]
원래 받았졌었는데 어느 순간 기점으로 invalid 뜨네요

**Comment by paikseung-tae** [comment]
Invalid: [jmana] https://jmana1.net/bookdetail?bookdetailid=529862

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / a876c913e0d94b7892f8935bdd00877b
input: https://jmana1.net/bookdetail?bookdetailid=529862
type: jmana
single: False
url: https://jmana1.net/bookdetail?bookdetailid=529862
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1654840723.6300552 (22-06-10 05:58:43 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://jmana1.net/bookdetail?bookdetailid=529862  (3.0s)

**Comment by seomen** [comment]
Invalid: [jmana] https://jmana1.net/bookdetail?bookdetailid=530148

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e247950f3d40493c833476ea5a6fd281
input: https://jmana1.net/bookdetail?bookdetailid=530148
type: jmana
single: False
url: https://jmana1.net/bookdetail?bookdetailid=530148
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1654846622.1279504 (22-06-10 07:37:02 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://jmana1.net/bookdetail?bookdetailid=530148  (11.1s)

**Comment by seomen** [comment]
Invalid: [jmana] https://jmana1.net/bookdetail?bookdetailid=530148

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e247950f3d40493c833476ea5a6fd281
input: https://jmana1.net/bookdetail?bookdetailid=530148
type: jmana
single: False
url: https://jmana1.net/bookdetail?bookdetailid=530148
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1654846622.1279504 (22-06-10 07:37:02 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "extractor\jmana_downloader", line 45, in init
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://jmana1.net/bookdetail?bookdetailid=530148  (11.1s)

**Comment by KurtBestor** [comment]
DPI 우회를 켜세요

**Comment by seomen** [comment]
감사합니다
