### ISSUE TITLE
폰허브 pornhub 다운로드가 안된지 오래됐어요 이번 업데이트 됐는데도 안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by tedmedc** [KurtBestor/Hitomi-Downloader#4868]
폰허브 pornhub 다운로드가 안된지 오래됐어요 이번 업데이트 됐는데도 안되네요 ㅠㅠ

업데이트 되면 되겠지 하고 오래 기다려서 오늘 업데이트 했는데도 안되네요 개발자님 ㅠㅠ

되게 해주세요 ㅠㅠ

**Comment by tedmedc** [comment]
Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 8d61b12f3b5c461a822cd28e78630a90
input: https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1654871955.703154 (22-06-10 14:39:15 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
id: ph627b34c1830f7
Video
id: ph627b34c1830f7
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 786, in __call__
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7  (46.0s)

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 열고 다음과 같이 입력하고 <kbd>Enter</kbd> 누르면 프로그램 폴더에 `test.txt` 파일이 만들어질텐데 보내주세요:
```python
with open('test.txt', 'wb') as f: f.write(downloader.read_html('https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7').encode('utf8'))
```

**Comment by admin576** [comment]
Traceback (most recent call last):
      File "console\Console", line 183, in execSingle
      File "<string>", line 1
        with open('test.txt', 'wb') as f: f.write(downloader.read_html('https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7').encode('utf8'))
           ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib\request", line 1350, in do_open
      File "http\client", line 1277, in request
      File "http\client", line 1323, in _send_request
      File "http\client", line 1272, in endheaders
      File "http\client", line 1032, in _send_output
      File "http\client", line 972, in send
      File "http\client", line 1439, in connect
      File "http\client", line 944, in connect
      File "socket", line 728, in create_connection
      File "socket", line 716, in create_connection
    TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "downloader", line 391, in read_html
      File "urllib\request", line 525, in open
      File "urllib\request", line 543, in _open
      File "urllib\request", line 503, in _call_chain
      File "urllib\request", line 1393, in https_open
      File "urllib\request", line 1352, in do_open
    urllib.error.URLError: <urlopen error [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib3\connection", line 160, in _new_conn
      File "urllib3\util\connection", line 84, in create_connection
      File "urllib3\util\connection", line 74, in create_connection
    TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib3\connectionpool", line 677, in urlopen
      File "urllib3\connectionpool", line 381, in _make_request
      File "urllib3\connectionpool", line 978, in _validate_conn
      File "urllib3\connection", line 309, in connect
      File "urllib3\connection", line 172, in _new_conn
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001E8EB472648>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "requests\adapters", line 449, in send
      File "urllib3\connectionpool", line 727, in urlopen
      File "urllib3\util\retry", line 446, in increment
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph627b34c1830f7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8EB472648>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "console\Console", line 187, in execSingle
      File "<string>", line 1, in <module>
      File "downloader", line 418, in read_html
      File "requests\sessions", line 555, in get
      File "downloader", line 212, in session_request
      File "requests\sessions", line 542, in request
      File "requests\sessions", line 655, in send
      File "requests\adapters", line 516, in send
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph627b34c1830f7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8EB472648>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

**Comment by admin576** [comment]
IPS에서 폰헙 IP를 밴한거 같은데 dpi 우회해도 어차피 IP밴이라 안 되고 VPN 으로 우회 사이트 접속은 됩니다. 프로그램에 VPN 기능 추가도 가능할까요?

**Comment by admin576** [comment]
https://apps.microsoft.com/store/detail/touchvpn/9NBLGGH5GB3F?hl=en-us&gl=US

윈도우 앱스토어에서 VPN 설치 후 다운은 가능합니다

**Comment by tedmedc** [comment]
> Ctrl + Alt + C 눌러서 콘솔 열고 다음과 같이 입력하고 Enter 누르면 프로그램 폴더에 `test.txt` 파일이 만들어질텐데 보내주세요:
> 
> ```python
> with open('test.txt', 'wb') as f: f.write(downloader.read_html('https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7').encode('utf8'))
> ```
