### ISSUE TITLE
검색기 데이터 다운로드 불가 WinError 10054 문제

### ISSUE THREAD

**Issue by Gunter-Dw-Jung** [KurtBestor/Hitomi-Downloader#4874]
검색기 데이터를 다운로드 하려고 버튼을 누르면 1분정도 응답없음이 뜨다가 다운로드를 실패했다고 메세지가 뜹니다.

또한 히토미 다운로더가 먹통이 되는 동안 다른 웹 브라우저의 인터넷 연결도 불량이 됩니다.

https://github.com/KurtBestor/Hitomi-Downloader/issues/2237 를 참고해 봤지만 저는 프록시 vpn 유니콘 등등을 사용하지 않으며 방화벽 또한 히토미 다운로더를 차단 하지 않는 상태입니다.

일본 거주중이며 올해 3월에 이사를 해서 인터넷 환경이 바뀌었습니다만 예전과 똑같이 히토미나 폰허브에 vpn 없이 접속 가능한 상황입니다. 인터넷이 느리다고 느껴지지는 않습니다.

마지막으로 시도해 보려고 하는게 dpi 우회인데 현재 회색으로 보이고 끄고 켤 수 없습니다. 현재 꺼져있다고 하는데 어떻게 켜야 하는지 방법을 모르겠습니다. issue 창에서 찾아보고 있는데 현재로서 정보가 없습니다.

Traceback (most recent call last):
  File "urllib\request", line 1350, in do_open
  File "http\client", line 1277, in request
  File "http\client", line 1323, in _send_request
  File "http\client", line 1272, in endheaders
  File "http\client", line 1032, in _send_output
  File "http\client", line 972, in send
  File "http\client", line 1447, in connect
  File "ssl", line 423, in wrap_socket
  File "ssl", line 870, in _create
  File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 410, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 543, in _open
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 1393, in https_open
  File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 371, in connect
  File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
  File "ssl", line 423, in wrap_socket
  File "ssl", line 870, in _create
  File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 449, in send
  File "urllib3\connectionpool", line 727, in urlopen
  File "urllib3\util\retry", line 410, in increment
  File "urllib3\packages\six", line 734, in reraise
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 371, in connect
  File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
  File "ssl", line 423, in wrap_socket
  File "ssl", line 870, in _create
  File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 210, in download_json
  File "hitomi_searcher", line 372, in download_json_
  File "downloader", line 437, in read_html
  File "requests\sessions", line 555, in get
  File "downloader", line 211, in session_request
  File "requests\sessions", line 542, in request
  File "requests\sessions", line 655, in send
  File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

----

Traceback (most recent call last):
  File "urllib\request", line 1350, in do_open
  File "http\client", line 1277, in request
  File "http\client", line 1323, in _send_request
  File "http\client", line 1272, in endheaders
  File "http\client", line 1032, in _send_output
  File "http\client", line 972, in send
  File "http\client", line 1447, in connect
  File "ssl", line 423, in wrap_socket
  File "ssl", line 870, in _create
  File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 410, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 543, in _open
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 1393, in https_open
  File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 371, in connect
  File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
  File "ssl", line 423, in wrap_socket
  File "ssl", line 870, in _create
  File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 449, in send
  File "urllib3\connectionpool", line 727, in urlopen
  File "urllib3\util\retry", line 410, in increment
  File "urllib3\packages\six", line 734, in reraise
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 371, in connect
  File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
  File "ssl", line 423, in wrap_socket
  File "ssl", line 870, in _create
  File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 210, in download_json
  File "hitomi_searcher", line 372, in download_json_
  File "downloader", line 437, in read_html
  File "requests\sessions", line 555, in get
  File "downloader", line 211, in session_request
  File "requests\sessions", line 542, in request
  File "requests\sessions", line 655, in send
  File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

**Comment by Gunter-Dw-Jung** [comment]
dpi 우회를 껐는데 성공했습니다.
