### ISSUE TITLE
vimeo 비공개 동영상 다운로드가안됩니다.

### ISSUE THREAD

**Issue by wangdohwan** [KurtBestor/Hitomi-Downloader#4876]
patreon에서 vimeo 비공개 영상 다운로드가안돼요.. 쿠키불러오기를해도안되는데 방법이없을까요?

**Comment by wangdohwan** [comment]
Invalid: [vimeo] https://vimeo.com/718135608?embedded=true&source=video_title&owner=142075928

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 43cba686943348cf8481099ac625e445
input: https://vimeo.com/718135608?embedded=true&source=video_title&owner=142075928
type: vimeo
single: True
url: https://vimeo.com/718135608?embedded=true&source=video_title&owner=142075928
dir: 
zip: 
artist: None
valid / done: False / False
range / range_p: None / None
time: 1654948635.299238 (22-06-11 11:57:15 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading webpage
ERROR: [vimeo] 718135608: This video is protected by a password, use the --video-password option
stop
Traceback (most recent call last):
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\extractor\common", line 642, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\extractor\vimeo", line 890, in _real_extract
   video_password = self._get_video_password()
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\extractor\vimeo", line 90, in _get_video_password
   expected=True)
yt_dlp.utils.ExtractorError: This video is protected by a password, use the --video-password option

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1395, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1465, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\extractor\common", line 668, in extract
   raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [vimeo] 718135608: This video is protected by a password, use the --video-password option

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\vimeo_downloader", line 22, in read
 File "utils", line 786, in __call__
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\vimeo_downloader", line 45, in get
 File "ytdl", line 411, in extract_info
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1386, in extract_info
   return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1413, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 381, in report_error
yt_dlp.utils.DownloadError: ERROR: [vimeo] 718135608: This video is protected by a password, use the --video-password option

Invalid: fail=True
EOT: https://vimeo.com/718135608?embedded=true&source=video_title&owner=142075928  (3.2s)

[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading jwt token
[debug] [vimeo] 718135608: Downloading JSON metadata
[warning] [vimeo] Unable to download JSON metadata: HTTP Error 400: Bad Request
[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading jwt token
[debug] [vimeo] 718135608: Downloading JSON metadata
[warning] [vimeo] Unable to download JSON metadata: HTTP Error 400: Bad Request
[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading jwt token
[debug] [vimeo] 718135608: Downloading JSON metadata
[warning] [vimeo] Unable to download JSON metadata: HTTP Error 400: Bad Request
[debug] [vimeo] 718135608: Downloading webpage
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading JSON metadata
[debug] [vimeo] 718135608: Downloading jwt token
[debug] [vimeo] 718135608: Downloading JSON metadata
[warning] [vimeo] Unable to download JSON metadata: HTTP Error 400: Bad Request
ERROR: [vimeo] 718135608: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1395, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1479, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1535, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 2479, in process_video_result
   self.raise_no_formats(info_dict)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 968, in raise_no_formats
   expected=has_drm or ignored or expected)
yt_dlp.utils.ExtractorError: [vimeo] 718135608: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\vimeo_downloader", line 22, in read
 File "utils", line 786, in __call__
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\vimeo_downloader", line 45, in get
 File "ytdl", line 411, in extract_info
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1386, in extract_info
   return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
 File "C:\Users\wang\AppData\Local\Temp\_MEI252962\ytdl_310c9e59\yt_dlp\yt_dlp\YoutubeDL", line 1413, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 381, in report_error
yt_dlp.utils.DownloadError: ERROR: [vimeo] 718135608: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
