### ISSUE TITLE
업데이트 이후 뉴토끼 다운이 안됩니다.

### ISSUE THREAD

**Issue by kd00kd** [KurtBestor/Hitomi-Downloader#4879]
업데이트 전에는 뉴토끼 다운이 되었는데 업데이트 하고나니까 안되네요ㅠㅠ

[작업정보]
Browser required; Use --safemode
https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 3 / False / 5a0886eacbe240318b7125467580d435
input: https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98
type: manatoki
single: False
url: https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1654960091.370328 (22-06-11 15:08:11 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\manatoki_downloader", line 42, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 122, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98  (10.0s)

stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\manatoki_downloader", line 42, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 122, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98  (10.0s)

stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\manatoki_downloader", line 42, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 122, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98  (46.4s)

stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\manatoki_downloader", line 42, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 122, in get_soup
 File "clf2", line 114, in solve
 File "clf2", line 92, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki141.com/webtoon/843874/%ED%95%98%EB%82%98%ED%95%98%EB%82%98%EB%91%98  (10.0s)

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나온 내용 보여주세요
