### ISSUE TITLE
인스타그램 다운로드 오류

### ISSUE THREAD

**Issue by Infi9613** [KurtBestor/Hitomi-Downloader#4892]
쿠키 입력 완료한 상태입니다
Invalid: [insta] https://www.instagram.com/dlwlrma

version: 3.7l (22-06-07 05:23:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / a84ec08c9bdf49f39fed9f872af4a3a1
input: https://www.instagram.com/dlwlrma
type: insta
single: False
url: https://www.instagram.com/dlwlrma
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~99999999 / None
time: 1655224181.5298657 (22-06-14 16:29:41 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1169, in start
 File "extractor\insta_downloader", line 40, in init
 File "extractor\insta_downloader", line 28, in get_session
 File "clf2", line 143, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.instagram.com/dlwlrma  (101.4s)

**Comment by Rounlet** [comment]
비슷한 경우라고 생각돼서 대신 올려드립니다!
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/47098778/a3b6e087-18c0-4cdc-8ab8-1ca3a00ea49d)
