### ISSUE TITLE
업데이트후 픽시브코믹이 다운이 안되네요

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#4893]
항상 감사히 잘 쓰고 있습니다
업데이트 전에는 아무 이상 없었는데
업데이트 후에 다운이 안되네요
쿠키 초기화를 해도 안됩니다
정보 올릴게요

59분 32초 뒤 다시 시작: https://comic.pixiv.net/works/8426

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / cdfb997a07464ae4b59a0f9d90242189
input: https://comic.pixiv.net/works/8426
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8426
dir: 
zip: 
artist: とおる
valid / done: False / True
range / range_p: None / None
time: 1655269605.3736482 (22-06-15 05:06:45 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
dirFormat: [artist] title
no pages
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\pixiv_comic_downloader", line 66, in read
 File "extractor\pixiv_comic_downloader", line 150, in get_imgs
 File "extractor\pixiv_comic_downloader", line 128, in get_pages
Exception: no pages

Invalid: fail=True
EOT: https://comic.pixiv.net/works/8426  (7.7s)

**Comment by wlskekrk** [comment]
테스트버전 올려주신걸로 해보니까 잘되네요 정말 감사합니다
