### ISSUE TITLE
업데이트가 계속 실패합니다

### ISSUE THREAD

**Issue by zifm** [KurtBestor/Hitomi-Downloader#4896]
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 8479, in <module>
  File "hitomi_downloader_GUI.py", line 2760, in update
  File "updater.py", line 99, in update
  File "updater.py", line 106, in move_and_start
PermissionError: [WinError 5] 액세스가 거부되었습니다: 'tmp_update\\hitomi_downloader_GUI.exe_old'

이렇게 나와요 ㅠㅠ

**Comment by KurtBestor** [comment]
액세스를 허용해주세요
