### ISSUE TITLE
luscious 사이트 문제있나요?

### ISSUE THREAD

**Issue by kasuda112** [KurtBestor/Hitomi-Downloader#4905]
어제까지만해도 잘받아졌는데 오늘은 모든항목이 받아지질 않네요
원래 다운로더상 캡챠화면 뜨고 로그인하면 정상다운 됐었는데
오늘은 로그인해야 볼수있는 카테고리 / 아닌 카테고리 상관없이 다운 시도하면 모든 앨범이 잠시 읽다가 바로 invalid로 넘어갑니다.
혹여 사이트 문제일까요?

작업 첨부합니다

- [Invalid: [luscious] https://www.luscious.net/albums/chars_458531/

version: 3.7m (22-06-12 13:19:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 0221b86b7f7e48c8a6a3cde033048245
input: https://www.luscious.net/albums/chars_458531/
type: luscious
single: False
url: https://www.luscious.net/albums/chars_458531/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1655401737.105178 (22-06-16 17:48:57 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\luscious_downloader", line 66, in read
 File "extractor\luscious_downloader", line 168, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.luscious.net/albums/chars_458531/  (3.5s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\luscious_downloader", line 66, in read
 File "extractor\luscious_downloader", line 168, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.luscious.net/albums/chars_458531/  (2.3s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\luscious_downloader", line 66, in read
 File "extractor\luscious_downloader", line 168, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.luscious.net/albums/chars_458531/  (2.0s)
 ]

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kasuda112** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

테스트 결과입니다

1. 이전 일부 항목에서만 다운로더내의 웹브라우저로 인증하여 다운하던것이 모든 항목에 대해 웹브라우저 인증을 거치는것으로 바뀌었네요
2. 일단 작동은 하나 문제는 2개이상의 동시작업시 fail to create opengl ~~~ 오류가 뜨면서 다운로더가 튕깁니다(에러 내역 jpg파일로 캡쳐해뒀으나 첨부방법을 모르겠네요. 필요시 첨부방법 알려주시면 첨부하겠습니다.)
3. 동시작업 4개부터 1개까지 테스트 해봤는데 동시작업 1개일때는 오류발생하지 않고 2개이상부터는 오류가 발생합니다
4. 아무래도 인증절차중 충돌하는듯 합니다.
5. 일단은 1개 단일작업을 통해 받는중이며 이는 문제없이 작동합니다.

감사합니다.

**Comment by KurtBestor** [comment]
동시 작업 여러개 해도 한번에 한 개씩만 브라우저 동작하는데 왜 그런지 모르겠네요

테스트해봐도 재현할 수가 없어요

**Comment by kasuda112** [comment]
> 동시 작업 여러개 해도 한번에 한 개씩만 브라우저 동작하는데 왜 그런지 모르겠네요
> 
> 테스트해봐도 재현할 수가 없어요

아 결국 해결했습니다.
에러창에 그래픽 드라이버 업데이트랑 opengl 버전관련말이 있길래 찾답보니 장치관리에서 다운로더의 opengl 항목의 사용부분을 자동에서 외장그래픽으로 잡으니까 문제없이 작동하네요.
4개 동시작업에도 오류나지않고 작동하는거 확인했습니다. 감사합니다.
