### ISSUE TITLE
마나토끼 원피스 1화~57화까지만 다운이 안됩니다

### ISSUE THREAD

**Issue by matt2724** [KurtBestor/Hitomi-Downloader#4909]
사이트에서 페이지는 정상적으로 로딩이 되는데 다운만 안되네요
전체 목록을 다운받아도 58화부터만 다운되고 1화부터 57화까지는 개별로 받으려고해도 에러만 뜨고 다운이 안됩니다

전체 목록 주소
https://manatoki141.net/comic/122227

1화 주소
https://manatoki141.net/comic/6861239

**Comment by matt2724** [comment]
Invalid: [manatoki] https://manatoki141.net/comic/6861239

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko_kr
order / group / uid: 0 / False / be262f5983e348809c09583ebc444fa6
input: https://manatoki141.net/comic/6861239
type: manatoki
single: False
url: https://manatoki141.net/comic/6861239
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1655447697.566916 (22-06-17 06:34:57 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
can not find page
stop
Traceback (most recent call last):
 File "utils", line 1170, in start
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\manatoki_downloader", line 63, in init
Exception: can not find page

Invalid: fail=True
EOT: https://manatoki141.net/comic/6861239  (51.4s)
