### ISSUE TITLE
Luscious Problem

### ISSUE THREAD

**Issue by CashOver** [KurtBestor/Hitomi-Downloader#4923]
Hi I would like to warn you that Luscious is not working with all items as an example:

Invalid: [luscious] https://www.luscious.net/albums/naruto-hentai-collection_394700/

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / pt_br
order / group / uid: 0 / False / 06f0558800c1407ea6040deaebcf4915
input: https://www.luscious.net/albums/naruto-hentai-collection_394700/
type: luscious
single: False
url: https://www.luscious.net/albums/naruto-hentai-collection_394700/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~89550000 / None
time: 1655744230.6811337 (22-06-20 16:57:10 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: None None
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\luscious_downloader", line 60, in read
 File "extractor\luscious_downloader", line 146, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.luscious.net/albums/naruto-hentai-collection_394700/  (3.6s)

---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by tdi2020** [comment]
This has been modified in the test version.
Please check out here : https://github.com/KurtBestor/Hitomi-Downloader/issues/4905

**Comment by CashOver** [comment]
But I would like to know if this error will be fixed ?

**Comment by tdi2020** [comment]
Yes, It's been fixed.
