### ISSUE TITLE
제이마나쪽 다운로드가 안됩니다

### ISSUE THREAD

**Issue by jinhons** [KurtBestor/Hitomi-Downloader#4924]
9분 0초 뒤 다시 시작: https://jmana1.net/comic_list_title?bookname=%EB%9D%BC%EC%9D%B4%EC%96%B4+%EA%B2%8C%EC%9E%84

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 4d284e38ba8847989273270845096bc8
input: https://jmana1.net/comic_list_title?bookname=%EB%9D%BC%EC%9D%B4%EC%96%B4+%EA%B2%8C%EC%9E%84
type: jmana
single: False
url: https://jmana1.net/comic_list_title?bookname=%EB%9D%BC%EC%9D%B4%EC%96%B4+%EA%B2%8C%EC%9E%84
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1655792024.578646 (22-06-21 06:13:44 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://jmana1.net/comic_list_title?bookname=%EB%9D%BC%EC%9D%B4%EC%96%B4+%EA%B2%8C%EC%9E%84  (8.1s)

해당 이슈 혹시 확인 가능하실까요?

**Comment by dlraud21** [comment]
따로 말씀안남기셔서 직접 문제 해결했습니다
구버전으로 이용했고 파일 이름쪽 개발사측 정한 이름 일부 제거후 해보니 정상적으로 이용가능합니다
"_" 라는 단어를 제거만 했습니다.

**Comment by dlraud21** [comment]
개발사 아니지만 지금 다운이 되시나요?
