### ISSUE TITLE
Avgle 사이트 다운로드가 안돼요...

### ISSUE THREAD

**Issue by akg1020** [KurtBestor/Hitomi-Downloader#4927]
Invalid: [avgle] https://avgle.com/video/Npx_0_88q__/isafe

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.25136-SP0 / ko_kr
order / group / uid: 0 / False / 128765bd0b934fd9bc0eb1c444a00253
input: https://avgle.com/video/Npx_0_88q__/isafe
type: avgle
single: True
url: https://avgle.com/video/Npx_0_88q__/isafe
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1655820151.9125104 (22-06-21 14:02:31 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
version: 0.4
https://ip59439325.cdn.qooqlevideo.com/key=ujGydMDwGVe4zS92bxJmGA,s=,end=1655827061,limit=1/data=1655827061/state=YrHP3Ysq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/2/62246682.mp4/seg-1-v1-a1.ts
https://ip59439325.cdn.qooqlevideo.com/key=ujGydMDwGVe4zS92bxJmGA,s=,end=1655827061,limit=1/data=1655827061/state=YrHP3Ysq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/2/62246682.mp4/seg-2-v1-a1.ts
https://ip59439325.cdn.qooqlevideo.com/key=ujGydMDwGVe4zS92bxJmGA,s=,end=1655827061,limit=1/data=1655827061/state=YrHP3Ysq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/2/62246682.mp4/seg-3-v1-a1.ts
version: 0.4
https://ip59439325.cdn.qooqlevideo.com/key=ujGydMDwGVe4zS92bxJmGA,s=,end=1655827061,limit=1/data=1655827061/state=YrHP3Ysq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/2/62246682.mp4/seg-1-v1-a1.ts
https://ip59439325.cdn.qooqlevideo.com/key=ujGydMDwGVe4zS92bxJmGA,s=,end=1655827061,limit=1/data=1655827061/state=YrHP3Ysq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/2/62246682.mp4/seg-2-v1-a1.ts
https://ip59439325.cdn.qooqlevideo.com/key=ujGydMDwGVe4zS92bxJmGA,s=,end=1655827061,limit=1/data=1655827061/state=YrHP3Ysq/referer=force,.avgle.com/reftag=56109644/media=hlsA/ssd3/177/2/62246682.mp4/seg-3-v1-a1.ts
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 391, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\avgle_downloader", line 28, in read
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\avgle_downloader", line 59, in get_video
 File "downloader", line 418, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 212, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://avgle.com/video/Npx_0_88q__/isafe  (5.2s)

강제로 끊기면서 이런 현상이 발생하네요 이건 어떻게 해결할까요?

**Comment by akg1020** [comment]
참고로 혹시 링크 문제가 될 수 있어서 일부 가렸습니다
