### ISSUE TITLE
soundcloud error

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#4928]
[Tracks] NCS

version: 3.7m (22-06-20 14:29:31 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 6 / False / 53b4e5fa1e7b4d9ab63c2404d9a1dac1
input: https://soundcloud.com/nocopyrightsounds
type: soundcloud
single: False
url: https://soundcloud.com/nocopyrightsounds
dir: hitomi_downloaded_soundcloud\[Tracks] NCS
zip: 
artist: NCS
valid / done: False / True
range / range_p: ~2000000 / None
time: 1655801569.370787 (22-06-21 08:52:49 UTC)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: True
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_soundcloud\[Tracks] NCS\NCS - BVRNOUT Ft. Mia Vaile - Take It Easy (DNB Edit) [NCS Release].mp3

...

[1077] hitomi_downloaded_soundcloud\[Tracks] NCS\NCS - DJ ASSASS1N - Frag Out [NCS Release].mp3

[URLs]
[0001] LazyUrl(https://soundcloud.com/nocopyrightsounds/brianna-mendoza-bvrnout-ft-mia-vaile-take-it-easy-dnb-edit-ncs-release)    --->    https://cf-media.sndcdn.com/5xk1JNMvO8Jm.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNXhrMUpOTXZPOEptLjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjU1ODAyMDExfX19XX0_&Signature=AMqNDn2rIYCkQ4vGIHn7RN9od0FB92LKeKONa5tN6tT~3Ggx3sArUmg3ZphQwgcwyDB-JPj7A6gGWBCwTc4lmpO00zKWCOgyRiVnjLgj02FbFiWl0wAd9DPMI8XqqI1b0~Oi5cDkWuKH8s0HozD1eNPKwzKMZGnvMqI6uvgigzKlpv~qFBJGSAmIMZMWSD8jizY~8vI0sAKiIlpiy~11HrhMnSvL6BhjmvxxU6zppqpBncnGWqrzP9n~fK-0vN~6Yjt5p6L4PYLvfuWg8n3PK5soUTewirKzdVoSa7j86hkphTTLv2ye-mqFCaiQucnofdRxB47t~-BJOewDftt~lw__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ

...

[1077] LazyUrl(https://soundcloud.com/nocopyrightsounds/dj-assass1n-frag-out)    --->    https://cf-media.sndcdn.com/FvhRMlMI4ym5.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vRnZoUk1sTUk0eW01LjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjU1ODAzODA5fX19XX0_&Signature=JKTUSxHA9gN93ufKX7YI4FPDDsw1l6qdBY~Um2IamQhkEVqBYcen7j1Q1s8eSqOw5~8aWJqFMaCGWdt5Ss-RsUpYKgADrjcHHqxdeQ4wlnThaq~9aAU7sOZH3irlYWMMqN9cSK0OCD5fvFrvalHU2h-A6DaKtKlq4sK6CSAx2KGfZ-G4DpN7dkSgpd-E9K6WNnmt2hT5g4Dqz~hxP2WKXvnZjByEQCvQOHfGB0c7MJCdxWhWqOe6jNfn02WnfEG0qO0HnBKAXpZwtECNocCVqgIrzS613x1ZekzIUlCbLVMWCdIgFVsP9Acmfg4dO31FNq7-He4gSJd68Lt7cC9aYQ__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ

[Messages]
[debug] [soundcloud:user] nocopyrightsounds: Downloading user info
[debug] [download] Downloading playlist: NCS (Tracks)
[debug] [soundcloud:user] 16069159: Downloading track page 1
[debug] [soundcloud:user] 16069159: Downloading track page 2
[debug] [soundcloud:user] 16069159: Downloading track page 3
[debug] [soundcloud:user] 16069159: Downloading track page 4
[debug] [soundcloud:user] 16069159: Downloading track page 5
[debug] [soundcloud:user] 16069159: Downloading track page 6
[debug] [soundcloud:user] 16069159: Downloading track page 7
[debug] [soundcloud:user] 16069159: Downloading track page 8
[debug] [soundcloud:user] 16069159: Downloading track page 9
[debug] [soundcloud:user] playlist NCS (Tracks): Downloading 1077 videos
[debug] [download] Downloading video 1 of 1077
[debug] [soundcloud] nocopyrightsounds/brianna-mendoza-bvrnout-ft-mia-vaile-take-it-easy-dnb-edit-ncs-release: Downloading info JSON
[debug] [soundcloud] 1277886982: Downloading JSON metadata
[debug] [soundcloud] 1277886982: Downloading JSON metadata
[debug] [soundcloud] 1277886982: Downloading JSON metadata

...

[debug] [download] Downloading video 621 of 1077
[debug] [soundcloud] nocopyrightsounds/nurko-last-heroes-promise-me-feat-jessie-chambers-ncs-release: Downloading info JSON
[debug] [soundcloud] 473886993: Downloading JSON metadata
[debug] [soundcloud] 473886993: Downloading JSON metadata
[debug] [soundcloud] 473886993: Downloading JSON metadata
[debug] [download] Downloading video 622 of 1077
[debug] [soundcloud] nocopyrightsounds/diviners-falling-feat-harley-bird-ncs-release: Downloading info JSON

⋮

54313 hidden messages

⋮

Fail : \\?\G:\새 폴더 (5)\기타\hitomi_downloaded_soundcloud\[Tracks] NCS\NCS - DM Galaxy - Paralyzed (Disfigure Remix) [NCS Release].mp3
Traceback (most recent call last):
 File "downloader", line 1054, in download
Exception: 403

retry (20)

...

Fail : \\?\G:\새 폴더 (5)\기타\hitomi_downloaded_soundcloud\[Tracks] NCS\NCS - DJ ASSASS1N - Frag Out [NCS Release].mp3
Traceback (most recent call last):
 File "downloader", line 1054, in download
Exception: 403

stop
valid=False 1
EOT: https://soundcloud.com/nocopyrightsounds  (16751.2s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
