### ISSUE TITLE
xhamster 다운로드가 또 막힌거같습니다..ㅠ

### ISSUE THREAD

**Issue by Gemini582** [KurtBestor/Hitomi-Downloader#4946]
Invalid: [xhamster] https://xhwide.com/videos/dominican-lipz-best-blowjob-ever-dslaf-12472387

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / b21fd386bc36490f9b110624bd90f389
input: https://xhwide.com/videos/dominican-lipz-best-blowjob-ever-dslaf-12472387
type: xhamster
single: True
url: https://xhwide.com/videos/dominican-lipz-best-blowjob-ever-dslaf-12472387
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1656256386.0469754 (22-06-26 15:13:06 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.06.22.1
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 391, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\xhamster_downloader", line 58, in read
 File "utils", line 786, in __call__
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\xhamster_downloader", line 76, in get
 File "extractor\xhamster_downloader", line 105, in get_info
 File "downloader", line 418, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 212, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://xhwide.com/videos/dominican-lipz-best-blowjob-ever-dslaf-12472387  (1.8s)

확인 한번 부탁드립니다

**Comment by Gemini582** [comment]
6/28 10:22 이유는 모르겠지만 다시 다운로드가 됩니다!
