### ISSUE TITLE
다운로드 불가 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#4954]
https://hentai-cosplays.com  

어제 위 사이트에서 꽤 많은 양을 다운받고,
오늘 다운을 이어서 받으려니 브라우저상 captcha 에서 안넘어갔습니다. (브라우저가 자동으로 닫힐 경우에도 다운로드 불가)
그래서 재도전 하니 브라우저에 i'm not robot 같은 버튼이 떠있었고 그걸 누르니 ,
브라우저 상에서 404 forbidden 이라는 텍스트가 있는 페이지가 뜨고 브라우저가 닫힙니다.
그 뒤로는 아예 다운로드가 불가한 상태입니다.

-이상한 점-
만약 ip 밴이라면 사이트 상에서 이미지 로드도 막힐것 같은데 사이트 접속도 잘 되고 정상적으로 모든 게시물이 봐집니다.
이 경우에는 히토미 다운로더 자체를 막은것일까요? 
아니면 [아이피 + 히토미 다운로더] 이렇게의 조합을 막은것일지 궁금합니다.

그리고 다시 받으려면 방법이 없을지 궁금합니다.

아래는 로그입니다.

-------------------------------------

Invalid: [hentaicosplay] https://hentai-cosplays.com/image/fategrandorder-mansei-bushi-ashu-x-sada-cosplay-8p/

version: 3.7m (22-06-21 02:04:31 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 2481 / False / 2b2095665338445fbfc3b130f046295b
input: https://hentai-cosplays.com/image/fategrandorder-mansei-bushi-ashu-x-sada-cosplay-8p/
type: hentaicosplay
single: False
url: https://hentai-cosplays.com/image/fategrandorder-mansei-bushi-ashu-x-sada-cosplay-8p/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~9999999 / None
time: 1656499372.835448 (22-06-29 10:42:52 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.06.29
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1187, in start
 File "utils", line 1257, in start_
 File "extractor\hentaicosplay_downloader", line 82, in read
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://hentai-cosplays.com/image/fategrandorder-mansei-bushi-ashu-x-sada-cosplay-8p/  (7.7s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4961#issuecomment-1179475364
