### ISSUE TITLE
Hentaicosplay 사이트 먹통 ㅗ디었네요 

### ISSUE THREAD

**Issue by Siva2323** [KurtBestor/Hitomi-Downloader#4961]
Invalid: [hentaicosplay] https://hentai-cosplays.com/image/djawa-bambi--succubus-2b/

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 599e6d7db07c463b959981fb961797a7
input: https://hentai-cosplays.com/image/djawa-bambi--succubus-2b/
type: hentaicosplay
single: False
url: https://hentai-cosplays.com/image/djawa-bambi--succubus-2b/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: ~5000 / None
time: 1656825159.8638039 (22-07-03 05:12:39 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.06.29
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\hentaicosplay_downloader", line 82, in read
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://hentai-cosplays.com/image/djawa-bambi--succubus-2b/  (7.2s)

-----------------------------------

막히네요...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Siva2323** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

안되네요

Invalid: [hentaicosplay] https://hentai-cosplays.com/image/djawa--holidays-in-eden/

version: 3.7m (22-07-09 03:59:30 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 6 / False / 63411a7c23d24999bd40463899fd6efa
input: https://hentai-cosplays.com/image/djawa--holidays-in-eden/
type: hentaicosplay
single: False
url: https://hentai-cosplays.com/image/djawa--holidays-in-eden/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1657357472.386992 (22-07-09 09:04:32 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.06.29
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
read start ua: Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.70 Mobile Safari/537.36
no html
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
read start ua: Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/103.0.5060.63 Mobile/15E148 Safari/604.1
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1207, in start
 File "utils", line 1277, in start_
 File "decorator", line 232, in fun
 File "constants", line 962, in wrapper
 File "constants", line 933, in wrapper
 File "extractor\hentaicosplay_downloader", line 92, in read
 File "clf2", line 143, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://hentai-cosplays.com/image/djawa--holidays-in-eden/  (182.1s)

**Comment by KurtBestor** [comment]
캡챠 창 뜨면 푸셔야해요

**Comment by tdi2020** [comment]
여전히 다운이 안되는 것을 확인하였습니다.

한가지 이상한 부분은, 캡챠가 눌러도 눌러도 계속해서 뜨다가 실패한다는 점이에요.
verify i am not a bot  <- 요 버튼이 떠서 누르면 
[ ] 사람입니다  <- 요 박스가 뜨고, 그걸 다시 누르면
다시 verify i am not a bot 버튼으로 뜨면서 무한 반복되다가 어느 순간 꺼집니다. 
10번 정도 반복하다 붉게 되네요.

캡챠 사진고르기나 이런건 전혀 뜨지 않고 저 두 버튼만 반복해서 번갈아 떴습니다. (물론 빠짐없이 체크박스는 누름) 
해결 방법이 있을까요?


아래는 2회 시도한 로그입니다!




Invalid: [hentaicosplay] https://hentai-cosplays.com/image/bluecake-yeeun-reverse-bunny-girl-and-verred/

version: 3.7m (22-07-11 03:05:09 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid / False / b0bf893ae16948d28b28eab93bc6dd7c
input: https://hentai-cosplays.com/image/bluecake-yeeun-reverse-bunny-girl-and-verred/
type: hentaicosplay
single: False
url: https://hentai-cosplays.com/image/bluecake-yeeun-reverse-bunny-girl-and-verred/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1657893005.9743261 (22-07-15 13:50:05 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.06.29
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
read start ua: Mozilla/5.0 (Linux; Android 10; LM-Q720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.70 Mobile Safari/537.36
no html
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
read start ua: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1207, in start
 File "utils", line 1277, in start_
 File "decorator", line 232, in fun
 File "constants", line 962, in wrapper
 File "constants", line 933, in wrapper
 File "extractor\hentaicosplay_downloader", line 92, in read
 File "clf2", line 143, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://hentai-cosplays.com/image/bluecake-yeeun-reverse-bunny-girl-and-verred/  (184.5s)

read start ua: Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/103.0.5060.63 Mobile/15E148 Safari/604.1
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
read start ua: Mozilla/5.0 (Linux; Android 10; LM-Q720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.70 Mobile Safari/537.36
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
wait captcha...
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1207, in start
 File "utils", line 1277, in start_
 File "decorator", line 232, in fun
 File "constants", line 962, in wrapper
 File "constants", line 933, in wrapper
 File "extractor\hentaicosplay_downloader", line 92, in read
 File "clf2", line 143, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://hentai-cosplays.com/image/bluecake-yeeun-reverse-bunny-girl-and-verred/  (182.0s)
