### ISSUE TITLE
유튜브 음원변환이 되지 않습니다 

### ISSUE THREAD

**Issue by keroberos-s** [KurtBestor/Hitomi-Downloader#5014]
Every Heart -ミンナノキモチ／Minnanokimochi- (The Greatest Version)

version: 3.7m (22-06-08 05:17:46 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 8 / False / 262cac0a9d5542c6ae68e81e3e388a1a
input: https://www.youtube.com/watch?v=8mPLTkyV2Uk
type: youtube
single: True
url: https://www.youtube.com/watch?v=8mPLTkyV2Uk
dir: hitomi_downloaded_youtube
zip: 
artist: BoA - Topic
valid / done: False / True
range / range_p: None / None
time: 1658319480.5837371 (22-07-20 12:18:00 UTC)
tags: []
lock: False
color: invalid_done
paused: False
format: mp3
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.tmp

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=8mPLTkyV2Uk)    --->    https://rr2---sn-ab02a0nfpgxapox-20nl.googlevideo.com/videoplayback?expire=1658341079&ei=d_LXYvzRJo364gLXyq2wDg&ip=182.222.170.212&id=o-ANLgGlGeDNHfOAWzLk_IeZk4U0Pf3fGXPH1qKc5DwuX5&itag=22&source=youtube&requiressl=yes&mh=9j&mm=31%2C29&mn=sn-ab02a0nfpgxapox-20nl%2Csn-ab02a0nfpgxapox-bh2sd&ms=au%2Crdu&mv=m&mvi=2&pl=25&gcr=kr&initcwndbps=2108750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=283.445&lmt=1650622264985232&mt=1658319205&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=2318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZYAohJPpQaec_d3xBgPCmuP6Za0Knl_q72OoDRxuvsUCIQDta5FGIbPJVFxmS2kk1WTun5RpTUPTwnoe7T1ZXOssrA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOllYmSadO51tV16qHKdiURFIxWmP1xms7nK4nGLagVuAiEA30PKQIPClrXqYj-Vo41FjS-7JEl1151xCll_SmJhfLI%3D

[Messages]
[debug] [youtube] 8mPLTkyV2Uk: Downloading webpage
[debug] [youtube] 8mPLTkyV2Uk: Downloading android player API JSON
[27p][0.35335689045936397fps][None][None] mhtml [None / None] ─ sb2 - 48x27 (storyboard)
[45p][0.5053003533568905fps][None][None] mhtml [None / None] ─ sb1 - 45x45 (storyboard)
[90p][0.5053003533568905fps][None][None] mhtml [None / None] ─ sb0 - 90x90 (storyboard)
[None][0fps][48.852kbps][48.852] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][56.463kbps][56.463] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][74.099kbps][74.099] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.541kbps][129.541] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][143.714kbps][143.714] webm [None / opus] ─ 251 - audio only (medium)
[144p][6fps][24.0kbps(fixed)][45.318] 3gp [mp4v.20.3 / mp4a.40.2] ─ 17 - 176x144 (144p)
[144p][25fps][None][12.8] mp4 [avc1.4d400b / None] ─ 160 - 144x144 (144p)
[144p][25fps][None][15.524] webm [vp9 / None] ─ 278 - 144x144 (144p)
[240p][25fps][None][20.762] mp4 [avc1.4d400c / None] ─ 133 - 240x240 (240p)
[240p][25fps][None][20.176] webm [vp9 / None] ─ 242 - 240x240 (240p)
[360p][25fps][None][32.739] mp4 [avc1.4d4015 / None] ─ 134 - 360x360 (360p)
[360p][25fps][96.0kbps(fixed)][161.39] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 360x360 (360p)
[360p][25fps][None][28.914] webm [vp9 / None] ─ 243 - 360x360 (360p)
[480p][25fps][None][51.539] mp4 [avc1.4d401e / None] ─ 135 - 480x480 (480p)
[480p][25fps][None][38.91] webm [vp9 / None] ─ 244 - 480x480 (480p)
[720p][25fps][192.0kbps(fixed)][231.87] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 720x720 (720p)
[720p][25fps][None][103.218] mp4 [avc1.64001f / None] ─ 136 - 720x720 (720p)
[720p][25fps][None][71.411] webm [vp9 / None] ─ 247 - 720x720 (720p)
[1080p][25fps][None][207.635] mp4 [avc1.640020 / None] ─ 137 - 1080x1080 (1080p)
[1080p][25fps][None][150.296] webm [vp9 / None] ─ 248 - 1080x1080 (1080p)

utime: 1650758400.0
# stream_final <ytdl.Video object at 0x000001FE432536C8> 22 - 720x720 (720p) 720p mp4 mp4a.40.2 25fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192.0
Subtype: mp4
FPS: 25

Convert: C:\Users\newkero\Desktop\hitomi_downloader_GUI\hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.tmp
rename (1): C:\Users\newkero\Desktop\hitomi_downloader_GUI\hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.tmp -> C:\Users\newkero\Desktop\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp5c7f7a387f764a3686641095f4e44783_i.tmp
-i tmp5c7f7a387f764a3686641095f4e44783_i.tmp -shortest -preset ultrafast -b:a 192k -threads 0 tmp5c7f7a387f764a3686641095f4e44783_o.mp3
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp5c7f7a387f764a3686641095f4e44783_i.tmp': 
 Metadata: 
   major_brand     : mp42 
   minor_version   : 0 
   compatible_brands: isommp42 
   creation_time   : 2022-04-22T10:10:49.000000Z 
 Duration: 00:04:43.42, start: 0.000000, bitrate: 231 kb/s 
 Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 720x720 [SAR 1:1 DAR 1:1], 100 kb/s, 25 fps, 25 tbr, 12800 tbn (default) 
   Metadata: 
     creation_time   : 2022-04-22T10:10:49.000000Z 
     handler_name    : ISO Media file produced by Google Inc. Created on: 04/22/2022. 
     vendor_id       : [0][0][0][0] 
 Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default) 
   Metadata: 
     creation_time   : 2022-04-22T10:10:49.000000Z 
     handler_name    : ISO Media file produced by Google Inc. Created on: 04/22/2022. 
     vendor_id       : [0][0][0][0] 
Codec AVOption preset (Encoding preset [0, 8]) specified for output file #0 (tmp5c7f7a387f764a3686641095f4e44783_o.mp3) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream. 
Stream mapping: 
 Stream #0:1 -> #0:0 (aac (native) -> mp3 (libmp3lame)) 
Press [q] to stop, [?] for help 
Output #0, mp3, to 'tmp5c7f7a387f764a3686641095f4e44783_o.mp3': 
 Metadata: 
   major_brand     : mp42 
   minor_version   : 0 
   compatible_brands: isommp42 
   TSSE            : Lavf59.8.100 
 Stream #0:0(und): Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s (default) 
   Metadata: 
     creation_time   : 2022-04-22T10:10:49.000000Z 
     handler_name    : ISO Media file produced by Google Inc. Created on: 04/22/2022. 
     vendor_id       : [0][0][0][0] 
     encoder         : Lavc59.12.100 libmp3lame 
size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x     size=    1024kB time=00:00:43.78 bitrate= 191.6kbits/s speed=87.6x     size=    2048kB time=00:01:28.53 bitrate= 189.5kbits/s speed=88.5x     size=    3072kB time=00:02:13.22 bitrate= 188.9kbits/s speed=88.8x     size=    4096kB time=00:02:57.08 bitrate= 189.5kbits/s speed=88.5x     size=    5120kB time=00:03:41.91 bitrate= 189.0kbits/s speed=88.7x     size=    6144kB time=00:04:24.28 bitrate= 190.4kbits/s speed=88.1x     size=    6644kB time=00:04:43.42 bitrate= 192.0kbits/s speed=88.5x     
video:0kB audio:6643kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.011216% 
[code]
0
rename (1): C:\Users\newkero\Desktop\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp5c7f7a387f764a3686641095f4e44783_o.mp3 -> hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.mp3
rename: hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.mp3 -> hitomi_downloaded_youtube\Every Heart -ミンナノキモチ／Minnanokimochi- (The Greatest Version) (8mPLTkyV2Uk).mp3
Lazyurl pp Error: hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.tmp
Traceback (most recent call last):
 File "hitomi_downloader", line 325, in run
 File "extractor\youtube_downloader", line 297, in pp
FileExistsError: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'hitomi_downloaded_youtube\\5c20401a566b4e5b9f4d032c71ca323e_audio.mp3' -> 'hitomi_downloaded_youtube\\Every Heart -ミンナノキモチ／Minnanokimochi- (The Greatest Version) (8mPLTkyV2Uk).mp3'

utime Error: hitomi_downloaded_youtube\5c20401a566b4e5b9f4d032c71ca323e_audio.tmp
Traceback (most recent call last):
 File "hitomi_downloader", line 339, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_youtube\\5c20401a566b4e5b9f4d032c71ca323e_audio.tmp'

stop
-show_streams -print_format json -v error "5c20401a566b4e5b9f4d032c71ca323e_audio.tmp"
{ 

} 
5c20401a566b4e5b9f4d032c71ca323e_audio.tmp: No such file or directory 
Traceback (most recent call last):
 File "utils", line 1655, in finish
 File "ffmpeg", line 672, in get_info
 File "ffmpeg", line 669, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.youtube.com/watch?v=8mPLTkyV2Uk  (6.4s)

노란색뜨네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4903
