### ISSUE TITLE
kissjav playlist 다운로드 불가 현상

### ISSUE THREAD

**Issue by Pseudo-Ray** [KurtBestor/Hitomi-Downloader#5020]
안녕하세요.

https://github.com/KurtBestor/Hitomi-Downloader/issues/4835 의 해결법을 보고 프리뷰를 적용해 보았으나,

사이트 자체의 재생목록 방식이 변경되어 그런지 playlist 를 통째로 받는 건 작동을 하지 않네요.

다음은 오류 로그입니다.

3분 3초 뒤 다시 시작: https://kissjav.li/playlist/51243/onlyfans/

version: 3.7m (22-07-21 04:50:42 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / 930d893092eb4cd9be9fda113700e44f
input: https://kissjav.li/playlist/51243/onlyfans/
type: kissjav
single: True
url: https://kissjav.li/playlist/51243/onlyfans/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1658413286.558982 (22-07-21 14:21:26 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\kissjav_downloader", line 19, in read
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\kissjav_downloader", line 34, in get_video
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kissjav.li/playlist/51243/onlyfans/  (3.8s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\kissjav_downloader", line 19, in read
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\kissjav_downloader", line 34, in get_video
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kissjav.li/playlist/51243/onlyfans/  (3.7s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\kissjav_downloader", line 19, in read
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\kissjav_downloader", line 34, in get_video
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kissjav.li/playlist/51243/onlyfans/  (3.8s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1184, in start
 File "utils", line 1254, in start_
 File "extractor\kissjav_downloader", line 19, in read
 File "decorator", line 232, in fun
 File "constants", line 933, in wrapper
 File "constants", line 904, in wrapper
 File "extractor\kissjav_downloader", line 34, in get_video
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kissjav.li/playlist/51243/onlyfans/  (3.8s)

'NoneType' object has no attribute 'findAll'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "extractor\kissjav_downloader", line 19, in read
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\kissjav_downloader", line 34, in get_video
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://kissjav.li/playlist/51243/onlyfans/  (3.7s)

**Comment by KurtBestor** [comment]
Playlist 는 지원하지 않아요
