### ISSUE TITLE
업데이트 후, 히토미 작품을 압축후 삭제 옵션으로 할 경우 생기는 오류

### ISSUE THREAD

**Issue by Tentailsahri** [KurtBestor/Hitomi-Downloader#5036]
업데이트 전엔 안그랬는데, 업데이트 후에 

히토미 작품을 옵션-설정-압축 에서 히토미를 zip으로 압축 후 원본파일 삭제 하는 옵션을 할 경우

작품들이 정상적으로 다 다운이 되지만

작품목록에는 빨간색으로 표시되면서 Invaild 라고 나옵니다.

작품명 예시 : Invalid: [hitomi] #-*- [Starraisins] Suwako | 스와코 단편 (2095249)

더블클릭하면 정상적으로 파일 다운도 되있고 연결도 되있는데, 오류파일로 출력이 납니다.

**Comment by Tentailsahri** [comment]
방금 추가로 실험해본 결과 pixiv도 똑같습니다.

압축 후 원본파일 삭제 옵션의 문제 같아요

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by Tentailsahri** [comment]
> 

꼭 이것 말고 다른걸 받아도 동일하게 일어납니다.

Invalid: [hitomi] #-*- [Hinata Yuu] Kyou mo Iroha ga Sabori ni Kita. | 오늘도 이로하가 땡땡이치러 왔다 (2280634)

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / b89522e4ba12438f8ad6797672125f35
input: [Hinata Yuu] Kyou mo Iroha ga Sabori ni Kita. | 오늘도 이로하가 땡땡이치러 왔다 (2280634)
type: hitomi
single: False
url: https://hitomi.la/galleries/2280634.html
dir: 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다
zip: 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다.zip
artist: hinata yuu
valid / done: False / True
range / range_p: None / None
time: 1658896693.8850942 (22-07-27 04:38:13 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: False


[Gallery]
갤러리 넘버: 2280634

제목: Kyou mo Iroha ga Sabori ni Kita. | 오늘도 이로하가 땡땡이치러 왔다

작가: hinata yuu

그룹: atelier hinata

타입: doujinshi

시리즈: blue archive

캐릭터: iroha natsume

태그: female:kissing, female:loli, female:nakadashi, female:sole female, female:very long hair, female:x-ray, male:sole male

언어: Korean


[File Names]
[0001] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0000.webp
[0002] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0001.webp
[0003] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0002.webp
[0004] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0003.webp
[0005] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0004.webp
[0006] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0005.webp
[0007] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0006.webp
[0008] 다운\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\0007.webp


[URLs]
[0001] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://aa.hitomi.la/webp/1658894402/3354/3661411120660d5c7ae40a94f4e28d6e0fc5a407be8a637137b6722f8860c1ad.webp
[0002] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://aa.hitomi.la/webp/1658894402/3240/e1aa12f7ff8f49b41e332d744a3e2a95d77affcb24f9737d82656aecb2bdba8c.webp
[0003] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://ba.hitomi.la/webp/1658894402/1200/83e568ae5bf4772f3bc111f97d89e55419f154457a60d496cbd319e54e770b04.webp
[0004] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://ba.hitomi.la/webp/1658894402/3557/8869d678f3158a0157071f15c940f84f645e020debdef0f7b3b55fab4efd3e5d.webp
[0005] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://ba.hitomi.la/webp/1658894402/134/1b5debd12039fe6cd178f31562a7973d6e19344416b3fdf8a10d00ee59802860.webp
[0006] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://ba.hitomi.la/webp/1658894402/1797/c57955e71b89fe550dba02b40c970e2384e4b350f23f7671001983da85f9e057.webp
[0007] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://ba.hitomi.la/webp/1658894402/3733/76c21e4211fa31de2c163b2850f3e6511b1daf92509b3a525d71297d7eeff95e.webp
[0008] LazyUrl(https://hitomi.la/reader/2280634.html)    --->    https://aa.hitomi.la/webp/1658894402/1924/934570c0a23018f814b6f3d33e896098f8d20321ea52b17abe44b523705c5847.webp


[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 8

stop
quality: 75%
[0000.webp]  [webp] 1280x1791 --> pass
[0001.webp]  [webp] 1110x1553 --> pass
[0002.webp]  [webp] 1110x1553 --> pass
[0003.webp]  [webp] 1280x1791 --> pass
[0004.webp]  [webp] 1280x1791 --> pass
[0005.webp]  [webp] 1280x1791 --> pass
[0006.webp]  [webp] 1280x1791 --> pass
[0007.webp]  [webp] 1280x1791 --> pass
Compress... 0000.webp
Compress... 0001.webp
Compress... 0002.webp
Compress... 0003.webp
Compress... 0004.webp
Compress... 0005.webp
Compress... 0006.webp
Compress... 0007.webp
[WinError 3] 지정된 경로를 찾을 수 없습니다: 'D:\\십미아리\\동인지\\히토미\\다운\\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\\0000.webp' -> 'D:\\십미아리\\동인지\\히토미\\다운\\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\\0000_hook.webp'
stop
Traceback (most recent call last):
 File "utils", line 1209, in start
 File "utils", line 1463, in finish
 File "utils", line 223, in exec_hook
 File "dynamic_module_5", line 13, in hook_rename
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'D:\\십미아리\\동인지\\히토미\\다운\\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\\0000.webp' -> 'D:\\십미아리\\동인지\\히토미\\다운\\[Hinata Yuu] [Korean] (2280634) Kyou mo Iroha ga Sabori ni Kita. ｜ 오늘도 이로하가 땡땡이치러 왔다\\0000_hook.webp'

Invalid: fail=True
EOT: #-*- [Hinata Yuu] Kyou mo Iroha ga Sabori ni Kita. | 오늘도 이로하가 땡땡이치러 왔다 (2280634)  (5.3s)

**Comment by KurtBestor** [comment]
프로그램 문제가 아니라 후킹 스크립트에서 오류가 나는 거네요

**Comment by Tentailsahri** [comment]
> 프로그램 문제가 아니라 후킹 스크립트에서 오류가 나는 거네요

해결 했습니다.

https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins

여기서 Rename after task is finished 이게 문제였네요.
