### ISSUE TITLE
윈도우11로 업그레이드 한 이후로 실행이 안됩니다.

### ISSUE THREAD

**Issue by rodoria** [KurtBestor/Hitomi-Downloader#5045]
pc를 교체한 후 os도 10에서 11로 업그레이드했습니다.
그 후로 실행하면 다운로더는 실행이 안되고 _MEIxxxxxx폴더가 다운로더와 동일폴더에 생성되었다가 사라집니다.
x는 숫자인데 매번바뀌고 다섯자리일때도 있고 여섯자리일때도 있습니다.
_MEI폴더는 금방 사라져서 생기자마자 다른 위치로 변경하는 식으로 폴더내용중 일부를 남겨서 살펴봤는데
backports, certifi, cryptography등의 폴더 .dll .pyd파일들이 있습니다.

**Comment by rodoria** [comment]
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 58, in <module>
  File "single.pyo", line 22, in __init__
OSError: [Errno 17] File exists

이런 로그파일이 있네요

**Comment by rodoria** [comment]
해결했습니다.
관리자권한으로 실행하니 정상적으로 실행되네요.
