### ISSUE TITLE
특정 만화가 다운이 되질 않아요

### ISSUE THREAD

**Issue by Ojdd** [KurtBestor/Hitomi-Downloader#5047]
[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: -710 / False / 6a50036093134c98ab3f7bf168768024
input: 2241209
type: ehen
single: False
url: https://e-hentai.org/g/2241209/fcba7a4141
dir: 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)
zip: 
artist: ushiro muki
valid / done: True / False
range / range_p: None / None
time: 1658757685.0121808 (22-07-25 14:01:25 UTC)
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: False

[Gallery]
갤러리 넘버: 2241209

제목: [Ushiro Muki] Houshoku | 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital]

작가: ushiro muki

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:anal, female:double penetration, female:loli, female:rape, female:sole female, female:twintails, male:bbm

언어: Korean

[File Names]
[0001] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0104_.jpg
[0002] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0105_.jpg
[0003] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0106_.jpg
[0004] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0107_.jpg
[0005] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0108_.jpg
[0006] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0109_.jpg
[0007] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0110_.jpg
[0008] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0111_.jpg
[0009] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0112_.jpg
[0010] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0113_.jpg
[0011] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0114_.jpg
[0012] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0115_.jpg
[0013] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0116_.jpg
[0014] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0117_.jpg
[0015] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0118_.jpg
[0016] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0119_.jpg
[0017] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0120_.jpg
[0018] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0121_.jpg
[0019] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0122_.jpg
[0020] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0123_.jpg
[0021] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0124_.jpg
[0022] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0125_.jpg
[0023] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0126_.jpg
[0024] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0127_.jpg
[0025] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0128_.jpg
[0026] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0129_.jpg
[0027] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0130_.jpg
[0028] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0131_.jpg
[0029] 다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0131_ (2).jpg

[URLs]
[0001] LazyUrl_ehen(https://e-hentai.org/s/2aef5ec3e0/2241209-1)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=1&key=rdofynj9vj2
[0002] LazyUrl_ehen(https://e-hentai.org/s/90e12108c0/2241209-2)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=2&key=hqyci8f9vj2
[0003] LazyUrl_ehen(https://e-hentai.org/s/d88addc150/2241209-3)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=3&key=bepjwq69vj2
[0004] LazyUrl_ehen(https://e-hentai.org/s/c3e171b9a5/2241209-4)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=4&key=mq1vxeg9vj2
[0005] LazyUrl_ehen(https://e-hentai.org/s/d679ff33fb/2241209-5)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=5&key=mhmqbrw9vj2
[0006] LazyUrl_ehen(https://e-hentai.org/s/e2bd5cad86/2241209-6)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=6&key=2c4ph4o9vj2
[0007] LazyUrl_ehen(https://e-hentai.org/s/8d0b4e9211/2241209-7)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=7&key=f3h4orv9vj2
[0008] LazyUrl_ehen(https://e-hentai.org/s/70fcd998ac/2241209-8)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=8&key=vd182qs9vj2
[0009] LazyUrl_ehen(https://e-hentai.org/s/7c828733e9/2241209-9)    --->    https://e-hentai.org/fullimg.php?gid=2241209&page=9&key=9xlm9em9vj2
[0010] LazyUrl_ehen(https://e-hentai.org/s/28806e5ecd/2241209-10)
[0011] LazyUrl_ehen(https://e-hentai.org/s/89e245cf6e/2241209-11)
[0012] LazyUrl_ehen(https://e-hentai.org/s/d036b54699/2241209-12)
[0013] LazyUrl_ehen(https://e-hentai.org/s/7abe614181/2241209-13)
[0014] LazyUrl_ehen(https://e-hentai.org/s/a919b2e857/2241209-14)
[0015] LazyUrl_ehen(https://e-hentai.org/s/e631f98210/2241209-15)
[0016] LazyUrl_ehen(https://e-hentai.org/s/57a56feeb4/2241209-16)
[0017] LazyUrl_ehen(https://e-hentai.org/s/5813ee1c26/2241209-17)
[0018] LazyUrl_ehen(https://e-hentai.org/s/472d8e9b1a/2241209-18)
[0019] LazyUrl_ehen(https://e-hentai.org/s/a71d05298e/2241209-19)
[0020] LazyUrl_ehen(https://e-hentai.org/s/ac10d0a876/2241209-20)
[0021] LazyUrl_ehen(https://e-hentai.org/s/fc3eda8609/2241209-21)
[0022] LazyUrl_ehen(https://e-hentai.org/s/8eccfbd291/2241209-22)
[0023] LazyUrl_ehen(https://e-hentai.org/s/2d3035e539/2241209-23)
[0024] LazyUrl_ehen(https://e-hentai.org/s/1009ba8612/2241209-24)
[0025] LazyUrl_ehen(https://e-hentai.org/s/157f33dc7e/2241209-25)
[0026] LazyUrl_ehen(https://e-hentai.org/s/3e6d284eb3/2241209-26)
[0027] LazyUrl_ehen(https://e-hentai.org/s/a0ea21f3fa/2241209-27)
[0028] LazyUrl_ehen(https://e-hentai.org/s/2139d7c014/2241209-28)
[0029] LazyUrl_ehen(https://e-hentai.org/s/0fa97ba11d/2241209-29)

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:2241209)
Find_ehen(id:2241209, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
max_page = 35575
BFS: 1.0
BFS: 2.0
BFS: 3.0
BFS: 4.0
BFS: 5.0
BFS: 6.0
BFS: 7.0
BFS: 8.0
BFS: 9.0
BFS: 10.0
BFS: 11.2
BFS: 12.2
#### https://e-hentai.org/g/2241209/fcba7a4141    ---->    https://e-hentai.org/g/2241209/fcba7a4141/?p=1
MPV: False
get_title_ehen: https://e-hentai.org/g/2241209/fcba7a4141
FINAL SERVER: ehen
ehen_url: https://e-hentai.org/g/2241209/fcba7a4141
imgs: 29
E-Hentai: https://e-hentai.org/g/2241209/fcba7a4141

Fail : \\?\C:\Users\kimbi\Desktop\다운로더\다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0104_.jpg
Traceback (most recent call last):
 File "downloader", line 1166, in download
Exception: HTML: E-Hentai.org Login

retry (1)

Fail : \\?\C:\Users\kimbi\Desktop\다운로더\다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0104_.jpg
Traceback (most recent call last):
 File "downloader", line 1166, in download
Exception: HTML: E-Hentai.org Login

retry (2)

Fail : \\?\C:\Users\kimbi\Desktop\다운로더\다운로드\[Ushiro Muki] [Ushiro Muki] Houshoku ｜ 포식 (COMIC AUN 2022-04) [Korean] [팀 털난보리] [Digital] (2241209)\b120ahit01524_0104_.jpg
Traceback (most recent call last):
 File "downloader", line 1166, in download
Exception: HTML: E-Hentai.org Login

다른 만화는 정상적으로 다운되는데 이거만 계속 retry 뜨고 무한로딩되면서 다운이 안되는데 왜 이런거에요?

**Comment by Ojdd** [comment]
몇개 다운받아보니까 다른 만화도 어떤건 다운되고 어떤건 무한로딩 되네요

**Comment by KurtBestor** [comment]
로그인을 하지 않으면 `원본 이미지 다운로드`는 쓸 수 없어요

**Comment by Ojdd** [comment]
> 로그인을 하지 않으면 `원본 이미지 다운로드`는 쓸 수 없어요

이미 로그인되있어요 몇개는 정상적으로 원본다운로드 했구요
