### ISSUE TITLE
인스타그램 릴스 다운로드가 안됩니다. 

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#5051]
몇몇 영상이 빠져서 보니까 릴스 쪽에서 누락이 있었더라구요. 
혹시 릴스는 지원 안되나요?

**Comment by mita5549** [comment]
Invalid: [insta] https://www.instagram.com/reel/CPKpc2NAz9j

version: 3.7l (22-06-07 05:23:56 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / be4024e3e50e4173819bfc026b7ef0b2
input: https://www.instagram.com/reel/CPKpc2NAz9j
type: insta
single: False
url: https://www.instagram.com/reel/CPKpc2NAz9j
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1659191728.3772802 (22-07-30 14:35:28 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
no username
stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\insta_downloader", line 54, in read
 File "extractor\insta_downloader", line 234, in get_user_info
 File "ree", line 15, in find
ree.NotFound: no username

Invalid: fail=True
EOT: https://www.instagram.com/reel/CPKpc2NAz9j  (8.0s)

입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
감사합니다!
정상으로 작동 합니다!
