### ISSUE TITLE
3.7n 이후 이헨 만화 다운이 안됩니다

### ISSUE THREAD

**Issue by gulmen11** [KurtBestor/Hitomi-Downloader#5073]
이전까지 input을 'e-hentai.org'로 넣으면 자동으로 url이 'exhentai.org'로 바뀌는 일부 자료들의 다운이 문제없이 잘 되다가 3.7n (7월 28일 릴리즈) 업데이트이후 무한로딩이 걸리면서 주황색 창으로 바뀜과 동시에 자료 다운이 되지 않습니다.

여태까지 잘 써오다 갑자기 이런 문제가 발생하니 당황스럽네요.
(서버는 자동, 원본 이미지 다운로드 옵션 미사용)

[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)

version: 3.7n (22-07-28 02:04:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / c5ebcdad56624e7abb7d96f85e51c1d5
input: https://e-hentai.org/g/2263805/c0f21d34ee
type: ehen
single: False
url: https://exhentai.org/g/2263805/c0f21d34ee
dir: C:\Users\abbb\Pictures\hitomi.la\[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)
zip: 
artist: nora higuma
valid / done: False / True
range / range_p: None / None
time: 1659285679.167527 (22-07-31 16:41:19 UTC)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 2263805

제목: [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi | 친구 엄마의 알몸을 보게 된 소년의 이야기 [Korean]

작가: nora higuma

그룹: N/A

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: female:bukkake, female:milf, female:sole female, male:shotacon, male:sole male

언어: Korean

[File Names]
[0001] C:\Users\abbb\Pictures\hitomi.la\[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)\00.jpg
[0002] C:\Users\abbb\Pictures\hitomi.la\[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)\01.jpg
[0003] C:\Users\abbb\Pictures\hitomi.la\[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)\02.jpg
[0004] C:\Users\abbb\Pictures\hitomi.la\[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)\03.jpg
[0005] C:\Users\abbb\Pictures\hitomi.la\[Nora Higuma][N／A][Original] [Nora Higuma] Tomodachi no Okaa-san no Hadaka o Michatta Shounen no Ohanashi ｜ 친구 엄마의 알몸을 보게 된 소년의 이 (2263805)\04.jpg

[URLs]
[0001] LazyUrl_ehen(https://exhentai.org/s/3c6203d180/2263805-1)
[0002] LazyUrl_ehen(https://exhentai.org/s/ef80c11f4f/2263805-2)
[0003] LazyUrl_ehen(https://exhentai.org/s/7e2c5b3c86/2263805-3)
[0004] LazyUrl_ehen(https://exhentai.org/s/12765566c1/2263805-4)
[0005] LazyUrl_ehen(https://exhentai.org/s/95bc57f138/2263805-5)

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/2263805/c0f21d34ee)
#### https://e-hentai.org/g/2263805/c0f21d34ee    ---->    https://e-hentai.org/g/2263805/c0f21d34ee
Traceback (most recent call last):
 File "downloader", line 379, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 565, in read
 File "hitomi_downloader", line 448, in get_imgs
 File "extractor\ehen_downloader", line 181, in ehen_imgs
 File "downloader", line 430, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/2263805/c0f21d34ee

get_imgs server: ehen
ehen_imgs(ex:True, url:https://e-hentai.org/g/2263805/c0f21d34ee)
#### https://exhentai.org/g/2263805/c0f21d34ee    ---->    https://exhentai.org/g/2263805/c0f21d34ee
MPV: False
get_title_ehen: https://exhentai.org/g/2263805/c0f21d34ee
FINAL SERVER: ehen
ehen_url: https://exhentai.org/g/2263805/c0f21d34ee
imgs: 5
E-Hentai: https://exhentai.org/g/2263805/c0f21d34ee

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/3c6203d180/2263805-1
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

LazyUrl error (https://exhentai.org/s/3c6203d180/2263805-1):
Traceback (most recent call last):
 File "hitomi_downloader", line 235, in run
 File "utils", line 805, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\ehen_downloader", line 308, in get
Exception: 509.gif

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/ef80c11f4f/2263805-2
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

LazyUrl error (https://exhentai.org/s/ef80c11f4f/2263805-2):
Traceback (most recent call last):
 File "hitomi_downloader", line 235, in run
 File "utils", line 805, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\ehen_downloader", line 308, in get
Exception: 509.gif

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/7e2c5b3c86/2263805-3
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

LazyUrl error (https://exhentai.org/s/7e2c5b3c86/2263805-3):
Traceback (most recent call last):
 File "hitomi_downloader", line 235, in run
 File "utils", line 805, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\ehen_downloader", line 308, in get
Exception: 509.gif

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/12765566c1/2263805-4
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

LazyUrl error (https://exhentai.org/s/12765566c1/2263805-4):
Traceback (most recent call last):
 File "hitomi_downloader", line 235, in run
 File "utils", line 805, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\ehen_downloader", line 308, in get
Exception: 509.gif

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

ehen retry... https://exhentai.org/s/95bc57f138/2263805-5
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 343, in get_img
Exception: No image

LazyUrl error (https://exhentai.org/s/95bc57f138/2263805-5):
Traceback (most recent call last):
 File "hitomi_downloader", line 235, in run
 File "utils", line 805, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\ehen_downloader", line 308, in get
Exception: 509.gif

stop
valid=False 1
EOT: https://e-hentai.org/g/2263805/c0f21d34ee  (357.2s)

**Comment by gulmen11** [comment]
![44](https://user-images.githubusercontent.com/84175774/182783251-11883dbe-bcaa-442e-ab84-555dc4c6bc41.png)

태그를 보고 다시 둘러봐서 확인했는데 저렇게 나오네요.

**Comment by KurtBestor** [comment]
쿠키에 문제가 있는 것 같은데 초기화하고 다시 시도해보세요

**Comment by KurtBestor** [comment]
저 테스트 버전에서 문제가 있는 것 같은데 정식 버전이나 이 테스트 버전으로 해보세요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
