### ISSUE TITLE
pinterest not download

### ISSUE THREAD

**Issue by murazi** [KurtBestor/Hitomi-Downloader#5132]
```
Invalid: [pinter] https://www.pinterest.com/pin/229331806016523692/

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_cn
order / group / uid: 0 / False / e005ee39bced41eb87de3b904f316a5b
input: https://www.pinterest.com/pin/229331806016523692/
type: pinter
single: False
url: https://www.pinterest.com/pin/229331806016523692/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: 1 / None
time: 1660618027.5489116 (22-08-16 02:47:07 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.08.14
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
type: pin
type: pin
type: pin
type: pin
pin
stop
Traceback (most recent call last):
 File "utils", line 1182, in start
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pinter_downloader", line 34, in init
NotImplementedError: pin

Invalid: fail=True
EOT: https://www.pinterest.com/pin/229331806016523692/  (0.9s)
```

Download single page works only

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
