### ISSUE TITLE
nozomi 일부 url 인식 불가 문제

### ISSUE THREAD

**Issue by AXfYVzWUQ5Cd** [KurtBestor/Hitomi-Downloader#5146]
Invalid: [nozomi] https://nozomi.la/search.html?q=haze%2freverb

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 021411c4572b4cd3926cd269fe2c3dce
input: https://nozomi.la/search.html?q=haze%2freverb
type: nozomi
single: False
url: https://nozomi.la/search.html?q=haze%2freverb
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1660973400.3890579 (22-08-20 05:30:00 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
haze/reverb: 0
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1281, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=haze%2freverb  (2.5s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by DavidShaoziqi** [comment]
The bug is still there, dude. When quantity of the icons is less than 64 (the max of one page), the downloader reports an error like above dialog. Could you give us some advice or patches to fix that problem? 
By the way, your work is awesome, thank you!
