### ISSUE TITLE
픽시브 코믹이 다운로드가 안되네요

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#5158]
전체적으로 안되는거 같습니다

**Comment by qj8x67s33a44** [comment]
Invalid: [pixiv_comic] https://comic.pixiv.net/works/8284

version: 3.7n (22-08-13 12:57:05 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 1 / False / 4d0a4bf194754a579acb5d8bb704cf7a
input: https://comic.pixiv.net/works/8284
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8284
dir: 
zip: 
artist: 原作：花散ここ , 漫画：もりのもみじ
valid / done: False / True
range / range_p: None / None
time: 1661291155.2758594 (22-08-23 21:45:55 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\pixiv_comic_downloader", line 67, in read
 File "extractor\pixiv_comic_downloader", line 155, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\pixiv_comic_downloader", line 121, in get_pages
IndexError: list index out of range

Invalid: fail=True
EOT: https://comic.pixiv.net/works/8284  (3.4s)

**Comment by qj8x67s33a44** [comment]
Invalid: [pixiv_comic] https://comic.pixiv.net/works/8285

version: 3.7n (22-08-13 12:57:05 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / a1a0b34b9ca24716968a04de7d29987b
input: https://comic.pixiv.net/works/8285
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8285
dir: 
zip: 
artist: 原作：てんてんどんどん, 漫画：まぶた単
valid / done: False / True
range / range_p: None / None
time: 1661291173.3474002 (22-08-23 21:46:13 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
dirFormat: [artist] title
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\pixiv_comic_downloader", line 67, in read
 File "extractor\pixiv_comic_downloader", line 155, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\pixiv_comic_downloader", line 121, in get_pages
IndexError: list index out of range

Invalid: fail=True
EOT: https://comic.pixiv.net/works/8285  (9.0s)

**Comment by qj8x67s33a44** [comment]
[景山五月(漫画)、梨(原作)] コワい話は≠くだけで。

version: 3.7n (22-08-13 12:57:05 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: -4 / False / 5094700ead0649058a88cee8d530cd06
input: https://comic.pixiv.net/works/8623
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8623
dir: hitomi_downloaded_pixiv_comic\[景山五月(漫画)、梨(原作)] コワい話は≠くだけで。
zip: 
artist: 景山五月(漫画)、梨(原作)
valid / done: True / True
range / range_p: None / None
time: 1661291216.3797874 (22-08-23 21:46:56 UTC)
tags: []
lock: False
color: None
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
dirFormat: [artist] title
Skip: 更新日： 2022年8月23日 - 本日UP
stop

**Comment by qj8x67s33a44** [comment]
되는게 있고 안되는게 있네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by qj8x67s33a44** [comment]
잘 됩니다 감사합니다

**Comment by qj8x67s33a44** [comment]
Invalid: [pixiv_comic] https://comic.pixiv.net/works/785

version: 3.7n (22-08-24 05:18:15 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / e178c345e1624feda96b88a11679c2be
input: https://comic.pixiv.net/works/785
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/785
dir: 
zip: 
artist: 吉田覚
valid / done: False / True
range / range_p: None / None
time: 1661488463.47161 (22-08-26 04:34:23 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
dirFormat: [artist] title
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\pixiv_comic_downloader", line 67, in read
 File "extractor\pixiv_comic_downloader", line 155, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\pixiv_comic_downloader", line 116, in get_pages
IndexError: list index out of range

Invalid: fail=True
EOT: https://comic.pixiv.net/works/785  (11.2s)

이거만 다운로드가 안되네요

몇번씩 시도해봐도 안됩니다 확인 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
