### ISSUE TITLE
카카오 페이지는 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by smims210** [KurtBestor/Hitomi-Downloader#5176]
어제부터 갑자기 카카오 페이지 다운로드가 안 되네요
작품 화수 체크하고 페이지 개수까지는 정상적으로 읽히는데
마지막 단계인 다운로드만 시작하면 되는데 다운로드가 시작되지 않네요
![캡처](https://user-images.githubusercontent.com/73337900/187182812-fe6e21a0-a003-4100-b666-4466605d9040.JPG)

**Comment by username7655** [comment]
version: 3.7n (22-08-27 14:14:50 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / a38cb889972c496994e7636a61717877
input: https://page.kakao.com/home?seriesId=47736136
type: kakaopage
single: False
url: https://page.kakao.com/home?seriesId=47736136
dir: T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤
zip: 
artist: YASUHISA HARA
valid / done: False / True
range / range_p: None / [668]
time: 1661769888.607574 (22-08-29 10:44:48 UTC)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]
[0001] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0000.jpg
[0002] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0001.jpg
[0003] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0002.jpg
[0004] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0003.jpg
[0005] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0004.jpg
[0006] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0005.jpg
[0007] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0006.jpg
[0008] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0007.jpg
[0009] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0008.jpg
[0010] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0009.jpg
[0011] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0010.jpg
[0012] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0011.jpg
[0013] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0012.jpg
[0014] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0013.jpg
[0015] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0014.jpg
[0016] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0015.jpg
[0017] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0016.jpg
[0018] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0017.jpg
[0019] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0018.jpg
[0020] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0019.jpg
[0021] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0020.jpg
[0022] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0021.jpg
[0023] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0022.jpg
[0024] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0023.jpg
[0025] T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0024.jpg


[URLs]
[0001] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/ai9zIDeBVFxeOmtlv-az8nuptvZKAQgHwSQhV-ywkM57U3OEx7LvBuCI9AsNF0K_&filename=6401776_1629881846727.jpeg&signature=SqzVo6nInDxDcfa%2BYVATYTBNfXU%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0002] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/XY_hUNNG2aOgHEL_0-Xn3noL6RitbTll4WpcUB21peXZHPWyQJ_Qfdw7fV9mTJJA&filename=6401776_1629881847196.jpeg&signature=2e7RrWIOjwOWa7nxeiJC%2F4EUWMs%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0003] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/OOkIAXH26Ho8q9ynZTgHVroBB4tkxJZQZmIWrRSuJ8jFKUwmdRPPB1lKzCJaJeaY&filename=6401776_1629881847647.jpeg&signature=pxs7yN7g6hcm9VHjc97SEE74pLU%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0004] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/-Aa-3Qfy9vfiU62A17iux2K4ue6uMMeORHvi-k3NSOKpnuEP9e9LaAQqNZkTKwoH&filename=6401776_1629881848082.jpeg&signature=PBm3E%2FWoOVTJm0jhoEoIfVoL7%2Fk%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0005] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/-Apl4Yq95nkXY9olxDKZfEKXx1e4tuBrI86dz7YYplHgGwFxl0hu5uHOYjIE06dk&filename=6401776_1629881848419.jpeg&signature=jfL6msUiZR6cnkOO4zEw8HmWXT4%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0006] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/EbpcGD56NPEDgMDhirQYrdKIVPpjeOLgfNdqefNGw1aBQB21O-qTENoZ4DeGJ4L-&filename=6401776_1629881848834.jpeg&signature=0%2FcRPfhEansg7yGN92DJRoxWJiE%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0007] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/JCqZRnvEJiFglmvhdd0dS8R6p5hO70XXR6SCBqxZkd343xyCnVW3uQuB5s76ZMFc&filename=6401776_1629881849176.jpeg&signature=lpJyoVoVBU8N3umn8o3zyk%2Ba5UA%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0008] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/BgX9MYokMxvJ2xDtdPwCNmIcDMvhC3ZutL_ZKDUBWbbhUnLVktrAhp-TNEaLXv5Z&filename=6401776_1629881849588.jpeg&signature=tG%2F2LxZq8j%2Beu5dSJh1AvpG4WBU%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0009] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/UItgyG1dbF_2GB6cFntL1_Xt1hAq2KPrs0fcdjF-O8JY4tZnYA-jghq7wMJVyE5i&filename=6401776_1629881849880.jpeg&signature=5SuEzlLL4TL5Fmnd%2B2Q1X%2Fi9Vbo%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0010] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/yXkMpkqsbFdmvK26VuqdVbdcMtzLYWcYLY7Ur2jGSaiLUy27THQsLgQCMNRXUf1X&filename=6401776_1629881850181.jpeg&signature=gHMxQJlcrHOGCSoyTEBaQqp%2BTJA%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0011] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/XttISQvSAONQ_NZB3wiFq_ZGr78lc8J8M0WdWen0LMTSW5wCT38G5zKHAcJoOzt8&filename=6401776_1629881850604.jpeg&signature=u2%2Fw7Ot2nvqkEw1Et57185FVUiM%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0012] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/rBbYEoVx-QTUe4yNNPwT7g1Waqs1mSlPZA-J3-1EKJF8mT7Ejd75cpKu7RjVdRz_&filename=6401776_1629881851125.jpeg&signature=uZEPZAlJquLwJemToyz72XIvxsQ%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0013] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/PpPZiiF8y6lGIK2hiittLKcgODJR0koAj6ss7X_JV-vJZ7uivl8rmgiivbfXul6t&filename=6401776_1629881851550.jpeg&signature=X9plIS%2B1u4mNPNHt0NwAyNTVNkc%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0014] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/kbf29i4loXjjI5DevVJ5xdEPQw8XvbW26oWbu_33-O6r0KQGAKxtRsfdRA3Nz4EI&filename=6401776_1629881852054.jpeg&signature=x4akrMomfjrF26Ksi93JW95IIvY%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0015] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/AacQoj8xc0LDgR6uuyiqGh86vAYFsMRIeEmCrvKoMFW-7SKiwGVYF7I_K3VDGgfh&filename=6401776_1629881852466.jpeg&signature=IldFYigYWbXlTAWk9tVB5KT6ztw%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0016] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/Km_YTbAP-pVHyqNr7GRMZTyM4XiUk_A7Z0eC4Gld1AHZ1zUrb-c6uIURgPeP2dpc&filename=6401776_1629881852787.jpeg&signature=rbnJRxyaLE1DS3%2FPBKLKC2llxHI%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0017] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/tRkdXjmOhX38zW44dHkxEgXdFFNnrjrgqhULymdud9zzG4EsAuEEbaTTY11Gxt35&filename=6401776_1629881853113.jpeg&signature=3vrHv%2BRqRphoPB8Tnk6mPvj%2Bcgg%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0018] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/gA6LvNF8il7qmxzuOESbtWWz8lkDLUTVJkXJyKjjP4dyy60BahtUWQbJMpgBm-Zv&filename=6401776_1629881853518.jpeg&signature=B2zdOceihP90kySnooXlFS%2FugHo%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0019] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/ygNIYdUlO_AzDDWdBjsMsLEyI1MhCeVBCpu4jlP7sKMv0nhCjfXGtKXtsaQ_M0b_&filename=6401776_1629881853850.jpeg&signature=EPk9IRwMfGGz4%2BkcUAS1WOZuOB8%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0020] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/utrUG_4GbcFwIW374Nli5GnzG670QICyQNQ88geiI7rqUwLOwGuqmbYev81xK61G&filename=6401776_1629881854120.jpeg&signature=gssc82bEZljQS%2BPcOUx5Ic2IcIs%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0021] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/_uaS4re4La6H02H_0lIEJVsSh_CkfEweu2U_FKxr73fpaz_yhogghm7dUq0sMn2C&filename=6401776_1629881854503.jpeg&signature=wxAqTS1m7BNxv6bB5OlYZqE9joY%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0022] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/4x7PfIlBvKeARxZboOENOrLq492cUxUVw5nK_i8RbzarbALrRLAIKReiCA9HE5rq&filename=6401776_1629881854814.jpeg&signature=ZlkcrTSmnBvNRiu53JN%2B8dECxbg%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0023] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/FZFTyl7BNWQlwg1vM3sHpxQZSKKETZl8_JGcinCpPbd8-sUHK3vbJLvQ6LAfj73C&filename=6401776_1629881855011.jpeg&signature=vw8UTqQVKZhNVsBmwhVFVyFSqBQ%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0024] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/f0mJnnHEf6R95nTUA6r6l5mW6ZvaJZgZhiNmYjBrtwFijVGrJMg2T5pV6cywzt89&filename=6401776_1629881855199.jpeg&signature=HeZ4z561unJ7VSncENtkQjZBRBU%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX
[0025] LazyUrl(https://page.kakao.com/)    --->    https://page-edge-jz.kakao.com/sdownload/resource/--jsZEESpuk3cHRKl68wZPMuYcf_5Z1RWkrOS4y_XOo_CyhNzQPxUewkGR20aFIp&filename=6401776_1629881855453.jpeg&signature=8qTwaDU5wkdeKlMtad2xihijTCs%3D&expires=1661777120&credential=lUt9i42FY2I4ggejDuJPPXMt5QR0LkfX


[Messages]
tid: 54dc2a9d8bb04c099019ba143b71e25e
제668화 배신 25

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404


Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404


Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404


Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0003.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (1)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (1)
retry (1)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404


Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (1)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0003.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (2)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (2)
retry (2)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404


Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (2)

retry (21)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0024.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (22)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0024.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

retry (23)

Fail : \\?\T:\Down_hitomi\Kakaopage\[YASUHISA HARA] 킹덤\제668화 배신\0024.jpg
Traceback (most recent call last):
 File "downloader", line 1099, in download
Exception: 404

stop
valid=False 1
EOT: https://page.kakao.com/home?seriesId=47736136  (208.7s)

**Comment by Lylaspace** [comment]
저도 그런데ㅠㅠ 해결 방법이 있나요?

**Comment by jinjins7** [comment]
저도 똑같네요..ㄷㄷ
저는 카카오페이지에 웹툰..
https://page.kakao.com/home?seriesId=47497773
이거나 다른 웹툰 해도 위에분이랑 같네요.ㄷ

**Comment by hnodfg** [comment]
저도 그런데 뭔가 카카오페이지 측에서 이미지 코드를 바꿨나보네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hnodfg** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

테스트 해봤는데 아직도 안되는것 같아요

Browser required; Use --safemode
https://page.kakao.com/home?seriesId=59365151&orderby=desc

version: 3.7n (22-09-06 07:00:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 050b18f1a3024054bdcb6de8baaab203
input: https://page.kakao.com/home?seriesId=59365151&orderby=desc
type: kakaopage
single: False
url: https://page.kakao.com/home?seriesId=59365151&orderby=desc
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [1]
time: 1662453044.128722 (22-09-06 08:30:44 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\kakaopage_downloader", line 56, in read
 File "extractor\kakaopage_downloader", line 151, in get_info
 File "extractor\kakaopage_downloader", line 113, in read_html
 File "clf2", line 118, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://page.kakao.com/home?seriesId=59365151&orderby=desc  (1.1s)


stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\kakaopage_downloader", line 56, in read
 File "extractor\kakaopage_downloader", line 151, in get_info
 File "extractor\kakaopage_downloader", line 113, in read_html
 File "clf2", line 118, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://page.kakao.com/home?seriesId=59365151&orderby=desc  (1.1s)

**Comment by hnodfg** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

다운로드 잘 되는데요
한가지 특정 폴더에서는 --safemode로 실행이 안되던데 이럴 수도 있나요?

**Comment by Lylaspace** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘 되는 것 같습니다 감사합니다

**Comment by ssjj813** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

테스트 파일 다운 후 시도 해도 같은 증상이 반복됩니다.

**Comment by smims210** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
아주 잘 됩니다. 감사합니다 ㅠㅠ

**Comment by jinjins7** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

작동 잘 됩니다!

**Comment by y364** [comment]
Cannot query field "isWaitfreePlus" on type "Series". Did you mean "isWaitfree"?
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\kakaopage_downloader", line 61, in read
 File "extractor\kakaopage_downloader", line 619, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/content/47736136  (53.9s)

테스트버전 실행했을때 이런식으로 뜨면서 안되는데 해결책이 있을까요?
