### ISSUE TITLE
코믹 워커 다운로드 문의드립니다

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#5181]
이거 다운로드 가능할까요?

Invalid: [comicwalker] https://comic-walker.com/contents/detail/KDCW_TS01202877010000_68/

version: 3.7n (22-08-27 14:14:50 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 59 / False / 2ca8ece7c5ea46cda8b1feef22b3b9fa
input: https://comic-walker.com/contents/detail/KDCW_TS01202877010000_68/
type: comicwalker
single: False
url: https://comic-walker.com/contents/detail/KDCW_TS01202877010000_68/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1661899893.6077406 (22-08-30 22:51:33 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_title: "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91') "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91')
get_title: "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91') "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91')
'result'
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\comicwalker_downloader", line 65, in read
 File "extractor\comicwalker_downloader", line 156, in get_imgs
 File "extractor\comicwalker_downloader", line 85, in get_imgs_page
KeyError: 'result'

Invalid: fail=True
EOT: https://comic-walker.com/contents/detail/KDCW_TS01202877010000_68/  (1.5s)

get_title: "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91') "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91')
get_title: "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91') "夫の扶養からぬけだしたい【タテスク】"(b'\xe5\xa4\xab\xe3\x81\xae\xe6\x89\xb6\xe9\xa4\x8a\xe3\x81\x8b\xe3\x82\x89\xe3\x81\xac\xe3\x81\x91\xe3\x81\xa0\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x80\x90\xe3\x82\xbf\xe3\x83\x86\xe3\x82\xb9\xe3\x82\xaf\xe3\x80\x91')
'result'
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\comicwalker_downloader", line 65, in read
 File "extractor\comicwalker_downloader", line 156, in get_imgs
 File "extractor\comicwalker_downloader", line 85, in get_imgs_page
KeyError: 'result'

Invalid: fail=True
EOT: https://comic-walker.com/contents/detail/KDCW_TS01202877010000_68/  (1.5s)

**Comment by KurtBestor** [comment]
BOOK☆WALKER 로 넘겨주는 페이지고 해당 사이트는 현재 지원하지 않아요
