### ISSUE TITLE
rule34 다운로드 오류 관련

### ISSUE THREAD

**Issue by enpi1** [KurtBestor/Hitomi-Downloader#5191]
한 두어달전부터 히토미 다운로더를 통해 다운이 전혀 되지 않는데요

Invalid: [rule34_xxx] https://rule34.xxx/index.php?page=post&s=list&tags=ascendant_one

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / acbcb00baadd4664810e20bc09df3a08
input: https://rule34.xxx/index.php?page=post&s=list&tags=ascendant_one
type: rule34_xxx
single: False
url: https://rule34.xxx/index.php?page=post&s=list&tags=ascendant_one
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1662062713.4883945 (22-09-01 20:05:13 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags=ascendant_one&pid=0&limit=100
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 397, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "extractor\rule34_xxx_downloader", line 62, in read
 File "extractor\rule34_xxx_downloader", line 112, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "downloader", line 424, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 218, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://rule34.xxx/index.php?page=post&s=list&tags=ascendant_one  (92.9s)

이렇게 뜨는데 어떤 이유일까요

**Comment by enpi1** [comment]
해결하였습니다. 

1. 현재 실행되어 있는 우회 프로그램을 끄시고
2. 히토미 다운로더를 관리자 권한으로 실행시키신 후 dpi 우회? 그걸 키시면 됩니다 감사합니다
