### ISSUE TITLE
히토미 또 막힌거같습니다. 

### ISSUE THREAD

**Issue by mercythekiller** [KurtBestor/Hitomi-Downloader#5197]
invalid 뜨면서 안되네요.
일부 파일은 받아지기도 하는데 대부분 안됩니다.

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/2301821.html)
Find_ehen(id:2301821, ex:False)
Find in HK...
not found in HK
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/2301821.html)
Find_ehen(id:2301821, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
 File "hitomi_downloader", line 612, in read
 File "hitomi_downloader", line 447, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 614, in read
 File "hitomi_downloader", line 447, in get_imgs
 File "extractor\ehen_downloader", line 162, in ehen_imgs
Exception: URL not found

**Comment by mercythekiller** [comment]
아무래도 제 ip가 막힌듯 합니다. 하도 답답해서 vpn 구매하니 잘 되긴 하네요.

**Comment by mercythekiller** [comment]
vpn도 일부 파일이 안받아 지다가 10분후에 막혀버리네요. 물론 vpn 재접속으로 ip를 변경하면 받아지긴 하는데 잠시뿐이고요. 특히 제목이 일본어나 영어가 아닌 알파벳이 섞입니다. 노답이네요.  나름 장기 후원자로서 유세 떠는건 아닙니다만 제발 해결 부탁드립니다. ㅠㅠ

**Comment by KurtBestor** [comment]
`옵션 - 설정 - Hitomi.la / E(x)Hentai 설정 - 갤러리 정보` 를 원래대로 돌려놓아 주세요

**Comment by mercythekiller** [comment]
고맙습니다 선생님
선생님은 영웅입니다.
