### ISSUE TITLE
havent been able to download nhentai, just me? tried using vpns too and still no luck, both test and normal exe

### ISSUE THREAD

**Issue by unduesnow** [KurtBestor/Hitomi-Downloader#5202]
Restart in 4m 53s: https://nhentai.net/g/418601/

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10/ en_us
order / group / uid: 0 / False / 90c046628a8e4a7cbd5dc8e9a732897a
input: https://nhentai.net/g/418601/
type: nhentai
single: False
url: https://nhentai.net/g/418601/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1662404777.5434573 (22-09-05 19:06:17 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "extractor\nhentai_downloader", line 33, in read
 File "extractor\nhentai_downloader", line 129, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\nhentai_downloader", line 96, in get_info
IndexError: list index out of range

Invalid: fail=True
quality: 100%
EOT: https://nhentai.net/g/418601/  (10.2s)

**Comment by hades259** [comment]
nhentai downloader not working for a long time , sad but no fix from hitomi dude :(

**Comment by unduesnow** [comment]
aw man thats what i thought, its been a few weeks now, whenever i open the site it starts with checking connection and i think its cuz of that. really annoying honestly, i use it to find comic chapters but hitomi for download now i guess
