### ISSUE TITLE
거의 6개월동안 실행이 안됩니다 

### ISSUE THREAD

**Issue by asd1sfn54** [KurtBestor/Hitomi-Downloader#5206]
정말 다운받고 싶은게 있어서 많은 방법을 시도했으나 실패하고 여기다가 질문 올립니다 

1. 윈도우10 62비트 윈도우 디펜더 사용중입니다 .
2. 정상적으로 실행하면 무반응 이라 오른쪽 마우스 클릭후 관리자권한으로 실행으로만 실행됩니다.
3.  다운받고 싶은 작품이 등장했는데 다운할려고 하니  Browser required; Use --safemode 빨간 글씨 뜨고 안됨
4. 그래서 검색후  hitomi_downloader_GUI.exe --safemode 해봤으나 무반응 
5. 디펜더 끄고 해봤으나 무반응
6. 테스트 버전 찾아서 해봤으나 역시나  무반응
7. 다른 검색으로 찾아보니 이런내용이 있어서 시도해봄  Ctrl + Alt + C 눌러서 콘솔 열고 다음 입력하고 Enter 눌러서 나온 내용 보여주세요:

__import__('importlib').resources.path('certifi', 'cacert.pem').__enter__() 

나온 결과 : WindowsPath('C:/Users/유/AppData/Local/Temp/_MEI128002/certifi/cacert.pem')

--safemode --debug시도해서 

나온 결과 
<class 'str'> 42686
fix value (zh): 이미 추가한 작업 다시 시작할지 물어봄
fix value (zh): UI 스케일 ({}%)
fix value (zh): 재시작 후 적용됩니다
fix value (zh-tw): 이미 추가한 작업 다시 시작할지 물어봄
fix value (zh-tw): UI 스케일 ({}%)
fix value (zh-tw): 재시작 후 적용됩니다
fix value (fr): 이미 추가한 작업 다시 시작할지 물어봄
fix value (fr): UI 스케일 ({}%)
fix value (fr): 재시작 후 적용됩니다
fix value (ja): 이미 추가한 작업 다시 시작할지 물어봄
fix value (ja): UI 스케일 ({}%)
fix value (ja): 재시작 후 적용됩니다
fix value (pl): 이미 추가한 작업 다시 시작할지 물어봄
fix value (pl): UI 스케일 ({}%)
fix value (pl): 재시작 후 적용됩니다
fix value (pt): 이미 추가한 작업 다시 시작할지 물어봄
fix value (pt): UI 스케일 ({}%)
fix value (pt): 재시작 후 적용됩니다
fix value (es): 이미 추가한 작업 다시 시작할지 물어봄
fix value (es): UI 스케일 ({}%)
fix value (es): 재시작 후 적용됩니다
fix value (vi): 이미 추가한 작업 다시 시작할지 물어봄
fix value (vi): UI 스케일 ({}%)
fix value (vi): 재시작 후 적용됩니다
drv: PyQt
C:\Users\유\_MEI139762\bs4\element:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
['C:\\Users\\유\\_MEI139762\\WinDivert.dll', 'C:\\Users\\유\\_MEI139762\\WinDivert64.sys']
no goodbye_dpi
debug A
debug B
debug C
pyi: 4.10
debug D
@@@@ LazyUrl.Register @@@@ ehen <class 'extractor.ehen_downloader.LazyUrl_ehen'>
@@@@ LazyUrl.Register @@@@ hiyobi <class 'extractor.hiyobi_downloader.LazyUrl_hiyobi'>
@@@@ LazyUrl.Register @@@@ gelbooru <class 'extractor.gelbooru_downloader.LazyUrl_gelbooru'>
@@@@ LazyUrl.Register @@@@ sankaku <class 'extractor.sankaku_downloader.LazyUrl_sankaku'>
@@@@ LazyUrl.Register @@@@ twitter <class 'extractor.twitter_downloader.LazyUrl_twitter'>
@@@@ LazyUrl.Register @@@@ nhentai <class 'extractor.nhentai_downloader.LazyUrl_nhentai'>
@@@@ LazyUrl.Register @@@@ nhentai_com <class 'extractor.nhentai_com_downloader.LazyUrl_nhentai_com'>
PrefixPath: C:/Users/À¯/_MEI139762/PyQt/Qt
LibraryExecutablesPath: C:/Users/À¯/_MEI139762/PyQt/Qt/bin
BinariesPath: C:/Users/À¯/_MEI139762/PyQt/Qt/bin
constants: False

MyApplication.__init__ None
nativeEventFilter installed
PIL: 8.3.0
webp: True
webp_anim: True

ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
  QT WARNING: QIODevice::read (QFile, ":\artists_korean.json"): device not open
[j_artists] Expecting value: line 1 column 1 (char 0)
initate
font id: 0
font family: Open Sans    (len: 1)
font id: 1
font family: Han Santteut Dotum    (len: 1)
Font: Gulim -> Hitomi Font
Platform: Windows-10-10.0.19041-SP0
System: Windows
Temp: C:\Users\유\AppData\Local\Temp
Qt 5.14.1 / PyQt 5.14.1 / SIP 6.6.1
$ C:\Users\유\Documents\hitomi_downloader_GUI\hitomi_downloader_GUI.exe --safemode --debug
{'debug': True, 'disable-gpu': False, 'no-browser': False, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': True, 'experimental': False, 'auto-scale': False, 'scale': 1, 'round-menu': True}

C:\Users\유
C:\Users\유\Documents\hitomi_downloader_GUI
[strip path] %TEMP%

The environment does not allow connecting to the splash screen. Are the splash resources attached to the bootloader or did an error occur?
Traceback (most recent call last):
  File "PyInstaller\fake-modules\pyi_splash", line 98, in <module>
  File "os", line 681, in __getitem__
KeyError: '_PYIBoot_SPLASH'
AccentColor (0, 120, 215)
ARGS: ['C:\\Users\\유\\Documents\\hitomi_downloader_GUI\\hitomi_downloader_GUI.exe', '--single-process', '--disable-shared-workers']
DPI: 96.0
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
build ani sync default 41.666666666666664 60 False
Ani.__init__
show: _name=C:\Users\유\Documents\hitomi_downloader_GUI\hitomi_downloader_GUI
read db
legacy: False
not checked
lang= ko, app=<MyApplication.MyApplication object at 0x0000022388BC1E58>
t0: 7.52788782119751
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 211, 211, 211, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 159, 188, 212, 255'
  QT WARNING: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 106, 165, 213, 255'
install <MyWidgets.MyLabel object at 0x00000223969F6558>
winId: 722226
handle: <PyQt.QtGui.QWindow object at 0x0000022395E97C18>
  QT FATAL: Could not find QtWebEngineProcess.exe

**Comment by hnodfg** [comment]
hitomi_downloader_GUI.exe 바로가기 만든다음에 바로가기 속성에 들어가서 
대상(T): 뒤에 --safemode 입력하시고 바로가기 실행하시면 될거에요

**Comment by asd1sfn54** [comment]
> hitomi_downloader_GUI.exe 바로가기 만든다음에 바로가기 속성에 들어가서 대상(T): 뒤에 --safemode 입력하시고 바로가기 실행하시면 될거에요

바로가기 만들고 --safemode 입력하고 했는데 왼쪽 더블클릭 우측 마우스 관리자 실행시
둘다 사용자계정컨트롤 게시자를 알수없는 뜨고 예 눌러도 무반응 이네요 ㅠㅠ

**Comment by hnodfg** [comment]
> > hitomi_downloader_GUI.exe 바로가기 만든다음에 바로가기 속성에 들어가서 대상(T): 뒤에 --safemode 입력하시고 바로가기 실행하시면 될거에요
> 
> 바로가기 만들고 --safemode 입력하고 왼쪽 더블클릭 또는 우측 마우스 관리자 실행시 둘다 사용자계정컨트롤 게시자를 알수없는 ~~ 변경 뜨고 예 눌러도 무반응 이네요 ㅠㅠ

음... 그러면 히토미 다운로더 파일을 다른곳으로 옮겨서 해보실레요? 저도 처음엔 안되다가 폴더 옮기니까 되더라고요

**Comment by asd1sfn54** [comment]
> > > hitomi_downloader_GUI.exe 바로가기 만든다음에 바로가기 속성에 들어가서 대상(T): 뒤에 --safemode 입력하시고 바로가기 실행하시면 될거에요
> > 
> > 
> > 바로가기 만들고 --safemode 입력하고 왼쪽 더블클릭 또는 우측 마우스 관리자 실행시 둘다 사용자계정컨트롤 게시자를 알수없는 ~~ 변경 뜨고 예 눌러도 무반응 이네요 ㅠㅠ
> 
> 음... 그러면 히토미 다운로더 파일을 다른곳으로 옮겨서 해보실레요? 저도 처음엔 안되다가 폴더 옮기니까 되더라고요

c디스크 내에서 바탕화면 내문서 아무리 이동해도 안되더니 d디스크에서는 정상작동하네요 정말 감사합니다! 
이거 고친다고 몇개월동안 포기도 몇번하고 했는데 정말 감사합니다

**Comment by ahrigatohaha** [comment]
> > > > hitomi_downloader_GUI.exe 바로가기 만든다음에 바로가기 속성에 들어가서 대상(T): 뒤에 --safemode 입력하시고 바로가기 실행하시면 될거에요
> > > 
> > > 
> > > 바로가기 만들고 --safemode 입력하고 왼쪽 더블클릭 또는 우측 마우스 관리자 실행시 둘다 사용자계정컨트롤 게시자를 알수없는 ~~ 변경 뜨고 예 눌러도 무반응 이네요 ㅠㅠ
> > 
> > 
> > 음... 그러면 히토미 다운로더 파일을 다른곳으로 옮겨서 해보실레요? 저도 처음엔 안되다가 폴더 옮기니까 되더라고요
> 
> c디스크 내에서 바탕화면 내문서 아무리 이동해도 안되더니 d디스크에서는 정상작동하네요 정말 감사합니다! 이거 고친다고 몇개월동안 포기도 몇번하고 했는데 정말 감사합니다

와 대박.. 바로 되네요... 윈도우 깔린 메인 하드는 보안이 쎈건지 전혀 실행이 안돼쓴데 와 D드라이브에 넣으니까 바로 켜지네요. 이거 좀 쩌는 듯
