### ISSUE TITLE
마나토끼 다운이 안됩니다.

### ISSUE THREAD

**Issue by hohoe** [KurtBestor/Hitomi-Downloader#5217]
항상 감사하는 마음으로 사용하고 있는 유저입니다.

vpn관련 인가? 하여 본 ip로 접속해도 다운이 되지 않습니다.

마나토끼 다운이 되지않는 상황의  작업정보는 다음과 같습니다.

Invalid: [manatoki] https://manatoki152.net/comic/7161661

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 1a7f6ba416f44513910cedfe15bbb271
input: https://manatoki152.net/comic/7161661
type: manatoki
single: False
url: https://manatoki152.net/comic/7161661
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1662648629.7365975 (22-09-08 14:50:29 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1182, in start
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 592, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki152.net/comic/7161661  (30.9s)

**Comment by hohoe** [comment]
실행 파일 덮어씌워서 실행하니 다시 잘 작동 됩니다. 해당 이슈 닫겠습니다.
