### ISSUE TITLE
픽시브 정지된 계정 무한 읽는 중

### ISSUE THREAD

**Issue by sosoeun** [KurtBestor/Hitomi-Downloader#5223]
다시시작 하는 중에 정지된 계정이 섞여있었는데

무한 읽는 중 상태로 다음으로 넘어가지 않습니다. 

원래는 빨간색으로 표시되거나 노랑색 표시가 되며 넘어갔던걸로 기억합니다.

정지되거나 삭제된 계정은 패스 할수 있는 방법이 잇을까요

process_ids error (id: 83288844, d:0):
Traceback (most recent call last):
 File "extractor\pixiv_downloader", line 498, in run
 File "extractor\pixiv_downloader", line 289, in get_info
 File "extractor\pixiv_downloader", line 132, in illust
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 125, in call
extractor.pixiv_downloader.HTTPError: 404 Client Error

**Comment by fade-out-0770** [comment]
https://www.pixiv.net/users/22217975 이주소 맞으신가요?
 저는 붉게되면서 패스 되네요. 
새로 받아서 아무 설정 없이 한번 받아보시는건 어떠세요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by sosoeun** [comment]
제대로 작동합니다. 항상 감사합니다.
