### ISSUE TITLE
Problems downloading facebook.

### ISSUE THREAD

**Issue by duckmanDP** [KurtBestor/Hitomi-Downloader#5228]
Hello.
I'm downloading this user's photos from facebook, but I get this error.
What I can do?

-------------------------------------------------------------------------
Invalid: [facebook] https://facebook.com/rias.gremorys.313

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-8.1-6.3.9600-SP0 / es_es
order / group / uid: 0 / False / a1ec384246064b6bb5d004e8cb47d3a6
input: https://facebook.com/rias.gremorys.313
type: facebook
single: False
url: https://facebook.com/rias.gremorys.313
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1662931945.7943325 (22-09-11 21:32:25 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
dtsg: NAcOtejcD6yQA9iFJCyuCsKIVHqmEDtzh8QwoZ9LoG5tGZB4RHmnyOQ:47:1662915431
lsd: Zsb5AHzkP3pm0qWlghJtLY
items: 9, c: 9
not f
items: 105, c: 96
not f
items: 225, c: 120
not f
items: 329, c: 104
not f
items: 409, c: 80
not f
items: 489, c: 80
not f
items: 561, c: 72
not f
items: 633, c: 72
not f
items: 697, c: 64
not f
items: 737, c: 40
not f
items: 793, c: 56
not f
items: 865, c: 72
not f
items: 921, c: 56
not f
items: 969, c: 48
not f
items: 1017, c: 48
not f
items: 1065, c: 48
not f
items: 1105, c: 40
not f
items: 1145, c: 40
not f
items: 1185, c: 40
not f
items: 1233, c: 48
not f
items: 1273, c: 40
not f
items: 1313, c: 40
not f
items: 1353, c: 40
not f
items: 1393, c: 40
not f
items: 1433, c: 40
not f
items: 1473, c: 40
not f
items: 1513, c: 40
not f
items: 1553, c: 40
not f
items: 1585, c: 32
not f
items: 1617, c: 32
not f
items: 1648, c: 31
not f
items: 1680, c: 32
not f
items: 1712, c: 32
not f
items: 1736, c: 24
not f
items: 1768, c: 32
not f
items: 1792, c: 24
not f
items: 1824, c: 32
not f
items: 1864, c: 40
not f
items: 1896, c: 32
not f
items: 1928, c: 32
not f
items: 1960, c: 32
not f
items: 1992, c: 32
not f
items: 2016, c: 24
not f
items: 2016, c: 0
not f
items: 2040, c: 24
not f
items: 2064, c: 24
not f
items: 2096, c: 32
not f
items: 2128, c: 32
not f
items: 2152, c: 24
not f
items: 2168, c: 16
not f
items: 2192, c: 24
not f
items: 2216, c: 24
not f
items: 2256, c: 40
not f
items: 2280, c: 24
not f
items: 2320, c: 40
not f
items: 2344, c: 24
not f
items: 2376, c: 32
not f
items: 2408, c: 32
not f
items: 2440, c: 32
not f
items: 2472, c: 32
not f
items: 2496, c: 24
not f
items: 2528, c: 32
not f
items: 2560, c: 32
not f
items: 2592, c: 32
not f
items: 2616, c: 24
not f
items: 2640, c: 24
not f
items: 2656, c: 16
not f
items: 2680, c: 24
not f
items: 2704, c: 24
not f
items: 2728, c: 24
not f
items: 2744, c: 16
not f
items: 2760, c: 16
not f
items: 2784, c: 24
not f
items: 2808, c: 24
not f
items: 2840, c: 32
not f
items: 2856, c: 16
not f
items: 2864, c: 8
not f
items: 2880, c: 16
not f
items: 2888, c: 8
not f
items: 2896, c: 8
not f
items: 2904, c: 8
not f
items: 2912, c: 8
not f
items: 2920, c: 8
not f
items: 2952, c: 32
not f
items: 2976, c: 24
not f
items: 3008, c: 32
not f
items: 3032, c: 24
not f
items: 3048, c: 16
not f
items: 3048, c: 0
not f
items: 3056, c: 8
not f
items: 3080, c: 24
not f
items: 3112, c: 32
not f
items: 3136, c: 24
not f
items: 3168, c: 32
not f
items: 3184, c: 16
not f
items: 3192, c: 8
not f
items: 3216, c: 24
not f
items: 3224, c: 8
not f
items: 3248, c: 24
not f
items: 3248, c: 0
not f
items: 3272, c: 24
not f
items: 3304, c: 32
not f
items: 3328, c: 24
not f
items: 3352, c: 24
not f
items: 3376, c: 24
not f
items: 3400, c: 24
not f
items: 3424, c: 24
not f
items: 3456, c: 32
not f
items: 3480, c: 24
not f
items: 3512, c: 32
not f
items: 3536, c: 24
not f
items: 3560, c: 24
not f
items: 3592, c: 32
not f
items: 3608, c: 16
not f
items: 3632, c: 24
not f
items: 3656, c: 24
not f
items: 3680, c: 24
not f
items: 3704, c: 24
not f
items: 3728, c: 24
not f
items: 3752, c: 24
not f
items: 3776, c: 24
not f
items: 3800, c: 24
not f
items: 3816, c: 16
not f
items: 3824, c: 8
not f
items: 3848, c: 24
not f
items: 3872, c: 24
not f
items: 3896, c: 24
not f
items: 3904, c: 8
not f
items: 3912, c: 8
not f
items: 3936, c: 24
not f
items: 3960, c: 24
not f
items: 3984, c: 24
not f
items: 4008, c: 24
not f
items: 4032, c: 24
not f
items: 4056, c: 24
not f
items: 4080, c: 24
not f
items: 4104, c: 24
not f
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "extractor\facebook_downloader", line 75, in read
 File "extractor\facebook_downloader", line 248, in get_imgs
 File "clf2", line 143, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://facebook.com/rias.gremorys.313  (1804.7s)
-----------------------------------------------------------------

**Comment by duckmanDP** [comment]
UPDATE:
I managed to download 4500 images by adjusting the "Maximum page limit" but after that amount it shows me an error.
How can I reduce the number of requests so that I don't get banned from Facebook?
![imagen](https://user-images.githubusercontent.com/17814879/190885096-14b0bd26-56cf-450a-b34f-e33094476456.png)
