### ISSUE TITLE
며칠전부터 폰헙 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by houseofkard** [KurtBestor/Hitomi-Downloader#5229]
작업내용은 다음과 같습니다 

5분 28초 뒤 다시 시작: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 37 / False / a418679f367e4a0e909dd2dfeca52132
input: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1662960010.520999 (22-09-12 05:20:10 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (90.6s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.2s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.2s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.0s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.7s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.6s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.8s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.9s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (91.9s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.1s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.1s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.9s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (90.2s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.4s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  (89.2s)

id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
id: ph624587c69b283
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 401, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph624587c69b283  [(89.4s)[](url)](url)

![20220912_142910](https://user-images.githubusercontent.com/113329673/189580108-12e8278f-1539-47a1-8b76-7f18ba994346.jpg)

스샷도 함께 첨부합니다 저 파일들 전부 저런 상태이고 ㅠ 다 지우고 다시 다운로드 눌러봐도 동일합니다

**Comment by houseofkard** [comment]
콘솔 열고 명령어 쓰니까 아래와 같이 나왔습니다! 


with open('test.txt', 'wb') as f: f.write(downloader.read_html('https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7').encode('utf8')) 

    Traceback (most recent call last):
      File "console\Console", line 185, in execSingle
      File "<string>", line 1
        with open('test.txt', 'wb') as f: f.write(downloader.read_html('https://www.pornhub.com/view_video.php?viewkey=ph627b34c1830f7').encode('utf8'))
           ^
    SyntaxError: invalid syntax
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib\request", line 1350, in do_open
      File "http\client", line 1277, in request
      File "http\client", line 1323, in _send_request
      File "http\client", line 1272, in endheaders
      File "http\client", line 1032, in _send_output
      File "http\client", line 972, in send
      File "http\client", line 1439, in connect
      File "http\client", line 944, in connect
      File "socket", line 728, in create_connection
      File "socket", line 716, in create_connection
    TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "downloader", line 397, in read_html
      File "urllib\request", line 525, in open
      File "urllib\request", line 543, in _open
      File "urllib\request", line 503, in _call_chain
      File "urllib\request", line 1393, in https_open
      File "urllib\request", line 1352, in do_open
    urllib.error.URLError: <urlopen error [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib3\connection", line 160, in _new_conn
      File "urllib3\util\connection", line 84, in create_connection
      File "urllib3\util\connection", line 74, in create_connection
    TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib3\connectionpool", line 677, in urlopen
      File "urllib3\connectionpool", line 381, in _make_request
      File "urllib3\connectionpool", line 978, in _validate_conn
      File "urllib3\connection", line 309, in connect
      File "urllib3\connection", line 172, in _new_conn
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D5EE0C4A88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "requests\adapters", line 449, in send
      File "urllib3\connectionpool", line 727, in urlopen
      File "urllib3\util\retry", line 446, in increment
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph627b34c1830f7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D5EE0C4A88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "console\Console", line 189, in execSingle
      File "<string>", line 1, in <module>
      File "downloader", line 424, in read_html
      File "requests\sessions", line 555, in get
      File "downloader", line 218, in session_request
      File "requests\sessions", line 542, in request
      File "requests\sessions", line 655, in send
      File "requests\adapters", line 516, in send
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph627b34c1830f7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D5EE0C4A88>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))
    Error try_n: pornhub_downloader get 2 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader read 1 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 401, in read
  File "utils", line 797, in __call__
  File "decorator", line 232, in fun
  File "constants", line 968, in wrapper
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader get 2 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader read 1 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 401, in read
  File "utils", line 797, in __call__
  File "decorator", line 232, in fun
  File "constants", line 968, in wrapper
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader get 2 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader read 1 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 401, in read
  File "utils", line 797, in __call__
  File "decorator", line 232, in fun
  File "constants", line 968, in wrapper
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader get 1 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader get 1 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Error try_n: pornhub_downloader get 1 Traceback (most recent call last):
  File "constants", line 939, in wrapper
  File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'
