### ISSUE TITLE
nhentai 안됩니다.

### ISSUE THREAD

**Issue by jjung3831** [KurtBestor/Hitomi-Downloader#5231]
nvalid: [nhentai] https://nhentai.net/g/410731/

version: 3.7n (22-09-11 01:35:59 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 7e09eeae9df74bd0b937495c344281b3
input: https://nhentai.net/g/410731/
type: nhentai
single: False
url: https://nhentai.net/g/410731/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1663127730.337405 (22-09-14 03:55:30 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
Extra data: line 1 column 233 (char 232)
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\nhentai_downloader", line 33, in read
 File "extractor\nhentai_downloader", line 129, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\nhentai_downloader", line 97, in get_info
 File "json\__init__", line 348, in loads
 File "json\decoder", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 233 (char 232)

Invalid: fail=True
EOT: https://nhentai.net/g/410731/  (11.3s)

no html
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
Extra data: line 1 column 233 (char 232)
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\nhentai_downloader", line 33, in read
 File "extractor\nhentai_downloader", line 129, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\nhentai_downloader", line 97, in get_info
 File "json\__init__", line 348, in loads
 File "json\decoder", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 233 (char 232)

Invalid: fail=True
EOT: https://nhentai.net/g/410731/  (16.7s)

3.7n으로 잘되다가 몇주전부터 안되요.ㅠㅠ
dpi 우회도 켰어요.

**Comment by fade-out-0770** [comment]
v3.7n 으로 다운 잘되네요. 제가 jjung님이랑 어떤부분이 다른진 잘모르겠네요.

아래링크는 스크린샷입니다.
https://ibb.co/gPQ08jZ

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
여기서 새로 받아서 해보시죠.

**Comment by jjung3831** [comment]
감사합니다.
기존에 있던곳에 덮어쓰기로 해봤는데 안됬고
폴더 새로만들어서 거기다가 넣고 해보니깐 되네요.
원인은 몰르겠지만 새폴더에 넣고 하니깐 잘됩니다.
감사합니다.^^
