### ISSUE TITLE
welovemanga 사이트에서 다운이 안되네요

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#5238]
항상 감사히 잘 사용하고 있습니다
잘 되던 곳이었는데 어제부터 전혀 안되고 있습니다
화수 선택까지는 되는데 그 뒤로 다운이 진행이 안되네요
정보 올립니다

DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW

version: 3.7n (22-08-24 05:18:15 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 2 / False / 05c97421f0aa4fedb7df23e65b0e3583
input: https://welovemanga.one/757/
type: lhscan
single: False
url: https://welovemanga.one/757/
dir: hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW
zip: 
artist: None
valid / done: False / True
range / range_p: None / [32]
time: 1663250126.828277 (22-09-15 13:55:26 UTC)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
[0002] hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
[0003] hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg

[URLs]
[0001] LazyUrl(https://welovemanga.one/757/92554/)    --->    https://s4.ihlv1.xyz/images2/20220914/1_6321524e030e5.jpg
&site=mm2r.net
[0002] LazyUrl(https://welovemanga.one/757/92554/)    --->    https://s4.ihlv1.xyz/images2/20220914/2_632152509643a.jpg
&site=mm2r.net
[0003] LazyUrl(https://welovemanga.one/757/92554/)    --->    https://s4.ihlv1.xyz/images2/20220914/3_632152536fd41.jpg&site=mm2r.net

[Messages]
no html
no html
https://welovemanga.one/757/ -> https://welovemanga.one/757/
Chapter 27.5
https://s4.ihlv1.xyz/images2/20220914/1_6321524e030e5.jpg
&site=mm2r.net

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (1)
retry (1)
retry (1)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (2)
retry (2)
retry (2)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (3)
retry (3)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (3)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (4)
retry (4)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (4)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (5)
retry (5)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (5)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (6)
retry (6)
retry (6)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (7)
retry (7)
retry (7)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (8)
retry (8)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (8)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (9)
retry (9)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (9)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (10)
retry (10)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (10)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (11)
retry (11)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (11)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (12)
retry (12)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (12)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (13)
retry (13)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (13)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (14)
retry (14)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (14)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (15)
retry (15)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (15)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (16)
retry (16)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (16)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (17)
retry (17)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (17)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (18)
retry (18)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (18)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (19)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (19)
retry (19)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (20)
retry (20)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (20)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (21)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (21)
retry (21)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (22)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (22)
retry (22)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (23)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0000.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

retry (23)
retry (23)

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0002.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

Fail : \\?\D:\hitomi_downloader_GUI  220325\hitomi_downloaded_lhscan\DEKOBOKO MAJO NO OYAKO JIJOU (MANGA) - RAW\Chapter 27.5\0001.jpg
Traceback (most recent call last):
 File "downloader", line 1209, in download
OSError: Size = 0

stop
valid=False 1
EOT: https://welovemanga.one/757/  (43.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
오오 잘됩니다 정말 감사드립니다
