### ISSUE TITLE
마나토끼 일부 만화가 다운이 안되네요

### ISSUE THREAD

**Issue by byeoriabba** [KurtBestor/Hitomi-Downloader#5245]
작업정보는 이렇게 나옵니다 

[후지 아즈키] 성녀의 마력은 만능입니다

version: 3.7i (22-09-15 17:37:44 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 883 / False / 3b1af1a64bbb4cbab8519bd1ae361f79
input: https://manatoki125.net/comic/150792
type: manatoki
single: False
url: https://manatoki152.net/comic/150792
dir: hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다
zip: 
artist: 후지 아즈키
valid / done: False / True
range / range_p: None / [1]
time: 1662564502.2349687 (22-09-07 15:28:22 UTC) - 813241s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0000.jpg
[0002] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0001.jpg
[0003] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0002.jpg
[0004] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0003.jpg
[0005] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0004.jpg
[0006] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0005.jpg
[0007] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0006.jpg
[0008] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0007.jpg
[0009] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0008.jpg
[0010] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0009.jpg
[0011] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0010.jpg
[0012] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0011.jpg
[0013] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0012.jpg
[0014] hitomi_downloaded_manatoki\[후지 아즈키] 성녀의 마력은 만능입니다\성녀의 마력은 만능입니다 1-1화\0013.jpg

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1182, in start
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 592, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki125.net/comic/150792  (556.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1182, in start
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 592, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki125.net/comic/150792  (69.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 81, in init
 File "utils", line 598, in __get__
 File "extractor\manatoki_downloader", line 97, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki125.net/comic/150792  (28.0s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 81, in init
 File "utils", line 598, in __get__
 File "extractor\manatoki_downloader", line 97, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki125.net/comic/150792  (40.5s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 81, in init
 File "utils", line 598, in __get__
 File "extractor\manatoki_downloader", line 97, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki125.net/comic/150792  (40.0s)

**Comment by kial0218** [comment]
저도 동일한 증상이네요
