### ISSUE TITLE
업데이트 후 유튜브 다운이 안되는데..

### ISSUE THREAD

**Issue by hoindinwgj** [KurtBestor/Hitomi-Downloader#5260]
업데이트 전까지 잘 되다가 업데이트 후 

version: 3.7o (22-09-19 06:37:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 659fa63322894a9eb8ff0d08297344c1
input: https://www.youtube.com/shorts/P4nVbDmHzvg
type: youtube
single: True
url: https://www.youtube.com/shorts/P4nVbDmHzvg
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1663617379.0463622 (22-09-19 19:56:19 UTC) - 346s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://www.youtube.com/shorts/P4nVbDmHzvg
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\youtube_downloader", line 386, in read
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\youtube_downloader", line 451, in get_videos
NotImplementedError: https://www.youtube.com/shorts/P4nVbDmHzvg

Invalid: fail=True
EOT: https://www.youtube.com/shorts/P4nVbDmHzvg  (1.2s)

라고 뜨며 안됩니다. 혹시 조언을 받을 수 있을까요?

**Comment by hoindinwgj** [comment]
빠른 업데이트 감사합니다. 업데이트 후 잘 작동되네요.
