### ISSUE TITLE
카카오페이지 다운로드가 막혔습니다

### ISSUE THREAD

**Issue by Hot-IcedTea** [KurtBestor/Hitomi-Downloader#5268]
이번에 웹 홈페이지를 수정한다더니 주소가 바뀐것 같습니다

확인 해주시면 감사하겠습니다 ^^

**Comment by username7655** [comment]
그리구 예전에는 속도가 어느정도 나왔는데 카카페 직전 막혀서 패치했을때 5장씩 끊어서 받아지더라고요. 웹툰같은거 1천장 넘어가면 속도가 한세월이던데 이건 사이트 특성상 어쩔수없나요?

**Comment by Hot-IcedTea** [comment]
> 그리구 예전에는 속도가 어느정도 나왔는데 카카페 직전 막혀서 패치했을때 5장씩 끊어서 받아지더라고요. 웹툰같은거 1천장 넘어가면 속도가 한세월이던데 이건 사이트 특성상 어쩔수없나요?

사이트 들어가보면 아시겠지만 개발자도구에서 사진 저장방식이 귀찮게 바뀌어서 읽는데 더 시간이 걸리는것 같더라구요
이번에 바뀐 방식은 더 복잡해서 도저히 손크로로는 답이 안나오는 상황이라...
개발자님 피드백 해주시는거 오매불망 기다리고만 있습니다 ㅎㅎ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by smims210** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

작동 잘 됩니다. 이제서야 드디어 ㅠㅠ

**Comment by y364** [comment]
테스트 버전 실행해 봤는데
Cannot query field "isWaitfreePlus" on type "Series". Did you mean "isWaitfree"?
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\kakaopage_downloader", line 61, in read
 File "extractor\kakaopage_downloader", line 619, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/content/47736136  (53.9s)
이렇게 뜨는데 어떻게 해야될까요?? ㅠㅠ
