### ISSUE TITLE
db가 깨졌을 때는 어떻게 대처하면 됩니까? 

### ISSUE THREAD

**Issue by Laser-Cho** [KurtBestor/Hitomi-Downloader#5291]
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 4081, in append_datas_
Exception: No data

Traceback (most recent call last):
File "hitomi_downloader_GUI", line 4081, in append_datas_
Exception: No data

Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1645, in foo
File "decorator", line 232, in fun
File "MyConfigParser", line 20, in w
File "MyConfigParser", line 107, in get
sqlite3.DatabaseError: database disk image is malformed

Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1645, in foo
File "decorator", line 232, in fun
File "MyConfigParser", line 20, in w
File "MyConfigParser", line 107, in get
sqlite3.DatabaseError: database disk image is malformed

라는 에러가 나오고, 다운로드는 되지만 추가적인 저장 등이 되지는 않습니다.

DB가 깨진 것 같은데, 대처방법 좀 알려주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/5249#issuecomment-1320841043
