### ISSUE TITLE
마나토끼 최신화 다운로드 불가현상 (단순 중복글 아닙니다)

### ISSUE THREAD

**Issue by SIJEFO** [KurtBestor/Hitomi-Downloader#5292]
어느 시점부터 마나토끼의 만화들이 다운로드되지 않습니다.
전체가 다운로드 되지 않는건 아니고 새로 추가되는 링크는 정상적으로 다운로드가 진행되며, 다운로드 되지 않는건 기존에 추가해놨던 만화들을 다시시작을 눌렀을 때 최신화가 다운로드 되지 않고, "다시 시작 실패; 복구됨" 이 뜨는겁니다.

기존 이슈의 댓글에서 최신화는 쿠키를 적용하고 캡챠 인증을 해야 한다고 하던데, 저같은 경우엔 만화가 다운로드 되지 않기 시작한 그 시점부터 캡챠인증이 뜨질 않더라구요. (쿠키적용은 물론 했습니다.)
그리고 최신화이긴 하지만, 그 최신화가 몇개월 전에 나온. 최신화이지만 사이트 내에선 최신화로 분류되지 않는 에피소드 또한 다운로드 되지 않습니다.

만, 다운로드 되지 않는 만화의 마나토끼 주소를 현재 주소인 156으로 변경할 경우엔 정상적으로 다운로드 되긴 합니다.
대신 이렇게 링크를 갱신하여 다운로드 할 경우엔 이미 다운로드한 에피소드를 건너뛰지 않고, 모든 에피소드의 모든 이미지를 일일이 체크하여 다운로드에 상당히 오랜 시간이 소요됩니다.
또한, 대부분의 만화는 이러한 방법으로 다운로드가 가능해지긴 하지만, 일부 만화는 이러한 방법으로도 해결이 되지 않습니다.
게다가 이 방법도 사이트 주소의 넘버링이 2~3정도 올라가면 다운로드 불가 현상이 다시 나타나게 됩니다.

강변 도시의 셀린느

version: 3.7m (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 3 / False / cdc62bd6948a481abaf9e60d325fd502
input: https://manatoki146.net/comic/11142750
type: manatoki
single: False
url: https://manatoki153.net/comic/11142750
dir: E:\Re_Manga\강변 도시의 셀린느
zip: 
artist: 히노시타 아카메
valid / done: False / True
range / range_p: None / None
time: 1663323479.3975377 (22-09-16 10:17:59 UTC) - 1204001s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0000.jpg
[0002] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0001.jpg
[0003] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0002.jpg
[0004] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0003.jpg
[0005] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0004.jpg
[0006] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0005.jpg
[0007] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0006.jpg
[0008] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0007.jpg
[0009] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0008.jpg
[0010] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0009.jpg
[0011] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0010.jpg
[0012] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0011.jpg
[0013] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0012.jpg
[0014] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0013.jpg
[0015] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0014.jpg
[0016] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0015.jpg
[0017] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0016.jpg
[0018] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0017.jpg
[0019] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0018.jpg
[0020] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0019.jpg
[0021] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0020.jpg
[0022] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0021.jpg
[0023] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0022.jpg
[0024] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0023.jpg
[0025] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0024.jpg
[0026] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0025.jpg
[0027] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0026.jpg
[0028] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0027.jpg
[0029] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0028.jpg
[0030] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0029.jpg
[0031] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0030.jpg
[0032] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0031.jpg
[0033] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0032.jpg
[0034] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0033.jpg
[0035] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0034.jpg
[0036] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0035.jpg
[0037] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0036.jpg
[0038] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0037.jpg
[0039] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0038.jpg
[0040] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0039.jpg
[0041] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0040.jpg
[0042] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0041.jpg
[0043] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0042.jpg
[0044] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0043.jpg
[0045] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0044.jpg
[0046] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0045.jpg
[0047] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0046.jpg
[0048] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0047.jpg
[0049] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0048.jpg
[0050] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0049.jpg
[0051] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0050.jpg
[0052] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0051.jpg
[0053] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0052.jpg
[0054] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0053.jpg
[0055] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0054.jpg
[0056] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 1화\0055.jpg
[0057] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0000.jpg
[0058] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0001.jpg
[0059] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0002.jpg
[0060] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0003.jpg
[0061] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0004.jpg
[0062] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0005.jpg
[0063] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0006.jpg
[0064] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0007.jpg
[0065] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0008.jpg
[0066] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0009.jpg
[0067] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0010.jpg
[0068] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0011.jpg
[0069] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0012.jpg
[0070] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0013.jpg
[0071] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0014.jpg
[0072] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0015.jpg
[0073] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0016.jpg
[0074] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0017.jpg
[0075] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0018.jpg
[0076] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0019.jpg
[0077] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0020.jpg
[0078] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0021.jpg
[0079] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0022.jpg
[0080] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0023.jpg
[0081] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0024.jpg
[0082] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0025.jpg
[0083] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0026.jpg
[0084] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0027.jpg
[0085] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0028.jpg
[0086] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0029.jpg
[0087] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0030.jpg
[0088] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0031.jpg
[0089] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0032.jpg
[0090] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 2화\0033.jpg
[0091] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0000.jpg
[0092] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0001.jpg
[0093] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0002.jpg
[0094] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0003.jpg
[0095] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0004.jpg
[0096] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0005.jpg
[0097] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0006.jpg
[0098] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0007.jpg
[0099] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0008.jpg
[0100] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0009.jpg
[0101] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0010.jpg
[0102] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0011.jpg
[0103] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0012.jpg
[0104] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0013.jpg
[0105] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0014.jpg
[0106] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0015.jpg
[0107] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0016.jpg
[0108] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0017.jpg
[0109] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0018.jpg
[0110] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0019.jpg
[0111] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0020.jpg
[0112] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0021.jpg
[0113] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0022.jpg
[0114] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0023.jpg
[0115] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0024.jpg
[0116] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0025.jpg
[0117] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0026.jpg
[0118] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0027.jpg
[0119] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0028.jpg
[0120] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0029.jpg
[0121] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0030.jpg
[0122] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0031.jpg
[0123] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 3화\0032.jpg
[0124] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0000.jpg
[0125] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0001.jpg
[0126] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0002.jpg
[0127] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0003.jpg
[0128] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0004.jpg
[0129] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0005.jpg
[0130] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0006.jpg
[0131] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0007.jpg
[0132] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0008.jpg
[0133] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0009.jpg
[0134] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0010.jpg
[0135] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0011.jpg
[0136] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0012.jpg
[0137] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0013.jpg
[0138] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0014.jpg
[0139] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0015.jpg
[0140] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0016.jpg
[0141] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0017.jpg
[0142] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0018.jpg
[0143] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0019.jpg
[0144] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0020.jpg
[0145] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0021.jpg
[0146] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 4화\0022.jpg
[0147] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0000.jpeg
[0148] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0001.jpeg
[0149] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0002.jpeg
[0150] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0003.jpeg
[0151] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0004.jpeg
[0152] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0005.jpeg
[0153] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0006.jpeg
[0154] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0007.jpeg
[0155] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0008.jpeg
[0156] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0009.jpeg
[0157] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0010.jpeg
[0158] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0011.jpeg
[0159] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0012.jpeg
[0160] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0013.jpeg
[0161] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0014.jpeg
[0162] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0015.jpeg
[0163] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0016.jpeg
[0164] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0017.jpeg
[0165] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0018.jpeg
[0166] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0019.jpeg
[0167] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0020.jpeg
[0168] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0021.jpeg
[0169] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0022.jpeg
[0170] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0023.jpeg
[0171] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 5화\0024.jpeg
[0172] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0000.jpeg
[0173] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0001.jpeg
[0174] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0002.jpeg
[0175] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0003.jpeg
[0176] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0004.jpeg
[0177] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0005.jpeg
[0178] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0006.jpeg
[0179] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0007.jpeg
[0180] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0008.jpeg
[0181] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0009.jpeg
[0182] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0010.jpeg
[0183] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0011.jpeg
[0184] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0012.jpeg
[0185] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0013.jpeg
[0186] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0014.jpeg
[0187] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0015.jpeg
[0188] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0016.jpeg
[0189] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0017.jpeg
[0190] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0018.jpeg
[0191] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0019.jpeg
[0192] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0020.jpeg
[0193] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0021.jpeg
[0194] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0022.jpeg
[0195] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0023.jpeg
[0196] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0024.jpeg
[0197] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0025.jpeg
[0198] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0026.jpeg
[0199] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0027.jpeg
[0200] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0028.jpeg
[0201] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0029.jpeg
[0202] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0030.jpeg
[0203] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0031.jpeg
[0204] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0032.jpeg
[0205] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0033.jpeg
[0206] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0034.jpeg
[0207] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0035.jpeg
[0208] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 6화\0036.jpeg
[0209] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0000.jpeg
[0210] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0001.jpeg
[0211] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0002.jpeg
[0212] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0003.jpeg
[0213] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0004.jpeg
[0214] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0005.jpeg
[0215] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0006.jpeg
[0216] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0007.jpeg
[0217] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0008.jpeg
[0218] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0009.jpeg
[0219] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0010.jpeg
[0220] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0011.jpeg
[0221] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0012.jpeg
[0222] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0013.jpeg
[0223] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0014.jpeg
[0224] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0015.jpeg
[0225] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0016.jpeg
[0226] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0017.jpeg
[0227] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0018.jpeg
[0228] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0019.jpeg
[0229] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0020.jpeg
[0230] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0021.jpeg
[0231] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0022.jpeg
[0232] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0023.jpeg
[0233] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0024.jpeg
[0234] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0025.jpeg
[0235] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0026.jpeg
[0236] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0027.jpeg
[0237] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0028.jpeg
[0238] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0029.jpeg
[0239] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0030.jpeg
[0240] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0031.jpeg
[0241] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0032.jpeg
[0242] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0033.jpeg
[0243] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0034.jpeg
[0244] E:\Re_Manga\강변 도시의 셀린느\강변 도시의 셀린느 7화\0035.jpeg

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 81, in init
 File "utils", line 598, in __get__
 File "extractor\manatoki_downloader", line 97, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
invalid; revert
EOT: https://manatoki146.net/comic/11142750  (19.8s)

**Comment by ghkdqofjr1122** [comment]
한 작품의 모든 에피소드의 모든 이미지를 받는게 오래걸리는 작업이 아니에요. 뭔가 기능을 제대로 못 쓰시는듯

**Comment by ghkdqofjr1122** [comment]
"선택 화 다운로드" 기능을 써보세요
