### ISSUE TITLE
manatoki 다운로드에서 오류가 발생합니다

### ISSUE THREAD

**Issue by marlin-meyolk** [KurtBestor/Hitomi-Downloader#5293]
최신 버전인 3.7p에서 추가한 신규 다운로드와 구버전에서 추가했던 다운로드 모두 clf Timeout 이라 출력합니다.

Invalid: [manatoki] https://manatoki156.net/comic/512179

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 8 / False / 64294d0d8a3f4a1b9afa84f604d10b3c
input: https://manatoki156.net/comic/512179
type: manatoki
single: False
url: https://manatoki156.net/comic/512179
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1664532002.4227579 (22-09-30 10:00:02 UTC) - 13973s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 56, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 136, in get_soup
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki156.net/comic/512179  (732.9s)

clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 56, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 136, in get_soup
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://manatoki156.net/comic/512179  (797.1s)

[미도리카와 요우] 치한에게 당할뻔한 S급 미소녀를 구했더니 옆자리 소꿉친구였다

version: 3.2a (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 491 / False / c6c2976cd88f488a9fd19b1f41477751
input: https://manatoki156.net/comic/5770470
type: manatoki
single: False
url: https://manatoki153.net/comic/5770470
dir: hitomi_downloaded_manatoki\[미도리카와 요우] 치한에게 당할뻔한 S급 미소녀를 구했더니 옆자리 소꿉친구였다
zip: 
artist: 미도리카와 요우
valid / done: False / True
range / range_p: None / None
time: 1663681880.08518 (22-09-20 13:51:20 UTC) - 864263s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
(생략)

[URLs]

[Messages]
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\manatoki_downloader", line 56, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 136, in get_soup
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
invalid; revert
EOT: https://manatoki156.net/comic/5770470  (797.3s)

**Comment by ghkdqofjr1122** [comment]
캡챠 입력하셨나요?
