### ISSUE TITLE
xvideo 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

### ISSUE THREAD

**Issue by ksaeil2001** [KurtBestor/Hitomi-Downloader#5300]
Invalid: [xvideo] https://www.xvideos.com/video31897519/studiofow_-_nier_automata_first_assembly#show-related

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 6a59cd8a7c14485b92cca368ba28766e
input: https://www.xvideos.com/video31897519/studiofow_-_nier_automata_first_assembly#show-related
type: xvideo
single: True
url: https://www.xvideos.com/video31897519/studiofow_-_nier_automata_first_assembly#show-related
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1664788008.2665377 (22-10-03 09:06:48 UTC) - 89s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.09.01
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "timeout", line 29, in wrapper
 File "timeout", line 22, in f_
 File "downloader", line 105, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 413, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "timeout", line 29, in wrapper
 File "timeout", line 22, in f_
 File "downloader", line 105, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "timeout", line 29, in wrapper
 File "timeout", line 22, in f_
 File "downloader", line 105, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 811, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 440, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 234, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://www.xvideos.com/video31897519/studiofow_-_nier_automata_first_assembly#show-related  (7.3s)

**Comment by ksaeil2001** [comment]
문제가 뭘까

**Comment by fade-out-0770** [comment]
ip 밴당하신거아닐까 생각이 들어요.  전 잘되네요. 버젼은 version: 3.7p (22-09-19 23:58:13 UTC) 이걸로 동일하네요.
