### ISSUE TITLE
픽시브 코믹 또 다운로드가 안되네요

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#5329]
Invalid: [pixiv_comic] https://comic.pixiv.net/works/8757

version: 3.7p (22-09-30 02:27:54 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 46 / False / 6f313d94788b4def9d7f5514fb777935
input: https://comic.pixiv.net/works/8757
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8757
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1665647915.4976332 (22-10-13 07:58:35 UTC) - 977s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\pixiv_comic_downloader", line 66, in read
 File "extractor\pixiv_comic_downloader", line 51, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/8757  (6.1s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
