### ISSUE TITLE
데이터를 다운로드 하는 중에 실패했습니다

### ISSUE THREAD

**Issue by godnao** [KurtBestor/Hitomi-Downloader#5330]
Traceback (most recent call last):
  File "downloader", line 413, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 641, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 446, in read_html
  File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://kurtpyanywhere.com/h_data

라고 뜨네요...

**Comment by KurtBestor** [comment]
지금도 그러나요?
