### ISSUE TITLE
니코니코동화가 다운이 안됩니다

### ISSUE THREAD

**Issue by son8520** [KurtBestor/Hitomi-Downloader#5332]

**Comment by catki1348** [comment]
저도 니코니코 다운이 안되네요

Invalid: [nico] https://www.nicovideo.jp/watch/so41221044

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / d635699c5fd0488c8398d272f8f74718
input: https://www.nicovideo.jp/watch/so41221044
type: nico
single: True
url: https://www.nicovideo.jp/watch/so41221044
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1666876356.3397412 (22-10-27 13:12:36 UTC) - 5s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
Cannot execute CSS selectors because the soupsieve package is not installed.
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\nico_downloader", line 106, in read
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\nico_downloader", line 128, in get_video
 File "nndownload", line 372, in request_video
 File "nndownload", line 859, in perform_api_request
 File "bs4\element", line 1938, in select_one
 File "bs4\element", line 1970, in select
NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/so41221044  (3.4s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by son8520** [comment]
다운받은걸로 니코동 영상을 다운받으니 잘 됩니다!
-----Original Message-----

**Comment by catki1348** [comment]
테스트 용 파일로
쿠키 불러오기 다시 하니 정상적으로 다운로드 되었습니다.

**Comment by catki1348** [comment]
감사 합니다.

**Comment by jinsu421** [comment]
안녕하세요, 베타버전으로는 로그인도 쿠키도 없이 니코동 영상 다운은 잘됩니다만, 최신판은 왜 안되는건가요?

베타버전으로 계속 써도 무난한건가요?

**Comment by jinsu421** [comment]
> 안녕하세요, 베타버전으로는 로그인도 쿠키도 없이 니코동 영상 다운은 잘됩니다만, 최신판은 왜 안되는건가요?
> 
> 베타버전으로 계속 써도 무난한건가요?

참고사항으로 적자면, 최신판은 dpi를 켜고 사용하였고, 베타의 경우 dpi가 기본상태(꺼져있음) 이였습니다.
다만, 2가지 버전 둘다 dpi 온오프의 유무와는 관계가 없던것같습니다. 파일정리 때문에 버전 하나만 사용하고싶은데
참고나 조언좀 부탁드립니다.

**Comment by KurtBestor** [comment]
@jinsu421 사이트 구조 변경으로 정식 버전은 작동하지 않고 고친 게 테스트 버전이에요
