### ISSUE TITLE
[danbooru] 단부루 다운이 안됩니다.

### ISSUE THREAD

**Issue by bgm0001** [KurtBestor/Hitomi-Downloader#5336]
Invalid: [danbooru] https://danbooru.donmai.us/explore/posts/popular?date=2022-10-16&scale=week

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 81c187861ebe43828e885b08785a25c3
input: https://danbooru.donmai.us/explore/posts/popular?date=2022-10-16&scale=week
type: danbooru
single: False
url: https://danbooru.donmai.us/explore/posts/popular?date=2022-10-16&scale=week
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1665918312.9750345 (22-10-16 11:05:12 UTC) - 112s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://danbooru.donmai.us/explore/posts/popular?date=2022-10-16&scale=week
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\danbooru_downloader", line 53, in read
 File "extractor\danbooru_downloader", line 41, in name
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\danbooru_downloader", line 115, in read_soup
 File "downloader", line 339, in read_soup
 File "downloader", line 446, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/explore/posts/popular?date=2022-10-16&scale=week

Invalid: fail=True
quality: 100%
EOT: https://danbooru.donmai.us/explore/posts/popular?date=2022-10-16&scale=week  (2.1s)

**Comment by bgm0001** [comment]
정상작동 됩니다. 감사합니다!
