### ISSUE TITLE
lhscan 이 갑자기 다운이 안됩니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#5351]
항상 감사히 잘 쓰고 있습니다
잘되다가 2,3일 전부터 갑자기 안되네요
정보 올릴게요

Invalid: [lhscan] https://welovemanga.one/2849/

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / 56134be0ab00422da52f496df11b12b5
input: https://welovemanga.one/2849/
type: lhscan
single: False
url: https://welovemanga.one/2849/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [2]
time: 1666524934.0117168 (22-10-23 11:35:34 UTC) - 394s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
https://welovemanga.one/2849/ -> https://welovemanga.one/2849/
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
Chapter 3
no cn
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\lhscan_downloader", line 94, in read
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 190, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 112, in get_imgs_page
 File "ree", line 14, in find
ree.NotFound: no cn

Invalid: fail=True
EOT: https://welovemanga.one/2849/  (26.6s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
오 여기도 잘됩니다
바쁘실텐데 봐주신거 정말 감사합니다
