### ISSUE TITLE
spankbang 에서 다운이 안되는 영상이 다수 있습니다

### ISSUE THREAD

**Issue by k750627** [KurtBestor/Hitomi-Downloader#5353]
Invalid: [etc] https://spankbang.com/794cu/video/porn

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / d17b721a15f84a3d8aba3ad8e7af185d
input: https://spankbang.com/794cu/video/porn
type: etc
single: True
url: https://spankbang.com/794cu/video/porn
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1666534605.0915804 (22-10-23 14:16:45 UTC) - 7s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
extractor: spankbang
get_video: True, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
get_video: True, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
get_video: True, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
get_video: True, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
ERROR: [SpankBang] 794cu: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
get_video: False, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
get_video: False, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
get_video: False, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
get_video: False, https://spankbang.com/794cu/video/porn
[debug] [SpankBang] 794cu: Downloading webpage
ERROR: [SpankBang] 794cu: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 805, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 425, in urlopen
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 3682, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 672, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\spankbang", line 76, in _real_extract
   video_id, headers={'Cookie': 'country=US'})
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 1081, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 1032, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 866, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 823, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 1477, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 1553, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\extractor\common", line 698, in extract
   raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [SpankBang] 794cu: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 63, in get_video
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\etc_downloader", line 92, in _get_video
 File "extractor\etc_downloader", line 88, in _get_video
 File "ytdl", line 433, in extract_info
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 1466, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 1495, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 794cu: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\etc_downloader", line 27, in read
 File "extractor\etc_downloader", line 75, in get_video
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\etc_downloader", line 92, in _get_video
 File "extractor\etc_downloader", line 88, in _get_video
 File "ytdl", line 433, in extract_info
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 1466, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\zello\AppData\Local\Temp\_MEI45442\ytdl_069989dc\yt_dlp\yt_dlp\YoutubeDL", line 1495, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 794cu: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://spankbang.com/794cu/video/porn  (6.4s)

**Comment by k750627** [comment]
상위처럼 진행이 안되는경우가 몇십개가 있습니다. 
프로그램 재실행시 가끔 DPI 우회가 꺼져있다는 메세지도 있었는데 옵션에서 껏다 켰다 해봐도 차이가 없습니다.
