### ISSUE TITLE
데이터 다운로드중 실패가 뜹니다

### ISSUE THREAD

**Issue by k750627** [KurtBestor/Hitomi-Downloader#5363]
Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 372, in download_json_
  File "myjson", line 14, in loads
  File "json\__init__", line 348, in loads
  File "json\decoder", line 337, in decode
  File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by lumiamilk** [comment]
I have the same problem
