### ISSUE TITLE
픽시브 코믹 에러 확인 부탁드립니다.

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#5370]
Invalid: [pixiv_comic] https://comic.pixiv.net/works/7179

version: 3.7p (22-10-24 10:57:36 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 243 / False / 4fdd88cd5ba447a8bcf45572ee0b7fd0
input: https://comic.pixiv.net/works/7179
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/7179
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1667120512.7563193 (22-10-30 09:01:52 UTC) - 52s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\pixiv_comic_downloader", line 66, in read
 File "extractor\pixiv_comic_downloader", line 51, in name
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/7179  (6.2s)

**Comment by qj8x67s33a44** [comment]
이거 어떻게 안될까요?? 여전히 잘 안되네요
