### ISSUE TITLE
lhscan 사이트 다운이 안되는 것 같습니다.

### ISSUE THREAD

**Issue by seica2031** [KurtBestor/Hitomi-Downloader#5390]
읽는중에서 제목까지는 뜨는데 그 이후로는 안되네요
작업 정보 올립니다. 감사합니다.

Invalid: [lhscan] https://welovemanga.one/599/

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / a1c5af79344545008f28ed237d17c837
input: https://welovemanga.one/599/
type: lhscan
single: False
url: https://welovemanga.one/599/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1667703451.8175187 (22-11-06 02:57:31 UTC) - 209s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
no html
https://welovemanga.one/599/ -> https://welovemanga.one/599/
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
no cn
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\lhscan_downloader", line 94, in read
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 190, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 112, in get_imgs_page
 File "ree", line 14, in find
ree.NotFound: no cn

Invalid: fail=True
EOT: https://welovemanga.one/599/  (34.2s)

https://welovemanga.one/599/ -> https://welovemanga.one/599/
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
no cn
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\lhscan_downloader", line 94, in read
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 190, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 112, in get_imgs_page
 File "ree", line 14, in find
ree.NotFound: no cn

Invalid: fail=True
EOT: https://welovemanga.one/599/  (34.8s)

no html
https://welovemanga.one/599/ -> https://welovemanga.one/599/
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
Chapter 1
no cn
stop
Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\lhscan_downloader", line 94, in read
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 190, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\lhscan_downloader", line 112, in get_imgs_page
 File "ree", line 14, in find
ree.NotFound: no cn

Invalid: fail=True
EOT: https://welovemanga.one/599/  (29.3s)

**Comment by seica2031** [comment]
다른 분 이슈에 올려주신 파일 실행시 잘 다운 됩니다. 감사합니다.
