### ISSUE TITLE
nhentai.net 좀쓰다보면 안됩니다.

### ISSUE THREAD

**Issue by jjung3831** [KurtBestor/Hitomi-Downloader#5392]
Invalid: [nhentai] https://nhentai.net/g/426799/

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 4 / False / fb26bf7e4d6d410db730d6200608cdf7
input: https://nhentai.net/g/426799/
type: nhentai
single: False
url: https://nhentai.net/g/426799/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1667715918.4761596 (22-11-06 06:25:18 UTC) - 200s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "extractor\nhentai_downloader", line 26, in init
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://nhentai.net/g/426799/  (112.5s)

no html
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "extractor\nhentai_downloader", line 26, in init
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://nhentai.net/g/426799/  (102.5s)

wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1215, in start
 File "extractor\nhentai_downloader", line 26, in init
 File "clf2", line 147, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://nhentai.net/g/426799/  (132.4s)

막힌건가요??

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by jjung3831** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘됩니다.
감사합니다.^^
