### ISSUE TITLE
CANNOT download video from youku.com 无法下载优酷视频

### ISSUE THREAD

**Issue by amakerlife** [KurtBestor/Hitomi-Downloader#5393]
I CANNOT download any video from youku.com, because youku often changes the `ccode`. 

Please change ccode and fix it, thanks.

我无法下载 优酷 的任何视频，因为 优酷 经常更换 ccode，下载视频需要正确的 ccode 才能与优酷建立连接。

提示的错误信息为 `ccode 参数错误`。

望修复，谢谢。

log:
```
Invalid: [youku] https://v.youku.com/v_show/id_XNTE1MzczOTg4MA==.html?spm=a2h0c.8166622.PhoneSokuUgc_6.dtitle

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / zh_cn
order / group / uid: 0 / False / 73fed6c4aa9d46fa86f54081eb9fdd52
input: https://v.youku.com/v_show/id_XNTE1MzczOTg4MA==.html?spm=a2h0c.8166622.PhoneSokuUgc_6.dtitle
type: youku
single: True
url: https://v.youku.com/v_show/id_XNTE1MzczOTg4MA==.html?spm=a2h0c.8166622.PhoneSokuUgc_6.dtitle
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1667718827.5493317 (22-11-06 07:13:47 UTC) - 11s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.10.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
[debug] [youku] XNTE1MzczOTg4MA: Retrieving cna info
[debug] [youku] XNTE1MzczOTg4MA: Downloading JSON metadata
ERROR: [youku] XNTE1MzczOTg4MA: Youku server reported error -6001: ccode参数错误; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\extractor\common", line 672, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\extractor\youku", line 186, in _real_extract
   raise ExtractorError(msg)
yt_dlp.utils.ExtractorError: Youku server reported error -6001: ccode参数错误; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\YoutubeDL", line 1477, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\YoutubeDL", line 1553, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\extractor\common", line 698, in extract
   raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [youku] XNTE1MzczOTg4MA: Youku server reported error -6001: ccode参数错误; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\youku_downloader", line 16, in read
 File "utils", line 811, in __call__
 File "extractor\youku_downloader", line 36, in get
 File "ytdl", line 433, in extract_info
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\YoutubeDL", line 1466, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\yuyan\AppData\Local\Temp\_MEI32162\ytdl_f7b16bd5\yt_dlp\yt_dlp\YoutubeDL", line 1495, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
yt_dlp.utils.DownloadError: ERROR: [youku] XNTE1MzczOTg4MA: Youku server reported error -6001: ccode参数错误; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://v.youku.com/v_show/id_XNTE1MzczOTg4MA==.html?spm=a2h0c.8166622.PhoneSokuUgc_6.dtitle  (7.7s)

```

**Comment by amakerlife** [comment]
@KurtBestor

**Comment by KurtBestor** [comment]
I made a PR to yt-dlp: https://github.com/yt-dlp/yt-dlp/pull/5622

**Comment by amakerlife** [comment]
Please @me when this pr is merged. 
Thanks.
