### ISSUE TITLE
이런 메시지가 뜨면서 Danbooru(단부루) 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by Foxchandaisuki** [KurtBestor/Hitomi-Downloader#5416]
Invalid: [danbooru] https://danbooru.donmai.us/posts?tags=afnroll&z=1

version: 3.7p (22-09-19 23:58:13 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 465fbd2168f146fba0733f5991c57350
input: https://danbooru.donmai.us/posts?tags=afnroll&z=1
type: danbooru
single: False
url: https://danbooru.donmai.us/posts?tags=afnroll&z=1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1668284320.782359 (22-11-12 20:18:40 UTC) - 17s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.11.11
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://danbooru.donmai.us/posts?tags=afnroll&z=1&page=1
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "timeout", line 29, in wrapper
 File "timeout", line 22, in f_
 File "downloader", line 105, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 413, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "timeout", line 29, in wrapper
 File "timeout", line 22, in f_
 File "downloader", line 105, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "timeout", line 29, in wrapper
 File "timeout", line 22, in f_
 File "downloader", line 105, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1230, in start
 File "utils", line 1304, in start_
 File "extractor\danbooru_downloader", line 55, in read
 File "extractor\danbooru_downloader", line 142, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 970, in wrapper
 File "constants", line 941, in wrapper
 File "extractor\danbooru_downloader", line 115, in read_soup
 File "downloader", line 339, in read_soup
 File "downloader", line 440, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 234, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://danbooru.donmai.us/posts?tags=afnroll&z=1  (1.9s)

**Comment by Foxchandaisuki** [comment]
이미 단부루, danbooru로 올라온 이슈들 검색까지 다 해 본 상태입니다. 거기에 테스트 버전 링크 걸어주신 거 다운받아서 써봤는데도 안 됐어요...
