### ISSUE TITLE
baraag 도와주세요

### ISSUE THREAD

**Issue by newb1eeee** [KurtBestor/Hitomi-Downloader#5455]
Invalid: [baraag] https://baraag.net/@robot

version: 3.7p (22-11-23 10:34:48 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / b36f5cc920584ddbabd65416206e7df5
input: https://baraag.net/@robot
type: baraag
single: False
url: https://baraag.net/@robot
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1669307349.9604151 (22-11-24 16:29:09 UTC) - 9s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.11.11
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
You need to sign in or sign up before continuing.: https://baraag.net/@robot
stop
Traceback (most recent call last):
 File "utils", line 1234, in start
 File "utils", line 1309, in start_
 File "extractor\baraag_downloader", line 48, in read
 File "mastodon", line 36, in get_imgs
errors.Invalid: You need to sign in or sign up before continuing.: https://baraag.net/@robot

Invalid: fail=False
EOT: https://baraag.net/@robot  (2.5s)

You need to sign in or sign up before continuing.: https://baraag.net/@robot
stop
Traceback (most recent call last):
 File "utils", line 1234, in start
 File "utils", line 1309, in start_
 File "extractor\baraag_downloader", line 48, in read
 File "mastodon", line 36, in get_imgs
errors.Invalid: You need to sign in or sign up before continuing.: https://baraag.net/@robot

Invalid: fail=False
EOT: https://baraag.net/@robot  (2.7s)

You need to sign in or sign up before continuing.: https://baraag.net/@robot
stop
Traceback (most recent call last):
 File "utils", line 1234, in start
 File "utils", line 1309, in start_
 File "extractor\baraag_downloader", line 48, in read
 File "mastodon", line 36, in get_imgs
errors.Invalid: You need to sign in or sign up before continuing.: https://baraag.net/@robot

Invalid: fail=False
EOT: https://baraag.net/@robot  (3.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1234, in start
 File "utils", line 1324, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://baraag.net/@robot  (5.7s)

---------------------------------------------------------------------------------------------------------------------------------------------------

히토미나 픽시브 등등 dpi우회 읽히는데 굼떠서그렇지 잘되는거같은데 유독 baraag만 안됩니다.

확장프로그램 cookie txt 내보낼때 include sub domains 이게  false라고 떠서 이게 문제인가 싶어서 해결할려고 시도하는데

광고차단기같은걸 다 꺼도 안됩니다. 이게 그냥 baraag 자체의 문제일까요? 당장 브라우저로 볼 수는 있는데....
쿠키 초기화하고 새로 불러들이거나 아예 다운로더 새로 다운받아서 새로 쿠키 불러들여보고해도 결국은 안됩니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/5435#issuecomment-1328256556
