### ISSUE TITLE
폰허브 다운로드가 안 됩니다..

### ISSUE THREAD

**Issue by gehenna3702** [KurtBestor/Hitomi-Downloader#5472]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

위 링크 파일 덮어쓰기 했는데도 안 돼요...

다운로드 100%인데 노란색 뜹니다. 실행해 보면 파일이 뚝뚝 끊겨요...

작업 정보입니다.

NUT ON ME and then LET'S FUCK 🚨

version: 3.7p (22-11-30 07:08:33 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 401e9702fa544a3a8b21a661fb459967
input: https://www.pornhub.com/view_video.php?viewkey=ph62b7ffa40a6a1
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph62b7ffa40a6a1
dir: F:\ph d m2
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1669801727.4371521 (22-11-30 09:48:47 UTC) - 378s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.11.11
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] F:\ph d m2\[Candy Love] NUT ON ME and then LET'S FUCK 🚨 (ph62b7ffa40a6a1).mp4

[URLs]
[0001] LazyUrl(https://www.pornhub.com/view_video.php?viewkey=ph62b7ffa40a6a1)    --->    M3u8_stream(https://ev-h.phncdn.com/hls/videos/202206/26/410624311/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_410624311.mp4.urlset/index-f1-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=wtZ9PMtMes84vPfsHKqSmDp53WE%3D)

[Messages]
【ffmpeg】 load...
id: ph62b7ffa40a6a1
【ffmpeg】 loaded
【ffprobe】 load...
【ffprobe】 loaded
Video
[debug] [PornHub] ph62b7ffa40a6a1: Downloading pc webpage
[debug] [PornHub] ph62b7ffa40a6a1: Downloading m3u8 information
[debug] [PornHub] ph62b7ffa40a6a1: Downloading m3u8 information
[debug] [PornHub] ph62b7ffa40a6a1: Downloading m3u8 information
[debug] [PornHub] ph62b7ffa40a6a1: Downloading m3u8 information
[debug] [PornHub] ph62b7ffa40a6a1: Downloading JSON metadata
[warning] [PornHub] ph62b7ffa40a6a1: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[240p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/240P_1000K_410624311.mp4/index-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=xj2BNMdw2UCY3mst1A4ZAru%2FavQ%3D
[240p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_410624311.mp4.urlset/index-f4-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=wtZ9PMtMes84vPfsHKqSmDp53WE%3D
[480p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/480P_2000K_410624311.mp4/index-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=n57KTPI1dz6ZaAgq%2F%2FYgFJdY6Jo%3D
[480p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_410624311.mp4.urlset/index-f3-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=wtZ9PMtMes84vPfsHKqSmDp53WE%3D
[720p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/720P_4000K_410624311.mp4/index-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=jaRue5h%2Flo4tnpnrL1IBeytCf6g%3D
[720p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_410624311.mp4.urlset/index-f2-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=wtZ9PMtMes84vPfsHKqSmDp53WE%3D
[1080p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_410624311.mp4.urlset/index-f1-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=wtZ9PMtMes84vPfsHKqSmDp53WE%3D

[1080p] m3u8_native https://ev-h.phncdn.com/hls/videos/202206/26/410624311/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_410624311.mp4.urlset/index-f1-v1-a1.m3u8?validfrom=1669798133&validto=1669805333&ipa=218.232.125.97&hdl=-1&hash=wtZ9PMtMes84vPfsHKqSmDp53WE%3D
### reset size ###
use just download: overwrite=False
media: 0
Convert: F:\ph d m2\[Candy Love] NUT ON ME and then LET'S FUCK 🚨 (ph62b7ffa40a6a1).mp4
rename (1): F:\ph d m2\[Candy Love] NUT ON ME and then LET'S FUCK 🚨 (ph62b7ffa40a6a1).mp4 -> F:\ph d m2\tmp4d1e5e85d84f4b94bc50ee42058a2d57_i.mp4
-i tmp4d1e5e85d84f4b94bc50ee42058a2d57_i.mp4 -acodec copy -vcodec copy -threads 0 tmp4d1e5e85d84f4b94bc50ee42058a2d57_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
rename (1): F:\ph d m2\tmp4d1e5e85d84f4b94bc50ee42058a2d57_i.mp4 -> F:\ph d m2\[Candy Love] NUT ON ME and then LET'S FUCK 🚨 (ph62b7ffa40a6a1).mp4

Fail m3u8 pp : [Candy Love] NUT ON ME and then LET'S FUCK 🚨 (ph62b7ffa40a6a1).mp4
Traceback (most recent call last):
 File "downloader", line 982, in download
 File "m3u8_tools", line 286, in _pp
 File "ffmpeg", line 343, in convert
 File "ffmpeg", line 330, in convert
 File "ffmpeg", line 166, in run
 File "patch_subprocess", line 16, in __init__
 File "subprocess", line 800, in __init__
 File "subprocess", line 1207, in _execute_child
OSError: [WinError 193] %1은(는) 올바른 Win32 응용 프로그램이 아닙니다

stop
valid=False 1
-show_streams -print_format json -v error "[Candy Love] NUT ON ME and then LET'S FUCK 🚨 (ph62b7ffa40a6a1).mp4"
Traceback (most recent call last):
 File "utils", line 1726, in finish
 File "ffmpeg", line 703, in get_info
 File "ffmpeg", line 697, in get_info
 File "ffmpeg", line 166, in run
 File "patch_subprocess", line 16, in __init__
 File "subprocess", line 800, in __init__
 File "subprocess", line 1207, in _execute_child
OSError: [WinError 193] %1은(는) 올바른 Win32 응용 프로그램이 아닙니다

EOT: https://www.pornhub.com/view_video.php?viewkey=ph62b7ffa40a6a1  (41.9s)

**Comment by KurtBestor** [comment]
이 프로그램 cmd 에서 실행하면 어떻게 뜨나요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/download/Utils/ffmpeg3.exe

**Comment by gehenna3702** [comment]
![2022-12-02 16 13 23](https://user-images.githubusercontent.com/77250986/205236765-4e7dfd9e-ab8e-41e5-862e-4c0e28db18d0.png)
이렇게 뜹니다

**Comment by KurtBestor** [comment]
cmd에서 다음과 같이 입력하고:
```
cd %temp%
```

다음을 실행하면 어떻게 뜨나요?
```
ffmpeg.exe
```

**Comment by gehenna3702** [comment]
![2022-12-03 18 05 03](https://user-images.githubusercontent.com/77250986/205433342-366753e6-a140-4437-99c0-9403a023ac15.png)
이렇게 떠여
