### ISSUE TITLE
픽시브 코믹 대량 다운로드가 안됩니다...

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#5498]
대량 다운로드가 안돼요.

https://comic.pixiv.net/works/8917
https://comic.pixiv.net/works/8916
https://comic.pixiv.net/works/8914
https://comic.pixiv.net/works/8912
https://comic.pixiv.net/works/8910
https://comic.pixiv.net/works/8909
https://comic.pixiv.net/works/8908
https://comic.pixiv.net/works/8875
https://comic.pixiv.net/works/8866
https://comic.pixiv.net/works/8847

위 10개만 다운로드 추가를 해도 몇개만 다운로드되고 나머지는 다운로드가 안돼요..

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

혹시 몰라서 위 링크에 베타 버전 업데이트 해주실때마다 시도해보는데 계속 안되네요.

다른 일로 바쁘실테지만 수정 가능하다면 부탁드립니다...

항상 감사드립니다.

--------

Invalid: [pixiv_comic] https://comic.pixiv.net/works/8909

version: 3.7p (22-12-07 11:04:41 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 4 / False / f2c6c33dcc3543eca48589ddbadfe516
input: https://comic.pixiv.net/works/8909
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8909
dir: 
zip: 
artist: 加森キキ
valid / done: False / True
range / range_p: None / None
time: 1670417517.5699728 (22-12-07 12:51:57 UTC) - 59s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.11.11
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
https://comic.pixiv.net/viewer/stories/131967
https://comic.pixiv.net/viewer/stories/131967
https://comic.pixiv.net/viewer/stories/131967
https://comic.pixiv.net/viewer/stories/131967
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1266, in start
 File "utils", line 1341, in start_
 File "decorator", line 232, in fun
 File "constants", line 980, in wrapper
 File "constants", line 951, in wrapper
 File "extractor\pixiv_comic_downloader", line 46, in read
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/8909  (24.4s)

----------

Invalid: [pixiv_comic] https://comic.pixiv.net/works/8908

version: 3.7p (22-12-07 11:04:41 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 3 / False / f161610b0639468593d7bbf3a31a272f
input: https://comic.pixiv.net/works/8908
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/8908
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1670417517.589029 (22-12-07 12:51:57 UTC) - 71s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.11.11
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1266, in start
 File "utils", line 1341, in start_
 File "decorator", line 232, in fun
 File "constants", line 980, in wrapper
 File "constants", line 951, in wrapper
 File "extractor\pixiv_comic_downloader", line 46, in read
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/8908  (28.3s)

---------

**Comment by qj8x67s33a44** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

정말 잘 됩니다, 다시 한 번 정말 감사드립니다.
