### ISSUE TITLE
[Errno 9] Bad file descriptor: 'CONOUT$' 가 떠서 실행이 안됩니다.

### ISSUE THREAD

**Issue by Jack12qe** [KurtBestor/Hitomi-Downloader#5592]
````python
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\youtube_downloader", line 409, in read
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\ASUS\AppData\Local\Temp\_MEI222562\ytdl_f1401405\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\ASUS\AppData\Local\Temp\_MEI222562\ytdl_f1401405\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

````

**Comment by KurtBestor** [comment]
[yt-dlp](https://github.com/yt-dlp/yt-dlp) 문제이긴 한데 업데이트 오래 걸릴 것 같아서 일단 동작하게 수정했어요

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by zzzinter** [comment]
This one works. Thanks for the updating.
Latest beta version of Hitomi Downloader
Last update: 2023.01.02

**Comment by Jack12qe** [comment]
덕분에 잘 동작되네요. 
빠른 조치 감사합니다.
