### ISSUE TITLE
비리비리 영상 다운이안됩니다.

### ISSUE THREAD

**Issue by Abdiel4** [KurtBestor/Hitomi-Downloader#5593]
Invalid: [bili] https://www.bilibili.com/video/BV1CA411S7wE/?spm_id_from=333.999.0.0&vd_source=c1194d0ee6ba406d3650c70de4e348ae

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / 91998ba207664b06b25b405b0c1b5cab
input: https://www.bilibili.com/video/BV1CA411S7wE/?spm_id_from=333.999.0.0&vd_source=c1194d0ee6ba406d3650c70de4e348ae
type: bili
single: True
url: https://www.bilibili.com/video/BV1CA411S7wE/?spm_id_from=333.999.0.0&vd_source=c1194d0ee6ba406d3650c70de4e348ae
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672687358.74486 (23-01-02 19:22:38 UTC) - 6s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1CA411S7wE/?spm_id_from=333.999.0.0&vd_source=c1194d0ee6ba406d3650c70de4e348ae -> https://www.bilibili.com/video/BV1CA411S7wE/?spm_id_from=333.999.0.0&vd_source=c1194d0ee6ba406d3650c70de4e348ae
CURRENT_QUALITY: None
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\bili_downloader", line 117, in read
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\bili_downloader", line 169, in get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\user\AppData\Local\Temp\_MEI77402\ytdl_f9f20d96\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\user\AppData\Local\Temp\_MEI77402\ytdl_f9f20d96\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1CA411S7wE/?spm_id_from=333.999.0.0&vd_source=c1194d0ee6ba406d3650c70de4e348ae  (1.5s)

**Comment by Jack12qe** [comment]
개발자님이 업데이트 전에 쓰시라고 올려주신 프리버전 링크입니다.
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
