### ISSUE TITLE
All objects are Invalid

### ISSUE THREAD

**Issue by zzzinter** [KurtBestor/Hitomi-Downloader#5594]
Hi there, 
It has been working great all the time until today. I cannot download any video from Youtube or Bili. Information attached below.
Please help. Thanks a lot.

Invalid: [bili] https://www.bilibili.com/video/BV1BG4y137mG?spm_id_from=333.1007.tianma.1-1-1.click

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_cn
order / group / uid: 0 / False / 9d032d0da74f4e3fbae3d739f2c00e08
input: https://www.bilibili.com/video/BV1BG4y137mG?spm_id_from=333.1007.tianma.1-1-1.click
type: bili
single: True
url: https://www.bilibili.com/video/BV1BG4y137mG/?spm_id_from=333.1007.tianma.1-1-1.click
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672688365.952883 (23-01-02 19:39:25 UTC) - 328s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1BG4y137mG?spm_id_from=333.1007.tianma.1-1-1.click -> https://www.bilibili.com/video/BV1BG4y137mG/?spm_id_from=333.1007.tianma.1-1-1.click
CURRENT_QUALITY: None
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\bili_downloader", line 117, in read
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\bili_downloader", line 169, in get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\xxx\AppData\Local\Temp\_MEI66362\ytdl_b0cec280\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\xxx\AppData\Local\Temp\_MEI66362\ytdl_b0cec280\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1BG4y137mG?spm_id_from=333.1007.tianma.1-1-1.click  (1.6s)

**Comment by hydratioNx99** [comment]
temporary fix at the bottom

https://github.com/KurtBestor/Hitomi-Downloader/issues/5592
