### ISSUE TITLE
갑자기 유튜브가 다운로드 안됩니다.

### ISSUE THREAD

**Issue by assstone** [KurtBestor/Hitomi-Downloader#5595]
유튜브가 어제까지는 다운로드가 잘 됐는데, 
아침에 일어나니 갑자기 다운로드가 안 됩니다.

밑에는 "작업 정보" 입니다.
========================================
Invalid: [youtube] https://www.youtube.com/watch?v=jxQhNfiBGFo

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 9eafb822383a456c83917b0909b3b247
input: https://www.youtube.com/watch?v=jxQhNfiBGFo
type: youtube
single: True
url: https://www.youtube.com/watch?v=jxQhNfiBGFo
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672694946.1946838 (23-01-02 21:29:06 UTC) - 76s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\youtube_downloader", line 409, in read
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\assst\AppData\Local\Temp\_MEI70482\ytdl_dd38fde2\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=jxQhNfiBGFo  (6.6s)

**Comment by Jack12qe** [comment]
개발자님이 업데이트 전에 쓰시라고 올려두신 프리버전 링크 올려드립니다.
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
