### ISSUE TITLE
Periscope,트위터 라이브 오류

### ISSUE THREAD

**Issue by pkackaks** [KurtBestor/Hitomi-Downloader#5602]
저번 업데이트 전까지는 되었는데 안되네요 ㅠㅠ

Invalid: [etc] https://www.pscp.tv/official_izone/1ypKdOqRkjRxW

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / 1f86ce3b60f44319bd9f099ea7feca82
input: https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
type: etc
single: True
url: https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672764655.389702 (23-01-03 16:50:55 UTC) - 1164s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
extractor: periscope
get_video: True, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
get_video: True, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
get_video: True, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
get_video: True, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
[Errno 9] Bad file descriptor: 'CONOUT$'
get_video: False, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
get_video: False, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
get_video: False, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
get_video: False, https://www.pscp.tv/official_izone/1ypKdOqRkjRxW
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "extractor\etc_downloader", line 63, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\pkqkr\AppData\Local\Temp\_MEI70242\ytdl_7567ced9\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\pkqkr\AppData\Local\Temp\_MEI70242\ytdl_7567ced9\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\etc_downloader", line 27, in read
 File "extractor\etc_downloader", line 75, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\pkqkr\AppData\Local\Temp\_MEI70242\ytdl_7567ced9\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\pkqkr\AppData\Local\Temp\_MEI70242\ytdl_7567ced9\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://www.pscp.tv/official_izone/1ypKdOqRkjRxW  (0.7s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5592
