### ISSUE TITLE
유튜브 다운로드 불가능

### ISSUE THREAD

**Issue by aweq21sxc** [KurtBestor/Hitomi-Downloader#5603]
c드라이브에 중복된 파일들 제거 후에 갑자기 안되는거 같음...
어떻게 해야하는지..

Invalid: [youtube] https://www.youtube.com/watch?v=BYVSJYNUfu0

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 4a05b08d9eb84320ac87dd9bd2486842
input: https://www.youtube.com/watch?v=BYVSJYNUfu0
type: youtube
single: True
url: https://www.youtube.com/watch?v=BYVSJYNUfu0
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672772539.4093668 (23-01-03 19:02:19 UTC) - 290s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\youtube_downloader", line 409, in read
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI104242\ytdl_31bb744e\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=BYVSJYNUfu0  (6.7s)

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\youtube_downloader", line 409, in read
 File "extractor\youtube_downloader", line 402, in read
 File "utils", line 851, in __call__
 File "extractor\youtube_downloader", line 77, in get
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\gilga\AppData\Local\Temp\_MEI175522\ytdl_f3c66bca\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=BYVSJYNUfu0  (6.6s)

새로운 파일을 받아도 여전히 안됨

**Comment by aweq21sxc** [comment]
1월1일 날짜로 복원을 시도했지만 제거된 파일은 안 돌아온거같음

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5592
