### ISSUE TITLE
Does not want to download from hentai.net

### ISSUE THREAD

**Issue by hahapy** [KurtBestor/Hitomi-Downloader#5604]
Invalid: [nhentai] https://nhentai.net/g/415446/

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ru_ru
order / group / uid: 0 / False / b6fc234ced034ba2a3251c273b09471c
input: https://nhentai.net/g/415446/
type: nhentai
single: False
url: https://nhentai.net/g/415446/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672774163.5599248 (23-01-03 19:29:23 UTC) - 29s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\nhentai_downloader", line 33, in read
 File "extractor\nhentai_downloader", line 129, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\nhentai_downloader", line 96, in get_info
IndexError: list index out of range

Invalid: fail=True
EOT: https://nhentai.net/g/415446/  (26.5s)

**Comment by Deamarat** [comment]
Somehow I make it work. 
I start with one link, open the built-in browser, open the link inside the browser, pass cloudflare check, a nutaku ad pops up, then the next links added start downloading. When the ad doesn't show can't download even if the cloudflare check pass. 
I suspect this ad is hijacking the links inside the gallery page, just need to be opened once.
