### ISSUE TITLE
All downloads are failed (error message: "Invalid")

### ISSUE THREAD

**Issue by tluocs** [KurtBestor/Hitomi-Downloader#5605]
No matter what download format (mp3 or mp4), and no matter what Youtube URL (have tried more than 20 different URLs), all the downloads will fail. Very strange.

![screen](https://user-images.githubusercontent.com/25195389/210469129-2c2d496b-6f07-4cd4-97ba-c899c1915c02.jpg)
The below is the log (task info) for an example video:

---------------------------------------------------------------------------------------------
Invalid: [youtube] https://youtu.be/nQdnzKw6UAs

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / f4eb92145c2c478ebd9ff647499f900c
input: https://youtu.be/nQdnzKw6UAs
type: youtube
single: True
url: https://youtu.be/nQdnzKw6UAs
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672796282.5527015 (23-01-04 01:38:02 UTC) - 13s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp3
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 67, in get
 File "ytdl", line 539, in __init__
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\ccadmin\AppData\Local\Temp\_MEI2079962\ytdl_498a10d3\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\ccadmin\AppData\Local\Temp\_MEI2079962\ytdl_498a10d3\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

---------------------------------------------------------------------------------------------

**Comment by SamUni88** [comment]
Yesterday, already happen. :(

**Comment by dadavuvu** [comment]
i have the same problem :(

**Comment by athletefigher** [comment]
same... No download...

**Comment by hancepark** [comment]
same with me

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5592

**Comment by darknarciss** [comment]
same with me....

**Comment by zg1999919** [comment]
不知道这种情况怎么解决？
到现在也是这种情况

**Comment by zg1999919** [comment]
tuyoube下载失败！

**Comment by iG8R** [comment]
Same here.

**Comment by qhghong** [comment]
same with me，2023/1/6
