### ISSUE TITLE
xhamster 오류입니다

### ISSUE THREAD

**Issue by daredevil1503** [KurtBestor/Hitomi-Downloader#5614]
xhamster로 다운로드 할려면 자꾸 invalid 가 뜹니다

Invalid: [etc] https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 75 / False / 0d6ece6288234d5baae88f4c1d35fc95
input: https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
type: etc
single: True
url: https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672915249.374368 (23-01-05 10:40:49 UTC) - 213s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
extractor: xhamster
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
[Errno 9] Bad file descriptor: 'CONOUT$'
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "extractor\etc_downloader", line 63, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\etc_downloader", line 27, in read
 File "extractor\etc_downloader", line 75, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2  (0.6s)

extractor: xhamster
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
[Errno 9] Bad file descriptor: 'CONOUT$'
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "extractor\etc_downloader", line 63, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\etc_downloader", line 27, in read
 File "extractor\etc_downloader", line 75, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\82102\AppData\Local\Temp\_MEI168762\ytdl_a8fa69e4\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2  (0.7s)

extractor: xhamster
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: True, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
[Errno 9] Bad file descriptor: 'CONOUT$'
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
get_video: False, https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2
[Errno 9] Bad file descriptor: 'CONOUT$'
stop
Traceback (most recent call last):
 File "extractor\etc_downloader", line 63, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\82102\AppData\Local\Temp\_MEI156682\ytdl_8834e1ee\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\82102\AppData\Local\Temp\_MEI156682\ytdl_8834e1ee\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "extractor\etc_downloader", line 27, in read
 File "extractor\etc_downloader", line 75, in get_video
 File "decorator", line 232, in fun
 File "constants", line 905, in wrapper
 File "constants", line 876, in wrapper
 File "extractor\etc_downloader", line 86, in _get_video
 File "ytdl", line 367, in YoutubeDL
 File "C:\Users\82102\AppData\Local\Temp\_MEI156682\ytdl_8834e1ee\yt_dlp\yt_dlp\YoutubeDL", line 589, in __init__
   windows_enable_vt_mode()
 File "C:\Users\82102\AppData\Local\Temp\_MEI156682\ytdl_8834e1ee\yt_dlp\yt_dlp\utils", line 5661, in windows_enable_vt_mode
   handle = os.open('CONOUT$', os.O_RDWR)
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

Invalid: fail=True
EOT: https://ko.xhday.com/videos/retro-usa-682-90s-compilation-xhgcUf2  (1.0s)

quality: 75%

어디가 잘못된건지 알 수 있을까요

**Comment by darknarciss** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/5605#issuecomment-1371043874
우선 여기서 급한대로 새로 다운 받아서 쓰세요
저도 기존꺼 지우고 여기서 새로 받아서 쓰니 잘 돼요
임시 버전이라고 하더라구요 얘네들도 시간이 좀 걸린다고 하네요...
