### ISSUE TITLE
Can't download illustration from pixiv

### ISSUE THREAD

**Issue by lumiamilk** [KurtBestor/Hitomi-Downloader#5628]
I have imported the pixiv cookie and tried the latest version of the Hitomi-Downloader and also tried the Technical-Preview version,
It shows the information: "invalid: [pixiv] https://www.pixiv.net/users/44265104"
I can login in pixiv by chrome and also can visit the illustration of the artist.

Here is the log:
——————————————————————————————————————
Invalid: [pixiv] https://www.pixiv.net/users/44265104

version: 3.8a (23-01-07 09:34:25 UTC)
platform / locale: Windows-10-10.0.17763-SP0 / zh_cn
order / group / uid: 0 / False / 8e34443251ae4169ae8869dbff442fbf
input: https://www.pixiv.net/users/44265104
type: pixiv
single: False
url: https://www.pixiv.net/users/44265104
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1673245527.2123601 (23-01-09 06:25:27 UTC) - 54s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.01.06
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
sid: 7666590_RcpJTRczdwvs6INDG0rnGj8270BVkbQ7
types: ['illusts', 'manga'], tag: None
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1263, in start
 File "utils", line 1339, in start_
 File "extractor\pixiv_downloader", line 93, in read
 File "extractor\pixiv_downloader", line 451, in get_info
 File "extractor\pixiv_downloader", line 500, in process_user
 File "extractor\pixiv_downloader", line 166, in top
 File "decorator", line 232, in fun
 File "constants", line 910, in wrapper
 File "constants", line 879, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 139, in call
 File "downloader", line 406, in read_json
 File "myjson", line 14, in loads
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://www.pixiv.net/users/44265104  (47.6s)

**Comment by lumiamilk** [comment]
well......when I have cleared the old cookie in Hitomi-Downloader and imported the latest cookie of pixiv, then it works well......
