### ISSUE TITLE
Fail to start http server 오류

### ISSUE THREAD

**Issue by danielkandi** [KurtBestor/Hitomi-Downloader#5630]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 10066, in <module>
  File "hitomi_server\__init__", line 389, in start
  File "hitomi_server\__init__", line 348, in join
  File "hitomi_server\__init__", line 341, in run
  File "decorator", line 232, in fun
  File "locker", line 63, in _wrapper
  File "hitomi_server\__init__", line 372, in switch
  File "hitomi_server\__init__", line 364, in switch
  File "hitomi_server\__init__", line 101, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 139, in server_bind
  File "socket", line 676, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 0: invalid start byte

컴퓨터 이름은 영문입니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/211476218-7ee73c59-0cd1-480d-9153-3afa5ee1d9e9.png)

여기에 어떻게 적혀있나요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/211477787-8291b1b7-a909-4221-a231-057f0fa84769.png)

여기에 어떻게 적혀있나요?

**Comment by danielkandi** [comment]
장치 이름이 한글로 적혀 있네요!
영문으로 수정하고 나서 오류가 사라지고 다운도 잘됩니다.
감사합니다!
