### ISSUE TITLE
Err: Failed to start HTTP server; OSError: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다.

### ISSUE THREAD

**Issue by paradoxsprial** [KurtBestor/Hitomi-Downloader#5639]
### 1. 문제점
HTTP 서버가 동작하지 않습니다.
### 2. 에러메시지
```
Err: Failed to start HTTP server

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 10066, in <module>
  File "hitomi_server\__init__", line 389, in start
  File "hitomi_server\__init__", line 348, in join
  File "hitomi_server\__init__", line 341, in run
  File "decorator", line 232, in fun
  File "locker", line 63, in _wrapper
  File "hitomi_server\__init__", line 372, in switch
  File "hitomi_server\__init__", line 364, in switch
  File "hitomi_server\__init__", line 101, in __init__
  File "socketserver", line 452, in __init__
  File "http\server", line 137, in server_bind
  File "socketserver", line 466, in server_bind
OSError: [WinError 10013] 액세스 권한에 의해 숨겨진 소켓에 액세스를 시도했습니다
```
### 3. 시스템 정보
version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
admin: True
goodbyedpi: True

<details>
  <summary>추가 정보 열기 (정보를 얻기 위하여, avgle 링크를 넣어 의도적으로 발생 시킨 에러 로그)</summary>

  ```
  No data; See: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension
  version: 3.8a (23-01-06 05:25:55 UTC)
  platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
  order / group / uid: 0 / False / 
  input:
  type: avgle
  single: True
  url:
  dir: 
  zip: 
  artist: None
  valid / done: False / True
  range / range_p: None / None
  time: 1673677756.5880332 (23-01-14 06:29:16 UTC) - 393s elapsed
  tags: []
  lock: False
  color: invalid
  paused: False
  format: None
  p2f: None
  segment: None
  admin: True
  goodbyedpi: True
  ytdl: yt_dlp 2023.01.06
  pinned: False
  extras: {}
  live: False
  changed: True
  
  
  [Gallery]
  None
  
  
  [File Names]
  
  
  
  [URLs]
  
  
  
  [Messages]
  No data; See: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension
  stop
  Traceback (most recent call last):
   File "utils", line 1245, in start
   File "extractor\avgle_downloader", line 25, in init
  errors.Invalid: No data; See: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension
  
  Invalid: fail=False
  quality: 100%
  EOT: (1.0s)
  ```
</details>

### 4. 해결을 위한 노력
- 컴퓨터에 열린 포트 확인
  * 입력: netstat -ano | findstr "6974"
  * 출력: <없음>
- 장치 이름 확인
  * 이름: DESKTOP-XXXXXXX
  * 모두 영문으로 문제 없음
- 방화벽 확인
  * 방화벽에 앱이 허용되어 있음
  * 방화벽을 모두 끈 상태에서도 여전히 같은 오류 발생
- 설정 파일 없이, 초기 상태에서 실행

**Comment by paradoxsprial** [comment]
윈도우를 업데이트 하였더니 해결되었습니다.
