### ISSUE TITLE
트위치 다시보기 다운 안됨 (vpn적용)

### ISSUE THREAD

**Issue by hjsg1010** [KurtBestor/Hitomi-Downloader#5649]
Invalid: [twitch] https://www.twitch.tv/videos/1708865802

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 3e3e406fc31841da9a1ef495615e6528
input: https://www.twitch.tv/videos/1708865802
type: twitch
single: True
url: https://www.twitch.tv/videos/1708865802
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1674014786.8790925 (23-01-18 04:06:26 UTC) - 98s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.06
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
downloader_v3 fail... p[16 / 92]
Traceback (most recent call last):
 File "urllib3\response", line 436, in _error_catcher
 File "urllib3\response", line 518, in read
 File "http\client", line 461, in read
 File "http\client", line 505, in readinto
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\models", line 758, in generate
 File "urllib3\response", line 575, in stream
 File "urllib3\response", line 540, in read
 File "contextlib", line 130, in __exit__
 File "urllib3\response", line 441, in _error_catcher
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 78, in run
 File "requests\models", line 836, in content
 File "requests\models", line 765, in generate
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

downloader_v3 fail... p[44 / 92]
Traceback (most recent call last):
 File "urllib3\response", line 436, in _error_catcher
 File "urllib3\response", line 518, in read
 File "http\client", line 461, in read
 File "http\client", line 505, in readinto
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\models", line 758, in generate
 File "urllib3\response", line 575, in stream
 File "urllib3\response", line 540, in read
 File "contextlib", line 130, in __exit__
 File "urllib3\response", line 441, in _error_catcher
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 78, in run
 File "requests\models", line 836, in content
 File "requests\models", line 765, in generate
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 807, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 428, in urlopen
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\YoutubeDL", line 3730, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\YoutubeDL", line 1502, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\YoutubeDL", line 1578, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 680, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 516, in _real_extract
   video = self._download_info(vod_id)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 381, in _download_info
   'Downloading stream metadata GraphQL')
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 158, in _download_gql
   return self._download_base_gql(video_id, ops, note)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 148, in _download_base_gql
   headers=headers, fatal=fatal)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 1034, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 1000, in download_handle
   data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 868, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 825, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [twitch:vod] 1708865802: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\twitch_downloader", line 115, in extract_info
 File "ytdl", line 436, in extract_info
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\YoutubeDL", line 1491, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\YoutubeDL", line 1520, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [twitch:vod] 1708865802: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 807, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 428, in urlopen
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\YoutubeDL", line 3730, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "extractor\twitch_downloader", line 55, in read
 File "utils", line 834, in __call__
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\twitch_downloader", line 142, in get
 File "extractor\twitch_downloader", line 121, in extract_info
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 381, in _download_info
   'Downloading stream metadata GraphQL')
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 158, in _download_gql
   return self._download_base_gql(video_id, ops, note)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\twitch", line 148, in _download_base_gql
   headers=headers, fatal=fatal)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 1034, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 1000, in download_handle
   data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 868, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI191122\ytdl_a0fdca13\yt_dlp\yt_dlp\extractor\common", line 825, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://www.twitch.tv/videos/1708865802  (43.3s)

downloader_v3 fail... p[72 / 92]
Traceback (most recent call last):
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1369, in getresponse
 File "http\client", line 310, in begin
 File "http\client", line 271, in _read_status
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 735, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 428, in _make_request
 File "urllib3\connectionpool", line 336, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 69, in run
 File "requests\sessions", line 555, in get
 File "downloader", line 230, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 677, in send
 File "requests\sessions", line 677, in <listcomp>
 File "requests\sessions", line 245, in resolve_redirects
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=15)

downloader_v3 fail... p[67 / 92]
Traceback (most recent call last):
 File "urllib3\response", line 436, in _error_catcher
 File "urllib3\response", line 518, in read
 File "http\client", line 461, in read
 File "http\client", line 505, in readinto
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\models", line 758, in generate
 File "urllib3\response", line 575, in stream
 File "urllib3\response", line 540, in read
 File "contextlib", line 130, in __exit__
 File "urllib3\response", line 441, in _error_catcher
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 78, in run
 File "requests\models", line 836, in content
 File "requests\models", line 765, in generate
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

downloader_v3 fail... p[74 / 92]
Traceback (most recent call last):
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1369, in getresponse
 File "http\client", line 310, in begin
 File "http\client", line 271, in _read_status
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 735, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 428, in _make_request
 File "urllib3\connectionpool", line 336, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 69, in run
 File "requests\sessions", line 555, in get
 File "downloader", line 230, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=15)

downloader_v3 fail... p[73 / 92]
Traceback (most recent call last):
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1369, in getresponse
 File "http\client", line 310, in begin
 File "http\client", line 271, in _read_status
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 735, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 428, in _make_request
 File "urllib3\connectionpool", line 336, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 69, in run
 File "requests\sessions", line 555, in get
 File "downloader", line 230, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 677, in send
 File "requests\sessions", line 677, in <listcomp>
 File "requests\sessions", line 245, in resolve_redirects
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=15)

downloader_v3 fail... p[13 / 64]
Traceback (most recent call last):
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1369, in getresponse
 File "http\client", line 310, in begin
 File "http\client", line 271, in _read_status
 File "socket", line 589, in readinto
 File "ssl", line 1071, in recv_into
 File "ssl", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 735, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 428, in _make_request
 File "urllib3\connectionpool", line 336, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 69, in run
 File "requests\sessions", line 555, in get
 File "downloader", line 230, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 677, in send
 File "requests\sessions", line 677, in <listcomp>
 File "requests\sessions", line 245, in resolve_redirects
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out. (read timeout=15)

[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1708865802
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1708865802: Downloading stream metadata GraphQL
'NoneType' object does not support item assignment
stop
Traceback (most recent call last):
 File "extractor\twitch_downloader", line 115, in extract_info
 File "ytdl", line 436, in extract_info
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\YoutubeDL", line 1491, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\YoutubeDL", line 1502, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\YoutubeDL", line 1578, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\extractor\common", line 680, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\extractor\twitch", line 516, in _real_extract
   video = self._download_info(vod_id)
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\extractor\twitch", line 384, in _download_info
   video['moments'] = traverse_obj(data, (1, 'data', 'video', 'moments', 'edges', ..., 'node'))
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "extractor\twitch_downloader", line 55, in read
 File "utils", line 834, in __call__
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\twitch_downloader", line 142, in get
 File "extractor\twitch_downloader", line 121, in extract_info
 File "C:\Users\hjsg1\AppData\Local\Temp\_MEI168362\ytdl_cfd800b2\yt_dlp\yt_dlp\extractor\twitch", line 384, in _download_info
   video['moments'] = traverse_obj(data, (1, 'data', 'video', 'moments', 'edges', ..., 'node'))
TypeError: 'NoneType' object does not support item assignment

Invalid: fail=True
EOT: https://www.twitch.tv/videos/1708865802  (3.1s)

위와 같은 에러가뜨면서 다운이 안되네요 ㅜㅜ

**Comment by KurtBestor** [comment]
구독자 전용인데 로그인 쿠키 넣으셨나요?
