### ISSUE TITLE
유튜브 실시간 스트리밍의 영상들은 다운로드 진행이 안됩니다.

### ISSUE THREAD

**Issue by eat-kiwi** [KurtBestor/Hitomi-Downloader#5679]
유튜브 내 동영상 탭으로 업로드가 된 영상들은 정상적으로 다운로드 진행이 가능하나
실시간 스트리밍 탭에 있는 영상들*(실시간 방송 중인 영상이 아닌 시작과 끝이 있는 완전한 영상)은 다운로드 진행이 되지 않습니다.

이 문제에 대한 해결 방법으로 이 곳에 배포 해주신 각종 beta 버전이나 preview 버전들을 통해 다운로드를 시도하였으나 그럼에도 불구하고 진행이 되지 않았습니다.

아래에 해당 이슈에 대한 작업 정보를 업로드 하겠습니다.

``` Invalid: [youtube] https://www.youtube.com/live/DyzISX6_pcI?feature=share

version: 3.8a (23-01-25 16:08:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / af3e93b085154d429bbc9a5174409a06
input: https://www.youtube.com/live/DyzISX6_pcI?feature=share
type: youtube
single: True
url: https://www.youtube.com/live/DyzISX6_pcI?feature=share
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1675128898.0960178 (23-01-31 01:34:58 UTC) - 7s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.06
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
https://www.youtube.com/live/DyzISX6_pcI?feature=share
stop
Traceback (most recent call last):
 File "utils", line 1276, in start
 File "utils", line 1352, in start_
 File "extractor\youtube_downloader", line 389, in read
 File "decorator", line 232, in fun
 File "constants", line 911, in wrapper
 File "constants", line 880, in wrapper
 File "extractor\youtube_downloader", line 456, in get_videos
NotImplementedError: https://www.youtube.com/live/DyzISX6_pcI?feature=share

Invalid: fail=True
EOT: https://www.youtube.com/live/DyzISX6_pcI?feature=share  (1.7s)
```

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by eat-kiwi** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

확인이 늦었습니다. 정상 작동 확인했습니다!
