### ISSUE TITLE
Invalid: [luscious]

### ISSUE THREAD

**Issue by Gogothe1** [KurtBestor/Hitomi-Downloader#5699]
I want to download an album but i can't because i have this issue. Is there a solution ?

Invalid: [luscious] https://www.luscious.net/albums/wasp-cosplay-gallery_316434/

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / fr_fr
order / group / uid: 0 / False / d3ad601383bb483cbc410241bcaffd60
input: https://www.luscious.net/albums/wasp-cosplay-gallery_316434/
type: luscious
single: False
url: https://www.luscious.net/albums/wasp-cosplay-gallery_316434/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1675887265.3054543 (23-02-08 20:14:25 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.06
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
403
stop
Traceback (most recent call last):
 File "downloader", line 397, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 430, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.luscious.net/graphql/nobatch/?operationName=AlbumListOwnPictures&query=+query+AlbumListOwnPictures%28%24input%3A+PictureListInput%21%29+%7B+picture+%7B+list%28input%3A+%24input%29+%7B+info+%7B+...FacetCollectionInfo+%7D+items+%7B+...PictureStandardWithoutAlbum+%7D+%7D+%7D+%7D+fragment+FacetCollectionInfo+on+FacetCollectionInfo+%7B+page+has_next_page+has_previous_page+total_items+total_pages+items_per_page+url_complete+%7D+fragment+PictureStandardWithoutAlbum+on+Picture+%7B+__typename+id+title+created+like_status+number_of_comments+number_of_favorites+status+width+height+resolution+aspect_ratio+url_to_original+url_to_video+is_animated+position+tags+%7B+category+text+url+%7D+permissions+url+thumbnails+%7B+width+height+size+url+%7D+%7D+&variables=%7B%22input%22%3A%7B%22filters%22%3A%5B%7B%22name%22%3A%22album_id%22%2C%22value%22%3A%22316434%22%7D%5D%2C%22display%22%3A%22position%22%2C%22page%22%3A1%7D%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "extractor\luscious_downloader", line 79, in read
 File "extractor\luscious_downloader", line 118, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\luscious_downloader", line 134, in get_imgs_p
 File "downloader", line 438, in read_html
Exception: 403

Invalid: fail=True
EOT: https://www.luscious.net/albums/wasp-cosplay-gallery_316434/  (100.8s)

**Comment by AriaArcadia** [comment]
I met up with the same problem and even likely error code

I wonder whether it is the problem with api.luscious.net
I don't know but guess
I set the cookies and proxy as well as goodbyeDPI
the version is hitomi_downloader_GUI_test, youtube/bilibili/hitomi works successfully

However I can't find any effective way to solve 403forbidden

**Comment by adultGHAN** [comment]
The API URL has changed.

old : https://api.luscious.net
new : https://members.luscious.net

thanks.

**Comment by JoGaTo** [comment]
Okay, but it's still giving me invalid shit even with downloading the dev tech version.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
