### ISSUE TITLE
히토미 몇몇 파일이 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by asfsdw** [KurtBestor/Hitomi-Downloader#5724]
Invalid: [hitomi] #-*- [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)

version: 3.8a (23-02-09 15:42:21 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 2 / False / 56bae472cd4c413291faa97de220eb07
input: [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)
type: hitomi
single: False
url: https://hitomi.la/galleries/2143862.html
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1676551790.2161102 (23-02-16 12:49:50 UTC) - 552s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.06
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 2143862

제목: Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편

작가: akatsuki myuuto

그룹: akatukiya

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: group, multi-work series, female:big breasts, female:harem, female:nakadashi, female:schoolgirl uniform, female:shimaidon, female:x-ray, male:glasses, male:sole male, male:teacher, male:virginity

언어: Korean

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Can not find hash2
stop
Traceback (most recent call last):
 File "hitomi_downloader", line 618, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1276, in start
 File "utils", line 1352, in start_
 File "hitomi_downloader", line 620, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

Invalid: fail=True
quality: 100%
EOT: #-*- [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)  (85.4s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Can not find hash2
stop
Traceback (most recent call last):
 File "hitomi_downloader", line 618, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1276, in start
 File "utils", line 1352, in start_
 File "hitomi_downloader", line 620, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

Invalid: fail=True
quality: 100%
EOT: #-*- [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)  (155.3s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Can not find hash2
stop
Traceback (most recent call last):
 File "hitomi_downloader", line 613, in read
 File "hitomi_downloader", line 450, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "hitomi_downloader", line 615, in read
 File "hitomi_downloader", line 450, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

Invalid: fail=True
quality: 100%
EOT: #-*- [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)  (124.4s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Can not find hash2
stop
Traceback (most recent call last):
 File "hitomi_downloader", line 613, in read
 File "hitomi_downloader", line 450, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "hitomi_downloader", line 615, in read
 File "hitomi_downloader", line 450, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

Invalid: fail=True
quality: 100%
EOT: #-*- [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)  (77.8s)

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:False)
Find in HK...
not found in HK
using custom cookies in find_ehen
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/2143862.html)
Find_ehen(id:2143862, ex:True)
Find in HK...
not found in HK
using custom cookies in find_ehen
Can not find hash2
stop
Traceback (most recent call last):
 File "hitomi_downloader", line 613, in read
 File "hitomi_downloader", line 450, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "hitomi_downloader", line 615, in read
 File "hitomi_downloader", line 450, in get_imgs
 File "extractor\ehen_downloader", line 187, in ehen_imgs
 File "extractor\ehen_downloader", line 157, in find_ehen
Exception: Can not find hash2

Invalid: fail=True
quality: 100%
EOT: #-*- [Akatsuki Myuuto] Nanaka no Rakuen 1 ~Inaka no Gakkou de Bishoujo Harem~ Mina de Koibito Gokko Hen | 나나카의 낙원 1 ~시골 학교에서 미소녀와 하렘 생활~ 다 같이 연인 놀이 편 (2143862)  (115.6s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5197
