### ISSUE TITLE
The latest version crashes on start

### ISSUE THREAD

**Issue by pedjas** [KurtBestor/Hitomi-Downloader#5727]
Cannot run the latest version. It crashes with this info:

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 211, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "downloader.py", line 327, in <module>
  File "downloader.py", line 183, in patch_session
  File "downloader.py", line 127, in __init__
  File "requests\adapters.py", line 129, in __init__
  File "downloader.py", line 143, in init_poolmanager
  File "downloader.py", line 132, in _ssl_context
  File "ssl.py", line 589, in create_default_context
  File "ssl.py", line 490, in load_default_certs
  File "ssl.py", line 482, in _load_windows_store_certs
ssl.SSLError: nested asn1 error (_ssl.c:4034)

**Comment by KurtBestor** [comment]
How about [this](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview)?

**Comment by pedjas** [comment]
> How about [this](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview)?

Now it runs fine. 

Antivirus screamed insanely on new compiled exe, but it finally allowed it to run, with bit of a help.

Nice app, by the way.
