### ISSUE TITLE
몇몇 자료들이 다운로드가 안되는거 같습니다

### ISSUE THREAD

**Issue by scdtony** [KurtBestor/Hitomi-Downloader#5729]
version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 93 / False / 4a4dc4243ec14dcdafa1ec3fe0a32e08
input: https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1
type: hitomi
single: False
url: https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1676641586.088897 (23-02-17 13:46:26 UTC) - 1068s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.02.17
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1)
Find_ehen(id:1139627, ex:False)
Find in HK...
Found in HK: 8c498c8bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1139627/8c498c8bf6    ---->    https://e-hentai.org/g/1139627/8c498c8bf6
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 567, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1139627/8c498c8bf6

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 577, in read
 File "hitomi_downloader", line 567, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1139627/8c498c8bf6

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1)
Find_ehen(id:1139627, ex:True)
Find in HK...
Found in HK: 8c498c8bf6
using custom cookies in find_ehen
#### https://exhentai.org/g/1139627/8c498c8bf6    ---->    https://exhentai.org/g/1139627/8c498c8bf6
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 567, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://exhentai.org/g/1139627/8c498c8bf6

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1)
Find_ehen(id:1139627, ex:False)
Find in HK...
Found in HK: 8c498c8bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1139627/8c498c8bf6    ---->    https://e-hentai.org/g/1139627/8c498c8bf6
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1)
Find_ehen(id:1139627, ex:True)
Find in HK...
Found in HK: 8c498c8bf6
using custom cookies in find_ehen
#### https://exhentai.org/g/1139627/8c498c8bf6    ---->    https://exhentai.org/g/1139627/8c498c8bf6
404 Client Error: Not Found for url: https://exhentai.org/g/1139627/8c498c8bf6
stop
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 613, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1139627/8c498c8bf6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "hitomi_downloader", line 615, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://exhentai.org/g/1139627/8c498c8bf6

Invalid: fail=True
quality: 100%
EOT: https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1  (19.3s)

get_imgs server: hitomi:la
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1)
Find_ehen(id:1139627, ex:False)
Find in HK...
Found in HK: 8c498c8bf6
using custom cookies in find_ehen
#### https://e-hentai.org/g/1139627/8c498c8bf6    ---->    https://e-hentai.org/g/1139627/8c498c8bf6
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1)
Find_ehen(id:1139627, ex:True)
Find in HK...
Found in HK: 8c498c8bf6
using custom cookies in find_ehen
#### https://exhentai.org/g/1139627/8c498c8bf6    ---->    https://exhentai.org/g/1139627/8c498c8bf6
404 Client Error: Not Found for url: https://exhentai.org/g/1139627/8c498c8bf6
stop
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 613, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1139627/8c498c8bf6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "hitomi_downloader", line 615, in read
 File "hitomi_downloader", line 453, in get_imgs
 File "extractor\ehen_downloader", line 208, in ehen_imgs
 File "downloader", line 518, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://exhentai.org/g/1139627/8c498c8bf6

Invalid: fail=True
quality: 100%
EOT: https://hitomi.la/doujinshi/mc-gakuen-nana-jigenme-%7C-mc%ED%95%99%EC%9B%90-7%EA%B5%90%EC%8B%9C-%ED%95%9C%EA%B5%AD%EC%96%B4-1139627.html#1  (19.7s)

이러는 것들 특징이 익헨사이트서는 내려갔는데 히토미서는 내려가진 안내려간 파일들이 이러는것 같습니다

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5197
