### ISSUE TITLE
단부루 Danbooru 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by glitteri** [KurtBestor/Hitomi-Downloader#5730]
오류메시지는 다음과 같습니다.
테스트버전 올려주신 거 확인하고 설치했는데도 안되고
no html 뿜으면서 안되는데 정작 해당 페이지 접속은 엣지에서 잘만 됩니다.

4분 57초 뒤 다시 시작: https://danbooru.donmai.us/?tags=irohara_mitabi

version: 3.8a (23-02-09 15:42:21 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / a1e7ead52c4c4858acd002b7b7cf24e6
input: https://danbooru.donmai.us/?tags=irohara_mitabi
type: danbooru
single: False
url: https://danbooru.donmai.us/?tags=irohara_mitabi
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1676657123.6756227 (23-02-17 18:05:23 UTC) - 13s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.02.17
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
https://danbooru.donmai.us/?tags=irohara_mitabi&page=1
403 Client Error: Forbidden for url: https://danbooru.donmai.us/?tags=irohara_mitabi&page=1
stop
Traceback (most recent call last):
 File "downloader", line 477, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\danbooru_downloader", line 67, in read
 File "extractor\danbooru_downloader", line 157, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 911, in wrapper
 File "constants", line 880, in wrapper
 File "extractor\danbooru_downloader", line 128, in read_soup
 File "downloader", line 421, in read_soup
 File "downloader", line 528, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/?tags=irohara_mitabi&page=1

Invalid: fail=True
EOT: https://danbooru.donmai.us/?tags=irohara_mitabi  (10.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by glitteri** [comment]
드디어 됩니다 감사합니다ㅠ
