### ISSUE TITLE
쿠키 사용하면 Err 메세지가 뜹니다 작동이 안됩니다.

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#5736]
오늘 쿠키 사용하면 Err 메세지가 뜹니다 작동이 안됩니다
사용하는 쿠키 Get cookies.txt 입니다 모든 사이트이  쿠키가 작동이 안됩니다.
![1865edc0076_mqbxlv](https://user-images.githubusercontent.com/47520785/220375162-0e89bd47-3a74-4aa9-8e99-39bc1ea8ca75.jpg)

자세한 정 보기
Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9385, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
http.cookiejar.LoadError: invalid Netscape format cookies file 'D:/download/HItomi Downloader 0.5/hitomi_downloader_GUI_test/루리웹01.txt': 'comicbook.com\tFALSE\t/gaming/news/final-fantasy-7-surprising-collaboration-powerwash-simulator-playstation-xbox-nintendo-switch\tTRUE\t1677737955\texco-uid\t6ucwadmqlka7ibfj\t24'

암튼 항상 감사합니다ㅠㅠb따봉

**Comment by geniussjt** [comment]
잘됩니다 정말 정말 감사합니다ㅠㅠb따봉

**Comment by fluidko** [comment]
> ![image](https://user-images.githubusercontent.com/22697167/220699504-6ea12cd8-1cbc-468f-8ac1-86712ea45bde.png) Get cookies.txt 팝업창에서 오른쪽 위에 있는 설정으로 들어가서 'Include Cookie Size Values'를 체크 해제해 주면 정상 작동합니다.

혹시 지금 보여주신 화면을 어디 들어가면 볼 수 있나요?

**Comment by geniussjt** [comment]
> 
![1](https://user-images.githubusercontent.com/47520785/220928113-6d10de3e-a41c-42a9-b4f4-5c0706f7212b.jpg)

![2](https://user-images.githubusercontent.com/47520785/220928153-77db06d7-a599-457c-b6ea-3f2d70307ba3.jpg)

사진으로 하면 사진1에 1번 2번하면 2번 사진 화면으로 볼 수 있습니다^^

**Comment by KurtBestor** [comment]
해당 확장프로그램이 업데이트를 이상하게 했네요

**Comment by lumiamilk** [comment]
in the chrome web store, some people found the Get cookies.txt taking other people's cookies, is it true ?
anyway, I have deleted the Get cookies.txt and use other extension for instead.

**Comment by lumiamilk** [comment]
here is the discussion:
https://old.reddit.com/r/youtubedl/comments/10ar7o7/if_youve_been_using_the_get_cookiestxt_chrome/
