### ISSUE TITLE
저도 쿠기적용시 Err 뜹니다.

### ISSUE THREAD

**Issue by sb2941** [KurtBestor/Hitomi-Downloader#5738]
![화면 캡처 2023-02-22 143331](https://user-images.githubusercontent.com/75178740/220531990-d45fa72e-0941-4c7d-9182-6196a62ca166.png)

Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9557, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
http.cookiejar.LoadError: invalid Netscape format cookies file 'E:/내 작업물/컴퓨터 관련/필수 프로그램/hitomi_downloader_GUI_test_v20230210/Supported Sites/ccc3a0ec-8900-4bb4-99d0-b931bc7de2d8.txt': '.channel.io\tTRUE\t/front/v5/elastic/plugins/75671354-8e5e-400b-a11f-34a8be826ce2\tTRUE\t1709050197\tx-veil-id\t5c5b3570-b3af-4335-91cb-b736ee582886\t45'

단, 이전에 적용해놨던 쿠키를 미리 내보내기 했었던 쿠키 파일은 잘 불러와 집니다.

[쿠키_정보-2.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/10800375/_.-2.txt)

**Comment by depth221** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/5736#issuecomment-1440418617
저는 이렇게 해결했습니다.
