### ISSUE TITLE
히토미 데이터 다운로드가 안됩니다ㅜ

### ISSUE THREAD

**Issue by cul9** [KurtBestor/Hitomi-Downloader#5740]
Traceback (most recent call last):
  File "downloader", line 485, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 641, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 518, in read_html
  File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://kurtpyanywhere.com/h_data

요렇게 떠용

**Comment by cul9** [comment]
dpi 우회를 켜니까 되네요 죄송합니다..
