### ISSUE TITLE
cookies load doesnt work

### ISSUE THREAD

**Issue by cope1302** [KurtBestor/Hitomi-Downloader#5743]
```
Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9385, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
http.cookiejar.LoadError: invalid Netscape format cookies file 'C:/hd/exhentai.org_cookies.txt': '.exhentai.org\tTRUE\t/\tFALSE\t1708702176\tipb_member_id\t1252524\t32'
```

cookie file was generated by 'Get cookies.txt' extension for chrome

**Comment by hwnnhji** [comment]
me too. it doesn't work now

Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9385, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
http.cookiejar.LoadError: invalid Netscape format cookies file 'C:/Users/MSI/Downloads/all_cookies.txt': 'kr.louisvuitton.com\tFALSE\t/kor-kr/products/multiple-wallet-damier-other-nvprod3580048v\tTRUE\t\tSGID\t.springboot11-prd\t21'

**Comment by depth221** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/5736#issuecomment-1440418617

In the setting of the Get Cookie.txt, disable **Include Cookie Size Values**, and it works.
