### ISSUE TITLE
쿠키 설정하려는데 Err만 뜨면서 오류가 나네요 

### ISSUE THREAD

**Issue by gopr03** [KurtBestor/Hitomi-Downloader#5750]
Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9385, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
http.cookiejar.LoadError: invalid Netscape format cookies file 'C:/Users/H501/Downloads/0393843d-d855-4d2b-b6bc-f723e59b3b3c.txt': '.uefa.com\tTRUE\t/uefachampionsleague/video/027e-175e92cd99d9-706bb2d0c9a2-1000--highlights-liverpool-2-5-real-madrid\tFALSE\t\t_schn\t_bkpjx1\t12'

**Comment by jushi-xianyu** [comment]
I had the same problem.
I used Chrome's ''Get cookies.txt''.
And I cleared the cookie and reloaded the web page to get the ''cookie.txt'' is also the same error.


Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9385, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
http.cookiejar.LoadError: invalid Netscape format cookies file 'B:/hitomi_downloader_GUI/bilibili.com_cookies.txt': 'api.vc.bilibili.com\tFALSE\t/dynamic_svr/v1/dynamic_svr\tFALSE\t\tl\tv\t2'

**Comment by jominhyun** [comment]
저도 같은 증상입니다

**Comment by cocokakao** [comment]
Me too

**Comment by whory13** [comment]
same to me
