### ISSUE TITLE
nozomi.la 영상 포맷 파일들이 다운로드가 안됩니다..

### ISSUE THREAD

**Issue by fdsa1538** [KurtBestor/Hitomi-Downloader#5754]
version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 62e31bcc2fc54b2f989c01a26dd198f9
input: https://nozomi.la/search.html?q=najar
type: nozomi
single: False
url: https://nozomi.la/search.html?q=najar
dir: hitomi_downloaded_nozomi\najar
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.02.17
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_nozomi\najar\31803768.webm
[0002] hitomi_downloaded_nozomi\najar\31794293.gif
[0003] hitomi_downloaded_nozomi\najar\31767655.webm
[0004] hitomi_downloaded_nozomi\najar\31675742.webm
[0005] hitomi_downloaded_nozomi\najar\31675733.gif
[0006] hitomi_downloaded_nozomi\najar\31569979.webm
[0007] hitomi_downloaded_nozomi\najar\31564366.gif
[0008] hitomi_downloaded_nozomi\najar\31459184.webm
[0009] hitomi_downloaded_nozomi\najar\31435232.webm
[0010] hitomi_downloaded_nozomi\najar\31401740.webm

(gif 확장자는 다운이 되는데 webm이나 mp4 등등으로 되어있는 것들은 빨간색이 뜹니다.)

[URLs]
[0001] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/d/c2/b833e151447e3127de7655322da4b2f2fce98325ae442334e49d93efbfae6c2d.webm
[0002] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/a/43/2137607a517b4bc9b53e6075442a1037b12931ba6279f9ac8099b45d6cf8143a.gif
[0003] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/c/19/d649f972b33fc123f201a42c9cbc2ce74515ec4c00f1fc1a944c1bdbaad4519c.webm
[0004] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/3/8c/a9c8bd6f13afab98b373908b8eb71358d26bddeb45469c7af8a1304c8830a8c3.webm
[0005] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/8/b7/695e5fbf4d28d88b1deb7e41be955c86fdefc58389da2d3c2fe3336cc9918b78.gif
[0006] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/2/30/6a069839326f15dc15c2362bfc4e9e6f8f04cdf74f9e94c90fbe74607636a302.webm
[0007] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/a/4c/d6aedee7e7c5be2de6b154c4ee80f7a4f72d169cd1855fcfd66254f35c34f4ca.gif
[0008] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/f/92/b6521407603ca1e53aa06682a7d4c5b17d09077c5e75fc22581e43a14fd6192f.webm
[0009] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/3/8e/65f6440e5da65edc7de0fb0bc5cd85fd2d5f4e0dbaffc2aa1484012f048d88e3.webm
[0010] LazyUrl(https://nozomi.la/search.html?q=najar)    --->    https://i.nozomi.la/e/32/3a3253de6a0a729ed2912880a50dfb2a18eaaafb8a618c7b52f506d40afa832e.webm

(파일이 영상포맷이면 url 맨 앞이 i가 아니라 v가 되어서 그런 것 같습니다.. 근데 프로그래밍 할 줄 몰라서..)

[Messages]
najar: 59
ids: 59

Fail_404 : 
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

바쁘시겠지만 언젠가 수정되길 기원합니다.. 
ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fdsa1538** [comment]
엄청 잘됩니다!! 🥰

**Comment by fdsa1538** [comment]
이 사이트, gif들은 앞글자 i였다가 최근에 g로 또 바꾼 것 같아요 ㅠㅠ
