### ISSUE TITLE
bilibili의 1080P 비디오를 다운로드할 수 없습니다.

### ISSUE THREAD

**Issue by netlovehf** [KurtBestor/Hitomi-Downloader#5760]
bilibili의 1080P 비디오를 다운로드할 수 없습니다.

**Comment by netlovehf** [comment]
Traceback (most recent call last):
  File "http\cookiejar", line 2038, in _really_load
ValueError: too many values to unpack (expected 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9385, in loadCookies
  File "cooker", line 84, in load
  File "cooker", line 55, in load
  File "http\cookiejar", line 2078, in _really_load
