### ISSUE TITLE
iwara 사이트의 리뉴얼된 이후로 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by ddegi99** [KurtBestor/Hitomi-Downloader#5794]
내용은 제목 그대로 입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by YTOAA** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Invalid: [iwara] https://www.iwara.tv/profile/user954919

version: 3.8a (23-04-08 09:56:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 1 / False / 31213a61387f41f1bcdccdfde7feb995
input: https://www.iwara.tv/profile/user954919
type: iwara
single: True
url: https://www.iwara.tv/profile/user954919
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1680957110.2216036 (23-04-08 12:31:50 UTC) - 29s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/profile/user954919  (16.7s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/profile/user954919  (14.5s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/profile/user954919  (9.0s)

**Comment by KurtBestor** [comment]
아직 단일 포스트만 지원해요

**Comment by YTOAA** [comment]
> 아직 단일 포스트만 지원해요

아 단일 포스터 다운로드 확인했습니다. 그러면 분류를 수동으로 해야겠네요

**Comment by KurtBestor** [comment]
프로필도 받아지게 했어요
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by YTOAA** [comment]
> 프로필도 받아지게 했어요 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

몇몇 iwara 링크는 정상적이지 않네요
다른분들 말씀처럼 로그인이 되어있으면 정상적으로 보이는데
아닐때는 페이지가 없는것처럼 404를 표시해서
혹시나 해서 쿠키를 줘봤지만 안되네요
문제가 되는 iwara 링크입니다
https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise

**Comment by charlificate** [comment]
아무래도 loli 나 shota 태그가 달려있거나 private로 되어있는 영상들은 쿠키를 주거나 인 앱 브라우저로 로그인을 해도 다운이 안되더라고요. 로그인 하지 않으면 안보이는것과 관련이 있는 듯 한데 고쳐주실 수 있으면 부탁드립니다.

**Comment by ddegi99** [comment]
아직은 안되는거 같아요. 계속 읽는 중... 이렇게 되네요

2023년 4월 22일 (토) 오후 5:59, charlificate ***@***.***>님이 작성:

**Comment by charlificate** [comment]
또 User 프로필에서 다운받을 때, 처음 32개 링크만 다운받을 수 있고 그 이후는 다운이 안됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by YTOAA** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

각각의 문제되는 개별 포스터를 다운로드하면 제대로 다운로드 됩니다 다만
프로필로 다운로드 할때는 여전히 안되는거 같습니다.

**Comment by KurtBestor** [comment]
@ytoaa 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/6031#issuecomment-2008927904
