### ISSUE TITLE
카카페 다운이 안되네요

### ISSUE THREAD

**Issue by fgkkgoe** [KurtBestor/Hitomi-Downloader#5806]
며칠 전까지만 해도 잘되던게 갑자기 안되네요.

Invalid: [kakaopage] https://page.kakao.com/content/48206197

version: 3.8a (23-03-11 23:45:57 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 16d3b0389b654922bb34ae1524a4eb43
input: https://page.kakao.com/content/48206197
type: kakaopage
single: False
url: https://page.kakao.com/content/48206197
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [324]
time: 1679297406.1375377 (23-03-20 07:30:06 UTC) - 313s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
마검왕 325화 0
Cannot query field "freeChangeDate" on type "Single".
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\kakaopage_downloader", line 61, in read
 File "extractor\kakaopage_downloader", line 616, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/content/48206197  (27.9s)

**Comment by ys7726** [comment]
안된지 몇주정도되었습니다ㅜㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fgkkgoe** [comment]
감사합니다! 이제 잘 되네요
