### ISSUE TITLE
크롤러서버 점검요망 오류 내용 포함

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader#5814]
{'debug': False, 'disable-gpu': True, 'no-browser': False, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': False, 'experimental': False, 'auto-scale': False, 'scale': 1, 'round-menu': True}
./sub\requests\__init__.py:104: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (5.1.0)/charset_normalizer (2.1.1) doesn't match a supported version!
  RequestsDependencyWarning)
Hitomi Downloader v3.7h
<class 'str'> 42686
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.60 Safari/537.36
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.118 Safari/537.36
load ids...
SELECT key FROM infos ORDER BY key DESC
SELECT key FROM infos_del ORDER BY key DESC
ids loaded
Traceback (most recent call last):
  File "C:\hitomi_server\crawler_bot.py", line 211, in <module>
    ids_cur = get_ids()
  File "C:\hitomi_server\crawler_bot.py", line 141, in get_ids
    id = crop[0]*256*256*256 + crop[1]*256*256 + crop[2]*256 + crop[3]
IndexError: index out of range

**Comment by KurtBestor** [comment]
고쳤어요

**Comment by ys32** [comment]
감사합니다
