### ISSUE TITLE
iwara 다운이 막히는데 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by rororoororo** [KurtBestor/Hitomi-Downloader#5824]
Invalid: [iwara] https://www.iwara.tv/video/k2ayoueezfkx6gvq/defeat-of-irybelda

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / ec31caaef7e048c38a0ba3e7a55b8b2c
input: https://www.iwara.tv/video/k2ayoueezfkx6gvq/defeat-of-irybelda
type: iwara
single: True
url: https://www.iwara.tv/video/k2ayoueezfkx6gvq/defeat-of-irybelda
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1679674486.487376 (23-03-24 16:14:46 UTC) - 795s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'parent'
stop
Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "extractor\iwara_downloader", line 99, in read
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\iwara_downloader", line 171, in get_files
AttributeError: 'NoneType' object has no attribute 'parent'

Invalid: fail=True
quality: 100%
EOT: https://www.iwara.tv/video/k2ayoueezfkx6gvq/defeat-of-irybelda  (1.7s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5794
