### ISSUE TITLE
Nozomi.la 다운로드 시도시에 401 Authorization Required 뜨면서 다운이 안됩니다.

### ISSUE THREAD

**Issue by nagisachan74** [KurtBestor/Hitomi-Downloader#5829]
[0051] LazyUrl(https://nozomi.la/search.html?q=pixiv_id_87293355)    --->    https://i.nozomi.la/8/b7/a7fa15b36e340b277ca55325af3a90156103496cc832013aaa54ddab3209ab78.png
[0052] LazyUrl(https://nozomi.la/search.html?q=pixiv_id_87293355)    --->    https://i.nozomi.la/f/76/010b1f42abde6dd6e3b8974eccec09acc678faf0fbc13871f7b91e9de5f0876f.png
[0053] LazyUrl(https://nozomi.la/search.html?q=pixiv_id_87293355)    --->    https://i.nozomi.la/3/22/b619320ea96171343becd81b34b5cb9e396860354ea8a0997bca98fc35601223.png

[Messages]
pixiv_id_87293355: 36
ids: 36

Fail : \\?\D:\자료2\hitomi_downloader_GUI_test\hitomi_downloaded_nozomi\pixiv_id_87293355\31992024.png
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: 401 Authorization Required

Fail : \\?\D:\자료2\hitomi_downloader_GUI_test\hitomi_downloaded_nozomi\pixiv_id_87293355\31891365.png
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: 401 Authorization Required

보아하니 lazyurl에서 다운로드 주소를 i.nozomi.la 주소로 인식해서 그런걸로 보입니다..

현재 해당 주소로 접속하려하면 아이디와 비밀번호를 요구하는 상황입니다.

w.nozomi.la로 연결되게끔 하는 방법이 없을까요??

**Comment by ddw1345** [comment]
webp로 바뀌면서 화질도 열화됐네요
서버 부담 줄이려고 원본 이미지 url을 막아놓은듯 하네요

**Comment by fdsa1538** [comment]
> webp로 바뀌면서 화질도 열화됐네요 서버 부담 줄이려고 원본 이미지 url을 막아놓은듯 하네요

화질이 열화됐나요? 그냥 webp로 바꾼 것 같은데.. F12 눌러서 보니까 사이트에 보여주는 것도 w로 시작하는 링크로 쏴주던데요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/5754
