### ISSUE TITLE
내장 goodbyedpi 실행 과정에서 error 22가 뜹니다.

### ISSUE THREAD

**Issue by Weltgeschichte** [KurtBestor/Hitomi-Downloader#5830]
Failed to run GoodbyeDPI

Traceback (most recent call last): 
File "goodbye_dpi", line 86, in run 
File "goodbye_dpi", line 185, in run 
File "goodbye_dpi", line 114, in load
File "zipfile", line 1240, in __init_

OSError: [Errno 22] Invalid argument: 'C:\\Users\\SEOKMI~1\\AppData\Local\\Temp\\_MEI247802\ \goodbyedpi.zip'

이렇게 뜨고, goodbyedpi가 실행되지 않습니다.

**Comment by Weltgeschichte** [comment]
찾아봤는데 아래 트로이 목마 윈도우 디펜더 관련해서 나는 오류인것 같습니다. 디펜더가 goodbyedpi.zip를 트로이로 검진해서 삭제해서 다운로더에서 goodbyedpi.zip를 찾을 수 없기 때문에 생기는 오류 같네요

**Comment by movomo** [comment]
디펜더에서 goodbyedpi 실행 허용하자 정상적으로 실행되었습니다.
