### ISSUE TITLE
케모노 파티 플러그인에 추가했는데 에러나네요 어떻게하는건가요?

### ISSUE THREAD

**Issue by ys7726** [KurtBestor/Hitomi-Downloader#5843]
![image](https://user-images.githubusercontent.com/69583055/229146423-5494f353-6285-4e20-b5c4-a5feb16aa262.png)

Invalid: [kemono.party] https://kemono.party/fanbox/user/49494721

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 7820 / False / fe13a88a1d634565b80c113174563ca0
input: https://kemono.party/fanbox/user/49494721
type: kemono.party
single: False
url: https://kemono.party/fanbox/user/49494721
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1680272244.140172 (23-03-31 14:17:24 UTC) - 73s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Not a post
stop
Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "dynamic_module_0", line 42, in read
 File "dynamic_module_0", line 59, in read_info
NotImplementedError: Not a post

Invalid: fail=True
EOT: https://kemono.party/fanbox/user/49494721  (10.9s)

https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins
사이트 플러그인의 케모노 파티 다운로드를 히토미 다운로더 플러그인에 추가했는데 인발리드 에러나네요
어떻게 사용하는건지 사용법을 봐도 모르겠습니다 ㅜㅜ

**Comment by rickmiron** [comment]
![rty](https://user-images.githubusercontent.com/99231649/229260674-fc7f73f7-4bf8-4709-a798-b4736c966ffe.png)

**Comment by ys7726** [comment]
> ![rty](https://user-images.githubusercontent.com/99231649/229260674-fc7f73f7-4bf8-4709-a798-b4736c966ffe.png)

그래도 안되네요 ㅜㅜ

**Comment by YTOAA** [comment]
kemono dl , gallery dl 쓰는게 훨 정신건강에 이로울 겁니다.

**Comment by rickmiron** [comment]
스크립트는 user(https://kemono.party/fanbox/user/49494721)가 아닌 post(https://kemono.party/fanbox/user/49494721/post/5615171)에서 작동합니다.

**Comment by rickmiron** [comment]
브라우저에서 이 스크립트를 사용하여 각 사용자의 게시물 링크를 얻을 수 있습니다.
사용 방법은 먼저 사용자의 웹 페이지로 이동하여 Ctrl+Shift+C 또는 F12를 눌러 측면 창을 열고 해당 창의 콘솔 탭에 들어가 코드를 붙여넣고 ENTER를 누르는 것입니다.

    const elementos = document.getElementsByClassName('card-list__items')[0].getElementsByTagName("a");
    const galerias = [];

    for (let i = 0; i < elementos.length; i++) {
        galerias.push(elementos[i].href);
      }

    let url = document.querySelector('.next')?.href;

    async function traeGalerias() {
      for (let j = 0; j < 5 && url; ++j) {
        const response = await fetch(url);
        const html = await response.text();
        const pagina = (new DOMParser()).parseFromString(html, 'text/html');
        const elementos = pagina.getElementsByClassName('card-list__items')[0].getElementsByTagName("a");
        
        for (let i = 0; i < elementos.length; i++) {
          galerias.push(elementos[i].href);
        }
        
        console.log("pag", j + 2);
        url = pagina.querySelector('.next')?.href;
      }
      mostrarGaleria();
    }

    function mostrarGaleria() {
      document.head.remove();
      document.body.innerHTML = galerias.join("<"+"br>");
      document.querySelector('script').remove();
    }

    if (url) {
        traeGalerias();
    } else {
        mostrarGaleria();
    }

**Comment by ushijimalove** [comment]
일괄 다운 안되고 게시물 하나씩만 됩니다 전체 다운로드 할려면 다른거 쓰셔야 됩니다

**Comment by ys7726** [comment]
> kemono dl

개별로 받아야하군요 
포스트 링크쓰니 그나마 일괄 다운이 되는데 그래도 너무 불편하네요 ㅜㅜ

**Comment by fade-out-0770** [comment]
> 브라우저에서 이 스크립트를 사용하여 각 USER의 POST 링크를 가져올 수 있습니다. 사용 방법은 먼저 웹 페이지로 이동하여 Ctrl+Shift+C 또는 F12를 눌러 측면 창을 열고 해당 창의 콘솔 탭에 들어가 코드를 붙여넣고 ENTER를 누르는 것입니다.
> 
> ```
> const elementos = document.querySelector('.card-list__items').getElementsByTagName("a");
> const galerias = [];
> 
> for (let i = 0; i < elementos.length; i++) {
>     galerias.push(elementos[i].href);
>   }
> 
> let url = document.querySelector('.next')?.href;
> 
> async function traeGalerias() {
>   for (let j = 0; j < 30 && url; ++j) {
>     const response = await fetch(url);
>     const html = await response.text();
>     const pagina = (new DOMParser()).parseFromString(html, 'text/html');
>     const elementos = pagina.querySelector('.card-list__items').getElementsByTagName("a");
>     
>     for (let i = 0; i < elementos.length; i++) {
>       galerias.push(elementos[i].href);
>     }
>     
>     console.log("pag", j + 2);
>     url = pagina.querySelector('.next')?.href;
>   }
>   mostrarGaleria();
> }
> 
> function mostrarGaleria() {
>   document.head.remove();
>   document.body.innerHTML = galerias.join("<"+"br>");
>   document.querySelector('script').remove();
> }
> 
> if (url) {
>     traeGalerias();
> } else {
>     mostrarGaleria();
> }
> ```

감사합니다 덕분에 엄청 편하게 받을수있네요.
