### ISSUE TITLE
Unable to download Twitter link.

### ISSUE THREAD

**Issue by murazi** [KurtBestor/Hitomi-Downloader#5850]
[Messages]
format: None
type: single
401 Unauthorized (Could not authenticate you)
stop
Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "extractor\twitter_downloader", line 96, in read
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\twitter_downloader", line 992, in get_artist_username
 File "extractor\twitter_downloader", line 333, in tweet
 File "extractor\twitter_downloader", line 397, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 301, in _call
Exception: 401 Unauthorized (Could not authenticate you)

Invalid: fail=True
---
hitomi-downloader
v3.8a

**Comment by Ash-627** [comment]
Me too
