### ISSUE TITLE
iwara 사이트 개편후 다운로드 불가

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader#5859]
사이트 주소도 바뀌었고 ui가 전체적으로 개편되었습니다.
이에 다음 테스트버전에 대응 패치 가능하신지..?

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5794

**Comment by YTOAA** [comment]
> Duplicate of #5794

Invalid: [iwara] https://www.iwara.tv/profile/user954919

version: 3.8a (23-04-08 09:56:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 1 / False / 31213a61387f41f1bcdccdfde7feb995
input: https://www.iwara.tv/profile/user954919
type: iwara
single: True
url: https://www.iwara.tv/profile/user954919
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1680957110.2216036 (23-04-08 12:31:50 UTC) - 29s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/profile/user954919  (16.7s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/profile/user954919  (14.5s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/profile/user954919  (9.0s)
