### ISSUE TITLE
다운 에러가 뜹니다. 도움 좀 부탁드리겠습니다.

### ISSUE THREAD

**Issue by Friedesama** [KurtBestor/Hitomi-Downloader#5860]
안녕하세요. 개발자님의 노고에 감사드립니다.

다름이 아니고 갑자기 히토미, kissjav가 다운이 되질 않는데, 혹시 해결 방법 좀 알려주실 수 있나요??

<히토미 다운시>

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / ea8b71177afc4319b4b14dabb011a6a9
input: https://hitomi.la/doujinshi/dia-s-story-%E6%97%A5%E6%9C%AC%E8%AA%9E-2517197.html#1
type: hitomi
single: False
url: https://hitomi.la/doujinshi/dia-s-story-%E6%97%A5%E6%9C%AC%E8%AA%9E-2517197.html#1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1680931449.39167 (23-04-08 05:24:09 UTC) - 219s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 97, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

<kissjav 다운시>

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / ee6e39f7ab114d0bb7780f4d95810fae
input: https://kissjav.com/247868/%EC%9D%B8%ED%84%B0%EB%84%B7-%EC%95%A8%EB%B2%94-%ED%95%B4%EB%8F%85-37/#close
type: kissjav
single: True
url: https://kissjav.com/247868/%EC%9D%B8%ED%84%B0%EB%84%B7-%EC%95%A8%EB%B2%94-%ED%95%B4%EB%8F%85-37/#close
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1680931880.8126118 (23-04-08 05:31:20 UTC) - 8s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "downloader", line 467, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 97, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

**Comment by STR-HK** [comment]
참고해보시겠어요?: https://github.com/KurtBestor/Hitomi-Downloader/issues/2237
