### ISSUE TITLE
iwara 의 일부 동영상에서 다운로드가 되지 않습니다. (test 버전 사용)

### ISSUE THREAD

**Issue by lakals** [KurtBestor/Hitomi-Downloader#5869]
항상 감사합니다.
새로 업로드해 주신 test 버전을 사용하여 테스트 해 보았는데, 일부 동영상은 다운로드 되지만 일부 동영상은 다운로드 되지 않는 이슈를 확인했습니다.

두 가지 형태의 실패 메시지를 확인했고, 예시를 첨부합니다.
확인해주시면 감사하겠습니다.

# case 1

https://www.iwara.tv/video/b9tElmyKrvTb1P/genshin-impacthurly-burly4kmmdcamera-dl

[iwara] Embeded: https://youtu.be/IU2wifdcKc4

version: 3.8a (23-04-08 09:56:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 22 / False / 86f89cd456a3487b8f01bf0c19da58a8
input: https://www.iwara.tv/video/b9tElmyKrvTb1P/genshin-impacthurly-burly4kmmdcamera-dl
type: iwara
single: True
url: https://www.iwara.tv/video/b9tElmyKrvTb1P/genshin-impacthurly-burly4kmmdcamera-dl
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1681057570.3232596 (23-04-09 16:26:10 UTC) - 540s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
[iwara] Embeded: https://youtu.be/IU2wifdcKc4
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 69, in get_info
errors.Invalid: [iwara] Embeded: https://youtu.be/IU2wifdcKc4

Invalid: fail=False
EOT: https://www.iwara.tv/video/b9tElmyKrvTb1P/genshin-impacthurly-burly4kmmdcamera-dl  (23.6s)

[iwara] Embeded: https://youtu.be/IU2wifdcKc4
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 69, in get_info
errors.Invalid: [iwara] Embeded: https://youtu.be/IU2wifdcKc4

Invalid: fail=False
EOT: https://www.iwara.tv/video/b9tElmyKrvTb1P/genshin-impacthurly-burly4kmmdcamera-dl  (24.0s)

# case 2

https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise

1분 6초 뒤 다시 시작: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise

version: 3.8a (23-04-08 09:56:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 20 / False / 99d4d4ad3cef4b22a3f0b12f3c3acfa6
input: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise
type: iwara
single: True
url: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1681057901.7765658 (23-04-09 16:31:41 UTC) - 247s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise  (29.8s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise  (15.5s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise  (30.2s)

'NoneType' object has no attribute 'find'
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 59, in get_info
AttributeError: 'NoneType' object has no attribute 'find'

Invalid: fail=True
EOT: https://www.iwara.tv/video/4qt8YmjqBByhoG/sexercise  (12.3s)

**Comment by YTOAA** [comment]
두 iwara 링크 모두 지금 정상적이지 않네요

**Comment by lakals** [comment]
> 두 iwara 링크 모두 지금 정상적이지 않네요

둘다 정상 동작합니다.
개편 후에 로그인하지 않은 유저에게 404를 띄우는 경우가 있는데, 그 이유인지는 모르겠네요.
