### ISSUE TITLE
픽시브 자꾸 no html 오류가 뜹니다

### ISSUE THREAD

**Issue by ksaeil2001** [KurtBestor/Hitomi-Downloader#5881]
Invalid: [pixiv] https://www.pixiv.net/users/7314141

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: -3341 / False / 58bbfe2c186d404fb8ac8c85f99a0f3b
input: https://www.pixiv.net/users/7314141
type: pixiv
single: False
url: https://www.pixiv.net/users/7314141
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1681557474.032306 (23-04-15 11:17:54 UTC) - 525s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (299.2s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (299.0s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (299.7s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (199.7s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (199.8s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (199.6s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (199.6s)

No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1245, in start
 File "extractor\pixiv_downloader", line 40, in init
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/users/7314141  (298.9s)
이렇게 끕니다

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 네트워크 - 내장 웹브라우저 - 보기` 누르고 해당 페이지 들어가면 어떻게 뜨나요?

**Comment by Dalgut** [comment]
저도 같은 증상이네요 브라우저를 크롬,파이어폭스 둘다 써보고 재설치도 해본상태인데 동일합니다.
내장브라우저에서 보기를누르면 로딩만 계속진행하다 about blank라고 표시되는군요
