### ISSUE TITLE
쿠키 이외에 로그인 등을 제공할 방법이 있을까요?

### ISSUE THREAD

**Issue by lakals** [KurtBestor/Hitomi-Downloader#5895]
iwara 개편 후, 로그인 전/후에 상당한 차이를 보이게 변경되었습니다.
짧게 요약하면, **로그인 해야 영상페이지가 보이고**, **쿠키로는 로그인이 안되는 상황** 입니다.

(버그인지 의도인지는 모르겠지만) 로그인하지 않은 경우, 적지 않은 확률로 영상 페이지에서 404 not found 를 띄웁니다.

로그인 상태를 유지할 필요가 있는데, 로그인 유지에 쿠키를 사용하지 않는지 쿠키 파일을 넣어도 로그인 상태가 되지 않습니다.
내장 웹브라우저를 열어서 직접 로그인해보긴 했는데, 그런 식으로는 세션이 유지되지 않네요 ㅠㅠ
매번 셀레니움 드라이버를 새로 만드시는 건가... ㅠㅠ

방법이 있을까요?

404가 떴을 때 나타나는 에러 로그는 다음과 같습니다.

4분 8초 뒤 다시 시작: https://www.iwara.tv/video/sNWDHr1TETEUFv

version: 3.8a (23-04-08 09:56:18 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 0 / False / fbf73d9e1b9a4c39af85bcd73475ae63
input: https://www.iwara.tv/video/sNWDHr1TETEUFv
type: iwara
single: True
url: https://www.iwara.tv/video/sNWDHr1TETEUFv
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1682029008.1920717 (23-04-20 22:16:48 UTC) - 260s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
no source
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 90, in get_info
Exception: no source

Invalid: fail=True
EOT: https://www.iwara.tv/video/sNWDHr1TETEUFv  (10.2s)

no source
stop
Traceback (most recent call last):
 File "utils", line 1280, in start
 File "utils", line 1356, in start_
 File "extractor\iwara_downloader", line 30, in read
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\iwara_downloader", line 90, in get_info
Exception: no source

Invalid: fail=True
EOT: https://www.iwara.tv/video/sNWDHr1TETEUFv  (21.0s)

**Comment by charlificate** [comment]
아무래도 loli 나 shota 태그가 달려있거나 private로 되어있는 영상들은 쿠키를 주거나 인 앱 브라우저로 로그인을 해도 다운이 안되더라고요. 로그인 하지 않으면 안보이는것과 관련이 있는 듯 합니다.
