### ISSUE TITLE
뉴토끼 다운로드가 안됩니다 ㅠㅠ

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#5898]
Browser required; Use --safemode

이런 문구가 뜨면서 다운이 안되네요 ㅠㅠ

작업정보 내용은 이렇습니다

Browser required; Use --safemode
https://newtoki286.com/webtoon/574870/%EC%83%88%EC%97%84%EB%A7%88%EC%9D%98-%EC%B9%9C%EA%B5%AC%EB%93%A4

version: 3.8a (23-04-21 14:53:44 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 5d1a95ed24d245588b0dba3f6c5dc61a
input: https://newtoki286.com/webtoon/574870/%EC%83%88%EC%97%84%EB%A7%88%EC%9D%98-%EC%B9%9C%EA%B5%AC%EB%93%A4
type: manatoki
single: False
url: https://newtoki286.com/webtoon/574870/%EC%83%88%EC%97%84%EB%A7%88%EC%9D%98-%EC%B9%9C%EA%B5%AC%EB%93%A4
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1682163359.3068957 (23-04-22 11:35:59 UTC) - 7s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

Path: C:\Users\정지훈\AppData\Local\Temp\_MEI113442
Invalid characters: 정지훈

stop
Traceback (most recent call last):
 File "utils", line 1265, in start
 File "decorator", line 232, in fun
 File "constants", line 912, in wrapper
 File "constants", line 881, in wrapper
 File "extractor\manatoki_downloader", line 56, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 141, in get_soup
 File "clf2", line 116, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki286.com/webtoon/574870/%EC%83%88%EC%97%84%EB%A7%88%EC%9D%98-%EC%B9%9C%EA%B5%AC%EB%93%A4  (4.0s)

**Comment by bhfaker** [comment]
다행히 해결됐습니다. 윈도우 사용자명을 한글에서 영어로 바꾸니까 정상적으로 작동하네요.
