### ISSUE TITLE
Unable to download afreecatv video files

### ISSUE THREAD

**Issue by admin576** [KurtBestor/Hitomi-Downloader#5906]
Invalid: [afreeca] https://vod.afreecatv.com/player/91121085

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 5fc5a82fefc947ecadb715c4dac89e3f
input: https://vod.afreecatv.com/player/91121085
type: afreeca
single: True
url: https://vod.afreecatv.com/player/91121085
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1682342182.7384284 (23-04-24 13:16:22 UTC) - 470s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
url_thumb: https://iflv14.afreecatv.com/save/afreeca/station/2022/0820/16/thumb/1660982250578477_L_7.jpg
No VodParameter
stop
Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "extractor\afreeca_downloader", line 39, in read
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\afreeca_downloader", line 71, in get_video
 File "ree", line 14, in find
ree.NotFound: No VodParameter

Invalid: fail=True
quality: 75%
EOT: https://vod.afreecatv.com/player/91121085  (1.1s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/5685
