### ISSUE TITLE
유튜브 연령제한 영상이 갑자기 막혔습니다.

### ISSUE THREAD

**Issue by xxx1129x** [KurtBestor/Hitomi-Downloader#5921]
Login required; Update your cookies: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.
https://www.youtube.com/watch?v=kiSbHlYKXcQ

version: 3.8a (23-04-29 23:48:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 1 / False / df98730be92f4823bbb2991e58a69325
input: https://www.youtube.com/watch?v=kiSbHlYKXcQ
type: youtube
single: True
url: https://www.youtube.com/watch?v=kiSbHlYKXcQ
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1682816162.5236578 (23-04-30 00:56:02 UTC) - 508s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\youtube", line 4018, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 1172, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 575, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\youtube", line 4018, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 1172, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 575, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\youtube", line 4018, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 1172, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 575, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kiSbHlYKXcQ
[debug] [youtube] kiSbHlYKXcQ: Downloading webpage
[debug] [youtube] kiSbHlYKXcQ: Downloading android player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading tv embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded client config
[debug] [youtube] kiSbHlYKXcQ: Downloading player 0c487f05
[debug] [youtube] kiSbHlYKXcQ: Downloading web embedded player API JSON
[debug] [youtube] kiSbHlYKXcQ: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\youtube", line 4018, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 1172, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 575, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

Traceback (most recent call last):
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\youtube", line 4018, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 1172, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 834, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 575, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

[youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.
stop
Traceback (most recent call last):
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\youtube", line 4018, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\extractor\common", line 1172, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1366, in start_
 File "extractor\youtube_downloader", line 413, in read
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 834, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 575, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ash83\AppData\Local\Temp\_MEI15002\ytdl_c943bdea\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 385, in report_error
errors.LoginRequired: [youtube] kiSbHlYKXcQ: Sign in to confirm your age. This video may be inappropriate for some users.

Invalid: fail=False
EOT: https://www.youtube.com/watch?v=kiSbHlYKXcQ  (20.6s)

이렇게 작업정보가 나오네요. 방법이 있을까요?^^;;

**Comment by STR-HK** [comment]
성인인증 된 유튜브 계정으로 로그인 한 뒤, 쿠키를 저장하시고 다운로더에서 불러오세요.

**Comment by xxx1129x** [comment]
> 성인인증 된 유튜브 계정으로 로그인 한 뒤, 쿠키를 저장하시고 다운로더에서 불러오세요.

답변 감사드립니다. 평소 쿠키 받던 크롬 앱이 막혔는데 혹시 어떤걸로 가져오시는지 여쭤봐도 될까요 ㅠ

**Comment by STR-HK** [comment]
[이거](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) 사용해보세요.

**Comment by xxx1129x** [comment]
> 

오오 예전꺼랑 비슷하게 생겼네요^^ 감사합니다!
