### ISSUE TITLE
인스타 개별 다운로드 불가능 현상

### ISSUE THREAD

**Issue by Opti-mizing** [KurtBestor/Hitomi-Downloader#5930]
안녕하세요
항상 개발하시느라 고생많으십니다.

사이트체인지로 추정되는 현상 제보드립니다.

현재 이용중인 버전은 v3.8b (Last updated on: May 02, 2023) 
네트워크 - 내장 웹브라우저 - 보기로 봤을때 쿠키는 정상적으로 적용됐습니다. 

지금 발생하고 있는 현상은 개별링크 (https://www.instagram.com/p/CrnfpceSMbB) 다운로드를 하면 에러가 나는데 
계정 메인주소 (https://www.instagram.com/lilyiu_) 로 페이지 조절해서 ~10 이렇게 하면 정상적으로 다운로드가 되는 현상입니다. 

비슷한 이슈가 열려있는게 없어서 제가 바보라서 그런건지 모르겠네요 ;; 
분명 전에는 개별링크로 했을때도 다운이 된걸로 기억합니다. 

Invalid: [insta] https://www.instagram.com/p/CrnfpceSMbB

version: 3.8b (23-05-02 02:03:27 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 7d8ccc72e747485eb8b586a54cf57b72
input: https://www.instagram.com/p/CrnfpceSMbB
type: insta
single: False
url: https://www.instagram.com/p/CrnfpceSMbB
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1683025375.615446 (23-05-02 11:02:55 UTC) - 44s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
not f
not f
not f
no html
no html
no media_owner_id
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\insta_downloader", line 69, in read
 File "extractor\insta_downloader", line 236, in get_user_info
 File "ree", line 14, in find
ree.NotFound: no media_owner_id

Invalid: fail=True
EOT: https://www.instagram.com/p/CrnfpceSMbB  (27.1s)

이상입니다.

**Comment by Happy-Hannah** [comment]
저도 동일 증상이 있네요.
정확히 기억이 안나지만 한달전 쯤은 잘 됐었어요. 
개발자님 감사먼저 드립니다 ^^

로그 동일하겠지만 올려요

Invalid: [insta] https://www.instagram.com/p/Cr0bWxBLZjB

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 2452ad975303426ca06451e3455a7c14
input: https://www.instagram.com/p/Cr0bWxBLZjB
type: insta
single: False
url: https://www.instagram.com/p/Cr0bWxBLZjB
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1683440245.7344341 (23-05-07 06:17:25 UTC) - 66s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
no html
not f
not f
not f
no html
no media_owner_id
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\insta_downloader", line 69, in read
 File "extractor\insta_downloader", line 236, in get_user_info
 File "ree", line 14, in find
ree.NotFound: no media_owner_id

Invalid: fail=True
EOT: https://www.instagram.com/p/Cr0bWxBLZjB  (30.9s)

**Comment by WhiteCode5342** [comment]
저도 똑같은 현상이 일어납니다
계정 프로필 주소 넣으면 잘 다운 되지만
게시물 하나의 주소를 넣으면 Invalid 뜹니다
스토리는 잘 다운됩니다.

**Comment by easter1208** [comment]
저도 동일합니다. 개별 릴스나 피드를 다운로드를 못하네요ㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by easter1208** [comment]
> 

정상동작합니다! 감사합니다

**Comment by Happy-Hannah** [comment]
테스트 버전으로 저도 잘 동작하네요. 감사합니다!

**Comment by Opti-mizing** [comment]
정상동작하네요 감사합니당
