### ISSUE TITLE
다운로더 업데이트 이후 픽시브 다운로드 시에 safe mode 뜨면서 안됩니다

### ISSUE THREAD

**Issue by suzukioha** [KurtBestor/Hitomi-Downloader#5934]
업데이트 이전 버전으로 설치하면 다시 정상적으로 다운됩니다.

**Comment by writternkk** [comment]
픽시브뿐 아니라, 마나토끼랑 Welovemanga.one(Lhscan 후신)도 그런 현상이 발견되네요.
내장 브라우저가 완전히 잠겨서 생기는 문제 같은데, 일단 lh 쪽 코드를 대신 올립니다.

Browser required; Use --safemode
https://welovemanga.one/433/

version: 3.8b (23-05-04 00:06:10 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / b043ea82fad34bebad892811ba037caf
input: https://welovemanga.one/433/
type: lhscan
single: False
url: https://welovemanga.one/433/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1683224120.8230133 (23-05-04 18:15:20 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]

Path: C:\Users\남기권\AppData\Local\Temp\_MEI223642
Invalid characters: 남기권

stop
Traceback (most recent call last):
 File "utils", line 1275, in start
 File "extractor\lhscan_downloader", line 61, in init
 File "extractor\lhscan_downloader", line 42, in get_soup_session
 File "clf2", line 116, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
quality: 100%
EOT: https://welovemanga.one/433/  (0.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by suzukioha** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

안되네요 ㅠㅠ 제 짧은 생각입니다만 작업정보를 보니까

Path: C:\Users\윈도우명(한글임)\AppData\Local\Temp\_MEI101122
Invalid characters: 윈도우명(한글임)

경로? path가 c드라이브로 돼서 그런 거 같습니다.
영문으로 된 다른 하드디스크로 경로를 설정했었는데

업데이트 된 버전이나 테스트버전 동일합니다. 


작업정보는 


Browser required; Use --safemode
https://www.pixiv.net/users/93851808

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10
order / group / uid: 16 / False / 1820c5c0090e486a90c41fc7a9c6b303
input: https://www.pixiv.net/users/93851808
type: pixiv
single: False
url: https://www.pixiv.net/users/93851808
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1683269798.150499 (23-05-05 06:56:38 UTC) - 385s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]

Path: C:\Users\윈도우명(한글임)\AppData\Local\Temp\_MEI101122
Invalid characters: 윈도우명(한글임)

stop
Traceback (most recent call last):
 File "utils", line 1275, in start
 File "extractor\pixiv_downloader", line 41, in init
 File "clf2", line 116, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://www.pixiv.net/users/93851808  (0.2s)


Path: C:\Users\윈도우명(한글임)\AppData\Local\Temp\_MEI101122
Invalid characters: 윈도우명(한글임)

stop
Traceback (most recent call last):
 File "utils", line 1275, in start
 File "extractor\pixiv_downloader", line 41, in init
 File "clf2", line 116, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://www.pixiv.net/users/93851808  (0.0s)


Path: C:\Users\윈도우명(한글임)\AppData\Local\Temp\_MEI101122
Invalid characters: 윈도우명(한글임)

stop
Traceback (most recent call last):
 File "utils", line 1275, in start
 File "extractor\pixiv_downloader", line 41, in init
 File "clf2", line 116, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://www.pixiv.net/users/93851808  (0.0s)



이상입니다

최신버전 3.8b, 3.8c , 올려주신 테스트 모드 모두 동일하며

3.8a 버전은 정상적으로 다운로드 됩니다.

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 열고 다음과 같이 입력하면 어떻게 뜨나요?
```
sys._MEIPASS
```

**Comment by suzukioha** [comment]
> Ctrl + Alt + C 눌러서 콘솔 열고 다음과 같이 입력하면 어떻게 뜨나요?
> 
>Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]    
다운로드가 가능한 3.8a 버전은 이렇게 뜨고



Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
다운로드가 되지 않는 3.8c 버전은 이렇게 뜹니다.

**Comment by suzukioha** [comment]
'C:\\Users\\윈도우명(한글임)\\AppData\\Local\\Temp\\_MEI121762'   이렇게 뜹니다.
c드라이브로 임시저장폴더가 설정되서 그런거 같습니다..ㅠㅠㅠ

그런데 저는 따로 설정은 건드리지 않았어요
지금도 3.8a 버전은 정상적으로 다운로드 됩니다

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 열고 다음과 같이 입력하면 각 버전에서 어떻게 뜨나요?
```
options.OPTIONS
```

**Comment by suzukioha** [comment]
>  다운로드가 가능한 3.8a 에서는

options.OPTIONS 

{'debug': False, 'disable-gpu': False, 'no-browser': False, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': True, 'experimental': False, 'auto-scale': False, 'scale': 1, 'round-menu': True}

이렇게 뜹니다

ㅡㅡㅡㅡㅡ

다운로드가 불가능한 3.8c에서는

options.OPTIONS 

{'debug': False, 'disable-gpu': False, 'no-browser': True, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': False, 'experimental': False, 'auto-scale': False, 'scale': 1, 'round-menu': True}

라고 뜹니다.

**Comment by KurtBestor** [comment]
v3.8a 에선 `--safemode` 로 실행했는데 v3.8c 에선 그렇지 않네요
`--safemode` 로 실행해주세요

**Comment by suzukioha** [comment]
> v3.8a 에선 `--safemode` 로 실행했는데 v3.8c 에선 그렇지 않네요 `--safemode` 로 실행해주세요

#5206 여기에 나와있는 대로 바로가기 만든 후 -> 속성 -> 대상 "D:\hitomi_downloader_GUIwe\hitomi_downloader_GUI.exe --safemode"이렇게 하니까 되네요 !

놀랍게도 해당 다운로더 폴더 내에 임시폴더 _MEI174962 가 생성 되었습니다

정상적으로 구동되네요 감사합니다 !!

**Comment by writternkk** [comment]
저도 바로가기>속성>대상 방법으로 해결했습니다.
감사합니다.
