### ISSUE TITLE
업데이트 이후 디시인사이드가 안됩니다

### ISSUE THREAD

**Issue by suzukioha** [KurtBestor/Hitomi-Downloader#5954]
Invalid: [dc] https://gall.dcinside.com/mgallery/board/view/?id=aiphoto&no=423&page=1

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10
order / group / uid: 376 / False / b5b8a7bf8f1c43b9b70f9e4517ed31d2
input: https://gall.dcinside.com/mgallery/board/view/?id=aiphoto&no=423&page=1
type: dc
single: False
url: https://gall.dcinside.com/mgallery/board/view/?id=aiphoto&no=423&page=1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1683584611.216365 (23-05-08 22:23:31 UTC) - 16s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'string'
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "dynamic_module_2", line 85, in read
 File "dynamic_module_2", line 81, in name
AttributeError: 'NoneType' object has no attribute 'string'

Invalid: fail=True
EOT: https://gall.dcinside.com/mgallery/board/view/?id=aiphoto&no=423&page=1  (1.4s)

쿠키 적용해도 안 되고 디시 로그인 해도 안 됩니다
3.8c 버전은 안 되지만, 3.8a 버전은 작동해요

**Comment by suzukioha** [comment]
혹시 몰라서 --safemode로 시도해봤지만 안 됩니다.

**Comment by onanana** [comment]
DPI 우회 켜면 디씨 접속 안되더라구요
히토미 다운로더만의 문제가 아니라
모든 DPI 우회 프로그램 켜면 디시가 안돼요
디시 자체에서 막아 놓은 거 같던데
DPI 우회 끄면 됩니다

**Comment by k750627** [comment]
요세  우회 안되있어도 안되는경우가 많음.. 답답해죽겠음 ㅠ

**Comment by suzukioha** [comment]
> DPI 우회 켜면 디씨 접속 안되더라구요 히토미 다운로더만의 문제가 아니라 모든 DPI 우회 프로그램 켜면 디시가 안돼요 디시 자체에서 막아 놓은 거 같던데 DPI 우회 끄면 됩니다

dpi를 꺼도 똑같네요.. dpi 우회를 키더라도 3.8a 버전은 잘 됩니다.

**Comment by belinim701** [comment]
저도 그냥 goodbyedpi.exe 프로그램은 켜도 디시인사이드 들어가지는데, 히토미 다운로더에서의 dpi 우회를 켜면 안 들어가지더라고요ㅠㅠ

**Comment by Winneaker5261** [comment]
dpi 프로그램 끄고 옵션에서도 끄고 했는데도 다운이 안되네요
저만 그런 건지..
