### ISSUE TITLE
뉴토끼 다운로드시 완료가 되지 않습니다.

### ISSUE THREAD

**Issue by berasala** [KurtBestor/Hitomi-Downloader#5972]
뉴토끼에서 만화 다운로드시

몇몇 작품들이 완료가 안되고 있는대, 그중 작업 정보 입니다.

로그가 너무 길어 업로드가 안되어 마지막 부분 fail 발생한 부분 첨부 했습니다.

-------------------------------------------------------------------------------------
우리는 공부를 못해

version: 3.8c+ (23-05-08 15:42:12 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 9 / False / a532ead14e824b8895b99c99605f5820
input: https://manatoki288.net/comic/122304
type: manatoki
single: False
url: https://manatoki288.net/comic/122304
dir: hitomi_downloaded_manatoki\우리는 공부를 못해
zip: 
artist: 츠츠이 타이시
valid / done: False / True
range / range_p: None / None
time: 1684021012.599213 (23-05-13 23:36:52 UTC) - 18939s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (1)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (2)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (3)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (4)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (5)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (6)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (7)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (8)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (9)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (10)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (11)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (12)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (13)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (14)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (15)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (16)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (17)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (18)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (19)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (20)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (21)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (22)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

retry (23)

Fail : \\?\C:\Users\LCW\Desktop\hitomi_downloader_GUI\hitomi_downloaded_manatoki\우리는 공부를 못해\우리는 공부를 못해 27화\0012.jpg
Traceback (most recent call last):
 File "downloader", line 1271, in download
Exception: HTML: Google Drive - Virus scan warning

stop
valid=False 1
quality: 100%
[0000.png]  [jpg] 608x850 --> 608x850
[0018.png]  [jpg] 600x867 --> 600x867
[0000.png]  [jpg] 746x1080 --> 746x1080
[0001.png]  [jpg] 746x1080 --> 746x1080
[0002.png]  [jpg] 746x1080 --> 746x1080
[0003.png]  [jpg] 743x1080 --> 743x1080
[0004.png]  [jpg] 747x1080 --> 747x1080
[0005.png]  [jpg] 747x1080 --> 747x1080
[0006.png]  [jpg] 749x1080 --> 749x1080
[0007.png]  [jpg] 747x1080 --> 747x1080
[0008.png]  [jpg] 747x1080 --> 747x1080
[0009.png]  [jpg] 747x1080 --> 747x1080
[0010.png]  [jpg] 748x1080 --> 748x1080
[0011.png]  [jpg] 746x1080 --> 746x1080
[0012.png]  [jpg] 745x1080 --> 745x1080
[0013.png]  [jpg] 745x1080 --> 745x1080
[0014.png]  [jpg] 745x1080 --> 745x1080
[0015.png]  [jpg] 744x1080 --> 744x1080
[0016.png]  [jpg] 744x1080 --> 744x1080
[0017.png]  [jpg] 746x1080 --> 746x1080
[0018.png]  [jpg] 747x1080 --> 747x1080
[0019.png]  [jpg] 742x1080 --> 742x1080
[0000.png]  [jpg] 748x1080 --> 748x1080
[0001.png]  [jpg] 748x1080 --> 748x1080
[0002.png]  [jpg] 748x1080 --> 748x1080
[0003.png]  [jpg] 748x1080 --> 748x1080
[0004.png]  [jpg] 748x1080 --> 748x1080
[0005.png]  [jpg] 748x1080 --> 748x1080
[0006.png]  [jpg] 748x1080 --> 748x1080
[0007.png]  [jpg] 748x1080 --> 748x1080
[0008.png]  [jpg] 748x1080 --> 748x1080
[0009.png]  [jpg] 748x1080 --> 748x1080
[0010.png]  [jpg] 748x1080 --> 748x1080
[0011.png]  [jpg] 748x1080 --> 748x1080
[0012.png]  [jpg] 748x1080 --> 748x1080
[0013.png]  [jpg] 748x1080 --> 748x1080
[0014.png]  [jpg] 748x1080 --> 748x1080
[0015.png]  [jpg] 748x1080 --> 748x1080
[0016.png]  [jpg] 748x1080 --> 748x1080
[0017.png]  [jpg] 748x1080 --> 748x1080
[0018.png]  [jpg] 748x1080 --> 748x1080
[0019.png]  [jpg] 748x1080 --> 748x1080
[0020.png]  [jpg] 748x1080 --> 748x1080
[0021.png]  [jpg] 748x1080 --> 748x1080
[0022.png]  [jpg] 748x1080 --> 748x1080
[0023.png]  [jpg] 748x1080 --> 748x1080
[0024.png]  [jpg] 748x1080 --> 748x1080
[0025.png]  [jpg] 748x1080 --> 748x1080
[0026.png]  [jpg] 748x1080 --> 748x1080
[0027.png]  [jpg] 748x1080 --> 748x1080
[0028.png]  [jpg] 748x1080 --> 748x1080
[0029.png]  [jpg] 748x1080 --> 748x1080
[0030.png]  [jpg] 748x1080 --> 748x1080
[0031.png]  [jpg] 748x1080 --> 748x1080
[0032.png]  [jpg] 748x1080 --> 748x1080
[0033.png]  [jpg] 748x1080 --> 748x1080
[0034.png]  [jpg] 748x1080 --> 748x1080
[0035.png]  [jpg] 748x1080 --> 748x1080
[0036.png]  [jpg] 748x1080 --> 748x1080
[0037.png]  [jpg] 748x1080 --> 748x1080
[0000.png]  [jpg] 761x1080 --> 761x1080
[0001.png]  [jpg] 761x1080 --> 761x1080
[0002.png]  [jpg] 761x1080 --> 761x1080
[0003.png]  [jpg] 761x1080 --> 761x1080
[0004.png]  [jpg] 761x1080 --> 761x1080
[0005.png]  [jpg] 761x1080 --> 761x1080
[0006.png]  [jpg] 761x1080 --> 761x1080
[0007.png]  [jpg] 761x1080 --> 761x1080
[0008.png]  [jpg] 761x1080 --> 761x1080
[0009.png]  [jpg] 761x1080 --> 761x1080
[0010.png]  [jpg] 761x1080 --> 761x1080
[0011.png]  [jpg] 761x1080 --> 761x1080
[0012.png]  [jpg] 761x1080 --> 761x1080
[0013.png]  [jpg] 761x1080 --> 761x1080
[0014.png]  [jpg] 761x1080 --> 761x1080
[0015.png]  [jpg] 761x1080 --> 761x1080
[0016.png]  [jpg] 761x1080 --> 761x1080
[0017.png]  [jpg] 761x1080 --> 761x1080
[0021.png]  [jpg] 761x1080 --> 761x1080
[0022.png]  [jpg] 761x1080 --> 761x1080
[0023.png]  [jpg] 761x1080 --> 761x1080
[0024.png]  [jpg] 761x1080 --> 761x1080
[0025.png]  [jpg] 761x1080 --> 761x1080
[0026.png]  [jpg] 761x1080 --> 761x1080
[0027.png]  [jpg] 761x1080 --> 761x1080
[0028.png]  [jpg] 761x1080 --> 761x1080
[0029.png]  [jpg] 761x1080 --> 761x1080
[0030.png]  [jpg] 761x1080 --> 761x1080
[0031.png]  [jpg] 761x1080 --> 761x1080
[0032.png]  [jpg] 761x1080 --> 761x1080
[0033.png]  [jpg] 761x1080 --> 761x1080
[0034.png]  [jpg] 761x1080 --> 761x1080
[0035.png]  [jpg] 761x1080 --> 761x1080
[0036.png]  [jpg] 761x1080 --> 761x1080
[0037.png]  [jpg] 761x1080 --> 761x1080
[0038.png]  [jpg] 761x1080 --> 761x1080
[0000.png]  [jpg] 745x1080 --> 745x1080
[0001.png]  [jpg] 745x1080 --> 745x1080
[0002.png]  [jpg] 744x1080 --> 744x1080
[0003.png]  [jpg] 744x1080 --> 744x1080
[0004.png]  [jpg] 745x1080 --> 745x1080
[0005.png]  [jpg] 745x1080 --> 745x1080
[0006.png]  [jpg] 745x1080 --> 745x1080
[0007.png]  [jpg] 744x1080 --> 744x1080
[0008.png]  [jpg] 745x1080 --> 745x1080
[0009.png]  [jpg] 745x1080 --> 745x1080
[0010.png]  [jpg] 746x1080 --> 746x1080
[0011.png]  [jpg] 746x1080 --> 746x1080
[0012.png]  [jpg] 745x1080 --> 745x1080
[0013.png]  [jpg] 745x1080 --> 745x1080
[0014.png]  [jpg] 746x1080 --> 746x1080
[0015.png]  [jpg] 745x1080 --> 745x1080
[0016.png]  [jpg] 747x1080 --> 747x1080
[0017.png]  [jpg] 745x1080 --> 745x1080
[0018.png]  [jpg] 748x1080 --> 748x1080
[0019.png]  [jpg] 745x1080 --> 745x1080
[0020.png]  [jpg] 745x1080 --> 745x1080
[0021.png]  [jpg] 744x1080 --> 744x1080
[0022.png]  [jpg] 744x1080 --> 744x1080
[0023.png]  [jpg] 745x1080 --> 745x1080
[0024.png]  [jpg] 745x1080 --> 745x1080
[0025.png]  [jpg] 745x1080 --> 745x1080
[0026.png]  [jpg] 744x1080 --> 744x1080
[0027.png]  [jpg] 745x1080 --> 745x1080
[0028.png]  [jpg] 745x1080 --> 745x1080
[0029.png]  [jpg] 746x1080 --> 746x1080
[0030.png]  [jpg] 746x1080 --> 746x1080
[0031.png]  [jpg] 745x1080 --> 745x1080
[0032.png]  [jpg] 745x1080 --> 745x1080
[0033.png]  [jpg] 746x1080 --> 746x1080
[0034.png]  [jpg] 745x1080 --> 745x1080
[0035.png]  [jpg] 747x1080 --> 747x1080
[0036.png]  [jpg] 745x1080 --> 745x1080
[0037.png]  [jpg] 748x1080 --> 748x1080
EOT: https://manatoki288.net/comic/122304  (8529.4s)

------------------------------------------------------------------------------------

문외인이지만 작업정보 보면 27화에서 12.jpg 파일을 뭔가 히자 못해서 발생한것 같아 보입니다.

**Comment by byeoriabba** [comment]
해당 이미지가 마나토끼 자체에서 로딩이 되지 않아서 생기는 오류로 마나토끼에서 해결되어야 할 문제 입니다

**Comment by berasala** [comment]
> 해당 이미지가 마나토끼 자체에서 로딩이 되지 않아서 생기는 오류로 마나토끼에서 해결되어야 할 문제 입니다

답변 감사합니다 ㅠㅠ
