### ISSUE TITLE
마나토끼, 제이마나등에서 다운이 아예 안되요.ㅠㅠ

### ISSUE THREAD

**Issue by junjun5353** [KurtBestor/Hitomi-Downloader#5975]
다운누르면 바로 빨간색으로 
Browser required; Use --safemode 라고 뜨면서 다운이 되지 않아요.
마나토끼, 제이마나 전부 그런데 또 유투브는 다운이 잘 되구요.
바쁘시겠지만  부탁드리겠습니다.  항상 감사합니다.

Browser required; Use --safemode
https://manatoki288.net/comic/15881346

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / c28bc6056c2a469fae0f7ef89e480207
input: https://manatoki288.net/comic/15881346
type: manatoki
single: False
url: https://manatoki288.net/comic/15881346
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1684116799.3999586 (23-05-15 02:13:19 UTC) - 215s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]

Path: C:\Users\이희준\AppData\Local\Temp\_MEI250322
Invalid characters: 이희준

stop
Traceback (most recent call last):
 File "utils", line 1275, in start
 File "decorator", line 232, in fun
 File "constants", line 886, in wrapper
 File "constants", line 884, in wrapper
 File "extractor\manatoki_downloader", line 56, in init
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\manatoki_downloader", line 141, in get_soup
 File "clf2", line 116, in solve
 File "clf2", line 96, in _init
errors.BrowserRequired

Invalid: fail=False
EOT: https://manatoki288.net/comic/15881346  (0.0s)

**Comment by writternkk** [comment]
내장 브라우저가 안 뜨는 부분은 임시로 아래와 같이 하시면 해결됩니다.

① hitomi_downloader_gui.exe 선택
② 마우스 오른쪽 클릭
③ 바로가기 클릭
④ Hitomi_downloader_gui.exe 바로가기 선택
⑤ 마우스 오른쪽 클릭
⑥ 속성 클릭
⑧ 대상(T)의 경로값 맨 뒤에 --safemode 입력 후 확인

이후, 바로가기로 프로그램을 시작하시면 만화 쪽 사이트도 다 내려받으실 수 있습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/5955#issuecomment-1562171268
