### ISSUE TITLE
쿠키 불러오기 err 에러

### ISSUE THREAD

**Issue by ys7726** [KurtBestor/Hitomi-Downloader#5979]
[](url)
![제목 없음](https://github.com/KurtBestor/Hitomi-Downloader/assets/69583055/c1b64296-3242-48e8-8d9e-152e4c429760)

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9588, in loadCookiesFromBrowser
  File "cooker", line 167, in extract_cookies_from_browser
  File "C:\Users\ys\AppData\Local\Temp\_MEI198442\ytdl_d276c7da\yt_dlp\yt_dlp\cookies", line 120, in extract_cookies_from_browser
  File "C:\Users\ys\AppData\Local\Temp\_MEI198442\ytdl_d276c7da\yt_dlp\yt_dlp\cookies", line 281, in _extract_chrome_cookies
FileNotFoundError: could not find whale cookies database in "C:\Users\ys\AppData\Local\Naver\Naver Whale\User Data"

brave앱 쓰는데 불러오기 누르면 err 에러가 떠서 확장프로그램 editthiscookie에서 클립보드 복사해서 cookies.txt에 붙여넣기해서 불러오기하고있는데 번거롭네요

chrome,firefox,edge,opera,brave 클릭해도 err에러나는데 get cookies처럼 편하게 쿠키 불러오는 방법 없을까요?

**Comment by Mango-Clark** [comment]
3.8c, 테스트 버전 v3.8c (Last updated on: May 05, 2023) 
에서도 모두 같은 에러를 확인했습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ys7726** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

쿠키 다운은되는데 카카오페이지에서는 기본무료제공만되고 기다리면무료는 안되네요 ㅜ

**Comment by Mango-Clark** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘 되지만 Firefox가 컴퓨터에 없음에도 버튼이 활성화 되어 있습니다. 누르면 FileNotFoundError가 뜹니다.

**Comment by CLANK0624** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

쿠키 관련해서 해당 링크에 있는 테스트 빌드로 해봤지만
여전히 쿠키 불러오기에서 에러가 발생합니다..

확인 부탁드리겠습니다
https://github.com/KurtBestor/Hitomi-Downloader/issues/6010
