### ISSUE TITLE
Can't download from exhentai. 

### ISSUE THREAD

**Issue by NachoFul123** [KurtBestor/Hitomi-Downloader#5987]
i'm in russia and exhentai not blocked here but it can't download from exhentai but if gallery exist on hitomi it will download from it. . 
Changing priority server or choosing manually not working.
Everything worked fine last week. Proxy does not fix the problem and turning on Bypass dpi to.

Invalid: [hitomi] https://exhentai.org/g/2556591/8450d8cfdd/

version: 3.8c+ (23-05-08 15:42:12 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ru_ru
order / group / uid: 0 / False / 0e19506da9cb4828b475015d44e6f96f
input: https://exhentai.org/g/2556591/8450d8cfdd/
type: ehen
single: False
url: https://exhentai.org/g/2556591/8450d8cfdd/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1684428522.0328314 (23-05-18 16:48:42 UTC) - 679s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 458, in get_imgs
 File "hitomi", line 639, in pop_img
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "hitomi", line 612, in update_module
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

Read reader FAILED - auto
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 598, in read
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 458, in get_imgs
 File "hitomi", line 639, in pop_img
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "hitomi", line 612, in update_module
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

get_imgs server: hitomi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 458, in get_imgs
 File "hitomi", line 639, in pop_img
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "hitomi", line 612, in update_module
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

get_imgs server: hiyobi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 707, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 94, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 94, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000148129CA948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2556591 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000148129CA948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 467, in get_imgs
 File "hitomi_downloader", line 467, in <listcomp>
 File "extractor\hiyobi_downloader", line 38, in pop_img_hiyobi
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2556591 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000148129CA948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Read reader FAILED - auto
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 707, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 94, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 94, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000148129CA948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2556591 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000148129CA948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 598, in read
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 467, in get_imgs
 File "hitomi_downloader", line 467, in <listcomp>
 File "extractor\hiyobi_downloader", line 38, in pop_img_hiyobi
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2556591 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000148129CA948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

get_imgs server: hitomi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] Удаленный хост принудительно разорвал существующее подключение>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 458, in get_imgs
 File "hitomi", line 639, in pop_img
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "hitomi", line 612, in update_module
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

get_imgs server: hiyobi
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 707, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 94, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 94, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000014822A64388>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2556591 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014822A64388>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 467, in get_imgs
 File "hitomi_downloader", line 467, in <listcomp>
 File "extractor\hiyobi_downloader", line 38, in pop_img_hiyobi
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2556591 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014822A64388>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/2556591/8450d8cfdd/)
using custom cookies
Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 588, in read
 File "hitomi_downloader", line 469, in get_imgs
 File "extractor\ehen_downloader", line 201, in ehen_imgs
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

Read reader FAILED - auto
Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

**Comment by NachoFul123** [comment]
And it magicaly started working for some reason
