### ISSUE TITLE
선생님 노조미에서 특정 태그들이 다운이 안됩니다

### ISSUE THREAD

**Issue by suzukioha** [KurtBestor/Hitomi-Downloader#5989]
https://nozomi.la/search.html?q=Realistic
https://nozomi.la/search.html?q=StableDiffusion
https://nozomi.la/search.html?q=AI

ai관련 태그들은 다운로드가 안 됩니다.
 
목록을 불러오면서 수치가 n / x 중에서 n이 어느 정도 진행이 되다가 진행이 멈춥니다.

29분 46초 뒤 다시 시작: https://nozomi.la/search.html?q=AI

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 2 / False / e8fda92f6f6d4960872b0f1d13ef8f42
input: https://nozomi.la/search.html?q=AI
type: nozomi
single: False
url: https://nozomi.la/search.html?q=AI
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1684534028.187156 (23-05-19 22:07:08 UTC) - 150s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/7/11/32169117.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (268.2s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (273.3s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (258.3s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/7/11/32169117.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (225.9s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (271.6s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (321.9s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (254.5s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/7/11/32169117.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (313.8s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (332.8s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (357.2s)

AI: 3147
ids: 3147
404
stop
Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 537, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://j.nozomi.la/post/6/04/32170046.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\nozomi_downloader", line 75, in read
 File "multiprocessing\pool", line 268, in map
 File "multiprocessing\pool", line 657, in get
 File "multiprocessing\pool", line 121, in worker
 File "multiprocessing\pool", line 44, in mapstar
 File "extractor\nozomi_downloader", line 75, in <lambda>
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\nozomi_downloader", line 26, in read_post
 File "downloader", line 424, in read_json
 File "downloader", line 547, in read_html
Exception: 404

Invalid: fail=True
EOT: https://nozomi.la/search.html?q=AI  (135.3s)

**Comment by suzukioha** [comment]
캐릭터들이나 작품 제목, 아티스트 등의 태그들은 정상작동해요
