### ISSUE TITLE
toonkor 문제가 있습니다

### ISSUE THREAD

**Issue by inki123** [KurtBestor/Hitomi-Downloader#5991]
Invalid: [toonkor] https://toonkor215.com/%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / b344a37a893b46549acd3aee05ff3037
input: https://toonkor215.com/%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98
type: toonkor
single: False
url: https://toonkor215.com/%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1684599851.9955146 (23-05-20 16:24:11 UTC) - 232s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
HTTPSConnectionPool(host='toonkor215.com', port=443): Max retries exceeded with url: /%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DCE32EF188>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001DCE32EF188>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='toonkor215.com', port=443): Max retries exceeded with url: /%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DCE32EF188>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1275, in start
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "dynamic_module_14", line 42, in init
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='toonkor215.com', port=443): Max retries exceeded with url: /%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DCE32EF188>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

Invalid: fail=True
EOT: https://toonkor215.com/%ED%95%9C%EC%A7%80%EB%B6%95-%EC%95%84%EB%9E%98  (169.2s)

toonkor사이트에서 읽어오지 못하는거같습니다. 무엇이 문제일까요

**Comment by byeoriabba** [comment]
저번주 툰코 사이트 자체가 터졌었습니다 24시간정도 그때 다운 시도 하셨던것 같습니다
