### ISSUE TITLE
히토미 다운로더 쿠키 플러그인이 안되는데 어떻게하나요?

### ISSUE THREAD

**Issue by wajgds** [KurtBestor/Hitomi-Downloader#6008]
예전엔 로그인하고 txt파일을 다운받아서 사용했는데
billbill에 로그인-1080변경후 새로고침-쿠키 내보내기로 복사하고 메모장에 옮기면 .txt파일을 불러오면 오류가나오고
히토미 다운로더 설정-네트워크-불러오기-크롬으로 불러오니

Invalid: [bili] https://www.bilibili.com/video/BV1Wz4y1z7Za/?spm_id_from=333.999.0.0&vd_source=da90eaebc1d8fc5a11049654f2ff2545

version: 3.8c+ (23-05-25 07:30:37 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 069f6217be5e4aed8b7a0f8ed416755b
input: https://www.bilibili.com/video/BV1Wz4y1z7Za/?spm_id_from=333.999.0.0&vd_source=da90eaebc1d8fc5a11049654f2ff2545
type: bili
single: True
url: https://www.bilibili.com/video/BV1Wz4y1z7Za/?spm_id_from=333.999.0.0&vd_source=da90eaebc1d8fc5a11049654f2ff2545
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1685518127.4713483 (23-05-31 07:28:47 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1Wz4y1z7Za/?spm_id_from=333.999.0.0&vd_source=da90eaebc1d8fc5a11049654f2ff2545 -> https://www.bilibili.com/video/BV1Wz4y1z7Za/?spm_id_from=333.999.0.0&vd_source=da90eaebc1d8fc5a11049654f2ff2545
There are multiple cookies with name, 'SESSDATA'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\bili_downloader", line 115, in read
 File "requests\cookies", line 197, in get
 File "requests\cookies", line 394, in _find_no_duplicates
requests.cookies.CookieConflictError: There are multiple cookies with name, 'SESSDATA'

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1Wz4y1z7Za/?spm_id_from=333.999.0.0&vd_source=da90eaebc1d8fc5a11049654f2ff2545  (1.3s)
이런 오류가뜨면서 20메가정도로 다운받던 영상도 오류가떠서 다운자체가 안됩니다

**Comment by fade-out-0770** [comment]
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by EditThisCookie

플러그인에서 복사한 쿠키가 ↖이렇게 시작하는 쿠키인가요?  아니라면 설정 하는 곳에 Netscape HTTP Cookie File을 선택하시고 쿠키를 다시 시도 해보세요.
저는 다운 됐습니다.
