### ISSUE TITLE
쿠키를 불러오질 못합니다

### ISSUE THREAD

**Issue by CLANK0624** [KurtBestor/Hitomi-Downloader#6010]
쿠키 파일이나
브라우저에서 바로 쿠키 가져오기할 떄 에러가 납니다

이전 5월25일에 비슷한 쿠키 이슈에 링크 걸어주신
테크니컬 리뷰 버젼도 써봤지만
증상은 그대로입니다

1. Cookies.txt를 불러왔을 때
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9562, in loadCookiesTxt
  File "cooker", line 92, in load
  File "cooker", line 62, in load
  File "cooker", line 53, in prepare_line
http.cookiejar.LoadError: invalid length 1

2. Edge에서 바로 가져왔을 때
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9574, in loadCookiesFromBrowser
  File "cooker", line 97, in load
  File "cooker", line 82, in update
AttributeError: 'YoutubeDLCookieJar' object has no attribute 'get_dict'

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
