### ISSUE TITLE
트위터 다운로드가 Invalid됩니다.

### ISSUE THREAD

**Issue by hinazen1235** [KurtBestor/Hitomi-Downloader#6012]
Invalid: [twitter] https://twitter.com/search

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / fa521b2044aa4611bad1ba0c7b9e18ea
input: https://twitter.com/search
type: twitter
single: False
url: https://twitter.com/search
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1685687004.3752499 (23-06-02 06:23:24 UTC) - 8s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
format: None
type: user
User 'search' not found
User 'search' not found
User 'search' not found
User 'search' not found
'user'
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\twitter_downloader", line 104, in read
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "extractor\twitter_downloader", line 1014, in get_artist_username
 File "extractor\twitter_downloader", line 1009, in get_artist_username
 File "extractor\twitter_downloader", line 327, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/search  (7.0s)

format: None
type: user
User 'search' not found
User 'search' not found
User 'search' not found
User 'search' not found
'user'
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\twitter_downloader", line 104, in read
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "extractor\twitter_downloader", line 1014, in get_artist_username
 File "extractor\twitter_downloader", line 1009, in get_artist_username
 File "extractor\twitter_downloader", line 327, in user_by_screen_name
KeyError: 'user'

Invalid: fail=True
EOT: https://twitter.com/search  (7.2s)

**Comment by KurtBestor** [comment]
Twitter Search 는 지원하지 않아요
