### ISSUE TITLE
픽시브 코믹 에러

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#6022]
확인 부탁드립니다.

Invalid: [pixiv_comic] https://comic.pixiv.net/works/9132

version: 3.8c+ (23-05-22 09:26:32 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 291 / False / f0f81edadf94405dbe1af4043d479295
input: https://comic.pixiv.net/works/9132
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/9132
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1685859638.20737 (23-06-04 06:20:38 UTC) - 1161s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1305, in start
 File "utils", line 1384, in start_
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "extractor\pixiv_comic_downloader", line 47, in read
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://comic.pixiv.net/works/9132  (126.0s)

**Comment by qj8x67s33a44** [comment]
쿠키 초기화 하니까 되네요
