### ISSUE TITLE
i don't know what to do

### ISSUE THREAD

**Issue by v5598** [KurtBestor/Hitomi-Downloader#6050]
Invalid: [youtube] https://www.youtube.com/watch?v=f4SM2SYmEHg

version: 3.8c+ (23-06-18 14:50:49 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / a57ccaf0ba48411fb0a963719ae3b769
input: https://www.youtube.com/watch?v=f4SM2SYmEHg
type: youtube
single: True
url: https://www.youtube.com/watch?v=f4SM2SYmEHg
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687300569.0368466 (23-06-20 22:36:09 UTC) - 22s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=f4SM2SYmEHg
[debug] [youtube] f4SM2SYmEHg: Downloading webpage
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
live: not_live
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 595, in __init__
 File "ytdl", line 632, in get_subtitles
 File "ytdl", line 625, in foo
AttributeError: 'NoneType' object has no attribute 'items'

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=f4SM2SYmEHg
[debug] [youtube] f4SM2SYmEHg: Downloading webpage
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
live: not_live
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 595, in __init__
 File "ytdl", line 632, in get_subtitles
 File "ytdl", line 625, in foo
AttributeError: 'NoneType' object has no attribute 'items'

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=f4SM2SYmEHg
[debug] [youtube] f4SM2SYmEHg: Downloading webpage
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
live: not_live
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 595, in __init__
 File "ytdl", line 632, in get_subtitles
 File "ytdl", line 625, in foo
AttributeError: 'NoneType' object has no attribute 'items'

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=f4SM2SYmEHg
[debug] [youtube] f4SM2SYmEHg: Downloading webpage
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] f4SM2SYmEHg: Downloading android player API JSON
live: not_live
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 595, in __init__
 File "ytdl", line 632, in get_subtitles
 File "ytdl", line 625, in foo
AttributeError: 'NoneType' object has no attribute 'items'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 850, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 595, in __init__
 File "ytdl", line 632, in get_subtitles
 File "ytdl", line 625, in foo
AttributeError: 'NoneType' object has no attribute 'items'

'NoneType' object has no attribute 'items'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\youtube_downloader", line 413, in read
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 850, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 595, in __init__
 File "ytdl", line 632, in get_subtitles
 File "ytdl", line 625, in foo
AttributeError: 'NoneType' object has no attribute 'items'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=f4SM2SYmEHg  (13.5s)

**Comment by Mango-Clark** [comment]
try to use tech pre version
> https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
