### ISSUE TITLE
어제까진  폰허브 유튜브  픽시브 등등 잘 받아졌는데

### ISSUE THREAD

**Issue by hoohoohoo507** [KurtBestor/Hitomi-Downloader#6052]
오늘 받으려고 보니  유튜브 폰허브  픽시브 등등  전부  다운불가 되어버렸네요....
무슨 일인지...

**Comment by tttest231** [comment]
저도 다 막혔더라구요 혹시 로그보면 같은 오류나시나요?


Invalid: [youtube] https://www.youtube.com/watch?v=x0rQUNp7pZE

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 2f75d45761874ab98c31ff8edfe1aad4
input: https://www.youtube.com/watch?v=x0rQUNp7pZE
type: youtube
single: True
url: https://www.youtube.com/watch?v=x0rQUNp7pZE
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687344675.195189 (23-06-21 10:51:15 UTC) - 11s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.21
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\linka\AppData\Local\Temp\_MEI421682\ytdl_2b78a4ea\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

**Comment by krehard** [comment]
저도 그렇네요...

**Comment by hoohoohoo507** [comment]
4분 58초 뒤 다시 시작: https://www.youtube.com/watch?v=eAEbx4XLM_8

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 34ed9aa220c14377bc199696a8668413
input: https://www.youtube.com/watch?v=eAEbx4XLM_8
type: youtube
single: True
url: https://www.youtube.com/watch?v=eAEbx4XLM_8
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687347472.8397865 (23-06-21 11:37:52 UTC) - 10s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.06.21
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 834, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

'MyCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\youtube_downloader", line 413, in read
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 834, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\5600X\AppData\Local\Temp\_MEI973922\ytdl_889fe96e\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
quality: 75%
EOT: https://www.youtube.com/watch?v=eAEbx4XLM_8  (7.6s)

이런 상태긴 한데  같은지는 모르겠네요...

**Comment by beatmusiqjug** [comment]
저도 아에 안받아지네요.. 어제까지 잘되다가 그리고 여태까지는 다운은 잘 받아져서 굳이 오류 피드백 안적었는데 그동안 제가 알고있던 오류가 몇개있는데  1. 녹화를 5시59분59초만하고 더이상 녹화가 안된다는점 2. 예전엔 인스타그램 개별적으로 하나씩 받아졌는데 이젠 그사람 인스타 전체를 해야 받아 지더라고요. 전부다받는건가능 개별적은 불가능 예전엔 개별로도 잘됐던기능  3. 아프리카 예전엔 720p로 1080p 화질별로 원하는대로 용량 생각해서 받아졌는데 요즘엔 아프리카로 받으면 720p로 설정해놔도 무조건 1080p로 받아집니다. 4. 예전에는 유튜브 아프리카 둘다 녹화되던데 어느순간 안되던데 다시 되긴 하는거 같던데 아프리카가 안되다가 갑자기 되었었나 그때도 720p로는 녹화안되고 1080p로만 녹화되더라고요 예전엔 720p로도 녹화되었는데 버전이 예전에 좀됐었는데 그땐 잘되던게 하나씩 지금은 안되더라고요 그냥 다운은 잘되길래 지금도 감사하니깐 잘쓰긴해서 굳이 피드백안했었는데 수정해주시면 감사하겠습니다.

**Comment by hoohoohoo507** [comment]
히토미로  녹화도 가능한가요 ???  처음 알았네요...

**Comment by hoohoohoo507** [comment]
위에 테스트 버전으로 받아보니 잘 되네요... ㅎㅎㅎ  창과 방패의 대결인듯...

**Comment by maze888** [comment]
저도 유튜브 안 받아져요.

Invalid: [youtube] https://www.youtube.com/watch?v=_f5A1QW9hZg

version: 3.8c+ (23-06-08 03:21:07 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / eb3fdc11d3af4836af946b252d771e4f
input: https://www.youtube.com/watch?v=_f5A1QW9hZg
type: youtube
single: True
url: https://www.youtube.com/watch?v=_f5A1QW9hZg
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687362121.2491295 (23-06-21 15:42:01 UTC) - 125s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2023.06.21
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 850, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

'MyCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\youtube_downloader", line 413, in read
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 850, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\mazepc\AppData\Local\Temp\_MEI152082\ytdl_6d7d3f5c\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=_f5A1QW9hZg  (8.5s)

**Comment by hoohoohoo507** [comment]
위에 링크된 테스트 버전으로 받으시면 되요

**Comment by maze888** [comment]
> 위에 링크된 테스트 버전으로 받으시면 되요

테스트 버전 말고 정식 버전은 언제 릴리즈될까요..?
