### ISSUE TITLE
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### ISSUE THREAD

**Issue by zhgna** [KurtBestor/Hitomi-Downloader#6053]
Invalid: [youtube] https://www.youtube.com/watch?v=D8PVVEDs7kY

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / zh_cn
order / group / uid: 0 / False / aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
input: https://www.youtube.com/watch?v=D8PVVEDs7kY
type: youtube
single: True
url: https://www.youtube.com/watch?v=D8PVVEDs7kY
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687345298.7911468 (23-06-21 11:01:38 UTC) - 24s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 834, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

'MyCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\youtube_downloader", line 413, in read
 File "extractor\youtube_downloader", line 406, in read
 File "utils", line 834, in __call__
 File "extractor\youtube_downloader", line 78, in get
 File "extractor\youtube_downloader", line 68, in get
 File "ytdl", line 563, in __init__
 File "ytdl", line 553, in __init__
 File "ytdl", line 438, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\YoutubeDL", line 1631, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 705, in extract
   self.initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 614, in initialize
   self._real_initialize()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 524, in _real_initialize
   self._initialize_pref()
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\youtube", line 512, in _initialize_pref
   cookies = self._get_cookies('https://www.youtube.com/')
 File "C:\Users\86185\AppData\Local\Temp\_MEI304882\ytdl_f85570c4\yt_dlp\yt_dlp\extractor\common", line 3459, in _get_cookies
   return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
AttributeError: 'MyCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=D8PVVEDs7kY  (18.9s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by lastlament** [comment]
> Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

i had the same issue, and this fix worked. thank you!

**Comment by zhgna** [comment]
YES FIXED
















At 2023-06-22 12:02:53, "celeste ୨୧" ***@***.***> wrote:

Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

i had the same issue, and this fix worked. thank you!
