### ISSUE TITLE
최신 버전과 신규 테스트 버전에서 마나토끼 다운로드 불가 오류 문의드립니다.

### ISSUE THREAD

**Issue by snn001** [KurtBestor/Hitomi-Downloader#6065]
Invalid: [manatoki] https://manatoki293.net/comic/486756

version: 3.8c+ (23-06-21 11:48:38 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 85e5ead663a34656819c0248a4438448
input: https://manatoki293.net/comic/486756
type: manatoki
single: False
url: https://manatoki293.net/comic/486756
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687431597.421541 (23-06-22 10:59:57 UTC) - 16s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
no title
stop
Traceback (most recent call last):
 File "utils", line 1334, in start
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "extractor\manatoki_downloader", line 81, in init
 File "utils", line 645, in __get__
 File "extractor\manatoki_downloader", line 97, in name
 File "extractor\manatoki_downloader", line 118, in get_artist
 File "utils", line 2522, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki293.net/comic/486756  (14.4s)

작업 정보는 위와 같습니다.

최신 버전과 신규 테스트 버전에서 동일하게 나타나며

위 작업 정보는 신규 테스트 버전에서 복사했습니다.

항상 노고가 많으십니다.

감사합니다.

**Comment by snn001** [comment]
마나토끼 주소가 294로 변경 되면서 정상 다운로드 진행되는 범 확인했습니다.

감사합니다.
