### ISSUE TITLE
Enhancement: character substitution in file names

### ISSUE THREAD

**Issue by TheGhost78** [KurtBestor/Hitomi-Downloader#6080]
It would be good if there was the option to have automatic character substitution in the file names. For example:

"｜" replaced with "-",
"：" replaced with " -",
"？" replaced with nothing
"@" replaced with nothing, etc.

**Comment by STR-HK** [comment]
Make use of [hook ](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins#hooks)to achieve it.

**Comment by TheGhost78** [comment]
I'm not sure how they work.Basically, I thought an option that only allowed Windows-friendly names

**Comment by TheGhost78** [comment]
Thanks - I've created a few hooks to replace common characters. I tried to do ones for:
1F9261     🤦     FACE PALM (https://www.fileformat.info/info/unicode/char/1F926/index.htm)
1F3F9     🏹     BOW AND ARROW (https://www.fileformat.info/info/unicode/char/1F3F9/index.htm)
1F498     💘     HEART WITH ARROW (https://www.fileformat.info/info/unicode/char/1F498/index.htm)
but they didn't work.

It did work for:
2728     ✨     SPARKLES (https://www.fileformat.info/info/unicode/char/2728/index.htm)


I could not figure out how to replace a back slash '\', as the hook came up with an error message saying 'invalid format script'.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 5669, in exec_script
  File "dynamic_module_16", line 6
    c = '\'
          ^
SyntaxError: EOL while scanning string literal

**Comment by TheGhost78** [comment]
It would be good to include the option to subtitiute accented characters with non-acented ones, for example:
à to a
é to e
ü to u.
