### ISSUE TITLE
soundcloud 음악 다운이 안됩니다. 

### ISSUE THREAD

**Issue by forcolab** [KurtBestor/Hitomi-Downloader#6086]
Invalid: [soundcloud] https://soundcloud.com/georgecredit/george-boat-prod-by-deepshower

version: 3.8d+ (23-06-25 06:52:11 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 9f44dd943c034a189eaa049b7b423356
input: https://soundcloud.com/georgecredit/george-boat-prod-by-deepshower
type: soundcloud
single: True
url: https://soundcloud.com/georgecredit/george-boat-prod-by-deepshower
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687716844.3961568 (23-06-25 18:14:04 UTC) - 6s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [soundcloud] Extracting URL: https://soundcloud.com/georgecredit/george-boat-prod-by-deepshower
[debug] [soundcloud] georgecredit/george-boat-prod-by-deepshower: Downloading info JSON
[debug] [soundcloud] 356998157: Downloading JSON metadata
[debug] [soundcloud] 356998157: Downloading JSON metadata
[debug] [soundcloud] 356998157: Downloading JSON metadata
[debug] [soundcloud] Extracting URL: https://soundcloud.com/georgecredit/george-boat-prod-by-deepshower
[debug] [soundcloud] georgecredit/george-boat-prod-by-deepshower: Downloading info JSON
[debug] [soundcloud] 356998157: Downloading JSON metadata
[debug] [soundcloud] 356998157: Downloading JSON metadata
[debug] [soundcloud] 356998157: Downloading JSON metadata
'RequestsCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\soundcloud_downloader", line 114, in read
 File "decorator", line 232, in fun
 File "constants", line 934, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\soundcloud_downloader", line 156, in get_audios
 File "ytdl", line 440, in extract_info
 File "C:\Users\aaa\AppData\Local\Temp\_MEI139802\ytdl_82c63280\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aaa\AppData\Local\Temp\_MEI139802\ytdl_82c63280\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aaa\AppData\Local\Temp\_MEI139802\ytdl_82c63280\yt_dlp\yt_dlp\YoutubeDL", line 1652, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aaa\AppData\Local\Temp\_MEI139802\ytdl_82c63280\yt_dlp\yt_dlp\YoutubeDL", line 1711, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aaa\AppData\Local\Temp\_MEI139802\ytdl_82c63280\yt_dlp\yt_dlp\YoutubeDL", line 2673, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aaa\AppData\Local\Temp\_MEI139802\ytdl_82c63280\yt_dlp\yt_dlp\YoutubeDL", line 2410, in _calc_headers
   cookies = self.cookiejar.get_cookie_header(info_dict['url'])
AttributeError: 'RequestsCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
EOT: https://soundcloud.com/georgecredit/george-boat-prod-by-deepshower  (3.7s)

예전에 soundcloud 노래 다운이 잘 되었는데 오랜만에 해보니 다운이 안되네요
06.25 test 버전으로도 노래 다운을 시도했는데 안됩니다. 
혹시 해결 방법이 있을지 궁금합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by maticslaszlo** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview - that didn't solved problem

**Comment by forcolab** [comment]
잘 작동하는 것으로 확인되었습니다!
감사합니다!

**Comment by maticslaszlo** [comment]
Now it's working, but only downloaded m3u8, but didn't downloaded full video with chunks :(
