### ISSUE TITLE
YP: 'RequestsCookieJar' object has no attribute 'get_cookie_header'

### ISSUE THREAD

**Issue by maticslaszlo** [KurtBestor/Hitomi-Downloader#6087]
Invalid: fail=True
EOT: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/  (11.7s)

version: 3.8d (23-06-25 06:52:11 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / hu_hu
order / group / uid: 0 / False / 2e8da68be02846d5976f9281931df032
input: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
type: youporn
single: True
url: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687723594.8278232 (23-06-25 20:06:34 UTC) - 88s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
'RequestsCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\youporn_downloader", line 24, in read
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "extractor\youporn_downloader", line 38, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\malacka\AppData\Local\Temp\_MEI481202\ytdl_f9ee8a1c\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI481202\ytdl_f9ee8a1c\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI481202\ytdl_f9ee8a1c\yt_dlp\yt_dlp\YoutubeDL", line 1652, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI481202\ytdl_f9ee8a1c\yt_dlp\yt_dlp\YoutubeDL", line 1711, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI481202\ytdl_f9ee8a1c\yt_dlp\yt_dlp\YoutubeDL", line 2673, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\malacka\AppData\Local\Temp\_MEI481202\ytdl_f9ee8a1c\yt_dlp\yt_dlp\YoutubeDL", line 2410, in _calc_headers
   cookies = self.cookiejar.get_cookie_header(info_dict['url'])
AttributeError: 'RequestsCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
EOT: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/  (11.1s)

[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading JSON metadata
[debug] [YouPorn] 16435536: Downloading m3u8 information
[debug] [YouPorn] karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer: Downloading webpage
'RequestsCookieJar' object has no attribute 'get_cookie_header'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\youporn_downloader", line 24, in read
 File "decorator", line 232, in fun
 File "constants", line 934, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\youporn_downloader", line 38, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\malacka\AppData\Local\Temp\_MEI390042\ytdl_b5dc9671\yt_dlp\yt_dlp\YoutubeDL", line 1544, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI390042\ytdl_b5dc9671\yt_dlp\yt_dlp\YoutubeDL", line 1555, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI390042\ytdl_b5dc9671\yt_dlp\yt_dlp\YoutubeDL", line 1652, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI390042\ytdl_b5dc9671\yt_dlp\yt_dlp\YoutubeDL", line 1711, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\malacka\AppData\Local\Temp\_MEI390042\ytdl_b5dc9671\yt_dlp\yt_dlp\YoutubeDL", line 2673, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\malacka\AppData\Local\Temp\_MEI390042\ytdl_b5dc9671\yt_dlp\yt_dlp\YoutubeDL", line 2410, in _calc_headers
   cookies = self.cookiejar.get_cookie_header(info_dict['url'])
AttributeError: 'RequestsCookieJar' object has no attribute 'get_cookie_header'

Invalid: fail=True
EOT: https://www.youporn.com/watch/16435536/karina-seduces-mikes-friend-and-fucks-them-both-this-is-a-real-bitch-trailer/  (11.7s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/6086
