### ISSUE TITLE
xvideos 다운로드 invalid 뜨고 안됨

### ISSUE THREAD

**Issue by uniyui** [KurtBestor/Hitomi-Downloader#6110]
Invalid: [xvideo] www.xvideos.com/video68591943/princess_connect_rei_sex_creampie

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 10 / False / 05e5bdd69f31455ca200307f0950a960
input: www.xvideos.com/video68591943/princess_connect_rei_sex_creampie
type: xvideo
single: True
url: www.xvideos.com/video68591943/princess_connect_rei_sex_creampie
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1688143162.0074217 (23-06-30 16:39:22 UTC) - 114s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid URL 'www.xvideos.com/video68591943/princess_connect_rei_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video68591943/princess_connect_rei_sex_creampie?
stop
Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "urllib\request", line 510, in open
 File "urllib\request", line 328, in __init__
 File "urllib\request", line 354, in full_url
 File "urllib\request", line 383, in _parse
ValueError: unknown url type: 'www.xvideos.com/video68591943/princess_connect_rei_sex_creampie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 850, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 459, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 250, in session_request
 File "requests\sessions", line 528, in request
 File "requests\sessions", line 466, in prepare_request
 File "requests\models", line 316, in prepare
 File "requests\models", line 390, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'www.xvideos.com/video68591943/princess_connect_rei_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video68591943/princess_connect_rei_sex_creampie?

Invalid: fail=True
quality: 75%
EOT: www.xvideos.com/video68591943/princess_connect_rei_sex_creampie  (9.6s)

Invalid URL 'www.xvideos.com/video68591943/princess_connect_rei_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video68591943/princess_connect_rei_sex_creampie?
stop
Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "urllib\request", line 510, in open
 File "urllib\request", line 328, in __init__
 File "urllib\request", line 354, in full_url
 File "urllib\request", line 383, in _parse
ValueError: unknown url type: 'www.xvideos.com/video68591943/princess_connect_rei_sex_creampie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 850, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 459, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 250, in session_request
 File "requests\sessions", line 528, in request
 File "requests\sessions", line 466, in prepare_request
 File "requests\models", line 316, in prepare
 File "requests\models", line 390, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'www.xvideos.com/video68591943/princess_connect_rei_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video68591943/princess_connect_rei_sex_creampie?

Invalid: fail=True
quality: 75%
EOT: www.xvideos.com/video68591943/princess_connect_rei_sex_creampie  (11.1s)

==========

Invalid: [xvideo] www.xvideos.com/video65348279/princess_connect_yui_sex_creampie

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 11 / False / 5e64cbea81dc4300835b8949068faa86
input: www.xvideos.com/video65348279/princess_connect_yui_sex_creampie
type: xvideo
single: True
url: www.xvideos.com/video65348279/princess_connect_yui_sex_creampie
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1688143160.1035712 (23-06-30 16:39:20 UTC) - 124s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid URL 'www.xvideos.com/video65348279/princess_connect_yui_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video65348279/princess_connect_yui_sex_creampie?
stop
Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "urllib\request", line 510, in open
 File "urllib\request", line 328, in __init__
 File "urllib\request", line 354, in full_url
 File "urllib\request", line 383, in _parse
ValueError: unknown url type: 'www.xvideos.com/video65348279/princess_connect_yui_sex_creampie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 850, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 459, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 250, in session_request
 File "requests\sessions", line 528, in request
 File "requests\sessions", line 466, in prepare_request
 File "requests\models", line 316, in prepare
 File "requests\models", line 390, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'www.xvideos.com/video65348279/princess_connect_yui_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video65348279/princess_connect_yui_sex_creampie?

Invalid: fail=True
quality: 75%
EOT: www.xvideos.com/video65348279/princess_connect_yui_sex_creampie  (6.8s)

Invalid URL 'www.xvideos.com/video65348279/princess_connect_yui_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video65348279/princess_connect_yui_sex_creampie?
stop
Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "urllib\request", line 510, in open
 File "urllib\request", line 328, in __init__
 File "urllib\request", line 354, in full_url
 File "urllib\request", line 383, in _parse
ValueError: unknown url type: 'www.xvideos.com/video65348279/princess_connect_yui_sex_creampie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 850, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 459, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 250, in session_request
 File "requests\sessions", line 528, in request
 File "requests\sessions", line 466, in prepare_request
 File "requests\models", line 316, in prepare
 File "requests\models", line 390, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'www.xvideos.com/video65348279/princess_connect_yui_sex_creampie': No schema supplied. Perhaps you meant http://www.xvideos.com/video65348279/princess_connect_yui_sex_creampie?

Invalid: fail=True
quality: 75%
EOT: www.xvideos.com/video65348279/princess_connect_yui_sex_creampie  (14.8s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/6082#issuecomment-1606061700
