### ISSUE TITLE
트위터가 갑자기 막혔어요..

### ISSUE THREAD

**Issue by glxhalWKd** [KurtBestor/Hitomi-Downloader#6112]
어제 업뎃 이후로 안되는 거 같은데
확인해주시면 감사하겠슴다!

**Comment by KurtBestor** [comment]
업데이트 이후로 로그인해야만 다운로드 가능하게 바뀌었네요

**Comment by glxhalWKd** [comment]
쿠키 업뎃도 해봤는데 아예 먹통 된 듯.. 트위터 받는 건 이제 불가능해진 건지ㅠ

**Comment by sosoeun** [comment]
저도 마찬가지네요 일론이 얘기했던 제한이 아닌가 싶습니다.

**Comment by glxhalWKd** [comment]
트위터 돌아왔네요. 쿠키 업데이트하고 다시 다운해보니 됩니다

**Comment by qj8x67s33a44** [comment]
오전 9:08 2023-07-03

다운로드 안됩니다.

**Comment by qj8x67s33a44** [comment]
오전 9:08 2023-07-03

https://twitter.com/NIKKE_japan

읽는 중에서 무한 로딩, 다운로드 안됩니다.

retry... _pagination (5)
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 537, in _pagination
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 312, in _call
Exception: 404 Not Found (Sorry, that page does not exist)
