### ISSUE TITLE
xvideos 다운로드 오류가 뜹니다. 링크 마지막에 _가 들어가면 오류가 뜹니다.

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6115]
Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation that determines

version: 3.8c (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 2699 / False / 67ecd76d53d44430adc6f92e8d250591
input: https://www.xvideos.com/video53922235/porn-ja/0/_24_
type: xvideo
single: True
url: https://www.xvideos.com/video53922235/porn-ja/0/_24_
dir: C:\히 내 개인 폴더\hitomi_downloaded_xvideo
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1688283974.0193403 (23-07-02 07:46:14 UTC) - 844s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]
[0001] C:\히 내 개인 폴더\hitomi_downloaded_xvideo\Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4

[URLs]
[0001] LazyUrl(https://www.xvideos.com/video53922235/porn-ja/0/_24_)    --->    M3u8_stream(https://cdn77-vid.xvideos-cdn.com/Oa-TzLER3-NXWpNRxIZlkg==,1688294782/videos/hls/52/2e/14/522e145bfd07656caa6a3e4b23fc7d20/hls-1080p-fce20.m3u8)

[Messages]

Fail : Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4
Traceback (most recent call last):
 File "downloader", line 958, in download
OSError: [Errno 22] Invalid argument: '\\\\?\\C:\\히 내 개인 폴더\\hitomi_downloaded_xvideo\\Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4'

stop
valid=False 1
-show_streams -print_format json -v error "Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4"
{ 

} 
Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4: No such file or directory 
Traceback (most recent call last):
 File "utils", line 1795, in finish
 File "ffmpeg", line 773, in get_info
 File "ffmpeg", line 770, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.xvideos.com/video53922235/porn-ja/0/_24_  (9.7s)

('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1447, in connect
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 504, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 371, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 423, in wrap_socket
 File "ssl", line 870, in _create
 File "decorator", line 232, in fun
 File "locker", line 116, in _wrapper
 File "locker", line 55, in exec_
 File "locker", line 36, in run
 File "locker", line 116, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1369, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 834, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 915, in wrapper
 File "constants", line 884, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 531, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
invalid; revert
EOT: https://www.xvideos.com/video53922235/porn-ja/0/_24_  (7.6s)

Fail : Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4
Traceback (most recent call last):
 File "downloader", line 888, in download
OSError: [Errno 22] Invalid argument: '\\\\?\\C:\\히 내 개인 폴더\\hitomi_downloaded_xvideo\\Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4'

stop
valid=False 1
-show_streams -print_format json -v error "Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4"
{ 

} 
Cock begging masochist dying beauty 24 years old [Saddle tide climax onaho hole that fell into a female slave] Continues to be blamed only for chestnuts by impatient training, coveted Ma ● Ko unbearable flood. Continuous seeding copulation th (53922235).mp4: No such file or directory 
Traceback (most recent call last):
 File "utils", line 1869, in finish
 File "ffmpeg", line 773, in get_info
 File "ffmpeg", line 770, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.xvideos.com/video53922235/porn-ja/0/_24_  (8.4s)

https://www.xvideos.com/video53506723/_m_26_m_
https://www.xvideos.com/video50677561/_jd_21_
https://www.xvideos.com/video55211345/_x_3p_36_and_g_
https://www.xvideos.com/video54060413/s_g_
https://www.xvideos.com/video54059951/_x_27_sex_
https://www.xvideos.com/video53922235/porn-ja/0/_24_

노란색으로 오류 뜬 링크들 목록인데 전부 마지막에 _가 있네요...

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/75c15ba7-158d-4241-aaf7-e9b7f21b06e3)

https://www.xvideos.com/video53364077/_
https://www.xvideos.com/video59312899/_30_

빨간색으로 오류 뜬 2개인데 이것도 마지막에 _가 있습니다.

Invalid: [xvideo] https://www.xvideos.com/video59312899/_30_

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: -15498 / False / 79c0e7fe984e43c3b34b4f1d67072b3a
input: https://www.xvideos.com/video59312899/_30_
type: xvideo
single: True
url: https://www.xvideos.com/video59312899/_30_
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1688284669.1064286 (23-07-02 07:57:49 UTC) - 227s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1369, in getresponse
 File "http\client", line 310, in begin
 File "http\client", line 271, in _read_status
 File "socket", line 589, in readinto
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 727, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1369, in getresponse
 File "http\client", line 310, in begin
 File "http\client", line 271, in _read_status
 File "socket", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\xvideo_downloader", line 94, in read
 File "utils", line 850, in __call__
 File "extractor\xvideo_downloader", line 30, in get
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\xvideo_downloader", line 38, in _get
 File "downloader", line 459, in read_html
 File "requests\sessions", line 555, in get
 File "downloader", line 250, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 677, in send
 File "requests\sessions", line 677, in <listcomp>
 File "requests\sessions", line 245, in resolve_redirects
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://www.xvideos.com/video59312899/_30_  (170.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
