### ISSUE TITLE
트위터 다운로드가 전체적으로 잘 안되네요.

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#6125]
글이 적은 계정은 정상적으로 다운로드 됩니다.

다만 글이 많은 계정은 초반만 다운로드 하는 거 같습니다.

**Comment by qj8x67s33a44** [comment]
https://twitter.com/NIKKE_en

retry... _pagination (4)
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 566, in _pagination
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 318, in _call
Exception: 404 Not Found (Sorry, that page does not exist)

**Comment by qj8x67s33a44** [comment]
https://twitter.com/NIKKE_japan

order / group / uid: 33 / False / c8775fcf1d4d4edeb0556fb025d5948a
input: https://twitter.com/NIKKE_japan
type: twitter
single: False
url: https://twitter.com/NIKKE_japan
dir: 
zip: 
artist: 【公式】勝利の女神：NIKKE＠好評配信中
valid / done: True / False
range / range_p: None / None
time: 1688675808.4612136 (23-07-06 20:36:48 UTC) - 3140s elapsed
tags: []
lock: False
color: reading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {uids: ['1469201146418184192']}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
format: None
type: user
uid: 1469201146418184192
multiple tweets rt:False
mc: 1130
duplicate: 1604752603828867072
duplicate: 1604752603828867072
duplicate: 1600145662116761600
duplicate: 1594618093778898946
duplicate: 1580093659474640896
uid: 1469201146418184192
imgs: 913, ids: 839, ids_other: 5, types: img, video
retry... _pagination (1)
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 566, in _pagination
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 318, in _call
Exception: 404 Not Found (Sorry, that page does not exist)

이하 반복

**Comment by qj8x67s33a44** [comment]
이제 전체 다운로드는 불가능 할까요 ?

**Comment by qj8x67s33a44** [comment]
[10_52 2023-07-12.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/12022911/10_52.2023-07-12.txt)

마찬가지로 전체 다운로드가 잘 안되는 듯합니다.

**Comment by KurtBestor** [comment]
오래된 트윗은 타임라인에 나타나지 않는데 검색 기능으로 조금 더 오래된 트윗까지 가져올 수 있었어요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1028
그런데 최근에 Twitter 에서 검색에 Rate limit 를 걸어서 거의 사용할 수 없게 돼서 일단 비활성화 해두었어요

**Comment by qj8x67s33a44** [comment]
검색 기능 이라 함은 트위터 검색 기능을 말씀하시는게 맞을까요 ?

https://twitter.com/search?q=from%3Aghdckdhkd%20until%3A2022-12-31%20since%3A2022-01-01&src=typed_query

이렇게 검색 후 다운로드 시 다운로드가 안되긴 합니다.

앞으로 전체 다운로드가 불가능 ? 개선이 안될까요 ?
