### ISSUE TITLE
iwara에서 영상들이 다운이 안됩니다

### ISSUE THREAD

**Issue by mbc117** [KurtBestor/Hitomi-Downloader#6128]
Invalid: [iwara] https://www.iwara.tv/video/EWvYcRUokRZKrk/the-idolmsterrequestmodmv

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 73daa0de1fef44b0a0140a3d44787dd8
input: https://www.iwara.tv/video/EWvYcRUokRZKrk/the-idolmsterrequestmodmv
type: iwara
single: True
url: https://www.iwara.tv/video/EWvYcRUokRZKrk/the-idolmsterrequestmodmv
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1688564029.727783 (23-07-05 13:33:49 UTC) - 170s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\iwara_downloader", line 32, in read
 File "decorator", line 232, in fun
 File "constants", line 928, in wrapper
 File "constants", line 897, in wrapper
 File "extractor\iwara_downloader", line 145, in get_info
 File "clf2", line 146, in solve
Exception: clf Timeout

Invalid: fail=True
quality: 75%
EOT: https://www.iwara.tv/video/EWvYcRUokRZKrk/the-idolmsterrequestmodmv  (62.8s)

전부 이런씩으로 뜨내요

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 네트워크 설정 - 내부 웹브라우저 - 보기` 누르고 해당 링크 들어가면 어떻게 뜨나요?
