### ISSUE TITLE
유튜브가 다운이 되지 않습니다.

### ISSUE THREAD

**Issue by tokisma** [KurtBestor/Hitomi-Downloader#6136]
5분 0초 뒤 다시 시작: https://www.youtube.com/watch?v=12e98U6Tf0w

version: 3.8d+ (23-07-06 01:25:49 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / d094f5bc36624000b7dadbb7b233c2f7
input: https://www.youtube.com/watch?v=12e98U6Tf0w
type: youtube
single: True
url: https://www.youtube.com/watch?v=12e98U6Tf0w
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1688687245.518034 (23-07-06 23:47:25 UTC) - 14s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=12e98U6Tf0w
[debug] [youtube] 12e98U6Tf0w: Downloading webpage
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading m3u8 information
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 69, in get
 File "ytdl", line 565, in __init__
 File "ytdl", line 555, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2752, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2474, in _calc_headers
   cookies = self.cookiejar.get_cookies_for_url(info_dict['url'])
AttributeError: 'MyCookieJar' object has no attribute 'get_cookies_for_url'

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=12e98U6Tf0w
[debug] [youtube] 12e98U6Tf0w: Downloading webpage
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading m3u8 information
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 69, in get
 File "ytdl", line 565, in __init__
 File "ytdl", line 555, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2752, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2474, in _calc_headers
   cookies = self.cookiejar.get_cookies_for_url(info_dict['url'])
AttributeError: 'MyCookieJar' object has no attribute 'get_cookies_for_url'

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=12e98U6Tf0w
[debug] [youtube] 12e98U6Tf0w: Downloading webpage
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading m3u8 information
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 69, in get
 File "ytdl", line 565, in __init__
 File "ytdl", line 555, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2752, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2474, in _calc_headers
   cookies = self.cookiejar.get_cookies_for_url(info_dict['url'])
AttributeError: 'MyCookieJar' object has no attribute 'get_cookies_for_url'

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=12e98U6Tf0w
[debug] [youtube] 12e98U6Tf0w: Downloading webpage
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] 12e98U6Tf0w: Downloading ios player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] 12e98U6Tf0w: Downloading android player API JSON
[debug] [youtube] 12e98U6Tf0w: Downloading m3u8 information
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 69, in get
 File "ytdl", line 565, in __init__
 File "ytdl", line 555, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2752, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2474, in _calc_headers
   cookies = self.cookiejar.get_cookies_for_url(info_dict['url'])
AttributeError: 'MyCookieJar' object has no attribute 'get_cookies_for_url'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 440, in read
 File "utils", line 850, in __call__
 File "extractor\youtube_downloader", line 79, in get
 File "extractor\youtube_downloader", line 69, in get
 File "ytdl", line 565, in __init__
 File "ytdl", line 555, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2752, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2474, in _calc_headers
   cookies = self.cookiejar.get_cookies_for_url(info_dict['url'])
AttributeError: 'MyCookieJar' object has no attribute 'get_cookies_for_url'

'MyCookieJar' object has no attribute 'get_cookies_for_url'
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\youtube_downloader", line 447, in read
 File "extractor\youtube_downloader", line 440, in read
 File "utils", line 850, in __call__
 File "extractor\youtube_downloader", line 79, in get
 File "extractor\youtube_downloader", line 69, in get
 File "ytdl", line 565, in __init__
 File "ytdl", line 555, in __init__
 File "ytdl", line 440, in extract_info
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2752, in process_video_result
   format['http_headers'] = self._calc_headers(collections.ChainMap(format, info_dict))
 File "C:\Users\aibon\AppData\Local\Temp\_MEI424162\ytdl_aa8906a8\yt_dlp\yt_dlp\YoutubeDL", line 2474, in _calc_headers
   cookies = self.cookiejar.get_cookies_for_url(info_dict['url'])
AttributeError: 'MyCookieJar' object has no attribute 'get_cookies_for_url'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=12e98U6Tf0w  (14.1s)

다른 영상들도 몇개 시도해봤는데 다운로드가 안됩니다 ㅠㅠ

**Comment by KurtBestor** [comment]
프로그램 재시작하면 잘 될 거예요

**Comment by tokisma** [comment]
빠른 답변 감사드립니다 ㅠㅠ
