### ISSUE TITLE
YP doesn't download video, just m3u8 files

### ISSUE THREAD

**Issue by maticslaszlo** [KurtBestor/Hitomi-Downloader#6142]
Hello,

MyDirtyHobby - Fiona-Fuchs Enjoys A Good Fuck Outside In The Sun Before Taking A Load In Her Mouth

version: 3.8d+ (23-07-07 17:34:54 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / hu_hu
order / group / uid: 1 / False / a0d117b1da7245a4a72a1e0431d29ef5
input: https://www.youporn.com/watch/16948978/mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the-sun-before-taking-a-load-in-her-mouth/
type: youporn
single: True
url: https://www.youporn.com/watch/16948978/mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the-sun-before-taking-a-load-in-her-mouth/
dir: D:\Downloads
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1688764819.5887022 (23-07-07 21:20:19 UTC) - 454s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 2, 'overwrite': False}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] D:\Downloads\MyDirtyHobby - Fiona-Fuchs Enjoys A Good Fuck Outside In The Sun Before Taking A Load In Her Mouth (16948978).m3u8

[URLs]
[0001] LazyUrl(https://www.youporn.com/watch/16948978/mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the-sun-before-taking-a-load-in-her-mouth/)    --->    https://dv-h-ph.ypncdn.com/hls/videos/202207/20/412098791/,1080P_4000K,720P_4000K,480P_2000K,240P_1000K,_412098791.mp4.urlset/index-f1-v1-a1.m3u8?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47

[Messages]
[debug] [YouPorn] Extracting URL: https://www.youporn.com/watch/16948978/mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the...a-load-in-her-mouth/
[debug] [YouPorn] mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the-sun-before-taking-a-load-in-her-mouth: Downloading JSON metadata
[debug] [YouPorn] 16948978: Downloading m3u8 information
[debug] [YouPorn] mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the-sun-before-taking-a-load-in-her-mouth: Downloading webpage
### reset size ###
use just download: overwrite=False
stop
-show_streams -print_format json -v error "MyDirtyHobby - Fiona-Fuchs Enjoys A Good Fuck Outside In The Sun Before Taking A Load In Her Mouth (16948978).m3u8"
[hls @ 000001866cd9ca00] Filename extension of 'seg-1-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-2-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-3-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-4-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-5-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-6-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-7-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-8-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-9-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-10-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-11-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-12-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-13-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-14-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-15-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-16-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-17-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-18-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-19-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-20-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-21-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-22-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-23-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-24-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-25-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-26-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-27-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-28-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-29-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-30-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-31-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-32-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-33-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-34-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-35-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-36-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-37-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-38-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-39-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-40-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-41-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-42-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-43-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-44-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-45-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-46-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-47-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-48-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-49-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-50-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-51-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-52-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-53-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-54-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-55-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-56-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-57-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-58-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-59-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-60-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-61-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-62-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-63-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-64-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-65-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-66-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-67-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-68-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-69-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-70-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-71-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-72-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-73-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-74-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-75-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-76-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-77-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-78-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-79-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-80-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-81-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-82-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-83-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-84-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-85-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-86-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to{ 

} 
allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-87-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-88-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-89-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-90-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-91-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Filename extension of 'seg-92-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' is not a common multimedia extension, blocked for security reasons. 
If you wish to override this adjust allowed_extensions, you can set it to 'ALL' to allow all 
[hls @ 000001866cd9ca00] Error when loading first segment 'seg-1-f1-v1-a1.ts?l=0&ttl=1688772020&hash=2ac4d5c91d63e6f4ea94a6884caffa47' 
MyDirtyHobby - Fiona-Fuchs Enjoys A Good Fuck Outside In The Sun Before Taking A Load In Her Mouth (16948978).m3u8: Invalid data found when processing input 
Traceback (most recent call last):
 File "utils", line 1869, in finish
 File "ffmpeg", line 845, in get_info
 File "ffmpeg", line 842, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.youporn.com/watch/16948978/mydirtyhobby-fiona-fuchs-enjoys-a-good-fuck-outside-in-the-sun-before-taking-a-load-in-her-mouth/  (4.9s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by maticslaszlo** [comment]
Thanks. It's solved.
