### ISSUE TITLE
rule34 다운로드 불가-검색 가능, 다운로드 불가

### ISSUE THREAD

**Issue by npire3** [KurtBestor/Hitomi-Downloader#6164]
다운로더로 rule34 링크 다운로드가 안됩니다
먼저 issue에서 같은 사이트 관련한 문제들을 찾아봤는데 같은 문제 같지 않거나 제가 이해를 못한 부분이 있거나 싶고
링크 복사 붙이기, 다운로더 내부 검색창에서 이미지 번호 검색해서 다운받기 등
다양한 방식으로 시도했으나 안 되는 것 같습니다
정확히 말하면 111111 이라는 이미지 번호를 쳐서 그게 rule34의 이미지 중 111111이라는 번호를 가진 거구나 까지는 되는 거 같은데 다운로드는 못하고 있는 것 같아요

safemod나 그런 문제로는 보이지 않아 issue 작성하였습니다

Invalid: [rule34_xxx] https://rule34.xxx/index.php?page=post&s=view&id=8240318

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 7f2928effe7f4ecd815ba57f53383a41
input: https://rule34.xxx/index.php?page=post&s=view&id=8240318
type: rule34_xxx
single: False
url: https://rule34.xxx/index.php?page=post&s=view&id=8240318
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1689093940.6123123 (23-07-11 16:45:40 UTC) - 9s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Not Implemented
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\rule34_xxx_downloader", line 62, in read
 File "extractor\rule34_xxx_downloader", line 94, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://rule34.xxx/index.php?page=post&s=view&id=8240318  (1.2s)

**Comment by KurtBestor** [comment]
해당 사이트는 개별 포스트 다운로드를 지원하지 않아요
