### ISSUE TITLE
카카오페이지(카카페) 다운이 안되네요

### ISSUE THREAD

**Issue by fgkkgoe** [KurtBestor/Hitomi-Downloader#6169]
작업 정보입니다.

Invalid: [kakaopage] https://page.kakao.com/content/59787320

version: 3.8d (23-06-23 04:15:53 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 08ec64dfe868450aa3716e7deef575d4
input: https://page.kakao.com/content/59787320
type: kakaopage
single: False
url: https://page.kakao.com/content/59787320
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [1]
time: 1689249418.2567267 (23-07-13 11:56:58 UTC) - 28s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
환생표사 1화 0
Cannot query field "isWaitfreePlus" on type "Series". Did you mean "isWaitfree"?
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "extractor\kakaopage_downloader", line 61, in read
 File "extractor\kakaopage_downloader", line 619, in get_info
Exception: no imgs

Invalid: fail=True
quality: 100%
EOT: https://page.kakao.com/content/59787320  (18.1s)

**Comment by Bolined** [comment]
또 2달정도 기다려야될까요?
카카페 수정은 항상 늦게 고쳐주시더라구요... ㅠㅠ

**Comment by Hot-IcedTea** [comment]
아마 카카페는 수정이 힘들거나
개발자님이 사용을 잘 안하시는듯... ㅎㅎ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by berwgds** [comment]
작동 잘 되네요 :)

**Comment by fgkkgoe** [comment]
작동 잘 되네요 :)
