### ISSUE TITLE
PornHubPremium 쿠키 사용이 안됩니다.

### ISSUE THREAD

**Issue by li4ac1212** [KurtBestor/Hitomi-Downloader#6181]
Login required; Update your cookies
https://www.pornhubpremium.com/channels/perv-mom

version: 3.8d+ (23-07-16 15:16:31 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e29d26d5728045ac969f310b72e5f9ba
input: https://www.pornhubpremium.com/channels/perv-mom
type: pornhub
single: True
url: https://www.pornhubpremium.com/channels/perv-mom
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1689560123.10345 (23-07-17 02:15:23 UTC) - 122s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
is_login 2
is_login 1
is_login 0

stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1428, in start_
 File "decorator", line 232, in fun
 File "constants", line 904, in wrapper
 File "constants", line 902, in wrapper
 File "extractor\pornhub_downloader", line 248, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pornhubpremium.com/channels/perv-mom  (5.2s)

--------------------------------------------------------------------------------------

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/discussions/6124

**Comment by li4ac1212** [comment]
Login required; Update your cookies
https://www.pornhubpremium.com/channels/jays-pov

version: 3.8d+ (23-07-21 16:20:39 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 107644a88c9942e9bd4667f8db634fea
input: https://www.pornhubpremium.com/channels/jays-pov
type: pornhub
single: True
url: https://www.pornhubpremium.com/channels/jays-pov
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1689993333.7314775 (23-07-22 02:35:33 UTC) - 6s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
is_login 2
is_login 1
is_login 0

stop
Traceback (most recent call last):
 File "utils", line 1351, in start
 File "utils", line 1430, in start_
 File "decorator", line 232, in fun
 File "constants", line 899, in try_
 File "constants", line 897, in try_
 File "extractor\pornhub_downloader", line 248, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pornhubpremium.com/channels/jays-pov  (5.0s)


여전히 오류 뜨네요

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by li4ac1212** [comment]
Login required; Update your cookies
https://www.pornhubpremium.com/channels/jays-pov

version: 3.8d+ (23-07-22 05:01:47 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 7c8ab93f48754cc69c0494a5e530a503
input: https://www.pornhubpremium.com/channels/jays-pov
type: pornhub
single: True
url: https://www.pornhubpremium.com/channels/jays-pov
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1690091666.09659 (23-07-23 05:54:26 UTC) - 9s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
is_login 2
is_login 1
is_login 0

stop
Traceback (most recent call last):
 File "utils", line 1351, in start
 File "utils", line 1430, in start_
 File "decorator", line 232, in fun
 File "constants", line 899, in try_
 File "constants", line 897, in try_
 File "extractor\pornhub_downloader", line 248, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://www.pornhubpremium.com/channels/jays-pov  (5.0s)


여전히 쿠키 오류라고 뜹니다.

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 네트워크 - 내장 웹브라우저 - 보기` 누르고 해당 주소 들어가면 로그인 되어있다고 뜨나요?
