### ISSUE TITLE
아프리카 캐치 다운 어떤거는 되고 어떤거는 안됩니다

### ISSUE THREAD

**Issue by gibson-kim** [KurtBestor/Hitomi-Downloader#6215]
안되는 것 예시:
https://vod.afreecatv.com/player/105134415/catch
https://vod.afreecatv.com/player/105134782/catch

되는 것 예시:
https://vod.afreecatv.com/player/105134371/catch
https://vod.afreecatv.com/player/105094931/catch
https://vod.afreecatv.com/player/105133223/catch

같은 URL 형식, 같은 BJ 인데 되는 것도 있고 안되는 것도 있네요. 브라우저로 열면 전부 다 됩니다.

에러 예시:

[Messages]
url_thumb: https://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=catch_20230726_1752338_1_r
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\afreeca_downloader", line 45, in read
 File "extractor\afreeca_downloader", line 97, in get_video
IndexError: list index out of range

Invalid: fail=True
EOT: https://vod.afreecatv.com/player/105134782/catch  (2.2s)

[Messages]
url_thumb: https://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=catch_20230726_1752285_1_r
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\afreeca_downloader", line 45, in read
 File "extractor\afreeca_downloader", line 97, in get_video
IndexError: list index out of range

Invalid: fail=True
EOT: https://vod.afreecatv.com/player/105134415/catch  (1.9s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by gibson-kim** [comment]
저번에 안됐던 것들 이제 잘 됩니다. 좋은 프로그램 계속 업데이트 해주셔서 감사합니다.
