### ISSUE TITLE
3.8e 버전에서도 카카페 다운이 안됩니다

### ISSUE THREAD

**Issue by fgkkgoe** [KurtBestor/Hitomi-Downloader#6222]
작업 정보입니다.

Invalid: [kakaopage] https://page.kakao.com/content/59787320

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 593a747e5bbb4d4f98f2342fbb8e5658
input: https://page.kakao.com/content/59787320
type: kakaopage
single: False
url: https://page.kakao.com/content/59787320
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [1]
time: 1690531509.3598657 (23-07-28 08:05:09 UTC) - 29s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
환생표사 1화 0
Cannot query field "isWaitfreePlus" on type "Series". Did you mean "isWaitfree"?
no imgs
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\kakaopage_downloader", line 61, in read
 File "extractor\kakaopage_downloader", line 619, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/content/59787320  (23.9s)

**Comment by Bolined** [comment]
제발 고쳐주세요...
