### ISSUE TITLE
코믹워커 가끔 발생하는 버그

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#6231]
가끔 폴더명이 KADOKAWAの無料漫画サイト 이거로 다운로드 됩니다.

수정 가능할까요?

---------------

KADOKAWAの無料漫画サイト

version: 3.8e+ (23-07-28 02:47:14 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 5155 / False / 2d35485e54e346e086979f906a5e7927
input: https://comic-walker.com/contents/detail/KDCW_AM01100017010000_68/
type: comicwalker
single: False
url: https://comic-walker.com/contents/detail/KDCW_AM01100017010000_68/
dir: hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1690693988.3578591 (23-07-30 05:13:08 UTC) - 914s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0000.jpg
[0002] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0001.jpg
[0003] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0002.jpg
[0004] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0003.jpg
[0005] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0004.jpg
[0006] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0005.jpg
[0007] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0006.jpg
[0008] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0007.jpg
[0009] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0008.jpg
[0010] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0009.jpg
[0011] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0010.jpg
[0012] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0011.jpg
[0013] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0012.jpg
[0014] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0013.jpg
[0015] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0014.jpg
[0016] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0015.jpg
[0017] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0016.jpg
[0018] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0017.jpg
[0019] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0018.jpg
[0020] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0019.jpg
[0021] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0020.jpg
[0022] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0021.jpg
[0023] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0022.jpg
[0024] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0023.jpg
[0025] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0024.jpg
[0026] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0001 - でいとりっぱー Chapter１\0025.jpg
[0027] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0000.jpg
[0028] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0001.jpg
[0029] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0002.jpg
[0030] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0003.jpg
[0031] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0004.jpg
[0032] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0005.jpg
[0033] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0006.jpg
[0034] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0007.jpg
[0035] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0008.jpg
[0036] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0009.jpg
[0037] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0010.jpg
[0038] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0011.jpg
[0039] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0012.jpg
[0040] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0013.jpg
[0041] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0014.jpg
[0042] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0002 - でいとりっぱー Chapter２\0015.jpg
[0043] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0000.jpg
[0044] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0001.jpg
[0045] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0002.jpg
[0046] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0003.jpg
[0047] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0004.jpg
[0048] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0005.jpg
[0049] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0006.jpg
[0050] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0007.jpg
[0051] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0008.jpg
[0052] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0009.jpg
[0053] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0010.jpg
[0054] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0011.jpg
[0055] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0012.jpg
[0056] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0013.jpg
[0057] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0014.jpg
[0058] hitomi_downloaded_comicwalker\KADOKAWAの無料漫画サイト\0003 - でいとりっぱー Chapter３\0015.jpg

[URLs]
[0001] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC300EA288>
[0002] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2FD81948>
[0003] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2F6EC7C8>
[0004] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2EDD5288>
[0005] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC25079D68>
[0006] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC24EAEE88>
[0007] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC29AF8C48>
[0008] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2FD2A8E8>
[0009] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC30023C48>
[0010] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2F6EC7C8>
[0011] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC25094B88>
[0012] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2EDD5288>
[0013] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC25079D68>
[0014] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC24EAEE88>
[0015] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC29AF8C48>
[0016] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC30023C48>
[0017] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2FEB5EE8>
[0018] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC24EA09A8>
[0019] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC25094B88>
[0020] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC29B4E768>
[0021] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2FD2AD68>
[0022] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC24EAEE88>
[0023] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC30023C48>
[0024] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC2FEB5EE8>
[0025] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC25102468>
[0026] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010001_68)    --->    <_io.BytesIO object at 0x000001FC25094B88>
[0027] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2F705708>
[0028] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC300237C8>
[0029] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC25102B28>
[0030] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2FD2AF48>
[0031] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2FF0DE88>
[0032] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2F705708>
[0033] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC251290A8>
[0034] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2FEB5EE8>
[0035] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC25102468>
[0036] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC300237C8>
[0037] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2EDD5288>
[0038] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC25129048>
[0039] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2FD2AF48>
[0040] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC251290A8>
[0041] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC2F705708>
[0042] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010002_68)    --->    <_io.BytesIO object at 0x000001FC300EADC8>
[0043] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC29B4EA08>
[0044] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC300237C8>
[0045] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC25129048>
[0046] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC2EDD5288>
[0047] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC251290A8>
[0048] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC300EADC8>
[0049] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC2F705708>
[0050] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC3010E468>
[0051] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC300237C8>
[0052] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC25129048>
[0053] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC2FD2AD68>
[0054] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC300EAF48>
[0055] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC3010E3A8>
[0056] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC300EADC8>
[0057] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC3010E888>
[0058] LazyUrl(https://comic-walker.com/viewer/?tw=2&dlcl=ja&cid=KDCW_AM01100017010003_68)    --->    <_io.BytesIO object at 0x000001FC2FD2AD68>

[Messages]
stop
EOT: https://comic-walker.com/contents/detail/KDCW_AM01100017010000_68/  (6.7s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by qj8x67s33a44** [comment]
테스트 해보고 있습니다만 수정 해주신 버전은 연결이 자꾸 안됩니다.

Invalid: [comicwalker] https://comic-walker.com/contents/detail/KDCW_AM01201298010000_68/

version: 3.8e+ (23-07-30 11:11:32 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 5091 / False / b8d0b4aeda9143e391fe2082cceb540b
input: https://comic-walker.com/contents/detail/KDCW_AM01201298010000_68/
type: comicwalker
single: False
url: https://comic-walker.com/contents/detail/KDCW_AM01201298010000_68/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1690770842.8602097 (23-07-31 02:34:02 UTC) - 2713s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1358, in start
 File "utils", line 1437, in start_
 File "extractor\comicwalker_downloader", line 64, in read
 File "extractor\comicwalker_downloader", line 164, in get_imgs
 File "extractor\comicwalker_downloader", line 85, in get_imgs_page
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://comic-walker.com/contents/detail/KDCW_AM01201298010000_68/  (22.4s)
