### ISSUE TITLE
북토끼 갑자기 안되네요 

### ISSUE THREAD

**Issue by sungwooz** [KurtBestor/Hitomi-Downloader#6232]
늘 고맙게 쓰고 있습니다~

지난번 만들어주신 스크립트와 더불어 이번 업그레이드로 잘 사용하고 있습니다.
[aio_booktoki_v3.hds](https://raw.githubusercontent.com/STR-HK/hdl-stubs/main/%5BAllInOne%5D%20booktoki_v3.py)

(스크립트 가져오기 한다음에 URL 카피하고 실행해야 하는거 맞죠?) 

근데, 북토끼 URL이 바뀌어서 그런지?(그게 맞나요? 그 문제가 아닌거 같기도 하고) 갑자기 받아지지가 않습니다.

아래 에러메세지입니다.

확인 부탁드립니다 ㅠㅠㅠㅠ

늘 감사합니다....

Invalid: [booktoki] https://booktoki299.com/novel/4078203

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / f83020e84e3545239c4f9ee40224c334
input: https://booktoki299.com/novel/4078203
type: booktoki
single: False
url: https://booktoki299.com/novel/4078203
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1690785737.615667 (23-07-31 06:42:17 UTC) - 10s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "dynamic_module_0", line 29, in read
 File "dynamic_module_0", line 101, in get_artist
 File "dynamic_module_0", line 87, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki299.com/novel/4078203  (9.0s)

**Comment by writternkk** [comment]
제 개인적인 경험으로는 303으로 넘어간 뒤로 토끼네 운영진이 URL 통합에 나선 것 같습니다.
유사 사이트일 수도 있지만, newtoki.help 아래, 웹툰이 본진, 일본 만화는 /manhwa, 소설은 /book으로 나오네요.
