### ISSUE TITLE
인스타그램 다운로드 오류

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader#6233]
쿠키 오늘 일자(2023.07.31)로 최신화한 상태입니다.
작업 정보 및 내부 브라우저 상태 같이 첨부해드립니다.

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/47098778/44600d5f-4690-4890-82a1-5e459ec9ae13)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Invalid: [insta] https://www.instagram.com/loveyu_ju

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 8e70b54165e6483f8ae03f0be8649365
input: https://www.instagram.com/loveyu_ju
type: insta
single: False
url: https://www.instagram.com/loveyu_ju
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1690790613.0934901 (23-07-31 08:03:33 UTC) - 336s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\insta_downloader", line 47, in init
 File "extractor\insta_downloader", line 31, in get_session
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.instagram.com/loveyu_ju  (35.1s)

No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\insta_downloader", line 47, in init
 File "extractor\insta_downloader", line 31, in get_session
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.instagram.com/loveyu_ju  (35.1s)

No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\insta_downloader", line 47, in init
 File "extractor\insta_downloader", line 31, in get_session
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.instagram.com/loveyu_ju  (34.9s)

No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\insta_downloader", line 47, in init
 File "extractor\insta_downloader", line 31, in get_session
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.instagram.com/loveyu_ju  (34.9s)

No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\insta_downloader", line 47, in init
 File "extractor\insta_downloader", line 31, in get_session
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.instagram.com/loveyu_ju  (34.0s)

No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\insta_downloader", line 47, in init
 File "extractor\insta_downloader", line 31, in get_session
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.instagram.com/loveyu_ju  (35.0s)

**Comment by KurtBestor** [comment]
`about:blank` 링크 말고 해당 주소 들어가면 어떻게 뜨나요?

**Comment by Rounlet** [comment]
우선 크롬 통해서 들어가면 잘 들어가집니다.
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/47098778/e5a95c80-679b-4272-8624-c2d71fb48cd6)

다만 내부 웹브라우저를 통해서 보면
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/47098778/c808a870-b59e-4d99-a224-e66f4c7c290b)
인스타 주소가 뜨긴 뜨는데 아무것도 로딩되는게 없어요.
그러다가 결국에 about:blank가 뜨네요.

**Comment by KurtBestor** [comment]
프로그램 재시작해도 동일한가요?

**Comment by Rounlet** [comment]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/47098778/f95618bf-778b-468c-a9d9-247fa57a8670)
부끄럽네요.. 재시작하니까 정상 작동되었습니다.
무슨 이유인진 모르겠네요ㅠㅠ 
감사합니다.
