### ISSUE TITLE
트위터 다운 문제 발생

### ISSUE THREAD

**Issue by GaricBear** [KurtBestor/Hitomi-Downloader#6245]
몇 주 전부터 계속 이렇게 트위터 다운이 안됩니다...
이유를 알 수 있을 까요?

3분 21초 뒤 다시 시작: Invalid: [twitter] https://twitter.com/MT_azhu2

version: 3.8e+ (23-07-28 02:47:14 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 32aec7be45384faeba221d291a135652
input: https://twitter.com/MT_azhu2
type: twitter
single: False
url: https://twitter.com/MT_azhu2
dir: 
zip: 
artist: 阿朱
valid / done: False / True
range / range_p: None / None
time: 1691117636.4753036 (23-08-04 02:53:56 UTC) - 504s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {uids: ['1593644373694025728']}
live: False
changed: False

[File Names]

[URLs]

[Messages]
format: None
type: user
uid: 1593644373694025728
multiple tweets rt:True
mc: 15
Rate limit exceeded

stop
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 316, in _call
 File "requests\models", line 910, in json
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\twitter_downloader", line 156, in read
 File "extractor\twitter_downloader", line 775, in get_imgs
 File "utils", line 3781, in check_alive_iter
 File "extractor\twitter_downloader", line 503, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 319, in _call
Exception: Rate limit exceeded

Invalid: fail=True
EOT: https://twitter.com/MT_azhu2  (7.1s)

format: None
type: user
uid: 1593644373694025728
multiple tweets rt:True
mc: 15
Rate limit exceeded

stop
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 316, in _call
 File "requests\models", line 910, in json
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\twitter_downloader", line 156, in read
 File "extractor\twitter_downloader", line 775, in get_imgs
 File "utils", line 3781, in check_alive_iter
 File "extractor\twitter_downloader", line 503, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 319, in _call
Exception: Rate limit exceeded

Invalid: fail=True
EOT: https://twitter.com/MT_azhu2  (8.9s)

format: None
type: user
uid: 1593644373694025728
multiple tweets rt:True
mc: 15
Rate limit exceeded

stop
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 316, in _call
 File "requests\models", line 910, in json
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\twitter_downloader", line 156, in read
 File "extractor\twitter_downloader", line 775, in get_imgs
 File "utils", line 3781, in check_alive_iter
 File "extractor\twitter_downloader", line 503, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 319, in _call
Exception: Rate limit exceeded

Invalid: fail=True
EOT: https://twitter.com/MT_azhu2  (7.8s)

format: None
type: user
uid: 1593644373694025728
multiple tweets rt:True
mc: 15
Rate limit exceeded

stop
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 316, in _call
 File "requests\models", line 910, in json
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\twitter_downloader", line 156, in read
 File "extractor\twitter_downloader", line 775, in get_imgs
 File "utils", line 3781, in check_alive_iter
 File "extractor\twitter_downloader", line 503, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 319, in _call
Exception: Rate limit exceeded

Invalid: fail=True
EOT: https://twitter.com/MT_azhu2  (104.9s)

**Comment by GaricBear** [comment]
이유는 모르지만 해결 되었습니다...
한달 정도 뭘해도 안되어서 난감했었는데...
왜 갑자기 정상 다운이 되는거지.....

**Comment by KurtBestor** [comment]
Rate limit 넘어가면 필요한 시간만큼 쉬고 다시 시도하게 했어요

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by GaricBear** [comment]
> Rate limit 넘어가면 필요한 시간만큼 쉬고 다시 시도하게 했어요
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

지금은 다시 다운이 정상적으로 되는데 테스트 버전으로 다시 테스트 해보면 되는건가요?

**Comment by KurtBestor** [comment]
나중에 같은 오류가 생기면 그 때 바꿔서 쓰셔도 되고 그냥 바꿔서 쓰셔도 돼요

**Comment by GaricBear** [comment]
일일히 수정본으로 개인에게 주실 줄은 몰랐어요...
고생 많으십니다...

2023년 8월 8일 (화) 오후 4:18, Kurt Bestor ***@***.***>님이 작성:
