### ISSUE TITLE
Imgur 이 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by yeonggille** [KurtBestor/Hitomi-Downloader#6247]
안녕하세요, 언제나 고생 많으십니다.
다름이 아니고 imgur 본 사이트에서 다운로드 하려고 하면 오류 트레이스가 아무것도 남지 않은 채 다운로드가 되지 않습니다.
특별한 사유가 있는건 아니고 json에 뭔가 이상이 있는것도 같은데, 확인을 부탁드립니다.
감사합니다.

Invalid: [imgur] https://imgur.com/a/c8nHV

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 1 / False / e001470ae489496485b95aa9bdfde37e
input: https://imgur.com/a/c8nHV
type: imgur
single: False
url: https://imgur.com/a/c8nHV
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1691181769.9870954 (23-08-04 20:42:49 UTC) - 53s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\imgur_downloader", line 15, in init
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\imgur_downloader", line 59, in get_info
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://imgur.com/a/c8nHV  (5.7s)

**Comment by syuan666** [comment]
me too

**Comment by KurtBestor** [comment]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/14768120/aeba7332-1d2b-4a00-9277-8a4f04c22303)

재현할 수 없네요

**Comment by syuan666** [comment]
Ok


從我的iPhone傳送
