### ISSUE TITLE
트위터 다운로드시 로그인 필요

### ISSUE THREAD

**Issue by DaHoon-Jeong** [KurtBestor/Hitomi-Downloader#6292]
어제까지 문제가 없었는데 오늘부터 로그인 하라는 메시지가 나옵니다.
로그인을 하려면 안전하지 않은 브라우저라고 팅기네요..

Login required; Please login: 404 Not Found
https://twitter.com/i/status/1683772045203763201

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 1513ab8ec17c4db5b2a8348d913c5886
input: https://twitter.com/i/status/1683772045203763201
type: twitter
single: False
url: https://twitter.com/i/status/1683772045203763201
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1692717235.7971137 (23-08-22 15:13:55 UTC) - 263s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
format: None
type: single
404 Not Found
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\twitter_downloader", line 119, in read
 File "decorator", line 232, in fun
 File "constants", line 899, in try_
 File "constants", line 897, in try_
 File "extractor\twitter_downloader", line 1121, in get_artist_username
 File "extractor\twitter_downloader", line 433, in tweet
 File "extractor\twitter_downloader", line 503, in _pagination_tweets
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\twitter_downloader", line 312, in _call
extractor.twitter_downloader.LoginRequired: 404 Not Found

Invalid: fail=False
EOT: https://twitter.com/i/status/1683772045203763201  (0.3s)

**Comment by DaHoon-Jeong** [comment]
전체 쿠키를 업데이트 하니 다시 작동이 됩니다. 민망하네요;
