### ISSUE TITLE
틱톡이 다운이 안됩니다

### ISSUE THREAD

**Issue by wjrayzeus** [KurtBestor/Hitomi-Downloader#6293]
틱톡이 아예 다 안되긴 하는데 그 중 하나 작업 정보 올립니다

Invalid: [tiktok] https://www.tiktok.com/@jemima.c.robinson

version: 3.8e+ (23-08-18 16:19:31 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: -1040 / False / 734a52e00a1746af9d123770b578b435
input: https://www.tiktok.com/@jemima.c.robinson
type: tiktok
single: True
url: https://www.tiktok.com/@jemima.c.robinson
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1692717880.2428863 (23-08-22 15:24:40 UTC) - 629s elapsed
tags: ['red']
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
no html
items: 0
empty
not f
items: 0
empty
not f
items: 0
empty
not f
items: 0
empty
not f
items: 0
empty
no items
stop
Traceback (most recent call last):
 File "utils", line 1358, in start
 File "utils", line 1437, in start_
 File "extractor\tiktok_downloader", line 70, in read
 File "extractor\tiktok_downloader", line 192, in read_channel
Exception: no items

Invalid: fail=True
EOT: https://www.tiktok.com/@jemima.c.robinson  (90.8s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
