### ISSUE TITLE
비리비리 영상 다운이 되지 않습니다. 

### ISSUE THREAD

**Issue by yoondain** [KurtBestor/Hitomi-Downloader#6301]
techical preview 버전과 공식 버전으로 둘 다 쿠키도 넣고 다운로드 해 봤는데 다른 영상들은 잘 다운 되는 반면 이 영상은 다운이 되지 않습니다. 

비리비리 영상 링크: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69

=========================
공식 버전
=========================
Invalid: [bili] https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 9595e1d5962243eb968a8f429835238e
input: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
type: bili
single: True
url: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1692886308.3828497 (23-08-24 14:11:48 UTC) - 66s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69 -> https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
sd: c37fd0ee%2C1708071034%2Cffea4%2A81uQkyJOrqWa1aYsC4Hyo9MPJzsQJtAGTiOy1-eEkh82JHqAtODdpcGOOHvDmyJGNvNFxIAgAABQA
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
ERROR: [BiliBili] BV1Ex411W7Vv_p2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 2732, in process_video_result
   self.raise_no_formats(info_dict)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 1074, in raise_no_formats
   expected=has_drm or ignored or expected)
yt_dlp.utils.ExtractorError: [BiliBili] BV1Ex411W7Vv_p2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\bili_downloader", line 119, in read
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\bili_downloader", line 151, in get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI205562\ytdl_78701802\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [BiliBili] BV1Ex411W7Vv_p2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69  (22.2s)

========================

테스트 버전
=========================
Invalid: [bili] https://www.bilibili.com/video/BV1Ex411W7Vv?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69

version: 3.8e+ (23-08-23 02:00:38 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 06e99b1ba4fe44f8913161cb36b7e374
input: https://www.bilibili.com/video/BV1Ex411W7Vv?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
type: bili
single: True
url: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1692848926.3703785 (23-08-24 03:48:46 UTC) - 37373s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
redirect: https://www.bilibili.com/video/BV1Ex411W7Vv?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69 -> https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
sd: 7aaf6956%2C1708399579%2Cdb991%2A81cjaUmsym0YYf2sR-LsZM8QbTcbim9Pr9DnDTE62CFCMUTj7csGUkPo15dhOTPrcnDXR4pQAABQA
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ex411W7Vv/?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69
[debug] [BiliBili] 1Ex411W7Vv: Downloading webpage
[debug] [BiliBili] BV1Ex411W7Vv: Extracting videos in anthology
[debug] [BiliBili] Format(s) 1080P 高清, 360P 流畅, 480P 清晰, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [BiliBili] 12657695: Extracting chapters
[debug] [BiliBili] BV1Ex411W7Vv: Downloading JSON metadata
[debug] [info] BV1Ex411W7Vv_p2: Downloading subtitles: danmaku
[warning] No subtitle format found matching "vtt" for language danmaku, using xml
ERROR: [BiliBili] BV1Ex411W7Vv_p2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 1709, in __extract_info
   return self.process_ie_result(ie_result, download, extra_info)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 1768, in process_ie_result
   ie_result = self.process_video_result(ie_result, download=download)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 2732, in process_video_result
   self.raise_no_formats(info_dict)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 1074, in raise_no_formats
   expected=has_drm or ignored or expected)
yt_dlp.utils.ExtractorError: [BiliBili] BV1Ex411W7Vv_p2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1358, in start
 File "utils", line 1437, in start_
 File "extractor\bili_downloader", line 203, in read
 File "utils", line 4557, in ready
 File "decorator", line 232, in fun
 File "constants", line 929, in try_
 File "constants", line 898, in try_
 File "extractor\bili_downloader", line 45, in get
 File "ytdl", line 450, in extract_info
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\yoond\AppData\Local\Temp\_MEI220362\ytdl_de65cbec\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 407, in report_error
yt_dlp.utils.DownloadError: ERROR: [BiliBili] BV1Ex411W7Vv_p2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://www.bilibili.com/video/BV1Ex411W7Vv?p=2&vd_source=2a2e3cb30cb82038adfffa043be18a69  (51.9s)

**Comment by KurtBestor** [comment]
[yt-dlp](https://github.com/yt-dlp/yt-dlp/issues?q=)에 문의해주세요
