### ISSUE TITLE
xHamster 다운이 안됩니다ㅜㅜ;

### ISSUE THREAD

**Issue by darknarciss** [KurtBestor/Hitomi-Downloader#6318]
8분 16초 뒤 다시 시작: Invalid: [xhamster] https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 932386b82aba455097c8d647c0cfd07d
input: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705
type: xhamster
single: True
url: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1693609053.97906 (23-09-01 22:57:33 UTC) - 107s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (2.9s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (3.0s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (2.9s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (2.9s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (2.9s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (3.0s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (3.2s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (3.7s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (3.1s)

'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 854, in __call__
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster.com/videos/himiko-13-japanese-beauties-922705  (3.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by darknarciss** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

휴~~~ 이제야 되네요^^ 너무 감사합니다~~~
