### ISSUE TITLE
텀블러 이거 안되는거 맞나요?

### ISSUE THREAD

**Issue by sb2941** [KurtBestor/Hitomi-Downloader#6333]
Invalid: [tumblr] https://www.tumblr.com/zumidraws

version: 3.8e+ (23-09-09 06:12:40 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 09ebf5c3a5bf478eb7ce466136d3af4c
input: https://www.tumblr.com/zumidraws
type: tumblr
single: False
url: https://www.tumblr.com/zumidraws
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1694258811.3777943 (23-09-09 11:26:51 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no id
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\tumblr_downloader", line 57, in read
 File "extractor\tumblr_downloader", line 208, in get_id
Exception: no id

Invalid: fail=True
quality: 75%
EOT: https://www.tumblr.com/zumidraws  (0.8s)

no id
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\tumblr_downloader", line 57, in read
 File "extractor\tumblr_downloader", line 208, in get_id
Exception: no id

Invalid: fail=True
quality: 75%
EOT: https://www.tumblr.com/zumidraws  (0.7s)

no id
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\tumblr_downloader", line 57, in read
 File "extractor\tumblr_downloader", line 208, in get_id
Exception: no id

Invalid: fail=True
quality: 75%
EOT: https://www.tumblr.com/zumidraws  (0.7s)

no id
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\tumblr_downloader", line 57, in read
 File "extractor\tumblr_downloader", line 208, in get_id
Exception: no id

Invalid: fail=True
quality: 75%
EOT: https://www.tumblr.com/zumidraws  (0.8s)

**Comment by xel04** [comment]
안녕하세요. 저도 겪은 문제인데 아쉬운대로 zumidraws.tumblr.com <-- 주소를 이 형식으로 넣어보시겠어요? 저는 이 방식으로 됐습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by sb2941** [comment]
이제 https://www.tumblr.com/zumidraws로도 다시 되네요!

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/75178740/51d2ad92-7fa9-4cdd-a58e-03861cd65f9d)

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/75178740/930607ed-750d-4215-8649-4e89c217107f)
