### ISSUE TITLE
트위터 특정 계정이 읽는 도중에 중지됨

### ISSUE THREAD

**Issue by xel04** [KurtBestor/Hitomi-Downloader#6348]
안녕하세요. 트위터 몇몇 계정이 다운을 시도하면 읽는 도중에 오류가 납니다.
작업정보는 아래와 같습니다.

Invalid: [twitter] https://twitter.com/bobobo_boi

version: 3.8e+ (23-09-09 04:32:17 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 217 / False / 04c947aa2ba34aa1857d8e75d265f2dc
input: https://twitter.com/bobobo_boi
type: twitter
single: False
url: https://twitter.com/bobobo_boi
dir: 
zip: 
artist: ボボボAp-B 単行本『恥育玩具』発売中
valid / done: False / True
range / range_p: None / None
time: 1694698015.8945346 (23-09-14 13:26:55 UTC) - 51s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {uids: ['88758639']}
live: False
changed: True

[File Names]

[URLs]

[Messages]
format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (26.5s)

format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
duplicate: 1344715496357122048
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (27.8s)

format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
duplicate: 1344715496357122048
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (27.3s)

format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (26.3s)

format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
duplicate: 1344715496357122048
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (27.6s)

format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
duplicate: 1344715496357122048
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (27.2s)

format: None
type: user
uid: 88758639
multiple tweets rt:False
mc: 1929
call... UserMedia
duplicate: 1624739643500683266
duplicate: 1602570928298213376
duplicate: 1508847798032420866
duplicate: 1344715496357122048
call... UserMedia
duplicate: 1315905597825458176
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
call... UserMedia
duplicate: 674360289521897472
call... UserMedia
_Missing: User not found., Authorization: Denied by access control: Missing LdapGroup(visibility-admins); Missing LdapGroup(visibility-custom-suspension)
twitpic: http://twitpic.com/ddmklk
twitpic: http://twitpic.com/ddmb14
call... UserMedia
call... UserMedia
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\twitter_downloader", line 151, in read
 File "extractor\twitter_downloader", line 829, in get_imgs
 File "extractor\twitter_downloader", line 829, in <lambda>
 File "extractor\twitter_downloader", line 717, in id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Invalid: fail=True
EOT: https://twitter.com/bobobo_boi  (26.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by xel04** [comment]
잘 됩니다. 감사합니다!

**Comment by yoob859** [comment]
비슷한 오류인것 같은데 같은 방법으로 해결이 안되네요 확인부탁합니다!

Invalid: [twitter] https://x.com/ordan

version: 4.2+ (25-12-15 17:14:30 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / d9c3c3821b2d475b836f491401bc9f0c
input: https://x.com/ordan
type: twitter
single: False
url: https://x.com/ordan
dir: 
zip: 
artist: おるだん
valid / done: False / True
range / range_p: None / None
time: 1766666966.5504766 (25-12-25 12:49:26 UTC) - 201s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2025.12.08
pinned: False
extras: {uids: ['14994185']}
live: False
changed: True


[File Names]



[URLs]



[Messages]
format: None
type: user
uid: 14994185
multiple tweets rt:True
mc: 1479
call... UserTweets
duplicate: 2003673796709073218
call... UserTweets
duplicate: 2001944080302113208
duplicate: 1999451220722012586
call... UserTweets
duplicate: 1973717296469430712
call... UserTweets
duplicate: 1990007539652862394
call... UserTweets
duplicate: 1986743453125108068
duplicate: 1986078071112520085
call... UserTweets
duplicate: 1984992388205760753
duplicate: 1981903542756446378
duplicate: 1968981735162433749
call... UserTweets
duplicate: 1978318681676661061
duplicate: 1968981735162433749
call... UserTweets
duplicate: 1974009026859225451
duplicate: 1973714583211909557
duplicate: 1973717296469430712
call... UserTweets
duplicate: 1973016154504573028
duplicate: 1973016154504573028
duplicate: 1968981735162433749
call... UserTweets
duplicate: 1968910545404227599
duplicate: 1964649634384752816
duplicate: 1964646614477508905
duplicate: 1964641042193318115
duplicate: 1964641042193318115
call... UserTweets
duplicate: 1962157209259053401
call... UserTweets
duplicate: 1963935148195385641
duplicate: 1962157209259053401
duplicate: 1962157209259053401
duplicate: 1960919579875750279
call... UserTweets
duplicate: 1958092248941535703
duplicate: 1956159736954675388
call... UserTweets
duplicate: 1953856399227670941
duplicate: 1953856399227670941
duplicate: 1953742996597301302
call... UserTweets
'result'
stop
Traceback (most recent call last):
 File "utils", line 1417, in start
 File "utils", line 1507, in start_
 File "#script_6", line 161, in read
 File "#script_6", line 923, in get_imgs
 File "utils", line 4076, in check_alive_iter
 File "#script_6", line 712, in _pagination_tweets
KeyError: 'result'

Invalid: fail=True
EOT: https://x.com/ordan  (169.7s)
