### ISSUE TITLE
Hitomi Downloader不能下载？

### ISSUE THREAD

**Issue by sunandaji** [KurtBestor/Hitomi-Downloader#6367]
spankbang.com的视频Hitomi Downloader不能下载？
https://spankbang.com/717mr/video/sexy+softcore+slides+2

**Comment by sunandaji** [comment]
???

**Comment by sunandaji** [comment]
Softcore Slides

**Comment by sunandaji** [comment]
Softcore SlidesInvalid: [etc] https://spankbang.com/717mr/video/sexy+softcore+slides+2

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / zh_cn
order / group / uid: 0 / False / 0ad10e27a7484c42aac139641dc14f3a
input: https://spankbang.com/717mr/video/sexy+softcore+slides+2
type: etc
single: True
url: https://spankbang.com/717mr/video/sexy+softcore+slides+2
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1695351702.0848706 (23-09-22 03:01:42 UTC) - 677s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
extractor: spankbang
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 837, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 432, in urlopen
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 3863, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\utils\_utils", line 1515, in https_open
   functools.partial(_create_http_connection, self, conn_class, True), req, **kwargs)
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1688, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 710, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\spankbang", line 76, in _real_extract
   video_id, headers={'Cookie': 'country=US'})
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 1113, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 1064, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 898, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 855, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 64, in get_video
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\etc_downloader", line 95, in _get_video
 File "extractor\etc_downloader", line 91, in _get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\etc_downloader", line 28, in read
 File "extractor\etc_downloader", line 76, in get_video
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\etc_downloader", line 95, in _get_video
 File "extractor\etc_downloader", line 91, in _get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))

Invalid: fail=True
EOT: https://spankbang.com/717mr/video/sexy+softcore+slides+2  (321.8s)

extractor: spankbang
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: True, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
get_video: False, https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] Extracting URL: https://spankbang.com/717mr/video/sexy+softcore+slides+2
[debug] [SpankBang] 717mr: Downloading webpage
ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 944, in connect
 File "socket", line 728, in create_connection
 File "socket", line 716, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 837, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 432, in urlopen
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 3863, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\utils\_utils", line 1515, in https_open
   functools.partial(_create_http_connection, self, conn_class, True), req, **kwargs)
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1688, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 710, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\spankbang", line 76, in _real_extract
   video_id, headers={'Cookie': 'country=US'})
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 1113, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 1064, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 898, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\extractor\common", line 855, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 64, in get_video
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\etc_downloader", line 95, in _get_video
 File "extractor\etc_downloader", line 91, in _get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\etc_downloader", line 28, in read
 File "extractor\etc_downloader", line 76, in get_video
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\etc_downloader", line 95, in _get_video
 File "extractor\etc_downloader", line 91, in _get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI149242\ytdl_23c8430b\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 717mr: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))

I
