### ISSUE TITLE
comic walker error

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#6368]
Invalid: [comicwalker] https://comic-walker.com/contents/detail/KDCW_FS04204346010000_68/

version: 3.8e+ (23-09-20 02:08:58 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 8b3c95c026ac4afc8c4e923c73f4f38c
input: https://comic-walker.com/contents/detail/KDCW_FS04204346010000_68/
type: comicwalker
single: False
url: https://comic-walker.com/contents/detail/KDCW_FS04204346010000_68/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1695352238.127293 (23-09-22 03:10:38 UTC) - 10s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\comicwalker_downloader", line 64, in read
 File "extractor\comicwalker_downloader", line 164, in get_imgs
 File "extractor\comicwalker_downloader", line 85, in get_imgs_page
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://comic-walker.com/contents/detail/KDCW_FS04204346010000_68/  (1.9s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
