### ISSUE TITLE
카카오페이지 다운이 안되네요

### ISSUE THREAD

**Issue by berwgds** [KurtBestor/Hitomi-Downloader#6386]
수정한지 얼마나 됐다고 벌써 막혔네요.
작업 정보입니다.

Invalid: [kakaopage] https://page.kakao.com/content/54471153

version: 3.8e+ (23-09-20 02:08:58 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / eae9125022874ec2be388e36f0e163da
input: https://page.kakao.com/content/54471153
type: kakaopage
single: False
url: https://page.kakao.com/content/54471153
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1695628371.369671 (23-09-25 07:52:51 UTC) - 11s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'data'
stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\kakaopage_downloader", line 61, in read
 File "extractor\kakaopage_downloader", line 572, in get_info
 File "extractor\kakaopage_downloader", line 230, in get_pages
KeyError: 'data'

Invalid: fail=True
quality: 100%
EOT: https://page.kakao.com/content/54471153  (7.6s)

**Comment by Bolined** [comment]
저도 글을 남겼는데... 오늘 3시부터 다운이 안되네요
또 고쳐지려면 2달정도 기다려야될까요... ㅠㅠ

이번엔 너무 빨리 막혔네요

**Comment by Hot-IcedTea** [comment]
업뎃 된줄 모르고 있었네요...
매일 전체 글 확인을 하고 있을 수도 없고...
아직 3.8e버전이길래 방심했는데...
너무 아쉽네요 ㅠㅠ

**Comment by rakukracha** [comment]
저는 그거보다 소설류 폰트 바뀐거 때문에 미치겠네요.
가독성이 영 떨어져서 그냥 캡쳐하는 것조차 보기 싫어졌습니다.
아니 카카페 사이트 업데이트를 하려면 폰트 좀 봐가면서 해야지,
폰에서 보는건 멀쩡한데 PC 웹브라우저로 보는건 폰트가 개 쓰레기가 됐네요.
