### ISSUE TITLE
How do i get ffmpeg.exe back?

### ISSUE THREAD

**Issue by VanishingBlaze** [KurtBestor/Hitomi-Downloader#6396]

**Comment by KurtBestor** [comment]
Can you show me the task info?

**Comment by VanishingBlaze** [comment]
しぐれうい（9さい）が躍るだけ #shorts

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 5 / False / c890f29a4b654e0a9201b5611c8541c5
input: https://www.youtube.com/shorts/A-M0zMeG_Ec
type: youtube
single: True
url: https://www.youtube.com/shorts/A-M0zMeG_Ec
dir: hitomi_downloaded_youtube
zip: 
artist: しぐれうい
valid / done: False / True
range / range_p: None / None
time: 1696002672.2591722 (23-09-29 15:51:12 UTC) - 426389s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: mp4
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: False


[File Names]
[0001] hitomi_downloaded_youtube\しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4


[URLs]
[0001] LazyUrl(https://www.youtube.com/shorts/A-M0zMeG_Ec)    --->    https://rr4---sn-hp57ynlr.googlevideo.com/videoplayback?expire=1696024199&ei=J_IWZczEJoqjy_sPh8uR8AQ&ip=2600%3A1700%3A59a0%3A34b0%3A1173%3Ae627%3A4bac%3A1946&id=o-AJJp6Pdl3NpHc1l963QpS-EPUPpmp3jQrpfqjos2VQ2d&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=v7&mm=31%2C26&mn=sn-hp57ynlr%2Csn-5uaeznyz&ms=au%2Conr&mv=m&mvi=4&pl=41&initcwndbps=773750&spc=UWF9f7ImT-LuU40UxQxmae3xxYaTmfkbHZ9kFkpARg&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Br-7qJXEmI78a0yLf0StZIAP&gir=yes&clen=7531323&dur=13.886&lmt=1694773154366329&mt=1696002121&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=WEB&txp=553C434&n=o5ucMSaSKUwQcQ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIOL_9mX2F8qJ_9tcIaqx6yFSfXXnGtpbcC6waCg_IH8AiEAhKY3k0_ejh9WHP_vhW71bp9mjcrVguO62kVYDZ8xlbo%3D&sig=AOq0QJ8wRQIgdPIY43heRbZyzefHgb87EzyjHiNey7w8q-WrVHva-U0CIQDxPX3bF-06m3nYDPyTNZaxLJFYagzGwUr0HOkl0Fd33g%3D%3D


[Messages]
[debug] [youtube] Extracting URL: https://www.youtube.com/shorts/A-M0zMeG_Ec
[debug] [youtube] A-M0zMeG_Ec: Downloading webpage
[debug] [youtube] A-M0zMeG_Ec: Downloading ios player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] A-M0zMeG_Ec: Downloading ios player API JSON
Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 555, in get
 File "utils", line 972, in request
 File "downloader", line 250, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 114, in _wrapper
Exception: Timeout2

use just download: overwrite=True
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (2/3)...
[debug] [youtube] A-M0zMeG_Ec: Downloading ios player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (3/3)...
[debug] [youtube] A-M0zMeG_Ec: Downloading ios player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [youtube] A-M0zMeG_Ec: Downloading android player API JSON

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (1/3)...
[debug] [youtube] A-M0zMeG_Ec: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (2/3)...
[debug] [youtube] A-M0zMeG_Ec: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] HTTP Error 401: Unauthorized. Retrying (3/3)...
[debug] [youtube] A-M0zMeG_Ec: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[warning] [youtube] Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[warning] [youtube] Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] A-M0zMeG_Ec: Downloading player f7e1823a
retry (1)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

live: not_live
retry (2)
[27p][7.142857142857143fps][None][None] mhtml [None / None] ─ sb0 - 48x27 (storyboard)
[None][0fps][48.978kbps][48.978] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][64.789kbps][64.789] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.893kbps][129.893] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][125.654kbps][125.654] webm [None / opus] ─ 251 - audio only (medium)
[144p][24fps][None][84.443] mp4 [av01.0.00M.08 / None] ─ 394 - 144x256 (144p)
[144p][24fps][None][111.035] mp4 [avc1.4d400c / None] ─ 160 - 144x256 (144p)
[144p][24fps][None][86.545] webm [vp9 / None] ─ 278 - 144x256 (144p)
[240p][24fps][None][186.65] mp4 [av01.0.00M.08 / None] ─ 395 - 240x426 (240p)
[240p][24fps][None][245.002] mp4 [avc1.4d4015 / None] ─ 133 - 240x426 (240p)
[240p][24fps][None][188.572] webm [vp9 / None] ─ 242 - 240x426 (240p)
[360p][24fps][None][417.042] mp4 [av01.0.01M.08 / None] ─ 396 - 360x640 (360p)
[360p][24fps][None][633.808] mp4 [avc1.4d401e / None] ─ 134 - 360x640 (360p)
[360p][24fps][96.0kbps(fixed)][905.607] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 360x640 (360p)
[360p][24fps][None][402.309] webm [vp9 / None] ─ 243 - 360x640 (360p)
[480p][24fps][None][616.053] mp4 [av01.0.04M.08 / None] ─ 397 - 480x854 (480p)
[480p][24fps][None][1159.665] mp4 [avc1.4d401e / None] ─ 135 - 480x854 (480p)
[480p][24fps][None][611.908] webm [vp9 / None] ─ 244 - 480x854 (480p)
[720p][24fps][None][1049.373] mp4 [av01.0.05M.08 / None] ─ 398 - 720x1280 (720p)
[720p][24fps][None][1961.673] mp4 [avc1.4d401f / None] ─ 136 - 720x1280 (720p)
[720p][24fps][None][1451.515] webm [vp9 / None] ─ 247 - 720x1280 (720p)
[1080p][24fps][None][2568.231] mp4 [av01.0.08M.08 / None] ─ 399 - 1080x1920 (1080p)
[1080p][24fps][None][4338.944] mp4 [avc1.640028 / None] ─ 137 - 1080x1920 (1080p)
[1080p][24fps][None][2554.749] webm [vp9 / None] ─ 248 - 1080x1920 (1080p)

utime: 1694649600.0

# stream_final
[1080p][24fps][None][4338.944] mp4 [avc1.640028 / None] ─ 137 - 1080x1920 (1080p)

[None][0fps][48.978kbps][48.978] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][64.789kbps][64.789] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.893kbps][129.893] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][125.654kbps][125.654] webm [None / opus] ─ 251 - audio only (medium)
[360p][24fps][96.0kbps(fixed)][905.607] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 360x640 (360p)

[None][0fps][129.893kbps][129.893] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[360p][24fps][96.0kbps(fixed)][905.607] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 360x640 (360p)

[None][0fps][129.893kbps][129.893] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)

filename: しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4
Resolution: None
Codec: None / mp4a.40.2
Abr: 129.893
Subtype: m4a
FPS: 0

Download audio: https://rr4---sn-hp57ynlr.googlevideo.com/videoplayback?expire=1696024199&ei=J_IWZczEJoqjy_sPh8uR8AQ&ip=2600%3A1700%3A59a0%3A34b0%3A1173%3Ae627%3A4bac%3A1946&id=o-AJJp6Pdl3NpHc1l963QpS-EPUPpmp3jQrpfqjos2VQ2d&itag=140&source=youtube&requiressl=yes&mh=v7&mm=31%2C26&mn=sn-hp57ynlr%2Csn-5uaeznyz&ms=au%2Conr&mv=m&mvi=4&pl=41&initcwndbps=773750&spc=UWF9f7ImT-LuU40UxQxmae3xxYaTmfkbHZ9kFkpARg&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=Br-7qJXEmI78a0yLf0StZIAP&gir=yes&clen=226583&dur=13.955&lmt=1694773085218980&mt=1696002121&fvip=4&keepalive=yes&fexp=24007246&beids=24350018&c=WEB&txp=5532434&n=o5ucMSaSKUwQcQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTNkIoUO1C7czm9V_BepS2tKltWmsqNXfEKvYgUVVvb0CIFXmZa0NLhiyRufp5ioI8RtASr98pk2KvgeOgFUiVENZ&sig=AOq0QJ8wRAIgEDP0gDajYPUhu7gkc4Iza_npBnvFfugY4Ki3SemwCXUCIFD3Y_4Lo5Wfj8jwnPmV49h43w-lb-L6HQdBW5CudAho

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

use just download: overwrite=True
thumb: https://i.ytimg.com/vi/A-M0zMeG_Ec/sddefault.jpg
retry (3)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (4)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (5)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (6)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (7)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

audio done
Convert: D:\Downloads-data drive\hitomi_downloader_GUI\hitomi_downloaded_youtube\しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4
rename (1): C:\Users\vanis\AppData\Local\Temp\21e97bbc2fdf4150994deed9506a4e80_a.tmp -> D:\Downloads-data drive\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp198a228232e54bbba59eb29bb5dadee6_a.weba
rename (1): D:\Downloads-data drive\hitomi_downloader_GUI\hitomi_downloaded_youtube\しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4 -> D:\Downloads-data drive\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp198a228232e54bbba59eb29bb5dadee6_v.mp4
-i tmp198a228232e54bbba59eb29bb5dadee6_v.mp4 -i tmp198a228232e54bbba59eb29bb5dadee6_a.weba -c:v copy -c:a copy -strict experimental -preset ultrafast -threads 0 tmp198a228232e54bbba59eb29bb5dadee6_o.mp4
retry (8)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (9)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (10)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (11)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (12)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (13)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (14)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (15)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (16)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (17)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (18)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (19)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (20)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (21)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (22)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (23)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

【ffmpeg】 load...
【ffmpeg】 download...
Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 555, in get
 File "utils", line 972, in request
 File "downloader", line 250, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 655, in send
 File "requests\adapters", line 449, in send
 File "urllib3\connectionpool", line 677, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 160, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 752, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 114, in _wrapper
Exception: Timeout2

use just download: overwrite=True

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (1)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (2)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (3)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (4)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (5)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (6)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (7)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (8)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (9)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (10)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (11)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (12)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (13)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (14)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (15)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (16)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (17)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (18)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (19)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (20)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (21)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (22)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

retry (23)

Fail : \\?\C:\Users\vanis\AppData\Local\Temp\ffmpeg.exe
Traceback (most recent call last):
 File "downloader", line 1133, in download
 File "downloader", line 724, in __init__
PermissionError: [Errno 13] Permission denied: '\\\\?\\C:\\Users\\vanis\\AppData\\Local\\Temp\\ffmpeg.exe'

Lazyurl pp Error: hitomi_downloaded_youtube\しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 418, in run
 File "hitomi_downloader", line 411, in pp_
 File "extractor\youtube_downloader", line 302, in pp
 File "ffmpeg", line 281, in merge
 File "ffmpeg", line 160, in run
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ffmpeg", line 128, in load
Exception: Failed to download

utime Error: hitomi_downloaded_youtube\しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 432, in run
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'hitomi_downloaded_youtube\\しぐれうい（9さい）が躍るだけ\u3000#shorts (A-M0zMeG_Ec).mp4'

stop
-show_streams -print_format json -v error "しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4"
{ 

} 
しぐれうい（9さい）が躍るだけ #shorts (A-M0zMeG_Ec).mp4: No such file or directory 
Traceback (most recent call last):
 File "utils", line 1928, in finish
 File "ffmpeg", line 850, in get_info
 File "ffmpeg", line 847, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.youtube.com/shorts/A-M0zMeG_Ec  (243.7s)
