### ISSUE TITLE
flickr api key expired?

### ISSUE THREAD

**Issue by albyofdoom** [KurtBestor/Hitomi-Downloader#6410]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/12314939/c4a34a07-5f2e-4019-a9b6-d1934a6f5971)

```Invalid: [flickr] https://www.flickr.com/photos/andrilucas/

version: 3.8e+ (23-09-27 17:26:18 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / a576b336811940a7bd7db11326bca79b
input: https://www.flickr.com/photos/andrilucas/
type: flickr
single: False
url: https://www.flickr.com/photos/andrilucas/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1696155175.7932498 (23-10-01 10:12:55 UTC) - 150s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 79, in auth
Exception: {'status': 'bad', 'token': '72157720895617162-eca542bb1c046993', 'code': None}

Traceback (most recent call last):
 File "flickr_auth", line 31, in get_api
 File "flickr_auth", line 62, in auth
 File "flickr_auth", line 97, in auth
Exception: Auth timeout ^q^

Auth Failed:
Traceback (most recent call last):
 File "flickr_auth", line 31, in get_api
 File "flickr_auth", line 62, in auth
 File "flickr_auth", line 97, in auth
Exception: Auth timeout ^q^

stop
Traceback (most recent call last):
 File "flickr_auth", line 31, in get_api
 File "flickr_auth", line 62, in auth
 File "flickr_auth", line 97, in auth
Exception: Auth timeout ^q^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1365, in start
 File "utils", line 1444, in start_
 File "extractor\flickr_downloader", line 82, in read
 File "extractor\flickr_downloader", line 71, in name
 File "flickr_auth", line 35, in get_api
Exception: Auth Failed:
Traceback (most recent call last):
 File "flickr_auth", line 31, in get_api
 File "flickr_auth", line 62, in auth
 File "flickr_auth", line 97, in auth
Exception: Auth timeout ^q^


Invalid: fail=True
EOT: https://www.flickr.com/photos/andrilucas/  (140.7s)
```

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by albyofdoom** [comment]
@KurtBestor It got further, but still failed, just at a different point. 

```Invalid: [flickr] https://www.flickr.com/photos/andrilucas

version: 3.8e+ (23-10-04 02:29:37 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / en_us
order / group / uid: 0 / False / 22840adf255e4f7b8fa7708cc754e836
input: https://www.flickr.com/photos/andrilucas
type: flickr
single: False
url: https://www.flickr.com/photos/andrilucas
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1696390279.4020681 (23-10-04 03:31:19 UTC) - 94s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
https://www.flickr.com/photos/andrilucas/page1
https://www.flickr.com/photos/andrilucas/page2
https://www.flickr.com/photos/andrilucas/page3
https://www.flickr.com/photos/andrilucas/page4
https://www.flickr.com/photos/andrilucas/page5
https://www.flickr.com/photos/andrilucas/page6
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1365, in start
 File "utils", line 1444, in start_
 File "extractor\flickr_downloader", line 91, in read
 File "clf2", line 191, in solve
 File "extractor\flickr_downloader", line 74, in f
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.flickr.com/photos/andrilucas  (65.8s)
```
