### ISSUE TITLE
deviantart error

### ISSUE THREAD

**Issue by MiaoXi90010** [KurtBestor/Hitomi-Downloader#6420]
Everything worked fine when I downloaded Twitter. But I got an error when I downloaded deviantart(https://www.deviantart.com/yare-yare-dong/gallery/all).
Task info

Invalid: [deviant] https://yare-yare-dong.deviantart.com

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.17763-SP0 / zh_cn
order / group / uid: 0 / False / bff0254cc3d1486aab5c246b87edd66a
input: https://yare-yare-dong.deviantart.com
type: deviant
single: False
url: https://yare-yare-dong.deviantart.com
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1696346115.6843033 (23-10-03 15:15:15 UTC) - 1223s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
404 Client Error: Not Found for url: https://www.deviantart.com/_napi/da-user-profile/api/gallery/contents?username=yare-yare-dong&offset=0&limit=24&all_folder=true&mode=newest
stop
Traceback (most recent call last):
 File "urllib\request", line 1350, in do_open
 File "http\client", line 1277, in request
 File "http\client", line 1323, in _send_request
 File "http\client", line 1272, in endheaders
 File "http\client", line 1032, in _send_output
 File "http\client", line 972, in send
 File "http\client", line 1439, in connect
 File "http\client", line 948, in connect
 File "http\client", line 922, in _tunnel
 File "http\client", line 279, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 432, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 543, in _open
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 1393, in https_open
 File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error Remote end closed connection without response>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\deviant_downloader", line 174, in read
 File "extractor\deviant_downloader", line 194, in get_devs
 File "extractor\deviant_downloader", line 37, in read_html
 File "downloader", line 465, in read_html
 File "requests\models", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.deviantart.com/_napi/da-user-profile/api/gallery/contents?username=yare-yare-dong&offset=0&limit=24&all_folder=true&mode=newest

Invalid: fail=True
EOT: https://yare-yare-dong.deviantart.com  (5.5s)

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/issues/6025#issuecomment-1732978687
