### ISSUE TITLE
YouTube无效识别

### ISSUE THREAD

**Issue by babayaka999** [KurtBestor/Hitomi-Downloader#6453]
Invalid: [youtube] https://www.youtube.com/watch?v=qDzwVyd2CQw

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / zh_cn
order / group / uid: 0 / False / 12d0909d91124a8a9ca1b22d6a0e5119
input: https://www.youtube.com/watch?v=qDzwVyd2CQw
type: youtube
single: True
url: https://www.youtube.com/watch?v=qDzwVyd2CQw
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1696772993.9506605 (23-10-08 13:49:53 UTC) - 1053s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp None
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 70, in get
 File "ytdl", line 552, in __init__
 File "ytdl", line 349, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ytdl", line 315, in get_ytdl
 File "ytdl", line 309, in get_ytdl
 File "ytdl", line 405, in patch_ytdl
AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 70, in get
 File "ytdl", line 552, in __init__
 File "ytdl", line 349, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ytdl", line 315, in get_ytdl
 File "ytdl", line 309, in get_ytdl
 File "ytdl", line 405, in patch_ytdl
AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 70, in get
 File "ytdl", line 552, in __init__
 File "ytdl", line 349, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ytdl", line 315, in get_ytdl
 File "ytdl", line 309, in get_ytdl
 File "ytdl", line 405, in patch_ytdl
AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 70, in get
 File "ytdl", line 552, in __init__
 File "ytdl", line 349, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ytdl", line 315, in get_ytdl
 File "ytdl", line 309, in get_ytdl
 File "ytdl", line 405, in patch_ytdl
AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 443, in read
 File "utils", line 854, in __call__
 File "extractor\youtube_downloader", line 80, in get
 File "extractor\youtube_downloader", line 70, in get
 File "ytdl", line 552, in __init__
 File "ytdl", line 349, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ytdl", line 315, in get_ytdl
 File "ytdl", line 309, in get_ytdl
 File "ytdl", line 405, in patch_ytdl
AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'

type object 'YoutubeDL' has no attribute '_setup_opener'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\youtube_downloader", line 450, in read
 File "extractor\youtube_downloader", line 443, in read
 File "utils", line 854, in __call__
 File "extractor\youtube_downloader", line 80, in get
 File "extractor\youtube_downloader", line 70, in get
 File "ytdl", line 552, in __init__
 File "ytdl", line 349, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 63, in _wrapper
 File "ytdl", line 315, in get_ytdl
 File "ytdl", line 309, in get_ytdl
 File "ytdl", line 405, in patch_ytdl
AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=qDzwVyd2CQw  (182.5s)

**Comment by sdpigpig** [comment]
delete the config file "hitomi_downloader_GUI.ini" solve

**Comment by KurtBestor** [comment]
Please update to the latest version (3.8f)

**Comment by ixsk** [comment]
still can not work

**Comment by babayaka999** [comment]
最新版本还是无法工作

**Comment by 3118903208FAN** [comment]
The latest version (3.8f) still can not work.
