### ISSUE TITLE
기본 데이터 다운로드가 안돼요

### ISSUE THREAD

**Issue by BlueJong** [KurtBestor/Hitomi-Downloader#6457]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/147426302/9266cb6c-a6d6-4202-83bf-b573f3012e91)

삭제된 데이터는 잘 받아지는데 기본 데이터 다운로드는 안되네요

Traceback (most recent call last):
  File "urllib\request", line 1350, in do_open
  File "http\client", line 1277, in request
  File "http\client", line 1323, in _send_request
  File "http\client", line 1272, in endheaders
  File "http\client", line 1032, in _send_output
  File "http\client", line 972, in send
  File "http\client", line 1439, in connect
  File "http\client", line 944, in connect
  File "socket", line 728, in create_connection
  File "socket", line 716, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 430, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 543, in _open
  File "urllib\request", line 503, in _call_chain
  File "urllib\request", line 1393, in https_open
  File "urllib\request", line 1352, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connection", line 160, in _new_conn
  File "urllib3\util\connection", line 84, in create_connection
  File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool", line 677, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 309, in connect
  File "urllib3\connection", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000284E3078EC8>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 449, in send
  File "urllib3\connectionpool", line 727, in urlopen
  File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kurtpyanywhere.com', port=443): Max retries exceeded with url: /h_data (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000284E3078EC8>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 457, in read_html
  File "requests\sessions", line 555, in get
  File "downloader", line 248, in session_request
  File "requests\sessions", line 542, in request
  File "requests\sessions", line 655, in send
  File "requests\adapters", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kurtpyanywhere.com', port=443): Max retries exceeded with url: /h_data (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000284E3078EC8>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

자세한 정보보기 누르면 이렇게 나와요 ㅠ

**Comment by RDR2PCWHEN** [comment]
저도 같은 증상을 겪고 있습니다.
