### ISSUE TITLE
PH download issues

### ISSUE THREAD

**Issue by r2bec3a** [KurtBestor/Hitomi-Downloader#6464]
Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / zh_cn
order / group / uid: 1 / False / 1cfaa6edfbe84da69e5807f2035a0524
input: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1696995885.133341 (23-10-11 03:44:45 UTC) - 120s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
id: ph615d2e8381d3f
Video
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f
[debug] [PornHub] ph615d2e8381d3f: Downloading pc webpage
id: ph615d2e8381d3f
Video
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f
[debug] [PornHub] ph615d2e8381d3f: Downloading pc webpage
id: ph615d2e8381d3f
Video
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f
[debug] [PornHub] ph615d2e8381d3f: Downloading pc webpage
id: ph615d2e8381d3f
Video
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f
[debug] [PornHub] ph615d2e8381d3f: Downloading pc webpage
Unable to handle request: Unsupported proxy type: "https" (urllib)
stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\pornhub_downloader", line 286, in read
 File "utils", line 867, in __call__
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\pornhub_downloader", line 143, in get
 File "ytdl", line 464, in extract_info
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\pornhub", line 285, in _real_extract
   webpage = dl_webpage('pc')
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\pornhub", line 283, in dl_webpage
   video_id, 'Downloading %s webpage' % platform)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\pornhub", line 38, in _download_webpage_handle
   ret = dl(*args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\pornhub", line 36, in dl
   return super(PornHubBaseIE, self)._download_webpage_handle(*args, **kwargs)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI58242\ytdl_b15b8850\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph615d2e8381d3f  (16.5s)

**Comment by 179798071** [comment]
I'm having the same problem. How do I fix this?

**Comment by KurtBestor** [comment]
Can you share your proxy setting? It's in `Options - Preferences - Network - Proxy`

**Comment by r2bec3a** [comment]
> 您可以分享您的代理设置吗？在里面`Options - Preferences - Network - Proxy`

![003](https://github.com/KurtBestor/Hitomi-Downloader/assets/147575673/7d9fec51-c155-4ba2-9c42-b2595d605750)

**Comment by Aprilday** [comment]
3.8f，same problem

**Comment by KurtBestor** [comment]
How about this?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by r2bec3a** [comment]
> How about this?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

it works,thank you.

**Comment by qhghong** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview，its works，great
