### ISSUE TITLE
크롬 쿠키 불러오기 + 유튜브 성인제한 다운로드 에러

### ISSUE THREAD

**Issue by anatobedcry** [KurtBestor/Hitomi-Downloader#6479]
히토미 다운로더 내에 Chrome 쿠키를 추출하려고 하는 경우
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 9711, in loadCookiesFromBrowser
  File "cooker", line 286, in extract_cookies_from_browser
  File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI229242\ytdl_33c5416d\yt_dlp\yt_dlp\cookies", line 112, in extract_cookies_from_browser
    return _extract_chrome_cookies(browser_name, profile, keyring, logger)
  File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI229242\ytdl_33c5416d\yt_dlp\yt_dlp\cookies", line 281, in _extract_chrome_cookies
    cursor = _open_database_copy(cookie_database_path, tmpdir)
  File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI229242\ytdl_33c5416d\yt_dlp\yt_dlp\cookies", line 1042, in _open_database_copy
    shutil.copy(database_path, database_copy_path)
  File "shutil", line 248, in copy
  File "shutil", line 120, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\(사용자명)\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
가 뜹니다.

크롬 내장 플러그인으로 유튜브 쿠키를 추출해서 다운로드하려고 해도 역시 로그인을 해야된다며 에러가 뜹니다
계정은 이미 성인제한이 풀려있는 상태며, 내장 웹에서도 들어가지는걸 확인할 수 있었습니다.
VPN이나 애드블록도 꺼져있습니다.

아래는 성인제한을 다운받으려고 할때 나오는 에러 메세지입니다.

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\youtube", line 4173, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 1193, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 601, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 402, in report_error
 File "ytdl", line 398, in login_required
errors.LoginRequired: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\youtube", line 4173, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 1193, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 601, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 402, in report_error
 File "ytdl", line 398, in login_required
errors.LoginRequired: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\youtube", line 4173, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 1193, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 601, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 402, in report_error
 File "ytdl", line 398, in login_required
errors.LoginRequired: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
[warning] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[warning] No video formats found!
[warning] Requested format is not available
live: not_live
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex
[debug] [youtube] YTFwJ5MOi1A: Downloading webpage
[debug] [youtube] YTFwJ5MOi1A: Downloading ios player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading tv embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading android creator player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded client config
[debug] [youtube] YTFwJ5MOi1A: Downloading player 99faf012
[debug] [youtube] YTFwJ5MOi1A: Downloading web embedded player API JSON
[debug] [youtube] YTFwJ5MOi1A: Downloading web creator player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\youtube", line 4173, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 1193, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 601, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 402, in report_error
 File "ytdl", line 398, in login_required
errors.LoginRequired: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

Traceback (most recent call last):
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\youtube", line 4173, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 1193, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 451, in read
 File "utils", line 4673, in ready
 File "extractor\youtube_downloader", line 64, in get
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 601, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 402, in report_error
 File "ytdl", line 398, in login_required
errors.LoginRequired: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

[youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.
stop
Traceback (most recent call last):
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\youtube", line 4173, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\extractor\common", line 1193, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "extractor\youtube_downloader", line 458, in read
 File "extractor\youtube_downloader", line 451, in read
 File "utils", line 4673, in ready
 File "extractor\youtube_downloader", line 64, in get
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 601, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\LIMHYE~1\AppData\Local\Temp\_MEI361162\ytdl_3b08c054\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 402, in report_error
 File "ytdl", line 398, in login_required
errors.LoginRequired: [youtube] YTFwJ5MOi1A: Sign in to confirm your age. This video may be inappropriate for some users.

Invalid: fail=False
EOT: https://youtu.be/YTFwJ5MOi1A?si=9ikbPxlLMCtwh9ex  (28.2s)

**Comment by ny-k** [comment]
yt-dlp developers can fix this issue.

https://github.com/yt-dlp/yt-dlp/issues
