### ISSUE TITLE
Sankakucomplex 가 다운로드가 되지않습니다

### ISSUE THREAD

**Issue by DogFunfun** [KurtBestor/Hitomi-Downloader#6483]
항상 잘쓰고있습니다 
언젠가부터 다운될떄도 있고 안될때도 있어서 질문글을 올려봅니다
Invalid: [sankaku] https://chan.sankakucomplex.com/ko/post/show/d8bf3d5de86c796db9af8163c952a588

version: 3.8f+ (23-10-13 02:15:25 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 4 / False / 62fe346dd28f48a5b58b02905a297915
input: https://chan.sankakucomplex.com/ko/post/show/d8bf3d5de86c796db9af8163c952a588
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/post/show/d8bf3d5de86c796db9af8163c952a588
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1697271424.241543 (23-10-14 08:17:04 UTC) - 510s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1457, in start_
 File "extractor\sankaku_downloader", line 132, in read
 File "extractor\sankaku_downloader", line 128, in name
 File "utils", line 664, in __get__
 File "extractor\sankaku_downloader", line 115, in id
 File "extractor\sankaku_downloader", line 336, in get_id
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/post/show/d8bf3d5de86c796db9af8163c952a588  (3.0s)

Invalid: [sankaku] https://chan.sankakucomplex.com/ko/post/show/244585494f14c1d9c9cf0d23736cb835

version: 3.8f+ (23-10-13 02:15:25 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 3 / False / 2070060b52f64d69bb3d2357e428f187
input: https://chan.sankakucomplex.com/ko/post/show/244585494f14c1d9c9cf0d23736cb835
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/post/show/244585494f14c1d9c9cf0d23736cb835
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1697271429.6422646 (23-10-14 08:17:09 UTC) - 515s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1457, in start_
 File "extractor\sankaku_downloader", line 132, in read
 File "extractor\sankaku_downloader", line 128, in name
 File "utils", line 664, in __get__
 File "extractor\sankaku_downloader", line 115, in id
 File "extractor\sankaku_downloader", line 336, in get_id
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/post/show/244585494f14c1d9c9cf0d23736cb835  (3.1s)

안되는것도 더 많지만 일단 두개 먼저 올려봅니다 
다 안되는것도 아니라 잘 되는건 잘되서 혼자 이것저것해보왔는데도 안됩니다 ( ini지우기, 버전 업그레이드, 쿠키, dns 꺼보기)

**Comment by KurtBestor** [comment]
개별 포스트는 지원하지 않아요
