### ISSUE TITLE
Sankaku problem

### ISSUE THREAD

**Issue by lollos73** [KurtBestor/Hitomi-Downloader#6501]
hi
from testerday i can't download anything all result as the same of this, is one my problem or changed something?

Restart in 2m 33s: Invalid: [sankaku] https://chan.sankakucomplex.com/it/?tags=*deleted*
version: 3.8f+ (23-10-06 10:27:48 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / it_it
order / group / uid: 0 / False / f11de91fe3534de08ec40dfeb1f3c66a
input: https://chan.sankakucomplex.com/it/?tags=*deleted*
type: sankaku
single: False
url: https://chan.sankakucomplex.com/it/?tags=*deleted*
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1697866108.1028545 (23-10-21 05:28:28 UTC) - 173s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/it/?tags=*deleted*
https://chan.sankakucomplex.com/it/?tags=*deleted*&next=32985208&page=2
https://chan.sankakucomplex.com/it/?tags=*deleted*&next=32344562&page=3
https://chan.sankakucomplex.com/it/?tags=*deleted*&next=32270743&page=4
https://chan.sankakucomplex.com/it/?tags=*deleted*x&next=32270094&page=5
Traceback (most recent call last):
 File "extractor\sankaku_downloader", line 309, in get_imgs
KeyError: 'next-page-url'

no images
stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 325, in get_imgs
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/it/?tags=*deleted*  (25.7s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
