### ISSUE TITLE
아트스테이션 안되는거같아요.

### ISSUE THREAD

**Issue by sb2941** [KurtBestor/Hitomi-Downloader#6516]
https://www.artstation.com/666kart

이걸로 했을 때

====

Invalid: [artstation] https://www.artstation.com/666kart

version: 3.8f+ (23-10-27 02:04:38 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 2 / False / 1e945a3f607c49088ad809b767f485b9
input: https://www.artstation.com/666kart
type: artstation
single: False
url: https://www.artstation.com/666kart
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1698390924.3551464 (23-10-27 07:15:24 UTC) - 177s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (8.3s)

no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (11.8s)

no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (9.9s)

no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (9.3s)

no html
no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (12.0s)

no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (9.3s)

no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (9.3s)

no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://www.artstation.com/666kart  (8.8s)

====

https://666kart.artstation.com/

이걸로 했을 때

====

Invalid: [artstation] https://666kart.artstation.com/

version: 3.8f+ (23-10-27 02:04:38 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 505698b5a7874b34a8b827df52df7078
input: https://666kart.artstation.com/
type: artstation
single: False
url: https://www.artstation.com/666kart
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1698391041.5728755 (23-10-27 07:17:21 UTC) - 78s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
no html
enter captcha
wait captcha...
wait clf...
wait clf...
wait clf...
wait clf...
no html
no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://666kart.artstation.com/  (23.8s)

no html
enter captcha
wait captcha...
wait captcha...
wait clf...
wait clf...
wait clf...
wait clf...
no html
type: None, id: 666kart
https://www.artstation.com/666kart
albums: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1474, in start_
Exception: empty urls

Invalid: fail=True
quality: 75%
EOT: https://666kart.artstation.com/  (19.0s)

====

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by sb2941** [comment]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/75178740/65d214c7-57b6-4b34-b7a8-4770327a15b7)

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/75178740/b6c86f2e-d80c-4599-9c24-d3a9744b7a8b)

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/75178740/3951b4bc-8d58-4201-8cb4-2109b1fb5647)

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/75178740/e908f341-1774-4d70-9907-5fc1230096c6)

이제 잘 되네요.
