### ISSUE TITLE
트위터 다운로드시 오류 발생

### ISSUE THREAD

**Issue by vipvirn** [KurtBestor/Hitomi-Downloader#6517]
30분~1시간은 잘되다가 아래처럼 오류가 뜹니다
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 616, in write_config_safe
  File "hitomi_downloader_GUI", line 736, in write_config
  File "hitomi_downloader_GUI", line 757, in _write_config
  File "decorator", line 232, in fun
  File "MyConfigParser", line 40, in w
  File "MyConfigParser", line 22, in w
  File "MyConfigParser", line 129, in set
sqlite3.OperationalError: unable to open database file

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
