### ISSUE TITLE
deviant error

### ISSUE THREAD

**Issue by yp123111** [KurtBestor/Hitomi-Downloader#6536]
I have logged in, but there is still an error

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / zh_cn
order / group / uid: -431 / False / ec24741ad25b42219c08771cfcbca899
input: https://ohshinakai.deviantart.com
type: deviant
single: False
url: https://ohshinakai.deviantart.com
dir: hitomi_downloaded_deviant\ohshinakai (deviant_ohshinakai)
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1698879505.3185785 (23-11-01 22:58:25 UTC) - 34s elapsed
tags: []
lock: False
color: reading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
mature content: https://www.deviantart.com/ohshinakai/art/Busty-Ghost-Spider-973499384
mature content: https://www.deviantart.com/ohshinakai/art/Gigantic-breasts-in-lingerie-Citra-973539935
mature content: https://www.deviantart.com/ohshinakai/art/Stretched-to-the-limit-Milana-Mei-976415723
mature content: https://www.deviantart.com/ohshinakai/art/See-Told-ya-I-can-eat-em-without-hands-Kinsley-974328351
mature content: https://www.deviantart.com/ohshinakai/art/Citra-and-Kinsley-movie-night-Who-s-the-biggest-974032950
mature content: https://www.deviantart.com/ohshinakai/art/College-Student-Saga-Breast-Expansion-978214039
mature content: https://www.deviantart.com/ohshinakai/art/College-Student-Allison-Transformation-981404524
mature content: https://www.deviantart.com/ohshinakai/art/I-like-humans-971411391
mature content: https://www.deviantart.com/ohshinakai/art/Gigantic-Faye-and-Her-Busty-Girlfriends-981733420
mature content: https://www.deviantart.com/ohshinakai/art/Melissa-and-her-busty-friend-Shania-978647082
mature content: https://www.deviantart.com/ohshinakai/art/Poor-Milana-experiencing-some-unexpected-growth-976086637
mature content: https://www.deviantart.com/ohshinakai/art/Well-are-you-just-gonna-stare-at-me-Citra-975047551
mature content: https://www.deviantart.com/ohshinakai/art/C-Could-you-get-something-from-the-store-981755033
mature content: https://www.deviantart.com/ohshinakai/art/Kobeni-with-massive-breasts-970559304
mature content: https://www.deviantart.com/ohshinakai/art/Ginormous-Gabbie-Breast-Expansion-985975954
mature content: https://www.deviantart.com/ohshinakai/art/Enormous-Kinsley-in-extravagant-dress-979443365
mature content: https://www.deviantart.com/ohshinakai/art/Spider-Gwen-waiting-in-her-bedroom-976254782
mature content: https://www.deviantart.com/ohshinakai/art/A-very-pregnant-elf-Zorana-975632843
mature content: https://www.deviantart.com/ohshinakai/art/Look-what-you-did-to-me-husband-971205596
mature content: https://www.deviantart.com/ohshinakai/art/Amelia-got-a-big-bigger-966789880
mature content: https://www.deviantart.com/ohshinakai/art/Beautiful-and-busty-Safiyah-973676559
mature content: https://www.deviantart.com/ohshinakai/art/Miss-Moore-can-you-please-button-your-shirt-981387048
mature content: https://www.deviantart.com/ohshinakai/art/Intense-dreams-Kinsley-980973249
mature content: https://www.deviantart.com/ohshinakai/art/Ready-for-you-daily-elven-bath-Kinsley-974001753
mature content: https://www.deviantart.com/ohshinakai/art/Stretched-to-the-limit-Makima-971452732
mature content: https://www.deviantart.com/ohshinakai/art/Hey-Big-Sis-Notice-anything-different-969978030
mature content: https://www.deviantart.com/ohshinakai/art/Jealous-Sister-Part-I-970038241
mature content: https://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953
mature content: https://www.deviantart.com/ohshinakai/art/Well-it-fit-fine-this-morning-Rowen-973831806
mature content: https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-I-967677947
mature content: https://www.deviantart.com/ohshinakai/art/Must-be-something-in-the-foods-Valerie-967390567
mature content: https://www.deviantart.com/ohshinakai/art/Ready-for-your-morning-jog-Zorana-975632828
mature content: https://www.deviantart.com/ohshinakai/art/How-can-I-make-it-up-Kimberly-976048984
mature content: https://www.deviantart.com/ohshinakai/art/What-a-curious-feeling-Alicia-975020766
mature content: https://www.deviantart.com/ohshinakai/art/Oh-Princess-Fiona-975260157
mature content: https://www.deviantart.com/ohshinakai/art/You-came-looking-for-me-973496923
mature content: https://www.deviantart.com/ohshinakai/art/Bailey-too-big-for-her-uniform-969650552
mature content: https://www.deviantart.com/ohshinakai/art/Busty-and-Preggo-Citra-970209700
mature content: https://www.deviantart.com/ohshinakai/art/Ready-to-praise-The-Goddess-974339985
mature content: https://www.deviantart.com/ohshinakai/art/Vanessa-got-huge-970815495
mature content: https://www.deviantart.com/ohshinakai/art/What-do-you-mean-I-am-covered-up-Shelby-973971962
mature content: https://www.deviantart.com/ohshinakai/art/Mr-Zhu-would-you-please-step-into-my-office-967904943
mature content: https://www.deviantart.com/ohshinakai/art/A-very-pregnant-elf-Citra-971200116
mature content: https://www.deviantart.com/ohshinakai/art/What-this-is-MY-study-outfit-Shanoli-975464972
mature content: https://www.deviantart.com/ohshinakai/art/Gigantic-breasts-Rowen-973840724
mature content: https://www.deviantart.com/ohshinakai/art/Massive-breasts-Shannary-978911515
mature content: https://www.deviantart.com/ohshinakai/art/Kinsley-with-gigantic-breasts-973693855
mature content: https://www.deviantart.com/ohshinakai/art/Sexy-lingerie-966623449
mature content: https://www.deviantart.com/ohshinakai/art/Amelia-do-we-have-any-bigger-uniforms-968041858
mature content: https://www.deviantart.com/ohshinakai/art/Are-you-sure-you-want-to-try-my-drink-Shanoli-975524705
mature content: https://www.deviantart.com/ohshinakai/art/Busty-Royce-ready-to-serve-some-hot-beverages-974754839
mature content: https://www.deviantart.com/ohshinakai/art/Citra-with-huge-belly-and-boobs-975037408
mature content: https://www.deviantart.com/ohshinakai/art/Willelma-with-enormous-breasts-in-pink-top-977221163
mature content: https://www.deviantart.com/ohshinakai/art/Busty-Brunette-in-3D-style-952837671
mature content: https://www.deviantart.com/ohshinakai/art/Guess-Kinsley-sleeps-on-the-side-973988004
mature content: https://www.deviantart.com/ohshinakai/art/Enormous-Kinsley-in-pink-dress-973704167
mature content: https://www.deviantart.com/ohshinakai/art/Research-Director-Susu-967883587
mature content: https://www.deviantart.com/ohshinakai/art/Busty-Bimbo-Charlotte-966164703
mature content: https://www.deviantart.com/ohshinakai/art/Sanna-in-pink-sleepwear-950037578
mature content: https://www.deviantart.com/ohshinakai/art/Unexpected-growth-during-work-Jing-973811888
mature content: https://www.deviantart.com/ohshinakai/art/Gigantic-breasts-Sena-972024062
mature content: https://www.deviantart.com/ohshinakai/art/Eira-964991097
mature content: https://www.deviantart.com/ohshinakai/art/Lady-Barozzi-waiting-for-her-supper-968362592
mature content: https://www.deviantart.com/ohshinakai/art/Sexy-brunette-with-huge-fake-boobs-958891211
mature content: https://www.deviantart.com/ohshinakai/art/Busty-Bailey-in-school-uniform-969659083
mature content: https://www.deviantart.com/ohshinakai/art/Bimbo-Ciri-in-the-house-959925046
mature content: https://www.deviantart.com/ohshinakai/art/Wanna-take-bath-with-me-Kinsley-973988013
mature content: https://www.deviantart.com/ohshinakai/art/Starbucks-Mermaid-with-some-humongous-boobs-957863352
mature content: https://www.deviantart.com/ohshinakai/art/Holding-on-to-dear-life-Aniya-972440644
mature content: https://www.deviantart.com/ohshinakai/art/You-deserve-a-break-today-look-at-my-boobies-954476839

stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "extractor\deviant_downloader", line 79, in read
 File "extractor\deviant_downloader", line 156, in get_files
 File "decorator", line 232, in fun
 File "constants", line 874, in try_
 File "constants", line 872, in try_
 File "extractor\deviant_downloader", line 154, in foo
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\deviant_downloader", line 14, in wait
 File "utils", line 3889, in check_alive
errors.StopReading

Stopped: fail=False
EOT: https://ohshinakai.deviantart.com  (171.4s)

mature content: https://www.deviantart.com/ohshinakai/art/Jealous-Sister-Part-I-970038241
mature content: https://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953
mature content: https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-I-967677947
mature content: https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-II-968677227

File error (https://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4673, in ready
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\deviant_downloader", line 106, in get
Exception: no img

File error (https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-I-967677947):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4673, in ready
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\deviant_downloader", line 106, in get
Exception: no img

File error (https://www.deviantart.com/ohshinakai/art/Jealous-Sister-Part-I-970038241):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4673, in ready
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\deviant_downloader", line 106, in get
Exception: no img

File error (https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-II-968677227):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4673, in ready
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\deviant_downloader", line 106, in get
Exception: no img

stop
EOT: https://ohshinakai.deviantart.com  (3209.7s)

![20231102065822157](https://github.com/KurtBestor/Hitomi-Downloader/assets/27836359/d071590f-c458-4e4c-98b1-d85d3960b358)

**Comment by yp123111** [comment]
> 读取中... https://ohshinakai.deviantart.com
> 
> 版本：3.8f（23-10-05 11:50:20 UTC） 平台/区域设置：Windows-10-10.0.18362-SP0/zh_cn 订单/组/uid：-431/False/ec24741ad25b42219c08771cfcbca899 输入：[https:// ohshinakai.deviantart.com](https://ohshinakai.deviantart.com) 类型: deviant single: False url: https://ohshinakai.deviantart.com dir: hitomi_downloaded_deviant\ohshinakai (deviant_ohshinakai) zip: 艺术家: 无 有效/完成: True / False 范围 / range_p: 无 / 无 时间：1698879505.3185785（23-11-01 22:58:25 UTC）- 34秒已用 标签：[] 锁定：假 颜色：阅读 暂停：假 格式：无 p2f：无 段：无 admin: True goodbyedpi: True ytdl: yt_dlp 2023.10.07 固定: False 额外内容: {} live: False 更改: True
> 
> [文件名]
> 
> [网址]
> 
> [留言] 熟女内容：https://www.deviantart.com/ohshinakai/art/Busty-Ghost-Spider-973499384 熟女内容： https: [//www.deviantart.com/ohshinakai/art/Gigantic-breasts-in-内衣-Citra-973539935](https://www.deviantart.com/ohshinakai/art/Gigantic-breasts-in-lingerie-Citra-973539935) 成熟内容：https://www.deviantart.com/ohshinakai/art/Stretched-to-the-limit-Milana-Mei-976415723 成熟内容： https: [//www.deviantart.com/ohshinakai/ art/See-Told-ya-I-can-eat-em-without-hands-Kinsley-974328351](https://www.deviantart.com/ohshinakai/art/See-Told-ya-I-can-eat-em-without-hands-Kinsley-974328351) 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Citra-and-Kinsley-movie-night- Who-s-the-biggest-974032950](https://www.deviantart.com/ohshinakai/art/Citra-and-Kinsley-movie-night-Who-s-the-biggest-974032950) 成熟内容：https://www.deviantart.com/ohshinakai/art/College-Student-Saga-Breast-Expansion-978214039 成熟内容：https://www.deviantart.com/ohshinakai/art/College-Student-Allison-Transformation-981404524 成熟内容：[https://www.deviantart.com/ohshinakai/art/I-like-](https://www.deviantart.com/ohshinakai/art/I-like-humans-971411391) humans-971411391 成熟内容：https://www.deviantart.com/ohshinakai/art/Gigantic-Faye-and-Her-Busty-Girlfriends-981733420 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Melissa-and-her- busty-friend-Shania-978647082](https://www.deviantart.com/ohshinakai/art/Melissa-and-her-busty-friend-Shania-978647082) 成熟内容：https://www.deviantart.com/ohshinakai/art/Poor-Milana-experiencing-some-unexpected-growth-976086637 成熟内容：[https://www.deviantart.com/ ohshinakai/art/Well-are-you-just-gonna-stare-at-me-Citra-975047551](https://www.deviantart.com/ohshinakai/art/Well-are-you-just-gonna-stare-at-me-Citra-975047551) 成熟内容：https://www.deviantart.com/ohshinakai/art/C-Could-you-get-something-from-the-store-981755033 成熟内容：[https://www.deviantart.com/ohshinakai/art/Kobeni- with-massive-breasts-970559304](https://www.deviantart.com/ohshinakai/art/Kobeni-with-massive-breasts-970559304) 成熟内容：https://www.deviantart.com/ohshinakai/art/Ginormous-Gabbie-Breast-Expansion-985975954 成熟内容： https: [//www.deviantart.com/ohshinakai/art/ Enormous-Kinsley-in-extravagant-dress-979443365](https://www.deviantart.com/ohshinakai/art/Enormous-Kinsley-in-extravagant-dress-979443365) 成熟内容： https [://www.deviantart.com/ohshinakai/art/Spider-Gwen-waiting-in-her-bedroom-976254782](https://www.deviantart.com/ohshinakai/art/Spider-Gwen-waiting-in-her-bedroom-976254782) 成熟内容：[https://www. deviantart.com/ohshinakai/art/A-very-pregnant-elf-Zorana-975632843](https://www.deviantart.com/ohshinakai/art/A-very-pregnant-elf-Zorana-975632843) 成熟内容：https://www.deviantart.com/ohshinakai/art/Look-what-you-did-to-me-husband-971205596 mature content: https://www.deviantart.com/ohshinakai/art/Amelia-got-a-big-bigger-966789880 mature content: https://www.deviantart.com/ohshinakai/art/Beautiful-and-busty-Safiyah-973676559 mature content: https://www.deviantart.com/ohshinakai/art/Miss-Moore-can-you-please-button-your-shirt-981387048 mature content: https://www.deviantart.com/ohshinakai/art/Intense-dreams-Kinsley-980973249 mature content: https://www.deviantart.com/ohshinakai/art/Ready-for-you-daily-elven-bath-Kinsley-974001753 mature content: https://www.deviantart.com/ohshinakai/art/Stretched-to-the-limit-Makima-971452732 成熟的内容：[https://www.deviantart.com/ohshinakai/art/Hey-Big-Sis-Notice-anything-](https://www.deviantart.com/ohshinakai/art/Hey-Big-Sis-Notice-anything-different-969978030) Different-969978030 成熟的内容： https: [//www.deviantart.com/ohshinakai/art/Jealous-Sister -Part-I-970038241](https://www.deviantart.com/ohshinakai/art/Jealous-Sister-Part-I-970038241) 成熟内容： https [://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953](https://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953) 成熟内容：[https://www.deviantart .com/ohshinakai/art/Well-it-fit-fine-this-morning-Rowen-973831806](https://www.deviantart.com/ohshinakai/art/Well-it-fit-fine-this-morning-Rowen-973831806) 成熟内容：[https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part -I-967677947](https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-I-967677947) 成熟内容：https://www.deviantart.com/ohshinakai/art/Must-be-something-in-the-foods-Valerie-967390567 成熟内容：https://www.deviantart.com/ohshinakai/art/Ready-for-your-morning-jog-Zorana-975632828 成熟内容：[https://www.deviantart.com/ohshinakai/art/How-can-I- make-it-up-Kimberly-976048984](https://www.deviantart.com/ohshinakai/art/How-can-I-make-it-up-Kimberly-976048984) 成熟内容：https://www.deviantart.com/ohshinakai/art/What-a-curious-feeling-Alicia-975020766 成熟内容： https: [//www.deviantart.com/ ohshinakai/art/Oh-Princess-Fiona-975260157](https://www.deviantart.com/ohshinakai/art/Oh-Princess-Fiona-975260157) 成熟内容： https: [//www.deviantart.com/ohshinakai/art/You-came-looking-for-me-973496923](https://www.deviantart.com/ohshinakai/art/You-came-looking-for-me-973496923) 成熟内容：[https://www.deviantart. com/ohshinakai/art/Bailey-too-big-for-her-uniform-969650552](https://www.deviantart.com/ohshinakai/art/Bailey-too-big-for-her-uniform-969650552) 成熟内容：https://www.deviantart.com/ohshinakai/art/Busty-and-Preggo-Citra-970209700 成熟内容：https://www.deviantart.com/ohshinakai/art/Ready-to-praise-The-Goddess-974339985 成熟内容：https://www.deviantart.com/ohshinakai/art/Vanessa-got-huge-970815495 成熟内容：[https](https://www.deviantart.com/ohshinakai/art/What-do-you-mean-I-am-covered-up-Shelby-973971962) ://www.deviantart.com/ohshinakai/art/What-do-you-mean-I-am-covered-up-Shelby-973971962 成熟内容： https: [//www.deviantart.com/ohshinakai/ art/Mr-Zhu-would-you-please-step-into-my-office-967904943](https://www.deviantart.com/ohshinakai/art/Mr-Zhu-would-you-please-step-into-my-office-967904943) 成熟内容：https://www.deviantart.com/ohshinakai/art/A-very-pregnant-elf-Citra-971200116 成熟内容：[https](https://www.deviantart.com/ohshinakai/art/What-this-is-MY-study-outfit-Shanoli-975464972) ://www.deviantart.com/ohshinakai/art/What-this-is-MY-study-outfit-Shanoli-975464972 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Gigantic-乳房-Rowen-973840724](https://www.deviantart.com/ohshinakai/art/Gigantic-breasts-Rowen-973840724) mature content: https://www.deviantart.com/ohshinakai/art/Massive-breasts-Shannary-978911515 mature content: https://www.deviantart.com/ohshinakai/art/Kinsley-with-gigantic-breasts-973693855 mature content: https://www.deviantart.com/ohshinakai/art/Sexy-lingerie-966623449 mature content: https://www.deviantart.com/ohshinakai/art/Amelia-do-we-have-any-bigger-uniforms-968041858 mature content: https://www.deviantart.com/ohshinakai/art/Are-you-sure-you-want-to-try-my-drink-Shanoli-975524705 mature content: https://www.deviantart.com/ohshinakai/art/Busty-Royce-ready-to-serve-some-hot-beverages-974754839 mature content: https://www.deviantart.com/ohshinakai/art/Citra-with-huge-belly-and-boobs-975037408 成熟内容：[https://www.deviantart.com/ohshinakai/art/Willelma-with-enormous- Breasts-in-pink-top-977221163](https://www.deviantart.com/ohshinakai/art/Willelma-with-enormous-breasts-in-pink-top-977221163) 成熟内容：https://www.deviantart.com/ohshinakai/art/Busty-Brunette-in-3D-style-952837671 成熟内容： https: [//www.deviantart.com/ ohshinakai/art/Guess-Kinsley-sleeps-on-the-side-973988004](https://www.deviantart.com/ohshinakai/art/Guess-Kinsley-sleeps-on-the-side-973988004) 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Enormous-Kinsley-in-pink-dress-973704167](https://www.deviantart.com/ohshinakai/art/Enormous-Kinsley-in-pink-dress-973704167) 成熟内容：[https： //www.deviantart.com/ohshinakai/art/Research-Director-Susu-967883587](https://www.deviantart.com/ohshinakai/art/Research-Director-Susu-967883587) 成熟内容：https://www.deviantart.com/ohshinakai/art/Busty-Bimbo-Charlotte-966164703 成熟内容：https://www.deviantart.com/ohshinakai/art/Sanna-in-pink-sleepwear-950037578 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Unexpected-growth-during-work -Jing-973811888](https://www.deviantart.com/ohshinakai/art/Unexpected-growth-during-work-Jing-973811888) 成熟内容：https://www.deviantart.com/ohshinakai/art/Gigantic-breasts-Sena-972024062 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Eira-964991097](https://www.deviantart.com/ohshinakai/art/Eira-964991097) 成熟内容：https://www.deviantart.com/ohshinakai/art/Lady-Barozzi-waiting-for-her-supper-968362592 成熟内容：[https://www.deviantart.com/ohshinakai/art/Sexy-brunette-with -huge-fake-boobs-958891211](https://www.deviantart.com/ohshinakai/art/Sexy-brunette-with-huge-fake-boobs-958891211) 成熟内容：https://www.deviantart.com/ohshinakai/art/Busty-Bailey-in-school-uniform-969659083 成熟内容：https://www.deviantart.com/ohshinakai/art/Bimbo-Ciri-in-the-house-959925046 成熟内容： https: [//www.deviantart.com/ohshinakai/art/Wanna-take-bath -with-me-Kinsley-973988013](https://www.deviantart.com/ohshinakai/art/Wanna-take-bath-with-me-Kinsley-973988013) 成熟内容：https://www.deviantart.com/ohshinakai/art/Starbucks-Mermaid-with-some-humongous-boobs-957863352 成熟内容： https: [//www.deviantart.com /ohshinakai/art/Holding-on-to-dear-life-Aniya-972440644](https://www.deviantart.com/ohshinakai/art/Holding-on-to-dear-life-Aniya-972440644) 成熟内容：[https://www.deviantart.com/ohshinakai/art/You-deserve-a-break-today-look-at-my -boobies-954476839](https://www.deviantart.com/ohshinakai/art/You-deserve-a-break-today-look-at-my-boobies-954476839)
> 
> stop Traceback (most recent call last): File "utils", line 1367, in start File "utils", line 1446, in start_ File "extractor\deviant_downloader", line 79, in read File "extractor\deviant_downloader", line 156, in get_files File "decorator", line 232, in fun File "constants", line 874, in try_ File "constants", line 872, in try_ File "extractor\deviant_downloader", line 154, in foo File "ratelimit\decorators", line 113, in wrapper File "ratelimit\decorators", line 80, in wrapper File "extractor\deviant_downloader", line 14, in wait File "utils", line 3889, in check_alive errors.StopReading
> 
> Stopped: fail=False EOT: https://ohshinakai.deviantart.com (171.4s)
> 
> mature content: https://www.deviantart.com/ohshinakai/art/Jealous-Sister-Part-I-970038241 mature content: https://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953 mature content: https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-I-967677947 mature content: https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-II-968677227
> 
> File error (https://www.deviantart.com/ohshinakai/art/Life-as-a-Big-Breasted-Elf-Part-1-979742953): Traceback (most recent call last): File "hitomi_downloader", line 273, in run File "utils", line 4673, in ready File "decorator", line 232, in fun File "constants", line 903, in try_ File "constants", line 872, in try_ File "extractor\deviant_downloader", line 106, in get Exception: no img
> 
> File error (https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-I-967677947): Traceback (most recent call last): File "hitomi_downloader", line 273, in run File "utils", line 4673, in ready File "decorator", line 232, in fun File "constants", line 903, in try_ File "constants", line 872, in try_ File "extractor\deviant_downloader", line 106, in get Exception: no img
> 
> File error (https://www.deviantart.com/ohshinakai/art/Jealous-Sister-Part-I-970038241): Traceback (most recent call last): File "hitomi_downloader", line 273, in run File "utils", line 4673, in ready File "decorator", line 232, in fun File "constants", line 903, in try_ File "constants", line 872, in try_ File "extractor\deviant_downloader", line 106, in get Exception: no img
> 
> File error (https://www.deviantart.com/ohshinakai/art/McBoobies-Valerie-s-New-Job-Part-II-968677227): Traceback (most recent call last): File "hitomi_downloader", line 273, in run File "utils", line 4673, in ready File "decorator", line 232, in fun File "constants", line 903, in try_ File "constants", line 872, in try_ File "extractor\deviant_downloader", line 106, in get Exception: no img
> 
> stop EOT: https://ohshinakai.deviantart.com (3209.7s)
> 
> ![20231102065822157](https://user-images.githubusercontent.com/27836359/279821805-d071590f-c458-4e4c-98b1-d85d3960b358.png)
