### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zhgna** [KurtBestor/Hitomi-Downloader#6566]
Invalid: [youtube] https://www.youtube.com/watch?v=AAEakqIc1NM

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / zh_cn
order / group / uid: 0 / False / 0f48955ac5cf4c1e8465118244961399
input: https://www.youtube.com/watch?v=AAEakqIc1NM
type: youtube
single: True
url: https://www.youtube.com/watch?v=AAEakqIc1NM
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1699679534.15694 (23-11-11 05:12:14 UTC) - 438s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AAEakqIc1NM
[debug] [youtube] AAEakqIc1NM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 589, in __init__
 File "ytdl", line 579, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4070, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4030, in _download_player_responses
   webpage_url, video_id, fatal=False, query=query)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AAEakqIc1NM
[debug] [youtube] AAEakqIc1NM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 589, in __init__
 File "ytdl", line 579, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4070, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4030, in _download_player_responses
   webpage_url, video_id, fatal=False, query=query)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AAEakqIc1NM
[debug] [youtube] AAEakqIc1NM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 589, in __init__
 File "ytdl", line 579, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4070, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4030, in _download_player_responses
   webpage_url, video_id, fatal=False, query=query)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AAEakqIc1NM
[debug] [youtube] AAEakqIc1NM: Downloading webpage
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 589, in __init__
 File "ytdl", line 579, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4070, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4030, in _download_player_responses
   webpage_url, video_id, fatal=False, query=query)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 451, in read
 File "utils", line 4673, in ready
 File "extractor\youtube_downloader", line 64, in get
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 589, in __init__
 File "ytdl", line 579, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4070, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4030, in _download_player_responses
   webpage_url, video_id, fatal=False, query=query)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

Unable to handle request: Unsupported proxy type: "https" (urllib)
stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "extractor\youtube_downloader", line 458, in read
 File "extractor\youtube_downloader", line 451, in read
 File "utils", line 4673, in ready
 File "extractor\youtube_downloader", line 64, in get
 File "extractor\youtube_downloader", line 54, in get
 File "ytdl", line 589, in __init__
 File "ytdl", line 579, in __init__
 File "ytdl", line 464, in extract_info
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4070, in _real_extract
   webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\youtube", line 4030, in _download_player_responses
   webpage_url, video_id, fatal=False, query=query)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 456, in urlopen
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\86185\AppData\Local\Temp\_MEI171442\ytdl_1e5685cb\yt_dlp\yt_dlp\networking\common", line 127, in send
   raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=AAEakqIc1NM  (10.1s)

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/issues/6464
