### ISSUE TITLE
유튜브 다운로드 관련 문의넣습니다.

### ISSUE THREAD

**Issue by Allen-W16** [KurtBestor/Hitomi-Downloader#6571]
5시간 55분짜리 영상을 다운하는데 1시간 59분 59초만 다운됩니다. 끝나기 2시간 전부터 끝나는 지점까지만 다운됩니다.

version: 3.8f+ (23-11-11 12:54:10 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 87e4ee67a784454bb27f02a32db21925
input: https://www.youtube.com/watch?v=ORXawj3vOHc
type: youtube
single: True
url: https://www.youtube.com/watch?v=ORXawj3vOHc
dir: hitomi_downloaded_youtube
zip: 
artist: 꽃핀
valid / done: True / True
range / range_p: None / None
time: 1699727560.644148 (23-11-11 18:32:40 UTC) - 149s elapsed
tags: []
lock: False
color: done
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_youtube\🌺하루 뒤에 사라질 노래 방송🌺 (ORXawj3vOHc).mp4

[URLs]
[0001] Video(https://www.youtube.com/watch?v=ORXawj3vOHc)    --->    【local_lazy】 🌺하루 뒤에 사라질 노래 방송🌺 (ORXawj3vOHc).mp4

[Messages]
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ORXawj3vOHc
[debug] [youtube] ORXawj3vOHc: Downloading webpage
[debug] [youtube] ORXawj3vOHc: Downloading ios player API JSON
[debug] [youtube] ORXawj3vOHc: Downloading android player API JSON
[debug] [youtube] ORXawj3vOHc: Downloading MPD manifest
[debug] [youtube] ORXawj3vOHc: Downloading MPD manifest
live: post_live
[27p][0.004691091617019281fps][None][None] mhtml [None / None] ─ sb3 - 48x27 (storyboard)
[45p][0.10006098419102125fps][None][None] mhtml [None / None] ─ sb2 - 80x45 (storyboard)
[90p][0.10006098419102125fps][None][None] mhtml [None / None] ─ sb1 - 160x90 (storyboard)
[180p][0.10006098419102125fps][None][None] mhtml [None / None] ─ sb0 - 320x180 (storyboard)
[None][0fps][64.0kbps][64.0] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][144.0kbps][144.0] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)
[144p][30fps][None][192.223] mp4 [avc1.4d400c / None] ─ 160 - 256x144 (DASH video)
[240p][30fps][None][419.256] mp4 [avc1.4d4015 / None] ─ 133 - 426x240 (DASH video)
[360p][30fps][None][772.63] mp4 [avc1.4d401e / None] ─ 134 - 640x360 (DASH video)
[480p][30fps][None][1077.445] mp4 [avc1.4d401f / None] ─ 135 - 854x480 (DASH video)
[720p][30fps][None][2187.4] mp4 [avc1.4d401f / None] ─ 136 - 1280x720 (DASH video)
[720p][60fps][None][2639.005] mp4 [avc1.4d4020 / None] ─ 298 - 1280x720 (DASH video)
[1080p][30fps][None][4199.987] mp4 [avc1.4d4028 / None] ─ 137 - 1920x1080 (DASH video)
[1080p][60fps][None][5144.2] mp4 [avc1.4d402a / None] ─ 299 - 1920x1080 (DASH video)

utime: 1699660800.0

# stream_final
[1080p][60fps][None][5144.2] mp4 [avc1.4d402a / None] ─ 299 - 1920x1080 (DASH video)

[None][0fps][64.0kbps][64.0] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][144.0kbps][144.0] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)

[None][0fps][64.0kbps][64.0] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][144.0kbps][144.0] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)

[None][0fps][64.0kbps][64.0] m4a [None / mp4a.40.5] ─ 139 - audio only (DASH audio)
[None][0fps][144.0kbps][144.0] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)

[None][0fps][144.0kbps][144.0] m4a [None / mp4a.40.2] ─ 140 - audio only (DASH audio)

filename: 🌺하루 뒤에 사라질 노래 방송🌺 (ORXawj3vOHc).mp4
Resolution: 1080p
Codec: avc1.4d402a / None
Abr: None
Subtype: mp4
FPS: 60

Download audio: Dash_stream(https://manifest.googlevideo.com/api/manifest/dash/expire/1699749164/ei/zMhPZYO1BLqu2roP37eT8Ao/ip/211.117.89.84/id/ORXawj3vOHc.1/source/yt_live_broadcast/requiressl/yes/hfr/1/as/fmp4_audio_clear,webm_audio_clear,webm2_audio_clear,fmp4_sd_hd_clear,webm2_sd_hd_clear/force_finished/1/gcr/kr/spc/UWF9f38udBCo2StQAqBEf0Ti1TFggqs/vprv/1/pacing/0/itag_bl/376,377,384,385,612,613,617,619,623,628,655,656,660,662,666,671/keepalive/yes/fexp/24007246/beids/24350018/itag/0/playlist_type/DVR/sparams/expire,ei,ip,id,source,requiressl,hfr,as,force_finished,gcr,spc,vprv,itag,playlist_type/sig/ANLwegAwRQIgY0ZgKGhn-N8yIu_bJUh7grQsiiI0_-_ggWw6FalHFFYCIQDbfql-75YSQX39fVLVdIbCqlO2xldboFt1-sL5elF5KA==)
use just download: overwrite=True
media: 0
thumb: https://i.ytimg.com/vi/ORXawj3vOHc/maxresdefault.jpg
Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 555, in get
 File "utils", line 988, in request
 File "downloader", line 248, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 649, in send
 File "requests\sessions", line 742, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'C:\\Users\\seong\\Desktop\\파일\\Hitomi Downloaded\\Hitomi Downloaded 01\\hitomi_downloaded_youtube\\🌺하루 뒤에 사라질 노래 방송🌺 (ORXawj3vOHc).mp4'

### reset size ###
Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 555, in get
 File "utils", line 988, in request
 File "downloader", line 248, in session_request
 File "requests\sessions", line 542, in request
 File "requests\sessions", line 649, in send
 File "requests\sessions", line 742, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'C:\\Users\\seong\\Desktop\\파일\\Hitomi Downloaded\\Hitomi Downloaded 01\\hitomi_downloaded_youtube\\🌺하루 뒤에 사라질 노래 방송🌺 (ORXawj3vOHc).mp4'

### reset size ###
use just download: overwrite=True
stop
-show_streams -print_format json -v error "🌺하루 뒤에 사라질 노래 방송🌺 (ORXawj3vOHc).mp4"
EOT: https://www.youtube.com/watch?v=ORXawj3vOHc  (15.2s)

audio done

**Comment by Asylum0** [comment]
경험담일 뿐이지만 2시간이 넘는 스트리밍의 경우 그런 현상이 발생합니다.
어느정도 시간이 지난 뒤 받으면 정상적으로 받아지더라고요.
어느정도 시간이 필요한지까지는 모르겠습니다.
비슷한 영상을 저는 며칠정도 뒤에 받아서 정상적으로 받았기에...
