### ISSUE TITLE
Pixiv 다운로드가 안 되는 거 같습니다

### ISSUE THREAD

**Issue by ALo98e** [KurtBestor/Hitomi-Downloader#6588]
어제는 괜찮았는데 오늘 갑자기 안 되네요

쿠키를 업데이트 해도 안 되는 거 같습니다

로그 첨부합니다 항상 감사합니다 

Invalid: [pixiv] https://www.pixiv.net/users/554102

version: 3.8f+ (23-11-02 01:42:17 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 658 / False / 371d86bf7c9f40018a07aaba2b688c0c
input: https://www.pixiv.net/users/554102
type: pixiv
single: False
url: https://www.pixiv.net/users/554102
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1700203292.516103 (23-11-17 06:41:32 UTC) - 395s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
sid: 15857710_MHkXje8TcrZUFsMJqZIcWyVnPoqq6PC9
types: ['illusts', 'manga'], tag: None
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1378, in start
 File "utils", line 1457, in start_
 File "extractor\pixiv_downloader", line 109, in read
 File "extractor\pixiv_downloader", line 464, in get_info
 File "extractor\pixiv_downloader", line 513, in process_user
 File "extractor\pixiv_downloader", line 182, in top
 File "decorator", line 232, in fun
 File "constants", line 904, in try_
 File "constants", line 873, in try_
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 155, in call
 File "downloader", line 351, in read_json
 File "myjson", line 14, in loads
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://www.pixiv.net/users/554102  (40.8s)

**Comment by Asylum0** [comment]
오늘 오전까지만 해도 됐었는데 지금은 안되는군요...
오후에 뭔가 있었나?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Asylum0** [comment]
저는 다운로드 성공 확인했습니다.

**Comment by ALo98e** [comment]
아하 재실행해보니 쿠키 인식이 되는군요 감사합니다 :)
