### ISSUE TITLE
픽시브가 다운로드 되지 않습니다

### ISSUE THREAD

**Issue by chaoseverchosen** [KurtBestor/Hitomi-Downloader#6593]
Invalid: [pixiv] https://www.pixiv.net/users/24059583

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / c7e5e4ae96f440b4bb4f77d1a0d639dd
input: https://www.pixiv.net/users/24059583
type: pixiv
single: False
url: https://www.pixiv.net/users/24059583
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1700249023.9591424 (23-11-17 19:23:43 UTC) - 57s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
sid: 2791377_BX4FjZg4E8MRaF8WMnXRKVGSz4CGLYi5
types: ['illusts', 'manga'], tag: None
Extra data: line 1 column 2 (char 1)
stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "extractor\pixiv_downloader", line 109, in read
 File "extractor\pixiv_downloader", line 464, in get_info
 File "extractor\pixiv_downloader", line 513, in process_user
 File "extractor\pixiv_downloader", line 182, in top
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 155, in call
 File "downloader", line 351, in read_json
 File "myjson", line 14, in loads
 File "json\__init__", line 348, in loads
 File "json\decoder", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

Invalid: fail=True
EOT: https://www.pixiv.net/users/24059583  (40.2s)

**Comment by Asylum0** [comment]
인용해서 알려드리려고 했는데 이전에 있던 글이 없어졌나 안보이네요;;
아래에서 받아서 확인해주세요.
수정돼서 잘 받아지고 있습니다.

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 666hyun** [comment]
> 인용해서 알려드리려고 했는데 이전에 있던 글이 없어졌나 안보이네요;; 아래에서 받아서 확인해주세요. 수정돼서 잘 받아지고 있습니다.
> 
> https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

저도 같은 증상이라서 이거 받았는데 윈7이라고 안돌아가네요.
귀찮아서 미루고 있었더니 이렇게 두들겨맞을줄이야.
