### ISSUE TITLE
픽시브 코믹 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by nolahomerun** [KurtBestor/Hitomi-Downloader#6632]
8분 30초 뒤 다시 시작: Invalid: [pixiv_comic] https://comic.pixiv.net/works/9826

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 5a908e721bee42db841949fbb6d30018
input: https://comic.pixiv.net/works/9826
type: pixiv_comic
single: False
url: https://comic.pixiv.net/works/9826
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1701501268.3680804 (23-12-02 07:14:28 UTC) - 218s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no html
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f

stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\pixiv_comic_downloader", line 141, in read
 File "clf2", line 176, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://comic.pixiv.net/works/9826  (127.5s)

**Comment by nolahomerun** [comment]
아 쿠키 다시 불러오니까 되네요 픽시브 쿠키랑 픽시브 코믹 쿠키가 별도인가 보네요 픽시브 다운로드가 멀쩡히 잘 되고 있어서 미처 생각을 못했는데
