### ISSUE TITLE
4.0 버전에서 일부 사이트들의 쿠키 적용이 되지 않습니다

### ISSUE THREAD

**Issue by stomiii** [KurtBestor/Hitomi-Downloader#6653]
안녕하세요 만들어주신 프로그램 잘 사용하고 있습니다

사용중에 동일한 증상의 문제들은 이슈에 있는 테스트 파일로 찾아 해결 하였으나 이번 4.0 버전에서의 쿠키 이슈는 해결 되지 않은 것 같아 문의 드립니다

몇몇 트위터 계정들은 쿠키를 업데이트 하면 해결 되는 계정들도 있는 반면 다운로드가 되지 않는 계정들이 있습니다

이미 한번 다운로드 하였던 계정들도 쿠키를 업데이트 해도 다운로드가 되지 않는 문제 또한 있습니다

아이와라 같은 경우 쿠키 업데이트 및 내장 브라우저를 통해 로그인을 하여도 다운로드가 되지 않습니다
아이와라는 로그가 길어 파일로 첨부 했습니다
[Iwara Error.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/13548494/Iwara.Error.txt)

확인 부탁드리겠습니다

------------------------------트위터 로그
Login required; Please login
https://twitter.com/StebynnO

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 4 / False / e2652e8ac667441eac0012011046713c
input: https://twitter.com/StebynnO
type: twitter
single: False
url: https://twitter.com/StebynnO
dir: 
zip: 
artist: Steb | Commission Open
valid / done: False / True
range / range_p: None / None
time: 1701703982.0533943 (23-12-04 15:33:02 UTC) - 27s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {uids: ['1314960675395887107']}
live: False
changed: True

[File Names]

[URLs]

[Messages]
format: None
type: user
uid: 1314960675395887107
multiple tweets rt:False
mc: 179
call... UserMedia
Dependency: Unspecified
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 511, in _pagination_tweets
KeyError: 'timeline'

stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\twitter_downloader", line 154, in read
 File "extractor\twitter_downloader", line 807, in get_imgs
 File "utils", line 3922, in check_alive_iter
 File "extractor\twitter_downloader", line 536, in _pagination_tweets
extractor.twitter_downloader.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/StebynnO  (8.4s)

format: None
type: user
uid: 1314960675395887107
multiple tweets rt:False
mc: 179
call... UserMedia
Dependency: Unspecified
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 511, in _pagination_tweets
KeyError: 'timeline'

stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\twitter_downloader", line 154, in read
 File "extractor\twitter_downloader", line 807, in get_imgs
 File "utils", line 3922, in check_alive_iter
 File "extractor\twitter_downloader", line 536, in _pagination_tweets
extractor.twitter_downloader.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/StebynnO  (8.4s)

format: None
type: user
uid: 1314960675395887107
multiple tweets rt:False
mc: 179
call... UserMedia
call... UserMedia
Dependency: Unspecified
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 511, in _pagination_tweets
KeyError: 'timeline'

stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\twitter_downloader", line 154, in read
 File "extractor\twitter_downloader", line 807, in get_imgs
 File "utils", line 3922, in check_alive_iter
 File "extractor\twitter_downloader", line 536, in _pagination_tweets
extractor.twitter_downloader.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/StebynnO  (22.7s)

format: None
type: user
uid: 1314960675395887107
multiple tweets rt:False
mc: 179
call... UserMedia
call... UserMedia
Dependency: Unspecified
Traceback (most recent call last):
 File "extractor\twitter_downloader", line 511, in _pagination_tweets
KeyError: 'timeline'

stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\twitter_downloader", line 154, in read
 File "extractor\twitter_downloader", line 807, in get_imgs
 File "utils", line 3922, in check_alive_iter
 File "extractor\twitter_downloader", line 536, in _pagination_tweets
extractor.twitter_downloader.LoginRequired

Invalid: fail=False
EOT: https://twitter.com/StebynnO  (14.4s)

**Comment by KurtBestor** [comment]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/14768120/c58901e6-7957-4749-95b8-6535ea599bc9)

재현할 수 없네요
