### ISSUE TITLE
북토끼 다운로드가 안 되고 있어서 문의 드립니다.

### ISSUE THREAD

**Issue by JCYAK** [KurtBestor/Hitomi-Downloader#6663]
안녕하세요,
평소에 잘 쓰고 있는데 오늘 북토끼 다운로드가 안 되어 궁금합니다...
여기 에러 뜬 메세지 첨부 드려요
감사합니다 ~.~

29분 37초 뒤 다시 시작: Invalid: [booktoki] https://booktoki317.com/novel/9810502

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 58f3ecac426e4be0b75eff5762a6caf5
input: https://booktoki317.com/novel/9810502
type: booktoki
single: False
url: https://booktoki317.com/novel/9810502
dir: 
zip: 
artist: 고스름도치
valid / done: False / True
range / range_p: None / None
time: 1701906846.8747315 (23-12-06 23:54:06 UTC) - 874s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
['https://booktoki317.com/novel/9812821?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812824?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812827?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812830?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812833?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812839?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812842?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812845?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812851?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812854?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812857?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812860?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812863?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812866?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812869?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812872?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812875?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812878?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812881?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812884?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812887?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812890?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812893?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812896?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812899?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812902?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812905?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812908?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812911?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812914?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812917?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812920?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812923?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812926?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812929?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812932?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812935?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812938?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812941?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812944?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812947?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812953?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812956?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812959?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812962?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812968?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812971?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812974?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812977?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812980?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812983?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812986?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812989?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812992?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9812995?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9813001?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9813004?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9829246?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9829249?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9829252?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9829255?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9873766?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9873769?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9906672?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/9906677?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10053832?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10053837?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10053847?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10053852?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10053857?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10053867?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10119152?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10119157?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10119167?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10205527?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10205532?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10205537?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10338842?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10338847?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10338852?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10338857?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10338862?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10338867?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10351752?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10351757?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10402225?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10402229?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10469189?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10469193?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10469197?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10469201?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10546689?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10546693?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10561037?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10561041?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10648189?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10648193?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10648197?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10648201?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10648205?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822581?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822585?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822589?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822593?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822597?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822601?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822609?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822613?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822617?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822621?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822625?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/novel/10822629?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4&spage=1', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=10822633', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751681', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751685', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751689', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751693', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751697', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751701', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751705', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751709', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751717', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751721', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751725', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751729', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751733', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751741', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751745', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751749', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751757', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751761', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751765', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751769', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751773', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751777', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751781', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751789', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751793', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751797', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751801', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751805', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751809', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751813', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751817', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751821', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751825', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751829', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751833', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751837', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751841', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751845', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751849', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751853', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751857', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751861', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751865', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751869', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751873', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751877', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751881', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11751885', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948965', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948969', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948973', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948977', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948985', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948989', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948993', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=11948997', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095301', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095305', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095309', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095313', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095317', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095321', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12095329', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12241709', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12241713', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12241717', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12241721', 'https://booktoki317.com/bbs/view_init.php?bo_table=novel&wr_id=12241725']
Reading: 1/181
Reading: 2/181
Reading: 3/181
Reading: 4/181
Reading: 5/181
Reading: 6/181
Reading: 7/181
Reading: 8/181
Reading: 9/181
Reading: 10/181
Reading: 11/181
Reading: 12/181
Reading: 13/181
Reading: 14/181
Reading: 15/181
Reading: 16/181
Reading: 17/181
Reading: 18/181
Reading: 19/181
Reading: 20/181
Reading: 21/181
Reading: 22/181
Reading: 23/181
Reading: 24/181
Reading: 25/181
Reading: 26/181
Reading: 27/181
Reading: 28/181
Reading: 29/181
Reading: 30/181
Reading: 31/181
Reading: 32/181
Reading: 33/181
Reading: 34/181
Reading: 35/181
Reading: 36/181
Reading: 37/181
Reading: 38/181
Reading: 39/181
Reading: 40/181
Reading: 41/181
Reading: 42/181
Reading: 43/181
Reading: 44/181
Reading: 45/181
Reading: 46/181
Reading: 47/181
Reading: 48/181
Reading: 49/181
Reading: 50/181
Reading: 51/181
Reading: 52/181
Reading: 53/181
Reading: 54/181
Reading: 55/181
Reading: 56/181
Reading: 57/181
Reading: 58/181
Reading: 59/181
Reading: 60/181
Reading: 61/181
Reading: 62/181
Reading: 63/181
Reading: 64/181
Reading: 65/181
Reading: 66/181
Reading: 67/181
Reading: 68/181
Reading: 69/181
Reading: 70/181
Reading: 71/181
Reading: 72/181
Reading: 73/181
Reading: 74/181
Reading: 75/181
Reading: 76/181
Reading: 77/181
Reading: 78/181
Reading: 79/181
Reading: 80/181
Reading: 81/181
Reading: 82/181
Reading: 83/181
Reading: 84/181
Reading: 85/181
Reading: 86/181
Reading: 87/181
Reading: 88/181
Reading: 89/181
Reading: 90/181
Reading: 91/181
Reading: 92/181
Reading: 93/181
Reading: 94/181
Reading: 95/181
Reading: 96/181
Reading: 97/181
Reading: 98/181
Reading: 99/181
Reading: 100/181
Reading: 101/181
Reading: 102/181
Reading: 103/181
Reading: 104/181
Reading: 105/181
Reading: 106/181
Reading: 107/181
Reading: 108/181
Reading: 109/181
Reading: 110/181
Reading: 111/181
Reading: 112/181
Reading: 113/181

stop
Traceback (most recent call last):
 File "dynamic_module_2", line 52, in content_getter
 File "dynamic_module_2", line 121, in get_content
AttributeError: 'NoneType' object has no attribute 'find_all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "dynamic_module_2", line 56, in read
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "dynamic_module_2", line 54, in content_getter
 File "dynamic_module_2", line 105, in get_soup
 File "clf2", line 176, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://booktoki317.com/novel/9810502  (851.1s)

**Comment by yeorinhieut** [comment]
소설 목록에 캡챠가 포함되어 있어서 발생하는 오류입니다.
Cookie를 임포트 하거나, 다른 프로그램을 사용해 보세여

**Comment by whoSSR** [comment]
저도 이거보고 들어왔는데 북토끼 스크립트는 캡챠 문제가 있어 마나토끼 게시물로 캡챠 띄워서 해결했어요

쿠키로 해결할 수 있는거 같은데 잘 모르면 캡챠로 해결하는게 좋은거 같아요
