### ISSUE TITLE
카카오페이지 다운이 안되네요

### ISSUE THREAD

**Issue by Bolined** [KurtBestor/Hitomi-Downloader#6680]
로그인도 되고 내장 브라우저상에서 웹툰 열람도 가능한데 프로그램을 돌리면 스캔이 안되네요
분명히 4.0 최신 버전을 쓰는데 정보에는 버전이 3.8c로 나오네요...

작업 정보입니다

----------------------------------------------------------------------------------------

version: 3.8c (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 276 / False / 80f3364c17774279abd6665201f97e8a
input: https://page.kakao.com/content/50626843
type: kakaopage
single: False
url: https://page.kakao.com/content/50626843
dir:
zip: 
artist: Ping Ping Jun
valid / done: False / True
range / range_p: None / None
time: 1702099633.9043713 (23-12-09 05:27:13 UTC) - 368765s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
Invalid request. (GRAPHQL_VALIDATION_FAILED)
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\kakaopage_downloader", line 60, in read
 File "extractor\kakaopage_downloader", line 622, in get_info
 File "extractor\kakaopage_downloader", line 227, in get_pages
errors.Invalid: Invalid request. (GRAPHQL_VALIDATION_FAILED)

Invalid: fail=False
invalid; revert
EOT: https://page.kakao.com/content/50626843  (19.0s)

stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\kakaopage_downloader", line 60, in read
 File "extractor\kakaopage_downloader", line 619, in get_info
 File "extractor\kakaopage_downloader", line 249, in read_html
 File "clf2", line 176, in solve
clf2.Timeout

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/content/50626843  (100.4s)

Invalid request. (GRAPHQL_VALIDATION_FAILED)
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\kakaopage_downloader", line 60, in read
 File "extractor\kakaopage_downloader", line 622, in get_info
 File "extractor\kakaopage_downloader", line 227, in get_pages
errors.Invalid: Invalid request. (GRAPHQL_VALIDATION_FAILED)

Invalid: fail=False
invalid; revert
EOT: https://page.kakao.com/content/50626843  (45.4s)

**Comment by KurtBestor** [comment]
지금도 그런가요?

**Comment by Bolined** [comment]
아 이틀정도 안됐었는데 지금 돌려보니 되네요
확인 감사합니다
