### ISSUE TITLE
카카페(카카오페이지) 오류입니다.

### ISSUE THREAD

**Issue by berwgds** [KurtBestor/Hitomi-Downloader#6683]
Invalid request. (GRAPHQL_VALIDATION_FAILED)

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 88e57e87ff334dfb97c5e981e323ad10
input: https://page.kakao.com/content/54471153
type: kakaopage
single: False
url: https://page.kakao.com/content/54471153
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702469275.4403882 (23-12-13 12:07:55 UTC) - 15s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Invalid request. (GRAPHQL_VALIDATION_FAILED)
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\kakaopage_downloader", line 60, in read
 File "extractor\kakaopage_downloader", line 622, in get_info
 File "extractor\kakaopage_downloader", line 227, in get_pages
errors.Invalid: Invalid request. (GRAPHQL_VALIDATION_FAILED)

Invalid: fail=False
quality: 100%
EOT: https://page.kakao.com/content/54471153  (7.1s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/6680
