### ISSUE TITLE
인스타 사이트 오류로 다운이 안됩니다.

### ISSUE THREAD

**Issue by ziii255** [KurtBestor/Hitomi-Downloader#6685]
말 그대롭니다...
다운하면 지정된 주소로 되는게 아니라 로그인한 자기 인스타가 다운 되버립니다.
어떤 주소던지 그렇게 됩니다.
아 그리고 윈도우7버전은 올리실 생각이 없으신지도 궁금합니다.
그럼 수고하십시요

Invalid: [insta] https://www.instagram.com/jennie__kjn

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko_kr
order / group / uid: 1745 / False / bb2b0042011a466d88b79f87e68f1fdc
input: https://www.instagram.com/jennie__kjn
type: insta
single: False
url: https://www.instagram.com/seeredddd
dir: 
zip: 
artist: rlaueee
valid / done: False / True
range / range_p: None / None
time: 1702567370.057742 (23-12-14 15:22:50 UTC) - 71s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
no html
username: seeredddd
stories: True
['51951101825', None]
Failed to get stories: None
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1463, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://www.instagram.com/jennie__kjn  (67.6s)

**Comment by rv-arteaga** [comment]
Same...

**Comment by KurtBestor** [comment]
최신 버전을 사용해주세요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/6440, https://github.com/KurtBestor/Hitomi-Downloader/issues/6482#issuecomment-1780433118
