### ISSUE TITLE
hds 스크립트 설치 오류

### ISSUE THREAD

**Issue by wzxtzqrl** [KurtBestor/Hitomi-Downloader#6696]
Txt에서 링크를 읽어오는 스크립트를 인스톨 하려고 합니다.
https://github.com/KurtBestor/Hitomi-Downloader/discussions/5259#discussioncomment-3777105

그런데 올바르지 않은 형식의 스크립트라고 다음과 같은 오류가 발생합니다.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 5799, in exec_script
  File "dynamic_module_13", line 20, in <module>
AttributeError: type object 'QIcon' has no attribute 'Normal'

뭐가 문제일까요?

**Comment by rickmiron** [comment]
Script :

    import constants
    from PyQt6.QtWidgets import QFileDialog
    
    def foo(file_path):
      if not file_path:
          file_path, _ = QFileDialog.getOpenFileName(None, ":V")
      f = open(file_path, "r", encoding="utf-8")
      r = f.read()
      s = r.split("\n")
      for l in s:
          ui.edit.setText(l)
          ui.downButton.click()
    
    ficon = QtGui.QIcon()
    ficon.addPixmap(
      QtGui.QPixmap("imgs/icons/disk.png")
    )
    
    ui.action_fread = QtGui.QAction(constants.mainWindow)
    ui.action_fread.setIcon(ficon)
    ui.action_fread.setObjectName("action_fread")
    ui.action_fread.triggered.connect(lambda: foo("links.txt"))
    ui.action_fread.setText("Read links.txt")
    ui.menu_2.addAction(ui.action_fread)
    
    ui.action_fread1 = QtGui.QAction(constants.mainWindow)
    ui.action_fread1.setIcon(ficon)
    ui.action_fread1.setObjectName("action_fread1")
    ui.action_fread1.triggered.connect(foo)
    ui.action_fread1.setText("Search file.txt")
    ui.menu_2.addAction(ui.action_fread1)

**Comment by wzxtzqrl** [comment]
> Script :

오~!! 감사합니다.
그런데 기능을 하나 더 추가 하셨네요?
Search file.txt 이건 어떤 용도를 쓰나요?

**Comment by rickmiron** [comment]
버튼은 다른 위치에서 link.txt 파일을 검색하는 것입니다.
