### ISSUE TITLE
히토미 다운로더 실행이 안되는데 무슨 문제인가요?

### ISSUE THREAD

**Issue by wajgds** [KurtBestor/Hitomi-Downloader#6702]
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 306, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "Qt.py", line 24, in <module>
  File "Qt.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "PyQt\QtWebEngineCore.py", line 1, in <module>
ImportError: DLL load failed while importing QtWebEngineCore: 지정된 모듈을 찾을 수 없습니다.

**Comment by KurtBestor** [comment]
어떤 버전으로 실행하셨나요?

**Comment by wajgds** [comment]
> 어떤 버전으로 실행하셨나요?

4.0최신이요

**Comment by KurtBestor** [comment]
윈도 버전이 무엇인가요?
