### ISSUE TITLE
win11 ))- ehentai 다운 중 정지 현상 및 test 버전 응답없음 현상

### ISSUE THREAD

**Issue by MaidRed** [KurtBestor/Hitomi-Downloader#6705]
4분 37초 뒤 다시 시작: [Seravin] Soda Nikke by N／A (2768333)

version: 4.0+ (23-12-02 10:32:01 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 9 / False / c78d12e80b6845bbb6734ea78a013ebe
input: https://e-hentai.org/g/2768333/525e4a240e/
type: ehen
single: False
url: https://e-hentai.org/g/2768333/525e4a240e
dir: [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)
zip: 
artist: N／A
valid / done: False / True
range / range_p: None / None
time: 1702829820.6808836 (23-12-17 16:17:00 UTC) - 71176s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 2768333

제목: [Seravin] Soda Nikke

작가: N/A

그룹: N/A

타입: cosplay

시리즈: goddess of victory nikke

캐릭터: soda

태그: female:big breasts, female:gloves, female:maid, female:makeup

언어: N/A

[File Names]
[0001] [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)\set_1.jpg
[0002] [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)\set_2.jpg
[0003] [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)\set_3.jpg
[0004] [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)\set_4.jpg
[0005] [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)\set_5.jpg
[0006] [ 마루마루 ]\[ 마루마루 ]\[Seravin] Soda Nikke by N／A (2768333)\set_6.jpg

[URLs]
[0001] File_ehen(https://e-hentai.org/s/8f1ab65a36/2768333-1)    --->    https://e-hentai.org/fullimg/2768333/1/a2h375ja4zo/set_1.jpg
[0002] File_ehen(https://e-hentai.org/s/b55390e829/2768333-2)    --->    https://e-hentai.org/fullimg/2768333/2/f6pojfma4zo/set_2.jpg
[0003] File_ehen(https://e-hentai.org/s/c69699a8ca/2768333-3)    --->    https://e-hentai.org/fullimg/2768333/3/2z7jw39a4zo/set_3.jpg
[0004] File_ehen(https://e-hentai.org/s/1d987af858/2768333-4)    --->    https://e-hentai.org/fullimg/2768333/4/0cxqkava4zo/set_4.jpg
[0005] File_ehen(https://e-hentai.org/s/1f00cb5fa4/2768333-5)    --->    https://e-hentai.org/fullimg/2768333/5/q656xbra4zo/set_5.jpg
[0006] File_ehen(https://e-hentai.org/s/c63c205b86/2768333-6)    --->    https://e-hentai.org/fullimg/2768333/6/phddm1ua4zo/set_6.jpg
[0007] File_ehen(https://e-hentai.org/s/c251593972/2768333-7)
[0008] File_ehen(https://e-hentai.org/s/c9746f6293/2768333-8)
[0009] File_ehen(https://e-hentai.org/s/e9296127c3/2768333-9)
[0010] File_ehen(https://e-hentai.org/s/19d7d554d9/2768333-10)
[0011] File_ehen(https://e-hentai.org/s/e35b61e63f/2768333-11)
[0012] File_ehen(https://e-hentai.org/s/9187d19146/2768333-12)
[0013] File_ehen(https://e-hentai.org/s/beb9241265/2768333-13)
[0014] File_ehen(https://e-hentai.org/s/4efd345f46/2768333-14)
[0015] File_ehen(https://e-hentai.org/s/c2274fbf4a/2768333-15)
[0016] File_ehen(https://e-hentai.org/s/1c422ce377/2768333-16)

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 412, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 463, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2768333.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 537, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_0", line 266, in _pop_img
 File "dynamic_hitomi_0", line 231, in get_data
 File "downloader", line 473, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 412, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 463, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2768333.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 677, in read
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 537, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_0", line 266, in _pop_img
 File "dynamic_hitomi_0", line 231, in get_data
 File "downloader", line 473, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 412, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 463, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2768333.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 537, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_0", line 266, in _pop_img
 File "dynamic_hitomi_0", line 231, in get_data
 File "downloader", line 473, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1414, in connect
 File "http\client", line 918, in connect
 File "socket", line 787, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 430, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020FD01C4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2768333 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020FD01C4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 546, in get_imgs
 File "hitomi_downloader", line 546, in <listcomp>
 File "extractor\hiyobi_downloader", line 36, in pop_img_hiyobi
 File "downloader", line 457, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 248, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2768333 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020FD01C4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Read reader FAILED - auto
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1414, in connect
 File "http\client", line 918, in connect
 File "socket", line 787, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 430, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020FD01C4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2768333 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020FD01C4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 677, in read
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 546, in get_imgs
 File "hitomi_downloader", line 546, in <listcomp>
 File "extractor\hiyobi_downloader", line 36, in pop_img_hiyobi
 File "downloader", line 457, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 248, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2768333 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020FD01C4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 412, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 463, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/2768333.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 537, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_0", line 266, in _pop_img
 File "dynamic_hitomi_0", line 231, in get_data
 File "downloader", line 473, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1414, in connect
 File "http\client", line 918, in connect
 File "socket", line 787, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 430, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020FA7CE7E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2768333 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020FA7CE7E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 667, in read
 File "hitomi_downloader", line 546, in get_imgs
 File "hitomi_downloader", line 546, in <listcomp>
 File "extractor\hiyobi_downloader", line 36, in pop_img_hiyobi
 File "downloader", line 457, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 248, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hiyobi.me', port=443): Max retries exceeded with url: /reader/2768333 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020FA7CE7E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/2768333/525e4a240e/)
using custom cookies
#### https://e-hentai.org/g/2768333/525e4a240e    ---->    https://e-hentai.org/g/2768333/525e4a240e
MPV: False
get_title_ehen: https://e-hentai.org/g/2768333/525e4a240e
FINAL SERVER: ehen
ehen_url: https://e-hentai.org/g/2768333/525e4a240e
imgs: 16
E-Hentai: https://e-hentai.org/g/2768333/525e4a240e

ehen retry... https://e-hentai.org/s/c251593972/2768333-7
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/c251593972/2768333-7):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/c9746f6293/2768333-8
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/c9746f6293/2768333-8):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/e9296127c3/2768333-9
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/e9296127c3/2768333-9):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/19d7d554d9/2768333-10
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/19d7d554d9/2768333-10):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/e35b61e63f/2768333-11
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/e35b61e63f/2768333-11):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/9187d19146/2768333-12
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/9187d19146/2768333-12):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/beb9241265/2768333-13
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/beb9241265/2768333-13):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/4efd345f46/2768333-14
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/4efd345f46/2768333-14):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/c2274fbf4a/2768333-15
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/c2274fbf4a/2768333-15):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

ehen retry... https://e-hentai.org/s/1c422ce377/2768333-16
Traceback (most recent call last):
 File "extractor\ehen_downloader", line 323, in get_img
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

File error (https://e-hentai.org/s/1c422ce377/2768333-16):
Traceback (most recent call last):
 File "hitomi_downloader", line 273, in run
 File "utils", line 4708, in ready
 File "extractor\ehen_downloader", line 282, in get
extractor.ehen_downloader.BandwidthExceeded: 509 Bandwidth exceeded

stop
quality: 100%
EOT: https://e-hentai.org/g/2768333/525e4a240e/  (125.8s)

--------------------------------------

다운 되지도 않았는대 아예 멈춰 버리네요
다운로드 완료 되었다는 듯이 
폴더 파일 없음...
윈11에서 test 버전은 작동 정지 됩니다.
이유는.. 저도 궁금하네요

**Comment by KurtBestor** [comment]
https://e-hentai.org/home.php 에서 Image Limits 가 어떻게 되어있는지 보여주세요

이것과 같은 경우인가요?: https://github.com/KurtBestor/Hitomi-Downloader/issues/6703

**Comment by MaidRed** [comment]
> Image Limits

dk,  이런 거 떄문에 걸린거군요
참고 하겠습니다.

**Comment by MaidRed** [comment]
> https://e-hentai.org/home.php 에서 Image Limits 가 어떻게 되어있는지 보여주세요
> 
> 이것과 같은 경우인가요?: #6703

참고로 전에는 아무리 많이 받아도 이런 현상 없어서 
전혀 몰랐습니다 고생하십니ㅏㄷ

**Comment by MaidRed** [comment]
> https://e-hentai.org/home.php 에서 Image Limits 가 어떻게 되어있는지 보여주세요
> 
> 이것과 같은 경우인가요?: #6703

확인해 봤는데 
여유가 있어도 같은 현상이 생기네요
신규 test 버전은 응답 없음이 뜨지는 않지만
전송 도중 멈추는 현상은 동일하게 발생합니다.
