### ISSUE TITLE
픽시브 다운로드가 안됩니다

### ISSUE THREAD

**Issue by 234rr23** [KurtBestor/Hitomi-Downloader#6707]
항상 잘쓰고있습니다
쿠키 새로 불러와도 안됩니다

Invalid: [pixiv] https://www.pixiv.net/users/61997845

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko_kr
order / group / uid: 1 / False / 9bc9a5d6be994417bd320bc22eff2d29
input: https://www.pixiv.net/users/61997845
type: pixiv
single: False
url: https://www.pixiv.net/users/61997845
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702913574.7770293 (23-12-18 15:32:54 UTC) - 519s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
sid: 8119083_xg4Fvcw2Gv1FymNmcjIkNjYhBM2oXNsy
types: ['illusts', 'manga'], tag: None
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "utils", line 1367, in start
 File "utils", line 1446, in start_
 File "extractor\pixiv_downloader", line 109, in read
 File "extractor\pixiv_downloader", line 464, in get_info
 File "extractor\pixiv_downloader", line 513, in process_user
 File "extractor\pixiv_downloader", line 182, in top
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\pixiv_downloader", line 155, in call
 File "downloader", line 351, in read_json
 File "myjson", line 14, in loads
 File "json\__init__", line 348, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
EOT: https://www.pixiv.net/users/61997845  (41.9s)

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 네트워크 - 내장 웹브라우저 - 보기` 에서 해당 링크 들어가면 어떻게 보이나요?
