### ISSUE TITLE
다운로드에러 문제를 해결 못하겠어요

### ISSUE THREAD

**Issue by redfill2t9** [KurtBestor/Hitomi-Downloader#6709]
version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 6983d2bc4aac470a85b19ec033d866d2
input: https://manatoki319.net/comic/17698501
type: manatoki
single: False
url: https://manatoki319.net/comic/17698501
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702957518.8847878 (23-12-19 03:45:18 UTC) - 87s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: None None
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\manatoki_downloader", line 87, in init
 File "utils", line 663, in __get__
 File "extractor\manatoki_downloader", line 103, in name
 File "extractor\manatoki_downloader", line 121, in get_artist
 File "utils", line 2679, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki319.net/comic/17698501  (13.8s)

no title
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\manatoki_downloader", line 87, in init
 File "utils", line 663, in __get__
 File "extractor\manatoki_downloader", line 103, in name
 File "extractor\manatoki_downloader", line 121, in get_artist
 File "utils", line 2679, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki319.net/comic/17698501  (13.8s)

no title
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\manatoki_downloader", line 87, in init
 File "utils", line 663, in __get__
 File "extractor\manatoki_downloader", line 103, in name
 File "extractor\manatoki_downloader", line 121, in get_artist
 File "utils", line 2679, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki319.net/comic/17698501  (13.8s)

<img width="448" alt="44984985" src="https://github.com/KurtBestor/Hitomi-Downloader/assets/154297102/52f08db9-aa3d-4a41-a166-af48d99e4b22">

언제나 유용한 프로그램 이용할 수 있게 해주신점 감사합니다

지난주부터 이미지와 같은 에러로 GoodbyeDPI가 실행이 되지않아

검색해보니, 답변해두신것들 중 Temp폴더안 WinDivert64를 확인해보라신걸 보고

확인해보니 파일이 없어서(백신의 오진인가 뭔가로 사라진거같아요) GoodbyeDPI를 받아

실행도 해보고 WinDivert를 Temp안에 넣어도봤지만 히토미다운로더에서의 DPI작동은 실패했습니다

해서 따로 DPI를 켜고 다운로더를 사용해봤지만 어느사이트에서 사용해도 연결중에서 에러가 나고 작업정보 내용은 위와 같습니다

다운로더를 삭제재설치해도 같은에러가 생기고 어떻게 해결할 수 있을까요?

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by redfill2t9** [comment]
비트디펜더 사용하고 있어요
