### ISSUE TITLE
픽시브가 다운이 안되는데 뭐가 문제일까요

### ISSUE THREAD

**Issue by NyaHan16** [KurtBestor/Hitomi-Downloader#6727]
4분 55초 뒤 다시 시작: Invalid: [pixiv] https://www.pixiv.net/artworks/114437162

version: 4.0+ (23-12-22 13:44:48 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 7a05f5f9cf1846d3832675243e1e5ca8
input: https://www.pixiv.net/artworks/114437162
type: pixiv
single: False
url: https://www.pixiv.net/artworks/114437162
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1703340647.14772 (23-12-23 14:10:47 UTC) - 106s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html
No HTML
no html

stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\pixiv_downloader", line 46, in init
 File "clf2", line 176, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://www.pixiv.net/artworks/114437162  (100.9s)

오류가 뜨고난뒤에 작업정보 보기를 눌러서 뜬 오류를 그대로 복붙한것이고
![캡처](https://github.com/KurtBestor/Hitomi-Downloader/assets/153910972/20e1fb97-5791-43eb-8cfb-4731b868fce9)
현재 버전은 사진에 나오듯이 제일 최신버전입니다.

**Comment by zksxkxk** [comment]
일단 쿠키를 다시 먹여보세요

**Comment by NyaHan16** [comment]
쿠키 다시 맥여도 여전히 똑같이 읽는중... 만 반복하다가 오류납니다

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 네트워크 - 내장 웹브라우저 - 보기` 에서 해당 링크 들어가면 어떻게 보이나요?

**Comment by NyaHan16** [comment]
![123](https://github.com/KurtBestor/Hitomi-Downloader/assets/153910972/a308f94b-2279-47a5-acd5-7c0297fe6198)

제가 다운하고자 하는 주소를 입력하고 엔터를 눌러도 아무것도 뜨지 않습니다

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나오는 내용 보여주세요

**Comment by NyaHan16** [comment]
pyi: 4.10
PrefixPath: C:/Users/ADMINI~1/AppData/Local/Temp/_MEI139682/PyQt6/Qt6
LibraryExecutablesPath: C:/Users/ADMINI~1/AppData/Local/Temp/_MEI139682/PyQt6/Qt6/bin
BinariesPath: C:/Users/ADMINI~1/AppData/Local/Temp/_MEI139682/PyQt6/Qt6/bin
QT_PLUGIN_PATH: C:\Users\ADMINI~1\AppData\Local\Temp\_MEI139682\PyQt6\Qt6\plugins
QML2_IMPORT_PATH: C:\Users\ADMINI~1\AppData\Local\Temp\_MEI139682\PyQt6\Qt6\qml
constants: False

PIL: 9.3.0
webp: True

Font: 맑은 고딕 -> Open Sans
Platform: Windows-10-10.0.19045-SP0
System: Windows
Temp: C:\Users\ADMINI~1\AppData\Local\Temp
Qt 6.5.1 / PyQt 6.5.1 / SIP 6.7.12
$ D:\sitpal\adsf\만화\hitomi_downloader_GUI\hitomi_downloader_GUI.exe
{'debug': False, 'disable-gpu': False, 'no-browser': False, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': False, 'experimental': False, 'auto-scale': False, 'tmpdir': None, 'scale': 1, 'round-menu': True}

C:\Users\Administrator\AppData\Local\Temp
D:\sitpal\adsf\만화\hitomi_downloader_GUI
[strip path] %TEMP%

winId: 132900
handle: <PyQt.QtGui.QWindow object at 0x00000282F9888550>
Supported Image Formats: [b'bmp', b'pbm', b'pgm', b'png', b'ppm', b'webp', b'xbm', b'xpm']
^q^

Checking for updates... HitomiDownloader2

ml3o=pqNFTfxSReN2+fX5n8jba84=NzCVBOxXAVGoE9sU+fVI1jtHZ3tz+11GGDV6QUZwxwApEMa3WPYNvacqlsNnO3WgEzo2pMXaqE5JMjwoT7ueYREzsP+zQQ18KFTX0kIHRTFd10P4KaMqHMQPm7U2gc+kZyrsYoYMsy+6ub54KFSmfi9wjk=Mh67ot8E9yGJFzXfR9Vs9uQnaIpiv0RP+l26KdWCJAlKW7jBosG=85QfcuI+fi9zS=7JtStnSYfENsOLZMAE52dutLuXNLJhp2Xe1N47gDS0X4VTHtEeHi0rJeFpId1k9PzsNjvZ

v4.0 (latest: v4.0)
Encodings: ['cp949', 'utf-8', 'ascii', 'utf-8', 'utf-8']
legacy pageCheck: False
Saved: exists
download yt_dlp
yt-dlp8.tar.gz
import youtube-dl
youtube-dl version: 2023.10.07
[append_datas] size: 4454, elapsed time: 20.254085699999997
db: True
GoodbyeDPI activated

Styles:
    windowsvista
    Windows
    Fusion

vm: False

start GoodbyeDPI
GoodbyeDPI deactivated
close GoodbyeDPI
GoodbyeDPI activated
start GoodbyeDPI
GoodbyeDPI deactivated
close GoodbyeDPI
GoodbyeDPI activated
start GoodbyeDPI
Checking for updates... version_check.txt

fz2bX301VfTDt6+cWr1SW+E45ncIZZt2tDzdceLCaphPxKt+MI=TIbHqGyMhYkNWY=P+ahdgOw+QV3EXc1j3NoDcI0H25auFyZxONcSxeFxPbq0PjTyVzQ4KTRws7B=1US3aT3ZmeCYsLZb9ayOKBpRIchADzSENgECnJTE0PrP3StkvpAYR0u1m=laN5r=JYwDT=SWtoa0ABsySXDJLjYKI3WaDT4xeuGVJEltvAwxcpE47QglqYu+WFlUv86IXz2RqTtmCRd6PCvzxQLegoQKkhOpF98LLe8m3gO0E64SOke97Hgp8K0SEB8rbVgGXV2t=YLbTXVM8r43QtHhS7A

**Comment by KurtBestor** [comment]
[여기](https://github.com/KurtBestor/Hitomi-Downloader/releases) 에서 다른 버전들은 되나요?

**Comment by NyaHan16** [comment]
제가 기억하기론 픽시브에서 긁어 가는것을 막을때? 그때 이후로 계속 막혀온걸로 기억합니다.
자동업데이트로 계속 최신버전을 사용했고
전에 누가 테스트버전을 쓰면 사용가능하다고 해서 그때 테스트버전을 설치해보았지만 여전히 작동안되던걸로 기억합니다
