### ISSUE TITLE
Iwara 영상들이 다 Invalid라고 뜨네요 ㅠㅠ

### ISSUE THREAD

**Issue by charlificate** [KurtBestor/Hitomi-Downloader#6737]
![Screenshot 2023-12-26 033829](https://github.com/KurtBestor/Hitomi-Downloader/assets/49923803/32881439-fde4-4760-b5ab-115817996595)

이 중 하나 작업정보도 올려둘게요!

그리고 하시는 김에 #6031 이것도 다시 한번 봐주실 수 있을까요? 아직도 작가 다운로드가 제대로 안돼서요 ㅠㅠ

Invalid: [iwara] https://www.iwara.tv/video/IVHAdsQWEnAClJ

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / en_us
order / group / uid: 5 / False / eca4da24110245208655983bf908dbf0
input: https://www.iwara.tv/video/IVHAdsQWEnAClJ
type: iwara
single: True
url: https://www.iwara.tv/video/IVHAdsQWEnAClJ
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1703529229.2852526 (23-12-25 18:33:49 UTC) - 416s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
not f
button: Unfollow
button: Show more
button: Like
button: Add to
button: Share
button: Preview
button: Formatting
button: Submit
button: Unfollow
button: Show more
button: Like
button: Add to
button: Share
button: Reply
button: Reply
button: Show more
button: Reply
button: Show more
button: Reply
button: Show more
button: Preview
button: Formatting
button: Submit
button: Unfollow
button: Show more
button: Like
button: Add to
button: Download
button: Share
button: Reply
button: Reply
button: Show more
button: Reply
button: Show more
button: Reply
button: Show more
button: Preview
button: Formatting
button: Submit
not f
name: Source
not f
not f
button: Unfollow
button: Show more
button: Like
button: Add to
button: Share
button: Reply
button: Reply
button: Show more
button: Reply
button: Show more
button: Reply
button: Show more
button: Preview
button: Formatting
button: Submit
button: Unfollow
button: Show more
button: Like
button: Add to
button: Share
button: Reply
button: Reply
button: Show more
button: Reply
button: Show more
button: Reply
button: Show more
button: Preview
button: Formatting
button: Submit
button: Unfollow
button: Show more
button: Like
button: Add to
button: Download
button: Share
button: Reply
button: Reply
button: Show more
button: Reply
button: Show more
button: Reply
button: Show more
button: Preview
button: Formatting
button: Submit
not f
name: Source
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\iwara_downloader", line 32, in read
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\iwara_downloader", line 259, in get_info
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://www.iwara.tv/video/IVHAdsQWEnAClJ  (89.8s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by charlificate** [comment]
다시 개별 다운로드는 되는데 #6031 에서 제기된 특정 비디오가 작가 다운로드에서 다운 안되는 문제는 아직도 남아있습니다
