### ISSUE TITLE
spankbang 이 invalid가 너무 많이 뜨고 중간에 중지되는 영상도 너무 많습니다

### ISSUE THREAD

**Issue by k750627** [KurtBestor/Hitomi-Downloader#6753]
다운로드 안되는 영상 (이외에도 매우 다수)
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

Invalid: [etc] https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / e71563a992024b248e2a41cb29b1b165
input: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
type: etc
single: True
url: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1703986453.387112 (23-12-31 01:34:13 UTC) - 89s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
extractor: spankbang
get_video: True, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
get_video: True, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
get_video: True, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
get_video: True, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
ERROR: [SpankBang] 933i3: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
get_video: False, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
get_video: False, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
get_video: False, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
get_video: False, https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix
[debug] [SpankBang] 933i3: Downloading webpage
ERROR: [SpankBang] 933i3: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\networking\_urllib", line 410, in _send
   res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\networking\common", line 114, in send
   response = handler.send(request)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\networking\_helper", line 204, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\networking\common", line 325, in send
   return self._send(request)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\networking\_urllib", line 415, in _send
   raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 457, in urlopen
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 4070, in urlopen
   raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\spankbang", line 74, in _real_extract
   webpage = self._download_webpage(
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\extractor\common", line 860, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [SpankBang] 933i3: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 67, in get_video
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\etc_downloader", line 99, in _get_video
 File "extractor\etc_downloader", line 95, in _get_video
 File "ytdl", line 465, in extract_info
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 933i3: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\etc_downloader", line 31, in read
 File "extractor\etc_downloader", line 79, in get_video
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\etc_downloader", line 99, in _get_video
 File "extractor\etc_downloader", line 95, in _get_video
 File "ytdl", line 465, in extract_info
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI280722\ytdl_b3f1d0f2\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 933i3: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://jp.spankbang.com/933i3/video/the+more+the+better+emma+hix  (4.6s)

다운 중간에 멈춰서 재시도나 삭제후 재 다운로드 해도 안되는 경우
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[Spankbang] エロくて可愛いセフレに中出し

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 23 / False / fc395895c21d4900834c51f94660a39d
input: https://jp.spankbang.com/92cpq/video/porn
type: etc
single: True
url: https://jp.spankbang.com/92cpq/video/porn
dir: hitomi_downloaded_etc
zip: 
artist: giyuta685
valid / done: False / True
range / range_p: None / None
time: 1703981293.813633 (23-12-31 00:08:13 UTC) - 5265s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False

[File Names]
[0001] hitomi_downloaded_etc\[Spankbang] エロくて可愛いセフレに中出し (92cpq).mp4

[URLs]
[0001] LazyUrl(https://jp.spankbang.com/92cpq/video/porn)    --->    M3u8_stream(https://hls-uranus.sb-cd.com/hls/1/5/15226334-720p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=slDjxZIVRiHPPz6YlAQzwQ%2C1704018077)

[Messages]
extractor: spankbang
get_video: True, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
[debug] [SpankBang] 92cpq: Downloading stream JSON
[debug] [SpankBang] 92cpq: Downloading m3u8 information
[debug] [SpankBang] 92cpq: Downloading m3u8 information
[warning] [SpankBang] Failed to download m3u8 information: The read operation timed out
[debug] [SpankBang] 92cpq: Downloading m3u8 information
[debug] [SpankBang] 92cpq: Downloading m3u8 information
format:240p - 240p - resolution:240 - vbr:0 - audio:0 - url:https://vdownload-45.sb-cd.com/1/5/15226334-240p.mp4?secure=EYCISEeXBVGoSL5BUN-QBQ,1704024497&m=45&d=1&_tid=15226334
format:hls-373 - 426x240 - resolution:240 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-240p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
format:480p - 480p - resolution:480 - vbr:0 - audio:0 - url:https://vdownload-45.sb-cd.com/1/5/15226334-480p.mp4?secure=EYCISEeXBVGoSL5BUN-QBQ,1704024497&m=45&d=1&_tid=15226334
format:hls-1043-0 - 852x480 - resolution:480 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-480p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
format:hls-1043-1 - 852x480 - resolution:480 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-480p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=xxQjy8hgRcdNU530B9HUJw,1704021390
format:720p - 720p - resolution:720 - vbr:0 - audio:0 - url:https://vdownload-45.sb-cd.com/1/5/15226334-720p.mp4?secure=EYCISEeXBVGoSL5BUN-QBQ,1704024497&m=45&d=1&_tid=15226334
format:hls-2099-0 - 1280x720 - resolution:720 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-720p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
format:hls-2099-1 - 1280x720 - resolution:720 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-720p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=slDjxZIVRiHPPz6YlAQzwQ,1704018077
res: 4320
video0: format:hls-2099-1 - 1280x720 - resolution:720 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-720p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=slDjxZIVRiHPPz6YlAQzwQ,1704018077
video: format:hls-2099-1 - 1280x720 - resolution:720 - vbr:0 - audio:1 - url:https://hls-uranus.sb-cd.com/hls/1/5/15226334-720p.mp4/index-v1-a1.m3u8?_tid=15226334&d=1&m=45&secure=slDjxZIVRiHPPz6YlAQzwQ,1704018077
audio: None
url_thumb: https://tbi.sb-cd.com/t/15226334/1/5/w:500/t8-enh/porn.jpg
media: 0

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-34-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

retry (1)

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-34-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-34-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

retry (1)

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-80-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

retry (1)

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-80-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-80-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

retry (1)

Fail : https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-80-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957
Traceback (most recent call last):
 File "downloader", line 1138, in download
Exception: 502

Traceback (most recent call last):
 File "m3u8_tools", line 60, in run
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "m3u8_tools", line 346, in _read
 File "m3u8_tools", line 341, in _read
Exception: Failed to download: https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-80-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957

Fail : [Spankbang] エロくて可愛いセフレに中出し (92cpq).mp4
Traceback (most recent call last):
 File "downloader", line 900, in download
 File "m3u8_tools", line 312, in read
 File "m3u8_tools", line 60, in run
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "m3u8_tools", line 346, in _read
 File "m3u8_tools", line 341, in _read
Exception: Failed to download: https://vstream-45.sb-cd.com/hls/1/5/15226334-720p.mp4/hls_6s_-80-v1-a1.ts?_tid=15226334&d=1&m=45&secure=Y3y30aA8YvVOkuIGi4T9_g,1703996957

stop
valid=False 1 (0, hitomi_downloaded_etc\[Spankbang] エロくて可愛いセフレに中出し (92cpq).mp4)
-show_streams -print_format json -v error "[Spankbang] エロくて可愛いセフレに中出し (92cpq).mp4"
{ 

} 
[Spankbang] エロくて可愛いセフレに中出し (92cpq).mp4: Invalid argument 
Traceback (most recent call last):
 File "utils", line 1959, in finish
 File "ffmpeg", line 869, in get_info
 File "ffmpeg", line 866, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://jp.spankbang.com/92cpq/video/porn  (74.2s)

extractor: spankbang
get_video: True, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
get_video: True, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
get_video: True, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
get_video: True, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
ERROR: [SpankBang] 92cpq: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
get_video: False, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
get_video: False, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
get_video: False, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
get_video: False, https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] Extracting URL: https://jp.spankbang.com/92cpq/video/porn
[debug] [SpankBang] 92cpq: Downloading webpage
ERROR: [SpankBang] 92cpq: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\networking\_urllib", line 410, in _send
   res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\networking\common", line 114, in send
   response = handler.send(request)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\networking\_helper", line 204, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\networking\common", line 325, in send
   return self._send(request)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\networking\_urllib", line 415, in _send
   raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 457, in urlopen
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 4070, in urlopen
   raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\spankbang", line 74, in _real_extract
   webpage = self._download_webpage(
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\extractor\common", line 860, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [SpankBang] 92cpq: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 67, in get_video
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\etc_downloader", line 99, in _get_video
 File "extractor\etc_downloader", line 95, in _get_video
 File "ytdl", line 465, in extract_info
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 92cpq: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\etc_downloader", line 31, in read
 File "extractor\etc_downloader", line 79, in get_video
 File "decorator", line 232, in fun
 File "constants", line 903, in try_
 File "constants", line 872, in try_
 File "extractor\etc_downloader", line 99, in _get_video
 File "extractor\etc_downloader", line 95, in _get_video
 File "ytdl", line 465, in extract_info
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\sanggun\AppData\Local\Temp\_MEI228922\ytdl_28777a48\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 92cpq: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
invalid; revert
EOT: https://jp.spankbang.com/92cpq/video/porn  (12.1s)

**Comment by zizonkim** [comment]
지나가다가 혹시나해서 이 방법 한번 써보세요  지금 스팽크팽 주소가 http://jp 잖아요 사이트 언어가 일어로 되어있는건데 
사이트 우측 상단에 [A] 누르고 언어설정을 영어로 바꾸고 해당주소를 히토미에 복붙  
이거 안되면 저도 잘

**Comment by k750627** [comment]
그거도 시도해봤는데 역시 안먹히는 경우가 대부분이라..

**Comment by rickmiron** [comment]
plugin: https://github.com/rickmiron/variado/blob/main/spankbang_downloader.py

**Comment by kenasis428** [comment]
#6735 여기 테스트 파일 받아서 함 해보세요 .
