### ISSUE TITLE
xhamster 채널다운로드 인식 오류

### ISSUE THREAD

**Issue by gorehcna** [KurtBestor/Hitomi-Downloader#6755]
https://xhamster.com/creators/*****/exclusive 페이지는 잘 인식하나
https://xhamster.com/shemale/creators/*****/exclusive는 인식하지 않는 것 같습니다.

**Comment by Hyoros** [comment]
doubleposting won't help you. people have genuine problem like xhams unable to download (v4.0
https://xhamster.com/videos/blondelashes-cosplay-hinata-xhsxuSz

Fail_403 : \\?\C:\Users\(my directory)\Western C\z lump\Xhamster\blondelashes Cosplay Hinata (xhsxuSz).mp4
stop
valid=False 1 (0, C:\Users\(my directory)\Western C\z lump\Xhamster\blondelashes Cosplay Hinata (xhsxuSz).mp4)
-show_streams -print_format json -v error "blondelashes Cosplay Hinata (xhsxuSz).mp4"
{ 

} 
blondelashes Cosplay Hinata (xhsxuSz).mp4: No such file or directory 
Traceback (most recent call last):
 File "utils", line 1959, in finish
 File "ffmpeg", line 869, in get_info
 File "ffmpeg", line 866, in get_info
Exception: Failed to convert; exit code: 1
