### ISSUE TITLE
기본데이터 다운로드하는 도중이 실패합니다.

### ISSUE THREAD

**Issue by jumpingrabbit441** [KurtBestor/Hitomi-Downloader#6772]
Traceback (most recent call last):
  File "downloader", line 430, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 640, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 502, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 458, in read_html
  File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://kurtpyanywhere.com/h_data

삭제된 데이터의 경우 문제 없이 받아집니다.

**Comment by suzukioha** [comment]
이제 다시 되네요

**Comment by KurtBestor** [comment]
지금도 그런가요?

**Comment by jumpingrabbit441** [comment]
문제 없이 잘 됩니다.

**Comment by acarmit** [comment]
> 지금도 그런가요?

첨에 올리신분은 되신다는데 저는 오늘 하니까 오류가 납니다.

Traceback (most recent call last):
  File "downloader", line 430, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 640, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 502, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 463, in read_html
  File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://kurtpyanywhere.com/h_data

**Comment by acarmit** [comment]
오늘은 되네요...이건 프로그램 문제가 아닌 서버쪽문제인가 보네요
