### ISSUE TITLE
Only can download page 1 of v2ph

### ISSUE THREAD

**Issue by Sam0791** [KurtBestor/Hitomi-Downloader#6774]
FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み

version: 4.0+ (24-01-08 14:17:57 UTC)
platform / locale: Windows-10-10.0.19042-SP0 / zh_tw
order / group / uid: 0 / False / 657ec99759db423e8e325129a061009d
input: https://www.v2ph.com/album/z7n3m3na.html
type: v2ph
single: False
url: https://www.v2ph.com/album/z7n3m3na.html
dir: C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1704734462.0258203 (24-01-08 17:21:02 UTC) - 227s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0000.jpg
[0002] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0001.jpg
[0003] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0002.jpg
[0004] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0003.jpg
[0005] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0004.jpg
[0006] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0005.jpg
[0007] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0006.jpg
[0008] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0007.jpg
[0009] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0008.jpg
[0010] C:\Users\User\OneDrive\桌面\hitomi_downloader_GUI\Pics\FLASHデジタル写真集 豊田ルナ ヒロインは幼馴染み\0009.jpg

[URLs]
[0001] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0000.jpg
[0002] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0001.jpg
[0003] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0002.jpg
[0004] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0003.jpg
[0005] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0004.jpg
[0006] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0005.jpg
[0007] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0006.jpg
[0008] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0007.jpg
[0009] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0008.jpg
[0010] LazyUrl(https://www.v2ph.com/album/z7n3m3na.html)    --->    【local】 0009.jpg

[Messages]
https://www.v2ph.com/album/z7n3m3na.html
https://www.v2ph.com/album/z7n3m3na.html?page=2
Traceback (most recent call last):
 File "downloader", line 412, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\v2ph_downloader", line 85, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 909, in try_
 File "constants", line 878, in try_
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\v2ph_downloader", line 74, in read_soup
 File "downloader", line 356, in read_soup
 File "downloader", line 458, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.v2ph.com/album/z7n3m3na.html?page=2

stop
stop_live: False
EOT: https://www.v2ph.com/album/z7n3m3na.html  (32.8s)

https://www.v2ph.com/album/z7n3m3na.html
https://www.v2ph.com/album/z7n3m3na.html?page=2
Traceback (most recent call last):
 File "downloader", line 412, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\v2ph_downloader", line 85, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 909, in try_
 File "constants", line 878, in try_
 File "ratelimit\decorators", line 113, in wrapper
 File "ratelimit\decorators", line 80, in wrapper
 File "extractor\v2ph_downloader", line 74, in read_soup
 File "downloader", line 356, in read_soup
 File "downloader", line 458, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.v2ph.com/album/z7n3m3na.html?page=2

stop
stop_live: False
EOT: https://www.v2ph.com/album/z7n3m3na.html  (29.9s)

**Comment by rickmiron** [comment]
You need to add cookies from your user
