### ISSUE TITLE
can't download from youtube, stuck on "loading yt-dlp"

### ISSUE THREAD

**Issue by vvyce** [KurtBestor/Hitomi-Downloader#6776]
Invalid: [youtube] https://www.youtube.com/watch?v=XCTdS7FJ-4I

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ru_ru
order / group / uid: 0 / False / 70b8447a5344415e8f507a0205fc3385
input: https://www.youtube.com/watch?v=XCTdS7FJ-4I
type: youtube
single: True
url: https://www.youtube.com/watch?v=XCTdS7FJ-4I
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1704805372.093886 (24-01-09 13:02:52 UTC) - 587s elapsed
tags: []
lock: False
color: invalid
paused: False
format: {'format': 'mp3', 'res': 4320, 'abr': 320}
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: None None
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 473, in read
 File "utils", line 4708, in ready
 File "extractor\youtube_downloader", line 60, in get
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

No module named 'dataclasses'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\youtube_downloader", line 480, in read
 File "extractor\youtube_downloader", line 473, in read
 File "utils", line 4708, in ready
 File "extractor\youtube_downloader", line 60, in get
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI136802\ytdl_ca425ec1\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=XCTdS7FJ-4I  (21.8s)

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

### youtube retry...
Traceback (most recent call last):
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 473, in read
 File "utils", line 4708, in ready
 File "extractor\youtube_downloader", line 60, in get
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

No module named 'dataclasses'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\youtube_downloader", line 480, in read
 File "extractor\youtube_downloader", line 473, in read
 File "utils", line 4708, in ready
 File "extractor\youtube_downloader", line 60, in get
 File "extractor\youtube_downloader", line 50, in get
 File "ytdl", line 577, in __init__
 File "ytdl", line 351, in YoutubeDL
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ytdl", line 317, in get_ytdl
 File "ytdl", line 306, in get_ytdl
 File "imp", line 171, in load_source
 File "<frozen importlib._bootstrap>", line 702, in _load
 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\__init__", line 32, in <module>
   from .downloader.external import get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\__init__", line 26, in <module>
   from .external import FFmpegFD, get_external_downloader
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\downloader\external", line 14, in <module>
   from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\postprocessor\__init__", line 38, in <module>
   _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\plugins", line 162, in load_plugins
   name, Path(get_executable_path(), COMPAT_PACKAGE_NAME, name, '__init__'))
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\utils\_utils", line 4640, in get_executable_path
   from ..update import _get_variant_and_executable_path
 File "C:\Users\Mark\AppData\Local\Temp\_MEI122562\ytdl_33c8e208\yt_dlp\yt_dlp\update", line 12, in <module>
   from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=XCTdS7FJ-4I  (27.9s)

**Comment by KurtBestor** [comment]
Fixed

**Comment by keroberos-s** [comment]
다시 고장난건가요? 다른 영상안되서 이걸로도 해보는데 안되네요

**Comment by QuadrupleRainbow** [comment]
안녕하세요? 지금  4.1 버전으로 yt-dlp가 로딩되지 않아 youtube 영상을 내려받을 수 없는 같은 문제를 겪고 있습니다.

트위터나 pixiv에서도 영상을 내려받는데 FFprobe, FFmpeg가 로딩되지 않아 영상을 내려받지 못하는 비슷한 문제를 겪고 있습니다.
https://github.com/KurtBestor/Hitomi-Downloader/issues/7231

**Comment by QuadrupleRainbow** [comment]
이틀 동안 뭔 짓을 해도 해결 안 되고 오늘 오전만 해도 안 됐었는데 갑자기 오후 되니까 다시 작동하네요;; 다음에는 문제가 4일 이상 지속되는 경우에만 issue에 보고하겠습니다
