### ISSUE TITLE
soundcloud failed on add cover

### ISSUE THREAD

**Issue by AlexisinGit** [KurtBestor/Hitomi-Downloader#6778]
Seems to be broken on low wifi and certain mp3?

D V D - Britney Spears - Everytime (D v D & Supercub Remix)

version: 4.0+ (24-01-09 01:26:36 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: 2 / False / d0a88dae83c04974b6121c1e31026d8b
input: https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix
type: soundcloud
single: True
url: https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix
dir: hitomi_downloaded_soundcloud
zip: 
artist: D V D
valid / done: False / True
range / range_p: None / None
time: 1704963231.1660433 (24-01-11 08:53:51 UTC) - 101s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_soundcloud\D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3

[URLs]
[0001] LazyUrl(https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix)    --->    https://cf-media.sndcdn.com/8yQHfT5w0JjC?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vOHlRSGZUNXcwSmpDKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwNDk2MzM1N319fV19&Signature=VJEVbMc0Qq0eK20N65zE2mGnnUcSSmC86SK8JgbZBdI1ulEMXWbE2Hb4i8YO6HCgNw4-Ihwo-MylhfESeHfs61Pz7P1pXCVG6MKs9asbdb2YEFc-489Lyi211iWltpWeGRCeVZYhfkdxzI7g1Uwy83-srtKkMqLrSLSUiCA56nwUleCIdxR1psba7nsLdSwNkDMCCgOgJTaSeo8x4mS1Of~SfXhGXLtFjssxVcZvVAlFZhGOjCNccuDrPnPeY9jJSPT3tgP1Zx837YoWsU5ciLgeJOF4cmDMcbh55uub-DWtDM1b7PCQb5~u1Qi9-qyvPp~RPvIyRnrcgTY8R7mfiQ__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ

[Messages]
[ytdl] [debug] Encodings: locale cp936, fs utf-8, pref cp936, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'extract_flat': True, 'playlistend': 2000, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'writeautomaticsub': True, 'logger': <ytdl.Logger object at 0x000002353CB9B3D0>, 'proxy': 'socks5h://127.0.0.1:2080', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {'all': 'socks5h://127.0.0.1:2080'}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [soundcloud] Extracting URL: https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix
[ytdl] [soundcloud] dvdmtl/britney-spears-everytime-d-v-d-supercub-remix: Downloading info JSON
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] 772806214: Downloading webpage
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] Unable to download JSON metadata: [Errno 2] No such file or directory (caused by TransportError('[Errno 2] No such file or directory'))
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
【https】 format【download - audio only】 abr【None】
【m3u8_native】 format【hls_mp3_128 - audio only】 abr【128】
【http】 format【http_mp3_128 - audio only】 abr【128】
【m3u8_native】 format【hls_opus_64 - audio only】 abr【64】
rename (1): C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3 -> C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\tmpf2abc025c0704300b44bf67322ee0177_i.mp3
-i tmpf2abc025c0704300b44bf67322ee0177_i.mp3 -i tmpf2abc025c0704300b44bf67322ee0177_o.jpg -map 0 -map 1 -c copy -id3v2_version 3 -metadata album="Britney Spears - Everytime (D v D & Supercub Remix)" -metadata artist="D V D" -metadata:s:v comment="Cover (front)" tmpf2abc025c0704300b44bf67322ee0177_o.mp3
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Guessed Channel Layout for Input Stream #0.0 : stereo 
Input #0, wav, from 'tmpf2abc025c0704300b44bf67322ee0177_i.mp3': 
 Metadata: 
   encoded_by      : Logic Pro X 
   date            : 2020-03-09 
   creation_time   : 22:21:21 
   time_reference  : 158760000 
   umid            : 0x00000000000000000000000000000000000000000000000000000000DB004E07EB3B8F0BA03D7B52FF7F000006B0190E01000000E0357B52FF7F0000ECDE919A 
   coding_history  : 
 Duration: 00:03:26.40, bitrate: 1411 kb/s 
 Chapters: 
   Chapter #0:0: start 0.000000, end 206.400000 
     Metadata: 
       title           : Tempo: 150.0 
 Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s 
Input #1, image2, from 'tmpf2abc025c0704300b44bf67322ee0177_o.jpg': 
 Duration: 00:00:00.04, start: 0.000000, bitrate: 6988 kb/s 
 Stream #1:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 25 fps, 25 tbr, 25 tbn 
[mp3 @ 000001cc60b5c800] Invalid audio stream. Exactly one MP3 audio stream is required. 
[out#0/mp3 @ 000001cc60b5c700] Could not write header (incorrect codec parameters ?): Invalid argument 
[vost#0:1/copy @ 000001cc60b3ce00] Error initializing output stream: 
Stream mapping: 
 Stream #0:0 -> #0:0 (copy) 
 Stream #1:0 -> #0:1 (copy) 
   Last message repeated 1 times 
[code]
1
Lazyurl pp Error: \\?\C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3
Traceback (most recent call last):
 File "hitomi_downloader", line 458, in run
 File "hitomi_downloader", line 453, in pp_
 File "extractor\soundcloud_downloader", line 95, in pp
 File "ffmpeg", line 718, in add_cover
 File "ffmpeg", line 706, in add_cover
Exception: Failed to convert; exit code: 1

stop
-show_streams -print_format json -v error "D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3"
stop_live: False
EOT: https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix  (42.8s)

quality: 75%
[ytdl] [debug] Encodings: locale cp936, fs utf-8, pref cp936, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'extract_flat': True, 'playlistend': 2000, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'writeautomaticsub': True, 'logger': <ytdl.Logger object at 0x000002353C6D31F0>, 'proxy': 'socks5h://127.0.0.1:2080', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {'all': 'socks5h://127.0.0.1:2080'}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [soundcloud] Extracting URL: https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix
[ytdl] [soundcloud] dvdmtl/britney-spears-everytime-d-v-d-supercub-remix: Downloading info JSON
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] 772806214: Downloading webpage
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [soundcloud] 772806214: Downloading JSON metadata
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
【https】 format【download - audio only】 abr【None】
【m3u8_native】 format【hls_mp3_128 - audio only】 abr【128】
【http】 format【http_mp3_128 - audio only】 abr【128】
【m3u8_native】 format【hls_opus_64 - audio only】 abr【64】
rename (1): C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3 -> C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\tmp6b8ef40f48fa45c88291ea6ca95e119b_i.mp3
-i tmp6b8ef40f48fa45c88291ea6ca95e119b_i.mp3 -i tmp6b8ef40f48fa45c88291ea6ca95e119b_o.jpg -map 0 -map 1 -c copy -id3v2_version 3 -metadata album="Britney Spears - Everytime (D v D & Supercub Remix)" -metadata artist="D V D" -metadata:s:v comment="Cover (front)" tmp6b8ef40f48fa45c88291ea6ca95e119b_o.mp3
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Guessed Channel Layout for Input Stream #0.0 : stereo 
Input #0, wav, from 'tmp6b8ef40f48fa45c88291ea6ca95e119b_i.mp3': 
 Metadata: 
   encoded_by      : Logic Pro X 
   date            : 2020-03-09 
   creation_time   : 22:21:21 
   time_reference  : 158760000 
   umid            : 0x00000000000000000000000000000000000000000000000000000000DB004E07EB3B8F0BA03D7B52FF7F000006B0190E01000000E0357B52FF7F0000ECDE919A 
   coding_history  : 
 Duration: 00:03:26.40, bitrate: 1411 kb/s 
 Chapters: 
   Chapter #0:0: start 0.000000, end 206.400000 
     Metadata: 
       title           : Tempo: 150.0 
 Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s 
Input #1, image2, from 'tmp6b8ef40f48fa45c88291ea6ca95e119b_o.jpg': 
 Duration: 00:00:00.04, start: 0.000000, bitrate: 6988 kb/s 
 Stream #1:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 25 fps, 25 tbr, 25 tbn 
[mp3 @ 000001a8b6c95ec0] Invalid audio stream. Exactly one MP3 audio stream is required. 
[out#0/mp3 @ 000001a8b6cbcf80] Could not write header (incorrect codec parameters ?): Invalid argument 
[vost#0:1/copy @ 000001a8b6c9d400] Error initializing output stream: 
Stream mapping: 
 Stream #0:0 -> #0:0 (copy) 
 Stream #1:0 -> #0:1 (copy) 
   Last message repeated 1 times 
[code]
1
Lazyurl pp Error: \\?\C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3
Traceback (most recent call last):
 File "hitomi_downloader", line 458, in run
 File "hitomi_downloader", line 453, in pp_
 File "extractor\soundcloud_downloader", line 95, in pp
 File "ffmpeg", line 718, in add_cover
 File "ffmpeg", line 706, in add_cover
Exception: Failed to convert; exit code: 1

stop
-show_streams -print_format json -v error "D V D - Britney Spears - Everytime (D v D & Supercub Remix).mp3"
stop_live: False
EOT: https://soundcloud.com/dvdmtl/britney-spears-everytime-d-v-d-supercub-remix  (20.5s)

------

D V D - INTO U

version: 4.0+ (24-01-09 01:26:36 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: 1 / False / d8e24b4df3f1476fb49144e4763a3241
input: https://soundcloud.com/dvdmtl/into-u
type: soundcloud
single: True
url: https://soundcloud.com/dvdmtl/into-u
dir: hitomi_downloaded_soundcloud
zip: 
artist: D V D
valid / done: False / True
range / range_p: None / None
time: 1704962973.8552046 (24-01-11 08:49:33 UTC) - 406s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_soundcloud\D V D - INTO U.mp3

[URLs]
[0001] LazyUrl(https://soundcloud.com/dvdmtl/into-u)    --->    https://cf-media.sndcdn.com/42bXTwjyRYGH?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNDJiWFR3anlSWUdIKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwNDk2MzExNX19fV19&Signature=YldgB-zUTALUmLc6mxv2i7yNaHijqXDMTNX~BzcYruSBpadpvTiGxSjVimHUBaCx-lSkQMeEk1F4NuIMlnuknWqPrE~u0bH-G6-RbDg9Xuw08lReTP4WnaUCadsq7Uqk6bkebpXxxpIDAOXOKDl9kijL5BeKDRZsmryR91vy63xhEe7bjVqMkzVmXGWvdIaJjbQxWit~RDCb6LpC1rj93fWB7v4kzfBTjfrpQ2nz~HBMSHHH0zZ0EdMeFTJg9BkOMSQYB-ghI5Bjwuls0gY4YkX9ri5sMFGFh~n4mrEieYVNHS2C~rZtUf4oqCNRwhdkl7Se1zk4RZfZ7sSVMaQe0A__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ

[Messages]
[ytdl] [debug] Encodings: locale cp936, fs utf-8, pref cp936, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'extract_flat': True, 'playlistend': 2000, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'writeautomaticsub': True, 'logger': <ytdl.Logger object at 0x000002353D422880>, 'proxy': 'socks5h://127.0.0.1:2080', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {'all': 'socks5h://127.0.0.1:2080'}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [soundcloud] Extracting URL: https://soundcloud.com/dvdmtl/into-u
[ytdl] [soundcloud] dvdmtl/into-u: Downloading info JSON
[ytdl] [soundcloud] 983802610: Downloading JSON metadata
[ytdl] [soundcloud] 983802610: Downloading webpage
[ytdl] [soundcloud] 983802610: Downloading JSON metadata
[ytdl] [soundcloud] 983802610: Downloading JSON metadata
[ytdl] [soundcloud] 983802610: Downloading JSON metadata
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
【https】 format【download - audio only】 abr【None】
【m3u8_native】 format【hls_mp3_128 - audio only】 abr【128】
【http】 format【http_mp3_128 - audio only】 abr【128】
【m3u8_native】 format【hls_opus_64 - audio only】 abr【64】
rename (1): C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\D V D - INTO U.mp3 -> C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\tmpf060371c0e8e429ead0699dd978a9970_i.mp3
-i tmpf060371c0e8e429ead0699dd978a9970_i.mp3 -i tmpf060371c0e8e429ead0699dd978a9970_o.jpg -map 0 -map 1 -c copy -id3v2_version 3 -metadata album="INTO U" -metadata artist="D V D" -metadata:s:v comment="Cover (front)" tmpf060371c0e8e429ead0699dd978a9970_o.mp3
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Guessed Channel Layout for Input Stream #0.0 : stereo 
Input #0, wav, from 'tmpf060371c0e8e429ead0699dd978a9970_i.mp3': 
 Metadata: 
   encoded_by      : Logic Pro X 
   date            : 2021-02-12 
   creation_time   : 00:21:18 
   time_reference  : 158230800 
   umid            : 0x000000000000000000000000000000000000000000000000000000008A006DEBA9AF617A803AF55AFF7F000010D55406010000005033F55AFF7F0000ECEE3FDD 
   coding_history  : 
 Duration: 00:03:54.00, bitrate: 1411 kb/s 
 Chapters: 
   Chapter #0:0: start 0.000000, end 12.000000 
     Metadata: 
       title           : Tempo: 160.0 
   Chapter #0:1: start 12.000000, end 24.000000 
     Metadata: 
       title           : Marker 1 
   Chapter #0:2: start 24.000000, end 81.000000 
     Metadata: 
       title           : Marker 2 
   Chapter #0:3: start 81.000000, end 82.500000 
     Metadata: 
       title           : Marker 3 
   Chapter #0:4: start 82.500000, end 234.000000 
     Metadata: 
       title           : Marker 4 
   Chapter #0:5: start 82.500000, end 120.000000 
     Metadata: 
       title           : Marker 5 
   Chapter #0:6: start 120.000000, end 166.500000 
     Metadata: 
       title           : Marker 6 
   Chapter #0:7: start 166.500000, end 168.687483 
     Metadata: 
       title           : Marker 7 
   Chapter #0:8: start 168.687483, end 175.500000 
     Metadata: 
       title           : Marker 8 
   Chapter #0:9: start 175.500000, end 178.500000 
     Metadata: 
       title           : Marker 9 
   Chapter #0:10: start 178.500000, end 193.500000 
     Metadata: 
       title           : 
   Chapter #0:11: start 193.500000, end 234.000000 
     Metadata: 
       title           : Marker 11 
 Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s 
Input #1, image2, from 'tmpf060371c0e8e429ead0699dd978a9970_o.jpg': 
 Duration: 00:00:00.04, start: 0.000000, bitrate: 7081 kb/s 
 Stream #1:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 25 fps, 25 tbr, 25 tbn 
[mp3 @ 000001b534232c80] Invalid audio stream. Exactly one MP3 audio stream is required. 
[out#0/mp3 @ 000001b534232b80] Could not write header (incorrect codec parameters ?): Invalid argument 
[vost#0:1/copy @ 000001b53420ca80] Error initializing output stream: 
Stream mapping: 
 Stream #0:0 -> #0:0 (copy) 
 Stream #1:0 -> #0:1 (copy) 
   Last message repeated 1 times 
[code]
1
Lazyurl pp Error: \\?\C:\Users\Carlos4060\Documents\hitomi_downloader\hitomi_downloaded_soundcloud\D V D - INTO U.mp3
Traceback (most recent call last):
 File "hitomi_downloader", line 458, in run
 File "hitomi_downloader", line 453, in pp_
 File "extractor\soundcloud_downloader", line 95, in pp
 File "ffmpeg", line 718, in add_cover
 File "ffmpeg", line 706, in add_cover
Exception: Failed to convert; exit code: 1

stop
-show_streams -print_format json -v error "D V D - INTO U.mp3"
stop_live: False
EOT: https://soundcloud.com/dvdmtl/into-u  (45.8s)

**Comment by AlexisinGit** [comment]
flac seems to be the correct suffixes for these file, while hitomi treated it as mp3
