### ISSUE TITLE
베타 최신버전으로 픽시브 다운로드 불가

### ISSUE THREAD

**Issue by Orange6539** [KurtBestor/Hitomi-Downloader#6792]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
에 있는 최신버전으로 시도 해 보았습니다

https://www.pixiv.net/user/5786529/series/125818
다운로드 시 안되네요
옵션 -> 설정 -> 네트워크 -> 내장 웹브라우저로 접근시 잘 보입니다

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/80187210/33ef6025-495e-436c-9c66-a3332497524a)

아래는 오류 메세지 입니다
-------------------------------
4분 1초 뒤 다시 시작: Invalid: [pixiv] https://www.pixiv.net/user/5786529/series/125818

version: 4.0+ (24-01-13 03:12:49 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 000625ba7d8f493682e497398d935bf9
input: https://www.pixiv.net/user/5786529/series/125818
type: pixiv
single: False
url: https://www.pixiv.net/user/5786529/series/125818
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1705218365.9697285 (24-01-14 07:46:05 UTC) - 63s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
not f
not f
not f
sid: gf7s74pn0gsjfrkl8hnvh74pi6uis0ke

stop
Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "extractor\pixiv_downloader", line 110, in read
 File "extractor\pixiv_downloader", line 315, in get_info
 File "extractor\pixiv_downloader", line 138, in __init__
 File "decorator", line 232, in fun
 File "constants", line 904, in try_
 File "constants", line 902, in try_
 File "extractor\pixiv_downloader", line 508, in my_id
extractor.pixiv_downloader.LoginRequired

Invalid: fail=False
stop_live: False
EOT: https://www.pixiv.net/user/5786529/series/125818  (17.2s)

sid: 7232899_FWQNvFSM1NT9A3CQqhfOsAUTPVAk8Scs

stop
Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "extractor\pixiv_downloader", line 110, in read
 File "extractor\pixiv_downloader", line 481, in get_info
NotImplementedError

Invalid: fail=True
stop_live: False
EOT: https://www.pixiv.net/user/5786529/series/125818  (3.5s)

**Comment by suzukioha** [comment]
저는 잘 되는데 다운로더가 있는 경로에 한글이 있나요? 다운로더가 있는 드라이브 경로에 한글이 있으면 안되더라구요

**Comment by suzukioha** [comment]
확인해봤는데 저도 시리즈는 다운이 안 되네요 ARTWORKS나 USER 링크는 다운 잘 되네요

**Comment by suzukioha** [comment]
artworks나 users 링크는 잘 되는 거 보면 해당 링크가 시리즈 링크라서 그런듯

**Comment by suzukioha** [comment]
artworks나 users 링크는 잘 되는 거 보면 해당 링크가 시리즈 링크라서 그런듯
그냥 해당 시리즈의 작가 페이지로 가서 users링크로 다운 받으면 다 받아져요
