### ISSUE TITLE
툰코사이트가 다운되지 않습니다

### ISSUE THREAD

**Issue by byeoriabba** [KurtBestor/Hitomi-Downloader#6801]
아래는 작업 정보 입니다

Invalid: [toonkor] https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4

version: 4.0+ (24-01-13 03:12:49 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 35192b1e13874de29195b3493f47d1c3
input: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4
type: toonkor
single: False
url: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1705500491.5133526 (24-01-17 14:08:11 UTC) - 20s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4
stop
Traceback (most recent call last):
 File "downloader", line 430, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1362, in start
 File "decorator", line 232, in fun
 File "constants", line 909, in try_
 File "constants", line 878, in try_
 File "dynamic_module_8", line 42, in init
 File "downloader", line 458, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4

Invalid: fail=True
EOT: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4  (18.9s)

403 Client Error: Forbidden for url: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4
stop
Traceback (most recent call last):
 File "downloader", line 431, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1376, in start
 File "decorator", line 232, in fun
 File "constants", line 933, in try_
 File "constants", line 902, in try_
 File "dynamic_module_8", line 42, in init
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4

Invalid: fail=True
stop_live: False
EOT: https://toonkor326.com/%EA%B7%80%ED%99%98%EC%9E%90%EC%9D%98-%EB%A7%88%EB%B2%95%EC%9D%80-%ED%8A%B9%EB%B3%84%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4  (16.8s)

**Comment by cjs1a** [comment]
저도 안되는데 혹시 해결 되셨나요

**Comment by byeoriabba** [comment]
> 저도 안되는데 혹시 해결 되셨나요

URL 최신으로 변경하니 잘 되네요
