### ISSUE TITLE
deviant art 다운이 안됩니다.

### ISSUE THREAD

**Issue by qarthadsht** [KurtBestor/Hitomi-Downloader#6827]
며칠 전 까지만 해도 잠깐 안되던 거 테스트 버전 히토미 다운로더를 받아서 해보니 됐는데
이틀전부터 다시 안되네요.
정식판으로도 해보고, 기술테스트판으로도 해봐도 그렇고...

Invalid: [deviant] https://ripleyr14.deviantart.com

version: 4.0+ (24-01-13 03:12:49 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / 614fcd47e633414bab370cc4616e72df
input: https://ripleyr14.deviantart.com
type: deviant
single: False
url: https://ripleyr14.deviantart.com
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1705958592.6685858 (24-01-22 21:23:12 UTC) - 6s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
local variable 'link' referenced before assignment
stop
Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "extractor\deviant_downloader", line 76, in read
 File "extractor\deviant_downloader", line 29, in get_name
UnboundLocalError: local variable 'link' referenced before assignment

Invalid: fail=True
stop_live: False
EOT: https://ripleyr14.deviantart.com  (1.4s)

**Comment by VanishingBlaze** [comment]
yeah, same issue here

**Comment by Rounlet** [comment]
저도 같은 증상입니다.
쿠키도 새로 구워서 런칭했는데도 소용없네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by qarthadsht** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

직전처럼 아예 안되는건 아닌데...
다운 받기 전에 파일 갯수 체크? 하는 부분도 수십초에 10개씩 체크하듯이 느리고,
체크 다한 후 다운 받는 속도도 초당 10~50kb일 정도로 느리고...
가끔은 몇 번 재시도 해야 다운이 성공하고 그러네요. 몇 달 전엔 쑥쑥 받아졌는데
deviant art에서 뭔가 전송 제한을 건가 싶기도 하고 잘 모르겠네요.

결론:이제는 데비앙아트 다운이 되기는 하는데, 전송 속도가 상당히 느리고 자주 끊기는 느낌.

**Comment by SlyMalk** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

The error itself is fixed, but, as mentioned above, now reading and download speeds from deviantart are extremely slow, and eventually it just stops downloading completely.

Also 'Login' and 'Update your cookies' icons keep showing even after successful login and cookies update.

**Comment by KurtBestor** [comment]
속도 저하는 [여기](https://github.com/KurtBestor/Hitomi-Downloader/issues/6025#issuecomment-1732978687) 의 문제를 해결하기 위해 생겼고 [v3.8f](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.8f) 과 동일한 속도예요
빠르게 읽으면 DeviantArt 에서 차단해요. 이것은 웹브라우저로 직접 볼 때도 동일해요
