### ISSUE TITLE
저장실패 오류

### ISSUE THREAD

**Issue by vipvirn** [KurtBestor/Hitomi-Downloader#6859]
![12312312](https://github.com/KurtBestor/Hitomi-Downloader/assets/74667516/15dd3492-c3ef-4f9d-99e1-800a89cf191f)
사진과 같이 뜨면서 저장을 누르면 저장이 안됩니다.

**Comment by vipvirn** [comment]
재실행시 아래와 같이 오류가뜹니다

Traceback (most recent call last):
  File "customWidget_new", line 973, in _updateLazy
  File "decorator", line 232, in fun
  File "MyConfigParser", line 22, in w
  File "MyConfigParser", line 109, in get
sqlite3.DatabaseError: database disk image is malformed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 660, in write_config_safe
  File "hitomi_downloader_GUI", line 780, in write_config
  File "hitomi_downloader_GUI", line 946, in _write_config
  File "customWidget_new", line 934, in updateLazy
  File "main_thread", line 43, in run
  File "main_thread", line 71, in exec_new
  File "decorator", line 232, in fun
  File "locker", line 64, in _wrapper
  File "customWidget_new", line 975, in _updateLazy
  File "decorator", line 232, in fun
  File "MyConfigParser", line 40, in w
  File "MyConfigParser", line 22, in w
  File "MyConfigParser", line 109, in get
sqlite3.OperationalError: no such table: Pixmap

**Comment by vipvirn** [comment]
예전에 저와 비슷한 이슈 있었던 분에게 주셨던 repair_tasks.hds로 복구하면 
Traceback (most recent call last):
File "customWidget_new", line 973, in _updateLazy
File "decorator", line 232, in fun
File "MyConfigParser", line 22, in w
File "MyConfigParser", line 109, in get
sqlite3.DatabaseError: database disk image is malformed

During handling of the above exception, another exception occurred:
위와 같이 뜹니다. 내보내기랑, 다운로드는 되는데 저장할때 계속 저 문구가 뜹니다.
