### ISSUE TITLE
dc의 스크립트를 적용해도 다운이 안됩니다.ㅜㅜ

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#6866]
4일 8시 즈음 디도스로 추정되는 공격으로 서버가 다운되어 500번 오류가 출력되고, 디시 사이트에 로그인이 되지 않았습니다.
이후 새벽 2~3시에 다시 접속이 풀려 모바일과 pc 환경에서 이미지 로딩이 정상적으로 되는 것을 확인하고 다운로더를 다시 돌렸는데, invalid 오류가 뜹니다

사이트의 구조가 변경된 것인지... 일단은 시간을 두고 지켜보려 합니다만, 혹시 스크립트의 수정이 필요한 사안인가 여쭤봅니다..ㅜㅜ

다운 링크와 로그는 다음과 같습니다.

**Comment by mita5549** [comment]
https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1

작업정보
4분 47초 뒤 다시 시작: Invalid: [dc] https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1

version: 4.0+ (24-01-13 03:12:49 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 84524c461d5c400dae662a318dbb614a
input: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1
type: dc
single: False
url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1707072098.1848118 (24-02-04 18:41:38 UTC) - 15s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "dynamic_module_0", line 84, in read
 File "dynamic_module_0", line 79, in name
 File "dynamic_module_0", line 74, in soup
 File "dynamic_module_0", line 97, in read_page
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1

Invalid: fail=True
stop_live: False
EOT: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1  (2.1s)

500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "dynamic_module_0", line 84, in read
 File "dynamic_module_0", line 79, in name
 File "dynamic_module_0", line 74, in soup
 File "dynamic_module_0", line 97, in read_page
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1

Invalid: fail=True
stop_live: False
EOT: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1  (1.2s)

500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "dynamic_module_1", line 84, in read
 File "dynamic_module_1", line 79, in name
 File "dynamic_module_1", line 74, in soup
 File "dynamic_module_1", line 97, in read_page
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1

Invalid: fail=True
stop_live: False
EOT: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1  (0.9s)

Timeout
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "dynamic_module_1", line 84, in read
 File "dynamic_module_1", line 79, in name
 File "dynamic_module_1", line 74, in soup
 File "dynamic_module_1", line 97, in read_page
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 993, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 53, in exec
Exception: Timeout

Invalid: fail=True
stop_live: False
EOT: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1  (60.1s)

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1344, in getresponse
 File "http\client", line 307, in begin
 File "http\client", line 276, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 426, in _make_request
 File "<string>", line 3, in raise_from
 File "urllib3\connectionpool", line 421, in _make_request
 File "http\client", line 1344, in getresponse
 File "http\client", line 307, in begin
 File "http\client", line 276, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "dynamic_module_1", line 84, in read
 File "dynamic_module_1", line 79, in name
 File "dynamic_module_1", line 74, in soup
 File "dynamic_module_1", line 97, in read_page
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 993, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Invalid: fail=True
stop_live: False
EOT: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1  (3.9s)

500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "dynamic_module_1", line 84, in read
 File "dynamic_module_1", line 79, in name
 File "dynamic_module_1", line 74, in soup
 File "dynamic_module_1", line 97, in read_page
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1

Invalid: fail=True
stop_live: False
EOT: https://gall.dcinside.com/board/view/?id=comic_new3&no=15043459&exception_mode=recommend&page=1  (0.8s)

**Comment by mita5549** [comment]
현시각 문제 해결을 확인했습니다.
500 Server Error의 특성상 시간이 해결해주는 케이스였네요.
이해할 수 없었던 것은, 이미지는 로딩이 완벽하게 되는데도... 서버 에러가 날 수 있군요... =ㅅ=;;;
처음 알았습니다...
