### ISSUE TITLE
spankbang 다운로드 불가능.

### ISSUE THREAD

**Issue by zizonkim** [KurtBestor/Hitomi-Downloader#6881]
4분 59초 뒤 다시 시작: Invalid: [etc] https://spankbang.com/98j7m/video/19

version: 4.0+ (24-02-09 08:31:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / b0534610a47d4f7a908e10da481d18cc
input: https://spankbang.com/98j7m/video/19
type: etc
single: True
url: https://spankbang.com/98j7m/video/19
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1707568793.9405577 (24-02-10 12:39:53 UTC) - 9s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
extractor: spankbang
get_video: True, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001ECA4E355E0>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
get_video: True, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001ECA6668580>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
get_video: True, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001ECA5508730>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
get_video: True, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001EC9EF6BC10>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
ERROR: [SpankBang] 98j7m: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
get_video: False, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001EC9F6833A0>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
get_video: False, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001ECA55C4610>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
get_video: False, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001EC8EC24250>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
get_video: False, https://spankbang.com/98j7m/video/19
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'writesubtitles': True, 'legacyserverconnect': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001EC9F39FCD0>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, sqlite3-3.35.5, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Loaded 1886 extractors
[ytdl] [SpankBang] Extracting URL: https://spankbang.com/98j7m/video/19
[ytdl] [SpankBang] 98j7m: Downloading webpage
ERROR: [SpankBang] 98j7m: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\networking\_urllib", line 410, in _send
   res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
   return self._request_director.send(req)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\networking\common", line 114, in send
   response = handler.send(request)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\networking\_helper", line 204, in wrapper
   return func(self, *args, **kwargs)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\networking\common", line 325, in send
   return self._send(request)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\networking\_urllib", line 415, in _send
   raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 477, in urlopen
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 4070, in urlopen
   raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
   return func(self, *args, **kwargs)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
   ie_result = ie.extract(url)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\common", line 715, in extract
   ie_result = self._real_extract(url)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\spankbang", line 74, in _real_extract
   webpage = self._download_webpage(
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\common", line 1118, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\extractor\common", line 860, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [SpankBang] 98j7m: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 68, in get_video
 File "decorator", line 232, in fun
 File "constants", line 936, in try_
 File "constants", line 905, in try_
 File "extractor\etc_downloader", line 100, in _get_video
 File "extractor\etc_downloader", line 96, in _get_video
 File "ytdl", line 485, in extract_info
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 415, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 98j7m: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1391, in start
 File "utils", line 1470, in start_
 File "extractor\etc_downloader", line 32, in read
 File "extractor\etc_downloader", line 80, in get_video
 File "decorator", line 232, in fun
 File "constants", line 936, in try_
 File "constants", line 905, in try_
 File "extractor\etc_downloader", line 100, in _get_video
 File "extractor\etc_downloader", line 96, in _get_video
 File "ytdl", line 485, in extract_info
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\WINDOWS\system32\_MEI177362\ytdl_1806726c\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 415, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 98j7m: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
quality: 75%
stop_live: False
EOT: https://spankbang.com/98j7m/video/19  (6.8s)

1.  히토미 다운로더 파일 버전은 어제 업로드하신 2024.02.09 버전을 사용중입니다 

2. spankbang 같은 경우에는 플러그인을 다운받아서 적용후 다운받는 방식이 있지만 이는 다운로더에서 자체적으로 
화질을 720p로 받으라고 설정을 해놔도  영상 화질이 4k 급이면 제일 좋은 등급으로 높여서 다운이 됩니다 그래서 
플러그인 다운로드 방식은 화질설정방법을 모름 + 다운 받을시 용량이 매우매우 큼 

3. 현재 히토미다운로더 실행시킬때  exe파일 바로가기를 만들고 속성에 --safemode 넣고 도스창을 이용해서 
실행시키는 방식을 사용중입니다   물론 평범하게 safemode가 없는 원본 파일을 걍 더블클릭으로 실행해봐도 
spankbang 사이트는 다운 불가입니다

**Comment by aa99367** [comment]
This problem still exists
