### ISSUE TITLE
sankaku 다운로드 불가

### ISSUE THREAD

**Issue by elementarya** [KurtBestor/Hitomi-Downloader#6891]
산카쿠 다운로드 invalid 상태입니다.
며칠전 이슈는 플러그인 문제라 다른 것 같고,
3주전 이슈는 같은지 모르겠는데 오래돼서 따로 올렸습니다.
```sankaku
6분 18초 뒤 다시 시작: Invalid: [sankaku] https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 2 / False / 5b769d4ec0b7479ea9c27a6cd18fb092
input: https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1707842455.0390456 (24-02-13 16:40:55 UTC) - 251s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito
'title'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 272, in get_imgs
KeyError: 'title'

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito  (5.1s)

types: img, gif, video
https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito
'title'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 272, in get_imgs
KeyError: 'title'

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito  (18.2s)

types: img, gif, video
https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito
'title'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 272, in get_imgs
KeyError: 'title'

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/posts?tags=misaki_kurehito  (28.6s)
```

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/6718
