### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by hoon050824** [KurtBestor/Hitomi-Downloader#6895]
유튜브 비디오의 다운로드가 정상적으로 완료된 것 처럼 표시되나, 파일이 존재하지 않습니다

https://github.com/KurtBestor/Hitomi-Downloader/assets/46698298/852b6e50-2655-4229-8e4d-61cbebbe4635

아래는 작업 정보란에 출력된 내용입니다
```24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: -179 / False / ecdd7527e0b94bddb790d84be21083de
input: https://www.youtube.com/watch?v=NwSiN-GwyMg
type: youtube
single: True
url: https://www.youtube.com/watch?v=NwSiN-GwyMg
dir: hitomi_downloaded_youtube
zip: 
artist: Harunabi ch. 하루나비
valid / done: True / True
range / range_p: None / None
time: 1707962931.864688 (24-02-15 02:08:51 UTC) - 1076s elapsed
tags: []
lock: False
color: done
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False


[File Names]
[0001] hitomi_downloaded_youtube\[Harunabi ch. 하루나비] 24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비.webm


[URLs]
[0001] Video(https://www.youtube.com/watch?v=NwSiN-GwyMg)    --->    【local_lazy】 [Harunabi ch. 하루나비] 24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비.webm


[Messages]
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=NwSiN-GwyMg
[debug] [youtube] NwSiN-GwyMg: Downloading webpage
[debug] [youtube] NwSiN-GwyMg: Downloading ios player API JSON
[debug] [youtube] NwSiN-GwyMg: Downloading android player API JSON
[debug] [youtube] NwSiN-GwyMg: Downloading player b854ee52
[debug] [youtube] NwSiN-GwyMg: Downloading m3u8 information
live: was_live
[27p][0.005408036342004218fps][None][None] mhtml [None / None] ─ sb3 - 48x27 (storyboard)
[45p][0.10010275269049808fps][None][None] mhtml [None / None] ─ sb2 - 80x45 (storyboard)
[90p][0.10010275269049808fps][None][None] mhtml [None / None] ─ sb1 - 160x90 (storyboard)
[180p][0.10010275269049808fps][None][None] mhtml [None / None] ─ sb0 - 320x180 (storyboard)
[None][0fps][30.782kbps][30.782] m4a [None / mp4a.40.5] ─ 599 - audio only (ultralow)
[None][0fps][32.94kbps][32.94] webm [None / opus] ─ 600 - audio only (ultralow)
[None][0fps][48.782kbps][48.782] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][48.042kbps][48.042] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][63.373kbps][63.373] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.471kbps][129.471] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][119.983kbps][119.983] webm [None / opus] ─ 251 - audio only (medium)
[144p][15fps][None][27.568] mp4 [avc1.4d400b / None] ─ 597 - 256x144 (144p)
[144p][15fps][None][27.47] webm [vp9 / None] ─ 598 - 256x144 (144p)
[144p][30fps][None][47.785] mp4 [avc1.4D400C / None] ─ 160 - 256x144 (144p)
[144p][30fps][None][41.83] webm [vp09.00.11.08 / None] ─ 278 - 256x144 (144p)
[240p][30fps][None][98.925] mp4 [avc1.4D4015 / None] ─ 133 - 426x240 (240p)
[240p][30fps][None][77.787] webm [vp09.00.20.08 / None] ─ 242 - 426x240 (240p)
[360p][30fps][None][178.773] mp4 [avc1.4D401E / None] ─ 134 - 640x360 (360p)
[360p][30fps][96.0kbps(fixed)][279.178] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[360p][30fps][None][128.812] webm [vp09.00.21.08 / None] ─ 243 - 640x360 (360p)
[480p][30fps][None][299.367] mp4 [avc1.4D401F / None] ─ 135 - 854x480 (480p)
[480p][30fps][None][203.137] webm [vp09.00.30.08 / None] ─ 244 - 854x480 (480p)
[720p][30fps][192.0kbps(fixed)][645.384] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)
[720p][30fps][None][517.046] mp4 [avc1.64001f / None] ─ 136 - 1280x720 (720p)
[720p][30fps][None][400.982] webm [vp9 / None] ─ 247 - 1280x720 (720p)
[720p][60fps][None][691.317] mp4 [avc1.640020 / None] ─ 298 - 1280x720 (720p60)
[720p][60fps][None][493.087] webm [vp09.00.40.08 / None] ─ 302 - 1280x720 (720p60)
[1080p][60fps][None][1166.819] mp4 [avc1.64002A / None] ─ 299 - 1920x1080 (1080p60)
[1080p][60fps][None][672.55] webm [vp09.00.41.08 / None] ─ 303 - 1920x1080 (1080p60)
[1440p][60fps][None][2093.111] webm [vp09.00.50.08 / None] ─ 308 - 2560x1440 (1440p60)

utime: 1707868800.0

# stream_final
[1440p][60fps][None][2093.111] webm [vp09.00.50.08 / None] ─ 308 - 2560x1440 (1440p60)

[None][0fps][30.782kbps][30.782] m4a [None / mp4a.40.5] ─ 599 - audio only (ultralow)
[None][0fps][32.94kbps][32.94] webm [None / opus] ─ 600 - audio only (ultralow)
[None][0fps][48.782kbps][48.782] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][48.042kbps][48.042] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][63.373kbps][63.373] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.471kbps][129.471] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][119.983kbps][119.983] webm [None / opus] ─ 251 - audio only (medium)
[360p][30fps][96.0kbps(fixed)][279.178] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192.0kbps(fixed)][645.384] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

[None][0fps][30.782kbps][30.782] m4a [None / mp4a.40.5] ─ 599 - audio only (ultralow)
[None][0fps][48.782kbps][48.782] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.471kbps][129.471] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[360p][30fps][96.0kbps(fixed)][279.178] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[720p][30fps][192.0kbps(fixed)][645.384] mp4 [avc1.64001F / mp4a.40.2] ─ 22 - 1280x720 (720p)

[None][0fps][30.782kbps][30.782] m4a [None / mp4a.40.5] ─ 599 - audio only (ultralow)
[None][0fps][48.782kbps][48.782] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.471kbps][129.471] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)

[None][0fps][129.471kbps][129.471] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)

filename: [Harunabi ch. 하루나비] 24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비.webm
Resolution: 1440p
Codec: vp09.00.50.08 / None
Abr: None
Subtype: webm
FPS: 60

Download audio: https://rr1---sn-n3cgv5qc5oq-u5xs.googlevideo.com/videoplayback?expire=1707984533&ei=NXLNZeGWDN-g0-kP_o6vsAI&ip=118.222.205.8&id=o-AF4a9-FgtA5yKMGCxaefvI6CHzLDy0K7aYgIOnWT7mNt&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=QT&mm=31%2C29&mn=sn-n3cgv5qc5oq-u5xs%2Csn-n3cgv5qc5oq-bh2ss&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1261250&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=299261396&dur=18491.279&lmt=1707932051325612&mt=1707962700&fvip=7&keepalive=yes&fexp=24007246&c=IOS&txp=7308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIsRmlnYYZ93nQCXFYKnmy17mBwLLZps2KcP4qxKiqAXAiByRrx_gArUIMoP4ANlQRSAix7FYxmXQRV-bZ9goxxSdw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAMdWVaQuoxb55lU9mYv84aCZeJqWwUSVTJqe6d-wk6DaAiEAnowp_zJQhhm84cpiCyO__pC-OEgL2jRiMHCRPlZSFYA%3D
thumb: https://i.ytimg.com/vi/NwSiN-GwyMg/maxresdefault.jpg
Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 602, in get
 File "utils", line 988, in request
 File "downloader", line 248, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 697, in send
 File "requests\sessions", line 794, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'D:\\Path\\다시보기\\Recorder\\hitomi_downloader_GUI\\hitomi_downloaded_youtube\\[Harunabi ch. 하루나비] 24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비.webm'

### reset size ###
Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 602, in get
 File "utils", line 988, in request
 File "downloader", line 248, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 697, in send
 File "requests\sessions", line 794, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'D:\\Path\\다시보기\\Recorder\\hitomi_downloader_GUI\\hitomi_downloaded_youtube\\[Harunabi ch. 하루나비] 24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비.webm'

### reset size ###
use just download: overwrite=True
stop
-show_streams -print_format json -v error "[Harunabi ch. 하루나비] 24.02.14 2024 한국 우타이테 이상형 월드컵(64강부터) 📖 하루나비.webm"
EOT: https://www.youtube.com/watch?v=NwSiN-GwyMg  (8.8s)

downloader_v3 fail... p[176 / 286]
Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002036B0127C0>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rr1---sn-n3cgv5qc5oq-u5xs.googlevideo.com', port=443): Max retries exceeded with url: /videoplayback?expire=1707984533&ei=NXLNZeGWDN-g0-kP_o6vsAI&ip=118.222.205.8&id=o-AF4a9-FgtA5yKMGCxaefvI6CHzLDy0K7aYgIOnWT7mNt&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=QT&mm=31%2C29&mn=sn-n3cgv5qc5oq-u5xs%2Csn-n3cgv5qc5oq-bh2ss&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1261250&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=299261396&dur=18491.279&lmt=1707932051325612&mt=1707962700&fvip=7&keepalive=yes&fexp=24007246&c=IOS&txp=7308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIsRmlnYYZ93nQCXFYKnmy17mBwLLZps2KcP4qxKiqAXAiByRrx_gArUIMoP4ANlQRSAix7FYxmXQRV-bZ9goxxSdw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAMdWVaQuoxb55lU9mYv84aCZeJqWwUSVTJqe6d-wk6DaAiEAnowp_zJQhhm84cpiCyO__pC-OEgL2jRiMHCRPlZSFYA%3D&range=184549376-185597951 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002036B0127C0>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 76, in run
 File "requests\sessions", line 602, in get
 File "utils", line 988, in request
 File "downloader", line 248, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='rr1---sn-n3cgv5qc5oq-u5xs.googlevideo.com', port=443): Max retries exceeded with url: /videoplayback?expire=1707984533&ei=NXLNZeGWDN-g0-kP_o6vsAI&ip=118.222.205.8&id=o-AF4a9-FgtA5yKMGCxaefvI6CHzLDy0K7aYgIOnWT7mNt&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=QT&mm=31%2C29&mn=sn-n3cgv5qc5oq-u5xs%2Csn-n3cgv5qc5oq-bh2ss&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1261250&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=299261396&dur=18491.279&lmt=1707932051325612&mt=1707962700&fvip=7&keepalive=yes&fexp=24007246&c=IOS&txp=7308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIsRmlnYYZ93nQCXFYKnmy17mBwLLZps2KcP4qxKiqAXAiByRrx_gArUIMoP4ANlQRSAix7FYxmXQRV-bZ9goxxSdw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAMdWVaQuoxb55lU9mYv84aCZeJqWwUSVTJqe6d-wk6DaAiEAnowp_zJQhhm84cpiCyO__pC-OEgL2jRiMHCRPlZSFYA%3D&range=184549376-185597951 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002036B0127C0>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

audio done```

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hoon050824** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

정상작동 확인되었습니다.
