### ISSUE TITLE
쏘걸이 마지막 cleaning에서 멈춥니다.

### ISSUE THREAD

**Issue by elkare111** [KurtBestor/Hitomi-Downloader#6902]
[Messages]
stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSNI-989-미카미 유아-유모자막/SSNI-989-미카미 유아-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSNI-989-미카미 유아-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssni-989-%eb%af%b8%ec%b9%b4%eb%af%b8-%ec%9c%a0%ec%95%84-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (350.9s)

stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSNI-989-미카미 유아-유모자막/SSNI-989-미카미 유아-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSNI-989-미카미 유아-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssni-989-%eb%af%b8%ec%b9%b4%eb%af%b8-%ec%9c%a0%ec%95%84-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (15.7s)

stop
Invalid: fail=False
invalid; revert
EOT: https://kr62.sogirl.so/ssni-989-%eb%af%b8%ec%b9%b4%eb%af%b8-%ec%9c%a0%ec%95%84-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (0.0s)

작업정보 양이 너무 많아서 마지막쪽에 왠지 중요한 정보인것 같은 부분만 잘랐습니다.

**Comment by rickmiron** [comment]
문제를 발견했습니다. 다운로드할 수 있는 파일 제한이 있습니다.
options --> preferences --> advanced --> maximum page limit --> 9999

**Comment by elkare111** [comment]
> 이것을 시도해 보세요: options --> preferences --> advanced --> maximum page limit --> 9999

시도해봤고 다시시작을 해봤지만 대기중....이라는것에서 변화가 없었습니다...ㅠ

**Comment by elkare111** [comment]
Cleaning...SSIS-586-카와키타 사이카-유모자막

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 4f162b675b6a42acbdfcf8295b04e361
input: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
type: sogirl
single: False
url: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
dir: hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1708613366.9798548 (24-02-22 14:49:26 UTC) - 16s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


-----중략------


[1996] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1995
[1997] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1996
[1998] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1997
[1999] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1998
[2000] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1999


[URLs]
[0001] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video0.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894)    --->    【local_lazy】 0
[0002] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video1.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894)    --->    【local_lazy】 1
[0003] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video2.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894)    --->    【local_lazy】 2
[0004] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video3.ts?v=1&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894)    --->    【local_lazy】 3


----중략-----

[Messages]
stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (375.8s)

stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (12.9s)

stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (12.4s)

stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (12.7s)

stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (12.9s)

stop
Traceback (most recent call last):
 File "utils", line 1646, in finish
 File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/  (14.9s)

**Comment by elkare111** [comment]
Cleaning...SSIS-586-카와키타 사이카-유모자막

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 4f162b675b6a42acbdfcf8295b04e361
input: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
type: sogirl
single: False
url: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
dir: hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1708613366.9798548 (24-02-22 14:49:26 UTC) - 16s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

-----중략------

[1996] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1995
[1997] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1996
[1998] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1997
[1999] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1998
[2000] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1999

[URLs]
[0001] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video0.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 0
[0002] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video1.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 1
[0003] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video2.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 2
[0004] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video3.ts?v=1&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 3

----중략-----

[Messages]
stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (375.8s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.9s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.4s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.7s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.9s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (14.9s)

**Comment by elkare111** [comment]
> 작업 정보를 표시합니다

Cleaning...SSIS-586-카와키타 사이카-유모자막

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 4f162b675b6a42acbdfcf8295b04e361
input: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
type: sogirl
single: False
url: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/
dir: hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1708613366.9798548 (24-02-22 14:49:26 UTC) - 16s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

-----중략------

[1996] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1995
[1997] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1996
[1998] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1997
[1999] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1998
[2000] hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막\1999

[URLs]
[0001] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video0.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 0
[0002] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video1.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 1
[0003] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video2.ts?v=0&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 2
[0004] LazyUrl(https://vz-f66772da-d96.b-cdn.net/f52d2591-5d98-4b7e-84ee-38cc95df050f/1280x720/video3.ts?v=1&resolution=1280x720&server=806&contextId=e9f7f8f1-6676-4940-8e81-a41d52864894) ---> 【local_lazy】 3

----중략-----

[Messages]
stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (375.8s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.9s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.4s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.7s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (12.9s)

stop
Traceback (most recent call last):
File "utils", line 1646, in finish
File "dynamic_module_0", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막/SSIS-586-카와키타 사이카-유모자막.mp4' -> 'hitomi_downloaded_sogirl\SSIS-586-카와키타 사이카-유모자막.mp4'

EOT: https://kr62.sogirl.so/ssis-586-%ec%b9%b4%ec%99%80%ed%82%a4%ed%83%80-%ec%82%ac%ec%9d%b4%ec%b9%b4-%ec%9c%a0%eb%aa%a8%ec%9e%90%eb%a7%89/ (14.9s)

**Comment by rickmiron** [comment]
다시 시작하지 말고 다시 시도해 보세요.

**Comment by jajajajo3** [comment]
저도 같은증상이있어서. 수정했습니다.
import downloader
from utils import Downloader, get_print, LazyUrl, Soup, clean_title
from io import BytesIO
import clf2
from hashlib import md5
import requests
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from ffmpeg import run
import os
from time import sleep
import shutil
from concurrent.futures import ThreadPoolExecutor

USERAGEN = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

@Downloader.register
class Downloader_sogirl(Downloader):
    type = 'sogirl'
    URLS = ['.sogirl.so']
    display_name = 'SoGirl'
    ACCEPT_COOKIES = [r'(.*\.)?(sogirl)\.(so)']
    MAX_CORE = 4
    MAX_PARALLEL = 2
    user_agent = USERAGEN

    def read(self):
        sesion = requests.session()
        sesion.headers['User-Agent'] = USERAGEN
        un = self.url.find('k')
        domi = self.url[un:self.url.find('.')]
        infof = getinf(self.url, domi)
        self.title = infof['filename']
        self.setIcon(infof['thumb'])
        diir = self.dir
        if os.path.exists(diir + '.mp4'):
            self.urls.append(diir + '.mp4')
            self.single = True
        else:
            if not os.path.exists(diir):
                os.makedirs(diir)
            self.urls = getm3u8(infof['iframe'], sesion, diir, self.cw, domi)
    
    def post_processing(self):
        if not self.single:
            fin = len(self.urls)
            ini = 0
            name0 = ''
            self.cw.setTitle('Joining parts...' + self.title)
            while ini < fin:
                parts = [str(ele) for ele in range(ini, min(ini + 2000, fin))]
                part_file = f'part_{ini // 2000}.ts'
                run(f'-i concat:{"|".join(parts)} -c copy {part_file}', self.dir)
                if ini == 0:
                    name0 = part_file
                else:
                    name0 = f'{name0}|{part_file}'
                ini += 2000
            
            run(f'-i concat:{name0} -c copy "{self.title}.mp4"', self.dir)
            self.cw.setTitle('Cleaning...' + self.title)
            os.rename(self.dir + '/' + self.title + '.mp4', self.dir + '.mp4')
            shutil.rmtree(self.dir)
            self.cw.setNameAt(0, self.dir + '.mp4')
            self.single = True
            self.cw.setTitle(self.title)

class Video:
    def __init__(self, url, sesion, cw, pos, cifralis, pinx, arstr):
        self.session = sesion
        self.cw = cw
        self.url = LazyUrl(url, self.get, self)
        self.pos = pos
        self.filename = str(pos)
        self.cifralis = cifralis
        self.pinx = pinx
        self.arstr = arstr
    
    def get(self, urlx):
        ind = self.pos // 3
        while len(self.cifralis) <= ind:
            if self.pos % 3 == 0:
                if self.pos % 12 == 0:
                    ackey = ind * 12
                    mdd5 = md5(f'{self.arstr[0]}_{self.arstr[1]}_{ackey}.000001_false_720'.encode('utf8')).hexdigest()
                    self.pinx[1] = f'{self.arstr[2]}/ping?hash={mdd5}&time={ackey}.000001&paused=false&resolution=720'
                self.session.get(self.pinx[1], headers={'Referer': 'https://iframe.mediadelivery.net/'})
                clave = self.session.get(self.arstr[3] + str(ind), headers={'referer': 'https://iframe.mediadelivery.net/'})
                while len(self.cifralis) != ind:
                    sleep(0.01)
                self.cifralis.append(Cipher(algorithms.AES(clave.content), modes.CBC(self.arstr[4]), backend=default_backend()))
                break
            else:
                sleep(0.01)
        descri = self.cifralis[ind].decryptor()
        pvid = self.session.get(urlx, headers={'Referer': 'https://iframe.mediadelivery.net/'})
        filedes = descri.update(pvid.content) + descri.finalize()
        ruta = self.arstr[5] + '/' + self.filename
        with open(ruta, 'wb') as file:
            file.write(filedes)
        return ruta

def getinf(urlx, domi):
    info = {}
    sesion = clf2.solve(f'https://{domi}.sogirl.so/wp-json/')['session']
    soup = Soup(downloader.read_html(urlx, session=sesion))
    info['filename'] = clean_title(soup.find('meta', {'property': 'og:title'})['content'].strip())
    urlthumb = soup.find('meta', {'property': 'og:image'})['content']
    info['thumb'] = BytesIO()
    downloader.download(urlthumb, buffer=info['thumb'], session=sesion)
    info['iframe'] = soup.find('iframe')['data-lazy-src']
    return info

def getm3u8(iframe, sesionx, ruta, cw, domi):
    arstri = []
    sop = sesionx.get(iframe, headers={'Referer': f'https://{domi}.sogirl.so/'}).text
    un = sop.find('loadUrl("') + 9
    urb = sop[un:sop.find('"', un)]
    un = sop.find('.loadSource(', un) + 13
    playlis = sop[un:sop.find(')', un) - 1]
    arstri.append(playlis[playlis.find('&') + 8:])
    urv = urb[:urb.rfind('/')]
    arstri.append(urv[urv.rfind('/') + 1:])
    mdd5 = md5(f'{arstri[0]}_{arstri[1]}_0_true_0'.encode('utf8')).hexdigest()
    arstri.append(urv)
    pingg = urv + '/ping?hash=' + mdd5 + '&time=0&paused=true&resolution=0'
    sesionx.get(pingg, headers={'Referer': 'https://iframe.mediadelivery.net/'})
    sesionx.get(urv + '/activate', headers={'Referer': 'https://iframe.mediadelivery.net/'})
    mdd5 = md5(f'{arstri[0]}_{arstri[1]}_0_true_720'.encode('utf8')).hexdigest()
    pingg = urv + '/ping?hash=' + mdd5 + '&time=0&paused=true&resolution=720'
    lista = sesionx.get(playlis, headers={'Referer': iframe}).text
    linkm3u8 = playlis[:playlis.find('playlist')] + lista.split()[-1]
    resm3u8 = sesionx.get(linkm3u8, headers={'Referer': 'https://iframe.mediadelivery.net/'}).text
    nkey = True
    inf = False
    archunk = []
    pos = 0
    cifralis = []
    pinx = [0, pingg]
    tup = None
    for linea in resm3u8.split():
        if inf:
            archunk.append(Video(linea, sesionx, cw, pos, cifralis, pinx, tup).url)
            pos += 1
            inf = False
        elif '#EXTI' in linea:
            inf = True
        elif nkey and '#EXT-X-K' in linea:
            un = linea.find('URI') + 5
            arstri.append(linea[un:linea.find('"', un) - 1])
            un = linea.find('IV=') + 5
            arstri.append(bytes.fromhex(linea[un:]))
            arstri.append(ruta)
            tup = tuple(arstri)
            nkey = False
    return archunk

**Comment by jajajajo3** [comment]
저도 같은증상있어서 플러그인 수정했습니다. 
[sogirl수정본.txt](https://github.com/user-attachments/files/15951230/sogirl.txt)

**Comment by rickmiron** [comment]
구성에서 파일 제한을 2000개 이상으로 확장하려고 했나요?
