### ISSUE TITLE
sankakucomplex가 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by MazinS5917** [KurtBestor/Hitomi-Downloader#6937]
안녕하십니까. 4년째 이 프로그램을 쓰는 사람입니다.
예전부터 gelbooru에서 하나하나 다운을 받다가 귀찮기도 해서 kemono랑 같이 sankakucomplex이쪽으로 이주해온 사람입니다.
hitomi downloader에서 이것도 다운을 받을 수 있다고 하여 다운을 받아 왔습니다만 다음과 같은 상태가 되어 다운로드가 되지 않습니다.
이럴 경우에는 어떻게 해야 하나요?

Invalid: [sankaku] https://chan.sankakucomplex.com/ko/posts?tags=high_school_dxd

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / e3c96f7936be4e6cb6f5003a14c05c6b
input: https://chan.sankakucomplex.com/ko/posts?tags=high_school_dxd
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/posts?tags=high_school_dxd
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1709120601.7422187 (24-02-28 11:43:21 UTC) - 11s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2023.12.30
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/ko/posts?tags=high_school_dxd
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\sankaku_downloader", line 233, in get_imgs
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

no images
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\sankaku_downloader", line 144, in read
 File "extractor\sankaku_downloader", line 321, in get_imgs
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/posts?tags=high_school_dxd  (3.8s)

**Comment by KurtBestor** [comment]
VPN을 쓰시거나, 관리자권한으로 실행하고 `옵션 - 설정 - 네트워크 - DPI 우회` 켜세요
