### ISSUE TITLE
코믹워커 문제점

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#6948]
1. 읽는 중에서 멈춤
2. 읽는 게 너무 느림 (전체 정보를 다 읽어서 그런거 같음)
3. 중간 페이지 빠져서 다운로드 됨

Invalid: [comicwalker] https://comic-walker.com/detail/KC_000061_S

version: 4.0+ (24-02-24 09:20:17 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 47167925398f4c979db849b0c1785b4e
input: https://comic-walker.com/detail/KC_000061_S
type: comicwalker
single: False
url: https://comic-walker.com/detail/KC_000061_S
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1709182207.0192924 (24-02-29 04:50:07 UTC) - 11s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.12.30
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
cid: KC_0000610000100011_E, eid: 018d6aa0-f4c1-7278-bfc9-62904df25b18
cid: KC_0000610000200011_E, eid: 018d6aa1-013e-72f6-9089-db9165255c83
cid: KC_0000610000300011_E, eid: 018d6aa1-0677-733e-8912-0e3821768931
cid: KC_0000610000300021_E, eid: 018d6aa1-0677-733f-9285-a94b8a888ece
cid: KC_0000610000400011_E, eid: 018d6aa1-0ae7-7387-85c0-ee27407f1c41
cid: KC_0000610000400021_E, eid: 018d6aa1-0ae7-7388-bd86-dc0bf1df927a
cid: KC_0000610000500011_E, eid: 018d6aa1-0f07-73c8-9438-8eda1d7b6162
cid: KC_0000610000500021_E, eid: 018d6aa1-0f07-73c9-98f7-a44aa30c3f6d
403 Client Error: Forbidden for url: https://comic-walker.com/api/contents/viewer?episodeId=018d6aa1-0f07-73c9-98f7-a44aa30c3f6d&imageSizeType=width%3A1284
stop
Traceback (most recent call last):
 File "downloader", line 431, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\comicwalker_downloader", line 65, in read
 File "extractor\comicwalker_downloader", line 172, in get_imgs
 File "decorator", line 232, in fun
 File "utils", line 5007, in _wrapper
 File "extractor\comicwalker_downloader", line 81, in get_imgs_page
 File "downloader", line 351, in read_json
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://comic-walker.com/api/contents/viewer?episodeId=018d6aa1-0f07-73c9-98f7-a44aa30c3f6d&imageSizeType=width%3A1284

Invalid: fail=True
EOT: https://comic-walker.com/detail/KC_000061_S  (7.9s)

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 네트워크 - 내장 웹브라우저 - 보기` 눌러서 로그인하세요
