### ISSUE TITLE
최신버전 업데이트시 failed to start http server error 뜨고, 방화벽 팝업도 새로 뜹니다

### ISSUE THREAD

**Issue by suzukioha** [KurtBestor/Hitomi-Downloader#6950]
기존에는 업데이트시에도 방화벽 물어보지 않았는데 이번 최신 버전은 방화벽 허락 팝업창도 뜹니다.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 11554, in <module>
  File "hitomi_server\__init__", line 465, in start
  File "hitomi_server\__init__", line 416, in join
  File "hitomi_server\__init__", line 409, in run
  File "decorator", line 232, in fun
  File "locker", line 64, in _wrapper
  File "hitomi_server\__init__", line 448, in switch
  File "hitomi_server\__init__", line 439, in switch
Exception: Already open: 6978

오류메시지입니다.

vpn을 쓰고 있어서 굿바이 dpi를 꺼놓기에 dpi기능 때문인건지는 모르겠습니다.

계속 뜨는 건 아니고 뜰 때 있고 안 뜰 때 있네요

**Comment by KurtBestor** [comment]
프로그램을 5개 이상 띄우면 HTTP API 를 열 포트가 부족해서 에러 메시지가 생길 거예요
6975 ~ 6978 까지 체크하다가 모두 이미 열려있으면 HTTP API 를 열지 못해요

**Comment by suzukioha** [comment]
> 프로그램을 5개 이상 띄우면 HTTP API 를 열 포트가 부족해서 에러 메시지가 생길 거예요 6975 ~ 6978 까지 체크하다가 모두 이미 열려있으면 HTTP API 를 열지 못해요

https 웹사이트만 이용하면 상관없는건가요?? 
다운로더 10개정도 켜고 구글북마크대신 링크정리하면서 다운 받는 게 너무 편해서요 ㅠㅠ

**Comment by KurtBestor** [comment]
HTTP API 안 쓰시면 상관 없어요
`옵션 - 설정 - 고급 - HTTP API` 에서 설정할 수 있어요
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4339#issuecomment-1028542727

**Comment by suzukioha** [comment]
> HTTP API 안 쓰시면 상관 없어요 `옵션 - 설정 - 고급 - HTTP API` 에서 설정할 수 있어요 참고해주세요: [#4339 (comment)](https://github.com/KurtBestor/Hitomi-Downloader/issues/4339#issuecomment-1028542727)

제 옵션 보니까 HTTP API가 꺼져있는데 failed to start http server error 경고팝업이 안 뜨게끔은 할 수 없는건가요??
URL에 HTTP:// 로 시작되는 HTTP API 웹사이트는 사용하지 않는데 직접 다 꺼줘야 하다 보니까 번거롭네요

**Comment by KurtBestor** [comment]
16개까지 켜도 되게 수정했어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by suzukioha** [comment]
> 16개까지 이어졌네요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

감사합니다!! 잘 됩니다!

**Comment by suzukioha** [comment]
> 16개까지 켜도 되게 수정했어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

감사합니다!! 잘 됩니다!
