### ISSUE TITLE
Nicovideo error

### ISSUE THREAD

**Issue by thgdorns** [KurtBestor/Hitomi-Downloader#6963]
Downloads complete just fine, but the resulting video files are invalid.

Restart in 4m 58s: [MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255)

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: 0 / False / 5d21cdd3bf594f8faa7e300d53f8df2f
input: https://www.nicovideo.jp/watch/sm43097255
type: nico
single: True
url: https://www.nicovideo.jp/watch/sm43097255
dir: D:\OTR\[MMD]
zip: 
artist: MAXポンコチーノ
valid / done: False / True
range / range_p: None / None
time: 1709331143.463404 (24-03-01 22:12:23 UTC) - 29s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
admin: False
goodbyedpi: None
ytdl: yt_dlp 2023.12.30
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] D:\OTR\[MMD]\[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4

[URLs]
[0001] LazyUrl(https://www.nicovideo.jp/watch/sm43097255)    --->    M3u8_stream(https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/video-h264-720p.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=vP0-TAbvx8DIYQebAoVWNDhqC2Kq7Wo-OJKX-~8fzbJNpeKjl8YQHl-FNu68ZszmicoKIdW8QGiucuGjna3v9w6~e9Vi~1O833uB8anBJeq1-C78aDnkY1CVjm2F7biDe3O7d17-hOumgJUTJQ21JaKDCDeklgEjRNjUCywTHwslwX7ErSSiU0MImJSvaASr0GV9ux2cTzBzHX5Ac-wp5FZ0ay9IAH~E4~sAxtqOvVE3eC3nsLY5bZksAfXqiUTZ-miPif5yDQLtd1W6nmvNXm2dlH0zoUNBk5qVGHlEz70F5GJirNec~GWOHAcG2kuN7zP9vBaDWZlBbX0s0TGP6Q__&Key-Pair-Id=K11RB80NFXU134)

[Messages]
[ytdl] [debug] Encodings: locale cp932, fs utf-8, pref cp932, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000002004D54FBE0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Lazy loading extractors is disabled
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1834 extractors
[ytdl] [niconico] Extracting URL: https://www.nicovideo.jp/watch/sm43097255
[ytdl] [niconico] sm43097255: Downloading webpage
[ytdl] [niconico] sm43097255: Downloading JSON metadata
[ytdl] [niconico] sm43097255: Downloading m3u8 information
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
res: 4320
None m3u8_native 64 - audio only (Main Audio) - https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/audio-aac-64kbps.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=vIXiNfL2L8TxPYdeqCuPdrPds~nlTPdEaaNRLg3T1lQ5iJZvKfCdRA6jTzNpmIbTMYy7spBrXvEONhZ3ZLaxb9oi4dUAKTZPmV-3tlCji54zBxeFwrLh9m34T7swQ0MiYXwZ6jVNEXhX61tK4Wr3O9R1hFI55EKgJ9gk1UoKIbdds27swSM9TWZj0jhWZ6Zwnf8Vj2khX9Dpxq55YdL10nzkSMNDI4kEfZeZmOfH24K~rlB93a6Lhw2uS0sFnKqfEMpVwce8v9DRUyGjRNMTjhRUYV-46Lj~36lcPwk251asTmaDMBbSitUpymLWORMxpPxRl55AOwiCZwjfXy4Q6Q__&Key-Pair-Id=K11RB80NFXU134
None m3u8_native 128 - audio only (Main Audio) - https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/audio-aac-128kbps.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=Z4EY7u6tpvv1VnOddPa0jclPMjHArBzWjShh7InmjfuOEhjskRR0Jn-4jfwZkuSlm7kPlTephO9IgUgVXGKe0o1mhhD8Osk8Bx7~RwCyg3rSDsmzhYN4Q1xyThBdWe~PTV7kjJfbi9KZdew9XVIteB1J4676Tbjy0lEtQKPuQ9qU0p4AeuUIUbBc1q0e3NQwjWJyzAllgzhuvROUrJynJaKv3BzYTu0QdTAzzVvmKRnwoN7SFI8PrHcyAIofuVT2eiqfkqi3oSbny8fAAVdoZDIwT9CchPlDrM1k0GDk3Q9GPDeZUw0bLYgzERd5yVsm~P8qV-tJ02XxyeVQgTkngQ__&Key-Pair-Id=K11RB80NFXU134
360 niconico_dmc h264_360p_low-aac_64kbps-hls - 640x360 (DMC Low-Quality HLS) - niconico_dmc:sm43097255/archive_h264_360p_low/archive_aac_64kbps
360 niconico_dmc h264_360p_low-aac_64kbps-http - 640x360 (DMC Low-Quality HTTP) - niconico_dmc:sm43097255/archive_h264_360p_low/archive_aac_64kbps
360 niconico_dmc h264_360p_low-aac_128kbps-hls - 640x360 (DMC Low-Quality HLS) - niconico_dmc:sm43097255/archive_h264_360p_low/archive_aac_128kbps
360 niconico_dmc h264_360p_low-aac_128kbps-http - 640x360 (DMC Low-Quality HTTP) - niconico_dmc:sm43097255/archive_h264_360p_low/archive_aac_128kbps
144 m3u8_native 154 - 256x144 - https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/video-h264-144p.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=qV-gpO0rEBXkzXpCj4dGy~-yl9Ib03K5uPp1bGjIGbc~kCdP9wdgf6UhNGG7Crvgmiq3E4~~Q8ZExYJVVw3gVcM489~YPmzNNc5JP3bOIyK-7PKBhNElxoD1vTuKiF~wQIyrQv3-4SsFIbQvzyJB9acwFrQ-r3fbY~stm5LbxxFj9EH7IAsQ67vhqxGRjLeedFhBl7JC18lghaIlIKFIQquu-3iZEEXGdXiJvC0JzDv1siRFLn2lUrFh1gVoHhEvnUg36skhZC9-aIR~y1y1H1csuOuv2ZyGTjRW59WaJNpqdNq7sfvCQGPLZHw7J7g4IPPwc0DkhCnVQ7VgJsLr3w__&Key-Pair-Id=K11RB80NFXU134
360 niconico_dmc h264_360p-aac_64kbps-hls - 640x360 (DMC 360p HLS) - niconico_dmc:sm43097255/archive_h264_360p/archive_aac_64kbps
360 niconico_dmc h264_360p-aac_64kbps-http - 640x360 (DMC 360p HTTP) - niconico_dmc:sm43097255/archive_h264_360p/archive_aac_64kbps
360 niconico_dmc h264_360p-aac_128kbps-hls - 640x360 (DMC 360p HLS) - niconico_dmc:sm43097255/archive_h264_360p/archive_aac_128kbps
360 niconico_dmc h264_360p-aac_128kbps-http - 640x360 (DMC 360p HTTP) - niconico_dmc:sm43097255/archive_h264_360p/archive_aac_128kbps
360 m3u8_native 608 - 640x360 - https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/video-h264-360p.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=puK71BKoWx5p26h13Bj3mhnJ2lICI6kfDH6oJYofdauBJ3cYupdiizmRt2vM5SoJutBj5giXwGs-SpEYfJ9Hh2gfzJDqAECPMCremoN4eSV9YKt14IHce4uEDL~ljOtR-SVI6BKGuL88VIHOSfL5hH~XaTCXyMNtb8xi~oxUmRp6rmy~qaNZ1JN2woKgjRqVJB0D42mgb7tqiFIQ5aG~3TgLi4B~qYAfpGcISuUuCllmhtij02ICY9kgyM-z0cuYsvzJHoiVGPLBe36OtADEkg4ACsZcKTE3kSlQlhGGZ7lMIoRGON0inc6XSILde5eP9txLatbrsQFg7ZKEPVhHzw__&Key-Pair-Id=K11RB80NFXU134
480 niconico_dmc h264_480p-aac_64kbps-hls - 854x480 (DMC 480p HLS) - niconico_dmc:sm43097255/archive_h264_480p/archive_aac_64kbps
480 niconico_dmc h264_480p-aac_64kbps-http - 854x480 (DMC 480p HTTP) - niconico_dmc:sm43097255/archive_h264_480p/archive_aac_64kbps
480 niconico_dmc h264_480p-aac_128kbps-hls - 854x480 (DMC 480p HLS) - niconico_dmc:sm43097255/archive_h264_480p/archive_aac_128kbps
480 niconico_dmc h264_480p-aac_128kbps-http - 854x480 (DMC 480p HTTP) - niconico_dmc:sm43097255/archive_h264_480p/archive_aac_128kbps
480 m3u8_native 2028 - 854x480 - https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/video-h264-480p.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=YbC1QhHkHz~I5ZQggMhO1haq4ZYmFueWkz8vW5ZKDHcqyVLhwGQgefm2vWDLk4EVl2TwZ9iiOv0vSHqlk92F3w3ZskrGQ8K2z7OKtkSn6Ni~ORb6-t325KC7t77Tm3Wl2SDDAcFbIHIACm1CV4HQWqaj~VCto53adZquGG2yCozimL6BrCTr-rKsgzwvYdBn1FO8ZzXS6EqN8PRYXplfBmf9m4mjfGPBMBphl8~QGi4lkxZJ3gheRiHYxdqkXZLCqTUV8hrCy8D7WoCLN7qCRuJPIFbvmGA9TOY-xdSpcO4nc2bA4A-RNfU-DGRr3egAp0cSbIwhJTyhuIUPih7E7w__&Key-Pair-Id=K11RB80NFXU134
720 niconico_dmc h264_720p-aac_64kbps-hls - 1280x720 (DMC 720p HLS) - niconico_dmc:sm43097255/archive_h264_720p/archive_aac_64kbps
720 niconico_dmc h264_720p-aac_64kbps-http - 1280x720 (DMC 720p HTTP) - niconico_dmc:sm43097255/archive_h264_720p/archive_aac_64kbps
720 niconico_dmc h264_720p-aac_128kbps-hls - 1280x720 (DMC 720p HLS) - niconico_dmc:sm43097255/archive_h264_720p/archive_aac_128kbps
720 niconico_dmc h264_720p-aac_128kbps-http - 1280x720 (DMC 720p HTTP) - niconico_dmc:sm43097255/archive_h264_720p/archive_aac_128kbps
720 m3u8_native 2084 - 1280x720 - https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/video-h264-720p.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=vP0-TAbvx8DIYQebAoVWNDhqC2Kq7Wo-OJKX-~8fzbJNpeKjl8YQHl-FNu68ZszmicoKIdW8QGiucuGjna3v9w6~e9Vi~1O833uB8anBJeq1-C78aDnkY1CVjm2F7biDe3O7d17-hOumgJUTJQ21JaKDCDeklgEjRNjUCywTHwslwX7ErSSiU0MImJSvaASr0GV9ux2cTzBzHX5Ac-wp5FZ0ay9IAH~E4~sAxtqOvVE3eC3nsLY5bZksAfXqiUTZ-miPif5yDQLtd1W6nmvNXm2dlH0zoUNBk5qVGHlEz70F5GJirNec~GWOHAcG2kuN7zP9vBaDWZlBbX0s0TGP6Q__&Key-Pair-Id=K11RB80NFXU134
f_url: https://delivery.domand.nicovideo.jp/hlsbid/656b0aa6a370f93e4c2020dc/playlists/media/video-h264-720p.m3u8?session=ca25682cec4aedd87ee9d731c58c8b938b0b696d5670f9fa0000000065e3a449d54a8e49ac81ce6a&Expires=1709417545&Signature=vP0-TAbvx8DIYQebAoVWNDhqC2Kq7Wo-OJKX-~8fzbJNpeKjl8YQHl-FNu68ZszmicoKIdW8QGiucuGjna3v9w6~e9Vi~1O833uB8anBJeq1-C78aDnkY1CVjm2F7biDe3O7d17-hOumgJUTJQ21JaKDCDeklgEjRNjUCywTHwslwX7ErSSiU0MImJSvaASr0GV9ux2cTzBzHX5Ac-wp5FZ0ay9IAH~E4~sAxtqOvVE3eC3nsLY5bZksAfXqiUTZ-miPif5yDQLtd1W6nmvNXm2dlH0zoUNBk5qVGHlEz70F5GJirNec~GWOHAcG2kuN7zP9vBaDWZlBbX0s0TGP6Q__&Key-Pair-Id=K11RB80NFXU134
### reset size ###
use just download: overwrite=False
media: 0
Convert: \\?\D:\OTR\[MMD]\[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4
rename (1): D:\OTR\[MMD]\[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4 -> D:\OTR\[MMD]\tmp01893881264c482298e6bd2d65860c89_i.mp4
-i tmp01893881264c482298e6bd2d65860c89_i.mp4 -acodec copy -vcodec copy -threads 0 tmp01893881264c482298e6bd2d65860c89_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000213f8e2ed00] could not find corresponding track id 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000213f8e2ed00] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000213f8e2ed00] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000213f8e2ed00] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000213f8e2ed00] error reading header
tmp01893881264c482298e6bd2d65860c89_i.mp4: Invalid data found when processing input
[code]
1
rename (1): D:\OTR\[MMD]\tmp01893881264c482298e6bd2d65860c89_i.mp4 -> D:\OTR\[MMD]\[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4

Fail m3u8 pp : [MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4
Traceback (most recent call last):
 File "downloader", line 924, in download
 File "m3u8_tools", line 391, in _pp
 File "ffmpeg", line 384, in convert
 File "ffmpeg", line 372, in convert
Exception: Failed to convert; exit code: 1

stop
valid=False 1 (0, D:\OTR\[MMD]\[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4)
-show_streams -print_format json -v error "[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4"
{

}
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000012209b6c200] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000012209b6c200] error reading header
[MAXポンコチーノ] 【東方MMD】 紅美鈴 威風堂々【あぁん↓ あぁん↑】 (sm43097255).mp4: Invalid data found when processing input
Traceback (most recent call last):
 File "ffmpeg", line 883, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2008, in finish
 File "ffmpeg", line 886, in get_info
 File "ffmpeg", line 883, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.nicovideo.jp/watch/sm43097255  (26.5s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
