### ISSUE TITLE
툰코 스크립트 url 수정해서 잘 사용하고있었는데 이번에 크롤링을 막았는지 스크립트가 실행이 안되네요

### ISSUE THREAD

**Issue by back-horn** [KurtBestor/Hitomi-Downloader#6968]
Invalid: [toonkor] https://toonkor340.com/%EB%8F%99%EB%84%A4-%EB%88%84%EB%82%98

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / a96be4dea33c4111950d60ee73a5d010
input: https://toonkor340.com/%EB%8F%99%EB%84%A4-%EB%88%84%EB%82%98
type: toonkor
single: False
url: https://toonkor340.com/%EB%8F%99%EB%84%A4-%EB%88%84%EB%82%98
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1709380810.706589 (24-03-02 12:00:10 UTC) - 5s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.12.30
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://toonkor340.com/%EB%8F%99%EB%84%A4-%EB%88%84%EB%82%98
stop
Traceback (most recent call last):
 File "downloader", line 431, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "dynamic_module_0", line 42, in init
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://toonkor340.com/%EB%8F%99%EB%84%A4-%EB%88%84%EB%82%98

Invalid: fail=True
EOT: https://toonkor340.com/%EB%8F%99%EB%84%A4-%EB%88%84%EB%82%98  (2.6s)

**Comment by erebuseyny** [comment]
저도 같은 증상임.
