### ISSUE TITLE
can't load cookies with cookies.txt or using any of the browser options

### ISSUE THREAD

**Issue by jack652** [KurtBestor/Hitomi-Downloader#6971]
can't load cookies with cookies.txt or using any of the browser options

trying with cookie.txt gives the error
```
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 10530, in loadCookiesTxt
  File "cooker", line 213, in load
  File "cooker", line 67, in load
  File "cooker", line 58, in prepare_line
http.cookiejar.LoadError: invalid length 1
```

trying with the brave option gives the error
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Temp\_MEI214282\ytdl_ebb7d715\yt_dlp\yt_dlp\cookies", line 294, in _extract_chrome_cookies
    cursor = _open_database_copy(cookie_database_path, tmpdir)
  File "C:\Users\USERNAME\AppData\Local\Temp\_MEI214282\ytdl_ebb7d715\yt_dlp\yt_dlp\cookies", line 1061, in _open_database_copy
    shutil.copy(database_path, database_copy_path)
  File "shutil", line 418, in copy
  File "shutil", line 264, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\USERNAME\\AppData\\Local\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Network\\Cookies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 10542, in loadCookiesFromBrowser
  File "cooker", line 286, in extract_cookies_from_browser
  File "C:\Users\USERNAME\AppData\Local\Temp\_MEI214282\ytdl_ebb7d715\yt_dlp\yt_dlp\cookies", line 115, in extract_cookies_from_browser
    return _extract_chrome_cookies(browser_name, profile, keyring, logger)
  File "C:\Users\USERNAME\AppData\Local\Temp\_MEI214282\ytdl_ebb7d715\yt_dlp\yt_dlp\cookies", line 327, in _extract_chrome_cookies
    raise DownloadError(message)  # force exit
yt_dlp.utils.DownloadError: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
```
i replaced my username with USERNAME

**Comment by YunfengCUI** [comment]
I have also encountered this problem. How was it handled

**Comment by jack652** [comment]
> I have also encountered this problem. How was it handled

Closing the browsers and then loading cookies in Hitomi by choosing the browsers option
