### ISSUE TITLE
웨일 브라우저 쿠키 불러오기가 안됩니다

### ISSUE THREAD

**Issue by 13-12** [KurtBestor/Hitomi-Downloader#6998]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/80605929/f4226f3d-6b1a-4b78-b51b-704257e29c6a)
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/80605929/d92c10b7-94e6-4cae-9302-8089a71f5ba1)
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/80605929/c25ad60c-b040-43dd-b027-304aee0da6be)

Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI236282\ytdl_eb3651e0\yt_dlp\yt_dlp\cookies", line 294, in _extract_chrome_cookies
    cursor = _open_database_copy(cookie_database_path, tmpdir)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI236282\ytdl_eb3651e0\yt_dlp\yt_dlp\cookies", line 1061, in _open_database_copy
    shutil.copy(database_path, database_copy_path)
  File "shutil", line 418, in copy
  File "shutil", line 264, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\AppData\\Local\\Naver\\Naver Whale\\User Data\\Profile 1\\Network\\Cookies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 10542, in loadCookiesFromBrowser
  File "cooker", line 286, in extract_cookies_from_browser
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI236282\ytdl_eb3651e0\yt_dlp\yt_dlp\cookies", line 115, in extract_cookies_from_browser
    return _extract_chrome_cookies(browser_name, profile, keyring, logger)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI236282\ytdl_eb3651e0\yt_dlp\yt_dlp\cookies", line 327, in _extract_chrome_cookies
    raise DownloadError(message)  # force exit
yt_dlp.utils.DownloadError: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info

혹시 어떻게 해야하나요?

+
테스트 버전으로 해보려 했는데 받는 법도 모르겠습니다...
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/80605929/f586e34f-38d1-4226-b61b-5f5028733437)

**Comment by depth221** [comment]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/22697167/da96eec0-ded1-4c24-98af-5547df21ad4d)
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/22697167/a599f24a-8029-41d1-918b-f7a2782a1c57)

[Get cookies.txt LOCALLY](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) 확장 프로그램을 웨일에 설치하신 후 쿠키를 가져올 웹 사이트에 접속, 로그인하고 나서 'Export' 버튼을 눌러 cookies.txt 파일을 다운로드하세요. 다운로드한 파일을 히토미 다운로더에 가져오면 정상 작동합니다.
