### ISSUE TITLE
니코동 녹화를 하면 화면만 녹화되고 음성이 안됩니다;;

### ISSUE THREAD

**Issue by son8520** [KurtBestor/Hitomi-Downloader#7006]
ㅈㄱㄴ

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by son8520** [comment]
> 해당 작업 정보 보여주세요

洲崎西 第552回放送（2024.02.20） (so43424304)

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / f047bfee8dee4b81b8b8f26418e88d06
input: https://www.nicovideo.jp/watch/so43424304
type: nico
single: True
url: https://www.nicovideo.jp/watch/so43424304
dir: hitomi_downloaded_nico
zip: 
artist: シーサイドチャンネル
valid / done: False / True
range / range_p: None / None
time: 1710336259.0970309 (24-03-13 13:24:19 UTC) - 266s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.12.30
pinned: False
extras: {}
live: False
changed: True


[File Names]
[0001] hitomi_downloaded_nico\洲崎西 第552回放送（2024.02.20） (so43424304).mp4


[URLs]
[0001] LazyUrl(https://www.nicovideo.jp/watch/so43424304)    --->    Downloader(https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/video-h264-480p.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=b5E6--2R8uoPTw2qXqiYyfWA-XOZ7jkCg7KJXxSlpDbpOiVA9SlqGpFWzIP2fXG1rAyW8zNQ3R4wNBq6gkaX6ejsdCwdBMqEF2K2~3ZG1kIiv2F1hqeo4l~iZndq3wBVCwN6StO2ja5ZG1EqMaXwVMgeI2rGsNSOxG~TH3fsikNVi8s~87333OGNetBjYz59VvknoeRZZz2l6Xfrl70x3m5Bla-PpEMmTe5jjLyCxDwwlmse93Us3XdqaHViKWnW9V4gxi7Uztjia7ek9NVPFJJqUfOxmvbmRUXp5J9buGGJ~QREBvsGYDzlMBohj7S-J4IMLuL5ZADKbj02jh34lg__&Key-Pair-Id=K11RB80NFXU134)


[Messages]
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000019E110584C0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Lazy loading extractors is disabled
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1834 extractors
[ytdl] [niconico] Extracting URL: https://www.nicovideo.jp/watch/so43424304
[ytdl] [niconico] so43424304: Downloading webpage
[ytdl] [niconico] so43424304: Downloading JSON metadata
[ytdl] [niconico] so43424304: Downloading m3u8 information
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
res: 4320
None m3u8_native audio-aac-64kbps - audio only (Main Audio) - https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/audio-aac-64kbps.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=IxqMJ-akjD8ubokvIBfbdZlkprKzTvNFd881rpYWPEzT3Hx06ngQD9wUfvlGCDF-tqc200syQPlKBiG6FGffSjqpUgeoWXP3MnZMZf-YFksFMfx-jvku9hGQjACwNbIeIxKSkWPVJhxO4o~4eBbDrHHiagAnpIYNqe9A03QLK9vZfqOoeB34RAXcHUhfELwnpRgco90a4Qu-yQDzOPUCCoBXeb~GL2ucGpP-36UJPMNaqKNNOFcpdFDKCAYjHD2YYYbeOitOXzTaS2B~09LM-l5E~pZ64IqUuomayWEQFIzMEXEJY3fIyPOSvWo2elgGe4XEYas~vZcYAhvEQMtSaw__&Key-Pair-Id=K11RB80NFXU134
None m3u8_native audio-aac-128kbps - audio only (Main Audio) - https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/audio-aac-128kbps.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=IxioFGLblfDa6HxEB932X58FzsLAiTcEFn988fdN8K3IL-IbWsNutgi-~KZQX0szoWz27dKNdp-dR228IEfbF8HdFNnblNVTcAo~tnI9cVEsHs6NfKu~wXS5IEDL0jmpz8cWrg-eqWLwq7pW~1FeZHaupyonM8xJxCEIEBpvP7HLnnvTxn8wOWxr6WlSbm84dSe1c9oDAPS-hUB1Ob~lLX-Yk3O0IjJw7VFcdzgLHFhyC1HyuJ53yTHeH~NW5PSHYaRJJvi~R7x6Og48eFH~iAAV7ll8m0hvZEkaGePtb1YH8U6L9mWZFsLtTL0isJJHQdMB~jkLDyG~5sTylxENOQ__&Key-Pair-Id=K11RB80NFXU134
144 m3u8_native video-115 - 256x144 - https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/video-h264-144p.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=RfjVqZ3MYPHUp4DbCvE5mPfhOEWl9QpmVksmIJny5hHsx1DIR5lrGa7h7yrQntxxgYlrHDbFiOaOKVTCYswpDML0lhQ8Y2XX2G2h5AiAyWkn6yPnl4vHSHFPbUzCR9T~UTqjo3thbDCoqvAY7QGkU70QmMPtoDV9~opc2ez3dqWiemku0YVeF-nG1VPMjKEx4nFPGreeX8VsuJ4-c0wgDYjkuvarOYaWi6z5GzHEBkCcksIYjqKUYgG0lmjTaWnr30~xDAhX8FdGK~raWqq1MSZOmsbRq2A86ehA8qh6sVTp0pOyHqqWeRZpHTovWhjbocKxsSkwtBk8bS9lfak8rA__&Key-Pair-Id=K11RB80NFXU134
360 m3u8_native video-466 - 640x360 - https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/video-h264-360p.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=X-TxxPv1SZbE2EbcOkt243JCw8cpx6w1o9Km0vy~f1AHIJqydEwMtV58ubuI0cy2e6EgWBIOLkfkGQH~g6CMZm3Hs3QEv7dStlAQL80GiEOEi4Q1pHWp6kkdS2iETiHNTRd4Gj-eTnR70tkToFo-5Z7Q7f1wJFFwN82CG20r~4Jf~YeVJ~v6e3eoPRc34rkrFQ2GeOoI3EXJnkwDO5r5vtoYKsUHHe4w-f65AjBq5ZgxvBfmwy0UdVgGbUhXsx58e~3TvYyg9PbZj-d75~Qurk44hQv7BMaykgMSCr3xuljwiWjGbsuozGYBU7zkYj6y6AutJ4-POnwgHDjcu3nzjw__&Key-Pair-Id=K11RB80NFXU134
480 m3u8_native video-761 - 854x480 - https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/video-h264-480p.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=b5E6--2R8uoPTw2qXqiYyfWA-XOZ7jkCg7KJXxSlpDbpOiVA9SlqGpFWzIP2fXG1rAyW8zNQ3R4wNBq6gkaX6ejsdCwdBMqEF2K2~3ZG1kIiv2F1hqeo4l~iZndq3wBVCwN6StO2ja5ZG1EqMaXwVMgeI2rGsNSOxG~TH3fsikNVi8s~87333OGNetBjYz59VvknoeRZZz2l6Xfrl70x3m5Bla-PpEMmTe5jjLyCxDwwlmse93Us3XdqaHViKWnW9V4gxi7Uztjia7ek9NVPFJJqUfOxmvbmRUXp5J9buGGJ~QREBvsGYDzlMBohj7S-J4IMLuL5ZADKbj02jh34lg__&Key-Pair-Id=K11RB80NFXU134
f_url: https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/video-h264-480p.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=b5E6--2R8uoPTw2qXqiYyfWA-XOZ7jkCg7KJXxSlpDbpOiVA9SlqGpFWzIP2fXG1rAyW8zNQ3R4wNBq6gkaX6ejsdCwdBMqEF2K2~3ZG1kIiv2F1hqeo4l~iZndq3wBVCwN6StO2ja5ZG1EqMaXwVMgeI2rGsNSOxG~TH3fsikNVi8s~87333OGNetBjYz59VvknoeRZZz2l6Xfrl70x3m5Bla-PpEMmTe5jjLyCxDwwlmse93Us3XdqaHViKWnW9V4gxi7Uztjia7ek9NVPFJJqUfOxmvbmRUXp5J9buGGJ~QREBvsGYDzlMBohj7S-J4IMLuL5ZADKbj02jh34lg__&Key-Pair-Id=K11RB80NFXU134
acodec: None
### reset size ###
### reset size ###
use just download: overwrite=False
[ytdl] [hlsnative] Downloading m3u8 manifest
[ytdl] The stream has AES-128 encryption and pycryptodomex is not available; extraction will be delegated to ffmpeg
[ytdl] [download] Destination: \\?\D:\z\hitomi_downloaded_nico\洲崎西 第552回放送（2024.02.20） (so43424304).mp4
[ytdl] [debug] ffmpeg.exe command line: "C:\Users\b_a_k\AppData\Local\Temp\ffmpeg.exe" -y -loglevel verbose -cookies "nicosid=1710336261.1795945555; path=/; domain=.nicovideo.jp; 
domand_bid=eed78f3b837f1bda8f572aba70a714a4cd6d5f015194d5b66c358a9baff4a3ee; path=/; domain=.nicovideo.jp; 
" -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 
Accept-Language: en-us,en;q=0.5 
Sec-Fetch-Mode: navigate 
" -i "https://delivery.domand.nicovideo.jp/hlsbid/65d58bff914400df0183ccd3/playlists/media/video-h264-480p.m3u8?session=e7ee4771a132b4772a4e10e85ee67853aab8de81e61f56ac0000000065f2fa8610e409848061f843&Expires=1710422662&Signature=b5E6--2R8uoPTw2qXqiYyfWA-XOZ7jkCg7KJXxSlpDbpOiVA9SlqGpFWzIP2fXG1rAyW8zNQ3R4wNBq6gkaX6ejsdCwdBMqEF2K2~3ZG1kIiv2F1hqeo4l~iZndq3wBVCwN6StO2ja5ZG1EqMaXwVMgeI2rGsNSOxG~TH3fsikNVi8s~87333OGNetBjYz59VvknoeRZZz2l6Xfrl70x3m5Bla-PpEMmTe5jjLyCxDwwlmse93Us3XdqaHViKWnW9V4gxi7Uztjia7ek9NVPFJJqUfOxmvbmRUXp5J9buGGJ~QREBvsGYDzlMBohj7S-J4IMLuL5ZADKbj02jh34lg__&Key-Pair-Id=K11RB80NFXU134" -c copy -f mpegts "file:\\?\D:\z\hitomi_downloaded_nico\洲崎西 第552回放送（2024.02.20） (so43424304).mp4"
[ytdl] [download] 100% of  172.99MiB in 00:01:56 at 1.48MiB/s
Lazyurl pp Error: \\?\D:\z\hitomi_downloaded_nico\洲崎西 第552回放送（2024.02.20） (so43424304).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 478, in run
 File "hitomi_downloader", line 473, in pp_
 File "C:\Users\b_a_k\AppData\Local\Temp\_MEI197362\ytdl_9949d17b\yt_dlp\yt_dlp\nico_downloader", line 86, in pp
   ffmpeg.merge(filename, self.info['audio_path'], cw=self.cw)
KeyError: 'audio_path'

stop
-show_streams -print_format json -v error "洲崎西 第552回放送（2024.02.20） (so43424304).mp4"
EOT: https://www.nicovideo.jp/watch/so43424304  (122.1s)

이겁니다

니코니코동화에서 洲崎西 라는 라디오 552회부터 전부 이런식으로 안됩니다 ㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
`옵션 - 설정 - YouTube - 파일명 형식` 에서 바꿀 수 있어요

**Comment by son8520** [comment]
> `옵션 - 설정 - YouTube - 파일명 형식` 에서 바꿀 수 있어요

감사합니다!
