### ISSUE TITLE
데이터 다운로드가 계속 실패합니다

### ISSUE THREAD

**Issue by kkkyhg** [KurtBestor/Hitomi-Downloader#7025]
며칠 전부터 이런 문제가 생기네요
해결법을 열심히 검색했지만 원인을 알 수 없었습니다

다운 실패 메세지에 디테일을 보면 아래와 같이 뜹니다

Traceback (most recent call last):
  File "urllib\request", line 1354, in do_open
  File "http\client", line 1252, in request
  File "http\client", line 1298, in _send_request
  File "http\client", line 1247, in endheaders
  File "http\client", line 1007, in _send_output
  File "http\client", line 947, in send
  File "http\client", line 1414, in connect
  File "http\client", line 918, in connect
  File "socket", line 787, in create_connection
  File "socket", line 918, in getaddrinfo
  File "decorator", line 232, in fun
  File "locker", line 123, in _wrapper
  File "locker", line 56, in exec
  File "locker", line 37, in run
  File "locker", line 123, in <lambda>
  File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader", line 431, in read_html
  File "urllib\request", line 525, in open
  File "urllib\request", line 542, in _open
  File "urllib\request", line 502, in _call_chain
  File "urllib\request", line 1397, in https_open
  File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connection", line 159, in _new_conn
  File "urllib3\util\connection", line 61, in create_connection
  File "socket", line 918, in getaddrinfo
  File "decorator", line 232, in fun
  File "locker", line 123, in _wrapper
  File "locker", line 56, in exec
  File "locker", line 37, in run
  File "locker", line 123, in <lambda>
  File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool", line 670, in urlopen
  File "urllib3\connectionpool", line 381, in _make_request
  File "urllib3\connectionpool", line 978, in _validate_conn
  File "urllib3\connection", line 309, in connect
  File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001AF522ECE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters", line 486, in send
  File "urllib3\connectionpool", line 726, in urlopen
  File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='{kurtpy}.com', port=443): Max retries exceeded with url: /h_data (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AF522ECE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 457, in read_html
  File "requests\sessions", line 602, in get
  File "downloader", line 249, in session_request
  File "requests\sessions", line 589, in request
  File "requests\sessions", line 703, in send
  File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='{kurtpy}.com', port=443): Max retries exceeded with url: /h_data (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AF522ECE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by Rainingdayz** [comment]
비슷한 오류를 해결한 적 있습니다.
제 경우는 '설정 - 네트워크 - DIP 우회' 비활성화 후 해결되었습니다.
