### ISSUE TITLE
단부루가 안되네요.

### ISSUE THREAD

**Issue by sb2941** [KurtBestor/Hitomi-Downloader#7034]
Invalid: [danbooru] https://danbooru.donmai.us/posts?tags=siino

version: 4.1+ (24-03-16 08:46:24 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 0c17bfb1d2b84d048bb8ae1af8145b1b
input: https://danbooru.donmai.us/posts?tags=siino
type: danbooru
single: False
url: https://danbooru.donmai.us/posts?tags=siino
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1710803959.1191278 (24-03-18 23:19:19 UTC) - 23s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1080
goodbyedpi: True
ytdl: yt_dlp 2024.03.10
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
https://danbooru.donmai.us/posts?tags=siino&page=1
403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=siino&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1397, in start
 File "utils", line 1481, in start_
 File "extractor\danbooru_downloader", line 65, in read
 File "extractor\danbooru_downloader", line 152, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 954, in try_
 File "constants", line 923, in try_
 File "extractor\danbooru_downloader", line 123, in read_soup
 File "downloader", line 357, in read_soup
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=siino&page=1

Invalid: fail=True
quality: 75%
EOT: https://danbooru.donmai.us/posts?tags=siino  (13.3s)

no html
https://danbooru.donmai.us/posts?tags=siino&page=1
403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=siino&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1397, in start
 File "utils", line 1481, in start_
 File "extractor\danbooru_downloader", line 65, in read
 File "extractor\danbooru_downloader", line 152, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 954, in try_
 File "constants", line 923, in try_
 File "extractor\danbooru_downloader", line 123, in read_soup
 File "downloader", line 357, in read_soup
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=siino&page=1

Invalid: fail=True
quality: 75%
EOT: https://danbooru.donmai.us/posts?tags=siino  (13.2s)

no html
https://danbooru.donmai.us/posts?tags=siino&page=1
403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=siino&page=1
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1397, in start
 File "utils", line 1481, in start_
 File "extractor\danbooru_downloader", line 65, in read
 File "extractor\danbooru_downloader", line 152, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 954, in try_
 File "constants", line 923, in try_
 File "extractor\danbooru_downloader", line 123, in read_soup
 File "downloader", line 357, in read_soup
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=siino&page=1

Invalid: fail=True
quality: 75%
EOT: https://danbooru.donmai.us/posts?tags=siino  (19.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
