### ISSUE TITLE
missav m3u8  다운 차단됨

### ISSUE THREAD

**Issue by Ka9800** [KurtBestor/Hitomi-Downloader#7053]
Invalid: [m3u8] https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 828497b3a20c46c2a9d6671a2999e772
input: https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8
type: m3u8
single: True
url: https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711118633.838835 (24-03-22 14:43:53 UTC) - 14s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
referer: https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8
n_thread: 2
403 Client Error: Forbidden for url: https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\m3u8_downloader", line 37, in read
 File "extractor\m3u8_downloader", line 65, in __init__
 File "extractor\m3u8_downloader", line 60, in __init__
 File "extractor\m3u8_downloader", line 56, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8

Invalid: fail=True
quality: 80%
EOT: https://surrit.com/568fc623-9fe0-4c67-a47a-fa99d36c592a/1280x720/video.m3u8  (0.8s)

**Comment by Ka9800** [comment]
불과 3일전만해도 잘 다운되다가 막혔어요 ㅠ

**Comment by rickmiron** [comment]
plugin:https://github.com/rickmiron/variado/blob/main/missav_downloader.py

**Comment by Ka9800** [comment]
감사합니다
