### ISSUE TITLE
avsogirl 영상 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by kansar21** [KurtBestor/Hitomi-Downloader#7061]
[Messages]
stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (243.6s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (12.9s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (13.8s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (16.3s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (16.1s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (13.7s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (14.2s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (12.8s)

stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막/NHDTB-161-시로사키 리노-자막.mp4' -> 'hitomi_downloaded_sogirl\\NHDTB-161-시로사키 리노-자막.mp4'

EOT: https://kr63.sogirl.so/nhdtb-161-%ec%8b%9c%eb%a1%9c%ec%82%ac%ed%82%a4-%eb%a6%ac%eb%85%b8-%ec%9e%90%eb%a7%89/  (13.0s)

**Comment by rickmiron** [comment]
파일 제한이 2000인가요?
options-->preferences-->advanced-->maximum page limit

**Comment by kansar21** [comment]
파일 제한이 2000으로 설정되어 있어서 제한을 풀었더니 잘 됩니다.
대신에 안 되는 경우가 있습니다.

Invalid: [sogirl] https://kr63.sogirl.so/rbd-756-%ec%b9%b4%ec%99%80%ec%b9%b4%eb%af%b8-%eb%82%98%eb%82%98%eb%af%b8-%ec%9e%90%eb%a7%89/

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 4af3b533649743b5b882e2b84ea82c1d
input: https://kr63.sogirl.so/rbd-756-%ec%b9%b4%ec%99%80%ec%b9%b4%eb%af%b8-%eb%82%98%eb%82%98%eb%af%b8-%ec%9e%90%eb%a7%89/
type: sogirl
single: False
url: https://kr63.sogirl.so/rbd-756-%ec%b9%b4%ec%99%80%ec%b9%b4%eb%af%b8-%eb%82%98%eb%82%98%eb%af%b8-%ec%9e%90%eb%a7%89/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711376894.912181 (24-03-25 14:28:14 UTC) - 45s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
Invalid URL '//a.exosrv.com/iframe.php?idzone=3623681&size=300x100': No scheme supplied. Perhaps you meant https:////a.exosrv.com/iframe.php?idzone=3623681&size=300x100?
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_1", line 46, in read
 File "dynamic_module_1", line 123, in getm3u8
 File "requests\sessions", line 602, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 575, in request
 File "requests\sessions", line 486, in prepare_request
 File "requests\models", line 368, in prepare
 File "requests\models", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '//a.exosrv.com/iframe.php?idzone=3623681&size=300x100': No scheme supplied. Perhaps you meant https:////a.exosrv.com/iframe.php?idzone=3623681&size=300x100?

Invalid: fail=True
EOT: https://kr63.sogirl.so/rbd-756-%ec%b9%b4%ec%99%80%ec%b9%b4%eb%af%b8-%eb%82%98%eb%82%98%eb%af%b8-%ec%9e%90%eb%a7%89/  (4.7s)

Invalid URL '//a.exosrv.com/iframe.php?idzone=3623681&size=300x100': No scheme supplied. Perhaps you meant https:////a.exosrv.com/iframe.php?idzone=3623681&size=300x100?
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_1", line 46, in read
 File "dynamic_module_1", line 123, in getm3u8
 File "requests\sessions", line 602, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 575, in request
 File "requests\sessions", line 486, in prepare_request
 File "requests\models", line 368, in prepare
 File "requests\models", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '//a.exosrv.com/iframe.php?idzone=3623681&size=300x100': No scheme supplied. Perhaps you meant https:////a.exosrv.com/iframe.php?idzone=3623681&size=300x100?

Invalid: fail=True
EOT: https://kr63.sogirl.so/rbd-756-%ec%b9%b4%ec%99%80%ec%b9%b4%eb%af%b8-%eb%82%98%eb%82%98%eb%af%b8-%ec%9e%90%eb%a7%89/  (6.0s)

**Comment by rickmiron** [comment]
이미 수리했어요

**Comment by kansar21** [comment]
감사합니다 잘 동작합니다~

**Comment by avsogirladdress** [comment]
감사합니다! 이 주소들은 작동하고 있으며, AV쏘걸 주소에 더 쉽게 접근하기 위해 [https://avsogirl.net/](https://avsogirl.net/) 를 사용하고 있습니다.
