### ISSUE TITLE
정상 종료 했는데 오류로 파일 로그 불러 올 수가 없습니다.

### ISSUE THREAD

**Issue by MaidRed2** [KurtBestor/Hitomi-Downloader#7066]
![faf](https://github.com/KurtBestor/Hitomi-Downloader/assets/165164444/0c3346bc-087e-4a68-8560-2a8e50d31a35)

무엇이 문제 인지 전혀 이해가 안됨...

**Comment by MaidRed2** [comment]
> ![faf](https://private-user-images.githubusercontent.com/165164444/317261546-0c3346bc-087e-4a68-8560-2a8e50d31a35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDY4NzQsIm5iZiI6MTcxMTU0NjU3NCwicGF0aCI6Ii8xNjUxNjQ0NDQvMzE3MjYxNTQ2LTBjMzM0NmJjLTA4N2UtNGE2OC04NTYwLTJhOGU1MGQzMWEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMzM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDkzNTg4M2VlNDMxNzc2YWViNmE3ZDAxYmYwOWQ2NjQwZTBhZjdiYTczNzEyODIyZmUxNDk1ZDllN2ExNDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XXWWiNd1xFWWZ0gaSt45YCQSQCEXEtZhDO60GgK4KRM)
> 
> 무엇이 문제 인지 전혀 이해가 안됨...

> 실행 후 열리면 기존 작업 파일 자체가 불러 오기가 안됨

**Comment by MaidRed2** [comment]
test 버전 다운로드 후 사용
line 1774 에러 발생

**Comment by MaidRed2** [comment]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 544, in write_config_safe
  File "hitomi_downloader_GUI", line 665, in write_config
  File "hitomi_downloader_GUI", line 859, in _write_config
  File "decorator", line 232, in fun
  File "MyConfigParser", line 22, in w
  File "MyConfigParser", line 129, in set
sqlite3.DatabaseError: database disk image is malformed

test 버전 다운로드 후 사용
line 1774 에러 발생
자동 저장으로 백업 파일 만들어 둔건데 
자동 저장 파일이 이러니..
작업 내보내기에는 문제가 없으나 종료 시 저장이 안됨.
