### ISSUE TITLE
sankaku channel 이미지 실패

### ISSUE THREAD

**Issue by booralking** [KurtBestor/Hitomi-Downloader#7071]
Invalid: [sankaku] https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 29aa71151c0948cf8bdf3c59f3de6bf9
input: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
type: sankaku
single: False
url: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711612816.131787 (24-03-28 08:00:16 UTC) - 7s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI214482\ytdl_df9c10d7\yt_dlp\yt_dlp\sankaku_downloader", line 144, in read
   info = get_imgs(self.url, self.name, cw=self.cw, types=types, session=self.session)
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI214482\ytdl_df9c10d7\yt_dlp\yt_dlp\sankaku_downloader", line 269, in get_imgs
   tags = article.find('img', class_='preview')['data-auto_page'].split() #6718
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko  (1.8s)

types: img, gif, video
https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI214482\ytdl_df9c10d7\yt_dlp\yt_dlp\sankaku_downloader", line 144, in read
   info = get_imgs(self.url, self.name, cw=self.cw, types=types, session=self.session)
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI214482\ytdl_df9c10d7\yt_dlp\yt_dlp\sankaku_downloader", line 269, in get_imgs
   tags = article.find('img', class_='preview')['data-auto_page'].split() #6718
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko  (1.7s)

types: img, gif, video
https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 233, in get_imgs
   html = downloader.read_html(url, referer=url_old, session=session)
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

no images
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 144, in read
   info = get_imgs(self.url, self.name, cw=self.cw, types=types, session=self.session)
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 321, in get_imgs
   raise Exception('no images')
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko  (0.4s)

types: img, gif, video
https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 233, in get_imgs
   html = downloader.read_html(url, referer=url_old, session=session)
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

no images
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 144, in read
   info = get_imgs(self.url, self.name, cw=self.cw, types=types, session=self.session)
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 321, in get_imgs
   raise Exception('no images')
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko  (3.6s)

types: img, gif, video
https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 144, in read
   info = get_imgs(self.url, self.name, cw=self.cw, types=types, session=self.session)
 File "C:\Users\BOORAL~1\AppData\Local\Temp\_MEI228042\ytdl_cc6af62f\yt_dlp\yt_dlp\sankaku_downloader", line 269, in get_imgs
   tags = article.find('img', class_='preview')['data-auto_page'].split() #6718
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/posts?tags=kusanagi_motoko  (1.7s)

**Comment by code-KURO** [comment]
got the same error... tried using the "hitomi_downloader_GUI_test" and still got Invalid result.
