### ISSUE TITLE
AV19 영상 다운로드가 안됩니다..

### ISSUE THREAD

**Issue by GomT745** [KurtBestor/Hitomi-Downloader#7073]
4분 58초 뒤 다시 시작: Invalid: [av19] https://av19.gg/bbs/board.php?bo_table=korea&wr_id=26762

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 3e6d2593c7c747aeb65967c476d4ac9e
input: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=26762
type: av19
single: True
url: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=26762
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711659163.162227 (24-03-28 20:52:43 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/lg/b5c1ad1a04e0746288bb29c10d5a32fd/ming.html
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/lg/b5c1ad1a04e0746288bb29c10d5a32fd/ming.html

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=26762  (1.3s)

**Comment by rickmiron** [comment]
일시적인 오류입니다. 다시 시도해 주세요.

**Comment by GomT745** [comment]
@rickmiron 

오늘 대부분의 영상 확인 결과 과거 일부 영상을 제외한 최신 영상들에서 공통적으로 발생하고 있는 것을 확인하였습니다.
혹시 사용 시 다른 주의사항이 있을까요?

**Comment by rickmiron** [comment]
오류가 있는 동영상의 모든 링크를 표시합니다.
그리고 오류를 확인해보세요

**Comment by GomT745** [comment]
@rickmiron 

4분 58초 뒤 다시 시작: Invalid: [av19] https://av19.gg/bj/13669

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 6d9c650f9f2948d896016a475cdb9b79
input: https://av19.gg/bj/13669
type: av19
single: True
url: https://av19.gg/bj/13669
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765760.9304442 (24-03-30 02:29:20 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/vd2/dcfc93b12e99842509856f8a84f70c5a/ming.html
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/vd2/dcfc93b12e99842509856f8a84f70c5a/ming.html

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/bj/13669  (1.7s)

4분 38초 뒤 다시 시작: Invalid: [av19] https://av19.gg/leak/24146

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / b3a28584d07d4d9e8fb7e42851bd4a6e
input: https://av19.gg/leak/24146
type: av19
single: True
url: https://av19.gg/leak/24146
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765755.3161387 (24-03-30 02:29:15 UTC) - 23s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
403 Client Error: Forbidden for url: https://jp.thisiscdn.life/cupcup8//index.js
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jp.thisiscdn.life/cupcup8//index.js

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/leak/24146  (1.0s)

4분 27초 뒤 다시 시작: Invalid: [av19] https://av19.gg/fc2ppv/22699

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 2 / False / 943a048c19624a5ea892d7391404c8e0
input: https://av19.gg/fc2ppv/22699
type: av19
single: True
url: https://av19.gg/fc2ppv/22699
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765749.583374 (24-03-30 02:29:09 UTC) - 35s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://jp.thisiscdn.life/cupcup8//index.js
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://jp.thisiscdn.life/cupcup8//index.js

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/fc2ppv/22699  (1.4s)

4분 13초 뒤 다시 시작: Invalid: [av19] https://av19.gg/fcppv_jamak/413

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 4 / False / 490e95a1bb7e4893af1223d6421ec97d
input: https://av19.gg/fcppv_jamak/413
type: av19
single: True
url: https://av19.gg/fcppv_jamak/413
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765739.5934906 (24-03-30 02:28:59 UTC) - 50s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top/cupcup8/n6/1114/jm/FC2PPV-3599863-%EC%8B%A0%ED%98%BC%20%ED%98%B8%EC%95%BC%ED%98%B8%EC%95%BC%20%EC%B0%A8%EC%B9%B4%EC%99%80%20%EC%A0%8A%EC%9D%80%20%EC%95%84%EB%82%B4%2024%EC%84%B8%20%EC%9D%BC%EB%B3%B8%20%EC%95%BC%EB%8F%99-%EB%85%B8%EB%AA%A8%EC%9E%90%EB%A7%89.mp4/index.js
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top/cupcup8/n6/1114/jm/FC2PPV-3599863-%EC%8B%A0%ED%98%BC%20%ED%98%B8%EC%95%BC%ED%98%B8%EC%95%BC%20%EC%B0%A8%EC%B9%B4%EC%99%80%20%EC%A0%8A%EC%9D%80%20%EC%95%84%EB%82%B4%2024%EC%84%B8%20%EC%9D%BC%EB%B3%B8%20%EC%95%BC%EB%8F%99-%EB%85%B8%EB%AA%A8%EC%9E%90%EB%A7%89.mp4/index.js

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/fcppv_jamak/413  (1.9s)

4분 3초 뒤 다시 시작: Invalid: [av19] https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29427

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 5 / False / 12b8147434c44149a08353bb5b79cdcd
input: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29427
type: av19
single: True
url: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29427
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765734.7184353 (24-03-30 02:28:54 UTC) - 59s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/vd2/b7c79e4c40ae6dbc01b982335f8c2ba8/ming.html
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/vd2/b7c79e4c40ae6dbc01b982335f8c2ba8/ming.html

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29427  (2.2s)


3분 53초 뒤 다시 시작: Invalid: [av19] https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29430

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 6 / False / 5b545c96aa724b31901d471364b373a3
input: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29430
type: av19
single: True
url: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29430
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765731.6334848 (24-03-30 02:28:51 UTC) - 69s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/vd2/ca337591f7e31a6a700ba346980a78e5/ming.html
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6/vd2/ca337591f7e31a6a700ba346980a78e5/ming.html

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29430  (1.7s)

3분 39초 뒤 다시 시작: Invalid: [av19] https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29366

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 8 / False / e727c7d35f034567adeaaf0e5da304a2
input: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29366
type: av19
single: True
url: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29366
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765723.6895146 (24-03-30 02:28:43 UTC) - 82s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6//vod//lover_66463348579775/16cfe22f03gogo/script.html
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6//vod//lover_66463348579775/16cfe22f03gogo/script.html

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29366  (1.4s)


3분 39초 뒤 다시 시작: Invalid: [av19] https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29451

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 7 / False / b29e29933273409da0e23449b754bef4
input: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29451
type: av19
single: True
url: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29451
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711765728.3405397 (24-03-30 02:28:48 UTC) - 83s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6//vod//lover_69143425584450/27cad2fcd6gogo/script.html
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_8", line 29, in read
 File "dynamic_module_8", line 27, in read
 File "dynamic_module_8", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 520 Server Error:  for url: https://z124fdsf6dsf.onymyway.top//n6//vod//lover_69143425584450/27cad2fcd6gogo/script.html

Invalid: fail=True
quality: 100%
EOT: https://av19.gg/bbs/board.php?bo_table=korea&wr_id=29451  (1.5s)

**Comment by rickmiron** [comment]
한 번에 2개의 비디오를 다운로드했는데 모든 다운로드에 문제가 없었습니다.

**Comment by GomT745** [comment]
@rickmiron 

음... 저는 여전히 안되는 것을 보면 플러그인 이외의 다른 문제가 있는 것으로 보입니다.
답변해주셔서 감사합니다.

제가 찾은 차이점은 다운로드가 불가능한 영상의 경우 재생 시도 시 아래 문구가 노출되며 재생이 불가능하다는 부분뿐이었습니다.

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/123824675/1dc4ac85-d6cd-4987-98c1-de4f96e38c27)

"이 비디오 파일은 재생할 수 없습니다"
[오류코드:232011]

이 부분을 먼저 해결하고 재시도해보겠습니다.

**Comment by rickmiron** [comment]
VPN을 사용해 보세요

**Comment by GomT745** [comment]
@rickmiron 

VPN 사용 시 영상의 재생은 가능하나 다운로드는 불가능합니다.
컴퓨터를 포맷해봤지만 해결되지 않네요. Xb

**Comment by rickmiron** [comment]
Psiphon vpn을 사용해 보세요
