### ISSUE TITLE
Sankaku Issue

### ISSUE THREAD

**Issue by kingdsempai** [KurtBestor/Hitomi-Downloader#7083]
Using the recent technical version, this is the error I get when trying to download:

Invalid: [sankaku] https://chan.sankakucomplex.com/en/posts?tags=panels+order%3Apopular

version: 4.1+ (24-03-26 11:25:36 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / en_us
order / group / uid: 0 / False / 55f6637b6b32402d90e196729bd806d1
input: https://chan.sankakucomplex.com/en/posts?tags=panels+order%3Apopular
type: sankaku
single: False
url: https://chan.sankakucomplex.com/en/posts?tags=panels+order%3Apopular
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1712002266.8595474 (24-04-01 20:11:06 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 4320
goodbyedpi: None
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/en/posts?tags=panels+order%3Apopular
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1396, in start
 File "utils", line 1484, in start_
 File "extractor\sankaku_downloader", line 150, in read
 File "extractor\sankaku_downloader", line 275, in get_imgs
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/posts?tags=panels+order%3Apopular  (0.8s)

**Comment by kingdsempai** [comment]
> Did you find a solution to this? I am having the same issue.

Install this plugin.

https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py
