### ISSUE TITLE
다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by eternalgrow** [KurtBestor/Hitomi-Downloader#7101]
Invalid: [hitomi] https://exhentai.org/g/1404195/9e5e4f115e/

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / c60a0265ae3543728654ee56abcd909f
input: https://exhentai.org/g/1404195/9e5e4f115e/
type: hitomi
single: False
url: https://exhentai.org/g/1404195/9e5e4f115e/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1712473065.1740513 (24-04-07 06:57:45 UTC) - 42s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://e-hentai.org/g/1404195/9e5e4f115e    ---->    https://e-hentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://exhentai.org/g/1404195/9e5e4f115e    ---->    https://exhentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 176, in ehen_imgs
errors.LoginRequired

Read reader FAILED - auto
Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 176, in ehen_imgs
errors.LoginRequired

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://e-hentai.org/g/1404195/9e5e4f115e    ---->    https://e-hentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://exhentai.org/g/1404195/9e5e4f115e    ---->    https://exhentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 176, in ehen_imgs
errors.LoginRequired

Read reader FAILED - auto
Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 176, in ehen_imgs
errors.LoginRequired

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://e-hentai.org/g/1404195/9e5e4f115e    ---->    https://e-hentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://exhentai.org/g/1404195/9e5e4f115e    ---->    https://exhentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 176, in ehen_imgs
errors.LoginRequired

Read reader FAILED - auto
Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 176, in ehen_imgs
errors.LoginRequired

get_imgs server: hitomi
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 617, in get_imgs
 File "hitomi", line 648, in pop_img
 File "dynamic_hitomi_1", line 268, in _pop_img
 File "dynamic_hitomi_1", line 233, in get_data
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ltn.hitomi.la/galleries/1404195.js

get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/1404195/9e5e4f115e/)
using custom cookies
#### https://e-hentai.org/g/1404195/9e5e4f115e    ---->    https://e-hentai.org/g/1404195/9e5e4f115e
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "hitomi_downloader", line 781, in read
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/1404195/9e5e4f115e

Invalid: fail=True
EOT: https://exhentai.org/g/1404195/9e5e4f115e/  (36.8s)

**Comment by rickmiron** [comment]
오류 메시지는 hitomi와 e-hen의 링크가 더 이상 존재하지 않으며 ex-hen을 확인하려면 로그인해야 함을 나타냅니다.
쿠키를 추가하면 작동할 것입니다. 시도해 보고 다운로드할 수 있었습니다.

**Comment by eternalgrow** [comment]
감사합니다 쿠키를 추가하고 다운 받았습니다.

**Comment by eternalgrow** [comment]
> 오류 메시지는 hitomi와 e-hen의 링크가 더 이상 존재하지 않으며 ex-hen을 확인하려면 로그인해야 함을 나타냅니다. 쿠키를 추가하면 작동할 것입니다. 시도해 보고 다운로드할 수 있었습니다.

감사합니다 쿠키를 추가하고 다운 받았습니다.
