### ISSUE TITLE
코믹워커 다운로드 할때마다 화질이 다른 경우

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#7119]
![화면 캡처 2024-04-15 173505](https://github.com/KurtBestor/Hitomi-Downloader/assets/88294291/8dc07db6-3a5d-4b19-9947-6d9496d0e100)

어떤 건 파일이 좀 흐릿하게 다운로드 되고 어떤 건 선명하게 다운로드 됩니다.
픽시브 코믹도 마찬가지로 화질이 다르게 다운로드 되는 경우가 있고요

오른쪽처럼 선명하게 다운로드 돼야 하는 게 맞지 않나 생각하거든요
다운로드 했다가 지웠다가 며칠동안 반복 해보는데 계속 잘 안되네요
이거 어떻게 해야 할까요

**Comment by qj8x67s33a44** [comment]
[URLs]
[0001] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x000002361596A270>
[0002] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x0000023615998D60>
[0003] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x000002361598E860>
[0004] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x0000023615998270>
[0005] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x00000236159AF4F0>
[0006] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x00000236159C6E00>
[0007] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x00000236159C8400>
[0008] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x00000236159AF900>
[0009] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)
[0010] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x00000236159AF5E0>
[0011] File_comicwalker(https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E)    --->    <_io.BytesIO object at 0x00000236159AFE50>
...

Fail : https://cdn.comic-walker.com/images/674/1/1/20240201215540/1/9_e0896097e3b318a70ad25ac51c36f3cbfb3b5bb5df85a0aed49e6a1d79dcb355.webp?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4uY29taWMtd2Fsa2VyLmNvbS9pbWFnZXMvNjc0LzEvMS8yMDI0MDIwMTIxNTU0MC8xLyoud2VicCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzE4Mjk4N319fV19&Signature=N3zEkPlNBkw-veSaivlHwzwCC~xB2e9wC7WBQC4YSkj2MB7p~dlj~YS4upwGunPyHBvRWFRkgqkmquAlZ3UVTk8mnTM1ANA2YXYqBk2lB6EfEXpADRzslHu3b6zn4W0XyhChTc~a2lklcCE1muRuxt-UqqVGowWO0yHZelLeJReZ5SockzxXmw3Bcb3YyMnnKmRfJzJKKG9xu~jqWqn-M9EDrpcKlWYs7hbjNeuas-M6eojWkh8qY5tO8PEdHxuH0XLk-HRsEOXipGnU-vk48ceI5KWomoMAeJHGpso5f-p2Hqn5jnn7D8XlNFp2z-3rjtiyZE42gc4yEqWEMt8FWA__&Key-Pair-Id=K2YXDWASRN7F3E
Traceback (most recent call last):
 File "downloader", line 1222, in download
 File "downloader", line 1215, in Stream
 File "http\client", line 455, in read
 File "http\client", line 499, in readinto
 File "socket", line 669, in readinto
 File "ssl", line 1241, in recv_into
 File "ssl", line 1099, in read
socket.timeout: The read operation timed out


File error (https://comic-walker.com/detail/KC_000674_S/episodes/KC_0006740000100011_E):
Traceback (most recent call last):
 File "hitomi_downloader", line 318, in run
 File "utils", line 4862, in ready
 File "extractor\comicwalker_downloader", line 28, in get
 File "downloader", line 1305, in download
 File "downloader", line 1222, in download
 File "downloader", line 1215, in Stream
 File "http\client", line 455, in read
 File "http\client", line 499, in readinto
 File "socket", line 669, in readinto
 File "ssl", line 1241, in recv_into
 File "ssl", line 1099, in read
socket.timeout: The read operation timed out

stop
EOT: https://comic-walker.com/detail/KC_000674_S  (589.7s)

중간에 다운로드가 몇개씩 안되는 경우
이 경우엔 다시 시작해도 다운로드가 안된 건 다운로드가 안 됩니다.
전체 삭제하고 다시 다운로드 받으면 다운로드 되거나 다운로드가 또 안되거나 합니다.

**Comment by qj8x67s33a44** [comment]
episodeType=comics 이거도 다운로드 가능할까요

https://comic-walker.com/detail/KC_005332_S/episodes/KC_0053320000200011_E?episodeType=first
https://comic-walker.com/detail/KC_005332_S/episodes/KC_0053320000200012_E?episodeType=comics

두 개를 비교하면 제목을 제외하면 
#### - #### - 제목 으로 동일하기에
만약 제목이 동일하고 내용이 다르다면 중복 때문에 다운로드가 안되는 상황이 발생하지 않을 까요

episodeType=first 를
1 - #### - #### - 제목 로

episodeType=comics 를
2 - #### - #### - 제목 형식으로 하면

중복 때문에 다운로드 안되는 상황도 없을 거 같고 순서가 안 섞일 거 같은데
어떻게 생각하시는지
