### ISSUE TITLE
sankaku의 idol 링크 넣으면 chan 파일을 다운로드하는 버그

### ISSUE THREAD

**Issue by testafor** [KurtBestor/Hitomi-Downloader#7129]
현재 technical preview 다운로더로 idol.sankakucomplex.com의 검색결과 링크를 넣으면, 
같은 파라미터를 가진 chan.sankakucomplex.com의 파일들을 다운받습니다. 
폴더는 idol으로 생성됩니다. 
~~개별 게시물 다운로드는 정상적으로 됩니다.~~
개별 게시물도 chan게시물을 다운받네요.
로그 보니 URLs 부분 url 변경 과정에서 iv.가 되어야 할 게 s.로 변경되고 있네요.

[idol] ririsu_amano order：popular

version: 4.1+ (24-04-13 01:21:04 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 658be632af744ae9bed827655de0b348
input: https://idol.sankakucomplex.com/?tags=ririsu_amano+order%3Apopular
type: sankaku
single: False
url: https://idol.sankakucomplex.com/?tags=ririsu_amano+order%3Apopular
dir: hitomi_downloaded_sankaku\[idol] ririsu_amano order：popular
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1713426400.8087726 (24-04-18 07:46:40 UTC) - 279s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
res: 2160
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_sankaku\[idol] ririsu_amano order：popular\WKaoYNOqRJ0.jpg
[0002] hitomi_downloaded_sankaku\[idol] ririsu_amano order：popular\YoMBV8nVMOv.png

[URLs]
[0001] File_sankaku(https://idol.sankakucomplex.com/en/posts/WKaoYNOqRJ0)    --->    https://sankaku.app/en/posts/WKaoYNOqRJ0    --->    https://s.sankakucomplex.com/data/6a/33/6a334f5da5a7046822c92e081220ccf8.jpg?e=1713430007&m=98zi6-E1YoaHqybBwDIHyQ
[0002] File_sankaku(https://idol.sankakucomplex.com/en/posts/YoMBV8nVMOv)    --->    https://sankaku.app/en/posts/YoMBV8nVMOv    --->    https://s.sankakucomplex.com/data/33/fc/33fcbcb73747416c372aa101196de5c3.png?e=1713430012&m=wOW29I1vpxYGG2fO_RSpuQ

[Messages]
types: img, gif, video
https://idol.sankakucomplex.com/?tags=ririsu_amano+order%3Apopular
Traceback (most recent call last):
 File "extractor\sankaku_downloader", line 296, in get_imgs
 File "bs4\element", line 1573, in __getitem__
KeyError: 'next-page-url'

stop
EOT: https://idol.sankakucomplex.com/?tags=ririsu_amano+order%3Apopular  (13.9s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by testafor** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

테스트 좀 해봤는데 정상 작동하는 듯 합니다. 다른 버그를 발견했는데 중복 확인해보고 따로 이슈 올리겠습니다.
