### ISSUE TITLE
치지직 녹화가 정상적으로 진행되지않습니다

### ISSUE THREAD

**Issue by honsea2** [KurtBestor/Hitomi-Downloader#7138]
안녕하세요 개발자님 
어제부터 치지직 녹화가 정상적으로 진행되지않는 버그가 발생하였습니다
프로그램상에는 녹화가 진행되는데도 불구하고 녹화가 끊났음에도 해당 작업물의 동영상이 재생되지않는 버그가 발생하였습니다

이에 버그관련 내용을 첨부합니다
문의를 읽어주셔서 감사합니다

[은 또] 2024-04-26 06:23 에키드나 너 왜그러는데 대체

version: 4.1+ (24-04-13 01:21:04 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 8485e59e3f734a82b23f2ac53ccc800f
input: https://chzzk.naver.com/live/2ecd98310383bdd93fb5aa8e8151dee0
type: chzzk
single: True
url: https://chzzk.naver.com/live/2ecd98310383bdd93fb5aa8e8151dee0
dir: hitomi_downloaded_chzzk
zip: 
artist: 은 또
valid / done: True / True
range / range_p: None / None
time: 1714080180.8861775 (24-04-25 21:23:00 UTC) - 42s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1440
goodbyedpi: False
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {seg_err: 0, seg_all: 9}
live: True
changed: True

[File Names]
[0001] hitomi_downloaded_chzzk\[은 또] 2024-04-26 06：23 에키드나 너 왜그러는데 대체.mp4

[URLs]
[0001] Video(https://chzzk.naver.com/live/2ecd98310383bdd93fb5aa8e8151dee0)    --->    M3u8_stream(https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/hls_chunklist_1080p.m3u8?hdnts=st%3D1714078887~exp%3D1714109497~acl%3D%2A%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F%2A~hmac%3D802b2d9b703671513f36c08eedbe55745974caf4cf3d36b3d86b936aabe63b82)

[Messages]
status: OPEN
media: 0
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_760655678_1714080174616_26248_0_13125.m4v?type=hls&bitrate=983340&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_1190131715_1714080176616_26250_0_13126.m4v?type=hls&bitrate=1012615&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_3267763358_1714080178616_26252_0_13127.m4v?type=hls&bitrate=1049386&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_2593578779_1714080184616_26258_0_13130.m4v?type=hls&bitrate=1010871&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_489173916_1714080186616_26260_0_13131.m4v?type=hls&bitrate=1010328&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_2275277793_1714080188616_26262_0_13132.m4v?type=hls&bitrate=1053505&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_1425009061_1714080194616_26268_0_13135.m4v?type=hls&bitrate=1010672&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_2361046703_1714080196616_26270_0_13136.m4v?type=hls&bitrate=1022286&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_2745366123_1714080198616_26272_0_13137.m4v?type=hls&bitrate=999544&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0015/tcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2/hdntl=exp=1714109497~acl=*%2Ftcjdaifkiw25crc6kjb9rp8d6gs7k5r6b2%2F*~data=hdntl~hmac=fdfd9aa7e740ae4fee2117e1e8fae4997385dd5247e48a2c95bb2071d27316d7/1080p_3852796459_1714080206616_26280_0_13141.m4v?type=hls&bitrate=1022396&filetype=.m4v' for reading
Err: 0 / 9  (0.00%)
stop
quality: 100%
-show_streams -print_format json -v error "[은 또] 2024-04-26 06：23 에키드나 너 왜그러는데 대체.mp4"
{

}
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000022a76a2fa00] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000022a76a2fa00] error reading header
[은 또] 2024-04-26 06：23 에키드나 너 왜그러는데 대체.mp4: Invalid data found when processing input
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2021, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://chzzk.naver.com/live/2ecd98310383bdd93fb5aa8e8151dee0  (37.8s)

**Comment by mita5549** [comment]
저도 동 증상을 겪고 있습니다...
일단 영상 저장은 하고 있는데, 어떻게 해야 할까요...?

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/7137

**Comment by honsea2** [comment]
> Duplicate of #7137

작동 잘됩니다 버그를 해결해주셔서 감사합니다
