### ISSUE TITLE
저도 틱톡 다운이 되지 않습니다.

### ISSUE THREAD

**Issue by Request234** [KurtBestor/Hitomi-Downloader#7146]
Invalid: [tiktok] https://www.tiktok.com/@yadongyyyy

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 86 / False / 87168c272ccf485f8c6a548429dc2b47
input: https://www.tiktok.com/@yadongyyyy
type: tiktok
single: True
url: https://www.tiktok.com/@yadongyyyy
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1714410112.8153286 (24-04-29 17:01:52 UTC) - 31s elapsed
tags: ['red']
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.03.20.232704 from yt-dlp/yt-dlp-nightly-builds [07f5b2f75] (pip) API
[ytdl] [debug] params: {'extract_flat': True, 'playlistend': 1000000000, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001E6D7F1A700>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.5.2 Chrome/108.0.5359.220 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Lazy loading extractors is disabled
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1806 extractors
[ytdl] The program functionality for this site has been marked as broken, and will probably not work.
[ytdl] [tiktok:user] Extracting URL: https://www.tiktok.com/@yadongyyyy
[ytdl] [tiktok:user] yadongyyyy: Downloading webpage
ERROR: [tiktok:user] yadongyyyy: Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1421, in connect
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\common", line 864, in _request_webpage
 File "ytdl", line 487, in urlopen
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\YoutubeDL", line 4128, in urlopen
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\networking\common", line 115, in send
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\networking\_helper", line 204, in wrapper
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\networking\common", line 335, in send
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\networking\_urllib", line 410, in _send
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\networking\_urllib", line 328, in handle_response_read_exceptions
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\networking\_urllib", line 320, in handle_sslerror
yt_dlp.networking.exceptions.CertificateVerifyError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\YoutubeDL", line 1605, in wrapper
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\YoutubeDL", line 1740, in __extract_info
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\common", line 732, in extract
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\tiktok", line 827, in _real_extract
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\common", line 1135, in _download_webpage
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\common", line 1086, in download_content
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\common", line 920, in _download_webpage_handle
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\extractor\common", line 877, in _request_webpage
yt_dlp.utils.ExtractorError: [tiktok:user] yadongyyyy: Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_1", line 69, in read
 File "dynamic_module_1", line 136, in read_channel
 File "ytdl", line 497, in extract_info
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\YoutubeDL", line 1594, in extract_info
 File "C:\Users\master\AppData\Local\Temp\_MEI256882\ytdl_909d8cba\yt_dlp\yt_dlp\YoutubeDL", line 1623, in wrapper
 File "ytdl", line 425, in report_error
yt_dlp.utils.DownloadError: ERROR: [tiktok:user] yadongyyyy: Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://www.tiktok.com/@yadongyyyy  (4.9s)

[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.03.20.232704 from yt-dlp/yt-dlp-nightly-builds [07f5b2f75] (pip) API
[ytdl] [debug] params: {'extract_flat': True, 'playlistend': 1000000000, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001C99C19A7C0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.5.2 Chrome/108.0.5359.220 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Lazy loading extractors is disabled
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1806 extractors
[ytdl] The program functionality for this site has been marked as broken, and will probably not work.
[ytdl] [tiktok:user] Extracting URL: https://www.tiktok.com/@yadongyyyy
[ytdl] [tiktok:user] yadongyyyy: Downloading webpage
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
[ytdl] [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[ytdl] [tiktok:user] yadongyyyy: Downloading user video list page 1
ERROR: [tiktok:user] yadongyyyy: yadongyyyy: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\_utils", line 553, in decode
   return super().decode(s)
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 1030, in _parse_json
   return json.loads(
 File "json\__init__", line 370, in loads
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\_utils", line 561, in decode
   raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\YoutubeDL", line 1605, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\YoutubeDL", line 1740, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 732, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\tiktok", line 833, in _real_extract
   thumbnail = traverse_obj(videos, (0, 'author', 'avatar_larger', 'url_list', 0))
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\traversal", line 261, in traverse_obj
   result = _traverse_obj(obj, path, index == len(paths), True)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\traversal", line 249, in _traverse_obj
   results, has_branched, is_dict = apply_path(obj, path, test_type)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\traversal", line 237, in apply_path
   branching, results = apply_key(key, obj, last)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\traversal", line 175, in apply_key
   result = obj[key]
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\_utils", line 2198, in __getitem__
   self._cache.extend(itertools.islice(self._iterable, n))
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\tiktok", line 801, in _video_entries_api
   for retry in self.RetryManager():
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\_utils", line 5057, in __iter__
   self.error_callback(self.error, self.attempt, self.retries)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 3821, in _error_or_warning
   RetryManager.report_retry(
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\utils\_utils", line 5065, in report_retry
   raise e
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\tiktok", line 803, in _video_entries_api
   post_list = self._call_api(
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\tiktok", line 137, in _call_api
   raise e
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\tiktok", line 130, in _call_api
   res = self._call_api_impl(ep, real_query, manifest_app_version, video_id, fatal, note, errnote)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\tiktok", line 67, in _call_api_impl
   return self._download_json(
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 1086, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 1056, in download_handle
   return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 1046, in parse
   return getattr(ie, parser)(content, *args, **kwargs)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 1033, in _parse_json
   self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\extractor\common", line 1016, in __print_error
   raise ExtractorError(f'{video_id}: {errnote}', cause=err)
yt_dlp.utils.ExtractorError: [tiktok:user] yadongyyyy: yadongyyyy: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\tiktok_downloader", line 69, in read
 File "extractor\tiktok_downloader", line 136, in read_channel
 File "ytdl", line 497, in extract_info
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\YoutubeDL", line 1594, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\master\AppData\Local\Temp\_MEI212522\ytdl_fa7c8844\yt_dlp\yt_dlp\YoutubeDL", line 1623, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 425, in report_error
yt_dlp.utils.DownloadError: ERROR: [tiktok:user] yadongyyyy: yadongyyyy: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://www.tiktok.com/@yadongyyyy  (25.0s)

**Comment by mita5549** [comment]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/45882353/da77d94a-9832-4237-9f3c-58b5503159cb)

이 버전에서 정상 다운 확인했습니다. 쿠키나 스크립트 적용 없이 영상 하나만 고르고 해봤는데 잘 되네요.

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/45882353/a99dd6a4-e8d5-4886-a6c0-97be75f64950)

**Comment by Request234** [comment]
아 그렇군요 개별 다운해보겠습니다.
