### ISSUE TITLE
뉴토끼 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by pink0258** [KurtBestor/Hitomi-Downloader#7174]
2분 3초 뒤 다시 시작: Invalid: [manatoki] https://newtoki337.com/webtoon/33293465/%EB%82%98%EB%8A%94-%EC%82%AC%EC%9D%B4%EB%B9%84-%EA%B5%90%EC%A3%BC%EB%8B%A4

version: 4.1+ (24-04-26 23:09:49 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 2 / False / 99adb7435b40407b9748137b7addc054
input: https://newtoki337.com/webtoon/33293465/%EB%82%98%EB%8A%94-%EC%82%AC%EC%9D%B4%EB%B9%84-%EA%B5%90%EC%A3%BC%EB%8B%A4
type: manatoki
single: False
url: https://newtoki337.com/webtoon/33293465/나는-사이비-교주다
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1715498028.3389888 (24-05-12 07:13:48 UTC) - 221s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "C:\Users\Spi\AppData\Local\Temp\_MEI180242\ytdl_7aee1ac1\yt_dlp\yt_dlp\manatoki_downloader", line 85, in init
   self.name
 File "utils", line 666, in __get__
 File "C:\Users\Spi\AppData\Local\Temp\_MEI180242\ytdl_7aee1ac1\yt_dlp\yt_dlp\manatoki_downloader", line 101, in name
   artist = get_artist(self.soup)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI180242\ytdl_7aee1ac1\yt_dlp\yt_dlp\manatoki_downloader", line 119, in get_artist
   view = soup.find('div', class_='view-title', err='no title')
 File "utils", line 2747, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://newtoki337.com/webtoon/33293465/%EB%82%98%EB%8A%94-%EC%82%AC%EC%9D%B4%EB%B9%84-%EA%B5%90%EC%A3%BC%EB%8B%A4  (34.3s)

no title
stop
Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "C:\Users\Spi\AppData\Local\Temp\_MEI180242\ytdl_7aee1ac1\yt_dlp\yt_dlp\manatoki_downloader", line 85, in init
   self.name
 File "utils", line 666, in __get__
 File "C:\Users\Spi\AppData\Local\Temp\_MEI180242\ytdl_7aee1ac1\yt_dlp\yt_dlp\manatoki_downloader", line 101, in name
   artist = get_artist(self.soup)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI180242\ytdl_7aee1ac1\yt_dlp\yt_dlp\manatoki_downloader", line 119, in get_artist
   view = soup.find('div', class_='view-title', err='no title')
 File "utils", line 2747, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://newtoki337.com/webtoon/33293465/%EB%82%98%EB%8A%94-%EC%82%AC%EC%9D%B4%EB%B9%84-%EA%B5%90%EC%A3%BC%EB%8B%A4  (43.6s)

**Comment by gointo7** [comment]
aaa
