### ISSUE TITLE
pornhub 다운로드가 되질 않습니다

### ISSUE THREAD

**Issue by Horung** [KurtBestor/Hitomi-Downloader#7178]
Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 128 / False / d57139b0b8924d89acae95bf242f2075
input: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1715558990.6614602 (24-05-13 00:09:50 UTC) - 273s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
id: ph62238e96e50e3
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
Video
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip) API
[ytdl] [debug] params: {'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000021E53597FA0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.5.2 Chrome/108.0.5359.220 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1810 extractors
[ytdl] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
[ytdl] [PornHub] ph62238e96e50e3: Downloading pc webpage
id: ph62238e96e50e3
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000021E676193D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E676193D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\pornhub_downloader", line 90, in get
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E676193D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

id: ph62238e96e50e3
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000021E6764FE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6764FE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\pornhub_downloader", line 90, in get
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6764FE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

id: ph62238e96e50e3
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000021E6765E430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6765E430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\pornhub_downloader", line 90, in get
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6765E430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

HTTPSConnectionPool(host='www.pornhubpremium.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6766A040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000021E6765E430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6765E430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\pornhub_downloader", line 90, in get
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6765E430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 61, in create_connection
 File "socket", line 918, in getaddrinfo
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 93, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000021E6766A040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhubpremium.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6766A040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\pornhub_downloader", line 283, in read
 File "utils", line 879, in __call__
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\pornhub_downloader", line 99, in get
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhubpremium.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=ph62238e96e50e3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E6766A040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Invalid: fail=True
quality: 100%
EOT: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3  (41.1s)

id: ph62238e96e50e3
Video
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip) API
[ytdl] [debug] params: {'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000021E3263C160>, 'user_agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; es-es) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1810 extractors
[ytdl] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
[ytdl] [PornHub] ph62238e96e50e3: Downloading pc webpage
id: ph62238e96e50e3
Video
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip) API
[ytdl] [debug] params: {'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000021E7C776310>, 'user_agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; es-es) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1810 extractors
[ytdl] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
[ytdl] [PornHub] ph62238e96e50e3: Downloading pc webpage
id: ph62238e96e50e3
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
Video
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip) API
[ytdl] [debug] params: {'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000021E985737C0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.5.2 Chrome/108.0.5359.220 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1810 extractors
[ytdl] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
[ytdl] [PornHub] ph62238e96e50e3: Downloading pc webpage
id: ph62238e96e50e3
Video
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (pip) API
[ytdl] [debug] params: {'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000021E8D659EE0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.5.2 Chrome/108.0.5359.220 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1810 extractors
[ytdl] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3
[ytdl] [PornHub] ph62238e96e50e3: Downloading pc webpage
ERROR: [PornHub] ph62238e96e50e3: PhantomJS not found, Please download it from https://phantomjs.org/download.html
stop
Traceback (most recent call last):
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\YoutubeDL", line 1606, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\YoutubeDL", line 1741, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\common", line 734, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\pornhub", line 285, in _real_extract
   webpage = dl_webpage('pc')
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\pornhub", line 281, in dl_webpage
   return self._download_webpage(
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\common", line 1176, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\common", line 1127, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\pornhub", line 53, in _download_webpage_handle
   phantom = PhantomJSwrapper(self, required_version='2.0')
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\extractor\openload", line 115, in __init__
   raise ExtractorError(f'PhantomJS not found, {self.INSTALL_HINT}', expected=True)
yt_dlp.utils.ExtractorError: [PornHub] ph62238e96e50e3: PhantomJS not found, Please download it from https://phantomjs.org/download.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\pornhub_downloader", line 283, in read
 File "utils", line 879, in __call__
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\pornhub_downloader", line 142, in get
 File "ytdl", line 497, in extract_info
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\YoutubeDL", line 1595, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\houng\AppData\Local\Temp\_MEI196362\ytdl_e79d4ed0\yt_dlp\yt_dlp\YoutubeDL", line 1624, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 425, in report_error
yt_dlp.utils.DownloadError: ERROR: [PornHub] ph62238e96e50e3: PhantomJS not found, Please download it from https://phantomjs.org/download.html

Invalid: fail=True
quality: 100%
EOT: https://www.pornhub.com/view_video.php?viewkey=ph62238e96e50e3  (19.7s)

아예 안되지는 않고 다시시작 5트하면 1트정도는 성공하긴 합니다

**Comment by Horung** [comment]
3.8f로 다운그레이드하니 잘 됩니다 왜그런지는 모르겠습니다
