### ISSUE TITLE
저장시 오류

### ISSUE THREAD

**Issue by ljryul** [KurtBestor/Hitomi-Downloader#7189]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/56251421/e0c171bc-0ccf-4b84-a665-5ac7403c518c)

저장 시 아래와 같은 오류가 발생합니다.
프로그램 종료 후 재시작해도 동일한 증상이 발생하며, 마지막으로 저장된 작업 목록이 다시 생성되어 다운로드 됩니다.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 544, in write_config_safe
  File "hitomi_downloader_GUI", line 664, in write_config
  File "hitomi_downloader_GUI", line 685, in _write_config
  File "decorator", line 232, in fun
  File "MyConfigParser", line 40, in w
  File "MyConfigParser", line 22, in w
  File "MyConfigParser", line 129, in set
sqlite3.OperationalError: database is locked

**Comment by ljryul** [comment]
재부팅 후 정상화 됐습니다.
