### ISSUE TITLE
Kemono isn't working anymore

### ISSUE THREAD

**Issue by NagsWH** [KurtBestor/Hitomi-Downloader#7208]
I can't download any page and everytime Im trying to scrap a page this is what I get 

![Capture d'écran 2024-05-21 170436](https://github.com/KurtBestor/Hitomi-Downloader/assets/99557404/df93fd25-4743-4685-ae61-6295f5870380)

Restart in 4m 57s: Invalid: [kemono.party] https://kemono.su/fanbox/user/16447165/post/7539442

version: 4.1+ (24-04-10 01:21:10 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / fr_fr
order / group / uid: 0 / False / b956956a9d734eedbc0a4617fc226741
input: https://kemono.su/fanbox/user/16447165/post/7539442
type: kemono.party
single: False
url: https://kemono.su/fanbox/user/16447165/post/7539442
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1716304090.7828994 (24-05-21 15:08:10 UTC) - 50s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 1080
goodbyedpi: None
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
HTTPSConnectionPool(host='kemono.su', port=443): Max retries exceeded with url: /fanbox/user/16447165/post/7539442 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000222A15AD490>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1414, in connect
 File "http\client", line 918, in connect
 File "socket", line 808, in create_connection
 File "socket", line 796, in create_connection
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 428, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000222A15AD490>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kemono.su', port=443): Max retries exceeded with url: /fanbox/user/16447165/post/7539442 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000222A15AD490>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "Kemono.Su (8)", line 20, in read
 File "Kemono.Su (8)", line 58, in read_post
 File "downloader", line 454, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 246, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kemono.su', port=443): Max retries exceeded with url: /fanbox/user/16447165/post/7539442 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000222A15AD490>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

Invalid: fail=True
EOT: https://kemono.su/fanbox/user/16447165/post/7539442  (46.4s)

**Comment by fade-out-0770** [comment]
it worked  try again

![스크린샷 2024-05-30 225814](https://github.com/KurtBestor/Hitomi-Downloader/assets/74918094/761ed63f-ea23-4f72-aaca-573674297e7a)

**Comment by NagsWH** [comment]
nope 
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/99557404/7e6cbc95-ea30-4334-b034-92f22fad0ffb)

**Comment by dox987** [comment]
looks likr ur using extension right?
site domain has been changed from kemono.party to kemono.su 
so you have to edit extension file to kemono.su

**Comment by dox987** [comment]
try this
https://github.com/rickmiron/variado/blob/main/kemonosu_downloader.py

**Comment by NagsWH** [comment]
I've installed it but it keep not working ![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/99557404/af9222a1-6eb3-4e9b-9bdb-9c6122b9ab58)

**Comment by NagsWH** [comment]
Restart in 2m 10s: Invalid: [kemono.party] https://kemono.su/patreon/user/2729118

version: 4.1+ (24-04-10 01:21:10 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / fr_fr
order / group / uid: 0 / False / b3c1dba24d124cf4ba6ca1f8e0fd620f
input: https://kemono.su/patreon/user/2729118
type: kemono.party
single: False
url: https://kemono.su/patreon/user/2729118
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1717162347.91021 (24-05-31 13:32:27 UTC) - 217s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 1080
goodbyedpi: None
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
HTTPSConnectionPool(host='kemono.su', port=443): Max retries exceeded with url: /patreon/user/2729118 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002548A1E3DC0>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))
stop
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1414, in connect
 File "http\client", line 918, in connect
 File "socket", line 808, in create_connection
 File "socket", line 796, in create_connection
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 428, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connection", line 159, in _new_conn
 File "urllib3\util\connection", line 84, in create_connection
 File "urllib3\util\connection", line 74, in create_connection
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 309, in connect
 File "urllib3\connection", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002548A1E3DC0>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kemono.su', port=443): Max retries exceeded with url: /patreon/user/2729118 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002548A1E3DC0>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "Kemono.Su (3)", line 24, in read
 File "Kemono.Su (3)", line 28, in read_user
 File "downloader", line 454, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 246, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kemono.su', port=443): Max retries exceeded with url: /patreon/user/2729118 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002548A1E3DC0>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))

Invalid: fail=True
EOT: https://kemono.su/patreon/user/2729118  (46.3s)

**Comment by rickmiron** [comment]
The message it shows indicates that the url cannot connect to the page, try using a proxy, in Options-->preferences-->network

**Comment by NagsWH** [comment]
Thanks , do you have some proxy to try aswell ?

**Comment by NagsWH** [comment]
Nvm I've found some 
Thanks for you help
