### ISSUE TITLE
 Problem downloading from Gelbooru

### ISSUE THREAD

**Issue by jack652** [KurtBestor/Hitomi-Downloader#7211]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/48365199/20fb9618-435f-4095-a03d-d3a1cd487548)

```
Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=view&id=9961983&tags=nicole_demara+-rating%3Ageneral+-rating%3Asafe+-rating%3Aquestionable+-rating%3Aexplicit

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / en_us
order / group / uid: 2 / False / 6f892f98d73346eea972da98e32ccc57
input: https://gelbooru.com/index.php?page=post&s=view&id=9961983&tags=nicole_demara+-rating%3Ageneral+-rating%3Asafe+-rating%3Aquestionable+-rating%3Aexplicit
type: gelbooru
single: False
url: https://gelbooru.com/index.php?page=post&s=view&id=9961983&tags=nicole_demara+-rating%3Ageneral+-rating%3Asafe+-rating%3Aquestionable+-rating%3Aexplicit
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1716389283.7647452 (24-05-22 14:48:03 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
Not Implemented
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\gelbooru_downloader", line 59, in read
 File "extractor\gelbooru_downloader", line 101, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=view&id=9961983&tags=nicole_demara+-rating%3Ageneral+-rating%3Asafe+-rating%3Aquestionable+-rating%3Aexplicit  (0.1s)

Not Implemented
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\gelbooru_downloader", line 59, in read
 File "extractor\gelbooru_downloader", line 101, in get_imgs
NotImplementedError: Not Implemented

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=view&id=9961983&tags=nicole_demara+-rating%3Ageneral+-rating%3Asafe+-rating%3Aquestionable+-rating%3Aexplicit  (0.0s)

```

**Comment by jack652** [comment]
still happens
