### ISSUE TITLE
pixiv 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by fjscl4869** [KurtBestor/Hitomi-Downloader#7214]
Invalid: [pixiv] https://www.pixiv.net/users/6731088

version: 4.1+ (24-05-19 16:03:44 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 6f7f94e947a6492ea381e17f6eaba66a
input: https://www.pixiv.net/users/6731088
type: pixiv
single: False
url: https://www.pixiv.net/users/6731088
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1716624071.4017289 (24-05-25 08:01:11 UTC) - 86s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
sid: 10456839_8UTBiS643u4lB2LCI9sxi4xdsunNFH8l
types: ['illusts', 'manga'], tag: None
403 Client Error
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\pixiv_downloader", line 109, in read
 File "extractor\pixiv_downloader", line 470, in get_info
 File "extractor\pixiv_downloader", line 519, in process_user
 File "extractor\pixiv_downloader", line 181, in top
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "decorator", line 232, in fun
 File "utils", line 5070, in _wrapper
 File "extractor\pixiv_downloader", line 162, in call
extractor.pixiv_downloader.HTTPError: 403 Client Error

Invalid: fail=True
EOT: https://www.pixiv.net/users/6731088  (39.1s)

**Comment by Asylum0** [comment]
저도 방금까지 똑같았습니다.
403 클라이언트 에러라길레 기다리면 되겠지 하고 재시도간격을 30분으로 맞춰놓고 그냥 기다렸습니다.
지금은 잘 받아집니다.

**Comment by fjscl4869** [comment]
어제부터 안됬었는데 지금은 또 되는거보니 픽시브 서버 문제인거 같아요
