### ISSUE TITLE
X (Twitter) login using login feature or cookies not working / Calling cookie in Settings > Network freezes downloader

### ISSUE THREAD

**Issue by QuadrupleRainbow** [KurtBestor/Hitomi-Downloader#7224]
Hello.

**1.** Today I've tried to download from twitter, but the Hitomi downloader told me "Login required".

I've tried logging in by pressing the blue key icon in the Hitomi downloader and successfully logged in, but the downloading failed.

I've tried logging out from twitter on Chrome, logging back in, saving the x.com cookies using the "Get cookies.txt LOCALLY" Chrome extension, and updating the cookies in the Network tab in the Settings in Hitomi downloader. This also failed.

I've moved the Hitomi downloader to an external hard drive, connected the drive to another PC and retried the above two tasks. This also failed.

I've tried downloading the 4.1 version of Hitomi downloader from the internet, installing it new on the second PC, uploaded the x.com cookies through the Network tab, and tried downloading. This also failed. 
(More precisely, I downloaded the 4.1 version again from https://www.videohelp.com/software/Hitomi-Downloader because for some reason the download from Github kept giving me a timeout despite multiple trials)

**2.** Another interesting and perhaps more important symptom is that clicking on the "불러오기" (call) button in the Settings > Network tab freezes the Hitomi downloader for several minutes before it finally responds and allows me to upload the cookies.

These issues may have something to do with a recent Windows update, but I am not sure if this is the cause.

Thanks for your hard work. 

Attached below is the error message from the failed twitter.com download.
──────────────────────────────────────────────────────────
Login required; Please login: 404 Not Found
https://twitter.com/uni_lattes2

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19044-SP0 / ko_kr
order / group / uid: 0 / False / 51f7010eb4834e928544db4fd63dfb66
input: https://twitter.com/uni_lattes2
type: twitter
single: False
url: https://twitter.com/uni_lattes2
dir: 
zip: 
artist: ラテちゃん / LatteS2
valid / done: False / True
range / range_p: None / None
time: 1717081475.090284 (24-05-30 15:04:35 UTC) - 10s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: None None
pinned: False
extras: {uids: ['1786720410106761216']}
live: False
changed: True

[File Names]

[URLs]

[Messages]
format: None
type: user
!!! get guest_token
token type: <class 'str'>
generate csrf
uid: 1786720410106761216
multiple tweets rt:False
mc: 28
call... UserMedia
404 Not Found
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\twitter_downloader", line 152, in read
 File "extractor\twitter_downloader", line 778, in get_imgs
 File "utils", line 4008, in check_alive_iter
 File "extractor\twitter_downloader", line 502, in _pagination_tweets
 File "decorator", line 232, in fun
 File "utils", line 5007, in _wrapper
 File "extractor\twitter_downloader", line 320, in _call
extractor.twitter_downloader.LoginRequired: 404 Not Found

Invalid: fail=False
EOT: https://twitter.com/uni_lattes2  (6.4s)

**Comment by QuadrupleRainbow** [comment]
Never mind, found that the issue is a 
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/7194

Replace "x.com" in the cookies.txt file with "twitter.com" and it works
