### ISSUE TITLE
why did i can‘t download twitter media？

### ISSUE THREAD

**Issue by 1314520app** [KurtBestor/Hitomi-Downloader#7236]
replace cookies， it doesn“t work。

今天跟我接吻了吗 (@gao_gn)

version: 4.0 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / zh_cn
order / group / uid: 345 / False / abf5b9e5b8f34c0382fdc9df1dfd51c1
input: https://twitter.com/gao_gn
type: twitter
single: False
url: https://twitter.com/gao_gn
dir: hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)
zip: 
artist: 今天跟我接吻了吗
valid / done: False / True
range / range_p: None / None
time: 1716567305.2500463 (24-05-24 16:15:05 UTC) - 794777s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {uids: ['1538175953473417216']}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-24] 1794012520992346496_p0.jpg
[0002] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-24] 1794002526276395120_p0.jpg
[0003] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-24] 1793697060094390739_p0.jpg
[0004] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-24] 1793688523985604700_p0.jpg
[0005] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-23] 1793483959311171748_p0.mp4
[0006] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-22] 1792997025799168434_p0.jpg
[0007] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-21] 1792771031326920963_p0.jpg
[0008] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-20] 1792254578311987567_p0.jpg
[0009] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-19] 1792057374737613021_p0.jpg
[0010] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-19] 1792057374737613021_p1.jpg
[0011] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-18] 1791855191438070160_p0.jpg
[0012] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-18] 1791517309582119033_p0.jpg
[0013] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-17] 1791372947128713538_p0.jpg
[0014] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-17] 1791177029511250223_p0.jpg
[0015] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-15] 1790767592761856034_p0.jpg
[0016] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-15] 1790675916693344537_p0.jpg
[0017] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[24-05-14] 1790398526276653513_p0.mp4
....
[0340] hitomi_downloaded_twitter\今天跟我接吻了吗 (@gao_gn)\[22-07-20] 1549469993644855296_p0.jpg

[URLs]

[Messages]
format: None
type: user
HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/api/graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22gao_gn%22%2C%22withHighlightedLabel%22%3Atrue%7D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/api/graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22gao_gn%22%2C%22withHighlightedLabel%22%3Atrue%7D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\twitter_downloader", line 116, in read
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\twitter_downloader", line 1059, in get_artist_username
 File "extractor\twitter_downloader", line 1054, in get_artist_username
 File "extractor\twitter_downloader", line 394, in user_by_screen_name
 File "decorator", line 232, in fun
 File "utils", line 5007, in _wrapper
 File "extractor\twitter_downloader", line 292, in _call
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/api/graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22gao_gn%22%2C%22withHighlightedLabel%22%3Atrue%7D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

Invalid: fail=True
invalid; revert
EOT: https://twitter.com/gao_gn  (84.7s)

format: None
type: user
('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\15825\AppData\Local\Temp\_MEI91282\ytdl_6fa23e0e\yt_dlp\yt_dlp\twitter_downloader", line 119, in read
   self.artist, self.username = get_artist_username(self.url, self.session, self.cw)
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "C:\Users\15825\AppData\Local\Temp\_MEI91282\ytdl_6fa23e0e\yt_dlp\yt_dlp\twitter_downloader", line 1123, in get_artist_username
   raise e
 File "C:\Users\15825\AppData\Local\Temp\_MEI91282\ytdl_6fa23e0e\yt_dlp\yt_dlp\twitter_downloader", line 1118, in get_artist_username
   data = TwitterAPI(session, cw).user_by_screen_name(username)
 File "C:\Users\15825\AppData\Local\Temp\_MEI91282\ytdl_6fa23e0e\yt_dlp\yt_dlp\twitter_downloader", line 397, in user_by_screen_name
   return self._call(url_api, params=params)['data']['user']
 File "decorator", line 232, in fun
 File "utils", line 5007, in _wrapper
 File "C:\Users\15825\AppData\Local\Temp\_MEI91282\ytdl_6fa23e0e\yt_dlp\yt_dlp\twitter_downloader", line 296, in _call
   response = self.session.request(method, root + endpoint, params=params, headers=self.headers)
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Invalid: fail=True
invalid; revert
EOT: https://twitter.com/gao_gn  (76.7s)

**Comment by QuadrupleRainbow** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/7194

**Comment by Rocky-CN** [comment]
你配置代理了吗？在GUI的选项-->首选项-->网络里
Have you configured the proxy? In the GUI's Options-->Preferences-->Network

**Comment by 1314520app** [comment]
> 你配置代理了吗？在GUI的选项-->首选项-->网络里 Have you configured the proxy? In the GUI's Options-->Preferences-->Network

非常感谢，解决了哈哈哈

**Comment by JJHN585858** [comment]
> 你配置代理了吗？在GUI的选项-->首选项-->网络里你配置代理了吗？在GUI的选项-->首选项-->网络中

我目前油管视频无法下载请问怎么配置代理啊怎么填啊？
