### ISSUE TITLE
마나토끼 뉴토끼 다운로드가 막혔습니다

### ISSUE THREAD

**Issue by williams2222** [KurtBestor/Hitomi-Downloader#7276]
Invalid: [manatoki] https://manatoki342.net/comic/14165612

version: 4.1+ (24-06-02 04:24:37 UTC)
platform / locale: Windows-10-10.0.18363-SP0 / ko_kr
order / group / uid: 0 / False / 7dc555d8611b4890a6143ef5e81b689e
input: https://manatoki342.net/comic/14165612
type: manatoki
single: False
url: https://manatoki342.net/comic/14165612
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1718900600.7838023 (24-06-20 16:23:20 UTC) - 113s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1440
goodbyedpi: True
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
no html
no title
stop
Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\manatoki_downloader", line 85, in init
 File "utils", line 666, in __get__
 File "extractor\manatoki_downloader", line 101, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
 File "utils", line 2747, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki342.net/comic/14165612  (13.8s)

확인 부탁 드립니다

**Comment by woojien** [comment]
저도 안되어요~
계속 빨간 글만 떠용 ㅠㅠ

**Comment by arachne72** [comment]
다운하기 전에 설정>>내장 웹브라우저 보기 한다음 >다운할 링크 주소창에 붙이고 사람인지 체크한다음
정상적으로 이동 되면 내장 브라우저 닫고 다시 다운시도하면 됨요

**Comment by williams2222** [comment]
@arachne72 와우 잘 되네여요 감사합니다

**Comment by Omoide52** [comment]
> 다운하기 전에 설정>>내장 웹브라우저 보기 한다음 >다운할 링크 주소창에 붙이고 사람인지 체크한다음 정상적으로 이동 되면 내장 브라우저 닫고 다시 다운시도하면 됨요

감사합니다!

**Comment by henryhenry6969** [comment]
> 다운하기 전에 설정>>내장 웹브라우저 보기 한다음 >다운할 링크 주소창에 붙이고 사람인지 체크한다음 정상적으로 이동 되면 내장 브라우저 닫고 다시 다운시도하면 됨요

한번 더 설명해 주실 수 있나요? 다운로더에서 설정을 하라는 말씀이신지?
내장 웹브라우저 보기가 어디 있는지 찾을 수가 없어서요...ㅜ.ㅡ
다운로더 옵션 -> 설정 들어가도 없고
다운로더 다운 실패한 항목에서 브라우저로 보기가 있는데 활성화가 안되어 있거든요
아시는 분 한번만 더 설명 부착드립니다.

**Comment by Omoide52** [comment]
옵션 - 설정 들어가시면 창이 하나 뜨는데 거기서
네트워크 <<< 요거 누르시면 거기에 내장 웹브라우저가 있고 그 밑에 보기 << 누르시면 창이 하나 뜹니다 
그 때 나오는 창은 그대로 놔두시고 URL 주사창에 마나토끼 주소를 복붙 후 다운로드 누르면 
내장 웹브라우저 창에서 사람 확인 하는 페이지가 열리고 그 때 체크 해주면 사용 가능합니다

**Comment by henryhenry6969** [comment]
> 옵션 - 설정 들어가시면 창이 하나 뜨는데 거기서 네트워크 <<< 요거 누르시면 거기에 내장 웹브라우저가 있고 그 밑에 보기 << 누르시면 창이 하나 뜹니다 그 때 나오는 창은 그대로 놔두시고 URL 주사창에 마나토끼 주소를 복붙 후 다운로드 누르면 내장 웹브라우저 창에서 사람 확인 하는 페이지가 열리고 그 때 체크 해주면 사용 가능합니다

친절한 답변 고맙습니다~^^'
덕분에 해결 되었습니다 고맙습니다
좋은 하루 되세요~~
