### ISSUE TITLE
마나토끼가 막혔습니다.

### ISSUE THREAD

**Issue by geondori** [KurtBestor/Hitomi-Downloader#7284]
Invalid: [manatoki] https://manatoki342.net/comic/969645

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 1cabc4a36836438db6e206c775765862
input: https://manatoki342.net/comic/969645
type: manatoki
single: False
url: https://manatoki342.net/comic/969645
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1719190710.126629 (24-06-24 00:58:30 UTC) - 15s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
no title
stop
Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "C:\Users\geond\AppData\Local\Temp\_MEI143242\ytdl_a2f08008\yt_dlp\yt_dlp\manatoki_downloader", line 85, in init
   self.name
 File "utils", line 668, in __get__
 File "C:\Users\geond\AppData\Local\Temp\_MEI143242\ytdl_a2f08008\yt_dlp\yt_dlp\manatoki_downloader", line 101, in name
   artist = get_artist(self.soup)
 File "C:\Users\geond\AppData\Local\Temp\_MEI143242\ytdl_a2f08008\yt_dlp\yt_dlp\manatoki_downloader", line 119, in get_artist
   view = soup.find('div', class_='view-title', err='no title')
 File "utils", line 2735, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki342.net/comic/969645  (13.5s)

왜 이러는지좀 알려주세요

**Comment by Handstandg** [comment]
캡챠확인하셨음?

**Comment by whory13** [comment]
> 캡챠 확인음?

저도 똑같은데, 캡챠 확인용 창도 안뜸

**Comment by backlashlee** [comment]
저도 내장 웹브라우저 켜 가면서 받았는데 이젠 안 되네요.
되는 분 계세요?

**Comment by newdud122** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/7276

우선 업뎃나오기전까지 임시로 이렇게 해보세요

**Comment by Omoide52** [comment]
#7276 
방법으로 잘 하고 있었는데 아침에 일어나서 해보니
2번 확인을 하는 과정에서 안되게 막아놨나보네요 허허..
