### ISSUE TITLE
Rule34 Can't download, Invalid.

### ISSUE THREAD

**Issue by monaruss** [KurtBestor/Hitomi-Downloader#7285]
Invalid: [rule34_xxx] https://rule34.xxx/index.php?page=post&s=list&tags=binibon123

version: 4.1+ (24-06-02 04:24:37 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: 0 / False / bec071bcc2144f21bedd1c19e9d0123f
input: https://rule34.xxx/index.php?page=post&s=list&tags=binibon123
type: rule34_xxx
single: False
url: https://rule34.xxx/index.php?page=post&s=list&tags=binibon123
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1719207533.2436175 (24-06-24 05:38:53 UTC) - 2051s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 4320
goodbyedpi: None
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags=binibon123&pid=0&limit=100
403 Client Error: Forbidden for url: https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags=binibon123&pid=0&limit=100
stop
Traceback (most recent call last):
 File "downloader", line 438, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\rule34_xxx_downloader", line 55, in read
 File "extractor\rule34_xxx_downloader", line 106, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags=binibon123&pid=0&limit=100

Invalid: fail=True
EOT: https://rule34.xxx/index.php?page=post&s=list&tags=binibon123  (90.9s)

**Comment by monaruss** [comment]
I don't know how I don't know why, but I fixed it by restarting my PC and reinstalling the app on https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
