### ISSUE TITLE
No longer able to download from MyReadingManga.info

### ISSUE THREAD

**Issue by z10381035** [KurtBestor/Hitomi-Downloader#7298]
When attempting to download any image content from myreadingmanga.info using the Hitomi Downloader, I receive an error. Below is example of one download attempt:

Invalid: [mrm] https://myreadingmanga.info/sksk-dan-oji-mama-cg

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: 0 / False / 47b1759715ee41ef9e57510968a39b2f
input: https://myreadingmanga.info/sksk-dan-oji-mama-cg
type: mrm
single: False
url: https://myreadingmanga.info/sksk-dan-oji-mama-cg
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1719653394.9663348 (24-06-29 09:29:54 UTC) - 179s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.04.28.232723
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
cf protection
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\mrm_downloader", line 66, in read
 File "extractor\mrm_downloader", line 62, in name
 File "extractor\mrm_downloader", line 77, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://myreadingmanga.info/sksk-dan-oji-mama-cg  (7.0s)

cf protection
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\mrm_downloader", line 66, in read
 File "extractor\mrm_downloader", line 62, in name
 File "extractor\mrm_downloader", line 77, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://myreadingmanga.info/sksk-dan-oji-mama-cg  (7.0s)

**Comment by ADONISxdd** [comment]
don't know the reason it's not currently working but you should try temporary fix if you go to settings - network - click the view on the view in built in browser and paste the link of the myreadingmanga  and click the cloudflare it should download normally but you have to do it each time you close the software.

**Comment by z10381035** [comment]
Thank you ADONISxdd! That temporary workaround let me download for now.
