### ISSUE TITLE
데이터 다운로드 실패라고 나옵니다.

### ISSUE THREAD

**Issue by NaYana505** [KurtBestor/Hitomi-Downloader#7302]
Traceback (most recent call last):
  File "downloader", line 431, in read_html
  File "urllib\request", line 531, in open
  File "urllib\request", line 640, in http_response
  File "urllib\request", line 569, in error
  File "urllib\request", line 502, in _call_chain
  File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_searcher", line 209, in download_json
  File "hitomi_searcher", line 371, in download_json_
  File "downloader", line 459, in read_html
  File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://{kurtpy}.com/h_data

**Comment by NaYana505** [comment]
정상작동합니다
