### ISSUE TITLE
겔부루 다운이 안되네요...

### ISSUE THREAD

**Issue by 5pacezer0** [KurtBestor/Hitomi-Downloader#7328]
주소넣고 지정 페이지 다운로드 했는데 invalid 라고 뜨면서 안되는데 어떻게 해야 하나요?
최신 베타버전 받아도 해결이 안되네요...

Invalid: [gelbooru] https://gelbooru.com/index.php?page=post&s=list&tags=secelia_dote+

version: 4.1+ (24-07-14 10:32:29 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / b7da57e20c3f417189d411f9fbfd2c75
input: https://gelbooru.com/index.php?page=post&s=list&tags=secelia_dote+
type: gelbooru
single: False
url: https://gelbooru.com/index.php?page=post&s=list&tags=secelia_dote+
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: 1 / None
time: 1721135124.9585857 (24-07-16 13:05:24 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 2160
goodbyedpi: True
ytdl: yt_dlp 2024.07.09
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
user_id: None
https://gelbooru.com/index.php?page=post&s=list&tags=secelia_dote+
HTTPSConnectionPool(host='gelbooru.com', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=secelia_dote+ (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gelbooru.com', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=secelia_dote+ (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\gelbooru_downloader", line 59, in read
 File "extractor\gelbooru_downloader", line 125, in get_imgs
 File "downloader", line 364, in read_soup
 File "downloader", line 459, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='gelbooru.com', port=443): Max retries exceeded with url: /index.php?page=post&s=list&tags=secelia_dote+ (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=secelia_dote+  (0.5s)

**Comment by 5pacezer0** [comment]
해결됐습니다.
