### ISSUE TITLE
deviantart.com

### ISSUE THREAD

**Issue by tenjouina** [KurtBestor/Hitomi-Downloader#7353]
Invalid: [deviant] https://search?q=jimryu.deviantart.com

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ja_jp
order / group / uid: 0 / False / ba029dfc40284b53809c9302bcde14ca
input: https://search?q=jimryu.deviantart.com
type: deviant
single: False
url: https://search?q=jimryu.deviantart.com
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1721661725.4786747 (24-07-22 15:22:05 UTC) - 14s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.07.09
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1491, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://search?q=jimryu.deviantart.com  (6.1s)

**Comment by tenjouina** [comment]
はい、何個かDLしましたが全部出来ました
