### ISSUE TITLE
마나토끼가 다운로드가 안됩니다

### ISSUE THREAD

**Issue by samfan0429** [KurtBestor/Hitomi-Downloader#7375]
Invalid: [manatoki] https://manatoki346.net/comic/15734916

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 137694d37f134de5890eae3a9f3a0e6b
input: https://manatoki346.net/comic/15734916
type: manatoki
single: False
url: https://manatoki346.net/comic/15734916
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1722049831.759076 (24-07-27 03:10:31 UTC) - 76s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2024.07.09
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "C:\Users\USER\AppData\Local\Temp\_MEI81442\ytdl_5551ee13\yt_dlp\yt_dlp\manatoki_downloader", line 85, in init
   self.name
 File "utils", line 668, in __get__
 File "C:\Users\USER\AppData\Local\Temp\_MEI81442\ytdl_5551ee13\yt_dlp\yt_dlp\manatoki_downloader", line 101, in name
   artist = get_artist(self.soup)
 File "C:\Users\USER\AppData\Local\Temp\_MEI81442\ytdl_5551ee13\yt_dlp\yt_dlp\manatoki_downloader", line 119, in get_artist
   view = soup.find('div', class_='view-title', err='no title')
 File "utils", line 2735, in find
utils.SoupNotFound: no title

Invalid: fail=True
quality: 100%
EOT: https://manatoki346.net/comic/15734916  (13.7s)

위와 같은 내용으로 에러가 뜨는데. 현재 이건 해결이 안되고 있나요?

**Comment by kkk2579** [comment]
임시적으로 다운 받는법은 저번에 같은 사안 발생했을때 댓글로 올라왔었습니다
설정 -> 네트워크 -> 내장브라우저 열기 -> 내장브라우저에 해당 마나토끼 주소로 들어가서 캡차 인증 성공시킨후 -> 히토미다운로더에 해당 주소 입력하면 다운로드가 됩니다
