### ISSUE TITLE
yesterday it was still working but today its tripping (nhentai)

### ISSUE THREAD

**Issue by jaceelon** [KurtBestor/Hitomi-Downloader#7376]
Invalid: [nhentai] https://nhentai.net/g/464415/

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / en_us
order / group / uid: 0 / False / 34bf2ae21e6c42a59504531763d34ff6
input: https://nhentai.net/g/464415/
type: nhentai
single: False
url: https://nhentai.net/g/464415/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1722069411.2455883 (24-07-27 08:36:51 UTC) - 129s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.07.09
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
no html
no html
no html
no html
no html
no html
no html
no html
no html
404 Client Error: Not Found for url: https://nhentai.net/g/464415/1/
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\nhentai_downloader", line 70, in get_info
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nhentai.net/g/464415/1/

Invalid: fail=True
EOT: https://nhentai.net/g/464415/  (92.6s)

**Comment by jaceelon** [comment]
btw downloading from hitomi automatically redirects you to ex hentai gallery and make it slower for some reason
