### ISSUE TITLE
유튜브 다운로드에 대해서

### ISSUE THREAD

**Issue by nailro1289** [KurtBestor/Hitomi-Downloader#7383]
어제 다른 컴퓨터를 이용해서 프로그램 실행을 했는데

최신 버전인 4.1은 완전 다운이 가능했는데, 그 밑버전들은 불완전 다운이 되더군요

다운로드 과정을 보니 퍼센트 표시로 갔다가 100퍼센트가 된 후에 마지막에 '변환 중'이라는 상태로 나온 후에 그게 끝나야 다운로드 과정이 마쳤다는 신호더라구요

최신 버전인 4.1의 경우에는 이런 과정들이 완벽히 되었지만, 그 밑버전들의 경우에는 퍼센트까지 갔다가 100퍼센트까지 갔지만 '변환 중'이라는 과정이 들어가지 않고 그 상태로 멈추어 주황색 상태인 불완전 다운로드 상태로 남아있네요

![42342341 (1)](https://github.com/user-attachments/assets/78687016-9d9e-4398-b795-5085794fa488)

(혹시 몰라 이 동영상의 작업 정보를 남겨 놓겠습니다 :
【記念配信】誕生日、みんなから「おめでとう」のプレゼントが欲しい！！！【ASMR・立体音響・KU100】

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko_kr
order / group / uid: 157 / False / 4900ffb56e4443b7ac3786bdbe3328da
input: https://www.youtube.com/watch?v=BOISblXazNA
type: youtube
single: True
url: https://www.youtube.com/watch?v=BOISblXazNA
dir: hitomi_downloaded_youtube
zip: 
artist: 柚萌-yume- @毎日ASMR配信中
valid / done: False / True
range / range_p: None / None
time: 1720840077.790047 (24-07-13 03:07:57 UTC) - 1420461s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: mp4
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False

[File Names]
[0001] hitomi_downloaded_youtube\【記念配信】誕生日、みんなから「おめでとう」のプレゼントが欲しい！！！【ASMR・立体音響・KU100】 (BOISblXazNA).mp4

[URLs]
[0001] Video(https://www.youtube.com/watch?v=BOISblXazNA)    --->    https://rr5---sn-n3cgv5qc5oq-u5xs.googlevideo.com/videoplayback?expire=1720861777&ei=8e-RZuDJGZ2ZvcAPva2a6AI&ip=114.202.7.136&id=o-AGv8C62yyHuUdhjYBfmlIGDFNr-HDmOnzBq42Eb8UjDK&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=7Q&mm=31%2C29&mn=sn-n3cgv5qc5oq-u5xs%2Csn-n3cgv5qc5oq-bh2se&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=2185000&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=434981832&dur=3762.000&lmt=1720573309331933&mt=1720839664&fvip=2&keepalive=yes&c=IOS&txp=5309224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAM56NH_IhqeDo8D9VSlzF85ba619BjQiJOjVA9PPHLxOAiBvAkTyPH5QrP9TAQ19J3Q-As5zRwuzcojQpF2joA2blw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAKX_1rNE_r5S76X5Z7tKEAhibb6uRECT3MuRxqYfh8XLAiA6uxueHDhTjF_COvLLgCyJRMub4C0xDl5lzLmoPEcmVA%3D%3D

[Messages]
[warning] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[error] Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                   You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BOISblXazNA
[debug] [youtube] BOISblXazNA: Downloading webpage
[debug] [youtube] BOISblXazNA: Downloading ios player API JSON
[debug] [youtube] BOISblXazNA: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Precondition check failed.
[warning] [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[debug] [youtube] BOISblXazNA: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Precondition check failed.
[warning] [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[debug] [youtube] BOISblXazNA: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Precondition check failed.
[warning] [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[debug] [youtube] BOISblXazNA: Downloading android player API JSON
[warning] [youtube] YouTube said: ERROR - Precondition check failed.
[warning] [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] BOISblXazNA: Downloading player 8d9f6215
[warning] [youtube] BOISblXazNA: nsig extraction failed: You may experience throttling for some formats
        n = GWMYhWiYRa5ZRoRNJDY ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
[warning] [youtube] BOISblXazNA: nsig extraction failed: You may experience throttling for some formats
        n = sJpRBuTEURcridn7p2- ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
[debug] [youtube] BOISblXazNA: Downloading m3u8 information
[debug] [info] BOISblXazNA: Downloading subtitles: live_chat
[warning] No subtitle format found matching "vtt" for language live_chat, using json
live: was_live
[27p][0.02658160552897395fps][None][None] mhtml [None / None] ─ sb3 - 48x27 (storyboard)
[45p][0.10047846889952153fps][None][None] mhtml [None / None] ─ sb2 - 80x45 (storyboard)
[90p][0.10047846889952153fps][None][None] mhtml [None / None] ─ sb1 - 160x90 (storyboard)
[180p][0.10047846889952153fps][None][None] mhtml [None / None] ─ sb0 - 320x180 (storyboard)
[None][0fps][48.915kbps][48.915] webm [None / opus] ─ 249-drc - audio only (low, DRC, THROTTLED)
[None][0fps][63.388kbps][63.388] webm [None / opus] ─ 250-drc - audio only (low, DRC, THROTTLED)
[None][0fps][48.2kbps][48.2] webm [None / opus] ─ 249 - audio only (low, THROTTLED)
[None][0fps][62.485kbps][62.485] webm [None / opus] ─ 250 - audio only (low, THROTTLED)
[None][0fps][48.783kbps][48.783] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140-drc - audio only (medium, DRC, THROTTLED)
[None][0fps][124.291kbps][124.291] webm [None / opus] ─ 251-drc - audio only (medium, DRC, THROTTLED)
[None][0fps][122.266kbps][122.266] webm [None / opus] ─ 251 - audio only (medium, THROTTLED)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[144p][30fps][None][65.423] webm [vp9 / None] ─ 278 - 256x144 (144p, THROTTLED)
[144p][30fps][None][56.643] mp4 [avc1.4D400C / None] ─ 160 - 256x144 (144p)
[240p][30fps][None][122.802] webm [vp9 / None] ─ 242 - 426x240 (240p, THROTTLED)
[240p][30fps][None][124.962] mp4 [avc1.4D4015 / None] ─ 133 - 426x240 (240p)
[360p][30fps][96.0kbps(fixed)][342.466] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p, THROTTLED)
[360p][30fps][None][189.757] webm [vp9 / None] ─ 243 - 640x360 (360p, THROTTLED)
[360p][30fps][None][243.349] mp4 [avc1.4D401E / None] ─ 134 - 640x360 (360p)
[480p][30fps][None][304.985] webm [vp9 / None] ─ 244 - 854x480 (480p, THROTTLED)
[480p][30fps][None][465.646] mp4 [avc1.4D401F / None] ─ 135 - 854x480 (480p)
[720p][30fps][None][822.675] webm [vp9 / None] ─ 247 - 1280x720 (720p, THROTTLED)
[720p][30fps][None][925.001] mp4 [avc1.64001F / None] ─ 136 - 1280x720 (720p)

utime: 1720483200.0

# stream_final
[720p][30fps][None][925.001] mp4 [avc1.64001F / None] ─ 136 - 1280x720 (720p)

[None][0fps][48.915kbps][48.915] webm [None / opus] ─ 249-drc - audio only (low, DRC, THROTTLED)
[None][0fps][63.388kbps][63.388] webm [None / opus] ─ 250-drc - audio only (low, DRC, THROTTLED)
[None][0fps][48.2kbps][48.2] webm [None / opus] ─ 249 - audio only (low, THROTTLED)
[None][0fps][62.485kbps][62.485] webm [None / opus] ─ 250 - audio only (low, THROTTLED)
[None][0fps][48.783kbps][48.783] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140-drc - audio only (medium, DRC, THROTTLED)
[None][0fps][124.291kbps][124.291] webm [None / opus] ─ 251-drc - audio only (medium, DRC, THROTTLED)
[None][0fps][122.266kbps][122.266] webm [None / opus] ─ 251 - audio only (medium, THROTTLED)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[360p][30fps][96.0kbps(fixed)][342.466] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p, THROTTLED)

[None][0fps][48.783kbps][48.783] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140-drc - audio only (medium, DRC, THROTTLED)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[360p][30fps][96.0kbps(fixed)][342.466] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p, THROTTLED)

[None][0fps][48.783kbps][48.783] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140-drc - audio only (medium, DRC, THROTTLED)
[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)

[None][0fps][129.472kbps][129.472] m4a [None / mp4a.40.2] ─ 140-drc - audio only (medium, DRC, THROTTLED)

filename: 【記念配信】誕生日、みんなから「おめでとう」のプレゼントが欲しい！！！【ASMR・立体音響・KU100】 (BOISblXazNA).mp4
Resolution: 720p
Codec: avc1.64001F / None
Abr: None
Subtype: mp4
FPS: 30

Download audio: https://rr5---sn-n3cgv5qc5oq-u5xs.googlevideo.com/videoplayback?expire=1720861776&ei=8O-RZv2QFYSo7OsPl8S-uAo&ip=114.202.7.136&id=o-ABWuLJMP1njUB2w_SMJYJZYBr7HxnbXFe3cO-aJqnOYa&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=7Q&mm=31%2C29&mn=sn-n3cgv5qc5oq-u5xs%2Csn-n3cgv5qc5oq-bh2se&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=2185000&bui=AXc671I-ZAlsI1rJZ8cd1gekhU8q2e8cHJ049UUrseXFPRVN2RLx598ief4Tc33I_WWdK6792B60v9Z8&spc=NO7bAWm57waHwb9XACuLhNrnqjxk6FwyGQtFUxZH-iOfNS8UVrMsrqP-7WZF&vprv=1&svpuc=1&xtags=drc%3D1&mime=audio%2Fmp4&ns=KmGaA3r-lAH8JfHZ3CSQ94gQ&rqh=1&gir=yes&clen=60885744&dur=3762.073&lmt=1720573602602317&mt=1720839664&fvip=2&keepalive=yes&c=WEB&sefc=1&txp=5308224&n=sJpRBuTEURcridn7p2-&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAMKTEp_3OfLJqtMFikdxuVnMIDyGMXVMtGrExS92sMTAAiEA23EGigjspIRCNBAoDzWMYppXuXpFxCA0KPXgEnkgsuo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRgIhALAMDl2gH5HXq47980rdtomtlzF02d_kf5u0RjWoMzOjAiEAlUZirzYiXvn3XiKEnSrjcvEbBbKRszgKR8uvnx01Hhk%3D
use just download: overwrite=True

Fail_403 : \\?\C:\Users\MAIN\AppData\Local\Temp\4bd43483cb1b46ba811fc0cbf077e781_a.tmp
audio done
thumb: https://i.ytimg.com/vi/BOISblXazNA/maxresdefault.jpg
Convert: E:\새 폴더 (2)\새 폴더 (4)\새 폴더 (2)\hitomi_downloaded_youtube\【記念配信】誕生日、みんなから「おめでとう」のプレゼントが欲しい！！！【ASMR・立体音響・KU100】 (BOISblXazNA).mp4
Lazyurl pp Error: hitomi_downloaded_youtube\【記念配信】誕生日、みんなから「おめでとう」のプレゼントが欲しい！！！【ASMR・立体音響・KU100】 (BOISblXazNA).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 414, in run
 File "hitomi_downloader", line 407, in pp_
 File "extractor\youtube_downloader", line 297, in pp
 File "ffmpeg", line 281, in merge
 File "ffmpeg", line 241, in rename
Exception: No file

stop
-show_streams -print_format json -v error "【記念配信】誕生日、みんなから「おめでとう」のプレゼントが欲しい！！！【ASMR・立体音響・KU100】 (BOISblXazNA).mp4"
EOT: https://www.youtube.com/watch?v=BOISblXazNA  (130.2s)

)

이 상태에서 '다시 시작'을 하면 불완전 상태를 완전 다운로드 상태로 보여지지만, 다운로드된 폴더 안의 상태는 불완전 상태더군요

![23f3dswe](https://github.com/user-attachments/assets/a8e94914-b7aa-4c06-b08e-9dd248902cc2)

보통 mp4로 받았을 경우, 파일을 보면 해당 동영상 장면 중 하나가 아이콘처럼 표시되는데 반해, 해당 동영상 플레이어 아이콘이 뜨더군요. 즉, 다운로드가 불완전 상태로 받아졌다는 얘기죠

그리고 이 파일을 스마트폰에 넣어서 보려고 했는데, 영상은 나오나 오디오는 나오지 않네요. 즉, 다운로드를 불완전하게 받았다는 거죠

4.1말고도 그 밑버전들도 완전 상태로 다운 받을 수 있게 시스템을 업데이트해주셨으면 합니다

**Comment by qj8x67s33a44** [comment]
밑버전을 업데이트한게 최신버전일텐데요
뭔가 다른 이유라도 있으신진 모르겠으나
다운로드가 잘 되신다는 4.1을 사용하시는게 좋을듯 싶습니다

**Comment by nailro1289** [comment]
윈도우 10 설치되어 있는 회사 컴퓨터로 사용해 4.1을 설치해서 가능했습니다
집에 있는 컴퓨터는 윈도우10이 아닌 7이 설치되어 있어서 최신버전은 실행이 안되고 3.8f까지만 프로그램이 실행 가능합니다ㅜㅜ
3.8f에선 마나토끼 등 이미지 파일 받는 곳은 안정적으로 잘 받으나 유튜브는 불완전 다운로드가 되네요
3.8f도 유튜브 완전 다운로드 받을 수 있게 프로그래밍 해주셨으면 감사하겠습니다

2024년 7월 31일 (수) 오후 12:31, qj8x67s33a44 ***@***.***>님이 작성:
