### ISSUE TITLE
마나토끼가 몇일 전 부터 말썽입니다.

### ISSUE THREAD

**Issue by v5598** [KurtBestor/Hitomi-Downloader#7385]
몇일 전부터 마나토끼 사이트가 다운로드가 안되는데 제가 뭘 잘못하고 있는지 모르겠습니다. 
도와주시면 감사하겠습니다.
( _ _  ) 꾸벅

59분 29초 뒤 다시 시작: Invalid: [manatoki] https://manatoki347.net/comic/5828751

version: 4.1+ (24-05-19 16:03:44 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko_kr
order / group / uid: 8 / False / 190f9cc02a7045908fa7241dbe0d2b19
input: https://manatoki347.net/comic/5828751
type: manatoki
single: False
url: https://manatoki347.net/comic/5828751
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1722494644.5105462 (24-08-01 06:44:04 UTC) - 81s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 2160
goodbyedpi: True
ytdl: yt_dlp 2024.07.25
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1379, in start
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\manatoki_downloader", line 85, in init
 File "utils", line 666, in __get__
 File "extractor\manatoki_downloader", line 101, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
 File "utils", line 2747, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki347.net/comic/5828751  (49.2s)

**Comment by eyvanwalker** [comment]
저도 같은 증상으로 고민중입니다.
왜인지 비슷한 시기에 토끼다운로더도 로그인이 안되서 작동이 안되더라구요 ㅠㅠ
