### ISSUE TITLE
유튜브 실시간 녹화기능 오류

### ISSUE THREAD

**Issue by porsche-tiger** [KurtBestor/Hitomi-Downloader#7392]
안녕하세요 유튜브 녹화기능을 잘 쓰고 있던 사람입니다.  프로그램을 개발해주셔서 감사합니다.
다름이 아니라 8월 2일을 기점으로 일반영상 다운로드는 문제가 없는데 유튜브 라이브 녹화에 문제가 있어 다운로드가 되지 않고 있습니다. 하나의 채널이 아닌 모든 채널이 다 문제가 있습니다. 어떤 채널도 녹화가 되지 않고 있습니다. 부탁입니다.......제발 해결해주세요.....ㅠㅠ
작업코드랑 링크를 남겨놓겠습니다.

https://www.youtube.com/@%EB%AC%AD%EC%9D%B4/live

Invalid: [youtube] https://www.youtube.com/@%EB%AC%AD%EC%9D%B4/live

version: 4.1+ (24-05-19 16:03:44 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 8ee9d58dc5ff45fa9c86543d55850fe6
input: https://www.youtube.com/@%EB%AC%AD%EC%9D%B4/live
type: youtube
single: True
url: https://www.youtube.com/@%EB%AC%AD%EC%9D%B4/live
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1722782338.1904247 (24-08-04 14:38:58 UTC) - 310s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
res: 4320
goodbyedpi: False
ytdl: yt_dlp 2024.08.01
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'writeautomaticsub': True, 'logger': <ytdl.Logger object at 0x0000020B433CBC10>, 'user_agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1830 extractors
[ytdl] [youtube:tab] Extracting URL: https://www.youtube.com/@%EB%AC%AD%EC%9D%B4/live
[ytdl] [youtube:tab] @%EB%AC%AD%EC%9D%B4/live: Downloading webpage
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=03BUmjt3sVY
[ytdl] [youtube] 03BUmjt3sVY: Downloading webpage
[ytdl] [debug] [youtube] Extracted SAPISID cookie
[ytdl] [debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[ytdl] [youtube] 03BUmjt3sVY: Downloading ios player API JSON
[ytdl] [youtube] 03BUmjt3sVY: Downloading tv player API JSON
[ytdl] [youtube] 03BUmjt3sVY: Downloading m3u8 information
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: best/bestvideo+bestaudio
live: is_live
LIVE [None][60.0fps][None][5552.61] mp4 [None / None] ─ 233 - audio only (Default, IOS)
LIVE [None][60.0fps][None][5552.61] mp4 [None / None] ─ 234 - audio only (Default, IOS)
LIVE [144p][30.0fps][None][269.034] mp4 [avc1.4D400C / None] ─ 269 - 256x144 (IOS)
LIVE [240p][30.0fps][None][507.418] mp4 [avc1.4D4015 / None] ─ 229 - 426x240 (IOS)
LIVE [360p][30.0fps][None][962.461] mp4 [avc1.4D401E / None] ─ 230 - 640x360 (IOS)
LIVE [480p][30.0fps][None][1282.517] mp4 [avc1.4D401F / None] ─ 231 - 854x480 (IOS)
LIVE [720p][60.0fps][None][2922.155] mp4 [avc1.4D4020 / None] ─ 311 - 1280x720 (IOS)
LIVE [1080p][60.0fps][None][5552.61] mp4 [avc1.4D402A / None] ─ 312 - 1920x1080 (IOS)

utime: 1722729600.0

# stream_final
LIVE [1080p][60.0fps][None][5552.61] mp4 [avc1.4D402A / None] ─ 312 - 1920x1080 (IOS)

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 491, in read
 File "utils", line 4871, in ready
 File "extractor\youtube_downloader", line 236, in get
IndexError: list index out of range

list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\youtube_downloader", line 498, in read
 File "extractor\youtube_downloader", line 491, in read
 File "utils", line 4871, in ready
 File "extractor\youtube_downloader", line 236, in get
IndexError: list index out of range

Invalid: fail=True
EOT: https://www.youtube.com/@%EB%AC%AD%EC%9D%B4/live  (2.8s)

-------------------------------------------------------------------------------------------------------------

https://youtube.com/@%EC%95%84%EC%B9%B4%EC%BA%89/live

Invalid: [youtube] https://youtube.com/@%EC%95%84%EC%B9%B4%EC%BA%89/live

version: 4.1+ (24-05-19 16:03:44 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 1b58e4470fcd40bd959d5e7834f017f5
input: https://youtube.com/@%EC%95%84%EC%B9%B4%EC%BA%89/live
type: youtube
single: True
url: https://youtube.com/@%EC%95%84%EC%B9%B4%EC%BA%89/live
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1722782890.5616453 (24-08-04 14:48:10 UTC) - 14s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.08.01
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'writeautomaticsub': True, 'logger': <ytdl.Logger object at 0x0000024372C48D90>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.1', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1830 extractors
[ytdl] [youtube:tab] Extracting URL: https://youtube.com/@%EC%95%84%EC%B9%B4%EC%BA%89/live
[ytdl] [youtube:tab] @%EC%95%84%EC%B9%B4%EC%BA%89/live: Downloading webpage
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=AiE2yG9wndk
[ytdl] [youtube] AiE2yG9wndk: Downloading webpage
[ytdl] [debug] [youtube] Extracted SAPISID cookie
[ytdl] [debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[ytdl] [youtube] AiE2yG9wndk: Downloading ios player API JSON
[ytdl] [youtube] AiE2yG9wndk: Downloading tv player API JSON
[ytdl] [youtube] AiE2yG9wndk: Downloading m3u8 information
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: best/bestvideo+bestaudio
live: is_live
LIVE [None][60.0fps][None][5552.61] mp4 [None / None] ─ 233 - audio only (Default, IOS)
LIVE [None][60.0fps][None][5552.61] mp4 [None / None] ─ 234 - audio only (Default, IOS)
LIVE [144p][30.0fps][None][269.034] mp4 [avc1.4D400C / None] ─ 269 - 256x144 (IOS)
LIVE [240p][30.0fps][None][507.418] mp4 [avc1.4D4015 / None] ─ 229 - 426x240 (IOS)
LIVE [360p][30.0fps][None][962.461] mp4 [avc1.4D401E / None] ─ 230 - 640x360 (IOS)
LIVE [480p][30.0fps][None][1282.517] mp4 [avc1.4D401F / None] ─ 231 - 854x480 (IOS)
LIVE [720p][60.0fps][None][2922.155] mp4 [avc1.4D4020 / None] ─ 311 - 1280x720 (IOS)
LIVE [1080p][60.0fps][None][5552.61] mp4 [avc1.4D402A / None] ─ 312 - 1920x1080 (IOS)

utime: 1722643200.0

# stream_final
LIVE [1080p][60.0fps][None][5552.61] mp4 [avc1.4D402A / None] ─ 312 - 1920x1080 (IOS)

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 491, in read
 File "utils", line 4871, in ready
 File "extractor\youtube_downloader", line 236, in get
IndexError: list index out of range

list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\youtube_downloader", line 498, in read
 File "extractor\youtube_downloader", line 491, in read
 File "utils", line 4871, in ready
 File "extractor\youtube_downloader", line 236, in get
IndexError: list index out of range

Invalid: fail=True
EOT: https://youtube.com/@%EC%95%84%EC%B9%B4%EC%BA%89/live  (3.0s)

**Comment by porsche-tiger** [comment]
내장 웹브라우저로 라이브 주소 직접 치고 들어가니 브라우저 문제라고 하고 쿠키 설정이 불가능해 유튜브 로그인도 불가능합니다. 아마도 내장 웹브라우저를 바꿔야 하실 듯 합니다.

**Comment by KurtBestor** [comment]
고쳤어요
