### ISSUE TITLE
comic walker error

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#7401]
Invalid: [comicwalker] https://comic-walker.com/detail/KC_005379_S

version: 4.1+ (24-07-14 10:32:29 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / c7c3d90681e24d28a88e9b42a17852f8
input: https://comic-walker.com/detail/KC_005379_S
type: comicwalker
single: False
url: https://comic-walker.com/detail/KC_005379_S
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1723010312.8017535 (24-08-07 05:58:32 UTC) - 56s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: False
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\comicwalker_downloader", line 63, in read
 File "extractor\comicwalker_downloader", line 139, in get_title
Exception: no title

Invalid: fail=True
EOT: https://comic-walker.com/detail/KC_005379_S  (0.1s)

**Comment by qj8x67s33a44** [comment]
갑자기 픽시브 코믹도 안되더니 이것도 안되네요
죄송하지만 바쁘신 와중에 부탁 좀 드리겠습니다

**Comment by qj8x67s33a44** [comment]
https://comic-walker.com/detail/KC_003218_S?episodeType=comics
https://comic-walker.com/api/contents/viewer?episodeId=018f0e51-2585-7c32-ad5e-53196da0c5d2&imageSizeType=width%3A1284
https://cdn.comic-walker.com/images/3218/3/2/20240402165740/1/1_8c40a4951c66d9abd256d502151793a94c508d4100acba66b23190fb968ea801.webp?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4uY29taWMtd2Fsa2VyLmNvbS9pbWFnZXMvMzIxOC8zLzIvMjAyNDA0MDIxNjU3NDAvMS8qLndlYnAiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MjMwOTMwNTB9fX1dfQ__&Signature=FNfvxIsk-r4gOzivFDr0iJN-1f-Sg-0m8TR1827LRlMXW4XkmrBmPNWXPt7th~CbDqWCNyOGqrjQcca1S7ku9Smh4EjDUr6UCUQjCiDLwlC-FslRO603Y7OIgCQ7ftKASvrvMmGf0~g84NQbLWqG2CM7HhTp05DOwzmzjpJGM5L-cgKNbpxG6kq3aA4slRsHv8qAcS4mOgPX6PbBtrW7iL2goV3BFo7vY4sA-qxMbYc5Mg2SefYmgx3zkaXrpFPAnPiNChBptAkRNUeTHRyYAuZPoYiy2-uFidTfjBNjsW-jD9VmPjwDs0je8N-WaH-VfzpbjcycVl7iT1B~TlGi3w__&Key-Pair-Id=K2YXDWASRN7F3E

파이썬 requests 로 이미지 다운로드하면 엑박 이미지가 다운로드 됩니다.
어떻게 하면 제대로 다운로드가 가능할지 여쭤봐도 될까요?

with open("파일명.확장자", "wb") as f:
    image = requests.get(url)
    f.write(image.content)

이렇게 해보고 있습니다.
