### ISSUE TITLE
단부루 / Danbooru 사이트 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by naritataishinluv** [KurtBestor/Hitomi-Downloader#7425]
Invalid: [danbooru] https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29

version: 4.1+ 
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 1 / False / 7249b12c14bf4df999265cfcc3f436bb
input: https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29
type: danbooru
single: False
url: https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1723731500.803216 
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29&page=1
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\danbooru_downloader", line 66, in read
 File "extractor\danbooru_downloader", line 174, in get_imgs
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29  (4.3s)

https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29&page=1
403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29&page=1
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\danbooru_downloader", line 66, in read
 File "extractor\danbooru_downloader", line 153, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\danbooru_downloader", line 124, in read_soup
 File "downloader", line 364, in read_soup
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29&page=1

Invalid: fail=True
EOT: https://danbooru.donmai.us/posts?tags=narita_taishin_%28umamusume%29  (14.8s)

이렇게 뜨면서 다운이 안됩니다 
도와주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
