### ISSUE TITLE
치지직 클립 다운로드 불가

### ISSUE THREAD

**Issue by eleage8992** [KurtBestor/Hitomi-Downloader#7442]
쿠키 업데이트, dpi 우회, vpn, 브라우저 변경, 0810 베타버전 다운로드 등 
다양하게 시도 해봐도 치지직 클립을 다운받을수가 없습니다.

또한 관련있을지 몰라서 덧붙히자면 
이것저것 해보다가 내장 브라우저로 해당 클립 링크를 통해 페이지에 접속하면 클립영상이 재생되지 않는 모습을 확인했습니다.
재생 아이콘과 그 뒤에 로딩 모션만 계속 지속되는 상태입니다.

문제를 해결할수 있을까요?

Invalid: [chzzk] https://chzzk.naver.com/clips/oSkvPgEc7j

version: 4.1+ (24-08-10 17:02:13 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 3629 / False / 07ffb23477ce4005bbd6173670a39404
input: https://chzzk.naver.com/clips/oSkvPgEc7j
type: chzzk
single: True
url: https://chzzk.naver.com/clips/oSkvPgEc7j
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1724583144.2712233 (24-08-25 10:52:24 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1080
goodbyedpi: False
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
tab: oskvpgec7j
oskvpgec7j
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\chzzk_downloader", line 74, in read
NotImplementedError: oskvpgec7j

Invalid: fail=False
EOT: https://chzzk.naver.com/clips/oSkvPgEc7j  (0.0s)

tab: oskvpgec7j
oskvpgec7j
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\chzzk_downloader", line 74, in read
NotImplementedError: oskvpgec7j

Invalid: fail=False
EOT: https://chzzk.naver.com/clips/oSkvPgEc7j  (0.0s)

**Comment by eleage8992** [comment]
아무것도 바꾼게 없는데 갑자기 정상적으로 다운로드가 되는것을 보니 사이트의 일시적 문제였나 보네요 
해결되었습니다.
