### ISSUE TITLE
The download issue "404 not found" of twitter video.

### ISSUE THREAD

**Issue by wangzhao2222** [KurtBestor/Hitomi-Downloader#7444]
### Although login again, download process was cancelled abnormally with "Login required; Please login: 404 Not Found".

Login required; Please login: 404 Not Found
https://twitter.com/elonmusk

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / zh_cn
order / group / uid: 0 / False / 8c381a5a633c48a6a5b1cc9783f8d773
input: https://twitter.com/elonmusk
type: twitter
single: False
url: https://twitter.com/elonmusk
dir: 
zip: 
artist: Elon Musk
valid / done: False / True
range / range_p: None / None
time: 1724649444.474228 (24-08-26 05:17:24 UTC) - 10s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {uids: ['44196397']}
live: False
changed: True

[File Names]

[URLs]

[Messages]
format: None
type: user
!!! get guest_token
token type: <class 'str'>
generate csrf
uid: 44196397
multiple tweets rt:False
mc: 2440
call... UserMedia
404 Not Found
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\twitter_downloader", line 152, in read
 File "extractor\twitter_downloader", line 778, in get_imgs
 File "utils", line 4008, in check_alive_iter
 File "extractor\twitter_downloader", line 502, in _pagination_tweets
 File "decorator", line 232, in fun
 File "utils", line 5007, in _wrapper
 File "extractor\twitter_downloader", line 320, in _call
extractor.twitter_downloader.LoginRequired: 404 Not Found

Invalid: fail=False
EOT: https://twitter.com/elonmusk  (7.4s)

format: None
type: user
!!! get guest_token
token type: <class 'str'>
generate csrf
uid: 44196397
multiple tweets rt:False
mc: 2440
call... UserMedia
404 Not Found
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\twitter_downloader", line 152, in read
 File "extractor\twitter_downloader", line 778, in get_imgs
 File "utils", line 4008, in check_alive_iter
 File "extractor\twitter_downloader", line 502, in _pagination_tweets
 File "decorator", line 232, in fun
 File "utils", line 5007, in _wrapper
 File "extractor\twitter_downloader", line 320, in _call
extractor.twitter_downloader.LoginRequired: 404 Not Found

Invalid: fail=False
EOT: https://twitter.com/elonmusk  (7.5s)

**Comment by wangzhao2222** [comment]
reset and load cookies make it works.
