### ISSUE TITLE
Xhamster 다운로드가 안됩니다

### ISSUE THREAD

**Issue by wwkedesde** [KurtBestor/Hitomi-Downloader#7453]
19세 임신

version: 4.1+ (24-08-10 17:02:13 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / ebfc8238f5a24ada9915675c12123af3
input: https://xhamster.com/videos/19-and-pregnant-xhq5OhB
type: xhamster
single: True
url: https://xhamster.com/videos/19-and-pregnant-xhq5OhB
dir: hitomi_downloaded_xhamster
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1724743058.007604 (24-08-27 07:17:38 UTC) - 41s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}
admin: True
res: 1080
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_xhamster\19세 임신 (23824223).mp4

[URLs]
[0001] LazyUrl(https://xhamster.com/videos/19-and-pregnant-xhq5OhB)    --->    https://video5.xhcdn.com/key=B-r18B5fw+83z49AMANINw,end=1724756400,limit=3/data=59.23.18.102-dvp/referer=force,.xhcdn.com,.xhamster.com/speed=0/023/824/223/1080p.h264.mp4    --->    https://video5.xhcdn.com/key=B-r18B5fw+83z49AMANINw,end=1724756400,limit=3/data=59.23.18.102-dvp/referer=force,.xhcdn.com,.xhamster.com/speed=0/023/824/223/1080p.h264.mp4

[Messages]
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

### reset size ###
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader_v3", line 152, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

### reset size ###
use just download: overwrite=False

Fail : \\?\E:\다운로드\hitomi_downloader_GUI (1)\hitomi_downloaded_xhamster\19세 임신 (23824223).mp4
Traceback (most recent call last):
 File "downloader", line 1131, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1168, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1176, in download
Exception: https://video5.xhcdn.com/key=B-r18B5fw+83z49AMANINw,end=1724756400,limit=3/data=59.23.18.102-dvp/referer=force,.xhcdn.com,.xhamster.com/speed=0/023/824/223/1080p.h264.mp4
Traceback (most recent call last):
 File "downloader", line 1131, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1168, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

retry (1)

Fail : \\?\E:\다운로드\hitomi_downloader_GUI (1)\hitomi_downloaded_xhamster\19세 임신 (23824223).mp4
Traceback (most recent call last):
 File "downloader", line 1131, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1168, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1176, in download
Exception: https://video5.xhcdn.com/key=B-r18B5fw+83z49AMANINw,end=1724756400,limit=3/data=59.23.18.102-dvp/referer=force,.xhcdn.com,.xhamster.com/speed=0/023/824/223/1080p.h264.mp4
Traceback (most recent call last):
 File "downloader", line 1131, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1168, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

retry (2)

Fail : \\?\E:\다운로드\hitomi_downloader_GUI (1)\hitomi_downloaded_xhamster\19세 임신 (23824223).mp4
Traceback (most recent call last):
 File "downloader", line 1131, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1168, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1176, in download
Exception: https://video5.xhcdn.com/key=B-r18B5fw+83z49AMANINw,end=1724756400,limit=3/data=59.23.18.102-dvp/referer=force,.xhcdn.com,.xhamster.com/speed=0/023/824/223/1080p.h264.mp4
Traceback (most recent call last):
 File "downloader", line 1131, in download
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 1168, in download
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 725, in send
 File "requests\sessions", line 725, in <listcomp>
 File "requests\sessions", line 266, in resolve_redirects
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip358363419.ahcdn.com', port=443): Max retries exceeded with url: /key=X6c+yv3UjcY0VxR0qzLYAQ,s=,end=1724756400,limit=3/data=59.23.18.102-dvp/state=Zs16OxcS/referer=force,.xhcdn.com,.xhamster.com/reftag=078545629/ssd1/21/3/329889223/023/824/223/1080p.h264.mp4 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

stop
valid=False 1 (0, hitomi_downloaded_xhamster\19세 임신 (23824223).mp4)
-show_streams -print_format json -v error "19세 임신 (23824223).mp4"
{

}
19세 임신 (23824223).mp4: Invalid argument
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2026, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://xhamster.com/videos/19-and-pregnant-xhq5OhB  (38.3s)

크롬에서는 재생 누르면 광고 뜨고 영상 넘어가지는데

히토미 다운로더 내장 브라우저에서 키면 광고뜨는 부분에서 광고가 안뜨고 Source error 메세지가 뜨고 안넘어가네요

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
