### ISSUE TITLE
deviant

### ISSUE THREAD

**Issue by tenjouina** [KurtBestor/Hitomi-Downloader#7464]
Domoroboro (deviant_domoroboro)

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ja_jp
order / group / uid: 5 / False / 7e41d904853944babc21664f2ed5ab44
input: https://domoroboro.deviantart.com
type: deviant
single: False
url: https://domoroboro.deviantart.com
dir: hitomi_downloaded_deviant\Domoroboro (deviant_domoroboro)
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1725009206.7331986 (24-08-30 09:13:26 UTC) - 24717s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Part-15-Censored-for-the-Public-1092118421):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Part-15-Uncensored-for-Subs-1092118531):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-in-the-Shower-Sub-Exclusive-2-1092118649):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-in-the-Shower-Sub-Exclusive-1-1092118626):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Part-14-Censored-1091316820):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Part-14-Uncensored-for-Subs-1091316907):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Teachers-pet-Exclusive-4-1089062239):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Exclusive-Tangent-016-1084987636):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/WIP-Your-Goth-Personal-Assistant-1090240186):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Capture-and-Corrupt-Morgana-Release-Promo-1-1090237991):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Teachers-pet-Exclusive-2-1089062187):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Teachers-pet-Exclusive-3-1089062168):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Part-11-Censored-1089061928):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

File error (https://www.deviantart.com/domoroboro/art/Kim-and-Coffee-Part-11-Uncensored-for-Subs-1089061886):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

**Comment by tenjouina** [comment]
founderman (deviant_founderman)

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ja_jp
order / group / uid: 4 / False / 9ebb2113cb544e87b13e29690bd7abc5
input: https://founderman.deviantart.com
type: deviant
single: False
url: https://founderman.deviantart.com
dir: hitomi_downloaded_deviant\founderman (deviant_founderman)
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1724992678.335203 (24-08-30 04:37:58 UTC) - 41351s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

File error (https://www.deviantart.com/founderman/art/Drakken-s-New-Girl-3-Redux-Kim-Possible-Hypno-1091953403):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/Drakken-s-New-Girl-2-Redux-Kim-Possible-Hypno-1091948347):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/Drakken-s-New-Girl-1-Redux-Kim-Possible-Hypno-1091947031):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/Draft-Picks-1-Pokemon-Hypno-1090533313):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/Helen-Parr-Serves-Stu-Por-Remastered-5-1087281286):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/The-Complete-Experience-1-1086261682):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/In-His-Name-2-1085638167):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/In-His-Name-1-1085600985):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired


File error (https://www.deviantart.com/founderman/art/Our-Neighbor-The-Slaver-2-1085504934):
Traceback (most recent call last):
 File "hitomi_downloader", line 324, in run
 File "utils", line 4809, in ready
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\deviant_downloader", line 101, in get
extractor.deviant_downloader.LoginRequired

**Comment by tenjouina** [comment]
全部載せたらとんでもない量になるので一部抜粋してます
どうもこのサイトでやると処理が重いというか他のサイトに比べて遅い感じがします
