### ISSUE TITLE
Downloading from Twitter has stopped working

### ISSUE THREAD

**Issue by Stepan66650** [KurtBestor/Hitomi-Downloader#7483]
Hello, I recently downloaded images from Twitter and when I opened too many download lines, it no longer downloads and immediately gives an error.

Even deleting and installing it back does not help.

Invalid: [twitter] https://x.com/deko_morii

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ru_ru
order / group / uid: 0 / False / 2334e623b9ed4de3b1423b59bba5a98e
input: https://x.com/deko_morii
type: twitter
single: False
url: https://x.com/deko_morii
dir:
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1725787644.159665 (24-09-08 09:27:24 UTC) - 19s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
format: None
type: user
!!! get guest_token
!!! get guest_token
!!! get guest_token
!!! get guest_token
HTTPSConnectionPool(host='api.x.com', port=443): Max retries exceeded with url: /1.1/guest/activate.json (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))
stop
Traceback (most recent call last):
File "urllib3\connectionpool", line 670, in urlopen
File "urllib3\connectionpool", line 381, in _make_request
File "urllib3\connectionpool", line 978, in validate_conn
File "urllib3\connection", line 362, in connect
File "urllib3\util\ssl", line 386, in ssl_wrap_socket
File "ssl", line 500, in wrap_socket
File "ssl", line 1040, in _create
File "decorator", line 232, in fun
File "locker", line 123, in _wrapper
File "locker", line 56, in exec
File "locker", line 37, in run
File "locker", line 123, in
File "downloader", line 102, in do_handshake
File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "requests\adapters", line 486, in send
File "urllib3\connectionpool", line 726, in urlopen
File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.x.com', port=443): Max retries exceeded with url: /1.1/guest/activate.json (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1395, in start
File "utils", line 1474, in start_
File "C:\Users\serge\AppData\Local\Temp_MEI428082\ytdl_05655ae4\yt_dlp\yt_dlp\twitter_downloader", line 119, in read
self.artist, self.username = get_artist_username(self.url, self.session, self.cw)
File "decorator", line 232, in fun
File "constants", line 942, in try_
File "constants", line 911, in try_
File "C:\Users\serge\AppData\Local\Temp_MEI428082\ytdl_05655ae4\yt_dlp\yt_dlp\twitter_downloader", line 1123, in get_artist_username
raise e
File "C:\Users\serge\AppData\Local\Temp_MEI428082\ytdl_05655ae4\yt_dlp\yt_dlp\twitter_downloader", line 1118, in get_artist_username
data = TwitterAPI(session, cw).user_by_screen_name(username)
File "C:\Users\serge\AppData\Local\Temp_MEI428082\ytdl_05655ae4\yt_dlp\yt_dlp\twitter_downloader", line 208, in init
guest_token = _guest_token(session, self.headers, cache=cache_guest_token, cw=cw)
File "decorator", line 232, in fun
File "locker", line 64, in _wrapper
File "C:\Users\serge\AppData\Local\Temp_MEI428082\ytdl_05655ae4\yt_dlp\yt_dlp\twitter_downloader", line 177, in _guest_token
r = session.post(f'https://api.{domain}/1.1/guest/activate.json', headers=headers)
File "requests\sessions", line 637, in post
File "utils", line 996, in request
File "downloader", line 249, in session_request
File "requests\sessions", line 589, in request
File "requests\sessions", line 703, in send
File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.x.com', port=443): Max retries exceeded with url: /1.1/guest/activate.json (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://x.com/deko_morii (2.2s)

**Comment by Stepan66650** [comment]
The site is outgrowing its work joyreactor.cc although I used to work
