### ISSUE TITLE
치지직 다시보기 영상 다운로드 오류 현상이 있습니다

### ISSUE THREAD

**Issue by s1Iver** [KurtBestor/Hitomi-Downloader#7493]
Invalid: [chzzk] https://chzzk.naver.com/video/3472916

version: 4.1+ (24-09-14 13:29:11 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 1 / False / b1445992b1fa4866a266a7ec891c3e0e
input: https://chzzk.naver.com/video/3472916
type: chzzk
single: True
url: https://chzzk.naver.com/video/3472916
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1726431350.364977 (24-09-15 20:15:50 UTC) - 55s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
adult: False
adult_status: None
adult: False
adult_status: None
404 Client Error: Not Found for url: https://apis.naver.com/neonplayer/vodplay/v2/playback/1CAB2B5D9991908695575D651EEABC0C1E30?key=V121b2febd689045a38c64942abb4ce7e033693478c428a6d3e201702d822b6fd40874942abb4ce7e0336&sid=2099&env=real&lc=ko&cpl=ko
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1398, in start
 File "utils", line 1488, in start_
 File "extractor\chzzk_downloader", line 88, in read
 File "utils", line 4876, in ready
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\chzzk_downloader", line 178, in get
 File "downloader", line 364, in read_soup
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://apis.naver.com/neonplayer/vodplay/v2/playback/1CAB2B5D9991908695575D651EEABC0C1E30?key=V121b2febd689045a38c64942abb4ce7e033693478c428a6d3e201702d822b6fd40874942abb4ce7e0336&sid=2099&env=real&lc=ko&cpl=ko

Invalid: fail=True
EOT: https://chzzk.naver.com/video/3472916  (0.5s)

Invalid: [chzzk] https://chzzk.naver.com/video/3471282

version: 4.1+ (24-09-14 13:29:11 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / c2223e9cf3454ef2ac01cd99988e8ce9
input: https://chzzk.naver.com/video/3471282
type: chzzk
single: True
url: https://chzzk.naver.com/video/3471282
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1726431355.9359567 (24-09-15 20:15:55 UTC) - 67s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
adult: True
adult_status: ADULT
adult: True
adult_status: ADULT
404 Client Error: Not Found for url: https://apis.naver.com/neonplayer/vodplay/v2/playback/139DCF814DBA6A7801E48D9CA57AA1F99699?key=V123598219c8f7f760e499d6a553fbf3dd2bf30fdc76f996cd3bce15673d6cb2679c39d6a553fbf3dd2bf&sid=2099&env=real&lc=ko&cpl=ko
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1398, in start
 File "utils", line 1488, in start_
 File "extractor\chzzk_downloader", line 88, in read
 File "utils", line 4876, in ready
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\chzzk_downloader", line 178, in get
 File "downloader", line 364, in read_soup
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://apis.naver.com/neonplayer/vodplay/v2/playback/139DCF814DBA6A7801E48D9CA57AA1F99699?key=V123598219c8f7f760e499d6a553fbf3dd2bf30fdc76f996cd3bce15673d6cb2679c39d6a553fbf3dd2bf&sid=2099&env=real&lc=ko&cpl=ko

Invalid: fail=True
EOT: https://chzzk.naver.com/video/3471282  (0.2s)

오류 현상들은 위와 같이 글 작성 시간 기준 다시보기 업로드가 된 지 각각 50분, 3시간째인 영상에서 발생하며, 모두 9시간 길이의 긴 영상

정작 아래 링크의 영상들 중 하나는 길이가 12시간이지만 글 작성 시간 기준으로 22ㅅ간이 흘렀고, 하나는 3시간이 지났지만 길이가 4시간 정도의 영상으로, 정상적으로 다운로드 되는 것을 확인해 오류 현상들이 최근 업로드된 영상이며 길이가 긴 영상에서 발생하고 있습니다. 
https://chzzk.naver.com/video/3460313
https://chzzk.naver.com/video/3471045

**Comment by s1Iver** [comment]
#7137 으로는 해결되지 않고 있습니다
