### ISSUE TITLE
download youtube have issue:Sign in to confirm you’re not a bot. 

### ISSUE THREAD

**Issue by hakula007** [KurtBestor/Hitomi-Downloader#7507]
the error log is below, how to fix it?
errors.LoginRequired: [youtube] toK9rcrRzlk: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by hakula007** [comment]
errors.LoginRequired: [youtube] ROEaPaSSQRc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more


File error (https://www.youtube.com/watch?v=ROEaPaSSQRc):
Traceback (most recent call last):
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\YoutubeDL", line 1626, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\YoutubeDL", line 1761, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\extractor\common", line 740, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\extractor\youtube", line 4358, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\extractor\common", line 1263, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] ROEaPaSSQRc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 316, in run
 File "utils", line 4873, in ready
 File "extractor\youtube_downloader", line 75, in get
 File "extractor\youtube_downloader", line 54, in yt
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 646, in __init__
 File "ytdl", line 509, in extract_info
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\YoutubeDL", line 1615, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\zhf\AppData\Local\Temp\_MEI76322\ytdl_b54e71aa\yt_dlp\yt_dlp\YoutubeDL", line 1644, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 429, in report_error
 File "ytdl", line 425, in login_required
errors.LoginRequired: [youtube] ROEaPaSSQRc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by hakula007** [comment]
I already login youtube in inner brower, anyone have this issue?

**Comment by joyfullinmm** [comment]
The same problem. It just came recently and seemingly Google rolled out a new policy. Does it mean the end of command line yt-dlp?
