### ISSUE TITLE
유튜브 영상이 다운로드는 되는데, 정상적으로 재생되지 않습니다.

### ISSUE THREAD

**Issue by 23222322** [KurtBestor/Hitomi-Downloader#7508]
정확히는 다운로드는 되는데, 노란색(불완전한 작업)으로 나오고,
다운로드된 유튜브 폴더를 보면 mp4(화상만 있음) 파일과 weba(아마 음성 파일 같은데 재생이 안됩니다)로 나눠져 있는 것 같습니다.
![t2](https://github.com/user-attachments/assets/4c69782e-d063-4806-8c99-52289260701c)

히토미 다운로더 내의 목록에서 영상 좌클릭을 통해 재생하려고 하면 파일이 없습니다! 라고 나옵니다.
![t1](https://github.com/user-attachments/assets/68e5cc1a-bd50-49ac-94ab-3cff22fb3526)

대부분의 영상은 아무 문제 없이 다운로드 됩니다.
올해 6월 30일(당시 최신 버전)에 440여 개중 10개만 다운로드를 실패했었고, 지금 4.1 최신버전으로 다시 해보니 3개는 성공했습니다.

바로 밑은 실패한 유튜브 링크들입니다.
https://www.youtube.com/watch?v=kZelEwN8IWo
https://www.youtube.com/watch?v=e3jyIKI-SW0
https://www.youtube.com/watch?v=fejXRpHkZdU
https://www.youtube.com/watch?v=lpyIDooS6xo
https://www.youtube.com/watch?v=wM3VOakN7mA
https://www.youtube.com/watch?v=dXY7xmK_FJY
https://www.youtube.com/watch?v=dU1MhaDMeNQ

아래는 다시 해보니 성공한 링크들입니다.
https://www.youtube.com/watch?v=Q7wf3xEXCNo
https://www.youtube.com/watch?v=S4IwLbi4wq4
https://www.youtube.com/watch?v=MHjmbJj1l7A

아래는 실패한 작업 중 하나의 작업 정보입니다.
[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA)

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 3 / False / 3fe45a03f6bb4446a77e6078991f4956
input: https://www.youtube.com/watch?v=wM3VOakN7mA
type: youtube
single: True
url: https://www.youtube.com/watch?v=wM3VOakN7mA
dir: hitomi_downloaded_youtube
zip: 
artist: 옥냥이 RoofTopCAT
valid / done: False / True
range / range_p: None / None
time: 1726921673.9840906 (24-09-21 12:27:53 UTC) - 530s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: {'format': 'mp4', 'res': 4320, 'abr': 320}
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
goodbyedpi: False
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_youtube\[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4

[URLs]
[0001] Video(https://www.youtube.com/watch?v=wM3VOakN7mA)    --->    Dash_stream(https://manifest.googlevideo.com/api/manifest/dash/expire/1726943285/ei/1bvuZt22Ko-R7OsP8rfxuQU/ip/39.124.107.13/id/c0cdd539a90dee60/source/youtube/requiressl/yes/xpc/EgVo2aDSNQ==/playback_host/rr7---sn-n3cgv5qc5oq-20ns.googlevideo.com/mh/8R/mm/31,29/mn/sn-n3cgv5qc5oq-20ns,sn-n3cgv5qc5oq-bh2lr/ms/au,rdu/mv/m/mvi/7/pl/24/tx/51273605/txs/51273600,51273601,51273602,51273603,51273604,51273605/hfr/all/as/fmp4_audio_clear,webm_audio_clear,webm2_audio_clear,fmp4_sd_hd_clear,webm2_sd_hd_clear/initcwndbps/1423750/spc/54MbxWb0LyzIvALQke9B8DhmLI_elJhrFD10rU8pdl7HBxn5EpUV/vprv/1/rqh/2/mt/1726921261/fvip/7/keepalive/yes/itag/0/sparams/expire,ei,ip,id,source,requiressl,xpc,tx,txs,hfr,as,spc,vprv,rqh,itag/sig/AJfQdSswRQIhALcEzt6Q7juZZHDlM4asIm8HBPxvlsCoau79metm6diYAiBJQvKlFVgxMScbPXw3gEib80Q9H-tUHGApr47pz4BlQA==/lsparams/playback_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/ABPmVW0wRgIhAKFi8njZUx-DlaqJG_5JjQgeoaV0LEqxwp0BkA0Xj9aQAiEAgcwxY3kNMEJh27k9zWIXXJIXu7vG9RWctZ72GVIkuvU=)

[Messages]
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x00000264187199D0>, 'user_agent': 'Mozilla/5.0 (Microsoft Windows NT 6.2.9200.0); rv:22.0) Gecko/20130405 Firefox/22.0', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.19 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Lazy loading extractors is disabled
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1830 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=wM3VOakN7mA
[ytdl] [youtube] wM3VOakN7mA: Downloading webpage
[ytdl] [youtube] wM3VOakN7mA: Downloading ios player API JSON
[ytdl] [youtube] wM3VOakN7mA: Downloading web creator player API JSON
[ytdl] [youtube] wM3VOakN7mA: Downloading player a9d81eca
[ytdl] [debug] [youtube] Decrypted nsig zs8eh7min52mz9n5C => 6c8DtgyZkn2Zew
[ytdl] [debug] [youtube] Decrypted nsig a_cJoMo_1Oah-CJ_4 => 21iGiiQKUg4UsQ
[ytdl] [youtube] wM3VOakN7mA: Downloading m3u8 information
[ytdl] [youtube] wM3VOakN7mA: Downloading MPD manifest
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
live: not_live
[27p][1.1494252873563218fps][None][None] mhtml [None / None] ─ sb2 - 48x27 (storyboard)
[45p][1.0229885057471264fps][None][None] mhtml [None / None] ─ sb1 - 80x45 (storyboard)
[90p][1.0229885057471264fps][None][None] mhtml [None / None] ─ sb0 - 160x90 (storyboard)
[None][0fps][48.615kbps][48.615] m4a [None / mp4a.40.5] ─ 139-dash - audio only (DASH audio, WEB-C)
[None][0fps][51.604kbps][51.604] webm [None / opus] ─ 249-dash - audio only (DASH audio, WEB-C)
[None][0fps][69.944kbps][69.944] webm [None / opus] ─ 250-dash - audio only (DASH audio, WEB-C)
[None][0fps][47.656kbps][47.656] m4a [None / mp4a.40.5] ─ 139 - audio only (low, IOS)
[None][0fps][50.766kbps][50.766] webm [None / opus] ─ 249 - audio only (low, WEB-C)
[None][0fps][63.976kbps][63.976] webm [None / opus] ─ 250 - audio only (low, WEB-C)
[None][0fps][127.778kbps][127.778] m4a [None / mp4a.40.2] ─ 140-dash - audio only (DASH audio, WEB-C)
[None][0fps][126.165kbps][126.165] webm [None / opus] ─ 251-dash - audio only (DASH audio, WEB-C)
[None][0fps][127.12kbps][127.12] m4a [None / mp4a.40.2] ─ 140 - audio only (medium, IOS)
[None][0fps][116.774kbps][116.774] webm [None / opus] ─ 251 - audio only (medium, WEB-C)
[144p][30fps][None][108.0] mp4 [avc1.4d400b / None] ─ 160 - 256x144 (DASH video, WEB-C)
[144p][30fps][None][95.0] webm [vp9 / None] ─ 278 - 256x144 (DASH video, WEB-C)
[240p][30fps][None][242.0] mp4 [avc1.4d400c / None] ─ 133 - 426x240 (DASH video, WEB-C)
[240p][30fps][None][220.5] webm [vp9 / None] ─ 242 - 426x240 (DASH video, WEB-C)
[360p][30fps][None][224.535] mp4 [avc1.4d401e / None] ─ 134-dash - 640x360 (DASH video, WEB-C)
[360p][30fps][None][141.776] mp4 [avc1.4D401E / None] ─ 134 - 640x360 (360p, IOS)
[360p][30fps][96.0kbps(fixed)][268.357] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p, WEB-C)
[360p][30fps][None][405.72] webm [vp9 / None] ─ 243 - 640x360 (DASH video, WEB-C)
[480p][30fps][None][1155.0] mp4 [avc1.4d4014 / None] ─ 135 - 854x480 (DASH video, WEB-C)
[480p][30fps][None][752.64] webm [vp9 / None] ─ 244 - 854x480 (DASH video, WEB-C)
[720p][30fps][None][2310.0] mp4 [avc1.4d4014 / None] ─ 136 - 1280x720 (DASH video, WEB-C)
[720p][30fps][None][1505.28] webm [vp9 / None] ─ 247 - 1280x720 (DASH video, WEB-C)
[720p][60fps][None][1781.647] mp4 [avc1.4d4020 / None] ─ 298-dash - 1280x720 (DASH video, WEB-C)
[720p][60fps][None][1039.075] mp4 [avc1.4D4020 / None] ─ 298 - 1280x720 (720p60, IOS)
[720p][60fps][None][2646.0] webm [vp9 / None] ─ 302 - 1280x720 (DASH video, WEB-C)

utime: 1475712000.0

# stream_final
[720p][60fps][None][1781.647] mp4 [avc1.4d4020 / None] ─ 298-dash - 1280x720 (DASH video, WEB-C)

[27p][1.1494252873563218fps][None][None] mhtml [None / None] ─ sb2 - 48x27 (storyboard)
[45p][1.0229885057471264fps][None][None] mhtml [None / None] ─ sb1 - 80x45 (storyboard)
[90p][1.0229885057471264fps][None][None] mhtml [None / None] ─ sb0 - 160x90 (storyboard)
[None][0fps][48.615kbps][48.615] m4a [None / mp4a.40.5] ─ 139-dash - audio only (DASH audio, WEB-C)
[None][0fps][51.604kbps][51.604] webm [None / opus] ─ 249-dash - audio only (DASH audio, WEB-C)
[None][0fps][69.944kbps][69.944] webm [None / opus] ─ 250-dash - audio only (DASH audio, WEB-C)
[None][0fps][47.656kbps][47.656] m4a [None / mp4a.40.5] ─ 139 - audio only (low, IOS)
[None][0fps][50.766kbps][50.766] webm [None / opus] ─ 249 - audio only (low, WEB-C)
[None][0fps][63.976kbps][63.976] webm [None / opus] ─ 250 - audio only (low, WEB-C)
[None][0fps][127.778kbps][127.778] m4a [None / mp4a.40.2] ─ 140-dash - audio only (DASH audio, WEB-C)
[None][0fps][126.165kbps][126.165] webm [None / opus] ─ 251-dash - audio only (DASH audio, WEB-C)
[None][0fps][127.12kbps][127.12] m4a [None / mp4a.40.2] ─ 140 - audio only (medium, IOS)
[None][0fps][116.774kbps][116.774] webm [None / opus] ─ 251 - audio only (medium, WEB-C)
[360p][30fps][96.0kbps(fixed)][268.357] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p, WEB-C)

[None][0fps][48.615kbps][48.615] m4a [None / mp4a.40.5] ─ 139-dash - audio only (DASH audio, WEB-C)
[None][0fps][47.656kbps][47.656] m4a [None / mp4a.40.5] ─ 139 - audio only (low, IOS)
[None][0fps][127.778kbps][127.778] m4a [None / mp4a.40.2] ─ 140-dash - audio only (DASH audio, WEB-C)
[None][0fps][127.12kbps][127.12] m4a [None / mp4a.40.2] ─ 140 - audio only (medium, IOS)
[360p][30fps][96.0kbps(fixed)][268.357] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p, WEB-C)

streams_all: 28, streams: 5, streams_good: 5
[None][0fps][48.615kbps][48.615] m4a [None / mp4a.40.5] ─ 139-dash - audio only (DASH audio, WEB-C)
[None][0fps][47.656kbps][47.656] m4a [None / mp4a.40.5] ─ 139 - audio only (low, IOS)
[None][0fps][127.778kbps][127.778] m4a [None / mp4a.40.2] ─ 140-dash - audio only (DASH audio, WEB-C)
[None][0fps][127.12kbps][127.12] m4a [None / mp4a.40.2] ─ 140 - audio only (medium, IOS)

[None][0fps][127.778kbps][127.778] m4a [None / mp4a.40.2] ─ 140-dash - audio only (DASH audio, WEB-C)

filename: [옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4
Resolution: 720p
Codec: avc1.4d4020 / None
Abr: None
Subtype: mp4
FPS: 60

Download audio: Dash_stream(https://manifest.googlevideo.com/api/manifest/dash/expire/1726943285/ei/1bvuZt22Ko-R7OsP8rfxuQU/ip/39.124.107.13/id/c0cdd539a90dee60/source/youtube/requiressl/yes/xpc/EgVo2aDSNQ==/playback_host/rr7---sn-n3cgv5qc5oq-20ns.googlevideo.com/mh/8R/mm/31,29/mn/sn-n3cgv5qc5oq-20ns,sn-n3cgv5qc5oq-bh2lr/ms/au,rdu/mv/m/mvi/7/pl/24/tx/51273605/txs/51273600,51273601,51273602,51273603,51273604,51273605/hfr/all/as/fmp4_audio_clear,webm_audio_clear,webm2_audio_clear,fmp4_sd_hd_clear,webm2_sd_hd_clear/initcwndbps/1423750/spc/54MbxWb0LyzIvALQke9B8DhmLI_elJhrFD10rU8pdl7HBxn5EpUV/vprv/1/rqh/2/mt/1726921261/fvip/7/keepalive/yes/itag/0/sparams/expire,ei,ip,id,source,requiressl,xpc,tx,txs,hfr,as,spc,vprv,rqh,itag/sig/AJfQdSswRQIhALcEzt6Q7juZZHDlM4asIm8HBPxvlsCoau79metm6diYAiBJQvKlFVgxMScbPXw3gEib80Q9H-tUHGApr47pz4BlQA==/lsparams/playback_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/ABPmVW0wRgIhAKFi8njZUx-DlaqJG_5JjQgeoaV0LEqxwp0BkA0Xj9aQAiEAgcwxY3kNMEJh27k9zWIXXJIXu7vG9RWctZ72GVIkuvU=)
use just download: overwrite=True
media: 0
audio done
### reset size ###
use just download: overwrite=True
media: 0
Convert: D:\zzzzzz\두루미\hitomi_downloaded_youtube\[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4
rename (1): C:\Users\SEOEUNHO\AppData\Local\Temp\53a23a485cdd4105ab757a235566604d_a.tmp -> D:\zzzzzz\두루미\hitomi_downloaded_youtube\tmp06ef1d0f634a4703b092762cc7746bf4_a.weba
rename (1): D:\zzzzzz\두루미\hitomi_downloaded_youtube\[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4 -> D:\zzzzzz\두루미\hitomi_downloaded_youtube\tmp06ef1d0f634a4703b092762cc7746bf4_v.mp4
-show_streams -print_format json -v error "tmp06ef1d0f634a4703b092762cc7746bf4_v.mp4"
transcode... D:\zzzzzz\두루미\hitomi_downloaded_youtube\ffmpeg_info_tmp_f3ebf55421204f508ba5b28915d9f441.mp4
rename (1): D:\zzzzzz\두루미\hitomi_downloaded_youtube\tmp853affaa6b3648ce97d933e29a48fa74_o.mp4 -> D:\zzzzzz\두루미\hitomi_downloaded_youtube\ffmpeg_info_tmp_f3ebf55421204f508ba5b28915d9f441.mp4
-show_streams -print_format json -v error "ffmpeg_info_tmp_f3ebf55421204f508ba5b28915d9f441.mp4"
-show_streams -print_format json -v error "tmp06ef1d0f634a4703b092762cc7746bf4_a.weba"
transcode... D:\zzzzzz\두루미\hitomi_downloaded_youtube\ffmpeg_info_tmp_821c3aa33005453490c65f9a6a9dbe34.weba
Traceback (most recent call last):
 File "ffmpeg", line 936, in get_info
 File "ffmpeg", line 384, in convert
 File "ffmpeg", line 372, in convert
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "ffmpeg", line 936, in get_info
 File "ffmpeg", line 384, in convert
 File "ffmpeg", line 372, in convert
Exception: Failed to convert; exit code: 1

Lazyurl pp Error: \\?\D:\zzzzzz\두루미\hitomi_downloaded_youtube\[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 478, in run
 File "hitomi_downloader", line 471, in pp_
 File "C:\Users\SEOEUNHO\AppData\Local\Temp\_MEI18362\ytdl_f45e2881\yt_dlp\yt_dlp\youtube_downloader", line 338, in pp
   ext, out = ffmpeg.merge(filename, self.audio_path, cw=cw, vcodec=self.vcodec)
 File "ffmpeg", line 300, in merge
 File "ffmpeg", line 946, in get_info
 File "ffmpeg", line 936, in get_info
 File "ffmpeg", line 384, in convert
 File "ffmpeg", line 372, in convert
Exception: Failed to convert; exit code: 1

utime Error: \\?\D:\zzzzzz\두루미\hitomi_downloaded_youtube\[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 520, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\D:\\zzzzzz\\두루미\\hitomi_downloaded_youtube\\[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4'

stop
-show_streams -print_format json -v error "[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4"
{

}
[옥냥이 일상] 버디버디, 세이클럽 아세요？ (RoofTopCAT Luxury Life) (wM3VOakN7mA).mp4: Invalid argument
Traceback (most recent call last):
 File "ffmpeg", line 883, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2008, in finish
 File "ffmpeg", line 886, in get_info
 File "ffmpeg", line 883, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://www.youtube.com/watch?v=wM3VOakN7mA  (39.8s)

**Comment by Rsfinder** [comment]
same for me
Recently, most channel saves generate a tmp~ file😞

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 23222322** [comment]
정상적으로 다운로드 됩니다 ! 4.1 버전의 성공한 파일과 아주 근소한 용량 차이가 있네요 ! 어떻게 한거에요? 너무 신기합니다..! 당신은 신이야..♥ 감사합니다.
