### ISSUE TITLE
rule34video can't download

### ISSUE THREAD

**Issue by jzl543098871** [KurtBestor/Hitomi-Downloader#7524]
I have loaded rule34video_downloader（https://github.com/rickmiron/variado/blob/main/rule34video_downloader.py） and rule34video_downloaderW（https://github.com/rickmiron/variado/blob/main/rule34video_downloaderW.py） both doesn't work
my python version == 3.10.10
utils == 1.0.2
requests == 2.32.3

here is the info panel

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en
order / group / uid: -3 / False / 947b4530c145431d88b48981b2e6bb1e
input: https://rule34video.com/models/japs8005/
type: rule34video
single: False
url: https://rule34video.com/models/japs8005/
dir: hitomi_downloaded_rule34video\Artist]Japs8005
zip:
artist: None
valid / done: False / False
range / range_p: None / None
time: 1727621184.1293309 (24-09-29 14:46:24 UTC) - 21s elapsed
tags: []
lock: False
color: downloading
paused: False
format: None
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': False}
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.08.06
pinned: False
extras: {}
live: False
changed: True

[Messages]
1.09w
Japs8005
getx fin

File error (None):
Traceback (most recent call last):
File "hitomi_downloader", line 324, in run
File "utils", line 4809, in ready
File "dynamic_module_1", line 42, in get
File "requests\sessions", line 624, in head
File "downloader", line 249, in session_request
File "requests\sessions", line 575, in request
File "requests\sessions", line 486, in prepare_request
File "requests\models", line 368, in prepare
File "requests\models", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

**Comment by Summertoohot** [comment]
해당 파이썬 스크립트는 개발자님이 만든 게 아니므로 삭제하시고 프로그램을 실행하여 기본 내장된 스크립트로 작동되게 해보세요

**Comment by jzl543098871** [comment]
> 해당 파이썬 스크립트는 개발자님이 만든 게 아니므로 삭제하시고 프로그램을 실행하여 기본 내장된 스크립트로 작동되게 해보세요


I'm pretty sure that  I opened the hitomi_downloader_GUI and  loaded the Python script in the toolbar（both two）

**Comment by Handstandg** [comment]
> > 해당 파이썬 스크립트는 개발자님이 만든 게 아니므로 삭제하시고 프로그램을 실행하여 기본 내장된 스크립트로 작동되게 해보세요
> 
> I'm pretty sure that I opened the hitomi_downloader_GUI and loaded the Python script in the toolbar（both two）

[https://github.com/rickmiron/variado/blob/main/rule34video_downloader.py]
[https://github.com/rickmiron/variado/blob/main/rule34video_downloaderW.py]

이 두 개의 파이썬 스크립트를 적용하지 마시고 그냥 기본 상태에서 다운을 받아보세요 
아무 것도 적용하지 않는다면 rule34video 의 영상들은 etc 스크립트가 처리해줄겁니다

그리고 rule34video는  https://rule34video.com/models/japs8005/ 이런 링크는 유효하지 않습니다
업로더나 아티스트, 태그 URL은 적용되지 않습니다.
다운을 받기 위해서는 
https://rule34video.com/video/3544400/pt-br-ntr-waiting-1-japs-8005/
https://rule34video.com/video/3539031/ntr-mom-swap/
이런식으로 각 동영상의 URL을 넣어야 합니다.

추가로 rule34video에 로그인 한 후에 쿠키를 추출하여 다운로더 프로그램에 쿠키를 적용해보세요.

**Comment by jzl543098871** [comment]
> > > 해당 파이썬 스크립트는 개발자님이 만든 게 아니므로 삭제하시고 프로그램을 실행하여 기본 내장된 스크립트로 작동되게 해보세요
> > 
> > 
> > I'm pretty sure that I opened the hitomi_downloader_GUI and loaded the Python script in the toolbar（both two）
> 
> [https://github.com/rickmiron/variado/blob/main/rule34video_downloader.py] [https://github.com/rickmiron/variado/blob/main/rule34video_downloaderW.py]
> 
> 이 두 개의 파이썬 스크립트를 적용하지 마시고 그냥 기본 상태에서 다운을 받아보세요 아무 것도 적용하지 않는다면 rule34video 의 영상들은 etc 스크립트가 처리해줄겁니다
> 
> 그리고 rule34video는 https://rule34video.com/models/japs8005/ 이런 링크는 유효하지 않습니다 업로더나 아티스트, 태그 URL은 적용되지 않습니다. 다운을 받기 위해서는 https://rule34video.com/video/3544400/pt-br-ntr-waiting-1-japs-8005/ https://rule34video.com/video/3539031/ntr-mom-swap/ 이런식으로 각 동영상의 URL을 넣어야 합니다. (해당 동영상 링크들은 japs8005의 영상입니다.)
> 
> 추가로 rule34video에 로그인 한 후에 쿠키를 추출하여 다운로더 프로그램에 쿠키를 적용해보세요.
> 
> 그래도 안 된다면
> 
> https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> 프로그램을 최신 베타버전으로 받아보세요

Thank you for your explanation.I thought this program could traverse all the author's works and download them like YT-DLP
