### ISSUE TITLE
Nico nico broadcast issue 

### ISSUE THREAD

**Issue by NagsWH** [KurtBestor/Hitomi-Downloader#7533]
![image](https://github.com/user-attachments/assets/8a76331b-c708-4018-a810-53dd996749eb)
As the title says, download don't work anymore

**Comment by NagsWH** [comment]
Restart in 17s: Invalid: [nico] https://live.nicovideo.jp/watch/lv345959811

version: 4.1+ (24-05-19 16:03:44 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / fr_fr
order / group / uid: 0 / False / 6464c3bb23cd4dfa8f039f86ba2aa3bc
input: https://live.nicovideo.jp/watch/lv345959811
type: nico
single: True
url: https://live.nicovideo.jp/watch/lv345959811
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1727959957.65438 (24-10-03 12:52:37 UTC) - 289s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1440
goodbyedpi: False
ytdl: yt_dlp 2024.09.27
pinned: False
extras: {}
live: True
changed: True


[File Names]



[URLs]



[Messages]
[ytdl] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000018BA0354F70>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib
[ytdl] [debug] Loaded 1838 extractors
[ytdl] [niconico:live] Extracting URL: https://live.nicovideo.jp/watch/lv345959811
[ytdl] [niconico:live] lv345959811: Downloading webpage
[ytdl] [niconico:live] lv345959811: Connecting to WebSocket server
[ytdl] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000018BAF017CD0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib
[ytdl] [debug] Loaded 1838 extractors
[ytdl] [niconico:live] Extracting URL: https://live.nicovideo.jp/watch/lv345959811
[ytdl] [niconico:live] lv345959811: Downloading webpage
[ytdl] [niconico:live] lv345959811: Connecting to WebSocket server
This request requires WebSocket support. Ensure one of the following dependencies are installed: websockets
stop
Traceback (most recent call last):
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 108, in send
   handler.validate(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\_helper", line 208, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 334, in validate
   self._validate(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 322, in _validate
   self._check_url_scheme(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 275, in _check_url_scheme
   raise UnsupportedRequest(f'Unsupported url scheme: "{scheme}"')
yt_dlp.networking.exceptions.UnsupportedRequest: Unsupported url scheme: "wss"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\nico_downloader", line 147, in read
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\nico_downloader", line 191, in get_video
 File "extractor\nico_downloader", line 180, in get_video
 File "ytdl", line 509, in extract_info
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1615, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1626, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1761, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\niconico", line 961, in _real_extract
   ws = self._request_webpage(
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\common", line 897, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
 File "ytdl", line 499, in urlopen
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 4187, in urlopen
   raise RequestError(
yt_dlp.networking.exceptions.RequestError: This request requires WebSocket support. Ensure one of the following dependencies are installed: websockets

Invalid: fail=True
quality: 100%
EOT: https://live.nicovideo.jp/watch/lv345959811  (5.2s)

[ytdl] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000018B9559C430>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib
[ytdl] [debug] Loaded 1838 extractors
[ytdl] [niconico:live] Extracting URL: https://live.nicovideo.jp/watch/lv345959811
[ytdl] [niconico:live] lv345959811: Downloading webpage
[ytdl] [niconico:live] lv345959811: Connecting to WebSocket server
[ytdl] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000018BA0085B80>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib
[ytdl] [debug] Loaded 1838 extractors
[ytdl] [niconico:live] Extracting URL: https://live.nicovideo.jp/watch/lv345959811
[ytdl] [niconico:live] lv345959811: Downloading webpage
[ytdl] [niconico:live] lv345959811: Connecting to WebSocket server
This request requires WebSocket support. Ensure one of the following dependencies are installed: websockets
stop
Traceback (most recent call last):
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 108, in send
   handler.validate(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\_helper", line 208, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 334, in validate
   self._validate(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 322, in _validate
   self._check_url_scheme(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 275, in _check_url_scheme
   raise UnsupportedRequest(f'Unsupported url scheme: "{scheme}"')
yt_dlp.networking.exceptions.UnsupportedRequest: Unsupported url scheme: "wss"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\nico_downloader", line 147, in read
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\nico_downloader", line 191, in get_video
 File "extractor\nico_downloader", line 180, in get_video
 File "ytdl", line 509, in extract_info
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1615, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1626, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1761, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\niconico", line 961, in _real_extract
   ws = self._request_webpage(
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\common", line 897, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
 File "ytdl", line 499, in urlopen
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 4187, in urlopen
   raise RequestError(
yt_dlp.networking.exceptions.RequestError: This request requires WebSocket support. Ensure one of the following dependencies are installed: websockets

Invalid: fail=True
quality: 100%
EOT: https://live.nicovideo.jp/watch/lv345959811  (4.9s)

[ytdl] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000018BA96DFDF0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib
[ytdl] [debug] Loaded 1838 extractors
[ytdl] [niconico:live] Extracting URL: https://live.nicovideo.jp/watch/lv345959811
[ytdl] [niconico:live] lv345959811: Downloading webpage
[ytdl] [niconico:live] lv345959811: Connecting to WebSocket server
[ytdl] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe) API
[ytdl] [debug] params: {'noplaylist': True, 'playlistend': 1, 'subtitlesformat': 'vtt', 'no_check_certificate': True, 'hls_use_mpegts': True, 'overwrites': True, 'nopart': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000018BBD5717C0>, 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-12.0
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib
[ytdl] [debug] Loaded 1838 extractors
[ytdl] [niconico:live] Extracting URL: https://live.nicovideo.jp/watch/lv345959811
[ytdl] [niconico:live] lv345959811: Downloading webpage
[ytdl] [niconico:live] lv345959811: Connecting to WebSocket server
This request requires WebSocket support. Ensure one of the following dependencies are installed: websockets
stop
Traceback (most recent call last):
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 108, in send
   handler.validate(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\_helper", line 208, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 334, in validate
   self._validate(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 322, in _validate
   self._check_url_scheme(request)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\networking\common", line 275, in _check_url_scheme
   raise UnsupportedRequest(f'Unsupported url scheme: "{scheme}"')
yt_dlp.networking.exceptions.UnsupportedRequest: Unsupported url scheme: "wss"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1485, in start_
 File "extractor\nico_downloader", line 147, in read
 File "decorator", line 232, in fun
 File "constants", line 940, in try_
 File "constants", line 909, in try_
 File "extractor\nico_downloader", line 191, in get_video
 File "extractor\nico_downloader", line 180, in get_video
 File "ytdl", line 509, in extract_info
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1615, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1626, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 1761, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\niconico", line 961, in _real_extract
   ws = self._request_webpage(
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\extractor\common", line 897, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
 File "ytdl", line 499, in urlopen
 File "C:\Users\Shine\AppData\Local\Temp\_MEI187642\ytdl_5138cdbc\yt_dlp\yt_dlp\YoutubeDL", line 4187, in urlopen
   raise RequestError(
yt_dlp.networking.exceptions.RequestError: This request requires WebSocket support. Ensure one of the following dependencies are installed: websockets

Invalid: fail=True
quality: 100%
EOT: https://live.nicovideo.jp/watch/lv345959811  (4.9s)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by NagsWH** [comment]
It's working thanks
