### ISSUE TITLE
인스타 아무것도 다운이 안됩니다

### ISSUE THREAD

**Issue by kkor0313** [KurtBestor/Hitomi-Downloader#7535]
인앱 브라우저에 로그인도 되어있고 쿠기를 바꿔봐도 다운되는 컨텐츠가 없습니다

Login required; Please login: Fail: Please wait a few minutes before you try again. {'shortcode': 'DAs60MWzSvl', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}
https://www.instagram.com/p/DAs60MWzSvl

version: 4.1+ (24-10-03 18:33:51 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / en_us
order / group / uid: 0 / False / 6ee72116bdff4e628dd63a62c6a5748e
input: https://www.instagram.com/p/DAs60MWzSvl
type: insta
single: False
url: https://www.instagram.com/p/DAs60MWzSvl
dir: 
zip: 
artist: 池田 穂乃花（ikeda honoka）
valid / done: False / True
range / range_p: None / None
time: 1728105823.2160928 (24-10-05 05:23:43 UTC) - 2245s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: False
ytdl: yt_dlp 2024.09.27
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no html
username: ikeda_honoka
single post
single
Fail: Please wait a few minutes before you try again. {'shortcode': 'DAs60MWzSvl', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}
Fail: Please wait a few minutes before you try again. {'shortcode': 'DAs60MWzSvl', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}
stop
Traceback (most recent call last):
 File "utils", line 1400, in start
 File "utils", line 1490, in start_
 File "extractor\insta_downloader", line 73, in read
 File "extractor\insta_downloader", line 474, in get_imgs_single
 File "extractor\insta_downloader", line 428, in __init__
 File "decorator", line 232, in fun
 File "constants", line 918, in try_
 File "constants", line 915, in try_
 File "extractor\insta_downloader", line 321, in get_query
 File "extractor\insta_downloader", line 578, in wtf
extractor.insta_downloader.LoginRequired: Fail: Please wait a few minutes before you try again. {'shortcode': 'DAs60MWzSvl', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}

Invalid: fail=False
EOT: https://www.instagram.com/p/DAs60MWzSvl  (1835.6s)

**Comment by Opti-mizing** [comment]
계정별 다운로드는 정상적으로 가능하고, 특정 게시글 단위로 다운로드 하는기능이 사이트변경 된거같아요
