### ISSUE TITLE
Hitomi Downloader hanime(help) 하니메 다운 안됨

### ISSUE THREAD

**Issue by hc0178** [KurtBestor/Hitomi-Downloader#7572]
하니메 다운 안됨

I updated Hitomi Downloader version to the latest version, but Hanime cannot be downloaded. I'm attaching the task information below. Is it not working because I didn't meet the download requirements?

[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1

version: 4.1+ (24-10-20 17:47:02 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 23 / False / a0c282871997430384bafb9354679356
input: https://hanime.tv/videos/hentai/iribitari-gal-ni-manko-tsukawasete-morau-hanashi-1
type: hanime
single: True
url: https://hanime.tv/videos/hentai/iribitari-gal-ni-manko-tsukawasete-morau-hanashi-1
dir: F:\HITOMI\hitomi_downloaded_hanime
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1729589253.0123513 (24-10-22 09:27:33 UTC) - 718s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1080
goodbyedpi: True
ytdl: yt_dlp 2024.09.27
pinned: False
extras: {}
live: True
changed: False

[File Names]
[0001] F:\HITOMI\hitomi_downloaded_hanime\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4

[URLs]
[0001] M3u8_stream(https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/rmps7jnr9vl84q8jpAqzbh1km3Zc833hqvq8jAyp29hppw1fll4k1.m3u8)

[Messages]
('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 410, in increment
 File "urllib3\packages\six", line 734, in reraise
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1400, in start
 File "utils", line 1490, in start_
 File "extractor\hanime_downloader", line 50, in read
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\hanime_downloader", line 64, in get_video
 File "downloader", line 459, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 998, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))

Invalid: fail=True
EOT: https://hanime.tv/videos/hentai/iribitari-gal-ni-manko-tsukawasete-morau-hanashi-1  (0.5s)

['m3u8', 720, 210, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/rmps7jnr9vl84q8jpAqzbh1km3Zc833hqvq8jAyp29hppw1fll4k1.m3u8']
['m3u8', 480, 104, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/hqx5d78qkvf71hmkrcv3kAw4w2Zz0dlp527r83pbdlflc27khyzbq.m3u8']
['m3u8', 360, 67, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/vzr8t032f78gA7Azlssdcly3n7Ztzsxsc5z1fj1m33gtw51d9b4gy.m3u8']
Final stream:
['m3u8', 720, 210, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/rmps7jnr9vl84q8jpAqzbh1km3Zc833hqvq8jAyp29hppw1fll4k1.m3u8']
media: 0
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0002.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0003.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0002.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0003.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0002.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\F:\HITOMI\hitomi_downloaded_hanime\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 510, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\F:\\HITOMI\\hitomi_downloaded_hanime\\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4'

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

stop
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2031, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: F:\HITOMI\hitomi_downloaded_hanime\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4
EOT: https://hanime.tv/videos/hentai/iribitari-gal-ni-manko-tsukawasete-morau-hanashi-1  (8.5s)

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

['m3u8', 720, 210, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/rmps7jnr9vl84q8jpAqzbh1km3Zc833hqvq8jAyp29hppw1fll4k1.m3u8']
['m3u8', 480, 104, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/hqx5d78qkvf71hmkrcv3kAw4w2Zz0dlp527r83pbdlflc27khyzbq.m3u8']
['m3u8', 360, 67, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/vzr8t032f78gA7Azlssdcly3n7Ztzsxsc5z1fj1m33gtw51d9b4gy.m3u8']
Final stream:
['m3u8', 720, 210, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/rmps7jnr9vl84q8jpAqzbh1km3Zc833hqvq8jAyp29hppw1fll4k1.m3u8']
media: 0
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0002.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0003.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0002.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0003.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0000.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0002.html' for reading
Opening 'https://s32.highwinds-cdn.com/3/2/5/2/h1x/segs/b0/2/0001.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\F:\HITOMI\hitomi_downloaded_hanime\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 510, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\F:\\HITOMI\\hitomi_downloaded_hanime\\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4'

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

stop
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2031, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: F:\HITOMI\hitomi_downloaded_hanime\[Seven] Iribitari Gal ni Manko Tsukawasete Morau Hanashi 1 (3252).mp4
EOT: https://hanime.tv/videos/hentai/iribitari-gal-ni-manko-tsukawasete-morau-hanashi-1  (8.5s)

**Comment by lilik007** [comment]
Has this error not been resolved yet?
I have the same problem.

**Comment by lilik007** [comment]
Hasn't it been fixed yet? I have the same problem
