### ISSUE TITLE
Exhentai download가 안됩니다.

### ISSUE THREAD

**Issue by hwatatom** [KurtBestor/Hitomi-Downloader#7577]
최근 파일이 문제인가 해서 8월 거를 다운로드 해도

전부 Invalid: [hitomi] 라고 뜨면서 다운이 안됩니다.

혹시 이 문제 해결하신 분 있으신가요?

v4.1 입니다

![image](https://github.com/user-attachments/assets/26e18ee3-54db-4c80-ae70-8b4b1947b03e)

**Comment by BewuwuBew** [comment]
동일한 문제를 겪고 있습니다.
도움이 될까 싶어 작성자 글에 추가로 오류 내역도 첨부합니다.
참고로 이헨 / 익헨 모두 쿠키를 다시 내보내고 불러와도 똑같습니다.

[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/3101340/29bc305b43/)
using custom cookies
#### https://e-hentai.org/g/3101340/29bc305b43    ---->    https://e-hentai.org/g/3101340/29bc305b43
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/3101340/29bc305b43

Read reader FAILED - auto
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 757, in read
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/3101340/29bc305b43

get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/3101340/29bc305b43/)
using custom cookies
#### https://exhentai.org/g/3101340/29bc305b43    ---->    https://exhentai.org/g/3101340/29bc305b43
Traceback (most recent call last):
 File "hitomi_downloader", line 747, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 189, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'attrs'

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://exhentai.org/g/3101340/29bc305b43/)
using custom cookies
#### https://e-hentai.org/g/3101340/29bc305b43    ---->    https://e-hentai.org/g/3101340/29bc305b43
get_imgs server: ehen
ehen_imgs(ex:True, url:https://exhentai.org/g/3101340/29bc305b43/)
using custom cookies
#### https://exhentai.org/g/3101340/29bc305b43    ---->    https://exhentai.org/g/3101340/29bc305b43
'NoneType' object has no attribute 'attrs'
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "hitomi_downloader", line 791, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 171, in ehen_imgs
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/3101340/29bc305b43

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "hitomi_downloader", line 793, in read
 File "hitomi_downloader", line 628, in get_imgs
 File "extractor\ehen_downloader", line 189, in ehen_imgs
AttributeError: 'NoneType' object has no attribute 'attrs'

Invalid: fail=True
EOT: https://exhentai.org/g/3101340/29bc305b43/  (16.4s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by BewuwuBew** [comment]
테스트해봤는데
이미지 다운속도가 많이 느리지만, 받아지지 않는 것들 모두 정상적으로 다운 완료되었습니다. 감사합니다.
