### ISSUE TITLE
av19 invalid 문제

### ISSUE THREAD

**Issue by sadfrog12** [KurtBestor/Hitomi-Downloader#7581]
어제까지는 av19플러그인을 통해 주소 수정으로 다운이 가능했는데 

오늘 확인 해 보니 해당 웹사이트에서 뭔가 바꼈는지 다운이 불가능하네요

혹시 뭐가 문제인지 아시는분 있으신가요??

Invalid: [av19a] https://av19a.com/korea/60804

version: 4.1+ (24-10-20 17:47:02 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / f52fa5e05bdd44afb46b9279ea0414bc
input: https://av19a.com/korea/60804
type: av19a
single: True
url: https://av19a.com/korea/60804
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1729989160.5817242 (24-10-27 00:32:40 UTC) - 15s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.09.27
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
No segs
stop
Traceback (most recent call last):
 File "utils", line 1400, in start
 File "utils", line 1490, in start_
 File "av19a", line 30, in read
 File "av19a", line 28, in read
 File "av19a", line 26, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 192, in __init__
Exception: No segs

Invalid: fail=True
EOT: https://av19a.com/korea/60804  (3.8s)

**Comment by Mentalistcode** [comment]
수정좀 해주세요 ...

**Comment by zsfoqzid** [comment]
> 답답해서 분석해보니, m3u8 스트리밍 주소를 crypto js로 암호화해뒀더라구요. 기존은 python기반 스크립트에서 해당 주소를 추출해오는 방식이었는데, 이제는 주소가 암호화되었기 때문에 복호화하는 작업을 추가로 해야합니다. 직접 스크립트에 AES 기반 복호화 클래스도 작성해봤는데, 다운로드 하나 걸어보니 프로그램 렉이 너무 심해서 도저히 진행이 되지않더군요. 스크립트에서 crypto같은 라이브러리를 사용할 수 있도록, 다음 버전의 hitomi downloader 프로그램에서 라이브러리를 내장해주세요...

혹시나 해서 로컬 환경에 pycrypto를 설치해봤지만, 역시나 플러그인의 스크립트에 작성한 from Crypto가 동작하지 않네요..

**Comment by Mentalistcode** [comment]
쉽지 않은건가보네요..
