### ISSUE TITLE
pixiv 로그인 시 화면이 이상하게 나옵니다.

### ISSUE THREAD

**Issue by nightow** [KurtBestor/Hitomi-Downloader#7596]
[
![스크린샷 2024-10-31 220502](https://github.com/user-attachments/assets/cc98751a-7760-40fb-aba6-a0950e33c001)
](url)

바쁘시겠지만, 확인 부탁드리겠습니다.

**Comment by nightow** [comment]
Traceback (most recent call last):
 File "utils", line 1387, in start
 File "extractor\pixiv_downloader", line 63, in init
extractor.pixiv_downloader.LoginRequired
