### ISSUE TITLE
When downloading instagram, it will get stuck in "Reading" and the download will not be executed.

### ISSUE THREAD

**Issue by leonard-lin-joker** [KurtBestor/Hitomi-Downloader#7605]
When downloading Instagram, it will always be stuck in "Reading" and will not download at all.
I have updated the cookies, and there is no Error log. The display screen is always stuck there.
No matter how long it is left, it will always show "Reading"
Because there is no Error log, I can't tell where the problem is.
![Hitomi Downloader Issue](https://github.com/user-attachments/assets/832a9f72-4786-49d4-8a58-914150e56e7a)

**Comment by socrading** [comment]
I think it's an issue with the Instagram site, they may have altered the link address.
I try the old ver, the issue same.

**Comment by leonard-lin-joker** [comment]
Yes, I have also tried to use the old version and it has this situation. I don’t know if there will be any updates in this regard.

**Comment by Houkannis** [comment]
I have the same issue. Reader can't find any regular Instagram posts. Reader can find Instagram stories but can't download them

**Comment by instaisntdownsoicome** [comment]
same issue
in android app, insmate etc program is working. but in hitomi in pc, it can't read url.
why instagram always block the benifit? requsest is pending is fuc issue.

**Comment by Orudeon** [comment]
Still happening today, I think it's just blocked from downloading from Instagram now

**Comment by mykeehu** [comment]
> I have the same issue. Reader can't find any regular Instagram posts. Reader can find Instagram stories but can't download them

Same here. It reads the stories, then just spins and won't start downloading.

**Comment by shaonan150** [comment]
same issue

**Comment by twitchingaround** [comment]
Same issue plus i used the get cookies extension as suggested. I exported the cookie from instagram and imported into hitomi. I get either a continuous "Reading" or a red error saying i need to login and upload cookies. Help!

**Comment by twitchingaround** [comment]
> Same issue plus i used the get cookies extension as suggested. I exported the cookie from instagram and imported into hitomi. I get either a continuous "Reading" or a red error saying i need to login and upload cookies. Help!

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / en_us
order / group / uid: 0 / False / 504dfc793e424bf1aeee3bdcd5af360b
input: https://www.instagram.com/gbrsgroup/reel/DBvoCpGR0ao
type: insta
single: False
url: https://www.instagram.com/gbrsgroup/reel/DBvoCpGR0ao
dir: 
zip: 
artist: GBRS GROUP
valid / done: False / True
range / range_p: None / None
time: 1731170111.086902 (24-11-09 16:35:11 UTC) - 12959s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: None None
pinned: False
extras: {}
live: False
changed: False


[File Names]



[URLs]



[Messages]
no html
no html
no html
no html
no html
no html
username: gbrsgroup
single post
single
Fail: Please wait a few minutes before you try again. {'shortcode': 'DBvoCpGR0ao', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}
Fail: Please wait a few minutes before you try again. {'shortcode': 'DBvoCpGR0ao', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\insta_downloader", line 68, in read
 File "extractor\insta_downloader", line 469, in get_imgs_single
 File "extractor\insta_downloader", line 423, in __init__
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 911, in try_
 File "extractor\insta_downloader", line 316, in get_query
 File "extractor\insta_downloader", line 573, in wtf
extractor.insta_downloader.LoginRequired: Fail: Please wait a few minutes before you try again. {'shortcode': 'DBvoCpGR0ao', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}

Invalid: fail=False
EOT: https://www.instagram.com/gbrsgroup/reel/DBvoCpGR0ao  (1862.4s)

**Comment by Kataphractoi** [comment]
I have the similar issue. it will be reading for hours on end but some will eventually fall back into "you need to login" which is weird because when I go to try to login, I'm still logged in. 

> extractor.insta_downloader.LoginRequired: Fail: Please wait a few minutes before you try again. {'shortcode': 'DBvoCpGR0ao', 'child_comment_count': 3, 'fetch_comment_count': 40, 'parent_comment_count': 24, 'has_threaded_comments': True}

this part from the previous reply is the same for me.

**Comment by Orudeon** [comment]
This tech preview manages to download things, but only videos download correctly. All images download in 240 x something dimensions (such as 240 x 300, 240 x 295, 240 x 160) rather than the original large version.

**Comment by NoBbHG** [comment]
> This tech preview manages to download things, but only videos download correctly. All images download in 240 x something dimensions (such as 240 x 300, 240 x 295, 240 x 160) rather than the original large version.这个技术预览版可以下载文件，但只有视频下载正常。所有图片下载后的尺寸都是 240 倍左右（例如 240 x 300、240 x 295、240 x 160），而不是原始的大尺寸版本。

As you said, the problem still exists.@KurtBestor
