### ISSUE TITLE
hanime 다운 불가

### ISSUE THREAD

**Issue by ryzaui** [KurtBestor/Hitomi-Downloader#7612]
[Mary Jane] Yuutousei Ayaka no Uraomote 2

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / d05d796a1a324538bc94ab4e2c875bd2
input: https://hanime.tv/videos/hentai/yuutousei-ayaka-no-uraomote-2
type: hanime
single: True
url: https://hanime.tv/videos/hentai/yuutousei-ayaka-no-uraomote-2
dir: hitomi_downloaded_hanime
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1730812102.951915 (24-11-05 13:08:22 UTC) - 8s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: True
changed: True

[File Names]
[0001] hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4

[URLs]
[0001] M3u8_stream(https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8)

[Messages]
['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
['m3u8', 480, 52, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/bdvwm8np0b6489drj4yttczyl2ZlAf995rp0lpf77jdptp80vAwpq.m3u8']
['m3u8', 360, 39, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/28zqj86wb966vsApmAcpvqbmq7Zds86jklnn563tjAh2dhd2stg93.m3u8']
Final stream:
['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
media: 0
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 510, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\C:\\Users\\secre\\OneDrive\\바탕 화면\\hitomi_downloader_GUI (2)\\hitomi_downloaded_hanime\\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4'

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

stop
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2034, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
EOT: https://hanime.tv/videos/hentai/yuutousei-ayaka-no-uraomote-2  (4.6s)

['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
['m3u8', 480, 52, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/bdvwm8np0b6489drj4yttczyl2ZlAf995rp0lpf77jdptp80vAwpq.m3u8']
['m3u8', 360, 39, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/28zqj86wb966vsApmAcpvqbmq7Zds86jklnn563tjAh2dhd2stg93.m3u8']
Final stream:
['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
media: 0
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 510, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\C:\\Users\\secre\\OneDrive\\바탕 화면\\hitomi_downloader_GUI (2)\\hitomi_downloaded_hanime\\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4'

stop
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2034, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
EOT: https://hanime.tv/videos/hentai/yuutousei-ayaka-no-uraomote-2  (5.4s)

['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
['m3u8', 480, 52, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/bdvwm8np0b6489drj4yttczyl2ZlAf995rp0lpf77jdptp80vAwpq.m3u8']
['m3u8', 360, 39, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/28zqj86wb966vsApmAcpvqbmq7Zds86jklnn563tjAh2dhd2stg93.m3u8']
Final stream:
['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
media: 0
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 510, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\C:\\Users\\secre\\OneDrive\\바탕 화면\\hitomi_downloader_GUI (2)\\hitomi_downloaded_hanime\\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4'

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

stop
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2034, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
EOT: https://hanime.tv/videos/hentai/yuutousei-ayaka-no-uraomote-2  (6.8s)

['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
['m3u8', 480, 52, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/bdvwm8np0b6489drj4yttczyl2ZlAf995rp0lpf77jdptp80vAwpq.m3u8']
['m3u8', 360, 39, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/28zqj86wb966vsApmAcpvqbmq7Zds86jklnn563tjAh2dhd2stg93.m3u8']
Final stream:
['m3u8', 720, 109, 'https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/5dvs3871d715hlmksdpwmw4d83Zgk4nggktslsbh1p5kh28cx3by7.m3u8']
media: 0
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-00.top/2/7/7/1/v1x/segs/b0/2/jvEMBnRhjiJ0FXqyXTIUWW16.html' for reading
Opening 'https://eureka-24b-01.top/2/7/7/1/v1x/segs/b0/2/wZN6VmN8E1x52XsEgjPDxmEX.html' for reading
Opening 'https://eureka-24b-02.top/2/7/7/1/v1x/segs/b0/2/skB5kU72GUDZTH63Mk1PkYbW.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Opening 'https://eureka-24b-19.top/2/7/7/1/v1x/segs/b0/2/bn8MWuJb3FA0T4V3A6kqVUuS.html' for reading
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Err: 0 / 0  (0.00%)
utime Error: \\?\C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 510, in run
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '\\\\?\\C:\\Users\\secre\\OneDrive\\바탕 화면\\hitomi_downloader_GUI (2)\\hitomi_downloaded_hanime\\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4'

stop
Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

Traceback (most recent call last):
 File "m3u8_tools", line 61, in run
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 424, in _read
 File "m3u8_tools", line 411, in _read
ValueError: not mpegts

{

}
[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4: No such file or directory
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2034, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

valid=False 2: C:\Users\secre\OneDrive\바탕 화면\hitomi_downloader_GUI (2)\hitomi_downloaded_hanime\[Mary Jane] Yuutousei Ayaka no Uraomote 2 (2771).mp4
EOT: https://hanime.tv/videos/hentai/yuutousei-ayaka-no-uraomote-2  (5.9s)

**Comment by wooeorbs** [comment]
구버전으로 다운받으세요
며칠전에 구버전은 되고 신버전은 안된다고 건의드렸는데 바쁘신지 응답이 없으십니다
