### ISSUE TITLE
sooptv 녹화문제

### ISSUE THREAD

**Issue by kmaaw** [KurtBestor/Hitomi-Downloader#7620]
녹화 중간에 멈춰지길래 다시 다운받으려고 하니까 녹화가 안됩니다
Invalid: [afreeca] https://play.sooplive.co.kr/hiyoko040

version: 4.2+ (24-11-02 04:46:37 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / d7daf73cb2d54d90a0ce3617280d6225
input: https://play.sooplive.co.kr/hiyoko040
type: afreeca
single: True
url: https://play.sooplive.co.kr/hiyoko040
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1731075366.5050447 (24-11-08 14:16:06 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
url_thumb: https://liveimg.sooplive.co.kr/m/278517188?138
result: 1
urls_m3u8: 1
400 Client Error: Bad Request for url: https://pc-web.stream.sooplive.co.kr/live-stm-16/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.crI8d-9YpS4K6yo1m3a4cmdsgaV5E33GUfj88E4XJKAyPSv0lvVkqGNnX-N5094Jgdutls3kf2dxnGn_48at7jvwrjivBQYNtO-20LPCZiA,
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\afreeca_downloader", line 36, in read
 File "utils", line 4883, in ready
 File "extractor\afreeca_downloader", line 157, in get
 File "m3u8_tools", line 549, in playlist2stream
 File "m3u8_tools", line 543, in playlist2stream
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 157, in __init__
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://pc-web.stream.sooplive.co.kr/live-stm-16/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.crI8d-9YpS4K6yo1m3a4cmdsgaV5E33GUfj88E4XJKAyPSv0lvVkqGNnX-N5094Jgdutls3kf2dxnGn_48at7jvwrjivBQYNtO-20LPCZiA,

Invalid: fail=True
EOT: https://play.sooplive.co.kr/hiyoko040  (1.4s)

**Comment by dinosera** [comment]
저 또한.. 두시간전부터 다운먹통..

**Comment by KurtBestor** [comment]
고쳤어요. 프로그램 다시 시작해주세요
