### ISSUE TITLE
SoopTv Live download error 갑자기 다운 안됨..

### ISSUE THREAD

**Issue by dinosera** [KurtBestor/Hitomi-Downloader#7621]
작업정보.
Invalid: [afreeca] https://play.sooplive.co.kr/wannabe33

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 9f734d7e683042a8b60707768e716eed
input: https://play.sooplive.co.kr/wannabe33
type: afreeca
single: True
url: https://play.sooplive.co.kr/wannabe33
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1731078412.1546478 (24-11-08 15:06:52 UTC) - 192s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
url_thumb: https://liveimg.sooplive.co.kr/m/278528634?221
result: 1
urls_m3u8: 1
400 Client Error: Bad Request for url: https://pc-web.stream.sooplive.co.kr/live-stm-16/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.3HC4hKik5Zf2liAmspuA23WOoVkRTEKl30gpNec_NcWBQqVXQFem5oU5b1OeAlN4zvELpKhEIZVZBUSiopNOadLP1k7KII7A3_0tIv3CM5o,
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\afreeca_downloader", line 36, in read
 File "utils", line 4883, in ready
 File "extractor\afreeca_downloader", line 157, in get
 File "m3u8_tools", line 549, in playlist2stream
 File "m3u8_tools", line 543, in playlist2stream
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 157, in __init__
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://pc-web.stream.sooplive.co.kr/live-stm-16/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.3HC4hKik5Zf2liAmspuA23WOoVkRTEKl30gpNec_NcWBQqVXQFem5oU5b1OeAlN4zvELpKhEIZVZBUSiopNOadLP1k7KII7A3_0tIv3CM5o,

Invalid: fail=True
EOT: https://play.sooplive.co.kr/wannabe33  (0.8s)

다운로드중 갑자기 멈춰서 그 뒤로 아무 방송국도 다운되지 않음

**Comment by naturefarver** [comment]
저도 지금 똑같은 오류 증상으로 녹화가 전혀 안되네요 불안정한 작업 오류 삭제 안했더니 지금 수백개의 작업 오류가 생겼습니다 그런데 치지직 트위치 유튜브는 정상적으로 녹화가 잘 되는거 봐서는 현재 숲TV 방송만 녹화가 전혀 안되고 있습니다
