### ISSUE TITLE
nhentai invalid

### ISSUE THREAD

**Issue by Brimlesss** [KurtBestor/Hitomi-Downloader#7628]
I am receiving the following error when trying to download from nhentai.net. This is happening on both the latest release and the technical preview. 

Invalid: [nhentai] https://nhentai.net/g/538066/

version: 4.1 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19044-SP0 / en_gb
order / group / uid: 3 / False / ed784c5e4f714c88b87a9f0e36503302
input: https://nhentai.net/g/538066/
type: nhentai
single: False
url: https://nhentai.net/g/538066/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1731176627.663453 (24-11-09 18:23:47 UTC) - 489s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1080
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'w'
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "extractor\nhentai_downloader", line 98, in get_info
KeyError: 'w'

Invalid: fail=True
quality: 75%
EOT: https://nhentai.net/g/538066/  (5.6s)

no html
'w'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\nhentai_downloader", line 98, in get_info
KeyError: 'w'

Invalid: fail=True
quality: 75%
EOT: https://nhentai.net/g/538066/  (7.8s)

'w'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\nhentai_downloader", line 98, in get_info
KeyError: 'w'

Invalid: fail=True
quality: 75%
EOT: https://nhentai.net/g/538066/  (5.9s)

'w'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\nhentai_downloader", line 98, in get_info
KeyError: 'w'

Invalid: fail=True
quality: 75%
EOT: https://nhentai.net/g/538066/  (4.9s)

'w'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\nhentai_downloader", line 98, in get_info
KeyError: 'w'

Invalid: fail=True
quality: 75%
EOT: https://nhentai.net/g/538066/  (4.7s)

500 Server Error: Internal Server Error for url: https://nhentai.net/g/538066/1/
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\nhentai_downloader", line 70, in get_info
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://nhentai.net/g/538066/1/

Invalid: fail=True
quality: 75%
EOT: https://nhentai.net/g/538066/  (5.8s)

**Comment by arteee87** [comment]
They have changed the image format to *.webp on the website
This seems to be the reason the download fails.

Invalid: [nhentai] https://nhentai.net/g/538612/

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ru_ru
order / group / uid: 0 / False / cd0711f8eb094e3fb1d20e38cc539e6e
input: https://nhentai.net/g/538612/
type: nhentai
single: False
url: https://nhentai.net/g/538612/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1731534151.9336126 (24-11-13 21:42:31 UTC) - 6s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'w'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\nhentai_downloader", line 36, in read
 File "extractor\nhentai_downloader", line 105, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\nhentai_downloader", line 98, in get_info
KeyError: 'w'

Invalid: fail=True
EOT: https://nhentai.net/g/538612/  (4.4s)

**Comment by Schlauchboot** [comment]
As a temporary fix, you can clone the source code and modify line 98 from the file "Hitomi-Downloader\src\extractor\nhentai_downloader.py" from:

`format = {'j':'jpg', 'p':'png', 'g':'gif'}[type]`

to

`format = {'j':'jpg', 'p':'png', 'g':'gif', 'w': 'webp'}[type]`

Save this file as a new python script. Afterwards, import the new file as a script ("Tools" -> "Import script..."). This should temporarily fix this issue, until a proper patch is released.
