### ISSUE TITLE
핀터레스트 보드 다운로드가 안돼요

### ISSUE THREAD

**Issue by tjdbs020108** [KurtBestor/Hitomi-Downloader#7690]
분명 됐는데 갑자기 안되네요....?
트위터 미디어나 유튜브같은건 멀쩡히 되는데 핀터레스트가 안됩니다.
새로 깔아도 보고 쿠키도 새로 다운받아 넣어봤는데도 이러네요..

작업정도는 대략 이렇게 나옵니다 ↓

Invalid: [pinter] https://kr.pinterest.com/seoyun020108/ch182/

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 62d40d0cf01c4d21a615facc0c0e299c
input: https://kr.pinterest.com/seoyun020108/ch182/
type: pinter
single: False
url: https://kr.pinterest.com/seoyun020108/ch182/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1732384757.2935839 (24-11-23 17:59:17 UTC) - 1358s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
type: board
type: board
type: board
API request failed: 403
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\pinter_downloader", line 65, in read
 File "extractor\pinter_downloader", line 225, in get_imgs
 File "extractor\pinter_downloader", line 168, in _pagination
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "decorator", line 232, in fun
 File "utils", line 5084, in _wrapper
 File "extractor\pinter_downloader", line 164, in _call
Exception: API request failed: 403

Invalid: fail=True
EOT: https://kr.pinterest.com/seoyun020108/ch182/  (48.4s)

**Comment by prpetu** [comment]
저도 다운로드가 안되네요ㅜㅜ

**Comment by depth221** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/pull/7810
