### ISSUE TITLE
케모노 어제부터 오류뜨면서 아무것도 안되는데 서버문젠가요??

### ISSUE THREAD

**Issue by jkh0315** [KurtBestor/Hitomi-Downloader#7701]
Invalid: [kemono.party] https://kemono.su/patreon/user/91423284/post/116432597

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 1 / False / 84dd64e30b5d4805b19e55593fe4cbae
input: https://kemono.su/patreon/user/91423284/post/116432597
type: kemono.party
single: False
url: https://kemono.su/patreon/user/91423284/post/116432597
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1732698740.1472054 (24-11-27 09:12:20 UTC) - 6833s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su (2)", line 20, in read
 File "Kemono.Su (2)", line 59, in read_post
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://kemono.su/patreon/user/91423284/post/116432597  (0.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su (2)", line 20, in read
 File "Kemono.Su (2)", line 59, in read_post
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://kemono.su/patreon/user/91423284/post/116432597  (0.7s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su (2)", line 20, in read
 File "Kemono.Su (2)", line 59, in read_post
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://kemono.su/patreon/user/91423284/post/116432597  (0.9s)

이렇게 뜹니다

**Comment by korhentai** [comment]
coomer.su
도 같이 안되는거보니 홈페이지 소스가 바뀐걸수도 있겠네요

**Comment by BewuwuBew** [comment]
안 된 지 3~4주 정도 되었습니다 ㅠㅠ... 스크립트 수정해주시길 바랄 수 밖에...

**Comment by fade-out-0770** [comment]
저도 며칠 안됐는데 오늘 해보니 되네요. 별개로 자바스크립트 쓰던 게 있었는데 그것도 안되던 거 보니 지금 사이트 자체에서 뭔가 바꾸는 중인듯. 스크립트 자체는 돌아가긴 합니다.

**Comment by fade-out-0770** [comment]
> > 저도 며칠 안됐는데 오늘 해보니 되네요. 별개로 자바스크립트 쓰던 게 있었는데 그것도 안되던 거 보니 지금 사이트 자체에서 뭔가 바꾸는 중인듯. 스크립트 자체는 돌아가긴 합니다.
> 
> 앵? 진짜요 ? Invalid [coomer.su] / [kemono.su] url 이라는데요 ?

https://github.com/rickmiron/variado 혹시 여기 있는건 어떠세요 다른 분이 스크립트 모아놓은건데 coomer는 안써봤고 다른거 몇개는 써봤는데 잘되더라구요

**Comment by jkh0315** [comment]
> > > 저도 며칠 안됐는데 오늘 해보니 되네요. 별개로 자바스크립트 쓰던 게 있었는데 그것도 안되던 거 보니 지금 사이트 자체에서 뭔가 바꾸는 중인듯. 스크립트 자체는 돌아가긴 합니다.
> > 
> > 
> > 앵? 진짜요 ? Invalid [coomer.su] / [kemono.su] url 이라는데요 ?
> 
> https://github.com/rickmiron/variado 혹시 여기 있는건 어떠세요 다른 분이 스크립트 모아놓은건데 coomer는 안써봤고 다른거 몇개는 써봤는데 잘되더라구요

저도 저거 쓰는데 안됩니다 ㅜㅜ

**Comment by hangugin1651** [comment]
> > > 저도 며칠 안됐는데 오늘 해보니 되네요. 별개로 자바스크립트 쓰던 게 있었는데 그것도 안되던 거 보니 지금 사이트 자체에서 뭔가 바꾸는 중인듯. 스크립트 자체는 돌아가긴 합니다.
> > 
> > 
> > 앵? 진짜요 ? Invalid [coomer.su] / [kemono.su] url 이라는데요 ?
> 
> https://github.com/rickmiron/variado 혹시 여기 있는건 어떠세요 다른 분이 스크립트 모아놓은건데 coomer는 안써봤고 다른거 몇개는 써봤는데 잘되더라구요

혹시 저 스크립트 쓰시는데 동작하시나요? 저도 저 스크립트 사용 중이고 수정을 해보려고 했는데 스크립트 자체 오류보다는 사이트 보안 방식 같은게 바뀌면서 접속이 차단되는 것 같더라구요
