### ISSUE TITLE
유튜브 일부가 다운로드가 안됩니다.(아래테스트버전도 해봄)

### ISSUE THREAD

**Issue by good1hub2** [KurtBestor/Hitomi-Downloader#7706]
Login required; Please login: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.
https://www.youtube.com/watch?v=3f3DJhFcK5k

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 2cf7d77805974ca5a0cdfdc8eb87185f
input: https://www.youtube.com/watch?v=3f3DJhFcK5k
type: youtube
single: True
url: https://www.youtube.com/watch?v=3f3DJhFcK5k
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1732871449.361504 (24-11-29 09:10:49 UTC) - 105s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA856A91F0>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts)
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
[ytdl] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[ytdl] No video formats found!
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
[ytdl] Requested format is not available
live: not_live
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA851DFCD0>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1625, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1760, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\youtube", line 4671, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 1275, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 649, in __init__
 File "ytdl", line 512, in extract_info
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1614, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1643, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 432, in report_error
 File "ytdl", line 428, in login_required
errors.LoginRequired: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA8E8B9460>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
[ytdl] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[ytdl] No video formats found!
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
[ytdl] Requested format is not available
live: not_live
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA85AB35E0>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1625, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1760, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\youtube", line 4671, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 1275, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 649, in __init__
 File "ytdl", line 512, in extract_info
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1614, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1643, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 432, in report_error
 File "ytdl", line 428, in login_required
errors.LoginRequired: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA8E27ACD0>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
[ytdl] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[ytdl] No video formats found!
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
[ytdl] Requested format is not available
live: not_live
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA85A7C370>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1625, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1760, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\youtube", line 4671, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 1275, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 649, in __init__
 File "ytdl", line 512, in extract_info
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1614, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1643, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 432, in report_error
 File "ytdl", line 428, in login_required
errors.LoginRequired: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA85A34790>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
[ytdl] [youtube] Sign in to confirm your age. This video may be inappropriate for some users.
[ytdl] No video formats found!
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
[ytdl] Requested format is not available
live: not_live
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe) API
[ytdl] [debug] params: {'verbose': True, 'logger': <ytdl.Logger object at 0x000002DA85E12D90>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.3', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1839 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=3f3DJhFcK5k
[ytdl] [youtube] 3f3DJhFcK5k: Downloading webpage
[ytdl] [youtube] 3f3DJhFcK5k: Downloading ios player API JSON
[ytdl] [youtube] 3f3DJhFcK5k: Downloading mweb player API JSON
### youtube retry...
Traceback (most recent call last):
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1625, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1760, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\youtube", line 4671, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 1275, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 649, in __init__
 File "ytdl", line 512, in extract_info
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1614, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1643, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 432, in report_error
 File "ytdl", line 428, in login_required
errors.LoginRequired: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

Traceback (most recent call last):
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1625, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1760, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\youtube", line 4671, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 1275, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 512, in read
 File "utils", line 4883, in ready
 File "extractor\youtube_downloader", line 75, in get
 File "extractor\youtube_downloader", line 54, in yt
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 649, in __init__
 File "ytdl", line 512, in extract_info
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1614, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1643, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 432, in report_error
 File "ytdl", line 428, in login_required
errors.LoginRequired: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

[youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.
stop
Traceback (most recent call last):
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1625, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1760, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 741, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\youtube", line 4671, in _real_extract
   self.raise_no_formats(reason, expected=True)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\extractor\common", line 1275, in raise_no_formats
   raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\youtube_downloader", line 519, in read
 File "extractor\youtube_downloader", line 512, in read
 File "utils", line 4883, in ready
 File "extractor\youtube_downloader", line 75, in get
 File "extractor\youtube_downloader", line 54, in yt
 File "extractor\youtube_downloader", line 44, in yt
 File "ytdl", line 649, in __init__
 File "ytdl", line 512, in extract_info
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1614, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\user\AppData\Local\Temp\_MEI46722\ytdl_0ddeb7a0\yt_dlp\yt_dlp\YoutubeDL", line 1643, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 432, in report_error
 File "ytdl", line 428, in login_required
errors.LoginRequired: [youtube] 3f3DJhFcK5k: Sign in to confirm your age. This video may be inappropriate for some users.

Invalid: fail=False
EOT: https://www.youtube.com/watch?v=3f3DJhFcK5k  (25.2s)

**Comment by good1hub2** [comment]
> 유튜브 연령제한 때문인거 같은데 다운로더 브라우저에서 유튜브 로그인 하거나 쿠키 파일 불러오시면 될거같아요

둘다 해봐도 안되던데
