### ISSUE TITLE
카카오 페이지 작품 다운로드 가 안됩니다

### ISSUE THREAD

**Issue by codemonkey4578** [KurtBestor/Hitomi-Downloader#7723]
신작이 아니라 한참전에 완결된 구작입니다.
링크
https://page.kakao.com/content/49781597

화선택시 오류
![오류1](https://github.com/user-attachments/assets/47155cbe-e547-475f-b456-0a2c529e9f6a)

전체 다운로드시 오류

Invalid: [kakaopage] https://page.kakao.com/content/49781597

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / ccd8ef64665c4526b34449cb01e790c6
input: https://page.kakao.com/content/49781597
type: kakaopage
single: False
url: https://page.kakao.com/content/49781597
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1733401376.2563663 (24-12-05 12:22:56 UTC) - 35s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "requests\models", line 971, in json
 File "json\__init__", line 357, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\kakaopage_downloader", line 58, in read
 File "extractor\kakaopage_downloader", line 621, in get_info
 File "extractor\kakaopage_downloader", line 217, in get_pages
 File "requests\models", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
quality: 100%
EOT: https://page.kakao.com/content/49781597  (7.6s)

**Comment by Sky19547** [comment]
3시간 무료, 1일 무료, 전부다
전체 다운로드 오류 

[김순태, 낭선] 낭선기환담

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 3 / False / 8024108911a14cc3874f5d5a3afbb8ba
input: https://page.kakao.com/content/56952321
type: kakaopage
single: False
url: https://page.kakao.com/content/56952321
dir: hitomi_downloaded_kakaopage\[김순태, 낭선] 낭선기환담
zip: 
artist: 김순태, 낭선
valid / done: False / True
range / range_p: None / None
time: 1733300348.3259287 (24-12-04 08:19:08 UTC) - 176070s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True


[File Names]


[URLs]



[Messages]
Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "requests\models", line 971, in json
 File "json\__init__", line 357, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\kakaopage_downloader", line 58, in read
 File "extractor\kakaopage_downloader", line 621, in get_info
 File "extractor\kakaopage_downloader", line 217, in get_pages
 File "requests\models", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/content/56952321  (8.4s)

Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "requests\models", line 971, in json
 File "json\__init__", line 357, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\kakaopage_downloader", line 58, in read
 File "extractor\kakaopage_downloader", line 621, in get_info
 File "extractor\kakaopage_downloader", line 217, in get_pages
 File "requests\models", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/content/56952321  (11.2s)

Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "requests\models", line 971, in json
 File "json\__init__", line 357, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\kakaopage_downloader", line 58, in read
 File "extractor\kakaopage_downloader", line 621, in get_info
 File "extractor\kakaopage_downloader", line 217, in get_pages
 File "requests\models", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/content/56952321  (9.0s)

Expecting value: line 1 column 1 (char 0)
stop
Traceback (most recent call last):
 File "requests\models", line 971, in json
 File "json\__init__", line 357, in loads
 File "json\decoder", line 337, in decode
 File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\kakaopage_downloader", line 58, in read
 File "extractor\kakaopage_downloader", line 621, in get_info
 File "extractor\kakaopage_downloader", line 217, in get_pages
 File "requests\models", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Invalid: fail=True
invalid; revert
EOT: https://page.kakao.com/content/56952321  (9.1s)

작업 정보 입니다

**Comment by smims210** [comment]
카카오페이지에서 뭔가 바꾼듯 한데. 제작자님의 업데이트 필요한것 같습니다 ㅠㅠ
