### ISSUE TITLE
아직도 케모노 안되는거죠?

### ISSUE THREAD

**Issue by jkh0315** [KurtBestor/Hitomi-Downloader#7734]
Invalid: [kemono.party] https://kemono.su/patreon/user/55237716

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / 5dbc8d6c49964522a83e15267152bbcd
input: https://kemono.su/patreon/user/55237716
type: kemono.party
single: False
url: https://kemono.su/patreon/user/55237716
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1733639214.5441391 (24-12-08 06:26:54 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://kemono.su/patreon/user/55237716  (0.0s)

stop
Invalid: fail=False
EOT: https://kemono.su/patreon/user/55237716  (0.0s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su (4)", line 24, in read
 File "Kemono.Su (4)", line 30, in read_user
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://kemono.su/patreon/user/55237716  (0.7s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su (4)", line 24, in read
 File "Kemono.Su (4)", line 30, in read_user
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://kemono.su/patreon/user/55237716  (0.7s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su (4)", line 24, in read
 File "Kemono.Su (4)", line 30, in read_user
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://kemono.su/patreon/user/55237716  (0.7s)

dpi 우회 스크립트 재추가 별짓을 다해봐도 안되네요...

**Comment by hangugin1651** [comment]
저도 지금 같은 문제 겪고 있는데 혹시 kemonosu_downloader Qualiazero 스크립트 사용 중이신가요?

**Comment by jkh0315** [comment]
> 저도 지금 같은 문제 겪고 있는데 혹시 kemonosu_downloader Qualiazero 스크립트 사용 중이신가요?

넵 그렇습니다

**Comment by hangugin1651** [comment]
크롤링에 아주 얕은 지식이 있어서 스크립트를 직접 수정해보려고 했는데 처음에는 rid_user나 rid_post에서 문자열들을 제대로 못 긁어와서 "NoneType"이 되는 줄 알고 이것저것 수정을 해봤는데 여전히 오류가 발생하는 것을 보니 지금 사이트 자체를 못 읽는 것 같더라구요
저는 저 스크립트에서 오류가 발생하는 부분 중 하나인
titu=clean_title(soup.find('meta',{'name':'artist_name'})['content'])부분에서 'meta'라는 부분을 사이트에서 가리거나 바꿨는 줄 알았는데 그것도 아니라서 지금 원인을 잘 모르겠네요...
일부분이 제대로 동작하는지 print를 통해서 확인해보면서 수정하고 싶은데 히토미 다운로더는 오류만 log로 확인이 가능해서 혹시 동작 log도 확인할 수 있는 방법이 있는지 알고 싶네요

일단은 케모노 자체에서 사이트 리뉴얼하면서 해당 사이트 자체를 제대로 읽어오지 못하는 것 같아요

**Comment by hangugin1651** [comment]
kemonosu_downloader Qualiazero 스크립트 문제인 줄 알았는데 제가 간과한게 read_user라는 함수는 kemonosu_downloader Qualiazero 스크립트가 아니라 kemonoparty.hds에 있는 함수더군요
이거 위주로 확인 해봐야겠네요

**Comment by hangugin1651** [comment]
> kemonosu_downloader Qualiazero 스크립트 문제인 줄 알았는데 제가 간과한게 read_user라는 함수는 kemonosu_downloader Qualiazero 스크립트가 아니라 kemonoparty.hds에 있는 함수더군요 이거 위주로 확인 해봐야겠네요

아는 선에서는 해봤는데 지식이 얕아서 못 고치겠네요...
처음에 Nonetype이라길래 케모노 사이트에서 파일이나 사이트 elements 형식을 좀 바꾼 줄 알았는데 그게 아니라 사이트 자체를 인식을 못하는 것 같아요
조금 찾아봤는데 cloudflare 보안방식 때문에 우회를 해야할 수도 있다고 하는데 이게 원인인지는 모르겠네요
