### ISSUE TITLE
툰코 스크립트 작동이 안됩니다

### ISSUE THREAD

**Issue by williams2222** [KurtBestor/Hitomi-Downloader#7737]
Invalid: [toonkor] https://toonkor462.com/%EB%A7%88%EB%85%80%EC%99%80-%EC%95%BC%EC%88%98

version: 4.2+ (24-11-02 04:46:37 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 1476d2a13e134d388dffe9494ffc8a33
input: https://toonkor462.com/%EB%A7%88%EB%85%80%EC%99%80-%EC%95%BC%EC%88%98
type: toonkor
single: False
url: https://toonkor462.com/%EB%A7%88%EB%85%80%EC%99%80-%EC%95%BC%EC%88%98
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1733745758.9151366 (24-12-09 12:02:38 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1440
goodbyedpi: True
ytdl: yt_dlp 2024.12.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
403 Client Error: Forbidden for url: https://toonkor462.com/%EB%A7%88%EB%85%80%EC%99%80-%EC%95%BC%EC%88%98
stop
Traceback (most recent call last):
 File "downloader", line 438, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1387, in start
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "toonkor 사이트 추가 (3)", line 42, in init
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://toonkor462.com/%EB%A7%88%EB%85%80%EC%99%80-%EC%95%BC%EC%88%98

Invalid: fail=True
EOT: https://toonkor462.com/%EB%A7%88%EB%85%80%EC%99%80-%EC%95%BC%EC%88%98  (1.4s)

스크립트 수정해서 잘 쓰고 있었는데 오늘 급 안되네요
뭐가 문제인지 봐주시면 감사합니다

**Comment by inki123** [comment]
몇일전 접속할때 보안체크뜨는거봐선 접속방법을 바꾼거같습니다 저도 똑같이 다운로드가 안되는 현상입니다
