### ISSUE TITLE
유튜브 영상 다운 실패

### ISSUE THREAD

**Issue by Asylum0** [KurtBestor/Hitomi-Downloader#7745]
실시간 방송 영상이라 다운 가능하게 될 때 까지 시간이 걸리는걸까 했는데
빨간색으로 아얘 다운 불가 표시가 떴습니다.
유튜브가 아얘 안되는건가 했는데 다운이 되는 영상도 있네요.
preview버전 사용 중입니다.

version: 4.2+ (24-12-13 11:59:12 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: -4514 / False / 3e6a81ef779341be92b2b2f3445f9413
input: https://www.youtube.com/watch?v=d4l17lJKhDE
type: youtube
single: True
url: https://www.youtube.com/watch?v=d4l17lJKhDE
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1734093768.0710351 (24-12-13 12:42:48 UTC) - 30s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 2, 'overwrite': True, 'mode': 'query'}
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.12.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[ytdl] Deprecated Feature: Python version 3.8 is no longer supported! Please update to Python 3.9 or above
[ytdl] Deprecated Feature: Python version 3.8 is no longer supported! Please update to Python 3.9 or above
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x0000014D2FF6DD90>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.1', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4556.0 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1837 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=d4l17lJKhDE
[ytdl] [youtube] d4l17lJKhDE: Downloading webpage
[ytdl] [debug] [youtube] Extracted SAPISID cookie
[ytdl] [youtube] d4l17lJKhDE: Downloading web creator player API JSON
[ytdl] [youtube] d4l17lJKhDE: Downloading mweb player API JSON
[ytdl] [debug] [youtube] Extracting signature function js_2f1832d2_112
[ytdl] [youtube] d4l17lJKhDE: Downloading player 2f1832d2
[ytdl] [youtube] d4l17lJKhDE: Signature extraction failed: Some formats may be missing
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Extracting signature function js_2f1832d2_108
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] Only images are available for download. use --list-formats to see them
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
[ytdl] Requested format is not available
live: was_live
[27p][0.032133676092544985fps][None][None] mhtml [None / None] ─ sb3 - 48x27 (storyboard)
[45p][0.1005784061696658fps][None][None] mhtml [None / None] ─ sb2 - 80x45 (storyboard)
[90p][0.1005784061696658fps][None][None] mhtml [None / None] ─ sb1 - 160x90 (storyboard)
[180p][0.1005784061696658fps][None][None] mhtml [None / None] ─ sb0 - 320x180 (storyboard)

utime: 1734048000.0

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 512, in read
 File "utils", line 4883, in ready
 File "extractor\youtube_downloader", line 188, in get
Exception: No videos

No videos
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\youtube_downloader", line 519, in read
 File "extractor\youtube_downloader", line 512, in read
 File "utils", line 4883, in ready
 File "extractor\youtube_downloader", line 188, in get
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=d4l17lJKhDE  (3.4s)

**Comment by Asylum0** [comment]
5분 단위로 재시도하게 두고 그냥 놔둬봤더니 약 1시간만에 다운 성공했습니다.
1시간동안 무엇이 변했는지는 알 수 없군요.
개발자님 혹시 보시고 프로그램의 문제가 아니라고 판단되시면 close 해주셔도 될 것 같습니다.
실례했습니다...

**Comment by instaisntdownsoicome** [comment]
저도 요 2주간
재생목록 중자꾸 일부가 실패되거나
개별단위영상이 invaild 뜨든가
360으로 다운되든가
아주 자주 오류가 발생해서
시간 엄청 날렷는데


쿠키문제가 아닐까 싶음
쿠키 설정에 문제가 있음
이 문제를 해결해보세오
그문제가 이닐수도 잇지만

**Comment by lducjswo** [comment]
저도 같은 증상으로 고생중입니다
모두 다 안되면 모르겠는데 특별히 공통점도 없는 채널의 몇몇 영상들만 다운이 안되고 있어요

**Comment by instaisntdownsoicome** [comment]
> 저도 같은 증상으로 고생중입니다 모두 다 안되면 모르겠는데 특별히 공통점도 없는 채널의 몇몇 영상들만 다운이 안되고 있어요

아주 2024는 유튜브 인스타 포함해서 등등 여러앱 프로그램에서
Ai발전이 진짜 엿같아요
어떻게든 틀어막고 때려패고 정말 고통스러웟음
뭐만 하면 안되는게 자꾸 생기니까..


유튜브 프리미엄으로 다음재생목록으로 추가해서
300-1000개 영상을 재생목록화해서
다운 받는 영상들이 지금 문제가 많아서 아주 스트레스입니다

예를들어 100개영상 재생목록 다운누르몬
한 36개 다운받다가 완료됫다고 뜸

한 200개 재생목록 다운하면.
뭐 한 50개 다운하다가 완료됫다고 뜸


거의 대부분 재생목록들이  빈깡통처럼 다 완료가 안됨
그럼 다운이 안된 영상을 색출해서
개별영상 주소를 입력하면 invaild뜸



재생목록화 하는것은 옥석가리기로
각종 채널에서 원하는 것만 추려낸 것인데
어떤 채널애 있는 영상들은 전부다 되는데
어떤 채널에 일는 영상들은 다 안됨
어떤 채널애 있는 영상들은 일부만 됨


파이썬으로 주소 목록을 전부다 추출해내서
엑셀화하여 히토미에 주소목록을 일괄 다운할때는
또 다운로드가 다 됨(이건 그냥 되는 채널들만 모엿던걸수도 잇음)

애초에 지금 이 모든것이 쿠키 설정 문제인것으로 보임
지난주까지는 일부파일들이 자꾸 360으로 다운되길래
서드쿠키를 자꾸 삭제해주면서 새로 넣어주니
몇번 안되다가 결국에는 다 다운이 됫는데


어제부터 갑자기 쿠키를 이렇게 갈든 저렇게 갈든
다운이 안되는 애들은 계속 다운이 안됨
어제까지만 해도 하루애 쿠키를 한 20번은 갈앗는데
쿠키를 50번 더갈앗는데 오늘은 그냥 안되는건 계솓안됨
구글 아디도 계속 바꿔도 안됨
이게 인터넷 공유기로 다운을 시도하는 pc 태블릿이 전부다 안됨


그러나 다운이 안되는 영상을 색출해서
휴대폰 lte로 레드티2에서 다운하니 이건 또 됨
다운을 수십 수백번시도한 이 인터넷이 스팸같이 인식된듯
이 와이파이만 벗어나면 다운이 됨


인스타도 요청대기니 스팸이니 프래그니
ㅈㄹㅈㄹ해서 날려먹은 시간이 아주 빡치는데
Ai발전이 아주 엿같이 사람을 피곤하게 만드는듯

**Comment by DBdeepsleeper** [comment]
내장 브라우저 유튜브 로그인이 되어 있다면 로그아웃 해보세요.
이전에 문제가 있었다가 수정이 됐었는데 오늘 또 6갠가 다운이 안 돼서 로그아웃해 보니까 다운이 됐거든요.

내장 브라우저 실행 방법 댓글 이미지 참조
https://github.com/KurtBestor/Hitomi-Downloader/issues/7725#issuecomment-2521692959

**Comment by instaisntdownsoicome** [comment]
> 내장 브라우저 유튜브 로그인이 되어 있다면 로그아웃 해보세요. 이전에 문제가 있었다가 수정이 됐었는데 오늘 또 6갠가 다운이 안 돼서 로그아웃해 보니까 다운이 됐거든요.
> 
> 내장 브라우저 실행 방법 댓글 이미지 참조 [#7725 (comment)](https://github.com/KurtBestor/Hitomi-Downloader/issues/7725#issuecomment-2521692959)

쿠키 초기화하고
웹브라우저로 로그인해야
오히려 지난 1주일동안
다운안되는거 없이 잘됫음
쿠키를 갈아서 넣든
초기화하고 웹브라우저로 로그인해야
다운이 잘됫음

오늘 혹시나 해서 웹브라우저 로그아웃하고
쿠키만 넣엇더니 invaild뜸
그래서 쿠키초기화하고
웹브라우저로그인하니
바로 다운되긴햇디만
Invaild 뜸


인터넷이.낙인 찍힌듯
이 와이파이로는 태블릿에서
레드티 접근조차 안됨

**Comment by KurtBestor** [comment]
고쳤어요

**Comment by instaisntdownsoicome** [comment]
와 이럴줄 알앗으먼 그냥 기다릴걸
어제 22시 - 01시까지 이것저것 다 손대보다가
인터넷까지 터져서 멘탈나갓다가 겨우 수습하고 잣는데
어제 3시간 개뻘짓이엇네
심지어 그시간대에 고쳐지고 잇엇어

어재 머리너무아파서 게보린까지 먹고 잣는데
고쳐졋어요 말이 매우 비현실적으로 들린다
생각보다 빨리 고쳐졋내요


이럴줄알앗으면 그냥 맘편히 
딴거하다 기다릴걸


그나저나 이것도 인스타와같이
하나씩만 다운되는것 같네요
하지만 일단 전수다운되니 괜찮습니다

유튜브 다운 끝물이엇는데
말썽이어서 아주 머리가 아팟는데
꼭 얼마안남낫을때
하자가 생기면
기가차는데...

**Comment by instaisntdownsoicome** [comment]
개별영상은 다운되는데
재생목록이 링크 붙이면
계속 로딩중입니다

**Comment by instaisntdownsoicome** [comment]
여전히 일부 재생목록들은
다운되다가 멈추는.현상이 있습니다
26/78에서 멈춤
쿠키 초기화하고 쿠키 옵션 삭제후 새 쿠키 다운받고 투입
다시 되다가 58/78에서 멈춤
다시 쿠키 작업

지난주는 쿠키 갈아넣어도 진척이 없는경우가 잇엇으나
그건 개선된듯하나 이것또한 앞으로 어떻개 변할지모름
Ai발전이 참 이용자들을 두들겨패네요

**Comment by deneventure** [comment]
안녕하세용 이거 고쳐진거 쓰려면 Priview 버전으로 다운받아야 하나용?

**Comment by instaisntdownsoicome** [comment]
> 안녕하세용 이거 고쳐진거 쓰려면 Priview 버전으로 다운받아야 하나용?

최근에 올라온것도 되는것같긴한데
저는 oct 27에 올라온 버전으로 쓰고 잇어요
현재까지는 누락되는거 거의없이 다다운되고잇어요

**Comment by deneventure** [comment]
윗분 말씀대로 중간에 쿠키 입력 혹은 로그인 하라고 하면서 멈추내요 그럼 쿠키 다시 생성해서 넣으면 됩니다 불편 ㅠㅠ
