### ISSUE TITLE
핀터레스트 안되네요 고쳐주세용

### ISSUE THREAD

**Issue by ahrigatohaha** [KurtBestor/Hitomi-Downloader#7747]
![image](https://github.com/user-attachments/assets/13bdc0e3-2ece-4cb3-bfcc-568e5f5a31e5)

3분 43초 뒤 다시 시작: Invalid: [pinter] https://kr.pinterest.com/dddddsd3/2021-6/

version: 4.1 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / en_us
order / group / uid: 1 / False / 3d4e717da53e43b8bcb765cdfbce6396
input: https://kr.pinterest.com/dddddsd3/2021-6/
type: pinter
single: False
url: https://kr.pinterest.com/dddddsd3/2021-6/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1734174649.201592 (24-12-14 11:10:49 UTC) - 109s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 1080
goodbyedpi: None
ytdl: yt_dlp 2024.12.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
type: board
API request failed: 403
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\pinter_downloader", line 65, in read
 File "extractor\pinter_downloader", line 225, in get_imgs
 File "extractor\pinter_downloader", line 168, in _pagination
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "decorator", line 232, in fun
 File "utils", line 5084, in _wrapper
 File "extractor\pinter_downloader", line 164, in _call
Exception: API request failed: 403

Invalid: fail=True
EOT: https://kr.pinterest.com/dddddsd3/2021-6/  (28.3s)

type: board
API request failed: 403
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\pinter_downloader", line 65, in read
 File "extractor\pinter_downloader", line 225, in get_imgs
 File "extractor\pinter_downloader", line 168, in _pagination
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "decorator", line 232, in fun
 File "utils", line 5084, in _wrapper
 File "extractor\pinter_downloader", line 164, in _call
Exception: API request failed: 403

Invalid: fail=True
EOT: https://kr.pinterest.com/dddddsd3/2021-6/  (32.3s)

**Comment by depth221** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/pull/7810
일단 코드 수정 요청을 올리긴 했는데요, 급하시다면 [이 코드](https://github.com/KurtBestor/Hitomi-Downloader/blob/bcf257d7818797d443993b93aaa7237780931efe/src/extractor/pinter_downloader.py)를 python 파일로 저장하신 후 `Alt+S`로 불러오시면 정상적으로 다운로드됩니다.
