### ISSUE TITLE
av19 사이트가 갑자기 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by Mentalistcode** [KurtBestor/Hitomi-Downloader#7752]
Invalid: [av19] https://avav19.com/korea/67001

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / e0edcf53f4c9427f915ac9395b6e82a8
input: https://avav19.com/korea/67001
type: av19
single: True
url: https://avav19.com/korea/67001
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1734334041.3167214 (24-12-16 07:27:21 UTC) - 92s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.12.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "AV19", line 29, in read
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 195, in __init__
 File "requests\sessions", line 602, in get
 File "utils", line 1001, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://avav19.com/korea/67001  (1.6s)

HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "AV19", line 29, in read
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 195, in __init__
 File "requests\sessions", line 602, in get
 File "utils", line 1001, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://avav19.com/korea/67001  (1.6s)

HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "AV19 (2)", line 29, in read
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 195, in __init__
 File "requests\sessions", line 602, in get
 File "utils", line 1001, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://avav19.com/korea/67001  (1.6s)

HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "AV19 (3)", line 29, in read
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 195, in __init__
 File "requests\sessions", line 602, in get
 File "utils", line 1001, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://avav19.com/korea/67001  (1.8s)

HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
stop
Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 125, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 125, in <lambda>
 File "downloader", line 101, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "AV19 (3)", line 29, in read
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "m3u8_tools", line 195, in __init__
 File "requests\sessions", line 602, in get
 File "utils", line 1001, in request
 File "downloader", line 256, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='y.mt-find.com', port=443): Max retries exceeded with url: /n6/vd2/448b52213a693446f56942ed2204d73b/image0.txt (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

Invalid: fail=True
EOT: https://avav19.com/korea/67001  (1.6s)

**Comment by slot-machine-777** [comment]
이거 해결 하셨나요? 어떻게 하는지 알려주시면 감사하겠습니다
