### ISSUE TITLE
ytdlt오류로 유튜브 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#7757]
Invalid: [youtube] https://www.youtube.com/watch?v=8EMrjq188nQ

version: 4.2+ (24-12-13 11:59:12 UTC)
platform / locale: Windows-10-10.0.26100-SP0 / en_us
order / group / uid: 13651 / False / 2888aa218bcb4ae18d423de5a3bec11f
input: https://www.youtube.com/watch?v=8EMrjq188nQ
type: youtube
single: True
url: https://www.youtube.com/watch?v=8EMrjq188nQ
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1734474088.4996045 (24-12-17 22:21:28 UTC) - 33s elapsed
tags: []
lock: False
color: invalid
paused: False
format: mp4
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: False
res: 4320
goodbyedpi: None
ytdl: yt_dlp 2024.12.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[ytdl] Deprecated Feature: Python version 3.8 is no longer supported! Please update to Python 3.9 or above
[ytdl] Deprecated Feature: Python version 3.8 is no longer supported! Please update to Python 3.9 or above
[ytdl] [debug] Encodings: locale cp949, fs utf-8, pref cp949, out UTF-8 (No VT), error UTF-8 (No VT), screen UTF-8 (No VT)
[ytdl] [debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (win_exe) API
[ytdl] [debug] params: {'ignore_no_formats_error': True, 'verbose': True, 'logger': <ytdl.Logger object at 0x000001B85030F7C0>, 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.1', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.19 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[ytdl] [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[ytdl] [debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[ytdl] [debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.35.5, urllib3-1.25.11, websockets-13.1
[ytdl] [debug] Proxy map: {}
[ytdl] [debug] Request Handlers: urllib, websockets
[ytdl] [debug] Loaded 1837 extractors
[ytdl] [youtube] Extracting URL: https://www.youtube.com/watch?v=8EMrjq188nQ
[ytdl] [youtube] 8EMrjq188nQ: Downloading webpage
[ytdl] [debug] [youtube] Extracted SAPISID cookie
[ytdl] [youtube] 8EMrjq188nQ: Downloading web creator player API JSON
[ytdl] [youtube] 8EMrjq188nQ: Downloading mweb player API JSON
[ytdl] [debug] [youtube] Extracting signature function js_03dbdfab_107
[ytdl] [youtube] 8EMrjq188nQ: Downloading player 03dbdfab
[ytdl] [youtube] 8EMrjq188nQ: Signature extraction failed: Some formats may be missing
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Extracting signature function js_03dbdfab_103
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] [debug] [youtube] Could not find JS function "j"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl] Only images are available for download. use --list-formats to see them
[ytdl] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[ytdl] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[ytdl] [debug] Default format spec: bestvideo*+bestaudio/best
[ytdl] Requested format is not available
live: not_live
[27p][0.02289901534234028fps][None][None] mhtml [None / None] ─ sb3 - 48x27 (storyboard)
[45p][0.10029768719945042fps][None][None] mhtml [None / None] ─ sb2 - 80x45 (storyboard)
[90p][0.10029768719945042fps][None][None] mhtml [None / None] ─ sb1 - 160x90 (storyboard)
[180p][0.10029768719945042fps][None][None] mhtml [None / None] ─ sb0 - 320x180 (storyboard)

utime: 1733961600.0

Traceback (most recent call last):
 File "extractor\youtube_downloader", line 512, in read
 File "utils", line 4883, in ready
 File "extractor\youtube_downloader", line 188, in get
Exception: No videos

No videos
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\youtube_downloader", line 519, in read
 File "extractor\youtube_downloader", line 512, in read
 File "utils", line 4883, in ready
 File "extractor\youtube_downloader", line 188, in get
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=8EMrjq188nQ  (3.6s)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/7745
