### ISSUE TITLE
단부루 다운로드가 안됩니다...(검색 및 최신 테스트 빌드 사용해봄)

### ISSUE THREAD

**Issue by iseul21** [KurtBestor/Hitomi-Downloader#7776]
뭐가 문제일까 싶어서 내장 브라우저 켠 상태로 다운로드 시도했는데,
처음 다운로드 시도하면서 읽는 중 나올때는 내장 브라우저에 제가 다운로드 하려는 태그가 적용된 단부루 창이 잘 뜨더니,
곧 about:blank 창으로 전환되면서 다운로드도 실패가 뜨더군요.

단부루 측에서 다운로더 시도가 있을 때 about:blank 창으로 전환되게 만들어서 다운로드를 못 받게 하고 있는 것 같습니다.

Invalid: [danbooru] https://danbooru.donmai.us/posts?tags=azur_lane+official_art

version: 4.2+ (24-12-13 11:59:12 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 3b5d461007a64b4f82e36bbcb1c0ee14
input: https://danbooru.donmai.us/posts?tags=azur_lane+official_art
type: danbooru
single: False
url: https://danbooru.donmai.us/posts?tags=azur_lane+official_art
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1734950767.6870568 (24-12-23 10:46:07 UTC) - 229s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.12.13+
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
https://danbooru.donmai.us/posts?tags=azur_lane+official_art&page=1
403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=azur_lane+official_art&page=1
stop
Traceback (most recent call last):
 File "downloader", line 420, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "extractor\danbooru_downloader", line 66, in read
 File "extractor\danbooru_downloader", line 153, in get_imgs
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\danbooru_downloader", line 124, in read_soup
 File "downloader", line 364, in read_soup
 File "downloader", line 466, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://danbooru.donmai.us/posts?tags=azur_lane+official_art&page=1

Invalid: fail=True
EOT: https://danbooru.donmai.us/posts?tags=azur_lane+official_art  (16.0s)

**Comment by Qualiazero** [comment]
same problem with you

**Comment by Centurion-Mk2** [comment]
Gelbooru는 잘 다운로드 되던데....
