### ISSUE TITLE
마나토끼 다운 실패 + 내장 웹 브라우저 안열림

### ISSUE THREAD

**Issue by YuushaAvan** [KurtBestor/Hitomi-Downloader#7789]
Invalid: [manatoki] https://manatoki466.net/comic/21516094

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 1611b5a600964c9a90654728ee9c31c2
input: https://manatoki466.net/comic/21516094
type: manatoki
single: False
url: https://manatoki466.net/comic/21516094
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1735459848.3920996 (24-12-29 08:10:48 UTC) - 645s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 2160
goodbyedpi: None
ytdl: yt_dlp 2024.12.13+
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1387, in start
 File "decorator", line 232, in fun
 File "constants", line 946, in try_
 File "constants", line 915, in try_
 File "extractor\manatoki_downloader", line 85, in init
 File "utils", line 666, in __get__
 File "extractor\manatoki_downloader", line 101, in name
 File "extractor\manatoki_downloader", line 119, in get_artist
 File "utils", line 2756, in find
utils.SoupNotFound: no title

Invalid: fail=True
quality: 100%
EOT: https://manatoki466.net/comic/21516094  (14.0s)
![h11h1h1h1h1h](https://github.com/user-attachments/assets/71ade440-6902-42d7-8562-871f0e5bc905)

**Comment by YuushaAvan** [comment]
보통 마나토끼 다운이 안되면 쿠키를 불러오거나
내장웹브라우저에서 한번 열고나면 다운이 됐는데
이제는 내장웹브라우저도 안열리네요 ㅜㅜ

**Comment by Orange6539** [comment]
![111](https://github.com/user-attachments/assets/7e681699-b373-4a02-b1e1-eee200f8ea1b)

저 링크 다운 시도해 보니 저는 잘 되네요
